local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0505",
  bg_darker = "#140a0a",
  bg_dark = "#1e0f0f",
  bg_mid = "#281414",
  bg_light = "#321919",
  bg_lighter = "#3c1e1e",
  bg_lightest = "#462323",
  bg_alt1 = "#502828",
  bg_alt2 = "#5a2d2d",
  bg_alt3 = "#643232",
  bg_alt4 = "#6e3737",
  fg_lightest = "#ff9090",
  fg_light = "#ff8080",
  fg_mid = "#ff7070",
  fg_dark = "#ff6060",
  boundWolf = "#783c3c",
  gleipnirChains = "#824141",
  tyrsHand = "#8c4646",
  ragnarokJaws = "#964b4b",
  odinsDoom = "#a05050",
  bloodOath = "#8b0000",
  brokenBonds = "#a01010",
  apocalypticRage = "#b52020",
  fenrisWrath = "#ca3030",
  worldEnder = "#df4040",
  devourer = "#f45050",
  finalHowl = "#ff6060",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.boundWolf,
      insert = plt.ragnarokJaws,
      visual = plt.apocalypticRage,
      replace = plt.bloodOath,
      command = plt.devourer,
    },
    accent = {
      accent1 = plt.boundWolf,
      accent2 = plt.ragnarokJaws,
      accent3 = plt.apocalypticRage,
      accent4 = plt.fg_light,
      accent5 = plt.bloodOath,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.boundWolf,
      rainbow2 = plt.gleipnirChains,
      rainbow3 = plt.tyrsHand,
      rainbow4 = plt.ragnarokJaws,
      rainbow5 = plt.apocalypticRage,
      rainbow6 = plt.worldEnder,
      rainbow7 = plt.devourer,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.apocalypticRage,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.boundWolf,
      header2 = plt.bloodOath,
      special = plt.devourer,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.ragnarokJaws,
      indent = plt.bg_light,
      indent_scope = plt.boundWolf,
      picker = plt.apocalypticRage,
      yank = plt.worldEnder,
      mark = plt.fenrisWrath,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.boundWolf,
        indicator = plt.bloodOath,
      },
    },
    syn = {
      attribute = plt.devourer,
      boolean = plt.worldEnder,
      comment = plt.fg_mid,
      constant = plt.apocalypticRage,
      deprecated = plt.fg_dark,
      func = plt.bloodOath,
      identifier = plt.fg_lightest,
      keyword = plt.worldEnder,
      method = plt.bloodOath,
      number = plt.apocalypticRage,
      operator = plt.ragnarokJaws,
      parameter = plt.fenrisWrath,
      preproc = plt.devourer,
      punct = plt.fg_mid,
      regex = plt.worldEnder,
      special = plt.devourer,
      special2 = plt.worldEnder,
      special3 = plt.fenrisWrath,
      statement = plt.worldEnder,
      string = plt.bloodOath,
      symbol = plt.ragnarokJaws,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.bloodOath,
      warning = plt.apocalypticRage,
      info = plt.boundWolf,
      ok = plt.gleipnirChains,
      hint = plt.devourer,
      virtual_text_error = plt.bloodOath,
      virtual_text_warning = plt.apocalypticRage,
      virtual_text_info = plt.boundWolf,
      virtual_text_ok = plt.gleipnirChains,
      virtual_text_hint = plt.devourer,
    },
    diff = {
      add = plt.gleipnirChains,
      add_inline = plt.ragnarokJaws,
      change = plt.apocalypticRage,
      change_inline = plt.worldEnder,
      delete = plt.bloodOath,
      delete_inline = plt.tyrsHand,
      text = plt.devourer,
    },
    vcs = {
      added = plt.gleipnirChains,
      changed = plt.apocalypticRage,
      removed = plt.bloodOath,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.bloodOath,
      green = plt.gleipnirChains,
      yellow = plt.devourer,
      blue = plt.boundWolf,
      magenta = plt.apocalypticRage,
      cyan = plt.ragnarokJaws,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.bloodOath):brighten(0.2):to_hex(),
      green_bright = color(plt.gleipnirChains):brighten(0.15):to_hex(),
      yellow_bright = color(plt.devourer):brighten(0.15):to_hex(),
      blue_bright = color(plt.boundWolf):brighten(0.15):to_hex(),
      magenta_bright = color(plt.apocalypticRage):brighten(0.2):to_hex(),
      cyan_bright = color(plt.ragnarokJaws):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.fenrisWrath,
      indexed2 = plt.worldEnder,
    },
  }
end

return {
  name = "Jötunheim – Fenrir",
  author = "PrismPunk",
  description = "Bound wolf — Gleipnir's prisoner, Tyr's hand, Odin's doom, apocalyptic jaws. "
    .. "Fenrir, mightiest of wolves and son of Loki, grew so powerful that the gods "
    .. "feared him. They bound him with Gleipnir, a magical ribbon forged from impossible "
    .. "things — the sound of a cat's footfall, the beard of a woman, the roots of a "
    .. "mountain. The binding cost Tyr his hand, placed in Fenrir's jaws as pledge of "
    .. "good faith and bitten off when the wolf realized the deception. Bound until "
    .. "Ragnarok, Fenrir will break free to devour Odin himself, his apocalyptic jaws "
    .. "wide enough to span from earth to sky. The palette moves from deep blood-red "
    .. "darkness to blazing crimson fury — the rage of eternal imprisonment, the "
    .. "breaking of unbreakable bonds, and the world-ending vengeance of the bound wolf "
    .. "finally freed.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.bloodOath,
    base09 = palette.apocalypticRage,
    base0A = palette.fenrisWrath,
    base0B = palette.gleipnirChains,
    base0C = palette.devourer,
    base0D = palette.boundWolf,
    base0E = palette.ragnarokJaws,
    base0F = palette.worldEnder,
  },
  palette = palette,
  get = M.get,
}
