local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0b0e0f",
  bg_darker = "#111618",
  bg_dark = "#171e21",
  bg_mid = "#1d262a",
  bg_light = "#232e33",
  bg_lighter = "#29363c",
  bg_lightest = "#2f3e45",
  bg_alt1 = "#0e1213",
  bg_alt2 = "#14191c",
  bg_alt3 = "#1a2225",
  bg_alt4 = "#202a2e",
  fg_lightest = "#e8eff2",
  fg_light = "#c0cdd4",
  fg_mid = "#7a8f98",
  fg_dark = "#546870",
  flintSteel = "#88A8B8",
  pineNeedle = "#5A9878",
  snowGlare = "#A8D8F0",
  bowYew = "#C8A058",
  wolfFang = "#D8CCBA",
  bloodOnSnow = "#D05050",
  graniteVein = "#8878A0",
  avalanche = "#70B0B0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.flintSteel,
      insert = plt.pineNeedle,
      visual = plt.bowYew,
      replace = plt.bloodOnSnow,
      command = plt.wolfFang,
    },
    accent = {
      accent1 = plt.flintSteel,
      accent2 = plt.pineNeedle,
      accent3 = plt.bowYew,
      accent4 = plt.fg_light,
      accent5 = plt.bloodOnSnow,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.flintSteel,
      rainbow2 = plt.bowYew,
      rainbow3 = plt.pineNeedle,
      rainbow4 = plt.bloodOnSnow,
      rainbow5 = plt.graniteVein,
      rainbow6 = plt.avalanche,
      rainbow7 = plt.wolfFang,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.bowYew,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.flintSteel,
      header2 = plt.bloodOnSnow,
      special = plt.wolfFang,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.graniteVein,
      indent = plt.bg_light,
      indent_scope = plt.flintSteel,
      picker = plt.pineNeedle,
      yank = plt.bowYew,
      mark = plt.bloodOnSnow,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.flintSteel,
        indicator = plt.bloodOnSnow,
      },
    },
    syn = {
      attribute = plt.wolfFang,
      boolean = plt.bowYew,
      comment = plt.fg_mid,
      constant = plt.bowYew,
      deprecated = plt.fg_dark,
      func = plt.flintSteel,
      identifier = plt.fg_lightest,
      keyword = plt.bloodOnSnow,
      method = plt.flintSteel,
      number = plt.bowYew,
      operator = plt.graniteVein,
      parameter = plt.avalanche,
      preproc = plt.wolfFang,
      punct = plt.fg_mid,
      regex = plt.snowGlare,
      special = plt.wolfFang,
      special2 = plt.snowGlare,
      special3 = plt.avalanche,
      statement = plt.bloodOnSnow,
      string = plt.pineNeedle,
      symbol = plt.graniteVein,
      type = plt.wolfFang,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.bloodOnSnow,
      warning = plt.bowYew,
      info = plt.flintSteel,
      ok = plt.pineNeedle,
      hint = plt.wolfFang,
      virtual_text_error = plt.bloodOnSnow,
      virtual_text_warning = plt.bowYew,
      virtual_text_info = plt.flintSteel,
      virtual_text_ok = plt.pineNeedle,
      virtual_text_hint = plt.wolfFang,
    },
    diff = {
      add = plt.pineNeedle,
      add_inline = plt.avalanche,
      change = plt.bowYew,
      change_inline = plt.graniteVein,
      delete = plt.bloodOnSnow,
      delete_inline = plt.bloodOnSnow,
      text = plt.wolfFang,
    },
    vcs = {
      added = plt.pineNeedle,
      changed = plt.bowYew,
      removed = plt.bloodOnSnow,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.bloodOnSnow,
      green = plt.pineNeedle,
      yellow = plt.bowYew,
      blue = plt.flintSteel,
      magenta = plt.graniteVein,
      cyan = plt.avalanche,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.bloodOnSnow):brighten(0.2):to_hex(),
      green_bright = color(plt.pineNeedle):brighten(0.15):to_hex(),
      yellow_bright = color(plt.bowYew):brighten(0.15):to_hex(),
      blue_bright = color(plt.flintSteel):brighten(0.15):to_hex(),
      magenta_bright = color(plt.graniteVein):brighten(0.2):to_hex(),
      cyan_bright = color(plt.avalanche):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.snowGlare,
      indexed2 = plt.wolfFang,
    },
  }
end

return {
  name = "Jötunheim – Skaði",
  author = "PrismPunk",
  description = "Winter huntress — where Njörðr longed for the sea, Skaði chose "
    .. "the granite silence of Þrymheimr's frozen peaks. Her world is stone and "
    .. "pine-shadow: flint-steel grey sparks where arrowheads kiss rock; pine-needle "
    .. "evergreen cloaks the slopes in ancient dark. Snow-glare blinds from summit "
    .. "ice while bow-yew amber warms her grip against the cold. Wolf-fang ivory "
    .. "gleams in the dark beside her, and blood-on-snow crimson marks each hunt's "
    .. "clean end. Granite-vein violet threads through the mountain's bones, and "
    .. "avalanche teal rumbles in the compressed glacial heart of things. No "
    .. "softness, no shore-spray — only the huntress, the mountain, and the kill.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.bloodOnSnow,
    base09 = palette.bowYew,
    base0A = palette.snowGlare,
    base0B = palette.pineNeedle,
    base0C = palette.wolfFang,
    base0D = palette.flintSteel,
    base0E = palette.graniteVein,
    base0F = palette.avalanche,
  },
  palette = palette,
  get = M.get,
}
