local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0505",
  bg_darker = "#140a0a",
  bg_dark = "#1e0f0f",
  bg_mid = "#281414",
  bg_light = "#321919",
  bg_lighter = "#3c1e1e",
  bg_lightest = "#462323",
  bg_alt1 = "#502828",
  bg_alt2 = "#5a2d2d",
  bg_alt3 = "#643232",
  bg_alt4 = "#6e3737",
  fg_lightest = "#ffffb4",
  fg_light = "#ffeda0",
  fg_mid = "#ffd88c",
  fg_dark = "#ffc378",
  sunChaser = "#783c3c",
  wolfPursuit = "#824141",
  endlessHunger = "#8c4646",
  solarEclipse = "#964b4b",
  ragnarokJaws = "#a05050",
  dawnDevoured = "#ff4500",
  burningHorizon = "#ff6f28",
  solarFlare = "#ff9950",
  eclipsedLight = "#ffae64",
  finalSunrise = "#ffd88c",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.sunChaser,
      insert = plt.solarEclipse,
      visual = plt.burningHorizon,
      replace = plt.dawnDevoured,
      command = plt.finalSunrise,
    },
    accent = {
      accent1 = plt.sunChaser,
      accent2 = plt.solarEclipse,
      accent3 = plt.burningHorizon,
      accent4 = plt.fg_light,
      accent5 = plt.dawnDevoured,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.sunChaser,
      rainbow2 = plt.wolfPursuit,
      rainbow3 = plt.endlessHunger,
      rainbow4 = plt.solarEclipse,
      rainbow5 = plt.burningHorizon,
      rainbow6 = plt.solarFlare,
      rainbow7 = plt.eclipsedLight,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.burningHorizon,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.sunChaser,
      header2 = plt.dawnDevoured,
      special = plt.finalSunrise,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.solarEclipse,
      indent = plt.bg_light,
      indent_scope = plt.sunChaser,
      picker = plt.burningHorizon,
      yank = plt.solarFlare,
      mark = plt.eclipsedLight,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.sunChaser,
        indicator = plt.dawnDevoured,
      },
    },
    syn = {
      attribute = plt.finalSunrise,
      boolean = plt.solarFlare,
      comment = plt.fg_mid,
      constant = plt.burningHorizon,
      deprecated = plt.fg_dark,
      func = plt.dawnDevoured,
      identifier = plt.fg_lightest,
      keyword = plt.solarFlare,
      method = plt.dawnDevoured,
      number = plt.burningHorizon,
      operator = plt.solarEclipse,
      parameter = plt.eclipsedLight,
      preproc = plt.finalSunrise,
      punct = plt.fg_mid,
      regex = plt.solarFlare,
      special = plt.finalSunrise,
      special2 = plt.solarFlare,
      special3 = plt.eclipsedLight,
      statement = plt.solarFlare,
      string = plt.dawnDevoured,
      symbol = plt.solarEclipse,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dawnDevoured,
      warning = plt.burningHorizon,
      info = plt.sunChaser,
      ok = plt.wolfPursuit,
      hint = plt.finalSunrise,
      virtual_text_error = plt.dawnDevoured,
      virtual_text_warning = plt.burningHorizon,
      virtual_text_info = plt.sunChaser,
      virtual_text_ok = plt.wolfPursuit,
      virtual_text_hint = plt.finalSunrise,
    },
    diff = {
      add = plt.wolfPursuit,
      add_inline = plt.solarEclipse,
      change = plt.burningHorizon,
      change_inline = plt.solarFlare,
      delete = plt.dawnDevoured,
      delete_inline = plt.endlessHunger,
      text = plt.finalSunrise,
    },
    vcs = {
      added = plt.wolfPursuit,
      changed = plt.burningHorizon,
      removed = plt.dawnDevoured,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.dawnDevoured,
      green = plt.wolfPursuit,
      yellow = plt.finalSunrise,
      blue = plt.sunChaser,
      magenta = plt.burningHorizon,
      cyan = plt.solarEclipse,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.dawnDevoured):brighten(0.2):to_hex(),
      green_bright = color(plt.wolfPursuit):brighten(0.15):to_hex(),
      yellow_bright = color(plt.finalSunrise):brighten(0.15):to_hex(),
      blue_bright = color(plt.sunChaser):brighten(0.15):to_hex(),
      magenta_bright = color(plt.burningHorizon):brighten(0.2):to_hex(),
      cyan_bright = color(plt.solarEclipse):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.eclipsedLight,
      indexed2 = plt.solarFlare,
    },
  }
end

return {
  name = "Jötunheim – Sköll",
  author = "PrismPunk",
  description = "Sun-chaser — wolf of pursuit, solar eclipse, Ragnarok's hunger. "
    .. "Sköll is the great wolf who eternally pursues the sun across the sky, driven by "
    .. "an insatiable hunger. His brother Hati chases the moon. At Ragnarok, the wolves "
    .. "will finally catch their prey — Sköll will devour the sun, plunging the world "
    .. "into darkness as the final battle begins. The palette moves from deep blood-red "
    .. "darkness to brilliant solar yellows — the endless chase from shadow into light, "
    .. "the moment of eclipse when wolf jaws close around the sun, and the dying flare "
    .. "of daylight before eternal night.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dawnDevoured,
    base09 = palette.burningHorizon,
    base0A = palette.eclipsedLight,
    base0B = palette.wolfPursuit,
    base0C = palette.finalSunrise,
    base0D = palette.sunChaser,
    base0E = palette.solarEclipse,
    base0F = palette.solarFlare,
  },
  palette = palette,
  get = M.get,
}
