local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0a0a",
  bg_darker = "#141414",
  bg_dark = "#1e1e1e",
  bg_mid = "#282828",
  bg_light = "#323232",
  bg_lighter = "#3c3c3c",
  bg_lightest = "#464646",
  bg_alt1 = "#505050",
  bg_alt2 = "#5a5a5a",
  bg_alt3 = "#646464",
  bg_alt4 = "#6e6e6e",
  fg_lightest = "#ffffff",
  fg_light = "#e6e6e6",
  fg_mid = "#c8c8c8",
  fg_dark = "#aaaaaa",
  mountainFlesh = "#969696",
  impossibleSize = "#a0a0a0",
  futileBlow = "#aaaaaa",
  sleepingGiant = "#b4b4b4",
  gloveMistake = "#bebebe",
  hammerStrike = "#c8c8c8",
  stoneDisguise = "#d2d2d2",
  vastShadow = "#dcdcdc",
  mockingLaughter = "#e6e6e6",
  trueForm = "#f0f0f0",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.mountainFlesh,
      insert = plt.sleepingGiant,
      visual = plt.hammerStrike,
      replace = plt.stoneDisguise,
      command = plt.trueForm,
    },
    accent = {
      accent1 = plt.mountainFlesh,
      accent2 = plt.sleepingGiant,
      accent3 = plt.hammerStrike,
      accent4 = plt.fg_light,
      accent5 = plt.stoneDisguise,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.mountainFlesh,
      rainbow2 = plt.impossibleSize,
      rainbow3 = plt.futileBlow,
      rainbow4 = plt.sleepingGiant,
      rainbow5 = plt.gloveMistake,
      rainbow6 = plt.hammerStrike,
      rainbow7 = plt.stoneDisguise,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.hammerStrike,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.mountainFlesh,
      header2 = plt.stoneDisguise,
      special = plt.trueForm,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.sleepingGiant,
      indent = plt.bg_light,
      indent_scope = plt.mountainFlesh,
      picker = plt.hammerStrike,
      yank = plt.vastShadow,
      mark = plt.mockingLaughter,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.mountainFlesh,
        indicator = plt.stoneDisguise,
      },
    },
    syn = {
      attribute = plt.trueForm,
      boolean = plt.hammerStrike,
      comment = plt.fg_mid,
      constant = plt.hammerStrike,
      deprecated = plt.fg_dark,
      func = plt.mountainFlesh,
      identifier = plt.fg_lightest,
      keyword = plt.stoneDisguise,
      method = plt.mountainFlesh,
      number = plt.hammerStrike,
      operator = plt.sleepingGiant,
      parameter = plt.mockingLaughter,
      preproc = plt.trueForm,
      punct = plt.fg_mid,
      regex = plt.vastShadow,
      special = plt.trueForm,
      special2 = plt.vastShadow,
      special3 = plt.mockingLaughter,
      statement = plt.stoneDisguise,
      string = plt.impossibleSize,
      symbol = plt.sleepingGiant,
      type = plt.trueForm,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.stoneDisguise,
      warning = plt.hammerStrike,
      info = plt.mountainFlesh,
      ok = plt.impossibleSize,
      hint = plt.trueForm,
      virtual_text_error = plt.stoneDisguise,
      virtual_text_warning = plt.hammerStrike,
      virtual_text_info = plt.mountainFlesh,
      virtual_text_ok = plt.impossibleSize,
      virtual_text_hint = plt.trueForm,
    },
    diff = {
      add = plt.impossibleSize,
      add_inline = plt.sleepingGiant,
      change = plt.hammerStrike,
      change_inline = plt.vastShadow,
      delete = plt.stoneDisguise,
      delete_inline = plt.futileBlow,
      text = plt.trueForm,
    },
    vcs = {
      added = plt.impossibleSize,
      changed = plt.hammerStrike,
      removed = plt.stoneDisguise,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.stoneDisguise,
      green = plt.impossibleSize,
      yellow = plt.trueForm,
      blue = plt.mountainFlesh,
      magenta = plt.hammerStrike,
      cyan = plt.sleepingGiant,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.stoneDisguise):brighten(0.2):to_hex(),
      green_bright = color(plt.impossibleSize):brighten(0.15):to_hex(),
      yellow_bright = color(plt.trueForm):brighten(0.15):to_hex(),
      blue_bright = color(plt.mountainFlesh):brighten(0.15):to_hex(),
      magenta_bright = color(plt.hammerStrike):brighten(0.2):to_hex(),
      cyan_bright = color(plt.sleepingGiant):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.mockingLaughter,
      indexed2 = plt.vastShadow,
    },
  }
end

return {
  name = "Jötunheim – Skrýmir",
  author = "PrismPunk",
  description = "Vast giant — impossible size, Thor's futile blows, mountain disguise. "
    .. "When Thor and his companions journeyed through Jötunheim, they encountered "
    .. "Skrýmir, a giant so vast they mistook his glove for a cave. Thor struck the "
    .. "sleeping giant three times with Mjölnir, blows that would shatter mountains, "
    .. "yet Skrýmir merely brushed them away as if acorns had fallen on his head. "
    .. "Later revealed as Útgarða-Loki in disguise, the giant's impossible scale "
    .. "humbled even the thunder god. The palette is monochromatic stone and shadow — "
    .. "the colorless vastness of something too large to comprehend, where even the "
    .. "mightiest weapons seem like toys against living mountains.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.stoneDisguise,
    base09 = palette.hammerStrike,
    base0A = palette.mockingLaughter,
    base0B = palette.impossibleSize,
    base0C = palette.trueForm,
    base0D = palette.mountainFlesh,
    base0E = palette.sleepingGiant,
    base0F = palette.vastShadow,
  },
  palette = palette,
  get = M.get,
}
