local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#05050a",
  bg_darker = "#0a0a14",
  bg_dark = "#0f0f1e",
  bg_mid = "#141428",
  bg_light = "#191932",
  bg_lighter = "#1e1e3c",
  bg_lightest = "#232346",
  bg_alt1 = "#282850",
  bg_alt2 = "#2d2d5a",
  bg_alt3 = "#323264",
  bg_alt4 = "#37376e",
  fg_lightest = "#ffffff",
  fg_light = "#d2ffff",
  fg_mid = "#96d2ff",
  fg_dark = "#6eaadc",
  stormWings = "#3c3c78",
  eagleForm = "#414182",
  mountainFortress = "#46468c",
  kidnappedGoddess = "#4b4b96",
  idunnApples = "#5050a0",
  lokiTrick = "#5555aa",
  skyChase = "#4682b4",
  featherFall = "#5a96c8",
  asgardWalls = "#82bef0",
  divineRescue = "#befaff",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.stormWings,
      insert = plt.kidnappedGoddess,
      visual = plt.skyChase,
      replace = plt.asgardWalls,
      command = plt.divineRescue,
    },
    accent = {
      accent1 = plt.stormWings,
      accent2 = plt.kidnappedGoddess,
      accent3 = plt.skyChase,
      accent4 = plt.fg_light,
      accent5 = plt.asgardWalls,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.stormWings,
      rainbow2 = plt.eagleForm,
      rainbow3 = plt.mountainFortress,
      rainbow4 = plt.kidnappedGoddess,
      rainbow5 = plt.lokiTrick,
      rainbow6 = plt.skyChase,
      rainbow7 = plt.featherFall,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.skyChase,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.stormWings,
      header2 = plt.asgardWalls,
      special = plt.divineRescue,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.kidnappedGoddess,
      indent = plt.bg_light,
      indent_scope = plt.stormWings,
      picker = plt.skyChase,
      yank = plt.featherFall,
      mark = plt.lokiTrick,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.stormWings,
        indicator = plt.asgardWalls,
      },
    },
    syn = {
      attribute = plt.divineRescue,
      boolean = plt.featherFall,
      comment = plt.fg_mid,
      constant = plt.skyChase,
      deprecated = plt.fg_dark,
      func = plt.divineRescue,
      identifier = plt.fg_lightest,
      keyword = plt.featherFall,
      method = plt.divineRescue,
      number = plt.skyChase,
      operator = plt.kidnappedGoddess,
      parameter = plt.lokiTrick,
      preproc = plt.divineRescue,
      punct = plt.fg_mid,
      regex = plt.featherFall,
      special = plt.divineRescue,
      special2 = plt.featherFall,
      special3 = plt.lokiTrick,
      statement = plt.featherFall,
      string = plt.asgardWalls,
      symbol = plt.kidnappedGoddess,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.asgardWalls,
      warning = plt.skyChase,
      info = plt.stormWings,
      ok = plt.eagleForm,
      hint = plt.divineRescue,
      virtual_text_error = plt.asgardWalls,
      virtual_text_warning = plt.skyChase,
      virtual_text_info = plt.stormWings,
      virtual_text_ok = plt.eagleForm,
      virtual_text_hint = plt.divineRescue,
    },
    diff = {
      add = plt.eagleForm,
      add_inline = plt.kidnappedGoddess,
      change = plt.skyChase,
      change_inline = plt.featherFall,
      delete = plt.asgardWalls,
      delete_inline = plt.mountainFortress,
      text = plt.divineRescue,
    },
    vcs = {
      added = plt.eagleForm,
      changed = plt.skyChase,
      removed = plt.asgardWalls,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.asgardWalls,
      green = plt.eagleForm,
      yellow = plt.divineRescue,
      blue = plt.stormWings,
      magenta = plt.skyChase,
      cyan = plt.kidnappedGoddess,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.asgardWalls):brighten(0.2):to_hex(),
      green_bright = color(plt.eagleForm):brighten(0.15):to_hex(),
      yellow_bright = color(plt.divineRescue):brighten(0.15):to_hex(),
      blue_bright = color(plt.stormWings):brighten(0.15):to_hex(),
      magenta_bright = color(plt.skyChase):brighten(0.2):to_hex(),
      cyan_bright = color(plt.kidnappedGoddess):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.lokiTrick,
      indexed2 = plt.featherFall,
    },
  }
end

return {
  name = "Jötunheim – Thjazi",
  author = "PrismPunk",
  description = "Eagle giant — Idunn's kidnapper, storm wings, mountain fortress, "
    .. "Loki's trick. Thjazi, a powerful jötunn, transformed into a massive eagle and "
    .. "kidnapped Idunn, goddess of youth, along with her golden apples of immortality. "
    .. "He imprisoned her in his mountain fortress, causing the gods to age without her "
    .. "apples. Loki, forced to rescue her, borrowed Freyja's falcon cloak and flew to "
    .. "Thrymheim. As they escaped, Thjazi pursued in eagle form, but the gods set fire "
    .. "to Asgard's walls — the giant's feathers caught flame and he fell to his death. "
    .. "The palette moves from deep indigo night to brilliant sky blue — storm wings "
    .. "against mountain darkness, the desperate chase through cold northern skies, and "
    .. "the final fall from heaven's edge.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.asgardWalls,
    base09 = palette.skyChase,
    base0A = palette.lokiTrick,
    base0B = palette.eagleForm,
    base0C = palette.divineRescue,
    base0D = palette.stormWings,
    base0E = palette.kidnappedGoddess,
    base0F = palette.featherFall,
  },
  palette = palette,
  get = M.get,
}
