local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0f0a14",
  bg_darker = "#19142d",
  bg_dark = "#231e46",
  bg_mid = "#2d285f",
  bg_light = "#373278",
  bg_lighter = "#413c91",
  bg_lightest = "#4b46aa",
  bg_alt1 = "#5550c3",
  bg_alt2 = "#5f5adc",
  bg_alt3 = "#6964f5",
  bg_alt4 = "#736eff",
  fg_lightest = "#ffffff",
  fg_light = "#e6d4ff",
  fg_mid = "#c8a8ff",
  fg_dark = "#a582ff",
  illusionVeil = "#b99aff",
  impossibleTask = "#c8a8ff",
  giantTrickery = "#d7b6ff",
  humbledGods = "#e6c4ff",
  utgardKing = "#f0d0ff",
  magicRevealed = "#e6a8ff",
  falseContest = "#d796ff",
  cosmicJest = "#c884ff",
  thorsShame = "#b972ff",
  lokisBewilderment = "#aa60ff",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.illusionVeil,
      insert = plt.giantTrickery,
      visual = plt.humbledGods,
      replace = plt.magicRevealed,
      command = plt.utgardKing,
    },
    accent = {
      accent1 = plt.illusionVeil,
      accent2 = plt.giantTrickery,
      accent3 = plt.humbledGods,
      accent4 = plt.fg_light,
      accent5 = plt.magicRevealed,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.illusionVeil,
      rainbow2 = plt.impossibleTask,
      rainbow3 = plt.giantTrickery,
      rainbow4 = plt.humbledGods,
      rainbow5 = plt.utgardKing,
      rainbow6 = plt.magicRevealed,
      rainbow7 = plt.falseContest,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.humbledGods,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.illusionVeil,
      header2 = plt.magicRevealed,
      special = plt.utgardKing,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.giantTrickery,
      indent = plt.bg_light,
      indent_scope = plt.illusionVeil,
      picker = plt.humbledGods,
      yank = plt.falseContest,
      mark = plt.cosmicJest,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.illusionVeil,
        indicator = plt.magicRevealed,
      },
    },
    syn = {
      attribute = plt.utgardKing,
      boolean = plt.humbledGods,
      comment = plt.fg_mid,
      constant = plt.humbledGods,
      deprecated = plt.fg_dark,
      func = plt.illusionVeil,
      identifier = plt.fg_lightest,
      keyword = plt.magicRevealed,
      method = plt.illusionVeil,
      number = plt.humbledGods,
      operator = plt.giantTrickery,
      parameter = plt.cosmicJest,
      preproc = plt.utgardKing,
      punct = plt.fg_mid,
      regex = plt.falseContest,
      special = plt.utgardKing,
      special2 = plt.falseContest,
      special3 = plt.cosmicJest,
      statement = plt.magicRevealed,
      string = plt.impossibleTask,
      symbol = plt.giantTrickery,
      type = plt.utgardKing,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.magicRevealed,
      warning = plt.humbledGods,
      info = plt.illusionVeil,
      ok = plt.impossibleTask,
      hint = plt.utgardKing,
      virtual_text_error = plt.magicRevealed,
      virtual_text_warning = plt.humbledGods,
      virtual_text_info = plt.illusionVeil,
      virtual_text_ok = plt.impossibleTask,
      virtual_text_hint = plt.utgardKing,
    },
    diff = {
      add = plt.impossibleTask,
      add_inline = plt.giantTrickery,
      change = plt.humbledGods,
      change_inline = plt.falseContest,
      delete = plt.magicRevealed,
      delete_inline = plt.thorsShame,
      text = plt.utgardKing,
    },
    vcs = {
      added = plt.impossibleTask,
      changed = plt.humbledGods,
      removed = plt.magicRevealed,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.magicRevealed,
      green = plt.impossibleTask,
      yellow = plt.utgardKing,
      blue = plt.illusionVeil,
      magenta = plt.humbledGods,
      cyan = plt.giantTrickery,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.magicRevealed):brighten(0.2):to_hex(),
      green_bright = color(plt.impossibleTask):brighten(0.15):to_hex(),
      yellow_bright = color(plt.utgardKing):brighten(0.15):to_hex(),
      blue_bright = color(plt.illusionVeil):brighten(0.15):to_hex(),
      magenta_bright = color(plt.humbledGods):brighten(0.2):to_hex(),
      cyan_bright = color(plt.giantTrickery):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.cosmicJest,
      indexed2 = plt.falseContest,
    },
  }
end

return {
  name = "Jötunheim – Útgarða-Loki",
  author = "PrismPunk",
  description = "Illusion master — impossible contests, humbled gods, giant king's "
    .. "tricks. Thor and Loki journeyed to Útgarðr, where the giant king set them "
    .. "contests that seemed simple but proved impossible. Thor could not lift a "
    .. "cat (the World Serpent in disguise), could not drain a horn (connected to "
    .. "the ocean), could not defeat an old woman (Old Age herself). Only when the "
    .. "illusions lifted did the gods realize they'd been contending against cosmic "
    .. "forces. The palette shimmers with deep violet shadows and brilliant magenta "
    .. "highlights — the colors of magic and misdirection, where nothing is as it "
    .. "seems and even the mightiest gods are made fools by clever illusion.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.magicRevealed,
    base09 = palette.humbledGods,
    base0A = palette.cosmicJest,
    base0B = palette.impossibleTask,
    base0C = palette.utgardKing,
    base0D = palette.illusionVeil,
    base0E = palette.giantTrickery,
    base0F = palette.falseContest,
  },
  palette = palette,
  get = M.get,
}
