local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050a0f",
  bg_darker = "#0a1419",
  bg_dark = "#0f1e28",
  bg_mid = "#142837",
  bg_light = "#193246",
  bg_lighter = "#1e3c55",
  bg_lightest = "#234664",
  bg_alt1 = "#0c1820",
  bg_alt2 = "#111f2e",
  bg_alt3 = "#162a3c",
  bg_alt4 = "#1b344a",
  fg_lightest = "#e0ecf8",
  fg_light = "#b8d0e8",
  fg_mid = "#7098b8",
  fg_dark = "#4e7090",
  frostBlood = "#E85050",
  boneWhite = "#C8D8E8",
  fleshEarth = "#B87858",
  skullVault = "#68A8D8",
  brainCloud = "#8878A8",
  voidFrost = "#48A0A0",
  audhumla = "#D8A848",
  cosmicWound = "#C03030",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.skullVault,
      insert = plt.voidFrost,
      visual = plt.audhumla,
      replace = plt.frostBlood,
      command = plt.boneWhite,
    },
    accent = {
      accent1 = plt.skullVault,
      accent2 = plt.voidFrost,
      accent3 = plt.audhumla,
      accent4 = plt.fg_light,
      accent5 = plt.frostBlood,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.skullVault,
      rainbow2 = plt.audhumla,
      rainbow3 = plt.voidFrost,
      rainbow4 = plt.frostBlood,
      rainbow5 = plt.brainCloud,
      rainbow6 = plt.fleshEarth,
      rainbow7 = plt.boneWhite,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.audhumla,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.skullVault,
      header2 = plt.frostBlood,
      special = plt.boneWhite,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.fleshEarth,
      indent = plt.bg_light,
      indent_scope = plt.skullVault,
      picker = plt.voidFrost,
      yank = plt.audhumla,
      mark = plt.frostBlood,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.skullVault,
        indicator = plt.frostBlood,
      },
    },
    syn = {
      attribute = plt.boneWhite,
      boolean = plt.audhumla,
      comment = plt.fg_mid,
      constant = plt.audhumla,
      deprecated = plt.fg_dark,
      func = plt.skullVault,
      identifier = plt.fg_lightest,
      keyword = plt.frostBlood,
      method = plt.skullVault,
      number = plt.audhumla,
      operator = plt.brainCloud,
      parameter = plt.voidFrost,
      preproc = plt.boneWhite,
      punct = plt.fg_mid,
      regex = plt.fleshEarth,
      special = plt.boneWhite,
      special2 = plt.fleshEarth,
      special3 = plt.voidFrost,
      statement = plt.frostBlood,
      string = plt.voidFrost,
      symbol = plt.brainCloud,
      type = plt.boneWhite,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.frostBlood,
      warning = plt.audhumla,
      info = plt.skullVault,
      ok = plt.voidFrost,
      hint = plt.boneWhite,
      virtual_text_error = plt.frostBlood,
      virtual_text_warning = plt.audhumla,
      virtual_text_info = plt.skullVault,
      virtual_text_ok = plt.voidFrost,
      virtual_text_hint = plt.boneWhite,
    },
    diff = {
      add = plt.voidFrost,
      add_inline = plt.skullVault,
      change = plt.audhumla,
      change_inline = plt.fleshEarth,
      delete = plt.frostBlood,
      delete_inline = plt.cosmicWound,
      text = plt.boneWhite,
    },
    vcs = {
      added = plt.voidFrost,
      changed = plt.audhumla,
      removed = plt.frostBlood,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.frostBlood,
      green = plt.voidFrost,
      yellow = plt.audhumla,
      blue = plt.skullVault,
      magenta = plt.brainCloud,
      cyan = plt.boneWhite,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.frostBlood):brighten(0.2):to_hex(),
      green_bright = color(plt.voidFrost):brighten(0.15):to_hex(),
      yellow_bright = color(plt.audhumla):brighten(0.15):to_hex(),
      blue_bright = color(plt.skullVault):brighten(0.15):to_hex(),
      magenta_bright = color(plt.brainCloud):brighten(0.2):to_hex(),
      cyan_bright = color(plt.boneWhite):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.fleshEarth,
      indexed2 = plt.cosmicWound,
    },
  }
end

return {
  name = "Jötunheim – Ymir",
  author = "PrismPunk",
  description = "Primordial sacrifice — from the frost-black void of Ginnungagap "
    .. "rises the first giant whose death birthed the world. Frost-blood crimson "
    .. "pours from his veins to fill the seas; bone-white glacial peaks are carved "
    .. "from his skeleton. Flesh-earth ochre becomes the soil beneath all things, "
    .. "skull-vault ice-blue arches overhead as the inverted dome of sky. Brain-cloud "
    .. "violet gathers as storm-thoughts wrung from his mind; void-frost teal "
    .. "remembers the chasm before fire met ice. Auðumbla's warm amber milk-light "
    .. "nourishes what comes next, while cosmic-wound arterial red marks the "
    .. "sacrifice without which nothing could exist.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.frostBlood,
    base09 = palette.audhumla,
    base0A = palette.fleshEarth,
    base0B = palette.voidFrost,
    base0C = palette.boneWhite,
    base0D = palette.skullVault,
    base0E = palette.brainCloud,
    base0F = palette.cosmicWound,
  },
  palette = palette,
  get = M.get,
}
