local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.kanagawa.paper-edo")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.dragonBlue,
      insert = plt.dragonGreen,
      normal = plt.dragonYellow,
      replace = plt.dragonRed,
      visual = plt.dragonViolet,
    },
    accent = {
      accent1 = plt.dragonBlue,
      accent2 = plt.dragonOrange,
      accent3 = plt.dragonAqua,
      accent4 = plt.dragonGray,
      accent5 = plt.dragonRed,
      invert = plt.sumiInk4,
    },
    rainbow = {
      rainbow1 = plt.dragonRed,
      rainbow2 = plt.dragonPink,
      rainbow3 = plt.dragonYellow,
      rainbow4 = plt.dragonOrange,
      rainbow5 = plt.dragonGreen,
      rainbow6 = plt.dragonBlue,
      rainbow7 = plt.dragonAqua,
    },
    ui = {
      bg = plt.sumiInk0,
      bg_cursorline = plt.sumiInk3,
      bg_dim = plt.sumiInk0,
      bg_gutter = opts.gutter and plt.sumiInk4 or "none",
      bg_highlight = plt.sumiInk4,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_statusline = plt.sumiInk4,
      bg_visual = plt.sumiInk4,
      border = plt.dragonBlack6,
      cursorline = plt.sumiInk3,
      fg = plt.fujiWhite,
      fg_dim = plt.dragonGray2,
      fg_reverse = plt.sumiInk0,
      indent = plt.sumiInk5,
      line_nr = plt.dragonGray,
      line_nr_active = plt.fujiWhite,
      line_nr_dim = plt.sumiInk6,
      nontext = plt.sumiInk6,
      selection = plt.sumiInk4,
      win_separator = plt.dragonViolet,
      float = {
        bg = plt.sumiInk3,
        bg_border = plt.sumiInk3,
        fg = plt.oldWhite,
        fg_border = plt.sumiInk5,
      },
      pmenu = {
        bg = plt.sumiInk4,
        bg_border = plt.sumiInk4,
        bg_sbar = plt.sumiInk4,
        bg_sel = plt.sumiInk5,
        bg_thumb = plt.sumiInk6,
        fg = plt.fujiWhite,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
      },
    },
    syn = {
      attribute = plt.dragonYellow,
      boolean = plt.dragonOrange,
      comment = plt.dragonGray2,
      constant = plt.dragonOrange,
      deprecated = plt.dragonGray,
      func = plt.dragonBlue,
      identifier = plt.fujiWhite,
      keyword = plt.dragonPink,
      method = plt.dragonBlue,
      number = plt.dragonPink,
      operator = plt.dragonRed,
      parameter = plt.dragonGray,
      preproc = plt.dragonViolet,
      punct = plt.dragonGray,
      regex = plt.dragonYellow,
      special = plt.dragonYellow,
      statement = plt.dragonViolet,
      string = plt.dragonGreen,
      symbol = plt.dragonRed,
      type = plt.dragonAqua,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.dragonRed,
      hint = plt.dragonAqua,
      info = plt.dragonBlue,
      ok = plt.dragonGreen,
      warning = plt.dragonYellow,
      virtual_text_error = plt.dragonRed,
      virtual_text_hint = plt.dragonAqua,
      virtual_text_info = plt.dragonBlue,
      virtual_text_ok = plt.dragonGreen,
      virtual_text_warning = plt.dragonYellow,
    },
    diff = {
      add = plt.dragonGreen,
      add_inline = plt.edoTeal,
      change = plt.dragonYellow,
      change_inline = plt.edoAmber,
      delete = plt.dragonRed,
      delete_inline = plt.dragonPink,
      text = plt.dragonBlue,
    },
    vcs = {
      added = plt.dragonGreen,
      changed = plt.dragonYellow,
      removed = plt.dragonRed,
    },
    term = {
      black = plt.sumiInk0,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      blue = plt.dragonBlue,
      blue_bright = color(plt.dragonBlue):brighten(0.3):to_hex(),
      cyan = plt.dragonAqua,
      cyan_bright = color(plt.dragonAqua):brighten(0.1):to_hex(),
      green = plt.dragonGreen,
      green_bright = color(plt.dragonGreen):brighten(0.1):to_hex(),
      magenta = plt.dragonPink,
      magenta_bright = color(plt.dragonPink):brighten(0.2):to_hex(),
      red = plt.dragonRed,
      red_bright = color(plt.dragonRed):brighten(0.2):to_hex(),
      white = plt.oldWhite,
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      yellow = plt.dragonYellow,
      yellow_bright = color(plt.dragonYellow):brighten(0.2):to_hex(),
    },
  }
end

return {
  name = "Kanagawa Paper – Edo",
  author = "PrismPunk.nvim",
  description = "Dark ink and soft paper tones inspired by Kanagawa-Paper, translated into PrismPunk format.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.dragonGray,
    base06 = palette.fujiWhite,
    base07 = palette.oldWhite,
    base08 = palette.dragonRed,
    base09 = palette.dragonOrange,
    base0A = palette.dragonYellow,
    base0B = palette.dragonGreen,
    base0C = palette.dragonAqua,
    base0D = palette.dragonBlue,
    base0E = palette.dragonViolet,
    base0F = palette.dragonPink,
  },
  palette = palette,
  get = M.get,
}
