local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#16161D",
  sumiInk1 = "#181820",
  sumiInk2 = "#1A1A22",
  sumiInk3 = "#1F1F28",
  sumiInk4 = "#2A2A37",
  sumiInk5 = "#363646",
  sumiInk6 = "#54546D",
  sumiInkShadow = "#0F0F15",
  sumiInkEcho = "#1C1C24",
  sumiInkTint = "#242430",
  fujiWhite = "#DCD7BA",
  oldWhite = "#C8C093",
  fujiGray = "#727169",
  dragonGray = "#9E9B93",
  dragonGray2 = "#9E9B93",
  dragonGray3 = "#7A8382",
  katanaGray = "#717C7C",
  dragonRed = "#C4746E",
  dragonPink = "#A292A3",
  dragonOrange = "#B6927B",
  dragonOrange2 = "#B98D7B",
  dragonYellow = "#C4B28A",
  dragonGreen = "#699469",
  dragonGreen2 = "#8A9A7B",
  dragonBlue = "#658594",
  dragonBlue2 = "#859FAC",
  dragonBlue5 = "#435965",
  dragonViolet = "#8992A7",
  dragonAqua = "#8EA49E",
  dragonAsh = "#737C73",
  dragonTeal = "#949FB5",
  springViolet1 = "#938AA9",
  waveAqua1 = "#6A9589",
  waveAqua2 = "#7AA89F",
  dragonGlow = "#E6C4A0",
  dragonVivid = "#F0D4B0",
  dragonFlare = "#F8E4C0",
  dragonAccent1 = "#3A2F35",
  dragonAccent2 = "#44363D",
  dragonAccent3 = "#4E3D45",
  dragonAccent4 = "#58444D",
  dragonAccent5 = "#624B55",

  bg_darkest = "#0F0F15",
  fg_lightest = "#DCD7BA",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      command = plt.dragonBlue,
      insert = plt.dragonGreen,
      normal = plt.dragonYellow,
      replace = plt.dragonRed,
      visual = plt.springViolet1,
    },
    accent = {
      accent1 = plt.dragonBlue,
      accent2 = plt.dragonOrange,
      accent3 = plt.waveAqua1,
      accent4 = plt.dragonGray3,
      accent5 = plt.dragonRed,
      invert = plt.sumiInk4,
    },
    rainbow = {
      rainbow1 = plt.dragonRed,
      rainbow2 = plt.dragonPink,
      rainbow3 = plt.dragonBlue,
      rainbow4 = plt.dragonOrange2,
      rainbow5 = plt.dragonGreen,
      rainbow6 = plt.dragonAsh,
      rainbow7 = plt.dragonTeal,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.dragonGray2,
      fg_dimmer = plt.dragonGray3,
      fg_dark = plt.fujiGray,
      fg_reverse = plt.sumiInk3,
      bg = plt.sumiInk3,
      bg_dim = plt.sumiInk3,
      bg_m1 = plt.sumiInk2,
      bg_m2 = plt.sumiInk3,
      bg_m3 = plt.sumiInk4,
      bg_m4 = plt.sumiInk5,
      bg_p1 = plt.sumiInk4,
      bg_p2 = plt.sumiInk5,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk4 or "none",
      bg_cursorline = plt.sumiInk4,
      bg_cursorline_alt = plt.sumiInk5,
      cursorline = plt.sumiInk4,
      bg_highlight = plt.sumiInk5,
      bg_search = plt.dragonGlow,
      bg_visual = plt.sumiInk5,
      bg_statusline = plt.sumiInk4,
      border = plt.sumiInk6,
      header1 = plt.dragonYellow,
      header2 = plt.dragonBlue,
      special = plt.springViolet1,
      nontext = plt.sumiInk6,
      whitespace = plt.dragonAsh,
      win_separator = plt.sumiInk6,
      indent = plt.sumiInk5,
      indent_scope = plt.dragonBlue,
      picker = plt.dragonViolet,
      yank = plt.dragonVivid,
      mark = plt.dragonRed,
      scrollbar = plt.sumiInk6,
      selection = plt.sumiInk5,
      line_nr = plt.dragonGray3,
      line_nr_dim = plt.sumiInk6,
      line_nr_active = plt.fujiWhite,
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk4,
        fg_border = plt.sumiInk5,
        bg_border = plt.sumiInk4,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.sumiInk6,
        bg = plt.sumiInk4,
        bg_sel = plt.sumiInk5,
        bg_border = plt.sumiInk4,
        bg_sbar = plt.sumiInk4,
        bg_thumb = plt.sumiInk6,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk3,
        bg_alternate = plt.sumiInk1,
        fg_inactive = plt.dragonGray3,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.dragonYellow,
        indicator = plt.dragonBlue,
      },
    },
    syn = {
      attribute = plt.dragonYellow,
      boolean = plt.dragonPink,
      comment = plt.fujiGray,
      constant = plt.dragonOrange,
      deprecated = plt.katanaGray,
      func = plt.dragonBlue2,
      identifier = plt.dragonYellow,
      keyword = plt.dragonPink,
      method = plt.dragonBlue2,
      number = plt.dragonPink,
      operator = plt.dragonRed,
      parameter = plt.dragonGray,
      preproc = plt.dragonRed,
      punct = plt.dragonGray2,
      regex = plt.dragonRed,
      special = plt.dragonYellow,
      special2 = plt.dragonViolet,
      special3 = plt.waveAqua2,
      statement = plt.dragonViolet,
      string = plt.dragonGreen2,
      symbol = plt.dragonRed,
      type = plt.dragonAqua,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.dragonRed,
      warning = plt.dragonYellow,
      info = plt.dragonBlue,
      hint = plt.dragonAqua,
      ok = plt.dragonGreen,
      virtual_text_error = plt.dragonRed,
      virtual_text_warning = plt.dragonYellow,
      virtual_text_info = plt.dragonBlue,
      virtual_text_hint = plt.dragonAqua,
      virtual_text_ok = plt.dragonGreen,
    },
    diff = {
      add = plt.dragonGreen,
      add_inline = plt.dragonGreen2,
      change = plt.dragonYellow,
      change_inline = plt.dragonOrange2,
      delete = plt.dragonRed,
      delete_inline = plt.dragonPink,
      text = plt.dragonBlue,
    },
    vcs = {
      added = plt.dragonGreen,
      changed = plt.dragonYellow,
      removed = plt.dragonRed,
    },
    term = {
      black = plt.sumiInk3,
      red = plt.dragonRed,
      green = plt.dragonGreen,
      yellow = plt.dragonYellow,
      blue = plt.dragonBlue5,
      magenta = plt.dragonPink,
      cyan = plt.dragonAqua,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk3):brighten(0.6):to_hex(),
      red_bright = color(plt.dragonRed):brighten(0.2):to_hex(),
      green_bright = color(plt.dragonGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.dragonYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.dragonBlue5):brighten(0.3):to_hex(),
      magenta_bright = color(plt.dragonPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.dragonAqua):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.dragonGlow,
      indexed2 = plt.dragonFlare,
    },
  }
end

return {
  name = "Kanagawa Paper – Dragon",
  author = "PrismPunk.nvim",
  description = "The dragon awakens. Mid-dark ink canvas. Vibrant, balanced, and dangerously beautiful.",
  base16 = {
    base00 = palette.sumiInk3,
    base01 = palette.sumiInk4,
    base02 = palette.sumiInk5,
    base03 = palette.sumiInk6,
    base04 = palette.dragonGray2,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.fujiWhite,
    base08 = palette.dragonRed,
    base09 = palette.dragonOrange,
    base0A = palette.dragonYellow,
    base0B = palette.dragonGreen,
    base0C = palette.dragonAqua,
    base0D = palette.dragonBlue,
    base0E = palette.dragonViolet,
    base0F = palette.dragonPink,
  },
  palette = palette,
  get = M.get,
}
