local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.kanagawa.paper-sunset")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.sunsetGold,
      insert = plt.autumnGreen,
      visual = plt.horizonViolet,
      replace = plt.flareRose,
      command = plt.emberOrange,
    },
    accent = {
      accent1 = plt.sunsetGold,
      accent2 = plt.horizonViolet,
      accent3 = plt.twilightPink,
      accent4 = plt.duskCoral,
      accent5 = plt.emberOrange,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.flareRose,
      rainbow2 = plt.duskCoral,
      rainbow3 = plt.emberOrange,
      rainbow4 = plt.sunsetGold,
      rainbow5 = plt.autumnGreen,
      rainbow6 = plt.waveAqua1,
      rainbow7 = plt.horizonViolet,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.mistGray,
      fg_dark = plt.mistGray,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk1 or "none",
      bg_cursorline = plt.sumiInk3,
      bg_cursorline_alt = plt.sumiInk2,
      cursorline = plt.sumiInk3,
      bg_highlight = plt.sumiInk3,
      bg_search = plt.sunsetAccent2,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInk1,
      border = plt.sumiInk4,
      header1 = plt.sunsetGold,
      header2 = plt.horizonViolet,
      special = plt.flareRose,
      nontext = plt.sumiInk3,
      whitespace = plt.sumiInk3,
      win_separator = plt.sumiInk4,
      indent = plt.sumiInk2,
      indent_scope = plt.sunsetGold,
      picker = plt.horizonViolet,
      yank = plt.emberOrange,
      mark = plt.twilightPink,
      scrollbar = plt.sumiInk3,
      selection = plt.sumiInk3,
      line_nr = plt.sumiInk4,
      line_nr_dim = plt.sumiInk3,
      line_nr_active = plt.fujiWhite,
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = plt.fujiWhite,
        fg_border = plt.sumiInk4,
        bg = plt.sumiInk1,
        bg_sel = plt.sumiInk3,
        bg_border = plt.sumiInk1,
        bg_sbar = plt.sumiInk1,
        bg_thumb = plt.sumiInk4,
      },
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk1,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk1,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        fg_inactive = plt.mistGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.sunsetGold,
        indicator = plt.sunsetGold,
      },
    },
    syn = {
      attribute = plt.sandTan,
      boolean = plt.waveAqua1,
      comment = plt.mistGray,
      constant = plt.sandTan,
      deprecated = plt.mistGray,
      func = plt.horizonViolet,
      identifier = plt.fujiWhite,
      keyword = plt.autumnRed,
      method = plt.horizonViolet,
      number = plt.sunsetGold,
      operator = plt.emberOrange,
      parameter = plt.oldWhite,
      preproc = plt.flareRose,
      punct = plt.emberOrange,
      regex = plt.waveAqua1,
      special = plt.flareRose,
      special2 = plt.twilightPink,
      special3 = plt.duskCoral,
      statement = plt.autumnRed,
      string = plt.twilightPink,
      symbol = plt.flareRose,
      type = plt.horizonViolet,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.flareRose,
      warning = plt.sunsetGold,
      info = plt.waveAqua1,
      hint = plt.duskCoral,
      ok = plt.autumnGreen,
      virtual_text_error = plt.flareRose,
      virtual_text_warning = plt.sunsetGold,
      virtual_text_info = plt.waveAqua1,
      virtual_text_hint = plt.duskCoral,
      virtual_text_ok = plt.autumnGreen,
    },
    diff = {
      add = plt.autumnGreen,
      add_inline = plt.sunsetGlow,
      change = plt.sunsetGold,
      change_inline = plt.sunsetVivid,
      delete = plt.flareRose,
      delete_inline = plt.duskCoral,
      text = plt.waveAqua1,
    },
    vcs = {
      added = plt.autumnGreen,
      changed = plt.sunsetGold,
      removed = plt.flareRose,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.flareRose,
      green = plt.autumnGreen,
      yellow = plt.sunsetGold,
      blue = plt.waveBlue2,
      magenta = plt.horizonViolet,
      cyan = plt.waveAqua1,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.flareRose):brighten(0.2):to_hex(),
      green_bright = color(plt.autumnGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.sunsetGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.waveBlue2):brighten(0.3):to_hex(),
      magenta_bright = color(plt.horizonViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.waveAqua1):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.emberOrange,
      indexed2 = plt.twilightPink,
    },
  }
end

return {
  name = "Kanagawa Paper – Sunset",
  author = "PrismPunk.nvim",
  description = "Soft dusk variant with warm highlights and muted shadows.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softPaper,
    base08 = palette.flareRose,
    base09 = palette.duskCoral,
    base0A = palette.sunsetGold,
    base0B = palette.autumnGreen,
    base0C = palette.waveAqua1,
    base0D = palette.waveBlue2,
    base0E = palette.horizonViolet,
    base0F = palette.emberOrange,
  },
  palette = palette,
  get = M.get,
}
