local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.kanagawa.paper-nightfall")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.waveBlue2,
      insert = plt.autumnGreen,
      normal = plt.subtleGold,
      replace = plt.autumnRed,
      visual = plt.springViolet1,
    },
    accent = {
      accent1 = plt.waveBlue2,
      accent2 = plt.subtleGold,
      accent3 = plt.waveAqua1,
      accent4 = plt.springViolet1,
      accent5 = plt.gentlePink,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.autumnRed,
      rainbow2 = plt.gentlePink,
      rainbow3 = plt.autumnYellow,
      rainbow4 = plt.subtleGold,
      rainbow5 = plt.autumnGreen,
      rainbow6 = plt.waveBlue1,
      rainbow7 = plt.calmTeal,
    },
    ui = {
      bg = plt.sumiInk0,
      bg_cursorline = plt.sumiInk3,
      bg_dim = plt.sumiInk0,
      bg_gutter = opts.gutter and plt.sumiInk1 or "none",
      bg_highlight = plt.sumiInk3,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_statusline = plt.sumiInk1,
      bg_visual = plt.sumiInk3,
      border = plt.sumiInk4,
      cursorline = plt.sumiInk3,
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_reverse = plt.sumiInk0,
      indent = plt.sumiInk2,
      line_nr = plt.sumiInk4,
      line_nr_active = plt.fujiWhite,
      line_nr_dim = plt.sumiInk3,
      nontext = plt.sumiInk2,
      selection = plt.sumiInk3,
      win_separator = plt.sumiInk4,
      float = {
        bg = plt.sumiInk1,
        bg_border = plt.sumiInk1,
        fg = plt.oldWhite,
        fg_border = plt.sumiInk4,
      },
      pmenu = {
        bg = plt.sumiInk1,
        bg_border = plt.sumiInk1,
        bg_sbar = plt.sumiInk1,
        bg_sel = plt.sumiInk3,
        bg_thumb = plt.sumiInk4,
        fg = plt.fujiWhite,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        fg_inactive = plt.softGray,
        fg_selected = plt.fujiWhite,
      },
    },
    syn = {
      attribute = plt.oldWhite,
      boolean = plt.waveAqua1,
      comment = plt.softGray,
      constant = plt.oldWhite,
      deprecated = plt.softGray,
      func = plt.waveBlue1,
      identifier = plt.fujiWhite,
      keyword = plt.autumnRed,
      method = plt.waveBlue1,
      number = plt.waveBlue2,
      operator = plt.subtleGold,
      parameter = plt.oldWhite,
      preproc = plt.springViolet1,
      punct = plt.sumiInk4,
      regex = plt.waveAqua1,
      special = plt.waveAqua1,
      statement = plt.autumnRed,
      string = plt.gentlePink,
      symbol = plt.waveAqua1,
      type = plt.calmTeal,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.autumnRed,
      hint = plt.autumnGreen,
      info = plt.waveBlue1,
      ok = plt.waveAqua1,
      warning = plt.autumnYellow,
      virtual_text_error = plt.autumnRed,
      virtual_text_hint = plt.autumnGreen,
      virtual_text_info = plt.waveBlue1,
      virtual_text_ok = plt.waveAqua1,
      virtual_text_warning = plt.autumnYellow,
    },
    diff = {
      add = plt.autumnGreen,
      add_inline = plt.nightfallGlow,
      change = plt.subtleGold,
      change_inline = plt.duskAmber,
      delete = plt.autumnRed,
      delete_inline = plt.twilightCoral,
      text = plt.waveAqua1,
    },
    vcs = {
      added = plt.autumnGreen,
      changed = plt.autumnYellow,
      removed = plt.autumnRed,
    },
    term = {
      black = plt.sumiInk0,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      blue = plt.waveBlue1,
      blue_bright = color(plt.waveBlue1):brighten(0.3):to_hex(),
      cyan = plt.waveAqua1,
      cyan_bright = color(plt.waveAqua1):brighten(0.1):to_hex(),
      green = plt.autumnGreen,
      green_bright = color(plt.autumnGreen):brighten(0.1):to_hex(),
      magenta = plt.springViolet1,
      magenta_bright = color(plt.springViolet1):brighten(0.2):to_hex(),
      red = plt.autumnRed,
      red_bright = color(plt.autumnRed):brighten(0.2):to_hex(),
      white = plt.oldWhite,
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      yellow = plt.autumnYellow,
      yellow_bright = color(plt.autumnYellow):brighten(0.2):to_hex(),
    },
  }
end

return {
  name = "Kanagawa Paper – Nightfall",
  author = "PrismPunk.nvim",
  description = "Dark mode – Ink variant of Kanagawa Paper, extended with extra semantic colour mappings.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softGray,
    base08 = palette.autumnRed,
    base09 = palette.autumnYellow,
    base0A = palette.subtleGold,
    base0B = palette.autumnGreen,
    base0C = palette.waveAqua1,
    base0D = palette.waveBlue2,
    base0E = palette.springViolet1,
    base0F = palette.gentlePink,
  },
  palette = palette,
  get = M.get,
}
