local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0C0A05",
  savanna_night = "#111006",
  predator_core = "#181E0A",
  moonlit_grass = "#1F2B10",
  golden_fur = "#FFDD77",
  cheetah_gold = "#FFCC44",
  sunlit_spots = "#FFBB22",
  amber_glow = "#FFAA00",
  predator_gold = "#EE9900",
  urzkartaga_green = "#228844",
  jungle_curse = "#33AA55",
  emerald_eyes = "#44CC66",
  venom_vines = "#55EE77",
  fresh_blood = "#CC1122",
  claw_red = "#FF2233",
  hunt_rage = "#FF4455",
  dried_blood = "#880011",
  cheetah_spots = "#332211",
  shadow_fur = "#554433",
  midnight_spots = "#221A00",
  moon_dust = "#BBCC99",
  savanna_teal = "#669977",
  predator_teal = "#448866",
  term_red = "#FF2233",
  term_green = "#44CC66",
  term_yellow = "#FFCC44",
  term_blue = "#4488CC",
  term_purple = "#AA44AA",
  term_cyan = "#55BBAA",
  term_magenta = "#FF5588",
  term_red_bright = "#FF6666",
  term_green_bright = "#66EE88",
  term_yellow_bright = "#FFDD66",
  term_blue_bright = "#66AAFF",
  term_purple_bright = "#CC66CC",
  term_cyan_bright = "#77DDDD",

  bg_darkest = "#0C0A05",
  fg_lightest = "#FFDD66",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.cheetah_gold,
      insert = plt.claw_red,
      visual = plt.emerald_eyes,
      replace = plt.hunt_rage,
      command = plt.urzkartaga_green,
    },

    ui = {
      fg = plt.golden_fur,
      fg_dim = plt.sunlit_spots,
      fg_dimmer = plt.amber_glow,
      fg_dark = plt.emerald_eyes,
      fg_reverse = plt.void_black,

      bg_m4 = plt.moonlit_grass,
      bg_m3 = plt.predator_core,
      bg_m2 = plt.savanna_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.savanna_night,
      bg_p2 = plt.predator_core,
      bg_gutter = opts.gutter and plt.predator_core or "none",
      bg_cursorline = plt.predator_core,
      bg_cursorline_alt = plt.savanna_night,
      bg_search = plt.predator_gold,
      bg_visual = plt.fresh_blood,
      bg_statusline = plt.predator_core,

      border = plt.sunlit_spots,
      header1 = plt.cheetah_gold,
      header2 = plt.claw_red,
      special = plt.emerald_eyes,
      nontext = plt.savanna_night,
      whitespace = plt.moonlit_grass,
      win_separator = plt.sunlit_spots,
      indent = plt.savanna_night,
      indent_scope = plt.amber_glow,
      picker = plt.golden_fur,
      yank = plt.hunt_rage,
      mark = plt.claw_red,
      scrollbar = plt.predator_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.golden_fur,
        bg_selected = plt.predator_core,
        fg_inactive = plt.amber_glow,
        bg_inactive = plt.void_black,
        fg_alternate = plt.cheetah_gold,
        bg_alternate = plt.void_black,
        indicator = plt.fresh_blood,
      },

      pmenu = {
        fg = plt.golden_fur,
        fg_sel = "none",
        fg_border = plt.predator_core,
        bg_border = plt.predator_core,
        bg = plt.predator_core,
        bg_sel = plt.savanna_night,
        bg_sbar = plt.predator_core,
        bg_thumb = plt.sunlit_spots,
      },

      float = {
        fg = plt.golden_fur,
        bg = plt.savanna_night,
        fg_border = plt.predator_core,
        bg_border = plt.savanna_night,
      },
    },

    accent = {
      accent1 = plt.cheetah_gold,
      accent2 = plt.claw_red,
      accent3 = plt.emerald_eyes,
      accent4 = plt.urzkartaga_green,
      accent5 = plt.hunt_rage,
      invert = plt.predator_core,
    },

    rainbow = {
      rainbow1 = plt.cheetah_gold,
      rainbow2 = plt.sunlit_spots,
      rainbow3 = plt.predator_gold,
      rainbow4 = plt.emerald_eyes,
      rainbow5 = plt.venom_vines,
      rainbow6 = plt.claw_red,
      rainbow7 = plt.hunt_rage,
    },

    syn = {
      attribute = plt.golden_fur,
      boolean = plt.fresh_blood,
      comment = plt.moon_dust,
      constant = plt.amber_glow,
      deprecated = plt.moonlit_grass,
      func = plt.cheetah_gold,
      identifier = plt.golden_fur,
      keyword = plt.cheetah_gold,
      method = plt.sunlit_spots,
      number = plt.predator_gold,
      operator = plt.emerald_eyes,
      parameter = plt.moon_dust,
      preproc = plt.claw_red,
      punct = plt.sunlit_spots,
      regex = plt.venom_vines,
      statement = plt.cheetah_gold,
      string = plt.savanna_teal,
      symbol = plt.golden_fur,
      type = plt.emerald_eyes,
      variable = plt.golden_fur,
      special = plt.hunt_rage,
      special2 = plt.urzkartaga_green,
      special3 = plt.claw_red,
    },

    vcs = { added = plt.venom_vines, removed = plt.fresh_blood, changed = plt.sunlit_spots },
    diff = { add = plt.venom_vines, change = plt.emerald_eyes, delete = plt.claw_red, text = plt.predator_gold },
    diag = {
      ok = plt.venom_vines,
      error = plt.claw_red,
      warning = plt.predator_gold,
      info = plt.cheetah_gold,
      hint = plt.emerald_eyes,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_purple,
      cyan = plt.term_cyan,
      white = plt.golden_fur,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_purple_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.cheetah_gold,
      indexed2 = plt.claw_red,
    },

    treesitter = {
      ["@comment"] = plt.moon_dust,
      ["@comment.documentation"] = plt.amber_glow,
      ["@comment.error"] = plt.claw_red,
      ["@comment.warning"] = plt.predator_gold,
      ["@comment.todo"] = plt.cheetah_gold,
      ["@comment.note"] = plt.emerald_eyes,

      ["@constant"] = plt.amber_glow,
      ["@constant.builtin"] = plt.amber_glow,
      ["@constant.macro"] = plt.predator_gold,

      ["@string"] = plt.savanna_teal,
      ["@string.documentation"] = plt.savanna_teal,
      ["@string.regex"] = plt.venom_vines,
      ["@string.escape"] = plt.emerald_eyes,
      ["@string.special"] = plt.claw_red,
      ["@string.special.symbol"] = plt.golden_fur,
      ["@string.special.url"] = plt.cheetah_gold,
      ["@string.special.path"] = plt.savanna_teal,

      ["@character"] = plt.savanna_teal,
      ["@character.special"] = plt.emerald_eyes,

      ["@number"] = plt.predator_gold,
      ["@number.float"] = plt.predator_gold,

      ["@boolean"] = plt.claw_red,

      ["@function"] = plt.cheetah_gold,
      ["@function.builtin"] = plt.cheetah_gold,
      ["@function.call"] = plt.cheetah_gold,
      ["@function.macro"] = plt.sunlit_spots,
      ["@function.method"] = plt.sunlit_spots,
      ["@function.method.call"] = plt.sunlit_spots,

      ["@constructor"] = plt.golden_fur,

      ["@parameter"] = plt.moon_dust,
      ["@parameter.builtin"] = plt.golden_fur,

      ["@keyword"] = plt.cheetah_gold,
      ["@keyword.coroutine"] = plt.claw_red,
      ["@keyword.function"] = plt.cheetah_gold,
      ["@keyword.operator"] = plt.emerald_eyes,
      ["@keyword.return"] = plt.cheetah_gold,
      ["@keyword.import"] = plt.venom_vines,
      ["@keyword.storage"] = plt.cheetah_gold,
      ["@keyword.repeat"] = plt.cheetah_gold,
      ["@keyword.conditional"] = plt.cheetah_gold,
      ["@keyword.exception"] = plt.hunt_rage,
      ["@keyword.directive"] = plt.fresh_blood,
      ["@keyword.directive.define"] = plt.fresh_blood,

      ["@conditional"] = plt.cheetah_gold,
      ["@conditional.ternary"] = plt.cheetah_gold,

      ["@repeat"] = plt.cheetah_gold,

      ["@label"] = plt.sunlit_spots,

      ["@operator"] = plt.emerald_eyes,

      ["@exception"] = plt.hunt_rage,

      ["@variable"] = plt.golden_fur,
      ["@variable.builtin"] = plt.amber_glow,
      ["@variable.parameter"] = plt.moon_dust,
      ["@variable.member"] = plt.golden_fur,

      ["@type"] = plt.emerald_eyes,
      ["@type.builtin"] = plt.emerald_eyes,
      ["@type.definition"] = plt.emerald_eyes,
      ["@type.qualifier"] = plt.cheetah_gold,

      ["@attribute"] = plt.golden_fur,
      ["@attribute.builtin"] = plt.emerald_eyes,

      ["@property"] = plt.golden_fur,
      ["@field"] = plt.golden_fur,
      ["@module"] = plt.golden_fur,
      ["@module.builtin"] = plt.golden_fur,
      ["@namespace"] = plt.golden_fur,
      ["@namespace.builtin"] = plt.golden_fur,

      ["@punctuation.delimiter"] = plt.sunlit_spots,
      ["@punctuation.bracket"] = plt.amber_glow,
      ["@punctuation.special"] = plt.emerald_eyes,

      ["@tag"] = plt.cheetah_gold,
      ["@tag.attribute"] = plt.emerald_eyes,
      ["@tag.delimiter"] = plt.sunlit_spots,
      ["@tag.builtin"] = plt.cheetah_gold,

      ["@markup.strong"] = { fg = plt.cheetah_gold, bold = true },
      ["@markup.italic"] = { fg = plt.golden_fur, italic = true },
      ["@markup.strikethrough"] = { fg = plt.moonlit_grass, strikethrough = true },
      ["@markup.underline"] = { fg = plt.claw_red, underline = true },
      ["@markup.heading"] = plt.cheetah_gold,
      ["@markup.heading.1"] = plt.cheetah_gold,
      ["@markup.heading.2"] = plt.sunlit_spots,
      ["@markup.heading.3"] = plt.predator_gold,
      ["@markup.heading.4"] = plt.emerald_eyes,
      ["@markup.heading.5"] = plt.venom_vines,
      ["@markup.heading.6"] = plt.claw_red,
      ["@markup.quote"] = plt.moon_dust,
      ["@markup.math"] = plt.predator_gold,
      ["@markup.link"] = plt.emerald_eyes,
      ["@markup.link.label"] = plt.hunt_rage,
      ["@markup.link.url"] = plt.cheetah_gold,
      ["@markup.raw"] = plt.savanna_teal,
      ["@markup.raw.block"] = plt.savanna_teal,
      ["@markup.list"] = plt.cheetah_gold,
      ["@markup.list.checked"] = plt.venom_vines,
      ["@markup.list.unchecked"] = plt.moon_dust,

      ["@diff.plus"] = plt.venom_vines,
      ["@diff.minus"] = plt.claw_red,
      ["@diff.delta"] = plt.emerald_eyes,

      ["@none"] = "none",
      ["@conceal"] = plt.sunlit_spots,
      ["@spell"] = plt.golden_fur,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.golden_fur,
      ["@constructor.python"] = plt.cheetah_gold,
      ["@constructor.javascript"] = plt.cheetah_gold,
      ["@constructor.typescript"] = plt.cheetah_gold,
      ["@namespace.rust"] = plt.golden_fur,
      ["@type.qualifier.rust"] = plt.cheetah_gold,
      ["@constant.macro.c"] = plt.predator_gold,
      ["@constant.macro.cpp"] = plt.predator_gold,
      ["@namespace.go"] = plt.golden_fur,
      ["@property.css"] = plt.sunlit_spots,
      ["@type.css"] = plt.cheetah_gold,
      ["@label.json"] = plt.golden_fur,
      ["@field.yaml"] = plt.moon_dust,
      ["@property.toml"] = plt.moon_dust,
      ["@function.builtin.bash"] = plt.sunlit_spots,
      ["@string.regexp"] = plt.venom_vines,
      ["@character.special.regex"] = plt.emerald_eyes,
    },

    lsp = {
      ["@lsp.type.class"] = plt.emerald_eyes,
      ["@lsp.type.interface"] = plt.emerald_eyes,
      ["@lsp.type.struct"] = plt.emerald_eyes,
      ["@lsp.type.enum"] = plt.emerald_eyes,
      ["@lsp.type.enumMember"] = plt.amber_glow,
      ["@lsp.type.property"] = plt.golden_fur,
      ["@lsp.type.namespace"] = plt.golden_fur,

      ["@lsp.type.macro"] = plt.predator_gold,
      ["@lsp.type.decorator"] = plt.cheetah_gold,

      ["@lsp.type.builtinType"] = plt.emerald_eyes,
      ["@lsp.type.selfParameter"] = plt.cheetah_gold,
      ["@lsp.type.typeParameter"] = plt.emerald_eyes,

      ["@lsp.type.array"] = plt.emerald_eyes,
      ["@lsp.type.object"] = plt.emerald_eyes,
      ["@lsp.type.key"] = plt.golden_fur,
      ["@lsp.type.null"] = plt.amber_glow,
      ["@lsp.type.enumConstant"] = plt.amber_glow,

      ["@lsp.type.event"] = plt.emerald_eyes,
      ["@lsp.type.regexp"] = plt.venom_vines,
      ["@lsp.type.unresolvedReference"] = plt.claw_red,

      ["@lsp.mod.deprecated"] = { fg = plt.moonlit_grass, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.amber_glow,
      ["@lsp.mod.async"] = plt.cheetah_gold,
      ["@lsp.mod.static"] = plt.emerald_eyes,
      ["@lsp.mod.abstract"] = plt.emerald_eyes,
      ["@lsp.mod.defaultLibrary"] = plt.emerald_eyes,
      ["@lsp.mod.documentation"] = plt.moon_dust,
    },
  }
end

return {
  name = "Cheetah – Primal Goddess",
  author = "PrismPunk.nvim",
  description = "She was a woman once. Now she is the hunt. Golden fur under moonlight, "
    .. "cursed emerald eyes, and the endless hunger of Urzkartaga.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.savanna_night,
    base02 = palette.predator_core,
    base03 = palette.moonlit_grass,
    base04 = palette.moon_dust,
    base05 = palette.amber_glow,
    base06 = palette.golden_fur,
    base07 = palette.golden_fur,
    base08 = palette.claw_red,
    base09 = palette.predator_gold,
    base0A = palette.cheetah_gold,
    base0B = palette.emerald_eyes,
    base0C = palette.venom_vines,
    base0D = palette.savanna_teal,
    base0E = palette.hunt_rage,
    base0F = palette.fresh_blood,
  },

  palette = palette,
  get = M.get,
}
