local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0C080A",
  titan_void = "#110D14",
  colossal_core = "#181222",
  atomic_glow = "#221833",
  titan_orange = "#FF6611",
  colossal_orange = "#FF8833",
  magma_skin = "#FFAA55",
  eruption_glow = "#FFCC88",
  atomic_heat = "#FF4400",
  atomic_red = "#FF1122",
  inferno_red = "#FF3333",
  titan_rage = "#FF5555",
  volcano_hair = "#FF7766",
  titan_purple = "#AA22FF",
  colossal_violet = "#BB44FF",
  strength_pulse = "#CC66FF",
  royal_violence = "#DD88FF",
  titan_blue = "#2277FF",
  arctic_fury = "#4499FF",
  glacial_gaze = "#66BBFF",
  rubble_grey = "#666677",
  crushed_stone = "#888899",
  earthquake_dust = "#444455",
  term_red = "#FF3333",
  term_orange = "#FF8833",
  term_purple = "#BB44FF",
  term_blue = "#4499FF",
  term_green = "#44CC88",
  term_yellow = "#FFDD66",
  term_cyan = "#66CCFF",
  term_red_bright = "#FF6666",
  term_orange_bright = "#FFAA77",
  term_purple_bright = "#DD77FF",
  term_blue_bright = "#77BBFF",
  term_green_bright = "#66EEAA",
  term_yellow_bright = "#FFEE99",

  bg_darkest = "#0C080A",
  fg_lightest = "#FFEE99",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.titan_orange,
      insert = plt.atomic_red,
      visual = plt.titan_purple,
      replace = plt.inferno_red,
      command = plt.titan_blue,
    },

    ui = {
      fg = plt.magma_skin,
      fg_dim = plt.eruption_glow,
      fg_dimmer = plt.colossal_orange,
      fg_dark = plt.titan_purple,
      fg_reverse = plt.void_black,

      bg_m4 = plt.atomic_glow,
      bg_m3 = plt.colossal_core,
      bg_m2 = plt.titan_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.titan_void,
      bg_p2 = plt.colossal_core,
      bg_gutter = opts.gutter and plt.colossal_core or "none",
      bg_cursorline = plt.colossal_core,
      bg_cursorline_alt = plt.titan_void,
      bg_search = plt.volcano_hair,
      bg_visual = plt.atomic_red,
      bg_statusline = plt.colossal_core,

      border = plt.eruption_glow,
      header1 = plt.titan_orange,
      header2 = plt.atomic_red,
      special = plt.titan_purple,
      nontext = plt.titan_void,
      whitespace = plt.atomic_glow,
      win_separator = plt.eruption_glow,
      indent = plt.titan_void,
      indent_scope = plt.colossal_orange,
      picker = plt.magma_skin,
      yank = plt.titan_rage,
      mark = plt.inferno_red,
      scrollbar = plt.colossal_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.magma_skin,
        bg_selected = plt.colossal_core,
        fg_inactive = plt.colossal_orange,
        bg_inactive = plt.void_black,
        fg_alternate = plt.titan_orange,
        bg_alternate = plt.void_black,
        indicator = plt.atomic_red,
      },

      pmenu = {
        fg = plt.magma_skin,
        fg_sel = "none",
        fg_border = plt.colossal_core,
        bg_border = plt.colossal_core,
        bg = plt.colossal_core,
        bg_sel = plt.titan_void,
        bg_sbar = plt.colossal_core,
        bg_thumb = plt.eruption_glow,
      },

      float = {
        fg = plt.magma_skin,
        bg = plt.titan_void,
        fg_border = plt.colossal_core,
        bg_border = plt.titan_void,
      },
    },

    accent = {
      accent1 = plt.titan_orange,
      accent2 = plt.atomic_red,
      accent3 = plt.titan_purple,
      accent4 = plt.titan_blue,
      accent5 = plt.strength_pulse,
      invert = plt.colossal_core,
    },

    rainbow = {
      rainbow1 = plt.titan_orange,
      rainbow2 = plt.colossal_orange,
      rainbow3 = plt.magma_skin,
      rainbow4 = plt.atomic_red,
      rainbow5 = plt.titan_purple,
      rainbow6 = plt.titan_blue,
      rainbow7 = plt.glacial_gaze,
    },

    syn = {
      attribute = plt.magma_skin,
      boolean = plt.inferno_red,
      comment = plt.crushed_stone,
      constant = plt.eruption_glow,
      deprecated = plt.atomic_glow,
      func = plt.titan_orange,
      identifier = plt.magma_skin,
      keyword = plt.titan_orange,
      method = plt.colossal_orange,
      number = plt.volcano_hair,
      operator = plt.titan_purple,
      parameter = plt.crushed_stone,
      preproc = plt.atomic_red,
      punct = plt.eruption_glow,
      regex = plt.strength_pulse,
      statement = plt.titan_orange,
      string = plt.arctic_fury,
      symbol = plt.magma_skin,
      type = plt.titan_purple,
      variable = plt.magma_skin,
      special = plt.titan_rage,
      special2 = plt.titan_blue,
      special3 = plt.inferno_red,
    },

    vcs = { added = plt.arctic_fury, removed = plt.inferno_red, changed = plt.titan_purple },
    diff = { add = plt.arctic_fury, change = plt.titan_blue, delete = plt.atomic_red, text = plt.volcano_hair },
    diag = {
      ok = plt.arctic_fury,
      error = plt.inferno_red,
      warning = plt.titan_orange,
      info = plt.titan_purple,
      hint = plt.colossal_orange,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_orange,
      blue = plt.term_blue,
      magenta = plt.term_purple,
      cyan = plt.term_cyan,
      white = plt.magma_skin,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_orange_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_purple_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.titan_orange,
      indexed2 = plt.atomic_red,
    },

    treesitter = {
      ["@comment"] = plt.crushed_stone,
      ["@comment.documentation"] = plt.eruption_glow,
      ["@comment.error"] = plt.inferno_red,
      ["@comment.warning"] = plt.titan_orange,
      ["@comment.todo"] = plt.titan_purple,
      ["@comment.note"] = plt.arctic_fury,

      ["@constant"] = plt.eruption_glow,
      ["@constant.builtin"] = plt.eruption_glow,
      ["@constant.macro"] = plt.volcano_hair,

      ["@string"] = plt.arctic_fury,
      ["@string.documentation"] = plt.arctic_fury,
      ["@string.regex"] = plt.strength_pulse,
      ["@string.escape"] = plt.titan_purple,
      ["@string.special"] = plt.inferno_red,
      ["@string.special.symbol"] = plt.magma_skin,
      ["@string.special.url"] = plt.titan_blue,
      ["@string.special.path"] = plt.arctic_fury,

      ["@character"] = plt.arctic_fury,
      ["@character.special"] = plt.titan_purple,

      ["@number"] = plt.volcano_hair,
      ["@number.float"] = plt.volcano_hair,

      ["@boolean"] = plt.inferno_red,

      ["@function"] = plt.titan_orange,
      ["@function.builtin"] = plt.titan_orange,
      ["@function.call"] = plt.titan_orange,
      ["@function.macro"] = plt.colossal_orange,
      ["@function.method"] = plt.colossal_orange,
      ["@function.method.call"] = plt.colossal_orange,

      ["@constructor"] = plt.magma_skin,

      ["@parameter"] = plt.crushed_stone,
      ["@parameter.builtin"] = plt.magma_skin,

      ["@keyword"] = plt.titan_orange,
      ["@keyword.coroutine"] = plt.inferno_red,
      ["@keyword.function"] = plt.titan_orange,
      ["@keyword.operator"] = plt.titan_purple,
      ["@keyword.return"] = plt.titan_orange,
      ["@keyword.import"] = plt.arctic_fury,
      ["@keyword.storage"] = plt.titan_orange,
      ["@keyword.repeat"] = plt.titan_orange,
      ["@keyword.conditional"] = plt.titan_orange,
      ["@keyword.exception"] = plt.titan_rage,
      ["@keyword.directive"] = plt.atomic_red,
      ["@keyword.directive.define"] = plt.atomic_red,

      ["@conditional"] = plt.titan_orange,
      ["@conditional.ternary"] = plt.titan_orange,

      ["@repeat"] = plt.titan_orange,

      ["@label"] = plt.colossal_orange,

      ["@operator"] = plt.titan_purple,

      ["@exception"] = plt.titan_rage,

      ["@variable"] = plt.magma_skin,
      ["@variable.builtin"] = plt.eruption_glow,
      ["@variable.parameter"] = plt.crushed_stone,
      ["@variable.member"] = plt.magma_skin,

      ["@type"] = plt.titan_purple,
      ["@type.builtin"] = plt.titan_purple,
      ["@type.definition"] = plt.titan_purple,
      ["@type.qualifier"] = plt.titan_orange,

      ["@attribute"] = plt.magma_skin,
      ["@attribute.builtin"] = plt.titan_purple,

      ["@property"] = plt.magma_skin,
      ["@field"] = plt.magma_skin,
      ["@module"] = plt.magma_skin,
      ["@module.builtin"] = plt.magma_skin,
      ["@namespace"] = plt.magma_skin,
      ["@namespace.builtin"] = plt.magma_skin,

      ["@punctuation.delimiter"] = plt.eruption_glow,
      ["@punctuation.bracket"] = plt.colossal_orange,
      ["@punctuation.special"] = plt.titan_purple,

      ["@tag"] = plt.titan_orange,
      ["@tag.attribute"] = plt.titan_purple,
      ["@tag.delimiter"] = plt.eruption_glow,
      ["@tag.builtin"] = plt.titan_orange,

      ["@markup.strong"] = { fg = plt.titan_orange, bold = true },
      ["@markup.italic"] = { fg = plt.magma_skin, italic = true },
      ["@markup.strikethrough"] = { fg = plt.atomic_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.inferno_red, underline = true },
      ["@markup.heading"] = plt.titan_orange,
      ["@markup.heading.1"] = plt.titan_orange,
      ["@markup.heading.2"] = plt.colossal_orange,
      ["@markup.heading.3"] = plt.magma_skin,
      ["@markup.heading.4"] = plt.titan_purple,
      ["@markup.heading.5"] = plt.titan_blue,
      ["@markup.heading.6"] = plt.inferno_red,
      ["@markup.quote"] = plt.crushed_stone,
      ["@markup.math"] = plt.volcano_hair,
      ["@markup.link"] = plt.titan_blue,
      ["@markup.link.label"] = plt.titan_rage,
      ["@markup.link.url"] = plt.titan_purple,
      ["@markup.raw"] = plt.arctic_fury,
      ["@markup.raw.block"] = plt.arctic_fury,
      ["@markup.list"] = plt.titan_orange,
      ["@markup.list.checked"] = plt.arctic_fury,
      ["@markup.list.unchecked"] = plt.crushed_stone,

      ["@diff.plus"] = plt.arctic_fury,
      ["@diff.minus"] = plt.inferno_red,
      ["@diff.delta"] = plt.titan_purple,

      ["@none"] = "none",
      ["@conceal"] = plt.eruption_glow,
      ["@spell"] = plt.magma_skin,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.magma_skin,
      ["@constructor.python"] = plt.titan_orange,
      ["@constructor.javascript"] = plt.titan_orange,
      ["@constructor.typescript"] = plt.titan_orange,
      ["@namespace.rust"] = plt.magma_skin,
      ["@type.qualifier.rust"] = plt.titan_orange,
      ["@constant.macro.c"] = plt.volcano_hair,
      ["@constant.macro.cpp"] = plt.volcano_hair,
      ["@namespace.go"] = plt.magma_skin,
      ["@property.css"] = plt.colossal_orange,
      ["@type.css"] = plt.titan_orange,
      ["@label.json"] = plt.magma_skin,
      ["@field.yaml"] = plt.crushed_stone,
      ["@property.toml"] = plt.crushed_stone,
      ["@function.builtin.bash"] = plt.colossal_orange,
      ["@string.regexp"] = plt.strength_pulse,
      ["@character.special.regex"] = plt.titan_purple,
    },

    lsp = {
      ["@lsp.type.class"] = plt.titan_purple,
      ["@lsp.type.interface"] = plt.titan_purple,
      ["@lsp.type.struct"] = plt.titan_purple,
      ["@lsp.type.enum"] = plt.titan_purple,
      ["@lsp.type.enumMember"] = plt.eruption_glow,
      ["@lsp.type.property"] = plt.magma_skin,
      ["@lsp.type.namespace"] = plt.magma_skin,

      ["@lsp.type.macro"] = plt.volcano_hair,
      ["@lsp.type.decorator"] = plt.titan_orange,

      ["@lsp.type.builtinType"] = plt.titan_purple,
      ["@lsp.type.selfParameter"] = plt.titan_orange,
      ["@lsp.type.typeParameter"] = plt.titan_purple,

      ["@lsp.type.array"] = plt.titan_purple,
      ["@lsp.type.object"] = plt.titan_purple,
      ["@lsp.type.key"] = plt.magma_skin,
      ["@lsp.type.null"] = plt.eruption_glow,
      ["@lsp.type.enumConstant"] = plt.eruption_glow,

      ["@lsp.type.event"] = plt.titan_purple,
      ["@lsp.type.regexp"] = plt.strength_pulse,
      ["@lsp.type.unresolvedReference"] = plt.inferno_red,

      ["@lsp.mod.deprecated"] = { fg = plt.atomic_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.eruption_glow,
      ["@lsp.mod.async"] = plt.titan_orange,
      ["@lsp.mod.static"] = plt.titan_purple,
      ["@lsp.mod.abstract"] = plt.titan_purple,
      ["@lsp.mod.defaultLibrary"] = plt.titan_purple,
      ["@lsp.mod.documentation"] = plt.crushed_stone,
    },
  }
end

return {
  name = "Giganta – Colossal Queen",
  author = "PrismPunk.nvim",
  description = "She was small once. They laughed. Now cities tremble beneath her feet. "
    .. "Orange titan skin, atomic red hair, purple savage strength.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.titan_void,
    base02 = palette.colossal_core,
    base03 = palette.atomic_glow,
    base04 = palette.crushed_stone,
    base05 = palette.eruption_glow,
    base06 = palette.magma_skin,
    base07 = palette.magma_skin,
    base08 = palette.inferno_red,
    base09 = palette.titan_orange,
    base0A = palette.colossal_orange,
    base0B = palette.titan_blue,
    base0C = palette.titan_purple,
    base0D = palette.strength_pulse,
    base0E = palette.volcano_hair,
    base0F = palette.atomic_red,
  },

  palette = palette,
  get = M.get,
}
