local color = require("prismpunk.utils.color")

local palette = {
  abyss_black = "#0B0011",
  chemical_void = "#12001A",
  madness_shadow = "#1A0026",
  grin_core = "#250038",
  dead_skin = "#C8C8D4",
  sick_flesh = "#A8A8C0",
  grin_purple = "#BB88FF",
  psycho_royal = "#DD99FF",
  acid_green = "#00FF44",
  toxic_lime = "#44FF88",
  chemical_burn = "#88FFAA",
  joker_venom = "#AAFFC3",
  arterial_red = "#FF0033",
  lipstick_red = "#FF2255",
  murder_red = "#FF4466",
  chaos_red = "#FF6688",
  grin_yellow = "#FFFF44",
  fever_dream = "#FFFF88",
  broken_mind = "#FFFFBB",
  purple_suit = "#8800FF",
  violet_chaos = "#AA33FF",
  ultraviolet = "#CC66FF",
  laughing_gas = "#FF00CC",
  punchline_pink = "#FF44FF",
  bat_break = "#FF88FF",
  term_red = "#FF0033",
  term_green = "#00FF44",
  term_blue = "#8800FF",
  term_yellow = "#FFFF44",
  term_cyan = "#00FFCC",
  term_magenta = "#FF00CC",
  term_red_bright = "#FF4488",
  term_green_bright = "#88FFBB",
  term_yellow_bright = "#FFFF99",
  term_blue_bright = "#BB88FF",
  term_magenta_bright = "#FF88FF",
  term_cyan_bright = "#88FFFF",

  bg_darkest = "#0B0011",
  fg_lightest = "#FFFF99",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.acid_green,
      insert = plt.purple_suit,
      visual = plt.arterial_red,
      replace = plt.lipstick_red,
      command = plt.grin_yellow,
    },

    ui = {
      fg = plt.dead_skin,
      fg_dim = plt.psycho_royal,
      fg_dimmer = plt.grin_purple,
      fg_dark = plt.sick_flesh,
      fg_reverse = plt.abyss_black,

      bg_m4 = plt.grin_core,
      bg_m3 = plt.madness_shadow,
      bg_m2 = plt.chemical_void,
      bg_m1 = plt.abyss_black,
      bg_dim = plt.abyss_black,
      bg = plt.abyss_black,
      bg_p1 = plt.chemical_void,
      bg_p2 = plt.madness_shadow,
      bg_gutter = opts.gutter and plt.madness_shadow or "none",
      bg_cursorline = plt.madness_shadow,
      bg_cursorline_alt = plt.chemical_void,
      bg_search = plt.grin_yellow,
      bg_visual = plt.arterial_red,
      bg_statusline = plt.madness_shadow,

      border = plt.acid_green,
      header1 = plt.grin_yellow,
      header2 = plt.purple_suit,
      special = plt.laughing_gas,
      nontext = plt.chemical_void,
      whitespace = plt.grin_core,
      win_separator = plt.acid_green,
      indent = plt.chemical_void,
      indent_scope = plt.dead_skin,
      picker = plt.toxic_lime,
      yank = plt.fever_dream,
      mark = plt.murder_red,
      scrollbar = plt.madness_shadow,

      tabline = {
        bg = plt.abyss_black,
        fg_selected = plt.grin_yellow,
        bg_selected = plt.madness_shadow,
        fg_inactive = plt.grin_purple,
        bg_inactive = plt.abyss_black,
        fg_alternate = plt.acid_green,
        bg_alternate = plt.abyss_black,
        indicator = plt.lipstick_red,
      },

      pmenu = {
        fg = plt.dead_skin,
        fg_sel = "none",
        fg_border = plt.madness_shadow,
        bg_border = plt.madness_shadow,
        bg = plt.madness_shadow,
        bg_sel = plt.chemical_void,
        bg_sbar = plt.madness_shadow,
        bg_thumb = plt.grin_yellow,
      },

      float = {
        fg = plt.dead_skin,
        bg = plt.chemical_void,
        fg_border = plt.madness_shadow,
        bg_border = plt.chemical_void,
      },
    },

    accent = {
      accent1 = plt.grin_yellow,
      accent2 = plt.acid_green,
      accent3 = plt.purple_suit,
      accent4 = plt.lipstick_red,
      accent5 = plt.laughing_gas,
      invert = plt.madness_shadow,
    },

    rainbow = {
      rainbow1 = plt.acid_green,
      rainbow2 = plt.toxic_lime,
      rainbow3 = plt.grin_yellow,
      rainbow4 = plt.purple_suit,
      rainbow5 = plt.violet_chaos,
      rainbow6 = plt.lipstick_red,
      rainbow7 = plt.laughing_gas,
    },

    syn = {
      attribute = plt.dead_skin,
      boolean = plt.arterial_red,
      comment = plt.grin_purple,
      constant = plt.chemical_burn,
      deprecated = plt.grin_core,
      func = plt.toxic_lime,
      identifier = plt.dead_skin,
      keyword = plt.grin_yellow,
      method = plt.ultraviolet,
      number = plt.fever_dream,
      operator = plt.lipstick_red,
      parameter = plt.psycho_royal,
      preproc = plt.punchline_pink,
      punct = plt.grin_purple,
      regex = plt.laughing_gas,
      statement = plt.grin_yellow,
      string = plt.acid_green,
      symbol = plt.dead_skin,
      type = plt.fever_dream,
      variable = plt.dead_skin,
      special = plt.toxic_lime,
      special2 = plt.lipstick_red,
      special3 = plt.bat_break,
    },

    vcs = { added = plt.acid_green, removed = plt.arterial_red, changed = plt.grin_yellow },
    diff = { add = plt.acid_green, change = plt.violet_chaos, delete = plt.arterial_red, text = plt.chemical_burn },
    diag = {
      ok = plt.toxic_lime,
      error = plt.arterial_red,
      warning = plt.grin_yellow,
      info = plt.ultraviolet,
      hint = plt.punchline_pink,
    },

    term = {
      black = plt.abyss_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_magenta,
      cyan = plt.term_cyan,
      white = plt.dead_skin,

      black_bright = color(plt.abyss_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_magenta_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.grin_yellow,
      indexed2 = plt.acid_green,
    },

    treesitter = {
      ["@comment"] = plt.grin_purple,
      ["@comment.documentation"] = plt.psycho_royal,
      ["@comment.error"] = plt.arterial_red,
      ["@comment.warning"] = plt.grin_yellow,
      ["@comment.todo"] = plt.acid_green,
      ["@comment.note"] = plt.toxic_lime,

      ["@constant"] = plt.chemical_burn,
      ["@constant.builtin"] = plt.chemical_burn,
      ["@constant.macro"] = plt.broken_mind,

      ["@string"] = plt.acid_green,
      ["@string.documentation"] = plt.acid_green,
      ["@string.regex"] = plt.laughing_gas,
      ["@string.escape"] = plt.murder_red,
      ["@string.special"] = plt.lipstick_red,
      ["@string.special.symbol"] = plt.grin_yellow,
      ["@string.special.url"] = plt.bat_break,
      ["@string.special.path"] = plt.acid_green,

      ["@character"] = plt.acid_green,
      ["@character.special"] = plt.murder_red,

      ["@number"] = plt.fever_dream,
      ["@number.float"] = plt.fever_dream,

      ["@boolean"] = plt.arterial_red,

      ["@function"] = plt.toxic_lime,
      ["@function.builtin"] = plt.toxic_lime,
      ["@function.call"] = plt.toxic_lime,
      ["@function.macro"] = plt.ultraviolet,
      ["@function.method"] = plt.ultraviolet,
      ["@function.method.call"] = plt.ultraviolet,

      ["@constructor"] = plt.grin_yellow,

      ["@parameter"] = plt.psycho_royal,
      ["@parameter.builtin"] = plt.dead_skin,

      ["@keyword"] = plt.grin_yellow,
      ["@keyword.coroutine"] = plt.lipstick_red,
      ["@keyword.function"] = plt.grin_yellow,
      ["@keyword.operator"] = plt.laughing_gas,
      ["@keyword.return"] = plt.grin_yellow,
      ["@keyword.import"] = plt.toxic_lime,
      ["@keyword.storage"] = plt.grin_yellow,
      ["@keyword.repeat"] = plt.grin_yellow,
      ["@keyword.conditional"] = plt.grin_yellow,
      ["@keyword.exception"] = plt.arterial_red,
      ["@keyword.directive"] = plt.fever_dream,
      ["@keyword.directive.define"] = plt.fever_dream,

      ["@conditional"] = plt.grin_yellow,
      ["@conditional.ternary"] = plt.grin_yellow,

      ["@repeat"] = plt.grin_yellow,

      ["@label"] = plt.toxic_lime,

      ["@operator"] = plt.laughing_gas,

      ["@exception"] = plt.arterial_red,

      ["@variable"] = plt.dead_skin,
      ["@variable.builtin"] = plt.grin_yellow,
      ["@variable.parameter"] = plt.psycho_royal,
      ["@variable.member"] = plt.dead_skin,

      ["@type"] = plt.fever_dream,
      ["@type.builtin"] = plt.fever_dream,
      ["@type.definition"] = plt.fever_dream,
      ["@type.qualifier"] = plt.grin_yellow,

      ["@attribute"] = plt.dead_skin,
      ["@attribute.builtin"] = plt.fever_dream,

      ["@property"] = plt.dead_skin,
      ["@field"] = plt.dead_skin,
      ["@module"] = plt.dead_skin,
      ["@module.builtin"] = plt.dead_skin,
      ["@namespace"] = plt.dead_skin,
      ["@namespace.builtin"] = plt.dead_skin,

      ["@punctuation.delimiter"] = plt.grin_purple,
      ["@punctuation.bracket"] = plt.violet_chaos,
      ["@punctuation.special"] = plt.laughing_gas,

      ["@tag"] = plt.grin_yellow,
      ["@tag.attribute"] = plt.fever_dream,
      ["@tag.delimiter"] = plt.grin_purple,
      ["@tag.builtin"] = plt.grin_yellow,

      ["@markup.strong"] = { fg = plt.grin_yellow, bold = true },
      ["@markup.italic"] = { fg = plt.dead_skin, italic = true },
      ["@markup.strikethrough"] = { fg = plt.grin_core, strikethrough = true },
      ["@markup.underline"] = { fg = plt.acid_green, underline = true },
      ["@markup.heading"] = plt.grin_yellow,
      ["@markup.heading.1"] = plt.grin_yellow,
      ["@markup.heading.2"] = plt.acid_green,
      ["@markup.heading.3"] = plt.purple_suit,
      ["@markup.heading.4"] = plt.lipstick_red,
      ["@markup.heading.5"] = plt.laughing_gas,
      ["@markup.heading.6"] = plt.bat_break,
      ["@markup.quote"] = plt.grin_purple,
      ["@markup.math"] = plt.toxic_lime,
      ["@markup.link"] = plt.bat_break,
      ["@markup.link.label"] = plt.fever_dream,
      ["@markup.link.url"] = plt.laughing_gas,
      ["@markup.raw"] = plt.acid_green,
      ["@markup.raw.block"] = plt.acid_green,
      ["@markup.list"] = plt.grin_yellow,
      ["@markup.list.checked"] = plt.toxic_lime,
      ["@markup.list.unchecked"] = plt.grin_purple,

      ["@diff.plus"] = plt.acid_green,
      ["@diff.minus"] = plt.arterial_red,
      ["@diff.delta"] = plt.violet_chaos,

      ["@none"] = "none",
      ["@conceal"] = plt.chemical_burn,
      ["@spell"] = plt.dead_skin,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.dead_skin,
      ["@constructor.python"] = plt.grin_yellow,
      ["@constructor.javascript"] = plt.grin_yellow,
      ["@constructor.typescript"] = plt.grin_yellow,
      ["@namespace.rust"] = plt.dead_skin,
      ["@type.qualifier.rust"] = plt.grin_yellow,
      ["@constant.macro.c"] = plt.broken_mind,
      ["@constant.macro.cpp"] = plt.broken_mind,
      ["@namespace.go"] = plt.dead_skin,
      ["@property.css"] = plt.toxic_lime,
      ["@type.css"] = plt.grin_yellow,
      ["@label.json"] = plt.dead_skin,
      ["@field.yaml"] = plt.psycho_royal,
      ["@property.toml"] = plt.psycho_royal,
      ["@function.builtin.bash"] = plt.toxic_lime,
      ["@string.regexp"] = plt.laughing_gas,
      ["@character.special.regex"] = plt.punchline_pink,
    },

    lsp = {
      ["@lsp.type.class"] = plt.fever_dream,
      ["@lsp.type.interface"] = plt.fever_dream,
      ["@lsp.type.struct"] = plt.fever_dream,
      ["@lsp.type.enum"] = plt.fever_dream,
      ["@lsp.type.enumMember"] = plt.chemical_burn,
      ["@lsp.type.property"] = plt.dead_skin,
      ["@lsp.type.namespace"] = plt.dead_skin,

      ["@lsp.type.macro"] = plt.fever_dream,
      ["@lsp.type.decorator"] = plt.grin_yellow,

      ["@lsp.type.builtinType"] = plt.fever_dream,
      ["@lsp.type.selfParameter"] = plt.grin_yellow,
      ["@lsp.type.typeParameter"] = plt.fever_dream,

      ["@lsp.type.array"] = plt.fever_dream,
      ["@lsp.type.object"] = plt.fever_dream,
      ["@lsp.type.key"] = plt.dead_skin,
      ["@lsp.type.null"] = plt.chemical_burn,
      ["@lsp.type.enumConstant"] = plt.chemical_burn,

      ["@lsp.type.event"] = plt.fever_dream,
      ["@lsp.type.regexp"] = plt.laughing_gas,
      ["@lsp.type.unresolvedReference"] = plt.arterial_red,

      ["@lsp.mod.deprecated"] = { fg = plt.grin_core, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.chemical_burn,
      ["@lsp.mod.async"] = plt.grin_yellow,
      ["@lsp.mod.static"] = plt.fever_dream,
      ["@lsp.mod.abstract"] = plt.fever_dream,
      ["@lsp.mod.defaultLibrary"] = plt.fever_dream,
      ["@lsp.mod.documentation"] = plt.psycho_royal,
    },
  }
end

return {
  name = "Joker – Chaos Incarnate",
  author = "PrismPunk.nvim",
  description = "Not a clown. A walking punchline written in acid and blood. "
    .. "Sick green, psychotic purple, arterial red, and the yellow of a grin that never blinks. "
    .. "This theme is what happens when sanity dies laughing.",

  base16 = {
    base00 = palette.abyss_black,
    base01 = palette.chemical_void,
    base02 = palette.madness_shadow,
    base03 = palette.grin_core,
    base04 = palette.grin_purple,
    base05 = palette.psycho_royal,
    base06 = palette.sick_flesh,
    base07 = palette.dead_skin,
    base08 = palette.arterial_red,
    base09 = palette.grin_yellow,
    base0A = palette.acid_green,
    base0B = palette.toxic_lime,
    base0C = palette.laughing_gas,
    base0D = palette.purple_suit,
    base0E = palette.violet_chaos,
    base0F = palette.fever_dream,
  },

  palette = palette,
  get = M.get,
}
