local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1C1C1C",
  bg_darker = "#121212",
  bg_dark = "#303030",
  bg_mid = "#3C3836",
  bg_light = "#504945",
  bg_lighter = "#665C54",
  bg_lightest = "#7C6F64",
  fg_lightest = "#FBF1C7",
  fg_light = "#EBDBB2",
  fg_mid = "#D5C4A1",
  fg_dark = "#BDAE93",
  bg_alt1 = "#262626",
  bg_alt2 = "#0F0F0F",
  bg_alt3 = "#3A3836",
  bg_alt4 = "#000000",
  retroRed = "#FB5944",
  retroRedDark = "#CC241D",
  retroRedDeep = "#9D0006",
  retroGreen = "#B8BB26",
  retroGreenDark = "#98971A",
  retroGreenDeep = "#79740E",
  retroYellow = "#FABD2F",
  retroYellowDark = "#D79921",
  retroYellowDeep = "#B57614",
  retroBlue = "#83A598",
  retroBlueDark = "#458588",
  retroBlueDeep = "#076678",
  retroPurple = "#D3869B",
  retroPurpleDark = "#B16286",
  retroPurpleDeep = "#8F3F71",
  retroAqua = "#8EC07C",
  retroAquaDark = "#689D6A",
  retroAquaDeep = "#427B58",
  retroOrange = "#FE8019",
  retroOrangeDark = "#D65D0E",
  retroOrangeDeep = "#AF3A03",
  retroGray = "#928374",
  retroGrayDark = "#7C6F64",
  retroGrayDeep = "#504945",
  retroCream = "#EBDBB2",
  retroCreamLight = "#FBF1C7",
  retroCreamDark = "#D5C4A1",
  gruvboxBg = "#1C1C1C",
  gruvboxFg = "#EBDBB2",
  gruvboxRed = "#FB5944",
  gruvboxGreen = "#B8BB26",
  gruvboxYellow = "#FABD2F",
  gruvboxBlue = "#83A598",
  gruvboxPurple = "#D3869B",
  gruvboxAqua = "#8EC07C",
  gruvboxOrange = "#FE8019",
  gruvboxGray = "#928374",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.retroGray,
      insert = plt.retroGreen,
      visual = plt.retroBlue,
      replace = plt.retroRed,
      command = plt.retroYellow,
    },
    accent = {
      accent1 = plt.retroRed,
      accent2 = plt.retroGreen,
      accent3 = plt.retroYellow,
      accent4 = plt.retroBlue,
      accent5 = plt.retroAqua,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.retroRed,
      rainbow2 = plt.retroOrange,
      rainbow3 = plt.retroYellow,
      rainbow4 = plt.retroGreen,
      rainbow5 = plt.retroAqua,
      rainbow6 = plt.retroBlue,
      rainbow7 = plt.retroPurple,
    },
    ui = {
      fg = plt.fg_light,
      fg_dim = plt.fg_mid,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.retroGrayDark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.bg_alt3,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.retroGrayDeep,
      header1 = plt.retroYellow,
      header2 = plt.retroGreen,
      special = plt.retroOrange,
      nontext = plt.retroGrayDeep,
      whitespace = plt.retroGrayDark,
      win_separator = plt.bg_dark,
      indent = plt.bg_lighter,
      indent_scope = plt.retroGray,
      picker = plt.retroPurple,
      yank = plt.retroYellow,
      mark = plt.retroOrange,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_light,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.retroGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_light,
        fg_border = plt.retroGray,
        bg = plt.bg_mid,
        bg_sel = plt.bg_light,
        bg_border = plt.bg_mid,
        bg_sbar = plt.bg_mid,
        bg_thumb = plt.retroGrayDark,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_mid,
        bg_selected = plt.bg_darkest,
        bg_alternate = plt.bg_alt1,
        fg_inactive = plt.retroGray,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.retroYellow,
        indicator = plt.retroYellow,
      },
    },
    syn = {
      attribute = plt.retroYellow,
      boolean = plt.retroPurple,
      comment = plt.retroGray,
      constant = plt.retroPurple,
      deprecated = plt.retroGrayDeep,
      func = plt.retroGreen,
      identifier = plt.fg_light,
      keyword = plt.retroRed,
      method = plt.retroGreen,
      number = plt.retroPurple,
      operator = plt.retroAqua,
      parameter = plt.fg_mid,
      preproc = plt.retroAqua,
      punct = plt.fg_dark,
      regex = plt.retroOrange,
      special = plt.retroOrange,
      special2 = plt.retroBlue,
      special3 = plt.retroPurple,
      statement = plt.retroRed,
      string = plt.retroGreen,
      symbol = plt.retroYellow,
      type = plt.retroYellow,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.retroRed,
      warning = plt.retroOrange,
      info = plt.retroBlue,
      ok = plt.retroGreen,
      hint = plt.retroAqua,
      virtual_text_error = plt.retroRed,
      virtual_text_warning = plt.retroOrange,
      virtual_text_info = plt.retroBlue,
      virtual_text_ok = plt.retroGreen,
      virtual_text_hint = plt.retroAqua,
    },
    diff = {
      add = plt.retroGreen,
      add_inline = plt.retroGreenDeep,
      change = plt.retroYellow,
      change_inline = plt.retroYellowDeep,
      delete = plt.retroRed,
      delete_inline = plt.retroRedDeep,
      text = plt.retroBlue,
    },
    vcs = {
      added = plt.retroGreen,
      changed = plt.retroYellow,
      removed = plt.retroRed,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.retroRedDark,
      green = plt.retroGreenDark,
      yellow = plt.retroYellowDark,
      blue = plt.retroBlueDark,
      magenta = plt.retroPurpleDark,
      cyan = plt.retroAquaDark,
      white = plt.retroGray,
      black_bright = color(plt.retroGray):brighten(0.2):to_hex(),
      red_bright = color(plt.retroRed):brighten(0.2):to_hex(),
      green_bright = color(plt.retroGreen):brighten(0.2):to_hex(),
      yellow_bright = color(plt.retroYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.retroBlue):brighten(0.2):to_hex(),
      magenta_bright = color(plt.retroPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.retroAqua):brighten(0.2):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.retroOrange,
      indexed2 = plt.retroPurple,
    },
  }
end

return {
  name = "Retrobox",
  author = "PrismPunk.nvim (Original by Maxim Kim, ported from gruvbox)",
  description = "Retro groove color scheme with warm earthy tones.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.retroGray,
    base04 = palette.retroGrayDark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.retroRed,
    base09 = palette.retroOrange,
    base0A = palette.retroYellow,
    base0B = palette.retroGreen,
    base0C = palette.retroAqua,
    base0D = palette.retroBlue,
    base0E = palette.retroPurple,
    base0F = palette.retroOrangeDark,
  },
  palette = palette,
  get = M.get,
}
