local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0005",
  bg_darker = "#14000A",
  bg_dark = "#220014",
  bg_mid = "#2B001A",
  bg_light = "#3C1825",
  bg_lighter = "#4A2231",
  bg_lightest = "#5A2E3D",
  darkseid_stone = "#3C2F3F",
  tyrant_gray = "#5A485C",
  omega_rock = "#7A6A7F",
  imperial_silver = "#A090A5",
  fg_dark = "#5A485C",
  fg_mid = "#7A6A7F",
  fg_light = "#BBAEC0",
  fg_lightest = "#E4D8EC",
  apokolips_void = "#0A0005",
  scorched_depth = "#14000A",
  firepit_glow = "#220014",
  obsidian_core = "#2B001A",
  molten_red = "#FF2200",
  omega_beam = "#FF4444",
  blood_river = "#CC1122",
  firepit_orange = "#FF6600",
  lava_glow = "#FF8833",
  molten_red_deep = "#B31808",
  molten_red_bright = "#FF4A33",
  omega_beam_core = "#FF3333",
  blood_river_deep = "#990A18",
  firepit_orange_deep = "#CC4D00",
  firepit_orange_bright = "#FF9140",
  lava_glow_deep = "#CC6A29",
  lava_glow_bright = "#FFAD66",
  omega_cyan = "#00DDFF",
  beam_core = "#44EEFF",
  tyranny_blue = "#88CCFF",
  omega_cyan_deep = "#0099B3",
  omega_cyan_bright = "#66ECFF",
  beam_core_deep = "#25A5B5",
  beam_core_bright = "#79F2FF",
  tyranny_blue_deep = "#4F8BB3",
  tyranny_blue_bright = "#B3E0FF",
  apokoliptian_violet = "#7A4A8F",
  apokoliptian_violet_deep = "#593466",
  apokoliptian_violet_bright = "#A06BC0",
  hellsteel_ember = "#FF5522",
  hellsteel_ember_deep = "#C23C12",
  hellsteel_ember_bright = "#FF7A55",
  crackle_ash = "#66444F",
  pit_smoke = "#3F2933",
  ember_shadow = "#1A050C",
  term_red = "#FF4444",
  term_green = "#FF6600",
  term_blue = "#44EEFF",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.omega_beam,
      insert = plt.omega_cyan,
      visual = plt.firepit_orange,
      replace = plt.molten_red,
      command = plt.tyranny_blue,
    },
    accent = {
      accent1 = plt.omega_beam,
      accent2 = plt.firepit_orange,
      accent3 = plt.omega_cyan,
      accent4 = plt.tyranny_blue,
      accent5 = plt.apokoliptian_violet_bright,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.molten_red,
      rainbow2 = plt.omega_beam,
      rainbow3 = plt.firepit_orange,
      rainbow4 = plt.lava_glow,
      rainbow5 = plt.omega_cyan,
      rainbow6 = plt.beam_core,
      rainbow7 = plt.tyranny_blue,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darker,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_mid,
      bg_p2 = plt.bg_light,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.firepit_orange,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_dark,
      border = plt.omega_rock,
      header1 = plt.omega_beam,
      header2 = plt.tyranny_blue,
      special = plt.omega_cyan,
      nontext = plt.darkseid_stone,
      whitespace = plt.tyrant_gray,
      win_separator = plt.omega_rock,
      indent = plt.bg_light,
      indent_scope = plt.beam_core,
      picker = plt.apokoliptian_violet,
      yank = plt.lava_glow_bright,
      mark = plt.blood_river,
      scrollbar = plt.bg_lightest,
      selection = plt.bg_mid,
      line_nr = plt.tyrant_gray,
      line_nr_dim = plt.darkseid_stone,
      line_nr_active = plt.fg_lightest,
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.bg_darkest,
        fg_border = plt.omega_rock,
        bg = plt.bg_dark,
        bg_sel = plt.bg_mid,
        bg_border = plt.bg_dark,
        bg_sbar = plt.bg_dark,
        bg_thumb = plt.omega_rock,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.omega_rock,
        bg_border = plt.bg_darker,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.darkseid_stone,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.omega_beam,
        indicator = plt.omega_beam,
      },
    },
    syn = {
      attribute = plt.firepit_orange,
      boolean = plt.omega_beam,
      comment = plt.darkseid_stone,
      constant = plt.molten_red,
      deprecated = plt.crackle_ash,
      func = plt.beam_core,
      identifier = plt.fg_lightest,
      keyword = plt.omega_beam,
      method = plt.tyranny_blue,
      number = plt.lava_glow,
      operator = plt.omega_cyan,
      parameter = plt.omega_rock,
      preproc = plt.firepit_orange_deep,
      punct = plt.darkseid_stone,
      regex = plt.omega_cyan_deep,
      special = plt.lava_glow_bright,
      special2 = plt.tyranny_blue_bright,
      special3 = plt.apokoliptian_violet_bright,
      statement = plt.omega_beam_core,
      string = plt.firepit_orange,
      symbol = plt.molten_red_bright,
      type = plt.tyranny_blue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.blood_river,
      warning = plt.firepit_orange,
      info = plt.tyranny_blue,
      hint = plt.omega_cyan,
      ok = plt.lava_glow,
      virtual_text_error = plt.blood_river_deep,
      virtual_text_warning = plt.firepit_orange_deep,
      virtual_text_info = plt.tyranny_blue_deep,
      virtual_text_hint = plt.omega_cyan_deep,
      virtual_text_ok = plt.lava_glow_deep,
    },
    diff = {
      add = plt.firepit_orange,
      add_inline = plt.lava_glow_deep,
      change = plt.tyranny_blue,
      change_inline = plt.beam_core_deep,
      delete = plt.blood_river,
      delete_inline = plt.molten_red_deep,
      text = plt.omega_beam,
    },
    vcs = {
      added = plt.firepit_orange,
      changed = plt.tyranny_blue,
      removed = plt.blood_river,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.firepit_orange,
      blue = plt.term_blue,
      magenta = plt.omega_beam,
      cyan = plt.omega_cyan,
      white = plt.imperial_silver,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.term_red):brighten(0.2):to_hex(),
      green_bright = color(plt.term_green):brighten(0.2):to_hex(),
      yellow_bright = color(plt.firepit_orange):brighten(0.2):to_hex(),
      blue_bright = color(plt.term_blue):brighten(0.2):to_hex(),
      magenta_bright = color(plt.omega_beam):brighten(0.2):to_hex(),
      cyan_bright = color(plt.omega_cyan):brighten(0.2):to_hex(),
      white_bright = color(plt.imperial_silver):brighten(0.2):to_hex(),
      indexed1 = plt.blood_river,
      indexed2 = plt.tyranny_blue,
    },
  }
end

return {
  name = "Apokolips – Darkseid",
  author = "PrismPunk.nvim",
  description = "Omega-beam drenched dark theme from the fires of Apokolips.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.darkseid_stone,
    base04 = palette.omega_rock,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.molten_red,
    base09 = palette.firepit_orange,
    base0A = palette.lava_glow,
    base0B = palette.omega_cyan,
    base0C = palette.beam_core,
    base0D = palette.tyranny_blue,
    base0E = palette.omega_beam,
    base0F = palette.blood_river,
  },
  palette = palette,
  get = M.get,
}
