return {
  voidWhite = "#0F0F1A",
  abyssBlue = "#131325",
  deepHope = "#1A1A33",
  cosmicBlue = "#1F1F44",
  hopeCore = "#00EEFF",
  skyfireCyan = "#00DDFF",
  divineAzure = "#00CCFF",
  celestialGlow = "#00BBFF",
  starbirthBlue = "#00AAFF",
  angelFeather = "#CCFFFF",
  wingsOfDawn = "#E6F5FF",
  hopeRadiance = "#F0F8FF",
  pureLight = "#FFFFFF",
  etherealWhite = "#F8FAFF",
  sapphireTear = "#4488FF",
  miracleFlame = "#00FFCC",
  auroraVein = "#00FFAA",
  brokenChains = "#FFAA00",
  goldenPromise = "#FFDD00",
  term_red = "#FF3366",
  term_blue = "#0088FF",
  term_magenta = "#FF00FF",

  bg_darkest = "#1A1A33",
  fg_lightest = "#FFFFFF",
}

