return {
  life_void = "#0F1117",
  creation_black = "#171925",
  genesis_depth = "#222533",
  origin_core = "#2D3344",
  relic_white = "#FFFFFF",
  divine_radiance = "#F0F4FF",
  eternal_brill = "#E0E8FF",
  pure_lumen = "#D0DCFF",
  holy_glow = "#C0D0FF",
  prism_violet = "#E0D0FF",
  prism_indigo = "#D0DCFF",
  prism_blue = "#C0E8FF",
  prism_cyan = "#C0F0FF",
  prism_green = "#C8FFD8",
  prism_yellow = "#FFFFC0",
  prism_orange = "#FFE8C0",
  prism_red = "#FFD0D0",
  fallen_shadow = "#FF3366",
  term_red = "#FF6699",
  term_green = "#88FFCC",
  term_blue = "#88CCFF",

  bg_darkest = "#0F1117",
  fg_lightest = "#FFFFFF",
}

