local color = require("prismpunk.utils.color")

local palette = {
  hushVoid = "#000000",
  hushDark = "#0A0A0A",
  hushDeep = "#111111",
  hushMid = "#1A1A1A",
  hushLight = "#222222",
  hushShadow = "#151515",
  calmDeep = "#2B2B2B",
  calmMid = "#333333",
  calmLine = "#383838",
  calmRidge = "#3D3D3D",
  silenceDeep = "#404040",
  silenceMid = "#505050",
  silenceLight = "#606060",
  silenceBright = "#707070",
  silenceLighter = "#808080",
  silenceLightest = "#909090",
  silenceGlow = "#989898",
  clarityDim = "#A8A8A8",
  clarityCore = "#C0C0C0",
  clarityBright = "#E0E0E0",
  clarityPeak = "#F0F0F0",
  restoreDeep = "#113311",
  restoreMid = "#224422",
  restoreBright = "#335533",
  restorePulse = "#446644",
  restoreVivid = "#558855",
  mossDark = "#1A4A1A",
  mossLight = "#2A6A2A",
  mossSoft = "#356A35",
  phosphorMid = "#44CC44",
  phosphorGlow = "#66FF66",
  phosphorFlare = "#55EE55",
  glitchGreen = "#99FF99",
  glitchPale = "#AAFFAA",
  slateDark = "#1F1F1F",
  slateMid = "#282828",
  slateEcho = "#303030",
  staticWhite = "#BBBBBB",
  staticGray = "#CCCCCC",
  terminalFade = "#4A4A4A",
  scanlineGhost = "#1C1C1C",

  bg_darkest = "#000000",
  fg_lightest = "#AAFFAA",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.restoreMid,
      insert = plt.restoreBright,
      visual = plt.restorePulse,
      replace = plt.restoreDeep,
      command = plt.silenceBright,
    },
    accent = {
      accent1 = plt.restoreBright,
      accent2 = plt.restoreMid,
      accent3 = plt.restoreDeep,
      accent4 = plt.silenceBright,
      accent5 = plt.restorePulse,
      invert = plt.calmMid,
    },
    rainbow = {
      rainbow1 = plt.silenceBright,
      rainbow2 = plt.silenceLight,
      rainbow3 = plt.silenceMid,
      rainbow4 = plt.restoreDeep,
      rainbow5 = plt.restoreMid,
      rainbow6 = plt.restoreBright,
      rainbow7 = plt.restorePulse,
    },
    ui = {
      fg = plt.clarityCore,
      fg_dim = plt.clarityDim,
      fg_dimmer = plt.silenceLightest,
      fg_dark = plt.silenceBright,
      fg_reverse = plt.hushVoid,
      bg = plt.hushVoid,
      bg_dim = plt.hushVoid,
      bg_m1 = plt.hushDark,
      bg_m2 = plt.hushDeep,
      bg_m3 = plt.hushMid,
      bg_m4 = plt.hushLight,
      bg_p1 = plt.hushDeep,
      bg_p2 = plt.hushMid,
      bg_gutter = (opts.gutter ~= false) and plt.hushMid or "none",
      bg_cursorline = plt.calmLine,
      bg_cursorline_alt = plt.calmDeep,
      cursorline = plt.calmLine,
      bg_highlight = plt.calmDeep,
      bg_search = plt.restoreDeep,
      bg_visual = plt.restoreDeep,
      bg_statusline = plt.calmMid,
      border = plt.silenceMid,
      header1 = plt.clarityBright,
      header2 = plt.restoreBright,
      special = plt.restorePulse,
      nontext = plt.hushLight,
      whitespace = plt.hushLight,
      win_separator = plt.silenceMid,
      indent = plt.hushMid,
      indent_scope = plt.restoreMid,
      picker = plt.restorePulse,
      yank = plt.phosphorGlow,
      mark = plt.restoreBright,
      scrollbar = plt.silenceDeep,
      selection = plt.restoreDeep,
      line_nr = plt.silenceDeep,
      line_nr_dim = plt.silenceMid,
      line_nr_active = plt.clarityCore,
      pmenu = {
        fg = plt.clarityCore,
        fg_sel = plt.clarityBright,
        fg_border = plt.silenceMid,
        bg = plt.calmMid,
        bg_sel = plt.calmDeep,
        bg_border = plt.calmMid,
        bg_sbar = plt.calmMid,
        bg_thumb = plt.silenceMid,
      },
      float = {
        fg = plt.clarityCore,
        bg = plt.hushDeep,
        fg_border = plt.calmMid,
        bg_border = plt.hushDeep,
      },
      tabline = {
        bg = plt.hushVoid,
        bg_inactive = plt.hushVoid,
        bg_selected = plt.calmMid,
        bg_alternate = plt.hushDark,
        fg_inactive = plt.silenceLighter,
        fg_selected = plt.clarityCore,
        fg_alternate = plt.restoreMid,
        indicator = plt.restoreBright,
      },
    },
    syn = {
      attribute = plt.clarityCore,
      boolean = plt.restoreBright,
      comment = plt.silenceBright,
      constant = plt.mossDark,
      deprecated = plt.silenceMid,
      func = plt.glitchGreen,
      identifier = plt.phosphorGlow,
      keyword = plt.phosphorFlare,
      method = plt.glitchGreen,
      number = plt.silenceLightest,
      operator = plt.silenceLight,
      parameter = plt.glitchPale,
      preproc = plt.restoreVivid,
      punct = plt.silenceMid,
      regex = plt.silenceLight,
      special = plt.restorePulse,
      special2 = plt.restoreMid,
      special3 = plt.restoreVivid,
      statement = plt.clarityCore,
      string = plt.silenceLighter,
      symbol = plt.clarityCore,
      type = plt.restorePulse,
      variable = plt.clarityCore,
    },
    diag = {
      error = plt.restoreBright,
      warning = plt.restoreMid,
      info = plt.silenceBright,
      hint = plt.silenceMid,
      ok = plt.silenceLighter,
      virtual_text_error = plt.restoreDeep,
      virtual_text_warning = plt.restoreMid,
      virtual_text_info = plt.silenceLight,
      virtual_text_hint = plt.silenceDeep,
      virtual_text_ok = plt.silenceLight,
    },
    diff = {
      add = plt.silenceLighter,
      add_inline = plt.phosphorMid,
      change = plt.silenceLight,
      change_inline = plt.silenceBright,
      delete = plt.restoreBright,
      delete_inline = plt.restorePulse,
      text = plt.restoreDeep,
    },
    vcs = {
      added = plt.silenceLighter,
      changed = plt.restoreDeep,
      removed = plt.restoreBright,
    },
    term = {
      black = plt.hushVoid,
      red = plt.restoreBright,
      green = plt.silenceBright,
      yellow = plt.silenceLightest,
      blue = plt.hushVoid,
      magenta = plt.restoreMid,
      cyan = plt.silenceLight,
      white = plt.clarityCore,
      black_bright = color(plt.hushVoid):brighten(0.4):to_hex(),
      red_bright = plt.restorePulse,
      green_bright = color(plt.silenceBright):brighten(0.3):to_hex(),
      yellow_bright = plt.clarityDim,
      blue_bright = color(plt.hushVoid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.restoreMid):brighten(0.4):to_hex(),
      cyan_bright = color(plt.silenceLight):brighten(0.3):to_hex(),
      white_bright = plt.clarityBright,
      indexed1 = plt.phosphorGlow,
      indexed2 = plt.restorePulse,
    },
  }
end

return {
  name = "Detox: 1998 Terminal Green",
  author = "PrismPunk.nvim",
  description = "Pure 1998 CRT green phosphor. Zero blue. Deep readable greens. The terminal your soul remembers.",
  base16 = {
    base00 = palette.hushVoid,
    base01 = palette.hushDark,
    base02 = palette.hushDeep,
    base03 = palette.hushMid,
    base04 = palette.silenceBright,
    base05 = palette.silenceLightest,
    base06 = palette.clarityDim,
    base07 = palette.clarityCore,
    base08 = palette.restoreBright,
    base09 = palette.restoreMid,
    base0A = palette.restoreDeep,
    base0B = palette.silenceLighter,
    base0C = palette.restorePulse,
    base0D = palette.silenceLight,
    base0E = palette.restorePulse,
    base0F = palette.silenceMid,
  },
  palette = palette,
  get = M.get,
}
