local color = require("prismpunk.utils.color")

local palette = {
  ashVoid = "#0A0A0A",
  ashDark = "#121212",
  ashDeep = "#191919",
  ashMid = "#222222",
  ashLight = "#2A2A2A",
  ashBrighter = "#363636",
  ashPale = "#424242",
  cinerDeep = "#323035",
  cinerMid = "#3A383D",
  cinerLine = "#444248",
  cinerBright = "#514E55",
  cinerGlow = "#5C595E",
  slagDeep = "#505050",
  slagDim = "#404040",
  slagMid = "#5D5D5D",
  slagBright = "#6A6A6A",
  slagLighter = "#787878",
  slagLightest = "#858585",
  slagGlow = "#9F9F9F",
  slagShimmer = "#B2B2B2",
  smokeCore = "#C5C5C5",
  smokeDim = "#9D9D9D",
  smokeBright = "#DCDCDC",
  smokePale = "#E8E8E8",
  emberDeep = "#3A2825",
  emberFaint = "#221816",
  emberMid = "#453228",
  emberBright = "#50382A",
  emberPulse = "#5A4032",
  emberGlow = "#684836",
  emberFlare = "#7A5540",
  sootDeep = "#141414",
  sootMid = "#1E1E1E",
  sootLight = "#252525",
  sootEcho = "#2D2D2D",
  charVoid = "#151210",
  charDark = "#1B1715",
  charFade = "#261F1A",
  ashGhost = "#333333",
  cinerShadow = "#292729",

  bg_darkest = "#0A0A0A",
  fg_lightest = "#E8E8E8",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.smokeCore,
      insert = plt.slagLighter,
      normal = plt.slagBright,
      replace = plt.slagMid,
      visual = plt.emberPulse,
    },
    accent = {
      accent1 = plt.smokeBright,
      accent2 = plt.smokeCore,
      accent3 = plt.slagLighter,
      accent4 = plt.slagBright,
      accent5 = plt.emberPulse,
      invert = plt.cinerMid,
    },
    rainbow = {
      rainbow1 = plt.slagBright,
      rainbow2 = plt.slagMid,
      rainbow3 = plt.slagDeep,
      rainbow4 = plt.cinerDeep,
      rainbow5 = plt.smokeCore,
      rainbow6 = plt.smokeBright,
      rainbow7 = plt.emberPulse,
    },
    ui = {
      bg = plt.ashVoid,
      bg_cursorline = plt.cinerLine,
      bg_cursorline_alt = plt.cinerMid,
      bg_dim = plt.ashVoid,
      bg_gutter = opts.gutter and plt.ashMid or "none",
      bg_highlight = plt.cinerDeep,
      bg_m1 = plt.ashDark,
      bg_m2 = plt.ashDeep,
      bg_m3 = plt.ashMid,
      bg_m4 = plt.ashLight,
      bg_p1 = plt.ashDeep,
      bg_p2 = plt.ashMid,
      bg_search = plt.emberPulse,
      bg_statusline = plt.cinerMid,
      bg_visual = plt.emberDeep,
      border = plt.slagDeep,
      cursorline = plt.cinerLine,
      fg = plt.smokeCore,
      fg_dark = plt.slagDeep,
      fg_dim = plt.smokeCore,
      fg_dimmer = plt.slagLighter,
      fg_reverse = plt.ashVoid,
      header1 = plt.smokeBright,
      header2 = plt.smokeCore,
      indent = plt.ashMid,
      indent_scope = plt.slagDeep,
      line_nr = plt.slagDeep,
      line_nr_active = plt.smokeCore,
      line_nr_dim = plt.slagDeep,
      mark = plt.emberBright,
      nontext = plt.ashBrighter,
      picker = plt.slagDeep,
      scrollbar = plt.ashLight,
      selection = plt.emberDeep,
      special = plt.emberBright,
      whitespace = plt.ashDeep,
      win_separator = plt.slagDeep,
      yank = plt.emberPulse,
      float = {
        bg = plt.ashDeep,
        bg_border = plt.ashDeep,
        fg = plt.smokeCore,
        fg_border = plt.cinerMid,
      },
      pmenu = {
        bg = plt.cinerMid,
        bg_border = plt.cinerMid,
        bg_sbar = plt.cinerMid,
        bg_sel = plt.cinerDeep,
        bg_thumb = plt.slagDeep,
        fg = plt.smokeCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.ashVoid,
        bg_alternate = plt.ashVoid,
        bg_inactive = plt.ashVoid,
        bg_selected = plt.cinerMid,
        fg_alternate = plt.slagDeep,
        fg_inactive = plt.slagDeep,
        fg_selected = plt.smokeCore,
        indicator = plt.emberPulse,
      },
    },
    syn = {
      attribute = plt.smokeCore,
      boolean = plt.emberBright,
      comment = plt.slagMid,
      constant = plt.slagLightest,
      deprecated = plt.slagDeep,
      func = plt.emberBright,
      identifier = plt.emberGlow,
      keyword = plt.emberFlare,
      method = plt.emberBright,
      number = plt.slagLightest,
      operator = plt.slagDeep,
      parameter = plt.smokeDim,
      preproc = plt.emberMid,
      punct = plt.slagDeep,
      regex = plt.slagDeep,
      special = plt.emberPulse,
      special2 = plt.emberMid,
      special3 = plt.emberBright,
      statement = plt.smokeCore,
      string = plt.emberPulse,
      symbol = plt.smokeCore,
      type = plt.slagLightest,
      variable = plt.smokeCore,
    },
    diag = {
      error = plt.emberBright,
      hint = plt.slagMid,
      info = plt.smokeCore,
      ok = plt.slagLighter,
      virtual_text_error = plt.emberMid,
      virtual_text_hint = plt.slagDeep,
      virtual_text_info = plt.slagBright,
      virtual_text_ok = plt.slagMid,
      virtual_text_warning = plt.emberDeep,
      warning = plt.emberPulse,
    },
    diff = {
      add = plt.slagLighter,
      add_inline = plt.slagGlow,
      change = plt.slagDeep,
      change_inline = plt.sootMid,
      delete = plt.emberBright,
      delete_inline = plt.emberGlow,
      text = plt.emberMid,
    },
    vcs = {
      added = plt.slagLighter,
      changed = plt.emberDeep,
      removed = plt.emberBright,
    },
    term = {
      black = plt.ashVoid,
      black_bright = color(plt.ashVoid):brighten(0.4):to_hex(),
      blue = plt.ashVoid,
      blue_bright = color(plt.ashVoid):brighten(0.2):to_hex(),
      cyan = plt.slagMid,
      cyan_bright = color(plt.slagMid):brighten(0.3):to_hex(),
      green = plt.slagBright,
      green_bright = color(plt.slagBright):brighten(0.3):to_hex(),
      indexed1 = plt.slagLighter,
      indexed2 = plt.slagBright,
      magenta = plt.smokeCore,
      magenta_bright = color(plt.smokeCore):brighten(0.4):to_hex(),
      red = plt.emberBright,
      red_bright = plt.emberPulse,
      white = plt.smokeBright,
      white_bright = plt.smokeBright,
      yellow = plt.slagLightest,
      yellow_bright = plt.smokeBright,
    },
  }
end

return {
  name = "Detox: Ash",
  author = "PrismPunk.nvim",
  description = "Post-fire barrenness. Cool grays. Faint ember warmth. Silent aftermath. Zero dopamine.",
  base16 = {
    base00 = palette.ashVoid,
    base01 = palette.ashDark,
    base02 = palette.ashDeep,
    base03 = palette.ashMid,
    base04 = palette.slagBright,
    base05 = palette.slagLightest,
    base06 = palette.smokeCore,
    base07 = palette.smokeBright,
    base08 = palette.emberGlow,
    base09 = palette.emberMid,
    base0A = palette.emberDeep,
    base0B = palette.emberGlow,
    base0C = palette.emberPulse,
    base0D = palette.slagLightest,
    base0E = palette.emberPulse,
    base0F = palette.slagDeep,
  },
  palette = palette,
  get = M.get,
}
