local color = require("prismpunk.utils.color")

local palette = {
  barelySeen = "#404040",
  dampDeep = "#2B2B2B",
  dampLine = "#373737",
  dampMid = "#313131",
  echoFaint = "#5B5B5B",
  greyStill = "#464646",
  hushBright = "#2E2E35",
  hushDeep = "#1A1A1F",
  hushDim = "#161619",
  hushMid = "#242429",
  hushPulse = "#38383F",
  muteBright = "#494949",
  muteDeep = "#3D3D3D",
  muteLighter = "#4F4F4F",
  muteLightest = "#555555",
  muteMid = "#434343",
  mutedTone = "#4C4C4C",
  neutralCalm = "#525252",
  quietDark = "#111111",
  quietDeep = "#171717",
  quietDim = "#0D0D0D",
  quietLight = "#242424",
  quietMid = "#1E1E1E",
  quietVoid = "#0A0A0A",
  restfulGrey = "#585858",
  shadowMuted = "#272727",
  silenceDeep = "#2E2E2E",
  silentHush = "#343434",
  stillnessGrey = "#5E5E5E",
  subdued = "#616161",
  toneLow = "#646464",
  veilSoft = "#676767",
  whisperBright = "#D0D0D0",
  whisperCore = "#B8B8B8",
  whisperPale = "#E8E8E8",
  zenithMute = "#F0F0F0",
  zoneQuiet = "#6A6A6A",
  zoneStill = "#202020",
  zoneTranquil = "#3A3A3A",
  zymeSilent = "#6D6D6D",

  bg_darkest = "#0A0A0A",
  fg_lightest = "#E8E8E8",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.whisperCore,
      insert = plt.muteLighter,
      normal = plt.muteBright,
      replace = plt.muteMid,
      visual = plt.hushPulse,
    },
    accent = {
      accent1 = plt.whisperBright,
      accent2 = plt.whisperCore,
      accent3 = plt.muteLighter,
      accent4 = plt.muteBright,
      accent5 = plt.hushPulse,
      invert = plt.dampMid,
    },
    rainbow = {
      rainbow1 = plt.muteBright,
      rainbow2 = plt.muteMid,
      rainbow3 = plt.muteDeep,
      rainbow4 = plt.dampDeep,
      rainbow5 = plt.whisperCore,
      rainbow6 = plt.whisperBright,
      rainbow7 = plt.hushPulse,
    },
    ui = {
      bg = plt.quietVoid,
      bg_cursorline = plt.dampLine,
      bg_dim = plt.quietVoid,
      bg_gutter = opts.gutter and plt.quietMid or "none",
      bg_highlight = plt.dampDeep,
      bg_m1 = plt.quietDark,
      bg_m2 = plt.quietDeep,
      bg_m3 = plt.quietMid,
      bg_m4 = plt.quietLight,
      bg_p1 = plt.quietDeep,
      bg_p2 = plt.quietMid,
      bg_search = plt.hushPulse,
      bg_statusline = plt.dampMid,
      bg_visual = plt.hushDeep,
      border = plt.muteMid,
      cursorline = plt.dampLine,
      fg = plt.whisperCore,
      fg_dark = plt.muteMid,
      fg_dim = plt.whisperCore,
      fg_dimmer = plt.muteLighter,
      fg_reverse = plt.quietVoid,
      header1 = plt.whisperBright,
      header2 = plt.whisperCore,
      indent = plt.quietMid,
      indent_scope = plt.muteDeep,
      line_nr = plt.muteMid,
      line_nr_active = plt.whisperCore,
      line_nr_dim = plt.muteBright,
      mark = plt.hushBright,
      nontext = plt.quietLight,
      picker = plt.muteMid,
      scrollbar = plt.quietLight,
      selection = plt.hushDeep,
      special = plt.hushBright,
      whitespace = plt.quietMid,
      win_separator = plt.muteMid,
      yank = plt.hushPulse,
      float = {
        bg = plt.quietDeep,
        bg_border = plt.quietDeep,
        fg = plt.whisperCore,
        fg_border = plt.dampMid,
      },
      pmenu = {
        bg = plt.dampMid,
        bg_border = plt.dampMid,
        bg_sbar = plt.dampMid,
        bg_sel = plt.dampDeep,
        bg_thumb = plt.muteMid,
        fg = plt.whisperCore,
        fg_border = plt.dampMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.quietVoid,
        bg_alternate = plt.quietVoid,
        bg_inactive = plt.quietVoid,
        bg_selected = plt.dampMid,
        fg_alternate = plt.muteBright,
        fg_inactive = plt.muteLighter,
        fg_selected = plt.whisperCore,
        indicator = plt.hushPulse,
      },
    },
    syn = {
      attribute = plt.whisperCore,
      boolean = plt.hushBright,
      comment = plt.muteBright,
      constant = plt.muteLightest,
      deprecated = plt.muteMid,
      func = plt.whisperBright,
      identifier = plt.whisperCore,
      keyword = plt.whisperCore,
      method = plt.whisperBright,
      number = plt.muteLightest,
      operator = plt.muteMid,
      parameter = plt.muteLighter,
      preproc = plt.hushMid,
      punct = plt.muteDeep,
      regex = plt.muteMid,
      special = plt.hushPulse,
      special2 = plt.hushMid,
      special3 = plt.hushBright,
      statement = plt.whisperCore,
      string = plt.muteLighter,
      symbol = plt.whisperCore,
      type = plt.muteLightest,
      variable = plt.whisperCore,
    },
    diag = {
      error = plt.hushBright,
      hint = plt.muteMid,
      info = plt.whisperCore,
      ok = plt.muteLighter,
      virtual_text_error = plt.hushBright,
      virtual_text_hint = plt.muteMid,
      virtual_text_info = plt.whisperCore,
      virtual_text_ok = plt.muteLighter,
      virtual_text_warning = plt.hushPulse,
      warning = plt.hushPulse,
    },
    diff = {
      add = plt.muteLighter,
      add_inline = plt.muteDeep,
      change = plt.muteDeep,
      change_inline = plt.dampDeep,
      delete = plt.hushBright,
      delete_inline = plt.hushDeep,
      text = plt.hushMid,
    },
    vcs = {
      added = plt.muteLighter,
      changed = plt.hushDeep,
      removed = plt.hushBright,
    },
    term = {
      black = plt.quietVoid,
      black_bright = color(plt.quietVoid):brighten(0.4):to_hex(),
      blue = plt.quietVoid,
      blue_bright = color(plt.quietVoid):brighten(0.2):to_hex(),
      cyan = plt.muteMid,
      cyan_bright = color(plt.muteMid):brighten(0.3):to_hex(),
      green = plt.muteBright,
      green_bright = color(plt.muteBright):brighten(0.3):to_hex(),
      indexed1 = plt.muteLighter,
      indexed2 = plt.muteBright,
      magenta = plt.whisperCore,
      magenta_bright = color(plt.whisperCore):brighten(0.4):to_hex(),
      red = plt.hushBright,
      red_bright = plt.hushPulse,
      white = plt.whisperBright,
      white_bright = plt.whisperBright,
      yellow = plt.muteLightest,
      yellow_bright = plt.whisperBright,
    },
  }
end

return {
  name = "Detox: Mute",
  author = "PrismPunk.nvim",
  description = "Soundless silence. Barely-distinguishable grays. Single whispered accent. Extreme minimalism.",
  base16 = {
    base00 = palette.quietVoid,
    base01 = palette.quietDark,
    base02 = palette.quietDeep,
    base03 = palette.quietMid,
    base04 = palette.muteBright,
    base05 = palette.muteLightest,
    base06 = palette.whisperCore,
    base07 = palette.whisperBright,
    base08 = palette.hushBright,
    base09 = palette.hushMid,
    base0A = palette.hushDeep,
    base0B = palette.muteLighter,
    base0C = palette.hushPulse,
    base0D = palette.muteMid,
    base0E = palette.hushPulse,
    base0F = palette.muteMid,
  },
  palette = palette,
  get = M.get,
}
