local color = require("prismpunk.utils.color")

local palette = {
  archiveYellow = "#58544C",
  bondPaper = "#C0BAB5",
  celluloseFiber = "#4B4843",
  craftBrown = "#3B3831",
  fiberDim = "#434039",
  inkBright = "#40332A",
  inkDeep = "#2A1F15",
  inkDim = "#241912",
  inkMid = "#35291F",
  inkPulse = "#4A3D35",
  manuscriptTan = "#D8D2C8",
  pageBright = "#E8E2D8",
  pageCore = "#D0CAC5",
  pagePale = "#F0EAE0",
  paperDark = "#17150F",
  paperDeep = "#1F1A15",
  paperDim = "#13110D",
  paperLight = "#2F2B25",
  paperMid = "#27231D",
  paperVoid = "#0F0D0A",
  parchmentOld = "#B0AAA0",
  pulpDeep = "#37342F",
  pulpLine = "#47443F",
  pulpMid = "#3F3C37",
  pulpWarm = "#4F4A45",
  reamFold = "#332F29",
  sheetBright = "#656260",
  sheetDeep = "#4F4C47",
  sheetLighter = "#707070",
  sheetLightest = "#7B7A80",
  sheetMid = "#5A5755",
  stockHeavy = "#635F58",
  textureRough = "#6B6760",
  vellumCream = "#A8A298",
  vintageBeige = "#989288",
  watermarkFaint = "#757068",
  wovePaper = "#535048",
  zenithPaper = "#F8F4EC",
  zoneArchival = "#504C45",
  zonePulp = "#433F38",
  zymeAged = "#786F68",

  bg_darkest = "#0F0D0A",
  fg_lightest = "#F0EAE0",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.pageCore,
      insert = plt.sheetLighter,
      normal = plt.sheetBright,
      replace = plt.sheetMid,
      visual = plt.inkPulse,
    },
    accent = {
      accent1 = plt.pageBright,
      accent2 = plt.pageCore,
      accent3 = plt.sheetLighter,
      accent4 = plt.sheetBright,
      accent5 = plt.inkPulse,
      invert = plt.pulpMid,
    },
    rainbow = {
      rainbow1 = plt.sheetBright,
      rainbow2 = plt.sheetMid,
      rainbow3 = plt.sheetDeep,
      rainbow4 = plt.pulpDeep,
      rainbow5 = plt.pageCore,
      rainbow6 = plt.pageBright,
      rainbow7 = plt.inkPulse,
    },
    ui = {
      bg = plt.paperVoid,
      bg_cursorline = plt.pulpLine,
      bg_dim = plt.paperVoid,
      bg_gutter = opts.gutter and plt.paperMid or "none",
      bg_highlight = plt.pulpDeep,
      bg_m1 = plt.paperDark,
      bg_m2 = plt.paperDeep,
      bg_m3 = plt.paperMid,
      bg_m4 = plt.paperLight,
      bg_p1 = plt.paperDeep,
      bg_p2 = plt.paperMid,
      bg_search = plt.inkPulse,
      bg_statusline = plt.pulpMid,
      bg_visual = plt.inkDeep,
      border = plt.sheetDeep,
      cursorline = plt.pulpLine,
      fg = plt.pageCore,
      fg_dark = plt.sheetDeep,
      fg_dim = plt.pageCore,
      fg_dimmer = plt.sheetLighter,
      fg_reverse = plt.paperVoid,
      header1 = plt.pageBright,
      header2 = plt.pageCore,
      indent = plt.paperMid,
      indent_scope = plt.sheetDeep,
      line_nr = plt.sheetDeep,
      line_nr_active = plt.pageCore,
      line_nr_dim = plt.sheetDeep,
      mark = plt.inkBright,
      nontext = plt.paperDeep,
      picker = plt.sheetDeep,
      scrollbar = plt.paperLight,
      selection = plt.inkDeep,
      special = plt.inkBright,
      whitespace = plt.paperDeep,
      win_separator = plt.sheetDeep,
      yank = plt.inkPulse,
      float = {
        bg = plt.paperDeep,
        bg_border = plt.paperDeep,
        fg = plt.pageCore,
        fg_border = plt.pulpMid,
      },
      pmenu = {
        bg = plt.pulpMid,
        bg_border = plt.pulpMid,
        bg_sbar = plt.pulpMid,
        bg_sel = plt.pulpDeep,
        bg_thumb = plt.sheetDeep,
        fg = plt.pageCore,
        fg_border = plt.pulpMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.paperVoid,
        bg_alternate = plt.paperVoid,
        bg_inactive = plt.paperVoid,
        bg_selected = plt.pulpMid,
        fg_alternate = plt.sheetDeep,
        fg_inactive = plt.sheetDeep,
        fg_selected = plt.pageCore,
        indicator = plt.inkPulse,
      },
    },
    syn = {
      attribute = plt.pageCore,
      boolean = plt.inkBright,
      comment = plt.sheetMid,
      constant = plt.sheetLightest,
      deprecated = plt.sheetDeep,
      func = plt.pageBright,
      identifier = plt.pageCore,
      keyword = plt.pageCore,
      method = plt.pageBright,
      number = plt.sheetLightest,
      operator = plt.sheetDeep,
      parameter = plt.sheetLighter,
      preproc = plt.inkMid,
      punct = plt.sheetDeep,
      regex = plt.sheetDeep,
      special = plt.inkPulse,
      special2 = plt.inkMid,
      special3 = plt.inkBright,
      statement = plt.pageCore,
      string = plt.sheetLightest,
      symbol = plt.pageCore,
      type = plt.sheetLightest,
      variable = plt.pageCore,
    },
    diag = {
      error = plt.inkBright,
      hint = plt.sheetMid,
      info = plt.pageCore,
      ok = plt.sheetLighter,
      virtual_text_error = plt.inkBright,
      virtual_text_hint = plt.sheetMid,
      virtual_text_info = plt.pageCore,
      virtual_text_ok = plt.sheetLighter,
      virtual_text_warning = plt.inkPulse,
      warning = plt.inkPulse,
    },
    diff = {
      add = plt.sheetLighter,
      add_inline = plt.sheetDeep,
      change = plt.sheetDeep,
      change_inline = plt.pulpDeep,
      delete = plt.inkBright,
      delete_inline = plt.inkDeep,
      text = plt.inkMid,
    },
    vcs = {
      added = plt.sheetLighter,
      changed = plt.inkDeep,
      removed = plt.inkBright,
    },
    term = {
      black = plt.paperVoid,
      black_bright = color(plt.paperVoid):brighten(0.4):to_hex(),
      blue = plt.paperVoid,
      blue_bright = color(plt.paperVoid):brighten(0.2):to_hex(),
      cyan = plt.sheetMid,
      cyan_bright = color(plt.sheetMid):brighten(0.3):to_hex(),
      green = plt.sheetBright,
      green_bright = color(plt.sheetBright):brighten(0.3):to_hex(),
      indexed1 = plt.sheetLighter,
      indexed2 = plt.sheetBright,
      magenta = plt.pageCore,
      magenta_bright = color(plt.pageCore):brighten(0.4):to_hex(),
      red = plt.inkBright,
      red_bright = plt.inkPulse,
      white = plt.pageBright,
      white_bright = plt.pageBright,
      yellow = plt.sheetLightest,
      yellow_bright = plt.pageBright,
    },
  }
end

return {
  name = "Detox: Paper",
  author = "PrismPunk.nvim",
  description = "Aged pulp sheets. Cellulose fiber texture. Ink stain marks. Handmade documentation.",
  base16 = {
    base00 = palette.paperVoid,
    base01 = palette.paperDark,
    base02 = palette.paperDeep,
    base03 = palette.paperMid,
    base04 = palette.sheetBright,
    base05 = palette.sheetLightest,
    base06 = palette.pageCore,
    base07 = palette.pageBright,
    base08 = palette.inkBright,
    base09 = palette.inkMid,
    base0A = palette.inkDeep,
    base0B = palette.sheetLighter,
    base0C = palette.inkPulse,
    base0D = palette.sheetMid,
    base0E = palette.inkPulse,
    base0F = palette.sheetMid,
  },
  palette = palette,
  get = M.get,
}
