local color = require("prismpunk.utils.color")

local palette = {
  blockGrey = "#454545",
  bloodBright = "#774444",
  bloodDeep = "#552222",
  bloodDim = "#442020",
  bloodMid = "#663333",
  bloodPulse = "#884444",
  brutalistDark = "#181818",
  cellWall = "#2E2E2E",
  chainGrey = "#959595",
  concreteDeep = "#262626",
  crimsonMuted = "#995555",
  focusBright = "#E0E0E0",
  focusCore = "#C0C0C0",
  focusDim = "#A8A8A8",
  focusPale = "#F0F0F0",
  isolationGrey = "#151515",
  prisonDark = "#0B0B0B",
  prisonDeep = "#121212",
  prisonDim = "#060606",
  prisonLight = "#222222",
  prisonMid = "#1A1A1A",
  prisonVoid = "#000000",
  redAccent = "#AA5555",
  restraintMetal = "#6A6A6A",
  shadowBright = "#707070",
  shadowDeep = "#404040",
  shadowLighter = "#808080",
  shadowLightest = "#909090",
  shadowLight = "#606060",
  shadowMid = "#505050",
  stoneDeep = "#2B2B2B",
  stoneLine = "#3B3B3B",
  stoneMid = "#333333",
  structureGrey = "#5A5A5A",
  unforgivingGrey = "#4A4A4A",
  vaultDark = "#1F1F1F",
  zenithPrison = "#FFFFFF",
  zoneBrutalist = "#363636",
  zoneConfinement = "#2A2A2A",
  zoneIsolation = "#0F0F0F",
  zymeShadow = "#757575",

  bg_darkest = "#000000",
  fg_lightest = "#F0F0F0",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.shadowBright,
      insert = plt.bloodBright,
      normal = plt.bloodMid,
      replace = plt.bloodDeep,
      visual = plt.bloodPulse,
    },
    accent = {
      accent1 = plt.bloodBright,
      accent2 = plt.bloodMid,
      accent3 = plt.bloodDeep,
      accent4 = plt.shadowBright,
      accent5 = plt.bloodPulse,
      invert = plt.stoneMid,
    },
    rainbow = {
      rainbow1 = plt.shadowBright,
      rainbow2 = plt.shadowLight,
      rainbow3 = plt.shadowMid,
      rainbow4 = plt.bloodDeep,
      rainbow5 = plt.bloodMid,
      rainbow6 = plt.bloodBright,
      rainbow7 = plt.bloodPulse,
    },
    ui = {
      bg = plt.prisonVoid,
      bg_cursorline = plt.stoneLine,
      bg_dim = plt.prisonVoid,
      bg_gutter = opts.gutter and plt.prisonMid or "none",
      bg_highlight = plt.stoneDeep,
      bg_m1 = plt.prisonDark,
      bg_m2 = plt.prisonDeep,
      bg_m3 = plt.prisonMid,
      bg_m4 = plt.prisonLight,
      bg_p1 = plt.prisonDeep,
      bg_p2 = plt.prisonMid,
      bg_search = plt.bloodPulse,
      bg_statusline = plt.stoneMid,
      bg_visual = plt.bloodDeep,
      border = plt.shadowMid,
      cursorline = plt.stoneLine,
      fg = plt.focusCore,
      fg_dark = plt.shadowLight,
      fg_dim = plt.focusDim,
      fg_dimmer = plt.shadowLighter,
      fg_reverse = plt.prisonVoid,
      header1 = plt.bloodBright,
      header2 = plt.bloodMid,
      indent = plt.prisonMid,
      indent_scope = plt.shadowDeep,
      line_nr = plt.shadowMid,
      line_nr_active = plt.focusCore,
      line_nr_dim = plt.shadowLight,
      mark = plt.bloodBright,
      nontext = plt.prisonLight,
      picker = plt.shadowLight,
      scrollbar = plt.prisonLight,
      selection = plt.bloodDeep,
      special = plt.bloodPulse,
      whitespace = plt.prisonMid,
      win_separator = plt.shadowMid,
      yank = plt.bloodPulse,
      float = {
        bg = plt.prisonDeep,
        bg_border = plt.prisonDeep,
        fg = plt.focusCore,
        fg_border = plt.stoneMid,
      },
      pmenu = {
        bg = plt.stoneMid,
        bg_border = plt.stoneMid,
        bg_sbar = plt.stoneMid,
        bg_sel = plt.stoneDeep,
        bg_thumb = plt.shadowMid,
        fg = plt.focusCore,
        fg_border = plt.stoneMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.prisonVoid,
        bg_alternate = plt.prisonVoid,
        bg_inactive = plt.prisonVoid,
        bg_selected = plt.stoneMid,
        fg_alternate = plt.bloodMid,
        fg_inactive = plt.shadowLighter,
        fg_selected = plt.focusCore,
        indicator = plt.bloodPulse,
      },
    },
    syn = {
      attribute = plt.focusCore,
      boolean = plt.bloodBright,
      comment = plt.shadowBright,
      constant = plt.shadowLightest,
      deprecated = plt.shadowMid,
      func = plt.focusBright,
      identifier = plt.focusCore,
      keyword = plt.focusCore,
      method = plt.focusBright,
      number = plt.shadowLightest,
      operator = plt.shadowLight,
      parameter = plt.shadowLighter,
      preproc = plt.bloodDeep,
      punct = plt.shadowMid,
      regex = plt.shadowLight,
      special = plt.bloodPulse,
      special2 = plt.bloodMid,
      special3 = plt.bloodBright,
      statement = plt.focusCore,
      string = plt.shadowLighter,
      symbol = plt.focusCore,
      type = plt.shadowLightest,
      variable = plt.focusCore,
    },
    diag = {
      error = plt.bloodBright,
      hint = plt.shadowMid,
      info = plt.shadowBright,
      ok = plt.shadowLighter,
      virtual_text_error = plt.bloodBright,
      virtual_text_hint = plt.shadowMid,
      virtual_text_info = plt.shadowBright,
      virtual_text_ok = plt.shadowLighter,
      virtual_text_warning = plt.bloodMid,
      warning = plt.bloodMid,
    },
    diff = {
      add = plt.shadowLighter,
      add_inline = plt.shadowDeep,
      change = plt.shadowLight,
      change_inline = plt.stoneDeep,
      delete = plt.bloodBright,
      delete_inline = plt.bloodDeep,
      text = plt.bloodDeep,
    },
    vcs = {
      added = plt.shadowLighter,
      changed = plt.bloodDeep,
      removed = plt.bloodBright,
    },
    term = {
      black = plt.prisonVoid,
      black_bright = color(plt.prisonVoid):brighten(0.4):to_hex(),
      blue = plt.prisonVoid,
      blue_bright = color(plt.prisonVoid):brighten(0.2):to_hex(),
      cyan = plt.shadowLight,
      cyan_bright = color(plt.shadowLight):brighten(0.3):to_hex(),
      green = plt.shadowBright,
      green_bright = color(plt.shadowBright):brighten(0.3):to_hex(),
      indexed1 = plt.bloodMid,
      indexed2 = plt.bloodBright,
      magenta = plt.bloodMid,
      magenta_bright = color(plt.bloodMid):brighten(0.4):to_hex(),
      red = plt.bloodBright,
      red_bright = plt.bloodPulse,
      white = plt.focusCore,
      white_bright = plt.focusBright,
      yellow = plt.shadowLightest,
      yellow_bright = plt.focusBright,
    },
  }
end

return {
  name = "Detox: Brutalist Prison",
  author = "PrismPunk.nvim",
  description = "Zero blue. Tiny green warmth. Deep, readable blood-reds. Maximum focus. No dopamine.",
  base16 = {
    base00 = palette.prisonVoid,
    base01 = palette.prisonDark,
    base02 = palette.prisonDeep,
    base03 = palette.prisonMid,
    base04 = palette.shadowBright,
    base05 = palette.shadowLightest,
    base06 = palette.focusDim,
    base07 = palette.focusCore,
    base08 = palette.bloodBright,
    base09 = palette.bloodMid,
    base0A = palette.bloodDeep,
    base0B = palette.shadowLighter,
    base0C = palette.bloodPulse,
    base0D = palette.shadowLight,
    base0E = palette.bloodPulse,
    base0F = palette.shadowMid,
  },
  palette = palette,
  get = M.get,
}
