local color = require("prismpunk.utils.color")

local palette = {
  scarVoid = "#0A080A",
  scarDark = "#121012",
  scarDeep = "#1A181A",
  scarMid = "#222022",
  scarLight = "#2A282A",
  scarShadow = "#0F0D0F",
  scarEcho = "#1E1C1E",
  scarTint = "#2E2A2E",
  healDeep = "#32303A",
  healMid = "#3A3842",
  healLine = "#42404A",
  healRidge = "#484252",
  healSoft = "#504E58",
  healGlow = "#5E5670",
  healVivid = "#6A6290",
  menderDeep = "#4A4854",
  menderMid = "#555366",
  menderBright = "#606278",
  menderLighter = "#6B7389",
  menderLightest = "#7A849A",
  menderGlow = "#8892AC",
  menderVivid = "#94A0C2",
  menderPeak = "#A0AEC8",
  paleCore = "#D0C8D0",
  paleBright = "#E8DCE8",
  palePeak = "#F5E8F5",
  paleDim = "#B8B0B8",
  paleSoft = "#C8C0C8",
  markDeep = "#2A1820",
  markMid = "#35222A",
  markBright = "#402C35",
  markPulse = "#4A363F",
  markVivid = "#553F49",
  markGlow = "#603F50",
  markScarlet = "#703850",
  markFlesh = "#804060",
  markWound = "#903870",
  scarAccent1 = "#3C2A34",
  scarAccent2 = "#452E3A",
  scarAccent3 = "#503240",
  scarAccent4 = "#5B3646",

  bg_darkest = "#0A080A",
  fg_lightest = "#F5E8F5",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.menderBright,
      insert = plt.menderLighter,
      normal = plt.menderBright,
      replace = plt.menderMid,
      visual = plt.markPulse,
    },
    accent = {
      accent1 = plt.paleBright,
      accent2 = plt.paleCore,
      accent3 = plt.menderLighter,
      accent4 = plt.menderBright,
      accent5 = plt.markPulse,
      invert = plt.healMid,
    },
    rainbow = {
      rainbow1 = plt.menderBright,
      rainbow2 = plt.menderMid,
      rainbow3 = plt.menderDeep,
      rainbow4 = plt.healDeep,
      rainbow5 = plt.paleCore,
      rainbow6 = plt.paleBright,
      rainbow7 = plt.markPulse,
    },
    ui = {
      bg = plt.scarVoid,
      bg_cursorline = plt.healLine,
      bg_dim = plt.scarVoid,
      bg_gutter = opts.gutter and plt.scarMid or "none",
      bg_highlight = plt.healDeep,
      bg_m1 = plt.scarDark,
      bg_m2 = plt.scarDeep,
      bg_m3 = plt.scarMid,
      bg_m4 = plt.scarLight,
      bg_p1 = plt.scarDeep,
      bg_p2 = plt.scarMid,
      bg_statusline = plt.healMid,
      bg_visual = plt.markDeep,
      border = plt.menderMid,
      cursorline = plt.healLine,
      fg = plt.paleCore,
      fg_dim = plt.paleDim,
      fg_reverse = plt.scarVoid,
      indent = plt.scarMid,
      line_nr = plt.menderDeep,
      line_nr_active = plt.paleCore,
      line_nr_dim = plt.menderMid,
      nontext = plt.scarLight,
      selection = plt.markDeep,
      win_separator = plt.menderMid,
      float = {
        bg = plt.scarDeep,
        bg_border = plt.scarDeep,
        fg = plt.paleCore,
        fg_border = plt.healMid,
      },
      pmenu = {
        bg = plt.healMid,
        bg_border = plt.healMid,
        bg_sbar = plt.healMid,
        bg_sel = plt.healDeep,
        bg_thumb = plt.menderMid,
        fg = plt.paleCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.scarVoid,
        bg_inactive = plt.scarVoid,
        bg_selected = plt.healMid,
        fg_inactive = plt.menderLighter,
        fg_selected = plt.paleCore,
      },
    },
    syn = {
      attribute = plt.paleCore,
      boolean = plt.markBright,
      comment = plt.menderBright,
      constant = plt.menderLightest,
      deprecated = plt.menderMid,
      func = plt.paleBright,
      identifier = plt.paleCore,
      keyword = plt.paleCore,
      method = plt.paleBright,
      number = plt.menderLightest,
      operator = plt.menderMid,
      parameter = plt.menderLighter,
      preproc = plt.markMid,
      punct = plt.menderMid,
      regex = plt.menderMid,
      special = plt.markPulse,
      statement = plt.paleCore,
      string = plt.menderLighter,
      symbol = plt.paleCore,
      type = plt.menderLightest,
      variable = plt.paleCore,
    },
    diag = {
      error = plt.markBright,
      hint = plt.menderMid,
      info = plt.menderBright,
      ok = plt.menderLighter,
      warning = plt.markPulse,
      virtual_text_error = plt.markMid,
      virtual_text_hint = plt.menderDeep,
      virtual_text_info = plt.menderMid,
      virtual_text_ok = plt.menderLighter,
      virtual_text_warning = plt.markPulse,
    },
    diff = {
      add = plt.menderLighter,
      add_inline = plt.menderGlow,
      change = plt.menderDeep,
      change_inline = plt.menderBright,
      delete = plt.markBright,
      delete_inline = plt.markPulse,
      text = plt.markMid,
    },
    vcs = {
      added = plt.menderLighter,
      changed = plt.markMid,
      removed = plt.markBright,
    },
    term = {
      black = plt.scarVoid,
      black_bright = color(plt.scarVoid):brighten(0.4):to_hex(),
      blue = plt.menderMid,
      blue_bright = plt.menderBright,
      cyan = plt.menderLighter,
      cyan_bright = plt.menderGlow,
      green = plt.menderBright,
      green_bright = plt.menderVivid,
      magenta = plt.markPulse,
      magenta_bright = plt.markGlow,
      red = plt.markBright,
      red_bright = plt.markPulse,
      white = plt.paleCore,
      white_bright = plt.paleBright,
      yellow = plt.menderLightest,
      yellow_bright = plt.palePeak,
    },
  }
end

return {
  name = "Detox: Scar",
  author = "PrismPunk.nvim",
  description = "Pale pink tissue healing. Dark red scars. Recovery & acceptance. Trauma transformed.",
  base16 = {
    base00 = palette.scarVoid,
    base01 = palette.scarDark,
    base02 = palette.scarDeep,
    base03 = palette.scarMid,
    base04 = palette.menderBright,
    base05 = palette.menderLightest,
    base06 = palette.paleDim,
    base07 = palette.paleCore,
    base08 = palette.markBright,
    base09 = palette.markMid,
    base0A = palette.markDeep,
    base0B = palette.menderLighter,
    base0C = palette.markPulse,
    base0D = palette.menderMid,
    base0E = palette.markPulse,
    base0F = palette.menderMid,
  },
  palette = palette,
  get = M.get,
}
