local color = require("prismpunk.utils.color")

local palette = {
  silkVoid = "#0A0A0F",
  silkDark = "#121218",
  silkDeep = "#1A1A22",
  silkMid = "#22222A",
  silkLight = "#2A2A32",
  silkShadow = "#0E0E14",
  silkEcho = "#1E1E28",
  silkTint = "#262630",
  threadDeep = "#32323A",
  threadMid = "#3A3A42",
  threadLine = "#42424A",
  threadRidge = "#484852",
  threadSoft = "#504E5A",
  threadGlow = "#5A5868",
  threadVivid = "#646278",
  weaveDeep = "#4A4A52",
  weaveMid = "#555560",
  weaveBright = "#606070",
  weaveLighter = "#6B7080",
  weaveLightest = "#7A8090",
  weaveGlow = "#8890A0",
  weaveVivid = "#94A0B0",
  weavePeak = "#A0B0C0",
  fabricCore = "#D0C8D8",
  fabricBright = "#E8DCE8",
  fabricPeak = "#F5E8F5",
  fabricDim = "#B8B0C0",
  fabricSoft = "#C8C0D0",
  stitchDeep = "#3A3018",
  stitchMid = "#453A24",
  stitchBright = "#504530",
  stitchPulse = "#5A5038",
  stitchVivid = "#645A40",
  stitchGlow = "#6E6448",
  stitchGold = "#786E50",
  silkAccent1 = "#483C2A",
  silkAccent2 = "#524432",
  silkAccent3 = "#5C4C3A",
  silkAccent4 = "#665442",
  silkAccent5 = "#705C4A",

  bg_darkest = "#0A0A0F",
  fg_lightest = "#E8DCE8",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.weaveBright,
      insert = plt.weaveLighter,
      normal = plt.weaveBright,
      replace = plt.weaveMid,
      visual = plt.stitchPulse,
    },
    accent = {
      accent1 = plt.fabricBright,
      accent2 = plt.fabricCore,
      accent3 = plt.weaveLighter,
      accent4 = plt.weaveBright,
      accent5 = plt.stitchPulse,
      invert = plt.threadMid,
    },
    rainbow = {
      rainbow1 = plt.weaveBright,
      rainbow2 = plt.weaveMid,
      rainbow3 = plt.weaveDeep,
      rainbow4 = plt.threadDeep,
      rainbow5 = plt.fabricCore,
      rainbow6 = plt.fabricBright,
      rainbow7 = plt.stitchPulse,
    },
    ui = {
      bg = plt.silkVoid,
      bg_cursorline = plt.threadLine,
      bg_dim = plt.silkVoid,
      bg_gutter = opts.gutter and plt.silkMid or "none",
      bg_highlight = plt.threadDeep,
      bg_m1 = plt.silkDark,
      bg_m2 = plt.silkDeep,
      bg_m3 = plt.silkMid,
      bg_m4 = plt.silkLight,
      bg_p1 = plt.silkDeep,
      bg_p2 = plt.silkMid,
      bg_statusline = plt.threadMid,
      bg_visual = plt.stitchDeep,
      border = plt.weaveMid,
      cursorline = plt.threadLine,
      fg = plt.fabricCore,
      fg_dim = plt.fabricDim,
      fg_reverse = plt.silkVoid,
      indent = plt.silkMid,
      line_nr = plt.weaveDeep,
      line_nr_active = plt.fabricCore,
      line_nr_dim = plt.weaveMid,
      nontext = plt.silkLight,
      selection = plt.stitchDeep,
      win_separator = plt.weaveMid,
      float = {
        bg = plt.silkDeep,
        bg_border = plt.silkDeep,
        fg = plt.fabricCore,
        fg_border = plt.threadMid,
      },
      pmenu = {
        bg = plt.threadMid,
        bg_border = plt.threadMid,
        bg_sbar = plt.threadMid,
        bg_sel = plt.threadDeep,
        bg_thumb = plt.weaveMid,
        fg = plt.fabricCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.silkVoid,
        bg_inactive = plt.silkVoid,
        bg_selected = plt.threadMid,
        fg_inactive = plt.weaveLighter,
        fg_selected = plt.fabricCore,
      },
    },
    syn = {
      attribute = plt.fabricCore,
      boolean = plt.stitchBright,
      comment = plt.weaveBright,
      constant = plt.weaveLightest,
      deprecated = plt.weaveMid,
      func = plt.fabricBright,
      identifier = plt.fabricCore,
      keyword = plt.fabricCore,
      method = plt.fabricBright,
      number = plt.weaveLightest,
      operator = plt.weaveMid,
      parameter = plt.weaveLighter,
      preproc = plt.stitchMid,
      punct = plt.weaveMid,
      regex = plt.weaveMid,
      special = plt.stitchPulse,
      statement = plt.fabricCore,
      string = plt.weaveLighter,
      symbol = plt.fabricCore,
      type = plt.weaveLightest,
      variable = plt.fabricCore,
    },
    diag = {
      error = plt.stitchBright,
      hint = plt.weaveMid,
      info = plt.weaveBright,
      ok = plt.weaveLighter,
      warning = plt.stitchPulse,
      virtual_text_error = plt.stitchMid,
      virtual_text_hint = plt.weaveDeep,
      virtual_text_info = plt.weaveMid,
      virtual_text_ok = plt.weaveLighter,
      virtual_text_warning = plt.stitchPulse,
    },
    diff = {
      add = plt.weaveLighter,
      add_inline = plt.weaveGlow,
      change = plt.weaveDeep,
      change_inline = plt.weaveBright,
      delete = plt.stitchBright,
      delete_inline = plt.stitchPulse,
      text = plt.stitchMid,
    },
    vcs = {
      added = plt.weaveLighter,
      changed = plt.stitchMid,
      removed = plt.stitchBright,
    },
    term = {
      black = plt.silkVoid,
      black_bright = color(plt.silkVoid):brighten(0.4):to_hex(),
      blue = plt.weaveMid,
      blue_bright = plt.weaveBright,
      cyan = plt.weaveLighter,
      cyan_bright = plt.weaveGlow,
      green = plt.weaveBright,
      green_bright = plt.weaveVivid,
      magenta = plt.stitchPulse,
      magenta_bright = plt.stitchGlow,
      red = plt.stitchBright,
      red_bright = plt.stitchPulse,
      white = plt.fabricCore,
      white_bright = plt.fabricBright,
      yellow = plt.weaveLightest,
      yellow_bright = plt.fabricPeak,
    },
  }
end

return {
  name = "Detox: Silk",
  author = "PrismPunk.nvim",
  description = "Soft textile folds. Gentle tension. Thread gold stitching. Tactile serenity.",
  base16 = {
    base00 = palette.silkVoid,
    base01 = palette.silkDark,
    base02 = palette.silkDeep,
    base03 = palette.silkMid,
    base04 = palette.weaveBright,
    base05 = palette.weaveLightest,
    base06 = palette.fabricDim,
    base07 = palette.fabricCore,
    base08 = palette.stitchBright,
    base09 = palette.stitchMid,
    base0A = palette.stitchDeep,
    base0B = palette.weaveLighter,
    base0C = palette.stitchPulse,
    base0D = palette.weaveMid,
    base0E = palette.stitchPulse,
    base0F = palette.weaveMid,
  },
  palette = palette,
  get = M.get,
}
