local palette = require("prismpunk.palettes.dc.watchmen.nite-owl")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.owlBrownCore,
      insert = plt.nightVisionCore,
      visual = plt.nightPurpleCore,
      replace = plt.dangerRedCore,
      command = plt.twilightVioletCore,
    },
    accent = {
      accent1 = plt.nightPurpleCore,
      accent2 = plt.dangerRedCore,
      accent3 = plt.amberGlowCore,
      accent4 = plt.twilightVioletCore,
      accent5 = plt.owlshipMagentaCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.nightPurpleBright,
      rainbow2 = plt.crimsonAlertBright,
      rainbow3 = plt.amberGlowBright,
      rainbow4 = plt.nightVisionBright,
      rainbow5 = plt.twilightVioletBright,
      rainbow6 = plt.owlshipMagentaBright,
      rainbow7 = plt.owlBrownBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darker,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_darkest,
      bg_m3 = plt.bg_alt3,
      bg_m4 = plt.bg_alt4,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.nightPurpleDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.owlGray,
      header1 = plt.nightPurpleBright,
      header2 = plt.crimsonAlertBright,
      special = plt.owlshipMagenta,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.owlGray,
      indent = plt.bg_lighter,
      indent_scope = plt.nightPurpleCore,
      picker = plt.twilightViolet,
      yank = plt.nightVisionBright,
      mark = plt.owlshipMagenta,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.owlGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.owlGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.owlGray,
        bg_border = plt.bg_darker,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.nightPurpleBright,
        indicator = plt.nightPurpleCore,
      },
    },
    syn = {
      attribute = plt.owlshipMagenta,
      boolean = plt.twilightViolet,
      comment = plt.owlGray,
      constant = plt.vintageMap,
      deprecated = plt.owlGrayDark,
      func = plt.nightVisionCore,
      identifier = plt.fg_lightest,
      keyword = plt.nightPurpleCore,
      method = plt.nightVisionBright,
      number = plt.vintageMap,
      operator = plt.crimsonAlertCore,
      parameter = plt.fg_mid,
      preproc = plt.twilightVioletCore,
      punct = plt.fg_dark,
      regex = plt.owlshipMagenta,
      special = plt.owlshipMagenta,
      special2 = plt.twilightViolet,
      special3 = plt.crimsonAlert,
      statement = plt.nightPurpleCore,
      string = plt.nightVisionCore,
      symbol = plt.amberGlow,
      type = plt.tacticalOliveCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.owlshipMagenta,
      ok = plt.successGreen,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_hint = plt.owlshipMagenta,
      virtual_text_ok = plt.successGreen,
    },
    diff = {
      add = plt.nightVisionCore,
      add_inline = plt.nightVisionDeep,
      change = plt.amberGlowCore,
      change_inline = plt.amberGlowDeep,
      delete = plt.dangerRedCore,
      delete_inline = plt.dangerRedDeep,
      text = plt.owlshipMagenta,
    },
    vcs = {
      added = plt.nightVisionCore,
      changed = plt.amberGlowCore,
      removed = plt.dangerRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.dangerRedCore,
      green = plt.nightVisionCore,
      yellow = plt.amberGlowCore,
      blue = plt.techBlueCore,
      magenta = plt.nightPurpleCore,
      cyan = plt.blueprintCyanCore,
      white = plt.vintageMapCore,
      black_bright = plt.bg_dark,
      red_bright = plt.dangerRedBright,
      green_bright = plt.nightVisionBright,
      yellow_bright = plt.amberGlowBright,
      blue_bright = plt.techBlueBright,
      magenta_bright = plt.nightPurpleBright,
      cyan_bright = plt.blueprintCyanBright,
      white_bright = plt.vintageMapBright,
      indexed1 = plt.crimsonAlert,
      indexed2 = plt.nightPurple,
    },
  }
end

return {
  name = "Watchmen – Nite Owl",
  author = "PrismPunk.nvim",
  description = "Tech-savvy nostalgia — warm browns, purple mysteries, crimson alerts, and night-vision green.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.owlGray,
    base04 = palette.owlGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dangerRedCore,
    base09 = palette.crimsonAlertCore,
    base0A = palette.amberGlowCore,
    base0B = palette.nightVisionCore,
    base0C = palette.blueprintCyanCore,
    base0D = palette.twilightVioletCore,
    base0E = palette.nightPurpleCore,
    base0F = palette.owlshipMagentaCore,
  },
  palette = palette,
  get = M.get,
}
