local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.watchmen.silk-spectre")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.champagneGoldCore,
      insert = plt.silkPinkCore,
      normal = plt.velvetPurpleCore,
      replace = plt.lipstickRedCore,
      visual = plt.neonPinkCore,
    },
    accent = {
      accent1 = plt.silkPinkCore,
      accent2 = plt.velvetPurpleCore,
      accent3 = plt.champagneGoldCore,
      accent4 = plt.neonPinkCore,
      accent5 = plt.empowermentCyanCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.silkPinkBright,
      rainbow2 = plt.velvetPurpleBright,
      rainbow3 = plt.champagneGoldBright,
      rainbow4 = plt.neonPinkBright,
      rainbow5 = plt.empowermentCyanBright,
      rainbow6 = plt.lipstickRedBright,
      rainbow7 = plt.midnightVioletBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_dim = plt.bg_darker,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_darkest,
      bg_m3 = plt.bg_alt3,
      bg_m4 = plt.bg_alt4,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_search = plt.seductionMagentaDeep,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.noirGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dark = plt.fg_dark,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_reverse = plt.bg_alt1,
      header1 = plt.champagneGoldBright,
      header2 = plt.silkPinkBright,
      indent = plt.bg_lighter,
      indent_scope = plt.velvetPurpleCore,
      line_nr = plt.noirGrayDark,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.shadowPurple,
      mark = plt.seductionMagenta,
      nontext = plt.bg_lightest,
      picker = plt.neonPink,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      special = plt.empowermentCyan,
      whitespace = plt.bg_lightest,
      win_separator = plt.noirGray,
      yank = plt.champagneGoldBright,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.noirGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.noirGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_alternate = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_alternate = plt.silkPinkBright,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        indicator = plt.velvetPurpleCore,
      },
    },
    syn = {
      attribute = plt.champagneGold,
      boolean = plt.empowermentCyan,
      comment = plt.noirGray,
      constant = plt.laceWhite,
      deprecated = plt.noirGrayDark,
      func = plt.silkPinkCore,
      identifier = plt.fg_lightest,
      keyword = plt.velvetPurpleCore,
      method = plt.silkPinkBright,
      number = plt.laceWhite,
      operator = plt.neonPinkCore,
      parameter = plt.fg_mid,
      preproc = plt.midnightVioletCore,
      punct = plt.fg_dark,
      regex = plt.seductionMagenta,
      special = plt.neonPink,
      special2 = plt.empowermentCyan,
      special3 = plt.champagneGold,
      statement = plt.velvetPurpleCore,
      string = plt.silkPinkCore,
      symbol = plt.champagneGold,
      type = plt.empowermentCyanCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      hint = plt.empowermentCyan,
      info = plt.infoBlue,
      ok = plt.successGreen,
      virtual_text_error = plt.lipstickRedDeep,
      virtual_text_hint = plt.empowermentCyanDeep,
      virtual_text_info = plt.independenceBlueDeep,
      virtual_text_ok = plt.successGreen,
      virtual_text_warning = plt.strengthAmberDeep,
      warning = plt.warningAmber,
    },
    diff = {
      add = plt.successGreen,
      add_inline = plt.empowermentCyanBright,
      change = plt.strengthAmberCore,
      change_inline = plt.champagneGoldDeep,
      delete = plt.lipstickRedCore,
      delete_inline = plt.lipstickRedBright,
      text = plt.empowermentCyan,
    },
    vcs = {
      added = plt.successGreen,
      changed = plt.strengthAmberCore,
      removed = plt.lipstickRedCore,
    },
    term = {
      black = plt.bg_darkest,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      blue = plt.independenceBlueCore,
      blue_bright = color(plt.independenceBlueBright):brighten(0.15):to_hex(),
      cyan = plt.empowermentCyanCore,
      cyan_bright = color(plt.empowermentCyanBright):brighten(0.15):to_hex(),
      green = plt.successGreen,
      green_bright = color(plt.successGreen):brighten(0.2):to_hex(),
      indexed1 = plt.neonPink,
      indexed2 = plt.champagneGold,
      magenta = plt.velvetPurpleCore,
      magenta_bright = color(plt.velvetPurpleBright):brighten(0.15):to_hex(),
      red = plt.lipstickRedCore,
      red_bright = color(plt.lipstickRedBright):brighten(0.15):to_hex(),
      white = plt.laceWhiteCore,
      white_bright = color(plt.laceWhiteBright):brighten(0.1):to_hex(),
      yellow = plt.champagneGoldCore,
      yellow_bright = color(plt.champagneGoldBright):brighten(0.15):to_hex(),
    },
  }
end

return {
  name = "Watchmen – Silk Spectre",
  author = "PrismPunk.nvim",
  description = "Feminine power and elegance — silk pink, velvet purple, champagne gold, neon rebellion.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.noirGray,
    base04 = palette.noirGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.lipstickRedCore,
    base09 = palette.strengthAmberCore,
    base0A = palette.champagneGoldCore,
    base0B = palette.silkPinkCore,
    base0C = palette.empowermentCyanCore,
    base0D = palette.independenceBlueCore,
    base0E = palette.velvetPurpleCore,
    base0F = palette.seductionMagentaCore,
  },
  palette = palette,
  get = M.get,
}
