local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0E1A",
  kent_night = "#0D1322",
  farm_core = "#121A2E",
  sunrise_glow = "#182540",
  superboy_blue = "#0077FF",
  jon_blue = "#0088FF",
  hope_sky = "#0099FF",
  tomorrow_blue = "#44BBFF",
  kent_red = "#DD2233",
  superboy_red = "#EE3344",
  farm_barn_red = "#FF4455",
  heart_red = "#FF6677",
  sunrise_gold = "#FFBB00",
  jon_gold = "#FFCC22",
  wheat_field = "#FFDD44",
  tomorrow_gold = "#FFEE66",
  jon_skin = "#FFEEEE",
  smallville_cream = "#FFDDDD",
  morning_light = "#FFEEFF",
  term_blue = "#0088FF",
  term_red = "#EE3344",
  term_gold = "#FFCC22",
  term_cream = "#FFDDDD",
  term_blue_bright = "#44BBFF",
  term_red_bright = "#FF6677",
  term_gold_bright = "#FFEE66",

  bg_darkest = "#0A0E1A",
  fg_lightest = "#FFEEFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.jon_blue,
      insert = plt.sunrise_gold,
      visual = plt.superboy_red,
      replace = plt.farm_barn_red,
      command = plt.tomorrow_blue,
    },

    ui = {
      fg = plt.jon_skin,
      fg_dim = plt.smallville_cream,
      fg_dimmer = plt.morning_light,
      fg_dark = plt.hope_sky,
      fg_reverse = plt.void_black,

      bg_m4 = plt.sunrise_glow,
      bg_m3 = plt.farm_core,
      bg_m2 = plt.kent_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.kent_night,
      bg_p2 = plt.farm_core,
      bg_gutter = opts.gutter and plt.farm_core or "none",
      bg_cursorline = plt.farm_core,
      bg_cursorline_alt = plt.kent_night,
      bg_search = plt.wheat_field,
      bg_visual = plt.superboy_red,
      bg_statusline = plt.farm_core,

      border = plt.tomorrow_gold,
      header1 = plt.jon_blue,
      header2 = plt.superboy_red,
      special = plt.sunrise_gold,
      nontext = plt.kent_night,
      whitespace = plt.sunrise_glow,
      win_separator = plt.tomorrow_gold,
      indent = plt.kent_night,
      indent_scope = plt.hope_sky,
      picker = plt.jon_skin,
      yank = plt.farm_barn_red,
      mark = plt.heart_red,
      scrollbar = plt.farm_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.jon_skin,
        bg_selected = plt.farm_core,
        fg_inactive = plt.smallville_cream,
        bg_inactive = plt.void_black,
        fg_alternate = plt.sunrise_gold,
        bg_alternate = plt.void_black,
        indicator = plt.superboy_red,
      },

      pmenu = {
        fg = plt.jon_skin,
        fg_sel = "none",
        fg_border = plt.farm_core,
        bg_border = plt.farm_core,
        bg = plt.farm_core,
        bg_sel = plt.kent_night,
        bg_sbar = plt.farm_core,
        bg_thumb = plt.tomorrow_gold,
      },

      float = {
        fg = plt.jon_skin,
        bg = plt.kent_night,
        fg_border = plt.farm_core,
        bg_border = plt.kent_night,
      },
    },

    accent = {
      accent1 = plt.jon_blue,
      accent2 = plt.superboy_red,
      accent3 = plt.sunrise_gold,
      accent4 = plt.tomorrow_blue,
      accent5 = plt.farm_barn_red,
      invert = plt.farm_core,
    },

    rainbow = {
      rainbow1 = plt.jon_blue,
      rainbow2 = plt.hope_sky,
      rainbow3 = plt.tomorrow_blue,
      rainbow4 = plt.superboy_red,
      rainbow5 = plt.heart_red,
      rainbow6 = plt.sunrise_gold,
      rainbow7 = plt.wheat_field,
    },

    syn = {
      attribute = plt.jon_skin,
      boolean = plt.superboy_red,
      comment = plt.smallville_cream,
      constant = plt.tomorrow_gold,
      deprecated = plt.sunrise_glow,
      func = plt.jon_blue,
      identifier = plt.jon_skin,
      keyword = plt.jon_blue,
      method = plt.sunrise_gold,
      number = plt.superboy_red,
      operator = plt.tomorrow_blue,
      parameter = plt.smallville_cream,
      preproc = plt.farm_barn_red,
      punct = plt.morning_light,
      regex = plt.hope_sky,
      statement = plt.jon_blue,
      string = plt.wheat_field,
      symbol = plt.jon_skin,
      type = plt.superboy_red,
      variable = plt.jon_skin,
      special = plt.wheat_field,
      special2 = plt.tomorrow_blue,
      special3 = plt.heart_red,
    },

    vcs = { added = plt.tomorrow_blue, removed = plt.superboy_red, changed = plt.sunrise_gold },
    diff = { add = plt.tomorrow_blue, change = plt.hope_sky, delete = plt.farm_barn_red, text = plt.wheat_field },
    diag = {
      ok = plt.tomorrow_blue,
      error = plt.farm_barn_red,
      warning = plt.sunrise_gold,
      info = plt.jon_blue,
      hint = plt.hope_sky,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_gold,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_cream,
      white = plt.jon_skin,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_gold_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_cream,
      white_bright = "#ffffff",
      indexed1 = plt.jon_blue,
      indexed2 = plt.superboy_red,
    },

    treesitter = {
      ["@comment"] = plt.smallville_cream,
      ["@comment.documentation"] = plt.morning_light,
      ["@comment.error"] = plt.farm_barn_red,
      ["@comment.warning"] = plt.sunrise_gold,
      ["@comment.todo"] = plt.superboy_red,
      ["@comment.note"] = plt.tomorrow_blue,

      ["@constant"] = plt.tomorrow_gold,
      ["@constant.builtin"] = plt.tomorrow_gold,
      ["@constant.macro"] = plt.farm_barn_red,

      ["@string"] = plt.wheat_field,
      ["@string.documentation"] = plt.wheat_field,
      ["@string.regex"] = plt.hope_sky,
      ["@string.escape"] = plt.tomorrow_blue,
      ["@string.special"] = plt.superboy_red,
      ["@string.special.symbol"] = plt.jon_skin,
      ["@string.special.url"] = plt.sunrise_gold,
      ["@string.special.path"] = plt.wheat_field,

      ["@character"] = plt.wheat_field,
      ["@character.special"] = plt.tomorrow_blue,

      ["@number"] = plt.superboy_red,
      ["@number.float"] = plt.superboy_red,

      ["@boolean"] = plt.farm_barn_red,

      ["@function"] = plt.jon_blue,
      ["@function.builtin"] = plt.jon_blue,
      ["@function.call"] = plt.jon_blue,
      ["@function.macro"] = plt.sunrise_gold,
      ["@function.method"] = plt.sunrise_gold,
      ["@function.method.call"] = plt.sunrise_gold,

      ["@constructor"] = plt.jon_skin,

      ["@parameter"] = plt.smallville_cream,
      ["@parameter.builtin"] = plt.jon_skin,

      ["@keyword"] = plt.jon_blue,
      ["@keyword.coroutine"] = plt.superboy_red,
      ["@keyword.function"] = plt.jon_blue,
      ["@keyword.operator"] = plt.tomorrow_blue,
      ["@keyword.return"] = plt.jon_blue,
      ["@keyword.import"] = plt.wheat_field,
      ["@keyword.storage"] = plt.jon_blue,
      ["@keyword.repeat"] = plt.jon_blue,
      ["@keyword.conditional"] = plt.jon_blue,
      ["@keyword.exception"] = plt.wheat_field,
      ["@keyword.directive"] = plt.superboy_red,
      ["@keyword.directive.define"] = plt.superboy_red,

      ["@conditional"] = plt.jon_blue,
      ["@conditional.ternary"] = plt.jon_blue,

      ["@repeat"] = plt.jon_blue,

      ["@label"] = plt.sunrise_gold,

      ["@operator"] = plt.tomorrow_blue,

      ["@exception"] = plt.wheat_field,

      ["@variable"] = plt.jon_skin,
      ["@variable.builtin"] = plt.morning_light,
      ["@variable.parameter"] = plt.smallville_cream,
      ["@variable.member"] = plt.jon_skin,

      ["@type"] = plt.superboy_red,
      ["@type.builtin"] = plt.superboy_red,
      ["@type.definition"] = plt.superboy_red,
      ["@type.qualifier"] = plt.jon_blue,

      ["@attribute"] = plt.jon_skin,
      ["@attribute.builtin"] = plt.superboy_red,

      ["@property"] = plt.jon_skin,
      ["@field"] = plt.jon_skin,
      ["@module"] = plt.jon_skin,
      ["@module.builtin"] = plt.jon_skin,
      ["@namespace"] = plt.jon_skin,
      ["@namespace.builtin"] = plt.jon_skin,

      ["@punctuation.delimiter"] = plt.morning_light,
      ["@punctuation.bracket"] = plt.hope_sky,
      ["@punctuation.special"] = plt.tomorrow_blue,

      ["@tag"] = plt.jon_blue,
      ["@tag.attribute"] = plt.superboy_red,
      ["@tag.delimiter"] = plt.morning_light,
      ["@tag.builtin"] = plt.jon_blue,

      ["@markup.strong"] = { fg = plt.jon_blue, bold = true },
      ["@markup.italic"] = { fg = plt.jon_skin, italic = true },
      ["@markup.strikethrough"] = { fg = plt.sunrise_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.superboy_red, underline = true },
      ["@markup.heading"] = plt.jon_blue,
      ["@markup.heading.1"] = plt.jon_blue,
      ["@markup.heading.2"] = plt.superboy_red,
      ["@markup.heading.3"] = plt.sunrise_gold,
      ["@markup.heading.4"] = plt.tomorrow_blue,
      ["@markup.heading.5"] = plt.hope_sky,
      ["@markup.heading.6"] = plt.wheat_field,
      ["@markup.quote"] = plt.smallville_cream,
      ["@markup.math"] = plt.tomorrow_blue,
      ["@markup.link"] = plt.sunrise_gold,
      ["@markup.link.label"] = plt.wheat_field,
      ["@markup.link.url"] = plt.tomorrow_blue,
      ["@markup.raw"] = plt.wheat_field,
      ["@markup.raw.block"] = plt.wheat_field,
      ["@markup.list"] = plt.jon_blue,
      ["@markup.list.checked"] = plt.tomorrow_blue,
      ["@markup.list.unchecked"] = plt.smallville_cream,

      ["@diff.plus"] = plt.tomorrow_blue,
      ["@diff.minus"] = plt.superboy_red,
      ["@diff.delta"] = plt.sunrise_gold,

      ["@none"] = "none",
      ["@conceal"] = plt.morning_light,
      ["@spell"] = plt.jon_skin,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.jon_skin,
      ["@constructor.python"] = plt.jon_blue,
      ["@constructor.javascript"] = plt.jon_blue,
      ["@constructor.typescript"] = plt.jon_blue,
      ["@namespace.rust"] = plt.jon_skin,
      ["@type.qualifier.rust"] = plt.jon_blue,
      ["@constant.macro.c"] = plt.farm_barn_red,
      ["@constant.macro.cpp"] = plt.farm_barn_red,
      ["@namespace.go"] = plt.jon_skin,
      ["@property.css"] = plt.sunrise_gold,
      ["@type.css"] = plt.jon_blue,
      ["@label.json"] = plt.jon_skin,
      ["@field.yaml"] = plt.smallville_cream,
      ["@property.toml"] = plt.smallville_cream,
      ["@function.builtin.bash"] = plt.sunrise_gold,
      ["@string.regexp"] = plt.hope_sky,
      ["@character.special.regex"] = plt.tomorrow_blue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.superboy_red,
      ["@lsp.type.interface"] = plt.superboy_red,
      ["@lsp.type.struct"] = plt.superboy_red,
      ["@lsp.type.enum"] = plt.superboy_red,
      ["@lsp.type.enumMember"] = plt.tomorrow_gold,
      ["@lsp.type.property"] = plt.jon_skin,
      ["@lsp.type.namespace"] = plt.jon_skin,

      ["@lsp.type.macro"] = plt.farm_barn_red,
      ["@lsp.type.decorator"] = plt.jon_blue,

      ["@lsp.type.builtinType"] = plt.superboy_red,
      ["@lsp.type.selfParameter"] = plt.jon_blue,
      ["@lsp.type.typeParameter"] = plt.superboy_red,

      ["@lsp.type.array"] = plt.superboy_red,
      ["@lsp.type.object"] = plt.superboy_red,
      ["@lsp.type.key"] = plt.jon_skin,
      ["@lsp.type.null"] = plt.tomorrow_gold,
      ["@lsp.type.enumConstant"] = plt.tomorrow_gold,

      ["@lsp.type.event"] = plt.superboy_red,
      ["@lsp.type.regexp"] = plt.hope_sky,
      ["@lsp.type.unresolvedReference"] = plt.farm_barn_red,

      ["@lsp.mod.deprecated"] = { fg = plt.sunrise_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.tomorrow_gold,
      ["@lsp.mod.async"] = plt.jon_blue,
      ["@lsp.mod.static"] = plt.superboy_red,
      ["@lsp.mod.abstract"] = plt.superboy_red,
      ["@lsp.mod.defaultLibrary"] = plt.superboy_red,
      ["@lsp.mod.documentation"] = plt.smallville_cream,
    },
  }
end

return {
  name = "Jonathan Kent – Superboy Tomorrow",
  author = "PrismPunk.nvim",
  description = "He’s still got homework, chores, and a curfew — but when the world needs saving, "
    .. "he’s there with a brighter blue, a warmer red, and the biggest heart in the universe.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.kent_night,
    base02 = palette.farm_core,
    base03 = palette.sunrise_glow,
    base04 = palette.morning_light,
    base05 = palette.smallville_cream,
    base06 = palette.jon_skin,
    base07 = palette.jon_skin,
    base08 = palette.superboy_red,
    base09 = palette.kent_red,
    base0A = palette.sunrise_gold,
    base0B = palette.wheat_field,
    base0C = palette.jon_blue,
    base0D = palette.tomorrow_blue,
    base0E = palette.hope_sky,
    base0F = palette.tomorrow_gold,
  },

  palette = palette,
  get = M.get,
}
