local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0C10",
  steel_night = "#0D1116",
  forge_core = "#12181F",
  hammer_glow = "#18202A",
  gunmetal = "#1E242E",
  riveted_steel = "#283040",
  battleship_gray = "#354050",
  polished_steel = "#506070",
  steel_red = "#CC1122",
  hammer_red = "#DD2233",
  kinetic_red = "#EE3344",
  metropolis_red = "#FF5566",
  star_white = "#EEF2FF",
  flag_blue = "#002244",
  liberty_blue = "#003366",
  steel_sky = "#335588",
  term_red = "#DD2233",
  term_blue = "#335588",
  term_white = "#EEF2FF",
  term_red_bright = "#FF5566",
  term_blue_bright = "#5588CC",

  bg_darkest = "#0A0C10",
  fg_lightest = "#EEF2FF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.hammer_red,
      insert = plt.polished_steel,
      visual = plt.kinetic_red,
      replace = plt.metropolis_red,
      command = plt.flag_blue,
    },

    ui = {
      fg = plt.star_white,
      fg_dim = plt.polished_steel,
      fg_dimmer = plt.battleship_gray,
      fg_dark = plt.liberty_blue,
      fg_reverse = plt.void_black,

      bg_m4 = plt.hammer_glow,
      bg_m3 = plt.forge_core,
      bg_m2 = plt.steel_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.steel_night,
      bg_p2 = plt.forge_core,
      bg_gutter = opts.gutter and plt.forge_core or "none",
      bg_cursorline = plt.forge_core,
      bg_cursorline_alt = plt.steel_night,
      bg_search = plt.metropolis_red,
      bg_visual = plt.kinetic_red,
      bg_statusline = plt.forge_core,

      border = plt.star_white,
      header1 = plt.hammer_red,
      header2 = plt.flag_blue,
      special = plt.steel_sky,
      nontext = plt.steel_night,
      whitespace = plt.hammer_glow,
      win_separator = plt.star_white,
      indent = plt.steel_night,
      indent_scope = plt.riveted_steel,
      picker = plt.star_white,
      yank = plt.metropolis_red,
      mark = plt.kinetic_red,
      scrollbar = plt.forge_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.star_white,
        bg_selected = plt.forge_core,
        fg_inactive = plt.battleship_gray,
        bg_inactive = plt.void_black,
        fg_alternate = plt.hammer_red,
        bg_alternate = plt.void_black,
        indicator = plt.flag_blue,
      },

      pmenu = {
        fg = plt.star_white,
        fg_sel = "none",
        fg_border = plt.forge_core,
        bg_border = plt.forge_core,
        bg = plt.forge_core,
        bg_sel = plt.steel_night,
        bg_sbar = plt.forge_core,
        bg_thumb = plt.star_white,
      },

      float = {
        fg = plt.star_white,
        bg = plt.steel_night,
        fg_border = plt.forge_core,
        bg_border = plt.steel_night,
      },
    },

    accent = {
      accent1 = plt.hammer_red,
      accent2 = plt.flag_blue,
      accent3 = plt.polished_steel,
      accent4 = plt.kinetic_red,
      accent5 = plt.steel_sky,
      invert = plt.forge_core,
    },

    rainbow = {
      rainbow1 = plt.hammer_red,
      rainbow2 = plt.kinetic_red,
      rainbow3 = plt.metropolis_red,
      rainbow4 = plt.flag_blue,
      rainbow5 = plt.liberty_blue,
      rainbow6 = plt.steel_sky,
      rainbow7 = plt.polished_steel,
    },

    syn = {
      attribute = plt.star_white,
      boolean = plt.kinetic_red,
      comment = plt.battleship_gray,
      constant = plt.polished_steel,
      deprecated = plt.hammer_glow,
      func = plt.hammer_red,
      identifier = plt.star_white,
      keyword = plt.hammer_red,
      method = plt.flag_blue,
      number = plt.metropolis_red,
      operator = plt.steel_sky,
      parameter = plt.battleship_gray,
      preproc = plt.kinetic_red,
      punct = plt.polished_steel,
      regex = plt.steel_sky,
      statement = plt.hammer_red,
      string = plt.polished_steel,
      symbol = plt.star_white,
      type = plt.flag_blue,
      variable = plt.star_white,
      special = plt.metropolis_red,
      special2 = plt.steel_sky,
      special3 = plt.kinetic_red,
    },

    vcs = { added = plt.steel_sky, removed = plt.kinetic_red, changed = plt.flag_blue },
    diff = { add = plt.steel_sky, change = plt.polished_steel, delete = plt.metropolis_red, text = plt.hammer_red },
    diag = {
      ok = plt.steel_sky,
      error = plt.kinetic_red,
      warning = plt.hammer_red,
      info = plt.flag_blue,
      hint = plt.polished_steel,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_white,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_white,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.hammer_red,
      indexed2 = plt.flag_blue,
    },

    treesitter = {
      ["@comment"] = plt.battleship_gray,
      ["@comment.documentation"] = plt.polished_steel,
      ["@comment.error"] = plt.kinetic_red,
      ["@comment.warning"] = plt.hammer_red,
      ["@comment.todo"] = plt.metropolis_red,
      ["@comment.note"] = plt.steel_sky,

      ["@constant"] = plt.polished_steel,
      ["@constant.builtin"] = plt.polished_steel,
      ["@constant.macro"] = plt.metropolis_red,

      ["@string"] = plt.polished_steel,
      ["@string.documentation"] = plt.polished_steel,
      ["@string.regex"] = plt.steel_sky,
      ["@string.escape"] = plt.flag_blue,
      ["@string.special"] = plt.kinetic_red,
      ["@string.special.symbol"] = plt.star_white,
      ["@string.special.url"] = plt.flag_blue,
      ["@string.special.path"] = plt.polished_steel,

      ["@character"] = plt.polished_steel,
      ["@character.special"] = plt.flag_blue,

      ["@number"] = plt.metropolis_red,
      ["@number.float"] = plt.metropolis_red,

      ["@boolean"] = plt.kinetic_red,

      ["@function"] = plt.hammer_red,
      ["@function.builtin"] = plt.hammer_red,
      ["@function.call"] = plt.hammer_red,
      ["@function.macro"] = plt.flag_blue,
      ["@function.method"] = plt.flag_blue,
      ["@function.method.call"] = plt.flag_blue,

      ["@constructor"] = plt.star_white,

      ["@parameter"] = plt.battleship_gray,
      ["@parameter.builtin"] = plt.star_white,

      ["@keyword"] = plt.hammer_red,
      ["@keyword.coroutine"] = plt.kinetic_red,
      ["@keyword.function"] = plt.hammer_red,
      ["@keyword.operator"] = plt.steel_sky,
      ["@keyword.return"] = plt.hammer_red,
      ["@keyword.import"] = plt.steel_sky,
      ["@keyword.storage"] = plt.hammer_red,
      ["@keyword.repeat"] = plt.hammer_red,
      ["@keyword.conditional"] = plt.hammer_red,
      ["@keyword.exception"] = plt.metropolis_red,
      ["@keyword.directive"] = plt.kinetic_red,
      ["@keyword.directive.define"] = plt.kinetic_red,

      ["@conditional"] = plt.hammer_red,
      ["@conditional.ternary"] = plt.hammer_red,

      ["@repeat"] = plt.hammer_red,

      ["@label"] = plt.flag_blue,

      ["@operator"] = plt.steel_sky,

      ["@exception"] = plt.metropolis_red,

      ["@variable"] = plt.star_white,
      ["@variable.builtin"] = plt.polished_steel,
      ["@variable.parameter"] = plt.battleship_gray,
      ["@variable.member"] = plt.star_white,

      ["@type"] = plt.flag_blue,
      ["@type.builtin"] = plt.flag_blue,
      ["@type.definition"] = plt.flag_blue,
      ["@type.qualifier"] = plt.hammer_red,

      ["@attribute"] = plt.star_white,
      ["@attribute.builtin"] = plt.flag_blue,

      ["@property"] = plt.star_white,
      ["@field"] = plt.star_white,
      ["@module"] = plt.star_white,
      ["@module.builtin"] = plt.star_white,
      ["@namespace"] = plt.star_white,
      ["@namespace.builtin"] = plt.star_white,

      ["@punctuation.delimiter"] = plt.polished_steel,
      ["@punctuation.bracket"] = plt.riveted_steel,
      ["@punctuation.special"] = plt.steel_sky,

      ["@tag"] = plt.hammer_red,
      ["@tag.attribute"] = plt.flag_blue,
      ["@tag.delimiter"] = plt.polished_steel,
      ["@tag.builtin"] = plt.hammer_red,

      ["@markup.strong"] = { fg = plt.hammer_red, bold = true },
      ["@markup.italic"] = { fg = plt.star_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.hammer_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.kinetic_red, underline = true },
      ["@markup.heading"] = plt.hammer_red,
      ["@markup.heading.1"] = plt.hammer_red,
      ["@markup.heading.2"] = plt.kinetic_red,
      ["@markup.heading.3"] = plt.metropolis_red,
      ["@markup.heading.4"] = plt.flag_blue,
      ["@markup.heading.5"] = plt.liberty_blue,
      ["@markup.heading.6"] = plt.steel_sky,
      ["@markup.quote"] = plt.battleship_gray,
      ["@markup.math"] = plt.steel_sky,
      ["@markup.link"] = plt.flag_blue,
      ["@markup.link.label"] = plt.metropolis_red,
      ["@markup.link.url"] = plt.steel_sky,
      ["@markup.raw"] = plt.polished_steel,
      ["@markup.raw.block"] = plt.polished_steel,
      ["@markup.list"] = plt.hammer_red,
      ["@markup.list.checked"] = plt.steel_sky,
      ["@markup.list.unchecked"] = plt.battleship_gray,

      ["@diff.plus"] = plt.steel_sky,
      ["@diff.minus"] = plt.kinetic_red,
      ["@diff.delta"] = plt.flag_blue,

      ["@none"] = "none",
      ["@conceal"] = plt.polished_steel,
      ["@spell"] = plt.star_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.star_white,
      ["@constructor.python"] = plt.hammer_red,
      ["@constructor.javascript"] = plt.hammer_red,
      ["@constructor.typescript"] = plt.hammer_red,
      ["@namespace.rust"] = plt.star_white,
      ["@type.qualifier.rust"] = plt.hammer_red,
      ["@constant.macro.c"] = plt.metropolis_red,
      ["@constant.macro.cpp"] = plt.metropolis_red,
      ["@namespace.go"] = plt.star_white,
      ["@property.css"] = plt.flag_blue,
      ["@type.css"] = plt.hammer_red,
      ["@label.json"] = plt.star_white,
      ["@field.yaml"] = plt.battleship_gray,
      ["@property.toml"] = plt.battleship_gray,
      ["@function.builtin.bash"] = plt.flag_blue,
      ["@string.regexp"] = plt.steel_sky,
      ["@character.special.regex"] = plt.flag_blue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.flag_blue,
      ["@lsp.type.interface"] = plt.flag_blue,
      ["@lsp.type.struct"] = plt.flag_blue,
      ["@lsp.type.enum"] = plt.flag_blue,
      ["@lsp.type.enumMember"] = plt.polished_steel,
      ["@lsp.type.property"] = plt.star_white,
      ["@lsp.type.namespace"] = plt.star_white,

      ["@lsp.type.macro"] = plt.metropolis_red,
      ["@lsp.type.decorator"] = plt.hammer_red,

      ["@lsp.type.builtinType"] = plt.flag_blue,
      ["@lsp.type.selfParameter"] = plt.hammer_red,
      ["@lsp.type.typeParameter"] = plt.flag_blue,

      ["@lsp.type.array"] = plt.flag_blue,
      ["@lsp.type.object"] = plt.flag_blue,
      ["@lsp.type.key"] = plt.star_white,
      ["@lsp.type.null"] = plt.polished_steel,
      ["@lsp.type.enumConstant"] = plt.polished_steel,

      ["@lsp.type.event"] = plt.flag_blue,
      ["@lsp.type.regexp"] = plt.steel_sky,
      ["@lsp.type.unresolvedReference"] = plt.kinetic_red,

      ["@lsp.mod.deprecated"] = { fg = plt.hammer_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.polished_steel,
      ["@lsp.mod.async"] = plt.hammer_red,
      ["@lsp.mod.static"] = plt.flag_blue,
      ["@lsp.mod.abstract"] = plt.flag_blue,
      ["@lsp.mod.defaultLibrary"] = plt.flag_blue,
      ["@lsp.mod.documentation"] = plt.battleship_gray,
    },
  }
end

return {
  name = "Steel – John Henry Irons",
  author = "PrismPunk.nvim",
  description = "He built the armor himself. Forged the legend with his own hands. "
    .. "Steel-gray might, glowing red S, and the unbreakable heart of the man who stood up when Superman fell.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.steel_night,
    base02 = palette.forge_core,
    base03 = palette.hammer_glow,
    base04 = palette.riveted_steel,
    base05 = palette.battleship_gray,
    base06 = palette.polished_steel,
    base07 = palette.star_white,
    base08 = palette.kinetic_red,
    base09 = palette.hammer_red,
    base0A = palette.flag_blue,
    base0B = palette.liberty_blue,
    base0C = palette.steel_sky,
    base0D = palette.polished_steel,
    base0E = palette.metropolis_red,
    base0F = palette.hammer_red,
  },

  palette = palette,
  get = M.get,
}
