local color = require("prismpunk.utils.color")

describe("color.new", function()
  it("creates color object from hex", function()
    local c = color.new("#ff0000")
    assert.are.equal("#ff0000", c.hex)
    assert.is_table(c.rgb)
    assert.is_table(c.hsluv)
  end)

  it("normalizes hex without hash", function()
    local c = color.new("ff0000")
    assert.are.equal("#ff0000", c.hex)
  end)

  it("normalizes 3-char hex to 6-char", function()
    local c = color.new("#abc")
    assert.are.equal("#aabbcc", c.hex)
  end)

  it("handles uppercase hex", function()
    local c = color.new("#FF0000")
    assert.are.equal("#ff0000", c.hex)
  end)

  it("handles invalid input gracefully", function()
    local c = color.new("not-a-color")
    assert.are.equal("#000000", c.hex)
  end)

  it("handles nil input gracefully", function()
    local c = color.new(nil)
    assert.are.equal("#000000", c.hex)
  end)
end)

describe("color callable", function()
  it("works as color() shorthand", function()
    local c = color("#ff0000")
    assert.are.equal("#ff0000", c.hex)
  end)
end)

describe("color:brighten", function()
  it("increases lightness", function()
    local c = color("#333333")
    local brightened = c:brighten(0.3):to_hex()
    assert.is_true(brightened > "#333333")
  end)

  it("is chainable", function()
    local hex = color("#ff0000"):brighten(0.1):to_hex()
    assert.is_string(hex)
  end)

  it("clamps to max brightness", function()
    local c = color("#ffffff")
    local result = c:brighten(1.0):to_hex()
    assert.are.equal("#ffffff", result)
  end)

  it("accepts negative values to darken", function()
    local c = color("#ffffff")
    local result = c:brighten(-0.5):to_hex()
    assert.is_true(result < "#ffffff")
  end)
end)

describe("color:darken", function()
  it("decreases lightness", function()
    local c = color("#cccccc")
    local darkened = c:darken(0.3):to_hex()
    assert.is_true(darkened < "#cccccc")
  end)

  it("is chainable", function()
    local hex = color("#ff0000"):darken(0.1):to_hex()
    assert.is_string(hex)
  end)

  it("clamps to min darkness", function()
    local c = color("#000000")
    local result = c:darken(1.0):to_hex()
    assert.are.equal("#000000", result)
  end)
end)

describe("color:saturate", function()
  it("adjusts saturation", function()
    local c = color("#888888")
    local saturated = c:saturate(0.5):to_hex()
    assert.is_string(saturated)
  end)

  it("accepts negative values to desaturate", function()
    local c = color("#ff0000")
    local result = c:saturate(-0.5):to_hex()
    assert.is_string(result)
  end)

  it("is chainable", function()
    local hex = color("#ff0000"):saturate(0.2):to_hex()
    assert.is_string(hex)
  end)
end)

describe("color:rotate", function()
  it("rotates hue by degrees", function()
    local c = color("#ff0000")
    local rotated = c:rotate(180):to_hex()
    assert.is_string(rotated)
    assert.are_not.equal("#ff0000", rotated)
  end)

  it("wraps around 360 degrees", function()
    local c = color("#ff0000")
    local rotated = c:rotate(720):to_hex()
    assert.is_string(rotated)
  end)

  it("handles negative rotation", function()
    local c = color("#ff0000")
    local rotated = c:rotate(-90):to_hex()
    assert.is_string(rotated)
  end)

  it("is chainable", function()
    local hex = color("#ff0000"):rotate(45):to_hex()
    assert.is_string(hex)
  end)
end)

describe("color:to_hex", function()
  it("returns hex string", function()
    local hex = color("#ff0000"):to_hex()
    assert.are.equal("#ff0000", hex)
  end)
end)

describe("color:to_rgb", function()
  it("returns rgb table", function()
    local rgb = color("#ff0000"):to_rgb()
    assert.is_table(rgb)
    assert.are.equal(3, #rgb)
  end)

  it("returns values in 0-1 range", function()
    local rgb = color("#ff0000"):to_rgb()
    assert.is_true(rgb[1] >= 0 and rgb[1] <= 1)
    assert.is_true(rgb[2] >= 0 and rgb[2] <= 1)
    assert.is_true(rgb[3] >= 0 and rgb[3] <= 1)
  end)
end)

describe("color:to_hsluv", function()
  it("returns hsluv table", function()
    local hsluv = color("#ff0000"):to_hsluv()
    assert.is_table(hsluv)
    assert.are.equal(3, #hsluv)
  end)
end)

describe("color.blend", function()
  it("blends two colors", function()
    local result = color.blend("#ff0000", "#0000ff", 0.5)
    assert.is_string(result)
    assert.are_not.equal("#ff0000", result)
    assert.are_not.equal("#0000ff", result)
  end)

  it("alpha 0 returns first color", function()
    local result = color.blend("#ff0000", "#0000ff", 0)
    assert.are.equal("#ff0000", result)
  end)

  it("alpha 1 returns second color", function()
    local result = color.blend("#ff0000", "#0000ff", 1)
    assert.are.equal("#0000ff", result)
  end)

  it("defaults to 0.5 alpha", function()
    local result = color.blend("#ff0000", "#0000ff")
    assert.is_string(result)
  end)
end)

describe("color.brighten", function()
  it("brightens hex directly", function()
    local result = color.brighten("#333333", 0.3)
    assert.is_string(result)
    assert.is_true(result > "#333333")
  end)
end)

describe("color.darken", function()
  it("darkens hex directly", function()
    local result = color.darken("#cccccc", 0.3)
    assert.is_string(result)
    assert.is_true(result < "#cccccc")
  end)
end)

describe("color.hex_to_rgb", function()
  it("converts hex to rgb", function()
    local rgb = color.hex_to_rgb("#ff0000")
    assert.is_table(rgb)
    assert.are.equal(3, #rgb)
  end)
end)

describe("color.rgb_to_hex", function()
  it("converts rgb to hex", function()
    local hex = color.rgb_to_hex({ 1, 0, 0 })
    assert.are.equal("#ff0000", hex)
  end)

  it("roundtrips with hex_to_rgb", function()
    local original = "#ff8800"
    local rgb = color.hex_to_rgb(original)
    local hex = color.rgb_to_hex(rgb)
    assert.are.equal(original, hex)
  end)
end)

describe("color.get_luminance", function()
  it("returns number between 0 and 1", function()
    local lum = color.get_luminance("#ff0000")
    assert.is_number(lum)
    assert.is_true(lum >= 0 and lum <= 1)
  end)

  it("white has high luminance", function()
    local lum_white = color.get_luminance("#ffffff")
    local lum_black = color.get_luminance("#000000")
    assert.is_true(lum_white > lum_black)
  end)

  it("black has low luminance", function()
    local lum = color.get_luminance("#000000")
    assert.is_true(lum < 0.1)
  end)
end)

describe("color.calculate_contrast", function()
  it("returns contrast ratio", function()
    local lum1 = color.get_luminance("#ffffff")
    local lum2 = color.get_luminance("#000000")
    local contrast = color.calculate_contrast(lum1, lum2)
    assert.is_number(contrast)
    assert.is_true(contrast >= 1 and contrast <= 21)
  end)

  it("same color has contrast 1", function()
    local lum = color.get_luminance("#ff0000")
    local contrast = color.calculate_contrast(lum, lum)
    assert.are.equal(1, contrast)
  end)

  it("black/white has max contrast 21", function()
    local lum_white = color.get_luminance("#ffffff")
    local lum_black = color.get_luminance("#000000")
    local contrast = color.calculate_contrast(lum_white, lum_black)
    assert.is_true(contrast >= 20)
  end)
end)

describe("color.term_from_palette", function()
  it("generates terminal 16-color palette", function()
    local palette = {
      base00 = "#000000",
      base05 = "#ffffff",
      base08 = "#ff0000",
      base0A = "#ffff00",
      base0B = "#00ff00",
      base0C = "#00ffff",
      base0D = "#0000ff",
      base0E = "#ff00ff",
    }
    local term = color.term_from_palette(palette)

    assert.are.equal("#000000", term.black)
    assert.are.equal("#ffffff", term.white)
    assert.are.equal("#ff0000", term.red)
    assert.are.equal("#00ff00", term.green)
    assert.is_string(term.black_bright)
    assert.is_string(term.red_bright)
  end)

  it("handles missing keys with fallbacks", function()
    local term = color.term_from_palette({})
    assert.is_string(term.black)
    assert.is_string(term.white)
  end)

  it("handles nil input", function()
    local term = color.term_from_palette(nil)
    assert.is_table(term)
  end)
end)

describe("color edge cases", function()
  it("handles #000000", function()
    local c = color("#000000")
    assert.are.equal("#000000", c.hex)
  end)

  it("handles #ffffff", function()
    local c = color("#ffffff")
    assert.are.equal("#ffffff", c.hex)
  end)

  it("handles whitespace in hex", function()
    local c = color(" #ff0000 ")
    assert.are.equal("#ff0000", c.hex)
  end)

  it("method chaining works", function()
    local hex = color("#ff0000"):brighten(0.1):saturate(0.1):rotate(45):darken(0.1):to_hex()
    assert.is_string(hex)
  end)
end)
