local config = require("prismpunk.config")

describe("config.parse_theme", function()
  describe("string input - 3 parts", function()
    it("parses fully qualified scheme: dc/lantern-corps/green", function()
      local result = config.parse_theme("dc/lantern-corps/green")
      assert.are.equal("dc/lantern-corps", result.universe)
      assert.are.equal("green", result.name)
      assert.are.same({ { universe = "dc/lantern-corps", name = "green" } }, result.variants)
    end)

    it("parses 3-part scheme with different parent", function()
      local result = config.parse_theme("marvel/avengers/iron-man")
      assert.are.equal("marvel/avengers", result.universe)
      assert.are.equal("iron-man", result.name)
    end)
  end)

  describe("string input - 2 parts with known parent", function()
    it("parses lantern-corps/green (DC subcategory)", function()
      local result = config.parse_scheme("lantern-corps/green")
      assert.are.equal("dc/lantern-corps", result.universe)
      assert.are.equal("green", result.name)
    end)

    it("parses justice-league/superman (DC subcategory)", function()
      local result = config.parse_scheme("justice-league/superman")
      assert.are.equal("dc/justice-league", result.universe)
      assert.are.equal("superman", result.name)
    end)

    it("parses bat-family/batman (DC subcategory)", function()
      local result = config.parse_scheme("bat-family/batman")
      assert.are.equal("dc/bat-family", result.universe)
      assert.are.equal("batman", result.name)
    end)

    it("parses injustice-league/joker (DC subcategory)", function()
      local result = config.parse_scheme("injustice-league/joker")
      assert.are.equal("dc/injustice-league", result.universe)
      assert.are.equal("joker", result.name)
    end)

    it("parses watchmen/rorschach (DC subcategory)", function()
      local result = config.parse_scheme("watchmen/rorschach")
      assert.are.equal("dc/watchmen", result.universe)
      assert.are.equal("rorschach", result.name)
    end)
  end)

  describe("string input - 2 parts without known parent", function()
    it("parses kanagawa/paper-edo (direct universe)", function()
      local result = config.parse_scheme("kanagawa/paper-edo")
      assert.are.equal("kanagawa", result.universe)
      assert.are.equal("paper-edo", result.name)
      assert.is_true(#result.variants >= 1)
      assert.are.equal("kanagawa", result.variants[1].universe)
    end)

    it("parses tmnt/leonardo (direct universe)", function()
      local result = config.parse_scheme("tmnt/leonardo")
      assert.are.equal("tmnt", result.universe)
      assert.are.equal("leonardo", result.name)
    end)

    it("generates discovery variants for unknown category", function()
      local result = config.parse_scheme("new-universe/some-scheme")
      assert.are.equal("new-universe", result.universe)
      assert.are.equal("some-scheme", result.name)
      assert.is_true(#result.variants >= 1)
    end)
  end)

  describe("string input - single part", function()
    it("parses single name without universe", function()
      local result = config.parse_scheme("paper-edo")
      assert.is_nil(result.universe)
      assert.are.equal("paper-edo", result.name)
      assert.are.same({}, result.variants)
    end)
  end)

  describe("edge cases - string input", function()
    it("handles empty string", function()
      local result = config.parse_scheme("")
      assert.is_nil(result.universe)
      assert.is_nil(result.name)
      assert.are.same({}, result.variants)
    end)

    it("handles nil", function()
      local result = config.parse_scheme(nil)
      assert.is_nil(result.universe)
      assert.is_nil(result.name)
      assert.are.same({}, result.variants)
    end)
  end)

  describe("table input", function()
    it("accepts { universe, name } format", function()
      local result = config.parse_scheme({ universe = "dc/lantern-corps", name = "green" })
      assert.are.equal("dc/lantern-corps", result.universe)
      assert.are.equal("green", result.name)
    end)

    it("accepts { 'scheme-name' } shorthand", function()
      local result = config.parse_scheme({ "single-scheme" })
      assert.are.equal("single-scheme", result.name)
    end)

    it("accepts opts field", function()
      local result = config.parse_scheme({ universe = "kanagawa", name = "paper-edo", opts = { gutter = false } })
      assert.are.equal("kanagawa", result.universe)
      assert.are.equal("paper-edo", result.name)
      assert.are.same({ gutter = false }, result.opts)
    end)

    it("uses name field over index", function()
      local result = config.parse_scheme({ name = "preferred", [1] = "ignored" })
      assert.are.equal("preferred", result.name)
    end)
  end)

  describe("error handling", function()
    it("errors on invalid type (number)", function()
      assert.has_error(function()
        config.parse_scheme(123)
      end, "[prismpunk] Invalid scheme_spec type: number (expected string or table)")
    end)

    it("errors on invalid type (boolean)", function()
      assert.has_error(function()
        config.parse_scheme(true)
      end, "[prismpunk] Invalid scheme_spec type: boolean (expected string or table)")
    end)
  end)
end)

describe("config.setup", function()
  it("merges user config with defaults", function()
    local result = config.setup({ scheme = "kanagawa/paper-edo", gutter = false })
    assert.are.equal("kanagawa/paper-edo", result.scheme)
    assert.is_false(result.gutter)
    assert.is_table(result.styles)
    assert.is_table(result.terminals)
  end)

  it("returns defaults when no config provided", function()
    local result = config.setup()
    assert.is_table(result.styles)
    assert.is_table(result.terminals)
    assert.is_table(result.cache)
  end)

  it("validates config schema", function()
    assert.has_error(function()
      config.setup({ gutter = "not a boolean" })
    end)
  end)

  it("warns on unknown keys", function()
    local warned = false
    local orig_notify = vim.notify
    vim.notify = function(msg) -- luacheck: ignore
      if msg:match("Unknown config key") then warned = true end
    end
    config.setup({ unknown_key = "value" })
    vim.notify = orig_notify -- luacheck: ignore
    assert.is_true(warned)
  end)
end)

describe("config.defaults", function()
  it("has required default values", function()
    assert.is_table(config.defaults.styles)
    assert.is_table(config.defaults.terminals)
    assert.is_table(config.defaults.cache)
    assert.is_table(config.defaults.overrides)
  end)

  it("has style subcategories", function()
    assert.is_table(config.defaults.styles.comments)
    assert.is_table(config.defaults.styles.keywords)
    assert.is_table(config.defaults.styles.diagnostics)
    assert.is_table(config.defaults.styles.git)
    assert.is_table(config.defaults.styles.ui)
  end)

  it("has terminal defaults", function()
    assert.is_boolean(config.defaults.terminals.enabled)
    assert.is_boolean(config.defaults.terminals.auto_detect)
  end)

  it("has cache defaults", function()
    assert.is_boolean(config.defaults.cache.enable)
    assert.is_boolean(config.defaults.cache.persist_to_disk)
  end)

  it("has default scheme set", function()
    assert.is_string(config.defaults.scheme)
    assert.is_true(#config.defaults.scheme > 0)
  end)
end)

describe("config.DEFAULT_SCHEME", function()
  it("exports default scheme constant", function()
    assert.is_string(config.DEFAULT_SCHEME)
    assert.is_true(#config.DEFAULT_SCHEME > 0)
  end)

  it("matches defaults.scheme", function()
    assert.equal(config.DEFAULT_SCHEME, config.defaults.scheme)
  end)
  
  it("provides backwards compat DEFAULT_THEME alias", function()
    assert.equal(config.DEFAULT_THEME, config.DEFAULT_SCHEME)
  end)
end)

describe("config.schemes", function()
  it("has empty array as default", function()
    config.setup({})
    assert.is_table(config.defaults.schemes)
    assert.equal(0, #config.defaults.schemes)
  end)

  it("accepts schemes array in setup", function()
    local result = config.setup({
      schemes = { "dc/superman", "kanagawa" },
    })
    assert.is_table(result.schemes)
    assert.equal(2, #result.schemes)
  end)
end)

describe("config.is_scheme_allowed", function()
  before_each(function()
    config.setup({})
  end)

  it("allows all schemes when config.schemes is empty", function()
    assert.is_true(config.is_scheme_allowed("dc/superman"))
    assert.is_true(config.is_scheme_allowed("kanagawa/paper-edo"))
    assert.is_true(config.is_scheme_allowed("tmnt/leonardo"))
  end)

  it("allows explicitly listed schemes", function()
    config.setup({ schemes = { "dc/superman", "kanagawa" } })
    local schemes = config.get_allowed_schemes()
    assert.equal(2, #schemes)
    assert.is_true(config.is_scheme_allowed("dc/superman"))
    assert.is_true(config.is_scheme_allowed("kanagawa/paper-edo"))
  end)

  it("rejects schemes not in config", function()
    config.setup({ schemes = { "dc/superman" } })
    assert.is_false(config.is_scheme_allowed("tmnt/leonardo"))
    assert.is_false(config.is_scheme_allowed("kanagawa/paper-edo"))
  end)

  it("allows entire universe when universe is listed", function()
    config.setup({ schemes = { "dc" } })
    assert.is_true(config.is_scheme_allowed("dc/superman"))
    assert.is_true(config.is_scheme_allowed("dc/batman"))
    assert.is_true(config.is_scheme_allowed("dc/lantern-corps/green"))
  end)
end)

describe("config.get_allowed_schemes", function()
  it("returns empty table by default", function()
    config.setup({})
    local schemes = config.get_allowed_schemes()
    assert.is_table(schemes)
    assert.equal(0, #schemes)
  end)

  it("returns configured schemes", function()
    config.setup({ schemes = { "dc/superman", "kanagawa" } })
    local schemes = config.get_allowed_schemes()
    assert.is_table(schemes)
    assert.equal(2, #schemes)
  end)
end)

describe("config backwards compat", function()
  it("is_theme_allowed is alias for is_scheme_allowed", function()
    assert.are.equal(config.is_theme_allowed, config.is_scheme_allowed)
  end)
  
  it("get_allowed_themes is alias for get_allowed_schemes", function()
    assert.are.equal(config.get_allowed_themes, config.get_allowed_schemes)
  end)
  
  it("parse_theme is alias for parse_scheme", function()
    assert.are.equal(config.parse_theme, config.parse_scheme)
  end)
end)
