local color = require("prismpunk.utils.color")

local palette = {
  gotham_night = "#0B0E14",
  alley_depth = "#13161F",
  rain_shadow = "#1C222B",
  midnight_core = "#262D38",
  gordon_skin = "#5D5044",
  trench_coat = "#6D624F",
  honest_gray = "#8C8070",
  veteran_brown = "#A89A80",
  batsignal_yellow = "#FFD42A",
  signal_glow = "#FFE97B",
  beacon_light = "#FFFFC0",
  hope_white = "#FFFFFF",
  beacon_red = "#FF0033",
  siren_red = "#FF3355",
  emergency_red = "#FF5566",
  gotham_pd_blue = "#0066CC",
  patrol_blue = "#3388FF",
  nightshift_cyan = "#00AADD",
  cigarette_ember = "#FF4400",
  coffee_brown = "#8B4513",
  late_night = "#B5651D",
  manila_folder = "#D4C9A8",
  casefile_beige = "#E0D6B8",
  red_pen = "#CC0000",
  term_red = "#FF0033",
  term_green = "#88AA00",
  term_blue = "#0066CC",
  term_yellow = "#FFD42A",
  term_cyan = "#00AADD",
  term_magenta = "#CC66AA",
  term_red_bright = "#FF5588",
  term_green_bright = "#AADD55",
  term_yellow_bright = "#FFEE88",
  term_blue_bright = "#5599FF",
  term_magenta_bright = "#FF88CC",
  term_cyan_bright = "#88DDDD",

  bg_darkest = "#0B0E14",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.batsignal_yellow,
      insert = plt.gotham_pd_blue,
      visual = plt.beacon_red,
      replace = plt.siren_red,
      command = plt.nightshift_cyan,
    },

    ui = {
      fg = plt.hope_white,
      fg_dim = plt.veteran_brown,
      fg_dimmer = plt.honest_gray,
      fg_dark = plt.trench_coat,
      fg_reverse = plt.gotham_night,

      bg_m4 = plt.midnight_core,
      bg_m3 = plt.rain_shadow,
      bg_m2 = plt.alley_depth,
      bg_m1 = plt.gotham_night,
      bg_dim = plt.gotham_night,
      bg = plt.gotham_night,
      bg_p1 = plt.alley_depth,
      bg_p2 = plt.rain_shadow,
      bg_gutter = opts.gutter and plt.rain_shadow or "none",
      bg_cursorline = plt.rain_shadow,
      bg_cursorline_alt = plt.alley_depth,
      bg_search = plt.batsignal_yellow,
      bg_visual = plt.beacon_red,
      bg_statusline = plt.rain_shadow,

      border = plt.batsignal_yellow,
      header1 = plt.batsignal_yellow,
      header2 = plt.gotham_pd_blue,
      special = plt.cigarette_ember,
      nontext = plt.alley_depth,
      whitespace = plt.midnight_core,
      win_separator = plt.batsignal_yellow,
      indent = plt.alley_depth,
      indent_scope = plt.hope_white,
      picker = plt.patrol_blue,
      yank = plt.signal_glow,
      mark = plt.emergency_red,
      scrollbar = plt.rain_shadow,

      tabline = {
        bg = plt.gotham_night,
        fg_selected = plt.batsignal_yellow,
        bg_selected = plt.rain_shadow,
        fg_inactive = plt.honest_gray,
        bg_inactive = plt.gotham_night,
        fg_alternate = plt.gotham_pd_blue,
        bg_alternate = plt.gotham_night,
        indicator = plt.beacon_red,
      },

      pmenu = {
        fg = plt.hope_white,
        fg_sel = "none",
        fg_border = plt.rain_shadow,
        bg_border = plt.rain_shadow,
        bg = plt.rain_shadow,
        bg_sel = plt.alley_depth,
        bg_sbar = plt.rain_shadow,
        bg_thumb = plt.batsignal_yellow,
      },

      float = {
        fg = plt.hope_white,
        bg = plt.alley_depth,
        fg_border = plt.rain_shadow,
        bg_border = plt.alley_depth,
      },
    },

    accent = {
      accent1 = plt.batsignal_yellow,
      accent2 = plt.gotham_pd_blue,
      accent3 = plt.beacon_red,
      accent4 = plt.cigarette_ember,
      accent5 = plt.nightshift_cyan,
      invert = plt.rain_shadow,
    },

    rainbow = {
      rainbow1 = plt.batsignal_yellow,
      rainbow2 = plt.gotham_pd_blue,
      rainbow3 = plt.beacon_red,
      rainbow4 = plt.signal_glow,
      rainbow5 = plt.patrol_blue,
      rainbow6 = plt.emergency_red,
      rainbow7 = plt.nightshift_cyan,
    },

    syn = {
      attribute = plt.hope_white,
      boolean = plt.beacon_red,
      comment = plt.honest_gray,
      constant = plt.manila_folder,
      deprecated = plt.midnight_core,
      func = plt.nightshift_cyan,
      identifier = plt.hope_white,
      keyword = plt.batsignal_yellow,
      method = plt.patrol_blue,
      number = plt.signal_glow,
      operator = plt.cigarette_ember,
      parameter = plt.veteran_brown,
      preproc = plt.red_pen,
      punct = plt.honest_gray,
      regex = plt.nightshift_cyan,
      statement = plt.batsignal_yellow,
      string = plt.casefile_beige,
      symbol = plt.hope_white,
      type = plt.signal_glow,
      variable = plt.hope_white,
      special = plt.nightshift_cyan,
      special2 = plt.beacon_red,
      special3 = plt.gotham_pd_blue,
    },

    vcs = { added = plt.nightshift_cyan, removed = plt.beacon_red, changed = plt.batsignal_yellow },
    diff = { add = plt.nightshift_cyan, change = plt.patrol_blue, delete = plt.beacon_red, text = plt.signal_glow },
    diag = {
      ok = plt.nightshift_cyan,
      error = plt.beacon_red,
      warning = plt.batsignal_yellow,
      info = plt.gotham_pd_blue,
      hint = plt.casefile_beige,
    },

    term = {
      black = plt.gotham_night,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_magenta,
      cyan = plt.term_cyan,
      white = plt.hope_white,

      black_bright = color(plt.gotham_night):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_magenta_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.batsignal_yellow,
      indexed2 = plt.gotham_pd_blue,
    },

    treesitter = {
      ["@comment"] = plt.honest_gray,
      ["@comment.documentation"] = plt.veteran_brown,
      ["@comment.error"] = plt.beacon_red,
      ["@comment.warning"] = plt.batsignal_yellow,
      ["@comment.todo"] = plt.nightshift_cyan,
      ["@comment.note"] = plt.patrol_blue,

      ["@constant"] = plt.manila_folder,
      ["@constant.builtin"] = plt.manila_folder,
      ["@constant.macro"] = plt.coffee_brown,

      ["@string"] = plt.casefile_beige,
      ["@string.documentation"] = plt.casefile_beige,
      ["@string.regex"] = plt.nightshift_cyan,
      ["@string.escape"] = plt.cigarette_ember,
      ["@string.special"] = plt.beacon_red,
      ["@string.special.symbol"] = plt.batsignal_yellow,
      ["@string.special.url"] = plt.patrol_blue,
      ["@string.special.path"] = plt.casefile_beige,

      ["@character"] = plt.casefile_beige,
      ["@character.special"] = plt.cigarette_ember,

      ["@number"] = plt.signal_glow,
      ["@number.float"] = plt.signal_glow,

      ["@boolean"] = plt.beacon_red,

      ["@function"] = plt.nightshift_cyan,
      ["@function.builtin"] = plt.nightshift_cyan,
      ["@function.call"] = plt.nightshift_cyan,
      ["@function.macro"] = plt.cigarette_ember,
      ["@function.method"] = plt.patrol_blue,
      ["@function.method.call"] = plt.patrol_blue,

      ["@constructor"] = plt.batsignal_yellow,

      ["@parameter"] = plt.veteran_brown,
      ["@parameter.builtin"] = plt.hope_white,

      ["@keyword"] = plt.batsignal_yellow,
      ["@keyword.coroutine"] = plt.beacon_red,
      ["@keyword.function"] = plt.batsignal_yellow,
      ["@keyword.operator"] = plt.cigarette_ember,
      ["@keyword.return"] = plt.batsignal_yellow,
      ["@keyword.import"] = plt.nightshift_cyan,
      ["@keyword.storage"] = plt.batsignal_yellow,
      ["@keyword.repeat"] = plt.batsignal_yellow,
      ["@keyword.conditional"] = plt.batsignal_yellow,
      ["@keyword.exception"] = plt.beacon_red,
      ["@keyword.directive"] = plt.signal_glow,
      ["@keyword.directive.define"] = plt.signal_glow,

      ["@conditional"] = plt.batsignal_yellow,
      ["@conditional.ternary"] = plt.batsignal_yellow,

      ["@repeat"] = plt.batsignal_yellow,

      ["@label"] = plt.nightshift_cyan,

      ["@operator"] = plt.cigarette_ember,

      ["@exception"] = plt.beacon_red,

      ["@variable"] = plt.hope_white,
      ["@variable.builtin"] = plt.batsignal_yellow,
      ["@variable.parameter"] = plt.veteran_brown,
      ["@variable.member"] = plt.hope_white,

      ["@type"] = plt.signal_glow,
      ["@type.builtin"] = plt.signal_glow,
      ["@type.definition"] = plt.signal_glow,
      ["@type.qualifier"] = plt.batsignal_yellow,

      ["@attribute"] = plt.hope_white,
      ["@attribute.builtin"] = plt.signal_glow,

      ["@property"] = plt.hope_white,
      ["@field"] = plt.hope_white,
      ["@module"] = plt.hope_white,
      ["@module.builtin"] = plt.hope_white,
      ["@namespace"] = plt.hope_white,
      ["@namespace.builtin"] = plt.hope_white,

      ["@punctuation.delimiter"] = plt.honest_gray,
      ["@punctuation.bracket"] = plt.gotham_pd_blue,
      ["@punctuation.special"] = plt.cigarette_ember,

      ["@tag"] = plt.batsignal_yellow,
      ["@tag.attribute"] = plt.signal_glow,
      ["@tag.delimiter"] = plt.honest_gray,
      ["@tag.builtin"] = plt.batsignal_yellow,

      ["@markup.strong"] = { fg = plt.batsignal_yellow, bold = true },
      ["@markup.italic"] = { fg = plt.hope_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.midnight_core, strikethrough = true },
      ["@markup.underline"] = { fg = plt.gotham_pd_blue, underline = true },
      ["@markup.heading"] = plt.batsignal_yellow,
      ["@markup.heading.1"] = plt.batsignal_yellow,
      ["@markup.heading.2"] = plt.gotham_pd_blue,
      ["@markup.heading.3"] = plt.beacon_red,
      ["@markup.heading.4"] = plt.signal_glow,
      ["@markup.heading.5"] = plt.patrol_blue,
      ["@markup.heading.6"] = plt.nightshift_cyan,
      ["@markup.quote"] = plt.honest_gray,
      ["@markup.math"] = plt.nightshift_cyan,
      ["@markup.link"] = plt.patrol_blue,
      ["@markup.link.label"] = plt.signal_glow,
      ["@markup.link.url"] = plt.gotham_pd_blue,
      ["@markup.raw"] = plt.casefile_beige,
      ["@markup.raw.block"] = plt.casefile_beige,
      ["@markup.list"] = plt.batsignal_yellow,
      ["@markup.list.checked"] = plt.nightshift_cyan,
      ["@markup.list.unchecked"] = plt.honest_gray,

      ["@diff.plus"] = plt.nightshift_cyan,
      ["@diff.minus"] = plt.beacon_red,
      ["@diff.delta"] = plt.patrol_blue,

      ["@none"] = "none",
      ["@conceal"] = plt.manila_folder,
      ["@spell"] = plt.hope_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.hope_white,
      ["@constructor.python"] = plt.batsignal_yellow,
      ["@constructor.javascript"] = plt.batsignal_yellow,
      ["@constructor.typescript"] = plt.batsignal_yellow,
      ["@namespace.rust"] = plt.hope_white,
      ["@type.qualifier.rust"] = plt.batsignal_yellow,
      ["@constant.macro.c"] = plt.coffee_brown,
      ["@constant.macro.cpp"] = plt.coffee_brown,
      ["@namespace.go"] = plt.hope_white,
      ["@property.css"] = plt.nightshift_cyan,
      ["@type.css"] = plt.batsignal_yellow,
      ["@label.json"] = plt.hope_white,
      ["@field.yaml"] = plt.veteran_brown,
      ["@property.toml"] = plt.veteran_brown,
      ["@function.builtin.bash"] = plt.nightshift_cyan,
      ["@string.regexp"] = plt.cigarette_ember,
      ["@character.special.regex"] = plt.emergency_red,
    },

    lsp = {
      ["@lsp.type.class"] = plt.signal_glow,
      ["@lsp.type.interface"] = plt.signal_glow,
      ["@lsp.type.struct"] = plt.signal_glow,
      ["@lsp.type.enum"] = plt.signal_glow,
      ["@lsp.type.enumMember"] = plt.manila_folder,
      ["@lsp.type.property"] = plt.hope_white,
      ["@lsp.type.namespace"] = plt.hope_white,

      ["@lsp.type.macro"] = plt.signal_glow,
      ["@lsp.type.decorator"] = plt.batsignal_yellow,

      ["@lsp.type.builtinType"] = plt.signal_glow,
      ["@lsp.type.selfParameter"] = plt.batsignal_yellow,
      ["@lsp.type.typeParameter"] = plt.signal_glow,

      ["@lsp.type.array"] = plt.signal_glow,
      ["@lsp.type.object"] = plt.signal_glow,
      ["@lsp.type.key"] = plt.hope_white,
      ["@lsp.type.null"] = plt.manila_folder,
      ["@lsp.type.enumConstant"] = plt.manila_folder,

      ["@lsp.type.event"] = plt.signal_glow,
      ["@lsp.type.regexp"] = plt.cigarette_ember,
      ["@lsp.type.unresolvedReference"] = plt.beacon_red,

      ["@lsp.mod.deprecated"] = { fg = plt.midnight_core, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.manila_folder,
      ["@lsp.mod.async"] = plt.batsignal_yellow,
      ["@lsp.mod.static"] = plt.signal_glow,
      ["@lsp.mod.abstract"] = plt.signal_glow,
      ["@lsp.mod.defaultLibrary"] = plt.signal_glow,
      ["@lsp.mod.documentation"] = plt.veteran_brown,
    },
  }
end

return {
  name = "James Gordon",
  author = "PrismPunk.nvim",
  description = "The last honest cop in Gotham. Trench-coat khaki, rainy blues, "
    .. "red beacons, and the unquenchable yellow of the Bat-Signal. He never stops. Neither should you.",

  base16 = {
    base00 = palette.gotham_night,
    base01 = palette.alley_depth,
    base02 = palette.rain_shadow,
    base03 = palette.midnight_core,
    base04 = palette.honest_gray,
    base05 = palette.veteran_brown,
    base06 = palette.trench_coat,
    base07 = palette.hope_white,
    base08 = palette.beacon_red,
    base09 = palette.batsignal_yellow,
    base0A = palette.gotham_pd_blue,
    base0B = palette.nightshift_cyan,
    base0C = palette.signal_glow,
    base0D = palette.patrol_blue,
    base0E = palette.cigarette_ember,
    base0F = palette.manila_folder,
  },

  palette = palette,
  get = M.get,
}
