local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#060609",
  bg_darker = "#0B0B0E",
  bg_dark = "#121218",
  bg_mid = "#1A1A23",
  bg_light = "#3A3F4C",
  bg_lighter = "#565C64",
  bg_lightest = "#6A7178",
  fg_lightest = "#E8ECF0",
  fg_light = "#C8CCD4",
  fg_mid = "#ABB2BF",
  fg_dark = "#6A7178",
  bg_alt1 = "#0F0F14",
  bg_alt2 = "#080809",
  bg_alt3 = "#14151D",
  bg_alt4 = "#080A0D",
  timRed = "#FF0000",
  redRobinRed = "#E63946",
  detectiveRed = "#DC143C",
  drakeRed = "#C41E3A",
  titanRed = "#B71C1C",
  boStaff = "#8B4513",
  wingSteel = "#D4AF37",
  capeBlack = "#0E0E0E",
  drakeGray = "#1A1A1A",
  youngJustice = "#61AFEF",
  teenTitans = "#00DDAA",
  wayneBlue = "#4169E1",
  gothamTeal = "#56B6C2",
  detectiveGold = "#FFD700",
  clueMasterYellow = "#FFEB3B",
  evidenceAmber = "#FFA726",
  bruceGray = "#98C379",
  raAlGhul = "#00FF41",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.timRed,
      insert = plt.youngJustice,
      visual = plt.detectiveRed,
      replace = plt.titanRed,
      command = plt.detectiveGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.detectiveGold,
      bg_visual = plt.detectiveRed,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.timRed,
      header2 = plt.detectiveGold,
      special = plt.teenTitans,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.timRed,
      indent = plt.bg_lighter,
      indent_scope = plt.timRed,
      picker = plt.redRobinRed,
      yank = plt.detectiveGold,
      mark = plt.teenTitans,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.timRed,
        bg_alternate = plt.bg_darkest,
        indicator = plt.detectiveGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.timRed,
      accent2 = plt.detectiveGold,
      accent3 = plt.youngJustice,
      accent4 = plt.teenTitans,
      accent5 = plt.titanRed,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.timRed,
      rainbow2 = plt.detectiveGold,
      rainbow3 = plt.youngJustice,
      rainbow4 = plt.teenTitans,
      rainbow5 = plt.clueMasterYellow,
      rainbow6 = plt.evidenceAmber,
      rainbow7 = plt.redRobinRed,
    },

    syn = {
      attribute = plt.detectiveGold,
      boolean = plt.timRed,
      comment = plt.fg_dark,
      constant = plt.detectiveGold,
      deprecated = plt.fg_mid,
      func = plt.youngJustice,
      identifier = plt.fg_lightest,
      keyword = plt.timRed,
      method = plt.teenTitans,
      number = plt.wingSteel,
      operator = plt.teenTitans,
      parameter = plt.fg_mid,
      preproc = plt.wayneBlue,
      punct = plt.fg_mid,
      regex = plt.detectiveGold,
      statement = plt.timRed,
      string = plt.evidenceAmber,
      symbol = plt.teenTitans,
      type = plt.detectiveGold,
      variable = plt.fg_lightest,
      special = plt.clueMasterYellow,
      special2 = plt.redRobinRed,
      special3 = plt.youngJustice,
    },

    vcs = {
      added = plt.bruceGray,
      removed = plt.titanRed,
      changed = plt.evidenceAmber,
    },

    diff = {
      add = plt.bruceGray,
      change = plt.evidenceAmber,
      delete = plt.titanRed,
      text = plt.youngJustice,
    },

    diag = {
      ok = plt.bruceGray,
      error = plt.titanRed,
      warning = plt.evidenceAmber,
      info = plt.youngJustice,
      hint = plt.teenTitans,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.timRed,
      green = plt.bruceGray,
      yellow = plt.detectiveGold,
      blue = plt.youngJustice,
      magenta = plt.wayneBlue,
      cyan = plt.teenTitans,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.timRed):brighten(0.2):to_hex(),
      green_bright = color(plt.bruceGray):brighten(0.1):to_hex(),
      yellow_bright = color(plt.detectiveGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.youngJustice):brighten(0.3):to_hex(),
      magenta_bright = color(plt.wayneBlue):brighten(0.2):to_hex(),
      cyan_bright = color(plt.teenTitans):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.detectiveGold,
      indexed2 = plt.timRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.titanRed,
      ["@comment.warning"] = plt.evidenceAmber,
      ["@comment.todo"] = plt.timRed,
      ["@comment.note"] = plt.teenTitans,

      ["@constant"] = plt.detectiveGold,
      ["@constant.builtin"] = plt.detectiveGold,
      ["@constant.macro"] = plt.clueMasterYellow,

      ["@string"] = plt.evidenceAmber,
      ["@string.documentation"] = plt.evidenceAmber,
      ["@string.regex"] = plt.detectiveGold,
      ["@string.escape"] = plt.wayneBlue,
      ["@string.special"] = plt.teenTitans,
      ["@string.special.symbol"] = plt.teenTitans,
      ["@string.special.url"] = plt.youngJustice,
      ["@string.special.path"] = plt.teenTitans,

      ["@character"] = plt.evidenceAmber,
      ["@character.special"] = plt.wayneBlue,

      ["@number"] = plt.wingSteel,
      ["@number.float"] = plt.wingSteel,

      ["@boolean"] = plt.timRed,

      ["@function"] = plt.youngJustice,
      ["@function.builtin"] = plt.youngJustice,
      ["@function.call"] = plt.youngJustice,
      ["@function.macro"] = plt.wayneBlue,
      ["@function.method"] = plt.teenTitans,
      ["@function.method.call"] = plt.teenTitans,

      ["@constructor"] = plt.detectiveGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.timRed,
      ["@keyword.coroutine"] = plt.redRobinRed,
      ["@keyword.function"] = plt.timRed,
      ["@keyword.operator"] = plt.teenTitans,
      ["@keyword.return"] = plt.timRed,
      ["@keyword.import"] = plt.youngJustice,
      ["@keyword.storage"] = plt.timRed,
      ["@keyword.repeat"] = plt.timRed,
      ["@keyword.conditional"] = plt.timRed,
      ["@keyword.exception"] = plt.titanRed,
      ["@keyword.directive"] = plt.wayneBlue,
      ["@keyword.directive.define"] = plt.wayneBlue,

      ["@conditional"] = plt.timRed,
      ["@conditional.ternary"] = plt.timRed,

      ["@repeat"] = plt.timRed,

      ["@label"] = plt.redRobinRed,

      ["@operator"] = plt.teenTitans,

      ["@exception"] = plt.titanRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.redRobinRed,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.detectiveGold,
      ["@type.builtin"] = plt.detectiveGold,
      ["@type.definition"] = plt.detectiveGold,
      ["@type.qualifier"] = plt.timRed,

      ["@attribute"] = plt.detectiveGold,
      ["@attribute.builtin"] = plt.detectiveGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.detectiveGold,
      ["@module.builtin"] = plt.detectiveGold,

      ["@namespace"] = plt.detectiveGold,
      ["@namespace.builtin"] = plt.detectiveGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.teenTitans,

      ["@tag"] = plt.teenTitans,
      ["@tag.attribute"] = plt.detectiveGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.teenTitans,

      ["@markup.strong"] = { fg = plt.timRed, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.timRed,
      ["@markup.heading.1"] = plt.timRed,
      ["@markup.heading.2"] = plt.detectiveGold,
      ["@markup.heading.3"] = plt.youngJustice,
      ["@markup.heading.4"] = plt.teenTitans,
      ["@markup.heading.5"] = plt.clueMasterYellow,
      ["@markup.heading.6"] = plt.evidenceAmber,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.youngJustice,
      ["@markup.link"] = plt.youngJustice,
      ["@markup.link.label"] = plt.teenTitans,
      ["@markup.link.url"] = plt.youngJustice,
      ["@markup.raw"] = plt.evidenceAmber,
      ["@markup.raw.block"] = plt.evidenceAmber,
      ["@markup.list"] = plt.teenTitans,
      ["@markup.list.checked"] = plt.bruceGray,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.bruceGray,
      ["@diff.minus"] = plt.titanRed,
      ["@diff.delta"] = plt.evidenceAmber,

      ["@none"] = "none",
      ["@conceal"] = plt.wayneBlue,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.detectiveGold,
      ["@constructor.javascript"] = plt.detectiveGold,
      ["@constructor.typescript"] = plt.detectiveGold,
      ["@namespace.rust"] = plt.detectiveGold,
      ["@type.qualifier.rust"] = plt.timRed,
      ["@constant.macro.c"] = plt.clueMasterYellow,
      ["@constant.macro.cpp"] = plt.clueMasterYellow,
      ["@namespace.go"] = plt.detectiveGold,
      ["@property.css"] = plt.evidenceAmber,
      ["@type.css"] = plt.teenTitans,
      ["@label.json"] = plt.detectiveGold,
      ["@field.yaml"] = plt.evidenceAmber,
      ["@property.toml"] = plt.evidenceAmber,
      ["@function.builtin.bash"] = plt.youngJustice,
      ["@string.regexp"] = plt.detectiveGold,
      ["@character.special.regex"] = plt.wayneBlue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.detectiveGold,
      ["@lsp.type.interface"] = plt.detectiveGold,
      ["@lsp.type.struct"] = plt.detectiveGold,
      ["@lsp.type.enum"] = plt.detectiveGold,
      ["@lsp.type.enumMember"] = plt.timRed,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.detectiveGold,

      ["@lsp.type.macro"] = plt.clueMasterYellow,
      ["@lsp.type.decorator"] = plt.detectiveGold,

      ["@lsp.type.builtinType"] = plt.detectiveGold,
      ["@lsp.type.selfParameter"] = plt.redRobinRed,
      ["@lsp.type.typeParameter"] = plt.detectiveGold,

      ["@lsp.type.array"] = plt.detectiveGold,
      ["@lsp.type.object"] = plt.detectiveGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.timRed,
      ["@lsp.type.enumConstant"] = plt.timRed,

      ["@lsp.type.event"] = plt.detectiveGold,
      ["@lsp.type.regexp"] = plt.detectiveGold,
      ["@lsp.type.unresolvedReference"] = plt.detectiveGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.timRed,
      ["@lsp.mod.async"] = plt.timRed,
      ["@lsp.mod.static"] = plt.redRobinRed,
      ["@lsp.mod.abstract"] = plt.detectiveGold,
      ["@lsp.mod.defaultLibrary"] = plt.detectiveGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Bat-Family – Red Robin",
  author = "PrismPunk.nvim",
  description = "Tim Drake, the detective Robin. World's greatest detective gold, "
    .. "Young Justice blue, Teen Titans teal, and bo staff mastery.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.titanRed,
    base09 = palette.evidenceAmber,
    base0A = palette.detectiveGold,
    base0B = palette.bruceGray,
    base0C = palette.teenTitans,
    base0D = palette.youngJustice,
    base0E = palette.timRed,
    base0F = palette.wayneBlue,
  },

  palette = palette,
  get = M.get,
}
