local color = require("prismpunk.utils.color")

local palette = {
  fury_void = "#0A001A",
  apokolips_scar = "#120030",
  broken_chain = "#1A004D",
  freedom_depth = "#240066",
  warrior_steel = "#2A3377",
  fury_flesh = "#3D4D99",
  honor_skin = "#5566BB",
  barda_blue = "#7088FF",
  barda_royal = "#4488FF",
  freedom_blue = "#5599FF",
  mega_rod_blue = "#66AAFF",
  justice_glow = "#88BBFF",
  righteous_light = "#AADDFF",
  honor_gold = "#FFCC00",
  miracle_gold = "#FFDD22",
  love_ember = "#FFEE44",
  victory_gold = "#FFFF66",
  eternal_bond = "#FFFFAA",
  new_genesis_white = "#FFFFFF",
  hope_core = "#EEEEFF",
  freedom_dawn = "#DDDDFF",
  barda_red = "#FF3366",
  fury_crimson = "#FF5577",
  love_pulse = "#FF7799",
  term_red = "#FF4488",
  term_green = "#AAFF00",
  term_blue = "#4488FF",
  term_yellow = "#FFDD44",
  term_cyan = "#88BBFF",
  mega_rod_core = "#0033AA",
  fury_shadow = "#002266",
  honor_pulse = "#0044CC",
  battle_scars = "#0066FF",
  unbreakable = "#0088FF",

  bg_darkest = "#0A001A",
  fg_lightest = "#FFFFFF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.barda_royal,
      insert = plt.honor_gold,
      visual = plt.mega_rod_blue,
      replace = plt.miracle_gold,
      command = plt.justice_glow,
    },

    ui = {
      fg = plt.righteous_light,
      fg_dim = plt.barda_blue,
      fg_dimmer = plt.honor_skin,
      fg_dark = plt.warrior_steel,
      fg_reverse = plt.fury_void,

      bg_m4 = plt.freedom_depth,
      bg_m3 = plt.broken_chain,
      bg_m2 = plt.apokolips_scar,
      bg_m1 = plt.fury_void,
      bg_dim = plt.fury_void,
      bg = plt.fury_void,
      bg_p1 = plt.apokolips_scar,
      bg_p2 = plt.broken_chain,
      bg_gutter = opts.gutter and plt.broken_chain or "none",
      bg_cursorline = plt.broken_chain,
      bg_cursorline_alt = plt.apokolips_scar,
      bg_search = plt.barda_royal,
      bg_visual = plt.mega_rod_blue,
      bg_statusline = plt.broken_chain,

      border = plt.barda_royal,
      header1 = plt.barda_royal,
      header2 = plt.honor_gold,
      special = plt.victory_gold,
      nontext = plt.apokolips_scar,
      whitespace = plt.freedom_depth,
      win_separator = plt.barda_royal,
      indent = plt.apokolips_scar,
      indent_scope = plt.righteous_light,
      picker = plt.justice_glow,
      yank = plt.barda_royal,
      mark = plt.eternal_bond,
      scrollbar = plt.broken_chain,

      tabline = {
        bg = plt.fury_void,
        fg_selected = plt.barda_royal,
        bg_selected = plt.broken_chain,
        fg_inactive = plt.honor_skin,
        bg_inactive = plt.fury_void,
        fg_alternate = plt.victory_gold,
        bg_alternate = plt.fury_void,
        indicator = plt.mega_rod_blue,
      },

      pmenu = {
        fg = plt.righteous_light,
        fg_sel = "none",
        fg_border = plt.broken_chain,
        bg_border = plt.broken_chain,
        bg = plt.broken_chain,
        bg_sel = plt.apokolips_scar,
        bg_sbar = plt.broken_chain,
        bg_thumb = plt.barda_royal,
      },

      float = {
        fg = plt.righteous_light,
        bg = plt.apokolips_scar,
        fg_border = plt.broken_chain,
        bg_border = plt.apokolips_scar,
      },
    },

    accent = {
      accent1 = plt.barda_royal,
      accent2 = plt.honor_gold,
      accent3 = plt.mega_rod_blue,
      accent4 = plt.miracle_gold,
      accent5 = plt.justice_glow,
      invert = plt.broken_chain,
    },

    rainbow = {
      rainbow1 = plt.barda_royal,
      rainbow2 = plt.mega_rod_blue,
      rainbow3 = plt.justice_glow,
      rainbow4 = plt.freedom_blue,
      rainbow5 = plt.honor_gold,
      rainbow6 = plt.miracle_gold,
      rainbow7 = plt.victory_gold,
    },

    syn = {
      attribute = plt.righteous_light,
      boolean = plt.honor_gold,
      comment = plt.honor_skin,
      constant = plt.love_pulse, -- alive red
      deprecated = plt.freedom_depth,
      func = plt.mega_rod_blue,
      identifier = plt.righteous_light,
      keyword = plt.barda_royal,
      method = plt.justice_glow,
      number = plt.love_ember,
      operator = plt.miracle_gold,
      parameter = plt.barda_blue,
      preproc = plt.miracle_gold,
      punct = plt.honor_skin,
      regex = plt.mega_rod_blue,
      statement = plt.barda_royal,
      string = plt.love_pulse, -- alive red strings
      symbol = plt.righteous_light,
      type = plt.love_ember,
      variable = plt.righteous_light,
      special = plt.mega_rod_blue,
      special2 = plt.justice_glow,
      special3 = plt.barda_red, -- punchy red accent
    },

    vcs = { added = plt.victory_gold, removed = plt.barda_red, changed = plt.love_ember },
    diff = { add = plt.victory_gold, change = plt.mega_rod_blue, delete = plt.barda_red, text = plt.justice_glow },
    diag = {
      ok = plt.victory_gold,
      error = plt.barda_red,
      warning = plt.barda_royal,
      info = plt.mega_rod_blue,
      hint = plt.love_ember,
    },

    term = {
      black = plt.fury_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.barda_royal,
      cyan = plt.justice_glow,
      white = plt.righteous_light,

      black_bright = color(plt.fury_void):brighten(0.8):to_hex(),
      red_bright = "#ff6688",
      green_bright = "#ccff88",
      yellow_bright = "#ffee88",
      blue_bright = "#88ccff",
      magenta_bright = "#88aaff",
      cyan_bright = "#bbddff",
      white_bright = plt.new_genesis_white,
      indexed1 = plt.barda_royal,
      indexed2 = plt.victory_gold,
    },

    treesitter = {
      ["@comment"] = plt.honor_skin,
      ["@comment.documentation"] = plt.barda_blue,
      ["@comment.error"] = plt.barda_red,
      ["@comment.warning"] = plt.barda_royal,
      ["@comment.todo"] = plt.victory_gold,
      ["@comment.note"] = plt.mega_rod_blue,

      ["@constant"] = plt.love_pulse,
      ["@constant.builtin"] = plt.love_pulse,
      ["@constant.macro"] = plt.love_ember,

      ["@string"] = plt.love_pulse,
      ["@string.documentation"] = plt.love_pulse,
      ["@string.regex"] = plt.mega_rod_blue,
      ["@string.escape"] = plt.justice_glow,
      ["@string.special"] = plt.barda_red,
      ["@string.special.symbol"] = plt.barda_royal,
      ["@string.special.url"] = plt.barda_red,
      ["@string.special.path"] = plt.love_pulse,

      ["@character"] = plt.love_pulse,
      ["@character.special"] = plt.justice_glow,

      ["@number"] = plt.love_ember,
      ["@number.float"] = plt.love_ember,

      ["@boolean"] = plt.honor_gold,

      ["@function"] = plt.mega_rod_blue,
      ["@function.builtin"] = plt.mega_rod_blue,
      ["@function.call"] = plt.mega_rod_blue,
      ["@function.macro"] = plt.justice_glow,
      ["@function.method"] = plt.justice_glow,
      ["@function.method.call"] = plt.justice_glow,

      ["@constructor"] = plt.barda_royal,

      ["@parameter"] = plt.barda_blue,
      ["@parameter.builtin"] = plt.righteous_light,

      ["@keyword"] = plt.barda_royal,
      ["@keyword.coroutine"] = plt.honor_gold,
      ["@keyword.function"] = plt.barda_royal,
      ["@keyword.operator"] = plt.miracle_gold,
      ["@keyword.return"] = plt.barda_royal,
      ["@keyword.import"] = plt.mega_rod_blue,
      ["@keyword.storage"] = plt.barda_royal,
      ["@keyword.repeat"] = plt.barda_royal,
      ["@keyword.conditional"] = plt.barda_royal,
      ["@keyword.exception"] = plt.barda_red,
      ["@keyword.directive"] = plt.love_ember,
      ["@keyword.directive.define"] = plt.love_ember,

      ["@conditional"] = plt.barda_royal,
      ["@conditional.ternary"] = plt.barda_royal,

      ["@repeat"] = plt.barda_royal,

      ["@label"] = plt.mega_rod_blue,

      ["@operator"] = plt.miracle_gold,

      ["@exception"] = plt.barda_red,

      ["@variable"] = plt.righteous_light,
      ["@variable.builtin"] = plt.barda_royal,
      ["@variable.parameter"] = plt.barda_blue,
      ["@variable.member"] = plt.righteous_light,

      ["@type"] = plt.love_ember,
      ["@type.builtin"] = plt.love_ember,
      ["@type.definition"] = plt.love_ember,
      ["@type.qualifier"] = plt.barda_royal,

      ["@attribute"] = plt.righteous_light,
      ["@attribute.builtin"] = plt.love_ember,

      ["@property"] = plt.righteous_light,
      ["@field"] = plt.righteous_light,
      ["@module"] = plt.righteous_light,
      ["@module.builtin"] = plt.righteous_light,
      ["@namespace"] = plt.righteous_light,
      ["@namespace.builtin"] = plt.righteous_light,

      ["@punctuation.delimiter"] = plt.honor_skin,
      ["@punctuation.bracket"] = plt.honor_skin,
      ["@punctuation.special"] = plt.miracle_gold,

      ["@tag"] = plt.barda_royal,
      ["@tag.attribute"] = plt.love_ember,
      ["@tag.delimiter"] = plt.honor_skin,
      ["@tag.builtin"] = plt.barda_royal,

      ["@markup.strong"] = { fg = plt.barda_royal, bold = true },
      ["@markup.italic"] = { fg = plt.righteous_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.freedom_depth, strikethrough = true },
      ["@markup.underline"] = { fg = plt.honor_gold, underline = true },
      ["@markup.heading"] = plt.barda_royal,
      ["@markup.heading.1"] = plt.barda_royal,
      ["@markup.heading.2"] = plt.honor_gold,
      ["@markup.heading.3"] = plt.mega_rod_blue,
      ["@markup.heading.4"] = plt.justice_glow,
      ["@markup.heading.5"] = plt.miracle_gold,
      ["@markup.heading.6"] = plt.victory_gold,
      ["@markup.quote"] = plt.honor_skin,
      ["@markup.math"] = plt.mega_rod_blue,
      ["@markup.link"] = plt.justice_glow,
      ["@markup.link.label"] = plt.love_ember,
      ["@markup.link.url"] = plt.barda_red,
      ["@markup.raw"] = plt.victory_gold,
      ["@markup.raw.block"] = plt.victory_gold,
      ["@markup.list"] = plt.barda_royal,
      ["@markup.list.checked"] = plt.victory_gold,
      ["@markup.list.unchecked"] = plt.honor_skin,

      ["@diff.plus"] = plt.victory_gold,
      ["@diff.minus"] = plt.barda_red,
      ["@diff.delta"] = plt.mega_rod_blue,

      ["@none"] = "none",
      ["@conceal"] = plt.victory_gold,
      ["@spell"] = plt.righteous_light,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.righteous_light,
      ["@constructor.python"] = plt.barda_royal,
      ["@constructor.javascript"] = plt.barda_royal,
      ["@constructor.typescript"] = plt.barda_royal,
      ["@namespace.rust"] = plt.righteous_light,
      ["@type.qualifier.rust"] = plt.barda_royal,
      ["@constant.macro.c"] = plt.love_ember,
      ["@constant.macro.cpp"] = plt.love_ember,
      ["@namespace.go"] = plt.righteous_light,
      ["@property.css"] = plt.mega_rod_blue,
      ["@type.css"] = plt.barda_royal,
      ["@label.json"] = plt.righteous_light,
      ["@field.yaml"] = plt.barda_blue,
      ["@property.toml"] = plt.barda_blue,
      ["@function.builtin.bash"] = plt.mega_rod_blue,
      ["@string.regexp"] = plt.justice_glow,
      ["@character.special.regex"] = plt.miracle_gold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.love_ember,
      ["@lsp.type.interface"] = plt.love_ember,
      ["@lsp.type.struct"] = plt.love_ember,
      ["@lsp.type.enum"] = plt.love_ember,
      ["@lsp.type.enumMember"] = plt.victory_gold,
      ["@lsp.type.property"] = plt.righteous_light,
      ["@lsp.type.namespace"] = plt.righteous_light,

      ["@lsp.type.macro"] = plt.love_ember,
      ["@lsp.type.decorator"] = plt.barda_royal,

      ["@lsp.type.builtinType"] = plt.love_ember,
      ["@lsp.type.selfParameter"] = plt.barda_royal,
      ["@lsp.type.typeParameter"] = plt.love_ember,

      ["@lsp.type.array"] = plt.love_ember,
      ["@lsp.type.object"] = plt.love_ember,
      ["@lsp.type.key"] = plt.righteous_light,
      ["@lsp.type.null"] = plt.victory_gold,
      ["@lsp.type.enumConstant"] = plt.victory_gold,

      ["@lsp.type.event"] = plt.love_ember,
      ["@lsp.type.regexp"] = plt.justice_glow,
      ["@lsp.type.unresolvedReference"] = plt.barda_red,

      ["@lsp.mod.deprecated"] = { fg = plt.freedom_depth, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.victory_gold,
      ["@lsp.mod.async"] = plt.barda_royal,
      ["@lsp.mod.static"] = plt.love_ember,
      ["@lsp.mod.abstract"] = plt.love_ember,
      ["@lsp.mod.defaultLibrary"] = plt.love_ember,
      ["@lsp.mod.documentation"] = plt.barda_blue,
    },
  }
end

return {
  name = "New Gods – Big Barda",
  author = "PrismPunk.nvim",
  description = "The greatest warrior who chose love over tyranny. "
    .. "Royal blue might, molten gold honor, and now the living red of her iconic battle suit.",

  base16 = {
    base00 = palette.fury_void,
    base01 = palette.apokolips_scar,
    base02 = palette.broken_chain,
    base03 = palette.freedom_depth,
    base04 = palette.honor_skin,
    base05 = palette.barda_blue,
    base06 = palette.warrior_steel,
    base07 = palette.righteous_light,
    base08 = palette.barda_red,
    base09 = palette.barda_royal,
    base0A = palette.honor_gold,
    base0B = palette.mega_rod_blue,
    base0C = palette.justice_glow,
    base0D = palette.miracle_gold,
    base0E = palette.victory_gold,
    base0F = palette.eternal_bond,
  },

  palette = palette,
  get = M.get,
}
