local color = require("prismpunk.utils.color")

local palette = {
  metron_void = "#0A0014",
  timeless_depth = "#120028",
  chronal_shadow = "#1A0040",
  eternity_core = "#240066",
  observer_skin = "#332B55",
  chronal_flesh = "#4D4477",
  mobius_blue = "#665599",
  metron_purple = "#7F6BB3",
  source_knowledge = "#AADDFF",
  chronal_energy = "#88BBFF",
  mobius_current = "#6699FF",
  timeless_glow = "#4488FF",
  absolute_zero = "#2266FF",
  mobius_silver = "#CCCCCC",
  chronal_steel = "#BBBBDD",
  observer_white = "#EEEEFF",
  void_light = "#DDDDFF",
  sterile_radiance = "#CCCCFF",
  anti_life_violet = "#AA00FF",
  paradox_purple = "#BB22FF",
  eternity_pulse = "#CC44FF",
  singularity_glow = "#DD88FF",
  final_truth = "#EEBBFF",
  term_red = "#FF4488",
  term_green = "#88FFAA",
  term_blue = "#4488FF",
  term_yellow = "#FFDD88",
  term_cyan = "#88CCFF",
  time_fracture = "#110033",
  paradox_core = "#220066",
  mobius_coil = "#330099",
  chronal_rift = "#4400CC",
  final_moment = "#5500FF",

  bg_darkest = "#0A0014",
  fg_lightest = "#EEEEFF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.timeless_glow,
      insert = plt.paradox_purple,
      visual = plt.mobius_current,
      replace = plt.eternity_pulse,
      command = plt.chronal_energy,
    },

    ui = {
      fg = plt.observer_white,
      fg_dim = plt.source_knowledge,
      fg_dimmer = plt.metron_purple,
      fg_dark = plt.chronal_flesh,
      fg_reverse = plt.metron_void,

      bg_m4 = plt.eternity_core,
      bg_m3 = plt.chronal_shadow,
      bg_m2 = plt.timeless_depth,
      bg_m1 = plt.metron_void,
      bg_dim = plt.metron_void,
      bg = plt.metron_void,
      bg_p1 = plt.timeless_depth,
      bg_p2 = plt.chronal_shadow,
      bg_gutter = opts.gutter and plt.chronal_shadow or "none",
      bg_cursorline = plt.chronal_shadow,
      bg_cursorline_alt = plt.timeless_depth,
      bg_search = plt.timeless_glow,
      bg_visual = plt.mobius_current,
      bg_statusline = plt.chronal_shadow,

      border = plt.timeless_glow,
      header1 = plt.timeless_glow,
      header2 = plt.paradox_purple,
      special = plt.singularity_glow,
      nontext = plt.timeless_depth,
      whitespace = plt.eternity_core,
      win_separator = plt.timeless_glow,
      indent = plt.timeless_depth,
      indent_scope = plt.observer_white,
      picker = plt.chronal_energy,
      yank = plt.timeless_glow,
      mark = plt.void_light,
      scrollbar = plt.chronal_shadow,

      tabline = {
        bg = plt.metron_void,
        fg_selected = plt.timeless_glow,
        bg_selected = plt.chronal_shadow,
        fg_inactive = plt.metron_purple,
        bg_inactive = plt.metron_void,
        fg_alternate = plt.singularity_glow,
        bg_alternate = plt.metron_void,
        indicator = plt.mobius_current,
      },

      pmenu = {
        fg = plt.observer_white,
        fg_sel = "none",
        fg_border = plt.chronal_shadow,
        bg_border = plt.chronal_shadow,
        bg = plt.chronal_shadow,
        bg_sel = plt.timeless_depth,
        bg_sbar = plt.chronal_shadow,
        bg_thumb = plt.timeless_glow,
      },

      float = {
        fg = plt.observer_white,
        bg = plt.timeless_depth,
        fg_border = plt.chronal_shadow,
        bg_border = plt.timeless_depth,
      },
    },

    accent = {
      accent1 = plt.timeless_glow,
      accent2 = plt.paradox_purple,
      accent3 = plt.mobius_current,
      accent4 = plt.eternity_pulse,
      accent5 = plt.chronal_energy,
      invert = plt.chronal_shadow,
    },

    rainbow = {
      rainbow1 = plt.timeless_glow,
      rainbow2 = plt.mobius_current,
      rainbow3 = plt.chronal_energy,
      rainbow4 = plt.source_knowledge,
      rainbow5 = plt.paradox_purple,
      rainbow6 = plt.eternity_pulse,
      rainbow7 = plt.singularity_glow,
    },

    syn = {
      attribute = plt.observer_white,
      boolean = plt.paradox_purple,
      comment = plt.metron_purple,
      constant = plt.singularity_glow,
      deprecated = plt.eternity_core,
      func = plt.mobius_current,
      identifier = plt.observer_white,
      keyword = plt.timeless_glow,
      method = plt.chronal_energy,
      number = plt.eternity_pulse,
      operator = plt.source_knowledge,
      parameter = plt.source_knowledge,
      preproc = plt.source_knowledge,
      punct = plt.metron_purple,
      regex = plt.mobius_current,
      statement = plt.timeless_glow,
      string = plt.singularity_glow,
      symbol = plt.observer_white,
      type = plt.eternity_pulse,
      variable = plt.observer_white,
      special = plt.mobius_current,
      special2 = plt.chronal_energy,
      special3 = plt.paradox_purple,
    },

    vcs = { added = plt.singularity_glow, removed = plt.term_red, changed = plt.eternity_pulse },
    diff = {
      add = plt.singularity_glow,
      change = plt.mobius_current,
      delete = plt.term_red,
      text = plt.chronal_energy,
    },
    diag = {
      ok = plt.singularity_glow,
      error = plt.term_red,
      warning = plt.timeless_glow,
      info = plt.mobius_current,
      hint = plt.eternity_pulse,
    },

    term = {
      black = plt.metron_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.paradox_purple,
      cyan = plt.timeless_glow,
      white = plt.observer_white,

      black_bright = color(plt.metron_void):brighten(0.8):to_hex(),
      red_bright = "#ff6688",
      green_bright = "#aaffcc",
      yellow_bright = "#ffeeaa",
      blue_bright = "#88ccff",
      magenta_bright = "#dd88ff",
      cyan_bright = "#aaddff",
      white_bright = "#ffffff",
      indexed1 = plt.timeless_glow,
      indexed2 = plt.singularity_glow,
    },

    treesitter = {
      ["@comment"] = plt.metron_purple,
      ["@comment.documentation"] = plt.source_knowledge,
      ["@comment.error"] = plt.term_red,
      ["@comment.warning"] = plt.timeless_glow,
      ["@comment.todo"] = plt.singularity_glow,
      ["@comment.note"] = plt.mobius_current,

      ["@constant"] = plt.singularity_glow,
      ["@constant.builtin"] = plt.singularity_glow,
      ["@constant.macro"] = plt.eternity_pulse,

      ["@string"] = plt.singularity_glow,
      ["@string.documentation"] = plt.singularity_glow,
      ["@string.regex"] = plt.mobius_current,
      ["@string.escape"] = plt.chronal_energy,
      ["@string.special"] = plt.paradox_purple,
      ["@string.special.symbol"] = plt.timeless_glow,
      ["@string.special.url"] = plt.mobius_current,
      ["@string.special.path"] = plt.singularity_glow,

      ["@character"] = plt.singularity_glow,
      ["@character.special"] = plt.chronal_energy,

      ["@number"] = plt.eternity_pulse,
      ["@number.float"] = plt.eternity_pulse,

      ["@boolean"] = plt.paradox_purple,

      ["@function"] = plt.mobius_current,
      ["@function.builtin"] = plt.mobius_current,
      ["@function.call"] = plt.mobius_current,
      ["@function.macro"] = plt.chronal_energy,
      ["@function.method"] = plt.chronal_energy,
      ["@function.method.call"] = plt.chronal_energy,

      ["@constructor"] = plt.timeless_glow,

      ["@parameter"] = plt.source_knowledge,
      ["@parameter.builtin"] = plt.observer_white,

      ["@keyword"] = plt.timeless_glow,
      ["@keyword.coroutine"] = plt.paradox_purple,
      ["@keyword.function"] = plt.timeless_glow,
      ["@keyword.operator"] = plt.source_knowledge,
      ["@keyword.return"] = plt.timeless_glow,
      ["@keyword.import"] = plt.mobius_current,
      ["@keyword.storage"] = plt.timeless_glow,
      ["@keyword.repeat"] = plt.timeless_glow,
      ["@keyword.conditional"] = plt.timeless_glow,
      ["@keyword.exception"] = plt.term_red,
      ["@keyword.directive"] = plt.eternity_pulse,
      ["@keyword.directive.define"] = plt.eternity_pulse,

      ["@conditional"] = plt.timeless_glow,
      ["@conditional.ternary"] = plt.timeless_glow,

      ["@repeat"] = plt.timeless_glow,

      ["@label"] = plt.mobius_current,

      ["@operator"] = plt.source_knowledge,

      ["@exception"] = plt.term_red,

      ["@variable"] = plt.observer_white,
      ["@variable.builtin"] = plt.timeless_glow,
      ["@variable.parameter"] = plt.source_knowledge,
      ["@variable.member"] = plt.observer_white,

      ["@type"] = plt.eternity_pulse,
      ["@type.builtin"] = plt.eternity_pulse,
      ["@type.definition"] = plt.eternity_pulse,
      ["@type.qualifier"] = plt.timeless_glow,

      ["@attribute"] = plt.observer_white,
      ["@attribute.builtin"] = plt.eternity_pulse,

      ["@property"] = plt.observer_white,
      ["@field"] = plt.observer_white,
      ["@module"] = plt.observer_white,
      ["@module.builtin"] = plt.observer_white,
      ["@namespace"] = plt.observer_white,
      ["@namespace.builtin"] = plt.observer_white,

      ["@punctuation.delimiter"] = plt.metron_purple,
      ["@punctuation.bracket"] = plt.metron_purple,
      ["@punctuation.special"] = plt.source_knowledge,

      ["@tag"] = plt.timeless_glow,
      ["@tag.attribute"] = plt.eternity_pulse,
      ["@tag.delimiter"] = plt.metron_purple,
      ["@tag.builtin"] = plt.timeless_glow,

      ["@markup.strong"] = { fg = plt.timeless_glow, bold = true },
      ["@markup.italic"] = { fg = plt.observer_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.eternity_core, strikethrough = true },
      ["@markup.underline"] = { fg = plt.paradox_purple, underline = true },
      ["@markup.heading"] = plt.timeless_glow,
      ["@markup.heading.1"] = plt.timeless_glow,
      ["@markup.heading.2"] = plt.paradox_purple,
      ["@markup.heading.3"] = plt.mobius_current,
      ["@markup.heading.4"] = plt.chronal_energy,
      ["@markup.heading.5"] = plt.eternity_pulse,
      ["@markup.heading.6"] = plt.singularity_glow,
      ["@markup.quote"] = plt.metron_purple,
      ["@markup.math"] = plt.mobius_current,
      ["@markup.link"] = plt.chronal_energy,
      ["@markup.link.label"] = plt.eternity_pulse,
      ["@markup.link.url"] = plt.singularity_glow,
      ["@markup.raw"] = plt.singularity_glow,
      ["@markup.raw.block"] = plt.singularity_glow,
      ["@markup.list"] = plt.timeless_glow,
      ["@markup.list.checked"] = plt.singularity_glow,
      ["@markup.list.unchecked"] = plt.metron_purple,

      ["@diff.plus"] = plt.singularity_glow,
      ["@diff.minus"] = plt.term_red,
      ["@diff.delta"] = plt.mobius_current,

      ["@none"] = "none",
      ["@conceal"] = plt.singularity_glow,
      ["@spell"] = plt.observer_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.observer_white,
      ["@constructor.python"] = plt.timeless_glow,
      ["@constructor.javascript"] = plt.timeless_glow,
      ["@constructor.typescript"] = plt.timeless_glow,
      ["@namespace.rust"] = plt.observer_white,
      ["@type.qualifier.rust"] = plt.timeless_glow,
      ["@constant.macro.c"] = plt.eternity_pulse,
      ["@constant.macro.cpp"] = plt.eternity_pulse,
      ["@namespace.go"] = plt.observer_white,
      ["@property.css"] = plt.mobius_current,
      ["@type.css"] = plt.timeless_glow,
      ["@label.json"] = plt.observer_white,
      ["@field.yaml"] = plt.source_knowledge,
      ["@property.toml"] = plt.source_knowledge,
      ["@function.builtin.bash"] = plt.mobius_current,
      ["@string.regexp"] = plt.chronal_energy,
      ["@character.special.regex"] = plt.source_knowledge,
    },

    lsp = {
      ["@lsp.type.class"] = plt.eternity_pulse,
      ["@lsp.type.interface"] = plt.eternity_pulse,
      ["@lsp.type.struct"] = plt.eternity_pulse,
      ["@lsp.type.enum"] = plt.eternity_pulse,
      ["@lsp.type.enumMember"] = plt.singularity_glow,
      ["@lsp.type.property"] = plt.observer_white,
      ["@lsp.type.namespace"] = plt.observer_white,

      ["@lsp.type.macro"] = plt.eternity_pulse,
      ["@lsp.type.decorator"] = plt.timeless_glow,

      ["@lsp.type.builtinType"] = plt.eternity_pulse,
      ["@lsp.type.selfParameter"] = plt.timeless_glow,
      ["@lsp.type.typeParameter"] = plt.eternity_pulse,

      ["@lsp.type.array"] = plt.eternity_pulse,
      ["@lsp.type.object"] = plt.eternity_pulse,
      ["@lsp.type.key"] = plt.observer_white,
      ["@lsp.type.null"] = plt.singularity_glow,
      ["@lsp.type.enumConstant"] = plt.singularity_glow,

      ["@lsp.type.event"] = plt.eternity_pulse,
      ["@lsp.type.regexp"] = plt.chronal_energy,
      ["@lsp.type.unresolvedReference"] = plt.term_red,

      ["@lsp.mod.deprecated"] = { fg = plt.eternity_core, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.singularity_glow,
      ["@lsp.mod.async"] = plt.timeless_glow,
      ["@lsp.mod.static"] = plt.eternity_pulse,
      ["@lsp.mod.abstract"] = plt.eternity_pulse,
      ["@lsp.mod.defaultLibrary"] = plt.eternity_pulse,
      ["@lsp.mod.documentation"] = plt.source_knowledge,
    },
  }
end

return {
  name = "New Gods – Metron",
  author = "PrismPunk.nvim",
  description = "The eternal observer beyond time and allegiance. Absolute zero violet, "
    .. "sterile silver, and the merciless blue-white of pure knowledge.",

  base16 = {
    base00 = palette.metron_void,
    base01 = palette.timeless_depth,
    base02 = palette.chronal_shadow,
    base03 = palette.eternity_core,
    base04 = palette.metron_purple,
    base05 = palette.source_knowledge,
    base06 = palette.chronal_flesh,
    base07 = palette.observer_white,
    base08 = palette.term_red,
    base09 = palette.timeless_glow,
    base0A = palette.paradox_purple,
    base0B = palette.mobius_current,
    base0C = palette.chronal_energy,
    base0D = palette.eternity_pulse,
    base0E = palette.singularity_glow,
    base0F = palette.void_light,
  },

  palette = palette,
  get = M.get,
}
