local color = require("prismpunk.utils.color")

local palette = {
  source_void = "#0A001A",
  cosmic_depth = "#140032",
  eternity_shadow = "#1E004D",
  infinity_core = "#28006B",
  joshua_skin = "#443388",
  conduit_flesh = "#5E4AAA",
  source_violet = "#8877DD",
  takion_royal = "#A090FF",
  source_light = "#FFFFFF",
  source_glow = "#FFFFEE",
  source_flare = "#FFFFCC",
  source_radiance = "#FFFFAA",
  cosmic_cyan = "#00FFFF",
  cosmic_teal = "#00DDEE",
  cosmic_aqua = "#00BBFF",
  cosmic_blue = "#0088FF",
  cosmic_indigo = "#4466FF",
  chronos_purple = "#CC00FF",
  chronos_magenta = "#EE22FF",
  chronos_pink = "#FF44EE",
  chronos_lavender = "#FF88FF",
  creation_gold = "#FFDD00",
  destruction_red = "#FF0044",
  rebirth_orange = "#FF6600",
  equilibrium_green = "#00FF99",
  term_red = "#FF0044",
  term_green = "#00FF99",
  term_blue = "#0088FF",
  term_yellow = "#FFDD00",
  term_cyan = "#00FFFF",
  term_magenta = "#EE22FF",
  term_red_bright = "#FF4488",
  term_green_bright = "#88FFCC",
  term_yellow_bright = "#FFEE66",
  term_blue_bright = "#88BBFF",
  term_magenta_bright = "#FF88FF",
  term_cyan_bright = "#88FFFF",

  bg_darkest = "#0A001A",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.source_light,
      insert = plt.cosmic_cyan,
      visual = plt.chronos_magenta,
      replace = plt.destruction_red,
      command = plt.creation_gold,
    },

    ui = {
      fg = plt.source_light,
      fg_dim = plt.takion_royal,
      fg_dimmer = plt.source_violet,
      fg_dark = plt.conduit_flesh,
      fg_reverse = plt.source_void,

      bg_m4 = plt.infinity_core,
      bg_m3 = plt.eternity_shadow,
      bg_m2 = plt.cosmic_depth,
      bg_m1 = plt.source_void,
      bg_dim = plt.source_void,
      bg = plt.source_void,
      bg_p1 = plt.cosmic_depth,
      bg_p2 = plt.eternity_shadow,
      bg_gutter = opts.gutter and plt.eternity_shadow or "none",
      bg_cursorline = plt.eternity_shadow,
      bg_cursorline_alt = plt.cosmic_depth,
      bg_search = plt.source_flare,
      bg_visual = plt.chronos_pink,
      bg_statusline = plt.eternity_shadow,

      border = plt.source_glow,
      header1 = plt.source_light,
      header2 = plt.cosmic_cyan,
      special = plt.chronos_magenta,
      nontext = plt.cosmic_depth,
      whitespace = plt.infinity_core,
      win_separator = plt.source_glow,
      indent = plt.cosmic_depth,
      indent_scope = plt.source_light,
      picker = plt.cosmic_aqua,
      yank = plt.source_radiance,
      mark = plt.creation_gold,
      scrollbar = plt.eternity_shadow,

      tabline = {
        bg = plt.source_void,
        fg_selected = plt.source_light,
        bg_selected = plt.eternity_shadow,
        fg_inactive = plt.source_violet,
        bg_inactive = plt.source_void,
        fg_alternate = plt.cosmic_cyan,
        bg_alternate = plt.source_void,
        indicator = plt.chronos_magenta,
      },

      pmenu = {
        fg = plt.source_light,
        fg_sel = "none",
        fg_border = plt.eternity_shadow,
        bg_border = plt.eternity_shadow,
        bg = plt.eternity_shadow,
        bg_sel = plt.cosmic_depth,
        bg_sbar = plt.eternity_shadow,
        bg_thumb = plt.source_glow,
      },

      float = {
        fg = plt.source_light,
        bg = plt.cosmic_depth,
        fg_border = plt.eternity_shadow,
        bg_border = plt.cosmic_depth,
      },
    },

    accent = {
      accent1 = plt.source_light,
      accent2 = plt.cosmic_cyan,
      accent3 = plt.chronos_magenta,
      accent4 = plt.creation_gold,
      accent5 = plt.equilibrium_green,
      invert = plt.eternity_shadow,
    },

    rainbow = {
      rainbow1 = plt.source_light,
      rainbow2 = plt.cosmic_cyan,
      rainbow3 = plt.cosmic_blue,
      rainbow4 = plt.chronos_purple,
      rainbow5 = plt.chronos_magenta,
      rainbow6 = plt.creation_gold,
      rainbow7 = plt.equilibrium_green,
    },

    syn = {
      attribute = plt.source_light,
      boolean = plt.destruction_red,
      comment = plt.source_violet,
      constant = plt.creation_gold,
      deprecated = plt.infinity_core,
      func = plt.cosmic_cyan,
      identifier = plt.source_light,
      keyword = plt.source_glow,
      method = plt.cosmic_aqua,
      number = plt.creation_gold,
      operator = plt.chronos_pink,
      parameter = plt.takion_royal,
      preproc = plt.chronos_magenta,
      punct = plt.source_violet,
      regex = plt.cosmic_teal,
      statement = plt.source_glow,
      string = plt.equilibrium_green,
      symbol = plt.source_light,
      type = plt.creation_gold,
      variable = plt.source_light,
      special = plt.cosmic_cyan,
      special2 = plt.chronos_magenta,
      special3 = plt.destruction_red,
    },

    vcs = { added = plt.equilibrium_green, removed = plt.destruction_red, changed = plt.creation_gold },
    diff = {
      add = plt.equilibrium_green,
      change = plt.cosmic_indigo,
      delete = plt.destruction_red,
      text = plt.cosmic_aqua,
    },
    diag = {
      ok = plt.equilibrium_green,
      error = plt.destruction_red,
      warning = plt.creation_gold,
      info = plt.cosmic_cyan,
      hint = plt.chronos_lavender,
    },

    term = {
      black = plt.source_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_magenta,
      cyan = plt.term_cyan,
      white = plt.source_light,

      black_bright = color(plt.source_void):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_magenta_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.source_light,
      indexed2 = plt.cosmic_cyan,
    },

    treesitter = {
      ["@comment"] = plt.source_violet,
      ["@comment.documentation"] = plt.takion_royal,
      ["@comment.error"] = plt.destruction_red,
      ["@comment.warning"] = plt.creation_gold,
      ["@comment.todo"] = plt.equilibrium_green,
      ["@comment.note"] = plt.cosmic_cyan,

      ["@constant"] = plt.creation_gold,
      ["@constant.builtin"] = plt.creation_gold,
      ["@constant.macro"] = plt.rebirth_orange,

      ["@string"] = plt.equilibrium_green,
      ["@string.documentation"] = plt.equilibrium_green,
      ["@string.regex"] = plt.cosmic_teal,
      ["@string.escape"] = plt.chronos_pink,
      ["@string.special"] = plt.destruction_red,
      ["@string.special.symbol"] = plt.source_light,
      ["@string.special.url"] = plt.cosmic_blue,
      ["@string.special.path"] = plt.equilibrium_green,

      ["@character"] = plt.equilibrium_green,
      ["@character.special"] = plt.chronos_pink,

      ["@number"] = plt.creation_gold,
      ["@number.float"] = plt.creation_gold,

      ["@boolean"] = plt.destruction_red,

      ["@function"] = plt.cosmic_cyan,
      ["@function.builtin"] = plt.cosmic_cyan,
      ["@function.call"] = plt.cosmic_cyan,
      ["@function.macro"] = plt.chronos_magenta,
      ["@function.method"] = plt.cosmic_aqua,
      ["@function.method.call"] = plt.cosmic_aqua,

      ["@constructor"] = plt.source_light,

      ["@parameter"] = plt.takion_royal,
      ["@parameter.builtin"] = plt.source_light,

      ["@keyword"] = plt.source_glow,
      ["@keyword.coroutine"] = plt.chronos_magenta,
      ["@keyword.function"] = plt.source_glow,
      ["@keyword.operator"] = plt.chronos_pink,
      ["@keyword.return"] = plt.source_glow,
      ["@keyword.import"] = plt.cosmic_cyan,
      ["@keyword.storage"] = plt.source_glow,
      ["@keyword.repeat"] = plt.source_glow,
      ["@keyword.conditional"] = plt.source_glow,
      ["@keyword.exception"] = plt.destruction_red,
      ["@keyword.directive"] = plt.creation_gold,
      ["@keyword.directive.define"] = plt.creation_gold,

      ["@conditional"] = plt.source_glow,
      ["@conditional.ternary"] = plt.source_glow,

      ["@repeat"] = plt.source_glow,

      ["@label"] = plt.cosmic_cyan,

      ["@operator"] = plt.chronos_pink,

      ["@exception"] = plt.destruction_red,

      ["@variable"] = plt.source_light,
      ["@variable.builtin"] = plt.source_glow,
      ["@variable.parameter"] = plt.takion_royal,
      ["@variable.member"] = plt.source_light,

      ["@type"] = plt.creation_gold,
      ["@type.builtin"] = plt.creation_gold,
      ["@type.definition"] = plt.creation_gold,
      ["@type.qualifier"] = plt.source_glow,

      ["@attribute"] = plt.source_light,
      ["@attribute.builtin"] = plt.creation_gold,

      ["@property"] = plt.source_light,
      ["@field"] = plt.source_light,
      ["@module"] = plt.source_light,
      ["@module.builtin"] = plt.source_light,
      ["@namespace"] = plt.source_light,
      ["@namespace.builtin"] = plt.source_light,

      ["@punctuation.delimiter"] = plt.source_violet,
      ["@punctuation.bracket"] = plt.chronos_lavender,
      ["@punctuation.special"] = plt.chronos_pink,

      ["@tag"] = plt.source_glow,
      ["@tag.attribute"] = plt.creation_gold,
      ["@tag.delimiter"] = plt.source_violet,
      ["@tag.builtin"] = plt.source_glow,

      ["@markup.strong"] = { fg = plt.source_light, bold = true },
      ["@markup.italic"] = { fg = plt.source_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.infinity_core, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cosmic_cyan, underline = true },
      ["@markup.heading"] = plt.source_light,
      ["@markup.heading.1"] = plt.source_light,
      ["@markup.heading.2"] = plt.cosmic_cyan,
      ["@markup.heading.3"] = plt.chronos_magenta,
      ["@markup.heading.4"] = plt.creation_gold,
      ["@markup.heading.5"] = plt.equilibrium_green,
      ["@markup.heading.6"] = plt.rebirth_orange,
      ["@markup.quote"] = plt.source_violet,
      ["@markup.math"] = plt.cosmic_blue,
      ["@markup.link"] = plt.cosmic_aqua,
      ["@markup.link.label"] = plt.creation_gold,
      ["@markup.link.url"] = plt.chronos_pink,
      ["@markup.raw"] = plt.equilibrium_green,
      ["@markup.raw.block"] = plt.equilibrium_green,
      ["@markup.list"] = plt.source_glow,
      ["@markup.list.checked"] = plt.equilibrium_green,
      ["@markup.list.unchecked"] = plt.source_violet,

      ["@diff.plus"] = plt.equilibrium_green,
      ["@diff.minus"] = plt.destruction_red,
      ["@diff.delta"] = plt.cosmic_indigo,

      ["@none"] = "none",
      ["@conceal"] = plt.creation_gold,
      ["@spell"] = plt.source_light,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.source_light,
      ["@constructor.python"] = plt.source_light,
      ["@constructor.javascript"] = plt.source_light,
      ["@constructor.typescript"] = plt.source_light,
      ["@namespace.rust"] = plt.source_light,
      ["@type.qualifier.rust"] = plt.source_glow,
      ["@constant.macro.c"] = plt.creation_gold,
      ["@constant.macro.cpp"] = plt.creation_gold,
      ["@namespace.go"] = plt.source_light,
      ["@property.css"] = plt.cosmic_cyan,
      ["@type.css"] = plt.source_glow,
      ["@label.json"] = plt.source_light,
      ["@field.yaml"] = plt.takion_royal,
      ["@property.toml"] = plt.takion_royal,
      ["@function.builtin.bash"] = plt.cosmic_cyan,
      ["@string.regexp"] = plt.chronos_pink,
      ["@character.special.regex"] = plt.chronos_magenta,
    },

    lsp = {
      ["@lsp.type.class"] = plt.creation_gold,
      ["@lsp.type.interface"] = plt.creation_gold,
      ["@lsp.type.struct"] = plt.creation_gold,
      ["@lsp.type.enum"] = plt.creation_gold,
      ["@lsp.type.enumMember"] = plt.equilibrium_green,
      ["@lsp.type.property"] = plt.source_light,
      ["@lsp.type.namespace"] = plt.source_light,

      ["@lsp.type.macro"] = plt.creation_gold,
      ["@lsp.type.decorator"] = plt.source_glow,

      ["@lsp.type.builtinType"] = plt.creation_gold,
      ["@lsp.type.selfParameter"] = plt.source_glow,
      ["@lsp.type.typeParameter"] = plt.creation_gold,

      ["@lsp.type.array"] = plt.creation_gold,
      ["@lsp.type.object"] = plt.creation_gold,
      ["@lsp.type.key"] = plt.source_light,
      ["@lsp.type.null"] = plt.equilibrium_green,
      ["@lsp.type.enumConstant"] = plt.equilibrium_green,

      ["@lsp.type.event"] = plt.creation_gold,
      ["@lsp.type.regexp"] = plt.chronos_pink,
      ["@lsp.type.unresolvedReference"] = plt.destruction_red,

      ["@lsp.mod.deprecated"] = { fg = plt.infinity_core, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.equilibrium_green,
      ["@lsp.mod.async"] = plt.source_glow,
      ["@lsp.mod.static"] = plt.creation_gold,
      ["@lsp.mod.abstract"] = plt.creation_gold,
      ["@lsp.mod.defaultLibrary"] = plt.creation_gold,
      ["@lsp.mod.documentation"] = plt.takion_royal,
    },
  }
end

return {
  name = "New Gods – Takion",
  author = "PrismPunk.nvim",
  description = "Joshua Saunders became the living Source. Infinite white-gold light, "
    .. "cosmic cyan currents, and magenta waves of distorted time. "
    .. "This theme is the universe speaking through code.",

  base16 = {
    base00 = palette.source_void,
    base01 = palette.cosmic_depth,
    base02 = palette.eternity_shadow,
    base03 = palette.infinity_core,
    base04 = palette.source_violet,
    base05 = palette.takion_royal,
    base06 = palette.conduit_flesh,
    base07 = palette.source_light,
    base08 = palette.destruction_red,
    base09 = palette.creation_gold,
    base0A = palette.cosmic_cyan,
    base0B = palette.equilibrium_green,
    base0C = palette.chronos_magenta,
    base0D = palette.source_glow,
    base0E = palette.chronos_purple,
    base0F = palette.source_flare,
  },

  palette = palette,
  get = M.get,
}
