local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0C10",
  barfight_night = "#0D1118",
  digger_core = "#121822",
  pub_glow = "#182030",
  fosters_blue = "#00AAFF",
  vb_blue = "#00BBFF",
  xxxx_blue = "#00CCFF",
  boomer_blue = "#44DDFF",
  chicken_salt = "#FFDD00",
  chiko_roll = "#FFEE33",
  dimmie_yellow = "#FFFF55",
  stubby_red = "#FF2200",
  boomerang_red = "#FF3344",
  blood_gush = "#FF5566",
  pie_sauce = "#FF7788",
  outback_brown = "#8B5A2B",
  cork_hat = "#A07040",
  vegemite_brown = "#B58855",
  beer_foam = "#F0F8FF",
  hangover_white = "#E6EEFF",
  term_blue = "#00BBFF",
  term_yellow = "#FFEE33",
  term_red = "#FF3344",
  term_brown = "#B58855",
  term_white = "#E6EEFF",
  term_blue_bright = "#44DDFF",
  term_yellow_bright = "#FFFF88",
  term_red_bright = "#FF7788",

  bg_darkest = "#0A0C10",
  fg_lightest = "#FFFF88",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.vb_blue,
      insert = plt.dimmie_yellow,
      visual = plt.boomerang_red,
      replace = plt.blood_gush,
      command = plt.fosters_blue,
    },

    ui = {
      fg = plt.beer_foam,
      fg_dim = plt.hangover_white,
      fg_dimmer = plt.hangover_white,
      fg_dark = plt.cork_hat,
      fg_reverse = plt.void_black,

      bg_m4 = plt.pub_glow,
      bg_m3 = plt.digger_core,
      bg_m2 = plt.barfight_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.barfight_night,
      bg_p2 = plt.digger_core,
      bg_gutter = opts.gutter and plt.digger_core or "none",
      bg_cursorline = plt.digger_core,
      bg_cursorline_alt = plt.barfight_night,
      bg_search = plt.chicken_salt,
      bg_visual = plt.boomerang_red,
      bg_statusline = plt.digger_core,

      border = plt.dimmie_yellow,
      header1 = plt.vb_blue,
      header2 = plt.stubby_red,
      special = plt.chiko_roll,
      nontext = plt.barfight_night,
      whitespace = plt.pub_glow,
      win_separator = plt.dimmie_yellow,
      indent = plt.barfight_night,
      indent_scope = plt.boomer_blue,
      picker = plt.beer_foam,
      yank = plt.pie_sauce,
      mark = plt.blood_gush,
      scrollbar = plt.digger_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.beer_foam,
        bg_selected = plt.digger_core,
        fg_inactive = plt.hangover_white,
        bg_inactive = plt.void_black,
        fg_alternate = plt.boomerang_red,
        bg_alternate = plt.void_black,
        indicator = plt.chicken_salt,
      },

      pmenu = {
        fg = plt.beer_foam,
        fg_sel = "none",
        fg_border = plt.digger_core,
        bg_border = plt.digger_core,
        bg = plt.digger_core,
        bg_sel = plt.barfight_night,
        bg_sbar = plt.digger_core,
        bg_thumb = plt.dimmie_yellow,
      },

      float = {
        fg = plt.beer_foam,
        bg = plt.barfight_night,
        fg_border = plt.digger_core,
        bg_border = plt.barfight_night,
      },
    },

    accent = {
      accent1 = plt.vb_blue,
      accent2 = plt.boomerang_red,
      accent3 = plt.chicken_salt,
      accent4 = plt.boomer_blue,
      accent5 = plt.pie_sauce,
      invert = plt.digger_core,
    },

    rainbow = {
      rainbow1 = plt.vb_blue,
      rainbow2 = plt.xxxx_blue,
      rainbow3 = plt.boomer_blue,
      rainbow4 = plt.boomerang_red,
      rainbow5 = plt.blood_gush,
      rainbow6 = plt.chicken_salt,
      rainbow7 = plt.dimmie_yellow,
    },

    syn = {
      attribute = plt.beer_foam,
      boolean = plt.blood_gush,
      comment = plt.hangover_white,
      constant = plt.dimmie_yellow,
      deprecated = plt.pub_glow,
      func = plt.vb_blue,
      identifier = plt.beer_foam,
      keyword = plt.vb_blue,
      method = plt.chicken_salt,
      number = plt.stubby_red,
      operator = plt.boomer_blue,
      parameter = plt.hangover_white,
      preproc = plt.boomerang_red,
      punct = plt.beer_foam,
      regex = plt.xxxx_blue,
      statement = plt.vb_blue,
      string = plt.chiko_roll,
      symbol = plt.beer_foam,
      type = plt.chicken_salt,
      variable = plt.beer_foam,
      special = plt.pie_sauce,
      special2 = plt.boomer_blue,
      special3 = plt.blood_gush,
    },

    vcs = { added = plt.boomer_blue, removed = plt.boomerang_red, changed = plt.chicken_salt },
    diff = { add = plt.boomer_blue, change = plt.vb_blue, delete = plt.blood_gush, text = plt.dimmie_yellow },
    diag = {
      ok = plt.boomer_blue,
      error = plt.blood_gush,
      warning = plt.boomerang_red,
      info = plt.vb_blue,
      hint = plt.chicken_salt,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.vb_blue,
      indexed2 = plt.boomerang_red,
    },

    treesitter = {
      ["@comment"] = plt.hangover_white,
      ["@comment.documentation"] = plt.hangover_white,
      ["@comment.error"] = plt.blood_gush,
      ["@comment.warning"] = plt.boomerang_red,
      ["@comment.todo"] = plt.pie_sauce,
      ["@comment.note"] = plt.boomer_blue,

      ["@constant"] = plt.dimmie_yellow,
      ["@constant.builtin"] = plt.chicken_salt,
      ["@constant.macro"] = plt.blood_gush,

      ["@string"] = plt.chiko_roll,
      ["@string.documentation"] = plt.dimmie_yellow,
      ["@string.regex"] = plt.xxxx_blue,
      ["@string.escape"] = plt.boomer_blue,
      ["@string.special"] = plt.boomerang_red,
      ["@string.special.symbol"] = plt.beer_foam,
      ["@string.special.url"] = plt.chicken_salt,
      ["@string.special.path"] = plt.chiko_roll,

      ["@character"] = plt.chiko_roll,
      ["@character.special"] = plt.boomer_blue,

      ["@number"] = plt.stubby_red,
      ["@number.float"] = plt.stubby_red,

      ["@boolean"] = plt.boomerang_red,

      ["@function"] = plt.vb_blue,
      ["@function.builtin"] = plt.vb_blue,
      ["@function.call"] = plt.vb_blue,
      ["@function.macro"] = plt.chicken_salt,
      ["@function.method"] = plt.chicken_salt,
      ["@function.method.call"] = plt.chicken_salt,

      ["@constructor"] = plt.beer_foam,

      ["@parameter"] = plt.hangover_white,
      ["@parameter.builtin"] = plt.beer_foam,

      ["@keyword"] = plt.vb_blue,
      ["@keyword.coroutine"] = plt.boomerang_red,
      ["@keyword.function"] = plt.vb_blue,
      ["@keyword.operator"] = plt.boomer_blue,
      ["@keyword.return"] = plt.vb_blue,
      ["@keyword.import"] = plt.chicken_salt,
      ["@keyword.storage"] = plt.vb_blue,
      ["@keyword.repeat"] = plt.vb_blue,
      ["@keyword.conditional"] = plt.vb_blue,
      ["@keyword.exception"] = plt.blood_gush,
      ["@keyword.directive"] = plt.boomerang_red,
      ["@keyword.directive.define"] = plt.boomerang_red,

      ["@conditional"] = plt.vb_blue,
      ["@conditional.ternary"] = plt.vb_blue,

      ["@repeat"] = plt.vb_blue,

      ["@label"] = plt.chicken_salt,

      ["@operator"] = plt.boomer_blue,

      ["@exception"] = plt.blood_gush,

      ["@variable"] = plt.beer_foam,
      ["@variable.builtin"] = plt.dimmie_yellow,
      ["@variable.parameter"] = plt.hangover_white,
      ["@variable.member"] = plt.beer_foam,

      ["@type"] = plt.chicken_salt,
      ["@type.builtin"] = plt.chicken_salt,
      ["@type.definition"] = plt.chicken_salt,
      ["@type.qualifier"] = plt.vb_blue,

      ["@attribute"] = plt.beer_foam,
      ["@attribute.builtin"] = plt.chicken_salt,

      ["@property"] = plt.beer_foam,
      ["@field"] = plt.beer_foam,
      ["@module"] = plt.beer_foam,
      ["@module.builtin"] = plt.beer_foam,
      ["@namespace"] = plt.beer_foam,
      ["@namespace.builtin"] = plt.beer_foam,

      ["@punctuation.delimiter"] = plt.beer_foam,
      ["@punctuation.bracket"] = plt.boomer_blue,
      ["@punctuation.special"] = plt.xxxx_blue,

      ["@tag"] = plt.vb_blue,
      ["@tag.attribute"] = plt.chicken_salt,
      ["@tag.delimiter"] = plt.beer_foam,
      ["@tag.builtin"] = plt.vb_blue,

      ["@markup.strong"] = { fg = plt.vb_blue, bold = true },
      ["@markup.italic"] = { fg = plt.beer_foam, italic = true },
      ["@markup.strikethrough"] = { fg = plt.pub_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.boomerang_red, underline = true },
      ["@markup.heading"] = plt.vb_blue,
      ["@markup.heading.1"] = plt.vb_blue,
      ["@markup.heading.2"] = plt.boomerang_red,
      ["@markup.heading.3"] = plt.blood_gush,
      ["@markup.heading.4"] = plt.chicken_salt,
      ["@markup.heading.5"] = plt.dimmie_yellow,
      ["@markup.heading.6"] = plt.chiko_roll,
      ["@markup.quote"] = plt.hangover_white,
      ["@markup.math"] = plt.boomer_blue,
      ["@markup.link"] = plt.chicken_salt,
      ["@markup.link.label"] = plt.dimmie_yellow,
      ["@markup.link.url"] = plt.xxxx_blue,
      ["@markup.raw"] = plt.chiko_roll,
      ["@markup.raw.block"] = plt.chiko_roll,
      ["@markup.list"] = plt.vb_blue,
      ["@markup.list.checked"] = plt.boomer_blue,
      ["@markup.list.unchecked"] = plt.hangover_white,

      ["@diff.plus"] = plt.boomer_blue,
      ["@diff.minus"] = plt.boomerang_red,
      ["@diff.delta"] = plt.chicken_salt,

      ["@none"] = "none",
      ["@conceal"] = plt.dimmie_yellow,
      ["@spell"] = plt.beer_foam,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.beer_foam,
      ["@constructor.python"] = plt.vb_blue,
      ["@constructor.javascript"] = plt.vb_blue,
      ["@constructor.typescript"] = plt.vb_blue,
      ["@namespace.rust"] = plt.beer_foam,
      ["@type.qualifier.rust"] = plt.vb_blue,
      ["@constant.macro.c"] = plt.blood_gush,
      ["@constant.macro.cpp"] = plt.blood_gush,
      ["@namespace.go"] = plt.beer_foam,
      ["@property.css"] = plt.chicken_salt,
      ["@type.css"] = plt.vb_blue,
      ["@label.json"] = plt.beer_foam,
      ["@field.yaml"] = plt.hangover_white,
      ["@property.toml"] = plt.hangover_white,
      ["@function.builtin.bash"] = plt.chicken_salt,
      ["@string.regexp"] = plt.xxxx_blue,
      ["@character.special.regex"] = plt.boomer_blue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.chicken_salt,
      ["@lsp.type.interface"] = plt.chicken_salt,
      ["@lsp.type.struct"] = plt.chicken_salt,
      ["@lsp.type.enum"] = plt.chicken_salt,
      ["@lsp.type.enumMember"] = plt.dimmie_yellow,
      ["@lsp.type.property"] = plt.beer_foam,
      ["@lsp.type.namespace"] = plt.beer_foam,

      ["@lsp.type.macro"] = plt.blood_gush,
      ["@lsp.type.decorator"] = plt.vb_blue,

      ["@lsp.type.builtinType"] = plt.chicken_salt,
      ["@lsp.type.selfParameter"] = plt.vb_blue,
      ["@lsp.type.typeParameter"] = plt.chicken_salt,

      ["@lsp.type.array"] = plt.chicken_salt,
      ["@lsp.type.object"] = plt.chicken_salt,
      ["@lsp.type.key"] = plt.beer_foam,
      ["@lsp.type.null"] = plt.dimmie_yellow,
      ["@lsp.type.enumConstant"] = plt.dimmie_yellow,

      ["@lsp.type.event"] = plt.chicken_salt,
      ["@lsp.type.regexp"] = plt.xxxx_blue,
      ["@lsp.type.unresolvedReference"] = plt.blood_gush,

      ["@lsp.mod.deprecated"] = { fg = plt.pub_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.dimmie_yellow,
      ["@lsp.mod.async"] = plt.vb_blue,
      ["@lsp.mod.static"] = plt.chicken_salt,
      ["@lsp.mod.abstract"] = plt.chicken_salt,
      ["@lsp.mod.defaultLibrary"] = plt.chicken_salt,
      ["@lsp.mod.documentation"] = plt.hangover_white,
    },
  }
end

return {
  name = "Captain Boomerang – Digger Harkness",
  author = "PrismPunk.nvim",
  description = "Cheap beer neon, takeaway grease, and the ugliest blue jacket in Gotham. "
    .. "He’s a walking pub brawl with exploding boomerangs. Straya, c***!",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.barfight_night,
    base02 = palette.digger_core,
    base03 = palette.pub_glow,
    base04 = palette.boomer_blue,
    base05 = palette.hangover_white,
    base06 = palette.beer_foam,
    base07 = palette.beer_foam,
    base08 = palette.boomerang_red,
    base09 = palette.blood_gush,
    base0A = palette.chicken_salt,
    base0B = palette.dimmie_yellow,
    base0C = palette.vb_blue,
    base0D = palette.xxxx_blue,
    base0E = palette.fosters_blue,
    base0F = palette.chiko_roll,
  },

  palette = palette,
  get = M.get,
}
