local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0A0C",
  clay_night = "#0C0F10",
  karlo_core = "#111418",
  ooze_glow = "#182020",
  wet_clay = "#3A2F28",
  toxic_mud = "#4A3F38",
  karlo_brown = "#5A4F48",
  deep_ooze = "#6A5F58",
  corpse_skin = "#D8C8B8",
  stolen_flesh = "#E8D8C8",
  pale_mask = "#F0E8E0",
  hagen_green = "#228844",
  renuyu_toxin = "#33AA66",
  chemical_slime = "#44CC88",
  glowing_ooze = "#66EEAA",
  clayface_red = "#882222",
  oozing_red = "#AA3333",
  term_brown = "#6A5F58",
  term_green = "#44CC88",
  term_red = "#AA3333",
  term_flesh = "#E8D8C8",
  term_brown_bright = "#8A7F78",
  term_green_bright = "#66EEAA",
  term_red_bright = "#CC4444",

  bg_darkest = "#0A0A0C",
  fg_lightest = "#F0E8E0",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.renuyu_toxin,
      insert = plt.stolen_flesh,
      visual = plt.karlo_brown,
      replace = plt.oozing_red,
      command = plt.hagen_green,
    },

    ui = {
      fg = plt.stolen_flesh,
      fg_dim = plt.corpse_skin,
      fg_dimmer = plt.pale_mask,
      fg_dark = plt.toxic_mud,
      fg_reverse = plt.void_black,

      bg_m4 = plt.ooze_glow,
      bg_m3 = plt.karlo_core,
      bg_m2 = plt.clay_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.clay_night,
      bg_p2 = plt.karlo_core,
      bg_gutter = opts.gutter and plt.karlo_core or "none",
      bg_cursorline = plt.karlo_core,
      bg_cursorline_alt = plt.clay_night,
      bg_search = plt.glowing_ooze,
      bg_visual = plt.karlo_brown,
      bg_statusline = plt.karlo_core,

      border = plt.deep_ooze,
      header1 = plt.renuyu_toxin,
      header2 = plt.oozing_red,
      special = plt.hagen_green,
      nontext = plt.clay_night,
      whitespace = plt.ooze_glow,
      win_separator = plt.deep_ooze,
      indent = plt.clay_night,
      indent_scope = plt.toxic_mud,
      picker = plt.stolen_flesh,
      yank = plt.clayface_red,
      mark = plt.oozing_red,
      scrollbar = plt.karlo_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.stolen_flesh,
        bg_selected = plt.karlo_core,
        fg_inactive = plt.pale_mask,
        bg_inactive = plt.void_black,
        fg_alternate = plt.renuyu_toxin,
        bg_alternate = plt.void_black,
        indicator = plt.glowing_ooze,
      },

      pmenu = {
        fg = plt.stolen_flesh,
        fg_sel = "none",
        fg_border = plt.karlo_core,
        bg_border = plt.karlo_core,
        bg = plt.karlo_core,
        bg_sel = plt.clay_night,
        bg_sbar = plt.karlo_core,
        bg_thumb = plt.deep_ooze,
      },

      float = {
        fg = plt.stolen_flesh,
        bg = plt.clay_night,
        fg_border = plt.karlo_core,
        bg_border = plt.clay_night,
      },
    },

    accent = {
      accent1 = plt.renuyu_toxin,
      accent2 = plt.karlo_brown,
      accent3 = plt.oozing_red,
      accent4 = plt.glowing_ooze,
      accent5 = plt.deep_ooze,
      invert = plt.karlo_core,
    },

    rainbow = {
      rainbow1 = plt.hagen_green,
      rainbow2 = plt.renuyu_toxin,
      rainbow3 = plt.chemical_slime,
      rainbow4 = plt.karlo_brown,
      rainbow5 = plt.toxic_mud,
      rainbow6 = plt.oozing_red,
      rainbow7 = plt.clayface_red,
    },

    syn = {
      attribute = plt.stolen_flesh,
      boolean = plt.oozing_red,
      comment = plt.pale_mask,
      constant = plt.glowing_ooze,
      deprecated = plt.ooze_glow,
      func = plt.renuyu_toxin,
      identifier = plt.stolen_flesh,
      keyword = plt.renuyu_toxin,
      method = plt.hagen_green,
      number = plt.clayface_red,
      operator = plt.toxic_mud,
      parameter = plt.corpse_skin,
      preproc = plt.oozing_red,
      punct = plt.stolen_flesh,
      regex = plt.chemical_slime,
      statement = plt.renuyu_toxin,
      string = plt.glowing_ooze,
      symbol = plt.stolen_flesh,
      type = plt.hagen_green,
      variable = plt.stolen_flesh,
      special = plt.clayface_red,
      special2 = plt.chemical_slime,
      special3 = plt.oozing_red,
    },

    vcs = { added = plt.glowing_ooze, removed = plt.oozing_red, changed = plt.toxic_mud },
    diff = { add = plt.glowing_ooze, change = plt.renuyu_toxin, delete = plt.clayface_red, text = plt.karlo_brown },
    diag = {
      ok = plt.glowing_ooze,
      error = plt.clayface_red,
      warning = plt.oozing_red,
      info = plt.renuyu_toxin,
      hint = plt.hagen_green,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_brown,
      blue = plt.term_green,
      magenta = plt.term_red,
      cyan = plt.term_flesh,
      white = plt.term_flesh,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_brown_bright,
      blue_bright = plt.term_green_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_flesh,
      white_bright = "#ffffff",
      indexed1 = plt.renuyu_toxin,
      indexed2 = plt.karlo_brown,
    },

    treesitter = {
      ["@comment"] = plt.pale_mask,
      ["@comment.documentation"] = plt.corpse_skin,
      ["@comment.error"] = plt.clayface_red,
      ["@comment.warning"] = plt.oozing_red,
      ["@comment.todo"] = plt.renuyu_toxin,
      ["@comment.note"] = plt.glowing_ooze,

      ["@constant"] = plt.glowing_ooze,
      ["@constant.builtin"] = plt.chemical_slime,
      ["@constant.macro"] = plt.clayface_red,

      ["@string"] = plt.glowing_ooze,
      ["@string.documentation"] = plt.glowing_ooze,
      ["@string.regex"] = plt.chemical_slime,
      ["@string.escape"] = plt.hagen_green,
      ["@string.special"] = plt.oozing_red,
      ["@string.special.symbol"] = plt.stolen_flesh,
      ["@string.special.url"] = plt.renuyu_toxin,
      ["@string.special.path"] = plt.glowing_ooze,

      ["@character"] = plt.glowing_ooze,
      ["@character.special"] = plt.hagen_green,

      ["@number"] = plt.clayface_red,
      ["@number.float"] = plt.clayface_red,

      ["@boolean"] = plt.oozing_red,

      ["@function"] = plt.renuyu_toxin,
      ["@function.builtin"] = plt.renuyu_toxin,
      ["@function.call"] = plt.renuyu_toxin,
      ["@function.macro"] = plt.hagen_green,
      ["@function.method"] = plt.hagen_green,
      ["@function.method.call"] = plt.hagen_green,

      ["@constructor"] = plt.stolen_flesh,

      ["@parameter"] = plt.corpse_skin,
      ["@parameter.builtin"] = plt.stolen_flesh,

      ["@keyword"] = plt.renuyu_toxin,
      ["@keyword.coroutine"] = plt.oozing_red,
      ["@keyword.function"] = plt.renuyu_toxin,
      ["@keyword.operator"] = plt.toxic_mud,
      ["@keyword.return"] = plt.renuyu_toxin,
      ["@keyword.import"] = plt.glowing_ooze,
      ["@keyword.storage"] = plt.renuyu_toxin,
      ["@keyword.repeat"] = plt.renuyu_toxin,
      ["@keyword.conditional"] = plt.renuyu_toxin,
      ["@keyword.exception"] = plt.clayface_red,
      ["@keyword.directive"] = plt.oozing_red,
      ["@keyword.directive.define"] = plt.oozing_red,

      ["@conditional"] = plt.renuyu_toxin,
      ["@conditional.ternary"] = plt.renuyu_toxin,

      ["@repeat"] = plt.renuyu_toxin,

      ["@label"] = plt.glowing_ooze,

      ["@operator"] = plt.toxic_mud,

      ["@exception"] = plt.clayface_red,

      ["@variable"] = plt.stolen_flesh,
      ["@variable.builtin"] = plt.glowing_ooze,
      ["@variable.parameter"] = plt.corpse_skin,
      ["@variable.member"] = plt.stolen_flesh,

      ["@type"] = plt.hagen_green,
      ["@type.builtin"] = plt.hagen_green,
      ["@type.definition"] = plt.hagen_green,
      ["@type.qualifier"] = plt.renuyu_toxin,

      ["@attribute"] = plt.stolen_flesh,
      ["@attribute.builtin"] = plt.glowing_ooze,

      ["@property"] = plt.stolen_flesh,
      ["@field"] = plt.stolen_flesh,
      ["@module"] = plt.stolen_flesh,
      ["@module.builtin"] = plt.stolen_flesh,
      ["@namespace"] = plt.stolen_flesh,
      ["@namespace.builtin"] = plt.stolen_flesh,

      ["@punctuation.delimiter"] = plt.stolen_flesh,
      ["@punctuation.bracket"] = plt.toxic_mud,
      ["@punctuation.special"] = plt.chemical_slime,

      ["@tag"] = plt.renuyu_toxin,
      ["@tag.attribute"] = plt.glowing_ooze,
      ["@tag.delimiter"] = plt.stolen_flesh,
      ["@tag.builtin"] = plt.renuyu_toxin,

      ["@markup.strong"] = { fg = plt.renuyu_toxin, bold = true },
      ["@markup.italic"] = { fg = plt.stolen_flesh, italic = true },
      ["@markup.strikethrough"] = { fg = plt.ooze_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.oozing_red, underline = true },
      ["@markup.heading"] = plt.renuyu_toxin,
      ["@markup.heading.1"] = plt.renuyu_toxin,
      ["@markup.heading.2"] = plt.hagen_green,
      ["@markup.heading.3"] = plt.chemical_slime,
      ["@markup.heading.4"] = plt.karlo_brown,
      ["@markup.heading.5"] = plt.toxic_mud,
      ["@markup.heading.6"] = plt.deep_ooze,
      ["@markup.quote"] = plt.pale_mask,
      ["@markup.math"] = plt.chemical_slime,
      ["@markup.link"] = plt.glowing_ooze,
      ["@markup.link.label"] = plt.stolen_flesh,
      ["@markup.link.url"] = plt.hagen_green,
      ["@markup.raw"] = plt.glowing_ooze,
      ["@markup.raw.block"] = plt.glowing_ooze,
      ["@markup.list"] = plt.renuyu_toxin,
      ["@markup.list.checked"] = plt.glowing_ooze,
      ["@markup.list.unchecked"] = plt.corpse_skin,

      ["@diff.plus"] = plt.glowing_ooze,
      ["@diff.minus"] = plt.oozing_red,
      ["@diff.delta"] = plt.toxic_mud,

      ["@none"] = "none",
      ["@conceal"] = plt.glowing_ooze,
      ["@spell"] = plt.stolen_flesh,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.stolen_flesh,
      ["@constructor.python"] = plt.renuyu_toxin,
      ["@constructor.javascript"] = plt.renuyu_toxin,
      ["@constructor.typescript"] = plt.renuyu_toxin,
      ["@namespace.rust"] = plt.stolen_flesh,
      ["@type.qualifier.rust"] = plt.renuyu_toxin,
      ["@constant.macro.c"] = plt.clayface_red,
      ["@constant.macro.cpp"] = plt.clayface_red,
      ["@namespace.go"] = plt.stolen_flesh,
      ["@property.css"] = plt.glowing_ooze,
      ["@type.css"] = plt.hagen_green,
      ["@label.json"] = plt.stolen_flesh,
      ["@field.yaml"] = plt.corpse_skin,
      ["@property.toml"] = plt.corpse_skin,
      ["@function.builtin.bash"] = plt.hagen_green,
      ["@string.regexp"] = plt.chemical_slime,
      ["@character.special.regex"] = plt.hagen_green,
    },

    lsp = {
      ["@lsp.type.class"] = plt.hagen_green,
      ["@lsp.type.interface"] = plt.hagen_green,
      ["@lsp.type.struct"] = plt.hagen_green,
      ["@lsp.type.enum"] = plt.hagen_green,
      ["@lsp.type.enumMember"] = plt.glowing_ooze,
      ["@lsp.type.property"] = plt.stolen_flesh,
      ["@lsp.type.namespace"] = plt.stolen_flesh,

      ["@lsp.type.macro"] = plt.clayface_red,
      ["@lsp.type.decorator"] = plt.renuyu_toxin,

      ["@lsp.type.builtinType"] = plt.hagen_green,
      ["@lsp.type.selfParameter"] = plt.renuyu_toxin,
      ["@lsp.type.typeParameter"] = plt.hagen_green,

      ["@lsp.type.array"] = plt.hagen_green,
      ["@lsp.type.object"] = plt.hagen_green,
      ["@lsp.type.key"] = plt.stolen_flesh,
      ["@lsp.type.null"] = plt.glowing_ooze,
      ["@lsp.type.enumConstant"] = plt.glowing_ooze,

      ["@lsp.type.event"] = plt.hagen_green,
      ["@lsp.type.regexp"] = plt.chemical_slime,
      ["@lsp.type.unresolvedReference"] = plt.clayface_red,

      ["@lsp.mod.deprecated"] = { fg = plt.ooze_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.glowing_ooze,
      ["@lsp.mod.async"] = plt.renuyu_toxin,
      ["@lsp.mod.static"] = plt.hagen_green,
      ["@lsp.mod.abstract"] = plt.hagen_green,
      ["@lsp.mod.defaultLibrary"] = plt.hagen_green,
      ["@lsp.mod.documentation"] = plt.pale_mask,
    },
  }
end

return {
  name = "Clayface – Basil Karlo",
  author = "PrismPunk.nvim",
  description = "A living nightmare of wet clay and stolen faces. "
    .. "Toxic green Renuyu, rotting brown mud, corpse-white flesh, "
    .. "and the endless drip of something that was once human. He doesn’t just kill — he becomes you.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.clay_night,
    base02 = palette.karlo_core,
    base03 = palette.ooze_glow,
    base04 = palette.toxic_mud,
    base05 = palette.corpse_skin,
    base06 = palette.stolen_flesh,
    base07 = palette.stolen_flesh,
    base08 = palette.oozing_red,
    base09 = palette.clayface_red,
    base0A = palette.renuyu_toxin,
    base0B = palette.glowing_ooze,
    base0C = palette.hagen_green,
    base0D = palette.chemical_slime,
    base0E = palette.karlo_brown,
    base0F = palette.deep_ooze,
  },

  palette = palette,
  get = M.get,
}
