local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0A0B",
  mourning_night = "#0D0E10",
  tatsu_core = "#111216",
  ash_glow = "#1C1F26",
  soultaker_steel = "#A0B8CC",
  blade_edge = "#C8D8EE",
  ghost_white = "#E8F0FF",
  yamashiro_red = "#CC0022",
  blood_silk = "#EE1144",
  vengeance_red = "#FF3355",
  arterial_red = "#FF5577",
  trapped_jade = "#00CC99",
  spirit_teal = "#22EEBB",
  soul_glow = "#44FFDD",
  widow_black = "#0F1114",
  ash_gray = "#445566",
  cold_steel = "#667788",
  term_red = "#FF3355",
  term_teal = "#44FFDD",
  term_gray = "#667788",
  term_white = "#E8F0FF",
  term_red_bright = "#FF7799",
  term_teal_bright = "#66FFEE",

  bg_darkest = "#0A0A0B",
  fg_lightest = "#E8F0FF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.blood_silk,
      insert = plt.ghost_white,
      visual = plt.vengeance_red,
      replace = plt.arterial_red,
      command = plt.trapped_jade,
    },

    ui = {
      fg = plt.ghost_white,
      fg_dim = plt.blade_edge,
      fg_dimmer = plt.soultaker_steel,
      fg_dark = plt.cold_steel,
      fg_reverse = plt.void_black,

      bg_m4 = plt.ash_glow,
      bg_m3 = plt.tatsu_core,
      bg_m2 = plt.mourning_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.mourning_night,
      bg_p2 = plt.tatsu_core,
      bg_gutter = opts.gutter and plt.tatsu_core or "none",
      bg_cursorline = plt.tatsu_core,
      bg_cursorline_alt = plt.mourning_night,
      bg_search = plt.soul_glow,
      bg_visual = plt.vengeance_red,
      bg_statusline = plt.tatsu_core,

      border = plt.ash_gray,
      header1 = plt.blood_silk,
      header2 = plt.trapped_jade,
      special = plt.yamashiro_red,
      nontext = plt.mourning_night,
      whitespace = plt.ash_glow,
      win_separator = plt.ash_gray,
      indent = plt.mourning_night,
      indent_scope = plt.cold_steel,
      picker = plt.ghost_white,
      yank = plt.arterial_red,
      mark = plt.vengeance_red,
      scrollbar = plt.tatsu_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.ghost_white,
        bg_selected = plt.tatsu_core,
        fg_inactive = plt.soultaker_steel,
        bg_inactive = plt.void_black,
        fg_alternate = plt.blood_silk,
        bg_alternate = plt.void_black,
        indicator = plt.soul_glow,
      },

      pmenu = {
        fg = plt.ghost_white,
        fg_sel = "none",
        fg_border = plt.tatsu_core,
        bg_border = plt.tatsu_core,
        bg = plt.tatsu_core,
        bg_sel = plt.mourning_night,
        bg_sbar = plt.tatsu_core,
        bg_thumb = plt.ash_gray,
      },

      float = {
        fg = plt.ghost_white,
        bg = plt.mourning_night,
        fg_border = plt.tatsu_core,
        bg_border = plt.mourning_night,
      },
    },

    accent = {
      accent1 = plt.blood_silk,
      accent2 = plt.trapped_jade,
      accent3 = plt.soul_glow,
      accent4 = plt.vengeance_red,
      accent5 = plt.soultaker_steel,
      invert = plt.tatsu_core,
    },

    rainbow = {
      rainbow1 = plt.blood_silk,
      rainbow2 = plt.yamashiro_red,
      rainbow3 = plt.vengeance_red,
      rainbow4 = plt.trapped_jade,
      rainbow5 = plt.spirit_teal,
      rainbow6 = plt.soul_glow,
      rainbow7 = plt.soultaker_steel,
    },

    syn = {
      attribute = plt.ghost_white,
      boolean = plt.vengeance_red,
      comment = plt.soultaker_steel,
      constant = plt.soul_glow,
      deprecated = plt.ash_glow,
      func = plt.blood_silk,
      identifier = plt.ghost_white,
      keyword = plt.blood_silk,
      method = plt.trapped_jade,
      number = plt.arterial_red,
      operator = plt.cold_steel,
      parameter = plt.blade_edge,
      preproc = plt.vengeance_red,
      punct = plt.ghost_white,
      regex = plt.soul_glow,
      statement = plt.blood_silk,
      string = plt.soul_glow,
      symbol = plt.ghost_white,
      type = plt.trapped_jade,
      variable = plt.ghost_white,
      special = plt.yamashiro_red,
      special2 = plt.soul_glow,
      special3 = plt.arterial_red,
    },

    vcs = { added = plt.soul_glow, removed = plt.vengeance_red, changed = plt.soultaker_steel },
    diff = { add = plt.soul_glow, change = plt.trapped_jade, delete = plt.arterial_red, text = plt.blood_silk },
    diag = {
      ok = plt.soul_glow,
      error = plt.arterial_red,
      warning = plt.vengeance_red,
      info = plt.blood_silk,
      hint = plt.soultaker_steel,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_teal,
      yellow = plt.term_gray,
      blue = plt.term_teal,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_teal_bright,
      yellow_bright = plt.term_gray,
      blue_bright = plt.term_teal_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.blood_silk,
      indexed2 = plt.trapped_jade,
    },

    treesitter = {
      ["@comment"] = plt.soultaker_steel,
      ["@comment.documentation"] = plt.blade_edge,
      ["@comment.error"] = plt.arterial_red,
      ["@comment.warning"] = plt.vengeance_red,
      ["@comment.todo"] = plt.soul_glow,
      ["@comment.note"] = plt.cold_steel,

      ["@constant"] = plt.soul_glow,
      ["@constant.builtin"] = plt.soul_glow,
      ["@constant.macro"] = plt.arterial_red,

      ["@string"] = plt.soul_glow,
      ["@string.documentation"] = plt.soul_glow,
      ["@string.regex"] = plt.spirit_teal,
      ["@string.escape"] = plt.trapped_jade,
      ["@string.special"] = plt.vengeance_red,
      ["@string.special.symbol"] = plt.ghost_white,
      ["@string.special.url"] = plt.soul_glow,
      ["@string.special.path"] = plt.soul_glow,

      ["@character"] = plt.soul_glow,
      ["@character.special"] = plt.trapped_jade,

      ["@number"] = plt.arterial_red,
      ["@number.float"] = plt.arterial_red,

      ["@boolean"] = plt.vengeance_red,

      ["@function"] = plt.blood_silk,
      ["@function.builtin"] = plt.blood_silk,
      ["@function.call"] = plt.blood_silk,
      ["@function.macro"] = plt.trapped_jade,
      ["@function.method"] = plt.trapped_jade,
      ["@function.method.call"] = plt.trapped_jade,

      ["@constructor"] = plt.ghost_white,

      ["@parameter"] = plt.blade_edge,
      ["@parameter.builtin"] = plt.ghost_white,

      ["@keyword"] = plt.blood_silk,
      ["@keyword.coroutine"] = plt.vengeance_red,
      ["@keyword.function"] = plt.blood_silk,
      ["@keyword.operator"] = plt.cold_steel,
      ["@keyword.return"] = plt.blood_silk,
      ["@keyword.import"] = plt.soul_glow,
      ["@keyword.storage"] = plt.blood_silk,
      ["@keyword.repeat"] = plt.blood_silk,
      ["@keyword.conditional"] = plt.blood_silk,
      ["@keyword.exception"] = plt.arterial_red,
      ["@keyword.directive"] = plt.vengeance_red,
      ["@keyword.directive.define"] = plt.vengeance_red,

      ["@conditional"] = plt.blood_silk,
      ["@conditional.ternary"] = plt.blood_silk,

      ["@repeat"] = plt.blood_silk,

      ["@label"] = plt.soul_glow,

      ["@operator"] = plt.cold_steel,

      ["@exception"] = plt.arterial_red,

      ["@variable"] = plt.ghost_white,
      ["@variable.builtin"] = plt.soul_glow,
      ["@variable.parameter"] = plt.blade_edge,
      ["@variable.member"] = plt.ghost_white,

      ["@type"] = plt.trapped_jade,
      ["@type.builtin"] = plt.trapped_jade,
      ["@type.definition"] = plt.trapped_jade,
      ["@type.qualifier"] = plt.blood_silk,

      ["@attribute"] = plt.ghost_white,
      ["@attribute.builtin"] = plt.soul_glow,

      ["@property"] = plt.ghost_white,
      ["@field"] = plt.ghost_white,
      ["@module"] = plt.ghost_white,
      ["@module.builtin"] = plt.ghost_white,
      ["@namespace"] = plt.ghost_white,
      ["@namespace.builtin"] = plt.ghost_white,

      ["@punctuation.delimiter"] = plt.ghost_white,
      ["@punctuation.bracket"] = plt.cold_steel,
      ["@punctuation.special"] = plt.soul_glow,

      ["@tag"] = plt.blood_silk,
      ["@tag.attribute"] = plt.soul_glow,
      ["@tag.delimiter"] = plt.ghost_white,
      ["@tag.builtin"] = plt.blood_silk,

      ["@markup.strong"] = { fg = plt.blood_silk, bold = true },
      ["@markup.italic"] = { fg = plt.ghost_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.ash_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.vengeance_red, underline = true },
      ["@markup.heading"] = plt.blood_silk,
      ["@markup.heading.1"] = plt.blood_silk,
      ["@markup.heading.2"] = plt.yamashiro_red,
      ["@markup.heading.3"] = plt.vengeance_red,
      ["@markup.heading.4"] = plt.trapped_jade,
      ["@markup.heading.5"] = plt.spirit_teal,
      ["@markup.heading.6"] = plt.soul_glow,
      ["@markup.quote"] = plt.soultaker_steel,
      ["@markup.math"] = plt.cold_steel,
      ["@markup.link"] = plt.soul_glow,
      ["@markup.link.label"] = plt.ghost_white,
      ["@markup.link.url"] = plt.soul_glow,
      ["@markup.raw"] = plt.soul_glow,
      ["@markup.raw.block"] = plt.soul_glow,
      ["@markup.list"] = plt.blood_silk,
      ["@markup.list.checked"] = plt.soul_glow,
      ["@markup.list.unchecked"] = plt.blade_edge,

      ["@diff.plus"] = plt.soul_glow,
      ["@diff.minus"] = plt.vengeance_red,
      ["@diff.delta"] = plt.soultaker_steel,

      ["@none"] = "none",
      ["@conceal"] = plt.soul_glow,
      ["@spell"] = plt.ghost_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.ghost_white,
      ["@constructor.python"] = plt.blood_silk,
      ["@constructor.javascript"] = plt.blood_silk,
      ["@constructor.typescript"] = plt.blood_silk,
      ["@namespace.rust"] = plt.ghost_white,
      ["@type.qualifier.rust"] = plt.blood_silk,
      ["@constant.macro.c"] = plt.arterial_red,
      ["@constant.macro.cpp"] = plt.arterial_red,
      ["@namespace.go"] = plt.ghost_white,
      ["@property.css"] = plt.soul_glow,
      ["@type.css"] = plt.trapped_jade,
      ["@label.json"] = plt.ghost_white,
      ["@field.yaml"] = plt.blade_edge,
      ["@property.toml"] = plt.blade_edge,
      ["@function.builtin.bash"] = plt.trapped_jade,
      ["@string.regexp"] = plt.spirit_teal,
      ["@character.special.regex"] = plt.trapped_jade,
    },

    lsp = {
      ["@lsp.type.class"] = plt.trapped_jade,
      ["@lsp.type.interface"] = plt.trapped_jade,
      ["@lsp.type.struct"] = plt.trapped_jade,
      ["@lsp.type.enum"] = plt.trapped_jade,
      ["@lsp.type.enumMember"] = plt.soul_glow,
      ["@lsp.type.property"] = plt.ghost_white,
      ["@lsp.type.namespace"] = plt.ghost_white,

      ["@lsp.type.macro"] = plt.arterial_red,
      ["@lsp.type.decorator"] = plt.blood_silk,

      ["@lsp.type.builtinType"] = plt.trapped_jade,
      ["@lsp.type.selfParameter"] = plt.blood_silk,
      ["@lsp.type.typeParameter"] = plt.trapped_jade,

      ["@lsp.type.array"] = plt.trapped_jade,
      ["@lsp.type.object"] = plt.trapped_jade,
      ["@lsp.type.key"] = plt.ghost_white,
      ["@lsp.type.null"] = plt.soul_glow,
      ["@lsp.type.enumConstant"] = plt.soul_glow,

      ["@lsp.type.event"] = plt.trapped_jade,
      ["@lsp.type.regexp"] = plt.spirit_teal,
      ["@lsp.type.unresolvedReference"] = plt.arterial_red,

      ["@lsp.mod.deprecated"] = { fg = plt.ash_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.soul_glow,
      ["@lsp.mod.async"] = plt.blood_silk,
      ["@lsp.mod.static"] = plt.trapped_jade,
      ["@lsp.mod.abstract"] = plt.trapped_jade,
      ["@lsp.mod.defaultLibrary"] = plt.trapped_jade,
      ["@lsp.mod.documentation"] = plt.soultaker_steel,
    },
  }
end

return {
  name = "Katana – Tatsu Yamashiro",
  author = "PrismPunk.nvim",
  description = "A widow’s grief forged into steel."
    .. "Crimson silk, mourning black, ghost-white ash, "
    .. "and the cold jade of souls screaming inside the Soultaker blade. "
    .. "Every line of code is a cut. Every cut is eternal.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.mourning_night,
    base02 = palette.tatsu_core,
    base03 = palette.ash_glow,
    base04 = palette.cold_steel,
    base05 = palette.soultaker_steel,
    base06 = palette.ghost_white,
    base07 = palette.ghost_white,
    base08 = palette.vengeance_red,
    base09 = palette.arterial_red,
    base0A = palette.soul_glow,
    base0B = palette.spirit_teal,
    base0C = palette.blood_silk,
    base0D = palette.trapped_jade,
    base0E = palette.yamashiro_red,
    base0F = palette.widow_black,
  },

  palette = palette,
  get = M.get,
}
