local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#080C09",
  greenhouse_night = "#0A110B",
  isley_core = "#0E1710",
  vine_glow = "#182D1E",
  ivy_green = "#00AA44",
  chlorophyll = "#00CC55",
  emerald_vine = "#00EE77",
  spring_leaf = "#44FF99",
  orchid_magenta = "#FF22AA",
  venom_pink = "#FF44CC",
  lethal_petal = "#FF66EE",
  fertile_soil = "#3A2F22",
  root_brown = "#554433",
  bark_brown = "#776644",
  corpse_pale = "#DDEECC",
  greenhouse_white = "#EEFFEE",
  term_green = "#00EE77",
  term_magenta = "#FF66EE",
  term_white = "#EEFFEE",
  term_green_bright = "#66FFAA",
  term_magenta_bright = "#FF88FF",

  bg_darkest = "#080C09",
  fg_lightest = "#EEFFEE",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.chlorophyll,
      insert = plt.greenhouse_white,
      visual = plt.orchid_magenta,
      replace = plt.lethal_petal,
      command = plt.emerald_vine,
    },

    ui = {
      fg = plt.greenhouse_white,
      fg_dim = plt.corpse_pale,
      fg_dimmer = plt.spring_leaf,
      fg_dark = plt.root_brown,
      fg_reverse = plt.void_black,

      bg_m4 = plt.vine_glow,
      bg_m3 = plt.isley_core,
      bg_m2 = plt.greenhouse_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.greenhouse_night,
      bg_p2 = plt.isley_core,
      bg_gutter = opts.gutter and plt.isley_core or "none",
      bg_cursorline = plt.isley_core,
      bg_cursorline_alt = plt.greenhouse_night,
      bg_search = plt.venom_pink,
      bg_visual = plt.orchid_magenta,
      bg_statusline = plt.isley_core,

      border = plt.spring_leaf,
      header1 = plt.chlorophyll,
      header2 = plt.orchid_magenta,
      special = plt.lethal_petal,
      nontext = plt.root_brown,
      whitespace = plt.fertile_soil,
      win_separator = plt.spring_leaf,
      indent = plt.greenhouse_night,
      indent_scope = plt.fertile_soil,
      picker = plt.greenhouse_white,
      yank = plt.lethal_petal,
      mark = plt.venom_pink,
      scrollbar = plt.isley_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.greenhouse_white,
        bg_selected = plt.isley_core,
        fg_inactive = plt.emerald_vine,
        bg_inactive = plt.void_black,
        fg_alternate = plt.chlorophyll,
        bg_alternate = plt.void_black,
        indicator = plt.emerald_vine,
      },

      pmenu = {
        fg = plt.greenhouse_white,
        fg_sel = "none",
        fg_border = plt.isley_core,
        bg_border = plt.isley_core,
        bg = plt.isley_core,
        bg_sel = plt.greenhouse_night,
        bg_sbar = plt.isley_core,
        bg_thumb = plt.spring_leaf,
      },

      float = {
        fg = plt.greenhouse_white,
        bg = plt.greenhouse_night,
        fg_border = plt.spring_leaf,
        bg_border = plt.greenhouse_night,
      },
    },

    accent = {
      accent1 = plt.chlorophyll,
      accent2 = plt.orchid_magenta,
      accent3 = plt.emerald_vine,
      accent4 = plt.lethal_petal,
      accent5 = plt.spring_leaf,
      invert = plt.isley_core,
    },

    rainbow = {
      rainbow1 = plt.ivy_green,
      rainbow2 = plt.chlorophyll,
      rainbow3 = plt.emerald_vine,
      rainbow4 = plt.spring_leaf,
      rainbow5 = plt.orchid_magenta,
      rainbow6 = plt.venom_pink,
      rainbow7 = plt.lethal_petal,
    },

    syn = {
      attribute = plt.greenhouse_white,
      boolean = plt.lethal_petal,
      comment = plt.root_brown,
      constant = plt.spring_leaf,
      deprecated = plt.vine_glow,
      func = plt.chlorophyll,
      identifier = plt.greenhouse_white,
      keyword = plt.chlorophyll,
      method = plt.emerald_vine,
      number = plt.venom_pink,
      operator = plt.root_brown,
      parameter = plt.emerald_vine,
      preproc = plt.lethal_petal,
      punct = plt.greenhouse_white,
      regex = plt.spring_leaf,
      statement = plt.chlorophyll,
      string = plt.emerald_vine,
      symbol = plt.greenhouse_white,
      type = plt.emerald_vine,
      variable = plt.greenhouse_white,
      special = plt.orchid_magenta,
      special2 = plt.spring_leaf,
      special3 = plt.lethal_petal,
    },

    vcs = { added = plt.spring_leaf, removed = plt.orchid_magenta, changed = plt.emerald_vine },
    diff = { add = plt.spring_leaf, change = plt.emerald_vine, delete = plt.lethal_petal, text = plt.chlorophyll },
    diag = {
      ok = plt.spring_leaf,
      error = plt.lethal_petal,
      warning = plt.venom_pink,
      info = plt.chlorophyll,
      hint = plt.emerald_vine,
    },

    term = {
      black = plt.void_black,
      red = plt.term_magenta,
      green = plt.term_green,
      yellow = plt.term_green,
      blue = plt.term_green,
      magenta = plt.term_magenta,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_magenta_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_green_bright,
      blue_bright = plt.term_green_bright,
      magenta_bright = plt.term_magenta_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.chlorophyll,
      indexed2 = plt.emerald_vine,
    },

    treesitter = {
      ["@comment"] = plt.corpse_pale,
      ["@comment.documentation"] = plt.corpse_pale,
      ["@comment.error"] = plt.lethal_petal,
      ["@comment.warning"] = plt.venom_pink,
      ["@comment.todo"] = plt.spring_leaf,
      ["@comment.note"] = plt.emerald_vine,

      ["@constant"] = plt.spring_leaf,
      ["@constant.builtin"] = plt.spring_leaf,
      ["@constant.macro"] = plt.lethal_petal,

      ["@string"] = plt.spring_leaf,
      ["@string.documentation"] = plt.spring_leaf,
      ["@string.regex"] = plt.spring_leaf,
      ["@string.escape"] = plt.emerald_vine,
      ["@string.special"] = plt.orchid_magenta,
      ["@string.special.symbol"] = plt.greenhouse_white,
      ["@string.special.url"] = plt.spring_leaf,
      ["@string.special.path"] = plt.spring_leaf,

      ["@character"] = plt.spring_leaf,
      ["@character.special"] = plt.emerald_vine,

      ["@number"] = plt.venom_pink,
      ["@number.float"] = plt.venom_pink,

      ["@boolean"] = plt.lethal_petal,

      ["@function"] = plt.chlorophyll,
      ["@function.builtin"] = plt.chlorophyll,
      ["@function.call"] = plt.chlorophyll,
      ["@function.macro"] = plt.emerald_vine,
      ["@function.method"] = plt.emerald_vine,
      ["@function.method.call"] = plt.emerald_vine,

      ["@constructor"] = plt.greenhouse_white,

      ["@parameter"] = plt.corpse_pale,
      ["@parameter.builtin"] = plt.greenhouse_white,

      ["@keyword"] = plt.chlorophyll,
      ["@keyword.coroutine"] = plt.lethal_petal,
      ["@keyword.function"] = plt.chlorophyll,
      ["@keyword.operator"] = plt.root_brown,
      ["@keyword.return"] = plt.chlorophyll,
      ["@keyword.import"] = plt.spring_leaf,
      ["@keyword.storage"] = plt.chlorophyll,
      ["@keyword.repeat"] = plt.chlorophyll,
      ["@keyword.conditional"] = plt.chlorophyll,
      ["@keyword.exception"] = plt.lethal_petal,
      ["@keyword.directive"] = plt.venom_pink,
      ["@keyword.directive.define"] = plt.venom_pink,

      ["@conditional"] = plt.chlorophyll,
      ["@conditional.ternary"] = plt.chlorophyll,

      ["@repeat"] = plt.chlorophyll,

      ["@label"] = plt.spring_leaf,

      ["@operator"] = plt.root_brown,

      ["@exception"] = plt.lethal_petal,

      ["@variable"] = plt.greenhouse_white,
      ["@variable.builtin"] = plt.spring_leaf,
      ["@variable.parameter"] = plt.corpse_pale,
      ["@variable.member"] = plt.greenhouse_white,

      ["@type"] = plt.emerald_vine,
      ["@type.builtin"] = plt.emerald_vine,
      ["@type.definition"] = plt.emerald_vine,
      ["@type.qualifier"] = plt.chlorophyll,

      ["@attribute"] = plt.greenhouse_white,
      ["@attribute.builtin"] = plt.spring_leaf,

      ["@property"] = plt.greenhouse_white,
      ["@field"] = plt.greenhouse_white,
      ["@module"] = plt.greenhouse_white,
      ["@module.builtin"] = plt.greenhouse_white,
      ["@namespace"] = plt.greenhouse_white,
      ["@namespace.builtin"] = plt.greenhouse_white,

      ["@punctuation.delimiter"] = plt.greenhouse_white,
      ["@punctuation.bracket"] = plt.root_brown,
      ["@punctuation.special"] = plt.spring_leaf,

      ["@tag"] = plt.chlorophyll,
      ["@tag.attribute"] = plt.spring_leaf,
      ["@tag.delimiter"] = plt.greenhouse_white,
      ["@tag.builtin"] = plt.chlorophyll,

      ["@markup.strong"] = { fg = plt.chlorophyll, bold = true },
      ["@markup.italic"] = { fg = plt.greenhouse_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.vine_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.orchid_magenta, underline = true },
      ["@markup.heading"] = plt.chlorophyll,
      ["@markup.heading.1"] = plt.ivy_green,
      ["@markup.heading.2"] = plt.chlorophyll,
      ["@markup.heading.3"] = plt.emerald_vine,
      ["@markup.heading.4"] = plt.spring_leaf,
      ["@markup.heading.5"] = plt.orchid_magenta,
      ["@markup.heading.6"] = plt.lethal_petal,
      ["@markup.quote"] = plt.corpse_pale,
      ["@markup.math"] = plt.spring_leaf,
      ["@markup.link"] = plt.spring_leaf,
      ["@markup.link.label"] = plt.greenhouse_white,
      ["@markup.link.url"] = plt.emerald_vine,
      ["@markup.raw"] = plt.spring_leaf,
      ["@markup.raw.block"] = plt.spring_leaf,
      ["@markup.list"] = plt.chlorophyll,
      ["@markup.list.checked"] = plt.spring_leaf,
      ["@markup.list.unchecked"] = plt.corpse_pale,

      ["@diff.plus"] = plt.spring_leaf,
      ["@diff.minus"] = plt.orchid_magenta,
      ["@diff.delta"] = plt.emerald_vine,

      ["@none"] = "none",
      ["@conceal"] = plt.spring_leaf,
      ["@spell"] = plt.greenhouse_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.greenhouse_white,
      ["@constructor.python"] = plt.chlorophyll,
      ["@constructor.javascript"] = plt.chlorophyll,
      ["@constructor.typescript"] = plt.chlorophyll,
      ["@namespace.rust"] = plt.greenhouse_white,
      ["@type.qualifier.rust"] = plt.chlorophyll,
      ["@constant.macro.c"] = plt.lethal_petal,
      ["@constant.macro.cpp"] = plt.lethal_petal,
      ["@namespace.go"] = plt.greenhouse_white,
      ["@property.css"] = plt.spring_leaf,
      ["@type.css"] = plt.emerald_vine,
      ["@label.json"] = plt.greenhouse_white,
      ["@field.yaml"] = plt.corpse_pale,
      ["@property.toml"] = plt.corpse_pale,
      ["@function.builtin.bash"] = plt.emerald_vine,
      ["@string.regexp"] = plt.spring_leaf,
      ["@character.special.regex"] = plt.emerald_vine,
    },

    lsp = {
      ["@lsp.type.class"] = plt.emerald_vine,
      ["@lsp.type.interface"] = plt.emerald_vine,
      ["@lsp.type.struct"] = plt.emerald_vine,
      ["@lsp.type.enum"] = plt.emerald_vine,
      ["@lsp.type.enumMember"] = plt.spring_leaf,
      ["@lsp.type.property"] = plt.greenhouse_white,
      ["@lsp.type.namespace"] = plt.greenhouse_white,

      ["@lsp.type.macro"] = plt.lethal_petal,
      ["@lsp.type.decorator"] = plt.chlorophyll,

      ["@lsp.type.builtinType"] = plt.emerald_vine,
      ["@lsp.type.selfParameter"] = plt.chlorophyll,
      ["@lsp.type.typeParameter"] = plt.emerald_vine,

      ["@lsp.type.array"] = plt.emerald_vine,
      ["@lsp.type.object"] = plt.emerald_vine,
      ["@lsp.type.key"] = plt.greenhouse_white,
      ["@lsp.type.null"] = plt.spring_leaf,
      ["@lsp.type.enumConstant"] = plt.spring_leaf,

      ["@lsp.type.event"] = plt.emerald_vine,
      ["@lsp.type.regexp"] = plt.spring_leaf,
      ["@lsp.type.unresolvedReference"] = plt.lethal_petal,

      ["@lsp.mod.deprecated"] = { fg = plt.vine_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.spring_leaf,
      ["@lsp.mod.async"] = plt.chlorophyll,
      ["@lsp.mod.static"] = plt.emerald_vine,
      ["@lsp.mod.abstract"] = plt.emerald_vine,
      ["@lsp.mod.defaultLibrary"] = plt.emerald_vine,
      ["@lsp.mod.documentation"] = plt.corpse_pale,
    },
  }
end

return {
  name = "Poison Ivy – Pamela Isley",
  author = "PrismPunk.nvim",
  description = "She was human once. Now she’s the Green’s vengeance. "
    .. "Chlorophyll blood, toxic magenta flowers, root-brown earth, and the pale skin of corpses feeding her garden. "
    .. "Touch her plants and she’ll make you bloom — from the inside.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.greenhouse_night,
    base02 = palette.isley_core,
    base03 = palette.vine_glow,
    base04 = palette.fertile_soil,
    base05 = palette.corpse_pale,
    base06 = palette.greenhouse_white,
    base07 = palette.greenhouse_white,
    base08 = palette.orchid_magenta,
    base09 = palette.lethal_petal,
    base0A = palette.spring_leaf,
    base0B = palette.emerald_vine,
    base0C = palette.chlorophyll,
    base0D = palette.ivy_green,
    base0E = palette.venom_pink,
    base0F = palette.root_brown,
  },

  palette = palette,
  get = M.get,
}
