local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0908",
  asylum_night = "#0D0C0B",
  crane_core = "#12110F",
  burlap_glow = "#1E1B17",
  scarecrow_brown = "#6B5522",
  burlap_brown = "#887733",
  straw_yellow = "#AA9966",
  toxin_fog = "#CCBB88",
  fear_gas = "#00CC44",
  toxin_green = "#22EE66",
  nightmare_green = "#44FF88",
  terror_purple = "#8800CC",
  hallucination = "#AA22EE",
  mindbreak_purple = "#CC44FF",
  rust_red = "#883322",
  dried_blood = "#AA4433",
  asylum_white = "#E8E8E0",
  term_green = "#22EE66",
  term_purple = "#CC44FF",
  term_brown = "#887733",
  term_white = "#E8E8E0",
  term_green_bright = "#66FFAA",
  term_purple_bright = "#EE66FF",

  bg_darkest = "#0A0908",
  fg_lightest = "#E8E8E0",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.toxin_green,
      insert = plt.asylum_white,
      visual = plt.mindbreak_purple,
      replace = plt.hallucination,
      command = plt.fear_gas,
    },

    ui = {
      fg = plt.asylum_white,
      fg_dim = plt.toxin_fog,
      fg_dimmer = plt.straw_yellow,
      fg_dark = plt.burlap_brown,
      fg_reverse = plt.void_black,

      bg_m4 = plt.burlap_glow,
      bg_m3 = plt.crane_core,
      bg_m2 = plt.asylum_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.asylum_night,
      bg_p2 = plt.crane_core,
      bg_gutter = opts.gutter and plt.crane_core or "none",
      bg_cursorline = plt.crane_core,
      bg_cursorline_alt = plt.asylum_night,
      bg_search = plt.nightmare_green,
      bg_visual = plt.terror_purple,
      bg_statusline = plt.crane_core,

      border = plt.burlap_brown,
      header1 = plt.toxin_green,
      header2 = plt.mindbreak_purple,
      special = plt.dried_blood,
      nontext = plt.asylum_night,
      whitespace = plt.burlap_glow,
      win_separator = plt.scarecrow_brown,
      indent = plt.asylum_night,
      indent_scope = plt.scarecrow_brown,
      picker = plt.asylum_white,
      yank = plt.hallucination,
      mark = plt.terror_purple,
      scrollbar = plt.crane_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.asylum_white,
        bg_selected = plt.crane_core,
        fg_inactive = plt.toxin_fog,
        bg_inactive = plt.void_black,
        fg_alternate = plt.toxin_green,
        bg_alternate = plt.void_black,
        indicator = plt.mindbreak_purple,
      },

      pmenu = {
        fg = plt.asylum_white,
        fg_sel = "none",
        fg_border = plt.crane_core,
        bg_border = plt.crane_core,
        bg = plt.crane_core,
        bg_sel = plt.asylum_night,
        bg_sbar = plt.crane_core,
        bg_thumb = plt.burlap_brown,
      },

      float = {
        fg = plt.asylum_white,
        bg = plt.asylum_night,
        fg_border = plt.crane_core,
        bg_border = plt.asylum_night,
      },
    },

    accent = {
      accent1 = plt.toxin_green,
      accent2 = plt.mindbreak_purple,
      accent3 = plt.nightmare_green,
      accent4 = plt.hallucination,
      accent5 = plt.burlap_brown,
      invert = plt.crane_core,
    },

    rainbow = {
      rainbow1 = plt.toxin_green,
      rainbow2 = plt.fear_gas,
      rainbow3 = plt.nightmare_green,
      rainbow4 = plt.mindbreak_purple,
      rainbow5 = plt.hallucination,
      rainbow6 = plt.terror_purple,
      rainbow7 = plt.burlap_brown,
    },

    syn = {
      attribute = plt.asylum_white,
      boolean = plt.hallucination,
      comment = plt.toxin_fog,
      constant = plt.nightmare_green,
      deprecated = plt.burlap_glow,
      func = plt.toxin_green,
      identifier = plt.asylum_white,
      keyword = plt.toxin_green,
      method = plt.mindbreak_purple,
      number = plt.terror_purple,
      operator = plt.scarecrow_brown,
      parameter = plt.toxin_fog,
      preproc = plt.dried_blood,
      punct = plt.asylum_white,
      regex = plt.nightmare_green,
      statement = plt.toxin_green,
      string = plt.nightmare_green,
      symbol = plt.asylum_white,
      type = plt.mindbreak_purple,
      variable = plt.asylum_white,
      special = plt.rust_red,
      special2 = plt.nightmare_green,
      special3 = plt.hallucination,
    },

    vcs = { added = plt.nightmare_green, removed = plt.terror_purple, changed = plt.burlap_brown },
    diff = {
      add = plt.nightmare_green,
      change = plt.mindbreak_purple,
      delete = plt.dried_blood,
      text = plt.toxin_green,
    },
    diag = {
      ok = plt.nightmare_green,
      error = plt.dried_blood,
      warning = plt.hallucination,
      info = plt.toxin_green,
      hint = plt.mindbreak_purple,
    },

    term = {
      black = plt.void_black,
      red = plt.term_purple,
      green = plt.term_green,
      yellow = plt.term_brown,
      blue = plt.term_green,
      magenta = plt.term_purple,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_purple_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_brown,
      blue_bright = plt.term_green_bright,
      magenta_bright = plt.term_purple_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.toxin_green,
      indexed2 = plt.mindbreak_purple,
    },

    treesitter = {
      ["@comment"] = plt.toxin_fog,
      ["@comment.documentation"] = plt.straw_yellow,
      ["@comment.error"] = plt.dried_blood,
      ["@comment.warning"] = plt.hallucination,
      ["@comment.todo"] = plt.nightmare_green,
      ["@comment.note"] = plt.burlap_brown,

      ["@constant"] = plt.nightmare_green,
      ["@constant.builtin"] = plt.nightmare_green,
      ["@constant.macro"] = plt.dried_blood,

      ["@string"] = plt.nightmare_green,
      ["@string.documentation"] = plt.nightmare_green,
      ["@string.regex"] = plt.nightmare_green,
      ["@string.escape"] = plt.mindbreak_purple,
      ["@string.special"] = plt.terror_purple,
      ["@string.special.symbol"] = plt.asylum_white,
      ["@string.special.url"] = plt.nightmare_green,
      ["@string.special.path"] = plt.nightmare_green,

      ["@character"] = plt.nightmare_green,
      ["@character.special"] = plt.mindbreak_purple,

      ["@number"] = plt.terror_purple,
      ["@number.float"] = plt.terror_purple,

      ["@boolean"] = plt.hallucination,

      ["@function"] = plt.toxin_green,
      ["@function.builtin"] = plt.toxin_green,
      ["@function.call"] = plt.toxin_green,
      ["@function.macro"] = plt.mindbreak_purple,
      ["@function.method"] = plt.mindbreak_purple,
      ["@function.method.call"] = plt.mindbreak_purple,

      ["@constructor"] = plt.asylum_white,

      ["@parameter"] = plt.toxin_fog,
      ["@parameter.builtin"] = plt.asylum_white,

      ["@keyword"] = plt.toxin_green,
      ["@keyword.coroutine"] = plt.dried_blood,
      ["@keyword.function"] = plt.toxin_green,
      ["@keyword.operator"] = plt.scarecrow_brown,
      ["@keyword.return"] = plt.toxin_green,
      ["@keyword.import"] = plt.nightmare_green,
      ["@keyword.storage"] = plt.toxin_green,
      ["@keyword.repeat"] = plt.toxin_green,
      ["@keyword.conditional"] = plt.toxin_green,
      ["@keyword.exception"] = plt.dried_blood,
      ["@keyword.directive"] = plt.hallucination,
      ["@keyword.directive.define"] = plt.hallucination,

      ["@conditional"] = plt.toxin_green,
      ["@conditional.ternary"] = plt.toxin_green,

      ["@repeat"] = plt.toxin_green,

      ["@label"] = plt.nightmare_green,

      ["@operator"] = plt.scarecrow_brown,

      ["@exception"] = plt.dried_blood,

      ["@variable"] = plt.asylum_white,
      ["@variable.builtin"] = plt.nightmare_green,
      ["@variable.parameter"] = plt.toxin_fog,
      ["@variable.member"] = plt.asylum_white,

      ["@type"] = plt.mindbreak_purple,
      ["@type.builtin"] = plt.mindbreak_purple,
      ["@type.definition"] = plt.mindbreak_purple,
      ["@type.qualifier"] = plt.toxin_green,

      ["@attribute"] = plt.asylum_white,
      ["@attribute.builtin"] = plt.nightmare_green,

      ["@property"] = plt.asylum_white,
      ["@field"] = plt.asylum_white,
      ["@module"] = plt.asylum_white,
      ["@module.builtin"] = plt.asylum_white,
      ["@namespace"] = plt.asylum_white,
      ["@namespace.builtin"] = plt.asylum_white,

      ["@punctuation.delimiter"] = plt.asylum_white,
      ["@punctuation.bracket"] = plt.scarecrow_brown,
      ["@punctuation.special"] = plt.nightmare_green,

      ["@tag"] = plt.toxin_green,
      ["@tag.attribute"] = plt.nightmare_green,
      ["@tag.delimiter"] = plt.asylum_white,
      ["@tag.builtin"] = plt.toxin_green,

      ["@markup.strong"] = { fg = plt.toxin_green, bold = true },
      ["@markup.italic"] = { fg = plt.asylum_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.burlap_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.mindbreak_purple, underline = true },
      ["@markup.heading"] = plt.toxin_green,
      ["@markup.heading.1"] = plt.toxin_green,
      ["@markup.heading.2"] = plt.fear_gas,
      ["@markup.heading.3"] = plt.nightmare_green,
      ["@markup.heading.4"] = plt.mindbreak_purple,
      ["@markup.heading.5"] = plt.hallucination,
      ["@markup.heading.6"] = plt.terror_purple,
      ["@markup.quote"] = plt.toxin_fog,
      ["@markup.math"] = plt.nightmare_green,
      ["@markup.link"] = plt.nightmare_green,
      ["@markup.link.label"] = plt.asylum_white,
      ["@markup.link.url"] = plt.mindbreak_purple,
      ["@markup.raw"] = plt.nightmare_green,
      ["@markup.raw.block"] = plt.nightmare_green,
      ["@markup.list"] = plt.toxin_green,
      ["@markup.list.checked"] = plt.nightmare_green,
      ["@markup.list.unchecked"] = plt.toxin_fog,

      ["@diff.plus"] = plt.nightmare_green,
      ["@diff.minus"] = plt.dried_blood,
      ["@diff.delta"] = plt.mindbreak_purple,

      ["@none"] = "none",
      ["@conceal"] = plt.nightmare_green,
      ["@spell"] = plt.asylum_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.asylum_white,
      ["@constructor.python"] = plt.toxin_green,
      ["@constructor.javascript"] = plt.toxin_green,
      ["@constructor.typescript"] = plt.toxin_green,
      ["@namespace.rust"] = plt.asylum_white,
      ["@type.qualifier.rust"] = plt.toxin_green,
      ["@constant.macro.c"] = plt.dried_blood,
      ["@constant.macro.cpp"] = plt.dried_blood,
      ["@namespace.go"] = plt.asylum_white,
      ["@property.css"] = plt.nightmare_green,
      ["@type.css"] = plt.mindbreak_purple,
      ["@label.json"] = plt.asylum_white,
      ["@field.yaml"] = plt.toxin_fog,
      ["@property.toml"] = plt.toxin_fog,
      ["@function.builtin.bash"] = plt.mindbreak_purple,
      ["@string.regexp"] = plt.nightmare_green,
      ["@character.special.regex"] = plt.mindbreak_purple,
    },

    lsp = {
      ["@lsp.type.class"] = plt.mindbreak_purple,
      ["@lsp.type.interface"] = plt.mindbreak_purple,
      ["@lsp.type.struct"] = plt.mindbreak_purple,
      ["@lsp.type.enum"] = plt.mindbreak_purple,
      ["@lsp.type.enumMember"] = plt.nightmare_green,
      ["@lsp.type.property"] = plt.asylum_white,
      ["@lsp.type.namespace"] = plt.asylum_white,

      ["@lsp.type.macro"] = plt.dried_blood,
      ["@lsp.type.decorator"] = plt.toxin_green,

      ["@lsp.type.builtinType"] = plt.mindbreak_purple,
      ["@lsp.type.selfParameter"] = plt.toxin_green,
      ["@lsp.type.typeParameter"] = plt.mindbreak_purple,

      ["@lsp.type.array"] = plt.mindbreak_purple,
      ["@lsp.type.object"] = plt.mindbreak_purple,
      ["@lsp.type.key"] = plt.asylum_white,
      ["@lsp.type.null"] = plt.nightmare_green,
      ["@lsp.type.enumConstant"] = plt.nightmare_green,

      ["@lsp.type.event"] = plt.mindbreak_purple,
      ["@lsp.type.regexp"] = plt.nightmare_green,
      ["@lsp.type.unresolvedReference"] = plt.dried_blood,

      ["@lsp.mod.deprecated"] = { fg = plt.burlap_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.nightmare_green,
      ["@lsp.mod.async"] = plt.toxin_green,
      ["@lsp.mod.static"] = plt.mindbreak_purple,
      ["@lsp.mod.abstract"] = plt.mindbreak_purple,
      ["@lsp.mod.defaultLibrary"] = plt.mindbreak_purple,
      ["@lsp.mod.documentation"] = plt.toxin_fog,
    },
  }
end

return {
  name = "Scarecrow – Jonathan Crane",
  author = "PrismPunk.nvim",
  description = "Breathe in the fear toxin. Burlap brown, toxic green gas, "
    .. "nightmare purple hallucinations, and the rust-red of old blood."
    .. "Every character you type is another scream in the dark. He’s already inside your mind.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.asylum_night,
    base02 = palette.crane_core,
    base03 = palette.burlap_glow,
    base04 = palette.scarecrow_brown,
    base05 = palette.toxin_fog,
    base06 = palette.asylum_white,
    base07 = palette.asylum_white,
    base08 = palette.mindbreak_purple,
    base09 = palette.hallucination,
    base0A = palette.nightmare_green,
    base0B = palette.straw_yellow,
    base0C = palette.toxin_green,
    base0D = palette.fear_gas,
    base0E = palette.dried_blood,
    base0F = palette.burlap_brown,
  },

  palette = palette,
  get = M.get,
}
