local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0809",
  gotham_night = "#0C0A0B",
  falcone_core = "#111013",
  marble_glow = "#1C181C",
  roman_gold = "#AA8800",
  empire_gold = "#CCAA22",
  hangman_gold = "#EECC44",
  crown_gold = "#FFDD66",
  falcone_red = "#AA1122",
  lipstick_red = "#CC2233",
  roman_blood = "#EE3344",
  arterial_red = "#FF5566",
  marble_white = "#F0E8E8",
  silk_gray = "#BBAAAA",
  tombstone_gray = "#887777",
  term_gold = "#EECC44",
  term_red = "#EE3344",
  term_gray = "#BBAAAA",
  term_white = "#F0E8E8",
  term_gold_bright = "#FFDD88",
  term_red_bright = "#FF7799",

  bg_darkest = "#0A0809",
  fg_lightest = "#F0E8E8",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.roman_blood,
      insert = plt.marble_white,
      visual = plt.lipstick_red,
      replace = plt.arterial_red,
      command = plt.hangman_gold,
    },

    ui = {
      fg = plt.marble_white,
      fg_dim = plt.silk_gray,
      fg_dimmer = plt.tombstone_gray,
      fg_dark = plt.tombstone_gray,
      fg_reverse = plt.void_black,

      bg_m4 = plt.marble_glow,
      bg_m3 = plt.falcone_core,
      bg_m2 = plt.gotham_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.gotham_night,
      bg_p2 = plt.falcone_core,
      bg_gutter = opts.gutter and plt.falcone_core or "none",
      bg_cursorline = plt.falcone_core,
      bg_cursorline_alt = plt.gotham_night,
      bg_search = plt.crown_gold,
      bg_visual = plt.lipstick_red,
      bg_statusline = plt.falcone_core,

      border = plt.empire_gold,
      header1 = plt.roman_blood,
      header2 = plt.hangman_gold,
      special = plt.falcone_red,
      nontext = plt.gotham_night,
      whitespace = plt.marble_glow,
      win_separator = plt.silk_gray,
      indent = plt.gotham_night,
      indent_scope = plt.tombstone_gray,
      picker = plt.marble_white,
      yank = plt.arterial_red,
      mark = plt.lipstick_red,
      scrollbar = plt.falcone_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.marble_white,
        bg_selected = plt.falcone_core,
        fg_inactive = plt.silk_gray,
        bg_inactive = plt.void_black,
        fg_alternate = plt.roman_blood,
        bg_alternate = plt.void_black,
        indicator = plt.hangman_gold,
      },

      pmenu = {
        fg = plt.marble_white,
        fg_sel = "none",
        fg_border = plt.falcone_core,
        bg_border = plt.falcone_core,
        bg = plt.falcone_core,
        bg_sel = plt.gotham_night,
        bg_sbar = plt.falcone_core,
        bg_thumb = plt.empire_gold,
      },

      float = {
        fg = plt.marble_white,
        bg = plt.gotham_night,
        fg_border = plt.falcone_core,
        bg_border = plt.gotham_night,
      },
    },

    accent = {
      accent1 = plt.roman_blood,
      accent2 = plt.hangman_gold,
      accent3 = plt.lipstick_red,
      accent4 = plt.arterial_red,
      accent5 = plt.empire_gold,
      invert = plt.falcone_core,
    },

    rainbow = {
      rainbow1 = plt.roman_blood,
      rainbow2 = plt.lipstick_red,
      rainbow3 = plt.arterial_red,
      rainbow4 = plt.roman_gold,
      rainbow5 = plt.empire_gold,
      rainbow6 = plt.hangman_gold,
      rainbow7 = plt.crown_gold,
    },

    syn = {
      attribute = plt.marble_white,
      boolean = plt.arterial_red,
      comment = plt.silk_gray,
      constant = plt.crown_gold,
      deprecated = plt.marble_glow,
      func = plt.roman_blood,
      identifier = plt.marble_white,
      keyword = plt.roman_blood,
      method = plt.hangman_gold,
      number = plt.lipstick_red,
      operator = plt.tombstone_gray,
      parameter = plt.silk_gray,
      preproc = plt.falcone_red,
      punct = plt.marble_white,
      regex = plt.crown_gold,
      statement = plt.roman_blood,
      string = plt.crown_gold,
      symbol = plt.marble_white,
      type = plt.hangman_gold,
      variable = plt.marble_white,
      special = plt.falcone_red,
      special2 = plt.crown_gold,
      special3 = plt.arterial_red,
    },

    vcs = { added = plt.crown_gold, removed = plt.arterial_red, changed = plt.empire_gold },
    diff = { add = plt.crown_gold, change = plt.hangman_gold, delete = plt.roman_blood, text = plt.lipstick_red },
    diag = {
      ok = plt.crown_gold,
      error = plt.arterial_red,
      warning = plt.lipstick_red,
      info = plt.roman_blood,
      hint = plt.hangman_gold,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_gold,
      yellow = plt.term_gold,
      blue = plt.term_gold,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_gold_bright,
      yellow_bright = plt.term_gold_bright,
      blue_bright = plt.term_gold_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.roman_blood,
      indexed2 = plt.hangman_gold,
    },

    treesitter = {
      ["@comment"] = plt.silk_gray,
      ["@comment.documentation"] = plt.silk_gray,
      ["@comment.error"] = plt.arterial_red,
      ["@comment.warning"] = plt.lipstick_red,
      ["@comment.todo"] = plt.crown_gold,
      ["@comment.note"] = plt.empire_gold,

      ["@constant"] = plt.crown_gold,
      ["@constant.builtin"] = plt.crown_gold,
      ["@constant.macro"] = plt.arterial_red,

      ["@string"] = plt.crown_gold,
      ["@string.documentation"] = plt.crown_gold,
      ["@string.regex"] = plt.crown_gold,
      ["@string.escape"] = plt.hangman_gold,
      ["@string.special"] = plt.roman_blood,
      ["@string.special.symbol"] = plt.marble_white,
      ["@string.special.url"] = plt.crown_gold,
      ["@string.special.path"] = plt.crown_gold,

      ["@character"] = plt.crown_gold,
      ["@character.special"] = plt.hangman_gold,

      ["@number"] = plt.lipstick_red,
      ["@number.float"] = plt.lipstick_red,

      ["@boolean"] = plt.arterial_red,

      ["@function"] = plt.roman_blood,
      ["@function.builtin"] = plt.roman_blood,
      ["@function.call"] = plt.roman_blood,
      ["@function.macro"] = plt.hangman_gold,
      ["@function.method"] = plt.hangman_gold,
      ["@function.method.call"] = plt.hangman_gold,

      ["@constructor"] = plt.marble_white,

      ["@parameter"] = plt.silk_gray,
      ["@parameter.builtin"] = plt.marble_white,

      ["@keyword"] = plt.roman_blood,
      ["@keyword.coroutine"] = plt.arterial_red,
      ["@keyword.function"] = plt.roman_blood,
      ["@keyword.operator"] = plt.tombstone_gray,
      ["@keyword.return"] = plt.roman_blood,
      ["@keyword.import"] = plt.crown_gold,
      ["@keyword.storage"] = plt.roman_blood,
      ["@keyword.repeat"] = plt.roman_blood,
      ["@keyword.conditional"] = plt.roman_blood,
      ["@keyword.exception"] = plt.arterial_red,
      ["@keyword.directive"] = plt.lipstick_red,
      ["@keyword.directive.define"] = plt.lipstick_red,

      ["@conditional"] = plt.roman_blood,
      ["@conditional.ternary"] = plt.roman_blood,

      ["@repeat"] = plt.roman_blood,

      ["@label"] = plt.crown_gold,

      ["@operator"] = plt.tombstone_gray,

      ["@exception"] = plt.arterial_red,

      ["@variable"] = plt.marble_white,
      ["@variable.builtin"] = plt.crown_gold,
      ["@variable.parameter"] = plt.silk_gray,
      ["@variable.member"] = plt.marble_white,

      ["@type"] = plt.hangman_gold,
      ["@type.builtin"] = plt.hangman_gold,
      ["@type.definition"] = plt.hangman_gold,
      ["@type.qualifier"] = plt.roman_blood,

      ["@attribute"] = plt.marble_white,
      ["@attribute.builtin"] = plt.crown_gold,

      ["@property"] = plt.marble_white,
      ["@field"] = plt.marble_white,
      ["@module"] = plt.marble_white,
      ["@module.builtin"] = plt.marble_white,
      ["@namespace"] = plt.marble_white,
      ["@namespace.builtin"] = plt.marble_white,

      ["@punctuation.delimiter"] = plt.marble_white,
      ["@punctuation.bracket"] = plt.tombstone_gray,
      ["@punctuation.special"] = plt.crown_gold,

      ["@tag"] = plt.roman_blood,
      ["@tag.attribute"] = plt.crown_gold,
      ["@tag.delimiter"] = plt.marble_white,
      ["@tag.builtin"] = plt.roman_blood,

      ["@markup.strong"] = { fg = plt.roman_blood, bold = true },
      ["@markup.italic"] = { fg = plt.marble_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.marble_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.lipstick_red, underline = true },
      ["@markup.heading"] = plt.roman_blood,
      ["@markup.heading.1"] = plt.roman_blood,
      ["@markup.heading.2"] = plt.lipstick_red,
      ["@markup.heading.3"] = plt.arterial_red,
      ["@markup.heading.4"] = plt.roman_gold,
      ["@markup.heading.5"] = plt.empire_gold,
      ["@markup.heading.6"] = plt.hangman_gold,
      ["@markup.quote"] = plt.silk_gray,
      ["@markup.math"] = plt.crown_gold,
      ["@markup.link"] = plt.crown_gold,
      ["@markup.link.label"] = plt.marble_white,
      ["@markup.link.url"] = plt.hangman_gold,
      ["@markup.raw"] = plt.crown_gold,
      ["@markup.raw.block"] = plt.crown_gold,
      ["@markup.list"] = plt.roman_blood,
      ["@markup.list.checked"] = plt.crown_gold,
      ["@markup.list.unchecked"] = plt.silk_gray,

      ["@diff.plus"] = plt.crown_gold,
      ["@diff.minus"] = plt.arterial_red,
      ["@diff.delta"] = plt.hangman_gold,

      ["@none"] = "none",
      ["@conceal"] = plt.crown_gold,
      ["@spell"] = plt.marble_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.marble_white,
      ["@constructor.python"] = plt.roman_blood,
      ["@constructor.javascript"] = plt.roman_blood,
      ["@constructor.typescript"] = plt.roman_blood,
      ["@namespace.rust"] = plt.marble_white,
      ["@type.qualifier.rust"] = plt.roman_blood,
      ["@constant.macro.c"] = plt.arterial_red,
      ["@constant.macro.cpp"] = plt.arterial_red,
      ["@namespace.go"] = plt.marble_white,
      ["@property.css"] = plt.crown_gold,
      ["@type.css"] = plt.hangman_gold,
      ["@label.json"] = plt.marble_white,
      ["@field.yaml"] = plt.silk_gray,
      ["@property.toml"] = plt.silk_gray,
      ["@function.builtin.bash"] = plt.hangman_gold,
      ["@string.regexp"] = plt.crown_gold,
      ["@character.special.regex"] = plt.hangman_gold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.hangman_gold,
      ["@lsp.type.interface"] = plt.hangman_gold,
      ["@lsp.type.struct"] = plt.hangman_gold,
      ["@lsp.type.enum"] = plt.hangman_gold,
      ["@lsp.type.enumMember"] = plt.crown_gold,
      ["@lsp.type.property"] = plt.marble_white,
      ["@lsp.type.namespace"] = plt.marble_white,

      ["@lsp.type.macro"] = plt.arterial_red,
      ["@lsp.type.decorator"] = plt.roman_blood,

      ["@lsp.type.builtinType"] = plt.hangman_gold,
      ["@lsp.type.selfParameter"] = plt.roman_blood,
      ["@lsp.type.typeParameter"] = plt.hangman_gold,

      ["@lsp.type.array"] = plt.hangman_gold,
      ["@lsp.type.object"] = plt.hangman_gold,
      ["@lsp.type.key"] = plt.marble_white,
      ["@lsp.type.null"] = plt.crown_gold,
      ["@lsp.type.enumConstant"] = plt.crown_gold,

      ["@lsp.type.event"] = plt.hangman_gold,
      ["@lsp.type.regexp"] = plt.crown_gold,
      ["@lsp.type.unresolvedReference"] = plt.arterial_red,

      ["@lsp.mod.deprecated"] = { fg = plt.marble_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.crown_gold,
      ["@lsp.mod.async"] = plt.roman_blood,
      ["@lsp.mod.static"] = plt.hangman_gold,
      ["@lsp.mod.abstract"] = plt.hangman_gold,
      ["@lsp.mod.defaultLibrary"] = plt.hangman_gold,
      ["@lsp.mod.documentation"] = plt.silk_gray,
    },
  }
end

return {
  name = "Sofia Falcone – The Hangman",
  author = "PrismPunk.nvim",
  description = "Daughter of Carmine Falcone. Heir to an empire built on corpses. "
    .. "Black silk suits, blood-red manicured nails, and Roman gold that still drips with yesterday’s betrayals. "
    .. "She doesn’t ask twice. She hangs you once — and makes the whole city watch.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.gotham_night,
    base02 = palette.falcone_core,
    base03 = palette.marble_glow,
    base04 = palette.tombstone_gray,
    base05 = palette.silk_gray,
    base06 = palette.marble_white,
    base07 = palette.marble_white,
    base08 = palette.roman_blood,
    base09 = palette.lipstick_red,
    base0A = palette.crown_gold,
    base0B = palette.hangman_gold,
    base0C = palette.empire_gold,
    base0D = palette.roman_gold,
    base0E = palette.arterial_red,
    base0F = palette.falcone_red,
  },

  palette = palette,
  get = M.get,
}
