local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#08090A",
  asylum_void = "#0A0C0D",
  bayard_core = "#0D1012",
  sterile_glow = "#182028",
  knight_white = "#F0F8FF",
  surgical_white = "#E8F0FF",
  bleached_bone = "#DDE8FF",
  sterile_teal = "#00CCCC",
  medical_cyan = "#00EEFF",
  cold_sterile = "#44FFFF",
  scalpel_blue = "#4477AA",
  operating_room = "#5588CC",
  frost_steel = "#66AAFF",
  purge_red = "#CC2222",
  martyr_blood = "#EE4444",
  term_cyan = "#00EEFF",
  term_blue = "#66AAFF",
  term_red = "#EE4444",
  term_white = "#F0F8FF",
  term_cyan_bright = "#66FFFF",
  term_blue_bright = "#88CCFF",

  bg_darkest = "#08090A",
  fg_lightest = "#F0F8FF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.medical_cyan,
      insert = plt.knight_white,
      visual = plt.cold_sterile,
      replace = plt.bleached_bone,
      command = plt.scalpel_blue,
    },

    ui = {
      fg = plt.knight_white,
      fg_dim = plt.bleached_bone,
      fg_dimmer = plt.surgical_white,
      fg_dark = plt.frost_steel,
      fg_reverse = plt.void_black,

      bg_m4 = plt.sterile_glow,
      bg_m3 = plt.bayard_core,
      bg_m2 = plt.asylum_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.asylum_void,
      bg_p2 = plt.bayard_core,
      bg_gutter = opts.gutter and plt.bayard_core or "none",
      bg_cursorline = plt.bayard_core,
      bg_cursorline_alt = plt.asylum_void,
      bg_search = plt.cold_sterile,
      bg_visual = plt.medical_cyan,
      bg_statusline = plt.bayard_core,

      border = plt.operating_room,
      header1 = plt.medical_cyan,
      header2 = plt.scalpel_blue,
      special = plt.purge_red,
      nontext = plt.asylum_void,
      whitespace = plt.sterile_glow,
      win_separator = plt.scalpel_blue,
      indent = plt.asylum_void,
      indent_scope = plt.frost_steel,
      picker = plt.knight_white,
      yank = plt.cold_sterile,
      mark = plt.martyr_blood,
      scrollbar = plt.bayard_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.knight_white,
        bg_selected = plt.bayard_core,
        fg_inactive = plt.bleached_bone,
        bg_inactive = plt.void_black,
        fg_alternate = plt.medical_cyan,
        bg_alternate = plt.void_black,
        indicator = plt.cold_sterile,
      },

      pmenu = {
        fg = plt.knight_white,
        fg_sel = "none",
        fg_border = plt.bayard_core,
        bg_border = plt.bayard_core,
        bg = plt.bayard_core,
        bg_sel = plt.asylum_void,
        bg_sbar = plt.bayard_core,
        bg_thumb = plt.operating_room,
      },

      float = {
        fg = plt.knight_white,
        bg = plt.asylum_void,
        fg_border = plt.bayard_core,
        bg_border = plt.asylum_void,
      },
    },

    accent = {
      accent1 = plt.medical_cyan,
      accent2 = plt.scalpel_blue,
      accent3 = plt.cold_sterile,
      accent4 = plt.bleached_bone,
      accent5 = plt.sterile_teal,
      invert = plt.bayard_core,
    },

    rainbow = {
      rainbow1 = plt.sterile_teal,
      rainbow2 = plt.medical_cyan,
      rainbow3 = plt.cold_sterile,
      rainbow4 = plt.bleached_bone,
      rainbow5 = plt.scalpel_blue,
      rainbow6 = plt.operating_room,
      rainbow7 = plt.frost_steel,
    },

    syn = {
      attribute = plt.knight_white,
      boolean = plt.martyr_blood,
      comment = plt.bleached_bone,
      constant = plt.cold_sterile,
      deprecated = plt.sterile_glow,
      func = plt.medical_cyan,
      identifier = plt.knight_white,
      keyword = plt.medical_cyan,
      method = plt.scalpel_blue,
      number = plt.cold_sterile,
      operator = plt.frost_steel,
      parameter = plt.bleached_bone,
      preproc = plt.purge_red,
      punct = plt.knight_white,
      regex = plt.cold_sterile,
      statement = plt.medical_cyan,
      string = plt.cold_sterile,
      symbol = plt.knight_white,
      type = plt.scalpel_blue,
      variable = plt.knight_white,
      special = plt.purge_red,
      special2 = plt.cold_sterile,
      special3 = plt.martyr_blood,
    },

    vcs = { added = plt.cold_sterile, removed = plt.martyr_blood, changed = plt.scalpel_blue },
    diff = { add = plt.cold_sterile, change = plt.operating_room, delete = plt.purge_red, text = plt.medical_cyan },
    diag = {
      ok = plt.cold_sterile,
      error = plt.martyr_blood,
      warning = plt.purge_red,
      info = plt.medical_cyan,
      hint = plt.scalpel_blue,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_cyan,
      yellow = plt.term_cyan,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_cyan,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red,
      green_bright = plt.term_cyan_bright,
      yellow_bright = plt.term_cyan_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.medical_cyan,
      indexed2 = plt.scalpel_blue,
    },

    treesitter = {
      ["@comment"] = plt.bleached_bone,
      ["@comment.documentation"] = plt.bleached_bone,
      ["@comment.error"] = plt.martyr_blood,
      ["@comment.warning"] = plt.purge_red,
      ["@comment.todo"] = plt.cold_sterile,
      ["@comment.note"] = plt.operating_room,

      ["@constant"] = plt.cold_sterile,
      ["@constant.builtin"] = plt.cold_sterile,
      ["@constant.macro"] = plt.martyr_blood,

      ["@string"] = plt.cold_sterile,
      ["@string.documentation"] = plt.cold_sterile,
      ["@string.regex"] = plt.cold_sterile,
      ["@string.escape"] = plt.scalpel_blue,
      ["@string.special"] = plt.purge_red,
      ["@string.special.symbol"] = plt.knight_white,
      ["@string.special.url"] = plt.cold_sterile,
      ["@string.special.path"] = plt.cold_sterile,

      ["@character"] = plt.cold_sterile,
      ["@character.special"] = plt.scalpel_blue,

      ["@number"] = plt.cold_sterile,
      ["@number.float"] = plt.cold_sterile,

      ["@boolean"] = plt.martyr_blood,

      ["@function"] = plt.medical_cyan,
      ["@function.builtin"] = plt.medical_cyan,
      ["@function.call"] = plt.medical_cyan,
      ["@function.macro"] = plt.scalpel_blue,
      ["@function.method"] = plt.scalpel_blue,
      ["@function.method.call"] = plt.scalpel_blue,

      ["@constructor"] = plt.knight_white,

      ["@parameter"] = plt.bleached_bone,
      ["@parameter.builtin"] = plt.knight_white,

      ["@keyword"] = plt.medical_cyan,
      ["@keyword.coroutine"] = plt.martyr_blood,
      ["@keyword.function"] = plt.medical_cyan,
      ["@keyword.operator"] = plt.frost_steel,
      ["@keyword.return"] = plt.medical_cyan,
      ["@keyword.import"] = plt.cold_sterile,
      ["@keyword.storage"] = plt.medical_cyan,
      ["@keyword.repeat"] = plt.medical_cyan,
      ["@keyword.conditional"] = plt.medical_cyan,
      ["@keyword.exception"] = plt.martyr_blood,
      ["@keyword.directive"] = plt.purge_red,

      ["@conditional"] = plt.medical_cyan,
      ["@conditional.ternary"] = plt.medical_cyan,

      ["@repeat"] = plt.medical_cyan,

      ["@label"] = plt.cold_sterile,

      ["@operator"] = plt.frost_steel,

      ["@exception"] = plt.martyr_blood,

      ["@variable"] = plt.knight_white,
      ["@variable.builtin"] = plt.cold_sterile,
      ["@variable.parameter"] = plt.bleached_bone,
      ["@variable.member"] = plt.knight_white,

      ["@type"] = plt.scalpel_blue,
      ["@type.builtin"] = plt.scalpel_blue,
      ["@type.definition"] = plt.scalpel_blue,
      ["@type.qualifier"] = plt.medical_cyan,

      ["@attribute"] = plt.knight_white,
      ["@attribute.builtin"] = plt.cold_sterile,

      ["@property"] = plt.knight_white,
      ["@field"] = plt.knight_white,
      ["@module"] = plt.knight_white,
      ["@module.builtin"] = plt.knight_white,
      ["@namespace"] = plt.knight_white,
      ["@namespace.builtin"] = plt.knight_white,

      ["@punctuation.delimiter"] = plt.knight_white,
      ["@punctuation.bracket"] = plt.frost_steel,
      ["@punctuation.special"] = plt.cold_sterile,

      ["@tag"] = plt.medical_cyan,
      ["@tag.attribute"] = plt.cold_sterile,
      ["@tag.delimiter"] = plt.knight_white,
      ["@tag.builtin"] = plt.medical_cyan,

      ["@markup.strong"] = { fg = plt.medical_cyan, bold = true },
      ["@markup.italic"] = { fg = plt.knight_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.sterile_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cold_sterile, underline = true },
      ["@markup.heading"] = plt.medical_cyan,
      ["@markup.heading.1"] = plt.medical_cyan,
      ["@markup.heading.2"] = plt.cold_sterile,
      ["@markup.heading.3"] = plt.bleached_bone,
      ["@markup.heading.4"] = plt.scalpel_blue,
      ["@markup.heading.5"] = plt.operating_room,
      ["@markup.heading.6"] = plt.frost_steel,
      ["@markup.quote"] = plt.bleached_bone,
      ["@markup.math"] = plt.cold_sterile,
      ["@markup.link"] = plt.cold_sterile,
      ["@markup.link.label"] = plt.knight_white,
      ["@markup.link.url"] = plt.scalpel_blue,
      ["@markup.raw"] = plt.cold_sterile,
      ["@markup.raw.block"] = plt.cold_sterile,
      ["@markup.list"] = plt.medical_cyan,
      ["@markup.list.checked"] = plt.cold_sterile,
      ["@markup.list.unchecked"] = plt.bleached_bone,

      ["@diff.plus"] = plt.cold_sterile,
      ["@diff.minus"] = plt.martyr_blood,
      ["@diff.delta"] = plt.scalpel_blue,

      ["@none"] = "none",
      ["@conceal"] = plt.cold_sterile,
      ["@spell"] = plt.knight_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.knight_white,
      ["@constructor.python"] = plt.medical_cyan,
      ["@constructor.javascript"] = plt.medical_cyan,
      ["@constructor.typescript"] = plt.medical_cyan,
      ["@namespace.rust"] = plt.knight_white,
      ["@type.qualifier.rust"] = plt.medical_cyan,
      ["@constant.macro.c"] = plt.martyr_blood,
      ["@constant.macro.cpp"] = plt.martyr_blood,
      ["@namespace.go"] = plt.knight_white,
      ["@property.css"] = plt.cold_sterile,
      ["@type.css"] = plt.scalpel_blue,
      ["@label.json"] = plt.knight_white,
      ["@field.yaml"] = plt.bleached_bone,
      ["@property.toml"] = plt.bleached_bone,
      ["@function.builtin.bash"] = plt.scalpel_blue,
      ["@string.regexp"] = plt.cold_sterile,
      ["@character.special.regex"] = plt.scalpel_blue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.scalpel_blue,
      ["@lsp.type.interface"] = plt.scalpel_blue,
      ["@lsp.type.struct"] = plt.scalpel_blue,
      ["@lsp.type.enum"] = plt.scalpel_blue,
      ["@lsp.type.enumMember"] = plt.cold_sterile,
      ["@lsp.type.property"] = plt.knight_white,
      ["@lsp.type.namespace"] = plt.knight_white,

      ["@lsp.type.macro"] = plt.martyr_blood,
      ["@lsp.type.decorator"] = plt.medical_cyan,

      ["@lsp.type.builtinType"] = plt.scalpel_blue,
      ["@lsp.type.selfParameter"] = plt.medical_cyan,
      ["@lsp.type.typeParameter"] = plt.scalpel_blue,

      ["@lsp.type.array"] = plt.scalpel_blue,
      ["@lsp.type.object"] = plt.scalpel_blue,
      ["@lsp.type.key"] = plt.knight_white,
      ["@lsp.type.null"] = plt.cold_sterile,
      ["@lsp.type.enumConstant"] = plt.cold_sterile,

      ["@lsp.type.event"] = plt.scalpel_blue,
      ["@lsp.type.regexp"] = plt.cold_sterile,
      ["@lsp.type.unresolvedReference"] = plt.martyr_blood,

      ["@lsp.mod.deprecated"] = { fg = plt.sterile_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.cold_sterile,
      ["@lsp.mod.async"] = plt.medical_cyan,
      ["@lsp.mod.static"] = plt.scalpel_blue,
      ["@lsp.mod.abstract"] = plt.scalpel_blue,
      ["@lsp.mod.defaultLibrary"] = plt.scalpel_blue,
      ["@lsp.mod.documentation"] = plt.bleached_bone,
    },
  }
end

return {
  name = "White Knight – Lewis Bayard",
  author = "PrismPunk.nvim",
  description = "He wears sterile white armor and wields a scalpel made of faith. "
    .. "Antiseptic teal light, surgical steel blue, and the cold crimson of righteous amputation. Gotham is sick. "
    .. "He is the cure — whether it wants to be or not.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.asylum_void,
    base02 = palette.bayard_core,
    base03 = palette.sterile_glow,
    base04 = palette.frost_steel,
    base05 = palette.bleached_bone,
    base06 = palette.knight_white,
    base07 = palette.knight_white,
    base08 = palette.medical_cyan,
    base09 = palette.cold_sterile,
    base0A = palette.bleached_bone,
    base0B = palette.sterile_teal,
    base0C = palette.scalpel_blue,
    base0D = palette.operating_room,
    base0E = palette.purge_red,
    base0F = palette.martyr_blood,
  },

  palette = palette,
  get = M.get,
}
