local color = require("prismpunk.utils.color")

local palette = {
  scrollWhite = "#F4F0E8",
  scrollPale = "#E0DAC8",
  scrollLight = "#C8C0A8",
  scrollMid = "#A09880",
  scrollDark = "#787060",
  scrollDeep = "#504840",
  scrollInk = "#303028",
  scrollGround = "#181810",
  sumiBlack = "#080808",
  sumiDeep = "#181818",
  sumiMid = "#303030",
  sumiChar = "#484848",
  indigoDeep = "#184870",
  indigoBright = "#305890",
  sealDeep = "#C83830",
  sealBright = "#E05848",
  bg_darkest = "#F4F0E8",
  fg_lightest = "#080808",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.sumiBlack,
      insert = plt.sumiDeep,
      visual = plt.indigoDeep,
      replace = plt.sealBright,
      command = plt.sumiMid,
    },
    accent = {
      accent1 = plt.indigoDeep,
      accent2 = plt.indigoBright,
      accent3 = plt.sealDeep,
      accent4 = plt.sumiMid,
      accent5 = plt.sumiBlack,
      invert = plt.scrollWhite,
    },
    rainbow = {
      rainbow1 = plt.sealBright,
      rainbow2 = plt.sealDeep,
      rainbow3 = plt.indigoBright,
      rainbow4 = plt.indigoDeep,
      rainbow5 = plt.sumiMid,
      rainbow6 = plt.sumiChar,
      rainbow7 = plt.scrollDark,
    },
    ui = {
      fg = plt.sumiBlack,
      fg_dim = plt.sumiDeep,
      fg_dimmer = plt.sumiMid,
      fg_dark = plt.sumiChar,
      fg_reverse = plt.scrollWhite,
      bg = plt.scrollWhite,
      bg_dim = plt.scrollWhite,
      bg_m1 = plt.scrollPale,
      bg_m2 = plt.scrollLight,
      bg_m3 = plt.scrollMid,
      bg_m4 = plt.scrollDark,
      bg_p1 = plt.scrollPale,
      bg_p2 = plt.scrollLight,
      bg_gutter = (opts.gutter ~= false) and plt.scrollPale or "none",
      bg_cursorline = plt.scrollPale,
      bg_cursorline_alt = plt.scrollLight,
      cursorline = plt.scrollPale,
      bg_highlight = plt.scrollLight,
      bg_search = plt.indigoBright,
      bg_visual = plt.scrollLight,
      bg_statusline = plt.scrollPale,
      border = plt.scrollMid,
      header1 = plt.sumiBlack,
      header2 = plt.indigoDeep,
      special = plt.indigoDeep,
      nontext = plt.scrollMid,
      whitespace = plt.scrollDark,
      win_separator = plt.scrollDark,
      indent = plt.scrollPale,
      indent_scope = plt.indigoDeep,
      picker = plt.indigoBright,
      yank = plt.sealBright,
      mark = plt.indigoDeep,
      scrollbar = plt.scrollLight,
      selection = plt.scrollLight,
      line_nr = plt.scrollDark,
      line_nr_dim = plt.scrollMid,
      line_nr_active = plt.sumiBlack,
      float = {
        fg = plt.sumiDeep,
        bg = plt.scrollPale,
        fg_border = plt.scrollDark,
        bg_border = plt.scrollPale,
      },
      pmenu = {
        fg = plt.sumiDeep,
        fg_sel = plt.sumiBlack,
        fg_border = plt.scrollDark,
        bg = plt.scrollPale,
        bg_sel = plt.scrollLight,
        bg_border = plt.scrollPale,
        bg_sbar = plt.scrollPale,
        bg_thumb = plt.scrollDark,
      },
      tabline = {
        bg = plt.scrollWhite,
        bg_inactive = plt.scrollWhite,
        bg_selected = plt.scrollPale,
        bg_alternate = plt.scrollPale,
        fg_inactive = plt.scrollDark,
        fg_selected = plt.sumiBlack,
        fg_alternate = plt.indigoDeep,
        indicator = plt.sealBright,
      },
    },
    syn = {
      attribute = plt.sumiMid,
      boolean = plt.sealDeep,
      comment = plt.scrollDark,
      constant = plt.sumiDeep,
      deprecated = plt.scrollDark,
      func = plt.sumiBlack,
      identifier = plt.sumiDeep,
      keyword = plt.indigoDeep,
      method = plt.sumiBlack,
      number = plt.indigoDeep,
      operator = plt.sumiChar,
      parameter = plt.sumiMid,
      preproc = plt.indigoDeep,
      punct = plt.sumiChar,
      regex = plt.indigoBright,
      special = plt.indigoDeep,
      special2 = plt.sealDeep,
      special3 = plt.sealBright,
      statement = plt.indigoDeep,
      string = plt.sumiMid,
      symbol = plt.indigoDeep,
      type = plt.sumiDeep,
      variable = plt.sumiDeep,
    },
    diag = {
      error = plt.sealBright,
      warning = plt.sealDeep,
      info = plt.indigoBright,
      hint = plt.sumiChar,
      ok = plt.sumiMid,
      virtual_text_error = plt.sealDeep,
      virtual_text_warning = plt.sealDeep,
      virtual_text_info = plt.indigoDeep,
      virtual_text_hint = plt.scrollDark,
      virtual_text_ok = plt.scrollDark,
    },
    diff = {
      add = plt.sumiMid,
      add_inline = plt.sumiDeep,
      change = plt.indigoDeep,
      change_inline = plt.indigoBright,
      delete = plt.sealBright,
      delete_inline = plt.sealDeep,
      text = plt.sumiDeep,
    },
    vcs = {
      added = plt.sumiMid,
      changed = plt.indigoDeep,
      removed = plt.sealBright,
    },
    term = {
      black = plt.sumiBlack,
      red = plt.sealBright,
      green = plt.sumiMid,
      yellow = plt.indigoBright,
      blue = plt.indigoDeep,
      magenta = plt.indigoDeep,
      cyan = plt.sumiChar,
      white = plt.scrollMid,
      black_bright = color(plt.sumiBlack):brighten(0.4):to_hex(),
      red_bright = color(plt.sealBright):brighten(0.1):to_hex(),
      green_bright = color(plt.sumiMid):brighten(0.2):to_hex(),
      yellow_bright = color(plt.indigoBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.indigoDeep):brighten(0.2):to_hex(),
      magenta_bright = color(plt.indigoDeep):brighten(0.3):to_hex(),
      cyan_bright = color(plt.sumiChar):brighten(0.2):to_hex(),
      white_bright = color(plt.scrollMid):brighten(0.1):to_hex(),
      indexed1 = plt.scrollDeep,
      indexed2 = plt.scrollInk,
    },
  }
end

return {
  name = "Kanagawa Zen – Blank Scroll",
  author = "PrismPunk.nvim",
  description = "Inverted Sumi-e: soft warm off-white background, dark ink — the blank scroll before the first stroke, waiting.",

  base16 = {
    base00 = palette.scrollWhite,
    base01 = palette.scrollPale,
    base02 = palette.scrollLight,
    base03 = palette.scrollMid,
    base04 = palette.scrollDark,
    base05 = palette.sumiDeep,
    base06 = palette.sumiMid,
    base07 = palette.sumiBlack,
    base08 = palette.sealBright,
    base09 = palette.sealDeep,
    base0A = palette.indigoBright,
    base0B = palette.sumiMid,
    base0C = palette.sumiChar,
    base0D = palette.indigoDeep,
    base0E = palette.indigoBright,
    base0F = palette.scrollInk,
  },

  palette = palette,
  get = M.get,
}
