local color = require("prismpunk.utils.color")

local palette = {
  voidBlack = "#080A0C",
  deepVoid = "#101418",
  shadowSlate = "#1C2228",
  duskSlate = "#2C3440",
  ashSlate = "#3C4858",
  fadeSlate = "#506070",
  mistGrey = "#708090",
  hazeGrey = "#A0B0BC",
  fogWhite = "#C8D8E4",
  dissolveWhite = "#E8F0F8",
  depthBlue = "#285880",
  currentBlue = "#4080A8",
  sedimentDeep = "#C07830",
  sedimentWarm = "#D89840",
  sedimentBright = "#E8B850",
  sedimentPale = "#F8E0A0",
  bg_darkest = "#080A0C",
  fg_lightest = "#E8F0F8",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.mistGrey,
      insert = plt.currentBlue,
      visual = plt.fadeSlate,
      replace = plt.sedimentWarm,
      command = plt.hazeGrey,
    },
    accent = {
      accent1 = plt.currentBlue,
      accent2 = plt.sedimentWarm,
      accent3 = plt.sedimentBright,
      accent4 = plt.hazeGrey,
      accent5 = plt.sedimentPale,
      invert = plt.voidBlack,
    },
    rainbow = {
      rainbow1 = plt.currentBlue,
      rainbow2 = plt.sedimentWarm,
      rainbow3 = plt.hazeGrey,
      rainbow4 = plt.sedimentBright,
      rainbow5 = plt.mistGrey,
      rainbow6 = plt.sedimentPale,
      rainbow7 = plt.depthBlue,
    },
    ui = {
      fg = plt.dissolveWhite,
      fg_dim = plt.fogWhite,
      fg_dimmer = plt.hazeGrey,
      fg_dark = plt.mistGrey,
      fg_reverse = plt.voidBlack,
      bg = plt.voidBlack,
      bg_dim = plt.voidBlack,
      bg_m1 = plt.deepVoid,
      bg_m2 = plt.shadowSlate,
      bg_m3 = plt.duskSlate,
      bg_m4 = plt.ashSlate,
      bg_p1 = plt.shadowSlate,
      bg_p2 = plt.duskSlate,
      bg_gutter = (opts.gutter ~= false) and plt.deepVoid or "none",
      bg_cursorline = plt.shadowSlate,
      bg_cursorline_alt = plt.duskSlate,
      cursorline = plt.shadowSlate,
      bg_highlight = plt.depthBlue,
      bg_search = plt.currentBlue,
      bg_visual = plt.duskSlate,
      bg_statusline = plt.deepVoid,
      border = plt.ashSlate,
      header1 = plt.currentBlue,
      header2 = plt.hazeGrey,
      special = plt.sedimentWarm,
      nontext = plt.ashSlate,
      whitespace = plt.fadeSlate,
      win_separator = plt.duskSlate,
      indent = plt.shadowSlate,
      indent_scope = plt.depthBlue,
      picker = plt.currentBlue,
      yank = plt.sedimentBright,
      mark = plt.mistGrey,
      scrollbar = plt.ashSlate,
      selection = plt.depthBlue,
      line_nr = plt.fadeSlate,
      line_nr_dim = plt.duskSlate,
      line_nr_active = plt.dissolveWhite,
      float = {
        fg = plt.fogWhite,
        bg = plt.duskSlate,
        fg_border = plt.fadeSlate,
        bg_border = plt.duskSlate,
      },
      pmenu = {
        fg = plt.dissolveWhite,
        fg_sel = plt.dissolveWhite,
        fg_border = plt.fadeSlate,
        bg = plt.shadowSlate,
        bg_sel = plt.depthBlue,
        bg_border = plt.shadowSlate,
        bg_sbar = plt.shadowSlate,
        bg_thumb = plt.ashSlate,
      },
      tabline = {
        bg = plt.voidBlack,
        bg_inactive = plt.voidBlack,
        bg_selected = plt.shadowSlate,
        bg_alternate = plt.deepVoid,
        fg_inactive = plt.fadeSlate,
        fg_selected = plt.dissolveWhite,
        fg_alternate = plt.mistGrey,
        indicator = plt.currentBlue,
      },
    },
    syn = {
      attribute = plt.hazeGrey,
      boolean = plt.sedimentBright,
      comment = plt.fadeSlate,
      constant = plt.sedimentPale,
      deprecated = plt.mistGrey,
      func = plt.currentBlue,
      identifier = plt.fogWhite,
      keyword = plt.sedimentWarm,
      method = plt.currentBlue,
      number = plt.sedimentBright,
      operator = plt.mistGrey,
      parameter = plt.hazeGrey,
      preproc = plt.depthBlue,
      punct = plt.fadeSlate,
      regex = plt.sedimentBright,
      special = plt.sedimentWarm,
      special2 = plt.hazeGrey,
      special3 = plt.sedimentDeep,
      statement = plt.sedimentWarm,
      string = plt.fogWhite,
      symbol = plt.mistGrey,
      type = plt.hazeGrey,
      variable = plt.dissolveWhite,
    },
    diag = {
      error = plt.sedimentDeep,
      warning = plt.sedimentWarm,
      info = plt.currentBlue,
      hint = plt.mistGrey,
      ok = plt.hazeGrey,
      virtual_text_error = plt.sedimentDeep,
      virtual_text_warning = plt.sedimentWarm,
      virtual_text_info = plt.currentBlue,
      virtual_text_hint = plt.mistGrey,
      virtual_text_ok = plt.hazeGrey,
    },
    diff = {
      add = plt.depthBlue,
      add_inline = plt.currentBlue,
      change = plt.sedimentWarm,
      change_inline = plt.sedimentBright,
      delete = plt.sedimentDeep,
      delete_inline = plt.sedimentWarm,
      text = plt.duskSlate,
    },
    vcs = {
      added = plt.currentBlue,
      changed = plt.sedimentWarm,
      removed = plt.sedimentDeep,
    },
    term = {
      black = plt.voidBlack,
      red = plt.sedimentDeep,
      green = plt.mistGrey,
      yellow = plt.sedimentWarm,
      blue = plt.depthBlue,
      magenta = plt.fadeSlate,
      cyan = plt.currentBlue,
      white = plt.fogWhite,
      black_bright = color(plt.voidBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.sedimentDeep):brighten(0.2):to_hex(),
      green_bright = color(plt.mistGrey):brighten(0.1):to_hex(),
      yellow_bright = color(plt.sedimentWarm):brighten(0.2):to_hex(),
      blue_bright = color(plt.depthBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.fadeSlate):brighten(0.2):to_hex(),
      cyan_bright = color(plt.currentBlue):brighten(0.1):to_hex(),
      white_bright = color(plt.fogWhite):brighten(0.1):to_hex(),
      indexed1 = plt.dissolveWhite,
      indexed2 = plt.ashSlate,
    },
  }
end

return {
  name = "Kanagawa Zen – Dissolution",
  author = "PrismPunk.nvim",
  description = "Ink dropped in still water. The dark doesn't fight the light — it simply thins, disperses, becomes nothing. Two tensions: the blue-grey fade that is the whole world, and the amber sediment that remembers what solid things felt like.",

  base16 = {
    base00 = palette.voidBlack,
    base01 = palette.deepVoid,
    base02 = palette.shadowSlate,
    base03 = palette.duskSlate,
    base04 = palette.fadeSlate,
    base05 = palette.dissolveWhite,
    base06 = palette.fogWhite,
    base07 = palette.hazeGrey,
    base08 = palette.sedimentDeep,
    base09 = palette.sedimentWarm,
    base0A = palette.sedimentBright,
    base0B = palette.mistGrey,
    base0C = palette.currentBlue,
    base0D = palette.depthBlue,
    base0E = palette.hazeGrey,
    base0F = palette.sedimentPale,
  },

  palette = palette,
  get = M.get,
}
