local color = require("prismpunk.utils.color")

local palette = {
  dojoBlack = "#080806",
  dojoInk = "#141410",
  dojoWood = "#242420",
  dojoChar = "#3C3C38",
  dojoAsh = "#585850",
  dojoGrey = "#787870",
  giSilver = "#B8B8B0",
  giWhite = "#F0F0E8",
  giPure = "#F8F4EC",
  bloodDeep = "#800808",
  bloodDark = "#C01010",
  bloodMid = "#E03020",
  bloodBright = "#FF4030",
  ironDeep = "#B08030",
  ironMid = "#D4A050",
  ironBright = "#E8C060",
  bg_darkest = "#080806",
  fg_lightest = "#F8F4EC",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.giSilver,
      insert = plt.giWhite,
      visual = plt.bloodMid,
      replace = plt.bloodBright,
      command = plt.ironBright,
    },
    accent = {
      accent1 = plt.bloodMid,
      accent2 = plt.bloodBright,
      accent3 = plt.ironMid,
      accent4 = plt.giWhite,
      accent5 = plt.giPure,
      invert = plt.dojoBlack,
    },
    rainbow = {
      rainbow1 = plt.bloodBright,
      rainbow2 = plt.bloodMid,
      rainbow3 = plt.ironBright,
      rainbow4 = plt.ironMid,
      rainbow5 = plt.giWhite,
      rainbow6 = plt.giSilver,
      rainbow7 = plt.dojoGrey,
    },
    ui = {
      fg = plt.giWhite,
      fg_dim = plt.giSilver,
      fg_dimmer = plt.dojoGrey,
      fg_dark = plt.dojoAsh,
      fg_reverse = plt.dojoBlack,
      bg = plt.dojoBlack,
      bg_dim = plt.dojoBlack,
      bg_m1 = plt.dojoInk,
      bg_m2 = plt.dojoWood,
      bg_m3 = plt.dojoChar,
      bg_m4 = plt.dojoAsh,
      bg_p1 = plt.dojoWood,
      bg_p2 = plt.dojoChar,
      bg_gutter = (opts.gutter ~= false) and plt.dojoInk or "none",
      bg_cursorline = plt.dojoWood,
      bg_cursorline_alt = plt.dojoChar,
      cursorline = plt.dojoWood,
      bg_highlight = plt.dojoChar,
      bg_search = plt.bloodDeep,
      bg_visual = plt.dojoChar,
      bg_statusline = plt.dojoInk,
      border = plt.dojoChar,
      header1 = plt.giPure,
      header2 = plt.ironMid,
      special = plt.ironMid,
      nontext = plt.dojoChar,
      whitespace = plt.dojoAsh,
      win_separator = plt.dojoAsh,
      indent = plt.dojoWood,
      indent_scope = plt.bloodDeep,
      picker = plt.bloodMid,
      yank = plt.ironBright,
      mark = plt.bloodMid,
      scrollbar = plt.dojoChar,
      selection = plt.dojoChar,
      line_nr = plt.dojoGrey,
      line_nr_dim = plt.dojoAsh,
      line_nr_active = plt.giPure,
      float = {
        fg = plt.giSilver,
        bg = plt.dojoChar,
        fg_border = plt.dojoGrey,
        bg_border = plt.dojoChar,
      },
      pmenu = {
        fg = plt.giWhite,
        fg_sel = plt.giPure,
        fg_border = plt.dojoGrey,
        bg = plt.dojoWood,
        bg_sel = plt.dojoChar,
        bg_border = plt.dojoWood,
        bg_sbar = plt.dojoWood,
        bg_thumb = plt.dojoAsh,
      },
      tabline = {
        bg = plt.dojoBlack,
        bg_inactive = plt.dojoBlack,
        bg_selected = plt.dojoWood,
        bg_alternate = plt.dojoInk,
        fg_inactive = plt.dojoAsh,
        fg_selected = plt.giPure,
        fg_alternate = plt.ironMid,
        indicator = plt.bloodMid,
      },
    },
    syn = {
      attribute = plt.giSilver,
      boolean = plt.bloodBright,
      comment = plt.dojoGrey,
      constant = plt.giWhite,
      deprecated = plt.dojoAsh,
      func = plt.giPure,
      identifier = plt.giSilver,
      keyword = plt.bloodMid,
      method = plt.giPure,
      number = plt.ironBright,
      operator = plt.dojoGrey,
      parameter = plt.giSilver,
      preproc = plt.ironMid,
      punct = plt.dojoGrey,
      regex = plt.ironBright,
      special = plt.ironMid,
      special2 = plt.bloodMid,
      special3 = plt.bloodDeep,
      statement = plt.bloodMid,
      string = plt.giSilver,
      symbol = plt.ironBright,
      type = plt.giWhite,
      variable = plt.giWhite,
    },
    diag = {
      error = plt.bloodBright,
      warning = plt.ironBright,
      info = plt.giSilver,
      hint = plt.dojoGrey,
      ok = plt.giWhite,
      virtual_text_error = plt.bloodMid,
      virtual_text_warning = plt.ironMid,
      virtual_text_info = plt.dojoGrey,
      virtual_text_hint = plt.dojoAsh,
      virtual_text_ok = plt.giSilver,
    },
    diff = {
      add = plt.giWhite,
      add_inline = plt.giPure,
      change = plt.ironMid,
      change_inline = plt.ironBright,
      delete = plt.bloodMid,
      delete_inline = plt.bloodBright,
      text = plt.dojoGrey,
    },
    vcs = {
      added = plt.giWhite,
      changed = plt.ironMid,
      removed = plt.bloodMid,
    },
    term = {
      black = plt.dojoBlack,
      red = plt.bloodMid,
      green = plt.giWhite,
      yellow = plt.ironBright,
      blue = plt.dojoGrey,
      magenta = plt.bloodBright,
      cyan = plt.giSilver,
      white = plt.giPure,
      black_bright = color(plt.dojoBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.bloodMid):brighten(0.2):to_hex(),
      green_bright = color(plt.giWhite):brighten(0.1):to_hex(),
      yellow_bright = color(plt.ironBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.dojoGrey):brighten(0.3):to_hex(),
      magenta_bright = color(plt.bloodBright):brighten(0.1):to_hex(),
      cyan_bright = color(plt.giSilver):brighten(0.1):to_hex(),
      white_bright = color(plt.giPure):brighten(0.1):to_hex(),
      indexed1 = plt.ironDeep,
      indexed2 = plt.bloodDeep,
    },
  }
end

return {
  name = "Kanagawa Zen – Dojo",
  author = "PrismPunk.nvim",
  description = "Dark wood floor and gi white — a dojo at dawn, the silence before practice, one mark of blood red on the wall.",

  base16 = {
    base00 = palette.dojoBlack,
    base01 = palette.dojoInk,
    base02 = palette.dojoWood,
    base03 = palette.dojoChar,
    base04 = palette.dojoGrey,
    base05 = palette.giWhite,
    base06 = palette.giSilver,
    base07 = palette.giPure,
    base08 = palette.bloodMid,
    base09 = palette.ironMid,
    base0A = palette.ironBright,
    base0B = palette.giWhite,
    base0C = palette.giSilver,
    base0D = palette.dojoGrey,
    base0E = palette.bloodBright,
    base0F = palette.ironDeep,
  },

  palette = palette,
  get = M.get,
}
