local color = require("prismpunk.utils.color")

local palette = {
  wellBlack = "#060606",
  wellDeep = "#0E0E0E",
  wellInk = "#181818",
  wellChar = "#262626",
  wellAsh = "#363636",
  washDark = "#505050",
  washMid = "#707070",
  washLight = "#989898",
  washPale = "#C8C8C8",
  washWhite = "#E8E8E8",
  indigoDeep = "#1838A8",
  indigoMid = "#4068C8",
  indigoPale = "#80A0E0",
  sealDeep = "#C86820",
  sealMid = "#E89040",
  sealBright = "#F8C880",
  bg_darkest = "#060606",
  fg_lightest = "#E8E8E8",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.washLight,
      insert = plt.washPale,
      visual = plt.indigoMid,
      replace = plt.sealMid,
      command = plt.washWhite,
    },
    accent = {
      accent1 = plt.indigoMid,
      accent2 = plt.indigoPale,
      accent3 = plt.sealMid,
      accent4 = plt.washPale,
      accent5 = plt.washWhite,
      invert = plt.wellBlack,
    },
    rainbow = {
      rainbow1 = plt.indigoPale,
      rainbow2 = plt.indigoMid,
      rainbow3 = plt.sealBright,
      rainbow4 = plt.sealMid,
      rainbow5 = plt.washWhite,
      rainbow6 = plt.washPale,
      rainbow7 = plt.washMid,
    },
    ui = {
      fg = plt.washPale,
      fg_dim = plt.washLight,
      fg_dimmer = plt.washMid,
      fg_dark = plt.washDark,
      fg_reverse = plt.wellBlack,
      bg = plt.wellBlack,
      bg_dim = plt.wellBlack,
      bg_m1 = plt.wellDeep,
      bg_m2 = plt.wellInk,
      bg_m3 = plt.wellChar,
      bg_m4 = plt.wellAsh,
      bg_p1 = plt.wellInk,
      bg_p2 = plt.wellChar,
      bg_gutter = (opts.gutter ~= false) and plt.wellDeep or "none",
      bg_cursorline = plt.wellInk,
      bg_cursorline_alt = plt.wellChar,
      cursorline = plt.wellInk,
      bg_highlight = plt.wellChar,
      bg_search = plt.indigoDeep,
      bg_visual = plt.wellChar,
      bg_statusline = plt.wellDeep,
      border = plt.wellChar,
      header1 = plt.washWhite,
      header2 = plt.indigoMid,
      special = plt.indigoMid,
      nontext = plt.wellChar,
      whitespace = plt.wellAsh,
      win_separator = plt.washDark,
      indent = plt.wellInk,
      indent_scope = plt.indigoDeep,
      picker = plt.indigoMid,
      yank = plt.sealBright,
      mark = plt.indigoMid,
      scrollbar = plt.wellChar,
      selection = plt.wellChar,
      line_nr = plt.washMid,
      line_nr_dim = plt.washDark,
      line_nr_active = plt.washWhite,
      float = {
        fg = plt.washLight,
        bg = plt.wellChar,
        fg_border = plt.washDark,
        bg_border = plt.wellChar,
      },
      pmenu = {
        fg = plt.washPale,
        fg_sel = plt.washWhite,
        fg_border = plt.washDark,
        bg = plt.wellInk,
        bg_sel = plt.wellChar,
        bg_border = plt.wellInk,
        bg_sbar = plt.wellInk,
        bg_thumb = plt.washDark,
      },
      tabline = {
        bg = plt.wellBlack,
        bg_inactive = plt.wellBlack,
        bg_selected = plt.wellInk,
        bg_alternate = plt.wellDeep,
        fg_inactive = plt.washDark,
        fg_selected = plt.washWhite,
        fg_alternate = plt.indigoMid,
        indicator = plt.sealMid,
      },
    },
    syn = {
      attribute = plt.washLight,
      boolean = plt.sealMid,
      comment = plt.washMid,
      constant = plt.washPale,
      deprecated = plt.washDark,
      func = plt.washWhite,
      identifier = plt.washLight,
      keyword = plt.indigoMid,
      method = plt.washWhite,
      number = plt.sealBright,
      operator = plt.washMid,
      parameter = plt.washLight,
      preproc = plt.indigoPale,
      punct = plt.washMid,
      regex = plt.sealBright,
      special = plt.indigoMid,
      special2 = plt.sealMid,
      special3 = plt.indigoDeep,
      statement = plt.indigoMid,
      string = plt.washLight,
      symbol = plt.sealMid,
      type = plt.washPale,
      variable = plt.washPale,
    },
    diag = {
      error = plt.sealMid,
      warning = plt.sealBright,
      info = plt.indigoMid,
      hint = plt.washMid,
      ok = plt.washPale,
      virtual_text_error = plt.sealDeep,
      virtual_text_warning = plt.sealMid,
      virtual_text_info = plt.indigoPale,
      virtual_text_hint = plt.washDark,
      virtual_text_ok = plt.washLight,
    },
    diff = {
      add = plt.washPale,
      add_inline = plt.washWhite,
      change = plt.indigoMid,
      change_inline = plt.indigoPale,
      delete = plt.sealMid,
      delete_inline = plt.sealBright,
      text = plt.washLight,
    },
    vcs = {
      added = plt.washPale,
      changed = plt.indigoMid,
      removed = plt.sealMid,
    },
    term = {
      black = plt.wellBlack,
      red = plt.sealMid,
      green = plt.washPale,
      yellow = plt.sealBright,
      blue = plt.indigoMid,
      magenta = plt.indigoPale,
      cyan = plt.washLight,
      white = plt.washWhite,
      black_bright = color(plt.wellBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.sealMid):brighten(0.2):to_hex(),
      green_bright = color(plt.washPale):brighten(0.1):to_hex(),
      yellow_bright = color(plt.sealBright):brighten(0.1):to_hex(),
      blue_bright = color(plt.indigoMid):brighten(0.2):to_hex(),
      magenta_bright = color(plt.indigoPale):brighten(0.1):to_hex(),
      cyan_bright = color(plt.washLight):brighten(0.1):to_hex(),
      white_bright = color(plt.washWhite):brighten(0.1):to_hex(),
      indexed1 = plt.indigoDeep,
      indexed2 = plt.sealDeep,
    },
  }
end

return {
  name = "Kanagawa Zen – Inkstone",
  author = "PrismPunk.nvim",
  description = "Near-pure black with fading grey washes, pure Sumi-e — the inkstone well, a single indigo stroke, the artist's seal.",

  base16 = {
    base00 = palette.wellBlack,
    base01 = palette.wellDeep,
    base02 = palette.wellInk,
    base03 = palette.wellChar,
    base04 = palette.washMid,
    base05 = palette.washPale,
    base06 = palette.washLight,
    base07 = palette.washWhite,
    base08 = palette.sealMid,
    base09 = palette.sealBright,
    base0A = palette.indigoPale,
    base0B = palette.washPale,
    base0C = palette.washLight,
    base0D = palette.indigoMid,
    base0E = palette.indigoPale,
    base0F = palette.indigoDeep,
  },

  palette = palette,
  get = M.get,
}
