local color = require("prismpunk.utils.color")

local palette = {
  dragonBlack0 = "#0D0C0C",
  dragonBlack1 = "#12120F",
  dragonBlack2 = "#1C1A1A",
  dragonBlack3 = "#282626",
  dragonBlack4 = "#393535",
  dragonGray0 = "#4A4848",
  dragonGray1 = "#625E5E",
  dragonGray2 = "#7A7575",
  dragonAsh = "#A09898",
  waveBlue0 = "#223249",
  waveBlue1 = "#2D4360",
  dragonBlue = "#658594",
  dragonTeal = "#6A9589",
  dragonWhite0 = "#B8C3C3",
  dragonWhite1 = "#C5D0D0",
  dragonWhite2 = "#D8E2E2",
  springViolet0 = "#49455E",
  springViolet1 = "#6652A0",
  dragonViolet = "#8A739A",
  bg_darkest = "#0D0C0C",
  fg_lightest = "#D8E2E2",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.dragonBlue,
      insert = plt.dragonTeal,
      visual = plt.springViolet1,
      replace = plt.dragonViolet,
      command = plt.dragonWhite1,
    },
    accent = {
      accent1 = plt.dragonBlue,
      accent2 = plt.dragonTeal,
      accent3 = plt.springViolet1,
      accent4 = plt.dragonViolet,
      accent5 = plt.dragonWhite1,
      invert = plt.dragonBlack0,
    },
    rainbow = {
      rainbow1 = plt.dragonBlue,
      rainbow2 = plt.dragonTeal,
      rainbow3 = plt.springViolet1,
      rainbow4 = plt.dragonViolet,
      rainbow5 = plt.dragonWhite1,
      rainbow6 = plt.waveBlue1,
      rainbow7 = plt.springViolet0,
    },
    ui = {
      fg = plt.dragonWhite2,
      fg_dim = plt.dragonWhite1,
      fg_dimmer = plt.dragonWhite0,
      fg_dark = plt.dragonAsh,
      fg_reverse = plt.dragonBlack0,
      bg = plt.dragonBlack0,
      bg_dim = plt.dragonBlack0,
      bg_m1 = plt.dragonBlack1,
      bg_m2 = plt.dragonBlack2,
      bg_m3 = plt.dragonBlack3,
      bg_m4 = plt.dragonBlack4,
      bg_p1 = plt.dragonBlack2,
      bg_p2 = plt.dragonBlack3,
      bg_gutter = (opts.gutter ~= false) and plt.dragonBlack1 or "none",
      bg_cursorline = plt.dragonBlack2,
      bg_cursorline_alt = plt.dragonBlack3,
      cursorline = plt.dragonBlack2,
      bg_highlight = plt.waveBlue0,
      bg_search = plt.waveBlue1,
      bg_visual = plt.dragonBlack3,
      bg_statusline = plt.dragonBlack1,
      border = plt.dragonBlack4,
      header1 = plt.dragonBlue,
      header2 = plt.dragonTeal,
      special = plt.springViolet1,
      nontext = plt.dragonBlack3,
      whitespace = plt.dragonBlack4,
      win_separator = plt.dragonBlack4,
      indent = plt.dragonBlack2,
      indent_scope = plt.waveBlue0,
      picker = plt.springViolet1,
      yank = plt.dragonTeal,
      mark = plt.dragonBlue,
      scrollbar = plt.dragonBlack3,
      selection = plt.waveBlue0,
      line_nr = plt.dragonGray1,
      line_nr_dim = plt.dragonGray0,
      line_nr_active = plt.dragonWhite2,
      float = {
        fg = plt.dragonWhite1,
        bg = plt.dragonBlack3,
        fg_border = plt.dragonGray1,
        bg_border = plt.dragonBlack3,
      },
      pmenu = {
        fg = plt.dragonWhite2,
        fg_sel = plt.dragonWhite2,
        fg_border = plt.dragonGray1,
        bg = plt.dragonBlack2,
        bg_sel = plt.waveBlue0,
        bg_border = plt.dragonBlack2,
        bg_sbar = plt.dragonBlack2,
        bg_thumb = plt.dragonBlack4,
      },
      tabline = {
        bg = plt.dragonBlack0,
        bg_inactive = plt.dragonBlack0,
        bg_selected = plt.dragonBlack2,
        bg_alternate = plt.dragonBlack1,
        fg_inactive = plt.dragonGray1,
        fg_selected = plt.dragonWhite2,
        fg_alternate = plt.dragonBlue,
        indicator = plt.dragonTeal,
      },
    },
    syn = {
      attribute = plt.dragonWhite1,
      boolean = plt.dragonTeal,
      comment = plt.dragonGray1,
      constant = plt.dragonWhite0,
      deprecated = plt.dragonGray0,
      func = plt.dragonBlue,
      identifier = plt.dragonWhite2,
      keyword = plt.springViolet1,
      method = plt.dragonBlue,
      number = plt.dragonTeal,
      operator = plt.dragonAsh,
      parameter = plt.dragonWhite1,
      preproc = plt.waveBlue1,
      punct = plt.dragonGray1,
      regex = plt.dragonWhite0,
      special = plt.springViolet1,
      special2 = plt.dragonViolet,
      special3 = plt.springViolet0,
      statement = plt.springViolet1,
      string = plt.dragonTeal,
      symbol = plt.dragonBlue,
      type = plt.dragonTeal,
      variable = plt.dragonWhite2,
    },
    diag = {
      error = plt.springViolet1,
      warning = plt.dragonWhite0,
      info = plt.dragonBlue,
      hint = plt.dragonGray2,
      ok = plt.dragonTeal,
      virtual_text_error = plt.springViolet1,
      virtual_text_warning = plt.dragonWhite0,
      virtual_text_info = plt.dragonBlue,
      virtual_text_hint = plt.dragonGray2,
      virtual_text_ok = plt.dragonTeal,
    },
    diff = {
      add = plt.dragonTeal,
      add_inline = plt.dragonBlue,
      change = plt.dragonWhite0,
      change_inline = plt.dragonWhite1,
      delete = plt.springViolet1,
      delete_inline = plt.dragonViolet,
      text = plt.waveBlue1,
    },
    vcs = {
      added = plt.dragonTeal,
      changed = plt.dragonWhite0,
      removed = plt.springViolet1,
    },
    term = {
      black = plt.dragonBlack0,
      red = plt.springViolet1,
      green = plt.dragonTeal,
      yellow = plt.dragonWhite0,
      blue = plt.dragonBlue,
      magenta = plt.dragonViolet,
      cyan = plt.dragonTeal,
      white = plt.dragonWhite1,
      black_bright = color(plt.dragonBlack0):brighten(0.6):to_hex(),
      red_bright = color(plt.springViolet1):brighten(0.2):to_hex(),
      green_bright = color(plt.dragonTeal):brighten(0.1):to_hex(),
      yellow_bright = color(plt.dragonWhite0):brighten(0.2):to_hex(),
      blue_bright = color(plt.dragonBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.dragonViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.dragonTeal):brighten(0.1):to_hex(),
      white_bright = color(plt.dragonWhite1):brighten(0.2):to_hex(),
      indexed1 = plt.dragonWhite2,
      indexed2 = plt.springViolet0,
    },
  }
end

return {
  name = "Kanagawa Zen – Liminal",
  author = "PrismPunk.nvim",
  description = "Cold fluorescent corridor. Institutional blue-grey. The feeling of a space between spaces — vast, empty, wrong.",

  base16 = {
    base00 = palette.dragonBlack0,
    base01 = palette.dragonBlack1,
    base02 = palette.dragonBlack2,
    base03 = palette.dragonBlack3,
    base04 = palette.dragonGray1,
    base05 = palette.dragonWhite2,
    base06 = palette.dragonWhite1,
    base07 = palette.dragonWhite0,
    base08 = palette.springViolet1,
    base09 = palette.dragonViolet,
    base0A = palette.dragonWhite0,
    base0B = palette.dragonTeal,
    base0C = palette.dragonBlue,
    base0D = palette.waveBlue1,
    base0E = palette.springViolet0,
    base0F = palette.dragonGray2,
  },

  palette = palette,
  get = M.get,
}
