local color = require("prismpunk.utils.color")

local palette = {
  silenceBlack0 = "#060608",
  silenceBlack1 = "#0C0C10",
  silenceBlack2 = "#141418",
  silenceBlack3 = "#1E1E24",
  silenceBlack4 = "#28282E",
  silenceBlack5 = "#34343E",
  silenceGray0 = "#444454",
  silenceGray1 = "#5C5C70",
  silenceGray2 = "#787890",
  silenceGray3 = "#9898B0",
  silenceDeep0 = "#181828",
  silenceDeep1 = "#202038",
  emberDeep = "#A05030",
  emberWarm = "#C07048",
  emberBright = "#E09060",
  emberPale = "#F8D8B0",
  bg_darkest = "#060608",
  fg_lightest = "#F8D8B0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.silenceGray2,
      insert = plt.emberWarm,
      visual = plt.silenceGray1,
      replace = plt.emberBright,
      command = plt.silenceGray3,
    },
    accent = {
      accent1 = plt.silenceGray2,
      accent2 = plt.emberWarm,
      accent3 = plt.emberBright,
      accent4 = plt.silenceGray3,
      accent5 = plt.emberPale,
      invert = plt.silenceBlack0,
    },
    rainbow = {
      rainbow1 = plt.emberBright,
      rainbow2 = plt.silenceGray3,
      rainbow3 = plt.emberWarm,
      rainbow4 = plt.silenceGray2,
      rainbow5 = plt.emberPale,
      rainbow6 = plt.silenceGray1,
      rainbow7 = plt.emberDeep,
    },
    ui = {
      fg = plt.emberPale,
      fg_dim = plt.emberBright,
      fg_dimmer = plt.emberWarm,
      fg_dark = plt.silenceGray3,
      fg_reverse = plt.silenceBlack0,
      bg = plt.silenceBlack0,
      bg_dim = plt.silenceBlack0,
      bg_m1 = plt.silenceBlack1,
      bg_m2 = plt.silenceBlack2,
      bg_m3 = plt.silenceBlack3,
      bg_m4 = plt.silenceBlack4,
      bg_p1 = plt.silenceBlack2,
      bg_p2 = plt.silenceBlack3,
      bg_gutter = (opts.gutter ~= false) and plt.silenceBlack1 or "none",
      bg_cursorline = plt.silenceBlack2,
      bg_cursorline_alt = plt.silenceBlack3,
      cursorline = plt.silenceBlack2,
      bg_highlight = plt.silenceDeep0,
      bg_search = plt.silenceDeep1,
      bg_visual = plt.silenceBlack3,
      bg_statusline = plt.silenceBlack1,
      border = plt.silenceBlack5,
      header1 = plt.emberWarm,
      header2 = plt.silenceGray2,
      special = plt.emberWarm,
      nontext = plt.silenceBlack4,
      whitespace = plt.silenceBlack5,
      win_separator = plt.silenceBlack5,
      indent = plt.silenceBlack2,
      indent_scope = plt.silenceDeep0,
      picker = plt.emberWarm,
      yank = plt.emberBright,
      mark = plt.silenceGray2,
      scrollbar = plt.silenceBlack4,
      selection = plt.silenceDeep0,
      line_nr = plt.silenceGray0,
      line_nr_dim = plt.silenceBlack5,
      line_nr_active = plt.emberPale,
      float = {
        fg = plt.emberBright,
        bg = plt.silenceBlack3,
        fg_border = plt.silenceGray0,
        bg_border = plt.silenceBlack3,
      },
      pmenu = {
        fg = plt.emberPale,
        fg_sel = plt.emberPale,
        fg_border = plt.silenceGray0,
        bg = plt.silenceBlack2,
        bg_sel = plt.silenceDeep1,
        bg_border = plt.silenceBlack2,
        bg_sbar = plt.silenceBlack2,
        bg_thumb = plt.silenceBlack4,
      },
      tabline = {
        bg = plt.silenceBlack0,
        bg_inactive = plt.silenceBlack0,
        bg_selected = plt.silenceBlack2,
        bg_alternate = plt.silenceBlack1,
        fg_inactive = plt.silenceGray0,
        fg_selected = plt.emberPale,
        fg_alternate = plt.silenceGray2,
        indicator = plt.emberWarm,
      },
    },
    syn = {
      attribute = plt.emberBright,
      boolean = plt.silenceGray3,
      comment = plt.silenceGray0,
      constant = plt.emberPale,
      deprecated = plt.silenceGray1,
      func = plt.silenceGray2,
      identifier = plt.emberPale,
      keyword = plt.emberWarm,
      method = plt.silenceGray2,
      number = plt.emberBright,
      operator = plt.silenceGray1,
      parameter = plt.emberBright,
      preproc = plt.silenceDeep1,
      punct = plt.silenceGray0,
      regex = plt.emberBright,
      special = plt.emberWarm,
      special2 = plt.silenceGray3,
      special3 = plt.emberDeep,
      statement = plt.emberWarm,
      string = plt.emberBright,
      symbol = plt.silenceGray2,
      type = plt.silenceGray3,
      variable = plt.emberPale,
    },
    diag = {
      error = plt.emberDeep,
      warning = plt.emberWarm,
      info = plt.silenceGray2,
      hint = plt.silenceGray1,
      ok = plt.silenceGray3,
      virtual_text_error = plt.emberDeep,
      virtual_text_warning = plt.emberWarm,
      virtual_text_info = plt.silenceGray2,
      virtual_text_hint = plt.silenceGray1,
      virtual_text_ok = plt.silenceGray3,
    },
    diff = {
      add = plt.silenceGray2,
      add_inline = plt.silenceGray3,
      change = plt.emberWarm,
      change_inline = plt.emberBright,
      delete = plt.emberDeep,
      delete_inline = plt.emberWarm,
      text = plt.silenceDeep1,
    },
    vcs = {
      added = plt.silenceGray2,
      changed = plt.emberWarm,
      removed = plt.emberDeep,
    },
    term = {
      black = plt.silenceBlack0,
      red = plt.emberDeep,
      green = plt.silenceGray2,
      yellow = plt.emberWarm,
      blue = plt.silenceDeep1,
      magenta = plt.silenceGray1,
      cyan = plt.silenceGray3,
      white = plt.emberBright,
      black_bright = color(plt.silenceBlack0):brighten(0.6):to_hex(),
      red_bright = color(plt.emberDeep):brighten(0.2):to_hex(),
      green_bright = color(plt.silenceGray2):brighten(0.1):to_hex(),
      yellow_bright = color(plt.emberWarm):brighten(0.2):to_hex(),
      blue_bright = color(plt.silenceDeep1):brighten(0.3):to_hex(),
      magenta_bright = color(plt.silenceGray1):brighten(0.2):to_hex(),
      cyan_bright = color(plt.silenceGray3):brighten(0.1):to_hex(),
      white_bright = color(plt.emberBright):brighten(0.2):to_hex(),
      indexed1 = plt.emberPale,
      indexed2 = plt.silenceBlack5,
    },
  }
end

return {
  name = "Kanagawa Zen – Silence",
  author = "PrismPunk.nvim",
  description = "A room at 3am. Near-black with a barely-perceptible blue-grey cast. One ember — not warmth, just proof that cold has a limit.",

  base16 = {
    base00 = palette.silenceBlack0,
    base01 = palette.silenceBlack1,
    base02 = palette.silenceBlack2,
    base03 = palette.silenceBlack3,
    base04 = palette.silenceGray0,
    base05 = palette.emberPale,
    base06 = palette.emberBright,
    base07 = palette.emberWarm,
    base08 = palette.emberDeep,
    base09 = palette.emberWarm,
    base0A = palette.emberBright,
    base0B = palette.silenceGray2,
    base0C = palette.silenceGray3,
    base0D = palette.silenceDeep1,
    base0E = palette.silenceGray1,
    base0F = palette.silenceBlack5,
  },

  palette = palette,
  get = M.get,
}
