local color = require("prismpunk.utils.color")

local palette = {
  voidBlack = "#0A0A0A",
  inkBlack = "#181818",
  ashBlack = "#282828",
  stoneDeep = "#404040",
  stoneMid = "#606060",
  stoneLight = "#909090",
  stonePale = "#C0C0C0",
  gravelDark = "#A09078",
  gravelMid = "#B8AE9C",
  gravelLight = "#D0C8B4",
  gravelPale = "#E8E4D8",
  gravelCream = "#FFF0D0",
  sandDeep = "#786858",
  mossGold = "#C07020",
  mossAmber = "#E09030",
  mossFlare = "#F8C860",
  bg_darkest = "#0A0A0A",
  fg_lightest = "#FFF0D0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.stoneLight,
      insert = plt.gravelPale,
      visual = plt.mossAmber,
      replace = plt.mossFlare,
      command = plt.gravelCream,
    },
    accent = {
      accent1 = plt.mossAmber,
      accent2 = plt.mossFlare,
      accent3 = plt.mossGold,
      accent4 = plt.gravelPale,
      accent5 = plt.gravelCream,
      invert = plt.voidBlack,
    },
    rainbow = {
      rainbow1 = plt.mossFlare,
      rainbow2 = plt.mossAmber,
      rainbow3 = plt.mossGold,
      rainbow4 = plt.gravelPale,
      rainbow5 = plt.gravelLight,
      rainbow6 = plt.stoneLight,
      rainbow7 = plt.stoneMid,
    },
    ui = {
      fg = plt.gravelPale,
      fg_dim = plt.gravelLight,
      fg_dimmer = plt.gravelMid,
      fg_dark = plt.gravelDark,
      fg_reverse = plt.voidBlack,
      bg = plt.voidBlack,
      bg_dim = plt.voidBlack,
      bg_m1 = plt.inkBlack,
      bg_m2 = plt.ashBlack,
      bg_m3 = plt.stoneDeep,
      bg_m4 = plt.stoneMid,
      bg_p1 = plt.ashBlack,
      bg_p2 = plt.stoneDeep,
      bg_gutter = (opts.gutter ~= false) and plt.inkBlack or "none",
      bg_cursorline = plt.ashBlack,
      bg_cursorline_alt = plt.stoneDeep,
      cursorline = plt.ashBlack,
      bg_highlight = plt.stoneDeep,
      bg_search = plt.mossGold,
      bg_visual = plt.stoneDeep,
      bg_statusline = plt.inkBlack,
      border = plt.stoneDeep,
      header1 = plt.gravelPale,
      header2 = plt.mossAmber,
      special = plt.mossAmber,
      nontext = plt.stoneDeep,
      whitespace = plt.stoneMid,
      win_separator = plt.stoneMid,
      indent = plt.ashBlack,
      indent_scope = plt.mossGold,
      picker = plt.mossAmber,
      yank = plt.mossFlare,
      mark = plt.mossAmber,
      scrollbar = plt.stoneDeep,
      selection = plt.stoneDeep,
      line_nr = plt.stoneMid,
      line_nr_dim = plt.stoneDeep,
      line_nr_active = plt.gravelPale,
      float = {
        fg = plt.gravelLight,
        bg = plt.stoneDeep,
        fg_border = plt.stoneMid,
        bg_border = plt.stoneDeep,
      },
      pmenu = {
        fg = plt.gravelPale,
        fg_sel = plt.gravelCream,
        fg_border = plt.stoneMid,
        bg = plt.ashBlack,
        bg_sel = plt.stoneDeep,
        bg_border = plt.ashBlack,
        bg_sbar = plt.ashBlack,
        bg_thumb = plt.stoneMid,
      },
      tabline = {
        bg = plt.voidBlack,
        bg_inactive = plt.voidBlack,
        bg_selected = plt.ashBlack,
        bg_alternate = plt.inkBlack,
        fg_inactive = plt.stoneMid,
        fg_selected = plt.gravelPale,
        fg_alternate = plt.mossAmber,
        indicator = plt.mossFlare,
      },
    },
    syn = {
      attribute = plt.gravelLight,
      boolean = plt.mossFlare,
      comment = plt.stoneMid,
      constant = plt.gravelPale,
      deprecated = plt.sandDeep,
      func = plt.gravelPale,
      identifier = plt.gravelLight,
      keyword = plt.mossAmber,
      method = plt.gravelPale,
      number = plt.mossFlare,
      operator = plt.gravelMid,
      parameter = plt.gravelMid,
      preproc = plt.mossGold,
      punct = plt.stoneMid,
      regex = plt.mossFlare,
      special = plt.mossAmber,
      special2 = plt.gravelLight,
      special3 = plt.mossGold,
      statement = plt.mossAmber,
      string = plt.gravelLight,
      symbol = plt.mossFlare,
      type = plt.stoneLight,
      variable = plt.gravelPale,
    },
    diag = {
      error = plt.mossGold,
      warning = plt.mossAmber,
      info = plt.stoneLight,
      hint = plt.gravelMid,
      ok = plt.gravelPale,
      virtual_text_error = plt.mossGold,
      virtual_text_warning = plt.mossAmber,
      virtual_text_info = plt.stoneLight,
      virtual_text_hint = plt.gravelMid,
      virtual_text_ok = plt.gravelPale,
    },
    diff = {
      add = plt.gravelPale,
      add_inline = plt.gravelCream,
      change = plt.mossAmber,
      change_inline = plt.mossFlare,
      delete = plt.mossGold,
      delete_inline = plt.sandDeep,
      text = plt.stoneLight,
    },
    vcs = {
      added = plt.gravelPale,
      changed = plt.mossAmber,
      removed = plt.mossGold,
    },
    term = {
      black = plt.voidBlack,
      red = plt.mossGold,
      green = plt.gravelPale,
      yellow = plt.mossFlare,
      blue = plt.stoneLight,
      magenta = plt.mossAmber,
      cyan = plt.gravelLight,
      white = plt.gravelCream,
      black_bright = color(plt.voidBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.mossGold):brighten(0.2):to_hex(),
      green_bright = color(plt.gravelPale):brighten(0.1):to_hex(),
      yellow_bright = color(plt.mossFlare):brighten(0.2):to_hex(),
      blue_bright = color(plt.stoneLight):brighten(0.2):to_hex(),
      magenta_bright = color(plt.mossAmber):brighten(0.2):to_hex(),
      cyan_bright = color(plt.gravelLight):brighten(0.1):to_hex(),
      white_bright = color(plt.gravelCream):brighten(0.1):to_hex(),
      indexed1 = plt.stonePale,
      indexed2 = plt.sandDeep,
    },
  }
end

return {
  name = "Kanagawa Zen – Stone Garden",
  author = "PrismPunk.nvim",
  description = "Raked gravel and void shadow — extreme restraint, a single lantern of moss-gold against the achromatic field.",

  base16 = {
    base00 = palette.voidBlack,
    base01 = palette.inkBlack,
    base02 = palette.ashBlack,
    base03 = palette.stoneDeep,
    base04 = palette.stoneLight,
    base05 = palette.gravelPale,
    base06 = palette.gravelLight,
    base07 = palette.gravelCream,
    base08 = palette.mossGold,
    base09 = palette.mossAmber,
    base0A = palette.mossFlare,
    base0B = palette.gravelPale,
    base0C = palette.stoneLight,
    base0D = palette.gravelMid,
    base0E = palette.sandDeep,
    base0F = palette.stonePale,
  },

  palette = palette,
  get = M.get,
}
