local color = require("prismpunk.utils.color")

local palette = {
  voidBlack = "#080808",
  inkBlack = "#100E0C",
  ashBlack = "#1A1614",
  sootGray = "#28221E",
  charcoalGray = "#382E28",
  slateGray = "#504438",
  dustGray = "#6A5A4C",
  stoneGray = "#887868",
  candleCore = "#FFD060",
  candleFlame = "#F0A020",
  candleGlow = "#C87010",
  candleEmber = "#A05010",
  candleSmoke = "#784030",
  scrollCream = "#F0E8D0",
  scrollIvory = "#D8CEB8",
  scrollTan = "#B8A888",
  scrollSienna = "#907860",
  patina = "#7A9880",
  patinaDeep = "#4A6858",
  bg_darkest = "#080808",
  fg_lightest = "#F0E8D0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.candleFlame,
      insert = plt.candleCore,
      visual = plt.patina,
      replace = plt.candleGlow,
      command = plt.scrollIvory,
    },
    accent = {
      accent1 = plt.candleFlame,
      accent2 = plt.candleCore,
      accent3 = plt.candleGlow,
      accent4 = plt.patina,
      accent5 = plt.scrollCream,
      invert = plt.voidBlack,
    },
    rainbow = {
      rainbow1 = plt.candleCore,
      rainbow2 = plt.candleFlame,
      rainbow3 = plt.candleGlow,
      rainbow4 = plt.candleEmber,
      rainbow5 = plt.patina,
      rainbow6 = plt.scrollIvory,
      rainbow7 = plt.patinaDeep,
    },
    ui = {
      fg = plt.scrollCream,
      fg_dim = plt.scrollIvory,
      fg_dimmer = plt.scrollTan,
      fg_dark = plt.scrollSienna,
      fg_reverse = plt.voidBlack,
      bg = plt.voidBlack,
      bg_dim = plt.voidBlack,
      bg_m1 = plt.inkBlack,
      bg_m2 = plt.ashBlack,
      bg_m3 = plt.sootGray,
      bg_m4 = plt.charcoalGray,
      bg_p1 = plt.ashBlack,
      bg_p2 = plt.sootGray,
      bg_gutter = (opts.gutter ~= false) and plt.inkBlack or "none",
      bg_cursorline = plt.ashBlack,
      bg_cursorline_alt = plt.sootGray,
      cursorline = plt.ashBlack,
      bg_highlight = plt.charcoalGray,
      bg_search = plt.candleEmber,
      bg_visual = plt.sootGray,
      bg_statusline = plt.inkBlack,
      border = plt.sootGray,
      header1 = plt.candleFlame,
      header2 = plt.candleCore,
      special = plt.patina,
      nontext = plt.sootGray,
      whitespace = plt.charcoalGray,
      win_separator = plt.slateGray,
      indent = plt.ashBlack,
      indent_scope = plt.candleEmber,
      picker = plt.patina,
      yank = plt.candleCore,
      mark = plt.candleFlame,
      scrollbar = plt.sootGray,
      selection = plt.charcoalGray,
      line_nr = plt.dustGray,
      line_nr_dim = plt.slateGray,
      line_nr_active = plt.scrollCream,
      float = {
        fg = plt.scrollIvory,
        bg = plt.sootGray,
        fg_border = plt.slateGray,
        bg_border = plt.sootGray,
      },
      pmenu = {
        fg = plt.scrollCream,
        fg_sel = plt.scrollCream,
        fg_border = plt.slateGray,
        bg = plt.ashBlack,
        bg_sel = plt.sootGray,
        bg_border = plt.ashBlack,
        bg_sbar = plt.ashBlack,
        bg_thumb = plt.charcoalGray,
      },
      tabline = {
        bg = plt.voidBlack,
        bg_inactive = plt.voidBlack,
        bg_selected = plt.ashBlack,
        bg_alternate = plt.inkBlack,
        fg_inactive = plt.dustGray,
        fg_selected = plt.scrollCream,
        fg_alternate = plt.candleFlame,
        indicator = plt.candleGlow,
      },
    },
    syn = {
      attribute = plt.scrollIvory,
      boolean = plt.candleCore,
      comment = plt.dustGray,
      constant = plt.candleCore,
      deprecated = plt.scrollSienna,
      func = plt.candleFlame,
      identifier = plt.scrollCream,
      keyword = plt.candleGlow,
      method = plt.candleFlame,
      number = plt.candleCore,
      operator = plt.scrollTan,
      parameter = plt.scrollTan,
      preproc = plt.patina,
      punct = plt.dustGray,
      regex = plt.candleCore,
      special = plt.patina,
      special2 = plt.scrollIvory,
      special3 = plt.candleEmber,
      statement = plt.candleGlow,
      string = plt.scrollIvory,
      symbol = plt.candleCore,
      type = plt.patina,
      variable = plt.scrollCream,
    },
    diag = {
      error = plt.candleEmber,
      warning = plt.candleFlame,
      info = plt.patina,
      hint = plt.scrollTan,
      ok = plt.patinaDeep,
      virtual_text_error = plt.candleEmber,
      virtual_text_warning = plt.candleFlame,
      virtual_text_info = plt.patina,
      virtual_text_hint = plt.scrollTan,
      virtual_text_ok = plt.patinaDeep,
    },
    diff = {
      add = plt.patina,
      add_inline = plt.patinaDeep,
      change = plt.candleFlame,
      change_inline = plt.candleCore,
      delete = plt.candleEmber,
      delete_inline = plt.candleSmoke,
      text = plt.candleGlow,
    },
    vcs = {
      added = plt.patina,
      changed = plt.candleFlame,
      removed = plt.candleEmber,
    },
    term = {
      black = plt.voidBlack,
      red = plt.candleEmber,
      green = plt.patina,
      yellow = plt.candleFlame,
      blue = plt.patinaDeep,
      magenta = plt.candleSmoke,
      cyan = plt.patina,
      white = plt.scrollIvory,
      black_bright = color(plt.voidBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.candleEmber):brighten(0.2):to_hex(),
      green_bright = color(plt.patina):brighten(0.1):to_hex(),
      yellow_bright = color(plt.candleFlame):brighten(0.2):to_hex(),
      blue_bright = color(plt.patinaDeep):brighten(0.3):to_hex(),
      magenta_bright = color(plt.candleSmoke):brighten(0.2):to_hex(),
      cyan_bright = color(plt.patina):brighten(0.1):to_hex(),
      white_bright = color(plt.scrollIvory):brighten(0.2):to_hex(),
      indexed1 = plt.candleCore,
      indexed2 = plt.scrollTan,
    },
  }
end

return {
  name = "Kanagawa Zen – Tokonoma",
  author = "PrismPunk.nvim",
  description = "A tokonoma alcove at dusk — void black shadows, a single candleflame, aged scroll and patina bronze.",

  base16 = {
    base00 = palette.voidBlack,
    base01 = palette.inkBlack,
    base02 = palette.ashBlack,
    base03 = palette.sootGray,
    base04 = palette.dustGray,
    base05 = palette.scrollCream,
    base06 = palette.scrollIvory,
    base07 = palette.scrollTan,
    base08 = palette.candleEmber,
    base09 = palette.candleFlame,
    base0A = palette.candleCore,
    base0B = palette.patina,
    base0C = palette.patinaDeep,
    base0D = palette.scrollSienna,
    base0E = palette.candleSmoke,
    base0F = palette.candleGlow,
  },

  palette = palette,
  get = M.get,
}
