local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0C14",
  kryptonian_night = "#0D111A",
  fortress_core = "#121825",
  solar_glow = "#182340",
  kryptonian_blue = "#0055FF",
  metropolis_sky = "#0066FF",
  hope_blue = "#0088FF",
  sky_shield = "#44AAFF",
  house_of_el_red = "#CC1122",
  cape_red = "#DD2233",
  kryptonian_red = "#EE3344",
  hope_red = "#FF5566",
  shield_gold = "#FFAA00",
  solar_yellow = "#FFBB22",
  kryptonian_gold = "#FFCC44",
  sunrise_yellow = "#FFDD66",
  kansas_sunrise = "#FFCC88",
  clark_skin = "#FFDDAA",
  maize_field = "#FFEECC",
  term_blue = "#0088FF",
  term_red = "#DD2233",
  term_yellow = "#FFBB22",
  term_cyan = "#44CCFF",
  term_blue_bright = "#44AAFF",
  term_red_bright = "#FF5566",
  term_yellow_bright = "#FFDD66",

  bg_darkest = "#0A0C14",
  fg_lightest = "#FFDD66",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.kryptonian_blue,
      insert = plt.shield_gold,
      visual = plt.cape_red,
      replace = plt.kryptonian_red,
      command = plt.hope_blue,
    },

    ui = {
      fg = plt.clark_skin,
      fg_dim = plt.kansas_sunrise,
      fg_dimmer = plt.maize_field,
      fg_dark = plt.metropolis_sky,
      fg_reverse = plt.void_black,

      bg_m4 = plt.solar_glow,
      bg_m3 = plt.fortress_core,
      bg_m2 = plt.kryptonian_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.kryptonian_night,
      bg_p2 = plt.fortress_core,
      bg_gutter = opts.gutter and plt.fortress_core or "none",
      bg_cursorline = plt.fortress_core,
      bg_cursorline_alt = plt.kryptonian_night,
      bg_search = plt.sunrise_yellow,
      bg_visual = plt.cape_red,
      bg_statusline = plt.fortress_core,

      border = plt.shield_gold,
      header1 = plt.kryptonian_blue,
      header2 = plt.cape_red,
      special = plt.shield_gold,
      nontext = plt.kryptonian_night,
      whitespace = plt.solar_glow,
      win_separator = plt.shield_gold,
      indent = plt.kryptonian_night,
      indent_scope = plt.metropolis_sky,
      picker = plt.clark_skin,
      yank = plt.kryptonian_red,
      mark = plt.hope_red,
      scrollbar = plt.fortress_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.clark_skin,
        bg_selected = plt.fortress_core,
        fg_inactive = plt.kansas_sunrise,
        bg_inactive = plt.void_black,
        fg_alternate = plt.shield_gold,
        bg_alternate = plt.void_black,
        indicator = plt.cape_red,
      },

      pmenu = {
        fg = plt.clark_skin,
        fg_sel = "none",
        fg_border = plt.fortress_core,
        bg_border = plt.fortress_core,
        bg = plt.fortress_core,
        bg_sel = plt.kryptonian_night,
        bg_sbar = plt.fortress_core,
        bg_thumb = plt.shield_gold,
      },

      float = {
        fg = plt.clark_skin,
        bg = plt.kryptonian_night,
        fg_border = plt.fortress_core,
        bg_border = plt.kryptonian_night,
      },
    },

    accent = {
      accent1 = plt.kryptonian_blue,
      accent2 = plt.cape_red,
      accent3 = plt.shield_gold,
      accent4 = plt.hope_blue,
      accent5 = plt.kryptonian_red,
      invert = plt.fortress_core,
    },

    rainbow = {
      rainbow1 = plt.kryptonian_blue,
      rainbow2 = plt.metropolis_sky,
      rainbow3 = plt.hope_blue,
      rainbow4 = plt.cape_red,
      rainbow5 = plt.kryptonian_red,
      rainbow6 = plt.shield_gold,
      rainbow7 = plt.solar_yellow,
    },

    syn = {
      attribute = plt.clark_skin,
      boolean = plt.kryptonian_red,
      comment = plt.kansas_sunrise,
      constant = plt.shield_gold,
      deprecated = plt.solar_glow,
      func = plt.kryptonian_blue,
      identifier = plt.clark_skin,
      keyword = plt.kryptonian_blue,
      method = plt.shield_gold,
      number = plt.cape_red,
      operator = plt.hope_blue,
      parameter = plt.kansas_sunrise,
      preproc = plt.kryptonian_red,
      punct = plt.maize_field,
      regex = plt.sky_shield,
      statement = plt.kryptonian_blue,
      string = plt.shield_gold,
      symbol = plt.clark_skin,
      type = plt.cape_red,
      variable = plt.clark_skin,
      special = plt.sunrise_yellow,
      special2 = plt.metropolis_sky,
      special3 = plt.house_of_el_red,
    },

    vcs = { added = plt.sky_shield, removed = plt.cape_red, changed = plt.shield_gold },
    diff = { add = plt.sky_shield, change = plt.hope_blue, delete = plt.kryptonian_red, text = plt.sunrise_yellow },
    diag = {
      ok = plt.sky_shield,
      error = plt.kryptonian_red,
      warning = plt.shield_gold,
      info = plt.kryptonian_blue,
      hint = plt.hope_blue,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_cyan,
      white = plt.clark_skin,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.kryptonian_blue,
      indexed2 = plt.cape_red,
    },

    treesitter = {
      ["@comment"] = plt.kansas_sunrise,
      ["@comment.documentation"] = plt.maize_field,
      ["@comment.error"] = plt.kryptonian_red,
      ["@comment.warning"] = plt.shield_gold,
      ["@comment.todo"] = plt.cape_red,
      ["@comment.note"] = plt.hope_blue,

      ["@constant"] = plt.shield_gold,
      ["@constant.builtin"] = plt.shield_gold,
      ["@constant.macro"] = plt.kryptonian_red,

      ["@string"] = plt.shield_gold,
      ["@string.documentation"] = plt.shield_gold,
      ["@string.regex"] = plt.sky_shield,
      ["@string.escape"] = plt.metropolis_sky,
      ["@string.special"] = plt.cape_red,
      ["@string.special.symbol"] = plt.clark_skin,
      ["@string.special.url"] = plt.hope_blue,
      ["@string.special.path"] = plt.shield_gold,

      ["@character"] = plt.shield_gold,
      ["@character.special"] = plt.metropolis_sky,

      ["@number"] = plt.cape_red,
      ["@number.float"] = plt.cape_red,

      ["@boolean"] = plt.kryptonian_red,

      ["@function"] = plt.kryptonian_blue,
      ["@function.builtin"] = plt.kryptonian_blue,
      ["@function.call"] = plt.kryptonian_blue,
      ["@function.macro"] = plt.shield_gold,
      ["@function.method"] = plt.shield_gold,
      ["@function.method.call"] = plt.shield_gold,

      ["@constructor"] = plt.clark_skin,

      ["@parameter"] = plt.kansas_sunrise,
      ["@parameter.builtin"] = plt.clark_skin,

      ["@keyword"] = plt.kryptonian_blue,
      ["@keyword.coroutine"] = plt.kryptonian_red,
      ["@keyword.function"] = plt.kryptonian_blue,
      ["@keyword.operator"] = plt.hope_blue,
      ["@keyword.return"] = plt.kryptonian_blue,
      ["@keyword.import"] = plt.shield_gold,
      ["@keyword.storage"] = plt.kryptonian_blue,
      ["@keyword.repeat"] = plt.kryptonian_blue,
      ["@keyword.conditional"] = plt.kryptonian_blue,
      ["@keyword.exception"] = plt.sunrise_yellow,
      ["@keyword.directive"] = plt.kryptonian_red,
      ["@keyword.directive.define"] = plt.kryptonian_red,

      ["@conditional"] = plt.kryptonian_blue,
      ["@conditional.ternary"] = plt.kryptonian_blue,

      ["@repeat"] = plt.kryptonian_blue,

      ["@label"] = plt.shield_gold,

      ["@operator"] = plt.hope_blue,

      ["@exception"] = plt.sunrise_yellow,

      ["@variable"] = plt.clark_skin,
      ["@variable.builtin"] = plt.maize_field,
      ["@variable.parameter"] = plt.kansas_sunrise,
      ["@variable.member"] = plt.clark_skin,

      ["@type"] = plt.cape_red,
      ["@type.builtin"] = plt.cape_red,
      ["@type.definition"] = plt.cape_red,
      ["@type.qualifier"] = plt.kryptonian_blue,

      ["@attribute"] = plt.clark_skin,
      ["@attribute.builtin"] = plt.cape_red,

      ["@property"] = plt.clark_skin,
      ["@field"] = plt.clark_skin,
      ["@module"] = plt.clark_skin,
      ["@module.builtin"] = plt.clark_skin,
      ["@namespace"] = plt.clark_skin,
      ["@namespace.builtin"] = plt.clark_skin,

      ["@punctuation.delimiter"] = plt.maize_field,
      ["@punctuation.bracket"] = plt.metropolis_sky,
      ["@punctuation.special"] = plt.hope_blue,

      ["@tag"] = plt.kryptonian_blue,
      ["@tag.attribute"] = plt.cape_red,
      ["@tag.delimiter"] = plt.maize_field,
      ["@tag.builtin"] = plt.kryptonian_blue,

      ["@markup.strong"] = { fg = plt.kryptonian_blue, bold = true },
      ["@markup.italic"] = { fg = plt.clark_skin, italic = true },
      ["@markup.strikethrough"] = { fg = plt.solar_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cape_red, underline = true },
      ["@markup.heading"] = plt.kryptonian_blue,
      ["@markup.heading.1"] = plt.kryptonian_blue,
      ["@markup.heading.2"] = plt.cape_red,
      ["@markup.heading.3"] = plt.shield_gold,
      ["@markup.heading.4"] = plt.hope_blue,
      ["@markup.heading.5"] = plt.metropolis_sky,
      ["@markup.heading.6"] = plt.sky_shield,
      ["@markup.quote"] = plt.kansas_sunrise,
      ["@markup.math"] = plt.sky_shield,
      ["@markup.link"] = plt.hope_blue,
      ["@markup.link.label"] = plt.sunrise_yellow,
      ["@markup.link.url"] = plt.shield_gold,
      ["@markup.raw"] = plt.shield_gold,
      ["@markup.raw.block"] = plt.shield_gold,
      ["@markup.list"] = plt.kryptonian_blue,
      ["@markup.list.checked"] = plt.sky_shield,
      ["@markup.list.unchecked"] = plt.kansas_sunrise,

      ["@diff.plus"] = plt.sky_shield,
      ["@diff.minus"] = plt.cape_red,
      ["@diff.delta"] = plt.shield_gold,

      ["@none"] = "none",
      ["@conceal"] = plt.maize_field,
      ["@spell"] = plt.clark_skin,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.clark_skin,
      ["@constructor.python"] = plt.kryptonian_blue,
      ["@constructor.javascript"] = plt.kryptonian_blue,
      ["@constructor.typescript"] = plt.kryptonian_blue,
      ["@namespace.rust"] = plt.clark_skin,
      ["@type.qualifier.rust"] = plt.kryptonian_blue,
      ["@constant.macro.c"] = plt.kryptonian_red,
      ["@constant.macro.cpp"] = plt.kryptonian_red,
      ["@namespace.go"] = plt.clark_skin,
      ["@property.css"] = plt.shield_gold,
      ["@type.css"] = plt.kryptonian_blue,
      ["@label.json"] = plt.clark_skin,
      ["@field.yaml"] = plt.kansas_sunrise,
      ["@property.toml"] = plt.kansas_sunrise,
      ["@function.builtin.bash"] = plt.shield_gold,
      ["@string.regexp"] = plt.sky_shield,
      ["@character.special.regex"] = plt.metropolis_sky,
    },

    lsp = {
      ["@lsp.type.class"] = plt.cape_red,
      ["@lsp.type.interface"] = plt.cape_red,
      ["@lsp.type.struct"] = plt.cape_red,
      ["@lsp.type.enum"] = plt.cape_red,
      ["@lsp.type.enumMember"] = plt.shield_gold,
      ["@lsp.type.property"] = plt.clark_skin,
      ["@lsp.type.namespace"] = plt.clark_skin,

      ["@lsp.type.macro"] = plt.kryptonian_red,
      ["@lsp.type.decorator"] = plt.kryptonian_blue,

      ["@lsp.type.builtinType"] = plt.cape_red,
      ["@lsp.type.selfParameter"] = plt.kryptonian_blue,
      ["@lsp.type.typeParameter"] = plt.cape_red,

      ["@lsp.type.array"] = plt.cape_red,
      ["@lsp.type.object"] = plt.cape_red,
      ["@lsp.type.key"] = plt.clark_skin,
      ["@lsp.type.null"] = plt.shield_gold,
      ["@lsp.type.enumConstant"] = plt.shield_gold,

      ["@lsp.type.event"] = plt.cape_red,
      ["@lsp.type.regexp"] = plt.sky_shield,
      ["@lsp.type.unresolvedReference"] = plt.kryptonian_red,

      ["@lsp.mod.deprecated"] = { fg = plt.solar_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.shield_gold,
      ["@lsp.mod.async"] = plt.kryptonian_blue,
      ["@lsp.mod.static"] = plt.cape_red,
      ["@lsp.mod.abstract"] = plt.cape_red,
      ["@lsp.mod.defaultLibrary"] = plt.cape_red,
      ["@lsp.mod.documentation"] = plt.kansas_sunrise,
    },
  }
end

return {
  name = "Clark Kent – The Last Son of Krypton",
  author = "PrismPunk.nvim",
  description = "He’s faster than a speeding bullet, more powerful than a locomotive, "
    .. "and somehow still makes time to help you carry groceries. Blue, red, and golden hope.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.kryptonian_night,
    base02 = palette.fortress_core,
    base03 = palette.solar_glow,
    base04 = palette.maize_field,
    base05 = palette.kansas_sunrise,
    base06 = palette.clark_skin,
    base07 = palette.clark_skin,
    base08 = palette.kryptonian_red,
    base09 = palette.cape_red,
    base0A = palette.shield_gold,
    base0B = palette.solar_yellow,
    base0C = palette.kryptonian_blue,
    base0D = palette.hope_blue,
    base0E = palette.sky_shield,
    base0F = palette.sunrise_yellow,
  },

  palette = palette,
  get = M.get,
}
