local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0C12",
  composite_void = "#0D1018",
  split_core = "#12151F",
  fracture_glow = "#181C28",
  hope_blue = "#0088FF",
  composite_blue = "#0099FF",
  kryptonian_sky = "#00AAFF",
  solar_blue = "#44BBFF",
  hope_red = "#DD2233",
  cape_red = "#EE3344",
  house_of_el = "#FF4455",
  shield_gold = "#FFAA00",
  solar_gold = "#FFBB22",
  kryptonian_sun = "#FFCC44",
  gotham_night = "#0A0F1A",
  bat_purple = "#6600CC",
  composite_purple = "#7700DD",
  fear_violet = "#8800EE",
  dark_knight = "#9933FF",
  bat_teal = "#00CCAA",
  utility_teal = "#00DDBB",
  cape_shadow = "#00EECC",
  term_blue = "#0099FF",
  term_red = "#EE3344",
  term_purple = "#7700DD",
  term_gold = "#FFBB22",
  term_teal = "#00DDBB",
  term_blue_bright = "#44BBFF",
  term_red_bright = "#FF6677",
  term_purple_bright = "#AA33FF",

  bg_darkest = "#0A0C12",
  fg_lightest = "#44BBFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.composite_blue,
      insert = plt.composite_purple,
      visual = plt.cape_red,
      replace = plt.house_of_el,
      command = plt.fear_violet,
    },

    ui = {
      fg = plt.solar_gold,
      fg_dim = plt.kryptonian_sun,
      fg_dimmer = plt.shield_gold,
      fg_dark = plt.bat_purple,
      fg_reverse = plt.void_black,

      bg_m4 = plt.fracture_glow,
      bg_m3 = plt.split_core,
      bg_m2 = plt.composite_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.composite_void,
      bg_p2 = plt.split_core,
      bg_gutter = opts.gutter and plt.split_core or "none",
      bg_cursorline = plt.split_core,
      bg_cursorline_alt = plt.composite_void,
      bg_search = plt.house_of_el,
      bg_visual = plt.fear_violet,
      bg_statusline = plt.split_core,

      border = plt.solar_gold,
      header1 = plt.composite_blue,
      header2 = plt.composite_purple,
      special = plt.cape_red,
      nontext = plt.composite_void,
      whitespace = plt.fracture_glow,
      win_separator = plt.solar_gold,
      indent = plt.composite_void,
      indent_scope = plt.gotham_night,
      picker = plt.kryptonian_sun,
      yank = plt.house_of_el,
      mark = plt.fear_violet,
      scrollbar = plt.split_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.solar_gold,
        bg_selected = plt.split_core,
        fg_inactive = plt.shield_gold,
        bg_inactive = plt.void_black,
        fg_alternate = plt.cape_red,
        bg_alternate = plt.void_black,
        indicator = plt.bat_purple,
      },

      pmenu = {
        fg = plt.solar_gold,
        fg_sel = "none",
        fg_border = plt.split_core,
        bg_border = plt.split_core,
        bg = plt.split_core,
        bg_sel = plt.composite_void,
        bg_sbar = plt.split_core,
        bg_thumb = plt.solar_gold,
      },

      float = {
        fg = plt.solar_gold,
        bg = plt.composite_void,
        fg_border = plt.split_core,
        bg_border = plt.composite_void,
      },
    },

    accent = {
      accent1 = plt.composite_blue,
      accent2 = plt.composite_purple,
      accent3 = plt.cape_red,
      accent4 = plt.solar_gold,
      accent5 = plt.fear_violet,
      invert = plt.split_core,
    },

    rainbow = {
      rainbow1 = plt.composite_blue,
      rainbow2 = plt.kryptonian_sky,
      rainbow3 = plt.solar_blue,
      rainbow4 = plt.cape_red,
      rainbow5 = plt.composite_purple,
      rainbow6 = plt.fear_violet,
      rainbow7 = plt.solar_gold,
    },

    syn = {
      attribute = plt.solar_gold,
      boolean = plt.house_of_el,
      comment = plt.utility_teal,
      constant = plt.shield_gold,
      deprecated = plt.fracture_glow,
      func = plt.composite_blue,
      identifier = plt.solar_gold,
      keyword = plt.composite_blue,
      method = plt.composite_purple,
      number = plt.cape_red,
      operator = plt.bat_teal,
      parameter = plt.kryptonian_sun,
      preproc = plt.house_of_el,
      punct = plt.solar_gold,
      regex = plt.fear_violet,
      statement = plt.composite_blue,
      string = plt.solar_blue,
      symbol = plt.solar_gold,
      type = plt.composite_purple,
      variable = plt.solar_gold,
      special = plt.kryptonian_sun,
      special2 = plt.bat_purple,
      special3 = plt.cape_red,
    },

    vcs = { added = plt.solar_blue, removed = plt.house_of_el, changed = plt.fear_violet },
    diff = { add = plt.solar_blue, change = plt.bat_teal, delete = plt.cape_red, text = plt.kryptonian_sun },
    diag = {
      ok = plt.solar_blue,
      error = plt.house_of_el,
      warning = plt.composite_purple,
      info = plt.bat_teal,
      hint = plt.solar_gold,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_gold,
      blue = plt.term_purple,
      magenta = plt.term_red,
      cyan = plt.term_teal,
      white = plt.solar_gold,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_gold,
      blue_bright = plt.term_purple_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_teal,
      white_bright = "#ffffff",
      indexed1 = plt.composite_blue,
      indexed2 = plt.composite_purple,
    },

    treesitter = {
      ["@comment"] = plt.utility_teal,
      ["@comment.documentation"] = plt.kryptonian_sun,
      ["@comment.error"] = plt.house_of_el,
      ["@comment.warning"] = plt.cape_red,
      ["@comment.todo"] = plt.composite_purple,
      ["@comment.note"] = plt.bat_teal,

      ["@constant"] = plt.shield_gold,
      ["@constant.builtin"] = plt.shield_gold,
      ["@constant.macro"] = plt.house_of_el,

      ["@string"] = plt.solar_blue,
      ["@string.documentation"] = plt.solar_blue,
      ["@string.regex"] = plt.fear_violet,
      ["@string.escape"] = plt.bat_teal,
      ["@string.special"] = plt.cape_red,
      ["@string.special.symbol"] = plt.solar_gold,
      ["@string.special.url"] = plt.composite_purple,
      ["@string.special.path"] = plt.solar_blue,

      ["@character"] = plt.solar_blue,
      ["@character.special"] = plt.bat_teal,

      ["@number"] = plt.cape_red,
      ["@number.float"] = plt.cape_red,

      ["@boolean"] = plt.house_of_el,

      ["@function"] = plt.composite_blue,
      ["@function.builtin"] = plt.composite_blue,
      ["@function.call"] = plt.composite_blue,
      ["@function.macro"] = plt.composite_purple,
      ["@function.method"] = plt.composite_purple,
      ["@function.method.call"] = plt.composite_purple,

      ["@constructor"] = plt.solar_gold,

      ["@parameter"] = plt.kryptonian_sun,
      ["@parameter.builtin"] = plt.solar_gold,

      ["@keyword"] = plt.composite_blue,
      ["@keyword.coroutine"] = plt.house_of_el,
      ["@keyword.function"] = plt.composite_blue,
      ["@keyword.operator"] = plt.bat_teal,
      ["@keyword.return"] = plt.composite_blue,
      ["@keyword.import"] = plt.solar_blue,
      ["@keyword.storage"] = plt.composite_blue,
      ["@keyword.repeat"] = plt.composite_blue,
      ["@keyword.conditional"] = plt.composite_blue,
      ["@keyword.exception"] = plt.fear_violet,
      ["@keyword.directive"] = plt.house_of_el,
      ["@keyword.directive.define"] = plt.house_of_el,

      ["@conditional"] = plt.composite_blue,
      ["@conditional.ternary"] = plt.composite_blue,

      ["@repeat"] = plt.composite_blue,

      ["@label"] = plt.composite_purple,

      ["@operator"] = plt.bat_teal,

      ["@exception"] = plt.fear_violet,

      ["@variable"] = plt.solar_gold,
      ["@variable.builtin"] = plt.kryptonian_sun,
      ["@variable.parameter"] = plt.kryptonian_sun,
      ["@variable.member"] = plt.solar_gold,

      ["@type"] = plt.composite_purple,
      ["@type.builtin"] = plt.composite_purple,
      ["@type.definition"] = plt.composite_purple,
      ["@type.qualifier"] = plt.composite_blue,

      ["@attribute"] = plt.solar_gold,
      ["@attribute.builtin"] = plt.composite_purple,

      ["@property"] = plt.solar_gold,
      ["@field"] = plt.solar_gold,
      ["@module"] = plt.solar_gold,
      ["@module.builtin"] = plt.solar_gold,
      ["@namespace"] = plt.solar_gold,
      ["@namespace.builtin"] = plt.solar_gold,

      ["@punctuation.delimiter"] = plt.solar_gold,
      ["@punctuation.bracket"] = plt.gotham_night,
      ["@punctuation.special"] = plt.bat_teal,

      ["@tag"] = plt.composite_blue,
      ["@tag.attribute"] = plt.composite_purple,
      ["@tag.delimiter"] = plt.solar_gold,
      ["@tag.builtin"] = plt.composite_blue,

      ["@markup.strong"] = { fg = plt.composite_blue, bold = true },
      ["@markup.italic"] = { fg = plt.solar_gold, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fracture_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cape_red, underline = true },
      ["@markup.heading"] = plt.composite_blue,
      ["@markup.heading.1"] = plt.composite_blue,
      ["@markup.heading.2"] = plt.cape_red,
      ["@markup.heading.3"] = plt.composite_purple,
      ["@markup.heading.4"] = plt.solar_gold,
      ["@markup.heading.5"] = plt.bat_teal,
      ["@markup.heading.6"] = plt.fear_violet,
      ["@markup.quote"] = plt.utility_teal,
      ["@markup.math"] = plt.solar_blue,
      ["@markup.link"] = plt.bat_teal,
      ["@markup.link.label"] = plt.kryptonian_sun,
      ["@markup.link.url"] = plt.fear_violet,
      ["@markup.raw"] = plt.solar_blue,
      ["@markup.raw.block"] = plt.solar_blue,
      ["@markup.list"] = plt.composite_blue,
      ["@markup.list.checked"] = plt.solar_blue,
      ["@markup.list.unchecked"] = plt.utility_teal,

      ["@diff.plus"] = plt.solar_blue,
      ["@diff.minus"] = plt.cape_red,
      ["@diff.delta"] = plt.fear_violet,

      ["@none"] = "none",
      ["@conceal"] = plt.solar_gold,
      ["@spell"] = plt.solar_gold,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.solar_gold,
      ["@constructor.python"] = plt.composite_blue,
      ["@constructor.javascript"] = plt.composite_blue,
      ["@constructor.typescript"] = plt.composite_blue,
      ["@namespace.rust"] = plt.solar_gold,
      ["@type.qualifier.rust"] = plt.composite_blue,
      ["@constant.macro.c"] = plt.house_of_el,
      ["@constant.macro.cpp"] = plt.house_of_el,
      ["@namespace.go"] = plt.solar_gold,
      ["@property.css"] = plt.composite_purple,
      ["@type.css"] = plt.composite_blue,
      ["@label.json"] = plt.solar_gold,
      ["@field.yaml"] = plt.kryptonian_sun,
      ["@property.toml"] = plt.kryptonian_sun,
      ["@function.builtin.bash"] = plt.bat_teal,
      ["@string.regexp"] = plt.fear_violet,
      ["@character.special.regex"] = plt.bat_teal,
    },

    lsp = {
      ["@lsp.type.class"] = plt.composite_purple,
      ["@lsp.type.interface"] = plt.composite_purple,
      ["@lsp.type.struct"] = plt.composite_purple,
      ["@lsp.type.enum"] = plt.composite_purple,
      ["@lsp.type.enumMember"] = plt.solar_gold,
      ["@lsp.type.property"] = plt.solar_gold,
      ["@lsp.type.namespace"] = plt.solar_gold,

      ["@lsp.type.macro"] = plt.house_of_el,
      ["@lsp.type.decorator"] = plt.composite_blue,

      ["@lsp.type.builtinType"] = plt.composite_purple,
      ["@lsp.type.selfParameter"] = plt.composite_blue,
      ["@lsp.type.typeParameter"] = plt.composite_purple,

      ["@lsp.type.array"] = plt.composite_purple,
      ["@lsp.type.object"] = plt.composite_purple,
      ["@lsp.type.key"] = plt.solar_gold,
      ["@lsp.type.null"] = plt.solar_gold,
      ["@lsp.type.enumConstant"] = plt.solar_gold,

      ["@lsp.type.event"] = plt.composite_purple,
      ["@lsp.type.regexp"] = plt.fear_violet,
      ["@lsp.type.unresolvedReference"] = plt.house_of_el,

      ["@lsp.mod.deprecated"] = { fg = plt.fracture_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.solar_gold,
      ["@lsp.mod.async"] = plt.composite_blue,
      ["@lsp.mod.static"] = plt.composite_purple,
      ["@lsp.mod.abstract"] = plt.composite_purple,
      ["@lsp.mod.defaultLibrary"] = plt.composite_purple,
      ["@lsp.mod.documentation"] = plt.utility_teal,
    },
  }
end

return {
  name = "Composite Superman – Half God, Half Nightmare",
  author = "PrismPunk.nvim",
  description = "Two legends. One mind. Blue hope on the left, purple terror on the right. "
    .. "He is everything you admire… and everything you fear.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.composite_void,
    base02 = palette.split_core,
    base03 = palette.fracture_glow,
    base04 = palette.gotham_night,
    base05 = palette.kryptonian_sun,
    base06 = palette.solar_gold,
    base07 = palette.solar_gold,
    base08 = palette.house_of_el,
    base09 = palette.cape_red,
    base0A = palette.composite_purple,
    base0B = palette.fear_violet,
    base0C = palette.composite_blue,
    base0D = palette.solar_blue,
    base0E = palette.bat_teal,
    base0F = palette.kryptonian_sky,
  },

  palette = palette,
  get = M.get,
}
