local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0C0A18",
  dream_void = "#0F0D20",
  precog_core = "#141128",
  starlight_glow = "#1A1638",
  dream_indigo = "#5522FF",
  nia_indigo = "#6633FF",
  precog_violet = "#7744FF",
  starlight_purple = "#9988FF",
  dreamer_pink = "#FF66DD",
  nia_pink = "#FF77EE",
  hope_pink = "#FF88FF",
  cosmic_pink = "#FFAAEE",
  morning_sky = "#AADDFF",
  dream_sky = "#CCEEFF",
  nia_white = "#EEFFFF",
  term_indigo = "#6633FF",
  term_pink = "#FF77EE",
  term_sky = "#CCEEFF",
  term_indigo_bright = "#9988FF",
  term_pink_bright = "#FFAAFF",

  bg_darkest = "#0C0A18",
  fg_lightest = "#EEFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.nia_indigo,
      insert = plt.dreamer_pink,
      visual = plt.precog_violet,
      replace = plt.hope_pink,
      command = plt.starlight_purple,
    },

    ui = {
      fg = plt.nia_white,
      fg_dim = plt.dream_sky,
      fg_dimmer = plt.morning_sky,
      fg_dark = plt.precog_violet,
      fg_reverse = plt.void_black,

      bg_m4 = plt.starlight_glow,
      bg_m3 = plt.precog_core,
      bg_m2 = plt.dream_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.dream_void,
      bg_p2 = plt.precog_core,
      bg_gutter = opts.gutter and plt.precog_core or "none",
      bg_cursorline = plt.precog_core,
      bg_cursorline_alt = plt.dream_void,
      bg_search = plt.cosmic_pink,
      bg_visual = plt.nia_pink,
      bg_statusline = plt.precog_core,

      border = plt.nia_white,
      header1 = plt.nia_indigo,
      header2 = plt.dreamer_pink,
      special = plt.starlight_purple,
      nontext = plt.dream_void,
      whitespace = plt.starlight_glow,
      win_separator = plt.nia_white,
      indent = plt.dream_void,
      indent_scope = plt.dream_indigo,
      picker = plt.dream_sky,
      yank = plt.hope_pink,
      mark = plt.nia_pink,
      scrollbar = plt.precog_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.nia_white,
        bg_selected = plt.precog_core,
        fg_inactive = plt.morning_sky,
        bg_inactive = plt.void_black,
        fg_alternate = plt.dreamer_pink,
        bg_alternate = plt.void_black,
        indicator = plt.nia_indigo,
      },

      pmenu = {
        fg = plt.nia_white,
        fg_sel = "none",
        fg_border = plt.precog_core,
        bg_border = plt.precog_core,
        bg = plt.precog_core,
        bg_sel = plt.dream_void,
        bg_sbar = plt.precog_core,
        bg_thumb = plt.nia_white,
      },

      float = {
        fg = plt.nia_white,
        bg = plt.dream_void,
        fg_border = plt.precog_core,
        bg_border = plt.dream_void,
      },
    },

    accent = {
      accent1 = plt.nia_indigo,
      accent2 = plt.dreamer_pink,
      accent3 = plt.precog_violet,
      accent4 = plt.starlight_purple,
      accent5 = plt.hope_pink,
      invert = plt.precog_core,
    },

    rainbow = {
      rainbow1 = plt.nia_indigo,
      rainbow2 = plt.dream_indigo,
      rainbow3 = plt.precog_violet,
      rainbow4 = plt.starlight_purple,
      rainbow5 = plt.dreamer_pink,
      rainbow6 = plt.nia_pink,
      rainbow7 = plt.cosmic_pink,
    },

    syn = {
      attribute = plt.nia_white,
      boolean = plt.nia_pink,
      comment = plt.morning_sky,
      constant = plt.dream_sky,
      deprecated = plt.starlight_glow,
      func = plt.nia_indigo,
      identifier = plt.nia_white,
      keyword = plt.nia_indigo,
      method = plt.dreamer_pink,
      number = plt.hope_pink,
      operator = plt.precog_violet,
      parameter = plt.morning_sky,
      preproc = plt.nia_pink,
      punct = plt.dream_sky,
      regex = plt.starlight_purple,
      statement = plt.nia_indigo,
      string = plt.dream_sky,
      symbol = plt.nia_white,
      type = plt.dreamer_pink,
      variable = plt.nia_white,
      special = plt.cosmic_pink,
      special2 = plt.precog_violet,
      special3 = plt.nia_pink,
    },

    vcs = { added = plt.starlight_purple, removed = plt.nia_pink, changed = plt.dreamer_pink },
    diff = { add = plt.starlight_purple, change = plt.precog_violet, delete = plt.hope_pink, text = plt.cosmic_pink },
    diag = {
      ok = plt.starlight_purple,
      error = plt.nia_pink,
      warning = plt.dreamer_pink,
      info = plt.nia_indigo,
      hint = plt.precog_violet,
    },

    term = {
      black = plt.void_black,
      red = plt.term_pink,
      green = plt.term_indigo,
      yellow = plt.term_sky,
      blue = plt.term_indigo,
      magenta = plt.term_pink,
      cyan = plt.term_sky,
      white = plt.term_sky,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_pink_bright,
      green_bright = plt.term_indigo_bright,
      yellow_bright = plt.term_sky,
      blue_bright = plt.term_indigo_bright,
      magenta_bright = plt.term_pink_bright,
      cyan_bright = plt.term_sky,
      white_bright = "#ffffff",
      indexed1 = plt.nia_indigo,
      indexed2 = plt.dreamer_pink,
    },

    treesitter = {
      ["@comment"] = plt.morning_sky,
      ["@comment.documentation"] = plt.dream_sky,
      ["@comment.error"] = plt.nia_pink,
      ["@comment.warning"] = plt.hope_pink,
      ["@comment.todo"] = plt.dreamer_pink,
      ["@comment.note"] = plt.starlight_purple,

      ["@constant"] = plt.dream_sky,
      ["@constant.builtin"] = plt.dream_sky,
      ["@constant.macro"] = plt.hope_pink,

      ["@string"] = plt.dream_sky,
      ["@string.documentation"] = plt.dream_sky,
      ["@string.regex"] = plt.starlight_purple,
      ["@string.escape"] = plt.precog_violet,
      ["@string.special"] = plt.nia_pink,
      ["@string.special.symbol"] = plt.nia_white,
      ["@string.special.url"] = plt.dreamer_pink,
      ["@string.special.path"] = plt.dream_sky,

      ["@character"] = plt.dream_sky,
      ["@character.special"] = plt.precog_violet,

      ["@number"] = plt.hope_pink,
      ["@number.float"] = plt.hope_pink,

      ["@boolean"] = plt.nia_pink,

      ["@function"] = plt.nia_indigo,
      ["@function.builtin"] = plt.nia_indigo,
      ["@function.call"] = plt.nia_indigo,
      ["@function.macro"] = plt.dreamer_pink,
      ["@function.method"] = plt.dreamer_pink,
      ["@function.method.call"] = plt.dreamer_pink,

      ["@constructor"] = plt.nia_white,

      ["@parameter"] = plt.morning_sky,
      ["@parameter.builtin"] = plt.nia_white,

      ["@keyword"] = plt.nia_indigo,
      ["@keyword.coroutine"] = plt.nia_pink,
      ["@keyword.function"] = plt.nia_indigo,
      ["@keyword.operator"] = plt.precog_violet,
      ["@keyword.return"] = plt.nia_indigo,
      ["@keyword.import"] = plt.starlight_purple,
      ["@keyword.storage"] = plt.nia_indigo,
      ["@keyword.repeat"] = plt.nia_indigo,
      ["@keyword.conditional"] = plt.nia_indigo,
      ["@keyword.exception"] = plt.cosmic_pink,
      ["@keyword.directive"] = plt.nia_pink,
      ["@keyword.directive.define"] = plt.nia_pink,

      ["@conditional"] = plt.nia_indigo,
      ["@conditional.ternary"] = plt.nia_indigo,

      ["@repeat"] = plt.nia_indigo,

      ["@label"] = plt.dreamer_pink,

      ["@operator"] = plt.precog_violet,

      ["@exception"] = plt.cosmic_pink,

      ["@variable"] = plt.nia_white,
      ["@variable.builtin"] = plt.dream_sky,
      ["@variable.parameter"] = plt.morning_sky,
      ["@variable.member"] = plt.nia_white,

      ["@type"] = plt.dreamer_pink,
      ["@type.builtin"] = plt.dreamer_pink,
      ["@type.definition"] = plt.dreamer_pink,
      ["@type.qualifier"] = plt.nia_indigo,

      ["@attribute"] = plt.nia_white,
      ["@attribute.builtin"] = plt.dreamer_pink,

      ["@property"] = plt.nia_white,
      ["@field"] = plt.nia_white,
      ["@module"] = plt.nia_white,
      ["@module.builtin"] = plt.nia_white,
      ["@namespace"] = plt.nia_white,
      ["@namespace.builtin"] = plt.nia_white,

      ["@punctuation.delimiter"] = plt.dream_sky,
      ["@punctuation.bracket"] = plt.dream_indigo,
      ["@punctuation.special"] = plt.precog_violet,

      ["@tag"] = plt.nia_indigo,
      ["@tag.attribute"] = plt.dreamer_pink,
      ["@tag.delimiter"] = plt.dream_sky,
      ["@tag.builtin"] = plt.nia_indigo,

      ["@markup.strong"] = { fg = plt.nia_indigo, bold = true },
      ["@markup.italic"] = { fg = plt.nia_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.starlight_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.nia_pink, underline = true },
      ["@markup.heading"] = plt.nia_indigo,
      ["@markup.heading.1"] = plt.nia_indigo,
      ["@markup.heading.2"] = plt.dreamer_pink,
      ["@markup.heading.3"] = plt.nia_pink,
      ["@markup.heading.4"] = plt.precog_violet,
      ["@markup.heading.5"] = plt.starlight_purple,
      ["@markup.heading.6"] = plt.cosmic_pink,
      ["@markup.quote"] = plt.morning_sky,
      ["@markup.math"] = plt.starlight_purple,
      ["@markup.link"] = plt.precog_violet,
      ["@markup.link.label"] = plt.cosmic_pink,
      ["@markup.link.url"] = plt.dreamer_pink,
      ["@markup.raw"] = plt.dream_sky,
      ["@markup.raw.block"] = plt.dream_sky,
      ["@markup.list"] = plt.nia_indigo,
      ["@markup.list.checked"] = plt.starlight_purple,
      ["@markup.list.unchecked"] = plt.morning_sky,

      ["@diff.plus"] = plt.starlight_purple,
      ["@diff.minus"] = plt.nia_pink,
      ["@diff.delta"] = plt.dreamer_pink,

      ["@none"] = "none",
      ["@conceal"] = plt.dream_sky,
      ["@spell"] = plt.nia_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.nia_white,
      ["@constructor.python"] = plt.nia_indigo,
      ["@constructor.javascript"] = plt.nia_indigo,
      ["@constructor.typescript"] = plt.nia_indigo,
      ["@namespace.rust"] = plt.nia_white,
      ["@type.qualifier.rust"] = plt.nia_indigo,
      ["@constant.macro.c"] = plt.hope_pink,
      ["@constant.macro.cpp"] = plt.hope_pink,
      ["@namespace.go"] = plt.nia_white,
      ["@property.css"] = plt.dreamer_pink,
      ["@type.css"] = plt.nia_indigo,
      ["@label.json"] = plt.nia_white,
      ["@field.yaml"] = plt.morning_sky,
      ["@property.toml"] = plt.morning_sky,
      ["@function.builtin.bash"] = plt.dreamer_pink,
      ["@string.regexp"] = plt.starlight_purple,
      ["@character.special.regex"] = plt.precog_violet,
    },

    lsp = {
      ["@lsp.type.class"] = plt.dreamer_pink,
      ["@lsp.type.interface"] = plt.dreamer_pink,
      ["@lsp.type.struct"] = plt.dreamer_pink,
      ["@lsp.type.enum"] = plt.dreamer_pink,
      ["@lsp.type.enumMember"] = plt.dream_sky,
      ["@lsp.type.property"] = plt.nia_white,
      ["@lsp.type.namespace"] = plt.nia_white,

      ["@lsp.type.macro"] = plt.hope_pink,
      ["@lsp.type.decorator"] = plt.nia_indigo,

      ["@lsp.type.builtinType"] = plt.dreamer_pink,
      ["@lsp.type.selfParameter"] = plt.nia_indigo,
      ["@lsp.type.typeParameter"] = plt.dreamer_pink,

      ["@lsp.type.array"] = plt.dreamer_pink,
      ["@lsp.type.object"] = plt.dreamer_pink,
      ["@lsp.type.key"] = plt.nia_white,
      ["@lsp.type.null"] = plt.dream_sky,
      ["@lsp.type.enumConstant"] = plt.dream_sky,

      ["@lsp.type.event"] = plt.dreamer_pink,
      ["@lsp.type.regexp"] = plt.starlight_purple,
      ["@lsp.type.unresolvedReference"] = plt.nia_pink,

      ["@lsp.mod.deprecated"] = { fg = plt.starlight_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.dream_sky,
      ["@lsp.mod.async"] = plt.nia_indigo,
      ["@lsp.mod.static"] = plt.dreamer_pink,
      ["@lsp.mod.abstract"] = plt.dreamer_pink,
      ["@lsp.mod.defaultLibrary"] = plt.dreamer_pink,
      ["@lsp.mod.documentation"] = plt.morning_sky,
    },
  }
end

return {
  name = "Dreamer – Nia Nal",
  author = "PrismPunk.nvim",
  description = "She dreams the future in indigo and pink. Trans heroine. Legion legacy. "
    .. "Heart bigger than any precognition. The tomorrow she fights for is beautiful.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.dream_void,
    base02 = palette.precog_core,
    base03 = palette.starlight_glow,
    base04 = palette.dream_indigo,
    base05 = palette.morning_sky,
    base06 = palette.dream_sky,
    base07 = palette.nia_white,
    base08 = palette.nia_pink,
    base09 = palette.dreamer_pink,
    base0A = palette.precog_violet,
    base0B = palette.starlight_purple,
    base0C = palette.nia_indigo,
    base0D = palette.dream_indigo,
    base0E = palette.hope_pink,
    base0F = palette.cosmic_pink,
  },

  palette = palette,
  get = M.get,
}
