local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A080C",
  eradicator_void = "#0C0A10",
  judgment_core = "#12101A",
  purge_glow = "#181222",
  eradicator_metal = "#14141A",
  kryptonian_steel = "#1A1A24",
  obsidian_armor = "#22222E",
  eradicator_red = "#FF1122",
  purge_red = "#FF2233",
  judgment_red = "#FF3344",
  apocalypse_red = "#FF5566",
  eradicator_gold = "#FF8800",
  solar_forge = "#FF9900",
  kryptonian_flame = "#FFAA22",
  purge_gold = "#FFBB44",
  star_core_white = "#FFFFFF",
  eradicator_white = "#EEFFFF",
  cold_judgment = "#DDFFEE",
  term_red = "#FF2233",
  term_gold = "#FF9900",
  term_white = "#EEFFFF",
  term_red_bright = "#FF5566",
  term_gold_bright = "#FFBB44",

  bg_darkest = "#0A080C",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.eradicator_red,
      insert = plt.eradicator_gold,
      visual = plt.eradicator_metal,
      replace = plt.judgment_red,
      command = plt.purge_gold,
    },

    ui = {
      fg = plt.eradicator_white,
      fg_dim = plt.cold_judgment,
      fg_dimmer = plt.star_core_white,
      fg_dark = plt.obsidian_armor,
      fg_reverse = plt.void_black,

      bg_m4 = plt.purge_glow,
      bg_m3 = plt.judgment_core,
      bg_m2 = plt.eradicator_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.eradicator_void,
      bg_p2 = plt.judgment_core,
      bg_gutter = opts.gutter and plt.judgment_core or "none",
      bg_cursorline = plt.judgment_core,
      bg_cursorline_alt = plt.eradicator_void,
      bg_search = plt.apocalypse_red,
      bg_visual = plt.purge_red,
      bg_statusline = plt.judgment_core,

      border = plt.star_core_white,
      header1 = plt.eradicator_red,
      header2 = plt.eradicator_gold,
      special = plt.purge_gold,
      nontext = plt.eradicator_void,
      whitespace = plt.purge_glow,
      win_separator = plt.star_core_white,
      indent = plt.eradicator_void,
      indent_scope = plt.kryptonian_steel,
      picker = plt.cold_judgment,
      yank = plt.judgment_red,
      mark = plt.purge_red,
      scrollbar = plt.judgment_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.star_core_white,
        bg_selected = plt.judgment_core,
        fg_inactive = plt.cold_judgment,
        bg_inactive = plt.void_black,
        fg_alternate = plt.eradicator_red,
        bg_alternate = plt.void_black,
        indicator = plt.eradicator_gold,
      },

      pmenu = {
        fg = plt.eradicator_white,
        fg_sel = "none",
        fg_border = plt.judgment_core,
        bg_border = plt.judgment_core,
        bg = plt.judgment_core,
        bg_sel = plt.eradicator_void,
        bg_sbar = plt.judgment_core,
        bg_thumb = plt.star_core_white,
      },

      float = {
        fg = plt.eradicator_white,
        bg = plt.eradicator_void,
        fg_border = plt.judgment_core,
        bg_border = plt.eradicator_void,
      },
    },

    accent = {
      accent1 = plt.eradicator_red,
      accent2 = plt.eradicator_gold,
      accent3 = plt.eradicator_metal,
      accent4 = plt.purge_red,
      accent5 = plt.purge_gold,
      invert = plt.judgment_core,
    },

    rainbow = {
      rainbow1 = plt.eradicator_red,
      rainbow2 = plt.purge_red,
      rainbow3 = plt.judgment_red,
      rainbow4 = plt.eradicator_gold,
      rainbow5 = plt.solar_forge,
      rainbow6 = plt.kryptonian_flame,
      rainbow7 = plt.purge_gold,
    },

    syn = {
      attribute = plt.eradicator_white,
      boolean = plt.purge_red,
      comment = plt.cold_judgment,
      constant = plt.star_core_white,
      deprecated = plt.purge_glow,
      func = plt.eradicator_red,
      identifier = plt.eradicator_white,
      keyword = plt.eradicator_red,
      method = plt.eradicator_gold,
      number = plt.judgment_red,
      operator = plt.purge_gold,
      parameter = plt.cold_judgment,
      preproc = plt.purge_red,
      punct = plt.star_core_white,
      regex = plt.kryptonian_flame,
      statement = plt.eradicator_red,
      string = plt.solar_forge,
      symbol = plt.eradicator_white,
      type = plt.eradicator_gold,
      variable = plt.eradicator_white,
      special = plt.apocalypse_red,
      special2 = plt.purge_gold,
      special3 = plt.judgment_red,
    },

    vcs = { added = plt.purge_gold, removed = plt.purge_red, changed = plt.eradicator_gold },
    diff = {
      add = plt.purge_gold,
      change = plt.kryptonian_flame,
      delete = plt.judgment_red,
      text = plt.apocalypse_red,
    },
    diag = {
      ok = plt.purge_gold,
      error = plt.purge_red,
      warning = plt.eradicator_red,
      info = plt.eradicator_gold,
      hint = plt.solar_forge,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_gold,
      yellow = plt.term_white,
      blue = plt.term_gold,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_gold_bright,
      yellow_bright = plt.term_white,
      blue_bright = plt.term_gold_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.eradicator_red,
      indexed2 = plt.eradicator_gold,
    },

    treesitter = {
      ["@comment"] = plt.cold_judgment,
      ["@comment.documentation"] = plt.star_core_white,
      ["@comment.error"] = plt.purge_red,
      ["@comment.warning"] = plt.judgment_red,
      ["@comment.todo"] = plt.eradicator_red,
      ["@comment.note"] = plt.eradicator_gold,

      ["@constant"] = plt.star_core_white,
      ["@constant.builtin"] = plt.star_core_white,
      ["@constant.macro"] = plt.judgment_red,

      ["@string"] = plt.solar_forge,
      ["@string.documentation"] = plt.solar_forge,
      ["@string.regex"] = plt.kryptonian_flame,
      ["@string.escape"] = plt.purge_gold,
      ["@string.special"] = plt.purge_red,
      ["@string.special.symbol"] = plt.eradicator_white,
      ["@string.special.url"] = plt.eradicator_gold,
      ["@string.special.path"] = plt.solar_forge,

      ["@character"] = plt.solar_forge,
      ["@character.special"] = plt.purge_gold,

      ["@number"] = plt.judgment_red,
      ["@number.float"] = plt.judgment_red,

      ["@boolean"] = plt.purge_red,

      ["@function"] = plt.eradicator_red,
      ["@function.builtin"] = plt.eradicator_red,
      ["@function.call"] = plt.eradicator_red,
      ["@function.macro"] = plt.eradicator_gold,
      ["@function.method"] = plt.eradicator_gold,
      ["@function.method.call"] = plt.eradicator_gold,

      ["@constructor"] = plt.eradicator_white,

      ["@parameter"] = plt.cold_judgment,
      ["@parameter.builtin"] = plt.eradicator_white,

      ["@keyword"] = plt.eradicator_red,
      ["@keyword.coroutine"] = plt.purge_red,
      ["@keyword.function"] = plt.eradicator_red,
      ["@keyword.operator"] = plt.purge_gold,
      ["@keyword.return"] = plt.eradicator_red,
      ["@keyword.import"] = plt.solar_forge,
      ["@keyword.storage"] = plt.eradicator_red,
      ["@keyword.repeat"] = plt.eradicator_red,
      ["@keyword.conditional"] = plt.eradicator_red,
      ["@keyword.exception"] = plt.apocalypse_red,
      ["@keyword.directive"] = plt.purge_red,
      ["@keyword.directive.define"] = plt.purge_red,

      ["@conditional"] = plt.eradicator_red,
      ["@conditional.ternary"] = plt.eradicator_red,

      ["@repeat"] = plt.eradicator_red,

      ["@label"] = plt.eradicator_gold,

      ["@operator"] = plt.purge_gold,

      ["@exception"] = plt.apocalypse_red,

      ["@variable"] = plt.eradicator_white,
      ["@variable.builtin"] = plt.star_core_white,
      ["@variable.parameter"] = plt.cold_judgment,
      ["@variable.member"] = plt.eradicator_white,

      ["@type"] = plt.eradicator_gold,
      ["@type.builtin"] = plt.eradicator_gold,
      ["@type.definition"] = plt.eradicator_gold,
      ["@type.qualifier"] = plt.eradicator_red,

      ["@attribute"] = plt.eradicator_white,
      ["@attribute.builtin"] = plt.eradicator_gold,

      ["@property"] = plt.eradicator_white,
      ["@field"] = plt.eradicator_white,
      ["@module"] = plt.eradicator_white,
      ["@module.builtin"] = plt.eradicator_white,
      ["@namespace"] = plt.eradicator_white,
      ["@namespace.builtin"] = plt.eradicator_white,

      ["@punctuation.delimiter"] = plt.star_core_white,
      ["@punctuation.bracket"] = plt.obsidian_armor,
      ["@punctuation.special"] = plt.purge_gold,

      ["@tag"] = plt.eradicator_red,
      ["@tag.attribute"] = plt.eradicator_gold,
      ["@tag.delimiter"] = plt.star_core_white,
      ["@tag.builtin"] = plt.eradicator_red,

      ["@markup.strong"] = { fg = plt.eradicator_red, bold = true },
      ["@markup.italic"] = { fg = plt.eradicator_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.purge_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.purge_red, underline = true },
      ["@markup.heading"] = plt.eradicator_red,
      ["@markup.heading.1"] = plt.eradicator_red,
      ["@markup.heading.2"] = plt.purge_red,
      ["@markup.heading.3"] = plt.judgment_red,
      ["@markup.heading.4"] = plt.eradicator_gold,
      ["@markup.heading.5"] = plt.solar_forge,
      ["@markup.heading.6"] = plt.kryptonian_flame,
      ["@markup.quote"] = plt.cold_judgment,
      ["@markup.math"] = plt.purge_gold,
      ["@markup.link"] = plt.purge_gold,
      ["@markup.link.label"] = plt.apocalypse_red,
      ["@markup.link.url"] = plt.eradicator_gold,
      ["@markup.raw"] = plt.solar_forge,
      ["@markup.raw.block"] = plt.solar_forge,
      ["@markup.list"] = plt.eradicator_red,
      ["@markup.list.checked"] = plt.purge_gold,
      ["@markup.list.unchecked"] = plt.cold_judgment,

      ["@diff.plus"] = plt.purge_gold,
      ["@diff.minus"] = plt.purge_red,
      ["@diff.delta"] = plt.eradicator_gold,

      ["@none"] = "none",
      ["@conceal"] = plt.star_core_white,
      ["@spell"] = plt.eradicator_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.eradicator_white,
      ["@constructor.python"] = plt.eradicator_red,
      ["@constructor.javascript"] = plt.eradicator_red,
      ["@constructor.typescript"] = plt.eradicator_red,
      ["@namespace.rust"] = plt.eradicator_white,
      ["@type.qualifier.rust"] = plt.eradicator_red,
      ["@constant.macro.c"] = plt.judgment_red,
      ["@constant.macro.cpp"] = plt.judgment_red,
      ["@namespace.go"] = plt.eradicator_white,
      ["@property.css"] = plt.eradicator_gold,
      ["@type.css"] = plt.eradicator_red,
      ["@label.json"] = plt.eradicator_white,
      ["@field.yaml"] = plt.cold_judgment,
      ["@property.toml"] = plt.cold_judgment,
      ["@function.builtin.bash"] = plt.eradicator_gold,
      ["@string.regexp"] = plt.kryptonian_flame,
      ["@character.special.regex"] = plt.purge_gold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.eradicator_gold,
      ["@lsp.type.interface"] = plt.eradicator_gold,
      ["@lsp.type.struct"] = plt.eradicator_gold,
      ["@lsp.type.enum"] = plt.eradicator_gold,
      ["@lsp.type.enumMember"] = plt.star_core_white,
      ["@lsp.type.property"] = plt.eradicator_white,
      ["@lsp.type.namespace"] = plt.eradicator_white,

      ["@lsp.type.macro"] = plt.judgment_red,
      ["@lsp.type.decorator"] = plt.eradicator_red,

      ["@lsp.type.builtinType"] = plt.eradicator_gold,
      ["@lsp.type.selfParameter"] = plt.eradicator_red,
      ["@lsp.type.typeParameter"] = plt.eradicator_gold,

      ["@lsp.type.array"] = plt.eradicator_gold,
      ["@lsp.type.object"] = plt.eradicator_gold,
      ["@lsp.type.key"] = plt.eradicator_white,
      ["@lsp.type.null"] = plt.star_core_white,
      ["@lsp.type.enumConstant"] = plt.star_core_white,

      ["@lsp.type.event"] = plt.eradicator_gold,
      ["@lsp.type.regexp"] = plt.kryptonian_flame,
      ["@lsp.type.unresolvedReference"] = plt.purge_red,

      ["@lsp.mod.deprecated"] = { fg = plt.purge_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.star_core_white,
      ["@lsp.mod.async"] = plt.eradicator_red,
      ["@lsp.mod.static"] = plt.eradicator_gold,
      ["@lsp.mod.abstract"] = plt.eradicator_gold,
      ["@lsp.mod.defaultLibrary"] = plt.eradicator_gold,
      ["@lsp.mod.documentation"] = plt.cold_judgment,
    },
  }
end

return {
  name = "Eradicator – Last Son of Extinction",
  author = "PrismPunk.nvim",
  description = "He does not protect. He does not forgive. He purges impurity with blood-red "
    .. "judgment and molten gold fire. Krypton died so he could live. You are next.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.eradicator_void,
    base02 = palette.judgment_core,
    base03 = palette.purge_glow,
    base04 = palette.obsidian_armor,
    base05 = palette.cold_judgment,
    base06 = palette.eradicator_white,
    base07 = palette.star_core_white,
    base08 = palette.purge_red,
    base09 = palette.eradicator_red,
    base0A = palette.eradicator_gold,
    base0B = palette.solar_forge,
    base0C = palette.kryptonian_flame,
    base0D = palette.purge_gold,
    base0E = palette.judgment_red,
    base0F = palette.apocalypse_red,
  },

  palette = palette,
  get = M.get,
}
