local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0C0A12",
  planet_night = "#0F0D18",
  ink_core = "#141124",
  deadline_glow = "#1A1628",
  navy_trench = "#112244",
  midnight_navy = "#1A2A55",
  daily_planet_blue = "#223366",
  reporter_navy = "#334477",
  lois_red = "#CC1133",
  breaking_red = "#DD2244",
  headline_crimson = "#EE3355",
  scoop_rage = "#FF5577",
  lois_violet = "#AA22FF",
  truth_purple = "#BB33FF",
  justice_purple = "#CC55FF",
  expose_purple = "#DD77FF",
  press_white = "#EEFFFF",
  page_cream = "#DDEEFF",
  ink_paper = "#CCE0FF",
  term_red = "#DD2244",
  term_violet = "#BB33FF",
  term_navy = "#223366",
  term_cream = "#DDEEFF",
  term_red_bright = "#FF5577",
  term_violet_bright = "#DD77FF",

  bg_darkest = "#0C0A12",
  fg_lightest = "#EEFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.daily_planet_blue,
      insert = plt.lois_red,
      visual = plt.lois_violet,
      replace = plt.headline_crimson,
      command = plt.truth_purple,
    },

    ui = {
      fg = plt.press_white,
      fg_dim = plt.page_cream,
      fg_dimmer = plt.ink_paper,
      fg_dark = plt.reporter_navy,
      fg_reverse = plt.void_black,

      bg_m4 = plt.deadline_glow,
      bg_m3 = plt.ink_core,
      bg_m2 = plt.planet_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.planet_night,
      bg_p2 = plt.ink_core,
      bg_gutter = opts.gutter and plt.ink_core or "none",
      bg_cursorline = plt.ink_core,
      bg_cursorline_alt = plt.planet_night,
      bg_search = plt.scoop_rage,
      bg_visual = plt.breaking_red,
      bg_statusline = plt.ink_core,

      border = plt.press_white,
      header1 = plt.daily_planet_blue,
      header2 = plt.lois_red,
      special = plt.lois_violet,
      nontext = plt.planet_night,
      whitespace = plt.deadline_glow,
      win_separator = plt.press_white,
      indent = plt.planet_night,
      indent_scope = plt.midnight_navy,
      picker = plt.page_cream,
      yank = plt.headline_crimson,
      mark = plt.breaking_red,
      scrollbar = plt.ink_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.press_white,
        bg_selected = plt.ink_core,
        fg_inactive = plt.ink_paper,
        bg_inactive = plt.void_black,
        fg_alternate = plt.lois_red,
        bg_alternate = plt.void_black,
        indicator = plt.lois_violet,
      },

      pmenu = {
        fg = plt.press_white,
        fg_sel = "none",
        fg_border = plt.ink_core,
        bg_border = plt.ink_core,
        bg = plt.ink_core,
        bg_sel = plt.planet_night,
        bg_sbar = plt.ink_core,
        bg_thumb = plt.press_white,
      },

      float = {
        fg = plt.press_white,
        bg = plt.planet_night,
        fg_border = plt.ink_core,
        bg_border = plt.planet_night,
      },
    },

    accent = {
      accent1 = plt.daily_planet_blue,
      accent2 = plt.lois_red,
      accent3 = plt.lois_violet,
      accent4 = plt.truth_purple,
      accent5 = plt.headline_crimson,
      invert = plt.ink_core,
    },

    rainbow = {
      rainbow1 = plt.daily_planet_blue,
      rainbow2 = plt.navy_trench,
      rainbow3 = plt.reporter_navy,
      rainbow4 = plt.lois_red,
      rainbow5 = plt.breaking_red,
      rainbow6 = plt.lois_violet,
      rainbow7 = plt.justice_purple,
    },

    syn = {
      attribute = plt.press_white,
      boolean = plt.breaking_red,
      comment = plt.ink_paper,
      constant = plt.page_cream,
      deprecated = plt.deadline_glow,
      func = plt.daily_planet_blue,
      identifier = plt.press_white,
      keyword = plt.daily_planet_blue,
      method = plt.lois_violet,
      number = plt.headline_crimson,
      operator = plt.truth_purple,
      parameter = plt.ink_paper,
      preproc = plt.breaking_red,
      punct = plt.page_cream,
      regex = plt.expose_purple,
      statement = plt.daily_planet_blue,
      string = plt.page_cream,
      symbol = plt.press_white,
      type = plt.lois_violet,
      variable = plt.press_white,
      special = plt.scoop_rage,
      special2 = plt.lois_violet,
      special3 = plt.breaking_red,
    },

    vcs = { added = plt.expose_purple, removed = plt.breaking_red, changed = plt.lois_violet },
    diff = { add = plt.expose_purple, change = plt.truth_purple, delete = plt.headline_crimson, text = plt.scoop_rage },
    diag = {
      ok = plt.expose_purple,
      error = plt.breaking_red,
      warning = plt.lois_red,
      info = plt.lois_violet,
      hint = plt.daily_planet_blue,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_violet,
      yellow = plt.term_navy,
      blue = plt.term_navy,
      magenta = plt.term_red,
      cyan = plt.term_cream,
      white = plt.term_cream,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_violet_bright,
      yellow_bright = plt.term_navy,
      blue_bright = plt.term_navy,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_cream,
      white_bright = "#ffffff",
      indexed1 = plt.lois_red,
      indexed2 = plt.lois_violet,
    },

    treesitter = {
      ["@comment"] = plt.ink_paper,
      ["@comment.documentation"] = plt.page_cream,
      ["@comment.error"] = plt.breaking_red,
      ["@comment.warning"] = plt.headline_crimson,
      ["@comment.todo"] = plt.lois_red,
      ["@comment.note"] = plt.lois_violet,

      ["@constant"] = plt.page_cream,
      ["@constant.builtin"] = plt.page_cream,
      ["@constant.macro"] = plt.headline_crimson,

      ["@string"] = plt.page_cream,
      ["@string.documentation"] = plt.page_cream,
      ["@string.regex"] = plt.expose_purple,
      ["@string.escape"] = plt.truth_purple,
      ["@string.special"] = plt.breaking_red,
      ["@string.special.symbol"] = plt.press_white,
      ["@string.special.url"] = plt.lois_violet,
      ["@string.special.path"] = plt.page_cream,

      ["@character"] = plt.page_cream,
      ["@character.special"] = plt.truth_purple,

      ["@number"] = plt.headline_crimson,
      ["@number.float"] = plt.headline_crimson,

      ["@boolean"] = plt.breaking_red,

      ["@function"] = plt.daily_planet_blue,
      ["@function.builtin"] = plt.daily_planet_blue,
      ["@function.call"] = plt.daily_planet_blue,
      ["@function.macro"] = plt.lois_violet,
      ["@function.method"] = plt.lois_violet,
      ["@function.method.call"] = plt.lois_violet,

      ["@constructor"] = plt.press_white,

      ["@parameter"] = plt.ink_paper,
      ["@parameter.builtin"] = plt.press_white,

      ["@keyword"] = plt.daily_planet_blue,
      ["@keyword.coroutine"] = plt.breaking_red,
      ["@keyword.function"] = plt.daily_planet_blue,
      ["@keyword.operator"] = plt.truth_purple,
      ["@keyword.return"] = plt.daily_planet_blue,
      ["@keyword.import"] = plt.expose_purple,
      ["@keyword.storage"] = plt.daily_planet_blue,
      ["@keyword.repeat"] = plt.daily_planet_blue,
      ["@keyword.conditional"] = plt.daily_planet_blue,
      ["@keyword.exception"] = plt.scoop_rage,
      ["@keyword.directive"] = plt.breaking_red,
      ["@keyword.directive.define"] = plt.breaking_red,

      ["@conditional"] = plt.daily_planet_blue,
      ["@conditional.ternary"] = plt.daily_planet_blue,

      ["@repeat"] = plt.daily_planet_blue,

      ["@label"] = plt.lois_violet,

      ["@operator"] = plt.truth_purple,

      ["@exception"] = plt.scoop_rage,

      ["@variable"] = plt.press_white,
      ["@variable.builtin"] = plt.page_cream,
      ["@variable.parameter"] = plt.ink_paper,
      ["@variable.member"] = plt.press_white,

      ["@type"] = plt.lois_violet,
      ["@type.builtin"] = plt.lois_violet,
      ["@type.definition"] = plt.lois_violet,
      ["@type.qualifier"] = plt.daily_planet_blue,

      ["@attribute"] = plt.press_white,
      ["@attribute.builtin"] = plt.lois_violet,

      ["@property"] = plt.press_white,
      ["@field"] = plt.press_white,
      ["@module"] = plt.press_white,
      ["@module.builtin"] = plt.press_white,
      ["@namespace"] = plt.press_white,
      ["@namespace.builtin"] = plt.press_white,

      ["@punctuation.delimiter"] = plt.page_cream,
      ["@punctuation.bracket"] = plt.reporter_navy,
      ["@punctuation.special"] = plt.truth_purple,

      ["@tag"] = plt.daily_planet_blue,
      ["@tag.attribute"] = plt.lois_violet,
      ["@tag.delimiter"] = plt.page_cream,
      ["@tag.builtin"] = plt.daily_planet_blue,

      ["@markup.strong"] = { fg = plt.daily_planet_blue, bold = true },
      ["@markup.italic"] = { fg = plt.press_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.deadline_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.breaking_red, underline = true },
      ["@markup.heading"] = plt.daily_planet_blue,
      ["@markup.heading.1"] = plt.daily_planet_blue,
      ["@markup.heading.2"] = plt.lois_red,
      ["@markup.heading.3"] = plt.breaking_red,
      ["@markup.heading.4"] = plt.lois_violet,
      ["@markup.heading.5"] = plt.truth_purple,
      ["@markup.heading.6"] = plt.justice_purple,
      ["@markup.quote"] = plt.ink_paper,
      ["@markup.math"] = plt.expose_purple,
      ["@markup.link"] = plt.truth_purple,
      ["@markup.link.label"] = plt.scoop_rage,
      ["@markup.link.url"] = plt.lois_violet,
      ["@markup.raw"] = plt.page_cream,
      ["@markup.raw.block"] = plt.page_cream,
      ["@markup.list"] = plt.daily_planet_blue,
      ["@markup.list.checked"] = plt.expose_purple,
      ["@markup.list.unchecked"] = plt.ink_paper,

      ["@diff.plus"] = plt.expose_purple,
      ["@diff.minus"] = plt.breaking_red,
      ["@diff.delta"] = plt.lois_violet,

      ["@none"] = "none",
      ["@conceal"] = plt.page_cream,
      ["@spell"] = plt.press_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.press_white,
      ["@constructor.python"] = plt.daily_planet_blue,
      ["@constructor.javascript"] = plt.daily_planet_blue,
      ["@constructor.typescript"] = plt.daily_planet_blue,
      ["@namespace.rust"] = plt.press_white,
      ["@type.qualifier.rust"] = plt.daily_planet_blue,
      ["@constant.macro.c"] = plt.headline_crimson,
      ["@constant.macro.cpp"] = plt.headline_crimson,
      ["@namespace.go"] = plt.press_white,
      ["@property.css"] = plt.lois_violet,
      ["@type.css"] = plt.daily_planet_blue,
      ["@label.json"] = plt.press_white,
      ["@field.yaml"] = plt.ink_paper,
      ["@property.toml"] = plt.ink_paper,
      ["@function.builtin.bash"] = plt.lois_violet,
      ["@string.regexp"] = plt.expose_purple,
      ["@character.special.regex"] = plt.truth_purple,
    },

    lsp = {
      ["@lsp.type.class"] = plt.lois_violet,
      ["@lsp.type.interface"] = plt.lois_violet,
      ["@lsp.type.struct"] = plt.lois_violet,
      ["@lsp.type.enum"] = plt.lois_violet,
      ["@lsp.type.enumMember"] = plt.page_cream,
      ["@lsp.type.property"] = plt.press_white,
      ["@lsp.type.namespace"] = plt.press_white,

      ["@lsp.type.macro"] = plt.headline_crimson,
      ["@lsp.type.decorator"] = plt.daily_planet_blue,

      ["@lsp.type.builtinType"] = plt.lois_violet,
      ["@lsp.type.selfParameter"] = plt.daily_planet_blue,
      ["@lsp.type.typeParameter"] = plt.lois_violet,

      ["@lsp.type.array"] = plt.lois_violet,
      ["@lsp.type.object"] = plt.lois_violet,
      ["@lsp.type.key"] = plt.press_white,
      ["@lsp.type.null"] = plt.page_cream,
      ["@lsp.type.enumConstant"] = plt.page_cream,

      ["@lsp.type.event"] = plt.lois_violet,
      ["@lsp.type.regexp"] = plt.expose_purple,
      ["@lsp.type.unresolvedReference"] = plt.breaking_red,

      ["@lsp.mod.deprecated"] = { fg = plt.deadline_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.page_cream,
      ["@lsp.mod.async"] = plt.daily_planet_blue,
      ["@lsp.mod.static"] = plt.lois_violet,
      ["@lsp.mod.abstract"] = plt.lois_violet,
      ["@lsp.mod.defaultLibrary"] = plt.lois_violet,
      ["@lsp.mod.documentation"] = plt.ink_paper,
    },
  }
end

return {
  name = "Lois Lane – Front Page Justice",
  author = "PrismPunk.nvim",
  description = "She doesn’t fly. She doesn’t have heat vision. She has a press pass and a "
    .. "complete disregard for personal safety. Navy, crimson, and the violet fire of truth.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.planet_night,
    base02 = palette.ink_core,
    base03 = palette.deadline_glow,
    base04 = palette.reporter_navy,
    base05 = palette.ink_paper,
    base06 = palette.page_cream,
    base07 = palette.press_white,
    base08 = palette.breaking_red,
    base09 = palette.lois_red,
    base0A = palette.lois_violet,
    base0B = palette.truth_purple,
    base0C = palette.justice_purple,
    base0D = palette.expose_purple,
    base0E = palette.headline_crimson,
    base0F = palette.scoop_rage,
  },

  palette = palette,
  get = M.get,
}
