local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0C10",
  smallville_night = "#0D1118",
  barn_core = "#121924",
  porch_glow = "#182030",
  denim_blue = "#335577",
  martha_blue = "#446688",
  kansas_sky = "#5588AA",
  hope_blue = "#77AADD",
  barn_red = "#AA3322",
  flannel_red = "#BB4433",
  heart_red = "#CC6655",
  sunrise_red = "#EE8877",
  wheat_gold = "#DDBB88",
  martha_gold = "#EECC99",
  smallville_sun = "#FFDDAA",
  hope_gold = "#FFEECC",
  cream_white = "#FFFFF0",
  farmhouse_white = "#F8F8F0",
  ma_white = "#EEEEE4",
  term_red = "#BB4433",
  term_blue = "#5588AA",
  term_gold = "#EECC99",
  term_cream = "#F8F8F0",
  term_red_bright = "#EE8877",
  term_blue_bright = "#77AADD",
  term_gold_bright = "#FFEECC",

  bg_darkest = "#0A0C10",
  fg_lightest = "#FFFFF0",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.martha_blue,
      insert = plt.smallville_sun,
      visual = plt.flannel_red,
      replace = plt.heart_red,
      command = plt.kansas_sky,
    },

    ui = {
      fg = plt.cream_white,
      fg_dim = plt.farmhouse_white,
      fg_dimmer = plt.ma_white,
      fg_dark = plt.denim_blue,
      fg_reverse = plt.void_black,

      bg_m4 = plt.porch_glow,
      bg_m3 = plt.barn_core,
      bg_m2 = plt.smallville_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.smallville_night,
      bg_p2 = plt.barn_core,
      bg_gutter = opts.gutter and plt.barn_core or "none",
      bg_cursorline = plt.barn_core,
      bg_cursorline_alt = plt.smallville_night,
      bg_search = plt.smallville_sun,
      bg_visual = plt.flannel_red,
      bg_statusline = plt.barn_core,

      border = plt.wheat_gold,
      header1 = plt.martha_blue,
      header2 = plt.flannel_red,
      special = plt.martha_gold,
      nontext = plt.smallville_night,
      whitespace = plt.porch_glow,
      win_separator = plt.wheat_gold,
      indent = plt.smallville_night,
      indent_scope = plt.denim_blue,
      picker = plt.cream_white,
      yank = plt.sunrise_red,
      mark = plt.heart_red,
      scrollbar = plt.barn_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.cream_white,
        bg_selected = plt.barn_core,
        fg_inactive = plt.ma_white,
        bg_inactive = plt.void_black,
        fg_alternate = plt.flannel_red,
        bg_alternate = plt.void_black,
        indicator = plt.martha_gold,
      },

      pmenu = {
        fg = plt.cream_white,
        fg_sel = "none",
        fg_border = plt.barn_core,
        bg_border = plt.barn_core,
        bg = plt.barn_core,
        bg_sel = plt.smallville_night,
        bg_sbar = plt.barn_core,
        bg_thumb = plt.wheat_gold,
      },

      float = {
        fg = plt.cream_white,
        bg = plt.smallville_night,
        fg_border = plt.barn_core,
        bg_border = plt.smallville_night,
      },
    },

    accent = {
      accent1 = plt.martha_blue,
      accent2 = plt.flannel_red,
      accent3 = plt.martha_gold,
      accent4 = plt.kansas_sky,
      accent5 = plt.sunrise_red,
      invert = plt.barn_core,
    },

    rainbow = {
      rainbow1 = plt.martha_blue,
      rainbow2 = plt.denim_blue,
      rainbow3 = plt.kansas_sky,
      rainbow4 = plt.flannel_red,
      rainbow5 = plt.heart_red,
      rainbow6 = plt.martha_gold,
      rainbow7 = plt.smallville_sun,
    },

    syn = {
      attribute = plt.cream_white,
      boolean = plt.heart_red,
      comment = plt.ma_white,
      constant = plt.wheat_gold,
      deprecated = plt.porch_glow,
      func = plt.martha_blue,
      identifier = plt.cream_white,
      keyword = plt.martha_blue,
      method = plt.martha_gold,
      number = plt.sunrise_red,
      operator = plt.kansas_sky,
      parameter = plt.ma_white,
      preproc = plt.flannel_red,
      punct = plt.cream_white,
      regex = plt.kansas_sky,
      statement = plt.martha_blue,
      string = plt.wheat_gold,
      symbol = plt.cream_white,
      type = plt.martha_gold,
      variable = plt.cream_white,
      special = plt.smallville_sun,
      special2 = plt.kansas_sky,
      special3 = plt.heart_red,
    },

    vcs = { added = plt.kansas_sky, removed = plt.flannel_red, changed = plt.martha_gold },
    diff = { add = plt.kansas_sky, change = plt.denim_blue, delete = plt.heart_red, text = plt.smallville_sun },
    diag = {
      ok = plt.kansas_sky,
      error = plt.heart_red,
      warning = plt.flannel_red,
      info = plt.martha_blue,
      hint = plt.martha_gold,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_gold,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_cream,
      white = plt.term_cream,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_gold_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_cream,
      white_bright = "#ffffff",
      indexed1 = plt.martha_blue,
      indexed2 = plt.flannel_red,
    },

    treesitter = {
      ["@comment"] = plt.ma_white,
      ["@comment.documentation"] = plt.farmhouse_white,
      ["@comment.error"] = plt.heart_red,
      ["@comment.warning"] = plt.flannel_red,
      ["@comment.todo"] = plt.sunrise_red,
      ["@comment.note"] = plt.kansas_sky,

      ["@constant"] = plt.wheat_gold,
      ["@constant.builtin"] = plt.wheat_gold,
      ["@constant.macro"] = plt.sunrise_red,

      ["@string"] = plt.wheat_gold,
      ["@string.documentation"] = plt.wheat_gold,
      ["@string.regex"] = plt.kansas_sky,
      ["@string.escape"] = plt.denim_blue,
      ["@string.special"] = plt.flannel_red,
      ["@string.special.symbol"] = plt.cream_white,
      ["@string.special.url"] = plt.martha_gold,
      ["@string.special.path"] = plt.wheat_gold,

      ["@character"] = plt.wheat_gold,
      ["@character.special"] = plt.denim_blue,

      ["@number"] = plt.sunrise_red,
      ["@number.float"] = plt.sunrise_red,

      ["@boolean"] = plt.flannel_red,

      ["@function"] = plt.martha_blue,
      ["@function.builtin"] = plt.martha_blue,
      ["@function.call"] = plt.martha_blue,
      ["@function.macro"] = plt.martha_gold,
      ["@function.method"] = plt.martha_gold,
      ["@function.method.call"] = plt.martha_gold,

      ["@constructor"] = plt.cream_white,

      ["@parameter"] = plt.ma_white,
      ["@parameter.builtin"] = plt.cream_white,

      ["@keyword"] = plt.martha_blue,
      ["@keyword.coroutine"] = plt.flannel_red,
      ["@keyword.function"] = plt.martha_blue,
      ["@keyword.operator"] = plt.kansas_sky,
      ["@keyword.return"] = plt.martha_blue,
      ["@keyword.import"] = plt.wheat_gold,
      ["@keyword.storage"] = plt.martha_blue,
      ["@keyword.repeat"] = plt.martha_blue,
      ["@keyword.conditional"] = plt.martha_blue,
      ["@keyword.exception"] = plt.heart_red,
      ["@keyword.directive"] = plt.flannel_red,
      ["@keyword.directive.define"] = plt.flannel_red,

      ["@conditional"] = plt.martha_blue,
      ["@conditional.ternary"] = plt.martha_blue,

      ["@repeat"] = plt.martha_blue,

      ["@label"] = plt.martha_gold,

      ["@operator"] = plt.kansas_sky,

      ["@exception"] = plt.heart_red,

      ["@variable"] = plt.cream_white,
      ["@variable.builtin"] = plt.wheat_gold,
      ["@variable.parameter"] = plt.ma_white,
      ["@variable.member"] = plt.cream_white,

      ["@type"] = plt.martha_gold,
      ["@type.builtin"] = plt.martha_gold,
      ["@type.definition"] = plt.martha_gold,
      ["@type.qualifier"] = plt.martha_blue,

      ["@attribute"] = plt.cream_white,
      ["@attribute.builtin"] = plt.martha_gold,

      ["@property"] = plt.cream_white,
      ["@field"] = plt.cream_white,
      ["@module"] = plt.cream_white,
      ["@module.builtin"] = plt.cream_white,
      ["@namespace"] = plt.cream_white,
      ["@namespace.builtin"] = plt.cream_white,

      ["@punctuation.delimiter"] = plt.cream_white,
      ["@punctuation.bracket"] = plt.denim_blue,
      ["@punctuation.special"] = plt.kansas_sky,

      ["@tag"] = plt.martha_blue,
      ["@tag.attribute"] = plt.martha_gold,
      ["@tag.delimiter"] = plt.cream_white,
      ["@tag.builtin"] = plt.martha_blue,

      ["@markup.strong"] = { fg = plt.martha_blue, bold = true },
      ["@markup.italic"] = { fg = plt.cream_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.porch_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.flannel_red, underline = true },
      ["@markup.heading"] = plt.martha_blue,
      ["@markup.heading.1"] = plt.martha_blue,
      ["@markup.heading.2"] = plt.flannel_red,
      ["@markup.heading.3"] = plt.heart_red,
      ["@markup.heading.4"] = plt.martha_gold,
      ["@markup.heading.5"] = plt.smallville_sun,
      ["@markup.heading.6"] = plt.hope_gold,
      ["@markup.quote"] = plt.ma_white,
      ["@markup.math"] = plt.kansas_sky,
      ["@markup.link"] = plt.martha_gold,
      ["@markup.link.label"] = plt.smallville_sun,
      ["@markup.link.url"] = plt.denim_blue,
      ["@markup.raw"] = plt.wheat_gold,
      ["@markup.raw.block"] = plt.wheat_gold,
      ["@markup.list"] = plt.martha_blue,
      ["@markup.list.checked"] = plt.kansas_sky,
      ["@markup.list.unchecked"] = plt.ma_white,

      ["@diff.plus"] = plt.kansas_sky,
      ["@diff.minus"] = plt.flannel_red,
      ["@diff.delta"] = plt.martha_gold,

      ["@none"] = "none",
      ["@conceal"] = plt.wheat_gold,
      ["@spell"] = plt.cream_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.cream_white,
      ["@constructor.python"] = plt.martha_blue,
      ["@constructor.javascript"] = plt.martha_blue,
      ["@constructor.typescript"] = plt.martha_blue,
      ["@namespace.rust"] = plt.cream_white,
      ["@type.qualifier.rust"] = plt.martha_blue,
      ["@constant.macro.c"] = plt.sunrise_red,
      ["@constant.macro.cpp"] = plt.sunrise_red,
      ["@namespace.go"] = plt.cream_white,
      ["@property.css"] = plt.martha_gold,
      ["@type.css"] = plt.martha_blue,
      ["@label.json"] = plt.cream_white,
      ["@field.yaml"] = plt.ma_white,
      ["@property.toml"] = plt.ma_white,
      ["@function.builtin.bash"] = plt.martha_gold,
      ["@string.regexp"] = plt.kansas_sky,
      ["@character.special.regex"] = plt.denim_blue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.martha_gold,
      ["@lsp.type.interface"] = plt.martha_gold,
      ["@lsp.type.struct"] = plt.martha_gold,
      ["@lsp.type.enum"] = plt.martha_gold,
      ["@lsp.type.enumMember"] = plt.wheat_gold,
      ["@lsp.type.property"] = plt.cream_white,
      ["@lsp.type.namespace"] = plt.cream_white,

      ["@lsp.type.macro"] = plt.sunrise_red,
      ["@lsp.type.decorator"] = plt.martha_blue,

      ["@lsp.type.builtinType"] = plt.martha_gold,
      ["@lsp.type.selfParameter"] = plt.martha_blue,
      ["@lsp.type.typeParameter"] = plt.martha_gold,

      ["@lsp.type.array"] = plt.martha_gold,
      ["@lsp.type.object"] = plt.martha_gold,
      ["@lsp.type.key"] = plt.cream_white,
      ["@lsp.type.null"] = plt.wheat_gold,
      ["@lsp.type.enumConstant"] = plt.wheat_gold,

      ["@lsp.type.event"] = plt.martha_gold,
      ["@lsp.type.regexp"] = plt.kansas_sky,
      ["@lsp.type.unresolvedReference"] = plt.flannel_red,

      ["@lsp.mod.deprecated"] = { fg = plt.porch_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.wheat_gold,
      ["@lsp.mod.async"] = plt.martha_blue,
      ["@lsp.mod.static"] = plt.martha_gold,
      ["@lsp.mod.abstract"] = plt.martha_gold,
      ["@lsp.mod.defaultLibrary"] = plt.martha_gold,
      ["@lsp.mod.documentation"] = plt.ma_white,
    },
  }
end

return {
  name = "Martha Kent – Ma Kent",
  author = "PrismPunk.nvim",
  description = "She didn’t raise a Superman. She raised a good man. Warm denim, Kansas wheat, "
    .. "barn red, and the quiet, unbreakable love that taught the world’s greatest hero how to be human.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.smallville_night,
    base02 = palette.barn_core,
    base03 = palette.porch_glow,
    base04 = palette.denim_blue,
    base05 = palette.ma_white,
    base06 = palette.farmhouse_white,
    base07 = palette.cream_white,
    base08 = palette.flannel_red,
    base09 = palette.heart_red,
    base0A = palette.martha_gold,
    base0B = palette.smallville_sun,
    base0C = palette.martha_blue,
    base0D = palette.kansas_sky,
    base0E = palette.barn_red,
    base0F = palette.wheat_gold,
  },

  palette = palette,
  get = M.get,
}
