local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0E18",
  modern_void = "#0C111C",
  clark_core = "#121824",
  fortress_glow = "#182030",
  modern_blue = "#0044CC",
  superman_blue = "#0055EE",
  hope_blue = "#0066FF",
  skyfather_blue = "#3388FF",
  modern_red = "#BB1122",
  cape_red = "#CC2233",
  house_of_el_red = "#DD3344",
  heart_red = "#FF5566",
  shield_gold = "#FFAA00",
  solar_gold = "#FFBB33",
  hope_gold = "#FFCC44",
  sunrise_gold = "#FFDD88",
  fortress_white = "#F0F4FF",
  smallville_sky = "#DDE8FF",
  lois_cream = "#CCE0FF",
  term_blue = "#0055EE",
  term_red = "#CC2233",
  term_gold = "#FFBB33",
  term_cream = "#CCE0FF",
  term_blue_bright = "#3388FF",
  term_red_bright = "#FF6677",
  term_gold_bright = "#FFDD88",

  bg_darkest = "#0A0E18",
  fg_lightest = "#F0F4FF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.superman_blue,
      insert = plt.sunrise_gold,
      visual = plt.cape_red,
      replace = plt.house_of_el_red,
      command = plt.skyfather_blue,
    },

    ui = {
      fg = plt.fortress_white,
      fg_dim = plt.smallville_sky,
      fg_dimmer = plt.lois_cream,
      fg_dark = plt.hope_blue,
      fg_reverse = plt.void_black,

      bg_m4 = plt.fortress_glow,
      bg_m3 = plt.clark_core,
      bg_m2 = plt.modern_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.modern_void,
      bg_p2 = plt.clark_core,
      bg_gutter = opts.gutter and plt.clark_core or "none",
      bg_cursorline = plt.clark_core,
      bg_cursorline_alt = plt.modern_void,
      bg_search = plt.sunrise_gold,
      bg_visual = plt.cape_red,
      bg_statusline = plt.clark_core,

      border = plt.solar_gold,
      header1 = plt.superman_blue,
      header2 = plt.cape_red,
      special = plt.shield_gold,
      nontext = plt.modern_void,
      whitespace = plt.fortress_glow,
      win_separator = plt.solar_gold,
      indent = plt.modern_void,
      indent_scope = plt.hope_blue,
      picker = plt.fortress_white,
      yank = plt.heart_red,
      mark = plt.house_of_el_red,
      scrollbar = plt.clark_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.fortress_white,
        bg_selected = plt.clark_core,
        fg_inactive = plt.lois_cream,
        bg_inactive = plt.void_black,
        fg_alternate = plt.cape_red,
        bg_alternate = plt.void_black,
        indicator = plt.solar_gold,
      },

      pmenu = {
        fg = plt.fortress_white,
        fg_sel = "none",
        fg_border = plt.clark_core,
        bg_border = plt.clark_core,
        bg = plt.clark_core,
        bg_sel = plt.modern_void,
        bg_sbar = plt.clark_core,
        bg_thumb = plt.solar_gold,
      },

      float = {
        fg = plt.fortress_white,
        bg = plt.modern_void,
        fg_border = plt.clark_core,
        bg_border = plt.modern_void,
      },
    },

    accent = {
      accent1 = plt.superman_blue,
      accent2 = plt.cape_red,
      accent3 = plt.solar_gold,
      accent4 = plt.skyfather_blue,
      accent5 = plt.house_of_el_red,
      invert = plt.clark_core,
    },

    rainbow = {
      rainbow1 = plt.superman_blue,
      rainbow2 = plt.hope_blue,
      rainbow3 = plt.skyfather_blue,
      rainbow4 = plt.cape_red,
      rainbow5 = plt.house_of_el_red,
      rainbow6 = plt.solar_gold,
      rainbow7 = plt.sunrise_gold,
    },

    syn = {
      attribute = plt.fortress_white,
      boolean = plt.house_of_el_red,
      comment = plt.lois_cream,
      constant = plt.hope_gold,
      deprecated = plt.fortress_glow,
      func = plt.superman_blue,
      identifier = plt.fortress_white,
      keyword = plt.superman_blue,
      method = plt.solar_gold,
      number = plt.house_of_el_red,
      operator = plt.skyfather_blue,
      parameter = plt.smallville_sky,
      preproc = plt.cape_red,
      punct = plt.fortress_white,
      regex = plt.skyfather_blue,
      statement = plt.superman_blue,
      string = plt.hope_gold,
      symbol = plt.fortress_white,
      type = plt.solar_gold,
      variable = plt.fortress_white,
      special = plt.sunrise_gold,
      special2 = plt.skyfather_blue,
      special3 = plt.heart_red,
    },

    vcs = { added = plt.skyfather_blue, removed = plt.cape_red, changed = plt.solar_gold },
    diff = { add = plt.skyfather_blue, change = plt.hope_blue, delete = plt.house_of_el_red, text = plt.sunrise_gold },
    diag = {
      ok = plt.skyfather_blue,
      error = plt.house_of_el_red,
      warning = plt.cape_red,
      info = plt.superman_blue,
      hint = plt.solar_gold,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_gold,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_cream,
      white = plt.term_cream,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_gold_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_cream,
      white_bright = "#ffffff",
      indexed1 = plt.superman_blue,
      indexed2 = plt.cape_red,
    },

    treesitter = {
      ["@comment"] = plt.lois_cream,
      ["@comment.documentation"] = plt.smallville_sky,
      ["@comment.error"] = plt.house_of_el_red,
      ["@comment.warning"] = plt.cape_red,
      ["@comment.todo"] = plt.heart_red,
      ["@comment.note"] = plt.skyfather_blue,

      ["@constant"] = plt.hope_gold,
      ["@constant.builtin"] = plt.hope_gold,
      ["@constant.macro"] = plt.house_of_el_red,

      ["@string"] = plt.hope_gold,
      ["@string.documentation"] = plt.hope_gold,
      ["@string.regex"] = plt.skyfather_blue,
      ["@string.escape"] = plt.hope_blue,
      ["@string.special"] = plt.cape_red,
      ["@string.special.symbol"] = plt.fortress_white,
      ["@string.special.url"] = plt.solar_gold,
      ["@string.special.path"] = plt.hope_gold,

      ["@character"] = plt.hope_gold,
      ["@character.special"] = plt.hope_blue,

      ["@number"] = plt.house_of_el_red,
      ["@number.float"] = plt.house_of_el_red,

      ["@boolean"] = plt.cape_red,

      ["@function"] = plt.superman_blue,
      ["@function.builtin"] = plt.superman_blue,
      ["@function.call"] = plt.superman_blue,
      ["@function.macro"] = plt.solar_gold,
      ["@function.method"] = plt.solar_gold,
      ["@function.method.call"] = plt.solar_gold,

      ["@constructor"] = plt.fortress_white,

      ["@parameter"] = plt.smallville_sky,
      ["@parameter.builtin"] = plt.fortress_white,

      ["@keyword"] = plt.superman_blue,
      ["@keyword.coroutine"] = plt.cape_red,
      ["@keyword.function"] = plt.superman_blue,
      ["@keyword.operator"] = plt.skyfather_blue,
      ["@keyword.return"] = plt.superman_blue,
      ["@keyword.import"] = plt.hope_gold,
      ["@keyword.storage"] = plt.superman_blue,
      ["@keyword.repeat"] = plt.superman_blue,
      ["@keyword.conditional"] = plt.superman_blue,
      ["@keyword.exception"] = plt.heart_red,
      ["@keyword.directive"] = plt.cape_red,
      ["@keyword.directive.define"] = plt.cape_red,

      ["@conditional"] = plt.superman_blue,
      ["@conditional.ternary"] = plt.superman_blue,

      ["@repeat"] = plt.superman_blue,

      ["@label"] = plt.solar_gold,

      ["@operator"] = plt.skyfather_blue,

      ["@exception"] = plt.heart_red,

      ["@variable"] = plt.fortress_white,
      ["@variable.builtin"] = plt.hope_gold,
      ["@variable.parameter"] = plt.smallville_sky,
      ["@variable.member"] = plt.fortress_white,

      ["@type"] = plt.solar_gold,
      ["@type.builtin"] = plt.solar_gold,
      ["@type.definition"] = plt.solar_gold,
      ["@type.qualifier"] = plt.superman_blue,

      ["@attribute"] = plt.fortress_white,
      ["@attribute.builtin"] = plt.solar_gold,

      ["@property"] = plt.fortress_white,
      ["@field"] = plt.fortress_white,
      ["@module"] = plt.fortress_white,
      ["@module.builtin"] = plt.fortress_white,
      ["@namespace"] = plt.fortress_white,
      ["@namespace.builtin"] = plt.fortress_white,

      ["@punctuation.delimiter"] = plt.fortress_white,
      ["@punctuation.bracket"] = plt.hope_blue,
      ["@punctuation.special"] = plt.skyfather_blue,

      ["@tag"] = plt.superman_blue,
      ["@tag.attribute"] = plt.solar_gold,
      ["@tag.delimiter"] = plt.fortress_white,
      ["@tag.builtin"] = plt.superman_blue,

      ["@markup.strong"] = { fg = plt.superman_blue, bold = true },
      ["@markup.italic"] = { fg = plt.fortress_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fortress_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cape_red, underline = true },
      ["@markup.heading"] = plt.superman_blue,
      ["@markup.heading.1"] = plt.superman_blue,
      ["@markup.heading.2"] = plt.cape_red,
      ["@markup.heading.3"] = plt.house_of_el_red,
      ["@markup.heading.4"] = plt.solar_gold,
      ["@markup.heading.5"] = plt.sunrise_gold,
      ["@markup.heading.6"] = plt.hope_gold,
      ["@markup.quote"] = plt.smallville_sky,
      ["@markup.math"] = plt.skyfather_blue,
      ["@markup.link"] = plt.solar_gold,
      ["@markup.link.label"] = plt.sunrise_gold,
      ["@markup.link.url"] = plt.hope_blue,
      ["@markup.raw"] = plt.hope_gold,
      ["@markup.raw.block"] = plt.hope_gold,
      ["@markup.list"] = plt.superman_blue,
      ["@markup.list.checked"] = plt.skyfather_blue,
      ["@markup.list.unchecked"] = plt.smallville_sky,

      ["@diff.plus"] = plt.skyfather_blue,
      ["@diff.minus"] = plt.cape_red,
      ["@diff.delta"] = plt.solar_gold,

      ["@none"] = "none",
      ["@conceal"] = plt.fortress_white,
      ["@spell"] = plt.fortress_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fortress_white,
      ["@constructor.python"] = plt.superman_blue,
      ["@constructor.javascript"] = plt.superman_blue,
      ["@constructor.typescript"] = plt.superman_blue,
      ["@namespace.rust"] = plt.fortress_white,
      ["@type.qualifier.rust"] = plt.superman_blue,
      ["@constant.macro.c"] = plt.house_of_el_red,
      ["@constant.macro.cpp"] = plt.house_of_el_red,
      ["@namespace.go"] = plt.fortress_white,
      ["@property.css"] = plt.solar_gold,
      ["@type.css"] = plt.superman_blue,
      ["@label.json"] = plt.fortress_white,
      ["@field.yaml"] = plt.smallville_sky,
      ["@property.toml"] = plt.smallville_sky,
      ["@function.builtin.bash"] = plt.solar_gold,
      ["@string.regexp"] = plt.skyfather_blue,
      ["@character.special.regex"] = plt.hope_blue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.solar_gold,
      ["@lsp.type.interface"] = plt.solar_gold,
      ["@lsp.type.struct"] = plt.solar_gold,
      ["@lsp.type.enum"] = plt.solar_gold,
      ["@lsp.type.enumMember"] = plt.hope_gold,
      ["@lsp.type.property"] = plt.fortress_white,
      ["@lsp.type.namespace"] = plt.fortress_white,

      ["@lsp.type.macro"] = plt.house_of_el_red,
      ["@lsp.type.decorator"] = plt.superman_blue,

      ["@lsp.type.builtinType"] = plt.solar_gold,
      ["@lsp.type.selfParameter"] = plt.superman_blue,
      ["@lsp.type.typeParameter"] = plt.solar_gold,

      ["@lsp.type.array"] = plt.solar_gold,
      ["@lsp.type.object"] = plt.solar_gold,
      ["@lsp.type.key"] = plt.fortress_white,
      ["@lsp.type.null"] = plt.hope_gold,
      ["@lsp.type.enumConstant"] = plt.hope_gold,

      ["@lsp.type.event"] = plt.solar_gold,
      ["@lsp.type.regexp"] = plt.skyfather_blue,
      ["@lsp.type.unresolvedReference"] = plt.cape_red,

      ["@lsp.mod.deprecated"] = { fg = plt.fortress_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.hope_gold,
      ["@lsp.mod.async"] = plt.superman_blue,
      ["@lsp.mod.static"] = plt.solar_gold,
      ["@lsp.mod.abstract"] = plt.solar_gold,
      ["@lsp.mod.defaultLibrary"] = plt.solar_gold,
      ["@lsp.mod.documentation"] = plt.smallville_sky,
    },
  }
end

return {
  name = "Superman – Modern Era",
  author = "PrismPunk.nvim",
  description = "He’s a father now. A husband. A man who comes home for dinner. Deep cinematic blue, "
    .. "warm red, and a golden shield that still means hope — just a little older, a little wiser, "
    .. "and still the greatest hero Earth has ever known.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.modern_void,
    base02 = palette.clark_core,
    base03 = palette.fortress_glow,
    base04 = palette.hope_blue,
    base05 = palette.smallville_sky,
    base06 = palette.lois_cream,
    base07 = palette.fortress_white,
    base08 = palette.cape_red,
    base09 = palette.house_of_el_red,
    base0A = palette.solar_gold,
    base0B = palette.sunrise_gold,
    base0C = palette.superman_blue,
    base0D = palette.skyfather_blue,
    base0E = palette.modern_blue,
    base0F = palette.shield_gold,
  },

  palette = palette,
  get = M.get,
}
