local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0808",
  kingdom_void = "#0C0A0C",
  exile_core = "#121014",
  judgment_glow = "#18121C",
  kingdom_blue = "#113366",
  elder_blue = "#224477",
  last_hope_blue = "#335599",
  restored_blue = "#4466AA",
  kingdom_red = "#880011",
  mourning_red = "#AA1122",
  gulag_red = "#CC2233",
  apocalypse_red = "#EE3344",
  silver_hair = "#BBCCEE",
  elder_gold = "#998877",
  kingdom_gold = "#AA9988",
  restored_gold = "#BBAA99",
  term_red = "#CC2233",
  term_blue = "#335599",
  term_silver = "#BBCCEE",
  term_red_bright = "#EE3344",
  term_blue_bright = "#5588CC",

  bg_darkest = "#0A0808",
  fg_lightest = "#5588CC",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.gulag_red,
      insert = plt.restored_blue,
      visual = plt.mourning_red,
      replace = plt.apocalypse_red,
      command = plt.elder_blue,
    },

    ui = {
      fg = plt.silver_hair,
      fg_dim = plt.kingdom_gold,
      fg_dimmer = plt.elder_gold,
      fg_dark = plt.last_hope_blue,
      fg_reverse = plt.void_black,

      bg_m4 = plt.judgment_glow,
      bg_m3 = plt.exile_core,
      bg_m2 = plt.kingdom_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.kingdom_void,
      bg_p2 = plt.exile_core,
      bg_gutter = opts.gutter and plt.exile_core or "none",
      bg_cursorline = plt.exile_core,
      bg_cursorline_alt = plt.kingdom_void,
      bg_search = plt.apocalypse_red,
      bg_visual = plt.gulag_red,
      bg_statusline = plt.exile_core,

      border = plt.silver_hair,
      header1 = plt.gulag_red,
      header2 = plt.restored_blue,
      special = plt.kingdom_gold,
      nontext = plt.kingdom_void,
      whitespace = plt.judgment_glow,
      win_separator = plt.silver_hair,
      indent = plt.kingdom_void,
      indent_scope = plt.kingdom_blue,
      picker = plt.silver_hair,
      yank = plt.apocalypse_red,
      mark = plt.mourning_red,
      scrollbar = plt.exile_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.silver_hair,
        bg_selected = plt.exile_core,
        fg_inactive = plt.elder_gold,
        bg_inactive = plt.void_black,
        fg_alternate = plt.gulag_red,
        bg_alternate = plt.void_black,
        indicator = plt.restored_blue,
      },

      pmenu = {
        fg = plt.silver_hair,
        fg_sel = "none",
        fg_border = plt.exile_core,
        bg_border = plt.exile_core,
        bg = plt.exile_core,
        bg_sel = plt.kingdom_void,
        bg_sbar = plt.exile_core,
        bg_thumb = plt.silver_hair,
      },

      float = {
        fg = plt.silver_hair,
        bg = plt.kingdom_void,
        fg_border = plt.exile_core,
        bg_border = plt.kingdom_void,
      },
    },

    accent = {
      accent1 = plt.gulag_red,
      accent2 = plt.restored_blue,
      accent3 = plt.silver_hair,
      accent4 = plt.mourning_red,
      accent5 = plt.kingdom_gold,
      invert = plt.exile_core,
    },

    rainbow = {
      rainbow1 = plt.gulag_red,
      rainbow2 = plt.mourning_red,
      rainbow3 = plt.apocalypse_red,
      rainbow4 = plt.restored_blue,
      rainbow5 = plt.last_hope_blue,
      rainbow6 = plt.elder_blue,
      rainbow7 = plt.kingdom_gold,
    },

    syn = {
      attribute = plt.silver_hair,
      boolean = plt.mourning_red,
      comment = plt.elder_gold,
      constant = plt.kingdom_gold,
      deprecated = plt.judgment_glow,
      func = plt.gulag_red,
      identifier = plt.silver_hair,
      keyword = plt.gulag_red,
      method = plt.restored_blue,
      number = plt.apocalypse_red,
      operator = plt.last_hope_blue,
      parameter = plt.elder_gold,
      preproc = plt.mourning_red,
      punct = plt.silver_hair,
      regex = plt.last_hope_blue,
      statement = plt.gulag_red,
      string = plt.kingdom_gold,
      symbol = plt.silver_hair,
      type = plt.restored_blue,
      variable = plt.silver_hair,
      special = plt.apocalypse_red,
      special2 = plt.last_hope_blue,
      special3 = plt.mourning_red,
    },

    vcs = { added = plt.last_hope_blue, removed = plt.mourning_red, changed = plt.restored_blue },
    diff = { add = plt.last_hope_blue, change = plt.kingdom_gold, delete = plt.gulag_red, text = plt.apocalypse_red },
    diag = {
      ok = plt.last_hope_blue,
      error = plt.gulag_red,
      warning = plt.mourning_red,
      info = plt.restored_blue,
      hint = plt.kingdom_gold,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_blue,
      yellow = plt.term_silver,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_silver,
      white = plt.term_silver,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_blue_bright,
      yellow_bright = plt.term_silver,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_silver,
      white_bright = "#ffffff",
      indexed1 = plt.gulag_red,
      indexed2 = plt.restored_blue,
    },

    treesitter = {
      ["@comment"] = plt.elder_gold,
      ["@comment.documentation"] = plt.kingdom_gold,
      ["@comment.error"] = plt.gulag_red,
      ["@comment.warning"] = plt.mourning_red,
      ["@comment.todo"] = plt.apocalypse_red,
      ["@comment.note"] = plt.last_hope_blue,

      ["@constant"] = plt.kingdom_gold,
      ["@constant.builtin"] = plt.kingdom_gold,
      ["@constant.macro"] = plt.apocalypse_red,

      ["@string"] = plt.kingdom_gold,
      ["@string.documentation"] = plt.kingdom_gold,
      ["@string.regex"] = plt.last_hope_blue,
      ["@string.escape"] = plt.restored_blue,
      ["@string.special"] = plt.mourning_red,
      ["@string.special.symbol"] = plt.silver_hair,
      ["@string.special.url"] = plt.restored_blue,
      ["@string.special.path"] = plt.kingdom_gold,

      ["@character"] = plt.kingdom_gold,
      ["@character.special"] = plt.restored_blue,

      ["@number"] = plt.apocalypse_red,
      ["@number.float"] = plt.apocalypse_red,

      ["@boolean"] = plt.mourning_red,

      ["@function"] = plt.gulag_red,
      ["@function.builtin"] = plt.gulag_red,
      ["@function.call"] = plt.gulag_red,
      ["@function.macro"] = plt.restored_blue,
      ["@function.method"] = plt.restored_blue,
      ["@function.method.call"] = plt.restored_blue,

      ["@constructor"] = plt.silver_hair,

      ["@parameter"] = plt.elder_gold,
      ["@parameter.builtin"] = plt.silver_hair,

      ["@keyword"] = plt.gulag_red,
      ["@keyword.coroutine"] = plt.mourning_red,
      ["@keyword.function"] = plt.gulag_red,
      ["@keyword.operator"] = plt.last_hope_blue,
      ["@keyword.return"] = plt.gulag_red,
      ["@keyword.import"] = plt.kingdom_gold,
      ["@keyword.storage"] = plt.gulag_red,
      ["@keyword.repeat"] = plt.gulag_red,
      ["@keyword.conditional"] = plt.gulag_red,
      ["@keyword.exception"] = plt.apocalypse_red,
      ["@keyword.directive"] = plt.mourning_red,
      ["@keyword.directive.define"] = plt.mourning_red,

      ["@conditional"] = plt.gulag_red,
      ["@conditional.ternary"] = plt.gulag_red,

      ["@repeat"] = plt.gulag_red,

      ["@label"] = plt.restored_blue,

      ["@operator"] = plt.last_hope_blue,

      ["@exception"] = plt.apocalypse_red,

      ["@variable"] = plt.silver_hair,
      ["@variable.builtin"] = plt.kingdom_gold,
      ["@variable.parameter"] = plt.elder_gold,
      ["@variable.member"] = plt.silver_hair,

      ["@type"] = plt.restored_blue,
      ["@type.builtin"] = plt.restored_blue,
      ["@type.definition"] = plt.restored_blue,
      ["@type.qualifier"] = plt.gulag_red,

      ["@attribute"] = plt.silver_hair,
      ["@attribute.builtin"] = plt.restored_blue,

      ["@property"] = plt.silver_hair,
      ["@field"] = plt.silver_hair,
      ["@module"] = plt.silver_hair,
      ["@module.builtin"] = plt.silver_hair,
      ["@namespace"] = plt.silver_hair,
      ["@namespace.builtin"] = plt.silver_hair,

      ["@punctuation.delimiter"] = plt.silver_hair,
      ["@punctuation.bracket"] = plt.kingdom_blue,
      ["@punctuation.special"] = plt.last_hope_blue,

      ["@tag"] = plt.gulag_red,
      ["@tag.attribute"] = plt.restored_blue,
      ["@tag.delimiter"] = plt.silver_hair,
      ["@tag.builtin"] = plt.gulag_red,

      ["@markup.strong"] = { fg = plt.gulag_red, bold = true },
      ["@markup.italic"] = { fg = plt.silver_hair, italic = true },
      ["@markup.strikethrough"] = { fg = plt.judgment_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.mourning_red, underline = true },
      ["@markup.heading"] = plt.gulag_red,
      ["@markup.heading.1"] = plt.gulag_red,
      ["@markup.heading.2"] = plt.mourning_red,
      ["@markup.heading.3"] = plt.apocalypse_red,
      ["@markup.heading.4"] = plt.restored_blue,
      ["@markup.heading.5"] = plt.last_hope_blue,
      ["@markup.heading.6"] = plt.elder_blue,
      ["@markup.quote"] = plt.elder_gold,
      ["@markup.math"] = plt.last_hope_blue,
      ["@markup.link"] = plt.restored_blue,
      ["@markup.link.label"] = plt.apocalypse_red,
      ["@markup.link.url"] = plt.kingdom_gold,
      ["@markup.raw"] = plt.kingdom_gold,
      ["@markup.raw.block"] = plt.kingdom_gold,
      ["@markup.list"] = plt.gulag_red,
      ["@markup.list.checked"] = plt.last_hope_blue,
      ["@markup.list.unchecked"] = plt.elder_gold,

      ["@diff.plus"] = plt.last_hope_blue,
      ["@diff.minus"] = plt.mourning_red,
      ["@diff.delta"] = plt.restored_blue,

      ["@none"] = "none",
      ["@conceal"] = plt.kingdom_gold,
      ["@spell"] = plt.silver_hair,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.silver_hair,
      ["@constructor.python"] = plt.gulag_red,
      ["@constructor.javascript"] = plt.gulag_red,
      ["@constructor.typescript"] = plt.gulag_red,
      ["@namespace.rust"] = plt.silver_hair,
      ["@type.qualifier.rust"] = plt.gulag_red,
      ["@constant.macro.c"] = plt.apocalypse_red,
      ["@constant.macro.cpp"] = plt.apocalypse_red,
      ["@namespace.go"] = plt.silver_hair,
      ["@property.css"] = plt.restored_blue,
      ["@type.css"] = plt.gulag_red,
      ["@label.json"] = plt.silver_hair,
      ["@field.yaml"] = plt.elder_gold,
      ["@property.toml"] = plt.elder_gold,
      ["@function.builtin.bash"] = plt.restored_blue,
      ["@string.regexp"] = plt.last_hope_blue,
      ["@character.special.regex"] = plt.restored_blue,
    },

    lsp = {
      ["@lsp.type.class"] = plt.restored_blue,
      ["@lsp.type.interface"] = plt.restored_blue,
      ["@lsp.type.struct"] = plt.restored_blue,
      ["@lsp.type.enum"] = plt.restored_blue,
      ["@lsp.type.enumMember"] = plt.kingdom_gold,
      ["@lsp.type.property"] = plt.silver_hair,
      ["@lsp.type.namespace"] = plt.silver_hair,

      ["@lsp.type.macro"] = plt.apocalypse_red,
      ["@lsp.type.decorator"] = plt.gulag_red,

      ["@lsp.type.builtinType"] = plt.restored_blue,
      ["@lsp.type.selfParameter"] = plt.gulag_red,
      ["@lsp.type.typeParameter"] = plt.restored_blue,

      ["@lsp.type.array"] = plt.restored_blue,
      ["@lsp.type.object"] = plt.restored_blue,
      ["@lsp.type.key"] = plt.silver_hair,
      ["@lsp.type.null"] = plt.kingdom_gold,
      ["@lsp.type.enumConstant"] = plt.kingdom_gold,

      ["@lsp.type.event"] = plt.restored_blue,
      ["@lsp.type.regexp"] = plt.last_hope_blue,
      ["@lsp.type.unresolvedReference"] = plt.mourning_red,

      ["@lsp.mod.deprecated"] = { fg = plt.judgment_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.kingdom_gold,
      ["@lsp.mod.async"] = plt.gulag_red,
      ["@lsp.mod.static"] = plt.restored_blue,
      ["@lsp.mod.abstract"] = plt.restored_blue,
      ["@lsp.mod.defaultLibrary"] = plt.restored_blue,
      ["@lsp.mod.documentation"] = plt.elder_gold,
    },
  }
end

return {
  name = "Superman – Kingdom Come",
  author = "PrismPunk.nvim",
  description = "He returned from exile with silver in his hair and blood on his shield. "
    .. "Older. Sadder. Stronger. The world broke him once. Never again.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.kingdom_void,
    base02 = palette.exile_core,
    base03 = palette.judgment_glow,
    base04 = palette.kingdom_blue,
    base05 = palette.elder_gold,
    base06 = palette.kingdom_gold,
    base07 = palette.silver_hair,
    base08 = palette.gulag_red,
    base09 = palette.mourning_red,
    base0A = palette.restored_blue,
    base0B = palette.last_hope_blue,
    base0C = palette.elder_blue,
    base0D = palette.apocalypse_red,
    base0E = palette.kingdom_red,
    base0F = palette.kingdom_gold,
  },

  palette = palette,
  get = M.get,
}
