local color = require("prismpunk.utils.color")

local palette = {
  earth_void = "#0A0E17",
  biosphere_black = "#0E1421",
  tectonic_depth = "#141D2E",
  mantle_core = "#1A2539",
  entity_white = "#FFFFFF",
  life_radiance = "#F5FFFA",
  biosphere_glow = "#E8FFF5",
  verdant_light = "#D8FFED",
  living_aura = "#C8FFE5",
  ocean_blue = "#88CCFF",
  forest_green = "#88FFAA",
  sky_cyan = "#88FFEE",
  sunrise_yellow = "#FFEE88",
  magma_orange = "#FFAA88",
  coral_pink = "#FF88CC",
  lifeless_red = "#FF3366",
  term_red = "#FF6699",
  term_green = "#88FFAA",
  term_blue = "#88CCFF",

  bg_darkest = "#0A0E17",
  fg_lightest = "#FFFFFF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.entity_white,
      insert = plt.life_radiance,
      visual = plt.biosphere_glow,
      replace = plt.lifeless_red,
      command = plt.verdant_light,
    },

    ui = {
      fg = plt.living_aura,
      fg_dim = plt.verdant_light,
      fg_dimmer = plt.biosphere_glow,
      fg_dark = plt.life_radiance,
      fg_reverse = plt.earth_void,

      bg_m4 = plt.mantle_core,
      bg_m3 = plt.tectonic_depth,
      bg_m2 = plt.biosphere_black,
      bg_m1 = plt.earth_void,
      bg_dim = plt.earth_void,
      bg = plt.earth_void,
      bg_p1 = plt.biosphere_black,
      bg_p2 = plt.tectonic_depth,
      bg_gutter = opts.gutter and plt.tectonic_depth or "none",
      bg_cursorline = plt.tectonic_depth,
      bg_cursorline_alt = plt.biosphere_black,
      bg_search = plt.lifeless_red,
      bg_visual = plt.biosphere_glow,
      bg_statusline = plt.tectonic_depth,

      border = plt.entity_white,
      header1 = plt.entity_white,
      header2 = plt.life_radiance,
      special = plt.verdant_light,
      nontext = plt.biosphere_black,
      whitespace = plt.mantle_core,
      win_separator = plt.entity_white,
      indent = plt.biosphere_black,
      indent_scope = plt.living_aura,
      picker = plt.lifeless_red,
      yank = plt.entity_white,
      mark = plt.verdant_light,
      scrollbar = plt.tectonic_depth,

      tabline = {
        bg = plt.earth_void,
        fg_selected = plt.entity_white,
        bg_selected = plt.tectonic_depth,
        fg_inactive = plt.verdant_light,
        bg_inactive = plt.earth_void,
        fg_alternate = plt.verdant_light,
        bg_alternate = plt.earth_void,
        indicator = plt.life_radiance,
      },

      pmenu = {
        fg = plt.living_aura,
        fg_sel = "none",
        fg_border = plt.tectonic_depth,
        bg_border = plt.tectonic_depth,
        bg = plt.tectonic_depth,
        bg_sel = plt.biosphere_black,
        bg_sbar = plt.tectonic_depth,
        bg_thumb = plt.entity_white,
      },

      float = {
        fg = plt.living_aura,
        bg = plt.biosphere_black,
        fg_border = plt.tectonic_depth,
        bg_border = plt.biosphere_black,
      },
    },

    accent = {
      accent1 = plt.entity_white,
      accent2 = plt.life_radiance,
      accent3 = plt.biosphere_glow,
      accent4 = plt.verdant_light,
      accent5 = plt.living_aura,
      invert = plt.tectonic_depth,
    },

    rainbow = {
      rainbow1 = plt.coral_pink,
      rainbow2 = plt.magma_orange,
      rainbow3 = plt.sunrise_yellow,
      rainbow4 = plt.forest_green,
      rainbow5 = plt.sky_cyan,
      rainbow6 = plt.ocean_blue,
      rainbow7 = plt.entity_white,
    },

    syn = {
      attribute = plt.living_aura,
      boolean = plt.entity_white,
      comment = plt.verdant_light,
      constant = plt.life_radiance,
      deprecated = plt.tectonic_depth,
      func = plt.biosphere_glow,
      identifier = plt.living_aura,
      keyword = plt.entity_white,
      method = plt.verdant_light,
      number = plt.life_radiance,
      operator = plt.lifeless_red,
      parameter = plt.biosphere_glow,
      preproc = plt.lifeless_red,
      punct = plt.verdant_light,
      regex = plt.living_aura,
      statement = plt.entity_white,
      string = plt.life_radiance,
      symbol = plt.living_aura,
      type = plt.life_radiance,
      variable = plt.living_aura,
      special = plt.verdant_light,
      special2 = plt.lifeless_red,
      special3 = plt.biosphere_glow,
    },

    vcs = { added = plt.forest_green, removed = plt.lifeless_red, changed = plt.sky_cyan },
    diff = { add = plt.forest_green, change = plt.sky_cyan, delete = plt.lifeless_red, text = plt.ocean_blue },
    diag = {
      ok = plt.sky_cyan,
      error = plt.lifeless_red,
      warning = plt.magma_orange,
      info = plt.ocean_blue,
      hint = plt.coral_pink,
    },

    term = {
      black = plt.earth_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.sunrise_yellow,
      blue = plt.term_blue,
      magenta = plt.coral_pink,
      cyan = plt.sky_cyan,
      white = plt.entity_white,

      black_bright = color(plt.earth_void):brighten(0.8):to_hex(),
      red_bright = color(plt.term_red):brighten(0.2):to_hex(),
      green_bright = color(plt.term_green):brighten(0.15):to_hex(),
      yellow_bright = color(plt.sunrise_yellow):brighten(0.1):to_hex(),
      blue_bright = color(plt.term_blue):brighten(0.2):to_hex(),
      magenta_bright = color(plt.coral_pink):brighten(0.15):to_hex(),
      cyan_bright = color(plt.sky_cyan):brighten(0.1):to_hex(),
      white_bright = plt.entity_white,
      indexed1 = plt.lifeless_red,
      indexed2 = plt.verdant_light,
    },

    treesitter = {
      ["@comment"] = plt.verdant_light,
      ["@comment.documentation"] = plt.biosphere_glow,
      ["@comment.error"] = plt.lifeless_red,
      ["@comment.warning"] = plt.magma_orange,
      ["@comment.todo"] = plt.sky_cyan,
      ["@comment.note"] = plt.ocean_blue,

      ["@constant"] = plt.life_radiance,
      ["@constant.builtin"] = plt.life_radiance,
      ["@constant.macro"] = plt.living_aura,

      ["@string"] = plt.life_radiance,
      ["@string.documentation"] = plt.life_radiance,
      ["@string.regex"] = plt.coral_pink,
      ["@string.escape"] = plt.lifeless_red,
      ["@string.special"] = plt.sky_cyan,
      ["@string.special.symbol"] = plt.ocean_blue,
      ["@string.special.url"] = plt.forest_green,
      ["@string.special.path"] = plt.life_radiance,

      ["@character"] = plt.life_radiance,
      ["@character.special"] = plt.lifeless_red,

      ["@number"] = plt.life_radiance,
      ["@number.float"] = plt.life_radiance,

      ["@boolean"] = plt.entity_white,

      ["@function"] = plt.biosphere_glow,
      ["@function.builtin"] = plt.biosphere_glow,
      ["@function.call"] = plt.biosphere_glow,
      ["@function.macro"] = plt.verdant_light,
      ["@function.method"] = plt.verdant_light,
      ["@function.method.call"] = plt.verdant_light,

      ["@constructor"] = plt.entity_white,

      ["@parameter"] = plt.biosphere_glow,
      ["@parameter.builtin"] = plt.living_aura,

      ["@keyword"] = plt.entity_white,
      ["@keyword.coroutine"] = plt.sky_cyan,
      ["@keyword.function"] = plt.entity_white,
      ["@keyword.operator"] = plt.lifeless_red,
      ["@keyword.return"] = plt.entity_white,
      ["@keyword.import"] = plt.ocean_blue,
      ["@keyword.storage"] = plt.entity_white,
      ["@keyword.repeat"] = plt.entity_white,
      ["@keyword.conditional"] = plt.entity_white,
      ["@keyword.exception"] = plt.lifeless_red,
      ["@keyword.directive"] = plt.coral_pink,
      ["@keyword.directive.define"] = plt.coral_pink,

      ["@conditional"] = plt.entity_white,
      ["@conditional.ternary"] = plt.entity_white,

      ["@repeat"] = plt.entity_white,

      ["@label"] = plt.sky_cyan,

      ["@operator"] = plt.lifeless_red,

      ["@exception"] = plt.lifeless_red,

      ["@variable"] = plt.living_aura,
      ["@variable.builtin"] = plt.entity_white,
      ["@variable.parameter"] = plt.biosphere_glow,
      ["@variable.member"] = plt.living_aura,

      ["@type"] = plt.life_radiance,
      ["@type.builtin"] = plt.life_radiance,
      ["@type.definition"] = plt.life_radiance,
      ["@type.qualifier"] = plt.entity_white,

      ["@attribute"] = plt.living_aura,
      ["@attribute.builtin"] = plt.verdant_light,

      ["@property"] = plt.living_aura,
      ["@field"] = plt.living_aura,
      ["@module"] = plt.living_aura,
      ["@module.builtin"] = plt.living_aura,
      ["@namespace"] = plt.living_aura,
      ["@namespace.builtin"] = plt.living_aura,

      ["@punctuation.delimiter"] = plt.verdant_light,
      ["@punctuation.bracket"] = plt.verdant_light,
      ["@punctuation.special"] = plt.lifeless_red,

      ["@tag"] = plt.entity_white,
      ["@tag.attribute"] = plt.verdant_light,
      ["@tag.delimiter"] = plt.verdant_light,
      ["@tag.builtin"] = plt.entity_white,

      ["@markup.strong"] = { fg = plt.entity_white, bold = true },
      ["@markup.italic"] = { fg = plt.living_aura, italic = true },
      ["@markup.strikethrough"] = { fg = plt.tectonic_depth, strikethrough = true },
      ["@markup.underline"] = { fg = plt.lifeless_red, underline = true },
      ["@markup.heading"] = plt.entity_white,
      ["@markup.heading.1"] = plt.entity_white,
      ["@markup.heading.2"] = plt.life_radiance,
      ["@markup.heading.3"] = plt.biosphere_glow,
      ["@markup.heading.4"] = plt.verdant_light,
      ["@markup.heading.5"] = plt.living_aura,
      ["@markup.heading.6"] = plt.forest_green,
      ["@markup.quote"] = plt.verdant_light,
      ["@markup.math"] = plt.sky_cyan,
      ["@markup.link"] = plt.ocean_blue,
      ["@markup.link.label"] = plt.coral_pink,
      ["@markup.link.url"] = plt.sunrise_yellow,
      ["@markup.raw"] = plt.life_radiance,
      ["@markup.raw.block"] = plt.life_radiance,
      ["@markup.list"] = plt.entity_white,
      ["@markup.list.checked"] = plt.forest_green,
      ["@markup.list.unchecked"] = plt.verdant_light,

      ["@diff.plus"] = plt.forest_green,
      ["@diff.minus"] = plt.lifeless_red,
      ["@diff.delta"] = plt.sky_cyan,

      ["@none"] = "none",
      ["@conceal"] = plt.sky_cyan,
      ["@spell"] = plt.living_aura,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.living_aura,
      ["@constructor.python"] = plt.entity_white,
      ["@constructor.javascript"] = plt.entity_white,
      ["@constructor.typescript"] = plt.entity_white,
      ["@namespace.rust"] = plt.living_aura,
      ["@type.qualifier.rust"] = plt.entity_white,
      ["@constant.macro.c"] = plt.living_aura,
      ["@constant.macro.cpp"] = plt.living_aura,
      ["@namespace.go"] = plt.living_aura,
      ["@property.css"] = plt.ocean_blue,
      ["@type.css"] = plt.entity_white,
      ["@label.json"] = plt.living_aura,
      ["@field.yaml"] = plt.sky_cyan,
      ["@property.toml"] = plt.sky_cyan,
      ["@function.builtin.bash"] = plt.biosphere_glow,
      ["@string.regexp"] = plt.coral_pink,
      ["@character.special.regex"] = plt.lifeless_red,
    },

    lsp = {
      ["@lsp.type.class"] = plt.life_radiance,
      ["@lsp.type.interface"] = plt.life_radiance,
      ["@lsp.type.struct"] = plt.life_radiance,
      ["@lsp.type.enum"] = plt.life_radiance,
      ["@lsp.type.enumMember"] = plt.verdant_light,
      ["@lsp.type.property"] = plt.living_aura,
      ["@lsp.type.namespace"] = plt.living_aura,

      ["@lsp.type.macro"] = plt.living_aura,
      ["@lsp.type.decorator"] = plt.entity_white,

      ["@lsp.type.builtinType"] = plt.life_radiance,
      ["@lsp.type.selfParameter"] = plt.entity_white,
      ["@lsp.type.typeParameter"] = plt.life_radiance,

      ["@lsp.type.array"] = plt.life_radiance,
      ["@lsp.type.object"] = plt.life_radiance,
      ["@lsp.type.key"] = plt.living_aura,
      ["@lsp.type.null"] = plt.life_radiance,
      ["@lsp.type.enumConstant"] = plt.verdant_light,

      ["@lsp.type.event"] = plt.life_radiance,
      ["@lsp.type.regexp"] = plt.coral_pink,
      ["@lsp.type.unresolvedReference"] = plt.lifeless_red,

      ["@lsp.mod.deprecated"] = { fg = plt.tectonic_depth, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.life_radiance,
      ["@lsp.mod.async"] = plt.entity_white,
      ["@lsp.mod.static"] = plt.verdant_light,
      ["@lsp.mod.abstract"] = plt.life_radiance,
      ["@lsp.mod.defaultLibrary"] = plt.life_radiance,
      ["@lsp.mod.documentation"] = plt.biosphere_glow,
    },
  }
end

return {
  name = "Emotional Entity – The Entity (Life / Earth)",
  author = "PrismPunk.nvim",
  description = "The ultimate White Lantern. "
    .. "The living planet Earth itself — awakened and wearing the white ring.",

  base16 = {
    base00 = palette.earth_void,
    base01 = palette.biosphere_black,
    base02 = palette.tectonic_depth,
    base03 = palette.mantle_core,
    base04 = palette.verdant_light,
    base05 = palette.biosphere_glow,
    base06 = palette.life_radiance,
    base07 = palette.entity_white,
    base08 = palette.lifeless_red,
    base09 = palette.magma_orange,
    base0A = palette.sunrise_yellow,
    base0B = palette.forest_green,
    base0C = palette.sky_cyan,
    base0D = palette.ocean_blue,
    base0E = palette.coral_pink,
    base0F = palette.living_aura,
  },

  palette = palette,
  get = M.get,
}
