return {
  source_void = "#05051A",
  genesis_depth = "#0A0A30",
  celestial_shadow = "#0F0F4D",
  eternal_core = "#141466",
  prophet_skin = "#2A3377",
  shepherd_flesh = "#3D4D99",
  inheritor_blue = "#5566CC",
  izaya_royal = "#7088FF",
  highfather_white = "#FFFFFF",
  source_light = "#EEEEFF",
  genesis_glow = "#DDDDFF",
  divine_radiance = "#CCCCFF",
  hope_dawn = "#BBBBFF",
  source_gold = "#FFDD00",
  wisdom_gold = "#FFEE22",
  eternal_truth = "#FFFF44",
  shepherd_staff = "#FFFF88",
  miracle_light = "#FFFFBB",
  source_blue = "#4488FF",
  universal_truth = "#5599FF",
  infinity_glow = "#66AAFF",
  cosmic_peace = "#88BBFF",
  heavenly_azure = "#AADDFF",
  term_red = "#FF4488",
  term_green = "#AAFF88",
  term_blue = "#4488FF",
  term_yellow = "#FFEE88",
  term_cyan = "#88BBFF",
  staff_core = "#0033CC",
  prophecy_pulse = "#0044EE",
  source_fracture = "#0055FF",
  divine_mercy = "#3377FF",
  final_light = "#5599FF",

  bg_darkest = "#05051A",
  fg_lightest = "#FFFFFF",
}

