return {
  source_void = "#0A001A",
  cosmic_depth = "#140032",
  eternity_shadow = "#1E004D",
  infinity_core = "#28006B",
  joshua_skin = "#443388",
  conduit_flesh = "#5E4AAA",
  source_violet = "#8877DD",
  takion_royal = "#A090FF",
  source_light = "#FFFFFF",
  source_glow = "#FFFFEE",
  source_flare = "#FFFFCC",
  source_radiance = "#FFFFAA",
  cosmic_cyan = "#00FFFF",
  cosmic_teal = "#00DDEE",
  cosmic_aqua = "#00BBFF",
  cosmic_blue = "#0088FF",
  cosmic_indigo = "#4466FF",
  chronos_purple = "#CC00FF",
  chronos_magenta = "#EE22FF",
  chronos_pink = "#FF44EE",
  chronos_lavender = "#FF88FF",
  creation_gold = "#FFDD00",
  destruction_red = "#FF0044",
  rebirth_orange = "#FF6600",
  equilibrium_green = "#00FF99",
  term_red = "#FF0044",
  term_green = "#00FF99",
  term_blue = "#0088FF",
  term_yellow = "#FFDD00",
  term_cyan = "#00FFFF",
  term_magenta = "#EE22FF",
  term_red_bright = "#FF4488",
  term_green_bright = "#88FFCC",
  term_yellow_bright = "#FFEE66",
  term_blue_bright = "#88BBFF",
  term_magenta_bright = "#FF88FF",
  term_cyan_bright = "#88FFFF",

  bg_darkest = "#0A001A",
  fg_lightest = "#FFFFFF",
}

