local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0A0A",
  shiva_void = "#0E0E11",
  death_core = "#121218",
  silent_glow = "#1A1822",
  obsidian_black = "#0F0F14",
  midnight_gi = "#181820",
  shadow_silk = "#22222A",
  shiva_red = "#CC1122",
  arterial_crimson = "#DD1133",
  death_strike = "#EE3344",
  fatal_pulse = "#FF5566",
  jade_dragon = "#00CC77",
  venom_jade = "#00DD88",
  lethal_emerald = "#00EE99",
  assassin_teal = "#44FFAA",
  blade_steel = "#99AABB",
  katana_silver = "#BBCCDD",
  cold_moon = "#DDEEFF",
  term_red = "#DD1133",
  term_jade = "#00DD88",
  term_steel = "#BBCCDD",
  term_crimson = "#EE3344",
  term_black = "#181820",
  term_red_bright = "#FF5566",
  term_jade_bright = "#88FFAA",
  term_steel_bright = "#FFFFFF",

  bg_darkest = "#0A0A0A",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.arterial_crimson,
      insert = plt.jade_dragon,
      visual = plt.obsidian_black,
      replace = plt.death_strike,
      command = plt.lethal_emerald,
    },

    ui = {
      fg = plt.katana_silver,
      fg_dim = plt.blade_steel,
      fg_dimmer = plt.cold_moon,
      fg_dark = plt.shadow_silk,
      fg_reverse = plt.void_black,

      bg_m4 = plt.silent_glow,
      bg_m3 = plt.death_core,
      bg_m2 = plt.shiva_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.shiva_void,
      bg_p2 = plt.death_core,
      bg_gutter = opts.gutter and plt.death_core or "none",
      bg_cursorline = plt.death_core,
      bg_cursorline_alt = plt.shiva_void,
      bg_search = plt.fatal_pulse,
      bg_visual = plt.arterial_crimson,
      bg_statusline = plt.death_core,

      border = plt.katana_silver,
      header1 = plt.arterial_crimson,
      header2 = plt.jade_dragon,
      special = plt.lethal_emerald,
      nontext = plt.shiva_void,
      whitespace = plt.silent_glow,
      win_separator = plt.katana_silver,
      indent = plt.shiva_void,
      indent_scope = plt.midnight_gi,
      picker = plt.cold_moon,
      yank = plt.death_strike,
      mark = plt.shiva_red,
      scrollbar = plt.death_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.katana_silver,
        bg_selected = plt.death_core,
        fg_inactive = plt.blade_steel,
        bg_inactive = plt.void_black,
        fg_alternate = plt.arterial_crimson,
        bg_alternate = plt.void_black,
        indicator = plt.jade_dragon,
      },

      pmenu = {
        fg = plt.katana_silver,
        fg_sel = "none",
        fg_border = plt.death_core,
        bg_border = plt.death_core,
        bg = plt.death_core,
        bg_sel = plt.shiva_void,
        bg_sbar = plt.death_core,
        bg_thumb = plt.katana_silver,
      },

      float = {
        fg = plt.katana_silver,
        bg = plt.shiva_void,
        fg_border = plt.death_core,
        bg_border = plt.shiva_void,
      },
    },

    accent = {
      accent1 = plt.arterial_crimson,
      accent2 = plt.jade_dragon,
      accent3 = plt.obsidian_black,
      accent4 = plt.lethal_emerald,
      accent5 = plt.death_strike,
      invert = plt.death_core,
    },

    rainbow = {
      rainbow1 = plt.arterial_crimson,
      rainbow2 = plt.shiva_red,
      rainbow3 = plt.death_strike,
      rainbow4 = plt.jade_dragon,
      rainbow5 = plt.venom_jade,
      rainbow6 = plt.lethal_emerald,
      rainbow7 = plt.katana_silver,
    },

    syn = {
      attribute = plt.katana_silver,
      boolean = plt.shiva_red,
      comment = plt.blade_steel,
      constant = plt.cold_moon,
      deprecated = plt.silent_glow,
      func = plt.arterial_crimson,
      identifier = plt.katana_silver,
      keyword = plt.arterial_crimson,
      method = plt.lethal_emerald,
      number = plt.death_strike,
      operator = plt.jade_dragon,
      parameter = plt.blade_steel,
      preproc = plt.shiva_red,
      punct = plt.cold_moon,
      regex = plt.venom_jade,
      statement = plt.arterial_crimson,
      string = plt.assassin_teal,
      symbol = plt.katana_silver,
      type = plt.lethal_emerald,
      variable = plt.katana_silver,
      special = plt.fatal_pulse,
      special2 = plt.jade_dragon,
      special3 = plt.shiva_red,
    },

    vcs = { added = plt.assassin_teal, removed = plt.shiva_red, changed = plt.lethal_emerald },
    diff = { add = plt.assassin_teal, change = plt.venom_jade, delete = plt.death_strike, text = plt.fatal_pulse },
    diag = {
      ok = plt.assassin_teal,
      error = plt.shiva_red,
      warning = plt.arterial_crimson,
      info = plt.lethal_emerald,
      hint = plt.jade_dragon,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_jade,
      yellow = plt.term_steel,
      blue = plt.term_steel,
      magenta = plt.term_red,
      cyan = plt.term_jade,
      white = plt.term_steel,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_jade_bright,
      yellow_bright = plt.term_steel_bright,
      blue_bright = plt.term_steel_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_jade_bright,
      white_bright = "#ffffff",
      indexed1 = plt.arterial_crimson,
      indexed2 = plt.jade_dragon,
    },

    treesitter = {
      ["@comment"] = plt.blade_steel,
      ["@comment.documentation"] = plt.cold_moon,
      ["@comment.error"] = plt.shiva_red,
      ["@comment.warning"] = plt.death_strike,
      ["@comment.todo"] = plt.arterial_crimson,
      ["@comment.note"] = plt.lethal_emerald,

      ["@constant"] = plt.cold_moon,
      ["@constant.builtin"] = plt.cold_moon,
      ["@constant.macro"] = plt.death_strike,

      ["@string"] = plt.assassin_teal,
      ["@string.documentation"] = plt.assassin_teal,
      ["@string.regex"] = plt.venom_jade,
      ["@string.escape"] = plt.jade_dragon,
      ["@string.special"] = plt.shiva_red,
      ["@string.special.symbol"] = plt.katana_silver,
      ["@string.special.url"] = plt.lethal_emerald,
      ["@string.special.path"] = plt.assassin_teal,

      ["@character"] = plt.assassin_teal,
      ["@character.special"] = plt.jade_dragon,

      ["@number"] = plt.death_strike,
      ["@number.float"] = plt.death_strike,

      ["@boolean"] = plt.shiva_red,

      ["@function"] = plt.arterial_crimson,
      ["@function.builtin"] = plt.arterial_crimson,
      ["@function.call"] = plt.arterial_crimson,
      ["@function.macro"] = plt.lethal_emerald,
      ["@function.method"] = plt.lethal_emerald,
      ["@function.method.call"] = plt.lethal_emerald,

      ["@constructor"] = plt.katana_silver,

      ["@parameter"] = plt.blade_steel,
      ["@parameter.builtin"] = plt.katana_silver,

      ["@keyword"] = plt.arterial_crimson,
      ["@keyword.coroutine"] = plt.shiva_red,
      ["@keyword.function"] = plt.arterial_crimson,
      ["@keyword.operator"] = plt.jade_dragon,
      ["@keyword.return"] = plt.arterial_crimson,
      ["@keyword.import"] = plt.assassin_teal,
      ["@keyword.storage"] = plt.arterial_crimson,
      ["@keyword.repeat"] = plt.arterial_crimson,
      ["@keyword.conditional"] = plt.arterial_crimson,
      ["@keyword.exception"] = plt.fatal_pulse,
      ["@keyword.directive"] = plt.shiva_red,
      ["@keyword.directive.define"] = plt.shiva_red,

      ["@conditional"] = plt.arterial_crimson,
      ["@conditional.ternary"] = plt.arterial_crimson,

      ["@repeat"] = plt.arterial_crimson,

      ["@label"] = plt.lethal_emerald,

      ["@operator"] = plt.jade_dragon,

      ["@exception"] = plt.fatal_pulse,

      ["@variable"] = plt.katana_silver,
      ["@variable.builtin"] = plt.cold_moon,
      ["@variable.parameter"] = plt.blade_steel,
      ["@variable.member"] = plt.katana_silver,

      ["@type"] = plt.lethal_emerald,
      ["@type.builtin"] = plt.lethal_emerald,
      ["@type.definition"] = plt.lethal_emerald,
      ["@type.qualifier"] = plt.arterial_crimson,

      ["@attribute"] = plt.katana_silver,
      ["@attribute.builtin"] = plt.lethal_emerald,

      ["@property"] = plt.katana_silver,
      ["@field"] = plt.katana_silver,
      ["@module"] = plt.katana_silver,
      ["@module.builtin"] = plt.katana_silver,
      ["@namespace"] = plt.katana_silver,
      ["@namespace.builtin"] = plt.katana_silver,

      ["@punctuation.delecimeter"] = plt.cold_moon,
      ["@punctuation.bracket"] = plt.shadow_silk,
      ["@punctuation.special"] = plt.jade_dragon,

      ["@tag"] = plt.arterial_crimson,
      ["@tag.attribute"] = plt.lethal_emerald,
      ["@tag.delimiter"] = plt.cold_moon,
      ["@tag.builtin"] = plt.arterial_crimson,

      ["@markup.strong"] = { fg = plt.arterial_crimson, bold = true },
      ["@markup.italic"] = { fg = plt.katana_silver, italic = true },
      ["@markup.strikethrough"] = { fg = plt.silent_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.shiva_red, underline = true },
      ["@markup.heading"] = plt.arterial_crimson,
      ["@markup.heading.1"] = plt.arterial_crimson,
      ["@markup.heading.2"] = plt.shiva_red,
      ["@markup.heading.3"] = plt.death_strike,
      ["@markup.heading.4"] = plt.jade_dragon,
      ["@markup.heading.5"] = plt.lethal_emerald,
      ["@markup.heading.6"] = plt.venom_jade,
      ["@markup.quote"] = plt.blade_steel,
      ["@markup.math"] = plt.assassin_teal,
      ["@markup.link"] = plt.jade_dragon,
      ["@markup.link.label"] = plt.fatal_pulse,
      ["@markup.link.url"] = plt.lethal_emerald,
      ["@markup.raw"] = plt.assassin_teal,
      ["@markup.raw.block"] = plt.assassin_teal,
      ["@markup.list"] = plt.arterial_crimson,
      ["@markup.list.checked"] = plt.assassin_teal,
      ["@markup.list.unchecked"] = plt.blade_steel,

      ["@diff.plus"] = plt.assassin_teal,
      ["@diff.minus"] = plt.shiva_red,
      ["@diff.delta"] = plt.lethal_emerald,

      ["@none"] = "none",
      ["@conceal"] = plt.cold_moon,
      ["@spell"] = plt.katana_silver,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.katana_silver,
      ["@constructor.python"] = plt.arterial_crimson,
      ["@constructor.javascript"] = plt.arterial_crimson,
      ["@constructor.typescript"] = plt.arterial_crimson,
      ["@namespace.rust"] = plt.katana_silver,
      ["@type.qualifier.rust"] = plt.arterial_crimson,
      ["@constant.macro.c"] = plt.death_strike,
      ["@constant.macro.cpp"] = plt.death_strike,
      ["@namespace.go"] = plt.katana_silver,
      ["@property.css"] = plt.lethal_emerald,
      ["@type.css"] = plt.arterial_crimson,
      ["@label.json"] = plt.katana_silver,
      ["@field.yaml"] = plt.blade_steel,
      ["@property.toml"] = plt.blade_steel,
      ["@function.builtin.bash"] = plt.lethal_emerald,
      ["@string.regexp"] = plt.venom_jade,
      ["@character.special.regex"] = plt.jade_dragon,
    },

    lsp = {
      ["@lsp.type.class"] = plt.lethal_emerald,
      ["@lsp.type.interface"] = plt.lethal_emerald,
      ["@lsp.type.struct"] = plt.lethal_emerald,
      ["@lsp.type.enum"] = plt.lethal_emerald,
      ["@lsp.type.enumMember"] = plt.cold_moon,
      ["@lsp.type.property"] = plt.katana_silver,
      ["@lsp.type.namespace"] = plt.katana_silver,

      ["@lsp.type.macro"] = plt.death_strike,
      ["@lsp.type.decorator"] = plt.arterial_crimson,

      ["@lsp.type.builtinType"] = plt.lethal_emerald,
      ["@lsp.type.selfParameter"] = plt.arterial_crimson,
      ["@lsp.type.typeParameter"] = plt.lethal_emerald,

      ["@lsp.type.array"] = plt.lethal_emerald,
      ["@lsp.type.object"] = plt.lethal_emerald,
      ["@lsp.type.key"] = plt.katana_silver,
      ["@lsp.type.null"] = plt.cold_moon,
      ["@lsp.type.enumConstant"] = plt.cold_moon,

      ["@lsp.type.event"] = plt.lethal_emerald,
      ["@lsp.type.regexp"] = plt.venom_jade,
      ["@lsp.type.unresolvedReference"] = plt.shiva_red,

      ["@lsp.mod.deprecated"] = { fg = plt.silent_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.cold_moon,
      ["@lsp.mod.async"] = plt.arterial_crimson,
      ["@lsp.mod.static"] = plt.lethal_emerald,
      ["@lsp.mod.abstract"] = plt.lethal_emerald,
      ["@lsp.mod.defaultLibrary"] = plt.lethal_emerald,
      ["@lsp.mod.documentation"] = plt.blade_steel,
    },
  }
end

return {
  name = "Lady Shiva – Goddess of Death",
  author = "PrismPunk.nvim",
  description = "She needs no sword. She needs no gun. Every finger is a killing strike. "
    .. "Black gi. Crimson blood. Jade venom. The perfect predator.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.shiva_void,
    base02 = palette.death_core,
    base03 = palette.silent_glow,
    base04 = palette.shadow_silk,
    base05 = palette.blade_steel,
    base06 = palette.katana_silver,
    base07 = palette.cold_moon,
    base08 = palette.shiva_red,
    base09 = palette.arterial_crimson,
    base0A = palette.jade_dragon,
    base0B = palette.lethal_emerald,
    base0C = palette.assassin_teal,
    base0D = palette.venom_jade,
    base0E = palette.death_strike,
    base0F = palette.fatal_pulse,
  },

  palette = palette,
  get = M.get,
}
