local color = require("prismpunk.utils.color")

local palette = {
  life_void = "#0F1117",
  creation_black = "#171925",
  genesis_depth = "#222533",
  origin_core = "#2D3344",
  relic_white = "#FFFFFF",
  divine_radiance = "#F0F4FF",
  eternal_brill = "#E0E8FF",
  pure_lumen = "#D0DCFF",
  holy_glow = "#C0D0FF",
  prism_violet = "#E0D0FF",
  prism_indigo = "#D0DCFF",
  prism_blue = "#C0E8FF",
  prism_cyan = "#C0F0FF",
  prism_green = "#C8FFD8",
  prism_yellow = "#FFFFC0",
  prism_orange = "#FFE8C0",
  prism_red = "#FFD0D0",
  fallen_shadow = "#FF3366",
  term_red = "#FF6699",
  term_green = "#88FFCC",
  term_blue = "#88CCFF",

  bg_darkest = "#0F1117",
  fg_lightest = "#FFFFFF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.relic_white,
      insert = plt.divine_radiance,
      visual = plt.eternal_brill,
      replace = plt.fallen_shadow,
      command = plt.pure_lumen,
    },

    ui = {
      fg = plt.holy_glow,
      fg_dim = plt.pure_lumen,
      fg_dimmer = plt.eternal_brill,
      fg_dark = plt.divine_radiance,
      fg_reverse = plt.life_void,

      bg_m4 = plt.origin_core,
      bg_m3 = plt.genesis_depth,
      bg_m2 = plt.creation_black,
      bg_m1 = plt.life_void,
      bg_dim = plt.life_void,
      bg = plt.life_void,
      bg_p1 = plt.creation_black,
      bg_p2 = plt.genesis_depth,
      bg_gutter = opts.gutter and plt.genesis_depth or "none",
      bg_cursorline = plt.genesis_depth,
      bg_cursorline_alt = plt.creation_black,
      bg_search = plt.fallen_shadow,
      bg_visual = plt.eternal_brill,
      bg_statusline = plt.genesis_depth,

      border = plt.relic_white,
      header1 = plt.relic_white,
      header2 = plt.divine_radiance,
      special = plt.pure_lumen,
      nontext = plt.creation_black,
      whitespace = plt.origin_core,
      win_separator = plt.relic_white,
      indent = plt.creation_black,
      indent_scope = plt.holy_glow,
      picker = plt.fallen_shadow,
      yank = plt.relic_white,
      mark = plt.pure_lumen,
      scrollbar = plt.genesis_depth,

      tabline = {
        bg = plt.life_void,
        fg_selected = plt.relic_white,
        bg_selected = plt.genesis_depth,
        fg_inactive = plt.pure_lumen,
        bg_inactive = plt.life_void,
        fg_alternate = plt.pure_lumen,
        bg_alternate = plt.life_void,
        indicator = plt.divine_radiance,
      },

      pmenu = {
        fg = plt.holy_glow,
        fg_sel = "none",
        fg_border = plt.genesis_depth,
        bg_border = plt.genesis_depth,
        bg = plt.genesis_depth,
        bg_sel = plt.creation_black,
        bg_sbar = plt.genesis_depth,
        bg_thumb = plt.relic_white,
      },

      float = {
        fg = plt.holy_glow,
        bg = plt.creation_black,
        fg_border = plt.genesis_depth,
        bg_border = plt.creation_black,
      },
    },

    accent = {
      accent1 = plt.relic_white,
      accent2 = plt.divine_radiance,
      accent3 = plt.eternal_brill,
      accent4 = plt.pure_lumen,
      accent5 = plt.holy_glow,
      invert = plt.genesis_depth,
    },

    rainbow = {
      rainbow1 = plt.prism_red,
      rainbow2 = plt.prism_orange,
      rainbow3 = plt.prism_yellow,
      rainbow4 = plt.prism_green,
      rainbow5 = plt.prism_cyan,
      rainbow6 = plt.prism_blue,
      rainbow7 = plt.prism_violet,
    },

    syn = {
      attribute = plt.holy_glow,
      boolean = plt.relic_white,
      comment = plt.pure_lumen,
      constant = plt.divine_radiance,
      deprecated = plt.genesis_depth,
      func = plt.eternal_brill,
      identifier = plt.holy_glow,
      keyword = plt.relic_white,
      method = plt.pure_lumen,
      number = plt.divine_radiance,
      operator = plt.fallen_shadow,
      parameter = plt.eternal_brill,
      preproc = plt.fallen_shadow,
      punct = plt.pure_lumen,
      regex = plt.holy_glow,
      statement = plt.relic_white,
      string = plt.divine_radiance,
      symbol = plt.holy_glow,
      type = plt.divine_radiance,
      variable = plt.holy_glow,
      special = plt.pure_lumen,
      special2 = plt.fallen_shadow,
      special3 = plt.eternal_brill,
    },

    vcs = { added = plt.prism_green, removed = plt.fallen_shadow, changed = plt.prism_blue },
    diff = { add = plt.prism_green, change = plt.prism_blue, delete = plt.fallen_shadow, text = plt.prism_cyan },
    diag = {
      ok = plt.prism_cyan,
      error = plt.fallen_shadow,
      warning = plt.prism_orange,
      info = plt.prism_blue,
      hint = plt.prism_violet,
    },

    term = {
      black = plt.life_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.prism_yellow,
      blue = plt.term_blue,
      magenta = plt.prism_violet,
      cyan = plt.prism_cyan,
      white = plt.relic_white,

      black_bright = color(plt.life_void):brighten(0.8):to_hex(),
      red_bright = color(plt.term_red):brighten(0.2):to_hex(),
      green_bright = color(plt.term_green):brighten(0.15):to_hex(),
      yellow_bright = "#ffffe0",
      blue_bright = color(plt.term_blue):brighten(0.2):to_hex(),
      magenta_bright = "#f0d0ff",
      cyan_bright = "#ccffff",
      white_bright = plt.relic_white,
      indexed1 = plt.fallen_shadow,
      indexed2 = plt.pure_lumen,
    },

    treesitter = {
      ["@comment"] = plt.pure_lumen,
      ["@comment.documentation"] = plt.eternal_brill,
      ["@comment.error"] = plt.fallen_shadow,
      ["@comment.warning"] = plt.prism_orange,
      ["@comment.todo"] = plt.prism_cyan,
      ["@comment.note"] = plt.prism_blue,

      ["@constant"] = plt.divine_radiance,
      ["@constant.builtin"] = plt.divine_radiance,
      ["@constant.macro"] = plt.holy_glow,

      ["@string"] = plt.divine_radiance,
      ["@string.documentation"] = plt.divine_radiance,
      ["@string.regex"] = plt.prism_violet,
      ["@string.escape"] = plt.fallen_shadow,
      ["@string.special"] = plt.prism_indigo,
      ["@string.special.symbol"] = plt.prism_blue,
      ["@string.special.url"] = plt.prism_cyan,
      ["@string.special.path"] = plt.divine_radiance,

      ["@character"] = plt.divine_radiance,
      ["@character.special"] = plt.fallen_shadow,

      ["@number"] = plt.divine_radiance,
      ["@number.float"] = plt.divine_radiance,

      ["@boolean"] = plt.relic_white,

      ["@function"] = plt.eternal_brill,
      ["@function.builtin"] = plt.eternal_brill,
      ["@function.call"] = plt.eternal_brill,
      ["@function.macro"] = plt.pure_lumen,
      ["@function.method"] = plt.pure_lumen,
      ["@function.method.call"] = plt.pure_lumen,

      ["@constructor"] = plt.relic_white,

      ["@parameter"] = plt.eternal_brill,
      ["@parameter.builtin"] = plt.holy_glow,

      ["@keyword"] = plt.relic_white,
      ["@keyword.coroutine"] = plt.prism_cyan,
      ["@keyword.function"] = plt.relic_white,
      ["@keyword.operator"] = plt.fallen_shadow,
      ["@keyword.return"] = plt.relic_white,
      ["@keyword.import"] = plt.prism_blue,
      ["@keyword.storage"] = plt.relic_white,
      ["@keyword.repeat"] = plt.relic_white,
      ["@keyword.conditional"] = plt.relic_white,
      ["@keyword.exception"] = plt.fallen_shadow,
      ["@keyword.directive"] = plt.prism_violet,
      ["@keyword.directive.define"] = plt.prism_violet,

      ["@conditional"] = plt.relic_white,
      ["@conditional.ternary"] = plt.relic_white,

      ["@repeat"] = plt.relic_white,

      ["@label"] = plt.prism_cyan,

      ["@operator"] = plt.fallen_shadow,

      ["@exception"] = plt.fallen_shadow,

      ["@variable"] = plt.holy_glow,
      ["@variable.builtin"] = plt.relic_white,
      ["@variable.parameter"] = plt.eternal_brill,
      ["@variable.member"] = plt.holy_glow,

      ["@type"] = plt.divine_radiance,
      ["@type.builtin"] = plt.divine_radiance,
      ["@type.definition"] = plt.divine_radiance,
      ["@type.qualifier"] = plt.relic_white,

      ["@attribute"] = plt.holy_glow,
      ["@attribute.builtin"] = plt.pure_lumen,

      ["@property"] = plt.holy_glow,
      ["@field"] = plt.holy_glow,
      ["@module"] = plt.holy_glow,
      ["@module.builtin"] = plt.holy_glow,
      ["@namespace"] = plt.holy_glow,
      ["@namespace.builtin"] = plt.holy_glow,

      ["@punctuation.delimiter"] = plt.pure_lumen,
      ["@punctuation.bracket"] = plt.pure_lumen,
      ["@punctuation.special"] = plt.fallen_shadow,

      ["@tag"] = plt.relic_white,
      ["@tag.attribute"] = plt.pure_lumen,
      ["@tag.delimiter"] = plt.pure_lumen,
      ["@tag.builtin"] = plt.relic_white,

      ["@markup.strong"] = { fg = plt.relic_white, bold = true },
      ["@markup.italic"] = { fg = plt.holy_glow, italic = true },
      ["@markup.strikethrough"] = { fg = plt.genesis_depth, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fallen_shadow, underline = true },
      ["@markup.heading"] = plt.relic_white,
      ["@markup.heading.1"] = plt.relic_white,
      ["@markup.heading.2"] = plt.divine_radiance,
      ["@markup.heading.3"] = plt.eternal_brill,
      ["@markup.heading.4"] = plt.pure_lumen,
      ["@markup.heading.5"] = plt.holy_glow,
      ["@markup.heading.6"] = plt.prism_red,
      ["@markup.quote"] = plt.pure_lumen,
      ["@markup.math"] = plt.prism_cyan,
      ["@markup.link"] = plt.prism_blue,
      ["@markup.link.label"] = plt.prism_indigo,
      ["@markup.link.url"] = plt.prism_violet,
      ["@markup.raw"] = plt.divine_radiance,
      ["@markup.raw.block"] = plt.divine_radiance,
      ["@markup.list"] = plt.relic_white,
      ["@markup.list.checked"] = plt.prism_green,
      ["@markup.list.unchecked"] = plt.pure_lumen,

      ["@diff.plus"] = plt.prism_green,
      ["@diff.minus"] = plt.fallen_shadow,
      ["@diff.delta"] = plt.prism_blue,

      ["@none"] = "none",
      ["@conceal"] = plt.prism_cyan,
      ["@spell"] = plt.holy_glow,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.holy_glow,
      ["@constructor.python"] = plt.relic_white,
      ["@constructor.javascript"] = plt.relic_white,
      ["@constructor.typescript"] = plt.relic_white,
      ["@namespace.rust"] = plt.holy_glow,
      ["@type.qualifier.rust"] = plt.relic_white,
      ["@constant.macro.c"] = plt.holy_glow,
      ["@constant.macro.cpp"] = plt.holy_glow,
      ["@namespace.go"] = plt.holy_glow,
      ["@property.css"] = plt.prism_blue,
      ["@type.css"] = plt.relic_white,
      ["@label.json"] = plt.holy_glow,
      ["@field.yaml"] = plt.prism_cyan,
      ["@property.toml"] = plt.prism_cyan,
      ["@function.builtin.bash"] = plt.eternal_brill,
      ["@string.regexp"] = plt.prism_violet,
      ["@character.special.regex"] = plt.fallen_shadow,
    },

    lsp = {
      ["@lsp.type.class"] = plt.divine_radiance,
      ["@lsp.type.interface"] = plt.divine_radiance,
      ["@lsp.type.struct"] = plt.divine_radiance,
      ["@lsp.type.enum"] = plt.divine_radiance,
      ["@lsp.type.enumMember"] = plt.pure_lumen,
      ["@lsp.type.property"] = plt.holy_glow,
      ["@lsp.type.namespace"] = plt.holy_glow,

      ["@lsp.type.macro"] = plt.holy_glow,
      ["@lsp.type.decorator"] = plt.relic_white,

      ["@lsp.type.builtinType"] = plt.divine_radiance,
      ["@lsp.type.selfParameter"] = plt.relic_white,
      ["@lsp.type.typeParameter"] = plt.divine_radiance,

      ["@lsp.type.array"] = plt.divine_radiance,
      ["@lsp.type.object"] = plt.divine_radiance,
      ["@lsp.type.key"] = plt.holy_glow,
      ["@lsp.type.null"] = plt.divine_radiance,
      ["@lsp.type.enumConstant"] = plt.pure_lumen,

      ["@lsp.type.event"] = plt.divine_radiance,
      ["@lsp.type.regexp"] = plt.prism_violet,
      ["@lsp.type.unresolvedReference"] = plt.fallen_shadow,

      ["@lsp.mod.deprecated"] = { fg = plt.genesis_depth, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.divine_radiance,
      ["@lsp.mod.async"] = plt.relic_white,
      ["@lsp.mod.static"] = plt.pure_lumen,
      ["@lsp.mod.abstract"] = plt.divine_radiance,
      ["@lsp.mod.defaultLibrary"] = plt.divine_radiance,
      ["@lsp.mod.documentation"] = plt.eternal_brill,
    },
  }
end

return {
  name = "Emotional Entity – Relic (Life / White Light)",
  author = "PrismPunk.nvim",
  description = "The White Entity. The first lantern. The source of all emotion, all light, all life. "
    .. "Before the spectrum was split, there was only Relic.",

  base16 = {
    base00 = palette.life_void,
    base01 = palette.creation_black,
    base02 = palette.genesis_depth,
    base03 = palette.origin_core,
    base04 = palette.pure_lumen,
    base05 = palette.eternal_brill,
    base06 = palette.divine_radiance,
    base07 = palette.relic_white,
    base08 = palette.fallen_shadow,
    base09 = palette.prism_orange,
    base0A = palette.pure_lumen,
    base0B = palette.prism_green,
    base0C = palette.prism_cyan,
    base0D = palette.prism_blue,
    base0E = palette.prism_violet,
    base0F = palette.prism_red,
  },

  palette = palette,
  get = M.get,
}
