local palette = {
  cosmicBlack = "#050608",
  voidBlack = "#0A0A0E",
  abyssBlack = "#0E0E12",
  deepShadow = "#111217",
  venomNight = "#1A1A22",
  suitSteel = "#1C2026",
  maskMetal = "#3A3F4C",
  venomTubes = "#00FF88",
  venomGlow = "#00DD99",
  venomAccent = "#00FF99",
  bloodRed = "#FF0033",
  venomRed = "#FF1A44",
  rageRed = "#FF3355",
  coldGray = "#565C64",
  stoneGray = "#ABB2BF",
  lightGray = "#C8CCD4",
  ghostWhite = "#E6E8EF",
  infoBlue = "#61AFEF",
  warningOrange = "#FF8800",

  bg_darkest = "#050608",
  fg_lightest = "#E6E8EF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.venomTubes,
      insert = plt.bloodRed,
      visual = plt.venomRed,
      replace = plt.rageRed,
      command = plt.warningOrange,
    },

    ui = {
      fg = plt.stoneGray,
      fg_dim = plt.coldGray,
      fg_dimmer = plt.lightGray,
      fg_dark = plt.maskMetal,
      fg_reverse = plt.cosmicBlack,

      bg_m4 = plt.suitSteel,
      bg_m3 = plt.deepShadow,
      bg_m2 = plt.abyssBlack,
      bg_m1 = plt.voidBlack,
      bg_dim = plt.voidBlack,
      bg = plt.cosmicBlack,
      bg_p1 = plt.venomNight,
      bg_p2 = plt.deepShadow,
      bg_gutter = opts.gutter and plt.suitSteel or "none",
      bg_cursorline = plt.suitSteel,
      bg_cursorline_alt = plt.deepShadow,
      bg_search = plt.venomGlow,
      bg_visual = plt.venomRed,
      bg_statusline = plt.suitSteel,

      border = plt.venomTubes,
      header1 = plt.bloodRed,
      header2 = plt.venomTubes,
      special = plt.infoBlue,
      nontext = plt.maskMetal,
      whitespace = plt.coldGray,
      win_separator = plt.venomTubes,
      indent = plt.maskMetal,
      indent_scope = plt.venomTubes,
      picker = plt.bloodRed,
      yank = plt.venomGlow,
      mark = plt.warningOrange,
      scrollbar = plt.suitSteel,

      tabline = {
        bg = plt.cosmicBlack,
        fg_selected = plt.venomTubes,
        bg_selected = plt.suitSteel,
        fg_inactive = plt.coldGray,
        bg_inactive = plt.cosmicBlack,
        fg_alternate = plt.bloodRed,
        bg_alternate = plt.cosmicBlack,
        indicator = plt.venomTubes,
      },

      pmenu = {
        fg = plt.ghostWhite,
        fg_sel = "none",
        fg_border = plt.venomTubes,
        bg_border = plt.cosmicBlack,
        bg = plt.cosmicBlack,
        bg_sel = plt.suitSteel,
        bg_sbar = plt.cosmicBlack,
        bg_thumb = plt.venomTubes,
      },

      float = {
        fg = plt.ghostWhite,
        bg = plt.cosmicBlack,
        fg_border = plt.venomTubes,
        bg_border = plt.cosmicBlack,
      },
    },

    accent = {
      accent1 = plt.venomTubes,
      accent2 = plt.bloodRed,
      accent3 = plt.infoBlue,
      accent4 = plt.warningOrange,
      accent5 = plt.venomRed,
      invert = plt.cosmicBlack,
    },

    rainbow = {
      rainbow1 = plt.venomTubes,
      rainbow2 = plt.bloodRed,
      rainbow3 = plt.venomRed,
      rainbow4 = plt.infoBlue,
      rainbow5 = plt.warningOrange,
      rainbow6 = plt.venomGlow,
      rainbow7 = plt.rageRed,
    },

    syn = {
      attribute = plt.warningOrange,
      boolean = plt.venomTubes,
      comment = plt.maskMetal,
      constant = plt.bloodRed,
      deprecated = { fg = plt.coldGray, strikethrough = true },
      func = plt.infoBlue,
      identifier = plt.stoneGray,
      keyword = plt.venomTubes,
      method = plt.infoBlue,
      number = plt.venomRed,
      operator = plt.venomTubes,
      parameter = plt.coldGray,
      preproc = plt.warningOrange,
      punct = plt.lightGray,
      regex = plt.venomGlow,
      statement = plt.venomTubes,
      string = plt.bloodRed,
      symbol = plt.venomTubes,
      type = plt.ghostWhite,
      variable = plt.stoneGray,
      special = plt.venomGlow,
      special2 = plt.rageRed,
      special3 = plt.venomTubes,
    },

    vcs = { added = plt.venomTubes, removed = plt.bloodRed, changed = plt.warningOrange },
    diff = { add = plt.venomTubes, change = plt.warningOrange, delete = plt.bloodRed, text = plt.infoBlue },
    diag = {
      ok = plt.venomTubes,
      error = plt.bloodRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      hint = plt.venomGlow,
    },

    term = {
      black = plt.cosmicBlack,
      red = plt.bloodRed,
      green = plt.venomTubes,
      yellow = plt.warningOrange,
      blue = plt.infoBlue,
      magenta = plt.venomRed,
      cyan = plt.venomGlow,
      white = plt.lightGray,

      black_bright = "#1c2026",
      red_bright = "#ff3366",
      green_bright = "#33ffaa",
      yellow_bright = "#ffaa33",
      blue_bright = "#88ccff",
      magenta_bright = "#ff6688",
      cyan_bright = "#33ffcc",
      white_bright = "#ffffff",
    },

    treesitter = {
      ["@comment"] = plt.maskMetal,
      ["@constant"] = plt.bloodRed,
      ["@string"] = plt.bloodRed,
      ["@number"] = plt.venomRed,
      ["@boolean"] = plt.venomTubes,
      ["@function"] = plt.infoBlue,
      ["@keyword"] = plt.venomTubes,
      ["@operator"] = plt.venomTubes,
      ["@variable"] = plt.stoneGray,
      ["@type"] = plt.ghostWhite,
      ["@property"] = plt.lightGray,
      ["@punctuation"] = plt.coldGray,
      ["@tag"] = plt.venomTubes,
      ["@markup.strong"] = { fg = plt.bloodRed, bold = true },
      ["@diff.plus"] = plt.venomTubes,
      ["@diff.minus"] = plt.bloodRed,
      ["@conceal"] = plt.venomGlow,
    },

    lsp = {
      ["@lsp.type.class"] = plt.ghostWhite,
      ["@lsp.type.property"] = plt.lightGray,
      ["@lsp.mod.deprecated"] = { fg = plt.coldGray, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.venomTubes,
    },
  }
end

return {
  name = "League of Assassins – Bane",
  author = "PrismPunk.nvim",
  description = "I am the reckoning. Venom in my veins. Gotham will break.",

  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.deepShadow,
    base03 = palette.suitSteel,
    base04 = palette.maskMetal,
    base05 = palette.coldGray,
    base06 = palette.stoneGray,
    base07 = palette.lightGray,
    base08 = palette.bloodRed,
    base09 = palette.venomRed,
    base0A = palette.warningOrange,
    base0B = palette.venomTubes,
    base0C = palette.venomGlow,
    base0D = palette.infoBlue,
    base0E = palette.venomTubes,
    base0F = palette.rageRed,
  },

  palette = palette,
  get = M.get,
}
