local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0A0A",
  blank_void = "#0D0D0F",
  erased_core = "#111116",
  null_glow = "#181820",
  tactical_black = "#0F0F12",
  ghost_suit = "#16161A",
  shadow_blank = "#1E1E24",
  blank_mask = "#FFFFFF",
  ghost_white = "#EEEEFF",
  sterile_white = "#DDDDFF",
  cold_void_white = "#CCCCCC",
  reticle_red = "#FF1122",
  target_lock = "#FF2233",
  kill_confirm = "#FF4455",
  blood_reticle = "#FF6677",
  term_red = "#FF2233",
  term_white = "#EEEEFF",
  term_gray = "#CCCCCC",
  term_red_bright = "#FF6677",
  term_white_bright = "#FFFFFF",

  bg_darkest = "#0A0A0A",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.reticle_red,
      insert = plt.blank_mask,
      visual = plt.tactical_black,
      replace = plt.kill_confirm,
      command = plt.target_lock,
    },

    ui = {
      fg = plt.ghost_white,
      fg_dim = plt.sterile_white,
      fg_dimmer = plt.cold_void_white,
      fg_dark = plt.shadow_blank,
      fg_reverse = plt.void_black,

      bg_m4 = plt.null_glow,
      bg_m3 = plt.erased_core,
      bg_m2 = plt.blank_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.blank_void,
      bg_p2 = plt.erased_core,
      bg_gutter = opts.gutter and plt.erased_core or "none",
      bg_cursorline = plt.erased_core,
      bg_cursorline_alt = plt.blank_void,
      bg_search = plt.blood_reticle,
      bg_visual = plt.target_lock,
      bg_statusline = plt.erased_core,

      border = plt.blank_mask,
      header1 = plt.reticle_red,
      header2 = plt.blank_mask,
      special = plt.kill_confirm,
      nontext = plt.blank_void,
      whitespace = plt.null_glow,
      win_separator = plt.blank_mask,
      indent = plt.blank_void,
      indent_scope = plt.ghost_suit,
      picker = plt.ghost_white,
      yank = plt.kill_confirm,
      mark = plt.target_lock,
      scrollbar = plt.erased_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.blank_mask,
        bg_selected = plt.erased_core,
        fg_inactive = plt.cold_void_white,
        bg_inactive = plt.void_black,
        fg_alternate = plt.reticle_red,
        bg_alternate = plt.void_black,
        indicator = plt.target_lock,
      },

      pmenu = {
        fg = plt.ghost_white,
        fg_sel = "none",
        fg_border = plt.erased_core,
        bg_border = plt.erased_core,
        bg = plt.erased_core,
        bg_sel = plt.blank_void,
        bg_sbar = plt.erased_core,
        bg_thumb = plt.blank_mask,
      },

      float = {
        fg = plt.ghost_white,
        bg = plt.blank_void,
        fg_border = plt.erased_core,
        bg_border = plt.blank_void,
      },
    },

    accent = {
      accent1 = plt.reticle_red,
      accent2 = plt.blank_mask,
      accent3 = plt.tactical_black,
      accent4 = plt.target_lock,
      accent5 = plt.kill_confirm,
      invert = plt.erased_core,
    },

    rainbow = {
      rainbow1 = plt.reticle_red,
      rainbow2 = plt.target_lock,
      rainbow3 = plt.kill_confirm,
      rainbow4 = plt.blood_reticle,
      rainbow5 = plt.blank_mask,
      rainbow6 = plt.ghost_white,
      rainbow7 = plt.sterile_white,
    },

    syn = {
      attribute = plt.ghost_white,
      boolean = plt.target_lock,
      comment = plt.cold_void_white,
      constant = plt.blank_mask,
      deprecated = plt.null_glow,
      func = plt.reticle_red,
      identifier = plt.ghost_white,
      keyword = plt.reticle_red,
      method = plt.kill_confirm,
      number = plt.blood_reticle,
      operator = plt.blank_mask,
      parameter = plt.cold_void_white,
      preproc = plt.target_lock,
      punct = plt.blank_mask,
      regex = plt.sterile_white,
      statement = plt.reticle_red,
      string = plt.sterile_white,
      symbol = plt.ghost_white,
      type = plt.kill_confirm,
      variable = plt.ghost_white,
      special = plt.blood_reticle,
      special2 = plt.blank_mask,
      special3 = plt.target_lock,
    },

    vcs = { added = plt.sterile_white, removed = plt.target_lock, changed = plt.kill_confirm },
    diff = { add = plt.sterile_white, change = plt.blank_mask, delete = plt.blood_reticle, text = plt.kill_confirm },
    diag = {
      ok = plt.sterile_white,
      error = plt.target_lock,
      warning = plt.reticle_red,
      info = plt.blank_mask,
      hint = plt.kill_confirm,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_white,
      yellow = plt.term_gray,
      blue = plt.term_white,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_white_bright,
      yellow_bright = plt.term_gray,
      blue_bright = plt.term_white_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white_bright,
      white_bright = "#ffffff",
      indexed1 = plt.reticle_red,
      indexed2 = plt.blank_mask,
    },

    treesitter = {
      ["@comment"] = plt.cold_void_white,
      ["@comment.documentation"] = plt.blank_mask,
      ["@comment.error"] = plt.target_lock,
      ["@comment.warning"] = plt.blood_reticle,
      ["@comment.todo"] = plt.reticle_red,
      ["@comment.note"] = plt.kill_confirm,

      ["@constant"] = plt.blank_mask,
      ["@constant.builtin"] = plt.blank_mask,
      ["@constant.macro"] = plt.blood_reticle,

      ["@string"] = plt.sterile_white,
      ["@string.documentation"] = plt.sterile_white,
      ["@string.regex"] = plt.ghost_white,
      ["@string.escape"] = plt.blank_mask,
      ["@string.special"] = plt.target_lock,
      ["@string.special.symbol"] = plt.ghost_white,
      ["@string.special.url"] = plt.kill_confirm,
      ["@string.special.path"] = plt.sterile_white,

      ["@character"] = plt.sterile_white,
      ["@character.special"] = plt.blank_mask,

      ["@number"] = plt.blood_reticle,
      ["@number.float"] = plt.blood_reticle,

      ["@boolean"] = plt.target_lock,

      ["@function"] = plt.reticle_red,
      ["@function.builtin"] = plt.reticle_red,
      ["@function.call"] = plt.reticle_red,
      ["@function.macro"] = plt.kill_confirm,
      ["@function.method"] = plt.kill_confirm,
      ["@function.method.call"] = plt.kill_confirm,

      ["@constructor"] = plt.ghost_white,

      ["@parameter"] = plt.cold_void_white,
      ["@parameter.builtin"] = plt.ghost_white,

      ["@keyword"] = plt.reticle_red,
      ["@keyword.coroutine"] = plt.target_lock,
      ["@keyword.function"] = plt.reticle_red,
      ["@keyword.operator"] = plt.blank_mask,
      ["@keyword.return"] = plt.reticle_red,
      ["@keyword.import"] = plt.sterile_white,
      ["@keyword.storage"] = plt.reticle_red,
      ["@keyword.repeat"] = plt.reticle_red,
      ["@keyword.conditional"] = plt.reticle_red,
      ["@keyword.exception"] = plt.blood_reticle,
      ["@keyword.directive"] = plt.target_lock,
      ["@keyword.directive.define"] = plt.target_lock,

      ["@conditional"] = plt.reticle_red,
      ["@conditional.ternary"] = plt.reticle_red,

      ["@repeat"] = plt.reticle_red,

      ["@label"] = plt.kill_confirm,

      ["@operator"] = plt.blank_mask,

      ["@exception"] = plt.blood_reticle,

      ["@variable"] = plt.ghost_white,
      ["@variable.builtin"] = plt.blank_mask,
      ["@variable.parameter"] = plt.cold_void_white,
      ["@variable.member"] = plt.ghost_white,

      ["@type"] = plt.kill_confirm,
      ["@type.builtin"] = plt.kill_confirm,
      ["@type.definition"] = plt.kill_confirm,
      ["@type.qualifier"] = plt.reticle_red,

      ["@attribute"] = plt.ghost_white,
      ["@attribute.builtin"] = plt.kill_confirm,

      ["@property"] = plt.ghost_white,
      ["@field"] = plt.ghost_white,
      ["@module"] = plt.ghost_white,
      ["@module.builtin"] = plt.ghost_white,
      ["@namespace"] = plt.ghost_white,
      ["@namespace.builtin"] = plt.ghost_white,

      ["@punctuation.delimiter"] = plt.blank_mask,
      ["@punctuation.bracket"] = plt.shadow_blank,
      ["@punctuation.special"] = plt.blank_mask,

      ["@tag"] = plt.reticle_red,
      ["@tag.attribute"] = plt.kill_confirm,
      ["@tag.delimiter"] = plt.blank_mask,
      ["@tag.builtin"] = plt.reticle_red,

      ["@markup.strong"] = { fg = plt.reticle_red, bold = true },
      ["@markup.italic"] = { fg = plt.ghost_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.null_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.target_lock, underline = true },
      ["@markup.heading"] = plt.reticle_red,
      ["@markup.heading.1"] = plt.reticle_red,
      ["@markup.heading.2"] = plt.target_lock,
      ["@markup.heading.3"] = plt.kill_confirm,
      ["@markup.heading.4"] = plt.blood_reticle,
      ["@markup.heading.5"] = plt.blank_mask,
      ["@markup.heading.6"] = plt.ghost_white,
      ["@markup.quote"] = plt.cold_void_white,
      ["@markup.math"] = plt.sterile_white,
      ["@markup.link"] = plt.blank_mask,
      ["@markup.link.label"] = plt.blood_reticle,
      ["@markup.link.url"] = plt.kill_confirm,
      ["@markup.raw"] = plt.sterile_white,
      ["@markup.raw.block"] = plt.sterile_white,
      ["@markup.list"] = plt.reticle_red,
      ["@markup.list.checked"] = plt.sterile_white,
      ["@markup.list.unchecked"] = plt.cold_void_white,

      ["@diff.plus"] = plt.sterile_white,
      ["@diff.minus"] = plt.target_lock,
      ["@diff.delta"] = plt.kill_confirm,

      ["@none"] = "none",
      ["@conceal"] = plt.blank_mask,
      ["@spell"] = plt.ghost_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.ghost_white,
      ["@constructor.python"] = plt.reticle_red,
      ["@constructor.javascript"] = plt.reticle_red,
      ["@constructor.typescript"] = plt.reticle_red,
      ["@namespace.rust"] = plt.ghost_white,
      ["@type.qualifier.rust"] = plt.reticle_red,
      ["@constant.macro.c"] = plt.blood_reticle,
      ["@constant.macro.cpp"] = plt.blood_reticle,
      ["@namespace.go"] = plt.ghost_white,
      ["@property.css"] = plt.kill_confirm,
      ["@type.css"] = plt.reticle_red,
      ["@label.json"] = plt.ghost_white,
      ["@field.yaml"] = plt.cold_void_white,
      ["@property.toml"] = plt.cold_void_white,
      ["@function.builtin.bash"] = plt.kill_confirm,
      ["@string.regexp"] = plt.sterile_white,
      ["@character.special.regex"] = plt.blank_mask,
    },

    lsp = {
      ["@lsp.type.class"] = plt.kill_confirm,
      ["@lsp.type.interface"] = plt.kill_confirm,
      ["@lsp.type.struct"] = plt.kill_confirm,
      ["@lsp.type.enum"] = plt.kill_confirm,
      ["@lsp.type.enumMember"] = plt.blank_mask,
      ["@lsp.type.property"] = plt.ghost_white,
      ["@lsp.type.namespace"] = plt.ghost_white,

      ["@lsp.type.macro"] = plt.blood_reticle,
      ["@lsp.type.decorator"] = plt.reticle_red,

      ["@lsp.type.builtinType"] = plt.kill_confirm,
      ["@lsp.type.selfParameter"] = plt.reticle_red,
      ["@lsp.type.typeParameter"] = plt.kill_confirm,

      ["@lsp.type.array"] = plt.kill_confirm,
      ["@lsp.type.object"] = plt.kill_confirm,
      ["@lsp.type.key"] = plt.ghost_white,
      ["@lsp.type.null"] = plt.blank_mask,
      ["@lsp.type.enumConstant"] = plt.blank_mask,

      ["@lsp.type.event"] = plt.kill_confirm,
      ["@lsp.type.regexp"] = plt.sterile_white,
      ["@lsp.type.unresolvedReference"] = plt.target_lock,

      ["@lsp.mod.deprecated"] = { fg = plt.null_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.blank_mask,
      ["@lsp.mod.async"] = plt.reticle_red,
      ["@lsp.mod.static"] = plt.kill_confirm,
      ["@lsp.mod.abstract"] = plt.kill_confirm,
      ["@lsp.mod.defaultLibrary"] = plt.kill_confirm,
      ["@lsp.mod.documentation"] = plt.cold_void_white,
    },
  }
end

return {
  name = "Blank – The Assassin With No Name",
  author = "PrismPunk.nvim",
  description = "He has no face. No file. No mercy. "
    .. "Just a white mask and a red dot that appears right before you stop existing.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.blank_void,
    base02 = palette.erased_core,
    base03 = palette.null_glow,
    base04 = palette.shadow_blank,
    base05 = palette.cold_void_white,
    base06 = palette.sterile_white,
    base07 = palette.blank_mask,
    base08 = palette.target_lock,
    base09 = palette.reticle_red,
    base0A = palette.kill_confirm,
    base0B = palette.blood_reticle,
    base0C = palette.ghost_white,
    base0D = palette.sterile_white,
    base0E = palette.blood_reticle,
    base0F = palette.target_lock,
  },

  palette = palette,
  get = M.get,
}
