local palette = {
  cosmicBlack = "#050608",
  voidBlack = "#0A0A0E",
  abyssShadow = "#0E0E12",
  deepNight = "#111217",
  silkBlack = "#1A1A22",
  emeraldPoison = "#00FF88",
  venomGlow = "#00DD99",
  lethalTeal = "#00DDAA",
  jadeBlade = "#00FF99",
  shadowSteel = "#3A3F4C",
  coldGray = "#565C64",
  stoneGray = "#ABB2BF",
  ghostWhite = "#C8CCD4",
  pureWhite = "#E6E8EF",
  betrayalRed = "#FF3366",
  bloodSilk = "#E06C75",
  warningAmber = "#FFAA33",
  belovedBlue = "#61AFEF",

  bg_darkest = "#050608",
  fg_lightest = "#E6E8EF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.emeraldPoison,
      insert = plt.jadeBlade,
      visual = plt.lethalTeal,
      replace = plt.betrayalRed,
      command = plt.warningAmber,
    },

    ui = {
      fg = plt.pureWhite,
      fg_dim = plt.ghostWhite,
      fg_dimmer = plt.stoneGray,
      fg_dark = plt.shadowSteel,
      fg_reverse = plt.cosmicBlack,

      bg_m4 = plt.silkBlack,
      bg_m3 = plt.deepNight,
      bg_m2 = plt.abyssShadow,
      bg_m1 = plt.voidBlack,
      bg_dim = plt.voidBlack,
      bg = plt.cosmicBlack,
      bg_p1 = plt.deepNight,
      bg_p2 = plt.silkBlack,
      bg_gutter = opts.gutter and plt.silkBlack or "none",
      bg_cursorline = plt.silkBlack,
      bg_cursorline_alt = plt.deepNight,
      bg_search = plt.venomGlow,
      bg_visual = plt.lethalTeal,
      bg_statusline = plt.silkBlack,

      border = plt.emeraldPoison,
      header1 = plt.emeraldPoison,
      header2 = plt.jadeBlade,
      special = plt.belovedBlue,
      nontext = plt.shadowSteel,
      whitespace = plt.deepNight,
      win_separator = plt.emeraldPoison,
      indent = plt.shadowSteel,
      indent_scope = plt.jadeBlade,
      picker = plt.betrayalRed,
      yank = plt.venomGlow,
      mark = plt.warningAmber,
      scrollbar = plt.silkBlack,

      tabline = {
        bg = plt.cosmicBlack,
        fg_selected = plt.emeraldPoison,
        bg_selected = plt.silkBlack,
        fg_inactive = plt.coldGray,
        bg_inactive = plt.cosmicBlack,
        fg_alternate = plt.betrayalRed,
        bg_alternate = plt.cosmicBlack,
        indicator = plt.jadeBlade,
      },

      pmenu = {
        fg = plt.pureWhite,
        fg_sel = "none",
        fg_border = plt.emeraldPoison,
        bg_border = plt.cosmicBlack,
        bg = plt.cosmicBlack,
        bg_sel = plt.silkBlack,
        bg_sbar = plt.cosmicBlack,
        bg_thumb = plt.emeraldPoison,
      },

      float = {
        fg = plt.pureWhite,
        bg = plt.cosmicBlack,
        fg_border = plt.emeraldPoison,
        bg_border = plt.cosmicBlack,
      },
    },

    accent = {
      accent1 = plt.emeraldPoison,
      accent2 = plt.jadeBlade,
      accent3 = plt.lethalTeal,
      accent4 = plt.betrayalRed,
      accent5 = plt.belovedBlue,
      invert = plt.cosmicBlack,
    },

    rainbow = {
      rainbow1 = plt.emeraldPoison,
      rainbow2 = plt.jadeBlade,
      rainbow3 = plt.lethalTeal,
      rainbow4 = plt.venomGlow,
      rainbow5 = plt.betrayalRed,
      rainbow6 = plt.warningAmber,
      rainbow7 = plt.belovedBlue,
    },

    syn = {
      attribute = plt.warningAmber,
      boolean = plt.emeraldPoison,
      comment = { fg = plt.shadowSteel, italic = true },
      constant = plt.jadeBlade,
      deprecated = { fg = plt.coldGray, strikethrough = true, italic = true },
      func = plt.belovedBlue,
      identifier = plt.stoneGray,
      keyword = plt.emeraldPoison,
      method = plt.belovedBlue,
      number = plt.lethalTeal,
      operator = plt.emeraldPoison,
      parameter = { fg = plt.ghostWhite, italic = true },
      preproc = plt.warningAmber,
      punct = plt.ghostWhite,
      regex = plt.venomGlow,
      statement = plt.emeraldPoison,
      string = { fg = plt.jadeBlade, italic = true },
      symbol = plt.lethalTeal,
      type = plt.pureWhite,
      variable = plt.stoneGray,
      special = plt.venomGlow,
      special2 = plt.betrayalRed,
      special3 = plt.emeraldPoison,

      ["@function.builtin"] = { fg = plt.belovedBlue, bold = true },
      ["@variable.builtin"] = plt.emeraldPoison,
      ["@keyword.return"] = plt.betrayalRed,
      ["@keyword.operator"] = plt.emeraldPoison,
    },

    vcs = { added = plt.emeraldPoison, removed = plt.betrayalRed, changed = plt.warningAmber },
    diff = { add = plt.emeraldPoison, change = plt.warningAmber, delete = plt.betrayalRed, text = plt.belovedBlue },
    diag = {
      ok = plt.emeraldPoison,
      error = plt.betrayalRed,
      warning = plt.warningAmber,
      info = plt.belovedBlue,
      hint = plt.venomGlow,
    },

    term = {
      black = plt.cosmicBlack,
      red = plt.betrayalRed,
      green = plt.emeraldPoison,
      yellow = plt.warningAmber,
      blue = plt.belovedBlue,
      magenta = plt.lethalTeal,
      cyan = plt.venomGlow,
      white = plt.pureWhite,

      black_bright = "#1c2026",
      red_bright = "#ff6699",
      green_bright = "#33ffbb",
      yellow_bright = "#ffcc66",
      blue_bright = "#88ccff",
      magenta_bright = "#ff88cc",
      cyan_bright = "#33ffee",
      white_bright = "#ffffff",
    },

    treesitter = {
      ["@comment"] = { fg = plt.shadowSteel, italic = true },
      ["@constant"] = plt.jadeBlade,
      ["@constant.builtin"] = plt.emeraldPoison,
      ["@string"] = { fg = plt.jadeBlade, italic = true },
      ["@string.escape"] = plt.venomGlow,
      ["@number"] = plt.lethalTeal,
      ["@boolean"] = plt.emeraldPoison,
      ["@function"] = plt.belovedBlue,
      ["@function.builtin"] = { fg = plt.belovedBlue, bold = true },
      ["@function.method"] = plt.belovedBlue,
      ["@keyword"] = plt.emeraldPoison,
      ["@keyword.return"] = plt.betrayalRed,
      ["@operator"] = plt.emeraldPoison,
      ["@variable"] = plt.stoneGray,
      ["@variable.builtin"] = plt.emeraldPoison,
      ["@type"] = plt.pureWhite,
      ["@type.builtin"] = plt.emeraldPoison,
      ["@property"] = plt.ghostWhite,
      ["@punctuation"] = plt.coldGray,
      ["@punctuation.bracket"] = plt.ghostWhite,
      ["@tag"] = plt.emeraldPoison,
      ["@tag.attribute"] = plt.jadeBlade,
      ["@markup.heading"] = plt.emeraldPoison,
      ["@markup.strong"] = { fg = plt.betrayalRed, bold = true },
      ["@markup.italic"] = { fg = plt.jadeBlade, italic = true },
      ["@diff.plus"] = plt.emeraldPoison,
      ["@diff.minus"] = plt.betrayalRed,
      ["@diff.delta"] = plt.warningAmber,
      ["@conceal"] = plt.venomGlow,
    },

    lsp = {
      ["@lsp.type.class"] = plt.pureWhite,
      ["@lsp.type.struct"] = plt.pureWhite,
      ["@lsp.type.interface"] = plt.emeraldPoison,
      ["@lsp.type.property"] = plt.ghostWhite,
      ["@lsp.type.variable"] = plt.stoneGray,
      ["@lsp.type.function"] = plt.belovedBlue,
      ["@lsp.type.keyword"] = plt.emeraldPoison,
      ["@lsp.mod.deprecated"] = { fg = plt.coldGray, strikethrough = true, italic = true },
      ["@lsp.mod.readonly"] = plt.emeraldPoison,
    },
  }
end

return {
  name = "League of Assassins – Talia al Ghul",
  author = "PrismPunk.nvim",
  description = "She loves you. She will kill you. She will cry over your corpse. "
    .. "And she will do it all in perfect emerald silence.",

  base16 = {
    base00 = palette.cosmicBlack,
    base01 = palette.voidBlack,
    base02 = palette.deepNight,
    base03 = palette.silkBlack,
    base04 = palette.shadowSteel,
    base05 = palette.coldGray,
    base06 = palette.stoneGray,
    base07 = palette.pureWhite,
    base08 = palette.betrayalRed,
    base09 = palette.lethalTeal,
    base0A = palette.warningAmber,
    base0B = palette.emeraldPoison,
    base0C = palette.venomGlow,
    base0D = palette.belovedBlue,
    base0E = palette.jadeBlade,
    base0F = palette.emeraldPoison,
  },

  palette = palette,
  get = M.get,
}
