local color = require("prismpunk.utils.color")

local palette = {
  apokolips_void = "#0B0017",
  orphan_depth = "#15002B",
  granny_shadow = "#200048",
  escape_core = "#2B0066",
  free_skin = "#443377",
  miracle_flesh = "#5D4A99",
  escape_artist = "#8866CC",
  scott_royal = "#AA88FF",
  miracle_yellow = "#FFEE00",
  suit_green = "#00FF41",
  cape_red = "#FF0033",
  yellow_supernova = "#FFFF3D",
  green_hyperglow = "#66FF88",
  red_heartfire = "#FF3366",
  mask_dazzle = "#FFFFFF",
  motherbox_turq = "#00FFFF",
  ping_ultra = "#33FFFF",
  life_equation = "#66FFFF",
  aero_discs = "#99FFFF",
  miracle_light = "#CCFFFF",
  freedom_comet = "#FF00FF",
  never_caught = "#00FFAA",
  final_flash = "#FFFF00",
  scott_smile = "#FFFF77",
  term_red = "#FF0033",
  term_green = "#00FF41",
  term_yellow = "#FFEE00",
  term_cyan = "#00FFFF",
  unbreakable_joy = "#FFAA00",
  love_wins = "#FF0066",
  super_escape = "#00FF00",
  hope_explosion = "#FFFF55",
  term_red_bright = "#FF3366",
  term_green_bright = "#66FF88",
  term_yellow_bright = "#FFFF55",
  term_blue_bright = "#88FFFF",
  term_magenta_bright = "#FF88FF",
  term_cyan_bright = "#CCFFFF",
  term_black_bright = "#331144",

  bg_darkest = "#0B0017",
  fg_lightest = "#FFFF55",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.miracle_yellow,
      insert = plt.suit_green,
      visual = plt.cape_red,
      replace = plt.yellow_supernova,
      command = plt.motherbox_turq,
    },

    ui = {
      fg = plt.mask_dazzle,
      fg_dim = plt.scott_royal,
      fg_dimmer = plt.escape_artist,
      fg_dark = plt.miracle_flesh,
      fg_reverse = plt.apokolips_void,

      bg_m4 = plt.escape_core,
      bg_m3 = plt.granny_shadow,
      bg_m2 = plt.orphan_depth,
      bg_m1 = plt.apokolips_void,
      bg_dim = plt.apokolips_void,
      bg = plt.apokolips_void,
      bg_p1 = plt.orphan_depth,
      bg_p2 = plt.granny_shadow,
      bg_gutter = opts.gutter and plt.granny_shadow or "none",
      bg_cursorline = plt.granny_shadow,
      bg_cursorline_alt = plt.orphan_depth,
      bg_search = plt.miracle_yellow,
      bg_visual = plt.cape_red,
      bg_statusline = plt.granny_shadow,

      border = plt.miracle_yellow,
      header1 = plt.miracle_yellow,
      header2 = plt.suit_green,
      special = plt.freedom_comet,
      nontext = plt.orphan_depth,
      whitespace = plt.escape_core,
      win_separator = plt.miracle_yellow,
      indent = plt.orphan_depth,
      indent_scope = plt.mask_dazzle,
      picker = plt.green_hyperglow,
      yank = plt.yellow_supernova,
      mark = plt.red_heartfire,
      scrollbar = plt.granny_shadow,

      tabline = {
        bg = plt.apokolips_void,
        fg_selected = plt.miracle_yellow,
        bg_selected = plt.granny_shadow,
        fg_inactive = plt.escape_artist,
        bg_inactive = plt.apokolips_void,
        fg_alternate = plt.suit_green,
        bg_alternate = plt.apokolips_void,
        indicator = plt.cape_red,
      },

      pmenu = {
        fg = plt.mask_dazzle,
        fg_sel = "none",
        fg_border = plt.granny_shadow,
        bg_border = plt.granny_shadow,
        bg = plt.granny_shadow,
        bg_sel = plt.orphan_depth,
        bg_sbar = plt.granny_shadow,
        bg_thumb = plt.miracle_yellow,
      },

      float = {
        fg = plt.mask_dazzle,
        bg = plt.orphan_depth,
        fg_border = plt.granny_shadow,
        bg_border = plt.orphan_depth,
      },
    },

    accent = {
      accent1 = plt.miracle_yellow,
      accent2 = plt.suit_green,
      accent3 = plt.cape_red,
      accent4 = plt.freedom_comet,
      accent5 = plt.green_hyperglow,
      invert = plt.granny_shadow,
    },

    rainbow = {
      rainbow1 = plt.miracle_yellow,
      rainbow2 = plt.suit_green,
      rainbow3 = plt.cape_red,
      rainbow4 = plt.yellow_supernova,
      rainbow5 = plt.green_hyperglow,
      rainbow6 = plt.red_heartfire,
      rainbow7 = plt.freedom_comet,
    },

    syn = {
      attribute = plt.mask_dazzle,
      boolean = plt.cape_red,
      comment = plt.escape_artist,
      constant = plt.suit_green,
      deprecated = plt.escape_core,
      func = plt.motherbox_turq,
      identifier = plt.mask_dazzle,
      keyword = plt.miracle_yellow,
      method = plt.green_hyperglow,
      number = plt.yellow_supernova,
      operator = plt.red_heartfire,
      parameter = plt.scott_royal,
      preproc = plt.red_heartfire,
      punct = plt.escape_artist,
      regex = plt.motherbox_turq,
      statement = plt.miracle_yellow,
      string = plt.suit_green,
      symbol = plt.mask_dazzle,
      type = plt.yellow_supernova,
      variable = plt.mask_dazzle,
      special = plt.motherbox_turq,
      special2 = plt.cape_red,
      special3 = plt.freedom_comet,
    },

    vcs = { added = plt.suit_green, removed = plt.cape_red, changed = plt.miracle_yellow },
    diff = { add = plt.suit_green, change = plt.motherbox_turq, delete = plt.cape_red, text = plt.yellow_supernova },
    diag = {
      ok = plt.suit_green,
      error = plt.cape_red,
      warning = plt.miracle_yellow,
      info = plt.motherbox_turq,
      hint = plt.freedom_comet,
    },

    term = {
      black = plt.apokolips_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.motherbox_turq,
      magenta = plt.freedom_comet,
      cyan = plt.motherbox_turq,
      white = plt.mask_dazzle,

      black_bright = color(plt.apokolips_void):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_magenta_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.miracle_yellow,
      indexed2 = plt.suit_green,
    },

    treesitter = {
      ["@comment"] = plt.escape_artist,
      ["@comment.documentation"] = plt.scott_royal,
      ["@comment.error"] = plt.cape_red,
      ["@comment.warning"] = plt.miracle_yellow,
      ["@comment.todo"] = plt.suit_green,
      ["@comment.note"] = plt.motherbox_turq,

      ["@constant"] = plt.suit_green,
      ["@constant.builtin"] = plt.suit_green,
      ["@constant.macro"] = plt.yellow_supernova,

      ["@string"] = plt.suit_green,
      ["@string.documentation"] = plt.suit_green,
      ["@string.regex"] = plt.motherbox_turq,
      ["@string.escape"] = plt.life_equation,
      ["@string.special"] = plt.cape_red,
      ["@string.special.symbol"] = plt.miracle_yellow,
      ["@string.special.url"] = plt.freedom_comet,
      ["@string.special.path"] = plt.suit_green,

      ["@character"] = plt.suit_green,
      ["@character.special"] = plt.life_equation,

      ["@number"] = plt.yellow_supernova,
      ["@number.float"] = plt.yellow_supernova,

      ["@boolean"] = plt.cape_red,

      ["@function"] = plt.motherbox_turq,
      ["@function.builtin"] = plt.motherbox_turq,
      ["@function.call"] = plt.motherbox_turq,
      ["@function.macro"] = plt.life_equation,
      ["@function.method"] = plt.life_equation,
      ["@function.method.call"] = plt.life_equation,

      ["@constructor"] = plt.miracle_yellow,

      ["@parameter"] = plt.scott_royal,
      ["@parameter.builtin"] = plt.mask_dazzle,

      ["@keyword"] = plt.miracle_yellow,
      ["@keyword.coroutine"] = plt.cape_red,
      ["@keyword.function"] = plt.miracle_yellow,
      ["@keyword.operator"] = plt.red_heartfire,
      ["@keyword.return"] = plt.miracle_yellow,
      ["@keyword.import"] = plt.motherbox_turq,
      ["@keyword.storage"] = plt.miracle_yellow,
      ["@keyword.repeat"] = plt.miracle_yellow,
      ["@keyword.conditional"] = plt.miracle_yellow,
      ["@keyword.exception"] = plt.cape_red,
      ["@keyword.directive"] = plt.yellow_supernova,
      ["@keyword.directive.define"] = plt.yellow_supernova,

      ["@conditional"] = plt.miracle_yellow,
      ["@conditional.ternary"] = plt.miracle_yellow,

      ["@repeat"] = plt.miracle_yellow,

      ["@label"] = plt.motherbox_turq,

      ["@operator"] = plt.red_heartfire,

      ["@exception"] = plt.cape_red,

      ["@variable"] = plt.mask_dazzle,
      ["@variable.builtin"] = plt.miracle_yellow,
      ["@variable.parameter"] = plt.scott_royal,
      ["@variable.member"] = plt.mask_dazzle,

      ["@type"] = plt.yellow_supernova,
      ["@type.builtin"] = plt.yellow_supernova,
      ["@type.definition"] = plt.yellow_supernova,
      ["@type.qualifier"] = plt.miracle_yellow,

      ["@attribute"] = plt.mask_dazzle,
      ["@attribute.builtin"] = plt.yellow_supernova,

      ["@property"] = plt.mask_dazzle,
      ["@field"] = plt.mask_dazzle,
      ["@module"] = plt.mask_dazzle,
      ["@module.builtin"] = plt.mask_dazzle,
      ["@namespace"] = plt.mask_dazzle,
      ["@namespace.builtin"] = plt.mask_dazzle,

      ["@punctuation.delimiter"] = plt.escape_artist,
      ["@punctuation.bracket"] = plt.cape_red,
      ["@punctuation.special"] = plt.red_heartfire,

      ["@tag"] = plt.miracle_yellow,
      ["@tag.attribute"] = plt.yellow_supernova,
      ["@tag.delimiter"] = plt.escape_artist,
      ["@tag.builtin"] = plt.miracle_yellow,

      ["@markup.strong"] = { fg = plt.miracle_yellow, bold = true },
      ["@markup.italic"] = { fg = plt.mask_dazzle, italic = true },
      ["@markup.strikethrough"] = { fg = plt.escape_core, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cape_red, underline = true },
      ["@markup.heading"] = plt.miracle_yellow,
      ["@markup.heading.1"] = plt.miracle_yellow,
      ["@markup.heading.2"] = plt.suit_green,
      ["@markup.heading.3"] = plt.cape_red,
      ["@markup.heading.4"] = plt.yellow_supernova,
      ["@markup.heading.5"] = plt.green_hyperglow,
      ["@markup.heading.6"] = plt.red_heartfire,
      ["@markup.quote"] = plt.escape_artist,
      ["@markup.math"] = plt.motherbox_turq,
      ["@markup.link"] = plt.life_equation,
      ["@markup.link.label"] = plt.yellow_supernova,
      ["@markup.link.url"] = plt.freedom_comet,
      ["@markup.raw"] = plt.suit_green,
      ["@markup.raw.block"] = plt.suit_green,
      ["@markup.list"] = plt.miracle_yellow,
      ["@markup.list.checked"] = plt.suit_green,
      ["@markup.list.unchecked"] = plt.escape_artist,

      ["@diff.plus"] = plt.suit_green,
      ["@diff.minus"] = plt.cape_red,
      ["@diff.delta"] = plt.motherbox_turq,

      ["@none"] = "none",
      ["@conceal"] = plt.suit_green,
      ["@spell"] = plt.mask_dazzle,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.mask_dazzle,
      ["@constructor.python"] = plt.miracle_yellow,
      ["@constructor.javascript"] = plt.miracle_yellow,
      ["@constructor.typescript"] = plt.miracle_yellow,
      ["@namespace.rust"] = plt.mask_dazzle,
      ["@type.qualifier.rust"] = plt.miracle_yellow,
      ["@constant.macro.c"] = plt.yellow_supernova,
      ["@constant.macro.cpp"] = plt.yellow_supernova,
      ["@namespace.go"] = plt.mask_dazzle,
      ["@property.css"] = plt.motherbox_turq,
      ["@type.css"] = plt.miracle_yellow,
      ["@label.json"] = plt.mask_dazzle,
      ["@field.yaml"] = plt.scott_royal,
      ["@property.toml"] = plt.scott_royal,
      ["@function.builtin.bash"] = plt.motherbox_turq,
      ["@string.regexp"] = plt.life_equation,
      ["@character.special.regex"] = plt.red_heartfire,
    },

    lsp = {
      ["@lsp.type.class"] = plt.yellow_supernova,
      ["@lsp.type.interface"] = plt.yellow_supernova,
      ["@lsp.type.struct"] = plt.yellow_supernova,
      ["@lsp.type.enum"] = plt.yellow_supernova,
      ["@lsp.type.enumMember"] = plt.suit_green,
      ["@lsp.type.property"] = plt.mask_dazzle,
      ["@lsp.type.namespace"] = plt.mask_dazzle,

      ["@lsp.type.macro"] = plt.yellow_supernova,
      ["@lsp.type.decorator"] = plt.miracle_yellow,

      ["@lsp.type.builtinType"] = plt.yellow_supernova,
      ["@lsp.type.selfParameter"] = plt.miracle_yellow,
      ["@lsp.type.typeParameter"] = plt.yellow_supernova,

      ["@lsp.type.array"] = plt.yellow_supernova,
      ["@lsp.type.object"] = plt.yellow_supernova,
      ["@lsp.type.key"] = plt.mask_dazzle,
      ["@lsp.type.null"] = plt.suit_green,
      ["@lsp.type.enumConstant"] = plt.suit_green,

      ["@lsp.type.event"] = plt.yellow_supernova,
      ["@lsp.type.regexp"] = plt.life_equation,
      ["@lsp.type.unresolvedReference"] = plt.cape_red,

      ["@lsp.mod.deprecated"] = { fg = plt.escape_core, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.suit_green,
      ["@lsp.mod.async"] = plt.miracle_yellow,
      ["@lsp.mod.static"] = plt.yellow_supernova,
      ["@lsp.mod.abstract"] = plt.yellow_supernova,
      ["@lsp.mod.defaultLibrary"] = plt.yellow_supernova,
      ["@lsp.mod.documentation"] = plt.scott_royal,
    },
  }
end

return {
  name = "New Gods – Mister Miracle",
  author = "PrismPunk.nvim",
  description = "Scott Free. Nuclear yellow. Radioactive green. Blood-red cape. "
    .. "Hot-magenta escape trail no other god will ever touch. Freedom made visible.",

  base16 = {
    base00 = palette.apokolips_void,
    base01 = palette.orphan_depth,
    base02 = palette.granny_shadow,
    base03 = palette.escape_core,
    base04 = palette.escape_artist,
    base05 = palette.scott_royal,
    base06 = palette.miracle_flesh,
    base07 = palette.mask_dazzle,
    base08 = palette.cape_red,
    base09 = palette.miracle_yellow,
    base0A = palette.suit_green,
    base0B = palette.motherbox_turq,
    base0C = palette.yellow_supernova,
    base0D = palette.green_hyperglow,
    base0E = palette.freedom_comet,
    base0F = palette.red_heartfire,
  },

  palette = palette,
  get = M.get,
}
