local color = require("prismpunk.utils.color")

local palette = {
  apokolips_void = "#0C0018",
  firepit_depth = "#18002A",
  rage_shadow = "#260044",
  war_core = "#380066",
  warrior_skin = "#552B66",
  dog_of_war = "#773388",
  astro_violet = "#AA44CC",
  orion_royal = "#CC66FF",
  darkseid_red = "#FF0033",
  rage_fire = "#FF2244",
  war_crimson = "#FF4455",
  astro_rage = "#FF6677",
  new_genesis_gold = "#FFAA00",
  honor_glow = "#FFCC22",
  astro_gold = "#FFEE44",
  victory_sun = "#FFFF66",
  motherbox_fury = "#00CCFF",
  astro_cyan = "#22DDFF",
  rage_pulse = "#44EEFF",
  term_red = "#FF0033",
  term_green = "#00FF88",
  term_blue = "#00CCFF",
  term_yellow = "#FFAA00",
  term_cyan = "#44EEFF",
  term_red_bright = "#FF3366",
  term_green_bright = "#88FFAA",
  term_yellow_bright = "#FFDD44",
  term_blue_bright = "#88EEFF",
  term_magenta_bright = "#FF88FF",
  term_cyan_bright = "#88FFFF",
  blood_trail = "#FF0011",
  battle_scar = "#CC0022",
  final_rage = "#FF4488",
  astro_explosion = "#FFFF00",
  unbreakable_will = "#FF8800",

  bg_darkest = "#0C0018",
  fg_lightest = "#88FFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.darkseid_red,
      insert = plt.new_genesis_gold,
      visual = plt.astro_violet,
      replace = plt.rage_fire,
      command = plt.motherbox_fury,
    },

    ui = {
      fg = plt.victory_sun,
      fg_dim = plt.orion_royal,
      fg_dimmer = plt.astro_violet,
      fg_dark = plt.dog_of_war,
      fg_reverse = plt.apokolips_void,

      bg_m4 = plt.war_core,
      bg_m3 = plt.rage_shadow,
      bg_m2 = plt.firepit_depth,
      bg_m1 = plt.apokolips_void,
      bg_dim = plt.apokolips_void,
      bg = plt.apokolips_void,
      bg_p1 = plt.firepit_depth,
      bg_p2 = plt.rage_shadow,
      bg_gutter = opts.gutter and plt.rage_shadow or "none",
      bg_cursorline = plt.rage_shadow,
      bg_cursorline_alt = plt.firepit_depth,
      bg_search = plt.darkseid_red,
      bg_visual = plt.astro_violet,
      bg_statusline = plt.rage_shadow,

      border = plt.darkseid_red,
      header1 = plt.darkseid_red,
      header2 = plt.new_genesis_gold,
      special = plt.astro_explosion,
      nontext = plt.firepit_depth,
      whitespace = plt.war_core,
      win_separator = plt.darkseid_red,
      indent = plt.firepit_depth,
      indent_scope = plt.victory_sun,
      picker = plt.astro_cyan,
      yank = plt.rage_fire,
      mark = plt.astro_gold,
      scrollbar = plt.rage_shadow,

      tabline = {
        bg = plt.apokolips_void,
        fg_selected = plt.darkseid_red,
        bg_selected = plt.rage_shadow,
        fg_inactive = plt.astro_violet,
        bg_inactive = plt.apokolips_void,
        fg_alternate = plt.new_genesis_gold,
        bg_alternate = plt.apokolips_void,
        indicator = plt.rage_fire,
      },

      pmenu = {
        fg = plt.victory_sun,
        fg_sel = "none",
        fg_border = plt.rage_shadow,
        bg_border = plt.rage_shadow,
        bg = plt.rage_shadow,
        bg_sel = plt.firepit_depth,
        bg_sbar = plt.rage_shadow,
        bg_thumb = plt.darkseid_red,
      },

      float = {
        fg = plt.victory_sun,
        bg = plt.firepit_depth,
        fg_border = plt.rage_shadow,
        bg_border = plt.firepit_depth,
      },
    },

    accent = {
      accent1 = plt.darkseid_red,
      accent2 = plt.new_genesis_gold,
      accent3 = plt.astro_violet,
      accent4 = plt.rage_fire,
      accent5 = plt.astro_cyan,
      invert = plt.rage_shadow,
    },

    rainbow = {
      rainbow1 = plt.darkseid_red,
      rainbow2 = plt.rage_fire,
      rainbow3 = plt.war_crimson,
      rainbow4 = plt.new_genesis_gold,
      rainbow5 = plt.astro_gold,
      rainbow6 = plt.victory_sun,
      rainbow7 = plt.astro_violet,
    },

    syn = {
      attribute = plt.victory_sun,
      boolean = plt.darkseid_red,
      comment = plt.astro_violet,
      constant = plt.new_genesis_gold,
      deprecated = plt.war_core,
      func = plt.motherbox_fury,
      identifier = plt.victory_sun,
      keyword = plt.darkseid_red,
      method = plt.astro_cyan,
      number = plt.honor_glow,
      operator = plt.rage_pulse,
      parameter = plt.orion_royal,
      preproc = plt.rage_pulse,
      punct = plt.astro_violet,
      regex = plt.motherbox_fury,
      statement = plt.darkseid_red,
      string = plt.new_genesis_gold,
      symbol = plt.victory_sun,
      type = plt.honor_glow,
      variable = plt.victory_sun,
      special = plt.motherbox_fury,
      special2 = plt.astro_cyan,
      special3 = plt.darkseid_red,
    },

    vcs = { added = plt.new_genesis_gold, removed = plt.darkseid_red, changed = plt.rage_fire },
    diff = { add = plt.new_genesis_gold, change = plt.astro_violet, delete = plt.darkseid_red, text = plt.astro_cyan },
    diag = {
      ok = plt.new_genesis_gold,
      error = plt.darkseid_red,
      warning = plt.rage_fire,
      info = plt.motherbox_fury,
      hint = plt.honor_glow,
    },

    term = {
      black = plt.apokolips_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.astro_violet,
      cyan = plt.motherbox_fury,
      white = plt.victory_sun,

      black_bright = color(plt.apokolips_void):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_magenta_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.darkseid_red,
      indexed2 = plt.new_genesis_gold,
    },

    treesitter = {
      ["@comment"] = plt.astro_violet,
      ["@comment.documentation"] = plt.orion_royal,
      ["@comment.error"] = plt.darkseid_red,
      ["@comment.warning"] = plt.rage_fire,
      ["@comment.todo"] = plt.new_genesis_gold,
      ["@comment.note"] = plt.motherbox_fury,

      ["@constant"] = plt.new_genesis_gold,
      ["@constant.builtin"] = plt.new_genesis_gold,
      ["@constant.macro"] = plt.honor_glow,

      ["@string"] = plt.new_genesis_gold,
      ["@string.documentation"] = plt.new_genesis_gold,
      ["@string.regex"] = plt.motherbox_fury,
      ["@string.escape"] = plt.rage_pulse,
      ["@string.special"] = plt.darkseid_red,
      ["@string.special.symbol"] = plt.darkseid_red,
      ["@string.special.url"] = plt.motherbox_fury,
      ["@string.special.path"] = plt.new_genesis_gold,

      ["@character"] = plt.new_genesis_gold,
      ["@character.special"] = plt.rage_pulse,

      ["@number"] = plt.honor_glow,
      ["@number.float"] = plt.honor_glow,

      ["@boolean"] = plt.darkseid_red,

      ["@function"] = plt.motherbox_fury,
      ["@function.builtin"] = plt.motherbox_fury,
      ["@function.call"] = plt.motherbox_fury,
      ["@function.macro"] = plt.rage_pulse,
      ["@function.method"] = plt.rage_pulse,
      ["@function.method.call"] = plt.rage_pulse,

      ["@constructor"] = plt.darkseid_red,

      ["@parameter"] = plt.orion_royal,
      ["@parameter.builtin"] = plt.victory_sun,

      ["@keyword"] = plt.darkseid_red,
      ["@keyword.coroutine"] = plt.darkseid_red,
      ["@keyword.function"] = plt.darkseid_red,
      ["@keyword.operator"] = plt.rage_pulse,
      ["@keyword.return"] = plt.darkseid_red,
      ["@keyword.import"] = plt.motherbox_fury,
      ["@keyword.storage"] = plt.darkseid_red,
      ["@keyword.repeat"] = plt.darkseid_red,
      ["@keyword.conditional"] = plt.darkseid_red,
      ["@keyword.exception"] = plt.rage_fire,
      ["@keyword.directive"] = plt.honor_glow,
      ["@keyword.directive.define"] = plt.honor_glow,

      ["@conditional"] = plt.darkseid_red,
      ["@conditional.ternary"] = plt.darkseid_red,

      ["@repeat"] = plt.darkseid_red,

      ["@label"] = plt.motherbox_fury,

      ["@operator"] = plt.rage_pulse,

      ["@exception"] = plt.rage_fire,

      ["@variable"] = plt.victory_sun,
      ["@variable.builtin"] = plt.darkseid_red,
      ["@variable.parameter"] = plt.orion_royal,
      ["@variable.member"] = plt.victory_sun,

      ["@type"] = plt.honor_glow,
      ["@type.builtin"] = plt.honor_glow,
      ["@type.definition"] = plt.honor_glow,
      ["@type.qualifier"] = plt.darkseid_red,

      ["@attribute"] = plt.victory_sun,
      ["@attribute.builtin"] = plt.honor_glow,

      ["@property"] = plt.victory_sun,
      ["@field"] = plt.victory_sun,
      ["@module"] = plt.victory_sun,
      ["@module.builtin"] = plt.victory_sun,
      ["@namespace"] = plt.victory_sun,
      ["@namespace.builtin"] = plt.victory_sun,

      ["@punctuation.delimiter"] = plt.astro_violet,
      ["@punctuation.bracket"] = plt.astro_violet,
      ["@punctuation.special"] = plt.rage_pulse,

      ["@tag"] = plt.darkseid_red,
      ["@tag.attribute"] = plt.honor_glow,
      ["@tag.delimiter"] = plt.astro_violet,
      ["@tag.builtin"] = plt.darkseid_red,

      ["@markup.strong"] = { fg = plt.darkseid_red, bold = true },
      ["@markup.italic"] = { fg = plt.victory_sun, italic = true },
      ["@markup.strikethrough"] = { fg = plt.war_core, strikethrough = true },
      ["@markup.underline"] = { fg = plt.new_genesis_gold, underline = true },
      ["@markup.heading"] = plt.darkseid_red,
      ["@markup.heading.1"] = plt.darkseid_red,
      ["@markup.heading.2"] = plt.new_genesis_gold,
      ["@markup.heading.3"] = plt.astro_violet,
      ["@markup.heading.4"] = plt.rage_fire,
      ["@markup.heading.5"] = plt.honor_glow,
      ["@markup.heading.6"] = plt.victory_sun,
      ["@markup.quote"] = plt.astro_violet,
      ["@markup.math"] = plt.motherbox_fury,
      ["@markup.link"] = plt.astro_cyan,
      ["@markup.link.label"] = plt.honor_glow,
      ["@markup.link.url"] = plt.new_genesis_gold,
      ["@markup.raw"] = plt.new_genesis_gold,
      ["@markup.raw.block"] = plt.new_genesis_gold,
      ["@markup.list"] = plt.darkseid_red,
      ["@markup.list.checked"] = plt.new_genesis_gold,
      ["@markup.list.unchecked"] = plt.astro_violet,

      ["@diff.plus"] = plt.new_genesis_gold,
      ["@diff.minus"] = plt.darkseid_red,
      ["@diff.delta"] = plt.astro_violet,

      ["@none"] = "none",
      ["@conceal"] = plt.new_genesis_gold,
      ["@spell"] = plt.victory_sun,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.victory_sun,
      ["@constructor.python"] = plt.darkseid_red,
      ["@constructor.javascript"] = plt.darkseid_red,
      ["@constructor.typescript"] = plt.darkseid_red,
      ["@namespace.rust"] = plt.victory_sun,
      ["@type.qualifier.rust"] = plt.darkseid_red,
      ["@constant.macro.c"] = plt.honor_glow,
      ["@constant.macro.cpp"] = plt.honor_glow,
      ["@namespace.go"] = plt.victory_sun,
      ["@property.css"] = plt.motherbox_fury,
      ["@type.css"] = plt.darkseid_red,
      ["@label.json"] = plt.victory_sun,
      ["@field.yaml"] = plt.orion_royal,
      ["@property.toml"] = plt.orion_royal,
      ["@function.builtin.bash"] = plt.motherbox_fury,
      ["@string.regexp"] = plt.rage_pulse,
      ["@character.special.regex"] = plt.rage_pulse,
    },

    lsp = {
      ["@lsp.type.class"] = plt.honor_glow,
      ["@lsp.type.interface"] = plt.honor_glow,
      ["@lsp.type.struct"] = plt.honor_glow,
      ["@lsp.type.enum"] = plt.honor_glow,
      ["@lsp.type.enumMember"] = plt.new_genesis_gold,
      ["@lsp.type.property"] = plt.victory_sun,
      ["@lsp.type.namespace"] = plt.victory_sun,

      ["@lsp.type.macro"] = plt.honor_glow,
      ["@lsp.type.decorator"] = plt.darkseid_red,

      ["@lsp.type.builtinType"] = plt.honor_glow,
      ["@lsp.type.selfParameter"] = plt.darkseid_red,
      ["@lsp.type.typeParameter"] = plt.honor_glow,

      ["@lsp.type.array"] = plt.honor_glow,
      ["@lsp.type.object"] = plt.honor_glow,
      ["@lsp.type.key"] = plt.victory_sun,
      ["@lsp.type.null"] = plt.new_genesis_gold,
      ["@lsp.type.enumConstant"] = plt.new_genesis_gold,

      ["@lsp.type.event"] = plt.honor_glow,
      ["@lsp.type.regexp"] = plt.rage_pulse,
      ["@lsp.type.unresolvedReference"] = plt.rage_fire,

      ["@lsp.mod.deprecated"] = { fg = plt.war_core, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.new_genesis_gold,
      ["@lsp.mod.async"] = plt.darkseid_red,
      ["@lsp.mod.static"] = plt.honor_glow,
      ["@lsp.mod.abstract"] = plt.honor_glow,
      ["@lsp.mod.defaultLibrary"] = plt.honor_glow,
      ["@lsp.mod.documentation"] = plt.orion_royal,
    },
  }
end

return {
  name = "New Gods – Orion",
  author = "PrismPunk.nvim",
  description = "The Dog of War. Crimson rage of Apokolips. Golden honor of New Genesis. "
    .. "Violet storm of the Astro-Force. He is fury barely contained — and victory hard-won.",

  base16 = {
    base00 = palette.apokolips_void,
    base01 = palette.firepit_depth,
    base02 = palette.rage_shadow,
    base03 = palette.war_core,
    base04 = palette.astro_violet,
    base05 = palette.orion_royal,
    base06 = palette.dog_of_war,
    base07 = palette.victory_sun,
    base08 = palette.darkseid_red,
    base09 = palette.new_genesis_gold,
    base0A = palette.rage_fire,
    base0B = palette.motherbox_fury,
    base0C = palette.astro_cyan,
    base0D = palette.honor_glow,
    base0E = palette.war_crimson,
    base0F = palette.astro_gold,
  },

  palette = palette,
  get = M.get,
}
