return {
  void_black = "#0C0814",
  tamaran_void = "#110D1F",
  star_core = "#181133",
  nova_glow = "#221A44",
  tamaran_gold = "#FF8833",
  solar_orange = "#FFAA44",
  starfire_skin = "#FFCC66",
  sunrise_glow = "#FFDD88",
  radiant_heat = "#FF6600",
  starbolt_green = "#00FF88",
  tamaran_emerald = "#00CC77",
  solar_flare = "#00EE99",
  alien_radiance = "#44FFAA",
  tamaran_purple = "#CC33FF",
  koriand_rpurple = "#DD44FF",
  royal_starfire = "#EE66FF",
  nova_purple = "#FF88FF",
  kori_violet = "#AA22FF",
  starlight_violet = "#BB44FF",
  ultraviolet_gaze = "#CC66FF",
  term_orange = "#FFAA44",
  term_green = "#00EE99",
  term_purple = "#EE66FF",
  term_violet = "#CC66FF",
  term_cyan = "#44FFCC",
  term_yellow = "#FFDD88",
  term_orange_bright = "#FFCC77",
  term_green_bright = "#88FFAA",
  term_purple_bright = "#FF99FF",
  term_violet_bright = "#EE88FF",

  bg_darkest = "#0C0814",
  fg_lightest = "#88FFAA",
}

