local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1C1C1C",
  bg_darker = "#262626",
  bg_dark = "#303030",
  bg_mid = "#3A3A3A",
  bg_light = "#444444",
  bg_lighter = "#4E4E4E",
  bg_lightest = "#585858",
  fg_lightest = "#DADADA",
  fg_light = "#C7C7C7",
  fg_mid = "#9E9E9E",
  fg_dark = "#767676",
  bg_alt1 = "#242424",
  bg_alt2 = "#181818",
  bg_alt3 = "#2C2C2C",
  bg_alt4 = "#121212",
  roseBright = "#FF87AF",
  roseCore = "#D75F87",
  roseDeep = "#AF5F5F",
  greenBright = "#87D787",
  greenCore = "#5FAF5F",
  greenDeep = "#5F875F",
  mauveBright = "#D7AFD7",
  mauveCore = "#AF87AF",
  mauveDeep = "#875F87",
  tealBright = "#87D7D7",
  tealCore = "#87AFAF",
  tealDeep = "#5F8787",
  bronzeBright = "#D7AF87",
  bronzeCore = "#AF875F",
  bronzeDeep = "#875F5F",
  blueBright = "#87AFD7",
  blueCore = "#5F87AF",
  blueDeep = "#5F5F87",
  amberBright = "#FFAF5F",
  amberCore = "#D7875F",
  amberDeep = "#AF5F5F",
  jadeBright = "#5FD75F",
  jadeCore = "#5FAF5F",
  jadeDeep = "#5F875F",
  steelGray = "#9E9E9E",
  slateGray = "#767676",
  charcoalGray = "#585858",
  shadowGray = "#444444",
  dangerRed = "#D75F5F",
  warningOrange = "#FFAF5F",
  infoBlue = "#5FAFD7",
  successGreen = "#5FD75F",
  industrialSteel = "#87AFAF",
  dustyRose = "#D75F87",
  mutedBronze = "#AF875F",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.mauveCore,
      insert = plt.greenCore,
      visual = plt.tealCore,
      replace = plt.roseCore,
      command = plt.bronzeCore,
    },
    accent = {
      accent1 = plt.mauveCore,
      accent2 = plt.tealCore,
      accent3 = plt.bronzeCore,
      accent4 = plt.roseCore,
      accent5 = plt.greenCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.mauveCore,
      rainbow2 = plt.tealCore,
      rainbow3 = plt.bronzeCore,
      rainbow4 = plt.greenCore,
      rainbow5 = plt.roseCore,
      rainbow6 = plt.blueCore,
      rainbow7 = plt.amberCore,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.bronzeCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.slateGray,
      header1 = plt.tealBright,
      header2 = plt.mauveBright,
      special = plt.tealCore,
      nontext = plt.charcoalGray,
      whitespace = plt.slateGray,
      win_separator = plt.slateGray,
      indent = plt.bg_lighter,
      indent_scope = plt.mauveCore,
      picker = plt.mauveCore,
      yank = plt.amberBright,
      mark = plt.tealBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.slateGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.slateGray,
        bg = plt.bg_mid,
        bg_sel = plt.bg_lightest,
        bg_border = plt.bg_mid,
        bg_sbar = plt.bg_mid,
        bg_thumb = plt.slateGray,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.mauveCore,
        indicator = plt.mauveCore,
      },
    },
    syn = {
      attribute = plt.bronzeCore,
      boolean = plt.roseCore,
      comment = plt.slateGray,
      constant = plt.roseCore,
      deprecated = plt.charcoalGray,
      func = plt.tealCore,
      identifier = plt.fg_lightest,
      keyword = plt.mauveCore,
      method = plt.tealBright,
      number = plt.bronzeCore,
      operator = plt.tealDeep,
      parameter = plt.fg_mid,
      preproc = plt.bronzeCore,
      punct = plt.fg_mid,
      regex = plt.tealDeep,
      special = plt.tealDeep,
      special2 = plt.blueCore,
      special3 = plt.amberCore,
      statement = plt.mauveCore,
      string = plt.greenCore,
      symbol = plt.bronzeBright,
      type = plt.blueCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.tealCore,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.warningOrange,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.tealCore,
    },
    diff = {
      add = plt.greenCore,
      add_inline = plt.greenBright,
      change = plt.bronzeCore,
      change_inline = plt.bronzeBright,
      delete = plt.roseCore,
      delete_inline = plt.roseBright,
      text = plt.tealCore,
    },
    vcs = {
      added = plt.greenCore,
      changed = plt.bronzeCore,
      removed = plt.roseCore,
    },
    term = {
      black = plt.bg_alt3,
      red = plt.roseCore,
      green = plt.greenCore,
      yellow = plt.bronzeCore,
      blue = plt.blueCore,
      magenta = plt.mauveCore,
      cyan = plt.tealCore,
      white = plt.steelGray,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.roseCore):brighten(0.2):to_hex(),
      green_bright = color(plt.greenCore):brighten(0.2):to_hex(),
      yellow_bright = color(plt.bronzeCore):brighten(0.2):to_hex(),
      blue_bright = color(plt.blueCore):brighten(0.3):to_hex(),
      magenta_bright = color(plt.mauveCore):brighten(0.2):to_hex(),
      cyan_bright = color(plt.tealCore):brighten(0.2):to_hex(),
      white_bright = color(plt.steelGray):brighten(0.2):to_hex(),
      indexed1 = plt.roseCore,
      indexed2 = plt.bronzeCore,
    },
  }
end

return {
  name = "Habamax",
  author = "PrismPunk.nvim (Original by Maxim Kim)",
  description = "Hubba hubba hubba.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.charcoalGray,
    base04 = palette.slateGray,
    base05 = palette.steelGray,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.roseCore,
    base09 = palette.bronzeCore,
    base0A = palette.amberCore,
    base0B = palette.greenCore,
    base0C = palette.tealCore,
    base0D = palette.blueCore,
    base0E = palette.mauveCore,
    base0F = palette.roseDeep,
  },
  palette = palette,
  get = M.get,
}
