local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#161821",
  bg_darker = "#1A1C2A",
  bg_dark = "#1F2130",
  bg_mid = "#262831",
  bg_light = "#2D2F3C",
  bg_lighter = "#363841",
  bg_lightest = "#3F424F",
  fg_lightest = "#DADADA",
  fg_light = "#C5C8D1",
  fg_mid = "#A6A8B1",
  fg_dark = "#8787AF",
  bg_alt1 = "#1C1E2E",
  bg_alt2 = "#121418",
  bg_alt3 = "#212430",
  bg_alt4 = "#0E1015",
  lavenderBright = "#D7D7FF",
  lavenderCore = "#AF87D7",
  lavenderDeep = "#8787AF",
  lavenderDark = "#5F5F87",
  coralBright = "#FF5F5F",
  coralCore = "#D75F5F",
  coralDeep = "#D7005F",
  goldenBright = "#FFD75F",
  goldenCore = "#D7AF5F",
  goldenDeep = "#FFAF00",
  skyBright = "#87D7FF",
  skyCore = "#87AFD7",
  skyDeep = "#87AFFF",
  limeBright = "#87FF5F",
  limeCore = "#87D75F",
  limeDeep = "#00AF5F",
  tealBright = "#5FD7D7",
  tealCore = "#5FAFAF",
  tealDeep = "#5FD7AF",
  magentaBright = "#FF87FF",
  magentaCore = "#FF5FFF",
  magentaDeep = "#FF00AF",
  sorbetPurple = "#AF87D7",
  sorbetCoral = "#D75F5F",
  sorbetGold = "#D7AF5F",
  sorbetSky = "#87AFD7",
  sorbetLime = "#87D75F",
  sorbetTeal = "#5FAFAF",
  shadowGray = "#5F5F87",
  dimGray = "#707070",
  lightGray = "#DADADA",
  dangerRed = "#FF5F5F",
  warningOrange = "#FFAF00",
  infoBlue = "#00AFFF",
  successGreen = "#87D75F",
  twilightIndigo = "#5F5F87",
  moonGlow = "#D7D7FF",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.skyCore,
      insert = plt.limeCore,
      visual = plt.lavenderCore,
      replace = plt.coralCore,
      command = plt.goldenCore,
    },
    accent = {
      accent1 = plt.lavenderCore,
      accent2 = plt.skyCore,
      accent3 = plt.goldenCore,
      accent4 = plt.tealCore,
      accent5 = plt.limeCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.lavenderBright,
      rainbow2 = plt.skyCore,
      rainbow3 = plt.goldenCore,
      rainbow4 = plt.limeCore,
      rainbow5 = plt.tealCore,
      rainbow6 = plt.coralCore,
      rainbow7 = plt.lavenderDeep,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_lighter,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_lighter,
      bg_highlight = plt.bg_mid,
      bg_search = plt.goldenDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.lavenderDark,
      header1 = plt.lavenderBright,
      header2 = plt.skyCore,
      special = plt.magentaCore,
      nontext = plt.bg_lighter,
      whitespace = plt.dimGray,
      win_separator = plt.twilightIndigo,
      indent = plt.bg_lighter,
      indent_scope = plt.lavenderCore,
      picker = plt.tealCore,
      yank = plt.goldenBright,
      mark = plt.coralCore,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.lavenderDark,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.lavenderDark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_alt1,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.lavenderCore,
        indicator = plt.lavenderCore,
      },
    },
    syn = {
      attribute = plt.goldenCore,
      boolean = plt.coralCore,
      comment = plt.lavenderCore,
      constant = plt.coralCore,
      deprecated = plt.dimGray,
      func = plt.skyCore,
      identifier = plt.fg_lightest,
      keyword = plt.skyCore,
      method = plt.skyBright,
      number = plt.goldenCore,
      operator = plt.tealCore,
      parameter = plt.fg_mid,
      preproc = plt.skyCore,
      punct = plt.fg_mid,
      regex = plt.tealCore,
      special = plt.tealCore,
      special2 = plt.magentaCore,
      special3 = plt.lavenderCore,
      statement = plt.skyCore,
      string = plt.goldenCore,
      symbol = plt.goldenBright,
      type = plt.skyCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.tealCore,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.warningOrange,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.tealCore,
    },
    diff = {
      add = plt.limeCore,
      add_inline = plt.limeDeep,
      change = plt.skyCore,
      change_inline = plt.skyDeep,
      delete = plt.coralCore,
      delete_inline = plt.coralDeep,
      text = plt.magentaCore,
    },
    vcs = {
      added = plt.limeCore,
      changed = plt.skyCore,
      removed = plt.coralCore,
    },
    term = {
      black = plt.bg_alt3,
      red = plt.coralCore,
      green = plt.limeCore,
      yellow = plt.goldenCore,
      blue = plt.skyCore,
      magenta = plt.lavenderCore,
      cyan = plt.tealCore,
      white = plt.lightGray,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.coralCore):brighten(0.2):to_hex(),
      green_bright = color(plt.limeCore):brighten(0.1):to_hex(),
      yellow_bright = color(plt.goldenCore):brighten(0.2):to_hex(),
      blue_bright = color(plt.skyCore):brighten(0.3):to_hex(),
      magenta_bright = color(plt.lavenderCore):brighten(0.2):to_hex(),
      cyan_bright = color(plt.tealCore):brighten(0.1):to_hex(),
      white_bright = color(plt.lightGray):brighten(0.2):to_hex(),
      indexed1 = plt.goldenBright,
      indexed2 = plt.coralCore,
    },
  }
end

return {
  name = "Sorbet",
  author = "PrismPunk.nvim (Original by Maxence Weynans)",
  description = "A shallow grave, a monument to the ruined age.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.coralCore,
    base09 = palette.goldenCore,
    base0A = palette.goldenBright,
    base0B = palette.limeCore,
    base0C = palette.tealCore,
    base0D = palette.skyCore,
    base0E = palette.lavenderCore,
    base0F = palette.coralDeep,
  },
  palette = palette,
  get = M.get,
}
