local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.nvim-builtins.prism-sorbet")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.skyCore,
      insert = plt.limeCore,
      visual = plt.lavenderCore,
      replace = plt.coralCore,
      command = plt.goldenCore,
    },
    accent = {
      accent1 = plt.lavenderCore,
      accent2 = plt.skyCore,
      accent3 = plt.goldenCore,
      accent4 = plt.tealCore,
      accent5 = plt.limeCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.lavenderBright,
      rainbow2 = plt.skyCore,
      rainbow3 = plt.goldenCore,
      rainbow4 = plt.limeCore,
      rainbow5 = plt.tealCore,
      rainbow6 = plt.coralCore,
      rainbow7 = plt.lavenderDeep,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_lighter,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.lavenderDark,
      cursorline = plt.bg_lighter,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.lavenderCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lighter,
      selection = plt.bg_mid,
      win_separator = plt.twilightIndigo,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.lavenderDark,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.bg_lightest,
        fg = plt.fg_lightest,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.goldenCore,
      boolean = plt.coralCore,
      comment = plt.lavenderCore,
      constant = plt.coralCore,
      deprecated = plt.dimGray,
      func = plt.skyCore,
      identifier = plt.fg_lightest,
      keyword = plt.skyCore,
      method = plt.skyBright,
      number = plt.goldenCore,
      operator = plt.tealCore,
      parameter = plt.fg_mid,
      preproc = plt.skyCore,
      punct = plt.fg_mid,
      regex = plt.tealCore,
      special = plt.tealCore,
      statement = plt.skyCore,
      string = plt.goldenCore,
      symbol = plt.goldenBright,
      type = plt.skyCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.tealCore,
    },
    diff = {
      add = plt.limeCore,
      change = plt.skyCore,
      delete = plt.coralCore,
      text = plt.magentaCore,
    },
    vcs = {
      added = plt.limeCore,
      changed = plt.skyCore,
      removed = plt.coralCore,
    },
    term = {
      black = plt.bg_alt3,
      red = plt.coralCore,
      green = plt.limeCore,
      yellow = plt.goldenCore,
      blue = plt.skyCore,
      magenta = plt.lavenderCore,
      cyan = plt.tealCore,
      white = plt.lightGray,

      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.coralCore):brighten(0.2):to_hex(),
      green_bright = color(plt.limeCore):brighten(0.1):to_hex(),
      yellow_bright = color(plt.goldenCore):brighten(0.2):to_hex(),
      blue_bright = color(plt.skyCore):brighten(0.3):to_hex(),
      magenta_bright = color(plt.lavenderCore):brighten(0.2):to_hex(),
      cyan_bright = color(plt.tealCore):brighten(0.1):to_hex(),
      white_bright = color(plt.lightGray):brighten(0.2):to_hex(),
    },
  }
end

return {
  name = "Sorbet",
  author = "PrismPunk.nvim (Original by Maxence Weynans)",
  description = "A shallow grave, a monument to the ruined age.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.coralCore,
    base09 = palette.goldenCore,
    base0A = palette.goldenBright,
    base0B = palette.limeCore,
    base0C = palette.tealCore,
    base0D = palette.skyCore,
    base0E = palette.lavenderCore,
    base0F = palette.coralDeep,
  },
  palette = palette,
  get = M.get,
}
