local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0A0C",
  asylum_night = "#0C0F12",
  arkham_core = "#11161A",
  victorian_glow = "#182028",
  arkham_red = "#990018",
  blood_velvet = "#AA1122",
  madness_red = "#BB2233",
  scream_red = "#CC3344",
  asylum_green = "#006633",
  electroshock = "#007744",
  lobotomy_green = "#008855",
  decay_green = "#44AA88",
  sepia_gold = "#AA8855",
  victorian_gold = "#BB9966",
  gilded_madness = "#CCAA77",
  broken_gold = "#DDBB88",
  straitjacket = "#E8E8E0",
  ghost_white = "#D8D8D0",
  marble_white = "#C8C8C0",
  term_red = "#BB2233",
  term_green = "#008855",
  term_gold = "#CCAA77",
  term_white = "#D8D8D0",
  term_red_bright = "#CC3344",
  term_green_bright = "#44AA88",
  term_gold_bright = "#DDBB88",

  bg_darkest = "#0A0A0C",
  fg_lightest = "#D8D8D0",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.blood_velvet,
      insert = plt.ghost_white,
      visual = plt.madness_red,
      replace = plt.scream_red,
      command = plt.electroshock,
    },

    ui = {
      fg = plt.straitjacket,
      fg_dim = plt.ghost_white,
      fg_dimmer = plt.marble_white,
      fg_dark = plt.decay_green,
      fg_reverse = plt.void_black,

      bg_m4 = plt.victorian_glow,
      bg_m3 = plt.arkham_core,
      bg_m2 = plt.asylum_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.asylum_night,
      bg_p2 = plt.arkham_core,
      bg_gutter = opts.gutter and plt.arkham_core or "none",
      bg_cursorline = plt.arkham_core,
      bg_cursorline_alt = plt.asylum_night,
      bg_search = plt.gilded_madness,
      bg_visual = plt.madness_red,
      bg_statusline = plt.arkham_core,

      border = plt.broken_gold,
      header1 = plt.blood_velvet,
      header2 = plt.electroshock,
      special = plt.victorian_gold,
      nontext = plt.asylum_night,
      whitespace = plt.victorian_glow,
      win_separator = plt.broken_gold,
      indent = plt.asylum_night,
      indent_scope = plt.decay_green,
      picker = plt.straitjacket,
      yank = plt.scream_red,
      mark = plt.madness_red,
      scrollbar = plt.arkham_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.straitjacket,
        bg_selected = plt.arkham_core,
        fg_inactive = plt.marble_white,
        bg_inactive = plt.void_black,
        fg_alternate = plt.blood_velvet,
        bg_alternate = plt.void_black,
        indicator = plt.victorian_gold,
      },

      pmenu = {
        fg = plt.straitjacket,
        fg_sel = "none",
        fg_border = plt.arkham_core,
        bg_border = plt.arkham_core,
        bg = plt.arkham_core,
        bg_sel = plt.asylum_night,
        bg_sbar = plt.arkham_core,
        bg_thumb = plt.broken_gold,
      },

      float = {
        fg = plt.straitjacket,
        bg = plt.asylum_night,
        fg_border = plt.arkham_core,
        bg_border = plt.asylum_night,
      },
    },

    accent = {
      accent1 = plt.blood_velvet,
      accent2 = plt.electroshock,
      accent3 = plt.victorian_gold,
      accent4 = plt.madness_red,
      accent5 = plt.decay_green,
      invert = plt.arkham_core,
    },

    rainbow = {
      rainbow1 = plt.blood_velvet,
      rainbow2 = plt.madness_red,
      rainbow3 = plt.scream_red,
      rainbow4 = plt.electroshock,
      rainbow5 = plt.lobotomy_green,
      rainbow6 = plt.victorian_gold,
      rainbow7 = plt.gilded_madness,
    },

    syn = {
      attribute = plt.straitjacket,
      boolean = plt.scream_red,
      comment = plt.marble_white,
      constant = plt.gilded_madness,
      deprecated = plt.victorian_glow,
      func = plt.blood_velvet,
      identifier = plt.straitjacket,
      keyword = plt.blood_velvet,
      method = plt.electroshock,
      number = plt.scream_red,
      operator = plt.decay_green,
      parameter = plt.marble_white,
      preproc = plt.madness_red,
      punct = plt.straitjacket,
      regex = plt.lobotomy_green,
      statement = plt.blood_velvet,
      string = plt.gilded_madness,
      symbol = plt.straitjacket,
      type = plt.electroshock,
      variable = plt.straitjacket,
      special = plt.victorian_gold,
      special2 = plt.decay_green,
      special3 = plt.scream_red,
    },

    vcs = { added = plt.decay_green, removed = plt.madness_red, changed = plt.victorian_gold },
    diff = { add = plt.decay_green, change = plt.electroshock, delete = plt.scream_red, text = plt.blood_velvet },
    diag = {
      ok = plt.decay_green,
      error = plt.scream_red,
      warning = plt.madness_red,
      info = plt.blood_velvet,
      hint = plt.victorian_gold,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_gold,
      blue = plt.term_green,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_gold_bright,
      blue_bright = plt.term_green_bright,
      magenta_bright = plt.term_red_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.blood_velvet,
      indexed2 = plt.electroshock,
    },

    treesitter = {
      ["@comment"] = plt.marble_white,
      ["@comment.documentation"] = plt.ghost_white,
      ["@comment.error"] = plt.scream_red,
      ["@comment.warning"] = plt.madness_red,
      ["@comment.todo"] = plt.blood_velvet,
      ["@comment.note"] = plt.decay_green,

      ["@constant"] = plt.gilded_madness,
      ["@constant.builtin"] = plt.gilded_madness,
      ["@constant.macro"] = plt.scream_red,

      ["@string"] = plt.gilded_madness,
      ["@string.documentation"] = plt.gilded_madness,
      ["@string.regex"] = plt.lobotomy_green,
      ["@string.escape"] = plt.decay_green,
      ["@string.special"] = plt.blood_velvet,
      ["@string.special.symbol"] = plt.straitjacket,
      ["@string.special.url"] = plt.victorian_gold,
      ["@string.special.path"] = plt.gilded_madness,

      ["@character"] = plt.gilded_madness,
      ["@character.special"] = plt.decay_green,

      ["@number"] = plt.scream_red,
      ["@number.float"] = plt.scream_red,

      ["@boolean"] = plt.madness_red,

      ["@function"] = plt.blood_velvet,
      ["@function.builtin"] = plt.blood_velvet,
      ["@function.call"] = plt.blood_velvet,
      ["@function.macro"] = plt.electroshock,
      ["@function.method"] = plt.electroshock,
      ["@function.method.call"] = plt.electroshock,

      ["@constructor"] = plt.straitjacket,

      ["@parameter"] = plt.marble_white,
      ["@parameter.builtin"] = plt.straitjacket,

      ["@keyword"] = plt.blood_velvet,
      ["@keyword.coroutine"] = plt.madness_red,
      ["@keyword.function"] = plt.blood_velvet,
      ["@keyword.operator"] = plt.decay_green,
      ["@keyword.return"] = plt.blood_velvet,
      ["@keyword.import"] = plt.victorian_gold,
      ["@keyword.storage"] = plt.blood_velvet,
      ["@keyword.repeat"] = plt.blood_velvet,
      ["@keyword.conditional"] = plt.blood_velvet,
      ["@keyword.exception"] = plt.scream_red,
      ["@keyword.directive"] = plt.madness_red,
      ["@keyword.directive.define"] = plt.madness_red,

      ["@conditional"] = plt.blood_velvet,
      ["@conditional.ternary"] = plt.blood_velvet,

      ["@repeat"] = plt.blood_velvet,

      ["@label"] = plt.victorian_gold,

      ["@operator"] = plt.decay_green,

      ["@exception"] = plt.scream_red,

      ["@variable"] = plt.straitjacket,
      ["@variable.builtin"] = plt.gilded_madness,
      ["@variable.parameter"] = plt.marble_white,
      ["@variable.member"] = plt.straitjacket,

      ["@type"] = plt.electroshock,
      ["@type.builtin"] = plt.electroshock,
      ["@type.definition"] = plt.electroshock,
      ["@type.qualifier"] = plt.blood_velvet,

      ["@attribute"] = plt.straitjacket,
      ["@attribute.builtin"] = plt.victorian_gold,

      ["@property"] = plt.straitjacket,
      ["@field"] = plt.straitjacket,
      ["@module"] = plt.straitjacket,
      ["@module.builtin"] = plt.straitjacket,
      ["@namespace"] = plt.straitjacket,
      ["@namespace.builtin"] = plt.straitjacket,

      ["@punctuation.delimiter"] = plt.straitjacket,
      ["@punctuation.bracket"] = plt.decay_green,
      ["@punctuation.special"] = plt.lobotomy_green,

      ["@tag"] = plt.blood_velvet,
      ["@tag.attribute"] = plt.victorian_gold,
      ["@tag.delimiter"] = plt.straitjacket,
      ["@tag.builtin"] = plt.blood_velvet,

      ["@markup.strong"] = { fg = plt.blood_velvet, bold = true },
      ["@markup.italic"] = { fg = plt.straitjacket, italic = true },
      ["@markup.strikethrough"] = { fg = plt.victorian_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.scream_red, underline = true },
      ["@markup.heading"] = plt.blood_velvet,
      ["@markup.heading.1"] = plt.blood_velvet,
      ["@markup.heading.2"] = plt.madness_red,
      ["@markup.heading.3"] = plt.scream_red,
      ["@markup.heading.4"] = plt.electroshock,
      ["@markup.heading.5"] = plt.lobotomy_green,
      ["@markup.heading.6"] = plt.victorian_gold,
      ["@markup.quote"] = plt.marble_white,
      ["@markup.math"] = plt.decay_green,
      ["@markup.link"] = plt.victorian_gold,
      ["@markup.link.label"] = plt.gilded_madness,
      ["@markup.link.url"] = plt.lobotomy_green,
      ["@markup.raw"] = plt.gilded_madness,
      ["@markup.raw.block"] = plt.gilded_madness,
      ["@markup.list"] = plt.blood_velvet,
      ["@markup.list.checked"] = plt.decay_green,
      ["@markup.list.unchecked"] = plt.marble_white,

      ["@diff.plus"] = plt.decay_green,
      ["@diff.minus"] = plt.madness_red,
      ["@diff.delta"] = plt.victorian_gold,

      ["@none"] = "none",
      ["@conceal"] = plt.gilded_madness,
      ["@spell"] = plt.straitjacket,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.straitjacket,
      ["@constructor.python"] = plt.blood_velvet,
      ["@constructor.javascript"] = plt.blood_velvet,
      ["@constructor.typescript"] = plt.blood_velvet,
      ["@namespace.rust"] = plt.straitjacket,
      ["@type.qualifier.rust"] = plt.blood_velvet,
      ["@constant.macro.c"] = plt.scream_red,
      ["@constant.macro.cpp"] = plt.scream_red,
      ["@namespace.go"] = plt.straitjacket,
      ["@property.css"] = plt.victorian_gold,
      ["@type.css"] = plt.blood_velvet,
      ["@label.json"] = plt.straitjacket,
      ["@field.yaml"] = plt.marble_white,
      ["@property.toml"] = plt.marble_white,
      ["@function.builtin.bash"] = plt.electroshock,
      ["@string.regexp"] = plt.lobotomy_green,
      ["@character.special.regex"] = plt.decay_green,
    },

    lsp = {
      ["@lsp.type.class"] = plt.electroshock,
      ["@lsp.type.interface"] = plt.electroshock,
      ["@lsp.type.struct"] = plt.electroshock,
      ["@lsp.type.enum"] = plt.electroshock,
      ["@lsp.type.enumMember"] = plt.gilded_madness,
      ["@lsp.type.property"] = plt.straitjacket,
      ["@lsp.type.namespace"] = plt.straitjacket,

      ["@lsp.type.macro"] = plt.scream_red,
      ["@lsp.type.decorator"] = plt.blood_velvet,

      ["@lsp.type.builtinType"] = plt.electroshock,
      ["@lsp.type.selfParameter"] = plt.blood_velvet,
      ["@lsp.type.typeParameter"] = plt.electroshock,

      ["@lsp.type.array"] = plt.electroshock,
      ["@lsp.type.object"] = plt.electroshock,
      ["@lsp.type.key"] = plt.straitjacket,
      ["@lsp.type.null"] = plt.gilded_madness,
      ["@lsp.type.enumConstant"] = plt.gilded_madness,

      ["@lsp.type.event"] = plt.electroshock,
      ["@lsp.type.regexp"] = plt.lobotomy_green,
      ["@lsp.type.unresolvedReference"] = plt.scream_red,

      ["@lsp.mod.deprecated"] = { fg = plt.victorian_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.gilded_madness,
      ["@lsp.mod.async"] = plt.blood_velvet,
      ["@lsp.mod.static"] = plt.electroshock,
      ["@lsp.mod.abstract"] = plt.electroshock,
      ["@lsp.mod.defaultLibrary"] = plt.electroshock,
      ["@lsp.mod.documentation"] = plt.marble_white,
    },
  }
end

return {
  name = "Amadeus Arkham – The Founder",
  author = "PrismPunk.nvim",
  description = "He built the asylum to cure madness. "
    .. "Then carved his mother’s name into his own flesh with a razor."
    .. "Victorian blood, institutional green, and the endless scream of "
    .. "a man who became the first patient of the tomb he designed.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.asylum_night,
    base02 = palette.arkham_core,
    base03 = palette.victorian_glow,
    base04 = palette.decay_green,
    base05 = palette.marble_white,
    base06 = palette.ghost_white,
    base07 = palette.straitjacket,
    base08 = palette.madness_red,
    base09 = palette.scream_red,
    base0A = palette.victorian_gold,
    base0B = palette.gilded_madness,
    base0C = palette.blood_velvet,
    base0D = palette.electroshock,
    base0E = palette.arkham_red,
    base0F = palette.broken_gold,
  },

  palette = palette,
  get = M.get,
}
