local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0809",
  arkham_night = "#0E0B0D",
  quinz_core = "#121012",
  giggle_glow = "#20181C",
  harley_red = "#FF0044",
  joker_red = "#EE1133",
  blood_diamond = "#FF3355",
  lovebite_red = "#FF5577",
  chaos_black = "#110F11",
  joker_black = "#1C191B",
  bubblegum = "#FF66AA",
  mallet_pink = "#FF88CC",
  hyena_pink = "#FFAAEE",
  puddin_green = "#00FF88",
  venom_green = "#22DD99",
  asylum_white = "#EEEEFF",
  broken_heart = "#BB66FF",
  bruise_purple = "#AA44EE",
  term_red = "#FF3355",
  term_pink = "#FF88CC",
  term_green = "#00FF88",
  term_purple = "#BB66FF",
  term_white = "#EEEEFF",
  term_red_bright = "#FF5577",
  term_pink_bright = "#FFAADD",
  term_green_bright = "#44FFAA",

  bg_darkest = "#0A0809",
  fg_lightest = "#EEEEFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.harley_red,
      insert = plt.bubblegum,
      visual = plt.mallet_pink,
      replace = plt.lovebite_red,
      command = plt.puddin_green,
    },

    ui = {
      fg = plt.asylum_white,
      fg_dim = plt.hyena_pink,
      fg_dimmer = plt.mallet_pink,
      fg_dark = plt.bruise_purple,
      fg_reverse = plt.void_black,

      bg_m4 = plt.giggle_glow,
      bg_m3 = plt.quinz_core,
      bg_m2 = plt.arkham_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.arkham_night,
      bg_p2 = plt.quinz_core,
      bg_gutter = opts.gutter and plt.quinz_core or "none",
      bg_cursorline = plt.quinz_core,
      bg_cursorline_alt = plt.arkham_night,
      bg_search = plt.venom_green,
      bg_visual = plt.blood_diamond,
      bg_statusline = plt.quinz_core,

      border = plt.mallet_pink,
      header1 = plt.harley_red,
      header2 = plt.puddin_green,
      special = plt.bubblegum,
      nontext = plt.arkham_night,
      whitespace = plt.giggle_glow,
      win_separator = plt.hyena_pink,
      indent = plt.arkham_night,
      indent_scope = plt.joker_black,
      picker = plt.asylum_white,
      yank = plt.lovebite_red,
      mark = plt.joker_red,
      scrollbar = plt.quinz_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.asylum_white,
        bg_selected = plt.quinz_core,
        fg_inactive = plt.hyena_pink,
        bg_inactive = plt.void_black,
        fg_alternate = plt.harley_red,
        bg_alternate = plt.void_black,
        indicator = plt.bubblegum,
      },

      pmenu = {
        fg = plt.asylum_white,
        fg_sel = "none",
        fg_border = plt.quinz_core,
        bg_border = plt.quinz_core,
        bg = plt.quinz_core,
        bg_sel = plt.arkham_night,
        bg_sbar = plt.quinz_core,
        bg_thumb = plt.mallet_pink,
      },

      float = {
        fg = plt.asylum_white,
        bg = plt.arkham_night,
        fg_border = plt.quinz_core,
        bg_border = plt.arkham_night,
      },
    },

    accent = {
      accent1 = plt.harley_red,
      accent2 = plt.puddin_green,
      accent3 = plt.bubblegum,
      accent4 = plt.bruise_purple,
      accent5 = plt.mallet_pink,
      invert = plt.quinz_core,
    },

    rainbow = {
      rainbow1 = plt.harley_red,
      rainbow2 = plt.joker_red,
      rainbow3 = plt.blood_diamond,
      rainbow4 = plt.puddin_green,
      rainbow5 = plt.venom_green,
      rainbow6 = plt.bubblegum,
      rainbow7 = plt.mallet_pink,
    },

    syn = {
      attribute = plt.asylum_white,
      boolean = plt.joker_red,
      comment = plt.hyena_pink,
      constant = plt.bubblegum,
      deprecated = plt.giggle_glow,
      func = plt.harley_red,
      identifier = plt.asylum_white,
      keyword = plt.harley_red,
      method = plt.puddin_green,
      number = plt.lovebite_red,
      operator = plt.bruise_purple,
      parameter = plt.mallet_pink,
      preproc = plt.joker_red,
      punct = plt.asylum_white,
      regex = plt.venom_green,
      statement = plt.harley_red,
      string = plt.bubblegum,
      symbol = plt.asylum_white,
      type = plt.puddin_green,
      variable = plt.asylum_white,
      special = plt.joker_red,
      special2 = plt.venom_green,
      special3 = plt.lovebite_red,
    },

    vcs = { added = plt.venom_green, removed = plt.joker_red, changed = plt.bubblegum },
    diff = { add = plt.venom_green, change = plt.puddin_green, delete = plt.blood_diamond, text = plt.harley_red },
    diag = {
      ok = plt.venom_green,
      error = plt.joker_red,
      warning = plt.lovebite_red,
      info = plt.harley_red,
      hint = plt.bubblegum,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_pink,
      blue = plt.term_green,
      magenta = plt.term_pink,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_pink_bright,
      blue_bright = plt.term_green_bright,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.harley_red,
      indexed2 = plt.puddin_green,
    },

    treesitter = {
      ["@comment"] = plt.hyena_pink,
      ["@comment.documentation"] = plt.mallet_pink,
      ["@comment.error"] = plt.joker_red,
      ["@comment.warning"] = plt.lovebite_red,
      ["@comment.todo"] = plt.bubblegum,
      ["@comment.note"] = plt.venom_green,

      ["@constant"] = plt.bubblegum,
      ["@constant.builtin"] = plt.mallet_pink,
      ["@constant.macro"] = plt.joker_red,

      ["@string"] = plt.bubblegum,
      ["@string.documentation"] = plt.bubblegum,
      ["@string.regex"] = plt.venom_green,
      ["@string.escape"] = plt.puddin_green,
      ["@string.special"] = plt.joker_red,
      ["@string.special.symbol"] = plt.asylum_white,
      ["@string.special.url"] = plt.venom_green,
      ["@string.special.path"] = plt.bubblegum,

      ["@character"] = plt.bubblegum,
      ["@character.special"] = plt.puddin_green,

      ["@number"] = plt.lovebite_red,
      ["@number.float"] = plt.lovebite_red,

      ["@boolean"] = plt.joker_red,

      ["@function"] = plt.harley_red,
      ["@function.builtin"] = plt.harley_red,
      ["@function.call"] = plt.harley_red,
      ["@function.macro"] = plt.puddin_green,
      ["@function.method"] = plt.puddin_green,
      ["@function.method.call"] = plt.puddin_green,

      ["@constructor"] = plt.asylum_white,

      ["@parameter"] = plt.mallet_pink,
      ["@parameter.builtin"] = plt.asylum_white,

      ["@keyword"] = plt.harley_red,
      ["@keyword.coroutine"] = plt.joker_red,
      ["@keyword.function"] = plt.harley_red,
      ["@keyword.operator"] = plt.bruise_purple,
      ["@keyword.return"] = plt.harley_red,
      ["@keyword.import"] = plt.bubblegum,
      ["@keyword.storage"] = plt.harley_red,
      ["@keyword.repeat"] = plt.harley_red,
      ["@keyword.conditional"] = plt.harley_red,
      ["@keyword.exception"] = plt.joker_red,
      ["@keyword.directive"] = plt.lovebite_red,
      ["@keyword.directive.define"] = plt.lovebite_red,

      ["@conditional"] = plt.harley_red,
      ["@conditional.ternary"] = plt.harley_red,

      ["@repeat"] = plt.harley_red,

      ["@label"] = plt.bubblegum,

      ["@operator"] = plt.bruise_purple,

      ["@exception"] = plt.joker_red,

      ["@variable"] = plt.asylum_white,
      ["@variable.builtin"] = plt.bubblegum,
      ["@variable.parameter"] = plt.mallet_pink,
      ["@variable.member"] = plt.asylum_white,

      ["@type"] = plt.puddin_green,
      ["@type.builtin"] = plt.puddin_green,
      ["@type.definition"] = plt.puddin_green,
      ["@type.qualifier"] = plt.harley_red,

      ["@attribute"] = plt.asylum_white,
      ["@attribute.builtin"] = plt.bubblegum,

      ["@property"] = plt.asylum_white,
      ["@field"] = plt.asylum_white,
      ["@module"] = plt.asylum_white,
      ["@module.builtin"] = plt.asylum_white,
      ["@namespace"] = plt.asylum_white,
      ["@namespace.builtin"] = plt.asylum_white,

      ["@punctuation.delimiter"] = plt.asylum_white,
      ["@punctuation.bracket"] = plt.bruise_purple,
      ["@punctuation.special"] = plt.venom_green,

      ["@tag"] = plt.harley_red,
      ["@tag.attribute"] = plt.bubblegum,
      ["@tag.delimiter"] = plt.asylum_white,
      ["@tag.builtin"] = plt.harley_red,

      ["@markup.strong"] = { fg = plt.harley_red, bold = true },
      ["@markup.italic"] = { fg = plt.asylum_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.giggle_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.joker_red, underline = true },
      ["@markup.heading"] = plt.harley_red,
      ["@markup.heading.1"] = plt.harley_red,
      ["@markup.heading.2"] = plt.joker_red,
      ["@markup.heading.3"] = plt.blood_diamond,
      ["@markup.heading.4"] = plt.puddin_green,
      ["@markup.heading.5"] = plt.bubblegum,
      ["@markup.heading.6"] = plt.mallet_pink,
      ["@markup.quote"] = plt.hyena_pink,
      ["@markup.math"] = plt.venom_green,
      ["@markup.link"] = plt.bubblegum,
      ["@markup.link.label"] = plt.asylum_white,
      ["@markup.link.url"] = plt.venom_green,
      ["@markup.raw"] = plt.bubblegum,
      ["@markup.raw.block"] = plt.bubblegum,
      ["@markup.list"] = plt.harley_red,
      ["@markup.list.checked"] = plt.venom_green,
      ["@markup.list.unchecked"] = plt.mallet_pink,

      ["@diff.plus"] = plt.venom_green,
      ["@diff.minus"] = plt.joker_red,
      ["@diff.delta"] = plt.bubblegum,

      ["@none"] = "none",
      ["@conceal"] = plt.bubblegum,
      ["@spell"] = plt.asylum_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.asylum_white,
      ["@constructor.python"] = plt.harley_red,
      ["@constructor.javascript"] = plt.harley_red,
      ["@constructor.typescript"] = plt.harley_red,
      ["@namespace.rust"] = plt.asylum_white,
      ["@type.qualifier.rust"] = plt.harley_red,
      ["@constant.macro.c"] = plt.joker_red,
      ["@constant.macro.cpp"] = plt.joker_red,
      ["@namespace.go"] = plt.asylum_white,
      ["@property.css"] = plt.bubblegum,
      ["@type.css"] = plt.puddin_green,
      ["@label.json"] = plt.asylum_white,
      ["@field.yaml"] = plt.mallet_pink,
      ["@property.toml"] = plt.mallet_pink,
      ["@function.builtin.bash"] = plt.puddin_green,
      ["@string.regexp"] = plt.venom_green,
      ["@character.special.regex"] = plt.puddin_green,
    },

    lsp = {
      ["@lsp.type.class"] = plt.puddin_green,
      ["@lsp.type.interface"] = plt.puddin_green,
      ["@lsp.type.struct"] = plt.puddin_green,
      ["@lsp.type.enum"] = plt.puddin_green,
      ["@lsp.type.enumMember"] = plt.bubblegum,
      ["@lsp.type.property"] = plt.asylum_white,
      ["@lsp.type.namespace"] = plt.asylum_white,

      ["@lsp.type.macro"] = plt.joker_red,
      ["@lsp.type.decorator"] = plt.harley_red,

      ["@lsp.type.builtinType"] = plt.puddin_green,
      ["@lsp.type.selfParameter"] = plt.harley_red,
      ["@lsp.type.typeParameter"] = plt.puddin_green,

      ["@lsp.type.array"] = plt.puddin_green,
      ["@lsp.type.object"] = plt.puddin_green,
      ["@lsp.type.key"] = plt.asylum_white,
      ["@lsp.type.null"] = plt.bubblegum,
      ["@lsp.type.enumConstant"] = plt.bubblegum,

      ["@lsp.type.event"] = plt.puddin_green,
      ["@lsp.type.regexp"] = plt.venom_green,
      ["@lsp.type.unresolvedReference"] = plt.joker_red,

      ["@lsp.mod.deprecated"] = { fg = plt.giggle_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.bubblegum,
      ["@lsp.mod.async"] = plt.harley_red,
      ["@lsp.mod.static"] = plt.puddin_green,
      ["@lsp.mod.abstract"] = plt.puddin_green,
      ["@lsp.mod.defaultLibrary"] = plt.puddin_green,
      ["@lsp.mod.documentation"] = plt.hyena_pink,
    },
  }
end

return {
  name = "Harley Quinn – Harleen Quinzel",
  author = "PrismPunk.nvim",
  description = "Red and black diamonds, bubblegum violence, "
    .. "toxic love, and a laugh that cracks glass. She’s not crazy — she’s just in love. "
    .. "With a clown. And a mallet. And explosions.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.arkham_night,
    base02 = palette.quinz_core,
    base03 = palette.giggle_glow,
    base04 = palette.bruise_purple,
    base05 = palette.hyena_pink,
    base06 = palette.asylum_white,
    base07 = palette.asylum_white,
    base08 = palette.joker_red,
    base09 = palette.blood_diamond,
    base0A = palette.bubblegum,
    base0B = palette.mallet_pink,
    base0C = palette.harley_red,
    base0D = palette.puddin_green,
    base0E = palette.venom_green,
    base0F = palette.chaos_black,
  },

  palette = palette,
  get = M.get,
}
