local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#080A08",
  swamp_night = "#0A0D0B",
  grundy_core = "#0E1210",
  grave_glow = "#18221C",
  rot_green = "#226644",
  undead_flesh = "#338855",
  swamp_moss = "#44AA77",
  resurrection_green = "#55CC99",
  tombstone_gray = "#445555",
  corpse_gray = "#667777",
  moon_bone = "#99AAAA",
  death_blue = "#223366",
  rigor_blue = "#334488",
  cold_vein = "#4455AA",
  grundy_blood = "#882222",
  rust_red = "#AA3333",
  moon_sick = "#DDDDBB",
  grave_white = "#EEEECC",
  term_green = "#44AA77",
  term_blue = "#4455AA",
  term_red = "#AA3333",
  term_white = "#EEEECC",
  term_green_bright = "#66CC99",
  term_blue_bright = "#6677CC",

  bg_darkest = "#080A08",
  fg_lightest = "#EEEECC",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.undead_flesh,
      insert = plt.grave_white,
      visual = plt.swamp_moss,
      replace = plt.resurrection_green,
      command = plt.cold_vein,
    },

    ui = {
      fg = plt.grave_white,
      fg_dim = plt.moon_bone,
      fg_dimmer = plt.corpse_gray,
      fg_dark = plt.tombstone_gray,
      fg_reverse = plt.void_black,

      bg_m4 = plt.grave_glow,
      bg_m3 = plt.grundy_core,
      bg_m2 = plt.swamp_night,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.swamp_night,
      bg_p2 = plt.grundy_core,
      bg_gutter = opts.gutter and plt.grundy_core or "none",
      bg_cursorline = plt.grundy_core,
      bg_cursorline_alt = plt.swamp_night,
      bg_search = plt.resurrection_green,
      bg_visual = plt.swamp_moss,
      bg_statusline = plt.grundy_core,

      border = plt.corpse_gray,
      header1 = plt.undead_flesh,
      header2 = plt.cold_vein,
      special = plt.grundy_blood,
      nontext = plt.swamp_night,
      whitespace = plt.grave_glow,
      win_separator = plt.tombstone_gray,
      indent = plt.swamp_night,
      indent_scope = plt.tombstone_gray,
      picker = plt.grave_white,
      yank = plt.resurrection_green,
      mark = plt.rust_red,
      scrollbar = plt.grundy_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.grave_white,
        bg_selected = plt.grundy_core,
        fg_inactive = plt.moon_bone,
        bg_inactive = plt.void_black,
        fg_alternate = plt.undead_flesh,
        bg_alternate = plt.void_black,
        indicator = plt.swamp_moss,
      },

      pmenu = {
        fg = plt.grave_white,
        fg_sel = "none",
        fg_border = plt.grundy_core,
        bg_border = plt.grundy_core,
        bg = plt.grundy_core,
        bg_sel = plt.swamp_night,
        bg_sbar = plt.grundy_core,
        bg_thumb = plt.corpse_gray,
      },

      float = {
        fg = plt.grave_white,
        bg = plt.swamp_night,
        fg_border = plt.grundy_core,
        bg_border = plt.swamp_night,
      },
    },

    accent = {
      accent1 = plt.undead_flesh,
      accent2 = plt.cold_vein,
      accent3 = plt.swamp_moss,
      accent4 = plt.resurrection_green,
      accent5 = plt.grundy_blood,
      invert = plt.grundy_core,
    },

    rainbow = {
      rainbow1 = plt.rot_green,
      rainbow2 = plt.undead_flesh,
      rainbow3 = plt.swamp_moss,
      rainbow4 = plt.resurrection_green,
      rainbow5 = plt.cold_vein,
      rainbow6 = plt.rigor_blue,
      rainbow7 = plt.death_blue,
    },

    syn = {
      attribute = plt.grave_white,
      boolean = plt.grundy_blood,
      comment = plt.moon_bone,
      constant = plt.resurrection_green,
      deprecated = plt.grave_glow,
      func = plt.undead_flesh,
      identifier = plt.grave_white,
      keyword = plt.undead_flesh,
      method = plt.cold_vein,
      number = plt.rust_red,
      operator = plt.tombstone_gray,
      parameter = plt.corpse_gray,
      preproc = plt.grundy_blood,
      punct = plt.grave_white,
      regex = plt.swamp_moss,
      statement = plt.undead_flesh,
      string = plt.resurrection_green,
      symbol = plt.grave_white,
      type = plt.cold_vein,
      variable = plt.grave_white,
      special = plt.grundy_blood,
      special2 = plt.resurrection_green,
      special3 = plt.rust_red,
    },

    vcs = { added = plt.resurrection_green, removed = plt.grundy_blood, changed = plt.cold_vein },
    diff = { add = plt.resurrection_green, change = plt.swamp_moss, delete = plt.rust_red, text = plt.undead_flesh },
    diag = {
      ok = plt.resurrection_green,
      error = plt.grundy_blood,
      warning = plt.rust_red,
      info = plt.undead_flesh,
      hint = plt.cold_vein,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_green,
      blue = plt.term_blue,
      magenta = plt.term_red,
      cyan = plt.term_white,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_green_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_red,
      cyan_bright = plt.term_white,
      white_bright = "#ffffff",
      indexed1 = plt.undead_flesh,
      indexed2 = plt.cold_vein,
    },

    treesitter = {
      ["@comment"] = plt.moon_bone,
      ["@comment.documentation"] = plt.corpse_gray,
      ["@comment.error"] = plt.grundy_blood,
      ["@comment.warning"] = plt.rust_red,
      ["@comment.todo"] = plt.resurrection_green,
      ["@comment.note"] = plt.swamp_moss,

      ["@constant"] = plt.resurrection_green,
      ["@constant.builtin"] = plt.resurrection_green,
      ["@constant.macro"] = plt.grundy_blood,

      ["@string"] = plt.resurrection_green,
      ["@string.documentation"] = plt.resurrection_green,
      ["@string.regex"] = plt.swamp_moss,
      ["@string.escape"] = plt.cold_vein,
      ["@string.special"] = plt.grundy_blood,
      ["@string.special.symbol"] = plt.grave_white,
      ["@string.special.url"] = plt.resurrection_green,
      ["@string.special.path"] = plt.resurrection_green,

      ["@character"] = plt.resurrection_green,
      ["@character.special"] = plt.cold_vein,

      ["@number"] = plt.rust_red,
      ["@number.float"] = plt.rust_red,

      ["@boolean"] = plt.grundy_blood,

      ["@function"] = plt.undead_flesh,
      ["@function.builtin"] = plt.undead_flesh,
      ["@function.call"] = plt.undead_flesh,
      ["@function.macro"] = plt.cold_vein,
      ["@function.method"] = plt.cold_vein,
      ["@function.method.call"] = plt.cold_vein,

      ["@constructor"] = plt.grave_white,

      ["@parameter"] = plt.corpse_gray,
      ["@parameter.builtin"] = plt.grave_white,

      ["@keyword"] = plt.undead_flesh,
      ["@keyword.coroutine"] = plt.grundy_blood,
      ["@keyword.function"] = plt.undead_flesh,
      ["@keyword.operator"] = plt.tombstone_gray,
      ["@keyword.return"] = plt.undead_flesh,
      ["@keyword.import"] = plt.resurrection_green,
      ["@keyword.storage"] = plt.undead_flesh,
      ["@keyword.repeat"] = plt.undead_flesh,
      ["@keyword.conditional"] = plt.undead_flesh,
      ["@keyword.exception"] = plt.grundy_blood,
      ["@keyword.directive"] = plt.rust_red,
      ["@keyword.directive.define"] = plt.rust_red,

      ["@conditional"] = plt.undead_flesh,
      ["@conditional.ternary"] = plt.undead_flesh,

      ["@repeat"] = plt.undead_flesh,

      ["@label"] = plt.resurrection_green,

      ["@operator"] = plt.tombstone_gray,

      ["@exception"] = plt.grundy_blood,

      ["@variable"] = plt.grave_white,
      ["@variable.builtin"] = plt.resurrection_green,
      ["@variable.parameter"] = plt.corpse_gray,
      ["@variable.member"] = plt.grave_white,

      ["@type"] = plt.cold_vein,
      ["@type.builtin"] = plt.cold_vein,
      ["@type.definition"] = plt.cold_vein,
      ["@type.qualifier"] = plt.undead_flesh,

      ["@attribute"] = plt.grave_white,
      ["@attribute.builtin"] = plt.resurrection_green,

      ["@property"] = plt.grave_white,
      ["@field"] = plt.grave_white,
      ["@module"] = plt.grave_white,
      ["@module.builtin"] = plt.grave_white,
      ["@namespace"] = plt.grave_white,
      ["@namespace.builtin"] = plt.grave_white,

      ["@punctuation.delimiter"] = plt.grave_white,
      ["@punctuation.bracket"] = plt.tombstone_gray,
      ["@punctuation.special"] = plt.resurrection_green,

      ["@tag"] = plt.undead_flesh,
      ["@tag.attribute"] = plt.resurrection_green,
      ["@tag.delimiter"] = plt.grave_white,
      ["@tag.builtin"] = plt.undead_flesh,

      ["@markup.strong"] = { fg = plt.undead_flesh, bold = true },
      ["@markup.italic"] = { fg = plt.grave_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.grave_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.swamp_moss, underline = true },
      ["@markup.heading"] = plt.undead_flesh,
      ["@markup.heading.1"] = plt.undead_flesh,
      ["@markup.heading.2"] = plt.swamp_moss,
      ["@markup.heading.3"] = plt.resurrection_green,
      ["@markup.heading.4"] = plt.cold_vein,
      ["@markup.heading.5"] = plt.rigor_blue,
      ["@markup.heading.6"] = plt.death_blue,
      ["@markup.quote"] = plt.moon_bone,
      ["@markup.math"] = plt.resurrection_green,
      ["@markup.link"] = plt.resurrection_green,
      ["@markup.link.label"] = plt.grave_white,
      ["@markup.link.url"] = plt.cold_vein,
      ["@markup.raw"] = plt.resurrection_green,
      ["@markup.raw.block"] = plt.resurrection_green,
      ["@markup.list"] = plt.undead_flesh,
      ["@markup.list.checked"] = plt.resurrection_green,
      ["@markup.list.unchecked"] = plt.corpse_gray,

      ["@diff.plus"] = plt.resurrection_green,
      ["@diff.minus"] = plt.grundy_blood,
      ["@diff.delta"] = plt.cold_vein,

      ["@none"] = "none",
      ["@conceal"] = plt.resurrection_green,
      ["@spell"] = plt.grave_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.grave_white,
      ["@constructor.python"] = plt.undead_flesh,
      ["@constructor.javascript"] = plt.undead_flesh,
      ["@constructor.typescript"] = plt.undead_flesh,
      ["@namespace.rust"] = plt.grave_white,
      ["@type.qualifier.rust"] = plt.undead_flesh,
      ["@constant.macro.c"] = plt.grundy_blood,
      ["@constant.macro.cpp"] = plt.grundy_blood,
      ["@namespace.go"] = plt.grave_white,
      ["@property.css"] = plt.resurrection_green,
      ["@type.css"] = plt.cold_vein,
      ["@label.json"] = plt.grave_white,
      ["@field.yaml"] = plt.corpse_gray,
      ["@property.toml"] = plt.corpse_gray,
      ["@function.builtin.bash"] = plt.cold_vein,
      ["@string.regexp"] = plt.swamp_moss,
      ["@character.special.regex"] = plt.cold_vein,
    },

    lsp = {
      ["@lsp.type.class"] = plt.cold_vein,
      ["@lsp.type.interface"] = plt.cold_vein,
      ["@lsp.type.struct"] = plt.cold_vein,
      ["@lsp.type.enum"] = plt.cold_vein,
      ["@lsp.type.enumMember"] = plt.resurrection_green,
      ["@lsp.type.property"] = plt.grave_white,
      ["@lsp.type.namespace"] = plt.grave_white,

      ["@lsp.type.macro"] = plt.grundy_blood,
      ["@lsp.type.decorator"] = plt.undead_flesh,

      ["@lsp.type.builtinType"] = plt.cold_vein,
      ["@lsp.type.selfParameter"] = plt.undead_flesh,
      ["@lsp.type.typeParameter"] = plt.cold_vein,

      ["@lsp.type.array"] = plt.cold_vein,
      ["@lsp.type.object"] = plt.cold_vein,
      ["@lsp.type.key"] = plt.grave_white,
      ["@lsp.type.null"] = plt.resurrection_green,
      ["@lsp.type.enumConstant"] = plt.resurrection_green,

      ["@lsp.type.event"] = plt.cold_vein,
      ["@lsp.type.regexp"] = plt.swamp_moss,
      ["@lsp.type.unresolvedReference"] = plt.grundy_blood,

      ["@lsp.mod.deprecated"] = { fg = plt.grave_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.resurrection_green,
      ["@lsp.mod.async"] = plt.undead_flesh,
      ["@lsp.mod.static"] = plt.cold_vein,
      ["@lsp.mod.abstract"] = plt.cold_vein,
      ["@lsp.mod.defaultLibrary"] = plt.cold_vein,
      ["@lsp.mod.documentation"] = plt.moon_bone,
    },
  }
end

return {
  name = "Salomon Grundy – Born on a Monday",
  author = "PrismPunk.nvim",
  description = "Big. Dead. Angry. Rot-green swamp flesh, graveyard gray skin, "
    .. "corpse-blue veins, and the moon-sick yellow of a corpse that keeps coming back. "
    .. "He died on a Saturday. He was reborn on a Monday. And every day in between, "
    .. "he just wants to crush Batman’s skull.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.swamp_night,
    base02 = palette.grundy_core,
    base03 = palette.grave_glow,
    base04 = palette.tombstone_gray,
    base05 = palette.corpse_gray,
    base06 = palette.grave_white,
    base07 = palette.grave_white,
    base08 = palette.undead_flesh,
    base09 = palette.swamp_moss,
    base0A = palette.resurrection_green,
    base0B = palette.cold_vein,
    base0C = palette.rigor_blue,
    base0D = palette.death_blue,
    base0E = palette.grundy_blood,
    base0F = palette.rust_red,
  },

  palette = palette,
  get = M.get,
}
