local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0612",
  bg_darker = "#120A1A",
  bg_dark = "#1A0F24",
  bg_mid = "#23152E",
  bg_light = "#2C1B38",
  bg_lighter = "#352142",
  bg_lightest = "#3E284C",
  fg_lightest = "#F4E8D0",
  fg_light = "#E0D0A8",
  fg_mid = "#C8B880",
  fg_dark = "#A89858",
  bg_alt1 = "#150C1E",
  bg_alt2 = "#080410",
  bg_alt3 = "#1E1228",
  bg_alt4 = "#0D0716",
  imperialPurpleCore = "#8E44AD",
  imperialPurpleBright = "#A569BD",
  royalGoldCore = "#F39C12",
  royalGoldBright = "#F4D03F",
  mastermindVioletCore = "#673AB7",
  mastermindVioletBright = "#9575CD",
  calculatedCyanCore = "#00ACC1",
  calculatedCyanBright = "#26C6DA",
  utopianTealCore = "#16A085",
  utopianTealBright = "#48C9B0",
  logicBlueCore = "#2980B9",
  logicBlueBright = "#5DADE2",
  strategicAmberCore = "#FFB300",
  strategicAmberBright = "#FFD54F",
  intelligenceWhiteCore = "#E8EAF6",
  intelligenceWhiteBright = "#FFFFFF",
  chaosRedCore = "#C0392B",
  chaosRedBright = "#EC7063",
  schemeGreenCore = "#229954",
  schemeGreenBright = "#52BE80",
  coldGray = "#7F8C8D",
  coldGrayLight = "#95A5A6",
  successGreen = "#27AE60",
  warningAmber = "#FFC107",
  infoBlue = "#3498DB",
  errorRed = "#E74C3C",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.imperialPurpleCore,
      insert = plt.utopianTealCore,
      visual = plt.royalGoldCore,
      replace = plt.chaosRedCore,
      command = plt.mastermindVioletCore,
    },
    accent = {
      accent1 = plt.imperialPurpleCore,
      accent2 = plt.royalGoldCore,
      accent3 = plt.mastermindVioletCore,
      accent4 = plt.calculatedCyanCore,
      accent5 = plt.utopianTealCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.imperialPurpleBright,
      rainbow2 = plt.royalGoldBright,
      rainbow3 = plt.mastermindVioletBright,
      rainbow4 = plt.calculatedCyanBright,
      rainbow5 = plt.utopianTealBright,
      rainbow6 = plt.logicBlueBright,
      rainbow7 = plt.strategicAmberBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darker,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.imperialPurpleCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.coldGray,
      header1 = plt.imperialPurpleBright,
      header2 = plt.royalGoldBright,
      special = plt.royalGoldCore,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.coldGray,
      indent = plt.bg_lighter,
      indent_scope = plt.imperialPurpleCore,
      picker = plt.mastermindVioletCore,
      yank = plt.strategicAmberBright,
      mark = plt.logicBlueCore,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.coldGrayLight,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.coldGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.coldGray,
        bg_border = plt.bg_darker,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.imperialPurpleBright,
        indicator = plt.imperialPurpleCore,
      },
    },
    syn = {
      attribute = plt.royalGoldCore,
      boolean = plt.calculatedCyanCore,
      comment = plt.coldGray,
      constant = plt.intelligenceWhiteCore,
      deprecated = plt.coldGray,
      func = plt.utopianTealCore,
      identifier = plt.fg_lightest,
      keyword = plt.imperialPurpleCore,
      method = plt.utopianTealBright,
      number = plt.intelligenceWhiteCore,
      operator = plt.royalGoldCore,
      parameter = plt.fg_mid,
      preproc = plt.mastermindVioletCore,
      punct = plt.fg_dark,
      regex = plt.calculatedCyanCore,
      special = plt.calculatedCyanCore,
      special2 = plt.logicBlueCore,
      special3 = plt.strategicAmberCore,
      statement = plt.imperialPurpleCore,
      string = plt.utopianTealCore,
      symbol = plt.royalGoldCore,
      type = plt.logicBlueCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.calculatedCyanCore,
      ok = plt.successGreen,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_hint = plt.calculatedCyanCore,
      virtual_text_ok = plt.successGreen,
    },
    diff = {
      add = plt.schemeGreenCore,
      add_inline = plt.schemeGreenBright,
      change = plt.strategicAmberCore,
      change_inline = plt.strategicAmberBright,
      delete = plt.chaosRedCore,
      delete_inline = plt.chaosRedBright,
      text = plt.calculatedCyanCore,
    },
    vcs = {
      added = plt.schemeGreenCore,
      changed = plt.strategicAmberCore,
      removed = plt.chaosRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.chaosRedCore,
      green = plt.schemeGreenCore,
      yellow = plt.strategicAmberCore,
      blue = plt.logicBlueCore,
      magenta = plt.imperialPurpleCore,
      cyan = plt.calculatedCyanCore,
      white = plt.intelligenceWhiteCore,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = plt.chaosRedBright,
      green_bright = plt.schemeGreenBright,
      yellow_bright = plt.strategicAmberBright,
      blue_bright = plt.logicBlueBright,
      magenta_bright = plt.imperialPurpleBright,
      cyan_bright = plt.calculatedCyanBright,
      white_bright = plt.intelligenceWhiteBright,
      indexed1 = plt.chaosRedCore,
      indexed2 = plt.royalGoldCore,
    },
  }
end

return {
  name = "Watchmen – Ozymandias",
  author = "PrismPunk.nvim",
  description = "Genius strategist — imperial purple, royal gold, calculated perfection.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.coldGray,
    base04 = palette.coldGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.chaosRedCore,
    base09 = palette.strategicAmberCore,
    base0A = palette.royalGoldCore,
    base0B = palette.utopianTealCore,
    base0C = palette.calculatedCyanCore,
    base0D = palette.logicBlueCore,
    base0E = palette.imperialPurpleCore,
    base0F = palette.mastermindVioletCore,
  },
  palette = palette,
  get = M.get,
}
