local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0c0a02",
  bg_darker = "#181404",
  bg_dark = "#241e06",
  bg_mid = "#302808",
  bg_light = "#3c320a",
  bg_lighter = "#483c0c",
  bg_lightest = "#54460e",
  bg_alt1 = "#605010",
  bg_alt2 = "#6c5a12",
  bg_alt3 = "#786414",
  bg_alt4 = "#846e16",
  fg_darkest = "#fff7a7",
  fg_dark = "#fffbcb",
  fg_mid = "#fffce1",
  fg_light = "#fffef0",
  fg_lighter = "#fffff5",
  fg_lightest = "#ffffff",
  allSwift = "#ffeb3b",
  earlyWake = "#ffa726",
  solarFlare = "#ff6f00",
  coolingRunes = "#42a5f5",
  chariotReins = "#c0a020",
  dawnRace = "#ff9800",
  skyPath = "#ffca28",
  blazingShoulder = "#fffffa",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.allSwift,
      insert = plt.earlyWake,
      visual = plt.chariotReins,
      replace = plt.solarFlare,
      command = plt.coolingRunes,
    },
    accent = {
      accent1 = plt.allSwift,
      accent2 = plt.earlyWake,
      accent3 = plt.solarFlare,
      accent4 = plt.skyPath,
      accent5 = plt.coolingRunes,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.allSwift,
      rainbow2 = plt.earlyWake,
      rainbow3 = plt.dawnRace,
      rainbow4 = plt.skyPath,
      rainbow5 = plt.solarFlare,
      rainbow6 = plt.coolingRunes,
      rainbow7 = plt.chariotReins,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_lighter,
      fg_dimmer = plt.fg_light,
      fg_dark = plt.fg_mid,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.solarFlare,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.allSwift,
      header2 = plt.earlyWake,
      special = plt.coolingRunes,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.earlyWake,
      indent = plt.bg_light,
      indent_scope = plt.allSwift,
      picker = plt.solarFlare,
      yank = plt.coolingRunes,
      mark = plt.dawnRace,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_dark,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.allSwift,
        indicator = plt.earlyWake,
      },
    },
    syn = {
      attribute = plt.coolingRunes,
      boolean = plt.dawnRace,
      comment = plt.bg_alt3,
      constant = plt.chariotReins,
      deprecated = plt.bg_alt2,
      func = plt.earlyWake,
      identifier = plt.fg_light,
      keyword = plt.solarFlare,
      method = plt.earlyWake,
      number = plt.chariotReins,
      operator = plt.allSwift,
      parameter = plt.skyPath,
      preproc = plt.coolingRunes,
      punct = plt.bg_alt3,
      regex = plt.dawnRace,
      special = plt.coolingRunes,
      special2 = plt.solarFlare,
      special3 = plt.skyPath,
      statement = plt.solarFlare,
      string = plt.earlyWake,
      symbol = plt.allSwift,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.solarFlare,
      warning = plt.dawnRace,
      info = plt.coolingRunes,
      ok = plt.blazingShoulder,
      hint = plt.earlyWake,
      virtual_text_error = plt.solarFlare,
      virtual_text_warning = plt.dawnRace,
      virtual_text_info = plt.coolingRunes,
      virtual_text_ok = plt.blazingShoulder,
      virtual_text_hint = plt.earlyWake,
    },
    diff = {
      add = plt.blazingShoulder,
      add_inline = plt.earlyWake,
      change = plt.dawnRace,
      change_inline = plt.skyPath,
      delete = plt.solarFlare,
      delete_inline = plt.chariotReins,
      text = plt.coolingRunes,
    },
    vcs = {
      added = plt.blazingShoulder,
      changed = plt.dawnRace,
      removed = plt.solarFlare,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.solarFlare,
      green = plt.blazingShoulder,
      yellow = plt.skyPath,
      blue = plt.coolingRunes,
      magenta = plt.dawnRace,
      cyan = plt.earlyWake,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.solarFlare):brighten(0.2):to_hex(),
      green_bright = color(plt.blazingShoulder):brighten(0.15):to_hex(),
      yellow_bright = color(plt.skyPath):brighten(0.15):to_hex(),
      blue_bright = color(plt.coolingRunes):brighten(0.15):to_hex(),
      magenta_bright = color(plt.dawnRace):brighten(0.2):to_hex(),
      cyan_bright = color(plt.earlyWake):brighten(0.15):to_hex(),
      white_bright = plt.fg_lightest,
      indexed1 = plt.chariotReins,
      indexed2 = plt.allSwift,
    },
  }
end

return {
  name = "Svartálfheim – Álsviðr",
  author = "PrismPunk",
  description = "Sun's horse — all-swift, solar chariot, day-bringer, tireless runner. "
    .. "Álsviðr is one of the two divine horses that pull the chariot of the sun across "
    .. "the sky, alongside his companion Árvakr. Their names mean 'All-Swift' and "
    .. "'Early Awake', and they race tirelessly across the heavens each day carrying "
    .. "the sun goddess Sól. The gods placed cooling runes beneath their shoulders "
    .. "to protect them from the unbearable heat of the sun they draw. Without their "
    .. "speed the world would fall into darkness. This palette reflects that blazing "
    .. "solar energy — deep golden dusk tones rising into radiant sunlight and "
    .. "blinding white daylight at the peak of the sky.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.solarFlare,
    base09 = palette.dawnRace,
    base0A = palette.skyPath,
    base0B = palette.blazingShoulder,
    base0C = palette.coolingRunes,
    base0D = palette.earlyWake,
    base0E = palette.allSwift,
    base0F = palette.chariotReins,
  },
  palette = palette,
  get = M.get,
}
