local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0c0a04",
  bg_darker = "#181408",
  bg_dark = "#241e0c",
  bg_mid = "#302810",
  bg_light = "#3c3214",
  bg_lighter = "#483c18",
  bg_lightest = "#54461c",
  bg_alt1 = "#605020",
  bg_alt2 = "#6c5a24",
  bg_alt3 = "#786428",
  bg_alt4 = "#846e2c",
  fg_darkest = "#fffad4",
  fg_dark = "#fff5a7",
  fg_mid = "#ffeb7a",
  fg_light = "#ffe14d",
  fg_lighter = "#ffd700",
  fg_lightest = "#fffffa",
  cursedGold = "#c0a040",
  dragonHoard = "#b4963c",
  doomBringer = "#a88c38",
  endlessWealth = "#9c8234",
  fatalRing = "#907830",
  greedCurse = "#846e2c",
  goldenDoom = "#ffd700",
  shiningCurse = "#ffe14d",
  fatedGold = "#ffeb7a",
  andvariWealth = "#fff5a7",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.cursedGold,
      insert = plt.dragonHoard,
      visual = plt.doomBringer,
      replace = plt.endlessWealth,
      command = plt.fatalRing,
    },
    accent = {
      accent1 = plt.cursedGold,
      accent2 = plt.dragonHoard,
      accent3 = plt.doomBringer,
      accent4 = plt.fg_light,
      accent5 = plt.endlessWealth,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.cursedGold,
      rainbow2 = plt.dragonHoard,
      rainbow3 = plt.doomBringer,
      rainbow4 = plt.endlessWealth,
      rainbow5 = plt.fatalRing,
      rainbow6 = plt.greedCurse,
      rainbow7 = plt.goldenDoom,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.doomBringer,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.cursedGold,
      header2 = plt.endlessWealth,
      special = plt.fatalRing,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.dragonHoard,
      indent = plt.bg_light,
      indent_scope = plt.cursedGold,
      picker = plt.doomBringer,
      yank = plt.fatalRing,
      mark = plt.goldenDoom,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_light,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.cursedGold,
        indicator = plt.endlessWealth,
      },
    },
    syn = {
      attribute = plt.fatalRing,
      boolean = plt.goldenDoom,
      comment = plt.bg_alt3,
      constant = plt.doomBringer,
      deprecated = plt.bg_alt2,
      func = plt.endlessWealth,
      identifier = plt.fg_light,
      keyword = plt.goldenDoom,
      method = plt.endlessWealth,
      number = plt.doomBringer,
      operator = plt.dragonHoard,
      parameter = plt.shiningCurse,
      preproc = plt.fatalRing,
      punct = plt.bg_alt3,
      regex = plt.goldenDoom,
      special = plt.fatalRing,
      special2 = plt.goldenDoom,
      special3 = plt.shiningCurse,
      statement = plt.goldenDoom,
      string = plt.endlessWealth,
      symbol = plt.dragonHoard,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.endlessWealth,
      warning = plt.doomBringer,
      info = plt.cursedGold,
      ok = plt.fatedGold,
      hint = plt.fatalRing,
      virtual_text_error = plt.endlessWealth,
      virtual_text_warning = plt.doomBringer,
      virtual_text_info = plt.cursedGold,
      virtual_text_ok = plt.fatedGold,
      virtual_text_hint = plt.fatalRing,
    },
    diff = {
      add = plt.fatedGold,
      add_inline = plt.dragonHoard,
      change = plt.doomBringer,
      change_inline = plt.goldenDoom,
      delete = plt.endlessWealth,
      delete_inline = plt.cursedGold,
      text = plt.fatalRing,
    },
    vcs = {
      added = plt.fatedGold,
      changed = plt.doomBringer,
      removed = plt.endlessWealth,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.endlessWealth,
      green = plt.fatedGold,
      yellow = plt.fatalRing,
      blue = plt.cursedGold,
      magenta = plt.doomBringer,
      cyan = plt.dragonHoard,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.endlessWealth):brighten(0.2):to_hex(),
      green_bright = color(plt.fatedGold):brighten(0.15):to_hex(),
      yellow_bright = color(plt.fatalRing):brighten(0.15):to_hex(),
      blue_bright = color(plt.cursedGold):brighten(0.15):to_hex(),
      magenta_bright = color(plt.doomBringer):brighten(0.2):to_hex(),
      cyan_bright = color(plt.dragonHoard):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.shiningCurse,
      indexed2 = plt.goldenDoom,
    },
  }
end

return {
  name = "Svartálfheim – Andvaranautr",
  author = "PrismPunk",
  description = "Andvari's ring — cursed gold, dragon's hoard, doom-bringer, endless wealth. "
    .. "Andvaranautr is the cursed ring of the dwarf Andvari, taken by Loki to pay the "
    .. "blood-price for Ótr's death. Andvari cursed the gold, declaring it would bring "
    .. "death to all who possessed it. The ring passed through many hands — Hreidmar, "
    .. "Fáfnir who became a dragon to guard it, Sigurd who slew the dragon, and finally "
    .. "to the Nibelungs where it brought ruin to all. This is gold that glitters with "
    .. "fatal beauty, wealth that corrupts, treasure that destroys. The palette moves "
    .. "from deep shadow through rich golden browns to brilliant cursed gold, capturing "
    .. "the seductive gleam of doom itself.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.endlessWealth,
    base09 = palette.doomBringer,
    base0A = palette.shiningCurse,
    base0B = palette.fatedGold,
    base0C = palette.fatalRing,
    base0D = palette.cursedGold,
    base0E = palette.dragonHoard,
    base0F = palette.goldenDoom,
  },
  palette = palette,
  get = M.get,
}
