local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0604",
  bg_darker = "#140c08",
  bg_dark = "#1e120c",
  bg_mid = "#281810",
  bg_light = "#321e14",
  bg_lighter = "#3c2418",
  bg_lightest = "#462a1c",
  bg_alt1 = "#503020",
  bg_alt2 = "#5a3624",
  bg_alt3 = "#643c28",
  bg_alt4 = "#6e422c",
  fg_darkest = "#ffdccc",
  fg_dark = "#ffc899",
  fg_mid = "#ffb466",
  fg_light = "#ffa033",
  fg_lighter = "#ff8c00",
  fg_lightest = "#fffcf8",
  dwarvenMasterwork = "#a06040",
  beautysPrice = "#965a3c",
  stolenTreasure = "#8c5438",
  amberFire = "#824e34",
  necklaceGlow = "#784830",
  freyjasGold = "#6e422c",
  radiantAmber = "#ff8c00",
  goldenBeauty = "#ffa033",
  warmGlow = "#ffb466",
  treasuredLight = "#ffc899",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.dwarvenMasterwork,
      insert = plt.beautysPrice,
      visual = plt.stolenTreasure,
      replace = plt.amberFire,
      command = plt.necklaceGlow,
    },
    accent = {
      accent1 = plt.dwarvenMasterwork,
      accent2 = plt.beautysPrice,
      accent3 = plt.stolenTreasure,
      accent4 = plt.fg_light,
      accent5 = plt.amberFire,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.dwarvenMasterwork,
      rainbow2 = plt.beautysPrice,
      rainbow3 = plt.stolenTreasure,
      rainbow4 = plt.amberFire,
      rainbow5 = plt.necklaceGlow,
      rainbow6 = plt.freyjasGold,
      rainbow7 = plt.radiantAmber,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.stolenTreasure,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.dwarvenMasterwork,
      header2 = plt.amberFire,
      special = plt.necklaceGlow,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.beautysPrice,
      indent = plt.bg_light,
      indent_scope = plt.dwarvenMasterwork,
      picker = plt.stolenTreasure,
      yank = plt.necklaceGlow,
      mark = plt.radiantAmber,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_light,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.dwarvenMasterwork,
        indicator = plt.amberFire,
      },
    },
    syn = {
      attribute = plt.necklaceGlow,
      boolean = plt.radiantAmber,
      comment = plt.bg_alt3,
      constant = plt.stolenTreasure,
      deprecated = plt.bg_alt2,
      func = plt.amberFire,
      identifier = plt.fg_light,
      keyword = plt.radiantAmber,
      method = plt.amberFire,
      number = plt.stolenTreasure,
      operator = plt.beautysPrice,
      parameter = plt.goldenBeauty,
      preproc = plt.necklaceGlow,
      punct = plt.bg_alt3,
      regex = plt.radiantAmber,
      special = plt.necklaceGlow,
      special2 = plt.radiantAmber,
      special3 = plt.goldenBeauty,
      statement = plt.radiantAmber,
      string = plt.amberFire,
      symbol = plt.beautysPrice,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.amberFire,
      warning = plt.stolenTreasure,
      info = plt.dwarvenMasterwork,
      ok = plt.warmGlow,
      hint = plt.necklaceGlow,
      virtual_text_error = plt.amberFire,
      virtual_text_warning = plt.stolenTreasure,
      virtual_text_info = plt.dwarvenMasterwork,
      virtual_text_ok = plt.warmGlow,
      virtual_text_hint = plt.necklaceGlow,
    },
    diff = {
      add = plt.warmGlow,
      add_inline = plt.beautysPrice,
      change = plt.stolenTreasure,
      change_inline = plt.radiantAmber,
      delete = plt.amberFire,
      delete_inline = plt.dwarvenMasterwork,
      text = plt.necklaceGlow,
    },
    vcs = {
      added = plt.warmGlow,
      changed = plt.stolenTreasure,
      removed = plt.amberFire,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.amberFire,
      green = plt.warmGlow,
      yellow = plt.necklaceGlow,
      blue = plt.dwarvenMasterwork,
      magenta = plt.stolenTreasure,
      cyan = plt.beautysPrice,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.amberFire):brighten(0.2):to_hex(),
      green_bright = color(plt.warmGlow):brighten(0.15):to_hex(),
      yellow_bright = color(plt.necklaceGlow):brighten(0.15):to_hex(),
      blue_bright = color(plt.dwarvenMasterwork):brighten(0.15):to_hex(),
      magenta_bright = color(plt.stolenTreasure):brighten(0.2):to_hex(),
      cyan_bright = color(plt.beautysPrice):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.goldenBeauty,
      indexed2 = plt.radiantAmber,
    },
  }
end

return {
  name = "Svartálfheim – Brísingamen",
  author = "PrismPunk",
  description = "Freyja's necklace — dwarven masterwork, beauty's price, stolen treasure, amber fire. "
    .. "Brísingamen is the most beautiful necklace ever crafted, forged by four dwarven "
    .. "brothers — Alfrigg, Dvalinn, Berling, and Grerr. Freyja desired it so greatly "
    .. "that she spent one night with each dwarf to obtain it. The necklace shines with "
    .. "the fire of amber and gold, a masterwork of dwarven craft that enhances Freyja's "
    .. "already incomparable beauty. Loki once stole it at Odin's command, but Heimdall "
    .. "recovered it after a fierce battle. This is beauty that demands sacrifice, craft "
    .. "that transcends mortal skill, treasure worth any price. The palette moves from "
    .. "deep earth browns through rich amber to brilliant orange-gold fire.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.amberFire,
    base09 = palette.stolenTreasure,
    base0A = palette.goldenBeauty,
    base0B = palette.warmGlow,
    base0C = palette.necklaceGlow,
    base0D = palette.dwarvenMasterwork,
    base0E = palette.beautysPrice,
    base0F = palette.radiantAmber,
  },
  palette = palette,
  get = M.get,
}
