local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0d0806",
  bg_darker = "#1a100c",
  bg_dark = "#271812",
  bg_mid = "#342018",
  bg_light = "#41281e",
  bg_lighter = "#4e3024",
  bg_lightest = "#5b382a",
  bg_alt1 = "#684030",
  bg_alt2 = "#754836",
  bg_alt3 = "#82503c",
  bg_alt4 = "#8f5842",
  fg_darkest = "#b8926e",
  fg_dark = "#c9a482",
  fg_mid = "#dab696",
  fg_light = "#ebc8aa",
  fg_lighter = "#fcdabe",
  fg_lightest = "#fff5eb",
  bellowsPump = "#9d6b47",
  forgeGlow = "#b87d53",
  moltenMetal = "#d38f5f",
  hammerRing = "#eea16b",
  coolingSteel = "#7a8c9e",
  tempered = "#8a9cae",
  polished = "#9aacbe",
  masterwork = "#aabcce",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.forgeGlow,
      insert = plt.coolingSteel,
      visual = plt.bellowsPump,
      replace = plt.moltenMetal,
      command = plt.tempered,
    },
    accent = {
      accent1 = plt.forgeGlow,
      accent2 = plt.coolingSteel,
      accent3 = plt.bellowsPump,
      accent4 = plt.moltenMetal,
      accent5 = plt.tempered,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.forgeGlow,
      rainbow2 = plt.moltenMetal,
      rainbow3 = plt.hammerRing,
      rainbow4 = plt.coolingSteel,
      rainbow5 = plt.tempered,
      rainbow6 = plt.polished,
      rainbow7 = plt.bellowsPump,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_lighter,
      fg_dimmer = plt.fg_light,
      fg_dark = plt.fg_mid,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.bellowsPump,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.forgeGlow,
      header2 = plt.coolingSteel,
      special = plt.tempered,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.coolingSteel,
      indent = plt.bg_light,
      indent_scope = plt.forgeGlow,
      picker = plt.bellowsPump,
      yank = plt.tempered,
      mark = plt.moltenMetal,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_light,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.forgeGlow,
        indicator = plt.coolingSteel,
      },
    },
    syn = {
      attribute = plt.tempered,
      boolean = plt.moltenMetal,
      comment = plt.bg_alt3,
      constant = plt.bellowsPump,
      deprecated = plt.bg_alt2,
      func = plt.coolingSteel,
      identifier = plt.fg_light,
      keyword = plt.moltenMetal,
      method = plt.coolingSteel,
      number = plt.bellowsPump,
      operator = plt.forgeGlow,
      parameter = plt.hammerRing,
      preproc = plt.tempered,
      punct = plt.bg_alt3,
      regex = plt.moltenMetal,
      special = plt.tempered,
      special2 = plt.moltenMetal,
      special3 = plt.hammerRing,
      statement = plt.moltenMetal,
      string = plt.coolingSteel,
      symbol = plt.forgeGlow,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.bellowsPump,
      warning = plt.moltenMetal,
      info = plt.coolingSteel,
      ok = plt.polished,
      hint = plt.tempered,
      virtual_text_error = plt.bellowsPump,
      virtual_text_warning = plt.moltenMetal,
      virtual_text_info = plt.coolingSteel,
      virtual_text_ok = plt.polished,
      virtual_text_hint = plt.tempered,
    },
    diff = {
      add = plt.polished,
      add_inline = plt.coolingSteel,
      change = plt.moltenMetal,
      change_inline = plt.hammerRing,
      delete = plt.bellowsPump,
      delete_inline = plt.forgeGlow,
      text = plt.tempered,
    },
    vcs = {
      added = plt.polished,
      changed = plt.moltenMetal,
      removed = plt.bellowsPump,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.bellowsPump,
      green = plt.polished,
      yellow = plt.hammerRing,
      blue = plt.coolingSteel,
      magenta = plt.moltenMetal,
      cyan = plt.tempered,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.bellowsPump):brighten(0.2):to_hex(),
      green_bright = color(plt.polished):brighten(0.15):to_hex(),
      yellow_bright = color(plt.hammerRing):brighten(0.15):to_hex(),
      blue_bright = color(plt.coolingSteel):brighten(0.15):to_hex(),
      magenta_bright = color(plt.moltenMetal):brighten(0.2):to_hex(),
      cyan_bright = color(plt.tempered):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.masterwork,
      indexed2 = plt.forgeGlow,
    },
  }
end

return {
  name = "Svartálfheim – Brokkr",
  author = "PrismPunk",
  description = "Master smith — Eitri's brother, Loki's challenger, Mjolnir's maker, skilled craftsman. "
    .. "Brokkr is one of the greatest dwarven smiths, brother to Eitri (also called Sindri). "
    .. "When Loki wagered his head that the brothers couldn't forge treasures as fine as "
    .. "the Sons of Ivaldi, Brokkr and Eitri accepted the challenge. While Eitri worked "
    .. "the forge, Brokkr pumped the bellows without pause, even when Loki (as a fly) bit "
    .. "him repeatedly to disrupt the work. Together they forged Gullinbursti (the golden "
    .. "boar), Draupnir (the ring that drips gold), and Mjolnir (Thor's hammer) — though "
    .. "the hammer's handle was slightly short due to Loki's interference. Despite this "
    .. "flaw, the gods judged Mjolnir the finest treasure, and Brokkr won the wager. This "
    .. "is mastery through persistence, craft that overcomes sabotage, skill that creates "
    .. "legends. The palette contrasts warm forge tones with cool tempered steel.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.bellowsPump,
    base09 = palette.moltenMetal,
    base0A = palette.hammerRing,
    base0B = palette.polished,
    base0C = palette.tempered,
    base0D = palette.coolingSteel,
    base0E = palette.forgeGlow,
    base0F = palette.masterwork,
  },
  palette = palette,
  get = M.get,
}
