local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0808",
  bg_darker = "#141010",
  bg_dark = "#1e1818",
  bg_mid = "#282020",
  bg_light = "#322828",
  bg_lighter = "#3c3030",
  bg_lightest = "#463838",
  bg_alt1 = "#504040",
  bg_alt2 = "#5a4848",
  bg_alt3 = "#645050",
  bg_alt4 = "#6e5858",
  fg_darkest = "#fcd693",
  fg_dark = "#fde0a8",
  fg_mid = "#feeabd",
  fg_light = "#fff4d2",
  fg_lighter = "#fffae7",
  fg_lightest = "#ffffff",
  runeCarving = "#b8860b",
  ancientKnowledge = "#c99a2d",
  masterwork = "#daae4f",
  goldenThread = "#ebc271",
  brisingamenGlow = "#fcd693",
  dwarvenWisdom = "#786060",
  forgeMemory = "#826868",
  craftLegacy = "#8c7070",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.masterwork,
      insert = plt.goldenThread,
      visual = plt.runeCarving,
      replace = plt.brisingamenGlow,
      command = plt.ancientKnowledge,
    },
    accent = {
      accent1 = plt.masterwork,
      accent2 = plt.goldenThread,
      accent3 = plt.runeCarving,
      accent4 = plt.brisingamenGlow,
      accent5 = plt.ancientKnowledge,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.runeCarving,
      rainbow2 = plt.ancientKnowledge,
      rainbow3 = plt.masterwork,
      rainbow4 = plt.goldenThread,
      rainbow5 = plt.brisingamenGlow,
      rainbow6 = plt.dwarvenWisdom,
      rainbow7 = plt.forgeMemory,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_lighter,
      fg_dimmer = plt.fg_light,
      fg_dark = plt.fg_mid,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.masterwork,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.masterwork,
      header2 = plt.goldenThread,
      special = plt.runeCarving,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.ancientKnowledge,
      indent = plt.bg_light,
      indent_scope = plt.masterwork,
      picker = plt.brisingamenGlow,
      yank = plt.goldenThread,
      mark = plt.runeCarving,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_dark,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.masterwork,
        indicator = plt.goldenThread,
      },
    },
    syn = {
      attribute = plt.runeCarving,
      boolean = plt.brisingamenGlow,
      comment = plt.dwarvenWisdom,
      constant = plt.goldenThread,
      deprecated = plt.bg_alt2,
      func = plt.ancientKnowledge,
      identifier = plt.fg_light,
      keyword = plt.masterwork,
      method = plt.ancientKnowledge,
      number = plt.goldenThread,
      operator = plt.runeCarving,
      parameter = plt.brisingamenGlow,
      preproc = plt.runeCarving,
      punct = plt.forgeMemory,
      regex = plt.craftLegacy,
      special = plt.runeCarving,
      special2 = plt.masterwork,
      special3 = plt.brisingamenGlow,
      statement = plt.masterwork,
      string = plt.goldenThread,
      symbol = plt.ancientKnowledge,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.runeCarving,
      warning = plt.ancientKnowledge,
      info = plt.masterwork,
      ok = plt.brisingamenGlow,
      hint = plt.goldenThread,
      virtual_text_error = plt.runeCarving,
      virtual_text_warning = plt.ancientKnowledge,
      virtual_text_info = plt.masterwork,
      virtual_text_ok = plt.brisingamenGlow,
      virtual_text_hint = plt.goldenThread,
    },
    diff = {
      add = plt.brisingamenGlow,
      add_inline = plt.goldenThread,
      change = plt.ancientKnowledge,
      change_inline = plt.masterwork,
      delete = plt.runeCarving,
      delete_inline = plt.dwarvenWisdom,
      text = plt.craftLegacy,
    },
    vcs = {
      added = plt.brisingamenGlow,
      changed = plt.ancientKnowledge,
      removed = plt.runeCarving,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.runeCarving,
      green = plt.brisingamenGlow,
      yellow = plt.goldenThread,
      blue = plt.masterwork,
      magenta = plt.ancientKnowledge,
      cyan = plt.craftLegacy,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.runeCarving):brighten(0.2):to_hex(),
      green_bright = color(plt.brisingamenGlow):brighten(0.15):to_hex(),
      yellow_bright = color(plt.goldenThread):brighten(0.15):to_hex(),
      blue_bright = color(plt.masterwork):brighten(0.15):to_hex(),
      magenta_bright = color(plt.ancientKnowledge):brighten(0.2):to_hex(),
      cyan_bright = color(plt.craftLegacy):brighten(0.15):to_hex(),
      white_bright = plt.fg_lightest,
      indexed1 = plt.forgeMemory,
      indexed2 = plt.dwarvenWisdom,
    },
  }
end

return {
  name = "Svartálfheim – Dvalinn",
  author = "PrismPunk",
  description = "Master craftsman — rune-carver, Brisingamen maker, legendary dwarf, ancient smith. "
    .. "Dvalinn is one of the four greatest dwarven craftsmen, renowned for his mastery "
    .. "of rune-carving and metalwork. He helped create Freyja's legendary necklace "
    .. "Brisingamen, one of the most beautiful treasures in all the Nine Realms. His "
    .. "knowledge of ancient runes and smithing techniques has been passed down through "
    .. "generations of dwarven craftsmen. This palette moves from deep charcoal forge "
    .. "shadows through warm earth tones to brilliant golden light — representing the "
    .. "transformation of raw materials into legendary artifacts through skill and wisdom.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.runeCarving,
    base09 = palette.ancientKnowledge,
    base0A = palette.goldenThread,
    base0B = palette.brisingamenGlow,
    base0C = palette.craftLegacy,
    base0D = palette.masterwork,
    base0E = palette.dwarvenWisdom,
    base0F = palette.forgeMemory,
  },
  palette = palette,
  get = M.get,
}
