local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0c0402",
  bg_darker = "#180804",
  bg_dark = "#240c06",
  bg_mid = "#301008",
  bg_light = "#3c140a",
  bg_lighter = "#48180c",
  bg_lightest = "#541c0e",
  bg_alt1 = "#602010",
  bg_alt2 = "#6c2412",
  bg_alt3 = "#782814",
  bg_alt4 = "#842c16",
  fg_darkest = "#ff937e",
  fg_dark = "#ffada8",
  fg_mid = "#ffc7c2",
  fg_light = "#ffe1dc",
  fg_lighter = "#fff0ee",
  fg_lightest = "#ffffff",
  forgeMaster = "#ff4500",
  divineWeapons = "#ff5f2a",
  brokkrsBrother = "#ff7954",
  unmatchedSkill = "#ff937e",
  heatRising = "#903018",
  emberGlow = "#9c341a",
  moltenCore = "#a8381c",
  whiteHeat = "#fff8f7",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.forgeMaster,
      insert = plt.divineWeapons,
      visual = plt.heatRising,
      replace = plt.brokkrsBrother,
      command = plt.emberGlow,
    },
    accent = {
      accent1 = plt.forgeMaster,
      accent2 = plt.divineWeapons,
      accent3 = plt.brokkrsBrother,
      accent4 = plt.unmatchedSkill,
      accent5 = plt.heatRising,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.forgeMaster,
      rainbow2 = plt.divineWeapons,
      rainbow3 = plt.brokkrsBrother,
      rainbow4 = plt.unmatchedSkill,
      rainbow5 = plt.heatRising,
      rainbow6 = plt.emberGlow,
      rainbow7 = plt.moltenCore,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_lighter,
      fg_dimmer = plt.fg_light,
      fg_dark = plt.fg_mid,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.heatRising,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.forgeMaster,
      header2 = plt.divineWeapons,
      special = plt.emberGlow,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.divineWeapons,
      indent = plt.bg_light,
      indent_scope = plt.forgeMaster,
      picker = plt.heatRising,
      yank = plt.emberGlow,
      mark = plt.brokkrsBrother,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_dark,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.forgeMaster,
        indicator = plt.divineWeapons,
      },
    },
    syn = {
      attribute = plt.emberGlow,
      boolean = plt.brokkrsBrother,
      comment = plt.bg_alt3,
      constant = plt.heatRising,
      deprecated = plt.bg_alt2,
      func = plt.divineWeapons,
      identifier = plt.fg_light,
      keyword = plt.brokkrsBrother,
      method = plt.divineWeapons,
      number = plt.heatRising,
      operator = plt.forgeMaster,
      parameter = plt.unmatchedSkill,
      preproc = plt.emberGlow,
      punct = plt.bg_alt3,
      regex = plt.brokkrsBrother,
      special = plt.emberGlow,
      special2 = plt.brokkrsBrother,
      special3 = plt.unmatchedSkill,
      statement = plt.brokkrsBrother,
      string = plt.divineWeapons,
      symbol = plt.forgeMaster,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.forgeMaster,
      warning = plt.brokkrsBrother,
      info = plt.divineWeapons,
      ok = plt.whiteHeat,
      hint = plt.emberGlow,
      virtual_text_error = plt.forgeMaster,
      virtual_text_warning = plt.brokkrsBrother,
      virtual_text_info = plt.divineWeapons,
      virtual_text_ok = plt.whiteHeat,
      virtual_text_hint = plt.emberGlow,
    },
    diff = {
      add = plt.whiteHeat,
      add_inline = plt.divineWeapons,
      change = plt.brokkrsBrother,
      change_inline = plt.unmatchedSkill,
      delete = plt.forgeMaster,
      delete_inline = plt.heatRising,
      text = plt.emberGlow,
    },
    vcs = {
      added = plt.whiteHeat,
      changed = plt.brokkrsBrother,
      removed = plt.forgeMaster,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.forgeMaster,
      green = plt.whiteHeat,
      yellow = plt.unmatchedSkill,
      blue = plt.divineWeapons,
      magenta = plt.brokkrsBrother,
      cyan = plt.emberGlow,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.forgeMaster):brighten(0.2):to_hex(),
      green_bright = color(plt.whiteHeat):brighten(0.15):to_hex(),
      yellow_bright = color(plt.unmatchedSkill):brighten(0.15):to_hex(),
      blue_bright = color(plt.divineWeapons):brighten(0.15):to_hex(),
      magenta_bright = color(plt.brokkrsBrother):brighten(0.2):to_hex(),
      cyan_bright = color(plt.emberGlow):brighten(0.15):to_hex(),
      white_bright = plt.fg_lightest,
      indexed1 = plt.moltenCore,
      indexed2 = plt.heatRising,
    },
  }
end

return {
  name = "Svartálfheim – Eitri",
  author = "PrismPunk",
  description = "Master smith — forge master, divine weapons, Brokkr's brother, unmatched skill. "
    .. "Eitri (also called Sindri) is the greatest of the dwarven smiths, brother to Brokkr. "
    .. "When Loki challenged them to forge treasures finer than the Sons of Ivaldi, Eitri "
    .. "worked the forge while Brokkr pumped the bellows. Despite Loki's interference (as a "
    .. "fly biting Brokkr), Eitri forged three legendary treasures: Gullinbursti (the golden "
    .. "boar for Freyr), Draupnir (the self-replicating ring for Odin), and Mjolnir (Thor's "
    .. "hammer). Though Mjolnir's handle was shortened by Loki's sabotage, the gods judged "
    .. "it the finest treasure ever made. Eitri's skill is absolute — he creates weapons "
    .. "and artifacts for the gods themselves. This is mastery at its peak, the forge at "
    .. "white heat, divine craft made manifest. The palette burns from deep forge darkness "
    .. "through intense orange-red to brilliant white heat.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.forgeMaster,
    base09 = palette.brokkrsBrother,
    base0A = palette.unmatchedSkill,
    base0B = palette.whiteHeat,
    base0C = palette.emberGlow,
    base0D = palette.divineWeapons,
    base0E = palette.heatRising,
    base0F = palette.moltenCore,
  },
  palette = palette,
  get = M.get,
}
