local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1e1a",
  bg_darker = "#242a24",
  bg_dark = "#2e362e",
  bg_mid = "#384238",
  bg_light = "#424e42",
  bg_lighter = "#4c5a4c",
  bg_lightest = "#566656",
  bg_alt1 = "#2a322a",
  bg_alt2 = "#3d453d",
  bg_alt3 = "#505850",
  bg_alt4 = "#636b63",
  fg_lightest = "#d8ffd8",
  fg_light = "#c4eac4",
  fg_mid = "#92ae92",
  fg_dark = "#748a74",
  rootBlack = "#1a1e1a",
  barkShadow = "#242a24",
  underworldMoss = "#2a322a",
  muspelEmber = "#D06868",
  midgardDawn = "#BF7E9E",
  runeAmber = "#C4884A",
  asgardGold = "#D4AA5C",
  rootGreen = "#7EBF6E",
  urdWell = "#5CA8A8",
  niflFrost = "#6E9ECF",
  bifrostShimmer = "#9E7EBF",
  nornsGlow = "#B8D48A",
  worldAsh = "#A8C0A0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.niflFrost,
      insert = plt.rootGreen,
      visual = plt.bifrostShimmer,
      replace = plt.muspelEmber,
      command = plt.asgardGold,
    },

    accent = {
      accent1 = plt.niflFrost,
      accent2 = plt.runeAmber,
      accent3 = plt.urdWell,
      accent4 = plt.fg_light,
      accent5 = plt.muspelEmber,
      invert = plt.bg_mid,
    },

    rainbow = {
      rainbow1 = plt.muspelEmber,
      rainbow2 = plt.midgardDawn,
      rainbow3 = plt.asgardGold,
      rainbow4 = plt.runeAmber,
      rainbow5 = plt.rootGreen,
      rainbow6 = plt.niflFrost,
      rainbow7 = plt.urdWell,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.nornsGlow,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.asgardGold,
      header2 = plt.niflFrost,
      special = plt.worldAsh,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.bifrostShimmer,
      indent = plt.bg_light,
      indent_scope = plt.niflFrost,
      picker = plt.bifrostShimmer,
      yank = plt.nornsGlow,
      mark = plt.muspelEmber,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.asgardGold,
        indicator = plt.niflFrost,
      },
    },

    syn = {
      attribute = plt.asgardGold,
      boolean = plt.runeAmber,
      comment = plt.fg_mid,
      constant = plt.runeAmber,
      deprecated = plt.fg_dark,
      func = plt.niflFrost,
      identifier = plt.fg_lightest,
      keyword = plt.midgardDawn,
      method = plt.niflFrost,
      number = plt.midgardDawn,
      operator = plt.muspelEmber,
      parameter = plt.worldAsh,
      preproc = plt.bifrostShimmer,
      punct = plt.fg_mid,
      regex = plt.asgardGold,
      special = plt.asgardGold,
      special2 = plt.bifrostShimmer,
      special3 = plt.urdWell,
      statement = plt.bifrostShimmer,
      string = plt.rootGreen,
      symbol = plt.muspelEmber,
      type = plt.urdWell,
      variable = plt.fg_lightest,
    },

    diag = {
      error = plt.muspelEmber,
      warning = plt.asgardGold,
      info = plt.niflFrost,
      ok = plt.rootGreen,
      hint = plt.urdWell,
      virtual_text_error = plt.muspelEmber,
      virtual_text_warning = plt.asgardGold,
      virtual_text_info = plt.niflFrost,
      virtual_text_ok = plt.rootGreen,
      virtual_text_hint = plt.urdWell,
    },

    diff = {
      add = plt.rootGreen,
      add_inline = plt.urdWell,
      change = plt.asgardGold,
      change_inline = plt.runeAmber,
      delete = plt.muspelEmber,
      delete_inline = plt.midgardDawn,
      text = plt.niflFrost,
    },

    vcs = {
      added = plt.rootGreen,
      changed = plt.asgardGold,
      removed = plt.muspelEmber,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.muspelEmber,
      green = plt.rootGreen,
      yellow = plt.asgardGold,
      blue = plt.niflFrost,
      magenta = plt.midgardDawn,
      cyan = plt.urdWell,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.muspelEmber):brighten(0.2):to_hex(),
      green_bright = color(plt.rootGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.asgardGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.niflFrost):brighten(0.3):to_hex(),
      magenta_bright = color(plt.midgardDawn):brighten(0.2):to_hex(),
      cyan_bright = color(plt.urdWell):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.worldAsh,
      indexed2 = plt.nornsGlow,
    },
  }
end

return {
  name = "Yggdrasill – Askr",
  author = "PrismPunk",
  description = "The World Tree's heartwood — ancient bark, deep root-shadows, and cosmic green-grey canopy lit by rune-gold and frost-light. A palette drawn from Norse myth: Muspelheim embers, Niflheim frost, the Norns' glow, and the iridescent shimmer of the Bifrost.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.muspelEmber,
    base09 = palette.runeAmber,
    base0A = palette.asgardGold,
    base0B = palette.rootGreen,
    base0C = palette.urdWell,
    base0D = palette.niflFrost,
    base0E = palette.bifrostShimmer,
    base0F = palette.midgardDawn,
  },
  palette = palette,
  get = M.get,
}
