local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1e1a",
  bg_darker = "#242a24",
  bg_dark = "#2e362e",
  bg_mid = "#3a3226",
  bg_light = "#4a4032",
  bg_lighter = "#5a4e3e",
  bg_lightest = "#6a5c4a",
  bg_alt1 = "#2a322e",
  bg_alt2 = "#3d4542",
  bg_alt3 = "#3d4a3d",
  bg_alt4 = "#505d50",
  fg_lightest = "#fff6ce",
  fg_light = "#fadab6",
  fg_mid = "#9ca99c",
  fg_dark = "#768376",
  dawnShadow = "#1a1e1a",
  forestFloor = "#242a24",
  mossyBark = "#2e362e",
  groveDusk = "#3d4a3d",
  dawnAmber = "#dabe9e",
  morningGold = "#eaccaa",
  antlerIvory = "#fadab6",
  firstLight = "#ffe8c2",
  mistGlow = "#fff6ce",
  honeyWarm = "#cab092",
  fawnBrown = "#baa286",
  stagCoat = "#aa947a",
  mossGreen = "#899689",
  fernShade = "#637063",
  stoneGray = "#505d50",
  alertCoral = "#ff9a8a",
  rosebloom = "#ffb4aa",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.dawnAmber,
      insert = plt.mossGreen,
      visual = plt.morningGold,
      replace = plt.alertCoral,
      command = plt.antlerIvory,
    },
    accent = {
      accent1 = plt.dawnAmber,
      accent2 = plt.morningGold,
      accent3 = plt.antlerIvory,
      accent4 = plt.mossGreen,
      accent5 = plt.honeyWarm,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.dawnAmber,
      rainbow2 = plt.morningGold,
      rainbow3 = plt.antlerIvory,
      rainbow4 = plt.firstLight,
      rainbow5 = plt.honeyWarm,
      rainbow6 = plt.fawnBrown,
      rainbow7 = plt.stagCoat,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.mistGlow,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_mid,
      border = plt.stagCoat,
      header1 = plt.dawnAmber,
      header2 = plt.morningGold,
      special = plt.antlerIvory,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.honeyWarm,
      indent = plt.bg_mid,
      indent_scope = plt.dawnAmber,
      picker = plt.fawnBrown,
      yank = plt.mistGlow,
      mark = plt.antlerIvory,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.dawnAmber,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.morningGold,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.honeyWarm,
        bg = plt.bg_mid,
        bg_sel = plt.bg_light,
        bg_border = plt.bg_mid,
        bg_sbar = plt.bg_mid,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_mid,
        bg_alternate = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.dawnAmber,
        indicator = plt.morningGold,
      },
    },
    syn = {
      attribute = plt.antlerIvory,
      boolean = plt.alertCoral,
      comment = plt.fg_dark,
      constant = plt.alertCoral,
      deprecated = plt.fernShade,
      func = plt.dawnAmber,
      identifier = plt.fg_lightest,
      keyword = plt.morningGold,
      method = plt.honeyWarm,
      number = plt.mistGlow,
      operator = plt.fawnBrown,
      parameter = plt.mossGreen,
      preproc = plt.stagCoat,
      punct = plt.fg_mid,
      regex = plt.antlerIvory,
      special = plt.firstLight,
      special2 = plt.stagCoat,
      special3 = plt.rosebloom,
      statement = plt.morningGold,
      string = plt.honeyWarm,
      symbol = plt.dawnAmber,
      type = plt.mossGreen,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.alertCoral,
      warning = plt.dawnAmber,
      info = plt.honeyWarm,
      ok = plt.mossGreen,
      hint = plt.antlerIvory,
      virtual_text_error = plt.alertCoral,
      virtual_text_warning = plt.dawnAmber,
      virtual_text_info = plt.honeyWarm,
      virtual_text_ok = plt.mossGreen,
      virtual_text_hint = plt.antlerIvory,
    },
    diff = {
      add = plt.mossGreen,
      add_inline = plt.firstLight,
      change = plt.dawnAmber,
      change_inline = plt.morningGold,
      delete = plt.alertCoral,
      delete_inline = plt.rosebloom,
      text = plt.honeyWarm,
    },
    vcs = {
      added = plt.mossGreen,
      changed = plt.dawnAmber,
      removed = plt.alertCoral,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.alertCoral,
      green = plt.mossGreen,
      yellow = plt.dawnAmber,
      blue = plt.honeyWarm,
      magenta = plt.morningGold,
      cyan = plt.antlerIvory,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.8):to_hex(),
      red_bright = color(plt.alertCoral):brighten(0.2):to_hex(),
      green_bright = color(plt.mossGreen):brighten(0.15):to_hex(),
      yellow_bright = color(plt.dawnAmber):brighten(0.15):to_hex(),
      blue_bright = color(plt.honeyWarm):brighten(0.3):to_hex(),
      magenta_bright = color(plt.morningGold):brighten(0.2):to_hex(),
      cyan_bright = color(plt.antlerIvory):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.mistGlow,
      indexed2 = plt.firstLight,
    },
  }
end

return {
  name = "Yggdrasill – Dáinn",
  author = "PrismPunk",
  description = "The eastern stag grazing at dawn — warm amber light, antler ivory, morning mist rising through ancient branches.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.alertCoral,
    base09 = palette.dawnAmber,
    base0A = palette.mistGlow,
    base0B = palette.mossGreen,
    base0C = palette.antlerIvory,
    base0D = palette.honeyWarm,
    base0E = palette.morningGold,
    base0F = palette.firstLight,
  },
  palette = palette,
  get = M.get,
}
