local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1e1a",
  bg_darker = "#242a24",
  bg_dark = "#2e362e",
  bg_mid = "#3a2e26",
  bg_light = "#4a3a32",
  bg_lighter = "#5a463e",
  bg_lightest = "#6a524a",
  bg_alt1 = "#2a322e",
  bg_alt2 = "#3d4542",
  bg_alt3 = "#3d4a3d",
  bg_alt4 = "#505d50",
  fg_lightest = "#fabeb6",
  fg_light = "#eab2aa",
  fg_mid = "#9ca99c",
  fg_dark = "#768376",
  shadowEarth = "#1a1e1a",
  duskStone = "#242a24",
  clayBase = "#2e362e",
  desertSage = "#3d4a3d",
  terracotta = "#ca9a92",
  sunBaked = "#daa69e",
  warmClay = "#eab2aa",
  desertBloom = "#fabeb6",
  coralDust = "#ffcac2",
  peachGlow = "#ffd6ce",
  sageGreen = "#899689",
  drySage = "#768376",
  stoneGreen = "#637063",
  mossStone = "#505d50",
  earthShadow = "#3d4542",
  emberRed = "#ba8e86",
  rustOrange = "#aa827a",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.terracotta,
      insert = plt.sageGreen,
      visual = plt.sunBaked,
      replace = plt.coralDust,
      command = plt.warmClay,
    },
    accent = {
      accent1 = plt.terracotta,
      accent2 = plt.sunBaked,
      accent3 = plt.warmClay,
      accent4 = plt.sageGreen,
      accent5 = plt.emberRed,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.terracotta,
      rainbow2 = plt.sunBaked,
      rainbow3 = plt.warmClay,
      rainbow4 = plt.desertBloom,
      rainbow5 = plt.sageGreen,
      rainbow6 = plt.emberRed,
      rainbow7 = plt.drySage,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_alt1 or "none",
      bg_cursorline = plt.bg_alt2,
      bg_cursorline_alt = plt.bg_alt3,
      cursorline = plt.bg_alt2,
      bg_highlight = plt.bg_alt3,
      bg_search = plt.sunBaked,
      bg_visual = plt.bg_alt3,
      bg_statusline = plt.bg_mid,
      border = plt.emberRed,
      header1 = plt.terracotta,
      header2 = plt.sunBaked,
      special = plt.warmClay,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.drySage,
      indent = plt.bg_alt1,
      indent_scope = plt.terracotta,
      picker = plt.emberRed,
      yank = plt.sunBaked,
      mark = plt.warmClay,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_alt3,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.terracotta,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.emberRed,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.emberRed,
        bg = plt.bg_mid,
        bg_sel = plt.bg_light,
        bg_border = plt.bg_mid,
        bg_sbar = plt.bg_mid,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_alt3,
        bg_alternate = plt.bg_alt2,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.terracotta,
        indicator = plt.sunBaked,
      },
    },
    syn = {
      attribute = plt.warmClay,
      boolean = plt.coralDust,
      comment = plt.fg_dark,
      constant = plt.coralDust,
      deprecated = plt.stoneGreen,
      func = plt.terracotta,
      identifier = plt.fg_lightest,
      keyword = plt.terracotta,
      method = plt.emberRed,
      number = plt.peachGlow,
      operator = plt.sageGreen,
      parameter = plt.drySage,
      preproc = plt.emberRed,
      punct = plt.fg_mid,
      regex = plt.warmClay,
      special = plt.sunBaked,
      special2 = plt.sageGreen,
      special3 = plt.desertBloom,
      statement = plt.sunBaked,
      string = plt.sageGreen,
      symbol = plt.terracotta,
      type = plt.sunBaked,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.coralDust,
      warning = plt.terracotta,
      info = plt.emberRed,
      ok = plt.sageGreen,
      hint = plt.warmClay,
      virtual_text_error = plt.coralDust,
      virtual_text_warning = plt.terracotta,
      virtual_text_info = plt.emberRed,
      virtual_text_ok = plt.sageGreen,
      virtual_text_hint = plt.warmClay,
    },
    diff = {
      add = plt.sageGreen,
      add_inline = plt.drySage,
      change = plt.terracotta,
      change_inline = plt.sunBaked,
      delete = plt.coralDust,
      delete_inline = plt.peachGlow,
      text = plt.emberRed,
    },
    vcs = {
      added = plt.sageGreen,
      changed = plt.terracotta,
      removed = plt.coralDust,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.coralDust,
      green = plt.sageGreen,
      yellow = plt.terracotta,
      blue = plt.emberRed,
      magenta = plt.sunBaked,
      cyan = plt.warmClay,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.8):to_hex(),
      red_bright = color(plt.coralDust):brighten(0.2):to_hex(),
      green_bright = color(plt.sageGreen):brighten(0.15):to_hex(),
      yellow_bright = color(plt.terracotta):brighten(0.15):to_hex(),
      blue_bright = color(plt.emberRed):brighten(0.3):to_hex(),
      magenta_bright = color(plt.sunBaked):brighten(0.2):to_hex(),
      cyan_bright = color(plt.warmClay):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.desertBloom,
      indexed2 = plt.peachGlow,
    },
  }
end

return {
  name = "Yggdrasill – Duneyrr",
  author = "PrismPunk",
  description = "The southern stag of sun-baked lands — warm terracotta clay, desert sage, and earth touched by endless sun.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.coralDust,
    base09 = palette.terracotta,
    base0A = palette.warmClay,
    base0B = palette.sageGreen,
    base0C = palette.emberRed,
    base0D = palette.sunBaked,
    base0E = palette.desertBloom,
    base0F = palette.peachGlow,
  },
  palette = palette,
  get = M.get,
}
