local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1e1a",
  bg_darker = "#242a24",
  bg_dark = "#2e362e",
  bg_mid = "#3a2e3a",
  bg_light = "#4a3a4a",
  bg_lighter = "#5a465a",
  bg_lightest = "#6a526a",
  bg_alt1 = "#2a322e",
  bg_alt2 = "#3d4542",
  bg_alt3 = "#3d4a3d",
  bg_alt4 = "#505d50",
  fg_lightest = "#fabefa",
  fg_light = "#daa6da",
  fg_mid = "#9ca99c",
  fg_dark = "#768376",
  shadowDusk = "#1a1e1a",
  eveningStone = "#242a24",
  twilightBase = "#2e362e",
  duskViolet = "#3a2e3a",
  deepViolet = "#9a5a9a",
  amethyst = "#ca9aca",
  orchidGlow = "#daa6da",
  roseLight = "#eab2ea",
  fadingBloom = "#fabefa",
  softPink = "#ffcaff",
  blushMist = "#ffd6ff",
  sageGreen = "#899689",
  mossGreen = "#768376",
  stoneGreen = "#637063",
  forestShadow = "#505d50",
  earthTone = "#3d4542",
  lavender = "#ba8eba",
  plum = "#8a628a",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.amethyst,
      insert = plt.sageGreen,
      visual = plt.orchidGlow,
      replace = plt.softPink,
      command = plt.roseLight,
    },
    accent = {
      accent1 = plt.amethyst,
      accent2 = plt.orchidGlow,
      accent3 = plt.roseLight,
      accent4 = plt.sageGreen,
      accent5 = plt.lavender,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.deepViolet,
      rainbow2 = plt.amethyst,
      rainbow3 = plt.orchidGlow,
      rainbow4 = plt.roseLight,
      rainbow5 = plt.fadingBloom,
      rainbow6 = plt.sageGreen,
      rainbow7 = plt.lavender,
    },
    ui = {
      fg = plt.fadingBloom,
      fg_dim = plt.orchidGlow,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_alt1 or "none",
      bg_cursorline = plt.bg_alt2,
      bg_cursorline_alt = plt.bg_alt3,
      cursorline = plt.bg_alt2,
      bg_highlight = plt.bg_alt3,
      bg_search = plt.orchidGlow,
      bg_visual = plt.bg_alt3,
      bg_statusline = plt.bg_mid,
      border = plt.lavender,
      header1 = plt.deepViolet,
      header2 = plt.roseLight,
      special = plt.softPink,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.mossGreen,
      indent = plt.bg_alt1,
      indent_scope = plt.deepViolet,
      picker = plt.lavender,
      yank = plt.roseLight,
      mark = plt.softPink,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_alt3,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.deepViolet,
      float = {
        fg = plt.orchidGlow,
        bg = plt.bg_mid,
        fg_border = plt.lavender,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fadingBloom,
        fg_sel = "none",
        fg_border = plt.lavender,
        bg = plt.bg_mid,
        bg_sel = plt.bg_light,
        bg_border = plt.bg_mid,
        bg_sbar = plt.bg_mid,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_alt3,
        bg_alternate = plt.bg_alt2,
        fg_inactive = plt.plum,
        fg_selected = plt.fadingBloom,
        fg_alternate = plt.deepViolet,
        indicator = plt.roseLight,
      },
    },
    syn = {
      attribute = plt.softPink,
      boolean = plt.blushMist,
      comment = plt.fg_dark,
      constant = plt.blushMist,
      deprecated = plt.stoneGreen,
      func = plt.amethyst,
      identifier = plt.fadingBloom,
      keyword = plt.deepViolet,
      method = plt.orchidGlow,
      number = plt.softPink,
      operator = plt.sageGreen,
      parameter = plt.roseLight,
      preproc = plt.lavender,
      punct = plt.plum,
      regex = plt.roseLight,
      special = plt.softPink,
      special2 = plt.mossGreen,
      special3 = plt.blushMist,
      statement = plt.deepViolet,
      string = plt.sageGreen,
      symbol = plt.lavender,
      type = plt.amethyst,
      variable = plt.orchidGlow,
    },
    diag = {
      error = plt.softPink,
      warning = plt.amethyst,
      info = plt.lavender,
      ok = plt.sageGreen,
      hint = plt.roseLight,
      virtual_text_error = plt.softPink,
      virtual_text_warning = plt.amethyst,
      virtual_text_info = plt.lavender,
      virtual_text_ok = plt.sageGreen,
      virtual_text_hint = plt.roseLight,
    },
    diff = {
      add = plt.sageGreen,
      add_inline = plt.mossGreen,
      change = plt.amethyst,
      change_inline = plt.orchidGlow,
      delete = plt.softPink,
      delete_inline = plt.blushMist,
      text = plt.lavender,
    },
    vcs = {
      added = plt.sageGreen,
      changed = plt.amethyst,
      removed = plt.softPink,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.softPink,
      green = plt.sageGreen,
      yellow = plt.amethyst,
      blue = plt.lavender,
      magenta = plt.orchidGlow,
      cyan = plt.roseLight,
      white = plt.orchidGlow,
      black_bright = color(plt.bg_darkest):brighten(0.8):to_hex(),
      red_bright = color(plt.softPink):brighten(0.2):to_hex(),
      green_bright = color(plt.sageGreen):brighten(0.15):to_hex(),
      yellow_bright = color(plt.amethyst):brighten(0.15):to_hex(),
      blue_bright = color(plt.lavender):brighten(0.3):to_hex(),
      magenta_bright = color(plt.orchidGlow):brighten(0.2):to_hex(),
      cyan_bright = color(plt.roseLight):brighten(0.15):to_hex(),
      white_bright = color(plt.fadingBloom):brighten(0.1):to_hex(),
      indexed1 = plt.fadingBloom,
      indexed2 = plt.blushMist,
    },
  }
end

return {
  name = "Yggdrasill – Duraþrór",
  author = "PrismPunk",
  description = "The western stag of twilight hours — violet dusk, rose light fading, and the last glow before night.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.orchidGlow,
    base07 = palette.fadingBloom,
    base08 = palette.softPink,
    base09 = palette.deepViolet,
    base0A = palette.roseLight,
    base0B = palette.sageGreen,
    base0C = palette.lavender,
    base0D = palette.amethyst,
    base0E = palette.orchidGlow,
    base0F = palette.blushMist,
  },
  palette = palette,
  get = M.get,
}
