local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a2e2a",
  bg_darker = "#244238",
  bg_dark = "#2e5646",
  bg_mid = "#386a54",
  bg_light = "#427e62",
  bg_lighter = "#4c9270",
  bg_lightest = "#56a67e",
  bg_alt1 = "#1f3a32",
  bg_alt2 = "#2e4d44",
  bg_alt3 = "#3d6056",
  bg_alt4 = "#4c7368",
  fg_lightest = "#74e2a8",
  fg_light = "#60ba8c",
  fg_mid = "#56a67e",
  fg_dark = "#76867e",
  primordialDeep = "#1a2e2a",
  chaosBase = "#244238",
  sourceGreen = "#2e5646",
  originWater = "#386a54",
  riverBirth = "#427e62",
  churnGreen = "#4c9270",
  springFlow = "#56a67e",
  waterRush = "#60ba8c",
  cascadeGreen = "#6ace9a",
  torrentLight = "#74e2a8",
  foamGreen = "#8aeab6",
  mistSpray = "#a0f2c4",
  depthStone = "#1f3a32",
  ancientRock = "#2e4d44",
  stoneGreen = "#3d6056",
  mossStone = "#4c7368",
  weatheredGreen = "#76867e",
  ageGreen = "#899990",
  paleStone = "#9caca2",
  lichened = "#afbfb4",
  frostStone = "#c2d2c6",
  mistStone = "#d5e5d8",
  shadowGreen = "#2a3a36",
  duskGreen = "#3d4d48",
  midGreen = "#50605a",
  stoneGrey = "#63736c",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.springFlow,
      insert = plt.torrentLight,
      visual = plt.cascadeGreen,
      replace = plt.foamGreen,
      command = plt.waterRush,
    },
    accent = {
      accent1 = plt.springFlow,
      accent2 = plt.waterRush,
      accent3 = plt.cascadeGreen,
      accent4 = plt.torrentLight,
      accent5 = plt.churnGreen,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.riverBirth,
      rainbow2 = plt.churnGreen,
      rainbow3 = plt.springFlow,
      rainbow4 = plt.waterRush,
      rainbow5 = plt.cascadeGreen,
      rainbow6 = plt.torrentLight,
      rainbow7 = plt.foamGreen,
    },
    ui = {
      fg = plt.torrentLight,
      fg_dim = plt.waterRush,
      fg_dimmer = plt.springFlow,
      fg_dark = plt.weatheredGreen,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_alt1 or "none",
      bg_cursorline = plt.bg_alt2,
      bg_cursorline_alt = plt.bg_alt3,
      cursorline = plt.bg_alt2,
      bg_highlight = plt.bg_alt3,
      bg_search = plt.waterRush,
      bg_visual = plt.bg_alt3,
      bg_statusline = plt.bg_mid,
      border = plt.springFlow,
      header1 = plt.churnGreen,
      header2 = plt.cascadeGreen,
      special = plt.foamGreen,
      nontext = plt.bg_lighter,
      whitespace = plt.weatheredGreen,
      win_separator = plt.mossStone,
      indent = plt.bg_alt1,
      indent_scope = plt.churnGreen,
      picker = plt.springFlow,
      yank = plt.cascadeGreen,
      mark = plt.foamGreen,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_alt3,
      line_nr = plt.springFlow,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.churnGreen,
      float = {
        fg = plt.waterRush,
        bg = plt.bg_mid,
        fg_border = plt.springFlow,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.torrentLight,
        fg_sel = "none",
        fg_border = plt.springFlow,
        bg = plt.bg_mid,
        bg_sel = plt.bg_light,
        bg_border = plt.bg_mid,
        bg_sbar = plt.bg_mid,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_alt3,
        bg_alternate = plt.bg_alt2,
        fg_inactive = plt.originWater,
        fg_selected = plt.torrentLight,
        fg_alternate = plt.churnGreen,
        indicator = plt.cascadeGreen,
      },
    },
    syn = {
      attribute = plt.foamGreen,
      boolean = plt.cascadeGreen,
      comment = plt.weatheredGreen,
      constant = plt.cascadeGreen,
      deprecated = plt.mossStone,
      func = plt.churnGreen,
      identifier = plt.torrentLight,
      keyword = plt.riverBirth,
      method = plt.waterRush,
      number = plt.foamGreen,
      operator = plt.springFlow,
      parameter = plt.cascadeGreen,
      preproc = plt.springFlow,
      punct = plt.originWater,
      regex = plt.cascadeGreen,
      special = plt.foamGreen,
      special2 = plt.weatheredGreen,
      special3 = plt.cascadeGreen,
      statement = plt.riverBirth,
      string = plt.springFlow,
      symbol = plt.waterRush,
      type = plt.churnGreen,
      variable = plt.waterRush,
    },
    diag = {
      error = plt.mistSpray,
      warning = plt.churnGreen,
      info = plt.springFlow,
      ok = plt.torrentLight,
      hint = plt.cascadeGreen,
      virtual_text_error = plt.mistSpray,
      virtual_text_warning = plt.churnGreen,
      virtual_text_info = plt.springFlow,
      virtual_text_ok = plt.torrentLight,
      virtual_text_hint = plt.cascadeGreen,
    },
    diff = {
      add = plt.torrentLight,
      add_inline = plt.waterRush,
      change = plt.churnGreen,
      change_inline = plt.springFlow,
      delete = plt.mistSpray,
      delete_inline = plt.foamGreen,
      text = plt.cascadeGreen,
    },
    vcs = {
      added = plt.torrentLight,
      changed = plt.churnGreen,
      removed = plt.mistSpray,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.mistSpray,
      green = plt.torrentLight,
      yellow = plt.churnGreen,
      blue = plt.springFlow,
      magenta = plt.waterRush,
      cyan = plt.cascadeGreen,
      white = plt.waterRush,
      black_bright = color(plt.bg_darkest):brighten(0.8):to_hex(),
      red_bright = color(plt.mistSpray):brighten(0.1):to_hex(),
      green_bright = color(plt.torrentLight):brighten(0.15):to_hex(),
      yellow_bright = color(plt.churnGreen):brighten(0.15):to_hex(),
      blue_bright = color(plt.springFlow):brighten(0.2):to_hex(),
      magenta_bright = color(plt.waterRush):brighten(0.15):to_hex(),
      cyan_bright = color(plt.cascadeGreen):brighten(0.15):to_hex(),
      white_bright = color(plt.torrentLight):brighten(0.1):to_hex(),
      indexed1 = plt.torrentLight,
      indexed2 = plt.cascadeGreen,
    },
  }
end

return {
  name = "Yggdrasill – Hvergelmir",
  author = "PrismPunk",
  description = "The Primordial Spring — churning chaos where all rivers begin, origin waters in deep greens.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.weatheredGreen,
    base05 = palette.springFlow,
    base06 = palette.waterRush,
    base07 = palette.torrentLight,
    base08 = palette.mistSpray,
    base09 = palette.riverBirth,
    base0A = palette.cascadeGreen,
    base0B = palette.springFlow,
    base0C = palette.waterRush,
    base0D = palette.churnGreen,
    base0E = palette.cascadeGreen,
    base0F = palette.foamGreen,
  },
  palette = palette,
  get = M.get,
}
