local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#181a1e",
  bg_darker = "#1e2024",
  bg_dark = "#24272c",
  bg_mid = "#2c2f35",
  bg_light = "#34383f",
  bg_lighter = "#3d4149",
  bg_lightest = "#464b53",
  bg_alt1 = "#50555e",
  bg_alt2 = "#5a5f68",
  bg_alt3 = "#636972",
  bg_alt4 = "#6d737c",
  fg_lightest = "#e2ddd6",
  fg_light = "#c8c3ba",
  fg_mid = "#9e998f",
  fg_dark = "#6e6a62",
  hearthfire = "#d4944a",
  ironForge = "#8a9eae",
  birchBark = "#c8b88a",
  stormSky = "#6a8a9e",
  riverClay = "#b87a5a",
  runestone = "#9a8e7a",
  bifrost = "#7a8abe",
  mossThatch = "#7a9e6a",
  wolfPelt = "#8a7a9a",
  ashYggdrasil = "#5e6e5a",
  midwinterSun = "#e2c86a",
  shieldRim = "#ae8a5a",
  peatSmoke = "#2a2c2e",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.ironForge,
      insert = plt.hearthfire,
      visual = plt.wolfPelt,
      replace = plt.riverClay,
      command = plt.midwinterSun,
    },
    accent = {
      accent1 = plt.ironForge,
      accent2 = plt.hearthfire,
      accent3 = plt.stormSky,
      accent4 = plt.fg_light,
      accent5 = plt.midwinterSun,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.ironForge,
      rainbow2 = plt.hearthfire,
      rainbow3 = plt.mossThatch,
      rainbow4 = plt.wolfPelt,
      rainbow5 = plt.midwinterSun,
      rainbow6 = plt.riverClay,
      rainbow7 = plt.bifrost,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.midwinterSun,
      bg_visual = plt.peatSmoke,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.ironForge,
      header2 = plt.hearthfire,
      special = plt.midwinterSun,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.runestone,
      indent = plt.bg_light,
      indent_scope = plt.ironForge,
      picker = plt.stormSky,
      yank = plt.midwinterSun,
      mark = plt.wolfPelt,
      scrollbar = plt.bg_lighter,
      selection = plt.peatSmoke,
      line_nr = plt.fg_dark,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.ironForge,
        indicator = plt.hearthfire,
      },
    },
    syn = {
      attribute = plt.midwinterSun,
      boolean = plt.wolfPelt,
      comment = plt.runestone,
      constant = plt.stormSky,
      deprecated = plt.fg_dark,
      func = plt.hearthfire,
      identifier = plt.fg_light,
      keyword = plt.ironForge,
      method = plt.hearthfire,
      number = plt.riverClay,
      operator = plt.birchBark,
      parameter = plt.bifrost,
      preproc = plt.riverClay,
      punct = plt.fg_mid,
      regex = plt.wolfPelt,
      special = plt.midwinterSun,
      special2 = plt.shieldRim,
      special3 = plt.bifrost,
      statement = plt.ironForge,
      string = plt.mossThatch,
      symbol = plt.ashYggdrasil,
      type = plt.birchBark,
      variable = plt.fg_light,
      annotation = plt.shieldRim,
    },
    diag = {
      error = plt.riverClay,
      warning = plt.hearthfire,
      info = plt.stormSky,
      ok = plt.mossThatch,
      hint = plt.ashYggdrasil,
      virtual_text_error = plt.riverClay,
      virtual_text_warning = plt.hearthfire,
      virtual_text_info = plt.stormSky,
      virtual_text_ok = plt.mossThatch,
      virtual_text_hint = plt.ashYggdrasil,
    },
    diff = {
      add = plt.mossThatch,
      add_inline = plt.ashYggdrasil,
      change = plt.stormSky,
      change_inline = plt.bifrost,
      delete = plt.riverClay,
      delete_inline = plt.hearthfire,
      text = plt.midwinterSun,
    },
    vcs = {
      added = plt.mossThatch,
      changed = plt.stormSky,
      removed = plt.riverClay,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.riverClay,
      green = plt.mossThatch,
      yellow = plt.midwinterSun,
      blue = plt.stormSky,
      magenta = plt.wolfPelt,
      cyan = plt.ironForge,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.riverClay):brighten(0.2):to_hex(),
      green_bright = color(plt.mossThatch):brighten(0.15):to_hex(),
      yellow_bright = color(plt.midwinterSun):brighten(0.15):to_hex(),
      blue_bright = color(plt.stormSky):brighten(0.15):to_hex(),
      magenta_bright = color(plt.wolfPelt):brighten(0.2):to_hex(),
      cyan_bright = color(plt.ironForge):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.bifrost,
      indexed2 = plt.shieldRim,
    },
  }
end

return {
  name = "Midgard – Miðgarðr",
  author = "PrismPunk",
  description = "The mortal realm — hearthfire and iron, storm-grey skies, birch and river clay. "
    .. "Miðgarðr sits at the center of the Nine Realms, encircled by the world-serpent "
    .. "Jörmungandr, rooted in the ash of Yggdrasil. This is no realm of gods or "
    .. "giants — it is the human world, where longships creak against wooden docks, "
    .. "where smiths hammer iron by hearthlight, where rune-carved stones mark the "
    .. "crossroads between the known and the wild. The palette is grounded in the "
    .. "materials of mortal life: storm-grey iron, warm hearthfire, birch-bark parchment, "
    .. "river clay, moss-thatched roofs, and the distant shimmer of the Bifröst arcing "
    .. "overhead — a reminder that the gods watch, but mortals endure. Wolf pelts hang "
    .. "by the door, peat smoke curls from the longhouse, and the midwinter sun casts "
    .. "long gold across the frozen fields.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.riverClay,
    base09 = palette.hearthfire,
    base0A = palette.midwinterSun,
    base0B = palette.mossThatch,
    base0C = palette.ironForge,
    base0D = palette.stormSky,
    base0E = palette.wolfPelt,
    base0F = palette.bifrost,
  },
  palette = palette,
  get = M.get,
}
