local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1e1a",
  bg_darker = "#242a24",
  bg_dark = "#2e362e",
  bg_mid = "#2e3a42",
  bg_light = "#3a4a56",
  bg_lighter = "#465a6a",
  bg_lightest = "#526a7e",
  bg_alt1 = "#2a322e",
  bg_alt2 = "#3d4542",
  bg_alt3 = "#3d4a3d",
  bg_alt4 = "#505d50",
  fg_lightest = "#d6ffff",
  fg_light = "#b2e6ff",
  fg_mid = "#9ca99c",
  fg_dark = "#768376",
  crownShadow = "#1a1e1a",
  stormBase = "#242a24",
  windDusk = "#2e362e",
  nestledge = "#3d4a3d",
  skyHawk = "#82aace",
  windBlue = "#9acaf6",
  piercingAzure = "#a6daff",
  crownHeight = "#bef2ff",
  clarityGlow = "#cafeff",
  horizonMist = "#8ebae2",
  thermalDrift = "#769aba",
  stormWing = "#6a8aa6",
  talonSilver = "#899689",
  featherGray = "#637063",
  perchStone = "#505d50",
  alertOrange = "#ffb47a",
  dawnRose = "#ff9aaa",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.skyHawk,
      insert = plt.piercingAzure,
      visual = plt.windBlue,
      replace = plt.alertOrange,
      command = plt.crownHeight,
    },
    accent = {
      accent1 = plt.skyHawk,
      accent2 = plt.windBlue,
      accent3 = plt.piercingAzure,
      accent4 = plt.crownHeight,
      accent5 = plt.horizonMist,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.skyHawk,
      rainbow2 = plt.windBlue,
      rainbow3 = plt.piercingAzure,
      rainbow4 = plt.crownHeight,
      rainbow5 = plt.horizonMist,
      rainbow6 = plt.thermalDrift,
      rainbow7 = plt.stormWing,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.clarityGlow,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_mid,
      border = plt.stormWing,
      header1 = plt.skyHawk,
      header2 = plt.windBlue,
      special = plt.crownHeight,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.piercingAzure,
      indent = plt.bg_mid,
      indent_scope = plt.skyHawk,
      picker = plt.thermalDrift,
      yank = plt.clarityGlow,
      mark = plt.piercingAzure,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.skyHawk,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.windBlue,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.piercingAzure,
        bg = plt.bg_mid,
        bg_sel = plt.bg_light,
        bg_border = plt.bg_mid,
        bg_sbar = plt.bg_mid,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_mid,
        bg_alternate = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.skyHawk,
        indicator = plt.windBlue,
      },
    },
    syn = {
      attribute = plt.crownHeight,
      boolean = plt.alertOrange,
      comment = plt.fg_dark,
      constant = plt.alertOrange,
      deprecated = plt.featherGray,
      func = plt.skyHawk,
      identifier = plt.fg_lightest,
      keyword = plt.windBlue,
      method = plt.piercingAzure,
      number = plt.clarityGlow,
      operator = plt.horizonMist,
      parameter = plt.talonSilver,
      preproc = plt.thermalDrift,
      punct = plt.fg_mid,
      regex = plt.crownHeight,
      special = plt.clarityGlow,
      special2 = plt.thermalDrift,
      special3 = plt.dawnRose,
      statement = plt.windBlue,
      string = plt.piercingAzure,
      symbol = plt.skyHawk,
      type = plt.talonSilver,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dawnRose,
      warning = plt.alertOrange,
      info = plt.skyHawk,
      ok = plt.talonSilver,
      hint = plt.crownHeight,
      virtual_text_error = plt.dawnRose,
      virtual_text_warning = plt.alertOrange,
      virtual_text_info = plt.skyHawk,
      virtual_text_ok = plt.talonSilver,
      virtual_text_hint = plt.crownHeight,
    },
    diff = {
      add = plt.talonSilver,
      add_inline = plt.clarityGlow,
      change = plt.skyHawk,
      change_inline = plt.piercingAzure,
      delete = plt.dawnRose,
      delete_inline = plt.alertOrange,
      text = plt.windBlue,
    },
    vcs = {
      added = plt.talonSilver,
      changed = plt.skyHawk,
      removed = plt.dawnRose,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.dawnRose,
      green = plt.talonSilver,
      yellow = plt.alertOrange,
      blue = plt.skyHawk,
      magenta = plt.windBlue,
      cyan = plt.piercingAzure,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.8):to_hex(),
      red_bright = color(plt.dawnRose):brighten(0.2):to_hex(),
      green_bright = color(plt.talonSilver):brighten(0.15):to_hex(),
      yellow_bright = color(plt.alertOrange):brighten(0.15):to_hex(),
      blue_bright = color(plt.skyHawk):brighten(0.3):to_hex(),
      magenta_bright = color(plt.windBlue):brighten(0.2):to_hex(),
      cyan_bright = color(plt.piercingAzure):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.clarityGlow,
      indexed2 = plt.crownHeight,
    },
  }
end

return {
  name = "Yggdrasill – Veðrfölnir",
  author = "PrismPunk",
  description = "The sky hawk perched at the World Tree's crown — wind blues, piercing clarity, soaring above all realms with keen sight.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dawnRose,
    base09 = palette.alertOrange,
    base0A = palette.clarityGlow,
    base0B = palette.talonSilver,
    base0C = palette.piercingAzure,
    base0D = palette.skyHawk,
    base0E = palette.windBlue,
    base0F = palette.crownHeight,
  },
  palette = palette,
  get = M.get,
}
