local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#0B0A10",
  sumiInk1 = "#16151E",
  sumiInk2 = "#22212D",
  sumiInk3 = "#2D2C39",
  sumiInk4 = "#4F4C5B",
  sumiInkShadow = "#0F0E18",
  sumiInkEcho = "#1A1924",
  sumiInkTint = "#262530",
  fujiWhite = "#DED9C7",
  oldWhite = "#CBC3AD",
  softGray = "#72706D",
  ashGray = "#5B5854",
  steelGray = "#6F6B68",
  darkTeal = "#204D51",
  crimsonRed1 = "#B83238",
  crimsonRed2 = "#C94040",
  emberRed = "#FF4C4C",
  crimsonGlow = "#D13C42",
  crimsonVivid = "#E64A4A",
  crimsonFlare = "#F55C5C",
  emberGold = "#E6B252",
  softAmber = "#F1C67B",
  emberGlow = "#F0C070",
  emberVivid = "#FAD07A",
  forestGreen = "#61835B",
  lightGreen = "#7BA278",
  forestGlow = "#6D9367",
  forestVivid = "#79A272",
  stormBlue = "#2C4B6B",
  waveAqua1 = "#4C8C8F",
  stormGlow = "#355A7A",
  waveGlow = "#569CA0",
  violet1 = "#8C77B0",
  violet2 = "#9B88C3",
  violetGlow = "#9988C0",
  violetVivid = "#A595D0",
  emberPink = "#D16B7C",
  crimsonAccent1 = "#A02A30",
  crimsonAccent2 = "#B02F35",
  crimsonAccent3 = "#C0343A",
  crimsonAccent4 = "#D03A40",

  bg_darkest = "#204D51",
  fg_lightest = "#DED9C7",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      command = plt.emberGold,
      insert = plt.forestGreen,
      normal = plt.crimsonRed1,
      replace = plt.emberRed,
      visual = plt.stormBlue,
    },
    accent = {
      accent1 = plt.crimsonRed1,
      accent2 = plt.crimsonRed2,
      accent3 = plt.emberGold,
      accent4 = plt.stormBlue,
      accent5 = plt.violet1,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.crimsonRed1,
      rainbow2 = plt.emberGold,
      rainbow3 = plt.softAmber,
      rainbow4 = plt.forestGreen,
      rainbow5 = plt.stormBlue,
      rainbow6 = plt.waveAqua1,
      rainbow7 = plt.violet1,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.softGray,
      fg_dark = plt.ashGray,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk1 or "none",
      bg_cursorline = plt.sumiInk2,
      bg_cursorline_alt = plt.sumiInk3,
      cursorline = plt.sumiInk2,
      bg_highlight = plt.sumiInk3,
      bg_search = plt.emberGlow,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInk2,
      border = plt.sumiInk4,
      header1 = plt.emberGold,
      header2 = plt.crimsonRed1,
      special = plt.violet1,
      nontext = plt.sumiInk4,
      whitespace = plt.ashGray,
      win_separator = plt.sumiInk4,
      indent = plt.sumiInk2,
      indent_scope = plt.waveAqua1,
      picker = plt.violet1,
      yank = plt.emberVivid,
      mark = plt.crimsonRed2,
      scrollbar = plt.sumiInk4,
      selection = plt.sumiInk3,
      line_nr = plt.sumiInk4,
      line_nr_dim = plt.sumiInk3,
      line_nr_active = plt.fujiWhite,
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk2,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk2,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.sumiInk4,
        bg = plt.sumiInk2,
        bg_sel = plt.sumiInk3,
        bg_border = plt.sumiInk2,
        bg_sbar = plt.sumiInk2,
        bg_thumb = plt.sumiInk4,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        fg_inactive = plt.softGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.emberGold,
        indicator = plt.crimsonRed1,
      },
    },
    syn = {
      attribute = plt.oldWhite,
      boolean = plt.waveAqua1,
      comment = plt.softGray,
      constant = plt.oldWhite,
      deprecated = plt.ashGray,
      func = plt.stormBlue,
      identifier = plt.fujiWhite,
      keyword = plt.crimsonRed1,
      method = plt.stormBlue,
      number = plt.emberGold,
      operator = plt.emberGold,
      parameter = plt.fujiWhite,
      preproc = plt.crimsonRed2,
      punct = plt.softGray,
      regex = plt.waveAqua1,
      special = plt.crimsonRed2,
      special2 = plt.violet1,
      special3 = plt.waveAqua1,
      statement = plt.crimsonRed1,
      string = plt.emberRed,
      symbol = plt.crimsonRed2,
      type = plt.violet1,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.crimsonRed1,
      warning = plt.crimsonRed2,
      info = plt.waveAqua1,
      hint = plt.forestGreen,
      ok = plt.stormBlue,
      virtual_text_error = plt.crimsonRed2,
      virtual_text_warning = plt.emberGlow,
      virtual_text_info = plt.waveGlow,
      virtual_text_hint = plt.forestGlow,
      virtual_text_ok = plt.stormGlow,
    },
    diff = {
      add = plt.forestGreen,
      add_inline = plt.forestVivid,
      change = plt.emberGold,
      change_inline = plt.softAmber,
      delete = plt.crimsonRed1,
      delete_inline = plt.crimsonRed2,
      text = plt.waveAqua1,
    },
    vcs = {
      added = plt.forestGreen,
      changed = plt.emberGold,
      removed = plt.crimsonRed1,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.crimsonRed1,
      green = plt.forestGreen,
      yellow = plt.emberGold,
      blue = plt.stormBlue,
      magenta = plt.violet1,
      cyan = plt.waveAqua1,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.crimsonRed1):brighten(0.2):to_hex(),
      green_bright = color(plt.forestGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.emberGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.stormBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.violet1):brighten(0.2):to_hex(),
      cyan_bright = color(plt.waveAqua1):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.emberVivid,
      indexed2 = plt.violetVivid,
    },
  }
end

return {
  name = "Kanagawa Kami – Hachiman",
  author = "PrismPunk.nvim",
  description = "Dark, blood-red dominant theme with deep shadows and bright crimson accents.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softGray,
    base08 = palette.crimsonRed1,
    base09 = palette.crimsonRed2,
    base0A = palette.emberGold,
    base0B = palette.forestGreen,
    base0C = palette.waveAqua1,
    base0D = palette.stormBlue,
    base0E = palette.violet1,
    base0F = palette.emberRed,
  },
  palette = palette,
  get = M.get,
}
