local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#0A120E",
  sumiInk1 = "#141C18",
  sumiInk2 = "#1E2A24",
  sumiInk3 = "#283834",
  sumiInk4 = "#384E46",
  sumiInk5 = "#486858",
  sumiInk6 = "#5A8070",
  sumiInkShadow = "#060A08",
  sumiInkEcho = "#0C1610",
  sumiInkTint = "#101C14",
  sumiInkDeep = "#1A2820",
  sumiInkRidge = "#223830",
  sumiInkSoft = "#2A4438",
  fujiWhite = "#E0F0E8",
  oldWhite = "#C0D8D0",
  dragonGray = "#788878",
  dragonGray2 = "#98A898",
  fujinGreen = "#48D878",
  fujinStorm = "#5888A0",
  fujinBreeze = "#C8E8D8",
  fujinMist = "#A0C8B8",
  windWhite = "#D0E8DC",
  stormGray = "#5A7068",
  rushingAir = "#78B898",
  windGust = "#58A878",
  turbulentGreen = "#48B078",
  vortexTeal = "#68B8A0",
  swirlingGray = "#6A8078",
  leafGreen = "#38A060",
  breezeGray = "#88A098",
  autumnRed = "#C84848",
  autumnYellow = "#D8A848",
  autumnGreen = "#68A068",
  fujinGlow = "#80F0A0",
  fujinVortex = "#68B8A0",
  fujinVivid = "#90F8B0",
  fujinFlare = "#A8FFE0",
  fujinAccent1 = "#1A2820",
  fujinAccent2 = "#223028",
  fujinAccent3 = "#2A3830",
  fujinAccent4 = "#324038",
  fujinAccent5 = "#3A4840",
  stormGlow = "#90D8B0",
  stormVivid = "#A0E8C0",
  stormFlare = "#B0F0D0",

  bg_darkest = "#0A120E",
  fg_lightest = "#E0F0E8",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.fujinGreen,
      insert = plt.turbulentGreen,
      visual = plt.vortexTeal,
      replace = plt.autumnRed,
      command = plt.fujinGlow,
    },
    accent = {
      accent1 = plt.fujinGreen,
      accent2 = plt.windGust,
      accent3 = plt.fujinStorm,
      accent4 = plt.vortexTeal,
      accent5 = plt.fujinBreeze,
      invert = plt.stormGray,
    },
    rainbow = {
      rainbow1 = plt.autumnRed,
      rainbow2 = plt.autumnYellow,
      rainbow3 = plt.fujinGlow,
      rainbow4 = plt.autumnGreen,
      rainbow5 = plt.fujinGreen,
      rainbow6 = plt.fujinStorm,
      rainbow7 = plt.vortexTeal,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.dragonGray,
      fg_dark = plt.dragonGray2,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk3 or "none",
      bg_cursorline = plt.sumiInk2,
      bg_cursorline_alt = plt.sumiInk3,
      cursorline = plt.sumiInk2,
      bg_highlight = plt.sumiInk3,
      bg_search = plt.fujinAccent2,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInk1,
      border = plt.sumiInk4,
      header1 = plt.fujinGreen,
      header2 = plt.fujinStorm,
      special = plt.fujinVortex,
      nontext = plt.sumiInk5,
      whitespace = plt.dragonGray,
      win_separator = plt.sumiInk4,
      indent = plt.sumiInk3,
      indent_scope = plt.fujinGreen,
      picker = plt.vortexTeal,
      yank = plt.fujinVivid,
      mark = plt.autumnRed,
      scrollbar = plt.sumiInk4,
      selection = plt.sumiInk3,
      line_nr = plt.dragonGray2,
      line_nr_dim = plt.sumiInk4,
      line_nr_active = plt.fujiWhite,
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = plt.fujiWhite,
        fg_border = plt.sumiInk4,
        bg = plt.sumiInk2,
        bg_sel = plt.sumiInk3,
        bg_border = plt.sumiInk2,
        bg_sbar = plt.sumiInk2,
        bg_thumb = plt.sumiInk4,
      },
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk2,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk2,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.fujinGreen,
        indicator = plt.fujinGreen,
      },
    },
    syn = {
      attribute = plt.oldWhite,
      boolean = plt.fujinStorm,
      comment = plt.dragonGray,
      constant = plt.oldWhite,
      deprecated = plt.dragonGray2,
      func = plt.fujinGreen,
      identifier = plt.fujiWhite,
      keyword = plt.autumnRed,
      method = plt.fujinGreen,
      number = plt.autumnYellow,
      operator = plt.fujinGlow,
      parameter = plt.oldWhite,
      preproc = plt.vortexTeal,
      punct = plt.dragonGray,
      regex = plt.fujinStorm,
      special = plt.fujinGlow,
      special2 = plt.vortexTeal,
      special3 = plt.fujinStorm,
      statement = plt.autumnRed,
      string = plt.turbulentGreen,
      symbol = plt.fujinBreeze,
      type = plt.vortexTeal,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.autumnRed,
      warning = plt.autumnYellow,
      info = plt.fujinGreen,
      hint = plt.vortexTeal,
      ok = plt.turbulentGreen,
      virtual_text_error = plt.autumnRed,
      virtual_text_warning = plt.autumnYellow,
      virtual_text_info = plt.fujinGreen,
      virtual_text_hint = plt.vortexTeal,
      virtual_text_ok = plt.turbulentGreen,
    },
    diff = {
      add = plt.autumnGreen,
      add_inline = plt.fujinVivid,
      change = plt.fujinGlow,
      change_inline = plt.stormVivid,
      delete = plt.autumnRed,
      delete_inline = plt.autumnRed,
      text = plt.fujinStorm,
    },
    vcs = {
      added = plt.autumnGreen,
      changed = plt.fujinGlow,
      removed = plt.autumnRed,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.autumnRed,
      green = plt.fujinGreen,
      yellow = plt.autumnYellow,
      blue = plt.fujinStorm,
      magenta = plt.vortexTeal,
      cyan = plt.rushingAir,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.autumnRed):brighten(0.2):to_hex(),
      green_bright = color(plt.fujinGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.autumnYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.fujinStorm):brighten(0.3):to_hex(),
      magenta_bright = color(plt.vortexTeal):brighten(0.2):to_hex(),
      cyan_bright = color(plt.rushingAir):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.fujinGlow,
      indexed2 = plt.fujinBreeze,
    },
  }
end

return {
  name = "Kanagawa Kami – Fujin",
  author = "PrismPunk.nvim",
  description = "Wind god — turbulent greens and rushing whites on dark.",

  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.dragonGray,
    base08 = palette.autumnRed,
    base09 = palette.autumnYellow,
    base0A = palette.fujinGlow,
    base0B = palette.fujinGreen,
    base0C = palette.rushingAir,
    base0D = palette.fujinStorm,
    base0E = palette.vortexTeal,
    base0F = palette.turbulentGreen,
  },

  palette = palette,
  get = M.get,
}
