local color = require("prismpunk.utils.color")

local palette = {
  earthBlack = "#0A0806",
  soilBlack = "#120E08",
  ashBlack = "#1A1410",
  earthDeep = "#221A10",
  earthDark = "#2E2216",
  earthMid = "#3C2E1C",
  earthWarm = "#4A3A26",
  earthBright = "#5C4A34",
  foxDeep = "#8A3A10",
  foxMid = "#B04A18",
  foxBright = "#D05A20",
  foxFlame = "#E86A28",
  foxTip = "#F07A38",
  crimsonDeep = "#6A0E0E",
  crimsonMid = "#8A1A1A",
  crimsonBright = "#AA2828",
  crimsonVivid = "#C83838",
  grainGold = "#C89040",
  harvestPale = "#E0B870",
  bg_darkest = "#0A0806",
  fg_lightest = "#E0B870",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.foxBright,
      insert = plt.foxFlame,
      visual = plt.crimsonVivid,
      replace = plt.crimsonBright,
      command = plt.foxTip,
    },
    accent = {
      accent1 = plt.foxBright,
      accent2 = plt.foxFlame,
      accent3 = plt.crimsonVivid,
      accent4 = plt.grainGold,
      accent5 = plt.harvestPale,
      invert = plt.earthBlack,
    },
    rainbow = {
      rainbow1 = plt.foxFlame,
      rainbow2 = plt.crimsonVivid,
      rainbow3 = plt.foxTip,
      rainbow4 = plt.grainGold,
      rainbow5 = plt.harvestPale,
      rainbow6 = plt.foxBright,
      rainbow7 = plt.crimsonBright,
    },
    ui = {
      fg = plt.harvestPale,
      fg_dim = plt.grainGold,
      fg_dimmer = plt.foxTip,
      fg_dark = plt.foxMid,
      fg_reverse = plt.earthBlack,
      bg = plt.earthBlack,
      bg_dim = plt.earthBlack,
      bg_m1 = plt.soilBlack,
      bg_m2 = plt.ashBlack,
      bg_m3 = plt.earthDeep,
      bg_m4 = plt.earthDark,
      bg_p1 = plt.soilBlack,
      bg_p2 = plt.ashBlack,
      bg_gutter = (opts.gutter ~= false) and plt.soilBlack or "none",
      bg_cursorline = plt.soilBlack,
      bg_cursorline_alt = plt.ashBlack,
      cursorline = plt.soilBlack,
      bg_highlight = plt.earthDeep,
      bg_search = plt.foxDeep,
      bg_visual = plt.earthDark,
      bg_statusline = plt.soilBlack,
      border = plt.ashBlack,
      header1 = plt.foxFlame,
      header2 = plt.crimsonVivid,
      special = plt.grainGold,
      nontext = plt.ashBlack,
      whitespace = plt.earthDeep,
      win_separator = plt.ashBlack,
      indent = plt.soilBlack,
      indent_scope = plt.earthDeep,
      picker = plt.foxBright,
      yank = plt.foxFlame,
      mark = plt.crimsonVivid,
      scrollbar = plt.ashBlack,
      selection = plt.earthDeep,
      line_nr = plt.earthMid,
      line_nr_dim = plt.ashBlack,
      line_nr_active = plt.foxBright,
      float = {
        fg = plt.harvestPale,
        bg = plt.ashBlack,
        fg_border = plt.earthWarm,
        bg_border = plt.ashBlack,
      },
      pmenu = {
        fg = plt.harvestPale,
        fg_sel = plt.harvestPale,
        fg_border = plt.earthWarm,
        bg = plt.soilBlack,
        bg_sel = plt.earthDeep,
        bg_border = plt.soilBlack,
        bg_sbar = plt.soilBlack,
        bg_thumb = plt.ashBlack,
      },
      tabline = {
        bg = plt.earthBlack,
        bg_inactive = plt.earthBlack,
        bg_selected = plt.soilBlack,
        bg_alternate = plt.soilBlack,
        fg_inactive = plt.earthMid,
        fg_selected = plt.foxFlame,
        fg_alternate = plt.foxBright,
        indicator = plt.crimsonVivid,
      },
    },
    syn = {
      attribute = plt.crimsonVivid,
      boolean = plt.foxFlame,
      comment = plt.earthBright,
      constant = plt.harvestPale,
      deprecated = plt.ashBlack,
      func = plt.foxBright,
      identifier = plt.harvestPale,
      keyword = plt.foxFlame,
      method = plt.foxBright,
      number = plt.grainGold,
      operator = plt.earthWarm,
      parameter = plt.grainGold,
      preproc = plt.crimsonVivid,
      punct = plt.earthBright,
      regex = plt.crimsonBright,
      special = plt.grainGold,
      special2 = plt.crimsonVivid,
      special3 = plt.foxFlame,
      statement = plt.foxFlame,
      string = plt.foxMid,
      symbol = plt.grainGold,
      type = plt.foxBright,
      variable = plt.harvestPale,
    },
    diag = {
      error = plt.crimsonVivid,
      warning = plt.foxFlame,
      info = plt.foxBright,
      hint = plt.grainGold,
      ok = plt.harvestPale,
      virtual_text_error = plt.crimsonVivid,
      virtual_text_warning = plt.foxFlame,
      virtual_text_info = plt.foxBright,
      virtual_text_hint = plt.grainGold,
      virtual_text_ok = plt.harvestPale,
    },
    diff = {
      add = plt.earthDeep,
      add_inline = plt.earthMid,
      change = plt.foxDeep,
      change_inline = plt.foxMid,
      delete = color(plt.crimsonDeep):darken(0.4):to_hex(),
      delete_inline = plt.crimsonBright,
      text = plt.ashBlack,
    },
    vcs = {
      added = plt.foxBright,
      changed = plt.grainGold,
      removed = plt.crimsonBright,
    },
    term = {
      black = plt.earthBlack,
      red = plt.crimsonVivid,
      green = plt.foxMid,
      yellow = plt.grainGold,
      blue = plt.earthBright,
      magenta = plt.crimsonBright,
      cyan = plt.foxTip,
      white = plt.harvestPale,
      black_bright = color(plt.earthBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.crimsonVivid):brighten(0.2):to_hex(),
      green_bright = color(plt.foxMid):brighten(0.2):to_hex(),
      yellow_bright = color(plt.grainGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.earthBright):brighten(0.3):to_hex(),
      magenta_bright = color(plt.crimsonBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.foxTip):brighten(0.1):to_hex(),
      white_bright = color(plt.harvestPale):brighten(0.05):to_hex(),
      indexed1 = plt.foxFlame,
      indexed2 = plt.earthDeep,
    },
  }
end

return {
  name = "Kami – Inari",
  author = "PrismPunk.nvim",
  description = "Fox and harvest god. Warm fox-orange burns across dark earth; crimson torii gates cut the shrine night. Grain gold dusts the offering table. The kitsune passes between the red pillars.",

  base16 = {
    base00 = palette.earthBlack,
    base01 = palette.soilBlack,
    base02 = palette.ashBlack,
    base03 = palette.earthDeep,
    base04 = palette.earthMid,
    base05 = palette.harvestPale,
    base06 = palette.grainGold,
    base07 = palette.harvestPale,
    base08 = palette.crimsonVivid,
    base09 = palette.foxMid,
    base0A = palette.grainGold,
    base0B = palette.foxBright,
    base0C = palette.foxFlame,
    base0D = palette.foxTip,
    base0E = palette.crimsonBright,
    base0F = palette.foxDeep,
  },

  palette = palette,
  get = M.get,
}
