local color = require("prismpunk.utils.color")

local palette = {
  stormBlack = "#0A0A0C",
  cloudBlack = "#14141A",
  chargedBlack = "#1C1C28",
  purpleDeep = "#2A1A3C",
  purpleMid = "#4A2A6C",
  purpleBright = "#7A4AAC",
  purpleCharged = "#AA6AEC",
  purpleArc = "#CA8AFC",
  yellowDeep = "#8A7A00",
  yellowMid = "#CAB000",
  yellowBright = "#FAE800",
  yellowStrike = "#FFFA20",
  yellowFlash = "#FFFFA0",
  ozoneWhite = "#E0E0FF",
  flashWhite = "#FFFFF0",
  dangerRed = "#FA2A2A",
  bg_darkest = "#0A0A0C",
  fg_lightest = "#FFFFF0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.purpleBright,
      insert = plt.yellowBright,
      visual = plt.purpleCharged,
      replace = plt.dangerRed,
      command = plt.yellowStrike,
    },
    accent = {
      accent1 = plt.yellowBright,
      accent2 = plt.purpleCharged,
      accent3 = plt.yellowStrike,
      accent4 = plt.purpleArc,
      accent5 = plt.ozoneWhite,
      invert = plt.stormBlack,
    },
    rainbow = {
      rainbow1 = plt.yellowBright,
      rainbow2 = plt.purpleCharged,
      rainbow3 = plt.yellowStrike,
      rainbow4 = plt.purpleArc,
      rainbow5 = plt.yellowFlash,
      rainbow6 = plt.purpleBright,
      rainbow7 = plt.yellowMid,
    },
    ui = {
      fg = plt.ozoneWhite,
      fg_dim = plt.yellowFlash,
      fg_dimmer = plt.yellowMid,
      fg_dark = plt.purpleMid,
      fg_reverse = plt.stormBlack,
      bg = plt.stormBlack,
      bg_dim = plt.stormBlack,
      bg_m1 = plt.cloudBlack,
      bg_m2 = plt.chargedBlack,
      bg_m3 = plt.purpleDeep,
      bg_m4 = plt.purpleMid,
      bg_p1 = plt.cloudBlack,
      bg_p2 = plt.chargedBlack,
      bg_gutter = (opts.gutter ~= false) and plt.cloudBlack or "none",
      bg_cursorline = plt.cloudBlack,
      bg_cursorline_alt = plt.chargedBlack,
      cursorline = plt.cloudBlack,
      bg_highlight = plt.purpleDeep,
      bg_search = plt.yellowDeep,
      bg_visual = plt.purpleMid,
      bg_statusline = plt.cloudBlack,
      border = plt.chargedBlack,
      header1 = plt.yellowBright,
      header2 = plt.purpleCharged,
      special = plt.yellowStrike,
      nontext = plt.chargedBlack,
      whitespace = plt.purpleDeep,
      win_separator = plt.chargedBlack,
      indent = plt.cloudBlack,
      indent_scope = plt.purpleDeep,
      picker = plt.yellowBright,
      yank = plt.yellowStrike,
      mark = plt.purpleArc,
      scrollbar = plt.chargedBlack,
      selection = plt.purpleDeep,
      line_nr = plt.purpleMid,
      line_nr_dim = plt.chargedBlack,
      line_nr_active = plt.yellowBright,
      float = {
        fg = plt.ozoneWhite,
        bg = plt.chargedBlack,
        fg_border = plt.purpleBright,
        bg_border = plt.chargedBlack,
      },
      pmenu = {
        fg = plt.ozoneWhite,
        fg_sel = plt.flashWhite,
        fg_border = plt.purpleBright,
        bg = plt.cloudBlack,
        bg_sel = plt.purpleDeep,
        bg_border = plt.cloudBlack,
        bg_sbar = plt.cloudBlack,
        bg_thumb = plt.chargedBlack,
      },
      tabline = {
        bg = plt.stormBlack,
        bg_inactive = plt.stormBlack,
        bg_selected = plt.cloudBlack,
        bg_alternate = plt.cloudBlack,
        fg_inactive = plt.purpleMid,
        fg_selected = plt.yellowBright,
        fg_alternate = plt.purpleCharged,
        indicator = plt.yellowStrike,
      },
    },
    syn = {
      attribute = plt.purpleArc,
      boolean = plt.yellowStrike,
      comment = plt.purpleMid,
      constant = plt.yellowFlash,
      deprecated = plt.chargedBlack,
      func = plt.yellowBright,
      identifier = plt.ozoneWhite,
      keyword = plt.purpleCharged,
      method = plt.yellowBright,
      number = plt.yellowStrike,
      operator = plt.purpleBright,
      parameter = plt.ozoneWhite,
      preproc = plt.purpleArc,
      punct = plt.purpleMid,
      regex = plt.yellowMid,
      special = plt.yellowStrike,
      special2 = plt.purpleCharged,
      special3 = plt.purpleArc,
      statement = plt.purpleCharged,
      string = plt.yellowMid,
      symbol = plt.yellowFlash,
      type = plt.purpleBright,
      variable = plt.ozoneWhite,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.yellowDeep,
      info = plt.purpleBright,
      hint = plt.purpleArc,
      ok = plt.yellowBright,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.yellowDeep,
      virtual_text_info = plt.purpleBright,
      virtual_text_hint = plt.purpleArc,
      virtual_text_ok = plt.yellowBright,
    },
    diff = {
      add = plt.purpleDeep,
      add_inline = plt.purpleBright,
      change = plt.yellowDeep,
      change_inline = plt.yellowMid,
      delete = color(plt.dangerRed):darken(0.5):to_hex(),
      delete_inline = plt.dangerRed,
      text = plt.chargedBlack,
    },
    vcs = {
      added = plt.purpleBright,
      changed = plt.yellowBright,
      removed = plt.dangerRed,
    },
    term = {
      black = plt.stormBlack,
      red = plt.dangerRed,
      green = plt.purpleMid,
      yellow = plt.yellowDeep,
      blue = plt.purpleBright,
      magenta = plt.purpleCharged,
      cyan = plt.purpleArc,
      white = plt.ozoneWhite,
      black_bright = color(plt.stormBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerRed):brighten(0.2):to_hex(),
      green_bright = color(plt.purpleMid):brighten(0.3):to_hex(),
      yellow_bright = color(plt.yellowDeep):brighten(0.3):to_hex(),
      blue_bright = color(plt.purpleBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.purpleCharged):brighten(0.2):to_hex(),
      cyan_bright = color(plt.purpleArc):brighten(0.1):to_hex(),
      white_bright = color(plt.ozoneWhite):brighten(0.1):to_hex(),
      indexed1 = plt.flashWhite,
      indexed2 = plt.chargedBlack,
    },
  }
end

return {
  name = "Kami – Raijin",
  author = "PrismPunk.nvim",
  description = "Thunder god. Electric yellows discharge against charged purple atmosphere on storm-black sky. Lightning channels, ozone afterglow, the moment before and after the strike.",

  base16 = {
    base00 = palette.stormBlack,
    base01 = palette.cloudBlack,
    base02 = palette.chargedBlack,
    base03 = palette.purpleDeep,
    base04 = palette.purpleMid,
    base05 = palette.ozoneWhite,
    base06 = palette.yellowFlash,
    base07 = palette.flashWhite,
    base08 = palette.dangerRed,
    base09 = palette.yellowMid,
    base0A = palette.yellowBright,
    base0B = palette.yellowStrike,
    base0C = palette.purpleBright,
    base0D = palette.purpleCharged,
    base0E = palette.purpleArc,
    base0F = palette.yellowFlash,
  },

  palette = palette,
  get = M.get,
}
