local color = require("prismpunk.utils.color")

local palette = {
  abyssBlack = "#040A0A",
  deepBlack = "#0A1210",
  oceanBlack = "#0E1A18",
  greenAbyss = "#0A1E1A",
  greenDeep = "#0E2A24",
  greenMid = "#163C34",
  greenBright = "#1E5248",
  greenSurface = "#266860",
  tealDeep = "#1A4A48",
  tealMid = "#2A6A68",
  tealBright = "#3A8A88",
  tealShimmer = "#4AACAA",
  tealCrest = "#5ACAC8",
  bioGlow = "#00F0D0",
  bioFaint = "#00C8A8",
  seafoamPale = "#A0D8D0",
  seafoamBright = "#C8EEE8",
  bg_darkest = "#040A0A",
  fg_lightest = "#C8EEE8",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.tealBright,
      insert = plt.tealCrest,
      visual = plt.bioGlow,
      replace = plt.greenSurface,
      command = plt.tealShimmer,
    },
    accent = {
      accent1 = plt.tealBright,
      accent2 = plt.tealCrest,
      accent3 = plt.bioGlow,
      accent4 = plt.tealShimmer,
      accent5 = plt.seafoamBright,
      invert = plt.abyssBlack,
    },
    rainbow = {
      rainbow1 = plt.tealCrest,
      rainbow2 = plt.bioGlow,
      rainbow3 = plt.tealBright,
      rainbow4 = plt.tealShimmer,
      rainbow5 = plt.seafoamBright,
      rainbow6 = plt.greenSurface,
      rainbow7 = plt.tealMid,
    },
    ui = {
      fg = plt.seafoamBright,
      fg_dim = plt.tealCrest,
      fg_dimmer = plt.tealShimmer,
      fg_dark = plt.tealMid,
      fg_reverse = plt.abyssBlack,
      bg = plt.abyssBlack,
      bg_dim = plt.abyssBlack,
      bg_m1 = plt.deepBlack,
      bg_m2 = plt.oceanBlack,
      bg_m3 = plt.greenAbyss,
      bg_m4 = plt.greenDeep,
      bg_p1 = plt.deepBlack,
      bg_p2 = plt.oceanBlack,
      bg_gutter = (opts.gutter ~= false) and plt.deepBlack or "none",
      bg_cursorline = plt.deepBlack,
      bg_cursorline_alt = plt.oceanBlack,
      cursorline = plt.deepBlack,
      bg_highlight = plt.greenAbyss,
      bg_search = plt.tealDeep,
      bg_visual = plt.greenDeep,
      bg_statusline = plt.deepBlack,
      border = plt.oceanBlack,
      header1 = plt.tealCrest,
      header2 = plt.bioGlow,
      special = plt.tealShimmer,
      nontext = plt.oceanBlack,
      whitespace = plt.greenAbyss,
      win_separator = plt.oceanBlack,
      indent = plt.deepBlack,
      indent_scope = plt.greenAbyss,
      picker = plt.tealBright,
      yank = plt.bioGlow,
      mark = plt.tealCrest,
      scrollbar = plt.oceanBlack,
      selection = plt.greenAbyss,
      line_nr = plt.greenMid,
      line_nr_dim = plt.oceanBlack,
      line_nr_active = plt.tealBright,
      float = {
        fg = plt.seafoamBright,
        bg = plt.oceanBlack,
        fg_border = plt.tealMid,
        bg_border = plt.oceanBlack,
      },
      pmenu = {
        fg = plt.seafoamBright,
        fg_sel = plt.seafoamBright,
        fg_border = plt.tealMid,
        bg = plt.deepBlack,
        bg_sel = plt.greenAbyss,
        bg_border = plt.deepBlack,
        bg_sbar = plt.deepBlack,
        bg_thumb = plt.oceanBlack,
      },
      tabline = {
        bg = plt.abyssBlack,
        bg_inactive = plt.abyssBlack,
        bg_selected = plt.deepBlack,
        bg_alternate = plt.deepBlack,
        fg_inactive = plt.greenMid,
        fg_selected = plt.tealCrest,
        fg_alternate = plt.tealBright,
        indicator = plt.bioGlow,
      },
    },
    syn = {
      attribute = plt.bioGlow,
      boolean = plt.tealCrest,
      comment = plt.greenMid,
      constant = plt.seafoamBright,
      deprecated = plt.oceanBlack,
      func = plt.tealBright,
      identifier = plt.seafoamBright,
      keyword = plt.tealCrest,
      method = plt.tealBright,
      number = plt.tealShimmer,
      operator = plt.tealMid,
      parameter = plt.seafoamPale,
      preproc = plt.bioGlow,
      punct = plt.tealMid,
      regex = plt.greenSurface,
      special = plt.tealShimmer,
      special2 = plt.bioGlow,
      special3 = plt.tealCrest,
      statement = plt.tealCrest,
      string = plt.greenSurface,
      symbol = plt.tealShimmer,
      type = plt.tealBright,
      variable = plt.seafoamBright,
    },
    diag = {
      error = plt.tealDeep,
      warning = plt.greenSurface,
      info = plt.tealBright,
      hint = plt.bioFaint,
      ok = plt.bioGlow,
      virtual_text_error = plt.tealDeep,
      virtual_text_warning = plt.greenSurface,
      virtual_text_info = plt.tealBright,
      virtual_text_hint = plt.bioFaint,
      virtual_text_ok = plt.bioGlow,
    },
    diff = {
      add = plt.greenAbyss,
      add_inline = plt.greenMid,
      change = plt.tealDeep,
      change_inline = plt.tealMid,
      delete = color(plt.greenDeep):darken(0.4):to_hex(),
      delete_inline = plt.greenBright,
      text = plt.oceanBlack,
    },
    vcs = {
      added = plt.tealBright,
      changed = plt.tealShimmer,
      removed = plt.greenSurface,
    },
    term = {
      black = plt.abyssBlack,
      red = plt.greenBright,
      green = plt.tealBright,
      yellow = plt.tealShimmer,
      blue = plt.tealDeep,
      magenta = plt.bioGlow,
      cyan = plt.tealCrest,
      white = plt.seafoamBright,
      black_bright = color(plt.abyssBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.greenBright):brighten(0.2):to_hex(),
      green_bright = color(plt.tealBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.tealShimmer):brighten(0.2):to_hex(),
      blue_bright = color(plt.tealDeep):brighten(0.3):to_hex(),
      magenta_bright = color(plt.bioGlow):brighten(0.05):to_hex(),
      cyan_bright = color(plt.tealCrest):brighten(0.1):to_hex(),
      white_bright = color(plt.seafoamBright):brighten(0.05):to_hex(),
      indexed1 = plt.seafoamBright,
      indexed2 = plt.oceanBlack,
    },
  }
end

return {
  name = "Kami – Ryujin",
  author = "PrismPunk.nvim",
  description = "Sea dragon god. Deep ocean greens descend into the abyss; dragon scales shimmer in teal across the dark water. Bioluminescent fire pulses from the deep. The palace beneath the waves.",

  base16 = {
    base00 = palette.abyssBlack,
    base01 = palette.deepBlack,
    base02 = palette.oceanBlack,
    base03 = palette.greenAbyss,
    base04 = palette.greenMid,
    base05 = palette.seafoamBright,
    base06 = palette.tealCrest,
    base07 = palette.seafoamBright,
    base08 = palette.greenBright,
    base09 = palette.greenSurface,
    base0A = palette.tealShimmer,
    base0B = palette.tealBright,
    base0C = palette.tealCrest,
    base0D = palette.bioGlow,
    base0E = palette.bioFaint,
    base0F = palette.seafoamPale,
  },

  palette = palette,
  get = M.get,
}
