local color = require("prismpunk.utils.color")

local palette = {
  midnightBlack = "#08080E",
  voidBlack = "#0E0E18",
  deepBlue = "#141428",
  blueDeepest = "#1A1A3C",
  blueDark = "#242A50",
  blueMid = "#2E3A64",
  blueBright = "#3A4A78",
  silverDeep = "#6A7A8A",
  silverMid = "#8A9AAA",
  silverBright = "#AAC0D0",
  silverPale = "#C0D8E8",
  silverMoon = "#D8E8F8",
  frostWhite = "#E8F0FA",
  moonWhite = "#F0F8FF",
  haloViolet = "#6A7ACA",
  bg_darkest = "#08080E",
  fg_lightest = "#F0F8FF",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.silverBright,
      insert = plt.silverMoon,
      visual = plt.haloViolet,
      replace = plt.blueBright,
      command = plt.silverPale,
    },
    accent = {
      accent1 = plt.silverBright,
      accent2 = plt.silverMoon,
      accent3 = plt.haloViolet,
      accent4 = plt.silverPale,
      accent5 = plt.frostWhite,
      invert = plt.midnightBlack,
    },
    rainbow = {
      rainbow1 = plt.silverBright,
      rainbow2 = plt.silverMoon,
      rainbow3 = plt.haloViolet,
      rainbow4 = plt.silverPale,
      rainbow5 = plt.frostWhite,
      rainbow6 = plt.blueBright,
      rainbow7 = plt.silverMid,
    },
    ui = {
      fg = plt.frostWhite,
      fg_dim = plt.silverMoon,
      fg_dimmer = plt.silverPale,
      fg_dark = plt.silverMid,
      fg_reverse = plt.midnightBlack,
      bg = plt.midnightBlack,
      bg_dim = plt.midnightBlack,
      bg_m1 = plt.voidBlack,
      bg_m2 = plt.deepBlue,
      bg_m3 = plt.blueDeepest,
      bg_m4 = plt.blueDark,
      bg_p1 = plt.voidBlack,
      bg_p2 = plt.deepBlue,
      bg_gutter = (opts.gutter ~= false) and plt.voidBlack or "none",
      bg_cursorline = plt.voidBlack,
      bg_cursorline_alt = plt.deepBlue,
      cursorline = plt.voidBlack,
      bg_highlight = plt.blueDeepest,
      bg_search = plt.blueDark,
      bg_visual = plt.blueDark,
      bg_statusline = plt.voidBlack,
      border = plt.deepBlue,
      header1 = plt.silverMoon,
      header2 = plt.haloViolet,
      special = plt.silverBright,
      nontext = plt.deepBlue,
      whitespace = plt.blueDeepest,
      win_separator = plt.deepBlue,
      indent = plt.voidBlack,
      indent_scope = plt.blueDeepest,
      picker = plt.silverBright,
      yank = plt.silverMoon,
      mark = plt.haloViolet,
      scrollbar = plt.deepBlue,
      selection = plt.blueDeepest,
      line_nr = plt.blueMid,
      line_nr_dim = plt.deepBlue,
      line_nr_active = plt.silverBright,
      float = {
        fg = plt.frostWhite,
        bg = plt.deepBlue,
        fg_border = plt.silverMid,
        bg_border = plt.deepBlue,
      },
      pmenu = {
        fg = plt.frostWhite,
        fg_sel = plt.moonWhite,
        fg_border = plt.silverMid,
        bg = plt.voidBlack,
        bg_sel = plt.blueDeepest,
        bg_border = plt.voidBlack,
        bg_sbar = plt.voidBlack,
        bg_thumb = plt.deepBlue,
      },
      tabline = {
        bg = plt.midnightBlack,
        bg_inactive = plt.midnightBlack,
        bg_selected = plt.voidBlack,
        bg_alternate = plt.voidBlack,
        fg_inactive = plt.blueMid,
        fg_selected = plt.silverMoon,
        fg_alternate = plt.silverBright,
        indicator = plt.haloViolet,
      },
    },
    syn = {
      attribute = plt.haloViolet,
      boolean = plt.silverBright,
      comment = plt.blueMid,
      constant = plt.silverPale,
      deprecated = plt.deepBlue,
      func = plt.silverBright,
      identifier = plt.frostWhite,
      keyword = plt.silverMoon,
      method = plt.silverBright,
      number = plt.silverPale,
      operator = plt.silverMid,
      parameter = plt.frostWhite,
      preproc = plt.haloViolet,
      punct = plt.silverMid,
      regex = plt.silverDeep,
      special = plt.silverMoon,
      special2 = plt.haloViolet,
      special3 = plt.silverBright,
      statement = plt.silverMoon,
      string = plt.silverPale,
      symbol = plt.silverBright,
      type = plt.silverMid,
      variable = plt.frostWhite,
    },
    diag = {
      error = plt.blueBright,
      warning = plt.silverDeep,
      info = plt.silverBright,
      hint = plt.haloViolet,
      ok = plt.silverMoon,
      virtual_text_error = plt.blueBright,
      virtual_text_warning = plt.silverDeep,
      virtual_text_info = plt.silverBright,
      virtual_text_hint = plt.haloViolet,
      virtual_text_ok = plt.silverMoon,
    },
    diff = {
      add = plt.blueDeepest,
      add_inline = plt.blueDark,
      change = plt.blueDark,
      change_inline = plt.blueMid,
      delete = color(plt.deepBlue):darken(0.3):to_hex(),
      delete_inline = plt.blueBright,
      text = plt.deepBlue,
    },
    vcs = {
      added = plt.silverBright,
      changed = plt.silverPale,
      removed = plt.blueBright,
    },
    term = {
      black = plt.midnightBlack,
      red = plt.blueBright,
      green = plt.silverMid,
      yellow = plt.silverPale,
      blue = plt.blueMid,
      magenta = plt.haloViolet,
      cyan = plt.silverBright,
      white = plt.frostWhite,
      black_bright = color(plt.midnightBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.blueBright):brighten(0.2):to_hex(),
      green_bright = color(plt.silverMid):brighten(0.2):to_hex(),
      yellow_bright = color(plt.silverPale):brighten(0.1):to_hex(),
      blue_bright = color(plt.blueMid):brighten(0.3):to_hex(),
      magenta_bright = color(plt.haloViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.silverBright):brighten(0.1):to_hex(),
      white_bright = color(plt.frostWhite):brighten(0.05):to_hex(),
      indexed1 = plt.moonWhite,
      indexed2 = plt.deepBlue,
    },
  }
end

return {
  name = "Kami – Tsukuyomi",
  author = "PrismPunk.nvim",
  description = "Moon god. Cold silver-whites reflect across deep midnight blue. Lunar surface, frost on metal, the quiet light that rules the night sky.",

  base16 = {
    base00 = palette.midnightBlack,
    base01 = palette.voidBlack,
    base02 = palette.deepBlue,
    base03 = palette.blueDeepest,
    base04 = palette.blueMid,
    base05 = palette.frostWhite,
    base06 = palette.silverMoon,
    base07 = palette.moonWhite,
    base08 = palette.blueBright,
    base09 = palette.silverDeep,
    base0A = palette.silverPale,
    base0B = palette.silverMid,
    base0C = palette.silverBright,
    base0D = palette.silverMoon,
    base0E = palette.haloViolet,
    base0F = palette.frostWhite,
  },

  palette = palette,
  get = M.get,
}
