local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0F0A05",
  bg_darker = "#1A120A",
  bg_dark = "#251A10",
  bg_mid = "#302316",
  bg_light = "#3D2D1C",
  bg_lighter = "#4A3722",
  bg_lightest = "#57412A",
  fg_lightest = "#FFF8E8",
  fg_light = "#F0E6D0",
  fg_mid = "#D8C8A8",
  fg_dark = "#B8A888",
  bg_alt1 = "#150F08",
  bg_alt2 = "#0A0602",
  bg_alt3 = "#1F1710",
  bg_alt4 = "#050301",
  reporterYellow = "#FFD700",
  reporterYellowBright = "#FFEA4D",
  reporterYellowCore = "#F0C800",
  reporterYellowDeep = "#D4AF37",
  reporterYellowDark = "#B89530",
  jacketYellow = "#FFDB58",
  jacketYellowBright = "#FFE97D",
  jacketYellowCore = "#F0C745",
  jacketYellowDeep = "#D4A838",
  newsRed = "#D94A4A",
  newsRedBright = "#FF5F5F",
  newsRedCore = "#C23838",
  newsRedDeep = "#A02828",
  cameraGray = "#8A8480",
  cameraGrayLight = "#9F9A95",
  cameraGrayDark = "#6F6B68",
  microphoneBlue = "#4A7A9A",
  microphoneBlueBright = "#5F9AB8",
  microphoneBlueCore = "#3A627A",
  microphoneBlueDeep = "#2D4A5F",
  notebookPaper = "#EFE8D8",
  notebookPaperAged = "#D8D0B8",
  notebookInk = "#3A3128",
  pressPassGreen = "#5A7A5A",
  pressPassGreenBright = "#7A9A7A",
  pressPassGreenCore = "#4A6248",
  pressPassGreenDeep = "#3A4A38",
  channelSix = "#5F8FB8",
  channelSixBright = "#7DAFD8",
  channelSixCore = "#4A7098",
  channelSixDeep = "#385678",
  headlineBlack = "#2A2520",
  headlineBlackDeep = "#1A1510",
  truthOrange = "#D97A4A",
  truthOrangeBright = "#FF9565",
  truthOrangeDeep = "#B86238",
  investigatePurple = "#8A6B9A",
  investigatePurpleBright = "#A885B8",
  investigatePurpleCore = "#6F5678",
  investigatePurpleDeep = "#5A4460",
  studioLights = "#FFF5D0",
  studioLightsDim = "#E8D8B0",
  dangerRed = "#E74C3C",
  warningAmber = "#F39C12",
  infoBlue = "#3498DB",
  successGreen = "#27AE60",
  newsroom = "#1F1710",
  breakingNews = "#D94A38",
  journalist = "#D4AF37",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.reporterYellowCore,
      insert = plt.pressPassGreen,
      visual = plt.microphoneBlue,
      replace = plt.newsRed,
      command = plt.truthOrange,
    },
    accent = {
      accent1 = plt.reporterYellowCore,
      accent2 = plt.truthOrange,
      accent3 = plt.channelSix,
      accent4 = plt.investigatePurple,
      accent5 = plt.pressPassGreen,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.reporterYellowBright,
      rainbow2 = plt.truthOrangeBright,
      rainbow3 = plt.channelSixBright,
      rainbow4 = plt.pressPassGreenBright,
      rainbow5 = plt.investigatePurpleBright,
      rainbow6 = plt.microphoneBlueBright,
      rainbow7 = plt.newsRedBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.truthOrangeDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.cameraGray,
      header1 = plt.channelSixBright,
      header2 = plt.reporterYellowBright,
      special = plt.channelSix,
      nontext = plt.headlineBlackDeep,
      whitespace = plt.cameraGrayDark,
      win_separator = plt.cameraGray,
      indent = plt.bg_lighter,
      indent_scope = plt.channelSixCore,
      picker = plt.investigatePurple,
      yank = plt.reporterYellowBright,
      mark = plt.truthOrangeBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.cameraGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.cameraGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.cameraGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.channelSixBright,
        indicator = plt.reporterYellowCore,
      },
    },
    syn = {
      attribute = plt.truthOrange,
      boolean = plt.newsRed,
      comment = plt.cameraGray,
      constant = plt.notebookPaper,
      deprecated = plt.cameraGrayDark,
      func = plt.channelSix,
      identifier = plt.fg_lightest,
      keyword = plt.reporterYellowCore,
      method = plt.channelSixBright,
      number = plt.truthOrange,
      operator = plt.pressPassGreen,
      parameter = plt.fg_mid,
      preproc = plt.investigatePurple,
      punct = plt.fg_dark,
      regex = plt.investigatePurpleDeep,
      special = plt.channelSix,
      special2 = plt.investigatePurple,
      special3 = plt.pressPassGreen,
      statement = plt.reporterYellowCore,
      string = plt.pressPassGreen,
      symbol = plt.jacketYellow,
      type = plt.microphoneBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.channelSix,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.channelSix,
    },
    diff = {
      add = plt.pressPassGreen,
      add_inline = plt.pressPassGreenDeep,
      change = plt.truthOrange,
      change_inline = plt.truthOrangeDeep,
      delete = plt.newsRed,
      delete_inline = plt.newsRedDeep,
      text = plt.channelSix,
    },
    vcs = {
      added = plt.pressPassGreen,
      changed = plt.truthOrange,
      removed = plt.newsRed,
    },
    term = {
      black = plt.newsroom,
      red = plt.newsRedCore,
      green = plt.pressPassGreenCore,
      yellow = plt.reporterYellowCore,
      blue = plt.microphoneBlueCore,
      magenta = plt.investigatePurpleCore,
      cyan = plt.channelSixCore,
      white = plt.notebookPaper,
      black_bright = color(plt.newsroom):brighten(0.6):to_hex(),
      red_bright = color(plt.newsRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.pressPassGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.jacketYellowBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.microphoneBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.investigatePurpleBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.channelSixBright):brighten(0.2):to_hex(),
      white_bright = color(plt.studioLights):brighten(0.2):to_hex(),
      indexed1 = plt.reporterYellow,
      indexed2 = plt.newsRed,
    },
  }
end

return {
  name = "TMNT – April O'Neal",
  author = "PrismPunk.nvim",
  description = "Investigative reporter — truth-seeker, brave journalist, Channel 6 News.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.cameraGray,
    base04 = palette.cameraGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.newsRed,
    base09 = palette.truthOrange,
    base0A = palette.reporterYellow,
    base0B = palette.pressPassGreen,
    base0C = palette.channelSix,
    base0D = palette.microphoneBlue,
    base0E = palette.investigatePurple,
    base0F = palette.notebookInk,
  },
  palette = palette,
  get = M.get,
}
