local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.april-oneal")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.reporterYellowCore,
      insert = plt.pressPassGreen,
      visual = plt.microphoneBlue,
      replace = plt.newsRed,
      command = plt.truthOrange,
    },
    accent = {
      accent1 = plt.reporterYellowCore,
      accent2 = plt.truthOrange,
      accent3 = plt.channelSix,
      accent4 = plt.investigatePurple,
      accent5 = plt.pressPassGreen,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.reporterYellowBright,
      rainbow2 = plt.truthOrangeBright,
      rainbow3 = plt.channelSixBright,
      rainbow4 = plt.pressPassGreenBright,
      rainbow5 = plt.investigatePurpleBright,
      rainbow6 = plt.microphoneBlueBright,
      rainbow7 = plt.newsRedBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.truthOrangeDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.cameraGray,
      header1 = plt.channelSixBright,
      header2 = plt.reporterYellowBright,
      special = plt.channelSix,
      nontext = plt.headlineBlackDeep,
      whitespace = plt.cameraGrayDark,
      win_separator = plt.cameraGray,
      indent = plt.bg_lighter,
      indent_scope = plt.channelSixCore,
      picker = plt.investigatePurple,
      yank = plt.reporterYellowBright,
      mark = plt.truthOrangeBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.cameraGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.cameraGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.cameraGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.channelSixBright,
        indicator = plt.reporterYellowCore,
      },
    },
    syn = {
      attribute = plt.truthOrange,
      boolean = plt.newsRed,
      comment = plt.cameraGray,
      constant = plt.notebookPaper,
      deprecated = plt.cameraGrayDark,
      func = plt.channelSix,
      identifier = plt.fg_lightest,
      keyword = plt.reporterYellowCore,
      method = plt.channelSixBright,
      number = plt.truthOrange,
      operator = plt.pressPassGreen,
      parameter = plt.fg_mid,
      preproc = plt.investigatePurple,
      punct = plt.fg_dark,
      regex = plt.investigatePurpleDeep,
      special = plt.channelSix,
      special2 = plt.investigatePurple,
      special3 = plt.pressPassGreen,
      statement = plt.reporterYellowCore,
      string = plt.pressPassGreen,
      symbol = plt.jacketYellow,
      type = plt.microphoneBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.channelSix,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.channelSix,
    },
    diff = {
      add = plt.pressPassGreen,
      add_inline = plt.pressPassGreenDeep,
      change = plt.truthOrange,
      change_inline = plt.truthOrangeDeep,
      delete = plt.newsRed,
      delete_inline = plt.newsRedDeep,
      text = plt.channelSix,
    },
    vcs = {
      added = plt.pressPassGreen,
      changed = plt.truthOrange,
      removed = plt.newsRed,
    },
    term = {
      black = plt.newsroom,
      red = plt.newsRedCore,
      green = plt.pressPassGreenCore,
      yellow = plt.reporterYellowCore,
      blue = plt.microphoneBlueCore,
      magenta = plt.investigatePurpleCore,
      cyan = plt.channelSixCore,
      white = plt.notebookPaper,
      black_bright = color(plt.newsroom):brighten(0.6):to_hex(),
      red_bright = color(plt.newsRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.pressPassGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.jacketYellowBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.microphoneBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.investigatePurpleBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.channelSixBright):brighten(0.2):to_hex(),
      white_bright = color(plt.studioLights):brighten(0.2):to_hex(),
      indexed1 = plt.reporterYellow,
      indexed2 = plt.newsRed,
    },
  }
end

return {
  name = "TMNT – April O'Neal",
  author = "PrismPunk.nvim",
  description = "Investigative reporter — truth-seeker, brave journalist, Channel 6 News.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.cameraGray,
    base04 = palette.cameraGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.newsRed,
    base09 = palette.truthOrange,
    base0A = palette.reporterYellow,
    base0B = palette.pressPassGreen,
    base0C = palette.channelSix,
    base0D = palette.microphoneBlue,
    base0E = palette.investigatePurple,
    base0F = palette.notebookInk,
  },
  palette = palette,
  get = M.get,
}
