local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.last-ronin")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.roninGrayCore,
      insert = plt.rainSteel,
      visual = plt.moonlight,
      replace = plt.vengeance,
      command = plt.ashGray,
    },
    accent = {
      accent1 = plt.roninGrayCore,
      accent2 = plt.fadedBlue,
      accent3 = plt.fadedRed,
      accent4 = plt.fadedPurple,
      accent5 = plt.fadedOrange,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.roninGrayBright,
      rainbow2 = plt.fadedBlueBright,
      rainbow3 = plt.fadedRedBright,
      rainbow4 = plt.fadedPurpleBright,
      rainbow5 = plt.fadedOrangeBright,
      rainbow6 = plt.ashGrayLight,
      rainbow7 = plt.moonlightBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.moonlightDim,
      bg_visual = plt.shadowBlack,
      bg_statusline = plt.bg_light,
      border = plt.scarTissue,
      header1 = plt.moonlightBright,
      header2 = plt.roninGrayBright,
      special = plt.moonlight,
      nontext = plt.shadowBlackDeep,
      whitespace = plt.ashGrayDark,
      win_separator = plt.scarTissue,
      indent = plt.bg_lighter,
      indent_scope = plt.roninGrayCore,
      picker = plt.fadedPurple,
      yank = plt.moonlightBright,
      mark = plt.vengeance,
      scrollbar = plt.bg_lighter,
      selection = plt.shadowBlack,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.scarTissue,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.scarTissue,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.scarTissue,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.moonlight,
        indicator = plt.roninGrayCore,
      },
    },
    syn = {
      attribute = plt.ashGray,
      boolean = plt.fadedBlue,
      comment = plt.ashGray,
      constant = plt.moonlight,
      deprecated = plt.oldWound,
      func = plt.fadedPurple,
      identifier = plt.fg_lightest,
      keyword = plt.roninGrayCore,
      method = plt.fadedPurpleBright,
      number = plt.fadedOrange,
      operator = plt.rainSteel,
      parameter = plt.fg_mid,
      preproc = plt.fadedBlue,
      punct = plt.fg_dark,
      regex = plt.scarTissue,
      special = plt.moonlight,
      special2 = plt.rainSteelBright,
      special3 = plt.vengeance,
      statement = plt.roninGrayCore,
      string = plt.rainSteel,
      symbol = plt.moonlight,
      type = plt.fadedBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.vengeance,
      warning = plt.fadedOrangeBright,
      info = plt.moonlight,
      ok = plt.rainSteelBright,
      hint = plt.moonlightDim,
      virtual_text_error = plt.vengeanceDeep,
      virtual_text_warning = plt.fadedOrangeBright,
      virtual_text_info = plt.moonlightDim,
      virtual_text_ok = plt.rainSteelBright,
      virtual_text_hint = plt.moonlightDim,
    },
    diff = {
      add = plt.rainSteel,
      add_inline = plt.rainSteelDeep,
      change = plt.fadedOrange,
      change_inline = plt.fadedOrangeDeep,
      delete = plt.bloodRust,
      delete_inline = plt.bloodRustDeep,
      text = plt.moonlight,
    },
    vcs = {
      added = plt.rainSteel,
      changed = plt.fadedOrange,
      removed = plt.bloodRust,
    },
    term = {
      black = plt.shadowBlackDeep,
      red = plt.fadedRedCore,
      green = plt.rainSteelCore,
      yellow = plt.fadedOrangeCore,
      blue = plt.fadedBlueCore,
      magenta = plt.fadedPurpleCore,
      cyan = plt.moonlight,
      white = plt.ashGray,
      black_bright = color(plt.shadowBlackDeep):brighten(0.6):to_hex(),
      red_bright = color(plt.fadedRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.rainSteelBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.fadedOrangeBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.fadedBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.fadedPurpleBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.moonlightBright):brighten(0.2):to_hex(),
      white_bright = color(plt.ashGrayLight):brighten(0.2):to_hex(),
      indexed1 = plt.vengeance,
      indexed2 = plt.moonlight,
    },
  }
end

return {
  name = "TMNT – The Last Ronin",
  author = "PrismPunk.nvim",
  description = "Sole survivor — grief-stricken, vengeful, carrying all brothers' legacies.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.ashGray,
    base04 = palette.scarTissue,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.fadedRed,
    base09 = palette.fadedOrange,
    base0A = palette.moonlight,
    base0B = palette.rainSteel,
    base0C = palette.moonlightBright,
    base0D = palette.fadedBlue,
    base0E = palette.fadedPurple,
    base0F = palette.bloodRust,
  },
  palette = palette,
  get = M.get,
}
