local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.raphael")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.rageRedCore,
      insert = plt.toughGreen,
      visual = plt.fireOrange,
      replace = plt.crimsonFury,
      command = plt.angerYellow,
    },
    accent = {
      accent1 = plt.rageRedCore,
      accent2 = plt.fireOrange,
      accent3 = plt.crimsonFury,
      accent4 = plt.saiSilver,
      accent5 = plt.rebellionPurple,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.rageRedBright,
      rainbow2 = plt.crimsonFuryBright,
      rainbow3 = plt.fireOrangeBright,
      rainbow4 = plt.angerYellowBright,
      rainbow5 = plt.rebellionPurpleBright,
      rainbow6 = plt.saiSilver,
      rainbow7 = plt.toughGreenBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.angerYellowDeep,
      bg_visual = plt.shadowRed,
      bg_statusline = plt.bg_light,
      border = plt.saiSteel,
      header1 = plt.fireOrangeBright,
      header2 = plt.angerYellow,
      special = plt.crimsonFury,
      nontext = plt.fg_dark,
      whitespace = plt.grittyConcrete,
      win_separator = plt.saiSteel,
      indent = plt.bg_lighter,
      indent_scope = plt.rageRedCore,
      picker = plt.rebellionPurple,
      yank = plt.angerYellowBright,
      mark = plt.rageRedBright,
      scrollbar = plt.bg_lighter,
      selection = plt.shadowRed,
      line_nr = plt.fg_light,
      line_nr_dim = plt.fg_dark,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.saiSteel,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.saiEdge,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.saiEdge,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.crimsonFuryBright,
        indicator = plt.rageRedCore,
      },
    },
    syn = {
      attribute = plt.fireOrange,
      boolean = plt.crimsonFury,
      comment = plt.fg_mid,
      constant = plt.saiSilver,
      deprecated = plt.fg_dark,
      func = plt.fireOrange,
      identifier = plt.fg_lightest,
      keyword = plt.rageRedCore,
      method = plt.fireOrangeBright,
      number = plt.angerYellow,
      operator = plt.saiEdge,
      parameter = plt.fg_light,
      preproc = plt.rebellionPurple,
      punct = plt.fg_mid,
      regex = plt.rebellionPurple,
      special = plt.fireOrange,
      special2 = plt.rebellionPurpleBright,
      special3 = plt.toughGreen,
      statement = plt.rageRedCore,
      string = plt.toughGreenBright,
      symbol = plt.fireOrange,
      type = plt.saiSilver,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.fireOrange,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.fireOrange,
    },
    diff = {
      add = plt.toughGreen,
      add_inline = plt.toughGreenDeep,
      change = plt.fireOrange,
      change_inline = plt.fireOrangeDeep,
      delete = plt.rageRedCore,
      delete_inline = plt.rageRedDeep,
      text = plt.angerYellow,
    },
    vcs = {
      added = plt.toughGreen,
      changed = plt.fireOrange,
      removed = plt.rageRedCore,
    },
    term = {
      black = plt.alleyDark,
      red = plt.rageRedCore,
      green = plt.toughGreen,
      yellow = plt.angerYellow,
      blue = plt.rebellionPurple,
      magenta = plt.crimsonFury,
      cyan = plt.saiSilver,
      white = plt.fg_light,
      black_bright = color(plt.alleyDark):brighten(0.6):to_hex(),
      red_bright = color(plt.rageRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.toughGreen):brighten(0.2):to_hex(),
      yellow_bright = color(plt.angerYellowBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.rebellionPurpleBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.crimsonFuryBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.saiSilver):brighten(0.2):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.rageRed,
      indexed2 = plt.rebellionPurple,
    },
  }
end

return {
  name = "TMNT – Raphael",
  author = "PrismPunk.nvim",
  description = "Hot-headed warrior — fierce, passionate, rebellious.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.steelGray,
    base04 = palette.grittyConcrete,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.rageRedCore,
    base09 = palette.fireOrange,
    base0A = palette.angerYellow,
    base0B = palette.toughGreen,
    base0C = palette.saiSilver,
    base0D = palette.crimsonFury,
    base0E = palette.rebellionPurple,
    base0F = palette.rustBrown,
  },
  palette = palette,
  get = M.get,
}
