local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.shredder")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.bladeSteelCore,
      insert = plt.evilGreen,
      visual = plt.shadowPurple,
      replace = plt.crimsonRage,
      command = plt.armorSilver,
    },
    accent = {
      accent1 = plt.bladeSteelCore,
      accent2 = plt.crimsonRage,
      accent3 = plt.shadowPurple,
      accent4 = plt.armorSilver,
      accent5 = plt.vengeanceViolet,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.armorSilverBright,
      rainbow2 = plt.bladeSteelBright,
      rainbow3 = plt.crimsonRageBright,
      rainbow4 = plt.footClanRedBright,
      rainbow5 = plt.shadowPurpleBright,
      rainbow6 = plt.vengeanceVioletBright,
      rainbow7 = plt.darkPowerBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.darkPowerBright,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.bladeSteelCore,
      header1 = plt.crimsonRageBright,
      header2 = plt.armorSilverBright,
      special = plt.vengeanceViolet,
      nontext = plt.helmetDarkDeep,
      whitespace = plt.shuriken,
      win_separator = plt.bladeSteelCore,
      indent = plt.bg_lighter,
      indent_scope = plt.bladeSteelCore,
      picker = plt.darkPowerCore,
      yank = plt.crimsonRageBright,
      mark = plt.footClanRedBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.bladeSteelCore,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.bladeSteelCore,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bladeSteelCore,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.shadowPurpleBright,
        indicator = plt.bladeSteelCore,
      },
    },
    syn = {
      attribute = plt.crimsonRage,
      boolean = plt.footClanRed,
      comment = plt.shuriken,
      constant = plt.armorSilver,
      deprecated = plt.helmetDark,
      func = plt.shadowPurple,
      identifier = plt.fg_lightest,
      keyword = plt.bladeSteelCore,
      method = plt.shadowPurpleBright,
      number = plt.crimsonRageCore,
      operator = plt.spikesSilver,
      parameter = plt.fg_mid,
      preproc = plt.vengeanceViolet,
      punct = plt.fg_dark,
      regex = plt.darkPowerCore,
      special = plt.vengeanceViolet,
      special2 = plt.vengeanceVioletBright,
      special3 = plt.darkPower,
      statement = plt.bladeSteelCore,
      string = plt.evilGreen,
      symbol = plt.spikesSilverSharp,
      type = plt.armorSilverCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.crimsonRage,
      warning = plt.footClanRedBright,
      info = plt.bladeSteelBright,
      ok = plt.evilGreenBright,
      hint = plt.shadowPurple,
      virtual_text_error = plt.crimsonRageDeep,
      virtual_text_warning = plt.footClanRedCore,
      virtual_text_info = plt.bladeSteelCore,
      virtual_text_ok = plt.evilGreenCore,
      virtual_text_hint = plt.shadowPurpleCore,
    },
    diff = {
      add = plt.evilGreen,
      add_inline = plt.evilGreenDeep,
      change = plt.footClanRed,
      change_inline = plt.footClanRedDeep,
      delete = plt.crimsonRage,
      delete_inline = plt.crimsonRageDeep,
      text = plt.shadowPurple,
    },
    vcs = {
      added = plt.evilGreen,
      changed = plt.footClanRed,
      removed = plt.crimsonRage,
    },
    term = {
      black = plt.helmetDarkDeep,
      red = plt.crimsonRageCore,
      green = plt.evilGreenCore,
      yellow = plt.footClanRedBright,
      blue = plt.darkPowerBright,
      magenta = plt.vengeanceVioletCore,
      cyan = plt.shadowPurpleCore,
      white = plt.armorSilver,
      black_bright = color(plt.helmetDarkDeep):brighten(0.6):to_hex(),
      red_bright = color(plt.crimsonRageBright):brighten(0.2):to_hex(),
      green_bright = color(plt.evilGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.footClanRedBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.darkPowerBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.vengeanceVioletBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.shadowPurpleBright):brighten(0.2):to_hex(),
      white_bright = color(plt.armorSilverBright):brighten(0.2):to_hex(),
      indexed1 = plt.crimsonRage,
      indexed2 = plt.darkPower,
    },
  }
end

return {
  name = "TMNT – Shredder",
  author = "PrismPunk.nvim",
  description = "Master of evil — bladed armor, crimson rage, Foot Clan leader.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shuriken,
    base04 = palette.spikesSilver,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.crimsonRage,
    base09 = palette.footClanRed,
    base0A = palette.armorSilver,
    base0B = palette.evilGreen,
    base0C = palette.shadowPurple,
    base0D = palette.bladeSteelCore,
    base0E = palette.vengeanceViolet,
    base0F = palette.helmetDark,
  },
  palette = palette,
  get = M.get,
}
