local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.tmnt.splinter")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.wisdomGrayCore,
      insert = plt.zenGreen,
      visual = plt.meditationPurple,
      replace = plt.ancientRed,
      command = plt.candleGold,
    },
    accent = {
      accent1 = plt.wisdomGrayCore,
      accent2 = plt.senseiRobe,
      accent3 = plt.candleGold,
      accent4 = plt.meditationPurple,
      accent5 = plt.zenGreen,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.wisdomGrayBright,
      rainbow2 = plt.senseiRobeBright,
      rainbow3 = plt.candleGoldBright,
      rainbow4 = plt.zenGreenBright,
      rainbow5 = plt.meditationPurpleBright,
      rainbow6 = plt.spiritualBlueBright,
      rainbow7 = plt.teaGreenBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.candleGoldDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.tatamiBrown,
      header1 = plt.candleGoldBright,
      header2 = plt.meditationPurpleBright,
      special = plt.meditationPurple,
      nontext = plt.dojoWoodDark,
      whitespace = plt.incenseSmokeDark,
      win_separator = plt.tatamiBrown,
      indent = plt.bg_lighter,
      indent_scope = plt.wisdomGrayCore,
      picker = plt.spiritualBlue,
      yank = plt.candleGoldBright,
      mark = plt.teaGreenBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.tatamiBrown,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.tatamiBrown,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.tatamiBrown,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.meditationPurpleBright,
        indicator = plt.wisdomGrayCore,
      },
    },
    syn = {
      attribute = plt.candleGold,
      boolean = plt.meditationPurple,
      comment = plt.incenseSmoke,
      constant = plt.scrollPaper,
      deprecated = plt.incenseSmokeDark,
      func = plt.meditationPurple,
      identifier = plt.fg_lightest,
      keyword = plt.wisdomGrayCore,
      method = plt.meditationPurpleBright,
      number = plt.candleGold,
      operator = plt.zenGreen,
      parameter = plt.fg_mid,
      preproc = plt.spiritualBlue,
      punct = plt.fg_dark,
      regex = plt.teaGreenDeep,
      special = plt.meditationPurple,
      special2 = plt.spiritualBlue,
      special3 = plt.teaGreen,
      statement = plt.wisdomGrayCore,
      string = plt.zenGreen,
      symbol = plt.candleGold,
      type = plt.senseiRobe,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.ancientRedDeep,
      warning = plt.candleGoldBright,
      info = plt.spiritualBlueBright,
      ok = plt.zenGreenBright,
      hint = plt.meditationPurpleBright,
      virtual_text_error = plt.ancientRedDeep,
      virtual_text_warning = plt.candleGoldCore,
      virtual_text_info = plt.spiritualBlue,
      virtual_text_ok = plt.zenGreenCore,
      virtual_text_hint = plt.meditationPurpleCore,
    },
    diff = {
      add = plt.zenGreen,
      add_inline = plt.zenGreenDeep,
      change = plt.candleGold,
      change_inline = plt.candleGoldDeep,
      delete = plt.ancientRed,
      delete_inline = plt.ancientRedDeep,
      text = plt.meditationPurple,
    },
    vcs = {
      added = plt.zenGreen,
      changed = plt.candleGold,
      removed = plt.ancientRed,
    },
    term = {
      black = plt.dojoShadow,
      red = plt.ancientRedDeep,
      green = plt.zenGreenCore,
      yellow = plt.candleGoldCore,
      blue = plt.spiritualBlueCore,
      magenta = plt.meditationPurpleCore,
      cyan = plt.teaGreen,
      white = plt.wisdomGray,
      black_bright = color(plt.dojoShadow):brighten(0.6):to_hex(),
      red_bright = color(plt.ancientRedBright):brighten(0.2):to_hex(),
      green_bright = color(plt.zenGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.candleGoldBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.spiritualBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.meditationPurpleBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.teaGreenBright):brighten(0.2):to_hex(),
      white_bright = color(plt.wisdomGrayBright):brighten(0.2):to_hex(),
      indexed1 = plt.candleGold,
      indexed2 = plt.meditationPurple,
    },
  }
end

return {
  name = "TMNT – Master Splinter",
  author = "PrismPunk.nvim",
  description = "Wise sensei — calm, meditative, philosophical master.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.incenseSmoke,
    base04 = palette.tatamiBrown,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.ancientRed,
    base09 = palette.candleGoldDeep,
    base0A = palette.candleGold,
    base0B = palette.zenGreen,
    base0C = palette.teaGreen,
    base0D = palette.spiritualBlue,
    base0E = palette.meditationPurple,
    base0F = palette.dojoWood,
  },
  palette = palette,
  get = M.get,
}
