local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.acidpunk")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.acidGreenCore,
      insert = plt.neonPinkCore,
      visual = plt.toxicCyanCore,
      replace = plt.dripMagentaCore,
      command = plt.radioactiveLimeCore,
    },
    accent = {
      accent1 = plt.acidGreenCore,
      accent2 = plt.toxicCyanCore,
      accent3 = plt.neonPinkCore,
      accent4 = plt.radioactiveLimeCore,
      accent5 = plt.electricPurpleCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.acidGreenBright,
      rainbow2 = plt.neonPinkBright,
      rainbow3 = plt.toxicCyanBright,
      rainbow4 = plt.radioactiveLimeBright,
      rainbow5 = plt.electricPurpleBright,
      rainbow6 = plt.chemicalYellowBright,
      rainbow7 = plt.bioOrangeBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.chemicalYellowCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.neonGray,
      header1 = plt.acidGreenBright,
      header2 = plt.labWhiteCore,
      special = plt.electricPurpleCore,
      nontext = plt.bg_lightest,
      whitespace = plt.neonGrayDark,
      win_separator = plt.neonGray,
      indent = plt.bg_lighter,
      indent_scope = plt.acidGreenCore,
      picker = plt.spillVioletCore,
      yank = plt.chemicalYellowBright,
      mark = plt.bioOrangeBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.neonGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.neonGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.neonGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.acidGreenBright,
        indicator = plt.acidGreenCore,
      },
    },
    syn = {
      attribute = plt.radioactiveLimeCore,
      boolean = plt.toxicCyanCore,
      comment = plt.neonGray,
      constant = plt.labWhiteCore,
      deprecated = plt.voidBlack,
      func = plt.neonPinkCore,
      identifier = plt.fg_lightest,
      keyword = plt.acidGreenCore,
      method = plt.neonPinkBright,
      number = plt.labWhiteCore,
      operator = plt.radioactiveLimeCore,
      parameter = plt.fg_mid,
      preproc = plt.electricPurpleCore,
      punct = plt.fg_dark,
      regex = plt.spillVioletCore,
      special = plt.electricPurpleCore,
      special2 = plt.spillVioletCore,
      special3 = plt.bioOrangeCore,
      statement = plt.acidGreenCore,
      string = plt.neonPinkCore,
      symbol = plt.radioactiveLimeCore,
      type = plt.toxicCyanCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.electricPurpleCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.electricPurpleCore,
    },
    diff = {
      add = plt.biohazardGreenCore,
      add_inline = plt.acidGreenDeep,
      change = plt.chemicalYellowCore,
      change_inline = plt.chemicalYellowBright,
      delete = plt.dripMagentaCore,
      delete_inline = plt.dripMagentaBright,
      text = plt.electricPurpleCore,
    },
    vcs = {
      added = plt.biohazardGreenCore,
      changed = plt.chemicalYellowCore,
      removed = plt.dripMagentaCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.dripMagentaCore,
      green = plt.acidGreenCore,
      yellow = plt.chemicalYellowCore,
      blue = plt.toxicCyanCore,
      magenta = plt.neonPinkCore,
      cyan = plt.glowBlueCore,
      white = plt.labWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.dripMagentaBright):brighten(0.15):to_hex(),
      green_bright = color(plt.acidGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.chemicalYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.toxicCyanBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.neonPinkBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.glowBlueBright):brighten(0.15):to_hex(),
      white_bright = plt.labWhiteBright,
      indexed1 = plt.radioactiveLimeCore,
      indexed2 = plt.spillVioletCore,
    },
  }
end

return {
  name = "Punk – Acidpunk",
  author = "PrismPunk.nvim",
  description = "Neon chemical reactions — toxic green, electric pink, radioactive lime, glowing cyan.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.neonGray,
    base04 = palette.neonGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dripMagentaCore,
    base09 = palette.bioOrangeCore,
    base0A = palette.chemicalYellowCore,
    base0B = palette.neonPinkCore,
    base0C = palette.toxicCyanCore,
    base0D = palette.acidGreenDeep,
    base0E = palette.electricPurpleCore,
    base0F = palette.spillVioletCore,
  },

  palette = palette,
  get = M.get,
}
