local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0C10",
  bg_darker = "#0F1218",
  bg_dark = "#14181F",
  bg_mid = "#1A1E28",
  bg_light = "#202530",
  bg_lighter = "#262C38",
  bg_lightest = "#2C3340",
  fg_lightest = "#F5F8FA",
  fg_light = "#E0E8F0",
  fg_mid = "#C0CCD8",
  fg_dark = "#98A8B8",
  bg_alt1 = "#12151C",
  bg_alt2 = "#0C0E14",
  bg_alt3 = "#181C24",
  bg_alt4 = "#0E1116",
  silverGearCore = "#B0B8C0",
  silverGearBright = "#D0D8E0",
  silverGearDeep = "#A0A8B0",
  silverGearDark = "#808890",
  whiteGoldCore = "#E0D8C8",
  whiteGoldBright = "#FFF8E8",
  whiteGoldDeep = "#D0C8B8",
  whiteGoldDark = "#B0A898",
  sapphireJewelCore = "#264E8E",
  sapphireJewelBright = "#3E6AAE",
  sapphireJewelDeep = "#1E3E7E",
  sapphireJewelDark = "#162E5E",
  rubyJewelCore = "#8E264E",
  rubyJewelBright = "#AE3E5E",
  rubyJewelDeep = "#7E1E3E",
  rubyJewelDark = "#5E162E",
  emeraldJewelCore = "#268E4E",
  emeraldJewelBright = "#3EAE6A",
  emeraldJewelDeep = "#1E7E3E",
  emeraldJewelDark = "#165E2E",
  platinumWhiteCore = "#D8E0E8",
  platinumWhiteBright = "#FFFFFF",
  celestialBlueCore = "#3A5E8E",
  celestialBlueBright = "#5A7EAE",
  celestialBlueDeep = "#2A4E7E",
  celestialBlueDark = "#1A3E6E",
  moonsilverCore = "#C0C8D8",
  moonsilverBright = "#E0E8F8",
  moonsilverDeep = "#B0B8C8",
  moonsilverDark = "#9098A8",
  starlightCore = "#E8E8F5",
  starlightBright = "#FFFFFF",
  tickSilverCore = "#A0A8B8",
  tickSilverBright = "#C0C8D8",
  tockGoldCore = "#C8B898",
  tockGoldBright = "#E8D8B8",
  mechanismGray = "#6E7A88",
  mechanismGrayLight = "#7E8A98",
  mechanismGrayDark = "#5E6A78",
  shadowBlack = "#1E242E",
  successGreen = "#2E9E5A",
  warningAmber = "#D8B848",
  infoBlue = "#4A6E9E",
  errorRed = "#9E2E4E",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.silverGearCore,
      insert = plt.emeraldJewelCore,
      visual = plt.sapphireJewelCore,
      replace = plt.rubyJewelCore,
      command = plt.celestialBlueCore,
    },
    accent = {
      accent1 = plt.silverGearCore,
      accent2 = plt.sapphireJewelCore,
      accent3 = plt.emeraldJewelCore,
      accent4 = plt.whiteGoldCore,
      accent5 = plt.celestialBlueCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.moonsilverBright,
      rainbow2 = plt.whiteGoldBright,
      rainbow3 = plt.sapphireJewelBright,
      rainbow4 = plt.emeraldJewelBright,
      rainbow5 = plt.rubyJewelBright,
      rainbow6 = plt.celestialBlueBright,
      rainbow7 = plt.platinumWhiteBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.tockGoldBright,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.mechanismGray,
      header1 = plt.sapphireJewelBright,
      header2 = plt.whiteGoldBright,
      special = plt.celestialBlueCore,
      nontext = plt.bg_lightest,
      whitespace = plt.mechanismGrayLight,
      win_separator = plt.mechanismGray,
      indent = plt.bg_lighter,
      indent_scope = plt.silverGearCore,
      picker = plt.celestialBlueCore,
      yank = plt.whiteGoldBright,
      mark = plt.rubyJewelBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.mechanismGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.mechanismGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.mechanismGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.sapphireJewelBright,
        indicator = plt.silverGearCore,
      },
    },
    syn = {
      attribute = plt.whiteGoldCore,
      boolean = plt.sapphireJewelCore,
      comment = plt.mechanismGray,
      constant = plt.platinumWhiteCore,
      deprecated = plt.shadowBlack,
      func = plt.emeraldJewelCore,
      identifier = plt.fg_lightest,
      keyword = plt.whiteGoldDark,
      method = plt.emeraldJewelBright,
      number = plt.silverGearDeep,
      operator = plt.sapphireJewelBright,
      parameter = plt.fg_mid,
      preproc = plt.rubyJewelCore,
      punct = plt.fg_dark,
      regex = plt.sapphireJewelCore,
      special = plt.sapphireJewelCore,
      special2 = plt.celestialBlueCore,
      special3 = plt.moonsilverCore,
      statement = plt.celestialBlueBright,
      string = plt.emeraldJewelCore,
      symbol = plt.whiteGoldCore,
      type = plt.tickSilverCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.sapphireJewelCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.sapphireJewelCore,
    },
    diff = {
      add = plt.emeraldJewelCore,
      add_inline = plt.emeraldJewelDeep,
      change = plt.tockGoldCore,
      change_inline = plt.tockGoldBright,
      delete = plt.rubyJewelCore,
      delete_inline = plt.rubyJewelDeep,
      text = plt.sapphireJewelCore,
    },
    vcs = {
      added = plt.emeraldJewelCore,
      changed = plt.tockGoldCore,
      removed = plt.rubyJewelCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.rubyJewelCore,
      green = plt.emeraldJewelCore,
      yellow = plt.tockGoldCore,
      blue = plt.celestialBlueCore,
      magenta = plt.tickSilverCore,
      cyan = plt.moonsilverCore,
      white = plt.platinumWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.rubyJewelBright):brighten(0.15):to_hex(),
      green_bright = color(plt.emeraldJewelBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.tockGoldBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.celestialBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.tickSilverBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.moonsilverBright):brighten(0.15):to_hex(),
      white_bright = plt.starlightBright,
      indexed1 = plt.tockGoldCore,
      indexed2 = plt.celestialBlueCore,
    },
  }
end

return {
  name = "Punk – Clockpunk",
  author = "PrismPunk.nvim",
  description = "Renaissance precision — silver gears, jeweled mechanisms, astronomical elegance, celestial time.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.mechanismGray,
    base04 = palette.mechanismGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.rubyJewelCore,
    base09 = palette.tockGoldCore,
    base0A = palette.whiteGoldCore,
    base0B = palette.emeraldJewelCore,
    base0C = palette.moonsilverCore,
    base0D = palette.celestialBlueCore,
    base0E = palette.sapphireJewelCore,
    base0F = palette.silverGearCore,
  },
  palette = palette,
  get = M.get,
}
