local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.cryopunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.glacierBlueCore,
      insert = plt.frostCyanCore,
      visual = plt.crystalBlueCore,
      replace = plt.frostbiteRedCore,
      command = plt.arcticWhiteCore,
    },
    accent = {
      accent1 = plt.glacierBlueCore,
      accent2 = plt.crystalBlueCore,
      accent3 = plt.frostCyanCore,
      accent4 = plt.arcticWhiteCore,
      accent5 = plt.frozenPurpleCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.glacierBlueBright,
      rainbow2 = plt.frostCyanBright,
      rainbow3 = plt.crystalBlueBright,
      rainbow4 = plt.arcticWhiteBright,
      rainbow5 = plt.frozenPurpleBright,
      rainbow6 = plt.iceBlueBright,
      rainbow7 = plt.tundraTealBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.currentGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.glacierBlueCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.currentGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.currentGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.currentGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.iceBlueCore,
      boolean = plt.crystalBlueCore,
      comment = plt.permafrostGray,
      constant = plt.blizzardWhiteCore,
      deprecated = plt.voidBlack,
      func = plt.frostCyanCore,
      identifier = plt.fg_lightest,
      keyword = plt.glacierBlueCore,
      method = plt.frostCyanBright,
      number = plt.blizzardWhiteCore,
      operator = plt.arcticWhiteCore,
      parameter = plt.fg_mid,
      preproc = plt.frozenPurpleCore,
      punct = plt.fg_dark,
      regex = plt.icicleVioletCore,
      special = plt.frozenPurpleCore,
      statement = plt.glacierBlueCore,
      string = plt.frostCyanCore,
      symbol = plt.iceBlueCore,
      type = plt.crystalBlueCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.frozenPurpleCore,
    },
    diff = {
      add = plt.tundraTealCore,
      change = plt.iceBlueBright,
      delete = plt.frostbiteRedCore,
      text = plt.frozenPurpleCore,
    },
    vcs = {
      added = plt.tundraTealCore,
      changed = plt.iceBlueBright,
      removed = plt.frostbiteRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.frostbiteRedCore,
      green = plt.tundraTealCore,
      yellow = plt.iceBlueCore,
      blue = plt.crystalBlueCore,
      magenta = plt.frozenPurpleCore,
      cyan = plt.frostCyanCore,
      white = plt.blizzardWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.frostbiteRedCore):brighten(0.15):to_hex(),
      green_bright = color(plt.tundraTealBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.iceBlueBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.crystalBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.frozenPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.frostCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.blizzardWhiteBright,
    },
  }
end

return {
  name = "Punk – Cryopunk",
  author = "PrismPunk.nvim",
  description = "Frozen wasteland — glacier blue, frost cyan, crystal ice, arctic white, subzero cold.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.permafrostGray,
    base04 = palette.permafrostGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.frostbiteRedCore,
    base09 = palette.iceBlueCore,
    base0A = palette.arcticWhiteCore,
    base0B = palette.frostCyanCore,
    base0C = palette.tundraTealCore,
    base0D = palette.glacierBlueCore,
    base0E = palette.frozenPurpleCore,
    base0F = palette.icicleVioletCore,
  },
  palette = palette,
  get = M.get,
}
