local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.cyberpunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.cyberCyanCore,
      insert = plt.acidGreenCore,
      visual = plt.neonPinkCore,
      replace = plt.corpRedCore,
      command = plt.dataVioletCore,
    },
    accent = {
      accent1 = plt.cyberCyanCore,
      accent2 = plt.neonPinkCore,
      accent3 = plt.acidGreenCore,
      accent4 = plt.dataVioletCore,
      accent5 = plt.hologramYellowCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.cyberCyanBright,
      rainbow2 = plt.neonPinkBright,
      rainbow3 = plt.acidGreenBright,
      rainbow4 = plt.dataVioletBright,
      rainbow5 = plt.electricBlueBright,
      rainbow6 = plt.hologramYellowBright,
      rainbow7 = plt.hackPurpleBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.cyberCyanCore,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.cyberCyanCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.cyberCyanCore,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.cyberCyanCore,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.darkGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.dataVioletCore,
      boolean = plt.neonPinkCore,
      comment = plt.darkGray,
      constant = plt.hologramYellowCore,
      deprecated = plt.darkGrayDark,
      func = plt.cyberCyanCore,
      identifier = plt.fg_lightest,
      keyword = plt.neonPinkCore,
      method = plt.cyberCyanBright,
      number = plt.hologramYellowCore,
      operator = plt.acidGreenCore,
      parameter = plt.fg_mid,
      preproc = plt.dataVioletCore,
      punct = plt.fg_dark,
      regex = plt.hackPurpleCore,
      special = plt.dataVioletCore,
      statement = plt.neonPinkCore,
      string = plt.acidGreenCore,
      symbol = plt.hologramYellowCore,
      type = plt.electricBlueCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.dataVioletCore,
    },
    diff = {
      add = plt.acidGreenCore,
      change = plt.hologramYellowCore,
      delete = plt.corpRedCore,
      text = plt.cyberCyanCore,
    },
    vcs = {
      added = plt.acidGreenCore,
      changed = plt.hologramYellowCore,
      removed = plt.corpRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.corpRedCore,
      green = plt.acidGreenCore,
      yellow = plt.hologramYellowCore,
      blue = plt.electricBlueCore,
      magenta = plt.neonPinkCore,
      cyan = plt.cyberCyanCore,
      white = plt.chromeWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.corpRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.acidGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.hologramYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.electricBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.neonPinkBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.cyberCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.chromeWhiteBright,
    },
  }
end

return {
  name = "Punk – Cyberpunk",
  author = "PrismPunk.nvim",
  description = "Neon dystopia — cyber cyan, neon pink, acid green, digital rain, high-tech low-life.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.darkGray,
    base04 = palette.darkGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.corpRedCore,
    base09 = palette.warningOrangeCore,
    base0A = palette.hologramYellowCore,
    base0B = palette.acidGreenCore,
    base0C = palette.cyberCyanCore,
    base0D = palette.electricBlueCore,
    base0E = palette.neonPinkCore,
    base0F = palette.dataVioletCore,
  },
  palette = palette,
  get = M.get,
}
