local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.dieselpunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.steelGrayCore,
      insert = plt.militaryGreenCore,
      visual = plt.dieselYellowCore,
      replace = plt.mechRedCore,
      command = plt.metropolisBluCore,
    },
    accent = {
      accent1 = plt.steelGrayCore,
      accent2 = plt.dieselYellowCore,
      accent3 = plt.factoryOrangeCore,
      accent4 = plt.militaryGreenCore,
      accent5 = plt.artDecoGoldCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.dieselYellowBright,
      rainbow2 = plt.factoryOrangeBright,
      rainbow3 = plt.steelGrayBright,
      rainbow4 = plt.militaryGreenBright,
      rainbow5 = plt.metropolisBlueBright,
      rainbow6 = plt.artDecoGoldBright,
      rainbow7 = plt.mechRedBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.exhaustGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.steelGrayCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.exhaustGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.exhaustGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.exhaustGrayBright,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.artDecoGoldCore,
      boolean = plt.factoryOrangeCore,
      comment = plt.exhaustGray,
      constant = plt.chromeWhiteCore,
      deprecated = plt.sootBlackLight,
      func = plt.militaryGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.steelGrayCore,
      method = plt.militaryGreenBright,
      number = plt.chromeWhiteCore,
      operator = plt.dieselYellowCore,
      parameter = plt.fg_mid,
      preproc = plt.metropolisBluCore,
      punct = plt.fg_dark,
      regex = plt.tankGreenCore,
      special = plt.metropolisBluCore,
      statement = plt.steelGrayCore,
      string = plt.militaryGreenCore,
      symbol = plt.artDecoGoldCore,
      type = plt.engineBrownCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.metropolisBluCore,
    },
    diff = {
      add = plt.militaryGreenCore,
      change = plt.factoryOrangeCore,
      delete = plt.mechRedCore,
      text = plt.metropolisBluCore,
    },
    vcs = {
      added = plt.militaryGreenCore,
      changed = plt.factoryOrangeCore,
      removed = plt.mechRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.mechRedCore,
      green = plt.militaryGreenCore,
      yellow = plt.dieselYellowCore,
      blue = plt.metropolisBluCore,
      magenta = plt.engineBrownCore,
      cyan = plt.steelGrayCore,
      white = plt.chromeWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.mechRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.militaryGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.dieselYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.metropolisBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.engineBrownBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.steelGrayBright):brighten(0.18):to_hex(),
      white_bright = color(plt.chromeWhiteBright):brighten(0.1):to_hex(),
    },
  }
end

return {
  name = "Punk – Dieselpunk",
  author = "PrismPunk.nvim",
  description = "Industrial revolution — diesel yellow, steel gray, military green, Art Deco machinery.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.exhaustGray,
    base04 = palette.exhaustGrayBright,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.mechRedCore,
    base09 = palette.factoryOrangeCore,
    base0A = palette.dieselYellowCore,
    base0B = palette.militaryGreenCore,
    base0C = palette.steelGrayCore,
    base0D = palette.metropolisBluCore,
    base0E = palette.artDecoGoldCore,
    base0F = palette.engineBrownCore,
  },
  palette = palette,
  get = M.get,
}
