local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0D1410",
  bg_darker = "#141C17",
  bg_dark = "#1B251F",
  bg_mid = "#232E27",
  bg_light = "#2B372F",
  bg_lighter = "#334038",
  bg_lightest = "#3C4A41",
  fg_lightest = "#E8F5E0",
  fg_light = "#C8DBBB",
  fg_mid = "#A8C196",
  fg_dark = "#88A771",
  bg_alt1 = "#161E19",
  bg_alt2 = "#0F1612",
  bg_alt3 = "#1F271E",
  bg_alt4 = "#111914",
  jungleGreenCore = "#4ADE80",
  jungleGreenBright = "#6EE7A0",
  jungleGreenDeep = "#3ABD6B",
  vineGreenCore = "#22C55E",
  vineGreenBright = "#4ADE80",
  vineGreenDeep = "#16A34A",
  canopyTealCore = "#14B8A6",
  canopyTealBright = "#2DD4BF",
  canopyTealDeep = "#0F9488",
  tropicalOrangeCore = "#FB923C",
  tropicalOrangeBright = "#FDBA74",
  tropicalOrangeDeep = "#F97316",
  sunbeamYellowCore = "#FCD34D",
  sunbeamYellowBright = "#FDE68A",
  sunbeamYellowDeep = "#FACC15",
  orchidPurpleCore = "#C084FC",
  orchidPurpleBright = "#D8B4FE",
  mossGreen = "#6B8E6F",
  mossGreenLight = "#85A889",
  mossGreenDark = "#557059",
  bambooBeigeCore = "#DCC9A8",
  bambooBeigeBright = "#F0E0C4",
  hibiscusRedCore = "#F87171",
  hibiscusRedBright = "#FCA5A5",
  fernGreenCore = "#86EFAC",
  fernGreenBright = "#A7F3D0",
  undergrowthGreenCore = "#4ADE80",
  undergrowthGreenBright = "#6EE7A0",
  wildflowerVioletCore = "#A78BFA",
  currentGray = "#6B8E6F",
  currentGrayLight = "#85A889",
  overgrownBlack = "#0D1410",
  successGreen = "#4ADE80",
  errorRed = "#F87171",
  warningAmber = "#FCD34D",
  infoBlue = "#14B8A6",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.jungleGreenCore,
      insert = plt.vineGreenCore,
      visual = plt.canopyTealCore,
      replace = plt.hibiscusRedCore,
      command = plt.sunbeamYellowCore,
    },
    accent = {
      accent1 = plt.jungleGreenCore,
      accent2 = plt.canopyTealCore,
      accent3 = plt.vineGreenCore,
      accent4 = plt.tropicalOrangeCore,
      accent5 = plt.orchidPurpleCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.jungleGreenBright,
      rainbow2 = plt.vineGreenBright,
      rainbow3 = plt.canopyTealBright,
      rainbow4 = plt.tropicalOrangeBright,
      rainbow5 = plt.orchidPurpleBright,
      rainbow6 = plt.sunbeamYellowBright,
      rainbow7 = plt.fernGreenBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.sunbeamYellowBright,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.currentGray,
      header1 = plt.jungleGreenBright,
      header2 = plt.sunbeamYellowBright,
      special = plt.orchidPurpleCore,
      nontext = plt.bg_lightest,
      whitespace = plt.mossGreenDark,
      win_separator = plt.currentGray,
      indent = plt.bg_lighter,
      indent_scope = plt.jungleGreenCore,
      picker = plt.wildflowerVioletCore,
      yank = plt.sunbeamYellowBright,
      mark = plt.fernGreenBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.currentGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.currentGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.currentGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.jungleGreenBright,
        indicator = plt.jungleGreenCore,
      },
    },
    syn = {
      attribute = plt.tropicalOrangeCore,
      boolean = plt.canopyTealCore,
      comment = plt.mossGreen,
      constant = plt.bambooBeigeCore,
      deprecated = plt.overgrownBlack,
      func = plt.vineGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.jungleGreenCore,
      method = plt.vineGreenBright,
      number = plt.bambooBeigeCore,
      operator = plt.sunbeamYellowCore,
      parameter = plt.fg_mid,
      preproc = plt.orchidPurpleCore,
      punct = plt.fg_dark,
      regex = plt.wildflowerVioletCore,
      special = plt.orchidPurpleCore,
      special2 = plt.wildflowerVioletCore,
      special3 = plt.tropicalOrangeCore,
      statement = plt.jungleGreenCore,
      string = plt.vineGreenCore,
      symbol = plt.tropicalOrangeCore,
      type = plt.canopyTealCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.orchidPurpleCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.orchidPurpleCore,
    },
    diff = {
      add = plt.undergrowthGreenCore,
      add_inline = plt.undergrowthGreenBright,
      change = plt.sunbeamYellowCore,
      change_inline = plt.sunbeamYellowBright,
      delete = plt.hibiscusRedCore,
      delete_inline = plt.hibiscusRedBright,
      text = plt.orchidPurpleCore,
    },
    vcs = {
      added = plt.undergrowthGreenCore,
      changed = plt.sunbeamYellowCore,
      removed = plt.hibiscusRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.hibiscusRedCore,
      green = plt.jungleGreenCore,
      yellow = plt.sunbeamYellowCore,
      blue = plt.canopyTealCore,
      magenta = plt.orchidPurpleCore,
      cyan = plt.vineGreenCore,
      white = plt.bambooBeigeCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.hibiscusRedCore):brighten(0.15):to_hex(),
      green_bright = color(plt.jungleGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.sunbeamYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.canopyTealBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.orchidPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.vineGreenBright):brighten(0.15):to_hex(),
      white_bright = plt.bambooBeigeBright,
      indexed1 = plt.jungleGreenCore,
      indexed2 = plt.orchidPurpleCore,
    },
  }
end

return {
  name = "Punk – Junglepunk",
  author = "PrismPunk.nvim",
  description = "Dense rainforest — jungle green, vine growth, tropical canopy, wild undergrowth.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.mossGreen,
    base04 = palette.mossGreenLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.hibiscusRedCore,
    base09 = palette.tropicalOrangeCore,
    base0A = palette.sunbeamYellowCore,
    base0B = palette.vineGreenCore,
    base0C = palette.canopyTealCore,
    base0D = palette.jungleGreenCore,
    base0E = palette.orchidPurpleCore,
    base0F = palette.wildflowerVioletCore,
  },
  palette = palette,
  get = M.get,
}
