local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.junglepunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.jungleGreenCore,
      insert = plt.vineGreenCore,
      visual = plt.canopyTealCore,
      replace = plt.hibiscusRedCore,
      command = plt.sunbeamYellowCore,
    },
    accent = {
      accent1 = plt.jungleGreenCore,
      accent2 = plt.canopyTealCore,
      accent3 = plt.vineGreenCore,
      accent4 = plt.tropicalOrangeCore,
      accent5 = plt.orchidPurpleCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.jungleGreenBright,
      rainbow2 = plt.vineGreenBright,
      rainbow3 = plt.canopyTealBright,
      rainbow4 = plt.tropicalOrangeBright,
      rainbow5 = plt.orchidPurpleBright,
      rainbow6 = plt.sunbeamYellowBright,
      rainbow7 = plt.fernGreenBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.currentGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.jungleGreenCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.currentGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.currentGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.currentGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.tropicalOrangeCore,
      boolean = plt.canopyTealCore,
      comment = plt.mossGreen,
      constant = plt.bambooBeigeCore,
      deprecated = plt.overgrownBlack,
      func = plt.vineGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.jungleGreenCore,
      method = plt.vineGreenBright,
      number = plt.bambooBeigeCore,
      operator = plt.sunbeamYellowCore,
      parameter = plt.fg_mid,
      preproc = plt.orchidPurpleCore,
      punct = plt.fg_dark,
      regex = plt.wildflowerVioletCore,
      special = plt.orchidPurpleCore,
      statement = plt.jungleGreenCore,
      string = plt.vineGreenCore,
      symbol = plt.tropicalOrangeCore,
      type = plt.canopyTealCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.orchidPurpleCore,
    },
    diff = {
      add = plt.undergrowthGreenCore,
      change = plt.sunbeamYellowCore,
      delete = plt.hibiscusRedCore,
      text = plt.orchidPurpleCore,
    },
    vcs = {
      added = plt.undergrowthGreenCore,
      changed = plt.sunbeamYellowCore,
      removed = plt.hibiscusRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.hibiscusRedCore,
      green = plt.jungleGreenCore,
      yellow = plt.sunbeamYellowCore,
      blue = plt.canopyTealCore,
      magenta = plt.orchidPurpleCore,
      cyan = plt.vineGreenCore,
      white = plt.bambooBeigeCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.hibiscusRedCore):brighten(0.15):to_hex(),
      green_bright = color(plt.jungleGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.sunbeamYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.canopyTealBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.orchidPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.vineGreenBright):brighten(0.15):to_hex(),
      white_bright = plt.bambooBeigeBright,
    },
  }
end

return {
  name = "Punk – Junglepunk",
  author = "PrismPunk.nvim",
  description = "Dense rainforest — jungle green, vine growth, tropical canopy, wild undergrowth.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.mossGreen,
    base04 = palette.mossGreenLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.hibiscusRedCore,
    base09 = palette.tropicalOrangeCore,
    base0A = palette.sunbeamYellowCore,
    base0B = palette.vineGreenCore,
    base0C = palette.canopyTealCore,
    base0D = palette.jungleGreenCore,
    base0E = palette.orchidPurpleCore,
    base0F = palette.wildflowerVioletCore,
  },
  palette = palette,
  get = M.get,
}
