local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.junkpunk")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.rustOrangeCore,
      insert = plt.copperCore,
      visual = plt.steelBlueCore,
      replace = plt.dangerRedCore,
      command = plt.sparkYellowCore,
    },
    accent = {
      accent1 = plt.rustOrangeCore,
      accent2 = plt.steelBlueCore,
      accent3 = plt.copperCore,
      accent4 = plt.sparkYellowCore,
      accent5 = plt.salvagePurpleCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.rustOrangeBright,
      rainbow2 = plt.copperBright,
      rainbow3 = plt.steelBlueBright,
      rainbow4 = plt.sparkYellowBright,
      rainbow5 = plt.toxicGreenBright,
      rainbow6 = plt.brassBright,
      rainbow7 = plt.salvagePurpleBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.sparkYellowCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.currentGray,
      header1 = plt.rustOrangeBright,
      header2 = plt.sparkYellowBright,
      special = plt.salvagePurpleCore,
      nontext = plt.bg_lightest,
      whitespace = plt.scrapGrayLight,
      win_separator = plt.currentGray,
      indent = plt.bg_lighter,
      indent_scope = plt.rustOrangeCore,
      picker = plt.industrialVioletCore,
      yank = plt.sparkYellowBright,
      mark = plt.copperBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.currentGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.currentGrayLight,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.currentGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.steelBlueBright,
        indicator = plt.rustOrangeCore,
      },
    },
    syn = {
      attribute = plt.brassCore,
      boolean = plt.steelBlueCore,
      comment = plt.scrapGray,
      constant = plt.weatheredWhiteCore,
      deprecated = plt.scrapGray,
      func = plt.copperCore,
      identifier = plt.fg_lightest,
      keyword = plt.rustOrangeCore,
      method = plt.copperBright,
      number = plt.weatheredWhiteCore,
      operator = plt.sparkYellowCore,
      parameter = plt.fg_mid,
      preproc = plt.salvagePurpleCore,
      punct = plt.fg_dark,
      regex = plt.industrialVioletCore,
      special = plt.salvagePurpleCore,
      special2 = plt.industrialVioletCore,
      special3 = plt.toxicGreenCore,
      statement = plt.rustOrangeCore,
      string = plt.copperCore,
      symbol = plt.brassCore,
      type = plt.steelBlueCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.salvagePurpleCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.salvagePurpleCore,
    },
    diff = {
      add = plt.toxicGreenCore,
      add_inline = plt.toxicGreenBright,
      change = plt.sparkYellowCore,
      change_inline = plt.sparkYellowBright,
      delete = plt.dangerRedCore,
      delete_inline = plt.dangerRedBright,
      text = plt.salvagePurpleCore,
    },
    vcs = {
      added = plt.toxicGreenCore,
      changed = plt.sparkYellowCore,
      removed = plt.dangerRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.dangerRedCore,
      green = plt.toxicGreenCore,
      yellow = plt.sparkYellowCore,
      blue = plt.steelBlueCore,
      magenta = plt.salvagePurpleCore,
      cyan = plt.copperCore,
      white = plt.weatheredWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.dangerRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.toxicGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.sparkYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.steelBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.salvagePurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.copperBright):brighten(0.15):to_hex(),
      white_bright = plt.weatheredWhiteBright,
      indexed1 = plt.rustOrangeCore,
      indexed2 = plt.salvagePurpleCore,
    },
  }
end

return {
  name = "Punk – Junkpunk",
  author = "PrismPunk.nvim",
  description = "Post-apocalyptic salvage — rusted metal, corroded copper, weathered steel, makeshift tech.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.scrapGray,
    base04 = palette.scrapGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dangerRedCore,
    base09 = palette.sparkYellowCore,
    base0A = palette.brassCore,
    base0B = palette.copperCore,
    base0C = palette.steelBlueCore,
    base0D = palette.rustOrangeCore,
    base0E = palette.salvagePurpleCore,
    base0F = palette.industrialVioletCore,
  },
  palette = palette,
  get = M.get,
}
