local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0F0A",
  bg_darker = "#0F160F",
  bg_dark = "#141D14",
  bg_mid = "#1A241A",
  bg_light = "#202C20",
  bg_lighter = "#263426",
  bg_lightest = "#2C3C2C",
  fg_lightest = "#F0F5E8",
  fg_light = "#D8E4C8",
  fg_mid = "#B8CCA0",
  fg_dark = "#90A878",
  bg_alt1 = "#121812",
  bg_alt2 = "#0C110C",
  bg_alt3 = "#181F18",
  bg_alt4 = "#0E130E",
  solarYellowCore = "#F0C830",
  solarYellowBright = "#FFE76F",
  solarYellowDeep = "#DDB820",
  livingGreenCore = "#5EBD70",
  livingGreenBright = "#7FDF92",
  livingGreenDeep = "#4FA560",
  photosynthesisGreenCore = "#43A047",
  photosynthesisGreenBright = "#66BB6A",
  photosynthesisGreenDeep = "#388E3C",
  windTurquoiseCore = "#36C5C3",
  windTurquoiseBright = "#5FE3E1",
  windTurquoiseDeep = "#2FAAA8",
  skyBlueCore = "#61AED8",
  skyBlueBright = "#88D0ED",
  earthBrownCore = "#7A634A",
  earthBrownBright = "#9F8567",
  bioLimeCore = "#95C554",
  bioLimeBright = "#B7E078",
  bioLimeDeep = "#82AB48",
  renewableOrangeCore = "#FB8C00",
  renewableOrangeBright = "#FFB74D",
  harmonyPurpleCore = "#9C27B0",
  harmonyPurpleBright = "#BA68C8",
  mossGreen = "#7FAC7F",
  mossGreenLight = "#A4CCA4",
  bloomPinkCore = "#E91E63",
  bloomPinkBright = "#F06292",
  forestGray = "#556B55",
  forestGrayLight = "#667C66",
  rootBrown = "#5A4A3A",
  successGreen = "#66BB6A",
  warningAmber = "#FFD93D",
  infoBlue = "#6EC1E4",
  errorRed = "#EF5350",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.livingGreenCore,
      insert = plt.photosynthesisGreenCore,
      visual = plt.solarYellowCore,
      replace = plt.bloomPinkCore,
      command = plt.windTurquoiseCore,
    },
    accent = {
      accent1 = plt.livingGreenCore,
      accent2 = plt.solarYellowCore,
      accent3 = plt.windTurquoiseCore,
      accent4 = plt.photosynthesisGreenCore,
      accent5 = plt.bioLimeCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.solarYellowBright,
      rainbow2 = plt.livingGreenBright,
      rainbow3 = plt.windTurquoiseBright,
      rainbow4 = plt.skyBlueBright,
      rainbow5 = plt.bioLimeBright,
      rainbow6 = plt.harmonyPurpleBright,
      rainbow7 = plt.bloomPinkBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.solarYellowBright,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.forestGray,
      header1 = plt.solarYellowBright,
      header2 = plt.livingGreenBright,
      special = plt.windTurquoiseCore,
      nontext = plt.bg_lightest,
      whitespace = plt.forestGrayLight,
      win_separator = plt.forestGray,
      indent = plt.bg_lighter,
      indent_scope = plt.livingGreenCore,
      picker = plt.harmonyPurpleCore,
      yank = plt.solarYellowBright,
      mark = plt.renewableOrangeBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.forestGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.forestGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.forestGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.skyBlueBright,
        indicator = plt.livingGreenCore,
      },
    },
    syn = {
      attribute = plt.solarYellowCore,
      boolean = plt.windTurquoiseCore,
      comment = plt.forestGray,
      constant = plt.solarYellowCore,
      deprecated = plt.rootBrown,
      func = plt.photosynthesisGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.livingGreenCore,
      method = plt.photosynthesisGreenBright,
      number = plt.solarYellowCore,
      operator = plt.windTurquoiseCore,
      parameter = plt.fg_mid,
      preproc = plt.skyBlueCore,
      punct = plt.fg_dark,
      regex = plt.harmonyPurpleCore,
      special = plt.windTurquoiseCore,
      special2 = plt.harmonyPurpleCore,
      special3 = plt.bioLimeCore,
      statement = plt.livingGreenCore,
      string = plt.bioLimeCore,
      symbol = plt.solarYellowCore,
      type = plt.earthBrownCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.windTurquoiseCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.windTurquoiseCore,
    },
    diff = {
      add = plt.photosynthesisGreenCore,
      add_inline = plt.photosynthesisGreenDeep,
      change = plt.renewableOrangeCore,
      change_inline = plt.renewableOrangeBright,
      delete = plt.bloomPinkCore,
      delete_inline = plt.bloomPinkBright,
      text = plt.windTurquoiseCore,
    },
    vcs = {
      added = plt.photosynthesisGreenCore,
      changed = plt.renewableOrangeCore,
      removed = plt.bloomPinkCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.bloomPinkCore,
      green = plt.photosynthesisGreenCore,
      yellow = plt.solarYellowCore,
      blue = plt.skyBlueCore,
      magenta = plt.harmonyPurpleCore,
      cyan = plt.windTurquoiseCore,
      white = plt.fg_light,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.bloomPinkBright):brighten(0.15):to_hex(),
      green_bright = color(plt.photosynthesisGreenBright):brighten(0.18):to_hex(),
      yellow_bright = color(plt.solarYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.skyBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.harmonyPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.windTurquoiseBright):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_lightest):brighten(0.1):to_hex(),
      indexed1 = plt.solarYellowCore,
      indexed2 = plt.harmonyPurpleCore,
    },
  }
end

return {
  name = "Punk – Solarpunk",
  author = "PrismPunk.nvim",
  description = "Green technology future — solar yellow, living green, wind turquoise, sustainable harmony.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.forestGray,
    base04 = palette.forestGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.bloomPinkCore,
    base09 = palette.renewableOrangeCore,
    base0A = palette.solarYellowCore,
    base0B = palette.bioLimeCore,
    base0C = palette.windTurquoiseCore,
    base0D = palette.skyBlueCore,
    base0E = palette.livingGreenCore,
    base0F = palette.harmonyPurpleCore,
  },
  palette = palette,
  get = M.get,
}
