local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.steampunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.brassGoldCore,
      insert = plt.bronzeGreenCore,
      visual = plt.copperOrangeCore,
      replace = plt.velvetCrimsonCore,
      command = plt.pistonBlueCore,
    },
    accent = {
      accent1 = plt.brassGoldCore,
      accent2 = plt.copperOrangeCore,
      accent3 = plt.cogwheelBrownCore,
      accent4 = plt.bronzeGreenCore,
      accent5 = plt.mahoganyRedCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.brassGoldBright,
      rainbow2 = plt.copperOrangeBright,
      rainbow3 = plt.bronzeGreenBright,
      rainbow4 = plt.mahoganyRedBright,
      rainbow5 = plt.pistonBlueBright,
      rainbow6 = plt.gasLampYellowBright,
      rainbow7 = plt.cogwheelBrownBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.ironGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.brassGoldCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.ironGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.ironGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.ironGrayBright,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.gasLampYellowCore,
      boolean = plt.copperOrangeCore,
      comment = plt.coalSmoke,
      constant = plt.steamWhiteCore,
      deprecated = plt.coalSmokeDark,
      func = plt.bronzeGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.brassGoldCore,
      method = plt.bronzeGreenBright,
      number = plt.steamWhiteCore,
      operator = plt.copperOrangeCore,
      parameter = plt.fg_mid,
      preproc = plt.mahoganyRedCore,
      punct = plt.fg_dark,
      regex = plt.pistonBlueCore,
      special = plt.pistonBlueCore,
      statement = plt.brassGoldCore,
      string = plt.bronzeGreenCore,
      symbol = plt.gasLampYellowCore,
      type = plt.cogwheelBrownCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.pistonBlueCore,
    },
    diff = {
      add = plt.bronzeGreenCore,
      change = plt.copperOrangeCore,
      delete = plt.velvetCrimsonCore,
      text = plt.pistonBlueCore,
    },
    vcs = {
      added = plt.bronzeGreenCore,
      changed = plt.copperOrangeCore,
      removed = plt.velvetCrimsonCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.velvetCrimsonCore,
      green = plt.bronzeGreenCore,
      yellow = plt.gasLampYellowCore,
      blue = plt.pistonBlueCore,
      magenta = plt.mahoganyRedCore,
      cyan = plt.pistonBlueBright,
      white = plt.steamWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.velvetCrimsonBright):brighten(0.15):to_hex(),
      green_bright = color(plt.bronzeGreenBright):brighten(0.18):to_hex(),
      yellow_bright = color(plt.gasLampYellowBright):brighten(0.12):to_hex(),
      blue_bright = color(plt.pistonBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.mahoganyRedBright):brighten(0.18):to_hex(),
      cyan_bright = color(plt.ironGrayBright):brighten(0.2):to_hex(),
      white_bright = color(plt.steamWhiteBright):brighten(0.1):to_hex(),
    },
  }
end

return {
  name = "Punk – Steampunk",
  author = "PrismPunk.nvim",
  description = "Victorian machinery — brass gold, copper orange, cogwheel brown, steam and gears.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.coalSmoke,
    base04 = palette.ironGray,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.velvetCrimsonCore,
    base09 = palette.copperOrangeCore,
    base0A = palette.gasLampYellowCore,
    base0B = palette.bronzeGreenCore,
    base0C = palette.pistonBlueBright,
    base0D = palette.pistonBlueCore,
    base0E = palette.mahoganyRedCore,
    base0F = palette.brassGoldCore,
  },
  palette = palette,
  get = M.get,
}
