local palette = require("prismpunk.palettes.punk-cultures.stonepunk")

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.sandstoneYellowCore,
      insert = plt.mossGreenCore,
      visual = plt.slateBlueCore,
      replace = plt.ironOxideCore,
      command = plt.copperOreCore,
    },
    accent = {
      accent1 = plt.sandstoneYellowCore,
      accent2 = plt.copperOreCore,
      accent3 = plt.slateBlueCore,
      accent4 = plt.mossGreenCore,
      accent5 = plt.graniteGrayCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.sandstoneYellowBright,
      rainbow2 = plt.copperOreBright,
      rainbow3 = plt.slateBlueBright,
      rainbow4 = plt.mossGreenBright,
      rainbow5 = plt.graniteGrayBright,
      rainbow6 = plt.ashGrayBright,
      rainbow7 = plt.limestoneCreamBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.sandstoneYellowCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.rockGray,
      header1 = plt.slateBlueBright,
      header2 = plt.limestoneCreamCore,
      special = plt.copperOreCore,
      nontext = plt.bg_lightest,
      whitespace = plt.rockGrayLight,
      win_separator = plt.rockGray,
      indent = plt.bg_lighter,
      indent_scope = plt.sandstoneYellowCore,
      picker = plt.slateBlueCore,
      yank = plt.sandstoneYellowBright,
      mark = plt.copperOreBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.rockGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.rockGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.rockGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.slateBlueBright,
        indicator = plt.sandstoneYellowCore,
      },
    },
    syn = {
      attribute = plt.sandstoneYellowCore,
      boolean = plt.slateBlueCore,
      comment = plt.ashGrayCore,
      constant = plt.limestoneCreamCore,
      deprecated = plt.boulderGray,
      func = plt.copperOreCore,
      identifier = plt.fg_lightest,
      keyword = plt.sandstoneYellowCore,
      method = plt.copperOreBright,
      number = plt.limestoneCreamCore,
      operator = plt.graniteGrayCore,
      parameter = plt.fg_mid,
      preproc = plt.slateBlueCore,
      punct = plt.fg_dark,
      regex = plt.mossGreenCore,
      special = plt.copperOreCore,
      special2 = plt.ironOxideCore,
      special3 = plt.graniteGrayBright,
      statement = plt.sandstoneYellowCore,
      string = plt.mossGreenCore,
      symbol = plt.sandstoneYellowBright,
      type = plt.graniteGrayCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.slateBlueCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.slateBlueCore,
    },
    diff = {
      add = plt.mossGreenCore,
      add_inline = plt.mossGreenBright,
      change = plt.sandstoneYellowCore,
      change_inline = plt.sandstoneYellowBright,
      delete = plt.ironOxideCore,
      delete_inline = plt.ironOxideBright,
      text = plt.slateBlueCore,
    },
    vcs = {
      added = plt.mossGreenCore,
      changed = plt.sandstoneYellowCore,
      removed = plt.ironOxideCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.ironOxideCore,
      green = plt.mossGreenCore,
      yellow = plt.sandstoneYellowCore,
      blue = plt.slateBlueCore,
      magenta = plt.graniteGrayCore,
      cyan = plt.ashGrayCore,
      white = plt.limestoneCreamCore,
      black_bright = plt.bg_dark,
      red_bright = plt.ironOxideBright,
      green_bright = plt.mossGreenBright,
      yellow_bright = plt.sandstoneYellowBright,
      blue_bright = plt.slateBlueBright,
      magenta_bright = plt.graniteGrayBright,
      cyan_bright = plt.ashGrayBright,
      white_bright = plt.limestoneCreamBright,
      indexed1 = plt.copperOreCore,
      indexed2 = plt.slateBlueCore,
    },
  }
end

return {
  name = "Punk – Stonepunk",
  author = "PrismPunk.nvim",
  description = "Carved monoliths — sandstone, granite, moss and iron, ancient stone machinery.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.rockGray,
    base04 = palette.rockGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.ironOxideCore,
    base09 = palette.copperOreCore,
    base0A = palette.sandstoneYellowCore,
    base0B = palette.mossGreenCore,
    base0C = palette.slateBlueCore,
    base0D = palette.graniteGrayCore,
    base0E = palette.ashGrayCore,
    base0F = palette.clayBrownCore,
  },
  palette = palette,
  get = M.get,
}
