local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.stonepunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.graniteGrayCore,
      insert = plt.mossGreenCore,
      visual = plt.sandstoneYellowCore,
      replace = plt.ironOxideCore,
      command = plt.slateBlueCore,
    },
    accent = {
      accent1 = plt.graniteGrayCore,
      accent2 = plt.sandstoneYellowCore,
      accent3 = plt.clayBrownCore,
      accent4 = plt.slateBlueCore,
      accent5 = plt.mossGreenCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.limestoneCreamBright,
      rainbow2 = plt.sandstoneYellowBright,
      rainbow3 = plt.graniteGrayBright,
      rainbow4 = plt.clayBrownBright,
      rainbow5 = plt.slateBlueBright,
      rainbow6 = plt.mossGreenBright,
      rainbow7 = plt.copperOreBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.rockGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.graniteGrayCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.rockGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.rockGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.rockGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.copperOreCore,
      boolean = plt.slateBlueCore,
      comment = plt.rockGray,
      constant = plt.limestoneCreamCore,
      deprecated = plt.boulderGray,
      func = plt.mossGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.graniteGrayCore,
      method = plt.mossGreenBright,
      number = plt.limestoneCreamCore,
      operator = plt.sandstoneYellowCore,
      parameter = plt.fg_mid,
      preproc = plt.slateBlueCore,
      punct = plt.fg_dark,
      regex = plt.clayBrownCore,
      special = plt.slateBlueCore,
      statement = plt.graniteGrayCore,
      string = plt.mossGreenCore,
      symbol = plt.copperOreCore,
      type = plt.ashGrayCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.slateBlueCore,
    },
    diff = {
      add = plt.mossGreenCore,
      change = plt.sandstoneYellowCore,
      delete = plt.ironOxideCore,
      text = plt.slateBlueCore,
    },
    vcs = {
      added = plt.mossGreenCore,
      changed = plt.sandstoneYellowCore,
      removed = plt.ironOxideCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.ironOxideCore,
      green = plt.mossGreenCore,
      yellow = plt.sandstoneYellowCore,
      blue = plt.slateBlueCore,
      magenta = plt.clayBrownCore,
      cyan = plt.ashGrayCore,
      white = plt.limestoneCreamCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.ironOxideBright):brighten(0.15):to_hex(),
      green_bright = color(plt.mossGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.sandstoneYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.slateBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.clayBrownBright):brighten(0.18):to_hex(),
      cyan_bright = color(plt.ashGrayBright):brighten(0.15):to_hex(),
      white_bright = color(plt.limestoneCreamBright):brighten(0.1):to_hex(),
    },
  }
end

return {
  name = "Punk – Stonepunk",
  author = "PrismPunk.nvim",
  description = "Primitive stone age — granite gray, limestone cream, moss green, ancient earth.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.rockGray,
    base04 = palette.rockGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.ironOxideCore,
    base09 = palette.copperOreCore,
    base0A = palette.sandstoneYellowCore,
    base0B = palette.mossGreenCore,
    base0C = palette.ashGrayCore,
    base0D = palette.slateBlueCore,
    base0E = palette.clayBrownCore,
    base0F = palette.graniteGrayCore,
  },
  palette = palette,
  get = M.get,
}
