local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.punk-cultures.techpunk")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      normal = plt.techBlueCore,
      insert = plt.dataGreenCore,
      visual = plt.quantumVioletCore,
      replace = plt.laserRedCore,
      command = plt.neonCyanCore,
    },
    accent = {
      accent1 = plt.techBlueCore,
      accent2 = plt.quantumVioletCore,
      accent3 = plt.dataGreenCore,
      accent4 = plt.neonCyanCore,
      accent5 = plt.plasmaOrangeCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.techBlueBright,
      rainbow2 = plt.quantumVioletBright,
      rainbow3 = plt.neonCyanBright,
      rainbow4 = plt.dataGreenBright,
      rainbow5 = plt.plasmaOrangeBright,
      rainbow6 = plt.hologramPinkBright,
      rainbow7 = plt.networkBlueBright,
    },
    ui = {
      bg = plt.bg_darkest,
      bg_cursorline = plt.bg_dark,
      bg_dim = plt.bg_darkest,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_highlight = plt.bg_mid,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_statusline = plt.bg_light,
      bg_visual = plt.bg_mid,
      border = plt.metalGray,
      cursorline = plt.bg_dark,
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_reverse = plt.bg_alt1,
      indent = plt.bg_lighter,
      indent_scope = plt.techBlueCore,
      line_nr = plt.bg_lightest,
      line_nr_active = plt.fg_lightest,
      line_nr_dim = plt.bg_lighter,
      nontext = plt.bg_lightest,
      selection = plt.bg_mid,
      win_separator = plt.metalGray,
      float = {
        bg = plt.bg_darker,
        bg_border = plt.bg_darker,
        fg = plt.fg_light,
        fg_border = plt.metalGray,
      },
      pmenu = {
        bg = plt.bg_light,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_thumb = plt.metalGrayLight,
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
      },
    },
    syn = {
      attribute = plt.signalYellowCore,
      boolean = plt.neonCyanCore,
      comment = plt.metalGray,
      constant = plt.binaryWhiteCore,
      deprecated = plt.metalGrayDark,
      func = plt.dataGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.techBlueCore,
      method = plt.dataGreenBright,
      number = plt.binaryWhiteCore,
      operator = plt.quantumVioletCore,
      parameter = plt.fg_mid,
      preproc = plt.networkBlueCore,
      punct = plt.fg_dark,
      regex = plt.streamPurpleCore,
      special = plt.neonCyanCore,
      statement = plt.techBlueCore,
      string = plt.dataGreenCore,
      symbol = plt.signalYellowCore,
      type = plt.neonCyanCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.neonCyanCore,
    },
    diff = {
      add = plt.circuitGreenCore,
      change = plt.plasmaOrangeCore,
      delete = plt.laserRedCore,
      text = plt.neonCyanCore,
    },
    vcs = {
      added = plt.circuitGreenCore,
      changed = plt.plasmaOrangeCore,
      removed = plt.laserRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.laserRedCore,
      green = plt.dataGreenCore,
      yellow = plt.signalYellowCore,
      blue = plt.techBlueCore,
      magenta = plt.quantumVioletCore,
      cyan = plt.neonCyanCore,
      white = plt.binaryWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.laserRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.dataGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.signalYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.techBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.quantumVioletBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.neonCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.binaryWhiteBright,
    },
  }
end

return {
  name = "Punk – Techpunk",
  author = "PrismPunk.nvim",
  description = "High-tech innovation — tech blue, quantum violet, data green, digital circuits.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.metalGray,
    base04 = palette.metalGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.laserRedCore,
    base09 = palette.plasmaOrangeCore,
    base0A = palette.signalYellowCore,
    base0B = palette.dataGreenCore,
    base0C = palette.neonCyanCore,
    base0D = palette.techBlueCore,
    base0E = palette.quantumVioletCore,
    base0F = palette.streamPurpleCore,
  },
  palette = palette,
  get = M.get,
}
