local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0200",
  bg_darker = "#140400",
  bg_dark = "#1e0600",
  bg_mid = "#280800",
  bg_light = "#320a00",
  bg_lighter = "#3c0c00",
  bg_lightest = "#460e00",
  bg_alt1 = "#501000",
  bg_alt2 = "#5a1200",
  bg_alt3 = "#641400",
  bg_alt4 = "#6e1600",
  fg_lightest = "#ffebeb",
  fg_light = "#ffd0d0",
  fg_mid = "#ffb6b6",
  fg_dark = "#ff9c9c",
  consumingFire = "#ff0000",
  apocalypticBlaze = "#ff1a1a",
  creationsOpposite = "#ff3434",
  finalConflagration = "#ff4e4e",
  surtalogi = "#ff6868",
  surtrsFlame = "#ff8282",
  worldEnding = "#ff9c9c",
  cosmicDestruction = "#ffb6b6",
  allConsumingFire = "#ffd0d0",
  ashAndEmber = "#ffebeb",
  ragnarokInferno = "#a02000",
  destructiveHeat = "#961e00",
  primordialBurning = "#8c1c00",
  endOfAllThings = "#821a00",
  finalFlame = "#781800",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.consumingFire,
      insert = plt.creationsOpposite,
      visual = plt.surtalogi,
      replace = plt.ashAndEmber,
      command = plt.finalConflagration,
    },
    accent = {
      accent1 = plt.consumingFire,
      accent2 = plt.apocalypticBlaze,
      accent3 = plt.creationsOpposite,
      accent4 = plt.finalConflagration,
      accent5 = plt.surtalogi,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.consumingFire,
      rainbow2 = plt.apocalypticBlaze,
      rainbow3 = plt.creationsOpposite,
      rainbow4 = plt.finalConflagration,
      rainbow5 = plt.surtalogi,
      rainbow6 = plt.surtrsFlame,
      rainbow7 = plt.worldEnding,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.finalConflagration,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.consumingFire,
      header2 = plt.ashAndEmber,
      special = plt.creationsOpposite,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.apocalypticBlaze,
      indent = plt.bg_light,
      indent_scope = plt.consumingFire,
      picker = plt.surtalogi,
      yank = plt.finalConflagration,
      mark = plt.ragnarokInferno,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.consumingFire,
        indicator = plt.apocalypticBlaze,
      },
    },
    syn = {
      attribute = plt.creationsOpposite,
      boolean = plt.surtalogi,
      comment = plt.fg_mid,
      constant = plt.finalConflagration,
      deprecated = plt.fg_dark,
      func = plt.ashAndEmber,
      identifier = plt.fg_lightest,
      keyword = plt.consumingFire,
      method = plt.ashAndEmber,
      number = plt.finalConflagration,
      operator = plt.apocalypticBlaze,
      parameter = plt.surtrsFlame,
      preproc = plt.creationsOpposite,
      punct = plt.fg_mid,
      regex = plt.surtalogi,
      special = plt.creationsOpposite,
      special2 = plt.apocalypticBlaze,
      special3 = plt.surtrsFlame,
      statement = plt.consumingFire,
      string = plt.allConsumingFire,
      symbol = plt.apocalypticBlaze,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.consumingFire,
      warning = plt.finalConflagration,
      info = plt.surtalogi,
      ok = plt.allConsumingFire,
      hint = plt.creationsOpposite,
      virtual_text_error = plt.consumingFire,
      virtual_text_warning = plt.finalConflagration,
      virtual_text_info = plt.surtalogi,
      virtual_text_ok = plt.allConsumingFire,
      virtual_text_hint = plt.creationsOpposite,
    },
    diff = {
      add = plt.allConsumingFire,
      add_inline = plt.surtalogi,
      change = plt.finalConflagration,
      change_inline = plt.ragnarokInferno,
      delete = plt.consumingFire,
      delete_inline = plt.apocalypticBlaze,
      text = plt.creationsOpposite,
    },
    vcs = {
      added = plt.allConsumingFire,
      changed = plt.finalConflagration,
      removed = plt.consumingFire,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.consumingFire,
      green = plt.allConsumingFire,
      yellow = plt.finalConflagration,
      blue = plt.surtalogi,
      magenta = plt.creationsOpposite,
      cyan = plt.apocalypticBlaze,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.consumingFire):brighten(0.2):to_hex(),
      green_bright = color(plt.allConsumingFire):brighten(0.15):to_hex(),
      yellow_bright = color(plt.finalConflagration):brighten(0.15):to_hex(),
      blue_bright = color(plt.surtalogi):brighten(0.15):to_hex(),
      magenta_bright = color(plt.creationsOpposite):brighten(0.2):to_hex(),
      cyan_bright = color(plt.apocalypticBlaze):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.surtrsFlame,
      indexed2 = plt.ragnarokInferno,
    },
  }
end

return {
  name = "Muspelheim – Surtalogi",
  author = "PrismPunk",
  description = "Surtr's flame — consuming fire, apocalyptic blaze, creation's opposite, final conflagration. "
    .. "Surtalogi is the flame of Surtr himself, the all-consuming fire that will devour the Nine "
    .. "Realms at Ragnarök. It is not merely heat or light, but the fundamental opposite of creation — "
    .. "a force that unmakes reality itself. Where Ymir's body became the world, Surtalogi will "
    .. "reduce that world back to primordial chaos. This is the fire that burns hotter than stars, "
    .. "the blaze that even gods cannot withstand. When Surtr raises his flaming sword and unleashes "
    .. "Surtalogi upon the cosmos, all that was will become ash, and all that is will cease to be. "
    .. "The palette moves from near-black through deep blood reds to pure crimson and finally to "
    .. "pale ash-pink — the journey from smoldering ember to apocalyptic inferno to the pale aftermath "
    .. "of total annihilation.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.consumingFire,
    base09 = palette.finalConflagration,
    base0A = palette.surtrsFlame,
    base0B = palette.allConsumingFire,
    base0C = palette.apocalypticBlaze,
    base0D = palette.surtalogi,
    base0E = palette.creationsOpposite,
    base0F = palette.ragnarokInferno,
  },
  palette = palette,
  get = M.get,
}
