local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#0F0E14",
  sumiInk1 = "#191622",
  sumiInk2 = "#242233",
  sumiInk3 = "#2F2C44",
  sumiInk4 = "#5A566E",
  sumiInkShadow = "#0B0A10",
  sumiInkEcho = "#1C1B28",
  sumiInkTint = "#28263A",
  fujiWhite = "#E0DCCF",
  oldWhite = "#CFC7B7",
  softGray = "#73716E",
  autumnRed = "#C74C3C",
  autumnGreen = "#6B8750",
  autumnYellow = "#E6B64A",
  waveBlue1 = "#2A4B6F",
  waveAqua1 = "#5F9EA0",
  springViolet1 = "#9B7ECF",
  springViolet2 = "#A88ED1",
  divineGold = "#FFD96B",
  twilightGold = "#C9A55B",
  emberRed = "#E94E3D",
  heroicCyan = "#7FB4CA",
  celestialBlue = "#4A6B9C",
  moonGlow = "#B8A8D8",
  eclipsePurple = "#6B5A8E",
  eclipseGlow = "#D4C4F0",
  eclipseVivid = "#E0D4FF",
  eclipseFlare = "#ECE0FF",
  eclipseAccent1 = "#382E48",
  eclipseAccent2 = "#403654",
  eclipseAccent3 = "#483D60",
  eclipseAccent4 = "#50446C",
  eclipseAccent5 = "#584B78",
  winterYellow = "#4F4530",
  softAmber = "#F0D090",
  dawnCoral = "#FFB380",
  sacredTeal = "#5FA8A8",

  bg_darkest = "#0B0A10",
  fg_lightest = "#E0DCCF",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      command = plt.waveAqua1,
      insert = plt.heroicCyan,
      normal = plt.springViolet1,
      replace = plt.divineGold,
      visual = plt.moonGlow,
    },
    accent = {
      accent1 = plt.springViolet1,
      accent2 = plt.divineGold,
      accent3 = plt.heroicCyan,
      accent4 = plt.moonGlow,
      accent5 = plt.waveAqua1,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.springViolet1,
      rainbow2 = plt.moonGlow,
      rainbow3 = plt.divineGold,
      rainbow4 = plt.heroicCyan,
      rainbow5 = plt.waveAqua1,
      rainbow6 = plt.celestialBlue,
      rainbow7 = plt.springViolet2,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.softGray,
      fg_dark = plt.sumiInk4,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk1 or "none",
      bg_cursorline = plt.sumiInk2,
      bg_cursorline_alt = plt.sumiInk3,
      cursorline = plt.sumiInk2,
      bg_highlight = plt.sumiInk3,
      bg_search = plt.eclipseGlow,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInk1,
      border = plt.eclipsePurple,
      header1 = plt.springViolet1,
      header2 = plt.heroicCyan,
      special = plt.divineGold,
      nontext = plt.sumiInk3,
      whitespace = plt.softGray,
      win_separator = plt.eclipsePurple,
      indent = plt.sumiInk2,
      indent_scope = plt.springViolet1,
      picker = plt.springViolet2,
      yank = plt.divineGold,
      mark = plt.heroicCyan,
      scrollbar = plt.sumiInk4,
      selection = plt.sumiInk3,
      line_nr = plt.sumiInk4,
      line_nr_active = plt.fujiWhite,
      line_nr_dim = plt.sumiInk3,
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk1,
        fg_border = plt.moonGlow,
        bg_border = plt.sumiInk1,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.eclipsePurple,
        bg = plt.sumiInk1,
        bg_sel = plt.sumiInk3,
        bg_border = plt.sumiInk1,
        bg_sbar = plt.sumiInk1,
        bg_thumb = plt.eclipsePurple,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        fg_inactive = plt.softGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.springViolet1,
        indicator = plt.springViolet1,
      },
    },
    syn = {
      attribute = plt.twilightGold,
      boolean = plt.heroicCyan,
      comment = plt.softGray,
      constant = plt.twilightGold,
      deprecated = plt.sumiInk4,
      func = plt.celestialBlue,
      identifier = plt.fujiWhite,
      keyword = plt.springViolet1,
      method = plt.heroicCyan,
      number = plt.divineGold,
      operator = plt.moonGlow,
      parameter = plt.oldWhite,
      preproc = plt.springViolet2,
      punct = plt.softGray,
      regex = plt.waveAqua1,
      special = plt.divineGold,
      special2 = plt.moonGlow,
      special3 = plt.waveAqua1,
      statement = plt.springViolet1,
      string = plt.waveAqua1,
      symbol = plt.heroicCyan,
      type = plt.moonGlow,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.autumnRed,
      warning = plt.divineGold,
      info = plt.celestialBlue,
      ok = plt.heroicCyan,
      hint = plt.waveAqua1,
      virtual_text_error = plt.autumnRed,
      virtual_text_warning = plt.divineGold,
      virtual_text_info = plt.celestialBlue,
      virtual_text_ok = plt.heroicCyan,
      virtual_text_hint = plt.waveAqua1,
    },
    diff = {
      add = plt.heroicCyan,
      add_inline = plt.eclipseGlow,
      change = plt.divineGold,
      change_inline = plt.twilightGold,
      delete = plt.autumnRed,
      delete_inline = plt.emberRed,
      text = plt.moonGlow,
    },
    vcs = {
      added = plt.heroicCyan,
      changed = plt.divineGold,
      removed = plt.autumnRed,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.autumnRed,
      green = plt.autumnGreen,
      yellow = plt.autumnYellow,
      blue = plt.celestialBlue,
      magenta = plt.springViolet1,
      cyan = plt.heroicCyan,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.autumnRed):brighten(0.2):to_hex(),
      green_bright = color(plt.autumnGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.autumnYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.celestialBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.springViolet1):brighten(0.2):to_hex(),
      cyan_bright = color(plt.heroicCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.divineGold,
      indexed2 = plt.springViolet1,
    },
  }
end

return {
  name = "Amaterasu – Eclipse",
  author = "PrismPunk.nvim",
  description = "Dark mode – eclipsed sun with warm divine glow. The goddess descends.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.fujiWhite,
    base08 = palette.autumnRed,
    base09 = palette.divineGold,
    base0A = palette.twilightGold,
    base0B = palette.heroicCyan,
    base0C = palette.waveAqua1,
    base0D = palette.celestialBlue,
    base0E = palette.springViolet1,
    base0F = palette.moonGlow,
  },
  palette = palette,
  get = M.get,
}
