local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1A0005",
  bg_darker = "#24000A",
  bg_dark = "#330012",
  bg_mid = "#4D0022",
  bg_light = "#7A1144",
  bg_lighter = "#AA2266",
  bg_lightest = "#FF5599",

  fg_lightest = "#FFE8F0",
  fg_light = "#FFC8E0",
  fg_mid = "#FFA8D0",
  fg_dark = "#FF88B8",

  bg_alt1 = "#22000C",
  bg_alt2 = "#180006",
  bg_alt3 = "#33001A",
  bg_alt4 = "#2A0014",

  hyperRed = "#FF0033",
  cocainePink = "#FF66AA",
  afterburnMagenta = "#FF0088",
  psychoCyan = "#00FFFF",
  tremorViolet = "#CC00FF",
  speedFreakWhite = "#FFE8F0",
  adrenalineGold = "#FFCC00",
  bloodFlash = "#FF1A55",
  blurNeon = "#00FFCC",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.hyperRed,
      insert = plt.psychoCyan,
      visual = plt.afterburnMagenta,
      replace = plt.bloodFlash,
      command = plt.adrenalineGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.blurNeon,
      bg_visual = plt.tremorViolet,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.adrenalineGold,
      header2 = plt.hyperRed,
      special = plt.psychoCyan,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.cocainePink,
      indent = plt.bg_lighter,
      indent_scope = plt.hyperRed,
      picker = plt.afterburnMagenta,
      yank = plt.adrenalineGold,
      mark = plt.blurNeon,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.adrenalineGold,
        bg_alternate = plt.bg_darkest,
        indicator = plt.hyperRed,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.adrenalineGold,
      accent2 = plt.hyperRed,
      accent3 = plt.psychoCyan,
      accent4 = plt.afterburnMagenta,
      accent5 = plt.tremorViolet,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.adrenalineGold,
      rainbow2 = plt.hyperRed,
      rainbow3 = plt.afterburnMagenta,
      rainbow4 = plt.psychoCyan,
      rainbow5 = plt.tremorViolet,
      rainbow6 = plt.cocainePink,
      rainbow7 = plt.blurNeon,
    },

    syn = {
      attribute = plt.adrenalineGold,
      boolean = plt.psychoCyan,
      comment = plt.fg_dark,
      constant = plt.adrenalineGold,
      deprecated = plt.fg_mid,
      func = plt.hyperRed,
      identifier = plt.fg_lightest,
      keyword = plt.afterburnMagenta,
      method = plt.psychoCyan,
      number = plt.cocainePink,
      operator = plt.psychoCyan,
      parameter = plt.fg_mid,
      preproc = plt.hyperRed,
      punct = plt.fg_mid,
      regex = plt.bloodFlash,
      statement = plt.afterburnMagenta,
      string = plt.adrenalineGold,
      symbol = plt.psychoCyan,
      type = plt.speedFreakWhite,
      variable = plt.fg_lightest,
      special = plt.adrenalineGold,
      special2 = plt.afterburnMagenta,
      special3 = plt.hyperRed,
    },

    vcs = { added = plt.psychoCyan, removed = plt.bloodFlash, changed = plt.adrenalineGold },
    diff = { add = plt.psychoCyan, change = plt.adrenalineGold, delete = plt.bloodFlash, text = plt.tremorViolet },
    diag = {
      ok = plt.psychoCyan,
      error = plt.bloodFlash,
      warning = plt.cocainePink,
      info = plt.hyperRed,
      hint = plt.blurNeon,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.hyperRed,
      green = plt.psychoCyan,
      yellow = plt.adrenalineGold,
      blue = plt.tremorViolet,
      magenta = plt.afterburnMagenta,
      cyan = plt.blurNeon,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.hyperRed):brighten(0.2):to_hex(),
      green_bright = color(plt.psychoCyan):brighten(0.1):to_hex(),
      yellow_bright = color(plt.adrenalineGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.tremorViolet):brighten(0.3):to_hex(),
      magenta_bright = color(plt.afterburnMagenta):brighten(0.2):to_hex(),
      cyan_bright = color(plt.blurNeon):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.adrenalineGold,
      indexed2 = plt.hyperRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@constant"] = plt.adrenalineGold,
      ["@string"] = plt.adrenalineGold,
      ["@string.regex"] = plt.bloodFlash,
      ["@number"] = plt.cocainePink,
      ["@function"] = plt.hyperRed,
      ["@keyword"] = plt.afterburnMagenta,
      ["@operator"] = plt.psychoCyan,
      ["@variable"] = plt.fg_lightest,
      ["@type"] = plt.speedFreakWhite,
      ["@punctuation"] = plt.fg_mid,
      ["@tag"] = plt.afterburnMagenta,
      ["@markup.strong"] = { fg = plt.adrenalineGold, bold = true },
      ["@diff.plus"] = plt.psychoCyan,
      ["@diff.minus"] = plt.bloodFlash,
      ["@conceal"] = plt.tremorViolet,
      ["@spell"] = plt.fg_lightest,
    },

    lsp = {
      ["@lsp.type.class"] = plt.speedFreakWhite,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.adrenalineGold,
    },
  }
end

return {
  name = "Crime Syndicate – Johnny Quick",
  author = "PrismPunk.nvim",
  description = "Unhinged. Coked-up. Murderously fast. The psycho who outruns his own sanity.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.hyperRed,
    base09 = palette.cocainePink,
    base0A = palette.adrenalineGold,
    base0B = palette.psychoCyan,
    base0C = palette.blurNeon,
    base0D = palette.afterburnMagenta,
    base0E = palette.tremorViolet,
    base0F = palette.bloodFlash,
  },

  palette = palette,
  get = M.get,
}
