local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0807",
  bg_darker = "#0F0C0A",
  bg_dark = "#14110E",
  bg_mid = "#1C1814",
  bg_light = "#332F2A",
  bg_lighter = "#4A443D",
  bg_lightest = "#73685C",

  fg_lightest = "#D9C9B8",
  fg_light = "#C2B4A3",
  fg_mid = "#A08C7A",
  fg_dark = "#7A6655",

  bg_alt1 = "#110E0C",
  bg_alt2 = "#0D0B09",
  bg_alt3 = "#171411",
  bg_alt4 = "#120F0D",

  bloodMoon = "#992222",
  spiritWhite = "#D9C9B8",
  corpseBlue = "#557788",
  boneYellow = "#CCAA66",
  ritualRed = "#BB3333",
  barrowGreen = "#447766",
  wraithPurple = "#774477",
  talonGold = "#AA7733",
  deathFrost = "#99AAAA",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.corpseBlue,
      insert = plt.barrowGreen,
      visual = plt.ritualRed,
      replace = plt.bloodMoon,
      command = plt.talonGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.barrowGreen,
      bg_visual = plt.wraithPurple,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.talonGold,
      header2 = plt.bloodMoon,
      special = plt.barrowGreen,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_light,
      indent = plt.bg_lighter,
      indent_scope = plt.corpseBlue,
      picker = plt.ritualRed,
      yank = plt.talonGold,
      mark = plt.spiritWhite,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.talonGold,
        bg_alternate = plt.bg_darkest,
        indicator = plt.bloodMoon,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.talonGold,
      accent2 = plt.corpseBlue,
      accent3 = plt.barrowGreen,
      accent4 = plt.ritualRed,
      accent5 = plt.wraithPurple,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.talonGold,
      rainbow2 = plt.corpseBlue,
      rainbow3 = plt.ritualRed,
      rainbow4 = plt.barrowGreen,
      rainbow5 = plt.wraithPurple,
      rainbow6 = plt.bloodMoon,
      rainbow7 = plt.boneYellow,
    },

    syn = {
      attribute = plt.boneYellow,
      boolean = plt.spiritWhite,
      comment = plt.fg_dark,
      constant = plt.talonGold,
      deprecated = plt.fg_mid,
      func = plt.corpseBlue,
      identifier = plt.fg_lightest,
      keyword = plt.ritualRed,
      method = plt.barrowGreen,
      number = plt.boneYellow,
      operator = plt.deathFrost,
      parameter = plt.fg_mid,
      preproc = plt.corpseBlue,
      punct = plt.fg_mid,
      regex = plt.bloodMoon,
      statement = plt.ritualRed,
      string = plt.talonGold,
      symbol = plt.barrowGreen,
      type = plt.spiritWhite,
      variable = plt.fg_lightest,
      special = plt.boneYellow,
      special2 = plt.bloodMoon,
      special3 = plt.corpseBlue,
    },

    vcs = { added = plt.barrowGreen, removed = plt.ritualRed, changed = plt.talonGold },
    diff = { add = plt.barrowGreen, change = plt.talonGold, delete = plt.bloodMoon, text = plt.wraithPurple },
    diag = {
      ok = plt.barrowGreen,
      error = plt.bloodMoon,
      warning = plt.boneYellow,
      info = plt.corpseBlue,
      hint = plt.deathFrost,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.ritualRed,
      green = plt.barrowGreen,
      yellow = plt.talonGold,
      blue = plt.corpseBlue,
      magenta = plt.wraithPurple,
      cyan = plt.deathFrost,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.ritualRed):brighten(0.2):to_hex(),
      green_bright = color(plt.barrowGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.talonGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.corpseBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.wraithPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.deathFrost):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.talonGold,
      indexed2 = plt.bloodMoon,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.bloodMoon,
      ["@comment.warning"] = plt.boneYellow,
      ["@comment.todo"] = plt.talonGold,
      ["@comment.note"] = plt.barrowGreen,

      ["@constant"] = plt.talonGold,
      ["@constant.builtin"] = plt.talonGold,
      ["@constant.macro"] = plt.boneYellow,

      ["@string"] = plt.talonGold,
      ["@string.documentation"] = plt.talonGold,
      ["@string.regex"] = plt.bloodMoon,
      ["@string.escape"] = plt.ritualRed,
      ["@string.special"] = plt.barrowGreen,
      ["@string.special.symbol"] = plt.barrowGreen,
      ["@string.special.url"] = plt.wraithPurple,
      ["@string.special.path"] = plt.talonGold,

      ["@character"] = plt.talonGold,
      ["@character.special"] = plt.ritualRed,

      ["@number"] = plt.boneYellow,
      ["@number.float"] = plt.boneYellow,

      ["@boolean"] = plt.spiritWhite,

      ["@function"] = plt.corpseBlue,
      ["@function.builtin"] = plt.corpseBlue,
      ["@function.call"] = plt.corpseBlue,
      ["@function.macro"] = plt.wraithPurple,
      ["@function.method"] = plt.barrowGreen,
      ["@function.method.call"] = plt.barrowGreen,

      ["@constructor"] = plt.spiritWhite,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.ritualRed,
      ["@keyword.coroutine"] = plt.wraithPurple,
      ["@keyword.function"] = plt.ritualRed,
      ["@keyword.operator"] = plt.deathFrost,
      ["@keyword.return"] = plt.ritualRed,
      ["@keyword.import"] = plt.corpseBlue,
      ["@keyword.storage"] = plt.ritualRed,
      ["@keyword.repeat"] = plt.ritualRed,
      ["@keyword.conditional"] = plt.ritualRed,
      ["@keyword.exception"] = plt.bloodMoon,
      ["@keyword.directive"] = plt.corpseBlue,
      ["@keyword.directive.define"] = plt.corpseBlue,

      ["@conditional"] = plt.ritualRed,
      ["@conditional.ternary"] = plt.ritualRed,

      ["@repeat"] = plt.ritualRed,

      ["@label"] = plt.wraithPurple,

      ["@operator"] = plt.deathFrost,

      ["@exception"] = plt.bloodMoon,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.wraithPurple,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.spiritWhite,
      ["@type.builtin"] = plt.spiritWhite,
      ["@type.definition"] = plt.spiritWhite,
      ["@type.qualifier"] = plt.ritualRed,

      ["@attribute"] = plt.boneYellow,
      ["@attribute.builtin"] = plt.boneYellow,

      ["@property"] = plt.fg_light,
      ["@field"] = plt.fg_light,

      ["@module"] = plt.talonGold,
      ["@module.builtin"] = plt.talonGold,

      ["@namespace"] = plt.talonGold,
      ["@namespace.builtin"] = plt.talonGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.deathFrost,

      ["@tag"] = plt.ritualRed,
      ["@tag.attribute"] = plt.boneYellow,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.ritualRed,

      ["@markup.strong"] = { fg = plt.talonGold, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.deathFrost, underline = true },
      ["@markup.heading"] = plt.talonGold,
      ["@markup.heading.1"] = plt.talonGold,
      ["@markup.heading.2"] = plt.boneYellow,
      ["@markup.heading.3"] = plt.ritualRed,
      ["@markup.heading.4"] = plt.corpseBlue,
      ["@markup.heading.5"] = plt.barrowGreen,
      ["@markup.heading.6"] = plt.wraithPurple,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.deathFrost,
      ["@markup.link"] = plt.wraithPurple,
      ["@markup.link.label"] = plt.barrowGreen,
      ["@markup.link.url"] = plt.wraithPurple,
      ["@markup.raw"] = plt.talonGold,
      ["@markup.raw.block"] = plt.talonGold,
      ["@markup.list"] = plt.ritualRed,
      ["@markup.list.checked"] = plt.barrowGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.barrowGreen,
      ["@diff.minus"] = plt.bloodMoon,
      ["@diff.delta"] = plt.talonGold,

      ["@none"] = "none",
      ["@conceal"] = plt.wraithPurple,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.spiritWhite,
      ["@constructor.javascript"] = plt.spiritWhite,
      ["@constructor.typescript"] = plt.spiritWhite,
      ["@namespace.rust"] = plt.talonGold,
      ["@type.qualifier.rust"] = plt.ritualRed,
      ["@constant.macro.c"] = plt.boneYellow,
      ["@constant.macro.cpp"] = plt.boneYellow,
      ["@namespace.go"] = plt.talonGold,
      ["@property.css"] = plt.wraithPurple,
      ["@type.css"] = plt.ritualRed,
      ["@label.json"] = plt.talonGold,
      ["@field.yaml"] = plt.wraithPurple,
      ["@property.toml"] = plt.wraithPurple,
      ["@function.builtin.bash"] = plt.corpseBlue,
      ["@string.regexp"] = plt.bloodMoon,
      ["@character.special.regex"] = plt.ritualRed,
    },

    lsp = {
      ["@lsp.type.class"] = plt.spiritWhite,
      ["@lsp.type.interface"] = plt.spiritWhite,
      ["@lsp.type.struct"] = plt.spiritWhite,
      ["@lsp.type.enum"] = plt.spiritWhite,
      ["@lsp.type.enumMember"] = plt.talonGold,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.talonGold,

      ["@lsp.type.macro"] = plt.boneYellow,
      ["@lsp.type.decorator"] = plt.spiritWhite,

      ["@lsp.type.builtinType"] = plt.spiritWhite,
      ["@lsp.type.selfParameter"] = plt.wraithPurple,
      ["@lsp.type.typeParameter"] = plt.spiritWhite,

      ["@lsp.type.array"] = plt.spiritWhite,
      ["@lsp.type.object"] = plt.spiritWhite,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.talonGold,
      ["@lsp.type.enumConstant"] = plt.talonGold,

      ["@lsp.type.event"] = plt.spiritWhite,
      ["@lsp.type.regexp"] = plt.bloodMoon,
      ["@lsp.type.unresolvedReference"] = plt.bloodMoon,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.talonGold,
      ["@lsp.mod.async"] = plt.ritualRed,
      ["@lsp.mod.static"] = plt.wraithPurple,
      ["@lsp.mod.abstract"] = plt.spiritWhite,
      ["@lsp.mod.defaultLibrary"] = plt.spiritWhite,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Crime Syndicate – Owlman (Ancient Terror)",
  author = "PrismPunk.nvim",
  description = "The owl that walks as a man. The thing from the moor that was never human. "
    .. "Cornish nightmares made flesh.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.ritualRed,
    base09 = palette.boneYellow,
    base0A = palette.talonGold,
    base0B = palette.barrowGreen,
    base0C = palette.deathFrost,
    base0D = palette.corpseBlue,
    base0E = palette.wraithPurple,
    base0F = palette.bloodMoon,
  },

  palette = palette,
  get = M.get,
}
