local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A180E",
  bg_darker = "#0E2214",
  bg_dark = "#12301A",
  bg_mid = "#1A4428",
  bg_light = "#2F6650",
  bg_lighter = "#45886E",
  bg_lightest = "#66CC99",

  fg_lightest = "#E8FFF4",
  fg_light = "#C8F0E0",
  fg_mid = "#A8E0CC",
  fg_dark = "#7AB8A2",

  bg_alt1 = "#0F2418",
  bg_alt2 = "#091E10",
  bg_alt3 = "#133824",
  bg_alt4 = "#112C1C",

  volthoomGreen = "#00FF88",
  fearEmerald = "#00CC66",
  terrorCyan = "#00FFD4",
  paranoiaGold = "#CCFF00",
  dreadViolet = "#9933FF",
  corruptionTeal = "#00E699",
  nightmareRed = "#FF1A4D",
  ringGlow = "#66FFAA",
  voidBlack = "#001C0F",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.volthoomGreen,
      insert = plt.terrorCyan,
      visual = plt.nightmareRed,
      replace = plt.dreadViolet,
      command = plt.paranoiaGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.ringGlow,
      bg_visual = plt.dreadViolet,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.paranoiaGold,
      header2 = plt.nightmareRed,
      special = plt.corruptionTeal,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.fearEmerald,
      indent = plt.bg_lighter,
      indent_scope = plt.volthoomGreen,
      picker = plt.nightmareRed,
      yank = plt.ringGlow,
      mark = plt.terrorCyan,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.paranoiaGold,
        bg_alternate = plt.bg_darkest,
        indicator = plt.nightmareRed,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.paranoiaGold,
      accent2 = plt.volthoomGreen,
      accent3 = plt.terrorCyan,
      accent4 = plt.nightmareRed,
      accent5 = plt.dreadViolet,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.paranoiaGold,
      rainbow2 = plt.volthoomGreen,
      rainbow3 = plt.nightmareRed,
      rainbow4 = plt.terrorCyan,
      rainbow5 = plt.dreadViolet,
      rainbow6 = plt.corruptionTeal,
      rainbow7 = plt.ringGlow,
    },

    syn = {
      attribute = plt.paranoiaGold,
      boolean = plt.terrorCyan,
      comment = plt.fg_dark,
      constant = plt.paranoiaGold,
      deprecated = plt.fg_mid,
      func = plt.volthoomGreen,
      identifier = plt.fg_lightest,
      keyword = plt.nightmareRed,
      method = plt.corruptionTeal,
      number = plt.ringGlow,
      operator = plt.corruptionTeal,
      parameter = plt.fg_mid,
      preproc = plt.volthoomGreen,
      punct = plt.fg_mid,
      regex = plt.dreadViolet,
      statement = plt.nightmareRed,
      string = plt.paranoiaGold,
      symbol = plt.terrorCyan,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
      special = plt.ringGlow,
      special2 = plt.nightmareRed,
      special3 = plt.volthoomGreen,
    },

    vcs = { added = plt.terrorCyan, removed = plt.nightmareRed, changed = plt.paranoiaGold },
    diff = { add = plt.terrorCyan, change = plt.paranoiaGold, delete = plt.nightmareRed, text = plt.dreadViolet },
    diag = {
      ok = plt.terrorCyan,
      error = plt.nightmareRed,
      warning = plt.ringGlow,
      info = plt.volthoomGreen,
      hint = plt.corruptionTeal,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.nightmareRed,
      green = plt.volthoomGreen,
      yellow = plt.paranoiaGold,
      blue = plt.dreadViolet,
      magenta = plt.dreadViolet,
      cyan = plt.terrorCyan,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.nightmareRed):brighten(0.2):to_hex(),
      green_bright = color(plt.volthoomGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.paranoiaGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.dreadViolet):brighten(0.3):to_hex(),
      magenta_bright = color(plt.dreadViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.terrorCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.paranoiaGold,
      indexed2 = plt.nightmareRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.nightmareRed,
      ["@comment.warning"] = plt.ringGlow,
      ["@comment.todo"] = plt.paranoiaGold,
      ["@comment.note"] = plt.corruptionTeal,

      ["@constant"] = plt.paranoiaGold,
      ["@constant.builtin"] = plt.paranoiaGold,
      ["@constant.macro"] = plt.ringGlow,

      ["@string"] = plt.paranoiaGold,
      ["@string.regex"] = plt.dreadViolet,
      ["@string.escape"] = plt.nightmareRed,
      ["@string.special"] = plt.terrorCyan,

      ["@number"] = plt.ringGlow,
      ["@boolean"] = plt.terrorCyan,

      ["@function"] = plt.volthoomGreen,
      ["@function.builtin"] = plt.volthoomGreen,
      ["@function.macro"] = plt.dreadViolet,
      ["@function.method"] = plt.corruptionTeal,

      ["@constructor"] = plt.fg_lightest,

      ["@parameter"] = plt.fg_mid,

      ["@keyword"] = plt.nightmareRed,
      ["@keyword.operator"] = plt.corruptionTeal,
      ["@keyword.return"] = plt.nightmareRed,

      ["@variable"] = plt.fg_lightest,
      ["@property"] = plt.fg_light,

      ["@type"] = plt.fg_lightest,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.corruptionTeal,

      ["@tag"] = plt.nightmareRed,
      ["@tag.attribute"] = plt.ringGlow,

      ["@markup.strong"] = { fg = plt.paranoiaGold, bold = true },
      ["@markup.heading.1"] = plt.paranoiaGold,
      ["@markup.heading.2"] = plt.ringGlow,
      ["@markup.heading.3"] = plt.nightmareRed,

      ["@diff.plus"] = plt.terrorCyan,
      ["@diff.minus"] = plt.nightmareRed,
      ["@diff.delta"] = plt.paranoiaGold,

      ["@conceal"] = plt.dreadViolet,
      ["@spell"] = plt.fg_lightest,
    },

    lsp = {
      ["@lsp.type.class"] = plt.fg_lightest,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.paranoiaGold,
    },
  }
end

return {
  name = "Crime Syndicate – Power Ring",
  author = "PrismPunk.nvim",
  description = "Volthoom’s chosen. Fear made manifest. The ring that feeds on terror.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.nightmareRed,
    base09 = palette.ringGlow,
    base0A = palette.paranoiaGold,
    base0B = palette.terrorCyan,
    base0C = palette.corruptionTeal,
    base0D = palette.volthoomGreen,
    base0E = palette.dreadViolet,
    base0F = palette.fearEmerald,
  },

  palette = palette,
  get = M.get,
}
