local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#05090b",
  bg_darker = "#081114",
  bg_dark = "#0c191d",
  bg_mid = "#112327",
  bg_light = "#162f34",
  bg_lighter = "#1d3c42",
  bg_lightest = "#254a50",
  bg_alt1 = "#1a282c",
  bg_alt2 = "#223236",
  bg_alt3 = "#2b3c40",
  bg_alt4 = "#35464a",
  fg_lightest = "#e8f3f5",
  fg_light = "#c0d7db",
  fg_mid = "#79a9ad",
  fg_dark = "#568a90",
  corpseGlow = "#6FE1FF",
  barrowFrost = "#7CFFC8",
  graveBreath = "#CAFFF1",
  hoardGold = "#E0C870",
  woundRust = "#D07858",
  rotViolet = "#B088C8",
  boneAsh = "#B8C8C0",
  ironGrip = "#5AA8A0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.corpseGlow,
      insert = plt.barrowFrost,
      visual = plt.hoardGold,
      replace = plt.woundRust,
      command = plt.graveBreath,
    },
    accent = {
      accent1 = plt.corpseGlow,
      accent2 = plt.barrowFrost,
      accent3 = plt.hoardGold,
      accent4 = plt.fg_light,
      accent5 = plt.woundRust,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.corpseGlow,
      rainbow2 = plt.hoardGold,
      rainbow3 = plt.barrowFrost,
      rainbow4 = plt.rotViolet,
      rainbow5 = plt.graveBreath,
      rainbow6 = plt.woundRust,
      rainbow7 = plt.ironGrip,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.hoardGold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.corpseGlow,
      header2 = plt.barrowFrost,
      special = plt.rotViolet,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.ironGrip,
      indent = plt.bg_light,
      indent_scope = plt.corpseGlow,
      picker = plt.barrowFrost,
      yank = plt.hoardGold,
      mark = plt.woundRust,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.corpseGlow,
        indicator = plt.barrowFrost,
      },
    },
    syn = {
      attribute = plt.rotViolet,
      boolean = plt.hoardGold,
      comment = plt.fg_mid,
      constant = plt.hoardGold,
      deprecated = plt.fg_dark,
      func = plt.corpseGlow,
      identifier = plt.fg_lightest,
      keyword = plt.barrowFrost,
      method = plt.corpseGlow,
      number = plt.hoardGold,
      operator = plt.barrowFrost,
      parameter = plt.graveBreath,
      preproc = plt.rotViolet,
      punct = plt.fg_mid,
      regex = plt.ironGrip,
      special = plt.rotViolet,
      special2 = plt.woundRust,
      special3 = plt.boneAsh,
      statement = plt.barrowFrost,
      string = plt.ironGrip,
      symbol = plt.hoardGold,
      type = plt.rotViolet,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.woundRust,
      warning = plt.hoardGold,
      info = plt.boneAsh,
      ok = plt.barrowFrost,
      hint = plt.rotViolet,
      virtual_text_error = plt.woundRust,
      virtual_text_warning = plt.hoardGold,
      virtual_text_info = plt.boneAsh,
      virtual_text_ok = plt.barrowFrost,
      virtual_text_hint = plt.rotViolet,
    },
    diff = {
      add = plt.barrowFrost,
      add_inline = plt.ironGrip,
      change = plt.hoardGold,
      change_inline = plt.woundRust,
      delete = plt.woundRust,
      delete_inline = plt.corpseGlow,
      text = plt.boneAsh,
    },
    vcs = {
      added = plt.barrowFrost,
      changed = plt.hoardGold,
      removed = plt.woundRust,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.woundRust,
      green = plt.barrowFrost,
      yellow = plt.hoardGold,
      blue = plt.corpseGlow,
      magenta = plt.rotViolet,
      cyan = plt.ironGrip,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.woundRust):brighten(0.2):to_hex(),
      green_bright = color(plt.barrowFrost):brighten(0.15):to_hex(),
      yellow_bright = color(plt.hoardGold):brighten(0.15):to_hex(),
      blue_bright = color(plt.corpseGlow):brighten(0.15):to_hex(),
      magenta_bright = color(plt.rotViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.ironGrip):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.graveBreath,
      indexed2 = plt.boneAsh,
    },
  }
end

return {
  name = "Midgard – Draugr",
  author = "PrismPunk",
  description = "The restless dead who guard their barrow-hoards with superhuman grip — "
    .. "deep teal-black backgrounds evoke waterlogged burial chambers sealed beneath "
    .. "earth. Corpse-glow cyan burns in undead eyes, barrow-frost mint radiates "
    .. "spectral cold, and cursed hoard-gold glints among the bones. Wound-rust marks "
    .. "the draugr's ancient blade, rot-violet stains decaying flesh, and iron-grip "
    .. "teal speaks of strength that will not rest until the mound is broken open.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.woundRust,
    base09 = palette.hoardGold,
    base0A = palette.barrowFrost,
    base0B = palette.ironGrip,
    base0C = palette.rotViolet,
    base0D = palette.corpseGlow,
    base0E = palette.barrowFrost,
    base0F = palette.woundRust,
  },
  palette = palette,
  get = M.get,
}
