local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#041012",
  bg_darker = "#07181b",
  bg_dark = "#0b2326",
  bg_mid = "#103033",
  bg_light = "#174043",
  bg_lighter = "#1f5155",
  bg_lightest = "#286468",
  bg_alt1 = "#091518",
  bg_alt2 = "#1a2e30",
  bg_alt3 = "#22393c",
  bg_alt4 = "#2b4447",
  fg_lightest = "#e8fbfb",
  fg_light = "#b7ecec",
  fg_mid = "#7fd2d3",
  fg_dark = "#59b2b5",
  venomSpray = "#4FFFD2",
  scaleGlint = "#5EFF9C",
  coilSurge = "#3F9396",
  depthPressure = "#32797D",
  tailBite = "#D4605A",
  thunderNemesis = "#E8C850",
  abyssalGlow = "#BAFFDF",
  drownedSteel = "#94C8C1",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.venomSpray,
      insert = plt.scaleGlint,
      visual = plt.thunderNemesis,
      replace = plt.tailBite,
      command = plt.abyssalGlow,
    },
    accent = {
      accent1 = plt.venomSpray,
      accent2 = plt.thunderNemesis,
      accent3 = plt.scaleGlint,
      accent4 = plt.fg_light,
      accent5 = plt.tailBite,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.tailBite,
      rainbow2 = plt.thunderNemesis,
      rainbow3 = plt.scaleGlint,
      rainbow4 = plt.venomSpray,
      rainbow5 = plt.drownedSteel,
      rainbow6 = plt.coilSurge,
      rainbow7 = plt.abyssalGlow,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.thunderNemesis,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.venomSpray,
      header2 = plt.thunderNemesis,
      special = plt.abyssalGlow,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.coilSurge,
      indent = plt.bg_light,
      indent_scope = plt.venomSpray,
      picker = plt.scaleGlint,
      yank = plt.thunderNemesis,
      mark = plt.tailBite,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.venomSpray,
        indicator = plt.thunderNemesis,
      },
    },
    syn = {
      attribute = plt.abyssalGlow,
      boolean = plt.thunderNemesis,
      comment = plt.fg_mid,
      constant = plt.thunderNemesis,
      deprecated = plt.fg_dark,
      func = plt.venomSpray,
      identifier = plt.fg_lightest,
      keyword = plt.tailBite,
      method = plt.venomSpray,
      number = plt.thunderNemesis,
      operator = plt.tailBite,
      parameter = plt.drownedSteel,
      preproc = plt.coilSurge,
      punct = plt.fg_mid,
      regex = plt.scaleGlint,
      special = plt.abyssalGlow,
      special2 = plt.coilSurge,
      special3 = plt.drownedSteel,
      statement = plt.tailBite,
      string = plt.scaleGlint,
      symbol = plt.thunderNemesis,
      type = plt.abyssalGlow,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.tailBite,
      warning = plt.thunderNemesis,
      info = plt.coilSurge,
      ok = plt.scaleGlint,
      hint = plt.drownedSteel,
      virtual_text_error = plt.tailBite,
      virtual_text_warning = plt.thunderNemesis,
      virtual_text_info = plt.coilSurge,
      virtual_text_ok = plt.scaleGlint,
      virtual_text_hint = plt.drownedSteel,
    },
    diff = {
      add = plt.scaleGlint,
      add_inline = plt.venomSpray,
      change = plt.thunderNemesis,
      change_inline = plt.abyssalGlow,
      delete = plt.tailBite,
      delete_inline = plt.drownedSteel,
      text = plt.coilSurge,
    },
    vcs = {
      added = plt.scaleGlint,
      changed = plt.thunderNemesis,
      removed = plt.tailBite,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.tailBite,
      green = plt.scaleGlint,
      yellow = plt.thunderNemesis,
      blue = plt.coilSurge,
      magenta = plt.drownedSteel,
      cyan = plt.venomSpray,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.tailBite):brighten(0.2):to_hex(),
      green_bright = color(plt.scaleGlint):brighten(0.1):to_hex(),
      yellow_bright = color(plt.thunderNemesis):brighten(0.15):to_hex(),
      blue_bright = color(plt.coilSurge):brighten(0.3):to_hex(),
      magenta_bright = color(plt.drownedSteel):brighten(0.2):to_hex(),
      cyan_bright = color(plt.venomSpray):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.abyssalGlow,
      indexed2 = plt.depthPressure,
    },
  }
end

return {
  name = "Midgard – Jörmungandr",
  author = "PrismPunk",
  description = "The World Serpent coiled around Midgard's ocean floor — Jörmungandr, "
    .. "Thor's eternal nemesis, the tail-biter whose venom will blacken the sky at "
    .. "Ragnarök. Abyssal teal-black depths give way to bioluminescent venom-spray "
    .. "greens, scale-glint cyans, and the thunder-nemesis gold of lightning reflected "
    .. "in serpentine eyes, while tail-bite crimson marks where ouroboros closes.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.tailBite,
    base09 = palette.thunderNemesis,
    base0A = palette.abyssalGlow,
    base0B = palette.scaleGlint,
    base0C = palette.venomSpray,
    base0D = palette.venomSpray,
    base0E = palette.tailBite,
    base0F = palette.coilSurge,
  },
  palette = palette,
  get = M.get,
}
