local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#08070a",
  bg_darker = "#110e14",
  bg_dark = "#19161e",
  bg_mid = "#231f29",
  bg_light = "#2f2935",
  bg_lighter = "#3c3443",
  bg_lightest = "#4a4052",
  bg_alt1 = "#27212a",
  bg_alt2 = "#312a34",
  bg_alt3 = "#3a333e",
  bg_alt4 = "#453d49",
  fg_lightest = "#f3e9ff",
  fg_light = "#d7c2e6",
  fg_mid = "#a495a8",
  fg_dark = "#84788d",
  urdWell = "#A47BFF",
  verdandiLoom = "#7BC6FF",
  skuldVeil = "#D8B8FF",
  threadGold = "#E0C06A",
  shearsBronze = "#D09070",
  rootDew = "#7EC8A8",
  wyrdKnot = "#D0687A",
  ashBark = "#B8A898",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.urdWell,
      insert = plt.rootDew,
      visual = plt.skuldVeil,
      replace = plt.wyrdKnot,
      command = plt.verdandiLoom,
    },
    accent = {
      accent1 = plt.urdWell,
      accent2 = plt.verdandiLoom,
      accent3 = plt.threadGold,
      accent4 = plt.fg_light,
      accent5 = plt.wyrdKnot,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.urdWell,
      rainbow2 = plt.threadGold,
      rainbow3 = plt.verdandiLoom,
      rainbow4 = plt.rootDew,
      rainbow5 = plt.skuldVeil,
      rainbow6 = plt.wyrdKnot,
      rainbow7 = plt.shearsBronze,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.threadGold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.urdWell,
      header2 = plt.verdandiLoom,
      special = plt.skuldVeil,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.ashBark,
      indent = plt.bg_light,
      indent_scope = plt.urdWell,
      picker = plt.verdandiLoom,
      yank = plt.threadGold,
      mark = plt.wyrdKnot,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.urdWell,
        indicator = plt.verdandiLoom,
      },
    },
    syn = {
      attribute = plt.skuldVeil,
      boolean = plt.threadGold,
      comment = plt.fg_mid,
      constant = plt.threadGold,
      deprecated = plt.fg_dark,
      func = plt.urdWell,
      identifier = plt.fg_lightest,
      keyword = plt.verdandiLoom,
      method = plt.urdWell,
      number = plt.threadGold,
      operator = plt.verdandiLoom,
      parameter = plt.skuldVeil,
      preproc = plt.skuldVeil,
      punct = plt.fg_mid,
      regex = plt.rootDew,
      special = plt.skuldVeil,
      special2 = plt.shearsBronze,
      special3 = plt.ashBark,
      statement = plt.verdandiLoom,
      string = plt.rootDew,
      symbol = plt.threadGold,
      type = plt.skuldVeil,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.wyrdKnot,
      warning = plt.threadGold,
      info = plt.shearsBronze,
      ok = plt.rootDew,
      hint = plt.skuldVeil,
      virtual_text_error = plt.wyrdKnot,
      virtual_text_warning = plt.threadGold,
      virtual_text_info = plt.shearsBronze,
      virtual_text_ok = plt.rootDew,
      virtual_text_hint = plt.skuldVeil,
    },
    diff = {
      add = plt.rootDew,
      add_inline = plt.skuldVeil,
      change = plt.threadGold,
      change_inline = plt.shearsBronze,
      delete = plt.wyrdKnot,
      delete_inline = plt.verdandiLoom,
      text = plt.ashBark,
    },
    vcs = {
      added = plt.rootDew,
      changed = plt.threadGold,
      removed = plt.wyrdKnot,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.wyrdKnot,
      green = plt.rootDew,
      yellow = plt.threadGold,
      blue = plt.verdandiLoom,
      magenta = plt.urdWell,
      cyan = plt.skuldVeil,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.wyrdKnot):brighten(0.2):to_hex(),
      green_bright = color(plt.rootDew):brighten(0.15):to_hex(),
      yellow_bright = color(plt.threadGold):brighten(0.15):to_hex(),
      blue_bright = color(plt.verdandiLoom):brighten(0.15):to_hex(),
      magenta_bright = color(plt.urdWell):brighten(0.2):to_hex(),
      cyan_bright = color(plt.skuldVeil):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.shearsBronze,
      indexed2 = plt.ashBark,
    },
  }
end

return {
  name = "Midgard – Nornir",
  author = "PrismPunk",
  description = "Urðr, Verðandi, Skuld — the three who sit beneath Yggdrasill's root "
    .. "and carve destiny into living wood. Deep violet backgrounds recall the lightless "
    .. "well of memory; Urðr's violet, Verðandi's sky-blue, and Skuld's pale lavender "
    .. "mark past, present, and future. Golden fate-threads and crimson wyrd-knots weave "
    .. "through the code, while root-dew green and ash-bark grey ground the cosmic loom "
    .. "in the World Tree's enduring bark.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.wyrdKnot,
    base09 = palette.threadGold,
    base0A = palette.verdandiLoom,
    base0B = palette.rootDew,
    base0C = palette.skuldVeil,
    base0D = palette.urdWell,
    base0E = palette.verdandiLoom,
    base0F = palette.shearsBronze,
  },
  palette = palette,
  get = M.get,
}
