local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0c0804",
  bg_darker = "#141006",
  bg_dark = "#1d1709",
  bg_mid = "#28210d",
  bg_light = "#352b12",
  bg_lighter = "#453819",
  bg_lightest = "#574720",
  bg_alt1 = "#2e2619",
  bg_alt2 = "#393022",
  bg_alt3 = "#43392a",
  bg_alt4 = "#4e4333",
  fg_lightest = "#fff7df",
  fg_light = "#ebcf87",
  fg_mid = "#c0a266",
  fg_dark = "#9e8146",
  gramSteel = "#D4E4F0",
  dragonBlood = "#C74B3F",
  cursedGold = "#FFD86A",
  hoardFlame = "#FFB347",
  reginForge = "#D3A23F",
  birdSong = "#A8D48A",
  fafnirVenom = "#8BAA6E",
  brynhildPyre = "#E87D5A",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.cursedGold,
      insert = plt.birdSong,
      visual = plt.hoardFlame,
      replace = plt.dragonBlood,
      command = plt.gramSteel,
    },
    accent = {
      accent1 = plt.cursedGold,
      accent2 = plt.hoardFlame,
      accent3 = plt.birdSong,
      accent4 = plt.fg_light,
      accent5 = plt.dragonBlood,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.dragonBlood,
      rainbow2 = plt.hoardFlame,
      rainbow3 = plt.cursedGold,
      rainbow4 = plt.birdSong,
      rainbow5 = plt.gramSteel,
      rainbow6 = plt.reginForge,
      rainbow7 = plt.brynhildPyre,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.cursedGold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.cursedGold,
      header2 = plt.hoardFlame,
      special = plt.gramSteel,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.reginForge,
      indent = plt.bg_light,
      indent_scope = plt.cursedGold,
      picker = plt.birdSong,
      yank = plt.hoardFlame,
      mark = plt.dragonBlood,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.cursedGold,
        indicator = plt.hoardFlame,
      },
    },
    syn = {
      attribute = plt.gramSteel,
      boolean = plt.hoardFlame,
      comment = plt.fg_mid,
      constant = plt.hoardFlame,
      deprecated = plt.fg_dark,
      func = plt.cursedGold,
      identifier = plt.fg_lightest,
      keyword = plt.dragonBlood,
      method = plt.cursedGold,
      number = plt.hoardFlame,
      operator = plt.brynhildPyre,
      parameter = plt.reginForge,
      preproc = plt.fafnirVenom,
      punct = plt.fg_mid,
      regex = plt.birdSong,
      special = plt.gramSteel,
      special2 = plt.fafnirVenom,
      special3 = plt.reginForge,
      statement = plt.dragonBlood,
      string = plt.birdSong,
      symbol = plt.hoardFlame,
      type = plt.gramSteel,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dragonBlood,
      warning = plt.hoardFlame,
      info = plt.reginForge,
      ok = plt.birdSong,
      hint = plt.gramSteel,
      virtual_text_error = plt.dragonBlood,
      virtual_text_warning = plt.hoardFlame,
      virtual_text_info = plt.reginForge,
      virtual_text_ok = plt.birdSong,
      virtual_text_hint = plt.gramSteel,
    },
    diff = {
      add = plt.birdSong,
      add_inline = plt.fafnirVenom,
      change = plt.cursedGold,
      change_inline = plt.hoardFlame,
      delete = plt.dragonBlood,
      delete_inline = plt.brynhildPyre,
      text = plt.reginForge,
    },
    vcs = {
      added = plt.birdSong,
      changed = plt.cursedGold,
      removed = plt.dragonBlood,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.dragonBlood,
      green = plt.birdSong,
      yellow = plt.cursedGold,
      blue = plt.gramSteel,
      magenta = plt.brynhildPyre,
      cyan = plt.fafnirVenom,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.dragonBlood):brighten(0.2):to_hex(),
      green_bright = color(plt.birdSong):brighten(0.15):to_hex(),
      yellow_bright = color(plt.cursedGold):brighten(0.15):to_hex(),
      blue_bright = color(plt.gramSteel):brighten(0.1):to_hex(),
      magenta_bright = color(plt.brynhildPyre):brighten(0.2):to_hex(),
      cyan_bright = color(plt.fafnirVenom):brighten(0.2):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.reginForge,
      indexed2 = plt.hoardFlame,
    },
  }
end

return {
  name = "Midgard – Sigurðr",
  author = "PrismPunk",
  description = "The dragon-slayer emerges from Fáfnir's smoke-blackened cavern — Sigurðr, "
    .. "Regin's pupil and wielder of Gramr, bathed in wyrm-blood that opened his ears "
    .. "to birdsong. Deep charred-amber backgrounds recall the Gnitaheiðr treasure-cave, "
    .. "while cursed-gold and hoard-flame yellows gleam against dragon-blood crimson and "
    .. "the cool steel-blue of the legendary sword, tempered by the green of the "
    .. "nuthatches whose warnings saved the hero from treachery.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dragonBlood,
    base09 = palette.hoardFlame,
    base0A = palette.cursedGold,
    base0B = palette.birdSong,
    base0C = palette.gramSteel,
    base0D = palette.cursedGold,
    base0E = palette.dragonBlood,
    base0F = palette.reginForge,
  },
  palette = palette,
  get = M.get,
}
