local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0706",
  bg_darker = "#130e0c",
  bg_dark = "#1c1512",
  bg_mid = "#261f1a",
  bg_light = "#322a23",
  bg_lighter = "#40352d",
  bg_lightest = "#504238",
  bg_alt1 = "#2b2320",
  bg_alt2 = "#352c28",
  bg_alt3 = "#3f3531",
  bg_alt4 = "#493f3a",
  fg_lightest = "#f5ece7",
  fg_light = "#e0c7bb",
  fg_mid = "#a8938a",
  fg_dark = "#8c766c",
  oathBreaker = "#E76F51",
  thriceWound = "#FF8A6B",
  battleDust = "#FFB199",
  spearGift = "#B8D0D8",
  sagaInk = "#A0B8A8",
  thorrCurse = "#C49AB8",
  pyreEmber = "#D4A050",
  shameAsh = "#9CAAB0",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.thriceWound,
      insert = plt.sagaInk,
      visual = plt.pyreEmber,
      replace = plt.oathBreaker,
      command = plt.spearGift,
    },
    accent = {
      accent1 = plt.thriceWound,
      accent2 = plt.pyreEmber,
      accent3 = plt.sagaInk,
      accent4 = plt.fg_light,
      accent5 = plt.oathBreaker,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.oathBreaker,
      rainbow2 = plt.pyreEmber,
      rainbow3 = plt.thriceWound,
      rainbow4 = plt.sagaInk,
      rainbow5 = plt.spearGift,
      rainbow6 = plt.thorrCurse,
      rainbow7 = plt.battleDust,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.pyreEmber,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.thriceWound,
      header2 = plt.pyreEmber,
      special = plt.spearGift,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.shameAsh,
      indent = plt.bg_light,
      indent_scope = plt.thriceWound,
      picker = plt.sagaInk,
      yank = plt.pyreEmber,
      mark = plt.oathBreaker,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.thriceWound,
        indicator = plt.pyreEmber,
      },
    },
    syn = {
      attribute = plt.spearGift,
      boolean = plt.pyreEmber,
      comment = plt.fg_mid,
      constant = plt.pyreEmber,
      deprecated = plt.fg_dark,
      func = plt.thriceWound,
      identifier = plt.fg_lightest,
      keyword = plt.oathBreaker,
      method = plt.thriceWound,
      number = plt.pyreEmber,
      operator = plt.oathBreaker,
      parameter = plt.battleDust,
      preproc = plt.thorrCurse,
      punct = plt.fg_mid,
      regex = plt.sagaInk,
      special = plt.spearGift,
      special2 = plt.shameAsh,
      special3 = plt.battleDust,
      statement = plt.oathBreaker,
      string = plt.sagaInk,
      symbol = plt.pyreEmber,
      type = plt.spearGift,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.oathBreaker,
      warning = plt.pyreEmber,
      info = plt.shameAsh,
      ok = plt.sagaInk,
      hint = plt.spearGift,
      virtual_text_error = plt.oathBreaker,
      virtual_text_warning = plt.pyreEmber,
      virtual_text_info = plt.shameAsh,
      virtual_text_ok = plt.sagaInk,
      virtual_text_hint = plt.spearGift,
    },
    diff = {
      add = plt.sagaInk,
      add_inline = plt.spearGift,
      change = plt.pyreEmber,
      change_inline = plt.battleDust,
      delete = plt.oathBreaker,
      delete_inline = plt.thriceWound,
      text = plt.shameAsh,
    },
    vcs = {
      added = plt.sagaInk,
      changed = plt.pyreEmber,
      removed = plt.oathBreaker,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.oathBreaker,
      green = plt.sagaInk,
      yellow = plt.pyreEmber,
      blue = plt.spearGift,
      magenta = plt.thorrCurse,
      cyan = plt.shameAsh,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.oathBreaker):brighten(0.2):to_hex(),
      green_bright = color(plt.sagaInk):brighten(0.15):to_hex(),
      yellow_bright = color(plt.pyreEmber):brighten(0.15):to_hex(),
      blue_bright = color(plt.spearGift):brighten(0.1):to_hex(),
      magenta_bright = color(plt.thorrCurse):brighten(0.2):to_hex(),
      cyan_bright = color(plt.shameAsh):brighten(0.2):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.battleDust,
      indexed2 = plt.thriceWound,
    },
  }
end

return {
  name = "Midgard – Starkaðr",
  author = "PrismPunk",
  description = "The cursed champion who lived three lifetimes — Starkaðr, blessed by Óðinn "
    .. "with poetic skill and warrior prowess, cursed by Þórr to commit a shameful deed "
    .. "in each life. Deep blood-earth browns and smoke-stained backgrounds frame the "
    .. "tragedy: oath-breaker crimson and thrice-wound coral burn against saga-ink green "
    .. "and spear-gift steel-blue, while pyre-ember gold marks the final release and "
    .. "shame-ash grey clings to every triumph like dishonour to glory.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.oathBreaker,
    base09 = palette.pyreEmber,
    base0A = palette.thriceWound,
    base0B = palette.sagaInk,
    base0C = palette.spearGift,
    base0D = palette.thriceWound,
    base0E = palette.oathBreaker,
    base0F = palette.thorrCurse,
  },
  palette = palette,
  get = M.get,
}
