local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.apokolips.kalibak")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.kalibak_toxin,
      insert = plt.meltdown_yellow,
      visual = plt.beta_overcharge,
      replace = plt.toxic_sun,
      command = plt.plasma_leak,
    },
    accent = {
      accent1 = plt.meltdown_yellow,
      accent2 = plt.kalibak_toxin,
      accent3 = plt.beta_overcharge,
      accent4 = plt.toxic_sun,
      accent5 = plt.radiation_glow,
      invert = plt.firepit_toxic,
    },
    rainbow = {
      rainbow1 = plt.meltdown_yellow,
      rainbow2 = plt.kalibak_toxin,
      rainbow3 = plt.toxic_sun,
      rainbow4 = plt.beta_overcharge,
      rainbow5 = plt.venom_rage,
      rainbow6 = plt.plasma_leak,
      rainbow7 = plt.bile_yellow,
    },
    ui = {
      fg = plt.savage_jade,
      fg_dim = plt.parademon_skin,
      fg_dimmer = plt.toxic_scale,
      fg_dark = plt.beast_flesh,
      fg_reverse = plt.waste_void,
      bg = plt.waste_void,
      bg_dim = plt.waste_void,
      bg_m1 = plt.waste_void,
      bg_m2 = plt.sludge_depth,
      bg_m3 = plt.firepit_toxic,
      bg_m4 = plt.irradiated_core,
      bg_p1 = plt.sludge_depth,
      bg_p2 = plt.firepit_toxic,
      bg_gutter = (opts.gutter ~= false) and plt.firepit_toxic or "none",
      bg_cursorline = plt.firepit_toxic,
      bg_cursorline_alt = plt.sludge_depth,
      cursorline = plt.firepit_toxic,
      bg_highlight = plt.irradiated_core,
      bg_search = plt.meltdown_yellow,
      bg_visual = plt.radiation_glow,
      bg_statusline = plt.firepit_toxic,
      border = plt.kalibak_toxin,
      header1 = plt.meltdown_yellow,
      header2 = plt.kalibak_toxin,
      special = plt.plasma_leak,
      nontext = plt.sludge_depth,
      whitespace = plt.irradiated_core,
      win_separator = plt.kalibak_toxin,
      indent = plt.sludge_depth,
      indent_scope = plt.savage_jade,
      picker = plt.toxic_sun,
      yank = plt.meltdown_yellow,
      mark = plt.bile_yellow,
      scrollbar = plt.firepit_toxic,
      selection = plt.irradiated_core,
      line_nr = plt.parademon_skin,
      line_nr_dim = plt.toxic_scale,
      line_nr_active = plt.savage_jade,
      pmenu = {
        fg = plt.savage_jade,
        fg_sel = plt.savage_jade,
        fg_border = plt.firepit_toxic,
        bg = plt.firepit_toxic,
        bg_sel = plt.sludge_depth,
        bg_border = plt.firepit_toxic,
        bg_sbar = plt.firepit_toxic,
        bg_thumb = plt.meltdown_yellow,
      },
      float = {
        fg = plt.savage_jade,
        bg = plt.sludge_depth,
        fg_border = plt.firepit_toxic,
        bg_border = plt.sludge_depth,
      },
      tabline = {
        bg = plt.waste_void,
        bg_inactive = plt.waste_void,
        bg_selected = plt.firepit_toxic,
        bg_alternate = plt.waste_void,
        fg_inactive = plt.toxic_scale,
        fg_selected = plt.meltdown_yellow,
        fg_alternate = plt.plasma_leak,
        indicator = plt.beta_overcharge,
      },
    },
    syn = {
      attribute = plt.savage_jade,
      boolean = plt.meltdown_yellow,
      comment = plt.toxic_scale,
      constant = plt.bile_yellow,
      deprecated = plt.firepit_toxic,
      func = plt.beta_overcharge,
      identifier = plt.savage_jade,
      keyword = plt.kalibak_toxin,
      method = plt.toxic_sun,
      number = plt.radiation_glow,
      operator = plt.meltdown_yellow,
      parameter = plt.parademon_skin,
      preproc = plt.meltdown_yellow,
      punct = plt.toxic_scale,
      regex = plt.plasma_leak,
      statement = plt.kalibak_toxin,
      string = plt.bile_yellow,
      symbol = plt.savage_jade,
      type = plt.radiation_glow,
      variable = plt.savage_jade,
      special = plt.beta_overcharge,
      special2 = plt.meltdown_yellow,
      special3 = plt.plasma_leak,
    },
    diag = {
      error = plt.meltdown_yellow,
      warning = plt.kalibak_toxin,
      info = plt.beta_overcharge,
      hint = plt.bile_yellow,
      ok = plt.plasma_leak,
      virtual_text_error = plt.meltdown_yellow,
      virtual_text_warning = plt.kalibak_toxin,
      virtual_text_info = plt.beta_overcharge,
      virtual_text_hint = plt.bile_yellow,
      virtual_text_ok = plt.plasma_leak,
    },
    diff = {
      add = plt.bile_yellow,
      add_inline = plt.bile_green,
      change = plt.toxic_sun,
      change_inline = plt.venom_rage,
      delete = plt.meltdown_yellow,
      delete_inline = plt.term_red,
      text = plt.beta_overcharge,
    },
    vcs = {
      added = plt.bile_yellow,
      changed = plt.radiation_glow,
      removed = plt.meltdown_yellow,
    },
    term = {
      black = plt.waste_void,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.meltdown_yellow,
      blue = plt.term_blue,
      magenta = plt.kalibak_toxin,
      cyan = plt.plasma_leak,
      white = plt.savage_jade,
      black_bright = color(plt.waste_void):brighten(0.7):to_hex(),
      red_bright = color(plt.term_red):brighten(0.3):to_hex(),
      green_bright = color(plt.term_green):brighten(0.25):to_hex(),
      yellow_bright = color(plt.meltdown_yellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.term_blue):brighten(0.25):to_hex(),
      magenta_bright = color(plt.kalibak_toxin):brighten(0.2):to_hex(),
      cyan_bright = color(plt.plasma_leak):brighten(0.2):to_hex(),
      white_bright = plt.bile_green,
      indexed1 = plt.meltdown_yellow,
      indexed2 = plt.bile_yellow,
    },
  }
end

return {
  name = "Apokolips – Kalibak (Toxic-Yellow Overcharge)",
  author = "PrismPunk.nvim",
  description = "The beast went full nuclear meltdown. Toxic green and searing yellow radiation unleash unstoppable savage fury.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_lighter,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.meltdown_yellow,
    base09 = palette.kalibak_toxin,
    base0A = palette.toxic_sun,
    base0B = palette.radiation_glow,
    base0C = palette.plasma_leak,
    base0D = palette.beta_overcharge,
    base0E = palette.venom_rage,
    base0F = palette.bile_yellow,
  },
  palette = palette,
  get = M.get,
}
