local palette = require("prismpunk.palettes.dc.apokolips.yugakhan")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.yugaTeal,
      insert = plt.wallGlow,
      visual = plt.antiLifeTeal,
      replace = plt.cosmicCyan,
      command = plt.deadSilver,
    },
    accent = {
      accent1 = plt.yugaTeal,
      accent2 = plt.wallGlow,
      accent3 = plt.antiLifeTeal,
      accent4 = plt.cosmicCyan,
      accent5 = plt.finalBreath,
      invert = plt.wallDepth,
    },
    rainbow = {
      rainbow1 = plt.yugaTeal,
      rainbow2 = plt.antiLifeTeal,
      rainbow3 = plt.wallGlow,
      rainbow4 = plt.cosmicCyan,
      rainbow5 = plt.finalBreath,
      rainbow6 = plt.deadSilver,
      rainbow7 = plt.sourceFrost,
    },
    ui = {
      fg = plt.sourceFrost,
      fg_dim = plt.frozenGod,
      fg_dimmer = plt.primordialSkin,
      fg_dark = plt.titanFlesh,
      fg_reverse = plt.absoluteVoid,
      bg = plt.absoluteVoid,
      bg_dim = plt.absoluteVoid,
      bg_m1 = plt.absoluteVoid,
      bg_m2 = plt.sourceScar,
      bg_m3 = plt.wallDepth,
      bg_m4 = plt.entropyCore,
      bg_p1 = plt.sourceScar,
      bg_p2 = plt.wallDepth,
      bg_gutter = (opts.gutter ~= false) and plt.wallDepth or "none",
      bg_cursorline = plt.wallDepth,
      bg_cursorline_alt = plt.sourceScar,
      cursorline = plt.wallDepth,
      bg_highlight = plt.wallDepth,
      bg_search = plt.yugaTeal,
      bg_visual = plt.antiLifeTeal,
      bg_statusline = plt.wallDepth,
      border = plt.yugaTeal,
      header1 = plt.yugaTeal,
      header2 = plt.wallGlow,
      special = plt.finalBreath,
      nontext = plt.sourceScar,
      whitespace = plt.entropyCore,
      win_separator = plt.yugaTeal,
      indent = plt.sourceScar,
      indent_scope = plt.sourceFrost,
      picker = plt.cosmicCyan,
      yank = plt.yugaTeal,
      mark = plt.voidIce,
      scrollbar = plt.wallDepth,
      selection = plt.antiLifeTeal,
      line_nr = plt.elderStone,
      line_nr_dim = plt.entropyCore,
      line_nr_active = plt.sourceFrost,
      pmenu = {
        fg = plt.sourceFrost,
        fg_sel = plt.sourceFrost,
        fg_border = plt.wallDepth,
        bg = plt.wallDepth,
        bg_sel = plt.sourceScar,
        bg_border = plt.wallDepth,
        bg_sbar = plt.wallDepth,
        bg_thumb = plt.yugaTeal,
      },
      float = {
        fg = plt.sourceFrost,
        bg = plt.sourceScar,
        fg_border = plt.wallDepth,
        bg_border = plt.sourceScar,
      },
      tabline = {
        bg = plt.absoluteVoid,
        bg_inactive = plt.absoluteVoid,
        bg_selected = plt.wallDepth,
        bg_alternate = plt.absoluteVoid,
        fg_inactive = plt.elderStone,
        fg_selected = plt.yugaTeal,
        fg_alternate = plt.finalBreath,
        indicator = plt.wallGlow,
      },
    },
    syn = {
      attribute = plt.sourceFrost,
      boolean = plt.deadSilver,
      comment = plt.elderStone,
      constant = plt.finalBreath,
      deprecated = plt.entropyCore,
      func = plt.wallGlow,
      identifier = plt.sourceFrost,
      keyword = plt.yugaTeal,
      method = plt.antiLifeTeal,
      number = plt.cosmicCyan,
      operator = plt.deadSilver,
      parameter = plt.primordialSkin,
      preproc = plt.deadSilver,
      punct = plt.elderStone,
      regex = plt.wallGlow,
      statement = plt.yugaTeal,
      string = plt.finalBreath,
      symbol = plt.sourceFrost,
      type = plt.cosmicCyan,
      variable = plt.sourceFrost,
      special = plt.wallGlow,
      special2 = plt.antiLifeTeal,
      special3 = plt.deadSilver,
    },
    diag = {
      error = plt.yugaTeal,
      warning = plt.wallGlow,
      info = plt.deadSilver,
      hint = plt.cosmicCyan,
      ok = plt.finalBreath,
      virtual_text_error = plt.yugaTeal,
      virtual_text_warning = plt.wallGlow,
      virtual_text_info = plt.deadSilver,
      virtual_text_hint = plt.cosmicCyan,
      virtual_text_ok = plt.finalBreath,
    },
    diff = {
      add = plt.finalBreath,
      add_inline = plt.finalBreath,
      change = plt.wallGlow,
      change_inline = plt.wallGlow,
      delete = plt.yugaTeal,
      delete_inline = plt.yugaTeal,
      text = plt.antiLifeTeal,
    },
    vcs = {
      added = plt.finalBreath,
      changed = plt.cosmicCyan,
      removed = plt.yugaTeal,
    },
    term = {
      black = plt.absoluteVoid,
      red = plt.termRed,
      green = plt.termGreen,
      yellow = plt.termYellow,
      blue = plt.termBlue,
      magenta = plt.yugaTeal,
      cyan = plt.finalBreath,
      white = plt.sourceFrost,
      black_bright = "#222222",
      red_bright = "#ff4488",
      green_bright = "#44ffee",
      yellow_bright = "#cceeff",
      blue_bright = "#88ffff",
      magenta_bright = "#66ffee",
      cyan_bright = "#bbffff",
      white_bright = plt.sourceFrost,
      indexed1 = plt.yugaTeal,
      indexed2 = plt.finalBreath,
    },
  }
end

return {
  name = "Apokolips – Yuga Khan",
  author = "PrismPunk.nvim",
  description = "The First. The Last. The one who imprisoned the Old Gods and broke the Source itself. Cold cosmic teal and absolute black. There is no warmth here — only the end.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_lighter,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.yuga_teal,
    base09 = palette.anti_life_teal,
    base0A = palette.cosmic_cyan,
    base0B = palette.wall_glow,
    base0C = palette.final_breath,
    base0D = palette.dead_silver,
    base0E = palette.void_ice,
    base0F = palette.anti_life_black,
  },
  palette = palette,
  get = M.get,
}
