local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.1998term")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.silenceBright,
      insert = plt.restoreBright,
      normal = plt.restoreMid,
      replace = plt.restoreDeep,
      visual = plt.restorePulse,
    },
    accent = {
      accent1 = plt.restoreBright,
      accent2 = plt.restoreMid,
      accent3 = plt.restoreDeep,
      accent4 = plt.silenceBright,
      accent5 = plt.restorePulse,
      invert = plt.calmMid,
    },
    rainbow = {
      rainbow1 = plt.silenceBright,
      rainbow2 = plt.silenceLight,
      rainbow3 = plt.silenceMid,
      rainbow4 = plt.restoreDeep,
      rainbow5 = plt.restoreMid,
      rainbow6 = plt.restoreBright,
      rainbow7 = plt.restorePulse,
    },
    ui = {
      bg = plt.hushVoid,
      bg_cursorline = plt.calmLine,
      bg_dim = plt.hushVoid,
      bg_gutter = opts.gutter and plt.hushMid or "none",
      bg_highlight = plt.calmDeep,
      bg_m1 = plt.hushDark,
      bg_m2 = plt.hushDeep,
      bg_m3 = plt.hushMid,
      bg_m4 = plt.hushLight,
      bg_p1 = plt.hushDeep,
      bg_p2 = plt.hushMid,
      bg_statusline = plt.calmMid,
      bg_visual = plt.restoreDeep,
      border = plt.silenceMid,
      cursorline = plt.calmLine,
      fg = plt.clarityCore,
      fg_dim = plt.clarityDim,
      fg_reverse = plt.hushVoid,
      indent = plt.hushMid,
      line_nr = plt.silenceDeep,
      line_nr_active = plt.clarityCore,
      line_nr_dim = plt.silenceMid,
      nontext = plt.hushLight,
      selection = plt.restoreDeep,
      win_separator = plt.silenceMid,
      float = {
        bg = plt.hushDeep,
        bg_border = plt.hushDeep,
        fg = plt.clarityCore,
        fg_border = plt.calmMid,
      },
      pmenu = {
        bg = plt.calmMid,
        bg_border = plt.calmMid,
        bg_sbar = plt.calmMid,
        bg_sel = plt.calmDeep,
        bg_thumb = plt.silenceMid,
        fg = plt.clarityCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.hushVoid,
        bg_inactive = plt.hushVoid,
        bg_selected = plt.calmMid,
        fg_inactive = plt.silenceLighter,
        fg_selected = plt.clarityCore,
      },
    },
    syn = {
      attribute = plt.clarityCore,
      boolean = plt.restoreBright,
      comment = plt.silenceBright,
      constant = plt.silenceLightest,
      deprecated = plt.silenceMid,
      func = plt.clarityBright,
      identifier = plt.clarityCore,
      keyword = plt.clarityCore,
      method = plt.clarityBright,
      number = plt.silenceLightest,
      operator = plt.silenceLight,
      parameter = plt.silenceLighter,
      preproc = plt.restoreDeep,
      punct = plt.silenceMid,
      regex = plt.silenceLight,
      special = plt.restorePulse,
      statement = plt.clarityCore,
      string = plt.silenceLighter,
      symbol = plt.clarityCore,
      type = plt.silenceLightest,
      variable = plt.clarityCore,
    },
    diag = {
      error = plt.restoreBright,
      hint = plt.silenceMid,
      info = plt.silenceBright,
      ok = plt.silenceLighter,
      virtual_text_error = plt.restoreDeep,
      virtual_text_hint = plt.silenceDeep,
      virtual_text_info = plt.silenceLight,
      virtual_text_ok = plt.silenceLight,
      virtual_text_warning = plt.restoreMid,
      warning = plt.restoreMid,
    },
    diff = {
      add = plt.silenceLighter,
      add_inline = plt.phosphorMid,
      change = plt.silenceLight,
      change_inline = plt.silenceBright,
      delete = plt.restoreBright,
      delete_inline = plt.restorePulse,
      text = plt.restoreDeep,
    },
    vcs = {
      added = plt.silenceLighter,
      changed = plt.restoreDeep,
      removed = plt.restoreBright,
    },
    term = {
      black = plt.hushVoid,
      black_bright = color(plt.hushVoid):brighten(0.4):to_hex(),
      blue = plt.hushVoid,
      blue_bright = color(plt.hushVoid):brighten(0.2):to_hex(),
      cyan = plt.silenceLight,
      cyan_bright = color(plt.silenceLight):brighten(0.3):to_hex(),
      green = plt.silenceBright,
      green_bright = color(plt.silenceBright):brighten(0.3):to_hex(),
      magenta = plt.restoreMid,
      magenta_bright = color(plt.restoreMid):brighten(0.4):to_hex(),
      red = plt.restoreBright,
      red_bright = plt.restorePulse,
      white = plt.clarityCore,
      white_bright = plt.clarityBright,
      yellow = plt.silenceLightest,
      yellow_bright = plt.clarityDim,
    },
  }
end

return {
  name = "Detox: 1998 Terminal Green",
  author = "PrismPunk.nvim",
  description = "Pure 1998 CRT green phosphor. Zero blue. Deep readable greens. The terminal your soul remembers.",
  base16 = {
    base00 = palette.hushVoid,
    base01 = palette.hushDark,
    base02 = palette.hushDeep,
    base03 = palette.hushMid,
    base04 = palette.silenceBright,
    base05 = palette.silenceLightest,
    base06 = palette.clarityDim,
    base07 = palette.clarityCore,
    base08 = palette.restoreBright,
    base09 = palette.restoreMid,
    base0A = palette.restoreDeep,
    base0B = palette.silenceLighter,
    base0C = palette.restorePulse,
    base0D = palette.silenceLight,
    base0E = palette.restorePulse,
    base0F = palette.silenceMid,
  },
  palette = palette,
  get = M.get,
}
