local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.bone")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.dustCore,
      insert = plt.marrowLighter,
      normal = plt.marrowBright,
      replace = plt.marrowMid,
      visual = plt.decayPulse,
    },
    accent = {
      accent1 = plt.dustBright,
      accent2 = plt.dustCore,
      accent3 = plt.marrowLighter,
      accent4 = plt.marrowBright,
      accent5 = plt.decayPulse,
      invert = plt.creamMid,
    },
    rainbow = {
      rainbow1 = plt.marrowBright,
      rainbow2 = plt.marrowMid,
      rainbow3 = plt.marrowDeep,
      rainbow4 = plt.creamDeep,
      rainbow5 = plt.dustCore,
      rainbow6 = plt.dustBright,
      rainbow7 = plt.decayPulse,
    },
    ui = {
      bg = plt.boneVoid,
      bg_cursorline = plt.creamLine,
      bg_cursorline_alt = plt.creamMid,
      bg_dim = plt.boneVoid,
      bg_gutter = opts.gutter and plt.boneMid or "none",
      bg_highlight = plt.creamDeep,
      bg_m1 = plt.boneDark,
      bg_m2 = plt.boneDeep,
      bg_m3 = plt.boneMid,
      bg_m4 = plt.boneLight,
      bg_p1 = plt.boneDeep,
      bg_p2 = plt.boneMid,
      bg_search = plt.decayPulse,
      bg_statusline = plt.creamMid,
      bg_visual = plt.decayDeep,
      border = plt.marrowMid,
      cursorline = plt.creamLine,
      fg = plt.dustCore,
      fg_dark = plt.marrowMid,
      fg_dim = plt.dustCore,
      fg_dimmer = plt.marrowLighter,
      fg_reverse = plt.boneVoid,
      header1 = plt.dustBright,
      header2 = plt.dustCore,
      indent = plt.boneMid,
      indent_scope = plt.marrowDeep,
      line_nr = plt.marrowDeep,
      line_nr_active = plt.dustCore,
      line_nr_dim = plt.marrowMid,
      mark = plt.decayBright,
      nontext = plt.boneLight,
      picker = plt.marrowMid,
      scrollbar = plt.boneLight,
      selection = plt.decayDeep,
      special = plt.decayBright,
      whitespace = plt.boneMid,
      win_separator = plt.marrowMid,
      yank = plt.decayPulse,
      float = {
        bg = plt.boneDeep,
        bg_border = plt.boneDeep,
        fg = plt.dustCore,
        fg_border = plt.creamMid,
      },
      pmenu = {
        bg = plt.creamMid,
        bg_border = plt.creamMid,
        bg_sbar = plt.creamMid,
        bg_sel = plt.creamDeep,
        bg_thumb = plt.marrowMid,
        fg = plt.dustCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.boneVoid,
        bg_alternate = plt.boneVoid,
        bg_inactive = plt.boneVoid,
        bg_selected = plt.creamMid,
        fg_alternate = plt.marrowBright,
        fg_inactive = plt.marrowLighter,
        fg_selected = plt.dustCore,
        indicator = plt.decayPulse,
      },
    },
    syn = {
      attribute = plt.dustCore,
      boolean = plt.decayBright,
      comment = plt.marrowBright,
      constant = plt.marrowLightest,
      deprecated = plt.marrowMid,
      func = plt.dustBright,
      identifier = plt.dustCore,
      keyword = plt.dustCore,
      method = plt.dustBright,
      number = plt.marrowLightest,
      operator = plt.marrowMid,
      parameter = plt.marrowLighter,
      preproc = plt.decayMid,
      punct = plt.marrowDeep,
      regex = plt.marrowMid,
      special = plt.decayPulse,
      special2 = plt.decayMid,
      special3 = plt.decayBright,
      statement = plt.dustCore,
      string = plt.marrowLighter,
      symbol = plt.dustCore,
      type = plt.marrowLightest,
      variable = plt.dustCore,
    },
    diag = {
      error = plt.decayBright,
      hint = plt.marrowMid,
      info = plt.dustCore,
      ok = plt.marrowLighter,
      virtual_text_error = plt.decayMid,
      virtual_text_hint = plt.marrowDeep,
      virtual_text_info = plt.marrowBright,
      virtual_text_ok = plt.marrowMid,
      virtual_text_warning = plt.decayDeep,
      warning = plt.decayPulse,
    },
    diff = {
      add = plt.marrowLighter,
      add_inline = plt.marrowGlow,
      change = plt.marrowDeep,
      change_inline = plt.ivoryDeep,
      delete = plt.decayBright,
      delete_inline = plt.decayGlow,
      text = plt.decayMid,
    },
    vcs = {
      added = plt.marrowLighter,
      changed = plt.decayDeep,
      removed = plt.decayBright,
    },
    term = {
      black = plt.boneVoid,
      black_bright = color(plt.boneVoid):brighten(0.4):to_hex(),
      blue = plt.boneVoid,
      blue_bright = color(plt.boneVoid):brighten(0.2):to_hex(),
      cyan = plt.marrowMid,
      cyan_bright = color(plt.marrowMid):brighten(0.3):to_hex(),
      green = plt.marrowBright,
      green_bright = color(plt.marrowBright):brighten(0.3):to_hex(),
      indexed1 = plt.marrowLighter,
      indexed2 = plt.marrowBright,
      magenta = plt.dustCore,
      magenta_bright = color(plt.dustCore):brighten(0.4):to_hex(),
      red = plt.decayBright,
      red_bright = plt.decayPulse,
      white = plt.dustBright,
      white_bright = plt.dustBright,
      yellow = plt.marrowLightest,
      yellow_bright = plt.dustBright,
    },
  }
end

return {
  name = "Detox: Bone",
  author = "PrismPunk.nvim",
  description = "Skeletal bleached whites. Archaeological time. Deep earth decay. Memento mori.",
  base16 = {
    base00 = palette.boneVoid,
    base01 = palette.boneDark,
    base02 = palette.boneDeep,
    base03 = palette.boneMid,
    base04 = palette.marrowBright,
    base05 = palette.marrowLightest,
    base06 = palette.dustCore,
    base07 = palette.dustBright,
    base08 = palette.decayBright,
    base09 = palette.decayMid,
    base0A = palette.decayDeep,
    base0B = palette.marrowLighter,
    base0C = palette.decayPulse,
    base0D = palette.marrowMid,
    base0E = palette.decayPulse,
    base0F = palette.marrowMid,
  },
  palette = palette,
  get = M.get,
}
