local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.clay")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.clayCore,
      insert = plt.earthLighter,
      normal = plt.earthBright,
      replace = plt.earthMid,
      visual = plt.glazePulse,
    },
    accent = {
      accent1 = plt.clayBright,
      accent2 = plt.clayCore,
      accent3 = plt.earthLighter,
      accent4 = plt.earthBright,
      accent5 = plt.glazePulse,
      invert = plt.kilnMid,
    },
    rainbow = {
      rainbow1 = plt.earthBright,
      rainbow2 = plt.earthMid,
      rainbow3 = plt.earthDeep,
      rainbow4 = plt.kilnDeep,
      rainbow5 = plt.clayCore,
      rainbow6 = plt.clayBright,
      rainbow7 = plt.glazePulse,
    },
    ui = {
      bg = plt.clayVoid,
      bg_cursorline = plt.kilnLine,
      bg_cursorline_alt = plt.kilnMid,
      bg_dim = plt.clayVoid,
      bg_gutter = opts.gutter and plt.clayMid or "none",
      bg_highlight = plt.kilnDeep,
      bg_m1 = plt.clayDark,
      bg_m2 = plt.clayDeep,
      bg_m3 = plt.clayMid,
      bg_m4 = plt.clayLight,
      bg_p1 = plt.clayDeep,
      bg_p2 = plt.clayMid,
      bg_search = plt.glazePulse,
      bg_statusline = plt.kilnMid,
      bg_visual = plt.glazeDeep,
      border = plt.earthMid,
      cursorline = plt.kilnLine,
      fg = plt.clayCore,
      fg_dark = plt.earthMid,
      fg_dim = plt.clayCore,
      fg_dimmer = plt.earthLighter,
      fg_reverse = plt.clayVoid,
      header1 = plt.clayBright,
      header2 = plt.clayCore,
      indent = plt.clayMid,
      indent_scope = plt.earthDeep,
      line_nr = plt.earthDeep,
      line_nr_active = plt.clayCore,
      line_nr_dim = plt.earthMid,
      mark = plt.glazeBright,
      nontext = plt.clayLight,
      picker = plt.earthMid,
      scrollbar = plt.clayLight,
      selection = plt.glazeDeep,
      special = plt.glazeBright,
      whitespace = plt.clayMid,
      win_separator = plt.earthMid,
      yank = plt.glazePulse,
      float = {
        bg = plt.clayDeep,
        bg_border = plt.clayDeep,
        fg = plt.clayCore,
        fg_border = plt.kilnMid,
      },
      pmenu = {
        bg = plt.kilnMid,
        bg_border = plt.kilnMid,
        bg_sbar = plt.kilnMid,
        bg_sel = plt.kilnDeep,
        bg_thumb = plt.earthMid,
        fg = plt.clayCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.clayVoid,
        bg_alternate = plt.clayVoid,
        bg_inactive = plt.clayVoid,
        bg_selected = plt.kilnMid,
        fg_alternate = plt.earthBright,
        fg_inactive = plt.earthLighter,
        fg_selected = plt.clayCore,
        indicator = plt.glazePulse,
      },
    },
    syn = {
      attribute = plt.clayCore,
      boolean = plt.glazeBright,
      comment = plt.earthBright,
      constant = plt.earthLightest,
      deprecated = plt.earthMid,
      func = plt.clayBright,
      identifier = plt.clayCore,
      keyword = plt.clayCore,
      method = plt.clayBright,
      number = plt.earthLightest,
      operator = plt.earthMid,
      parameter = plt.earthLighter,
      preproc = plt.glazeMid,
      punct = plt.earthDeep,
      regex = plt.earthMid,
      special = plt.glazePulse,
      special2 = plt.glazeMid,
      special3 = plt.glazeBright,
      statement = plt.clayCore,
      string = plt.earthLighter,
      symbol = plt.clayCore,
      type = plt.earthLightest,
      variable = plt.clayCore,
    },
    diag = {
      error = plt.glazeBright,
      hint = plt.earthMid,
      info = plt.clayCore,
      ok = plt.earthLighter,
      virtual_text_error = plt.glazeMid,
      virtual_text_hint = plt.earthDeep,
      virtual_text_info = plt.earthBright,
      virtual_text_ok = plt.earthMid,
      virtual_text_warning = plt.glazeDeep,
      warning = plt.glazePulse,
    },
    diff = {
      add = plt.earthLighter,
      add_inline = plt.earthGlow,
      change = plt.earthDeep,
      change_inline = plt.terracottaMid,
      delete = plt.glazeBright,
      delete_inline = plt.glazeGlow,
      text = plt.glazeMid,
    },
    vcs = {
      added = plt.earthLighter,
      changed = plt.glazeDeep,
      removed = plt.glazeBright,
    },
    term = {
      black = plt.clayVoid,
      black_bright = color(plt.clayVoid):brighten(0.4):to_hex(),
      blue = plt.clayVoid,
      blue_bright = color(plt.clayVoid):brighten(0.2):to_hex(),
      cyan = plt.earthMid,
      cyan_bright = color(plt.earthMid):brighten(0.3):to_hex(),
      green = plt.earthBright,
      green_bright = color(plt.earthBright):brighten(0.3):to_hex(),
      indexed1 = plt.earthLighter,
      indexed2 = plt.earthBright,
      magenta = plt.clayCore,
      magenta_bright = color(plt.clayCore):brighten(0.4):to_hex(),
      red = plt.glazeBright,
      red_bright = plt.glazePulse,
      white = plt.clayBright,
      white_bright = plt.clayBright,
      yellow = plt.earthLightest,
      yellow_bright = plt.clayBright,
    },
  }
end

return {
  name = "Detox: Clay",
  author = "PrismPunk.nvim",
  description = "Fired earth pottery. Kiln-baked terracotta. Deep glaze stains. Handcrafted impermanence.",
  base16 = {
    base00 = palette.clayVoid,
    base01 = palette.clayDark,
    base02 = palette.clayDeep,
    base03 = palette.clayMid,
    base04 = palette.earthBright,
    base05 = palette.earthLightest,
    base06 = palette.clayCore,
    base07 = palette.clayBright,
    base08 = palette.glazeBright,
    base09 = palette.glazeMid,
    base0A = palette.glazeDeep,
    base0B = palette.earthLighter,
    base0C = palette.glazePulse,
    base0D = palette.earthMid,
    base0E = palette.glazePulse,
    base0F = palette.earthMid,
  },
  palette = palette,
  get = M.get,
}
