local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.concrete")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.urbCore,
      insert = plt.cementLighter,
      normal = plt.cementBright,
      replace = plt.cementMid,
      visual = plt.fracPulse,
    },
    accent = {
      accent1 = plt.urbBright,
      accent2 = plt.urbCore,
      accent3 = plt.cementLighter,
      accent4 = plt.cementBright,
      accent5 = plt.fracPulse,
      invert = plt.brutMid,
    },
    rainbow = {
      rainbow1 = plt.cementBright,
      rainbow2 = plt.cementMid,
      rainbow3 = plt.cementDeep,
      rainbow4 = plt.brutDeep,
      rainbow5 = plt.urbCore,
      rainbow6 = plt.urbBright,
      rainbow7 = plt.fracPulse,
    },
    ui = {
      bg = plt.concreteVoid,
      bg_cursorline = plt.brutLine,
      bg_cursorline_alt = plt.brutMid,
      bg_dim = plt.concreteVoid,
      bg_gutter = opts.gutter and plt.concreteMid or "none",
      bg_highlight = plt.brutDeep,
      bg_m1 = plt.concreteDark,
      bg_m2 = plt.concreteDeep,
      bg_m3 = plt.concreteMid,
      bg_m4 = plt.concreteLight,
      bg_p1 = plt.concreteDeep,
      bg_p2 = plt.concreteMid,
      bg_search = plt.fracPulse,
      bg_statusline = plt.brutMid,
      bg_visual = plt.fracDeep,
      border = plt.cementMid,
      cursorline = plt.brutLine,
      fg = plt.urbCore,
      fg_dark = plt.cementMid,
      fg_dim = plt.urbCore,
      fg_dimmer = plt.cementLighter,
      fg_reverse = plt.concreteVoid,
      header1 = plt.urbBright,
      header2 = plt.urbCore,
      indent = plt.concreteMid,
      indent_scope = plt.cementDeep,
      line_nr = plt.cementDeep,
      line_nr_active = plt.urbCore,
      line_nr_dim = plt.cementMid,
      mark = plt.fracBright,
      nontext = plt.concreteLight,
      picker = plt.cementMid,
      scrollbar = plt.concreteLight,
      selection = plt.fracDeep,
      special = plt.fracBright,
      whitespace = plt.concreteMid,
      win_separator = plt.cementMid,
      yank = plt.fracPulse,
      float = {
        bg = plt.concreteDeep,
        bg_border = plt.concreteDeep,
        fg = plt.urbCore,
        fg_border = plt.brutMid,
      },
      pmenu = {
        bg = plt.brutMid,
        bg_border = plt.brutMid,
        bg_sbar = plt.brutMid,
        bg_sel = plt.brutDeep,
        bg_thumb = plt.cementMid,
        fg = plt.urbCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.concreteVoid,
        bg_alternate = plt.concreteVoid,
        bg_inactive = plt.concreteVoid,
        bg_selected = plt.brutMid,
        fg_alternate = plt.cementBright,
        fg_inactive = plt.cementLighter,
        fg_selected = plt.urbCore,
        indicator = plt.fracPulse,
      },
    },
    syn = {
      attribute = plt.urbCore,
      boolean = plt.fracBright,
      comment = plt.cementBright,
      constant = plt.cementLightest,
      deprecated = plt.cementMid,
      func = plt.urbBright,
      identifier = plt.urbCore,
      keyword = plt.urbCore,
      method = plt.urbBright,
      number = plt.cementLightest,
      operator = plt.cementMid,
      parameter = plt.cementLighter,
      preproc = plt.fracMid,
      punct = plt.cementDeep,
      regex = plt.cementMid,
      special = plt.fracPulse,
      special2 = plt.fracMid,
      special3 = plt.fracBright,
      statement = plt.urbCore,
      string = plt.cementLighter,
      symbol = plt.urbCore,
      type = plt.cementLightest,
      variable = plt.urbCore,
    },
    diag = {
      error = plt.fracBright,
      hint = plt.cementMid,
      info = plt.urbCore,
      ok = plt.cementLighter,
      virtual_text_error = plt.fracMid,
      virtual_text_hint = plt.cementDeep,
      virtual_text_info = plt.cementBright,
      virtual_text_ok = plt.cementMid,
      virtual_text_warning = plt.fracDeep,
      warning = plt.fracPulse,
    },
    diff = {
      add = plt.cementLighter,
      add_inline = plt.cementGlow,
      change = plt.cementDeep,
      change_inline = plt.rebarMid,
      delete = plt.fracBright,
      delete_inline = plt.fracGlow,
      text = plt.fracMid,
    },
    vcs = {
      added = plt.cementLighter,
      changed = plt.fracDeep,
      removed = plt.fracBright,
    },
    term = {
      black = plt.concreteVoid,
      black_bright = color(plt.concreteVoid):brighten(0.4):to_hex(),
      blue = plt.concreteVoid,
      blue_bright = color(plt.concreteVoid):brighten(0.2):to_hex(),
      cyan = plt.cementMid,
      cyan_bright = color(plt.cementMid):brighten(0.3):to_hex(),
      green = plt.cementBright,
      green_bright = color(plt.cementBright):brighten(0.3):to_hex(),
      indexed1 = plt.cementLighter,
      indexed2 = plt.cementBright,
      magenta = plt.urbCore,
      magenta_bright = color(plt.urbCore):brighten(0.4):to_hex(),
      red = plt.fracBright,
      red_bright = plt.fracPulse,
      white = plt.urbBright,
      white_bright = plt.urbBright,
      yellow = plt.cementLightest,
      yellow_bright = plt.urbBright,
    },
  }
end

return {
  name = "Detox: Concrete",
  author = "PrismPunk.nvim",
  description = "Urban brutalism. True grayscale. Rust-orange breaks. Stark functional beauty.",
  base16 = {
    base00 = palette.concreteVoid,
    base01 = palette.concreteDark,
    base02 = palette.concreteDeep,
    base03 = palette.concreteMid,
    base04 = palette.cementBright,
    base05 = palette.cementLightest,
    base06 = palette.urbCore,
    base07 = palette.urbBright,
    base08 = palette.fracBright,
    base09 = palette.fracMid,
    base0A = palette.fracDeep,
    base0B = palette.cementLighter,
    base0C = palette.fracPulse,
    base0D = palette.cementMid,
    base0E = palette.fracPulse,
    base0F = palette.cementMid,
  },
  palette = palette,
  get = M.get,
}
