local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.copper")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.metallicCore,
      insert = plt.oxidLighter,
      normal = plt.oxidBright,
      replace = plt.oxidMid,
      visual = plt.polishPulse,
    },
    accent = {
      accent1 = plt.metallicBright,
      accent2 = plt.metallicCore,
      accent3 = plt.oxidLighter,
      accent4 = plt.oxidBright,
      accent5 = plt.polishPulse,
      invert = plt.patinMid,
    },
    rainbow = {
      rainbow1 = plt.oxidBright,
      rainbow2 = plt.oxidMid,
      rainbow3 = plt.oxidDeep,
      rainbow4 = plt.patinDeep,
      rainbow5 = plt.metallicCore,
      rainbow6 = plt.metallicBright,
      rainbow7 = plt.polishPulse,
    },
    ui = {
      bg = plt.copperVoid,
      bg_cursorline = plt.patinLine,
      bg_cursorline_alt = plt.patinMid,
      bg_dim = plt.copperVoid,
      bg_gutter = opts.gutter and plt.copperMid or "none",
      bg_highlight = plt.patinDeep,
      bg_m1 = plt.copperDark,
      bg_m2 = plt.copperDeep,
      bg_m3 = plt.copperMid,
      bg_m4 = plt.copperLight,
      bg_p1 = plt.copperDeep,
      bg_p2 = plt.copperMid,
      bg_search = plt.polishPulse,
      bg_statusline = plt.patinMid,
      bg_visual = plt.polishDeep,
      border = plt.oxidMid,
      cursorline = plt.patinLine,
      fg = plt.metallicCore,
      fg_dark = plt.oxidMid,
      fg_dim = plt.metallicCore,
      fg_dimmer = plt.oxidLighter,
      fg_reverse = plt.copperVoid,
      header1 = plt.metallicBright,
      header2 = plt.metallicCore,
      indent = plt.copperMid,
      indent_scope = plt.oxidDeep,
      line_nr = plt.oxidDeep,
      line_nr_active = plt.metallicCore,
      line_nr_dim = plt.oxidMid,
      mark = plt.polishBright,
      nontext = plt.copperLight,
      picker = plt.oxidMid,
      scrollbar = plt.copperLight,
      selection = plt.polishDeep,
      special = plt.polishBright,
      whitespace = plt.copperMid,
      win_separator = plt.oxidMid,
      yank = plt.polishPulse,
      float = {
        bg = plt.copperDeep,
        bg_border = plt.copperDeep,
        fg = plt.metallicCore,
        fg_border = plt.patinMid,
      },
      pmenu = {
        bg = plt.patinMid,
        bg_border = plt.patinMid,
        bg_sbar = plt.patinMid,
        bg_sel = plt.patinDeep,
        bg_thumb = plt.oxidMid,
        fg = plt.metallicCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.copperVoid,
        bg_alternate = plt.copperVoid,
        bg_inactive = plt.copperVoid,
        bg_selected = plt.patinMid,
        fg_alternate = plt.oxidBright,
        fg_inactive = plt.oxidLighter,
        fg_selected = plt.metallicCore,
        indicator = plt.polishPulse,
      },
    },
    syn = {
      attribute = plt.metallicCore,
      boolean = plt.polishBright,
      comment = plt.oxidBright,
      constant = plt.oxidLightest,
      deprecated = plt.oxidMid,
      func = plt.metallicBright,
      identifier = plt.metallicCore,
      keyword = plt.metallicCore,
      method = plt.metallicBright,
      number = plt.oxidLightest,
      operator = plt.oxidMid,
      parameter = plt.oxidLighter,
      preproc = plt.polishMid,
      punct = plt.oxidDeep,
      regex = plt.oxidMid,
      special = plt.polishPulse,
      special2 = plt.polishMid,
      special3 = plt.polishBright,
      statement = plt.metallicCore,
      string = plt.oxidLighter,
      symbol = plt.metallicCore,
      type = plt.oxidLightest,
      variable = plt.metallicCore,
    },
    diag = {
      error = plt.polishBright,
      hint = plt.oxidMid,
      info = plt.metallicCore,
      ok = plt.oxidLighter,
      virtual_text_error = plt.polishMid,
      virtual_text_hint = plt.oxidDeep,
      virtual_text_info = plt.oxidBright,
      virtual_text_ok = plt.oxidMid,
      virtual_text_warning = plt.polishDeep,
      warning = plt.polishPulse,
    },
    diff = {
      add = plt.oxidLighter,
      add_inline = plt.oxidGlow,
      change = plt.oxidDeep,
      change_inline = plt.verdigrisMid,
      delete = plt.polishBright,
      delete_inline = plt.polishGlow,
      text = plt.polishMid,
    },
    vcs = {
      added = plt.oxidLighter,
      changed = plt.polishDeep,
      removed = plt.polishBright,
    },
    term = {
      black = plt.copperVoid,
      black_bright = color(plt.copperVoid):brighten(0.4):to_hex(),
      blue = plt.copperVoid,
      blue_bright = color(plt.copperVoid):brighten(0.2):to_hex(),
      cyan = plt.oxidMid,
      cyan_bright = color(plt.oxidMid):brighten(0.3):to_hex(),
      green = plt.oxidBright,
      green_bright = color(plt.oxidBright):brighten(0.3):to_hex(),
      indexed1 = plt.oxidLighter,
      indexed2 = plt.oxidBright,
      magenta = plt.metallicCore,
      magenta_bright = color(plt.metallicCore):brighten(0.4):to_hex(),
      red = plt.polishBright,
      red_bright = plt.polishPulse,
      white = plt.metallicBright,
      white_bright = plt.metallicBright,
      yellow = plt.oxidLightest,
      yellow_bright = plt.metallicBright,
    },
  }
end

return {
  name = "Detox: Copper",
  author = "PrismPunk.nvim",
  description = "Oxidized metal heritage. Tarnished patina. Polish reflection glow. Industrial decay.",
  base16 = {
    base00 = palette.copperVoid,
    base01 = palette.copperDark,
    base02 = palette.copperDeep,
    base03 = palette.copperMid,
    base04 = palette.oxidBright,
    base05 = palette.oxidLightest,
    base06 = palette.metallicCore,
    base07 = palette.metallicBright,
    base08 = palette.polishBright,
    base09 = palette.polishMid,
    base0A = palette.polishDeep,
    base0B = palette.oxidLighter,
    base0C = palette.polishPulse,
    base0D = palette.oxidMid,
    base0E = palette.polishPulse,
    base0F = palette.oxidMid,
  },
  palette = palette,
  get = M.get,
}
