local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.ember")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.ashCore,
      insert = plt.glowLighter,
      normal = plt.glowBright,
      replace = plt.glowMid,
      visual = plt.flamePulse,
    },
    accent = {
      accent1 = plt.ashBright,
      accent2 = plt.ashCore,
      accent3 = plt.glowLighter,
      accent4 = plt.glowBright,
      accent5 = plt.flamePulse,
      invert = plt.fireMid,
    },
    rainbow = {
      rainbow1 = plt.glowBright,
      rainbow2 = plt.glowMid,
      rainbow3 = plt.glowDeep,
      rainbow4 = plt.fireDeep,
      rainbow5 = plt.ashCore,
      rainbow6 = plt.ashBright,
      rainbow7 = plt.flamePulse,
    },
    ui = {
      bg = plt.coalVoid,
      bg_cursorline = plt.fireLine,
      bg_cursorline_alt = plt.fireMid,
      bg_dim = plt.coalVoid,
      bg_gutter = opts.gutter and plt.coalMid or "none",
      bg_highlight = plt.fireDeep,
      bg_m1 = plt.coalDark,
      bg_m2 = plt.coalDeep,
      bg_m3 = plt.coalMid,
      bg_m4 = plt.coalLight,
      bg_p1 = plt.coalDeep,
      bg_p2 = plt.coalMid,
      bg_search = plt.flamePulse,
      bg_statusline = plt.fireMid,
      bg_visual = plt.flameDeep,
      border = plt.glowMid,
      cursorline = plt.fireLine,
      fg = plt.ashCore,
      fg_dark = plt.glowMid,
      fg_dim = plt.ashCore,
      fg_dimmer = plt.glowLighter,
      fg_reverse = plt.coalVoid,
      header1 = plt.ashBright,
      header2 = plt.ashCore,
      indent = plt.coalMid,
      indent_scope = plt.glowDeep,
      line_nr = plt.glowDeep,
      line_nr_active = plt.ashCore,
      line_nr_dim = plt.glowMid,
      mark = plt.flameBright,
      nontext = plt.coalLight,
      picker = plt.glowMid,
      scrollbar = plt.coalLight,
      selection = plt.flameDeep,
      special = plt.flameBright,
      whitespace = plt.coalMid,
      win_separator = plt.glowMid,
      yank = plt.flamePulse,
      float = {
        bg = plt.coalDeep,
        bg_border = plt.coalDeep,
        fg = plt.ashCore,
        fg_border = plt.fireMid,
      },
      pmenu = {
        bg = plt.fireMid,
        bg_border = plt.fireMid,
        bg_sbar = plt.fireMid,
        bg_sel = plt.fireDeep,
        bg_thumb = plt.glowMid,
        fg = plt.ashCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.coalVoid,
        bg_alternate = plt.coalVoid,
        bg_inactive = plt.coalVoid,
        bg_selected = plt.fireMid,
        fg_alternate = plt.glowBright,
        fg_inactive = plt.glowLighter,
        fg_selected = plt.ashCore,
        indicator = plt.flamePulse,
      },
    },
    syn = {
      attribute = plt.ashCore,
      boolean = plt.flameBright,
      comment = plt.glowBright,
      constant = plt.glowLightest,
      deprecated = plt.glowMid,
      func = plt.ashBright,
      identifier = plt.ashCore,
      keyword = plt.ashCore,
      method = plt.ashBright,
      number = plt.glowLightest,
      operator = plt.glowMid,
      parameter = plt.glowLighter,
      preproc = plt.flameMid,
      punct = plt.glowDeep,
      regex = plt.glowMid,
      special = plt.flamePulse,
      special2 = plt.flameMid,
      special3 = plt.flameBright,
      statement = plt.ashCore,
      string = plt.glowLighter,
      symbol = plt.ashCore,
      type = plt.glowLightest,
      variable = plt.ashCore,
    },
    diag = {
      error = plt.flameBright,
      hint = plt.glowMid,
      info = plt.ashCore,
      ok = plt.glowLighter,
      virtual_text_error = plt.flameMid,
      virtual_text_hint = plt.glowDeep,
      virtual_text_info = plt.glowBright,
      virtual_text_ok = plt.glowMid,
      virtual_text_warning = plt.flameDeep,
      warning = plt.flamePulse,
    },
    diff = {
      add = plt.glowLighter,
      add_inline = plt.glowShine,
      change = plt.glowDeep,
      change_inline = plt.smolderMid,
      delete = plt.flameBright,
      delete_inline = plt.flameGlow,
      text = plt.flameMid,
    },
    vcs = {
      added = plt.glowLighter,
      changed = plt.flameDeep,
      removed = plt.flameBright,
    },
    term = {
      black = plt.coalVoid,
      black_bright = color(plt.coalVoid):brighten(0.4):to_hex(),
      blue = plt.coalVoid,
      blue_bright = color(plt.coalVoid):brighten(0.2):to_hex(),
      cyan = plt.glowMid,
      cyan_bright = color(plt.glowMid):brighten(0.3):to_hex(),
      green = plt.glowBright,
      green_bright = color(plt.glowBright):brighten(0.3):to_hex(),
      indexed1 = plt.glowLighter,
      indexed2 = plt.glowBright,
      magenta = plt.ashCore,
      magenta_bright = color(plt.ashCore):brighten(0.4):to_hex(),
      red = plt.flameBright,
      red_bright = plt.flamePulse,
      white = plt.ashBright,
      white_bright = plt.ashBright,
      yellow = plt.glowLightest,
      yellow_bright = plt.ashBright,
    },
  }
end

return {
  name = "Detox: Ember",
  author = "PrismPunk.nvim",
  description = "Fading fire. Cooling coals. Pale yellow last flames. Peaceful dying intensity.",
  base16 = {
    base00 = palette.coalVoid,
    base01 = palette.coalDark,
    base02 = palette.coalDeep,
    base03 = palette.coalMid,
    base04 = palette.glowBright,
    base05 = palette.glowLightest,
    base06 = palette.ashCore,
    base07 = palette.ashBright,
    base08 = palette.flameBright,
    base09 = palette.flameMid,
    base0A = palette.flameDeep,
    base0B = palette.glowLighter,
    base0C = palette.flamePulse,
    base0D = palette.glowMid,
    base0E = palette.flamePulse,
    base0F = palette.glowMid,
  },
  palette = palette,
  get = M.get,
}
