local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.fog")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.glowCore,
      insert = plt.veilLighter,
      normal = plt.veilBright,
      replace = plt.veilMid,
      visual = plt.amberPulse,
    },
    accent = {
      accent1 = plt.glowBright,
      accent2 = plt.glowCore,
      accent3 = plt.veilLighter,
      accent4 = plt.veilBright,
      accent5 = plt.amberPulse,
      invert = plt.hazeMid,
    },
    rainbow = {
      rainbow1 = plt.veilBright,
      rainbow2 = plt.veilMid,
      rainbow3 = plt.veilDeep,
      rainbow4 = plt.hazeDeep,
      rainbow5 = plt.glowCore,
      rainbow6 = plt.glowBright,
      rainbow7 = plt.amberPulse,
    },
    ui = {
      bg = plt.mistVoid,
      bg_cursorline = plt.hazeLine,
      bg_cursorline_alt = plt.hazeMid,
      bg_dim = plt.mistVoid,
      bg_gutter = opts.gutter and plt.mistMid or "none",
      bg_highlight = plt.hazeDeep,
      bg_m1 = plt.mistDark,
      bg_m2 = plt.mistDeep,
      bg_m3 = plt.mistMid,
      bg_m4 = plt.mistLight,
      bg_p1 = plt.mistDeep,
      bg_p2 = plt.mistMid,
      bg_search = plt.amberPulse,
      bg_statusline = plt.hazeMid,
      bg_visual = plt.amberDeep,
      border = plt.veilMid,
      cursorline = plt.hazeLine,
      fg = plt.glowCore,
      fg_dark = plt.veilMid,
      fg_dim = plt.glowCore,
      fg_dimmer = plt.veilLighter,
      fg_reverse = plt.mistVoid,
      header1 = plt.glowBright,
      header2 = plt.glowCore,
      indent = plt.mistMid,
      indent_scope = plt.veilDeep,
      line_nr = plt.veilDeep,
      line_nr_active = plt.glowCore,
      line_nr_dim = plt.veilMid,
      mark = plt.amberBright,
      nontext = plt.mistLight,
      picker = plt.veilMid,
      scrollbar = plt.mistLight,
      selection = plt.amberDeep,
      special = plt.amberBright,
      whitespace = plt.mistMid,
      win_separator = plt.veilMid,
      yank = plt.amberPulse,
      float = {
        bg = plt.mistDeep,
        bg_border = plt.mistDeep,
        fg = plt.glowCore,
        fg_border = plt.hazeMid,
      },
      pmenu = {
        bg = plt.hazeMid,
        bg_border = plt.hazeMid,
        bg_sbar = plt.hazeMid,
        bg_sel = plt.hazeDeep,
        bg_thumb = plt.veilMid,
        fg = plt.glowCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.mistVoid,
        bg_alternate = plt.mistVoid,
        bg_inactive = plt.mistVoid,
        bg_selected = plt.hazeMid,
        fg_alternate = plt.veilBright,
        fg_inactive = plt.veilLighter,
        fg_selected = plt.glowCore,
        indicator = plt.amberPulse,
      },
    },
    syn = {
      attribute = plt.glowCore,
      boolean = plt.amberBright,
      comment = plt.veilBright,
      constant = plt.veilLightest,
      deprecated = plt.veilMid,
      func = plt.glowBright,
      identifier = plt.glowCore,
      keyword = plt.glowCore,
      method = plt.glowBright,
      number = plt.veilLightest,
      operator = plt.veilMid,
      parameter = plt.veilLighter,
      preproc = plt.amberMid,
      punct = plt.veilDeep,
      regex = plt.veilMid,
      special = plt.amberPulse,
      special2 = plt.amberMid,
      special3 = plt.amberBright,
      statement = plt.glowCore,
      string = plt.veilLighter,
      symbol = plt.glowCore,
      type = plt.veilLightest,
      variable = plt.glowCore,
    },
    diag = {
      error = plt.amberBright,
      hint = plt.veilMid,
      info = plt.glowCore,
      ok = plt.veilLighter,
      virtual_text_error = plt.amberMid,
      virtual_text_hint = plt.veilDeep,
      virtual_text_info = plt.veilBright,
      virtual_text_ok = plt.veilMid,
      virtual_text_warning = plt.amberDeep,
      warning = plt.amberPulse,
    },
    diff = {
      add = plt.veilLighter,
      add_inline = plt.veilShine,
      change = plt.veilDeep,
      change_inline = plt.vaporMid,
      delete = plt.amberBright,
      delete_inline = plt.amberGlow,
      text = plt.amberMid,
    },
    vcs = {
      added = plt.veilLighter,
      changed = plt.amberDeep,
      removed = plt.amberBright,
    },
    term = {
      black = plt.mistVoid,
      black_bright = color(plt.mistVoid):brighten(0.4):to_hex(),
      blue = plt.mistVoid,
      blue_bright = color(plt.mistVoid):brighten(0.2):to_hex(),
      cyan = plt.veilMid,
      cyan_bright = color(plt.veilMid):brighten(0.3):to_hex(),
      green = plt.veilBright,
      green_bright = color(plt.veilBright):brighten(0.3):to_hex(),
      indexed1 = plt.veilLighter,
      indexed2 = plt.veilBright,
      magenta = plt.glowCore,
      magenta_bright = color(plt.glowCore):brighten(0.4):to_hex(),
      red = plt.amberBright,
      red_bright = plt.amberPulse,
      white = plt.glowBright,
      white_bright = plt.glowBright,
      yellow = plt.veilLightest,
      yellow_bright = plt.glowBright,
    },
  }
end

return {
  name = "Detox: Fog",
  author = "PrismPunk.nvim",
  description = "Misty morning obscurity. Pale desaturated whites. Muted amber through haze. Diffuse clarity.",
  base16 = {
    base00 = palette.mistVoid,
    base01 = palette.mistDark,
    base02 = palette.mistDeep,
    base03 = palette.mistMid,
    base04 = palette.veilBright,
    base05 = palette.veilLightest,
    base06 = palette.glowCore,
    base07 = palette.glowBright,
    base08 = palette.amberBright,
    base09 = palette.amberMid,
    base0A = palette.amberDeep,
    base0B = palette.veilLighter,
    base0C = palette.amberPulse,
    base0D = palette.veilMid,
    base0E = palette.amberPulse,
    base0F = palette.veilMid,
  },
  palette = palette,
  get = M.get,
}
