local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.frost")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.clearCore,
      insert = plt.icyLighter,
      normal = plt.icyBright,
      replace = plt.icyMid,
      visual = plt.sunPulse,
    },
    accent = {
      accent1 = plt.clearBright,
      accent2 = plt.clearCore,
      accent3 = plt.icyLighter,
      accent4 = plt.icyBright,
      accent5 = plt.sunPulse,
      invert = plt.crystalMid,
    },
    rainbow = {
      rainbow1 = plt.icyBright,
      rainbow2 = plt.icyMid,
      rainbow3 = plt.icyDeep,
      rainbow4 = plt.crystalDeep,
      rainbow5 = plt.clearCore,
      rainbow6 = plt.clearBright,
      rainbow7 = plt.sunPulse,
    },
    ui = {
      bg = plt.frostVoid,
      bg_cursorline = plt.crystalLine,
      bg_cursorline_alt = plt.crystalMid,
      bg_dim = plt.frostVoid,
      bg_gutter = opts.gutter and plt.frostMid or "none",
      bg_highlight = plt.crystalDeep,
      bg_m1 = plt.frostDark,
      bg_m2 = plt.frostDeep,
      bg_m3 = plt.frostMid,
      bg_m4 = plt.frostLight,
      bg_p1 = plt.frostDeep,
      bg_p2 = plt.frostMid,
      bg_search = plt.sunPulse,
      bg_statusline = plt.crystalMid,
      bg_visual = plt.sunDeep,
      border = plt.icyMid,
      cursorline = plt.crystalLine,
      fg = plt.clearCore,
      fg_dark = plt.icyMid,
      fg_dim = plt.clearCore,
      fg_dimmer = plt.icyLighter,
      fg_reverse = plt.frostVoid,
      header1 = plt.clearBright,
      header2 = plt.clearCore,
      indent = plt.frostMid,
      indent_scope = plt.icyDeep,
      line_nr = plt.icyDeep,
      line_nr_active = plt.clearCore,
      line_nr_dim = plt.icyMid,
      mark = plt.sunBright,
      nontext = plt.frostLight,
      picker = plt.icyMid,
      scrollbar = plt.frostLight,
      selection = plt.sunDeep,
      special = plt.sunBright,
      whitespace = plt.frostMid,
      win_separator = plt.icyMid,
      yank = plt.sunPulse,
      float = {
        bg = plt.frostDeep,
        bg_border = plt.frostDeep,
        fg = plt.clearCore,
        fg_border = plt.crystalMid,
      },
      pmenu = {
        bg = plt.crystalMid,
        bg_border = plt.crystalMid,
        bg_sbar = plt.crystalMid,
        bg_sel = plt.crystalDeep,
        bg_thumb = plt.icyMid,
        fg = plt.clearCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.frostVoid,
        bg_alternate = plt.frostVoid,
        bg_inactive = plt.frostVoid,
        bg_selected = plt.crystalMid,
        fg_alternate = plt.icyBright,
        fg_inactive = plt.icyLighter,
        fg_selected = plt.clearCore,
        indicator = plt.sunPulse,
      },
    },
    syn = {
      attribute = plt.clearCore,
      boolean = plt.sunBright,
      comment = plt.icyBright,
      constant = plt.icyLightest,
      deprecated = plt.icyMid,
      func = plt.clearBright,
      identifier = plt.clearCore,
      keyword = plt.clearCore,
      method = plt.clearBright,
      number = plt.icyLightest,
      operator = plt.icyMid,
      parameter = plt.icyLighter,
      preproc = plt.sunMid,
      punct = plt.icyDeep,
      regex = plt.icyMid,
      special = plt.sunPulse,
      special2 = plt.sunMid,
      special3 = plt.sunBright,
      statement = plt.clearCore,
      string = plt.icyLighter,
      symbol = plt.clearCore,
      type = plt.icyLightest,
      variable = plt.clearCore,
    },
    diag = {
      error = plt.sunBright,
      hint = plt.icyMid,
      info = plt.clearCore,
      ok = plt.icyLighter,
      virtual_text_error = plt.sunMid,
      virtual_text_hint = plt.icyDeep,
      virtual_text_info = plt.icyBright,
      virtual_text_ok = plt.icyMid,
      virtual_text_warning = plt.sunDeep,
      warning = plt.sunPulse,
    },
    diff = {
      add = plt.icyLighter,
      add_inline = plt.icyShine,
      change = plt.icyDeep,
      change_inline = plt.chilledMid,
      delete = plt.sunBright,
      delete_inline = plt.sunGlow,
      text = plt.sunMid,
    },
    vcs = {
      added = plt.icyLighter,
      changed = plt.sunDeep,
      removed = plt.sunBright,
    },
    term = {
      black = plt.frostVoid,
      black_bright = color(plt.frostVoid):brighten(0.4):to_hex(),
      blue = plt.frostVoid,
      blue_bright = color(plt.frostVoid):brighten(0.2):to_hex(),
      cyan = plt.icyMid,
      cyan_bright = color(plt.icyMid):brighten(0.3):to_hex(),
      green = plt.icyBright,
      green_bright = color(plt.icyBright):brighten(0.3):to_hex(),
      indexed1 = plt.icyLighter,
      indexed2 = plt.icyBright,
      magenta = plt.clearCore,
      magenta_bright = color(plt.clearCore):brighten(0.4):to_hex(),
      red = plt.sunBright,
      red_bright = plt.sunPulse,
      white = plt.clearBright,
      white_bright = plt.clearBright,
      yellow = plt.icyLightest,
      yellow_bright = plt.clearBright,
    },
  }
end

return {
  name = "Detox: Frost",
  author = "PrismPunk.nvim",
  description = "Ice crystals & frozen surfaces. Pale cyan clarity. Faint sun through ice. Crystalline winter.",
  base16 = {
    base00 = palette.frostVoid,
    base01 = palette.frostDark,
    base02 = palette.frostDeep,
    base03 = palette.frostMid,
    base04 = palette.icyBright,
    base05 = palette.icyLightest,
    base06 = palette.clearCore,
    base07 = palette.clearBright,
    base08 = palette.sunBright,
    base09 = palette.sunMid,
    base0A = palette.sunDeep,
    base0B = palette.icyLighter,
    base0C = palette.sunPulse,
    base0D = palette.icyMid,
    base0E = palette.sunPulse,
    base0F = palette.icyMid,
  },
  palette = palette,
  get = M.get,
}
