local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.glass")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.prismCore,
      insert = plt.fractLighter,
      normal = plt.fractBright,
      replace = plt.fractMid,
      visual = plt.crackPulse,
    },
    accent = {
      accent1 = plt.prismBright,
      accent2 = plt.prismCore,
      accent3 = plt.fractLighter,
      accent4 = plt.fractBright,
      accent5 = plt.crackPulse,
      invert = plt.clearMid,
    },
    rainbow = {
      rainbow1 = plt.fractBright,
      rainbow2 = plt.fractMid,
      rainbow3 = plt.fractDeep,
      rainbow4 = plt.clearDeep,
      rainbow5 = plt.prismCore,
      rainbow6 = plt.prismBright,
      rainbow7 = plt.crackPulse,
    },
    ui = {
      bg = plt.glassVoid,
      bg_cursorline = plt.clearLine,
      bg_dim = plt.glassVoid,
      bg_gutter = opts.gutter and plt.glassMid or "none",
      bg_highlight = plt.clearDeep,
      bg_m1 = plt.glassDark,
      bg_m2 = plt.glassDeep,
      bg_m3 = plt.glassMid,
      bg_m4 = plt.glassLight,
      bg_p1 = plt.glassDeep,
      bg_p2 = plt.glassMid,
      bg_search = plt.crackPulse,
      bg_statusline = plt.clearMid,
      bg_visual = plt.crackDeep,
      border = plt.fractMid,
      cursorline = plt.clearLine,
      fg = plt.prismCore,
      fg_dark = plt.fractMid,
      fg_dim = plt.prismCore,
      fg_dimmer = plt.fractLighter,
      fg_reverse = plt.glassVoid,
      header1 = plt.prismBright,
      header2 = plt.prismCore,
      indent = plt.glassMid,
      indent_scope = plt.fractDeep,
      line_nr = plt.fractMid,
      line_nr_active = plt.prismCore,
      line_nr_dim = plt.fractBright,
      mark = plt.crackBright,
      nontext = plt.glassLight,
      picker = plt.fractMid,
      scrollbar = plt.glassLight,
      selection = plt.crackDeep,
      special = plt.crackBright,
      whitespace = plt.glassMid,
      win_separator = plt.fractMid,
      yank = plt.crackPulse,
      float = {
        bg = plt.glassDeep,
        bg_border = plt.glassDeep,
        fg = plt.prismCore,
        fg_border = plt.clearMid,
      },
      pmenu = {
        bg = plt.clearMid,
        bg_border = plt.clearMid,
        bg_sbar = plt.clearMid,
        bg_sel = plt.clearDeep,
        bg_thumb = plt.fractMid,
        fg = plt.prismCore,
        fg_border = plt.clearMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.glassVoid,
        bg_alternate = plt.glassVoid,
        bg_inactive = plt.glassVoid,
        bg_selected = plt.clearMid,
        fg_alternate = plt.fractBright,
        fg_inactive = plt.fractLighter,
        fg_selected = plt.prismCore,
        indicator = plt.crackPulse,
      },
    },
    syn = {
      attribute = plt.prismCore,
      boolean = plt.crackBright,
      comment = plt.fractBright,
      constant = plt.fractLightest,
      deprecated = plt.fractMid,
      func = plt.prismBright,
      identifier = plt.prismCore,
      keyword = plt.prismCore,
      method = plt.prismBright,
      number = plt.fractLightest,
      operator = plt.fractMid,
      parameter = plt.fractLighter,
      preproc = plt.crackMid,
      punct = plt.fractDeep,
      regex = plt.fractMid,
      special = plt.crackPulse,
      special2 = plt.crackMid,
      special3 = plt.crackBright,
      statement = plt.prismCore,
      string = plt.fractLighter,
      symbol = plt.prismCore,
      type = plt.fractLightest,
      variable = plt.prismCore,
    },
    diag = {
      error = plt.crackBright,
      hint = plt.fractMid,
      info = plt.prismCore,
      ok = plt.fractLighter,
      virtual_text_error = plt.crackBright,
      virtual_text_hint = plt.fractMid,
      virtual_text_info = plt.prismCore,
      virtual_text_ok = plt.fractLighter,
      virtual_text_warning = plt.crackPulse,
      warning = plt.crackPulse,
    },
    diff = {
      add = plt.fractLighter,
      add_inline = plt.fractDeep,
      change = plt.fractDeep,
      change_inline = plt.clearDeep,
      delete = plt.crackBright,
      delete_inline = plt.crackDeep,
      text = plt.crackMid,
    },
    vcs = {
      added = plt.fractLighter,
      changed = plt.crackDeep,
      removed = plt.crackBright,
    },
    term = {
      black = plt.glassVoid,
      black_bright = color(plt.glassVoid):brighten(0.4):to_hex(),
      blue = plt.glassVoid,
      blue_bright = color(plt.glassVoid):brighten(0.2):to_hex(),
      cyan = plt.fractMid,
      cyan_bright = color(plt.fractMid):brighten(0.3):to_hex(),
      green = plt.fractBright,
      green_bright = color(plt.fractBright):brighten(0.3):to_hex(),
      indexed1 = plt.fractLighter,
      indexed2 = plt.fractBright,
      magenta = plt.prismCore,
      magenta_bright = color(plt.prismCore):brighten(0.4):to_hex(),
      red = plt.crackBright,
      red_bright = plt.crackPulse,
      white = plt.prismBright,
      white_bright = plt.prismBright,
      yellow = plt.fractLightest,
      yellow_bright = plt.prismBright,
    },
  }
end

return {
  name = "Detox: Glass",
  author = "PrismPunk.nvim",
  description = "Transparent fragility. Cool clears. Faint red cracks. Brittle precision.",
  base16 = {
    base00 = palette.glassVoid,
    base01 = palette.glassDark,
    base02 = palette.glassDeep,
    base03 = palette.glassMid,
    base04 = palette.fractBright,
    base05 = palette.fractLightest,
    base06 = palette.prismCore,
    base07 = palette.prismBright,
    base08 = palette.crackBright,
    base09 = palette.crackMid,
    base0A = palette.crackDeep,
    base0B = palette.fractLighter,
    base0C = palette.crackPulse,
    base0D = palette.fractMid,
    base0E = palette.crackPulse,
    base0F = palette.fractMid,
  },
  palette = palette,
  get = M.get,
}
