local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.ink")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.scrollCore,
      insert = plt.fadeLighter,
      normal = plt.fadeBright,
      replace = plt.fadeMid,
      visual = plt.goldPulse,
    },
    accent = {
      accent1 = plt.scrollBright,
      accent2 = plt.scrollCore,
      accent3 = plt.fadeLighter,
      accent4 = plt.fadeBright,
      accent5 = plt.goldPulse,
      invert = plt.parchMid,
    },
    rainbow = {
      rainbow1 = plt.fadeBright,
      rainbow2 = plt.fadeMid,
      rainbow3 = plt.fadeDeep,
      rainbow4 = plt.parchDeep,
      rainbow5 = plt.scrollCore,
      rainbow6 = plt.scrollBright,
      rainbow7 = plt.goldPulse,
    },
    ui = {
      bg = plt.inkVoid,
      bg_cursorline = plt.parchLine,
      bg_dim = plt.inkVoid,
      bg_gutter = opts.gutter and plt.inkMid or "none",
      bg_highlight = plt.parchDeep,
      bg_m1 = plt.inkDark,
      bg_m2 = plt.inkDeep,
      bg_m3 = plt.inkMid,
      bg_m4 = plt.inkLight,
      bg_p1 = plt.inkDeep,
      bg_p2 = plt.inkMid,
      bg_search = plt.goldPulse,
      bg_statusline = plt.parchMid,
      bg_visual = plt.goldDeep,
      border = plt.fadeMid,
      cursorline = plt.parchLine,
      fg = plt.scrollCore,
      fg_dark = plt.fadeMid,
      fg_dim = plt.scrollCore,
      fg_dimmer = plt.fadeLighter,
      fg_reverse = plt.inkVoid,
      header1 = plt.scrollBright,
      header2 = plt.scrollCore,
      indent = plt.inkMid,
      indent_scope = plt.fadeDeep,
      line_nr = plt.fadeMid,
      line_nr_active = plt.scrollCore,
      line_nr_dim = plt.fadeBright,
      mark = plt.goldBright,
      nontext = plt.inkLight,
      picker = plt.fadeMid,
      scrollbar = plt.inkLight,
      selection = plt.goldDeep,
      special = plt.goldBright,
      whitespace = plt.inkMid,
      win_separator = plt.fadeMid,
      yank = plt.goldPulse,
      float = {
        bg = plt.inkDeep,
        bg_border = plt.inkDeep,
        fg = plt.scrollCore,
        fg_border = plt.parchMid,
      },
      pmenu = {
        bg = plt.parchMid,
        bg_border = plt.parchMid,
        bg_sbar = plt.parchMid,
        bg_sel = plt.parchDeep,
        bg_thumb = plt.fadeMid,
        fg = plt.scrollCore,
        fg_border = plt.parchMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.inkVoid,
        bg_alternate = plt.inkVoid,
        bg_inactive = plt.inkVoid,
        bg_selected = plt.parchMid,
        fg_alternate = plt.fadeBright,
        fg_inactive = plt.fadeLighter,
        fg_selected = plt.scrollCore,
        indicator = plt.goldPulse,
      },
    },
    syn = {
      attribute = plt.scrollCore,
      boolean = plt.goldBright,
      comment = plt.fadeBright,
      constant = plt.fadeLightest,
      deprecated = plt.fadeMid,
      func = plt.scrollBright,
      identifier = plt.scrollCore,
      keyword = plt.scrollCore,
      method = plt.scrollBright,
      number = plt.fadeLightest,
      operator = plt.fadeMid,
      parameter = plt.fadeLighter,
      preproc = plt.goldMid,
      punct = plt.fadeDeep,
      regex = plt.fadeMid,
      special = plt.goldPulse,
      special2 = plt.goldMid,
      special3 = plt.goldBright,
      statement = plt.scrollCore,
      string = plt.fadeLighter,
      symbol = plt.scrollCore,
      type = plt.fadeLightest,
      variable = plt.scrollCore,
    },
    diag = {
      error = plt.goldBright,
      hint = plt.fadeMid,
      info = plt.scrollCore,
      ok = plt.fadeLighter,
      virtual_text_error = plt.goldBright,
      virtual_text_hint = plt.fadeMid,
      virtual_text_info = plt.scrollCore,
      virtual_text_ok = plt.fadeLighter,
      virtual_text_warning = plt.goldPulse,
      warning = plt.goldPulse,
    },
    diff = {
      add = plt.fadeLighter,
      add_inline = plt.fadeDeep,
      change = plt.fadeDeep,
      change_inline = plt.parchDeep,
      delete = plt.goldBright,
      delete_inline = plt.goldDeep,
      text = plt.goldMid,
    },
    vcs = {
      added = plt.fadeLighter,
      changed = plt.goldDeep,
      removed = plt.goldBright,
    },
    term = {
      black = plt.inkVoid,
      black_bright = color(plt.inkVoid):brighten(0.4):to_hex(),
      blue = plt.inkVoid,
      blue_bright = color(plt.inkVoid):brighten(0.2):to_hex(),
      cyan = plt.fadeMid,
      cyan_bright = color(plt.fadeMid):brighten(0.3):to_hex(),
      green = plt.fadeBright,
      green_bright = color(plt.fadeBright):brighten(0.3):to_hex(),
      indexed1 = plt.fadeLighter,
      indexed2 = plt.fadeBright,
      magenta = plt.scrollCore,
      magenta_bright = color(plt.scrollCore):brighten(0.4):to_hex(),
      red = plt.goldBright,
      red_bright = plt.goldPulse,
      white = plt.scrollBright,
      white_bright = plt.scrollBright,
      yellow = plt.fadeLightest,
      yellow_bright = plt.scrollBright,
    },
  }
end

return {
  name = "Detox: Ink",
  author = "PrismPunk.nvim",
  description = "Old parchment spilled ink. Calligraphic history. Faded gold documentation. Literary nostalgia.",
  base16 = {
    base00 = palette.inkVoid,
    base01 = palette.inkDark,
    base02 = palette.inkDeep,
    base03 = palette.inkMid,
    base04 = palette.fadeBright,
    base05 = palette.fadeLightest,
    base06 = palette.scrollCore,
    base07 = palette.scrollBright,
    base08 = palette.goldBright,
    base09 = palette.goldMid,
    base0A = palette.goldDeep,
    base0B = palette.fadeLighter,
    base0C = palette.goldPulse,
    base0D = palette.fadeMid,
    base0E = palette.goldPulse,
    base0F = palette.fadeMid,
  },
  palette = palette,
  get = M.get,
}
