local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.linen")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.fabricCore,
      insert = plt.threadLighter,
      normal = plt.threadBright,
      replace = plt.threadMid,
      visual = plt.shadowPulse,
    },
    accent = {
      accent1 = plt.fabricBright,
      accent2 = plt.fabricCore,
      accent3 = plt.threadLighter,
      accent4 = plt.threadBright,
      accent5 = plt.shadowPulse,
      invert = plt.weaveMid,
    },
    rainbow = {
      rainbow1 = plt.threadBright,
      rainbow2 = plt.threadMid,
      rainbow3 = plt.threadDeep,
      rainbow4 = plt.weaveDeep,
      rainbow5 = plt.fabricCore,
      rainbow6 = plt.fabricBright,
      rainbow7 = plt.shadowPulse,
    },
    ui = {
      bg = plt.linenVoid,
      bg_cursorline = plt.weaveLine,
      bg_dim = plt.linenVoid,
      bg_gutter = opts.gutter and plt.linenMid or "none",
      bg_highlight = plt.weaveDeep,
      bg_m1 = plt.linenDark,
      bg_m2 = plt.linenDeep,
      bg_m3 = plt.linenMid,
      bg_m4 = plt.linenLight,
      bg_p1 = plt.linenDeep,
      bg_p2 = plt.linenMid,
      bg_search = plt.shadowPulse,
      bg_statusline = plt.weaveMid,
      bg_visual = plt.shadowDeep,
      border = plt.threadMid,
      cursorline = plt.weaveLine,
      fg = plt.fabricCore,
      fg_dark = plt.threadMid,
      fg_dim = plt.fabricCore,
      fg_dimmer = plt.threadLighter,
      fg_reverse = plt.linenVoid,
      header1 = plt.fabricBright,
      header2 = plt.fabricCore,
      indent = plt.linenMid,
      indent_scope = plt.threadDeep,
      line_nr = plt.threadMid,
      line_nr_active = plt.fabricCore,
      line_nr_dim = plt.threadBright,
      mark = plt.shadowBright,
      nontext = plt.linenLight,
      picker = plt.threadMid,
      scrollbar = plt.linenLight,
      selection = plt.shadowDeep,
      special = plt.shadowBright,
      whitespace = plt.linenMid,
      win_separator = plt.threadMid,
      yank = plt.shadowPulse,
      float = {
        bg = plt.linenDeep,
        bg_border = plt.linenDeep,
        fg = plt.fabricCore,
        fg_border = plt.weaveMid,
      },
      pmenu = {
        bg = plt.weaveMid,
        bg_border = plt.weaveMid,
        bg_sbar = plt.weaveMid,
        bg_sel = plt.weaveDeep,
        bg_thumb = plt.threadMid,
        fg = plt.fabricCore,
        fg_border = plt.weaveMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.linenVoid,
        bg_alternate = plt.linenVoid,
        bg_inactive = plt.linenVoid,
        bg_selected = plt.weaveMid,
        fg_alternate = plt.threadBright,
        fg_inactive = plt.threadLighter,
        fg_selected = plt.fabricCore,
        indicator = plt.shadowPulse,
      },
    },
    syn = {
      attribute = plt.fabricCore,
      boolean = plt.shadowBright,
      comment = plt.threadBright,
      constant = plt.threadLightest,
      deprecated = plt.threadMid,
      func = plt.fabricBright,
      identifier = plt.fabricCore,
      keyword = plt.fabricCore,
      method = plt.fabricBright,
      number = plt.threadLightest,
      operator = plt.threadMid,
      parameter = plt.threadLighter,
      preproc = plt.shadowMid,
      punct = plt.threadDeep,
      regex = plt.threadMid,
      special = plt.shadowPulse,
      special2 = plt.shadowMid,
      special3 = plt.shadowBright,
      statement = plt.fabricCore,
      string = plt.threadLighter,
      symbol = plt.fabricCore,
      type = plt.threadLightest,
      variable = plt.fabricCore,
    },
    diag = {
      error = plt.shadowBright,
      hint = plt.threadMid,
      info = plt.fabricCore,
      ok = plt.threadLighter,
      virtual_text_error = plt.shadowBright,
      virtual_text_hint = plt.threadMid,
      virtual_text_info = plt.fabricCore,
      virtual_text_ok = plt.threadLighter,
      virtual_text_warning = plt.shadowPulse,
      warning = plt.shadowPulse,
    },
    diff = {
      add = plt.threadLighter,
      add_inline = plt.threadDeep,
      change = plt.threadDeep,
      change_inline = plt.weaveDeep,
      delete = plt.shadowBright,
      delete_inline = plt.shadowDeep,
      text = plt.shadowMid,
    },
    vcs = {
      added = plt.threadLighter,
      changed = plt.shadowDeep,
      removed = plt.shadowBright,
    },
    term = {
      black = plt.linenVoid,
      black_bright = color(plt.linenVoid):brighten(0.4):to_hex(),
      blue = plt.linenVoid,
      blue_bright = color(plt.linenVoid):brighten(0.2):to_hex(),
      cyan = plt.threadMid,
      cyan_bright = color(plt.threadMid):brighten(0.3):to_hex(),
      green = plt.threadBright,
      green_bright = color(plt.threadBright):brighten(0.3):to_hex(),
      indexed1 = plt.threadLighter,
      indexed2 = plt.threadBright,
      magenta = plt.fabricCore,
      magenta_bright = color(plt.fabricCore):brighten(0.4):to_hex(),
      red = plt.shadowBright,
      red_bright = plt.shadowPulse,
      white = plt.fabricBright,
      white_bright = plt.fabricBright,
      yellow = plt.threadLightest,
      yellow_bright = plt.fabricBright,
    },
  }
end

return {
  name = "Detox: Linen",
  author = "PrismPunk.nvim",
  description = "Natural unbleached fabric. Warm off-whites. Thread shadow contrast. Textile comfort.",
  base16 = {
    base00 = palette.linenVoid,
    base01 = palette.linenDark,
    base02 = palette.linenDeep,
    base03 = palette.linenMid,
    base04 = palette.threadBright,
    base05 = palette.threadLightest,
    base06 = palette.fabricCore,
    base07 = palette.fabricBright,
    base08 = palette.shadowBright,
    base09 = palette.shadowMid,
    base0A = palette.shadowDeep,
    base0B = palette.threadLighter,
    base0C = palette.shadowPulse,
    base0D = palette.threadMid,
    base0E = palette.shadowPulse,
    base0F = palette.threadMid,
  },
  palette = palette,
  get = M.get,
}
