local color = require("prismpunk.utils.color")

local palette = {
  arsenicGrey = "#505A64",
  bloodDrop = "#4F3238",
  chromeMuted = "#6A7480",
  dropRedBright = "#402C35",
  dropRedDeep = "#2A1815",
  dropRedDim = "#241412",
  dropRedMid = "#35201F",
  dropRedPulse = "#4A3640",
  dropletBright = "#606A78",
  dropletDeep = "#4A5258",
  dropletLighter = "#6B7588",
  dropletLightest = "#7A8498",
  dropletMid = "#555F68",
  frostMetal = "#B8C8D8",
  liquidDeep = "#32383C",
  liquidLine = "#42484C",
  liquidMid = "#3A4044",
  mercuryDark = "#121618",
  mercuryDeep = "#1A1F24",
  mercuryDim = "#0E1113",
  mercuryLight = "#2A3034",
  mercuryMid = "#22282C",
  mercuryVoid = "#0A0C0F",
  metalSheen = "#A8B8C8",
  platinumPale = "#D0E0F0",
  poisonBright = "#DDE8F8",
  poisonCore = "#C8D8E8",
  quicksilver = "#909FAE",
  reflectCool = "#7F8F9E",
  shimmerSteel = "#959FAC",
  silverFlow = "#8595A5",
  steelLiquid = "#5A6470",
  surfaceTension = "#4E5864",
  toxicHaze = "#3E4448",
  vaporCold = "#E8F0F8",
  vermilionDim = "#553844",
  vialGlass = "#36404C",
  viscousMetal = "#465058",
  zenithQuicksilver = "#F0F8FF",
  zincPure = "#758595",

  bg_darkest = "#0A0C0F",
  fg_lightest = "#DDE8F8",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.poisonCore,
      insert = plt.dropletLighter,
      normal = plt.dropletBright,
      replace = plt.dropletMid,
      visual = plt.dropRedPulse,
    },
    accent = {
      accent1 = plt.poisonBright,
      accent2 = plt.poisonCore,
      accent3 = plt.dropletLighter,
      accent4 = plt.dropletBright,
      accent5 = plt.dropRedPulse,
      invert = plt.liquidMid,
    },
    rainbow = {
      rainbow1 = plt.dropletBright,
      rainbow2 = plt.dropletMid,
      rainbow3 = plt.dropletDeep,
      rainbow4 = plt.liquidDeep,
      rainbow5 = plt.poisonCore,
      rainbow6 = plt.poisonBright,
      rainbow7 = plt.dropRedPulse,
    },
    ui = {
      bg = plt.mercuryVoid,
      bg_cursorline = plt.liquidLine,
      bg_dim = plt.mercuryVoid,
      bg_gutter = opts.gutter and plt.mercuryMid or "none",
      bg_highlight = plt.liquidDeep,
      bg_m1 = plt.mercuryDark,
      bg_m2 = plt.mercuryDeep,
      bg_m3 = plt.mercuryMid,
      bg_m4 = plt.mercuryLight,
      bg_p1 = plt.mercuryDeep,
      bg_p2 = plt.mercuryMid,
      bg_search = plt.dropRedPulse,
      bg_statusline = plt.liquidMid,
      bg_visual = plt.dropRedDeep,
      border = plt.dropletMid,
      cursorline = plt.liquidLine,
      fg = plt.poisonCore,
      fg_dark = plt.dropletMid,
      fg_dim = plt.poisonCore,
      fg_dimmer = plt.dropletLighter,
      fg_reverse = plt.mercuryVoid,
      header1 = plt.poisonBright,
      header2 = plt.poisonCore,
      indent = plt.mercuryMid,
      indent_scope = plt.dropletDeep,
      line_nr = plt.dropletMid,
      line_nr_active = plt.poisonCore,
      line_nr_dim = plt.dropletBright,
      mark = plt.dropRedBright,
      nontext = plt.mercuryLight,
      picker = plt.dropletMid,
      scrollbar = plt.mercuryLight,
      selection = plt.dropRedDeep,
      special = plt.dropRedBright,
      whitespace = plt.mercuryMid,
      win_separator = plt.dropletMid,
      yank = plt.dropRedPulse,
      float = {
        bg = plt.mercuryDeep,
        bg_border = plt.mercuryDeep,
        fg = plt.poisonCore,
        fg_border = plt.liquidMid,
      },
      pmenu = {
        bg = plt.liquidMid,
        bg_border = plt.liquidMid,
        bg_sbar = plt.liquidMid,
        bg_sel = plt.liquidDeep,
        bg_thumb = plt.dropletMid,
        fg = plt.poisonCore,
        fg_border = plt.liquidMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.mercuryVoid,
        bg_alternate = plt.mercuryVoid,
        bg_inactive = plt.mercuryVoid,
        bg_selected = plt.liquidMid,
        fg_alternate = plt.dropletBright,
        fg_inactive = plt.dropletLighter,
        fg_selected = plt.poisonCore,
        indicator = plt.dropRedPulse,
      },
    },
    syn = {
      attribute = plt.poisonCore,
      boolean = plt.dropRedBright,
      comment = plt.dropletBright,
      constant = plt.dropletLightest,
      deprecated = plt.dropletMid,
      func = plt.poisonBright,
      identifier = plt.poisonCore,
      keyword = plt.poisonCore,
      method = plt.poisonBright,
      number = plt.dropletLightest,
      operator = plt.dropletMid,
      parameter = plt.dropletLighter,
      preproc = plt.dropRedMid,
      punct = plt.dropletDeep,
      regex = plt.dropletMid,
      special = plt.dropRedPulse,
      special2 = plt.dropRedMid,
      special3 = plt.dropRedBright,
      statement = plt.poisonCore,
      string = plt.dropletLighter,
      symbol = plt.poisonCore,
      type = plt.dropletLightest,
      variable = plt.poisonCore,
    },
    diag = {
      error = plt.dropRedBright,
      hint = plt.dropletMid,
      info = plt.poisonCore,
      ok = plt.dropletLighter,
      virtual_text_error = plt.dropRedBright,
      virtual_text_hint = plt.dropletMid,
      virtual_text_info = plt.poisonCore,
      virtual_text_ok = plt.dropletLighter,
      virtual_text_warning = plt.dropRedPulse,
      warning = plt.dropRedPulse,
    },
    diff = {
      add = plt.dropletLighter,
      add_inline = plt.dropletDeep,
      change = plt.dropletDeep,
      change_inline = plt.liquidDeep,
      delete = plt.dropRedBright,
      delete_inline = plt.dropRedDeep,
      text = plt.dropRedMid,
    },
    vcs = {
      added = plt.dropletLighter,
      changed = plt.dropRedDeep,
      removed = plt.dropRedBright,
    },
    term = {
      black = plt.mercuryVoid,
      black_bright = color(plt.mercuryVoid):brighten(0.4):to_hex(),
      blue = plt.mercuryVoid,
      blue_bright = color(plt.mercuryVoid):brighten(0.2):to_hex(),
      cyan = plt.dropletMid,
      cyan_bright = color(plt.dropletMid):brighten(0.3):to_hex(),
      green = plt.dropletBright,
      green_bright = color(plt.dropletBright):brighten(0.3):to_hex(),
      indexed1 = plt.dropletLighter,
      indexed2 = plt.dropletBright,
      magenta = plt.poisonCore,
      magenta_bright = color(plt.poisonCore):brighten(0.4):to_hex(),
      red = plt.dropRedBright,
      red_bright = plt.dropRedPulse,
      white = plt.poisonBright,
      white_bright = plt.poisonBright,
      yellow = plt.dropletLightest,
      yellow_bright = plt.poisonBright,
    },
  }
end

return {
  name = "Detox: Mercury",
  author = "PrismPunk.nvim",
  description = "Toxic liquid metal beauty. Cold silvers. Red droplet danger. Instable precision.",
  base16 = {
    base00 = palette.mercuryVoid,
    base01 = palette.mercuryDark,
    base02 = palette.mercuryDeep,
    base03 = palette.mercuryMid,
    base04 = palette.dropletBright,
    base05 = palette.dropletLightest,
    base06 = palette.poisonCore,
    base07 = palette.poisonBright,
    base08 = palette.dropRedBright,
    base09 = palette.dropRedMid,
    base0A = palette.dropRedDeep,
    base0B = palette.dropletLighter,
    base0C = palette.dropRedPulse,
    base0D = palette.dropletMid,
    base0E = palette.dropRedPulse,
    base0F = palette.dropletMid,
  },
  palette = palette,
  get = M.get,
}
