local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.moss")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.stillCore,
      insert = plt.leafLighter,
      normal = plt.leafBright,
      replace = plt.leafMid,
      visual = plt.glowPulse,
    },
    accent = {
      accent1 = plt.stillBright,
      accent2 = plt.stillCore,
      accent3 = plt.leafLighter,
      accent4 = plt.leafBright,
      accent5 = plt.glowPulse,
      invert = plt.greenMid,
    },
    rainbow = {
      rainbow1 = plt.leafBright,
      rainbow2 = plt.leafMid,
      rainbow3 = plt.leafDeep,
      rainbow4 = plt.greenDeep,
      rainbow5 = plt.stillCore,
      rainbow6 = plt.stillBright,
      rainbow7 = plt.glowPulse,
    },
    ui = {
      bg = plt.mossVoid,
      bg_cursorline = plt.greenLine,
      bg_dim = plt.mossVoid,
      bg_gutter = opts.gutter and plt.mossMid or "none",
      bg_highlight = plt.greenDeep,
      bg_m1 = plt.mossDark,
      bg_m2 = plt.mossDeep,
      bg_m3 = plt.mossMid,
      bg_m4 = plt.mossLight,
      bg_p1 = plt.mossDeep,
      bg_p2 = plt.mossMid,
      bg_search = plt.glowPulse,
      bg_statusline = plt.greenMid,
      bg_visual = plt.glowDeep,
      border = plt.leafMid,
      cursorline = plt.greenLine,
      fg = plt.stillCore,
      fg_dark = plt.leafMid,
      fg_dim = plt.stillCore,
      fg_dimmer = plt.leafLighter,
      fg_reverse = plt.mossVoid,
      header1 = plt.stillBright,
      header2 = plt.stillCore,
      indent = plt.mossMid,
      indent_scope = plt.leafDeep,
      line_nr = plt.leafMid,
      line_nr_active = plt.stillCore,
      line_nr_dim = plt.leafBright,
      mark = plt.glowBright,
      nontext = plt.mossLight,
      picker = plt.leafMid,
      scrollbar = plt.mossLight,
      selection = plt.glowDeep,
      special = plt.glowBright,
      whitespace = plt.mossMid,
      win_separator = plt.leafMid,
      yank = plt.glowPulse,
      float = {
        bg = plt.mossDeep,
        bg_border = plt.mossDeep,
        fg = plt.stillCore,
        fg_border = plt.greenMid,
      },
      pmenu = {
        bg = plt.greenMid,
        bg_border = plt.greenMid,
        bg_sbar = plt.greenMid,
        bg_sel = plt.greenDeep,
        bg_thumb = plt.leafMid,
        fg = plt.stillCore,
        fg_border = plt.greenMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.mossVoid,
        bg_alternate = plt.mossVoid,
        bg_inactive = plt.mossVoid,
        bg_selected = plt.greenMid,
        fg_alternate = plt.leafBright,
        fg_inactive = plt.leafLighter,
        fg_selected = plt.stillCore,
        indicator = plt.glowPulse,
      },
    },
    syn = {
      attribute = plt.stillCore,
      boolean = plt.glowBright,
      comment = plt.leafBright,
      constant = plt.leafLightest,
      deprecated = plt.leafMid,
      func = plt.stillBright,
      identifier = plt.stillCore,
      keyword = plt.stillCore,
      method = plt.stillBright,
      number = plt.leafLightest,
      operator = plt.leafMid,
      parameter = plt.leafLighter,
      preproc = plt.glowMid,
      punct = plt.leafDeep,
      regex = plt.leafMid,
      special = plt.glowPulse,
      special2 = plt.glowMid,
      special3 = plt.glowBright,
      statement = plt.stillCore,
      string = plt.leafLighter,
      symbol = plt.stillCore,
      type = plt.leafLightest,
      variable = plt.stillCore,
    },
    diag = {
      error = plt.glowBright,
      hint = plt.leafMid,
      info = plt.stillCore,
      ok = plt.leafLighter,
      virtual_text_error = plt.glowBright,
      virtual_text_hint = plt.leafMid,
      virtual_text_info = plt.stillCore,
      virtual_text_ok = plt.leafLighter,
      virtual_text_warning = plt.glowPulse,
      warning = plt.glowPulse,
    },
    diff = {
      add = plt.leafLighter,
      add_inline = plt.leafDeep,
      change = plt.leafDeep,
      change_inline = plt.greenDeep,
      delete = plt.glowBright,
      delete_inline = plt.glowDeep,
      text = plt.glowMid,
    },
    vcs = {
      added = plt.leafLighter,
      changed = plt.glowDeep,
      removed = plt.glowBright,
    },
    term = {
      black = plt.mossVoid,
      black_bright = color(plt.mossVoid):brighten(0.4):to_hex(),
      blue = plt.mossVoid,
      blue_bright = color(plt.mossVoid):brighten(0.2):to_hex(),
      cyan = plt.leafMid,
      cyan_bright = color(plt.leafMid):brighten(0.3):to_hex(),
      green = plt.leafBright,
      green_bright = color(plt.leafBright):brighten(0.3):to_hex(),
      indexed1 = plt.leafLighter,
      indexed2 = plt.leafBright,
      magenta = plt.stillCore,
      magenta_bright = color(plt.stillCore):brighten(0.4):to_hex(),
      red = plt.glowBright,
      red_bright = plt.glowPulse,
      white = plt.stillBright,
      white_bright = plt.stillBright,
      yellow = plt.leafLightest,
      yellow_bright = plt.stillBright,
    },
  }
end

return {
  name = "Detox: Moss",
  author = "PrismPunk.nvim",
  description = "Forest floor living decay. Deep green primary. Pale mushroom glow. Organic patience.",
  base16 = {
    base00 = palette.mossVoid,
    base01 = palette.mossDark,
    base02 = palette.mossDeep,
    base03 = palette.mossMid,
    base04 = palette.leafBright,
    base05 = palette.leafLightest,
    base06 = palette.stillCore,
    base07 = palette.stillBright,
    base08 = palette.glowBright,
    base09 = palette.glowMid,
    base0A = palette.glowDeep,
    base0B = palette.leafLighter,
    base0C = palette.glowPulse,
    base0D = palette.leafMid,
    base0E = palette.glowPulse,
    base0F = palette.leafMid,
  },
  palette = palette,
  get = M.get,
}
