local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.moth")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.moonCore,
      insert = plt.dustLighter,
      normal = plt.dustBright,
      replace = plt.dustMid,
      visual = plt.lampPulse,
    },
    accent = {
      accent1 = plt.moonBright,
      accent2 = plt.moonCore,
      accent3 = plt.dustLighter,
      accent4 = plt.dustBright,
      accent5 = plt.lampPulse,
      invert = plt.silverMid,
    },
    rainbow = {
      rainbow1 = plt.dustBright,
      rainbow2 = plt.dustMid,
      rainbow3 = plt.dustDeep,
      rainbow4 = plt.silverDeep,
      rainbow5 = plt.moonCore,
      rainbow6 = plt.moonBright,
      rainbow7 = plt.lampPulse,
    },
    ui = {
      bg = plt.nightVoid,
      bg_cursorline = plt.silverLine,
      bg_dim = plt.nightVoid,
      bg_gutter = opts.gutter and plt.nightMid or "none",
      bg_highlight = plt.silverDeep,
      bg_m1 = plt.nightDark,
      bg_m2 = plt.nightDeep,
      bg_m3 = plt.nightMid,
      bg_m4 = plt.nightLight,
      bg_p1 = plt.nightDeep,
      bg_p2 = plt.nightMid,
      bg_search = plt.lampPulse,
      bg_statusline = plt.silverMid,
      bg_visual = plt.lampDeep,
      border = plt.dustMid,
      cursorline = plt.silverLine,
      fg = plt.moonCore,
      fg_dark = plt.dustMid,
      fg_dim = plt.moonCore,
      fg_dimmer = plt.dustLighter,
      fg_reverse = plt.nightVoid,
      header1 = plt.moonBright,
      header2 = plt.moonCore,
      indent = plt.nightMid,
      indent_scope = plt.dustDeep,
      line_nr = plt.dustMid,
      line_nr_active = plt.moonCore,
      line_nr_dim = plt.dustBright,
      mark = plt.lampBright,
      nontext = plt.nightLight,
      picker = plt.dustMid,
      scrollbar = plt.nightLight,
      selection = plt.lampDeep,
      special = plt.lampBright,
      whitespace = plt.nightMid,
      win_separator = plt.dustMid,
      yank = plt.lampPulse,
      float = {
        bg = plt.nightDeep,
        bg_border = plt.nightDeep,
        fg = plt.moonCore,
        fg_border = plt.silverMid,
      },
      pmenu = {
        bg = plt.silverMid,
        bg_border = plt.silverMid,
        bg_sbar = plt.silverMid,
        bg_sel = plt.silverDeep,
        bg_thumb = plt.dustMid,
        fg = plt.moonCore,
        fg_border = plt.silverMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.nightVoid,
        bg_alternate = plt.nightVoid,
        bg_inactive = plt.nightVoid,
        bg_selected = plt.silverMid,
        fg_alternate = plt.dustBright,
        fg_inactive = plt.dustLighter,
        fg_selected = plt.moonCore,
        indicator = plt.lampPulse,
      },
    },
    syn = {
      attribute = plt.moonCore,
      boolean = plt.lampBright,
      comment = plt.dustBright,
      constant = plt.dustLightest,
      deprecated = plt.dustMid,
      func = plt.moonBright,
      identifier = plt.moonCore,
      keyword = plt.moonCore,
      method = plt.moonBright,
      number = plt.dustLightest,
      operator = plt.dustMid,
      parameter = plt.dustLighter,
      preproc = plt.lampMid,
      punct = plt.dustDeep,
      regex = plt.dustMid,
      special = plt.lampPulse,
      special2 = plt.lampMid,
      special3 = plt.lampBright,
      statement = plt.moonCore,
      string = plt.dustLighter,
      symbol = plt.moonCore,
      type = plt.dustLightest,
      variable = plt.moonCore,
    },
    diag = {
      error = plt.lampBright,
      hint = plt.dustMid,
      info = plt.moonCore,
      ok = plt.dustLighter,
      virtual_text_error = plt.lampBright,
      virtual_text_hint = plt.dustMid,
      virtual_text_info = plt.moonCore,
      virtual_text_ok = plt.dustLighter,
      virtual_text_warning = plt.lampPulse,
      warning = plt.lampPulse,
    },
    diff = {
      add = plt.dustLighter,
      add_inline = plt.dustDeep,
      change = plt.dustDeep,
      change_inline = plt.silverDeep,
      delete = plt.lampBright,
      delete_inline = plt.lampDeep,
      text = plt.lampMid,
    },
    vcs = {
      added = plt.dustLighter,
      changed = plt.lampDeep,
      removed = plt.lampBright,
    },
    term = {
      black = plt.nightVoid,
      black_bright = color(plt.nightVoid):brighten(0.4):to_hex(),
      blue = plt.nightVoid,
      blue_bright = color(plt.nightVoid):brighten(0.2):to_hex(),
      cyan = plt.dustMid,
      cyan_bright = color(plt.dustMid):brighten(0.3):to_hex(),
      green = plt.dustBright,
      green_bright = color(plt.dustBright):brighten(0.3):to_hex(),
      indexed1 = plt.dustLighter,
      indexed2 = plt.dustBright,
      magenta = plt.moonCore,
      magenta_bright = color(plt.moonCore):brighten(0.4):to_hex(),
      red = plt.lampBright,
      red_bright = plt.lampPulse,
      white = plt.moonBright,
      white_bright = plt.moonBright,
      yellow = plt.dustLightest,
      yellow_bright = plt.moonBright,
    },
  }
end

return {
  name = "Detox: Moth",
  author = "PrismPunk.nvim",
  description = "Nocturnal pale blues. Moonlit silvers. Soft lamplight warmth. Night-adapted focus. Gentle darkness.",
  base16 = {
    base00 = palette.nightVoid,
    base01 = palette.nightDark,
    base02 = palette.nightDeep,
    base03 = palette.nightMid,
    base04 = palette.dustBright,
    base05 = palette.dustLightest,
    base06 = palette.moonCore,
    base07 = palette.moonBright,
    base08 = palette.lampBright,
    base09 = palette.lampMid,
    base0A = palette.lampDeep,
    base0B = palette.dustLighter,
    base0C = palette.lampPulse,
    base0D = palette.dustMid,
    base0E = palette.lampPulse,
    base0F = palette.dustMid,
  },
  palette = palette,
  get = M.get,
}
