local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.mute")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.whisperCore,
      insert = plt.muteLighter,
      normal = plt.muteBright,
      replace = plt.muteMid,
      visual = plt.hushPulse,
    },
    accent = {
      accent1 = plt.whisperBright,
      accent2 = plt.whisperCore,
      accent3 = plt.muteLighter,
      accent4 = plt.muteBright,
      accent5 = plt.hushPulse,
      invert = plt.dampMid,
    },
    rainbow = {
      rainbow1 = plt.muteBright,
      rainbow2 = plt.muteMid,
      rainbow3 = plt.muteDeep,
      rainbow4 = plt.dampDeep,
      rainbow5 = plt.whisperCore,
      rainbow6 = plt.whisperBright,
      rainbow7 = plt.hushPulse,
    },
    ui = {
      bg = plt.quietVoid,
      bg_cursorline = plt.dampLine,
      bg_dim = plt.quietVoid,
      bg_gutter = opts.gutter and plt.quietMid or "none",
      bg_highlight = plt.dampDeep,
      bg_m1 = plt.quietDark,
      bg_m2 = plt.quietDeep,
      bg_m3 = plt.quietMid,
      bg_m4 = plt.quietLight,
      bg_p1 = plt.quietDeep,
      bg_p2 = plt.quietMid,
      bg_search = plt.hushPulse,
      bg_statusline = plt.dampMid,
      bg_visual = plt.hushDeep,
      border = plt.muteMid,
      cursorline = plt.dampLine,
      fg = plt.whisperCore,
      fg_dark = plt.muteMid,
      fg_dim = plt.whisperCore,
      fg_dimmer = plt.muteLighter,
      fg_reverse = plt.quietVoid,
      header1 = plt.whisperBright,
      header2 = plt.whisperCore,
      indent = plt.quietMid,
      indent_scope = plt.muteDeep,
      line_nr = plt.muteMid,
      line_nr_active = plt.whisperCore,
      line_nr_dim = plt.muteBright,
      mark = plt.hushBright,
      nontext = plt.quietLight,
      picker = plt.muteMid,
      scrollbar = plt.quietLight,
      selection = plt.hushDeep,
      special = plt.hushBright,
      whitespace = plt.quietMid,
      win_separator = plt.muteMid,
      yank = plt.hushPulse,
      float = {
        bg = plt.quietDeep,
        bg_border = plt.quietDeep,
        fg = plt.whisperCore,
        fg_border = plt.dampMid,
      },
      pmenu = {
        bg = plt.dampMid,
        bg_border = plt.dampMid,
        bg_sbar = plt.dampMid,
        bg_sel = plt.dampDeep,
        bg_thumb = plt.muteMid,
        fg = plt.whisperCore,
        fg_border = plt.dampMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.quietVoid,
        bg_alternate = plt.quietVoid,
        bg_inactive = plt.quietVoid,
        bg_selected = plt.dampMid,
        fg_alternate = plt.muteBright,
        fg_inactive = plt.muteLighter,
        fg_selected = plt.whisperCore,
        indicator = plt.hushPulse,
      },
    },
    syn = {
      attribute = plt.whisperCore,
      boolean = plt.hushBright,
      comment = plt.muteBright,
      constant = plt.muteLightest,
      deprecated = plt.muteMid,
      func = plt.whisperBright,
      identifier = plt.whisperCore,
      keyword = plt.whisperCore,
      method = plt.whisperBright,
      number = plt.muteLightest,
      operator = plt.muteMid,
      parameter = plt.muteLighter,
      preproc = plt.hushMid,
      punct = plt.muteDeep,
      regex = plt.muteMid,
      special = plt.hushPulse,
      special2 = plt.hushMid,
      special3 = plt.hushBright,
      statement = plt.whisperCore,
      string = plt.muteLighter,
      symbol = plt.whisperCore,
      type = plt.muteLightest,
      variable = plt.whisperCore,
    },
    diag = {
      error = plt.hushBright,
      hint = plt.muteMid,
      info = plt.whisperCore,
      ok = plt.muteLighter,
      virtual_text_error = plt.hushBright,
      virtual_text_hint = plt.muteMid,
      virtual_text_info = plt.whisperCore,
      virtual_text_ok = plt.muteLighter,
      virtual_text_warning = plt.hushPulse,
      warning = plt.hushPulse,
    },
    diff = {
      add = plt.muteLighter,
      add_inline = plt.muteDeep,
      change = plt.muteDeep,
      change_inline = plt.dampDeep,
      delete = plt.hushBright,
      delete_inline = plt.hushDeep,
      text = plt.hushMid,
    },
    vcs = {
      added = plt.muteLighter,
      changed = plt.hushDeep,
      removed = plt.hushBright,
    },
    term = {
      black = plt.quietVoid,
      black_bright = color(plt.quietVoid):brighten(0.4):to_hex(),
      blue = plt.quietVoid,
      blue_bright = color(plt.quietVoid):brighten(0.2):to_hex(),
      cyan = plt.muteMid,
      cyan_bright = color(plt.muteMid):brighten(0.3):to_hex(),
      green = plt.muteBright,
      green_bright = color(plt.muteBright):brighten(0.3):to_hex(),
      indexed1 = plt.muteLighter,
      indexed2 = plt.muteBright,
      magenta = plt.whisperCore,
      magenta_bright = color(plt.whisperCore):brighten(0.4):to_hex(),
      red = plt.hushBright,
      red_bright = plt.hushPulse,
      white = plt.whisperBright,
      white_bright = plt.whisperBright,
      yellow = plt.muteLightest,
      yellow_bright = plt.whisperBright,
    },
  }
end

return {
  name = "Detox: Mute",
  author = "PrismPunk.nvim",
  description = "Soundless silence. Barely-distinguishable grays. Single whispered accent. Extreme minimalism.",
  base16 = {
    base00 = palette.quietVoid,
    base01 = palette.quietDark,
    base02 = palette.quietDeep,
    base03 = palette.quietMid,
    base04 = palette.muteBright,
    base05 = palette.muteLightest,
    base06 = palette.whisperCore,
    base07 = palette.whisperBright,
    base08 = palette.hushBright,
    base09 = palette.hushMid,
    base0A = palette.hushDeep,
    base0B = palette.muteLighter,
    base0C = palette.hushPulse,
    base0D = palette.muteMid,
    base0E = palette.hushPulse,
    base0F = palette.muteMid,
  },
  palette = palette,
  get = M.get,
}
