local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.paper")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.pageCore,
      insert = plt.sheetLighter,
      normal = plt.sheetBright,
      replace = plt.sheetMid,
      visual = plt.inkPulse,
    },
    accent = {
      accent1 = plt.pageBright,
      accent2 = plt.pageCore,
      accent3 = plt.sheetLighter,
      accent4 = plt.sheetBright,
      accent5 = plt.inkPulse,
      invert = plt.pulpMid,
    },
    rainbow = {
      rainbow1 = plt.sheetBright,
      rainbow2 = plt.sheetMid,
      rainbow3 = plt.sheetDeep,
      rainbow4 = plt.pulpDeep,
      rainbow5 = plt.pageCore,
      rainbow6 = plt.pageBright,
      rainbow7 = plt.inkPulse,
    },
    ui = {
      bg = plt.paperVoid,
      bg_cursorline = plt.pulpLine,
      bg_dim = plt.paperVoid,
      bg_gutter = opts.gutter and plt.paperMid or "none",
      bg_highlight = plt.pulpDeep,
      bg_m1 = plt.paperDark,
      bg_m2 = plt.paperDeep,
      bg_m3 = plt.paperMid,
      bg_m4 = plt.paperLight,
      bg_p1 = plt.paperDeep,
      bg_p2 = plt.paperMid,
      bg_search = plt.inkPulse,
      bg_statusline = plt.pulpMid,
      bg_visual = plt.inkDeep,
      border = plt.sheetMid,
      cursorline = plt.pulpLine,
      fg = plt.pageCore,
      fg_dark = plt.sheetMid,
      fg_dim = plt.pageCore,
      fg_dimmer = plt.sheetLighter,
      fg_reverse = plt.paperVoid,
      header1 = plt.pageBright,
      header2 = plt.pageCore,
      indent = plt.paperMid,
      indent_scope = plt.sheetDeep,
      line_nr = plt.sheetMid,
      line_nr_active = plt.pageCore,
      line_nr_dim = plt.sheetBright,
      mark = plt.inkBright,
      nontext = plt.paperLight,
      picker = plt.sheetMid,
      scrollbar = plt.paperLight,
      selection = plt.inkDeep,
      special = plt.inkBright,
      whitespace = plt.paperMid,
      win_separator = plt.sheetMid,
      yank = plt.inkPulse,
      float = {
        bg = plt.paperDeep,
        bg_border = plt.paperDeep,
        fg = plt.pageCore,
        fg_border = plt.pulpMid,
      },
      pmenu = {
        bg = plt.pulpMid,
        bg_border = plt.pulpMid,
        bg_sbar = plt.pulpMid,
        bg_sel = plt.pulpDeep,
        bg_thumb = plt.sheetMid,
        fg = plt.pageCore,
        fg_border = plt.pulpMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.paperVoid,
        bg_alternate = plt.paperVoid,
        bg_inactive = plt.paperVoid,
        bg_selected = plt.pulpMid,
        fg_alternate = plt.sheetBright,
        fg_inactive = plt.sheetLighter,
        fg_selected = plt.pageCore,
        indicator = plt.inkPulse,
      },
    },
    syn = {
      attribute = plt.pageCore,
      boolean = plt.inkBright,
      comment = plt.sheetBright,
      constant = plt.sheetLightest,
      deprecated = plt.sheetMid,
      func = plt.pageBright,
      identifier = plt.pageCore,
      keyword = plt.pageCore,
      method = plt.pageBright,
      number = plt.sheetLightest,
      operator = plt.sheetMid,
      parameter = plt.sheetLighter,
      preproc = plt.inkMid,
      punct = plt.sheetDeep,
      regex = plt.sheetMid,
      special = plt.inkPulse,
      special2 = plt.inkMid,
      special3 = plt.inkBright,
      statement = plt.pageCore,
      string = plt.sheetLighter,
      symbol = plt.pageCore,
      type = plt.sheetLightest,
      variable = plt.pageCore,
    },
    diag = {
      error = plt.inkBright,
      hint = plt.sheetMid,
      info = plt.pageCore,
      ok = plt.sheetLighter,
      virtual_text_error = plt.inkBright,
      virtual_text_hint = plt.sheetMid,
      virtual_text_info = plt.pageCore,
      virtual_text_ok = plt.sheetLighter,
      virtual_text_warning = plt.inkPulse,
      warning = plt.inkPulse,
    },
    diff = {
      add = plt.sheetLighter,
      add_inline = plt.sheetDeep,
      change = plt.sheetDeep,
      change_inline = plt.pulpDeep,
      delete = plt.inkBright,
      delete_inline = plt.inkDeep,
      text = plt.inkMid,
    },
    vcs = {
      added = plt.sheetLighter,
      changed = plt.inkDeep,
      removed = plt.inkBright,
    },
    term = {
      black = plt.paperVoid,
      black_bright = color(plt.paperVoid):brighten(0.4):to_hex(),
      blue = plt.paperVoid,
      blue_bright = color(plt.paperVoid):brighten(0.2):to_hex(),
      cyan = plt.sheetMid,
      cyan_bright = color(plt.sheetMid):brighten(0.3):to_hex(),
      green = plt.sheetBright,
      green_bright = color(plt.sheetBright):brighten(0.3):to_hex(),
      indexed1 = plt.sheetLighter,
      indexed2 = plt.sheetBright,
      magenta = plt.pageCore,
      magenta_bright = color(plt.pageCore):brighten(0.4):to_hex(),
      red = plt.inkBright,
      red_bright = plt.inkPulse,
      white = plt.pageBright,
      white_bright = plt.pageBright,
      yellow = plt.sheetLightest,
      yellow_bright = plt.pageBright,
    },
  }
end

return {
  name = "Detox: Paper",
  author = "PrismPunk.nvim",
  description = "Aged pulp sheets. Cellulose fiber texture. Ink stain marks. Handmade documentation.",
  base16 = {
    base00 = palette.paperVoid,
    base01 = palette.paperDark,
    base02 = palette.paperDeep,
    base03 = palette.paperMid,
    base04 = palette.sheetBright,
    base05 = palette.sheetLightest,
    base06 = palette.pageCore,
    base07 = palette.pageBright,
    base08 = palette.inkBright,
    base09 = palette.inkMid,
    base0A = palette.inkDeep,
    base0B = palette.sheetLighter,
    base0C = palette.inkPulse,
    base0D = palette.sheetMid,
    base0E = palette.inkPulse,
    base0F = palette.sheetMid,
  },
  palette = palette,
  get = M.get,
}
