local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.petal")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.pressCore,
      insert = plt.dustLighter,
      normal = plt.dustBright,
      replace = plt.dustMid,
      visual = plt.stemPulse,
    },
    accent = {
      accent1 = plt.pressBright,
      accent2 = plt.pressCore,
      accent3 = plt.dustLighter,
      accent4 = plt.dustBright,
      accent5 = plt.stemPulse,
      invert = plt.bloomMid,
    },
    rainbow = {
      rainbow1 = plt.dustBright,
      rainbow2 = plt.dustMid,
      rainbow3 = plt.dustDeep,
      rainbow4 = plt.bloomDeep,
      rainbow5 = plt.pressCore,
      rainbow6 = plt.pressBright,
      rainbow7 = plt.stemPulse,
    },
    ui = {
      bg = plt.petalVoid,
      bg_cursorline = plt.bloomLine,
      bg_dim = plt.petalVoid,
      bg_gutter = opts.gutter and plt.petalMid or "none",
      bg_highlight = plt.bloomDeep,
      bg_m1 = plt.petalDark,
      bg_m2 = plt.petalDeep,
      bg_m3 = plt.petalMid,
      bg_m4 = plt.petalLight,
      bg_p1 = plt.petalDeep,
      bg_p2 = plt.petalMid,
      bg_search = plt.stemPulse,
      bg_statusline = plt.bloomMid,
      bg_visual = plt.stemDeep,
      border = plt.dustMid,
      cursorline = plt.bloomLine,
      fg = plt.pressCore,
      fg_dark = plt.dustMid,
      fg_dim = plt.pressCore,
      fg_dimmer = plt.dustLighter,
      fg_reverse = plt.petalVoid,
      header1 = plt.pressBright,
      header2 = plt.pressCore,
      indent = plt.petalMid,
      indent_scope = plt.dustDeep,
      line_nr = plt.dustMid,
      line_nr_active = plt.pressCore,
      line_nr_dim = plt.dustBright,
      mark = plt.stemBright,
      nontext = plt.petalLight,
      picker = plt.dustMid,
      scrollbar = plt.petalLight,
      selection = plt.stemDeep,
      special = plt.stemBright,
      whitespace = plt.petalMid,
      win_separator = plt.dustMid,
      yank = plt.stemPulse,
      float = {
        bg = plt.petalDeep,
        bg_border = plt.petalDeep,
        fg = plt.pressCore,
        fg_border = plt.bloomMid,
      },
      pmenu = {
        bg = plt.bloomMid,
        bg_border = plt.bloomMid,
        bg_sbar = plt.bloomMid,
        bg_sel = plt.bloomDeep,
        bg_thumb = plt.dustMid,
        fg = plt.pressCore,
        fg_border = plt.bloomMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.petalVoid,
        bg_alternate = plt.petalVoid,
        bg_inactive = plt.petalVoid,
        bg_selected = plt.bloomMid,
        fg_alternate = plt.dustBright,
        fg_inactive = plt.dustLighter,
        fg_selected = plt.pressCore,
        indicator = plt.stemPulse,
      },
    },
    syn = {
      attribute = plt.pressCore,
      boolean = plt.stemBright,
      comment = plt.dustBright,
      constant = plt.dustLightest,
      deprecated = plt.dustMid,
      func = plt.pressBright,
      identifier = plt.pressCore,
      keyword = plt.pressCore,
      method = plt.pressBright,
      number = plt.dustLightest,
      operator = plt.dustMid,
      parameter = plt.dustLighter,
      preproc = plt.stemMid,
      punct = plt.dustDeep,
      regex = plt.dustMid,
      special = plt.stemPulse,
      special2 = plt.stemMid,
      special3 = plt.stemBright,
      statement = plt.pressCore,
      string = plt.dustLighter,
      symbol = plt.pressCore,
      type = plt.dustLightest,
      variable = plt.pressCore,
    },
    diag = {
      error = plt.stemBright,
      hint = plt.dustMid,
      info = plt.pressCore,
      ok = plt.dustLighter,
      virtual_text_error = plt.stemBright,
      virtual_text_hint = plt.dustMid,
      virtual_text_info = plt.pressCore,
      virtual_text_ok = plt.dustLighter,
      virtual_text_warning = plt.stemPulse,
      warning = plt.stemPulse,
    },
    diff = {
      add = plt.dustLighter,
      add_inline = plt.dustDeep,
      change = plt.dustDeep,
      change_inline = plt.bloomDeep,
      delete = plt.stemBright,
      delete_inline = plt.stemDeep,
      text = plt.stemMid,
    },
    vcs = {
      added = plt.dustLighter,
      changed = plt.stemDeep,
      removed = plt.stemBright,
    },
    term = {
      black = plt.petalVoid,
      black_bright = color(plt.petalVoid):brighten(0.4):to_hex(),
      blue = plt.petalVoid,
      blue_bright = color(plt.petalVoid):brighten(0.2):to_hex(),
      cyan = plt.dustMid,
      cyan_bright = color(plt.dustMid):brighten(0.3):to_hex(),
      green = plt.dustBright,
      green_bright = color(plt.dustBright):brighten(0.3):to_hex(),
      indexed1 = plt.dustLighter,
      indexed2 = plt.dustBright,
      magenta = plt.pressCore,
      magenta_bright = color(plt.pressCore):brighten(0.4):to_hex(),
      red = plt.stemBright,
      red_bright = plt.stemPulse,
      white = plt.pressBright,
      white_bright = plt.pressBright,
      yellow = plt.dustLightest,
      yellow_bright = plt.pressBright,
    },
  }
end

return {
  name = "Detox: Petal",
  author = "PrismPunk.nvim",
  description = "Dried pressed flowers. Dusty pink botanical tones. Muted stem memory green. Fragile preservation.",
  base16 = {
    base00 = palette.petalVoid,
    base01 = palette.petalDark,
    base02 = palette.petalDeep,
    base03 = palette.petalMid,
    base04 = palette.dustBright,
    base05 = palette.dustLightest,
    base06 = palette.pressCore,
    base07 = palette.pressBright,
    base08 = palette.stemBright,
    base09 = palette.stemMid,
    base0A = palette.stemDeep,
    base0B = palette.dustLighter,
    base0C = palette.stemPulse,
    base0D = palette.dustMid,
    base0E = palette.stemPulse,
    base0F = palette.dustMid,
  },
  palette = palette,
  get = M.get,
}
