local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.plaster")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.dustCore,
      insert = plt.crackLighter,
      normal = plt.crackBright,
      replace = plt.crackMid,
      visual = plt.stainPulse,
    },
    accent = {
      accent1 = plt.dustBright,
      accent2 = plt.dustCore,
      accent3 = plt.crackLighter,
      accent4 = plt.crackBright,
      accent5 = plt.stainPulse,
      invert = plt.paintMid,
    },
    rainbow = {
      rainbow1 = plt.crackBright,
      rainbow2 = plt.crackMid,
      rainbow3 = plt.crackDeep,
      rainbow4 = plt.paintDeep,
      rainbow5 = plt.dustCore,
      rainbow6 = plt.dustBright,
      rainbow7 = plt.stainPulse,
    },
    ui = {
      bg = plt.plasterVoid,
      bg_cursorline = plt.paintLine,
      bg_dim = plt.plasterVoid,
      bg_gutter = opts.gutter and plt.plasterMid or "none",
      bg_highlight = plt.paintDeep,
      bg_m1 = plt.plasterDark,
      bg_m2 = plt.plasterDeep,
      bg_m3 = plt.plasterMid,
      bg_m4 = plt.plasterLight,
      bg_p1 = plt.plasterDeep,
      bg_p2 = plt.plasterMid,
      bg_search = plt.stainPulse,
      bg_statusline = plt.paintMid,
      bg_visual = plt.stainDeep,
      border = plt.crackMid,
      cursorline = plt.paintLine,
      fg = plt.dustCore,
      fg_dark = plt.crackMid,
      fg_dim = plt.dustCore,
      fg_dimmer = plt.crackLighter,
      fg_reverse = plt.plasterVoid,
      header1 = plt.dustBright,
      header2 = plt.dustCore,
      indent = plt.plasterMid,
      indent_scope = plt.crackDeep,
      line_nr = plt.crackMid,
      line_nr_active = plt.dustCore,
      line_nr_dim = plt.crackBright,
      mark = plt.stainBright,
      nontext = plt.plasterLight,
      picker = plt.crackMid,
      scrollbar = plt.plasterLight,
      selection = plt.stainDeep,
      special = plt.stainBright,
      whitespace = plt.plasterMid,
      win_separator = plt.crackMid,
      yank = plt.stainPulse,
      float = {
        bg = plt.plasterDeep,
        bg_border = plt.plasterDeep,
        fg = plt.dustCore,
        fg_border = plt.paintMid,
      },
      pmenu = {
        bg = plt.paintMid,
        bg_border = plt.paintMid,
        bg_sbar = plt.paintMid,
        bg_sel = plt.paintDeep,
        bg_thumb = plt.crackMid,
        fg = plt.dustCore,
        fg_border = plt.paintMid,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.plasterVoid,
        bg_alternate = plt.plasterVoid,
        bg_inactive = plt.plasterVoid,
        bg_selected = plt.paintMid,
        fg_alternate = plt.crackBright,
        fg_inactive = plt.crackLighter,
        fg_selected = plt.dustCore,
        indicator = plt.stainPulse,
      },
    },
    syn = {
      attribute = plt.dustCore,
      boolean = plt.stainBright,
      comment = plt.crackBright,
      constant = plt.crackLightest,
      deprecated = plt.crackMid,
      func = plt.dustBright,
      identifier = plt.dustCore,
      keyword = plt.dustCore,
      method = plt.dustBright,
      number = plt.crackLightest,
      operator = plt.crackMid,
      parameter = plt.crackLighter,
      preproc = plt.stainMid,
      punct = plt.crackDeep,
      regex = plt.crackMid,
      special = plt.stainPulse,
      special2 = plt.stainMid,
      special3 = plt.stainBright,
      statement = plt.dustCore,
      string = plt.crackLighter,
      symbol = plt.dustCore,
      type = plt.crackLightest,
      variable = plt.dustCore,
    },
    diag = {
      error = plt.stainBright,
      hint = plt.crackMid,
      info = plt.dustCore,
      ok = plt.crackLighter,
      virtual_text_error = plt.stainBright,
      virtual_text_hint = plt.crackMid,
      virtual_text_info = plt.dustCore,
      virtual_text_ok = plt.crackLighter,
      virtual_text_warning = plt.stainPulse,
      warning = plt.stainPulse,
    },
    diff = {
      add = plt.crackLighter,
      add_inline = plt.crackDeep,
      change = plt.crackDeep,
      change_inline = plt.paintDeep,
      delete = plt.stainBright,
      delete_inline = plt.stainDeep,
      text = plt.stainMid,
    },
    vcs = {
      added = plt.crackLighter,
      changed = plt.stainDeep,
      removed = plt.stainBright,
    },
    term = {
      black = plt.plasterVoid,
      black_bright = color(plt.plasterVoid):brighten(0.4):to_hex(),
      blue = plt.plasterVoid,
      blue_bright = color(plt.plasterVoid):brighten(0.2):to_hex(),
      cyan = plt.crackMid,
      cyan_bright = color(plt.crackMid):brighten(0.3):to_hex(),
      green = plt.crackBright,
      green_bright = color(plt.crackBright):brighten(0.3):to_hex(),
      indexed1 = plt.crackLighter,
      indexed2 = plt.crackBright,
      magenta = plt.dustCore,
      magenta_bright = color(plt.dustCore):brighten(0.4):to_hex(),
      red = plt.stainBright,
      red_bright = plt.stainPulse,
      white = plt.dustBright,
      white_bright = plt.dustBright,
      yellow = plt.crackLightest,
      yellow_bright = plt.dustBright,
    },
  }
end

return {
  name = "Detox: Plaster",
  author = "PrismPunk.nvim",
  description = "Crumbling faded walls. Aging architectural surfaces. Rust stain decay. Abandonment aesthetic.",
  base16 = {
    base00 = palette.plasterVoid,
    base01 = palette.plasterDark,
    base02 = palette.plasterDeep,
    base03 = palette.plasterMid,
    base04 = palette.crackBright,
    base05 = palette.crackLightest,
    base06 = palette.dustCore,
    base07 = palette.dustBright,
    base08 = palette.stainBright,
    base09 = palette.stainMid,
    base0A = palette.stainDeep,
    base0B = palette.crackLighter,
    base0C = palette.stainPulse,
    base0D = palette.crackMid,
    base0E = palette.stainPulse,
    base0F = palette.crackMid,
  },
  palette = palette,
  get = M.get,
}
