local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.sepia")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.archiveBright,
      insert = plt.archiveLighter,
      normal = plt.archiveBright,
      replace = plt.archiveMid,
      visual = plt.fadeblackPulse,
    },
    accent = {
      accent1 = plt.photoBright,
      accent2 = plt.photoCore,
      accent3 = plt.archiveLighter,
      accent4 = plt.archiveBright,
      accent5 = plt.fadeblackPulse,
      invert = plt.vintageMid,
    },
    rainbow = {
      rainbow1 = plt.archiveBright,
      rainbow2 = plt.archiveMid,
      rainbow3 = plt.archiveDeep,
      rainbow4 = plt.vintageDeep,
      rainbow5 = plt.photoCore,
      rainbow6 = plt.photoBright,
      rainbow7 = plt.fadeblackPulse,
    },
    ui = {
      bg = plt.sepiaVoid,
      bg_cursorline = plt.vintageLine,
      bg_dim = plt.sepiaVoid,
      bg_gutter = opts.gutter and plt.sepiaMid or "none",
      bg_highlight = plt.vintageDeep,
      bg_m1 = plt.sepiaDark,
      bg_m2 = plt.sepiaDeep,
      bg_m3 = plt.sepiaMid,
      bg_m4 = plt.sepiaLight,
      bg_p1 = plt.sepiaDeep,
      bg_p2 = plt.sepiaMid,
      bg_statusline = plt.vintageMid,
      bg_visual = plt.fadeblackDeep,
      border = plt.archiveMid,
      cursorline = plt.vintageLine,
      fg = plt.photoCore,
      fg_dim = plt.photoDim,
      fg_reverse = plt.sepiaVoid,
      indent = plt.sepiaMid,
      line_nr = plt.archiveDeep,
      line_nr_active = plt.photoCore,
      line_nr_dim = plt.archiveMid,
      nontext = plt.sepiaLight,
      selection = plt.fadeblackDeep,
      win_separator = plt.archiveMid,
      float = {
        bg = plt.sepiaDeep,
        bg_border = plt.sepiaDeep,
        fg = plt.photoCore,
        fg_border = plt.vintageMid,
      },
      pmenu = {
        bg = plt.vintageMid,
        bg_border = plt.vintageMid,
        bg_sbar = plt.vintageMid,
        bg_sel = plt.vintageDeep,
        bg_thumb = plt.archiveMid,
        fg = plt.photoCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.sepiaVoid,
        bg_inactive = plt.sepiaVoid,
        bg_selected = plt.vintageMid,
        fg_inactive = plt.archiveLighter,
        fg_selected = plt.photoCore,
      },
    },
    syn = {
      attribute = plt.photoCore,
      boolean = plt.fadeblackBright,
      comment = plt.archiveBright,
      constant = plt.archiveLightest,
      deprecated = plt.archiveMid,
      func = plt.photoBright,
      identifier = plt.photoCore,
      keyword = plt.photoCore,
      method = plt.photoBright,
      number = plt.archiveLightest,
      operator = plt.archiveMid,
      parameter = plt.archiveLighter,
      preproc = plt.fadeblackMid,
      punct = plt.archiveMid,
      regex = plt.archiveMid,
      special = plt.fadeblackPulse,
      statement = plt.photoCore,
      string = plt.archiveLighter,
      symbol = plt.photoCore,
      type = plt.archiveLightest,
      variable = plt.photoCore,
    },
    diag = {
      error = plt.fadeblackBright,
      hint = plt.archiveMid,
      info = plt.archiveBright,
      ok = plt.archiveLighter,
      warning = plt.fadeblackPulse,
      virtual_text_error = plt.fadeblackMid,
      virtual_text_hint = plt.archiveDeep,
      virtual_text_info = plt.archiveMid,
      virtual_text_ok = plt.archiveLighter,
      virtual_text_warning = plt.fadeblackPulse,
    },
    diff = {
      add = plt.archiveLighter,
      add_inline = plt.archiveGlow,
      change = plt.archiveDeep,
      change_inline = plt.archiveBright,
      delete = plt.fadeblackBright,
      delete_inline = plt.fadeblackPulse,
      text = plt.fadeblackMid,
    },
    vcs = {
      added = plt.archiveLighter,
      changed = plt.fadeblackMid,
      removed = plt.fadeblackBright,
    },
    term = {
      black = plt.sepiaVoid,
      black_bright = color(plt.sepiaVoid):brighten(0.4):to_hex(),
      blue = plt.archiveMid,
      blue_bright = plt.archiveBright,
      cyan = plt.archiveLighter,
      cyan_bright = plt.archiveGlow,
      green = plt.archiveBright,
      green_bright = plt.archiveVivid,
      magenta = plt.fadeblackPulse,
      magenta_bright = plt.fadeblackGlow,
      red = plt.fadeblackBright,
      red_bright = plt.fadeblackPulse,
      white = plt.photoCore,
      white_bright = plt.photoBright,
      yellow = plt.archiveLightest,
      yellow_bright = plt.photoPeak,
    },
  }
end

return {
  name = "Detox: Sepia",
  author = "PrismPunk.nvim",
  description = "Vintage aged photographs. Faded sepia tones. Historical nostalgia. Without dopamine.",
  base16 = {
    base00 = palette.sepiaVoid,
    base01 = palette.sepiaDark,
    base02 = palette.sepiaDeep,
    base03 = palette.sepiaMid,
    base04 = palette.archiveBright,
    base05 = palette.archiveLightest,
    base06 = palette.photoDim,
    base07 = palette.photoCore,
    base08 = palette.fadeblackBright,
    base09 = palette.fadeblackMid,
    base0A = palette.fadeblackDeep,
    base0B = palette.archiveLighter,
    base0C = palette.fadeblackPulse,
    base0D = palette.archiveMid,
    base0E = palette.fadeblackPulse,
    base0F = palette.archiveMid,
  },
  palette = palette,
  get = M.get,
}
