local color = require("prismpunk.utils.color")

local palette = {
  siltVoid = "#080A08",
  siltDark = "#10120F",
  siltDeep = "#181A17",
  siltMid = "#20231F",
  siltLight = "#282B27",
  siltShadow = "#0C0E0C",
  siltEcho = "#1C201B",
  siltTint = "#242724",
  sedDeep = "#2F3532",
  sedMid = "#37403B",
  sedLine = "#404845",
  sedRidge = "#47504D",
  sedSoft = "#4F5855",
  sedGlow = "#586460",
  sedVivid = "#62706B",
  driftDeep = "#4A5450",
  driftMid = "#556062",
  driftBright = "#609575",
  driftLighter = "#6BA589",
  driftLightest = "#7AB39D",
  driftGlow = "#88C0AA",
  driftVivid = "#95D0BB",
  driftPeak = "#A2E0CC",
  waterCore = "#C8DDD5",
  waterBright = "#E0F0E8",
  waterPeak = "#F0F8F5",
  waterDim = "#B0C5C0",
  waterSoft = "#C0D5D0",
  decayDeep = "#3A2F28",
  decayMid = "#453A32",
  decayBright = "#50453D",
  decayPulse = "#5A5048",
  decayVivid = "#645A52",
  decayGlow = "#6E645C",
  decayRust = "#786E66",
  siltAccent1 = "#483C34",
  siltAccent2 = "#52443C",
  siltAccent3 = "#5C4C44",
  siltAccent4 = "#66544C",
  siltAccent5 = "#705C54",

  bg_darkest = "#080A08",
  fg_lightest = "#E0F0E8",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.driftBright,
      insert = plt.driftLighter,
      normal = plt.driftBright,
      replace = plt.driftMid,
      visual = plt.decayPulse,
    },
    accent = {
      accent1 = plt.waterBright,
      accent2 = plt.waterCore,
      accent3 = plt.driftLighter,
      accent4 = plt.driftBright,
      accent5 = plt.decayPulse,
      invert = plt.sedMid,
    },
    rainbow = {
      rainbow1 = plt.driftBright,
      rainbow2 = plt.driftMid,
      rainbow3 = plt.driftDeep,
      rainbow4 = plt.sedDeep,
      rainbow5 = plt.waterCore,
      rainbow6 = plt.waterBright,
      rainbow7 = plt.decayPulse,
    },
    ui = {
      bg = plt.siltVoid,
      bg_cursorline = plt.sedLine,
      bg_dim = plt.siltVoid,
      bg_gutter = opts.gutter and plt.siltMid or "none",
      bg_highlight = plt.sedDeep,
      bg_m1 = plt.siltDark,
      bg_m2 = plt.siltDeep,
      bg_m3 = plt.siltMid,
      bg_m4 = plt.siltLight,
      bg_p1 = plt.siltDeep,
      bg_p2 = plt.siltMid,
      bg_statusline = plt.sedMid,
      bg_visual = plt.decayDeep,
      border = plt.driftMid,
      cursorline = plt.sedLine,
      fg = plt.waterCore,
      fg_dim = plt.waterDim,
      fg_reverse = plt.siltVoid,
      indent = plt.siltMid,
      line_nr = plt.driftDeep,
      line_nr_active = plt.waterCore,
      line_nr_dim = plt.driftMid,
      nontext = plt.siltLight,
      selection = plt.decayDeep,
      win_separator = plt.driftMid,
      float = {
        bg = plt.siltDeep,
        bg_border = plt.siltDeep,
        fg = plt.waterCore,
        fg_border = plt.sedMid,
      },
      pmenu = {
        bg = plt.sedMid,
        bg_border = plt.sedMid,
        bg_sbar = plt.sedMid,
        bg_sel = plt.sedDeep,
        bg_thumb = plt.driftMid,
        fg = plt.waterCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.siltVoid,
        bg_inactive = plt.siltVoid,
        bg_selected = plt.sedMid,
        fg_inactive = plt.driftLighter,
        fg_selected = plt.waterCore,
      },
    },
    syn = {
      attribute = plt.waterCore,
      boolean = plt.decayBright,
      comment = plt.driftBright,
      constant = plt.driftLightest,
      deprecated = plt.driftMid,
      func = plt.waterBright,
      identifier = plt.waterCore,
      keyword = plt.waterCore,
      method = plt.waterBright,
      number = plt.driftLightest,
      operator = plt.driftMid,
      parameter = plt.driftLighter,
      preproc = plt.decayMid,
      punct = plt.driftMid,
      regex = plt.driftMid,
      special = plt.decayPulse,
      statement = plt.waterCore,
      string = plt.driftLighter,
      symbol = plt.waterCore,
      type = plt.driftLightest,
      variable = plt.waterCore,
    },
    diag = {
      error = plt.decayBright,
      hint = plt.driftMid,
      info = plt.driftBright,
      ok = plt.driftLighter,
      warning = plt.decayPulse,
      virtual_text_error = plt.decayMid,
      virtual_text_hint = plt.driftDeep,
      virtual_text_info = plt.driftMid,
      virtual_text_ok = plt.driftLighter,
      virtual_text_warning = plt.decayPulse,
    },
    diff = {
      add = plt.driftLighter,
      add_inline = plt.driftGlow,
      change = plt.driftDeep,
      change_inline = plt.driftBright,
      delete = plt.decayBright,
      delete_inline = plt.decayPulse,
      text = plt.decayMid,
    },
    vcs = {
      added = plt.driftLighter,
      changed = plt.decayMid,
      removed = plt.decayBright,
    },
    term = {
      black = plt.siltVoid,
      black_bright = color(plt.siltVoid):brighten(0.4):to_hex(),
      blue = plt.driftMid,
      blue_bright = plt.driftBright,
      cyan = plt.driftLighter,
      cyan_bright = plt.driftGlow,
      green = plt.driftBright,
      green_bright = plt.driftVivid,
      magenta = plt.decayPulse,
      magenta_bright = plt.decayGlow,
      red = plt.decayBright,
      red_bright = plt.decayPulse,
      white = plt.waterCore,
      white_bright = plt.waterBright,
      yellow = plt.driftLightest,
      yellow_bright = plt.waterPeak,
    },
  }
end

return {
  name = "Detox: Silt",
  author = "PrismPunk.nvim",
  description = "Suspended sediment. Cool teals. Peachy decay warmth. Underwater stillness. Drifting contemplation.",
  base16 = {
    base00 = palette.siltVoid,
    base01 = palette.siltDark,
    base02 = palette.siltDeep,
    base03 = palette.siltMid,
    base04 = palette.driftBright,
    base05 = palette.driftLightest,
    base06 = palette.waterDim,
    base07 = palette.waterCore,
    base08 = palette.decayBright,
    base09 = palette.decayMid,
    base0A = palette.decayDeep,
    base0B = palette.driftLighter,
    base0C = palette.decayPulse,
    base0D = palette.driftMid,
    base0E = palette.decayPulse,
    base0F = palette.driftMid,
  },
  palette = palette,
  get = M.get,
}
