local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.slate")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.grainBright,
      insert = plt.grainLighter,
      normal = plt.grainBright,
      replace = plt.grainMid,
      visual = plt.goldPulse,
    },
    accent = {
      accent1 = plt.veineBright,
      accent2 = plt.veineCore,
      accent3 = plt.grainLighter,
      accent4 = plt.grainBright,
      accent5 = plt.goldPulse,
      invert = plt.minerMid,
    },
    rainbow = {
      rainbow1 = plt.grainBright,
      rainbow2 = plt.grainMid,
      rainbow3 = plt.grainDeep,
      rainbow4 = plt.minerDeep,
      rainbow5 = plt.veineCore,
      rainbow6 = plt.veineBright,
      rainbow7 = plt.goldPulse,
    },
    ui = {
      bg = plt.stoneVoid,
      bg_cursorline = plt.minerLine,
      bg_dim = plt.stoneVoid,
      bg_gutter = opts.gutter and plt.stoneMid or "none",
      bg_highlight = plt.minerDeep,
      bg_m1 = plt.stoneDark,
      bg_m2 = plt.stoneDeep,
      bg_m3 = plt.stoneMid,
      bg_m4 = plt.stoneLight,
      bg_p1 = plt.stoneDeep,
      bg_p2 = plt.stoneMid,
      bg_statusline = plt.minerMid,
      bg_visual = plt.goldDeep,
      border = plt.grainMid,
      cursorline = plt.minerLine,
      fg = plt.veineCore,
      fg_dim = plt.veineDim,
      fg_reverse = plt.stoneVoid,
      indent = plt.stoneMid,
      line_nr = plt.grainDeep,
      line_nr_active = plt.veineCore,
      line_nr_dim = plt.grainMid,
      nontext = plt.stoneLight,
      selection = plt.goldDeep,
      win_separator = plt.grainMid,
      float = {
        bg = plt.stoneDeep,
        bg_border = plt.stoneDeep,
        fg = plt.veineCore,
        fg_border = plt.minerMid,
      },
      pmenu = {
        bg = plt.minerMid,
        bg_border = plt.minerMid,
        bg_sbar = plt.minerMid,
        bg_sel = plt.minerDeep,
        bg_thumb = plt.grainMid,
        fg = plt.veineCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.stoneVoid,
        bg_inactive = plt.stoneVoid,
        bg_selected = plt.minerMid,
        fg_inactive = plt.grainLighter,
        fg_selected = plt.veineCore,
      },
    },
    syn = {
      attribute = plt.veineCore,
      boolean = plt.goldBright,
      comment = plt.grainBright,
      constant = plt.grainLightest,
      deprecated = plt.grainMid,
      func = plt.veineBright,
      identifier = plt.veineCore,
      keyword = plt.veineCore,
      method = plt.veineBright,
      number = plt.grainLightest,
      operator = plt.grainMid,
      parameter = plt.grainLighter,
      preproc = plt.goldMid,
      punct = plt.grainMid,
      regex = plt.grainMid,
      special = plt.goldPulse,
      statement = plt.veineCore,
      string = plt.grainLighter,
      symbol = plt.veineCore,
      type = plt.grainLightest,
      variable = plt.veineiveCore,
    },
    diag = {
      error = plt.goldBright,
      hint = plt.grainMid,
      info = plt.grainBright,
      ok = plt.grainLighter,
      warning = plt.goldPulse,
      virtual_text_error = plt.goldMid,
      virtual_text_hint = plt.grainDeep,
      virtual_text_info = plt.grainMid,
      virtual_text_ok = plt.grainLighter,
      virtual_text_warning = plt.goldPulse,
    },
    diff = {
      add = plt.grainLighter,
      add_inline = plt.grainGlow,
      change = plt.grainDeep,
      change_inline = plt.grainBright,
      delete = plt.goldBright,
      delete_inline = plt.goldPulse,
      text = plt.goldMid,
    },
    vcs = {
      added = plt.grainLighter,
      changed = plt.goldMid,
      removed = plt.goldBright,
    },
    term = {
      black = plt.stoneVoid,
      black_bright = color(plt.stoneVoid):brighten(0.4):to_hex(),
      blue = plt.grainMid,
      blue_bright = plt.grainBright,
      cyan = plt.grainLighter,
      cyan_bright = plt.grainGlow,
      green = plt.grainBright,
      green_bright = plt.grainVivid,
      magenta = plt.goldPulse,
      magenta_bright = plt.goldGlow,
      red = plt.goldBright,
      red_bright = plt.goldPulse,
      white = plt.veineCore,
      white_bright = plt.veineBright,
      yellow = plt.grainLightest,
      yellow_bright = plt.veinePeak,
    },
  }
end

return {
  name = "Detox: Slate",
  author = "PrismPunk.nvim",
  description = "Monolithic stone surface. Cool grays. Pale gold mineral seams. Solid timelessness.",
  base16 = {
    base00 = palette.stoneVoid,
    base01 = palette.stoneDark,
    base02 = palette.stoneDeep,
    base03 = palette.stoneMid,
    base04 = palette.grainBright,
    base05 = palette.grainLightest,
    base06 = palette.veineDim,
    base07 = palette.veineCore,
    base08 = palette.goldBright,
    base09 = palette.goldMid,
    base0A = palette.goldDeep,
    base0B = palette.grainLighter,
    base0C = palette.goldPulse,
    base0D = palette.grainMid,
    base0E = palette.goldPulse,
    base0F = palette.grainMid,
  },
  palette = palette,
  get = M.get,
}
