local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.smoke")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.vaporBright,
      insert = plt.vaporLighter,
      normal = plt.vaporBright,
      replace = plt.vaporMid,
      visual = plt.duskPulse,
    },
    accent = {
      accent1 = plt.cloudBright,
      accent2 = plt.cloudCore,
      accent3 = plt.vaporLighter,
      accent4 = plt.vaporBright,
      accent5 = plt.duskPulse,
      invert = plt.hazeMid,
    },
    rainbow = {
      rainbow1 = plt.vaporBright,
      rainbow2 = plt.vaporMid,
      rainbow3 = plt.vaporDeep,
      rainbow4 = plt.hazeDeep,
      rainbow5 = plt.cloudCore,
      rainbow6 = plt.cloudBright,
      rainbow7 = plt.duskPulse,
    },
    ui = {
      bg = plt.smokeVoid,
      bg_cursorline = plt.hazeLine,
      bg_dim = plt.smokeVoid,
      bg_gutter = opts.gutter and plt.smokeMid or "none",
      bg_highlight = plt.hazeDeep,
      bg_m1 = plt.smokeDark,
      bg_m2 = plt.smokeDeep,
      bg_m3 = plt.smokeMid,
      bg_m4 = plt.smokeLight,
      bg_p1 = plt.smokeDeep,
      bg_p2 = plt.smokeMid,
      bg_statusline = plt.hazeMid,
      bg_visual = plt.duskDeep,
      border = plt.vaporMid,
      cursorline = plt.hazeLine,
      fg = plt.cloudCore,
      fg_dim = plt.cloudDim,
      fg_reverse = plt.smokeVoid,
      indent = plt.smokeMid,
      line_nr = plt.vaporDeep,
      line_nr_active = plt.cloudCore,
      line_nr_dim = plt.vaporMid,
      nontext = plt.smokeLight,
      selection = plt.duskDeep,
      win_separator = plt.vaporMid,
      float = {
        bg = plt.smokeDeep,
        bg_border = plt.smokeDeep,
        fg = plt.cloudCore,
        fg_border = plt.hazeMid,
      },
      pmenu = {
        bg = plt.hazeMid,
        bg_border = plt.hazeMid,
        bg_sbar = plt.hazeMid,
        bg_sel = plt.hazeDeep,
        bg_thumb = plt.vaporMid,
        fg = plt.cloudCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.smokeVoid,
        bg_inactive = plt.smokeVoid,
        bg_selected = plt.hazeMid,
        fg_inactive = plt.vaporLighter,
        fg_selected = plt.cloudCore,
      },
    },
    syn = {
      attribute = plt.cloudCore,
      boolean = plt.duskBright,
      comment = plt.vaporBright,
      constant = plt.vaporLightest,
      deprecated = plt.vaporMid,
      func = plt.cloudBright,
      identifier = plt.cloudCore,
      keyword = plt.cloudCore,
      method = plt.cloudBright,
      number = plt.vaporLightest,
      operator = plt.vaporMid,
      parameter = plt.vaporLighter,
      preproc = plt.duskMid,
      punct = plt.vaporMid,
      regex = plt.vaporMid,
      special = plt.duskPulse,
      statement = plt.cloudCore,
      string = plt.vaporLighter,
      symbol = plt.cloudCore,
      type = plt.vaporLightest,
      variable = plt.cloudCore,
    },
    diag = {
      error = plt.duskBright,
      hint = plt.vaporMid,
      info = plt.vaporBright,
      ok = plt.vaporLighter,
      warning = plt.duskPulse,
      virtual_text_error = plt.duskMid,
      virtual_text_hint = plt.vaporDeep,
      virtual_text_info = plt.vaporMid,
      virtual_text_ok = plt.vaporLighter,
      virtual_text_warning = plt.duskPulse,
    },
    diff = {
      add = plt.vaporLighter,
      add_inline = plt.vaporGlow,
      change = plt.vaporDeep,
      change_inline = plt.vaporBright,
      delete = plt.duskBright,
      delete_inline = plt.duskPulse,
      text = plt.duskMid,
    },
    vcs = {
      added = plt.vaporLighter,
      changed = plt.duskMid,
      removed = plt.duskBright,
    },
    term = {
      black = plt.smokeVoid,
      black_bright = color(plt.smokeVoid):brighten(0.4):to_hex(),
      blue = plt.vaporMid,
      blue_bright = plt.vaporBright,
      cyan = plt.vaporLighter,
      cyan_bright = plt.vaporGlow,
      green = plt.vaporBright,
      green_bright = plt.vaporVivid,
      magenta = plt.duskPulse,
      magenta_bright = plt.duskGlow,
      red = plt.duskBright,
      red_bright = plt.duskPulse,
      white = plt.cloudCore,
      white_bright = plt.cloudBright,
      yellow = plt.vaporLightest,
      yellow_bright = plt.cloudPeak,
    },
  }
end

return {
  name = "Detox: Smoke",
  author = "PrismPunk.nvim",
  description = "Dissipating vapor haze. Neutral gray mist. Faint dusk glow. Ephemeral atmosphere.",
  base16 = {
    base00 = palette.smokeVoid,
    base01 = palette.smokeDark,
    base02 = palette.smokeDeep,
    base03 = palette.smokeMid,
    base04 = palette.vaporBright,
    base05 = palette.vaporLightest,
    base06 = palette.cloudDim,
    base07 = palette.cloudCore,
    base08 = palette.duskBright,
    base09 = palette.duskMid,
    base0A = palette.duskDeep,
    base0B = palette.vaporLighter,
    base0C = palette.duskPulse,
    base0D = palette.vaporMid,
    base0E = palette.duskPulse,
    base0F = palette.vaporMid,
  },
  palette = palette,
  get = M.get,
}
