local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.void")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.nullBright,
      insert = plt.nullLighter,
      normal = plt.nullBright,
      replace = plt.nullMid,
      visual = plt.focusPulse,
    },
    accent = {
      accent1 = plt.singleBright,
      accent2 = plt.singleCore,
      accent3 = plt.nullLighter,
      accent4 = plt.nullBright,
      accent5 = plt.focusPulse,
      invert = plt.nothingMid,
    },
    rainbow = {
      rainbow1 = plt.nullBright,
      rainbow2 = plt.nullMid,
      rainbow3 = plt.nullDeep,
      rainbow4 = plt.nothingDeep,
      rainbow5 = plt.singleCore,
      rainbow6 = plt.singleBright,
      rainbow7 = plt.focusPulse,
    },
    ui = {
      bg = plt.voidVoid,
      bg_cursorline = plt.nothingLine,
      bg_dim = plt.voidVoid,
      bg_gutter = opts.gutter and plt.voidMid or "none",
      bg_highlight = plt.nothingDeep,
      bg_m1 = plt.voidDark,
      bg_m2 = plt.voidDeep,
      bg_m3 = plt.voidMid,
      bg_m4 = plt.voidLight,
      bg_p1 = plt.voidDeep,
      bg_p2 = plt.voidMid,
      bg_statusline = plt.nothingMid,
      bg_visual = plt.focusDeep,
      border = plt.nullMid,
      cursorline = plt.nothingLine,
      fg = plt.singleCore,
      fg_dim = plt.singleDim,
      fg_reverse = plt.voidVoid,
      indent = plt.voidMid,
      line_nr = plt.nullDeep,
      line_nr_active = plt.singleCore,
      line_nr_dim = plt.nullMid,
      nontext = plt.voidLight,
      selection = plt.focusDeep,
      win_separator = plt.nullMid,
      float = {
        bg = plt.voidDeep,
        bg_border = plt.voidDeep,
        fg = plt.singleCore,
        fg_border = plt.nothingMid,
      },
      pmenu = {
        bg = plt.nothingMid,
        bg_border = plt.nothingMid,
        bg_sbar = plt.nothingMid,
        bg_sel = plt.nothingDeep,
        bg_thumb = plt.nullMid,
        fg = plt.singleCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.voidVoid,
        bg_inactive = plt.voidVoid,
        bg_selected = plt.nothingMid,
        fg_inactive = plt.nullLighter,
        fg_selected = plt.singleCore,
      },
    },
    syn = {
      attribute = plt.singleCore,
      boolean = plt.focusBright,
      comment = plt.nullBright,
      constant = plt.nullLightest,
      deprecated = plt.nullMid,
      func = plt.singleBright,
      identifier = plt.singleCore,
      keyword = plt.singleCore,
      method = plt.singleBright,
      number = plt.nullLightest,
      operator = plt.nullMid,
      parameter = plt.nullLighter,
      preproc = plt.focusMid,
      punct = plt.nullMid,
      regex = plt.nullMid,
      special = plt.focusPulse,
      statement = plt.singleCore,
      string = plt.nullLighter,
      symbol = plt.singleCore,
      type = plt.nullLightest,
      variable = plt.singleCore,
    },
    diag = {
      error = plt.focusBright,
      hint = plt.nullMid,
      info = plt.nullBright,
      ok = plt.nullLighter,
      warning = plt.focusPulse,
      virtual_text_error = plt.focusMid,
      virtual_text_hint = plt.nullDeep,
      virtual_text_info = plt.nullMid,
      virtual_text_ok = plt.nullLighter,
      virtual_text_warning = plt.focusPulse,
    },
    diff = {
      add = plt.nullLighter,
      add_inline = plt.nullGlow,
      change = plt.nullDeep,
      change_inline = plt.nullBright,
      delete = plt.focusBright,
      delete_inline = plt.focusPulse,
      text = plt.focusMid,
    },
    vcs = {
      added = plt.nullLighter,
      changed = plt.focusMid,
      removed = plt.focusBright,
    },
    term = {
      black = plt.voidVoid,
      black_bright = color(plt.voidVoid):brighten(0.4):to_hex(),
      blue = plt.nullMid,
      blue_bright = plt.nullBright,
      cyan = plt.nullLighter,
      cyan_bright = plt.nullGlow,
      green = plt.nullBright,
      green_bright = plt.nullVivid,
      magenta = plt.focusPulse,
      magenta_bright = plt.focusGlow,
      red = plt.focusBright,
      red_bright = plt.focusPulse,
      white = plt.singleCore,
      white_bright = plt.singleBright,
      yellow = plt.nullLightest,
      yellow_bright = plt.singlePeak,
    },
  }
end

return {
  name = "Detox: Void",
  author = "PrismPunk.nvim",
  description = "True sensory deprivation. Monochrome nothingness. Single cyan focus. Extreme minimalism.",
  base16 = {
    base00 = palette.voidVoid,
    base01 = palette.voidDark,
    base02 = palette.voidDeep,
    base03 = palette.voidMid,
    base04 = palette.nullBright,
    base05 = palette.nullLightest,
    base06 = palette.singleDim,
    base07 = palette.singleCore,
    base08 = palette.focusBright,
    base09 = palette.focusMid,
    base0A = palette.focusDeep,
    base0B = palette.nullLighter,
    base0C = palette.focusPulse,
    base0D = palette.nullMid,
    base0E = palette.focusPulse,
    base0F = palette.nullMid,
  },
  palette = palette,
  get = M.get,
}
