local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.wool")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.yarnBright,
      insert = plt.yarnLighter,
      normal = plt.yarnBright,
      replace = plt.yarnMid,
      visual = plt.dyePulse,
    },
    accent = {
      accent1 = plt.woolBright,
      accent2 = plt.woolCore,
      accent3 = plt.yarnLighter,
      accent4 = plt.yarnBright,
      accent5 = plt.dyePulse,
      invert = plt.fiberMid,
    },
    rainbow = {
      rainbow1 = plt.yarnBright,
      rainbow2 = plt.yarnMid,
      rainbow3 = plt.yarnDeep,
      rainbow4 = plt.fiberDeep,
      rainbow5 = plt.woolCore,
      rainbow6 = plt.woolBright,
      rainbow7 = plt.dyePulse,
    },
    ui = {
      bg = plt.woolVoid,
      bg_cursorline = plt.fiberLine,
      bg_dim = plt.woolVoid,
      bg_gutter = opts.gutter and plt.woolMid or "none",
      bg_highlight = plt.fiberDeep,
      bg_m1 = plt.woolDark,
      bg_m2 = plt.woolDeep,
      bg_m3 = plt.woolMid,
      bg_m4 = plt.woolLight,
      bg_p1 = plt.woolDeep,
      bg_p2 = plt.woolMid,
      bg_statusline = plt.fiberMid,
      bg_visual = plt.dyeDeep,
      border = plt.yarnMid,
      cursorline = plt.fiberLine,
      fg = plt.woolCore,
      fg_dim = plt.woolDim,
      fg_reverse = plt.woolVoid,
      indent = plt.woolMid,
      line_nr = plt.yarnDeep,
      line_nr_active = plt.woolCore,
      line_nr_dim = plt.yarnMid,
      nontext = plt.woolLight,
      selection = plt.dyeDeep,
      win_separator = plt.yarnMid,
      float = {
        bg = plt.woolDeep,
        bg_border = plt.woolDeep,
        fg = plt.woolCore,
        fg_border = plt.fiberMid,
      },
      pmenu = {
        bg = plt.fiberMid,
        bg_border = plt.fiberMid,
        bg_sbar = plt.fiberMid,
        bg_sel = plt.fiberDeep,
        bg_thumb = plt.yarnMid,
        fg = plt.woolCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.woolVoid,
        bg_inactive = plt.woolVoid,
        bg_selected = plt.fiberMid,
        fg_inactive = plt.yarnLighter,
        fg_selected = plt.woolCore,
      },
    },
    syn = {
      attribute = plt.woolCore,
      boolean = plt.dyeBright,
      comment = plt.yarnBright,
      constant = plt.yarnLightest,
      deprecated = plt.yarnMid,
      func = plt.woolBright,
      identifier = plt.woolCore,
      keyword = plt.woolCore,
      method = plt.woolBright,
      number = plt.yarnLightest,
      operator = plt.yarnMid,
      parameter = plt.yarnLighter,
      preproc = plt.dyeMid,
      punct = plt.yarnMid,
      regex = plt.yarnMid,
      special = plt.dyePulse,
      statement = plt.woolCore,
      string = plt.yarnLighter,
      symbol = plt.woolCore,
      type = plt.yarnLightest,
      variable = plt.woolCore,
    },
    diag = {
      error = plt.dyeBright,
      hint = plt.yarnMid,
      info = plt.yarnBright,
      ok = plt.yarnLighter,
      warning = plt.dyePulse,
      virtual_text_error = plt.dyeMid,
      virtual_text_hint = plt.yarnDeep,
      virtual_text_info = plt.yarnMid,
      virtual_text_ok = plt.yarnLighter,
      virtual_text_warning = plt.dyePulse,
    },
    diff = {
      add = plt.yarnLighter,
      add_inline = plt.yarnGlow,
      change = plt.yarnDeep,
      change_inline = plt.yarnBright,
      delete = plt.dyeBright,
      delete_inline = plt.dyePulse,
      text = plt.dyeMid,
    },
    vcs = {
      added = plt.yarnLighter,
      changed = plt.dyeMid,
      removed = plt.dyeBright,
    },
    term = {
      black = plt.woolVoid,
      black_bright = color(plt.woolVoid):brighten(0.4):to_hex(),
      blue = plt.yarnMid,
      blue_bright = plt.yarnBright,
      cyan = plt.yarnLighter,
      cyan_bright = plt.yarnGlow,
      green = plt.yarnBright,
      green_bright = plt.yarnVivid,
      magenta = plt.dyePulse,
      magenta_bright = plt.dyeGlow,
      red = plt.dyeBright,
      red_bright = plt.dyePulse,
      white = plt.woolCore,
      white_bright = plt.woolBright,
      yellow = plt.yarnLightest,
      yellow_bright = plt.woolPeak,
    },
  }
end

return {
  name = "Detox: Wool",
  author = "PrismPunk.nvim",
  description = "Knitted natural fiber. Hand-spun yarn texture. Natural sage dyes. Warm textile comfort.",
  base16 = {
    base00 = palette.woolVoid,
    base01 = palette.woolDark,
    base02 = palette.woolDeep,
    base03 = palette.woolMid,
    base04 = palette.yarnBright,
    base05 = palette.yarnLightest,
    base06 = palette.woolDim,
    base07 = palette.woolCore,
    base08 = palette.dyeBright,
    base09 = palette.dyeMid,
    base0A = palette.dyeDeep,
    base0B = palette.yarnLighter,
    base0C = palette.dyePulse,
    base0D = palette.yarnMid,
    base0E = palette.dyePulse,
    base0F = palette.yarnMid,
  },
  palette = palette,
  get = M.get,
}
