local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.zenkanagawa")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.depthBright,
      insert = plt.depthLighter,
      normal = plt.depthBright,
      replace = plt.depthMid,
      visual = plt.sunsetPulse,
    },
    accent = {
      accent1 = plt.horizonBright,
      accent2 = plt.horizonCore,
      accent3 = plt.depthLighter,
      accent4 = plt.depthBright,
      accent5 = plt.sunsetPulse,
      invert = plt.tidalMid,
    },
    rainbow = {
      rainbow1 = plt.depthBright,
      rainbow2 = plt.depthMid,
      rainbow3 = plt.depthDeep,
      rainbow4 = plt.tidalDeep,
      rainbow5 = plt.horizonCore,
      rainbow6 = plt.horizonBright,
      rainbow7 = plt.sunsetPulse,
    },
    ui = {
      bg = plt.waveVoid,
      bg_cursorline = plt.tidalLine,
      bg_dim = plt.waveVoid,
      bg_gutter = opts.gutter and plt.waveMid or "none",
      bg_highlight = plt.tidalDeep,
      bg_m1 = plt.waveDark,
      bg_m2 = plt.waveDeep,
      bg_m3 = plt.waveMid,
      bg_m4 = plt.waveLight,
      bg_p1 = plt.waveDeep,
      bg_p2 = plt.waveMid,
      bg_statusline = plt.tidalMid,
      bg_visual = plt.sunsetDeep,
      border = plt.depthMid,
      cursorline = plt.tidalLine,
      fg = plt.horizonCore,
      fg_dim = plt.horizonDim,
      fg_reverse = plt.waveVoid,
      indent = plt.waveMid,
      line_nr = plt.depthDeep,
      line_nr_active = plt.horizonCore,
      line_nr_dim = plt.depthMid,
      nontext = plt.waveLight,
      selection = plt.sunsetDeep,
      win_separator = plt.depthMid,
      float = {
        bg = plt.waveDeep,
        bg_border = plt.waveDeep,
        fg = plt.horizonCore,
        fg_border = plt.tidalMid,
      },
      pmenu = {
        bg = plt.tidalMid,
        bg_border = plt.tidalMid,
        bg_sbar = plt.tidalMid,
        bg_sel = plt.tidalDeep,
        bg_thumb = plt.depthMid,
        fg = plt.horizonCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.waveVoid,
        bg_inactive = plt.waveVoid,
        bg_selected = plt.tidalMid,
        fg_inactive = plt.depthLighter,
        fg_selected = plt.horizonCore,
      },
    },
    syn = {
      attribute = plt.horizonCore,
      boolean = plt.sunsetBright,
      comment = plt.depthBright,
      constant = plt.depthLightest,
      deprecated = plt.depthMid,
      func = plt.horizonBright,
      identifier = plt.horizonCore,
      keyword = plt.horizonCore,
      method = plt.horizonBright,
      number = plt.depthLightest,
      operator = plt.depthMid,
      parameter = plt.depthLighter,
      preproc = plt.sunsetMid,
      punct = plt.depthMid,
      regex = plt.depthMid,
      special = plt.sunsetPulse,
      statement = plt.horizonCore,
      string = plt.depthLighter,
      symbol = plt.horizonCore,
      type = plt.depthLightest,
      variable = plt.horizonCore,
    },
    diag = {
      error = plt.sunsetBright,
      hint = plt.depthMid,
      info = plt.depthBright,
      ok = plt.depthLighter,
      warning = plt.sunsetPulse,
      virtual_text_error = plt.sunsetMid,
      virtual_text_hint = plt.depthDeep,
      virtual_text_info = plt.depthMid,
      virtual_text_ok = plt.depthLighter,
      virtual_text_warning = plt.sunsetPulse,
    },
    diff = {
      add = plt.depthLighter,
      add_inline = plt.depthGlow,
      change = plt.depthDeep,
      change_inline = plt.depthBright,
      delete = plt.sunsetBright,
      delete_inline = plt.sunsetPulse,
      text = plt.sunsetMid,
    },
    vcs = {
      added = plt.depthLighter,
      changed = plt.sunsetMid,
      removed = plt.sunsetBright,
    },
    term = {
      black = plt.waveVoid,
      black_bright = color(plt.waveVoid):brighten(0.4):to_hex(),
      blue = plt.depthMid,
      blue_bright = plt.depthBright,
      cyan = plt.depthLighter,
      cyan_bright = plt.depthGlow,
      green = plt.depthBright,
      green_bright = plt.depthVivid,
      magenta = plt.sunsetPulse,
      magenta_bright = plt.sunsetGlow,
      red = plt.sunsetBright,
      red_bright = plt.sunsetPulse,
      white = plt.horizonCore,
      white_bright = plt.horizonBright,
      yellow = plt.depthLightest,
      yellow_bright = plt.horizonPeak,
    },
  }
end

return {
  name = "Detox: Kanagawa",
  author = "PrismPunk.nvim",
  description = "Desaturated indigo waves. Warm sunset accents. Contemplative & flowing. The ocean without dopamine.",
  base16 = {
    base00 = palette.waveVoid,
    base01 = palette.waveDark,
    base02 = palette.waveDeep,
    base03 = palette.waveMid,
    base04 = palette.depthBright,
    base05 = palette.depthLightest,
    base06 = palette.horizonDim,
    base07 = palette.horizonCore,
    base08 = palette.sunsetBright,
    base09 = palette.sunsetMid,
    base0A = palette.sunsetDeep,
    base0B = palette.depthLighter,
    base0C = palette.sunsetPulse,
    base0D = palette.depthMid,
    base0E = palette.sunsetPulse,
    base0F = palette.depthMid,
  },
  palette = palette,
  get = M.get,
}
