local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.detox.zenpaper")

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  return {
    modes = {
      command = plt.scrollBright,
      insert = plt.scrollLighter,
      normal = plt.scrollBright,
      replace = plt.scrollMid,
      visual = plt.brushPulse,
    },
    accent = {
      accent1 = plt.pensiveBright,
      accent2 = plt.pensiveCore,
      accent3 = plt.scrollLighter,
      accent4 = plt.scrollBright,
      accent5 = plt.brushPulse,
      invert = plt.inkMid,
    },
    rainbow = {
      rainbow1 = plt.scrollBright,
      rainbow2 = plt.scrollMid,
      rainbow3 = plt.scrollDeep,
      rainbow4 = plt.inkDeep,
      rainbow5 = plt.pensiveCore,
      rainbow6 = plt.pensiveBright,
      rainbow7 = plt.brushPulse,
    },
    ui = {
      bg = plt.paperVoid,
      bg_cursorline = plt.inkLine,
      bg_dim = plt.paperVoid,
      bg_gutter = opts.gutter and plt.paperMid or "none",
      bg_highlight = plt.inkDeep,
      bg_m1 = plt.paperDark,
      bg_m2 = plt.paperDeep,
      bg_m3 = plt.paperMid,
      bg_m4 = plt.paperLight,
      bg_p1 = plt.paperDeep,
      bg_p2 = plt.paperMid,
      bg_statusline = plt.inkMid,
      bg_visual = plt.brushDeep,
      border = plt.scrollMid,
      cursorline = plt.inkLine,
      fg = plt.pensiveCore,
      fg_dim = plt.pensiveDim,
      fg_reverse = plt.paperVoid,
      indent = plt.paperMid,
      line_nr = plt.scrollDeep,
      line_nr_active = plt.pensiveCore,
      line_nr_dim = plt.scrollMid,
      nontext = plt.paperLight,
      selection = plt.brushDeep,
      win_separator = plt.scrollMid,
      float = {
        bg = plt.paperDeep,
        bg_border = plt.paperDeep,
        fg = plt.pensiveCore,
        fg_border = plt.inkMid,
      },
      pmenu = {
        bg = plt.inkMid,
        bg_border = plt.inkMid,
        bg_sbar = plt.inkMid,
        bg_sel = plt.inkDeep,
        bg_thumb = plt.scrollMid,
        fg = plt.pensiveCore,
        fg_sel = "none",
      },
      tabline = {
        bg = plt.paperVoid,
        bg_inactive = plt.paperVoid,
        bg_selected = plt.inkMid,
        fg_inactive = plt.scrollLighter,
        fg_selected = plt.pensiveCore,
      },
    },
    syn = {
      attribute = plt.pensiveCore,
      boolean = plt.brushBright,
      comment = plt.scrollBright,
      constant = plt.scrollLightest,
      deprecated = plt.scrollMid,
      func = plt.pensiveBright,
      identifier = plt.pensiveCore,
      keyword = plt.pensiveCore,
      method = plt.pensiveBright,
      number = plt.scrollLightest,
      operator = plt.scrollMid,
      parameter = plt.scrollLighter,
      preproc = plt.brushMid,
      punct = plt.scrollMid,
      regex = plt.scrollMid,
      special = plt.brushPulse,
      statement = plt.pensiveCore,
      string = plt.scrollLighter,
      symbol = plt.pensiveCore,
      type = plt.scrollLightest,
      variable = plt.pensiveCore,
    },
    diag = {
      error = plt.brushBright,
      hint = plt.scrollMid,
      info = plt.scrollBright,
      ok = plt.scrollLighter,
      warning = plt.brushPulse,
      virtual_text_error = plt.brushMid,
      virtual_text_hint = plt.scrollDeep,
      virtual_text_info = plt.scrollMid,
      virtual_text_ok = plt.scrollLighter,
      virtual_text_warning = plt.brushPulse,
    },
    diff = {
      add = plt.scrollLighter,
      add_inline = plt.scrollGlow,
      change = plt.scrollDeep,
      change_inline = plt.scrollBright,
      delete = plt.brushBright,
      delete_inline = plt.brushPulse,
      text = plt.brushMid,
    },
    vcs = {
      added = plt.scrollLighter,
      changed = plt.brushMid,
      removed = plt.brushBright,
    },
    term = {
      black = plt.paperVoid,
      black_bright = color(plt.paperVoid):brighten(0.4):to_hex(),
      blue = plt.scrollMid,
      blue_bright = plt.scrollBright,
      cyan = plt.scrollLighter,
      cyan_bright = plt.scrollGlow,
      green = plt.scrollBright,
      green_bright = plt.scrollVivid,
      magenta = plt.brushPulse,
      magenta_bright = plt.brushGlow,
      red = plt.brushBright,
      red_bright = plt.brushPulse,
      white = plt.pensiveCore,
      white_bright = plt.pensiveBright,
      yellow = plt.scrollLightest,
      yellow_bright = plt.pensivePeak,
    },
  }
end

return {
  name = "Detox: Zenpaper",
  author = "PrismPunk.nvim",
  description = "Warm paper tones. Natural ink warmth. Contemplative browns. The journal beneath dopamine.",
  base16 = {
    base00 = palette.paperVoid,
    base01 = palette.paperDark,
    base02 = palette.paperDeep,
    base03 = palette.paperMid,
    base04 = palette.scrollBright,
    base05 = palette.scrollLightest,
    base06 = palette.pensiveDim,
    base07 = palette.pensiveCore,
    base08 = palette.brushBright,
    base09 = palette.brushMid,
    base0A = palette.brushDeep,
    base0B = palette.scrollLighter,
    base0C = palette.brushPulse,
    base0D = palette.scrollMid,
    base0E = palette.brushPulse,
    base0F = palette.scrollMid,
  },
  palette = palette,
  get = M.get,
}
