local color = require("prismpunk.utils.color")

local palette = {

  bg_darkest = "#041022",
  bg_darker = "#081427",
  bg_dark = "#111827",
  bg_mid = "#182230",
  bg_light = "#28333B",
  bg_lighter = "#6B7780",
  bg_lightest = "#B4C4CF",

  fg_lightest = "#6B7780",
  fg_light = "#B4C4CF",
  fg_mid = "#E8F4FF",
  fg_dark = "#FFF7E6",

  bg_alt1 = "#0C1523",
  bg_alt2 = "#060F1D",
  bg_alt3 = "#141D2D",
  bg_alt4 = "#0E1828",

  solarBlue = "#1E6FBF",
  skyAzure = "#2F7FBF",
  capeRed = "#D73A3A",
  emblemGold = "#FFD35A",
  justiceYellow = "#FFEA8A",
  fortressSilver = "#D9E6F0",
  kryptonCrimson = "#FF6666",
  solarFlare = "#FFD28A",
  hopeBlue = "#61AFEF",
  steelResolve = "#7FA3B8",
  azureBright = "#6FBFFF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.capeRed,
      insert = plt.kryptonCrimson,
      visual = plt.emblemGold,
      replace = plt.solarBlue,
      command = plt.skyAzure,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.capeRed,
      bg_visual = plt.solarBlue,
      bg_statusline = plt.bg_light,
      border = plt.currentGray,
      header1 = plt.capeRed,
      header2 = plt.emblemGold,
      special = plt.kryptonCrimson,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.capeRed,
      indent = plt.bg_lighter,
      indent_scope = plt.capeRed,
      picker = plt.emblemGold,
      yank = plt.solarFlare,
      mark = plt.kryptonCrimson,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.capeRed,
        bg_alternate = plt.bg_darkest,
        indicator = plt.emblemGold,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.currentGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.capeRed,
      accent2 = plt.emblemGold,
      accent3 = plt.kryptonCrimson,
      accent4 = plt.solarBlue,
      accent5 = plt.skyAzure,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.capeRed,
      rainbow2 = plt.emblemGold,
      rainbow3 = plt.kryptonCrimson,
      rainbow4 = plt.justiceYellow,
      rainbow5 = plt.solarBlue,
      rainbow6 = plt.azureBright,
      rainbow7 = plt.skyAzure,
    },

    syn = {
      attribute = plt.solarFlare,
      boolean = plt.kryptonCrimson,
      comment = plt.fg_dark,
      constant = plt.capeRed,
      deprecated = plt.fg_mid,
      func = plt.emblemGold,
      identifier = plt.fg_lightest,
      keyword = plt.capeRed,
      method = plt.justiceYellow,
      number = plt.skyAzure,
      operator = plt.steelResolve,
      parameter = plt.fg_mid,
      preproc = plt.emblemGold,
      punct = plt.fg_mid,
      regex = plt.solarFlare,
      statement = plt.capeRed,
      string = plt.solarBlue,
      symbol = plt.steelResolve,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
      special = plt.solarFlare,
      special2 = plt.emblemGold,
      special3 = plt.capeRed,
    },

    vcs = {
      added = plt.kryptonCrimson,
      removed = plt.skyAzure,
      changed = plt.capeRed,
    },

    diff = {
      add = plt.kryptonCrimson,
      change = plt.capeRed,
      delete = plt.skyAzure,
      text = plt.emblemGold,
    },

    diag = {
      ok = plt.kryptonCrimson,
      error = plt.skyAzure,
      warning = plt.solarFlare,
      info = plt.hopeBlue,
      hint = plt.kryptonCrimson,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.emblemGold,
      green = plt.kryptonCrimson,
      yellow = plt.solarBlue,
      blue = plt.capeRed,
      magenta = plt.steelResolve,
      cyan = plt.azureBright,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.emblemGold):brighten(0.2):to_hex(),
      green_bright = color(plt.kryptonCrimson):brighten(0.1):to_hex(),
      yellow_bright = color(plt.solarBlue):brighten(0.2):to_hex(),
      blue_bright = color(plt.capeRed):brighten(0.3):to_hex(),
      magenta_bright = color(plt.steelResolve):brighten(0.2):to_hex(),
      cyan_bright = color(plt.azureBright):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.capeRed,
      indexed2 = plt.emblemGold,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.skyAzure,
      ["@comment.warning"] = plt.solarFlare,
      ["@comment.todo"] = plt.capeRed,
      ["@comment.note"] = plt.kryptonCrimson,

      ["@constant"] = plt.capeRed,
      ["@constant.builtin"] = plt.capeRed,
      ["@constant.macro"] = plt.solarFlare,

      ["@string"] = plt.solarBlue,
      ["@string.documentation"] = plt.solarBlue,
      ["@string.regex"] = plt.solarFlare,
      ["@string.escape"] = plt.justiceYellow,
      ["@string.special"] = plt.kryptonCrimson,
      ["@string.special.symbol"] = plt.steelResolve,
      ["@string.special.url"] = plt.azureBright,
      ["@string.special.path"] = plt.solarBlue,

      ["@character"] = plt.solarBlue,
      ["@character.special"] = plt.justiceYellow,

      ["@number"] = plt.skyAzure,
      ["@number.float"] = plt.skyAzure,

      ["@boolean"] = plt.kryptonCrimson,

      ["@function"] = plt.emblemGold,
      ["@function.builtin"] = plt.emblemGold,
      ["@function.call"] = plt.emblemGold,
      ["@function.macro"] = plt.justiceYellow,
      ["@function.method"] = plt.justiceYellow,
      ["@function.method.call"] = plt.justiceYellow,

      ["@constructor"] = plt.fg_lightest,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.capeRed,
      ["@keyword.coroutine"] = plt.justiceYellow,
      ["@keyword.function"] = plt.capeRed,
      ["@keyword.operator"] = plt.steelResolve,
      ["@keyword.return"] = plt.capeRed,
      ["@keyword.import"] = plt.emblemGold,
      ["@keyword.storage"] = plt.capeRed,
      ["@keyword.repeat"] = plt.capeRed,
      ["@keyword.conditional"] = plt.capeRed,
      ["@keyword.exception"] = plt.capeRed,
      ["@keyword.directive"] = plt.emblemGold,
      ["@keyword.directive.define"] = plt.emblemGold,

      ["@conditional"] = plt.capeRed,
      ["@conditional.ternary"] = plt.capeRed,

      ["@repeat"] = plt.capeRed,

      ["@label"] = plt.azureBright,

      ["@operator"] = plt.steelResolve,

      ["@exception"] = plt.capeRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.azureBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.fg_lightest,
      ["@type.builtin"] = plt.fg_lightest,
      ["@type.definition"] = plt.fg_lightest,
      ["@type.qualifier"] = plt.capeRed,

      ["@attribute"] = plt.solarFlare,
      ["@attribute.builtin"] = plt.justiceYellow,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.fg_lightest,
      ["@module.builtin"] = plt.fg_lightest,

      ["@namespace"] = plt.fg_lightest,
      ["@namespace.builtin"] = plt.fg_lightest,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.steelResolve,

      ["@tag"] = plt.capeRed,
      ["@tag.attribute"] = plt.solarFlare,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.capeRed,

      ["@markup.strong"] = { fg = plt.capeRed, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.kryptonCrimson, underline = true },
      ["@markup.heading"] = plt.capeRed,
      ["@markup.heading.1"] = plt.capeRed,
      ["@markup.heading.2"] = plt.emblemGold,
      ["@markup.heading.3"] = plt.kryptonCrimson,
      ["@markup.heading.4"] = plt.justiceYellow,
      ["@markup.heading.5"] = plt.solarBlue,
      ["@markup.heading.6"] = plt.azureBright,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.kryptonCrimson,
      ["@markup.link"] = plt.azureBright,
      ["@markup.link.label"] = plt.kryptonCrimson,
      ["@markup.link.url"] = plt.azureBright,
      ["@markup.raw"] = plt.solarBlue,
      ["@markup.raw.block"] = plt.solarBlue,
      ["@markup.list"] = plt.capeRed,
      ["@markup.list.checked"] = plt.kryptonCrimson,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.kryptonCrimson,
      ["@diff.minus"] = plt.skyAzure,
      ["@diff.delta"] = plt.capeRed,

      ["@none"] = "none",
      ["@conceal"] = plt.azureBright,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.fg_lightest,
      ["@constructor.javascript"] = plt.fg_lightest,
      ["@constructor.typescript"] = plt.fg_lightest,
      ["@namespace.rust"] = plt.fg_lightest,
      ["@type.qualifier.rust"] = plt.capeRed,
      ["@constant.macro.c"] = plt.solarFlare,
      ["@constant.macro.cpp"] = plt.solarFlare,
      ["@namespace.go"] = plt.fg_lightest,
      ["@property.css"] = plt.justiceYellow,
      ["@type.css"] = plt.capeRed,
      ["@label.json"] = plt.fg_lightest,
      ["@field.yaml"] = plt.justiceYellow,
      ["@property.toml"] = plt.justiceYellow,
      ["@function.builtin.bash"] = plt.emblemGold,
      ["@string.regexp"] = plt.solarFlare,
      ["@character.special.regex"] = plt.justiceYellow,
    },

    lsp = {
      ["@lsp.type.class"] = plt.fg_lightest,
      ["@lsp.type.interface"] = plt.fg_lightest,
      ["@lsp.type.struct"] = plt.fg_lightest,
      ["@lsp.type.enum"] = plt.fg_lightest,
      ["@lsp.type.enumMember"] = plt.capeRed,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.fg_lightest,

      ["@lsp.type.macro"] = plt.solarFlare,
      ["@lsp.type.decorator"] = plt.fg_lightest,

      ["@lsp.type.builtinType"] = plt.fg_lightest,
      ["@lsp.type.selfParameter"] = plt.azureBright,
      ["@lsp.type.typeParameter"] = plt.fg_lightest,

      ["@lsp.type.array"] = plt.fg_lightest,
      ["@lsp.type.object"] = plt.fg_lightest,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.capeRed,
      ["@lsp.type.enumConstant"] = plt.capeRed,

      ["@lsp.type.event"] = plt.fg_lightest,
      ["@lsp.type.regexp"] = plt.solarFlare,
      ["@lsp.type.unresolvedReference"] = plt.justiceYellow,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.capeRed,
      ["@lsp.mod.async"] = plt.capeRed,
      ["@lsp.mod.static"] = plt.azureBright,
      ["@lsp.mod.abstract"] = plt.fg_lightest,
      ["@lsp.mod.defaultLibrary"] = plt.fg_lightest,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Injustice League – Bizarro",
  author = "PrismPunk.nvim",
  description = "Me am not hero — backwards Superman with inverted logic.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.skyAzure,
    base09 = palette.justiceYellow,
    base0A = palette.solarBlue,
    base0B = palette.kryptonCrimson,
    base0C = palette.azureBright,
    base0D = palette.emblemGold,
    base0E = palette.steelResolve,
    base0F = palette.capeRed,
  },

  palette = palette,
  get = M.get,
}
