local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0E14",
  arctic_void = "#0D131C",
  cold_core = "#111D2B",
  frost_glow = "#162538",
  parka_blue = "#0088FF",
  regime_blue = "#0099FF",
  absolute_zero = "#00AAFF",
  cryo_bright = "#33BBFF",
  frost_white = "#CCFFFF",
  goggles_white = "#E0FFFF",
  arctic_ice = "#F0FFFF",
  frozen_core = "#AADDFF",
  cryo_teal = "#00CCDD",
  freeze_pulse = "#00DDFF",
  subzero_teal = "#00EEFF",
  liquid_nitrogen = "#44FFFF",
  frozen_blood = "#AA1133",
  cryo_red = "#CC2255",
  execution_red = "#FF3366",
  frostbite_red = "#FF5588",
  cold_steel = "#445566",
  gunmetal = "#667788",
  cryo_chamber = "#223344",
  term_blue = "#0099FF",
  term_teal = "#00DDFF",
  term_red = "#FF3366",
  term_cyan = "#44FFFF",
  term_white = "#CCFFFF",
  term_grey = "#667788",
  term_blue_bright = "#33BBFF",
  term_teal_bright = "#00FFEE",
  term_red_bright = "#FF6688",
  term_cyan_bright = "#88FFFF",
  term_white_bright = "#FFFFFF",

  bg_darkest = "#0A0E14",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.regime_blue,
      insert = plt.execution_red,
      visual = plt.subzero_teal,
      replace = plt.frostbite_red,
      command = plt.absolute_zero,
    },

    ui = {
      fg = plt.goggles_white,
      fg_dim = plt.frost_white,
      fg_dimmer = plt.frozen_core,
      fg_dark = plt.cold_steel,
      fg_reverse = plt.void_black,

      bg_m4 = plt.frost_glow,
      bg_m3 = plt.cold_core,
      bg_m2 = plt.arctic_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.arctic_void,
      bg_p2 = plt.cold_core,
      bg_gutter = opts.gutter and plt.cold_core or "none",
      bg_cursorline = plt.cold_core,
      bg_cursorline_alt = plt.arctic_void,
      bg_search = plt.freeze_pulse,
      bg_visual = plt.frozen_blood,
      bg_statusline = plt.cold_core,

      border = plt.frost_white,
      header1 = plt.regime_blue,
      header2 = plt.execution_red,
      special = plt.subzero_teal,
      nontext = plt.arctic_void,
      whitespace = plt.frost_glow,
      win_separator = plt.frost_white,
      indent = plt.arctic_void,
      indent_scope = plt.arctic_ice,
      picker = plt.cryo_bright,
      yank = plt.frostbite_red,
      mark = plt.execution_red,
      scrollbar = plt.cold_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.goggles_white,
        bg_selected = plt.cold_core,
        fg_inactive = plt.frozen_core,
        bg_inactive = plt.void_black,
        fg_alternate = plt.regime_blue,
        bg_alternate = plt.void_black,
        indicator = plt.execution_red,
      },

      pmenu = {
        fg = plt.goggles_white,
        fg_sel = "none",
        fg_border = plt.cold_core,
        bg_border = plt.cold_core,
        bg = plt.cold_core,
        bg_sel = plt.arctic_void,
        bg_sbar = plt.cold_core,
        bg_thumb = plt.frost_white,
      },

      float = {
        fg = plt.goggles_white,
        bg = plt.arctic_void,
        fg_border = plt.cold_core,
        bg_border = plt.arctic_void,
      },
    },

    accent = {
      accent1 = plt.regime_blue,
      accent2 = plt.execution_red,
      accent3 = plt.subzero_teal,
      accent4 = plt.absolute_zero,
      accent5 = plt.freeze_pulse,
      invert = plt.cold_core,
    },

    rainbow = {
      rainbow1 = plt.regime_blue,
      rainbow2 = plt.absolute_zero,
      rainbow3 = plt.cryo_bright,
      rainbow4 = plt.subzero_teal,
      rainbow5 = plt.freeze_pulse,
      rainbow6 = plt.execution_red,
      rainbow7 = plt.frostbite_red,
    },

    syn = {
      attribute = plt.goggles_white,
      boolean = plt.frozen_blood,
      comment = plt.cold_steel,
      constant = plt.frost_white,
      deprecated = plt.frost_glow,
      func = plt.regime_blue,
      identifier = plt.goggles_white,
      keyword = plt.regime_blue,
      method = plt.subzero_teal,
      number = plt.execution_red,
      operator = plt.freeze_pulse,
      parameter = plt.cold_steel,
      preproc = plt.cryo_red,
      punct = plt.frost_white,
      regex = plt.liquid_nitrogen,
      statement = plt.regime_blue,
      string = plt.arctic_ice,
      symbol = plt.goggles_white,
      type = plt.subzero_teal,
      variable = plt.goggles_white,
      special = plt.frostbite_red,
      special2 = plt.freeze_pulse,
      special3 = plt.execution_red,
    },

    vcs = { added = plt.liquid_nitrogen, removed = plt.frozen_blood, changed = plt.subzero_teal },
    diff = {
      add = plt.liquid_nitrogen,
      change = plt.freeze_pulse,
      delete = plt.execution_red,
      text = plt.frostbite_red,
    },
    diag = {
      ok = plt.liquid_nitrogen,
      error = plt.execution_red,
      warning = plt.regime_blue,
      info = plt.subzero_teal,
      hint = plt.freeze_pulse,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_teal,
      yellow = plt.term_blue,
      blue = plt.term_blue,
      magenta = plt.term_teal,
      cyan = plt.term_cyan,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_teal_bright,
      yellow_bright = plt.term_blue_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_teal_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = plt.term_white_bright,
      indexed1 = plt.regime_blue,
      indexed2 = plt.execution_red,
    },

    treesitter = {
      ["@comment"] = plt.cold_steel,
      ["@comment.documentation"] = plt.frost_white,
      ["@comment.error"] = plt.execution_red,
      ["@comment.warning"] = plt.frostbite_red,
      ["@comment.todo"] = plt.regime_blue,
      ["@comment.note"] = plt.subzero_teal,

      ["@constant"] = plt.frost_white,
      ["@constant.builtin"] = plt.frost_white,
      ["@constant.macro"] = plt.execution_red,

      ["@string"] = plt.arctic_ice,
      ["@string.documentation"] = plt.arctic_ice,
      ["@string.regex"] = plt.liquid_nitrogen,
      ["@string.escape"] = plt.freeze_pulse,
      ["@string.special"] = plt.frozen_blood,
      ["@string.special.symbol"] = plt.goggles_white,
      ["@string.special.url"] = plt.subzero_teal,
      ["@string.special.path"] = plt.arctic_ice,

      ["@character"] = plt.arctic_ice,
      ["@character.special"] = plt.freeze_pulse,

      ["@number"] = plt.execution_red,
      ["@number.float"] = plt.execution_red,

      ["@boolean"] = plt.frozen_blood,

      ["@function"] = plt.regime_blue,
      ["@function.builtin"] = plt.regime_blue,
      ["@function.call"] = plt.regime_blue,
      ["@function.macro"] = plt.subzero_teal,
      ["@function.method"] = plt.subzero_teal,
      ["@function.method.call"] = plt.subzero_teal,

      ["@constructor"] = plt.goggles_white,

      ["@parameter"] = plt.cold_steel,
      ["@parameter.builtin"] = plt.goggles_white,

      ["@keyword"] = plt.regime_blue,
      ["@keyword.coroutine"] = plt.frozen_blood,
      ["@keyword.function"] = plt.regime_blue,
      ["@keyword.operator"] = plt.freeze_pulse,
      ["@keyword.return"] = plt.regime_blue,
      ["@keyword.import"] = plt.liquid_nitrogen,
      ["@keyword.storage"] = plt.regime_blue,
      ["@keyword.repeat"] = plt.regime_blue,
      ["@keyword.conditional"] = plt.regime_blue,
      ["@keyword.exception"] = plt.frostbite_red,
      ["@keyword.directive"] = plt.cryo_red,
      ["@keyword.directive.define"] = plt.cryo_red,

      ["@conditional"] = plt.regime_blue,
      ["@conditional.ternary"] = plt.regime_blue,

      ["@repeat"] = plt.regime_blue,

      ["@label"] = plt.subzero_teal,

      ["@operator"] = plt.freeze_pulse,

      ["@exception"] = plt.frostbite_red,

      ["@variable"] = plt.goggles_white,
      ["@variable.builtin"] = plt.frost_white,
      ["@variable.parameter"] = plt.cold_steel,
      ["@variable.member"] = plt.goggles_white,

      ["@type"] = plt.subzero_teal,
      ["@type.builtin"] = plt.subzero_teal,
      ["@type.definition"] = plt.subzero_teal,
      ["@type.qualifier"] = plt.regime_blue,

      ["@attribute"] = plt.goggles_white,
      ["@attribute.builtin"] = plt.subzero_teal,

      ["@property"] = plt.goggles_white,
      ["@field"] = plt.goggles_white,
      ["@module"] = plt.goggles_white,
      ["@module.builtin"] = plt.goggles_white,
      ["@namespace"] = plt.goggles_white,
      ["@namespace.builtin"] = plt.goggles_white,

      ["@punctuation.delimiter"] = plt.frost_white,
      ["@punctuation.bracket"] = plt.frozen_core,
      ["@punctuation.special"] = plt.freeze_pulse,

      ["@tag"] = plt.regime_blue,
      ["@tag.attribute"] = plt.subzero_teal,
      ["@tag.delimiter"] = plt.frost_white,
      ["@tag.builtin"] = plt.regime_blue,

      ["@markup.strong"] = { fg = plt.regime_blue, bold = true },
      ["@markup.italic"] = { fg = plt.goggles_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.frost_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.execution_red, underline = true },
      ["@markup.heading"] = plt.regime_blue,
      ["@markup.heading.1"] = plt.regime_blue,
      ["@markup.heading.2"] = plt.absolute_zero,
      ["@markup.heading.3"] = plt.subzero_teal,
      ["@markup.heading.4"] = plt.freeze_pulse,
      ["@markup.heading.5"] = plt.execution_red,
      ["@markup.heading.6"] = plt.frostbite_red,
      ["@markup.quote"] = plt.cold_steel,
      ["@markup.math"] = plt.liquid_nitrogen,
      ["@markup.link"] = plt.freeze_pulse,
      ["@markup.link.label"] = plt.frostbite_red,
      ["@markup.link.url"] = plt.subzero_teal,
      ["@markup.raw"] = plt.arctic_ice,
      ["@markup.raw.block"] = plt.arctic_ice,
      ["@markup.list"] = plt.regime_blue,
      ["@markup.list.checked"] = plt.liquid_nitrogen,
      ["@markup.list.unchecked"] = plt.cold_steel,

      ["@diff.plus"] = plt.liquid_nitrogen,
      ["@diff.minus"] = plt.frozen_blood,
      ["@diff.delta"] = plt.subzero_teal,

      ["@none"] = "none",
      ["@conceal"] = plt.frost_white,
      ["@spell"] = plt.goggles_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.goggles_white,
      ["@constructor.python"] = plt.regime_blue,
      ["@constructor.javascript"] = plt.regime_blue,
      ["@constructor.typescript"] = plt.regime_blue,
      ["@namespace.rust"] = plt.goggles_white,
      ["@type.qualifier.rust"] = plt.regime_blue,
      ["@constant.macro.c"] = plt.execution_red,
      ["@constant.macro.cpp"] = plt.execution_red,
      ["@namespace.go"] = plt.goggles_white,
      ["@property.css"] = plt.subzero_teal,
      ["@type.css"] = plt.regime_blue,
      ["@label.json"] = plt.goggles_white,
      ["@field.yaml"] = plt.cold_steel,
      ["@property.toml"] = plt.cold_steel,
      ["@function.builtin.bash"] = plt.subzero_teal,
      ["@string.regexp"] = plt.liquid_nitrogen,
      ["@character.special.regex"] = plt.freeze_pulse,
    },

    lsp = {
      ["@lsp.type.class"] = plt.subzero_teal,
      ["@lsp.type.interface"] = plt.subzero_teal,
      ["@lsp.type.struct"] = plt.subzero_teal,
      ["@lsp.type.enum"] = plt.subzero_teal,
      ["@lsp.type.enumMember"] = plt.frost_white,
      ["@lsp.type.property"] = plt.goggles_white,
      ["@lsp.type.namespace"] = plt.goggles_white,

      ["@lsp.type.macro"] = plt.execution_red,
      ["@lsp.type.decorator"] = plt.regime_blue,

      ["@lsp.type.builtinType"] = plt.subzero_teal,
      ["@lsp.type.selfParameter"] = plt.regime_blue,
      ["@lsp.type.typeParameter"] = plt.subzero_teal,

      ["@lsp.type.array"] = plt.subzero_teal,
      ["@lsp.type.object"] = plt.subzero_teal,
      ["@lsp.type.key"] = plt.goggles_white,
      ["@lsp.type.null"] = plt.frost_white,
      ["@lsp.type.enumConstant"] = plt.frost_white,

      ["@lsp.type.event"] = plt.subzero_teal,
      ["@lsp.type.regexp"] = plt.liquid_nitrogen,
      ["@lsp.type.unresolvedReference"] = plt.execution_red,

      ["@lsp.mod.deprecated"] = { fg = plt.frost_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.frost_white,
      ["@lsp.mod.async"] = plt.regime_blue,
      ["@lsp.mod.static"] = plt.subzero_teal,
      ["@lsp.mod.abstract"] = plt.subzero_teal,
      ["@lsp.mod.defaultLibrary"] = plt.subzero_teal,
      ["@lsp.mod.documentation"] = plt.cold_steel,
    },
  }
end

return {
  name = "Injustice Captain Cold – Absolute Zero Enforcer",
  author = "PrismPunk.nvim",
  description = "In Superman’s Regime, Captain Cold doesn’t steal. He executes. "
    .. "One shot from the cold gun and you’re a statue. Forever.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.arctic_void,
    base02 = palette.cold_core,
    base03 = palette.frost_glow,
    base04 = palette.cold_steel,
    base05 = palette.frost_white,
    base06 = palette.goggles_white,
    base07 = palette.arctic_ice,
    base08 = palette.execution_red,
    base09 = palette.regime_blue,
    base0A = palette.absolute_zero,
    base0B = palette.subzero_teal,
    base0C = palette.freeze_pulse,
    base0D = palette.liquid_nitrogen,
    base0E = palette.frostbite_red,
    base0F = palette.frozen_blood,
  },

  palette = palette,
  get = M.get,
}
