local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0C08",
  jungle_void = "#0E120B",
  grodd_throne = "#131A10",
  psychic_glow = "#1A2418",
  gorilla_fur = "#1E2B18",
  jungle_green = "#2D4422",
  grodd_green = "#3B6633",
  ape_dominator = "#558844",
  psychic_red = "#FF1122",
  mind_fire = "#FF3333",
  telepath_rage = "#FF5555",
  brain_burn = "#FF7766",
  grodd_eyes = "#FF0000",
  royal_gold = "#FFDD00",
  crown_bright = "#FFEA33",
  empire_gold = "#CCAA00",
  throne_gold = "#AA8800",
  fresh_blood = "#AA0011",
  gorilla_rage = "#CC1122",
  conquest_red = "#EE2233",
  vine_shadow = "#223322",
  deep_jungle = "#112211",
  moss_teal = "#448866",
  term_red = "#FF3333",
  term_green = "#558844",
  term_yellow = "#FFEA33",
  term_blue = "#4488CC",
  term_purple = "#AA44FF",
  term_cyan = "#44AA99",
  term_magenta = "#FF4488",
  term_red_bright = "#FF6666",
  term_green_bright = "#77AA66",
  term_yellow_bright = "#FFFF66",
  term_blue_bright = "#66AAFF",
  term_purple_bright = "#CC66FF",
  term_cyan_bright = "#66CCCC",

  bg_darkest = "#0A0C08",
  fg_lightest = "#FFFF66",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.psychic_red,
      insert = plt.royal_gold,
      visual = plt.grodd_green,
      replace = plt.conquest_red,
      command = plt.telepath_rage,
    },

    ui = {
      fg = plt.crown_bright,
      fg_dim = plt.royal_gold,
      fg_dimmer = plt.empire_gold,
      fg_dark = plt.ape_dominator,
      fg_reverse = plt.void_black,

      bg_m4 = plt.psychic_glow,
      bg_m3 = plt.grodd_throne,
      bg_m2 = plt.jungle_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.jungle_void,
      bg_p2 = plt.grodd_throne,
      bg_gutter = opts.gutter and plt.grodd_throne or "none",
      bg_cursorline = plt.grodd_throne,
      bg_cursorline_alt = plt.jungle_void,
      bg_search = plt.brain_burn,
      bg_visual = plt.gorilla_rage,
      bg_statusline = plt.grodd_throne,

      border = plt.royal_gold,
      header1 = plt.psychic_red,
      header2 = plt.royal_gold,
      special = plt.mind_fire,
      nontext = plt.jungle_void,
      whitespace = plt.psychic_glow,
      win_separator = plt.royal_gold,
      indent = plt.jungle_void,
      indent_scope = plt.empire_gold,
      picker = plt.crown_bright,
      yank = plt.telepath_rage,
      mark = plt.grodd_eyes,
      scrollbar = plt.grodd_throne,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.crown_bright,
        bg_selected = plt.grodd_throne,
        fg_inactive = plt.empire_gold,
        bg_inactive = plt.void_black,
        fg_alternate = plt.psychic_red,
        bg_alternate = plt.void0F,
        indicator = plt.gorilla_rage,
      },

      pmenu = {
        fg = plt.crown_bright,
        fg_sel = "none",
        fg_border = plt.grodd_throne,
        bg_border = plt.grodd_throne,
        bg = plt.grodd_throne,
        bg_sel = plt.jungle_void,
        bg_sbar = plt.grodd_throne,
        bg_thumb = plt.royal_gold,
      },

      float = {
        fg = plt.crown_bright,
        bg = plt.jungle_void,
        fg_border = plt.grodd_throne,
        bg_border = plt.jungle_void,
      },
    },

    accent = {
      accent1 = plt.psychic_red,
      accent2 = plt.royal_gold,
      accent3 = plt.grodd_green,
      accent4 = plt.conquest_red,
      accent5 = plt.mind_fire,
      invert = plt.grodd_throne,
    },

    rainbow = {
      rainbow1 = plt.psychic_red,
      rainbow2 = plt.mind_fire,
      rainbow3 = plt.telepath_rage,
      rainbow4 = plt.royal_gold,
      rainbow5 = plt.crown_bright,
      rainbow6 = plt.grodd_green,
      rainbow7 = plt.ape_dominator,
    },

    syn = {
      attribute = plt.crown_bright,
      boolean = plt.gorilla_rage,
      comment = plt.empire_gold,
      constant = plt.crown_bright,
      deprecated = plt.psychic_glow,
      func = plt.psychic_red,
      identifier = plt.crown_bright,
      keyword = plt.psychic_red,
      method = plt.royal_gold,
      number = plt.brain_burn,
      operator = plt.telepath_rage,
      parameter = plt.empire_gold,
      preproc = plt.conquest_red,
      punct = plt.royal_gold,
      regex = plt.mind_fire,
      statement = plt.psychic_red,
      string = plt.moss_teal,
      symbol = plt.crown_bright,
      type = plt.grodd_green,
      variable = plt.crown_bright,
      special = plt.grodd_eyes,
      special2 = plt.telepath_rage,
      special3 = plt.gorilla_rage,
    },

    vcs = { added = plt.moss_teal, removed = plt.gorilla_rage, changed = plt.royal_gold },
    diff = { add = plt.moss_teal, change = plt.brain_burn, delete = plt.fresh_blood, text = plt.telepath_rage },
    diag = {
      ok = plt.moss_teal,
      error = plt.grodd_eyes,
      warning = plt.royal_gold,
      info = plt.psychic_red,
      hint = plt.mind_fire,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_purple,
      cyan = plt.term_cyan,
      white = plt.crown_bright,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_purple_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.psychic_red,
      indexed2 = plt.royal_gold,
    },

    treesitter = {
      ["@comment"] = plt.empire_gold,
      ["@comment.documentation"] = plt.crown_bright,
      ["@comment.error"] = plt.grodd_eyes,
      ["@comment.warning"] = plt.telepath_rage,
      ["@comment.todo"] = plt.psychic_red,
      ["@comment.note"] = plt.moss_teal,

      ["@constant"] = plt.crown_bright,
      ["@constant.builtin"] = plt.crown_bright,
      ["@constant.macro"] = plt.brain_burn,

      ["@string"] = plt.moss_teal,
      ["@string.documentation"] = plt.moss_teal,
      ["@string.regex"] = plt.mind_fire,
      ["@string.escape"] = plt.telepath_rage,
      ["@string.special"] = plt.gorilla_rage,
      ["@string.special.symbol"] = plt.royal_gold,
      ["@string.special.url"] = plt.psychic_red,
      ["@string.special.path"] = plt.moss_teal,

      ["@character"] = plt.moss_teal,
      ["@character.special"] = plt.telepath_rage,

      ["@number"] = plt.brain_burn,
      ["@number.float"] = plt.brain_burn,

      ["@boolean"] = plt.gorilla_rage,

      ["@function"] = plt.psychic_red,
      ["@function.builtin"] = plt.psychic_red,
      ["@function.call"] = plt.psychic_red,
      ["@function.macro"] = plt.royal_gold,
      ["@function.method"] = plt.royal_gold,
      ["@function.method.call"] = plt.royal_gold,

      ["@constructor"] = plt.crown_bright,

      ["@parameter"] = plt.empire_gold,
      ["@parameter.builtin"] = plt.crown_bright,

      ["@keyword"] = plt.psychic_red,
      ["@keyword.coroutine"] = plt.gorilla_rage,
      ["@keyword.function"] = plt.psychic_red,
      ["@keyword.operator"] = plt.telepath_rage,
      ["@keyword.return"] = plt.psychic_red,
      ["@keyword.import"] = plt.moss_teal,
      ["@keyword.storage"] = plt.psychic_red,
      ["@keyword.repeat"] = plt.psychic_red,
      ["@keyword.conditional"] = plt.psychic_red,
      ["@keyword.exception"] = plt.grodd_eyes,
      ["@keyword.directive"] = plt.conquest_red,
      ["@keyword.directive.define"] = plt.conquest_red,

      ["@conditional"] = plt.psychic_red,
      ["@conditional.ternary"] = plt.psychic_red,

      ["@repeat"] = plt.psychic_red,

      ["@label"] = plt.royal_gold,

      ["@operator"] = plt.telepath_rage,

      ["@exception"] = plt.grodd_eyes,

      ["@variable"] = plt.crown_bright,
      ["@variable.builtin"] = plt.royal_gold,
      ["@variable.parameter"] = plt.empire_gold,
      ["@variable.member"] = plt.crown_bright,

      ["@type"] = plt.grodd_green,
      ["@type.builtin"] = plt.grodd_green,
      ["@type.definition"] = plt.grodd_green,
      ["@type.qualifier"] = plt.psychic_red,

      ["@attribute"] = plt.crown_bright,
      ["@attribute.builtin"] = plt.grodd_green,

      ["@property"] = plt.crown_bright,
      ["@field"] = plt.crown_bright,
      ["@module"] = plt.crown_bright,
      ["@module.builtin"] = plt.crown_bright,
      ["@namespace"] = plt.crown_bright,
      ["@namespace.builtin"] = plt.crown_bright,

      ["@punctuation.delimiter"] = plt.royal_gold,
      ["@punctuation.bracket"] = plt.empire_gold,
      ["@punctuation.special"] = plt.telepath_rage,

      ["@tag"] = plt.psychic_red,
      ["@tag.attribute"] = plt.grodd_green,
      ["@tag.delimiter"] = plt.royal_gold,
      ["@tag.builtin"] = plt.psychic_red,

      ["@markup.strong"] = { fg = plt.psychic_red, bold = true },
      ["@markup.italic"] = { fg = plt.crown_bright, italic = true },
      ["@markup.strikethrough"] = { fg = plt.psychic_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.telepath_rage, underline = true },
      ["@markup.heading"] = plt.psychic_red,
      ["@markup.heading.1"] = plt.grodd_eyes,
      ["@markup.heading.2"] = plt.psychic_red,
      ["@markup.heading.3"] = plt.telepath_rage,
      ["@markup.heading.4"] = plt.royal_gold,
      ["@markup.heading.5"] = plt.crown_bright,
      ["@markup.heading.6"] = plt.grodd_green,
      ["@markup.quote"] = plt.empire_gold,
      ["@markup.math"] = plt.brain_burn,
      ["@markup.link"] = plt.mind_fire,
      ["@markup.link.label"] = plt.telepath_rage,
      ["@markup.link.url"] = plt.psychic_red,
      ["@markup.raw"] = plt.moss_teal,
      ["@markup.raw.block"] = plt.moss_teal,
      ["@markup.list"] = plt.psychic_red,
      ["@markup.list.checked"] = plt.moss_teal,
      ["@markup.list.unchecked"] = plt.empire_gold,

      ["@diff.plus"] = plt.moss_teal,
      ["@diff.minus"] = plt.gorilla_rage,
      ["@diff.delta"] = plt.brain_burn,

      ["@none"] = "none",
      ["@conceal"] = plt.royal_gold,
      ["@spell"] = plt.crown_bright,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.crown_bright,
      ["@constructor.python"] = plt.psychic_red,
      ["@constructor.javascript"] = plt.psychic_red,
      ["@constructor.typescript"] = plt.psychic_red,
      ["@namespace.rust"] = plt.crown_bright,
      ["@type.qualifier.rust"] = plt.psychic_red,
      ["@constant.macro.c"] = plt.brain_burn,
      ["@constant.macro.cpp"] = plt.brain_burn,
      ["@namespace.go"] = plt.crown_bright,
      ["@property.css"] = plt.royal_gold,
      ["@type.css"] = plt.psychic_red,
      ["@label.json"] = plt.crown_bright,
      ["@field.yaml"] = plt.empire_gold,
      ["@property.toml"] = plt.empire_gold,
      ["@function.builtin.bash"] = plt.royal_gold,
      ["@string.regexp"] = plt.mind_fire,
      ["@character.special.regex"] = plt.telepath_rage,
    },

    lsp = {
      ["@lsp.type.class"] = plt.grodd_green,
      ["@lsp.type.interface"] = plt.grodd_green,
      ["@lsp.type.struct"] = plt.grodd_green,
      ["@lsp.type.enum"] = plt.grodd_green,
      ["@lsp.type.enumMember"] = plt.crown_bright,
      ["@lsp.type.property"] = plt.crown_bright,
      ["@lsp.type.namespace"] = plt.crown_bright,

      ["@lsp.type.macro"] = plt.brain_burn,
      ["@lsp.type.decorator"] = plt.psychic_red,

      ["@lsp.type.builtinType"] = plt.grodd_green,
      ["@lsp.type.selfParameter"] = plt.psychic_red,
      ["@lsp.type.typeParameter"] = plt.grodd_green,

      ["@lsp.type.array"] = plt.grodd_green,
      ["@lsp.type.object"] = plt.grodd_green,
      ["@lsp.type.key"] = plt.crown_bright,
      ["@lsp.type.null"] = plt.crown_bright,
      ["@lsp.type.enumConstant"] = plt.crown_bright,

      ["@lsp.type.event"] = plt.grodd_green,
      ["@lsp.type.regexp"] = plt.mind_fire,
      ["@lsp.type.unresolvedReference"] = plt.grodd_eyes,

      ["@lsp.mod.deprecated"] = { fg = plt.psychic_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.crown_bright,
      ["@lsp.mod.async"] = plt.psychic_red,
      ["@lsp.mod.static"] = plt.grodd_green,
      ["@lsp.mod.abstract"] = plt.grodd_green,
      ["@lsp.mod.defaultLibrary"] = plt.grodd_green,
      ["@lsp.mod.documentation"] = plt.empire_gold,
    },
  }
end

return {
  name = "Gorilla Grodd – Ape God-King",
  author = "PrismPunk.nvim",
  description = "Bow to Grodd. His mind is fire. His crown is gold. "
    .. "His will is unbreakable. You are already his puppet.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.jungle_void,
    base02 = palette.grodd_throne,
    base03 = palette.psychic_glow,
    base04 = palette.empire_gold,
    base05 = palette.royal_gold,
    base06 = palette.crown_bright,
    base07 = palette.crown_bright,
    base08 = palette.grodd_eyes,
    base09 = palette.psychic_red,
    base0A = palette.royal_gold,
    base0B = palette.grodd_green,
    base0C = palette.moss_teal,
    base0D = palette.telepath_rage,
    base0E = palette.brain_burn,
    base0F = palette.conquest_red,
  },

  palette = palette,
  get = M.get,
}
