local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0E14",
  cryo_void = "#0C141F",
  frost_core = "#0F1D2E",
  ice_glow = "#142840",
  corpse_pale = "#CCDDFF",
  frost_skin = "#DDEEFF",
  glacial_white = "#F0F8FF",
  dead_ice = "#AACCFF",
  cryo_blue = "#0088FF",
  killer_blue = "#0099FF",
  frostfire_blue = "#00BBFF",
  absolute_cryo = "#00DDFF",
  neon_ice = "#00FFFF",
  frozen_lips = "#BB2255",
  blood_ice = "#DD3366",
  murder_red = "#FF4477",
  frostbite_pink = "#FF6699",
  lethal_white = "#E0F8FF",
  crystal_shard = "#CCFFFF",
  blizzard_white = "#FFFFFF",
  term_blue = "#00BBFF",
  term_cyan = "#00FFFF",
  term_red = "#FF4477",
  term_white = "#E0F8FF",
  term_purple = "#AA77FF",
  term_magenta = "#FF66AA",
  term_blue_bright = "#00DDFF",
  term_cyan_bright = "#88FFFF",
  term_red_bright = "#FF7799",
  term_white_bright = "#FFFFFF",

  bg_darkest = "#0A0E14",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.killer_blue,
      insert = plt.murder_red,
      visual = plt.neon_ice,
      replace = plt.frostbite_pink,
      command = plt.absolute_cryo,
    },

    ui = {
      fg = plt.corpse_pale,
      fg_dim = plt.frost_skin,
      fg_dimmer = plt.dead_ice,
      fg_dark = plt.killer_blue,
      fg_reverse = plt.void_black,

      bg_m4 = plt.ice_glow,
      bg_m3 = plt.frost_core,
      bg_m2 = plt.cryo_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.cryo_void,
      bg_p2 = plt.frost_core,
      bg_gutter = opts.gutter and plt.frost_core or "none",
      bg_cursorline = plt.frost_core,
      bg_cursorline_alt = plt.cryo_void,
      bg_search = plt.neon_ice,
      bg_visual = plt.blood_ice,
      bg_statusline = plt.frost_core,

      border = plt.glacial_white,
      header1 = plt.killer_blue,
      header2 = plt.murder_red,
      special = plt.neon_ice,
      nontext = plt.cryo_void,
      whitespace = plt.ice_glow,
      win_separator = plt.glacial_white,
      indent = plt.cryo_void,
      indent_scope = plt.corpse_pale,
      picker = plt.lethal_white,
      yank = plt.frostbite_pink,
      mark = plt.murder_red,
      scrollbar = plt.frost_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.corpse_pale,
        bg_selected = plt.frost_core,
        fg_inactive = plt.dead_ice,
        bg_inactive = plt.void_black,
        fg_alternate = plt.killer_blue,
        bg_alternate = plt.void_black,
        indicator = plt.blood_ice,
      },

      pmenu = {
        fg = plt.corpse_pale,
        fg_sel = "none",
        fg_border = plt.frost_core,
        bg_border = plt.frost_core,
        bg = plt.frost_core,
        bg_sel = plt.cryo_void,
        bg_sbar = plt.frost_core,
        bg_thumb = plt.glacial_white,
      },

      float = {
        fg = plt.corpse_pale,
        bg = plt.cryo_void,
        fg_border = plt.frost_core,
        bg_border = plt.cryo_void,
      },
    },

    accent = {
      accent1 = plt.killer_blue,
      accent2 = plt.murder_red,
      accent3 = plt.neon_ice,
      accent4 = plt.absolute_cryo,
      accent5 = plt.frostbite_pink,
      invert = plt.frost_core,
    },

    rainbow = {
      rainbow1 = plt.killer_blue,
      rainbow2 = plt.frostfire_blue,
      rainbow3 = plt.absolute_cryo,
      rainbow4 = plt.neon_ice,
      rainbow5 = plt.murder_red,
      rainbow6 = plt.blood_ice,
      rainbow7 = plt.frostbite_pink,
    },

    syn = {
      attribute = plt.corpse_pale,
      boolean = plt.frozen_lips,
      comment = plt.dead_ice,
      constant = plt.glacial_white,
      deprecated = plt.ice_glow,
      func = plt.killer_blue,
      identifier = plt.corpse_pale,
      keyword = plt.killer_blue,
      method = plt.neon_ice,
      number = plt.murder_red,
      operator = plt.absolute_cryo,
      parameter = plt.dead_ice,
      preproc = plt.blood_ice,
      punct = plt.glacial_white,
      regex = plt.neon_ice,
      statement = plt.killer_blue,
      string = plt.lethal_white,
      symbol = plt.corpse_pale,
      type = plt.neon_ice,
      variable = plt.corpse_pale,
      special = plt.frostbite_pink,
      special2 = plt.absolute_cryo,
      special3 = plt.murder_red,
    },

    vcs = { added = plt.neon_ice, removed = plt.blood_ice, changed = plt.frostfire_blue },
    diff = { add = plt.neon_ice, change = plt.absolute_cryo, delete = plt.murder_red, text = plt.frostbite_pink },
    diag = {
      ok = plt.neon_ice,
      error = plt.murder_red,
      warning = plt.killer_blue,
      info = plt.frostfire_blue,
      hint = plt.absolute_cryo,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_cyan,
      yellow = plt.term_blue,
      blue = plt.term_blue,
      magenta = plt.term_magenta,
      cyan = plt.term_cyan,
      white = plt.term_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_cyan_bright,
      yellow_bright = plt.term_blue_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_magenta,
      cyan_bright = plt.term_cyan_bright,
      white_bright = plt.term_white_bright,
      indexed1 = plt.killer_blue,
      indexed2 = plt.murder_red,
    },

    treesitter = {
      ["@comment"] = plt.dead_ice,
      ["@comment.documentation"] = plt.glacial_white,
      ["@comment.error"] = plt.murder_red,
      ["@comment.warning"] = plt.frostbite_pink,
      ["@comment.todo"] = plt.killer_blue,
      ["@comment.note"] = plt.neon_ice,

      ["@constant"] = plt.glacial_white,
      ["@constant.builtin"] = plt.glacial_white,
      ["@constant.macro"] = plt.murder_red,

      ["@string"] = plt.lethal_white,
      ["@string.documentation"] = plt.lethal_white,
      ["@string.regex"] = plt.neon_ice,
      ["@string.escape"] = plt.absolute_cryo,
      ["@string.special"] = plt.blood_ice,
      ["@string.special.symbol"] = plt.corpse_pale,
      ["@string.special.url"] = plt.killer_blue,
      ["@string.special.path"] = plt.lethal_white,

      ["@character"] = plt.lethal_white,
      ["@character.special"] = plt.absolute_cryo,

      ["@number"] = plt.murder_red,
      ["@number.float"] = plt.murder_red,

      ["@boolean"] = plt.frozen_lips,

      ["@function"] = plt.killer_blue,
      ["@function.builtin"] = plt.killer_blue,
      ["@function.call"] = plt.killer_blue,
      ["@function.macro"] = plt.neon_ice,
      ["@function.method"] = plt.neon_ice,
      ["@function.method.call"] = plt.neon_ice,

      ["@constructor"] = plt.corpse_pale,

      ["@parameter"] = plt.dead_ice,
      ["@parameter.builtin"] = plt.corpse_pale,

      ["@keyword"] = plt.killer_blue,
      ["@keyword.coroutine"] = plt.blood_ice,
      ["@keyword.function"] = plt.killer_blue,
      ["@keyword.operator"] = plt.absolute_cryo,
      ["@keyword.return"] = plt.killer_blue,
      ["@keyword.import"] = plt.neon_ice,
      ["@keyword.storage"] = plt.killer_blue,
      ["@keyword.repeat"] = plt.killer_blue,
      ["@keyword.conditional"] = plt.killer_blue,
      ["@keyword.exception"] = plt.frostbite_pink,
      ["@keyword.directive"] = plt.blood_ice,
      ["@keyword.directive.define"] = plt.blood_ice,

      ["@conditional"] = plt.killer_blue,
      ["@conditional.ternary"] = plt.killer_blue,

      ["@repeat"] = plt.killer_blue,

      ["@label"] = plt.neon_ice,

      ["@operator"] = plt.absolute_cryo,

      ["@exception"] = plt.frostbite_pink,

      ["@variable"] = plt.corpse_pale,
      ["@variable.builtin"] = plt.frost_skin,
      ["@variable.parameter"] = plt.dead_ice,
      ["@variable.member"] = plt.corpse_pale,

      ["@type"] = plt.neon_ice,
      ["@type.builtin"] = plt.neon_ice,
      ["@type.definition"] = plt.neon_ice,
      ["@type.qualifier"] = plt.killer_blue,

      ["@attribute"] = plt.corpse_pale,
      ["@attribute.builtin"] = plt.neon_ice,

      ["@property"] = plt.corpse_pale,
      ["@field"] = plt.corpse_pale,
      ["@module"] = plt.corpse_pale,
      ["@module.builtin"] = plt.corpse_pale,
      ["@namespace"] = plt.corpse_pale,
      ["@namespace.builtin"] = plt.corpse_pale,

      ["@punctuation.delimiter"] = plt.glacial_white,
      ["@punctuation.bracket"] = plt.frost_skin,
      ["@punctuation.special"] = plt.absolute_cryo,

      ["@tag"] = plt.killer_blue,
      ["@tag.attribute"] = plt.neon_ice,
      ["@tag.delimiter"] = plt.glacial_white,
      ["@tag.builtin"] = plt.killer_blue,

      ["@markup.strong"] = { fg = plt.killer_blue, bold = true },
      ["@markup.italic"] = { fg = plt.corpse_pale, italic = true },
      ["@markup.strikethrough"] = { fg = plt.ice_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.murder_red, underline = true },
      ["@markup.heading"] = plt.killer_blue,
      ["@markup.heading.1"] = plt.killer_blue,
      ["@markup.heading.2"] = plt.frostfire_blue,
      ["@markup.heading.3"] = plt.absolute_cryo,
      ["@markup.heading.4"] = plt.neon_ice,
      ["@markup.heading.5"] = plt.murder_red,
      ["@markup.heading.6"] = plt.frostbite_pink,
      ["@markup.quote"] = plt.dead_ice,
      ["@markup.math"] = plt.neon_ice,
      ["@markup.link"] = plt.absolute_cryo,
      ["@markup.link.label"] = plt.frostbite_pink,
      ["@markup.link.url"] = plt.killer_blue,
      ["@markup.raw"] = plt.lethal_white,
      ["@markup.raw.block"] = plt.lethal_white,
      ["@markup.list"] = plt.killer_blue,
      ["@markup.list.checked"] = plt.neon_ice,
      ["@markup.list.unchecked"] = plt.dead_ice,

      ["@diff.plus"] = plt.neon_ice,
      ["@diff.minus"] = plt.blood_ice,
      ["@diff.delta"] = plt.frostfire_blue,

      ["@none"] = "none",
      ["@conceal"] = plt.glacial_white,
      ["@spell"] = plt.corpse_pale,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.corpse_pale,
      ["@constructor.python"] = plt.killer_blue,
      ["@constructor.javascript"] = plt.killer_blue,
      ["@constructor.typescript"] = plt.killer_blue,
      ["@namespace.rust"] = plt.corpse_pale,
      ["@type.qualifier.rust"] = plt.killer_blue,
      ["@constant.macro.c"] = plt.murder_red,
      ["@constant.macro.cpp"] = plt.murder_red,
      ["@namespace.go"] = plt.corpse_pale,
      ["@property.css"] = plt.neon_ice,
      ["@type.css"] = plt.killer_blue,
      ["@label.json"] = plt.corpse_pale,
      ["@field.yaml"] = plt.dead_ice,
      ["@property.toml"] = plt.dead_ice,
      ["@function.builtin.bash"] = plt.neon_ice,
      ["@string.regexp"] = plt.neon_ice,
      ["@character.special.regex"] = plt.absolute_cryo,
    },

    lsp = {
      ["@lsp.type.class"] = plt.neon_ice,
      ["@lsp.type.interface"] = plt.neon_ice,
      ["@lsp.type.struct"] = plt.neon_ice,
      ["@lsp.type.enum"] = plt.neon_ice,
      ["@lsp.type.enumMember"] = plt.glacial_white,
      ["@lsp.type.property"] = plt.corpse_pale,
      ["@lsp.type.namespace"] = plt.corpse_pale,

      ["@lsp.type.macro"] = plt.murder_red,
      ["@lsp.type.decorator"] = plt.killer_blue,

      ["@lsp.type.builtinType"] = plt.neon_ice,
      ["@lsp.type.selfParameter"] = plt.killer_blue,
      ["@lsp.type.typeParameter"] = plt.neon_ice,

      ["@lsp.type.array"] = plt.neon_ice,
      ["@lsp.type.object"] = plt.neon_ice,
      ["@lsp.type.key"] = plt.corpse_pale,
      ["@lsp.type.null"] = plt.glacial_white,
      ["@lsp.type.enumConstant"] = plt.glacial_white,

      ["@lsp.type.event"] = plt.neon_ice,
      ["@lsp.type.regexp"] = plt.neon_ice,
      ["@lsp.type.unresolvedReference"] = plt.murder_red,

      ["@lsp.mod.deprecated"] = { fg = plt.ice_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.glacial_white,
      ["@lsp.mod.async"] = plt.killer_blue,
      ["@lsp.mod.static"] = plt.neon_ice,
      ["@lsp.mod.abstract"] = plt.neon_ice,
      ["@lsp.mod.defaultLibrary"] = plt.neon_ice,
      ["@lsp.mod.documentation"] = plt.dead_ice,
    },
  }
end

return {
  name = "Injustice Killer Frost – Ice Queen of the Regime",
  author = "PrismPunk.nvim",
  description = "She used to be human. Now she’s a blizzard with a smile. "
    .. "Corpse-pale skin, electric cryo-blue hair, and a heart colder than absolute zero.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.cryo_void,
    base02 = palette.frost_core,
    base03 = palette.ice_glow,
    base04 = palette.dead_ice,
    base05 = palette.frost_skin,
    base06 = palette.corpse_pale,
    base07 = palette.glacial_white,
    base08 = palette.murder_red,
    base09 = palette.killer_blue,
    base0A = palette.frostfire_blue,
    base0B = palette.absolute_cryo,
    base0C = palette.neon_ice,
    base0D = palette.blood_ice,
    base0E = palette.frostbite_pink,
    base0F = palette.frozen_lips,
  },

  palette = palette,
  get = M.get,
}
