local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A080E",
  abyss = "#0D0B14",
  nightshade_core = "#120F1C",
  ultraviolet_glow = "#1A1433",
  corpse_pale = "#E8E0FF",
  moonlit_skin = "#D8D0FF",
  porcelain_death = "#F0E8FF",
  cold_flesh = "#CCC4FF",
  fresh_blood = "#DD1133",
  arterial_spray = "#FF2244",
  vampire_lips = "#CC0033",
  dried_crimson = "#880022",
  ultraviolet_core = "#9933FF",
  nightshade_purple = "#AA44FF",
  lethal_violet = "#BB55FF",
  toxic_uv = "#CC66FF",
  ultraviolet_flash = "#DD77FF",
  obsidian_hair = "#0F0D18",
  black_lace = "#1A1722",
  shadow_velvet = "#221F33",
  stolen_moonlight = "#4488FF",
  ice_blue = "#66AAFF",
  diamond_cold = "#88CCFF",
  sapphire_theft = "#3366CC",
  fang_white = "#FFFFFF",
  venom_glow = "#FF4488",
  term_red = "#FF2244",
  term_purple = "#BB55FF",
  term_blue = "#66AAFF",
  term_cyan = "#88CCFF",
  term_green = "#44BB88",
  term_yellow = "#FFBB44",
  term_magenta = "#FF66BB",
  term_red_bright = "#FF6666",
  term_purple_bright = "#EE77FF",
  term_blue_bright = "#88BBFF",
  term_cyan_bright = "#AADDFF",
  term_green_bright = "#66DDAA",
  term_yellow_bright = "#FFDD88",

  bg_darkest = "#0A080E",
  fg_lightest = "#FFFFFF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.nightshade_purple,
      insert = plt.arterial_spray,
      visual = plt.lethal_violet,
      replace = plt.fresh_blood,
      command = plt.stolen_moonlight,
    },

    ui = {
      fg = plt.corpse_pale,
      fg_dim = plt.moonlit_skin,
      fg_dimmer = plt.cold_flesh,
      fg_dark = plt.ultraviolet_core,
      fg_reverse = plt.void_black,

      bg_m4 = plt.ultraviolet_glow,
      bg_m3 = plt.nightshade_core,
      bg_m2 = plt.abyss,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.abyss,
      bg_p2 = plt.nightshade_core,
      bg_gutter = opts.gutter and plt.nightshade_core or "none",
      bg_cursorline = plt.nightshade_core,
      bg_cursorline_alt = plt.abyss,
      bg_search = plt.ultraviolet_flash,
      bg_visual = plt.vampire_lips,
      bg_statusline = plt.nightshade_core,

      border = plt.moonlit_skin,
      header1 = plt.nightshade_purple,
      header2 = plt.arterial_spray,
      special = plt.toxic_uv,
      nontext = plt.abyss,
      whitespace = plt.ultraviolet_glow,
      win_separator = plt.moonlit_skin,
      indent = plt.abyss,
      indent_scope = plt.cold_flesh,
      picker = plt.ice_blue,
      yank = plt.venom_glow,
      mark = plt.arterial_spray,
      scrollbar = plt.nightshade_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.corpse_pale,
        bg_selected = plt.nightshade_core,
        fg_inactive = plt.cold_flesh,
        bg_inactive = plt.void_black,
        fg_alternate = plt.nightshade_purple,
        bg_alternate = plt.void_black,
        indicator = plt.arterial_spray,
      },

      pmenu = {
        fg = plt.corpse_pale,
        fg_sel = "none",
        fg_border = plt.nightshade_core,
        bg_border = plt.nightshade_core,
        bg = plt.nightshade_core,
        bg_sel = plt.abyss,
        bg_sbar = plt.nightshade_core,
        bg_thumb = plt.moonlit_skin,
      },

      float = {
        fg = plt.corpse_pale,
        bg = plt.abyss,
        fg_border = plt.nightshade_core,
        bg_border = plt.abyss,
      },
    },

    accent = {
      accent1 = plt.nightshade_purple,
      accent2 = plt.arterial_spray,
      accent3 = plt.lethal_violet,
      accent4 = plt.stolen_moonlight,
      accent5 = plt.toxic_uv,
      invert = plt.nightshade_core,
    },

    rainbow = {
      rainbow1 = plt.nightshade_purple,
      rainbow2 = plt.lethal_violet,
      rainbow3 = plt.toxic_uv,
      rainbow4 = plt.ultraviolet_flash,
      rainbow5 = plt.arterial_spray,
      rainbow6 = plt.venom_glow,
      rainbow7 = plt.stolen_moonlight,
    },

    syn = {
      attribute = plt.corpse_pale,
      boolean = plt.arterial_spray,
      comment = plt.cold_flesh,
      constant = plt.ice_blue,
      deprecated = plt.ultraviolet_glow,
      func = plt.nightshade_purple,
      identifier = plt.corpse_pale,
      keyword = plt.nightshade_purple,
      method = plt.lethal_violet,
      number = plt.venom_glow,
      operator = plt.toxic_uv,
      parameter = plt.cold_flesh,
      preproc = plt.vampire_lips,
      punct = plt.moonlit_skin,
      regex = plt.stolen_moonlight,
      statement = plt.nightshade_purple,
      string = plt.sapphire_theft,
      symbol = plt.corpse_pale,
      type = plt.lethal_violet,
      variable = plt.corpse_pale,
      special = plt.ultraviolet_flash,
      special2 = plt.toxic_uv,
      special3 = plt.arterial_spray,
    },

    vcs = { added = plt.ice_blue, removed = plt.arterial_spray, changed = plt.lethal_violet },
    diff = { add = plt.ice_blue, change = plt.stolen_moonlight, delete = plt.fresh_blood, text = plt.venom_glow },
    diag = {
      ok = plt.ice_blue,
      error = plt.arterial_spray,
      warning = plt.lethal_violet,
      info = plt.nightshade_purple,
      hint = plt.toxic_uv,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_purple,
      cyan = plt.term_cyan,
      white = plt.corpse_pale,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_purple_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.nightshade_purple,
      indexed2 = plt.arterial_spray,
    },

    treesitter = {
      ["@comment"] = plt.cold_flesh,
      ["@comment.documentation"] = plt.ice_blue,
      ["@comment.error"] = plt.arterial_spray,
      ["@comment.warning"] = plt.lethal_violet,
      ["@comment.todo"] = plt.nightshade_purple,
      ["@comment.note"] = plt.stolen_moonlight,

      ["@constant"] = plt.ice_blue,
      ["@constant.builtin"] = plt.ice_blue,
      ["@constant.macro"] = plt.venom_glow,

      ["@string"] = plt.sapphire_theft,
      ["@string.documentation"] = plt.sapphire_theft,
      ["@string.regex"] = plt.stolen_moonlight,
      ["@string.escape"] = plt.toxic_uv,
      ["@string.special"] = plt.arterial_spray,
      ["@string.special.symbol"] = plt.fang_white,
      ["@string.special.url"] = plt.nightshade_purple,
      ["@string.special.path"] = plt.sapphire_theft,

      ["@character"] = plt.sapphire_theft,
      ["@character.special"] = plt.toxic_uv,

      ["@number"] = plt.venom_glow,
      ["@number.float"] = plt.venom_glow,

      ["@boolean"] = plt.arterial_spray,

      ["@function"] = plt.nightshade_purple,
      ["@function.builtin"] = plt.nightshade_purple,
      ["@function.call"] = plt.nightshade_purple,
      ["@function.macro"] = plt.lethal_violet,
      ["@function.method"] = plt.lethal_violet,
      ["@function.method.call"] = plt.lethal_violet,

      ["@constructor"] = plt.corpse_pale,

      ["@parameter"] = plt.cold_flesh,
      ["@parameter.builtin"] = plt.corpse_pale,

      ["@keyword"] = plt.nightshade_purple,
      ["@keyword.coroutine"] = plt.arterial_spray,
      ["@keyword.function"] = plt.nightshade_purple,
      ["@keyword.operator"] = plt.toxic_uv,
      ["@keyword.return"] = plt.nightshade_purple,
      ["@keyword.import"] = plt.stolen_moonlight,
      ["@keyword.storage"] = plt.nightshade_purple,
      ["@keyword.repeat"] = plt.nightshade_purple,
      ["@keyword.conditional"] = plt.nightshade_purple,
      ["@keyword.exception"] = plt.arterial_spray,
      ["@keyword.directive"] = plt.vampire_lips,
      ["@keyword.directive.define"] = plt.vampire_lips,

      ["@conditional"] = plt.nightshade_purple,
      ["@conditional.ternary"] = plt.nightshade_purple,

      ["@repeat"] = plt.nightshade_purple,

      ["@label"] = plt.lethal_violet,

      ["@operator"] = plt.toxic_uv,

      ["@exception"] = plt.arterial_spray,

      ["@variable"] = plt.corpse_pale,
      ["@variable.builtin"] = plt.fang_white,
      ["@variable.parameter"] = plt.cold_flesh,
      ["@variable.member"] = plt.corpse_pale,

      ["@type"] = plt.lethal_violet,
      ["@type.builtin"] = plt.lethal_violet,
      ["@type.definition"] = plt.lethal_violet,
      ["@type.qualifier"] = plt.nightshade_purple,

      ["@attribute"] = plt.corpse_pale,
      ["@attribute.builtin"] = plt.lethal_violet,

      ["@property"] = plt.corpse_pale,
      ["@field"] = plt.corpse_pale,
      ["@module"] = plt.corpse_pale,
      ["@module.builtin"] = plt.corpse_pale,
      ["@namespace"] = plt.corpse_pale,
      ["@namespace.builtin"] = plt.corpse_pale,

      ["@punctuation.delimiter"] = plt.moonlit_skin,
      ["@punctuation.bracket"] = plt.cold_flesh,
      ["@punctuation.special"] = plt.toxic_uv,

      ["@tag"] = plt.nightshade_purple,
      ["@tag.attribute"] = plt.lethal_violet,
      ["@tag.delimiter"] = plt.moonlit_skin,
      ["@tag.builtin"] = plt.nightshade_purple,

      ["@markup.strong"] = { fg = plt.nightshade_purple, bold = true },
      ["@markup.italic"] = { fg = plt.corpse_pale, italic = true },
      ["@markup.strikethrough"] = { fg = plt.ultraviolet_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.arterial_spray, underline = true },
      ["@markup.heading"] = plt.nightshade_purple,
      ["@markup.heading.1"] = plt.nightshade_purple,
      ["@markup.heading.2"] = plt.lethal_violet,
      ["@markup.heading.3"] = plt.toxic_uv,
      ["@markup.heading.4"] = plt.ultraviolet_flash,
      ["@markup.heading.5"] = plt.arterial_spray,
      ["@markup.heading.6"] = plt.venom_glow,
      ["@markup.quote"] = plt.cold_flesh,
      ["@markup.math"] = plt.ice_blue,
      ["@markup.link"] = plt.stolen_moonlight,
      ["@markup.link.label"] = plt.venom_glow,
      ["@markup.link.url"] = plt.nightshade_purple,
      ["@markup.raw"] = plt.sapphire_theft,
      ["@markup.raw.block"] = plt.sapphire_theft,
      ["@markup.list"] = plt.nightshade_purple,
      ["@markup.list.checked"] = plt.stolen_moonlight,
      ["@markup.list.unchecked"] = plt.cold_flesh,

      ["@diff.plus"] = plt.stolen_moonlight,
      ["@diff.minus"] = plt.arterial_spray,
      ["@diff.delta"] = plt.lethal_violet,

      ["@none"] = "none",
      ["@conceal"] = plt.moonlit_skin,
      ["@spell"] = plt.corpse_pale,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.corpse_pale,
      ["@constructor.python"] = plt.nightshade_purple,
      ["@constructor.javascript"] = plt.nightshade_purple,
      ["@constructor.typescript"] = plt.nightshade_purple,
      ["@namespace.rust"] = plt.corpse_pale,
      ["@type.qualifier.rust"] = plt.nightshade_purple,
      ["@constant.macro.c"] = plt.venom_glow,
      ["@constant.macro.cpp"] = plt.venom_glow,
      ["@namespace.go"] = plt.corpse_pale,
      ["@property.css"] = plt.lethal_violet,
      ["@type.css"] = plt.nightshade_purple,
      ["@label.json"] = plt.corpse_pale,
      ["@field.yaml"] = plt.cold_flesh,
      ["@property.toml"] = plt.cold_flesh,
      ["@function.builtin.bash"] = plt.lethal_violet,
      ["@string.regexp"] = plt.stolen_moonlight,
      ["@character.special.regex"] = plt.toxic_uv,
    },

    lsp = {
      ["@lsp.type.class"] = plt.lethal_violet,
      ["@lsp.type.interface"] = plt.lethal_violet,
      ["@lsp.type.struct"] = plt.lethal_violet,
      ["@lsp.type.enum"] = plt.lethal_violet,
      ["@lsp.type.enumMember"] = plt.ice_blue,
      ["@lsp.type.property"] = plt.corpse_pale,
      ["@lsp.type.namespace"] = plt.corpse_pale,

      ["@lsp.type.macro"] = plt.venom_glow,
      ["@lsp.type.decorator"] = plt.nightshade_purple,

      ["@lsp.type.builtinType"] = plt.lethal_violet,
      ["@lsp.type.selfParameter"] = plt.nightshade_purple,
      ["@lsp.type.typeParameter"] = plt.lethal_violet,

      ["@lsp.type.array"] = plt.lethal_violet,
      ["@lsp.type.object"] = plt.lethal_violet,
      ["@lsp.type.key"] = plt.corpse_pale,
      ["@lsp.type.null"] = plt.ice_blue,
      ["@lsp.type.enumConstant"] = plt.ice_blue,

      ["@lsp.type.event"] = plt.lethal_violet,
      ["@lsp.type.regexp"] = plt.stolen_moonlight,
      ["@lsp.type.unresolvedReference"] = plt.arterial_spray,

      ["@lsp.mod.deprecated"] = { fg = plt.ultraviolet_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.ice_blue,
      ["@lsp.mod.async"] = plt.nightshade_purple,
      ["@lsp.mod.static"] = plt.lethal_violet,
      ["@lsp.mod.abstract"] = plt.lethal_violet,
      ["@lsp.mod.defaultLibrary"] = plt.lethal_violet,
      ["@lsp.mod.documentation"] = plt.cold_flesh,
    },
  }
end

return {
  name = "Nocturna – True Nightshade",
  author = "PrismPunk.nvim",
  description = "She doesn’t sparkle. She doesn’t forgive. "
    .. "She drains you under ultraviolet light and leaves you cold. This is the real Nocturna.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.abyss,
    base02 = palette.nightshade_core,
    base03 = palette.ultraviolet_glow,
    base04 = palette.cold_flesh,
    base05 = palette.ice_blue,
    base06 = palette.moonlit_skin,
    base07 = palette.corpse_pale,
    base08 = palette.arterial_spray,
    base09 = palette.lethal_violet,
    base0A = palette.nightshade_purple,
    base0B = palette.stolen_moonlight,
    base0C = palette.toxic_uv,
    base0D = palette.ultraviolet_flash,
    base0E = palette.venom_glow,
    base0F = palette.vampire_lips,
  },

  palette = palette,
  get = M.get,
}
