local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0D0A1A",
  bg_darker = "#1A1430",
  bg_dark = "#261E46",
  bg_mid = "#32285C",
  bg_light = "#3E3272",
  bg_lighter = "#4A3C88",
  bg_lightest = "#56469E",

  fg_lightest = "#E8E6FF",
  fg_light = "#C8C6F0",
  fg_mid = "#7876A8",
  fg_dark = "#585680",

  bg_alt1 = "#151225",
  bg_alt2 = "#0A0815",
  bg_alt3 = "#1E1A35",
  bg_alt4 = "#100D1D",

  compassionCore = "#8B5CF6",
  compassionGlow = "#A78BFA",
  compassionBright = "#C4B5FD",
  compassionDeep = "#7C3AED",
  compassionDark = "#5B21B6",

  tribalIndigo = "#9333EA",
  empathyViolet = "#A855F7",
  sorrowDeep = "#6B21A8",
  midnightIndigo = "#581C87",
  mercyAmethyst = "#C084FC",

  redemptionAmber = "#FCD34D",
  noksOrange = "#FB923C",
  sufferingCrimson = "#F87171",
  healingGreen = "#4ADE80",
  peacefulBlue = "#60A5FA",
  sorrowPink = "#F472B6",
  peacefulCyan = "#22D3EE",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.compassionCore,
      insert = plt.empathyViolet,
      visual = plt.compassionGlow,
      replace = plt.sufferingCrimson,
      command = plt.compassionBright,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.compassionDeep,
      bg_visual = plt.compassionDark,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.compassionCore,
      header2 = plt.empathyViolet,
      special = plt.tribalIndigo,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.compassionCore,
      indent = plt.bg_lighter,
      indent_scope = plt.compassionGlow,
      picker = plt.sufferingCrimson,
      yank = plt.mercyAmethyst,
      mark = plt.empathyViolet,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.compassionBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.tribalIndigo,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.compassionCore,
      accent2 = plt.compassionBright,
      accent3 = plt.empathyViolet,
      accent4 = plt.tribalIndigo,
      accent5 = plt.sufferingCrimson,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.compassionCore,
      rainbow2 = plt.compassionBright,
      rainbow3 = plt.empathyViolet,
      rainbow4 = plt.compassionGlow,
      rainbow5 = plt.tribalIndigo,
      rainbow6 = plt.mercyAmethyst,
      rainbow7 = plt.sorrowDeep,
    },

    syn = {
      attribute = plt.redemptionAmber,
      boolean = plt.peacefulCyan,
      comment = plt.fg_dark,
      constant = plt.compassionBright,
      deprecated = plt.fg_mid,
      func = plt.empathyViolet,
      identifier = plt.fg_lightest,
      keyword = plt.compassionCore,
      method = plt.tribalIndigo,
      number = plt.compassionGlow,
      operator = plt.sufferingCrimson,
      parameter = plt.fg_mid,
      preproc = plt.compassionDeep,
      punct = plt.fg_mid,
      regex = plt.redemptionAmber,
      statement = plt.compassionCore,
      string = plt.healingGreen,
      symbol = plt.sufferingCrimson,
      type = plt.empathyViolet,
      variable = plt.fg_lightest,
      special = plt.redemptionAmber,
      special2 = plt.sufferingCrimson,
      special3 = plt.compassionDeep,
    },

    vcs = {
      added = plt.healingGreen,
      removed = plt.sufferingCrimson,
      changed = plt.redemptionAmber,
    },

    diff = {
      add = plt.healingGreen,
      change = plt.redemptionAmber,
      delete = plt.sufferingCrimson,
      text = plt.compassionCore,
    },

    diag = {
      ok = plt.healingGreen,
      error = plt.sufferingCrimson,
      warning = plt.redemptionAmber,
      info = plt.compassionCore,
      hint = plt.empathyViolet,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.sufferingCrimson,
      green = plt.healingGreen,
      yellow = plt.redemptionAmber,
      blue = plt.compassionCore,
      magenta = plt.sorrowPink,
      cyan = plt.empathyViolet,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.sufferingCrimson):brighten(0.2):to_hex(),
      green_bright = color(plt.healingGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.redemptionAmber):brighten(0.2):to_hex(),
      blue_bright = color(plt.compassionCore):brighten(0.3):to_hex(),
      magenta_bright = color(plt.sorrowPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.empathyViolet):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.compassionBright,
      indexed2 = plt.sufferingCrimson,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.sufferingCrimson,
      ["@comment.warning"] = plt.redemptionAmber,
      ["@comment.todo"] = plt.compassionCore,
      ["@comment.note"] = plt.empathyViolet,

      ["@constant"] = plt.compassionBright,
      ["@constant.builtin"] = plt.compassionBright,
      ["@constant.macro"] = plt.redemptionAmber,

      ["@string"] = plt.healingGreen,
      ["@string.documentation"] = plt.healingGreen,
      ["@string.regex"] = plt.redemptionAmber,
      ["@string.escape"] = plt.sorrowPink,
      ["@string.special"] = plt.empathyViolet,
      ["@string.special.symbol"] = plt.sufferingCrimson,
      ["@string.special.url"] = plt.tribalIndigo,
      ["@string.special.path"] = plt.empathyViolet,

      ["@character"] = plt.healingGreen,
      ["@character.special"] = plt.sorrowPink,

      ["@number"] = plt.compassionGlow,
      ["@number.float"] = plt.compassionGlow,

      ["@boolean"] = plt.peacefulCyan,

      ["@function"] = plt.empathyViolet,
      ["@function.builtin"] = plt.empathyViolet,
      ["@function.call"] = plt.empathyViolet,
      ["@function.macro"] = plt.compassionDeep,
      ["@function.method"] = plt.tribalIndigo,
      ["@function.method.call"] = plt.tribalIndigo,

      ["@constructor"] = plt.empathyViolet,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.compassionCore,
      ["@keyword.coroutine"] = plt.compassionGlow,
      ["@keyword.function"] = plt.compassionCore,
      ["@keyword.operator"] = plt.sufferingCrimson,
      ["@keyword.return"] = plt.compassionCore,
      ["@keyword.import"] = plt.compassionDeep,
      ["@keyword.storage"] = plt.compassionCore,
      ["@keyword.repeat"] = plt.compassionCore,
      ["@keyword.conditional"] = plt.compassionCore,
      ["@keyword.exception"] = plt.sufferingCrimson,
      ["@keyword.directive"] = plt.compassionDeep,
      ["@keyword.directive.define"] = plt.compassionDeep,

      ["@conditional"] = plt.compassionCore,
      ["@conditional.ternary"] = plt.compassionCore,

      ["@repeat"] = plt.compassionCore,

      ["@label"] = plt.compassionGlow,

      ["@operator"] = plt.sufferingCrimson,

      ["@exception"] = plt.sufferingCrimson,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.compassionGlow,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.empathyViolet,
      ["@type.builtin"] = plt.empathyViolet,
      ["@type.definition"] = plt.empathyViolet,
      ["@type.qualifier"] = plt.compassionCore,

      ["@attribute"] = plt.redemptionAmber,
      ["@attribute.builtin"] = plt.redemptionAmber,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.empathyViolet,
      ["@module.builtin"] = plt.empathyViolet,

      ["@namespace"] = plt.empathyViolet,
      ["@namespace.builtin"] = plt.empathyViolet,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.sufferingCrimson,

      ["@tag"] = plt.sufferingCrimson,
      ["@tag.attribute"] = plt.redemptionAmber,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.sufferingCrimson,

      ["@markup.strong"] = { fg = plt.compassionBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.compassionCore,
      ["@markup.heading.1"] = plt.compassionCore,
      ["@markup.heading.2"] = plt.compassionBright,
      ["@markup.heading.3"] = plt.empathyViolet,
      ["@markup.heading.4"] = plt.tribalIndigo,
      ["@markup.heading.5"] = plt.compassionGlow,
      ["@markup.heading.6"] = plt.mercyAmethyst,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.empathyViolet,
      ["@markup.link"] = plt.tribalIndigo,
      ["@markup.link.label"] = plt.empathyViolet,
      ["@markup.link.url"] = plt.tribalIndigo,
      ["@markup.raw"] = plt.healingGreen,
      ["@markup.raw.block"] = plt.healingGreen,
      ["@markup.list"] = plt.sufferingCrimson,
      ["@markup.list.checked"] = plt.healingGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.healingGreen,
      ["@diff.minus"] = plt.sufferingCrimson,
      ["@diff.delta"] = plt.redemptionAmber,

      ["@none"] = "none",
      ["@conceal"] = plt.compassionDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.empathyViolet,
      ["@constructor.javascript"] = plt.empathyViolet,
      ["@constructor.typescript"] = plt.empathyViolet,
      ["@namespace.rust"] = plt.empathyViolet,
      ["@type.qualifier.rust"] = plt.compassionCore,
      ["@constant.macro.c"] = plt.redemptionAmber,
      ["@constant.macro.cpp"] = plt.redemptionAmber,
      ["@namespace.go"] = plt.empathyViolet,
      ["@property.css"] = plt.empathyViolet,
      ["@type.css"] = plt.sufferingCrimson,
      ["@label.json"] = plt.empathyViolet,
      ["@field.yaml"] = plt.empathyViolet,
      ["@property.toml"] = plt.empathyViolet,
      ["@function.builtin.bash"] = plt.empathyViolet,
      ["@string.regexp"] = plt.redemptionAmber,
      ["@character.special.regex"] = plt.sorrowPink,
    },

    lsp = {
      ["@lsp.type.class"] = plt.empathyViolet,
      ["@lsp.type.interface"] = plt.empathyViolet,
      ["@lsp.type.struct"] = plt.empathyViolet,
      ["@lsp.type.enum"] = plt.empathyViolet,
      ["@lsp.type.enumMember"] = plt.compassionBright,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.empathyViolet,

      ["@lsp.type.macro"] = plt.redemptionAmber,
      ["@lsp.type.decorator"] = plt.empathyViolet,

      ["@lsp.type.builtinType"] = plt.empathyViolet,
      ["@lsp.type.selfParameter"] = plt.compassionGlow,
      ["@lsp.type.typeParameter"] = plt.empathyViolet,

      ["@lsp.type.array"] = plt.empathyViolet,
      ["@lsp.type.object"] = plt.empathyViolet,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.compassionBright,
      ["@lsp.type.enumConstant"] = plt.compassionBright,

      ["@lsp.type.event"] = plt.empathyViolet,
      ["@lsp.type.regexp"] = plt.redemptionAmber,
      ["@lsp.type.unresolvedReference"] = plt.redemptionAmber,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.compassionBright,
      ["@lsp.mod.async"] = plt.compassionCore,
      ["@lsp.mod.static"] = plt.compassionGlow,
      ["@lsp.mod.abstract"] = plt.empathyViolet,
      ["@lsp.mod.defaultLibrary"] = plt.empathyViolet,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Lantern Corps – Indigo (Compassion)",
  author = "PrismPunk.nvim",
  description = "Tor lorek san, bor nakka mur, Natromo faan tornek wot ur. "
    .. "Ter Lantern ker lo Abin Sur, Taan lek lek nok – Formorrow Sur!",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.sufferingCrimson,
    base09 = palette.noksOrange,
    base0A = palette.redemptionAmber,
    base0B = palette.healingGreen,
    base0C = palette.empathyViolet,
    base0D = palette.compassionCore,
    base0E = palette.compassionDeep,
    base0F = palette.compassionBright,
  },

  palette = palette,
  get = M.get,
}
