local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1A0000",
  bg_darker = "#2A0000",
  bg_dark = "#3A0000",
  bg_mid = "#4A0000",
  bg_light = "#5A0000",
  bg_lighter = "#6A0000",
  bg_lightest = "#7A0000",

  fg_lightest = "#FFD8D8",
  fg_light = "#E8B8B8",
  fg_mid = "#B88888",
  fg_dark = "#886868",

  bg_alt1 = "#220000",
  bg_alt2 = "#120000",
  bg_alt3 = "#320000",
  bg_alt4 = "#0D0000",

  voidCore = "#CC0000",
  voidGlow = "#E60000",
  voidBright = "#FF0000",
  voidDeep = "#A30000",
  voidDark = "#7A0000",

  corruptedRage = "#FF3333",
  corruptedAvarice = "#FFAA33",
  corruptedFear = "#FF7733",
  corruptedWill = "#CC6633",
  corruptedHope = "#CC3333",
  corruptedLove = "#CC3366",
  corruptedCompassion = "#FF6644",

  bloodFire = "#FF3333",
  crimsonWrath = "#DC143C",
  scarletFury = "#FF2400",
  rubyRage = "#E0115F",
  vermilionHate = "#E34234",
  maroonAnger = "#800000",
  brickRage = "#B22222",
  blazingCarnage = "#FF6666",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.voidCore,
      insert = plt.bloodFire,
      visual = plt.voidGlow,
      replace = plt.voidBright,
      command = plt.crimsonWrath,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.voidDeep,
      bg_visual = plt.voidDark,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.voidCore,
      header2 = plt.bloodFire,
      special = plt.crimsonWrath,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.voidCore,
      indent = plt.bg_lighter,
      indent_scope = plt.voidGlow,
      picker = plt.scarletFury,
      yank = plt.voidBright,
      mark = plt.bloodFire,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.voidBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.crimsonWrath,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.voidCore,
      accent2 = plt.voidBright,
      accent3 = plt.bloodFire,
      accent4 = plt.crimsonWrath,
      accent5 = plt.scarletFury,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.voidCore,
      rainbow2 = plt.voidBright,
      rainbow3 = plt.bloodFire,
      rainbow4 = plt.voidGlow,
      rainbow5 = plt.crimsonWrath,
      rainbow6 = plt.scarletFury,
      rainbow7 = plt.rubyRage,
    },

    syn = {
      attribute = plt.corruptedAvarice,
      boolean = plt.blazingCarnage,
      comment = plt.fg_dark,
      constant = plt.voidBright,
      deprecated = plt.fg_mid,
      func = plt.bloodFire,
      identifier = plt.fg_lightest,
      keyword = plt.voidCore,
      method = plt.crimsonWrath,
      number = plt.voidGlow,
      operator = plt.scarletFury,
      parameter = plt.fg_mid,
      preproc = plt.voidDeep,
      punct = plt.fg_mid,
      regex = plt.vermilionHate,
      statement = plt.voidCore,
      string = plt.corruptedWill,
      symbol = plt.scarletFury,
      type = plt.bloodFire,
      variable = plt.fg_lightest,
      special = plt.corruptedAvarice,
      special2 = plt.scarletFury,
      special3 = plt.voidDeep,
    },

    vcs = {
      added = plt.corruptedWill,
      removed = plt.voidBright,
      changed = plt.corruptedAvarice,
    },

    diff = {
      add = plt.corruptedWill,
      change = plt.corruptedAvarice,
      delete = plt.voidBright,
      text = plt.voidCore,
    },

    diag = {
      ok = plt.corruptedWill,
      error = plt.voidBright,
      warning = plt.corruptedAvarice,
      info = plt.voidCore,
      hint = plt.bloodFire,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.voidBright,
      green = plt.corruptedWill,
      yellow = plt.corruptedAvarice,
      blue = plt.voidCore,
      magenta = plt.rubyRage,
      cyan = plt.bloodFire,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.voidBright):brighten(0.2):to_hex(),
      green_bright = color(plt.corruptedWill):brighten(0.1):to_hex(),
      yellow_bright = color(plt.corruptedAvarice):brighten(0.2):to_hex(),
      blue_bright = color(plt.voidCore):brighten(0.3):to_hex(),
      magenta_bright = color(plt.rubyRage):brighten(0.2):to_hex(),
      cyan_bright = color(plt.bloodFire):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.voidBright,
      indexed2 = plt.scarletFury,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.voidBright,
      ["@comment.warning"] = plt.corruptedAvarice,
      ["@comment.todo"] = plt.voidCore,
      ["@comment.note"] = plt.bloodFire,

      ["@constant"] = plt.voidBright,
      ["@constant.builtin"] = plt.voidBright,
      ["@constant.macro"] = plt.corruptedAvarice,

      ["@string"] = plt.corruptedWill,
      ["@string.documentation"] = plt.corruptedWill,
      ["@string.regex"] = plt.vermilionHate,
      ["@string.escape"] = plt.corruptedAvarice,
      ["@string.special"] = plt.crimsonWrath,
      ["@string.special.symbol"] = plt.scarletFury,
      ["@string.special.url"] = plt.bloodFire,
      ["@string.special.path"] = plt.corruptedWill,

      ["@character"] = plt.corruptedWill,
      ["@character.special"] = plt.corruptedAvarice,

      ["@number"] = plt.voidGlow,
      ["@number.float"] = plt.voidGlow,

      ["@boolean"] = plt.blazingCarnage,

      ["@function"] = plt.bloodFire,
      ["@function.builtin"] = plt.bloodFire,
      ["@function.call"] = plt.bloodFire,
      ["@function.macro"] = plt.voidDeep,
      ["@function.method"] = plt.crimsonWrath,
      ["@function.method.call"] = plt.crimsonWrath,

      ["@constructor"] = plt.bloodFire,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.voidCore,
      ["@keyword.coroutine"] = plt.voidGlow,
      ["@keyword.function"] = plt.voidCore,
      ["@keyword.operator"] = plt.scarletFury,
      ["@keyword.return"] = plt.voidCore,
      ["@keyword.import"] = plt.voidDeep,
      ["@keyword.storage"] = plt.voidCore,
      ["@keyword.repeat"] = plt.voidCore,
      ["@keyword.conditional"] = plt.voidCore,
      ["@keyword.exception"] = plt.voidBright,
      ["@keyword.directive"] = plt.voidDeep,
      ["@keyword.directive.define"] = plt.voidDeep,

      ["@conditional"] = plt.voidCore,
      ["@conditional.ternary"] = plt.voidCore,

      ["@repeat"] = plt.voidCore,

      ["@label"] = plt.voidGlow,

      ["@operator"] = plt.scarletFury,

      ["@exception"] = plt.voidBright,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.voidGlow,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.bloodFire,
      ["@type.builtin"] = plt.bloodFire,
      ["@type.definition"] = plt.bloodFire,
      ["@type.qualifier"] = plt.voidCore,

      ["@attribute"] = plt.corruptedAvarice,
      ["@attribute.builtin"] = plt.corruptedAvarice,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.bloodFire,
      ["@module.builtin"] = plt.bloodFire,

      ["@namespace"] = plt.bloodFire,
      ["@namespace.builtin"] = plt.bloodFire,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.scarletFury,

      ["@tag"] = plt.voidCore,
      ["@tag.attribute"] = plt.corruptedAvarice,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.voidCore,

      ["@markup.strong"] = { fg = plt.voidBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.voidCore,
      ["@markup.heading.1"] = plt.voidBright,
      ["@markup.heading.2"] = plt.voidGlow,
      ["@markup.heading.3"] = plt.bloodFire,
      ["@markup.heading.4"] = plt.crimsonWrath,
      ["@markup.heading.5"] = plt.scarletFury,
      ["@markup.heading.6"] = plt.rubyRage,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.bloodFire,
      ["@markup.link"] = plt.crimsonWrath,
      ["@markup.link.label"] = plt.bloodFire,
      ["@markup.link.url"] = plt.crimsonWrath,
      ["@markup.raw"] = plt.corruptedWill,
      ["@markup.raw.block"] = plt.corruptedWill,
      ["@markup.list"] = plt.voidCore,
      ["@markup.list.checked"] = plt.corruptedWill,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.corruptedWill,
      ["@diff.minus"] = plt.voidBright,
      ["@diff.delta"] = plt.corruptedAvarice,

      ["@none"] = "none",
      ["@conceal"] = plt.voidDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.bloodFire,
      ["@constructor.javascript"] = plt.bloodFire,
      ["@constructor.typescript"] = plt.bloodFire,
      ["@namespace.rust"] = plt.bloodFire,
      ["@type.qualifier.rust"] = plt.voidCore,
      ["@constant.macro.c"] = plt.corruptedAvarice,
      ["@constant.macro.cpp"] = plt.corruptedAvarice,
      ["@namespace.go"] = plt.bloodFire,
      ["@property.css"] = plt.bloodFire,
      ["@type.css"] = plt.voidCore,
      ["@label.json"] = plt.bloodFire,
      ["@field.yaml"] = plt.bloodFire,
      ["@property.toml"] = plt.bloodFire,
      ["@function.builtin.bash"] = plt.bloodFire,
      ["@string.regexp"] = plt.vermilionHate,
      ["@character.special.regex"] = plt.corruptedAvarice,
    },

    lsp = {
      ["@lsp.type.class"] = plt.bloodFire,
      ["@lsp.type.interface"] = plt.bloodFire,
      ["@lsp.type.struct"] = plt.bloodFire,
      ["@lsp.type.enum"] = plt.bloodFire,
      ["@lsp.type.enumMember"] = plt.voidBright,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.bloodFire,

      ["@lsp.type.macro"] = plt.corruptedAvarice,
      ["@lsp.type.decorator"] = plt.bloodFire,

      ["@lsp.type.builtinType"] = plt.bloodFire,
      ["@lsp.type.selfParameter"] = plt.voidGlow,
      ["@lsp.type.typeParameter"] = plt.bloodFire,

      ["@lsp.type.array"] = plt.bloodFire,
      ["@lsp.type.object"] = plt.bloodFire,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.voidBright,
      ["@lsp.type.enumConstant"] = plt.voidBright,

      ["@lsp.type.event"] = plt.bloodFire,
      ["@lsp.type.regexp"] = plt.vermilionHate,
      ["@lsp.type.unresolvedReference"] = plt.corruptedAvarice,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.voidBright,
      ["@lsp.mod.async"] = plt.voidCore,
      ["@lsp.mod.static"] = plt.voidGlow,
      ["@lsp.mod.abstract"] = plt.bloodFire,
      ["@lsp.mod.defaultLibrary"] = plt.bloodFire,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Lantern Corps – Red (Rage)",
  author = "PrismPunk.nvim",
  description = "With blood and rage of crimson red, ripped from a corpse so freshly dead, "
    .. "together with our hellish hate, we'll burn you all—that is your fate!",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.voidBright,
    base09 = palette.corruptedAvarice,
    base0A = palette.corruptedAvarice,
    base0B = palette.corruptedWill,
    base0C = palette.bloodFire,
    base0D = palette.voidCore,
    base0E = palette.voidDeep,
    base0F = palette.voidBright,
  },

  palette = palette,
  get = M.get,
}
