local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#f5f0e8",
  bg_darker = "#ede8df",
  bg_dark = "#e5dfd6",
  bg_mid = "#ddd7cd",
  bg_light = "#d5cfc4",
  bg_lighter = "#cdc7bb",
  bg_lightest = "#c5bfb2",
  bg_alt1 = "#bdb7a9",
  bg_alt2 = "#b5afa0",
  bg_alt3 = "#ada797",
  bg_alt4 = "#a59f8e",
  fg_lightest = "#1a1410",
  fg_light = "#2e2820",
  fg_mid = "#423c30",
  fg_dark = "#565040",
  alfheimr = "#6b5540",
  lightRealm = "#7d6752",
  freyrsDomain = "#8f7964",
  radiantBeauty = "#a18b76",
  luminousHome = "#594935",
  shiningRealm = "#473d2b",
  dawnlight = "#353121",
  elvenglow = "#232517",
  brightMagic = "#11190d",
  fairBeings = "#5a5a4a",
  divineGift = "#464636",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.alfheimr,
      insert = plt.lightRealm,
      visual = plt.freyrsDomain,
      replace = plt.radiantBeauty,
      command = plt.luminousHome,
    },
    accent = {
      accent1 = plt.alfheimr,
      accent2 = plt.lightRealm,
      accent3 = plt.freyrsDomain,
      accent4 = plt.fg_light,
      accent5 = plt.radiantBeauty,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.alfheimr,
      rainbow2 = plt.lightRealm,
      rainbow3 = plt.freyrsDomain,
      rainbow4 = plt.radiantBeauty,
      rainbow5 = plt.luminousHome,
      rainbow6 = plt.shiningRealm,
      rainbow7 = plt.dawnlight,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.freyrsDomain,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.alfheimr,
      header2 = plt.radiantBeauty,
      special = plt.luminousHome,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.lightRealm,
      indent = plt.bg_light,
      indent_scope = plt.alfheimr,
      picker = plt.freyrsDomain,
      yank = plt.luminousHome,
      mark = plt.elvenglow,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.alfheimr,
        indicator = plt.radiantBeauty,
      },
    },
    syn = {
      attribute = plt.luminousHome,
      boolean = plt.elvenglow,
      comment = plt.fg_mid,
      constant = plt.freyrsDomain,
      deprecated = plt.fg_dark,
      func = plt.radiantBeauty,
      identifier = plt.fg_lightest,
      keyword = plt.elvenglow,
      method = plt.radiantBeauty,
      number = plt.freyrsDomain,
      operator = plt.lightRealm,
      parameter = plt.brightMagic,
      preproc = plt.luminousHome,
      punct = plt.fg_mid,
      regex = plt.elvenglow,
      special = plt.luminousHome,
      special2 = plt.elvenglow,
      special3 = plt.brightMagic,
      statement = plt.elvenglow,
      string = plt.radiantBeauty,
      symbol = plt.lightRealm,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.radiantBeauty,
      warning = plt.freyrsDomain,
      info = plt.alfheimr,
      ok = plt.shiningRealm,
      hint = plt.luminousHome,
      virtual_text_error = plt.radiantBeauty,
      virtual_text_warning = plt.freyrsDomain,
      virtual_text_info = plt.alfheimr,
      virtual_text_ok = plt.shiningRealm,
      virtual_text_hint = plt.luminousHome,
    },
    diff = {
      add = plt.shiningRealm,
      add_inline = plt.lightRealm,
      change = plt.freyrsDomain,
      change_inline = plt.elvenglow,
      delete = plt.radiantBeauty,
      delete_inline = plt.alfheimr,
      text = plt.luminousHome,
    },
    vcs = {
      added = plt.shiningRealm,
      changed = plt.freyrsDomain,
      removed = plt.radiantBeauty,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.radiantBeauty,
      green = plt.shiningRealm,
      yellow = plt.luminousHome,
      blue = plt.alfheimr,
      magenta = plt.freyrsDomain,
      cyan = plt.lightRealm,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.radiantBeauty):brighten(0.2):to_hex(),
      green_bright = color(plt.shiningRealm):brighten(0.15):to_hex(),
      yellow_bright = color(plt.luminousHome):brighten(0.15):to_hex(),
      blue_bright = color(plt.alfheimr):brighten(0.15):to_hex(),
      magenta_bright = color(plt.freyrsDomain):brighten(0.2):to_hex(),
      cyan_bright = color(plt.lightRealm):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.brightMagic,
      indexed2 = plt.elvenglow,
    },
  }
end

return {
  name = "Alfheim – Álfheimr",
  author = "PrismPunk",
  description = "Radiant beauty — light realm, Freyr's domain, luminous home, shining realm. "
    .. "Álfheimr is the realm of the Ljósálfar, the Light Elves, beings of radiant "
    .. "beauty and divine grace. Given to Freyr as a tooth-gift in his youth, it is a "
    .. "land of perpetual dawn, where light itself seems alive. The elves who dwell "
    .. "here are fairer than the sun, their magic bright and beneficial. The realm "
    .. "glows with an inner luminescence, as if the very air is woven from sunlight. "
    .. "The palette uses soft earth tones with warm beige backgrounds, capturing the "
    .. "gentle radiance of a realm where darkness never falls and beauty is the "
    .. "natural order of existence.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.radiantBeauty,
    base09 = palette.freyrsDomain,
    base0A = palette.brightMagic,
    base0B = palette.shiningRealm,
    base0C = palette.luminousHome,
    base0D = palette.alfheimr,
    base0E = palette.lightRealm,
    base0F = palette.elvenglow,
  },
  palette = palette,
  get = M.get,
}
