local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#f0ede8",
  bg_darker = "#e8e5df",
  bg_dark = "#dfdcd6",
  bg_mid = "#d7d4cd",
  bg_light = "#cfccc4",
  bg_lighter = "#c7c4bb",
  bg_lightest = "#bfbcb2",
  bg_alt1 = "#b7b4a9",
  bg_alt2 = "#afaca0",
  bg_alt3 = "#a7a497",
  bg_alt4 = "#9f9c8e",
  fg_lightest = "#14100a",
  fg_light = "#28241e",
  fg_mid = "#3c3832",
  fg_dark = "#504c46",
  byggvir = "#6b5530",
  grainSpirit = "#7d6742",
  freyrServant = "#8f7954",
  barleyBrewer = "#a18b66",
  humbleService = "#594521",
  agriculturalRole = "#473917",
  wheatWisdom = "#352d0d",
  harvestHelper = "#232103",
  grainGuardian = "#111500",
  fertileFields = "#5a5036",
  goldenGrain = "#463c22",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.byggvir,
      insert = plt.grainSpirit,
      visual = plt.freyrServant,
      replace = plt.barleyBrewer,
      command = plt.humbleService,
    },
    accent = {
      accent1 = plt.byggvir,
      accent2 = plt.grainSpirit,
      accent3 = plt.freyrServant,
      accent4 = plt.fg_light,
      accent5 = plt.barleyBrewer,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.byggvir,
      rainbow2 = plt.grainSpirit,
      rainbow3 = plt.freyrServant,
      rainbow4 = plt.barleyBrewer,
      rainbow5 = plt.humbleService,
      rainbow6 = plt.agriculturalRole,
      rainbow7 = plt.wheatWisdom,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.freyrServant,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.byggvir,
      header2 = plt.barleyBrewer,
      special = plt.humbleService,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.grainSpirit,
      indent = plt.bg_light,
      indent_scope = plt.byggvir,
      picker = plt.freyrServant,
      yank = plt.humbleService,
      mark = plt.harvestHelper,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.byggvir,
        indicator = plt.barleyBrewer,
      },
    },
    syn = {
      attribute = plt.humbleService,
      boolean = plt.harvestHelper,
      comment = plt.fg_mid,
      constant = plt.freyrServant,
      deprecated = plt.fg_dark,
      func = plt.barleyBrewer,
      identifier = plt.fg_lightest,
      keyword = plt.harvestHelper,
      method = plt.barleyBrewer,
      number = plt.freyrServant,
      operator = plt.grainSpirit,
      parameter = plt.grainGuardian,
      preproc = plt.humbleService,
      punct = plt.fg_mid,
      regex = plt.harvestHelper,
      special = plt.humbleService,
      special2 = plt.harvestHelper,
      special3 = plt.grainGuardian,
      statement = plt.harvestHelper,
      string = plt.barleyBrewer,
      symbol = plt.grainSpirit,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.barleyBrewer,
      warning = plt.freyrServant,
      info = plt.byggvir,
      ok = plt.agriculturalRole,
      hint = plt.humbleService,
      virtual_text_error = plt.barleyBrewer,
      virtual_text_warning = plt.freyrServant,
      virtual_text_info = plt.byggvir,
      virtual_text_ok = plt.agriculturalRole,
      virtual_text_hint = plt.humbleService,
    },
    diff = {
      add = plt.agriculturalRole,
      add_inline = plt.grainSpirit,
      change = plt.freyrServant,
      change_inline = plt.harvestHelper,
      delete = plt.barleyBrewer,
      delete_inline = plt.byggvir,
      text = plt.humbleService,
    },
    vcs = {
      added = plt.agriculturalRole,
      changed = plt.freyrServant,
      removed = plt.barleyBrewer,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.barleyBrewer,
      green = plt.agriculturalRole,
      yellow = plt.humbleService,
      blue = plt.byggvir,
      magenta = plt.freyrServant,
      cyan = plt.grainSpirit,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.barleyBrewer):brighten(0.2):to_hex(),
      green_bright = color(plt.agriculturalRole):brighten(0.15):to_hex(),
      yellow_bright = color(plt.humbleService):brighten(0.15):to_hex(),
      blue_bright = color(plt.byggvir):brighten(0.15):to_hex(),
      magenta_bright = color(plt.freyrServant):brighten(0.2):to_hex(),
      cyan_bright = color(plt.grainSpirit):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.grainGuardian,
      indexed2 = plt.harvestHelper,
    },
  }
end

return {
  name = "Alfheim – Byggvir",
  author = "PrismPunk",
  description = "Grain spirit — Freyr's servant, barley brewer, humble service, agricultural role. "
    .. "Byggvir is the faithful servant of Freyr and Gerðr, a spirit of grain and "
    .. "agriculture. His name means 'barley' and he represents the humble but "
    .. "essential work of cultivation and brewing. At Ægir's feast, when Loki mocked "
    .. "the gods, Byggvir defended his master's honor despite his lowly status. He "
    .. "embodies the dignity of service and the sacred nature of the harvest. The "
    .. "palette uses warm wheat and barley tones against muted earth backgrounds, "
    .. "capturing the golden fields of grain and the honest labor that sustains both "
    .. "gods and mortals.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.barleyBrewer,
    base09 = palette.freyrServant,
    base0A = palette.grainGuardian,
    base0B = palette.agriculturalRole,
    base0C = palette.humbleService,
    base0D = palette.byggvir,
    base0E = palette.grainSpirit,
    base0F = palette.harvestHelper,
  },
  palette = palette,
  get = M.get,
}
