local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#e8f0e8",
  bg_darker = "#dfe8df",
  bg_dark = "#d6dfd6",
  bg_mid = "#cdd7cd",
  bg_light = "#c4cfc4",
  bg_lighter = "#bbc7bb",
  bg_lightest = "#b2bfb2",
  bg_alt1 = "#a9b7a9",
  bg_alt2 = "#a0afa0",
  bg_alt3 = "#97a797",
  bg_alt4 = "#8e9f8e",
  fg_lightest = "#0a140a",
  fg_light = "#1e281e",
  fg_mid = "#323c32",
  fg_dark = "#465046",
  ljosalfar = "#3a6a4e",
  fairBeings = "#4c7c60",
  beneficialSpirits = "#5e8e72",
  brightMagic = "#70a084",
  divineBeauty = "#2e583e",
  radiantGrace = "#244630",
  lightElves = "#1a3422",
  elvishLuminescence = "#102214",
  sunFairer = "#061006",
  gracefulPresence = "#4a5a4a",
  etherealLight = "#363636",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.ljosalfar,
      insert = plt.fairBeings,
      visual = plt.beneficialSpirits,
      replace = plt.brightMagic,
      command = plt.divineBeauty,
    },
    accent = {
      accent1 = plt.ljosalfar,
      accent2 = plt.fairBeings,
      accent3 = plt.beneficialSpirits,
      accent4 = plt.fg_light,
      accent5 = plt.brightMagic,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.ljosalfar,
      rainbow2 = plt.fairBeings,
      rainbow3 = plt.beneficialSpirits,
      rainbow4 = plt.brightMagic,
      rainbow5 = plt.divineBeauty,
      rainbow6 = plt.radiantGrace,
      rainbow7 = plt.lightElves,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.beneficialSpirits,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.ljosalfar,
      header2 = plt.brightMagic,
      special = plt.divineBeauty,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.fairBeings,
      indent = plt.bg_light,
      indent_scope = plt.ljosalfar,
      picker = plt.beneficialSpirits,
      yank = plt.divineBeauty,
      mark = plt.elvishLuminescence,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.ljosalfar,
        indicator = plt.brightMagic,
      },
    },
    syn = {
      attribute = plt.divineBeauty,
      boolean = plt.elvishLuminescence,
      comment = plt.fg_mid,
      constant = plt.beneficialSpirits,
      deprecated = plt.fg_dark,
      func = plt.brightMagic,
      identifier = plt.fg_lightest,
      keyword = plt.elvishLuminescence,
      method = plt.brightMagic,
      number = plt.beneficialSpirits,
      operator = plt.fairBeings,
      parameter = plt.sunFairer,
      preproc = plt.divineBeauty,
      punct = plt.fg_mid,
      regex = plt.elvishLuminescence,
      special = plt.divineBeauty,
      special2 = plt.elvishLuminescence,
      special3 = plt.sunFairer,
      statement = plt.elvishLuminescence,
      string = plt.brightMagic,
      symbol = plt.fairBeings,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.brightMagic,
      warning = plt.beneficialSpirits,
      info = plt.ljosalfar,
      ok = plt.radiantGrace,
      hint = plt.divineBeauty,
      virtual_text_error = plt.brightMagic,
      virtual_text_warning = plt.beneficialSpirits,
      virtual_text_info = plt.ljosalfar,
      virtual_text_ok = plt.radiantGrace,
      virtual_text_hint = plt.divineBeauty,
    },
    diff = {
      add = plt.radiantGrace,
      add_inline = plt.fairBeings,
      change = plt.beneficialSpirits,
      change_inline = plt.elvishLuminescence,
      delete = plt.brightMagic,
      delete_inline = plt.ljosalfar,
      text = plt.divineBeauty,
    },
    vcs = {
      added = plt.radiantGrace,
      changed = plt.beneficialSpirits,
      removed = plt.brightMagic,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.brightMagic,
      green = plt.radiantGrace,
      yellow = plt.divineBeauty,
      blue = plt.ljosalfar,
      magenta = plt.beneficialSpirits,
      cyan = plt.fairBeings,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.brightMagic):brighten(0.2):to_hex(),
      green_bright = color(plt.radiantGrace):brighten(0.15):to_hex(),
      yellow_bright = color(plt.divineBeauty):brighten(0.15):to_hex(),
      blue_bright = color(plt.ljosalfar):brighten(0.15):to_hex(),
      magenta_bright = color(plt.beneficialSpirits):brighten(0.2):to_hex(),
      cyan_bright = color(plt.fairBeings):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.sunFairer,
      indexed2 = plt.elvishLuminescence,
    },
  }
end

return {
  name = "Alfheim – Ljósálfar",
  author = "PrismPunk",
  description = "Fair beings — beneficial spirits, bright magic, divine beauty, radiant grace. "
    .. "The Ljósálfar are the Light Elves of Álfheimr, beings of such radiant beauty "
    .. "that they are said to be fairer than the sun itself. They are beneficial "
    .. "spirits, their magic bright and healing, their presence a blessing. Unlike "
    .. "their dark counterparts in Svartálfheim, the Light Elves dwell in luminous "
    .. "halls and walk in perpetual dawn. They are associated with life, growth, and "
    .. "divine grace. The palette uses muted green-greys against soft backgrounds, "
    .. "emphasizing their ethereal nature and the gentle, life-giving light they "
    .. "embody.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.brightMagic,
    base09 = palette.beneficialSpirits,
    base0A = palette.sunFairer,
    base0B = palette.radiantGrace,
    base0C = palette.divineBeauty,
    base0D = palette.ljosalfar,
    base0E = palette.fairBeings,
    base0F = palette.elvishLuminescence,
  },
  palette = palette,
  get = M.get,
}
