local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050508",
  bg_darker = "#0A0A0E",
  bg_dark = "#0F0F14",
  bg_mid = "#16161D",
  bg_light = "#2D2D35",
  bg_lighter = "#44444D",
  bg_lightest = "#5A5A64",
  fg_lightest = "#F0F0F5",
  fg_light = "#D8D8E0",
  fg_mid = "#B0B0C0",
  fg_dark = "#808090",
  bg_alt1 = "#0D0D12",
  bg_alt2 = "#070709",
  bg_alt3 = "#12121A",
  bg_alt4 = "#08080B",
  championRed = "#FF0000",
  rannDefender = "#FF1744",
  heroicCrimson = "#E63946",
  suitScarlet = "#DC143C",
  alphaRed = "#C41E3A",
  zetaBeam = "#00FFFF",
  teleportCyan = "#00E5FF",
  quantumBlue = "#00BFFF",
  warpTeal = "#1E90FF",
  dimensionalBlue = "#4169E1",
  rayGunGold = "#FFD700",
  blasterBeam = "#FFB300",
  weaponChrome = "#C0C0C0",
  finSilver = "#D3D3D3",
  rannianCity = "#FF1493",
  alannaLove = "#FF69B4",
  princessPink = "#FFB6C1",
  sardathPink = "#DA70D6",
  alienSky = "#9D4EDD",
  threeRedMoons = "#DC143C",
  strangeWorld = "#8B00FF",
  cosmicVoid = "#4B0082",
  archaeologist = "#D2B48C",
  earthBorn = "#8B7355",
  stranded = "#B8860B",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.championRed,
      insert = plt.zetaBeam,
      visual = plt.rannDefender,
      replace = plt.threeRedMoons,
      command = plt.rayGunGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.rayGunGold,
      bg_visual = plt.rannDefender,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.championRed,
      header2 = plt.zetaBeam,
      special = plt.alannaLove,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.championRed,
      indent = plt.bg_lighter,
      indent_scope = plt.zetaBeam,
      picker = plt.threeRedMoons,
      yank = plt.rayGunGold,
      mark = plt.zetaBeam,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.championRed,
        bg_alternate = plt.bg_darkest,
        indicator = plt.zetaBeam,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.championRed,
      accent2 = plt.zetaBeam,
      accent3 = plt.rayGunGold,
      accent4 = plt.alannaLove,
      accent5 = plt.alienSky,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.championRed,
      rainbow2 = plt.zetaBeam,
      rainbow3 = plt.rayGunGold,
      rainbow4 = plt.alannaLove,
      rainbow5 = plt.alienSky,
      rainbow6 = plt.rannianCity,
      rainbow7 = plt.threeRedMoons,
    },

    syn = {
      attribute = plt.rayGunGold,
      boolean = plt.championRed,
      comment = plt.fg_dark,
      constant = plt.blasterBeam,
      deprecated = plt.fg_mid,
      func = plt.zetaBeam,
      identifier = plt.fg_lightest,
      keyword = plt.championRed,
      method = plt.quantumBlue,
      number = plt.weaponChrome,
      operator = plt.zetaBeam,
      parameter = plt.fg_mid,
      preproc = plt.alienSky,
      punct = plt.fg_mid,
      regex = plt.rayGunGold,
      statement = plt.championRed,
      string = plt.alannaLove,
      symbol = plt.zetaBeam,
      type = plt.rayGunGold,
      variable = plt.fg_lightest,
      special = plt.rannianCity,
      special2 = plt.threeRedMoons,
      special3 = plt.quantumBlue,
    },

    vcs = {
      added = plt.zetaBeam,
      removed = plt.threeRedMoons,
      changed = plt.rayGunGold,
    },

    diff = {
      add = plt.zetaBeam,
      change = plt.rayGunGold,
      delete = plt.threeRedMoons,
      text = plt.championRed,
    },

    diag = {
      ok = plt.zetaBeam,
      error = plt.threeRedMoons,
      warning = plt.blasterBeam,
      info = plt.dimensionalBlue,
      hint = plt.quantumBlue,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.championRed,
      green = plt.zetaBeam,
      yellow = plt.rayGunGold,
      blue = plt.quantumBlue,
      magenta = plt.alannaLove,
      cyan = plt.teleportCyan,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.championRed):brighten(0.2):to_hex(),
      green_bright = color(plt.zetaBeam):brighten(0.1):to_hex(),
      yellow_bright = color(plt.rayGunGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.quantumBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.alannaLove):brighten(0.2):to_hex(),
      cyan_bright = color(plt.teleportCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.rayGunGold,
      indexed2 = plt.championRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.threeRedMoons,
      ["@comment.warning"] = plt.blasterBeam,
      ["@comment.todo"] = plt.championRed,
      ["@comment.note"] = plt.zetaBeam,

      ["@constant"] = plt.blasterBeam,
      ["@constant.builtin"] = plt.blasterBeam,
      ["@constant.macro"] = plt.rayGunGold,

      ["@string"] = plt.alannaLove,
      ["@string.documentation"] = plt.alannaLove,
      ["@string.regex"] = plt.rayGunGold,
      ["@string.escape"] = plt.alienSky,
      ["@string.special"] = plt.zetaBeam,
      ["@string.special.symbol"] = plt.teleportCyan,
      ["@string.special.url"] = plt.quantumBlue,
      ["@string.special.path"] = plt.teleportCyan,

      ["@character"] = plt.alannaLove,
      ["@character.special"] = plt.alienSky,

      ["@number"] = plt.weaponChrome,
      ["@number.float"] = plt.weaponChrome,

      ["@boolean"] = plt.championRed,

      ["@function"] = plt.zetaBeam,
      ["@function.builtin"] = plt.zetaBeam,
      ["@function.call"] = plt.zetaBeam,
      ["@function.macro"] = plt.alienSky,
      ["@function.method"] = plt.quantumBlue,
      ["@function.method.call"] = plt.quantumBlue,

      ["@constructor"] = plt.rayGunGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.championRed,
      ["@keyword.coroutine"] = plt.rannDefender,
      ["@keyword.function"] = plt.championRed,
      ["@keyword.operator"] = plt.zetaBeam,
      ["@keyword.return"] = plt.championRed,
      ["@keyword.import"] = plt.zetaBeam,
      ["@keyword.storage"] = plt.championRed,
      ["@keyword.repeat"] = plt.championRed,
      ["@keyword.conditional"] = plt.championRed,
      ["@keyword.exception"] = plt.threeRedMoons,
      ["@keyword.directive"] = plt.alienSky,
      ["@keyword.directive.define"] = plt.alienSky,

      ["@conditional"] = plt.championRed,
      ["@conditional.ternary"] = plt.championRed,

      ["@repeat"] = plt.championRed,

      ["@label"] = plt.rannDefender,

      ["@operator"] = plt.zetaBeam,

      ["@exception"] = plt.threeRedMoons,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.rannDefender,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.rayGunGold,
      ["@type.builtin"] = plt.rayGunGold,
      ["@type.definition"] = plt.rayGunGold,
      ["@type.qualifier"] = plt.championRed,

      ["@attribute"] = plt.rayGunGold,
      ["@attribute.builtin"] = plt.rayGunGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.rayGunGold,
      ["@module.builtin"] = plt.rayGunGold,

      ["@namespace"] = plt.rayGunGold,
      ["@namespace.builtin"] = plt.rayGunGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.zetaBeam,

      ["@tag"] = plt.zetaBeam,
      ["@tag.attribute"] = plt.rayGunGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.zetaBeam,

      ["@markup.strong"] = { fg = plt.championRed, bold = true },
      ["@markup.italic"] = { fg = plt.alannaLove, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.championRed,
      ["@markup.heading.1"] = plt.championRed,
      ["@markup.heading.2"] = plt.zetaBeam,
      ["@markup.heading.3"] = plt.rayGunGold,
      ["@markup.heading.4"] = plt.alannaLove,
      ["@markup.heading.5"] = plt.alienSky,
      ["@markup.heading.6"] = plt.rannianCity,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.zetaBeam,
      ["@markup.link"] = plt.zetaBeam,
      ["@markup.link.label"] = plt.quantumBlue,
      ["@markup.link.url"] = plt.dimensionalBlue,
      ["@markup.raw"] = plt.alannaLove,
      ["@markup.raw.block"] = plt.alannaLove,
      ["@markup.list"] = plt.zetaBeam,
      ["@markup.list.checked"] = plt.zetaBeam,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.zetaBeam,
      ["@diff.minus"] = plt.threeRedMoons,
      ["@diff.delta"] = plt.rayGunGold,

      ["@none"] = "none",
      ["@conceal"] = plt.alienSky,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.rayGunGold,
      ["@constructor.javascript"] = plt.rayGunGold,
      ["@constructor.typescript"] = plt.rayGunGold,
      ["@namespace.rust"] = plt.rayGunGold,
      ["@type.qualifier.rust"] = plt.championRed,
      ["@constant.macro.c"] = plt.blasterBeam,
      ["@constant.macro.cpp"] = plt.blasterBeam,
      ["@namespace.go"] = plt.rayGunGold,
      ["@property.css"] = plt.alannaLove,
      ["@type.css"] = plt.zetaBeam,
      ["@label.json"] = plt.rayGunGold,
      ["@field.yaml"] = plt.alannaLove,
      ["@property.toml"] = plt.alannaLove,
      ["@function.builtin.bash"] = plt.zetaBeam,
      ["@string.regexp"] = plt.rayGunGold,
      ["@character.special.regex"] = plt.alienSky,
    },

    lsp = {
      ["@lsp.type.class"] = plt.rayGunGold,
      ["@lsp.type.interface"] = plt.rayGunGold,
      ["@lsp.type.struct"] = plt.rayGunGold,
      ["@lsp.type.enum"] = plt.rayGunGold,
      ["@lsp.type.enumMember"] = plt.championRed,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.rayGunGold,

      ["@lsp.type.macro"] = plt.blasterBeam,
      ["@lsp.type.decorator"] = plt.rayGunGold,

      ["@lsp.type.builtinType"] = plt.rayGunGold,
      ["@lsp.type.selfParameter"] = plt.rannDefender,
      ["@lsp.type.typeParameter"] = plt.rayGunGold,

      ["@lsp.type.array"] = plt.rayGunGold,
      ["@lsp.type.object"] = plt.rayGunGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.championRed,
      ["@lsp.type.enumConstant"] = plt.championRed,

      ["@lsp.type.event"] = plt.rayGunGold,
      ["@lsp.type.regexp"] = plt.rayGunGold,
      ["@lsp.type.unresolvedReference"] = plt.rayGunGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.championRed,
      ["@lsp.mod.async"] = plt.championRed,
      ["@lsp.mod.static"] = plt.rannDefender,
      ["@lsp.mod.abstract"] = plt.rayGunGold,
      ["@lsp.mod.defaultLibrary"] = plt.rayGunGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Space Heroes – Adam Strange",
  author = "PrismPunk.nvim",
  description = "Zeta-Beam flash! Stranded on Rann, champion in red. "
    .. "Ray-gun blaster, quantum teleportation, Alanna's pink love, alien violet skies, "
    .. "and three red moons. Earth archaeologist turned cosmic defender.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.threeRedMoons,
    base09 = palette.blasterBeam,
    base0A = palette.rayGunGold,
    base0B = palette.zetaBeam,
    base0C = palette.teleportCyan,
    base0D = palette.quantumBlue,
    base0E = palette.alienSky,
    base0F = palette.championRed,
  },

  palette = palette,
  get = M.get,
}
