local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0A0A",
  bg_darker = "#151515",
  bg_dark = "#1F1F1F",
  bg_mid = "#2A2A2A",
  bg_light = "#353535",
  bg_lighter = "#404040",
  bg_lightest = "#4B4B4B",

  fg_lightest = "#E8E8E8",
  fg_light = "#C8C8C8",
  fg_mid = "#787878",
  fg_dark = "#585858",

  bg_alt1 = "#121212",
  bg_alt2 = "#050505",
  bg_alt3 = "#1A1A1A",
  bg_alt4 = "#0F0F0F",

  batSignalGold = "#D1C27A",
  utilityAmber = "#FFB86B",
  capeSteel = "#7F8C99",
  gothamBlue = "#3B6EA5",
  vigilantRed = "#CC4444",
  hologramTeal = "#66CCCC",
  arkhamPurple = "#8B66CC",
  justiceGlow = "#FFD966",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.batSignalGold,
      insert = plt.gothamBlue,
      visual = plt.hologramTeal,
      replace = plt.vigilantRed,
      command = plt.capeSteel,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.arkhamPurple,
      bg_visual = plt.hologramTeal,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.batSignalGold,
      header2 = plt.utilityAmber,
      special = plt.hologramTeal,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.gothamBlue,
      indent = plt.bg_lighter,
      indent_scope = plt.gothamBlue,
      picker = plt.vigilantRed,
      yank = plt.batSignalGold,
      mark = plt.hologramTeal,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.batSignalGold,
        bg_alternate = plt.bg_darkest,
        indicator = plt.capeSteel,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.batSignalGold,
      accent2 = plt.gothamBlue,
      accent3 = plt.hologramTeal,
      accent4 = plt.utilityAmber,
      accent5 = plt.capeSteel,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.batSignalGold,
      rainbow2 = plt.utilityAmber,
      rainbow3 = plt.hologramTeal,
      rainbow4 = plt.gothamBlue,
      rainbow5 = plt.capeSteel,
      rainbow6 = plt.vigilantRed,
      rainbow7 = plt.justiceGlow,
    },

    syn = {
      attribute = plt.utilityAmber,
      boolean = plt.hologramTeal,
      comment = plt.fg_dark,
      constant = plt.utilityAmber,
      deprecated = plt.fg_mid,
      func = plt.capeSteel,
      identifier = plt.fg_lightest,
      keyword = plt.gothamBlue,
      method = plt.hologramTeal,
      number = plt.justiceGlow,
      operator = plt.vigilantRed,
      parameter = plt.fg_mid,
      preproc = plt.hologramTeal,
      punct = plt.fg_mid,
      regex = plt.utilityAmber,
      statement = plt.gothamBlue,
      string = plt.hologramTeal,
      symbol = plt.vigilantRed,
      type = plt.hologramTeal,
      variable = plt.fg_lightest,
      special = plt.utilityAmber,
      special2 = plt.vigilantRed,
      special3 = plt.gothamBlue,
    },

    vcs = {
      added = plt.hologramTeal,
      removed = plt.vigilantRed,
      changed = plt.batSignalGold,
    },

    diff = {
      add = plt.hologramTeal,
      change = plt.batSignalGold,
      delete = plt.vigilantRed,
      text = plt.capeSteel,
    },

    diag = {
      ok = plt.hologramTeal,
      error = plt.vigilantRed,
      warning = plt.utilityAmber,
      info = plt.capeSteel,
      hint = plt.hologramTeal,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.vigilantRed,
      green = plt.hologramTeal,
      yellow = plt.batSignalGold,
      blue = plt.gothamBlue,
      magenta = plt.arkhamPurple,
      cyan = plt.hologramTeal,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.vigilantRed):brighten(0.2):to_hex(),
      green_bright = color(plt.hologramTeal):brighten(0.1):to_hex(),
      yellow_bright = color(plt.batSignalGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.gothamBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.arkhamPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.hologramTeal):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.utilityAmber,
      indexed2 = plt.vigilantRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.vigilantRed,
      ["@comment.warning"] = plt.utilityAmber,
      ["@comment.todo"] = plt.gothamBlue,
      ["@comment.note"] = plt.hologramTeal,

      ["@constant"] = plt.utilityAmber,
      ["@constant.builtin"] = plt.utilityAmber,
      ["@constant.macro"] = plt.utilityAmber,

      ["@string"] = plt.hologramTeal,
      ["@string.documentation"] = plt.hologramTeal,
      ["@string.regex"] = plt.utilityAmber,
      ["@string.escape"] = plt.justiceGlow,
      ["@string.special"] = plt.hologramTeal,
      ["@string.special.symbol"] = plt.vigilantRed,
      ["@string.special.url"] = plt.capeSteel,
      ["@string.special.path"] = plt.hologramTeal,

      ["@character"] = plt.hologramTeal,
      ["@character.special"] = plt.justiceGlow,

      ["@number"] = plt.justiceGlow,
      ["@number.float"] = plt.justiceGlow,

      ["@boolean"] = plt.hologramTeal,

      ["@function"] = plt.capeSteel,
      ["@function.builtin"] = plt.capeSteel,
      ["@function.call"] = plt.capeSteel,
      ["@function.macro"] = plt.hologramTeal,
      ["@function.method"] = plt.hologramTeal,
      ["@function.method.call"] = plt.hologramTeal,

      ["@constructor"] = plt.hologramTeal,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.gothamBlue,
      ["@keyword.coroutine"] = plt.arkhamPurple,
      ["@keyword.function"] = plt.gothamBlue,
      ["@keyword.operator"] = plt.vigilantRed,
      ["@keyword.return"] = plt.gothamBlue,
      ["@keyword.import"] = plt.capeSteel,
      ["@keyword.storage"] = plt.gothamBlue,
      ["@keyword.repeat"] = plt.gothamBlue,
      ["@keyword.conditional"] = plt.gothamBlue,
      ["@keyword.exception"] = plt.gothamBlue,
      ["@keyword.directive"] = plt.capeSteel,
      ["@keyword.directive.define"] = plt.capeSteel,

      ["@conditional"] = plt.gothamBlue,
      ["@conditional.ternary"] = plt.gothamBlue,

      ["@repeat"] = plt.gothamBlue,

      ["@label"] = plt.arkhamPurple,

      ["@operator"] = plt.vigilantRed,

      ["@exception"] = plt.gothamBlue,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.arkhamPurple,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.hologramTeal,
      ["@type.builtin"] = plt.hologramTeal,
      ["@type.definition"] = plt.hologramTeal,
      ["@type.qualifier"] = plt.gothamBlue,

      ["@attribute"] = plt.utilityAmber,
      ["@attribute.builtin"] = plt.justiceGlow,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.hologramTeal,
      ["@module.builtin"] = plt.hologramTeal,

      ["@namespace"] = plt.hologramTeal,
      ["@namespace.builtin"] = plt.hologramTeal,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.vigilantRed,

      ["@tag"] = plt.gothamBlue,
      ["@tag.attribute"] = plt.utilityAmber,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.gothamBlue,

      ["@markup.strong"] = { fg = plt.batSignalGold, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.hologramTeal, underline = true },
      ["@markup.heading"] = plt.batSignalGold,
      ["@markup.heading.1"] = plt.batSignalGold,
      ["@markup.heading.2"] = plt.justiceGlow,
      ["@markup.heading.3"] = plt.utilityAmber,
      ["@markup.heading.4"] = plt.gothamBlue,
      ["@markup.heading.5"] = plt.hologramTeal,
      ["@markup.heading.6"] = plt.capeSteel,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.hologramTeal,
      ["@markup.link"] = plt.capeSteel,
      ["@markup.link.label"] = plt.hologramTeal,
      ["@markup.link.url"] = plt.capeSteel,
      ["@markup.raw"] = plt.hologramTeal,
      ["@markup.raw.block"] = plt.hologramTeal,
      ["@markup.list"] = plt.gothamBlue,
      ["@markup.list.checked"] = plt.hologramTeal,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.hologramTeal,
      ["@diff.minus"] = plt.vigilantRed,
      ["@diff.delta"] = plt.batSignalGold,

      ["@none"] = "none",
      ["@conceal"] = plt.arkhamPurple,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.hologramTeal,
      ["@constructor.javascript"] = plt.hologramTeal,
      ["@constructor.typescript"] = plt.hologramTeal,
      ["@namespace.rust"] = plt.hologramTeal,
      ["@type.qualifier.rust"] = plt.gothamBlue,
      ["@constant.macro.c"] = plt.utilityAmber,
      ["@constant.macro.cpp"] = plt.utilityAmber,
      ["@namespace.go"] = plt.hologramTeal,
      ["@property.css"] = plt.capeSteel,
      ["@type.css"] = plt.gothamBlue,
      ["@label.json"] = plt.hologramTeal,
      ["@field.yaml"] = plt.capeSteel,
      ["@property.toml"] = plt.capeSteel,
      ["@function.builtin.bash"] = plt.capeSteel,
      ["@string.regexp"] = plt.utilityAmber,
      ["@character.special.regex"] = plt.justiceGlow,
    },

    lsp = {
      ["@lsp.type.class"] = plt.hologramTeal,
      ["@lsp.type.interface"] = plt.hologramTeal,
      ["@lsp.type.struct"] = plt.hologramTeal,
      ["@lsp.type.enum"] = plt.hologramTeal,
      ["@lsp.type.enumMember"] = plt.batSignalGold,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.hologramTeal,

      ["@lsp.type.macro"] = plt.utilityAmber,
      ["@lsp.type.decorator"] = plt.hologramTeal,

      ["@lsp.type.builtinType"] = plt.hologramTeal,
      ["@lsp.type.selfParameter"] = plt.arkhamPurple,
      ["@lsp.type.typeParameter"] = plt.hologramTeal,

      ["@lsp.type.array"] = plt.hologramTeal,
      ["@lsp.type.object"] = plt.hologramTeal,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.utilityAmber,
      ["@lsp.type.enumConstant"] = plt.batSignalGold,

      ["@lsp.type.event"] = plt.hologramTeal,
      ["@lsp.type.regexp"] = plt.utilityAmber,
      ["@lsp.type.unresolvedReference"] = plt.justiceGlow,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.batSignalGold,
      ["@lsp.mod.async"] = plt.gothamBlue,
      ["@lsp.mod.static"] = plt.arkhamPurple,
      ["@lsp.mod.abstract"] = plt.hologramTeal,
      ["@lsp.mod.defaultLibrary"] = plt.hologramTeal,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Justice League – Batman",
  author = "PrismPunk.nvim",
  description = "Detective in the dark — stealth, intellect, and steel.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.vigilantRed,
    base09 = palette.utilityAmber,
    base0A = palette.batSignalGold,
    base0B = palette.hologramTeal,
    base0C = palette.hologramTeal,
    base0D = palette.gothamBlue,
    base0E = palette.arkhamPurple,
    base0F = palette.justiceGlow,
  },

  palette = palette,
  get = M.get,
}
