local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050508",
  bg_darker = "#0A0A0E",
  bg_dark = "#0F0F14",
  bg_mid = "#16161D",
  bg_light = "#2D2D35",
  bg_lighter = "#44444D",
  bg_lightest = "#5A5A64",
  fg_lightest = "#F5F5F0",
  fg_light = "#E8E8D0",
  fg_mid = "#C0C0A8",
  fg_dark = "#90907A",
  bg_alt1 = "#0D0D12",
  bg_alt2 = "#070709",
  bg_alt3 = "#12121A",
  bg_alt4 = "#08080B",
  canaryYellow = "#FFFF00",
  sonicYellow = "#FFEB3B",
  screamGold = "#FFD700",
  brightYellow = "#FFEA00",
  blazeYellow = "#FFF44F",
  leatherBlack = "#0A0A0A",
  jacketBlack = "#1A1A1A",
  fishnetsBlack = "#0D0D0D",
  bootsBlack = "#2D2D2D",
  blondePlatinum = "#FFF8DC",
  hairGold = "#F0E68C",
  goldenLocks = "#FAFAD2",
  sonicWave = "#00FFFF",
  cryBlue = "#00E5FF",
  soundCyan = "#00BCD4",
  acousticTeal = "#008B8B",
  birdsOfPreyGreen = "#39FF14",
  arrowGreen = "#00FF00",
  justiceGreen = "#32CD32",
  passionRed = "#FF1744",
  dangerRed = "#DC143C",
  loveRed = "#E63946",
  nightclubPurple = "#9D4EDD",
  starCityViolet = "#8B00FF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.canaryYellow,
      insert = plt.sonicWave,
      visual = plt.sonicYellow,
      replace = plt.passionRed,
      command = plt.screamGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.screamGold,
      bg_visual = plt.sonicYellow,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.canaryYellow,
      header2 = plt.sonicWave,
      special = plt.birdsOfPreyGreen,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.canaryYellow,
      indent = plt.bg_lighter,
      indent_scope = plt.canaryYellow,
      picker = plt.passionRed,
      yank = plt.screamGold,
      mark = plt.sonicWave,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.canaryYellow,
        bg_alternate = plt.bg_darkest,
        indicator = plt.screamGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.canaryYellow,
      accent2 = plt.sonicWave,
      accent3 = plt.birdsOfPreyGreen,
      accent4 = plt.blondePlatinum,
      accent5 = plt.passionRed,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.canaryYellow,
      rainbow2 = plt.sonicWave,
      rainbow3 = plt.birdsOfPreyGreen,
      rainbow4 = plt.screamGold,
      rainbow5 = plt.passionRed,
      rainbow6 = plt.nightclubPurple,
      rainbow7 = plt.blondePlatinum,
    },

    syn = {
      attribute = plt.screamGold,
      boolean = plt.canaryYellow,
      comment = plt.fg_dark,
      constant = plt.screamGold,
      deprecated = plt.fg_mid,
      func = plt.sonicWave,
      identifier = plt.fg_lightest,
      keyword = plt.canaryYellow,
      method = plt.soundCyan,
      number = plt.blazeYellow,
      operator = plt.sonicWave,
      parameter = plt.fg_mid,
      preproc = plt.nightclubPurple,
      punct = plt.fg_mid,
      regex = plt.screamGold,
      statement = plt.canaryYellow,
      string = plt.blondePlatinum,
      symbol = plt.sonicWave,
      type = plt.screamGold,
      variable = plt.fg_lightest,
      special = plt.birdsOfPreyGreen,
      special2 = plt.passionRed,
      special3 = plt.sonicWave,
    },

    vcs = {
      added = plt.arrowGreen,
      removed = plt.passionRed,
      changed = plt.sonicYellow,
    },

    diff = {
      add = plt.arrowGreen,
      change = plt.sonicYellow,
      delete = plt.passionRed,
      text = plt.sonicWave,
    },

    diag = {
      ok = plt.justiceGreen,
      error = plt.dangerRed,
      warning = plt.blazeYellow,
      info = plt.cryBlue,
      hint = plt.soundCyan,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.passionRed,
      green = plt.birdsOfPreyGreen,
      yellow = plt.canaryYellow,
      blue = plt.sonicWave,
      magenta = plt.nightclubPurple,
      cyan = plt.soundCyan,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.passionRed):brighten(0.2):to_hex(),
      green_bright = color(plt.birdsOfPreyGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.canaryYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.sonicWave):brighten(0.3):to_hex(),
      magenta_bright = color(plt.nightclubPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.soundCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.screamGold,
      indexed2 = plt.passionRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.blazeYellow,
      ["@comment.todo"] = plt.canaryYellow,
      ["@comment.note"] = plt.sonicWave,

      ["@constant"] = plt.screamGold,
      ["@constant.builtin"] = plt.screamGold,
      ["@constant.macro"] = plt.brightYellow,

      ["@string"] = plt.blondePlatinum,
      ["@string.documentation"] = plt.blondePlatinum,
      ["@string.regex"] = plt.screamGold,
      ["@string.escape"] = plt.nightclubPurple,
      ["@string.special"] = plt.sonicWave,
      ["@string.special.symbol"] = plt.soundCyan,
      ["@string.special.url"] = plt.sonicWave,
      ["@string.special.path"] = plt.soundCyan,

      ["@character"] = plt.blondePlatinum,
      ["@character.special"] = plt.nightclubPurple,

      ["@number"] = plt.blazeYellow,
      ["@number.float"] = plt.blazeYellow,

      ["@boolean"] = plt.canaryYellow,

      ["@function"] = plt.sonicWave,
      ["@function.builtin"] = plt.sonicWave,
      ["@function.call"] = plt.sonicWave,
      ["@function.macro"] = plt.nightclubPurple,
      ["@function.method"] = plt.soundCyan,
      ["@function.method.call"] = plt.soundCyan,

      ["@constructor"] = plt.screamGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.canaryYellow,
      ["@keyword.coroutine"] = plt.sonicYellow,
      ["@keyword.function"] = plt.canaryYellow,
      ["@keyword.operator"] = plt.sonicWave,
      ["@keyword.return"] = plt.canaryYellow,
      ["@keyword.import"] = plt.sonicWave,
      ["@keyword.storage"] = plt.canaryYellow,
      ["@keyword.repeat"] = plt.canaryYellow,
      ["@keyword.conditional"] = plt.canaryYellow,
      ["@keyword.exception"] = plt.passionRed,
      ["@keyword.directive"] = plt.nightclubPurple,
      ["@keyword.directive.define"] = plt.nightclubPurple,

      ["@conditional"] = plt.canaryYellow,
      ["@conditional.ternary"] = plt.canaryYellow,

      ["@repeat"] = plt.canaryYellow,

      ["@label"] = plt.sonicYellow,

      ["@operator"] = plt.sonicWave,

      ["@exception"] = plt.passionRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.sonicYellow,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.screamGold,
      ["@type.builtin"] = plt.screamGold,
      ["@type.definition"] = plt.screamGold,
      ["@type.qualifier"] = plt.canaryYellow,

      ["@attribute"] = plt.screamGold,
      ["@attribute.builtin"] = plt.screamGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.screamGold,
      ["@module.builtin"] = plt.screamGold,

      ["@namespace"] = plt.screamGold,
      ["@namespace.builtin"] = plt.screamGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.sonicWave,

      ["@tag"] = plt.sonicWave,
      ["@tag.attribute"] = plt.screamGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.sonicWave,

      ["@markup.strong"] = { fg = plt.canaryYellow, bold = true },
      ["@markup.italic"] = { fg = plt.blondePlatinum, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.canaryYellow,
      ["@markup.heading.1"] = plt.canaryYellow,
      ["@markup.heading.2"] = plt.screamGold,
      ["@markup.heading.3"] = plt.sonicWave,
      ["@markup.heading.4"] = plt.birdsOfPreyGreen,
      ["@markup.heading.5"] = plt.nightclubPurple,
      ["@markup.heading.6"] = plt.passionRed,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.sonicWave,
      ["@markup.link"] = plt.sonicWave,
      ["@markup.link.label"] = plt.soundCyan,
      ["@markup.link.url"] = plt.cryBlue,
      ["@markup.raw"] = plt.blondePlatinum,
      ["@markup.raw.block"] = plt.blondePlatinum,
      ["@markup.list"] = plt.sonicWave,
      ["@markup.list.checked"] = plt.arrowGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.arrowGreen,
      ["@diff.minus"] = plt.passionRed,
      ["@diff.delta"] = plt.sonicYellow,

      ["@none"] = "none",
      ["@conceal"] = plt.nightclubPurple,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.screamGold,
      ["@constructor.javascript"] = plt.screamGold,
      ["@constructor.typescript"] = plt.screamGold,
      ["@namespace.rust"] = plt.screamGold,
      ["@type.qualifier.rust"] = plt.canaryYellow,
      ["@constant.macro.c"] = plt.brightYellow,
      ["@constant.macro.cpp"] = plt.brightYellow,
      ["@namespace.go"] = plt.screamGold,
      ["@property.css"] = plt.blondePlatinum,
      ["@type.css"] = plt.sonicWave,
      ["@label.json"] = plt.screamGold,
      ["@field.yaml"] = plt.blondePlatinum,
      ["@property.toml"] = plt.blondePlatinum,
      ["@function.builtin.bash"] = plt.sonicWave,
      ["@string.regexp"] = plt.screamGold,
      ["@character.special.regex"] = plt.nightclubPurple,
    },

    lsp = {
      ["@lsp.type.class"] = plt.screamGold,
      ["@lsp.type.interface"] = plt.screamGold,
      ["@lsp.type.struct"] = plt.screamGold,
      ["@lsp.type.enum"] = plt.screamGold,
      ["@lsp.type.enumMember"] = plt.canaryYellow,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.screamGold,

      ["@lsp.type.macro"] = plt.brightYellow,
      ["@lsp.type.decorator"] = plt.screamGold,

      ["@lsp.type.builtinType"] = plt.screamGold,
      ["@lsp.type.selfParameter"] = plt.sonicYellow,
      ["@lsp.type.typeParameter"] = plt.screamGold,

      ["@lsp.type.array"] = plt.screamGold,
      ["@lsp.type.object"] = plt.screamGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.canaryYellow,
      ["@lsp.type.enumConstant"] = plt.canaryYellow,

      ["@lsp.type.event"] = plt.screamGold,
      ["@lsp.type.regexp"] = plt.screamGold,
      ["@lsp.type.unresolvedReference"] = plt.screamGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.canaryYellow,
      ["@lsp.mod.async"] = plt.canaryYellow,
      ["@lsp.mod.static"] = plt.sonicYellow,
      ["@lsp.mod.abstract"] = plt.screamGold,
      ["@lsp.mod.defaultLibrary"] = plt.screamGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Birds of Prey – Black Canary",
  author = "PrismPunk.nvim",
  description = "Dinah Lance's Canary Cry! Bright yellow suit, sonic scream waves, "
    .. "platinum blonde hair, leather jacket black, and Birds of Prey green. "
    .. "Star City's songbird with a deadly voice.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.passionRed,
    base09 = palette.blazeYellow,
    base0A = palette.canaryYellow,
    base0B = palette.birdsOfPreyGreen,
    base0C = palette.sonicWave,
    base0D = palette.cryBlue,
    base0E = palette.nightclubPurple,
    base0F = palette.screamGold,
  },

  palette = palette,
  get = M.get,
}
