local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050712",
  bg_darker = "#0A0D14",
  bg_dark = "#0E1420",
  bg_mid = "#162437",
  bg_light = "#2F3840",
  bg_lighter = "#3D4A57",
  bg_lightest = "#4A5A6A",
  fg_lightest = "#FFF7E6",
  fg_light = "#EEF7FF",
  fg_mid = "#B7C5D6",
  fg_dark = "#5A6169",
  bg_alt1 = "#0F1521",
  bg_alt2 = "#070A10",
  bg_alt3 = "#12192A",
  bg_alt4 = "#060912",
  boostNavy = "#0F3A6B",
  circuitBlue = "#1A4F8C",
  pulseBlue = "#2F6FBF",
  ionBlue = "#3B8EFF",
  neonCyan = "#66FFFF",
  showGold = "#FFD700",
  sponsorSilver = "#D9D9E6",
  gloryWhite = "#FFF7E6",
  fameAmber = "#FFCC66",
  egoMagenta = "#FF99CC",
  timeGreen = "#66FF99",
  skeetsDanger = "#FF6666",
  ripHunterWarn = "#FFC870",
  futureInfo = "#61AFEF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.boostNavy,
      insert = plt.ionBlue,
      visual = plt.neonCyan,
      replace = plt.skeetsDanger,
      command = plt.showGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.showGold,
      bg_visual = plt.circuitBlue,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.showGold,
      header2 = plt.ionBlue,
      special = plt.neonCyan,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.ionBlue,
      indent = plt.bg_lighter,
      indent_scope = plt.ionBlue,
      picker = plt.fameAmber,
      yank = plt.showGold,
      mark = plt.neonCyan,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.ionBlue,
        bg_alternate = plt.bg_darkest,
        indicator = plt.showGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.ionBlue,
      accent2 = plt.showGold,
      accent3 = plt.neonCyan,
      accent4 = plt.sponsorSilver,
      accent5 = plt.skeetsDanger,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.ionBlue,
      rainbow2 = plt.showGold,
      rainbow3 = plt.neonCyan,
      rainbow4 = plt.circuitBlue,
      rainbow5 = plt.fameAmber,
      rainbow6 = plt.egoMagenta,
      rainbow7 = plt.timeGreen,
    },

    syn = {
      attribute = plt.showGold,
      boolean = plt.neonCyan,
      comment = plt.fg_dark,
      constant = plt.fameAmber,
      deprecated = plt.fg_mid,
      func = plt.ionBlue,
      identifier = plt.fg_lightest,
      keyword = plt.boostNavy,
      method = plt.neonCyan,
      number = plt.fameAmber,
      operator = plt.ionBlue,
      parameter = plt.fg_mid,
      preproc = plt.egoMagenta,
      punct = plt.fg_mid,
      regex = plt.fameAmber,
      statement = plt.boostNavy,
      string = plt.timeGreen,
      symbol = plt.neonCyan,
      type = plt.ionBlue,
      variable = plt.fg_lightest,
      special = plt.showGold,
      special2 = plt.neonCyan,
      special3 = plt.egoMagenta,
    },

    vcs = {
      added = plt.timeGreen,
      removed = plt.skeetsDanger,
      changed = plt.showGold,
    },

    diff = {
      add = plt.timeGreen,
      change = plt.showGold,
      delete = plt.skeetsDanger,
      text = plt.neonCyan,
    },

    diag = {
      ok = plt.timeGreen,
      error = plt.skeetsDanger,
      warning = plt.ripHunterWarn,
      info = plt.futureInfo,
      hint = plt.neonCyan,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.skeetsDanger,
      green = plt.timeGreen,
      yellow = plt.showGold,
      blue = plt.boostNavy,
      magenta = plt.egoMagenta,
      cyan = plt.neonCyan,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.skeetsDanger):brighten(0.2):to_hex(),
      green_bright = color(plt.timeGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.showGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.boostNavy):brighten(0.3):to_hex(),
      magenta_bright = color(plt.egoMagenta):brighten(0.2):to_hex(),
      cyan_bright = color(plt.neonCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.ionBlue,
      indexed2 = plt.showGold,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.skeetsDanger,
      ["@comment.warning"] = plt.ripHunterWarn,
      ["@comment.todo"] = plt.boostNavy,
      ["@comment.note"] = plt.neonCyan,

      ["@constant"] = plt.fameAmber,
      ["@constant.builtin"] = plt.fameAmber,
      ["@constant.macro"] = plt.fameAmber,

      ["@string"] = plt.timeGreen,
      ["@string.documentation"] = plt.timeGreen,
      ["@string.regex"] = plt.fameAmber,
      ["@string.escape"] = plt.egoMagenta,
      ["@string.special"] = plt.neonCyan,
      ["@string.special.symbol"] = plt.neonCyan,
      ["@string.special.url"] = plt.neonCyan,
      ["@string.special.path"] = plt.ionBlue,

      ["@character"] = plt.timeGreen,
      ["@character.special"] = plt.egoMagenta,

      ["@number"] = plt.fameAmber,
      ["@number.float"] = plt.fameAmber,

      ["@boolean"] = plt.neonCyan,

      ["@function"] = plt.ionBlue,
      ["@function.builtin"] = plt.ionBlue,
      ["@function.call"] = plt.ionBlue,
      ["@function.macro"] = plt.egoMagenta,
      ["@function.method"] = plt.neonCyan,
      ["@function.method.call"] = plt.neonCyan,

      ["@constructor"] = plt.ionBlue,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.boostNavy,
      ["@keyword.coroutine"] = plt.pulseBlue,
      ["@keyword.function"] = plt.boostNavy,
      ["@keyword.operator"] = plt.ionBlue,
      ["@keyword.return"] = plt.boostNavy,
      ["@keyword.import"] = plt.egoMagenta,
      ["@keyword.storage"] = plt.boostNavy,
      ["@keyword.repeat"] = plt.boostNavy,
      ["@keyword.conditional"] = plt.boostNavy,
      ["@keyword.exception"] = plt.skeetsDanger,
      ["@keyword.directive"] = plt.egoMagenta,
      ["@keyword.directive.define"] = plt.egoMagenta,

      ["@conditional"] = plt.boostNavy,
      ["@conditional.ternary"] = plt.boostNavy,

      ["@repeat"] = plt.boostNavy,

      ["@label"] = plt.pulseBlue,

      ["@operator"] = plt.ionBlue,

      ["@exception"] = plt.skeetsDanger,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.pulseBlue,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.ionBlue,
      ["@type.builtin"] = plt.ionBlue,
      ["@type.definition"] = plt.ionBlue,
      ["@type.qualifier"] = plt.boostNavy,

      ["@attribute"] = plt.showGold,
      ["@attribute.builtin"] = plt.showGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.ionBlue,
      ["@module.builtin"] = plt.ionBlue,

      ["@namespace"] = plt.ionBlue,
      ["@namespace.builtin"] = plt.ionBlue,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.neonCyan,

      ["@tag"] = plt.neonCyan,
      ["@tag.attribute"] = plt.showGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.neonCyan,

      ["@markup.strong"] = { fg = plt.showGold, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.boostNavy,
      ["@markup.heading.1"] = plt.showGold,
      ["@markup.heading.2"] = plt.ionBlue,
      ["@markup.heading.3"] = plt.neonCyan,
      ["@markup.heading.4"] = plt.circuitBlue,
      ["@markup.heading.5"] = plt.fameAmber,
      ["@markup.heading.6"] = plt.egoMagenta,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.ionBlue,
      ["@markup.link"] = plt.neonCyan,
      ["@markup.link.label"] = plt.ionBlue,
      ["@markup.link.url"] = plt.neonCyan,
      ["@markup.raw"] = plt.timeGreen,
      ["@markup.raw.block"] = plt.timeGreen,
      ["@markup.list"] = plt.neonCyan,
      ["@markup.list.checked"] = plt.timeGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.timeGreen,
      ["@diff.minus"] = plt.skeetsDanger,
      ["@diff.delta"] = plt.showGold,

      ["@none"] = "none",
      ["@conceal"] = plt.egoMagenta,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.ionBlue,
      ["@constructor.javascript"] = plt.ionBlue,
      ["@constructor.typescript"] = plt.ionBlue,
      ["@namespace.rust"] = plt.ionBlue,
      ["@type.qualifier.rust"] = plt.boostNavy,
      ["@constant.macro.c"] = plt.fameAmber,
      ["@constant.macro.cpp"] = plt.fameAmber,
      ["@namespace.go"] = plt.ionBlue,
      ["@property.css"] = plt.ionBlue,
      ["@type.css"] = plt.neonCyan,
      ["@label.json"] = plt.ionBlue,
      ["@field.yaml"] = plt.ionBlue,
      ["@property.toml"] = plt.ionBlue,
      ["@function.builtin.bash"] = plt.ionBlue,
      ["@string.regexp"] = plt.fameAmber,
      ["@character.special.regex"] = plt.egoMagenta,
    },

    lsp = {
      ["@lsp.type.class"] = plt.ionBlue,
      ["@lsp.type.interface"] = plt.ionBlue,
      ["@lsp.type.struct"] = plt.ionBlue,
      ["@lsp.type.enum"] = plt.ionBlue,
      ["@lsp.type.enumMember"] = plt.fameAmber,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.ionBlue,

      ["@lsp.type.macro"] = plt.fameAmber,
      ["@lsp.type.decorator"] = plt.showGold,

      ["@lsp.type.builtinType"] = plt.ionBlue,
      ["@lsp.type.selfParameter"] = plt.pulseBlue,
      ["@lsp.type.typeParameter"] = plt.ionBlue,

      ["@lsp.type.array"] = plt.ionBlue,
      ["@lsp.type.object"] = plt.ionBlue,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.fameAmber,
      ["@lsp.type.enumConstant"] = plt.fameAmber,

      ["@lsp.type.event"] = plt.ionBlue,
      ["@lsp.type.regexp"] = plt.fameAmber,
      ["@lsp.type.unresolvedReference"] = plt.fameAmber,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.fameAmber,
      ["@lsp.mod.async"] = plt.boostNavy,
      ["@lsp.mod.static"] = plt.pulseBlue,
      ["@lsp.mod.abstract"] = plt.ionBlue,
      ["@lsp.mod.defaultLibrary"] = plt.ionBlue,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Justice League – Booster Gold",
  author = "PrismPunk.nvim",
  description = "Greatest hero you've never heard of! Time-traveling showboat with sponsor deals, "
    .. "fame-seeking ego, and Skeets the robot sidekick.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.skeetsDanger,
    base09 = palette.fameAmber,
    base0A = palette.showGold,
    base0B = palette.timeGreen,
    base0C = palette.neonCyan,
    base0D = palette.boostNavy,
    base0E = palette.egoMagenta,
    base0F = palette.futureInfo,
  },

  palette = palette,
  get = M.get,
}
