local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#04050A",
  bg_darker = "#0B0D13",
  bg_dark = "#12141B",
  bg_mid = "#181A24",
  bg_light = "#2B2F36",
  bg_lighter = "#5B6069",
  bg_lightest = "#B8C7D6",

  fg_lightest = "#F2F7FF",
  fg_light = "#D9E6FF",
  fg_mid = "#B8C7D6",
  fg_dark = "#5B6069",

  bg_alt1 = "#0E1018",
  bg_alt2 = "#080913",
  bg_alt3 = "#151824",
  bg_alt4 = "#10121A",

  fateGold = "#FFD966",
  fateDeepBlue = "#2F5FA6",
  arcaneGlow = "#66E0FF",
  helmetBronze = "#B07A2D",
  voidMystic = "#8B66CC",
  destinyRose = "#FFB8D9",
  warningOracle = "#FFD280",
  dangerChaos = "#FF6666",
  infoAstral = "#61AFEF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.fateDeepBlue,
      insert = plt.arcaneGlow,
      visual = plt.fateGold,
      replace = plt.helmetBronze,
      command = plt.voidMystic,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.voidMystic,
      bg_visual = plt.fateDeepBlue,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.fateGold,
      header2 = plt.arcaneGlow,
      special = plt.destinyRose,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.fateDeepBlue,
      indent = plt.bg_lighter,
      indent_scope = plt.fateDeepBlue,
      picker = plt.fateGold,
      yank = plt.fateGold,
      mark = plt.destinyRose,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.fateGold,
        bg_alternate = plt.bg_darkest,
        indicator = plt.arcaneGlow,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.fateGold,
      accent2 = plt.fateDeepBlue,
      accent3 = plt.arcaneGlow,
      accent4 = plt.helmetBronze,
      accent5 = plt.voidMystic,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.fateGold,
      rainbow2 = plt.fateDeepBlue,
      rainbow3 = plt.arcaneGlow,
      rainbow4 = plt.helmetBronze,
      rainbow5 = plt.voidMystic,
      rainbow6 = plt.destinyRose,
      rainbow7 = plt.warningOracle,
    },

    syn = {
      attribute = plt.destinyRose,
      boolean = plt.arcaneGlow,
      comment = plt.fg_dark,
      constant = plt.fg_lightest,
      deprecated = plt.fg_mid,
      func = plt.voidMystic,
      identifier = plt.fg_lightest,
      keyword = plt.fateDeepBlue,
      method = plt.arcaneGlow,
      number = plt.warningOracle,
      operator = plt.arcaneGlow,
      parameter = plt.fg_mid,
      preproc = plt.voidMystic,
      punct = plt.fg_mid,
      regex = plt.destinyRose,
      statement = plt.fateDeepBlue,
      string = plt.fateGold,
      symbol = plt.helmetBronze,
      type = plt.helmetBronze,
      variable = plt.fg_lightest,
      special = plt.destinyRose,
      special2 = plt.arcaneGlow,
      special3 = plt.fateDeepBlue,
    },

    vcs = {
      added = plt.arcaneGlow,
      removed = plt.dangerChaos,
      changed = plt.fateGold,
    },

    diff = {
      add = plt.arcaneGlow,
      change = plt.fateGold,
      delete = plt.dangerChaos,
      text = plt.voidMystic,
    },

    diag = {
      ok = plt.arcaneGlow,
      error = plt.dangerChaos,
      warning = plt.warningOracle,
      info = plt.infoAstral,
      hint = plt.arcaneGlow,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.dangerChaos,
      green = plt.arcaneGlow,
      yellow = plt.fateGold,
      blue = plt.fateDeepBlue,
      magenta = plt.voidMystic,
      cyan = plt.arcaneGlow,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerChaos):brighten(0.2):to_hex(),
      green_bright = color(plt.arcaneGlow):brighten(0.1):to_hex(),
      yellow_bright = color(plt.fateGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.fateDeepBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.voidMystic):brighten(0.2):to_hex(),
      cyan_bright = color(plt.arcaneGlow):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.fateGold,
      indexed2 = plt.helmetBronze,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.dangerChaos,
      ["@comment.warning"] = plt.warningOracle,
      ["@comment.todo"] = plt.fateDeepBlue,
      ["@comment.note"] = plt.arcaneGlow,

      ["@constant"] = plt.fg_lightest,
      ["@constant.builtin"] = plt.fg_lightest,
      ["@constant.macro"] = plt.destinyRose,

      ["@string"] = plt.fateGold,
      ["@string.documentation"] = plt.fateGold,
      ["@string.regex"] = plt.destinyRose,
      ["@string.escape"] = plt.warningOracle,
      ["@string.special"] = plt.arcaneGlow,
      ["@string.special.symbol"] = plt.helmetBronze,
      ["@string.special.url"] = plt.voidMystic,
      ["@string.special.path"] = plt.fateGold,

      ["@character"] = plt.fateGold,
      ["@character.special"] = plt.warningOracle,

      ["@number"] = plt.warningOracle,
      ["@number.float"] = plt.warningOracle,

      ["@boolean"] = plt.arcaneGlow,

      ["@function"] = plt.voidMystic,
      ["@function.builtin"] = plt.voidMystic,
      ["@function.call"] = plt.voidMystic,
      ["@function.macro"] = plt.arcaneGlow,
      ["@function.method"] = plt.arcaneGlow,
      ["@function.method.call"] = plt.arcaneGlow,

      ["@constructor"] = plt.helmetBronze,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.fateDeepBlue,
      ["@keyword.coroutine"] = plt.voidMystic,
      ["@keyword.function"] = plt.fateDeepBlue,
      ["@keyword.operator"] = plt.arcaneGlow,
      ["@keyword.return"] = plt.fateDeepBlue,
      ["@keyword.import"] = plt.voidMystic,
      ["@keyword.storage"] = plt.fateDeepBlue,
      ["@keyword.repeat"] = plt.fateDeepBlue,
      ["@keyword.conditional"] = plt.fateDeepBlue,
      ["@keyword.exception"] = plt.fateDeepBlue,
      ["@keyword.directive"] = plt.voidMystic,
      ["@keyword.directive.define"] = plt.voidMystic,

      ["@conditional"] = plt.fateDeepBlue,
      ["@conditional.ternary"] = plt.fateDeepBlue,

      ["@repeat"] = plt.fateDeepBlue,

      ["@label"] = plt.voidMystic,

      ["@operator"] = plt.arcaneGlow,

      ["@exception"] = plt.fateDeepBlue,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.voidMystic,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.helmetBronze,
      ["@type.builtin"] = plt.helmetBronze,
      ["@type.definition"] = plt.helmetBronze,
      ["@type.qualifier"] = plt.fateDeepBlue,

      ["@attribute"] = plt.destinyRose,
      ["@attribute.builtin"] = plt.warningOracle,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.helmetBronze,
      ["@module.builtin"] = plt.helmetBronze,

      ["@namespace"] = plt.helmetBronze,
      ["@namespace.builtin"] = plt.helmetBronze,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.arcaneGlow,

      ["@tag"] = plt.fateDeepBlue,
      ["@tag.attribute"] = plt.destinyRose,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.fateDeepBlue,

      ["@markup.strong"] = { fg = plt.fateGold, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.arcaneGlow, underline = true },
      ["@markup.heading"] = plt.fateGold,
      ["@markup.heading.1"] = plt.fateGold,
      ["@markup.heading.2"] = plt.warningOracle,
      ["@markup.heading.3"] = plt.fateDeepBlue,
      ["@markup.heading.4"] = plt.voidMystic,
      ["@markup.heading.5"] = plt.arcaneGlow,
      ["@markup.heading.6"] = plt.voidMystic,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.arcaneGlow,
      ["@markup.link"] = plt.voidMystic,
      ["@markup.link.label"] = plt.arcaneGlow,
      ["@markup.link.url"] = plt.voidMystic,
      ["@markup.raw"] = plt.fateGold,
      ["@markup.raw.block"] = plt.fateGold,
      ["@markup.list"] = plt.fateDeepBlue,
      ["@markup.list.checked"] = plt.arcaneGlow,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.arcaneGlow,
      ["@diff.minus"] = plt.dangerChaos,
      ["@diff.delta"] = plt.fateGold,

      ["@none"] = "none",
      ["@conceal"] = plt.voidMystic,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.helmetBronze,
      ["@constructor.javascript"] = plt.helmetBronze,
      ["@constructor.typescript"] = plt.helmetBronze,
      ["@namespace.rust"] = plt.helmetBronze,
      ["@type.qualifier.rust"] = plt.fateDeepBlue,
      ["@constant.macro.c"] = plt.destinyRose,
      ["@constant.macro.cpp"] = plt.destinyRose,
      ["@namespace.go"] = plt.helmetBronze,
      ["@property.css"] = plt.voidMystic,
      ["@type.css"] = plt.fateDeepBlue,
      ["@label.json"] = plt.helmetBronze,
      ["@field.yaml"] = plt.voidMystic,
      ["@property.toml"] = plt.voidMystic,
      ["@function.builtin.bash"] = plt.voidMystic,
      ["@string.regexp"] = plt.destinyRose,
      ["@character.special.regex"] = plt.warningOracle,
    },

    lsp = {
      ["@lsp.type.class"] = plt.helmetBronze,
      ["@lsp.type.interface"] = plt.helmetBronze,
      ["@lsp.type.struct"] = plt.helmetBronze,
      ["@lsp.type.enum"] = plt.helmetBronze,
      ["@lsp.type.enumMember"] = plt.fateGold,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.helmetBronze,

      ["@lsp.type.macro"] = plt.destinyRose,
      ["@lsp.type.decorator"] = plt.helmetBronze,

      ["@lsp.type.builtinType"] = plt.helmetBronze,
      ["@lsp.type.selfParameter"] = plt.voidMystic,
      ["@lsp.type.typeParameter"] = plt.helmetBronze,

      ["@lsp.type.array"] = plt.helmetBronze,
      ["@lsp.type.object"] = plt.helmetBronze,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.fg_lightest,
      ["@lsp.type.enumConstant"] = plt.fateGold,

      ["@lsp.type.event"] = plt.helmetBronze,
      ["@lsp.type.regexp"] = plt.destinyRose,
      ["@lsp.type.unresolvedReference"] = plt.warningOracle,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.fateGold,
      ["@lsp.mod.async"] = plt.fateDeepBlue,
      ["@lsp.mod.static"] = plt.voidMystic,
      ["@lsp.mod.abstract"] = plt.helmetBronze,
      ["@lsp.mod.defaultLibrary"] = plt.helmetBronze,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Justice League – Dr Fate",
  author = "PrismPunk.nvim",
  description = "Order of destiny — gold mysticism and cosmic law.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.fateGold,
    base09 = palette.warningOracle,
    base0A = palette.fateGold,
    base0B = palette.arcaneGlow,
    base0C = palette.arcaneGlow,
    base0D = palette.fateDeepBlue,
    base0E = palette.voidMystic,
    base0F = palette.helmetBronze,
  },

  palette = palette,
  get = M.get,
}
