local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#07110B",
  bg_darker = "#0C120B",
  bg_dark = "#121617",
  bg_mid = "#182220",
  bg_light = "#1E2824",
  bg_lighter = "#242E28",
  bg_lightest = "#2A342E",

  fg_lightest = "#E8F4EE",
  fg_light = "#C5D3CB",
  fg_mid = "#90A096",
  fg_dark = "#6A7470",

  bg_alt1 = "#0E1812",
  bg_alt2 = "#050A07",
  bg_alt3 = "#0B2F1C",
  bg_alt4 = "#091309",

  voidCore = "#2B9A56",
  voidGlow = "#3FA963",
  voidBright = "#28C268",
  voidDeep = "#0F3F25",
  voidDark = "#0A2818",

  corruptedRage = "#F06C6C",
  corruptedAvarice = "#FFE080",
  corruptedFear = "#F0D090",
  corruptedWill = "#28C268",
  corruptedHope = "#70BFFF",
  corruptedLove = "#F06C6C",
  corruptedCompassion = "#80ECFF",

  emerald = "#28C268",
  forest = "#2B9A56",
  quiverBrown = "#8A5F38",
  arrowFeather = "#A8D8C8",
  hoodDark = "#16543A",
  moss = "#3FA963",
  stoneGray = "#C5D3CB",
  shadowGray = "#4A5450",
  dimGray = "#6A7470",
  accentGold = "#FFE080",
  accentCyan = "#80ECFF",
  lightGray = "#E8F4EE",
  dangerRed = "#F06C6C",
  warningOrange = "#F0D090",
  infoBlue = "#70BFFF",
  urbanGrit = "#4A5450",
  leatherBrown = "#6A4A2E",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.emerald,
      insert = plt.forest,
      visual = plt.hoodDark,
      replace = plt.dangerRed,
      command = plt.accentGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.voidDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.hoodDark,
      header1 = plt.emerald,
      header2 = plt.accentGold,
      special = plt.arrowFeather,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.hoodDark,
      indent = plt.bg_lighter,
      indent_scope = plt.forest,
      picker = plt.dangerRed,
      yank = plt.accentGold,
      mark = plt.arrowFeather,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.emerald,
        bg_alternate = plt.bg_darkest,
        indicator = plt.forest,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.hoodDark,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.emerald,
      accent2 = plt.forest,
      accent3 = plt.accentGold,
      accent4 = plt.arrowFeather,
      accent5 = plt.quiverBrown,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.emerald,
      rainbow2 = plt.forest,
      rainbow3 = plt.moss,
      rainbow4 = plt.accentGold,
      rainbow5 = plt.arrowFeather,
      rainbow6 = plt.accentCyan,
      rainbow7 = plt.quiverBrown,
    },

    syn = {
      attribute = plt.accentGold,
      boolean = plt.arrowFeather,
      comment = plt.shadowGray,
      constant = plt.moss,
      deprecated = plt.dimGray,
      func = plt.accentGold,
      identifier = plt.fg_lightest,
      keyword = plt.emerald,
      method = plt.arrowFeather,
      number = plt.quiverBrown,
      operator = plt.accentCyan,
      parameter = plt.fg_light,
      preproc = plt.forest,
      punct = plt.fg_mid,
      regex = plt.accentCyan,
      statement = plt.emerald,
      string = plt.voidBright,
      symbol = plt.quiverBrown,
      type = plt.arrowFeather,
      variable = plt.fg_lightest,
      special = plt.accentGold,
      special2 = plt.accentCyan,
      special3 = plt.forest,
    },

    vcs = {
      added = plt.emerald,
      removed = plt.dangerRed,
      changed = plt.accentGold,
    },

    diff = {
      add = plt.emerald,
      change = plt.accentGold,
      delete = plt.dangerRed,
      text = plt.accentCyan,
    },

    diag = {
      ok = plt.emerald,
      error = plt.dangerRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      hint = plt.accentCyan,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.dangerRed,
      green = plt.emerald,
      yellow = plt.accentGold,
      blue = plt.infoBlue,
      magenta = plt.arrowFeather,
      cyan = plt.accentCyan,
      white = plt.stoneGray,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerRed):brighten(0.2):to_hex(),
      green_bright = color(plt.emerald):brighten(0.1):to_hex(),
      yellow_bright = color(plt.accentGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.infoBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.arrowFeather):brighten(0.2):to_hex(),
      cyan_bright = color(plt.accentCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.stoneGray):brighten(0.2):to_hex(),
      indexed1 = plt.accentGold,
      indexed2 = plt.dangerRed,
    },

    treesitter = {
      ["@comment"] = plt.shadowGray,
      ["@comment.documentation"] = plt.dimGray,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningOrange,
      ["@comment.todo"] = plt.infoBlue,
      ["@comment.note"] = plt.accentCyan,

      ["@constant"] = plt.moss,
      ["@constant.builtin"] = plt.moss,
      ["@constant.macro"] = plt.accentGold,

      ["@string"] = plt.voidBright,
      ["@string.documentation"] = plt.voidBright,
      ["@string.regex"] = plt.accentCyan,
      ["@string.escape"] = plt.accentGold,
      ["@string.special"] = plt.arrowFeather,
      ["@string.special.symbol"] = plt.quiverBrown,
      ["@string.special.url"] = plt.accentCyan,
      ["@string.special.path"] = plt.voidBright,

      ["@character"] = plt.voidBright,
      ["@character.special"] = plt.accentGold,

      ["@number"] = plt.quiverBrown,
      ["@number.float"] = plt.quiverBrown,

      ["@boolean"] = plt.arrowFeather,

      ["@function"] = plt.accentGold,
      ["@function.builtin"] = plt.accentGold,
      ["@function.call"] = plt.accentGold,
      ["@function.macro"] = plt.forest,
      ["@function.method"] = plt.arrowFeather,
      ["@function.method.call"] = plt.arrowFeather,

      ["@constructor"] = plt.arrowFeather,

      ["@parameter"] = plt.fg_light,
      ["@parameter.builtin"] = plt.fg_lightest,

      ["@keyword"] = plt.emerald,
      ["@keyword.coroutine"] = plt.forest,
      ["@keyword.function"] = plt.emerald,
      ["@keyword.operator"] = plt.accentCyan,
      ["@keyword.return"] = plt.emerald,
      ["@keyword.import"] = plt.forest,
      ["@keyword.storage"] = plt.emerald,
      ["@keyword.repeat"] = plt.emerald,
      ["@keyword.conditional"] = plt.emerald,
      ["@keyword.exception"] = plt.dangerRed,
      ["@keyword.directive"] = plt.forest,
      ["@keyword.directive.define"] = plt.forest,

      ["@conditional"] = plt.emerald,
      ["@conditional.ternary"] = plt.emerald,

      ["@repeat"] = plt.emerald,

      ["@label"] = plt.moss,

      ["@operator"] = plt.accentCyan,

      ["@exception"] = plt.dangerRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.forest,
      ["@variable.parameter"] = plt.fg_light,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.arrowFeather,
      ["@type.builtin"] = plt.arrowFeather,
      ["@type.definition"] = plt.arrowFeather,
      ["@type.qualifier"] = plt.emerald,

      ["@attribute"] = plt.accentGold,
      ["@attribute.builtin"] = plt.accentGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.arrowFeather,
      ["@module.builtin"] = plt.arrowFeather,

      ["@namespace"] = plt.arrowFeather,
      ["@namespace.builtin"] = plt.arrowFeather,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.quiverBrown,

      ["@tag"] = plt.emerald,
      ["@tag.attribute"] = plt.accentGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.emerald,

      ["@markup.strong"] = { fg = plt.emerald, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.shadowGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.arrowFeather, underline = true },
      ["@markup.heading"] = plt.emerald,
      ["@markup.heading.1"] = plt.emerald,
      ["@markup.heading.2"] = plt.accentGold,
      ["@markup.heading.3"] = plt.forest,
      ["@markup.heading.4"] = plt.arrowFeather,
      ["@markup.heading.5"] = plt.moss,
      ["@markup.heading.6"] = plt.accentCyan,
      ["@markup.quote"] = plt.dimGray,
      ["@markup.math"] = plt.arrowFeather,
      ["@markup.link"] = plt.accentCyan,
      ["@markup.link.label"] = plt.arrowFeather,
      ["@markup.link.url"] = plt.accentCyan,
      ["@markup.raw"] = plt.voidBright,
      ["@markup.raw.block"] = plt.voidBright,
      ["@markup.list"] = plt.emerald,
      ["@markup.list.checked"] = plt.emerald,
      ["@markup.list.unchecked"] = plt.dimGray,

      ["@diff.plus"] = plt.emerald,
      ["@diff.minus"] = plt.dangerRed,
      ["@diff.delta"] = plt.accentGold,

      ["@none"] = "none",
      ["@conceal"] = plt.voidDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.arrowFeather,
      ["@constructor.javascript"] = plt.arrowFeather,
      ["@constructor.typescript"] = plt.arrowFeather,
      ["@namespace.rust"] = plt.arrowFeather,
      ["@type.qualifier.rust"] = plt.emerald,
      ["@constant.macro.c"] = plt.accentGold,
      ["@constant.macro.cpp"] = plt.accentGold,
      ["@namespace.go"] = plt.arrowFeather,
      ["@property.css"] = plt.arrowFeather,
      ["@type.css"] = plt.emerald,
      ["@label.json"] = plt.arrowFeather,
      ["@field.yaml"] = plt.arrowFeather,
      ["@property.toml"] = plt.arrowFeather,
      ["@function.builtin.bash"] = plt.accentGold,
      ["@string.regexp"] = plt.accentCyan,
      ["@character.special.regex"] = plt.accentGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.arrowFeather,
      ["@lsp.type.interface"] = plt.arrowFeather,
      ["@lsp.type.struct"] = plt.arrowFeather,
      ["@lsp.type.enum"] = plt.arrowFeather,
      ["@lsp.type.enumMember"] = plt.moss,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.arrowFeather,

      ["@lsp.type.macro"] = plt.accentGold,
      ["@lsp.type.decorator"] = plt.arrowFeather,

      ["@lsp.type.builtinType"] = plt.arrowFeather,
      ["@lsp.type.selfParameter"] = plt.forest,
      ["@lsp.type.typeParameter"] = plt.arrowFeather,

      ["@lsp.type.array"] = plt.arrowFeather,
      ["@lsp.type.object"] = plt.arrowFeather,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.moss,
      ["@lsp.type.enumConstant"] = plt.moss,

      ["@lsp.type.event"] = plt.arrowFeather,
      ["@lsp.type.regexp"] = plt.accentCyan,
      ["@lsp.type.unresolvedReference"] = plt.accentGold,

      ["@lsp.mod.deprecated"] = { fg = plt.dimGray, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.moss,
      ["@lsp.mod.async"] = plt.emerald,
      ["@lsp.mod.static"] = plt.forest,
      ["@lsp.mod.abstract"] = plt.arrowFeather,
      ["@lsp.mod.defaultLibrary"] = plt.arrowFeather,
      ["@lsp.mod.documentation"] = plt.dimGray,
    },
  }
end

return {
  name = "Justice League – Green Arrow",
  author = "PrismPunk.nvim",
  description = "Urban archer—precision, craft, and grit.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.arrowFeather,
    base08 = palette.dangerRed,
    base09 = palette.quiverBrown,
    base0A = palette.accentGold,
    base0B = palette.emerald,
    base0C = palette.accentCyan,
    base0D = palette.infoBlue,
    base0E = palette.forest,
    base0F = palette.moss,
  },

  palette = palette,
  get = M.get,
}
