local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#070507",
  bg_darker = "#0E0B0B",
  bg_dark = "#131216",
  bg_mid = "#19171B",
  bg_light = "#1F1D21",
  bg_lighter = "#252327",
  bg_lightest = "#2B292D",

  fg_lightest = "#EFE7E6",
  fg_light = "#C5BBB8",
  fg_mid = "#B0A39A",
  fg_dark = "#7A7370",

  bg_alt1 = "#100E10",
  bg_alt2 = "#050305",
  bg_alt3 = "#1C1A1E",
  bg_alt4 = "#0A0809",

  voidCore = "#B06F2D",
  voidGlow = "#D48842",
  voidBright = "#E89F58",
  voidDeep = "#8A5724",
  voidDark = "#5A3A18",

  corruptedRage = "#D94F4F",
  corruptedAvarice = "#FFD966",
  corruptedFear = "#FFC870",
  corruptedWill = "#2F8A5A",
  corruptedHope = "#61AFEF",
  corruptedLove = "#C94A4A",
  corruptedCompassion = "#66D9CC",

  bronze = "#B06F2D",
  wingGreen = "#2F8A5A",
  flameRed = "#C94A4A",
  leather = "#312A24",
  feather = "#FFD9B3",
  accentTeal = "#66D9CC",
  stoneGray = "#B0A39A",
  shadowGray = "#332F30",
  dimGray = "#5A5354",
  lightGray = "#EFE7E6",
  accentGold = "#FFD966",
  dangerRed = "#D94F4F",
  warningOrange = "#FFC870",
  infoBlue = "#61AFEF",

  nthMetal = "#D48842",
  maceStrike = "#E85C5C",
  wingSpan = "#3FA96F",
  thanagar = "#B07A3A",
  warriorSpirit = "#C94A4A",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.bronze,
      insert = plt.wingGreen,
      visual = plt.flameRed,
      replace = plt.maceStrike,
      command = plt.accentGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.voidDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.bronze,
      header1 = plt.nthMetal,
      header2 = plt.flameRed,
      special = plt.accentTeal,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bronze,
      indent = plt.bg_lighter,
      indent_scope = plt.bronze,
      picker = plt.maceStrike,
      yank = plt.accentGold,
      mark = plt.wingSpan,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.nthMetal,
        bg_alternate = plt.bg_darkest,
        indicator = plt.bronze,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.bronze,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.bronze,
      accent2 = plt.nthMetal,
      accent3 = plt.flameRed,
      accent4 = plt.wingGreen,
      accent5 = plt.accentGold,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.flameRed,
      rainbow2 = plt.maceStrike,
      rainbow3 = plt.bronze,
      rainbow4 = plt.accentGold,
      rainbow5 = plt.wingGreen,
      rainbow6 = plt.wingSpan,
      rainbow7 = plt.accentTeal,
    },

    syn = {
      attribute = plt.accentGold,
      boolean = plt.wingGreen,
      comment = plt.shadowGray,
      constant = plt.leather,
      deprecated = plt.dimGray,
      func = plt.wingGreen,
      identifier = plt.fg_lightest,
      keyword = plt.bronze,
      method = plt.wingSpan,
      number = plt.accentGold,
      operator = plt.accentTeal,
      parameter = plt.fg_mid,
      preproc = plt.nthMetal,
      punct = plt.fg_mid,
      regex = plt.accentTeal,
      statement = plt.bronze,
      string = plt.nthMetal,
      symbol = plt.flameRed,
      type = plt.feather,
      variable = plt.fg_lightest,
      special = plt.flameRed,
      special2 = plt.accentTeal,
      special3 = plt.thanagar,
    },

    vcs = {
      added = plt.wingGreen,
      removed = plt.maceStrike,
      changed = plt.accentGold,
    },

    diff = {
      add = plt.wingGreen,
      change = plt.accentGold,
      delete = plt.maceStrike,
      text = plt.accentTeal,
    },

    diag = {
      ok = plt.wingGreen,
      error = plt.dangerRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      hint = plt.accentTeal,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.flameRed,
      green = plt.wingGreen,
      yellow = plt.accentGold,
      blue = plt.infoBlue,
      magenta = plt.warriorSpirit,
      cyan = plt.accentTeal,
      white = plt.stoneGray,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.flameRed):brighten(0.2):to_hex(),
      green_bright = color(plt.wingGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.accentGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.infoBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.warriorSpirit):brighten(0.2):to_hex(),
      cyan_bright = color(plt.accentTeal):brighten(0.1):to_hex(),
      white_bright = color(plt.stoneGray):brighten(0.2):to_hex(),
      indexed1 = plt.accentGold,
      indexed2 = plt.flameRed,
    },

    treesitter = {
      ["@comment"] = plt.shadowGray,
      ["@comment.documentation"] = plt.dimGray,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningOrange,
      ["@comment.todo"] = plt.infoBlue,
      ["@comment.note"] = plt.accentTeal,

      ["@constant"] = plt.leather,
      ["@constant.builtin"] = plt.leather,
      ["@constant.macro"] = plt.accentGold,

      ["@string"] = plt.nthMetal,
      ["@string.documentation"] = plt.nthMetal,
      ["@string.regex"] = plt.accentTeal,
      ["@string.escape"] = plt.accentGold,
      ["@string.special"] = plt.feather,
      ["@string.special.symbol"] = plt.flameRed,
      ["@string.special.url"] = plt.accentTeal,
      ["@string.special.path"] = plt.nthMetal,

      ["@character"] = plt.nthMetal,
      ["@character.special"] = plt.accentGold,

      ["@number"] = plt.accentGold,
      ["@number.float"] = plt.accentGold,

      ["@boolean"] = plt.wingGreen,

      ["@function"] = plt.wingGreen,
      ["@function.builtin"] = plt.wingGreen,
      ["@function.call"] = plt.wingGreen,
      ["@function.macro"] = plt.nthMetal,
      ["@function.method"] = plt.wingSpan,
      ["@function.method.call"] = plt.wingSpan,

      ["@constructor"] = plt.feather,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.bronze,
      ["@keyword.coroutine"] = plt.nthMetal,
      ["@keyword.function"] = plt.bronze,
      ["@keyword.operator"] = plt.accentTeal,
      ["@keyword.return"] = plt.bronze,
      ["@keyword.import"] = plt.nthMetal,
      ["@keyword.storage"] = plt.bronze,
      ["@keyword.repeat"] = plt.bronze,
      ["@keyword.conditional"] = plt.bronze,
      ["@keyword.exception"] = plt.maceStrike,
      ["@keyword.directive"] = plt.nthMetal,
      ["@keyword.directive.define"] = plt.nthMetal,

      ["@conditional"] = plt.bronze,
      ["@conditional.ternary"] = plt.bronze,

      ["@repeat"] = plt.bronze,

      ["@label"] = plt.nthMetal,

      ["@operator"] = plt.accentTeal,

      ["@exception"] = plt.maceStrike,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.nthMetal,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.feather,
      ["@type.builtin"] = plt.feather,
      ["@type.definition"] = plt.feather,
      ["@type.qualifier"] = plt.bronze,

      ["@attribute"] = plt.accentGold,
      ["@attribute.builtin"] = plt.accentGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.feather,
      ["@module.builtin"] = plt.feather,

      ["@namespace"] = plt.feather,
      ["@namespace.builtin"] = plt.feather,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.flameRed,

      ["@tag"] = plt.bronze,
      ["@tag.attribute"] = plt.accentGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.bronze,

      ["@markup.strong"] = { fg = plt.flameRed, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.shadowGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.feather, underline = true },
      ["@markup.heading"] = plt.bronze,
      ["@markup.heading.1"] = plt.flameRed,
      ["@markup.heading.2"] = plt.nthMetal,
      ["@markup.heading.3"] = plt.accentGold,
      ["@markup.heading.4"] = plt.wingGreen,
      ["@markup.heading.5"] = plt.wingSpan,
      ["@markup.heading.6"] = plt.accentTeal,
      ["@markup.quote"] = plt.dimGray,
      ["@markup.math"] = plt.feather,
      ["@markup.link"] = plt.accentTeal,
      ["@markup.link.label"] = plt.wingSpan,
      ["@markup.link.url"] = plt.accentTeal,
      ["@markup.raw"] = plt.nthMetal,
      ["@markup.raw.block"] = plt.nthMetal,
      ["@markup.list"] = plt.bronze,
      ["@markup.list.checked"] = plt.wingGreen,
      ["@markup.list.unchecked"] = plt.dimGray,

      ["@diff.plus"] = plt.wingGreen,
      ["@diff.minus"] = plt.maceStrike,
      ["@diff.delta"] = plt.accentGold,

      ["@none"] = "none",
      ["@conceal"] = plt.voidDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.feather,
      ["@constructor.javascript"] = plt.feather,
      ["@constructor.typescript"] = plt.feather,
      ["@namespace.rust"] = plt.feather,
      ["@type.qualifier.rust"] = plt.bronze,
      ["@constant.macro.c"] = plt.accentGold,
      ["@constant.macro.cpp"] = plt.accentGold,
      ["@namespace.go"] = plt.feather,
      ["@property.css"] = plt.wingSpan,
      ["@type.css"] = plt.bronze,
      ["@label.json"] = plt.feather,
      ["@field.yaml"] = plt.wingSpan,
      ["@property.toml"] = plt.wingSpan,
      ["@function.builtin.bash"] = plt.wingGreen,
      ["@string.regexp"] = plt.accentTeal,
      ["@character.special.regex"] = plt.accentGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.feather,
      ["@lsp.type.interface"] = plt.feather,
      ["@lsp.type.struct"] = plt.feather,
      ["@lsp.type.enum"] = plt.feather,
      ["@lsp.type.enumMember"] = plt.leather,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.feather,

      ["@lsp.type.macro"] = plt.accentGold,
      ["@lsp.type.decorator"] = plt.feather,

      ["@lsp.type.builtinType"] = plt.feather,
      ["@lsp.type.selfParameter"] = plt.nthMetal,
      ["@lsp.type.typeParameter"] = plt.feather,

      ["@lsp.type.array"] = plt.feather,
      ["@lsp.type.object"] = plt.feather,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.leather,
      ["@lsp.type.enumConstant"] = plt.leather,

      ["@lsp.type.event"] = plt.feather,
      ["@lsp.type.regexp"] = plt.accentTeal,
      ["@lsp.type.unresolvedReference"] = plt.accentGold,

      ["@lsp.mod.deprecated"] = { fg = plt.dimGray, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.leather,
      ["@lsp.mod.async"] = plt.bronze,
      ["@lsp.mod.static"] = plt.nthMetal,
      ["@lsp.mod.abstract"] = plt.feather,
      ["@lsp.mod.defaultLibrary"] = plt.feather,
      ["@lsp.mod.documentation"] = plt.dimGray,
    },
  }
end

return {
  name = "Justice League – Hawkgirl",
  author = "PrismPunk.nvim",
  description = "Resilient warrior—bronze wings and fierce heart.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stoneGray,
    base06 = palette.lightGray,
    base07 = palette.feather,
    base08 = palette.flameRed,
    base09 = palette.thanagar,
    base0A = palette.accentGold,
    base0B = palette.wingGreen,
    base0C = palette.accentTeal,
    base0D = palette.wingSpan,
    base0E = palette.bronze,
    base0F = palette.leather,
  },

  palette = palette,
  get = M.get,
}
