local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a0d14",
  bg_darker = "#241520",
  bg_dark = "#2e1d2c",
  bg_mid = "#382838",
  bg_light = "#423244",
  bg_lighter = "#4c3d50",
  bg_lightest = "#56485c",
  bg_alt1 = "#2a1826",
  bg_alt2 = "#3d2a3a",
  bg_alt3 = "#504050",
  bg_alt4 = "#635466",
  fg_lightest = "#f0ddef",
  fg_light = "#d8c4d6",
  fg_mid = "#a88ea6",
  fg_dark = "#887088",
  falconCloak = "#C4556A",
  seidrFlame = "#C87A9E",
  brisingamen = "#C8960A",
  amberTear = "#E2AE38",
  sessrumnir = "#8AAE6E",
  folkvangrDew = "#5AADA0",
  vanaBloom = "#B07AB8",
  catSilver = "#8A9EBE",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.catSilver,
      insert = plt.sessrumnir,
      visual = plt.vanaBloom,
      replace = plt.falconCloak,
      command = plt.amberTear,
    },
    accent = {
      accent1 = plt.catSilver,
      accent2 = plt.brisingamen,
      accent3 = plt.folkvangrDew,
      accent4 = plt.fg_light,
      accent5 = plt.falconCloak,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.falconCloak,
      rainbow2 = plt.seidrFlame,
      rainbow3 = plt.amberTear,
      rainbow4 = plt.brisingamen,
      rainbow5 = plt.sessrumnir,
      rainbow6 = plt.folkvangrDew,
      rainbow7 = plt.vanaBloom,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.amberTear,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.amberTear,
      header2 = plt.catSilver,
      special = plt.brisingamen,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.vanaBloom,
      indent = plt.bg_light,
      indent_scope = plt.catSilver,
      picker = plt.vanaBloom,
      yank = plt.amberTear,
      mark = plt.falconCloak,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.amberTear,
        indicator = plt.catSilver,
      },
    },
    syn = {
      attribute = plt.brisingamen,
      boolean = plt.brisingamen,
      comment = plt.fg_mid,
      constant = plt.brisingamen,
      deprecated = plt.fg_dark,
      func = plt.catSilver,
      identifier = plt.fg_lightest,
      keyword = plt.seidrFlame,
      method = plt.catSilver,
      number = plt.seidrFlame,
      operator = plt.falconCloak,
      parameter = plt.fg_light,
      preproc = plt.vanaBloom,
      punct = plt.fg_mid,
      regex = plt.brisingamen,
      special = plt.amberTear,
      special2 = plt.vanaBloom,
      special3 = plt.folkvangrDew,
      statement = plt.vanaBloom,
      string = plt.sessrumnir,
      symbol = plt.falconCloak,
      type = plt.folkvangrDew,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.falconCloak,
      warning = plt.amberTear,
      info = plt.catSilver,
      ok = plt.sessrumnir,
      hint = plt.folkvangrDew,
      virtual_text_error = plt.falconCloak,
      virtual_text_warning = plt.amberTear,
      virtual_text_info = plt.catSilver,
      virtual_text_ok = plt.sessrumnir,
      virtual_text_hint = plt.folkvangrDew,
    },
    diff = {
      add = plt.sessrumnir,
      add_inline = plt.folkvangrDew,
      change = plt.amberTear,
      change_inline = plt.brisingamen,
      delete = plt.falconCloak,
      delete_inline = plt.seidrFlame,
      text = plt.catSilver,
    },
    vcs = {
      added = plt.sessrumnir,
      changed = plt.amberTear,
      removed = plt.falconCloak,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.falconCloak,
      green = plt.sessrumnir,
      yellow = plt.amberTear,
      blue = plt.catSilver,
      magenta = plt.vanaBloom,
      cyan = plt.folkvangrDew,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.falconCloak):brighten(0.2):to_hex(),
      green_bright = color(plt.sessrumnir):brighten(0.1):to_hex(),
      yellow_bright = color(plt.amberTear):brighten(0.2):to_hex(),
      blue_bright = color(plt.catSilver):brighten(0.3):to_hex(),
      magenta_bright = color(plt.vanaBloom):brighten(0.2):to_hex(),
      cyan_bright = color(plt.folkvangrDew):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.brisingamen,
      indexed2 = plt.seidrFlame,
    },
  }
end

return {
  name = "Vanaheim – Freyja",
  author = "PrismPunk",
  description = "Goddess of love, beauty, seiðr magic, and the Brísingamen necklace. "
    .. "Deep plum-wine nights lit by falcon-cloak rose, seiðr orchid-flame, "
    .. "amber tears, and dwarf-forged gold — with Fólkvangr dew and silver "
    .. "cat-fur as cool counterpoints to the warm enchantment.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.falconCloak,
    base09 = palette.seidrFlame,
    base0A = palette.amberTear,
    base0B = palette.sessrumnir,
    base0C = palette.folkvangrDew,
    base0D = palette.catSilver,
    base0E = palette.vanaBloom,
    base0F = palette.brisingamen,
  },
  palette = palette,
  get = M.get,
}
