local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0C0E10",
  bg_darker = "#121416",
  bg_dark = "#181C1E",
  bg_mid = "#1E2426",
  bg_light = "#262C2E",
  bg_lighter = "#2E3436",
  bg_lightest = "#363C3E",
  fg_lightest = "#F5F8FA",
  fg_light = "#E0E8ED",
  fg_mid = "#C0CCD6",
  fg_dark = "#98A8B4",
  bg_alt1 = "#14181A",
  bg_alt2 = "#0E1012",
  bg_alt3 = "#1A1E22",
  bg_alt4 = "#101214",
  atomicOrangeCore = "#F55A24",
  atomicOrangeBright = "#FF8558",
  atomicOrangeDeep = "#E54918",
  atomicOrangeDark = "#CC3810",
  chromeBlueCore = "#0096C7",
  chromeBlueBright = "#48CAE4",
  chromeBlueDeep = "#0077B6",
  chromeBlueDark = "#03045E",
  reactorGreenCore = "#05E095",
  reactorGreenBright = "#39FFB9",
  reactorGreenDeep = "#04C780",
  reactorGreenDark = "#039B68",
  raygunRedCore = "#E63958",
  raygunRedBright = "#F26888",
  raygunRedDeep = "#D82648",
  raygunRedDark = "#BB1838",
  turbineYellowCore = "#FFC300",
  turbineYellowBright = "#FFE040",
  turbineYellowDeep = "#E6AF00",
  jetAgeBlueCore = "#3ABEEB",
  jetAgeBlueBright = "#72D5F5",
  jetAgeBlueDeep = "#28A3D6",
  jetAgeBlueDark = "#1A7FA0",
  spaceWhiteCore = "#E9ECEF",
  spaceWhiteBright = "#FFFFFF",
  rocketSilverCore = "#9DA5AD",
  rocketSilverBright = "#C8CED4",
  nucleusVioletCore = "#A552C6",
  nucleusVioletBright = "#C57EE6",
  geigerCore = "#00C4E6",
  geigerBright = "#33E1FF",
  radiumGlowCore = "#9BEB1B",
  radiumGlowBright = "#C1FF5C",
  falloutGray = "#7B8590",
  falloutGrayBright = "#A0AAB5",
  steelGray = "#6C7A89",
  steelGrayLight = "#8895A4",
  successGreen = "#06FFA5",
  warningAmber = "#FFD60A",
  infoBlue = "#00B4D8",
  errorRed = "#EF476F",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.chromeBlueCore,
      insert = plt.reactorGreenCore,
      visual = plt.atomicOrangeCore,
      replace = plt.raygunRedCore,
      command = plt.turbineYellowCore,
    },
    accent = {
      accent1 = plt.chromeBlueCore,
      accent2 = plt.atomicOrangeCore,
      accent3 = plt.reactorGreenCore,
      accent4 = plt.turbineYellowCore,
      accent5 = plt.jetAgeBlueCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.atomicOrangeBright,
      rainbow2 = plt.chromeBlueBright,
      rainbow3 = plt.reactorGreenBright,
      rainbow4 = plt.turbineYellowBright,
      rainbow5 = plt.jetAgeBlueBright,
      rainbow6 = plt.nucleusVioletBright,
      rainbow7 = plt.radiumGlowBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.turbineYellowBright,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.steelGray,
      header1 = plt.chromeBlueBright,
      header2 = plt.turbineYellowBright,
      special = plt.jetAgeBlueCore,
      nontext = plt.bg_lightest,
      whitespace = plt.falloutGray,
      win_separator = plt.steelGray,
      indent = plt.bg_lighter,
      indent_scope = plt.chromeBlueCore,
      picker = plt.nucleusVioletCore,
      yank = plt.turbineYellowBright,
      mark = plt.atomicOrangeBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.steelGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.steelGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.steelGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.chromeBlueBright,
        indicator = plt.chromeBlueCore,
      },
    },
    syn = {
      attribute = plt.turbineYellowCore,
      boolean = plt.jetAgeBlueCore,
      comment = plt.falloutGray,
      constant = plt.spaceWhiteCore,
      deprecated = plt.falloutGray,
      func = plt.reactorGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.chromeBlueCore,
      method = plt.reactorGreenBright,
      number = plt.spaceWhiteCore,
      operator = plt.atomicOrangeCore,
      parameter = plt.fg_mid,
      preproc = plt.nucleusVioletCore,
      punct = plt.fg_dark,
      regex = plt.geigerCore,
      special = plt.jetAgeBlueCore,
      special2 = plt.nucleusVioletCore,
      special3 = plt.radiumGlowCore,
      statement = plt.chromeBlueCore,
      string = plt.reactorGreenCore,
      symbol = plt.turbineYellowCore,
      type = plt.rocketSilverCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.jetAgeBlueCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.jetAgeBlueCore,
    },
    diff = {
      add = plt.reactorGreenCore,
      add_inline = plt.reactorGreenDeep,
      change = plt.turbineYellowCore,
      change_inline = plt.turbineYellowDeep,
      delete = plt.raygunRedCore,
      delete_inline = plt.raygunRedDeep,
      text = plt.jetAgeBlueCore,
    },
    vcs = {
      added = plt.reactorGreenCore,
      changed = plt.turbineYellowCore,
      removed = plt.raygunRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.raygunRedCore,
      green = plt.reactorGreenCore,
      yellow = plt.turbineYellowCore,
      blue = plt.chromeBlueCore,
      magenta = plt.nucleusVioletCore,
      cyan = plt.jetAgeBlueCore,
      white = plt.spaceWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.raygunRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.reactorGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.turbineYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.chromeBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.nucleusVioletBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.jetAgeBlueBright):brighten(0.15):to_hex(),
      white_bright = plt.spaceWhiteBright,
      indexed1 = plt.turbineYellowCore,
      indexed2 = plt.nucleusVioletCore,
    },
  }
end

return {
  name = "Punk – Atompunk",
  author = "PrismPunk.nvim",
  description = "1950s retro-futurism — atomic orange, chrome blue, reactor green, jet age optimism.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.falloutGray,
    base04 = palette.steelGray,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.raygunRedCore,
    base09 = palette.atomicOrangeCore,
    base0A = palette.turbineYellowCore,
    base0B = palette.reactorGreenCore,
    base0C = palette.jetAgeBlueCore,
    base0D = palette.chromeBlueCore,
    base0E = palette.nucleusVioletCore,
    base0F = palette.rocketSilverCore,
  },
  palette = palette,
  get = M.get,
}
