local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#08100A",
  bg_darker = "#0E160F",
  bg_dark = "#141C15",
  bg_mid = "#1A241B",
  bg_light = "#202C21",
  bg_lighter = "#263427",
  bg_lightest = "#2C3C2D",
  fg_lightest = "#E8F5EA",
  fg_light = "#D0E4D2",
  fg_mid = "#B0C8B2",
  fg_dark = "#88A88A",
  bg_alt1 = "#101812",
  bg_alt2 = "#0A100C",
  bg_alt3 = "#161E17",
  bg_alt4 = "#0C140D",
  dnaGreenCore = "#2EE610",
  dnaGreenBright = "#5AFF3D",
  dnaGreenDeep = "#26CC0C",
  dnaGreenDark = "#1FA008",
  mutationPinkCore = "#E60DD9",
  mutationPinkBright = "#FF3FF5",
  mutationPinkDeep = "#CC0AC0",
  mutationPinkDark = "#A008A0",
  cellCyanCore = "#00E6B4",
  cellCyanBright = "#33FFD4",
  cellCyanDeep = "#00CC9F",
  cellCyanDark = "#00A080",
  petriYellowCore = "#D4E600",
  petriYellowBright = "#F0FF33",
  petriYellowDeep = "#BCCC00",
  petriYellowDark = "#98A000",
  biohazardOrangeCore = "#E65C00",
  biohazardOrangeBright = "#FF8533",
  biohazardOrangeDeep = "#CC5000",
  biohazardOrangeDark = "#A04000",
  enzymeBlueCore = "#00B4E6",
  enzymeBlueBright = "#33D4FF",
  enzymeBlueDeep = "#009FCC",
  enzymeBlueDark = "#0080A0",
  tissueRedCore = "#E62E5C",
  tissueRedBright = "#FF5C85",
  tissueRedDeep = "#CC2650",
  tissueRedDark = "#A01F40",
  organVioletCore = "#A024E0",
  organVioletBright = "#C74FFF",
  organVioletDeep = "#8C1FCC",
  organVioletDark = "#7018A0",
  synapseGoldCore = "#E69E00",
  synapseGoldBright = "#FFC233",
  synapseGoldDeep = "#CC8800",
  synapseGoldDark = "#A06A00",
  cultureMediumCore = "#78C088",
  cultureMediumBright = "#98E4A8",
  specimenWhiteCore = "#E0F5E0",
  specimenWhiteBright = "#FFFFFF",
  contaminationRedCore = "#C81230",
  labGray = "#6A7A6A",
  labGrayLight = "#7A8A7A",
  labGrayDark = "#5A6A5A",
  successGreen = "#39FF14",
  warningAmber = "#FFB000",
  infoBlue = "#00C8FF",
  errorRed = "#DC143C",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.dnaGreenCore,
      insert = plt.cellCyanCore,
      visual = plt.mutationPinkCore,
      replace = plt.tissueRedCore,
      command = plt.enzymeBlueCore,
    },
    accent = {
      accent1 = plt.dnaGreenCore,
      accent2 = plt.mutationPinkCore,
      accent3 = plt.cellCyanCore,
      accent4 = plt.organVioletCore,
      accent5 = plt.petriYellowCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.dnaGreenBright,
      rainbow2 = plt.mutationPinkBright,
      rainbow3 = plt.cellCyanBright,
      rainbow4 = plt.petriYellowBright,
      rainbow5 = plt.enzymeBlueBright,
      rainbow6 = plt.organVioletBright,
      rainbow7 = plt.biohazardOrangeBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.petriYellowBright,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.labGray,
      header1 = plt.dnaGreenBright,
      header2 = plt.mutationPinkBright,
      special = plt.organVioletCore,
      nontext = plt.bg_lightest,
      whitespace = plt.labGrayDark,
      win_separator = plt.labGray,
      indent = plt.bg_lighter,
      indent_scope = plt.dnaGreenCore,
      picker = plt.organVioletCore,
      yank = plt.petriYellowBright,
      mark = plt.mutationPinkBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.labGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.labGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.labGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.dnaGreenBright,
        indicator = plt.dnaGreenCore,
      },
    },
    syn = {
      attribute = plt.synapseGoldCore,
      boolean = plt.cellCyanCore,
      comment = plt.labGray,
      constant = plt.specimenWhiteCore,
      deprecated = plt.labGrayDark,
      func = plt.cellCyanCore,
      identifier = plt.fg_lightest,
      keyword = plt.dnaGreenCore,
      method = plt.cellCyanBright,
      number = plt.specimenWhiteCore,
      operator = plt.mutationPinkCore,
      parameter = plt.fg_mid,
      preproc = plt.organVioletCore,
      punct = plt.fg_dark,
      regex = plt.enzymeBlueCore,
      special = plt.organVioletCore,
      special2 = plt.enzymeBlueBright,
      special3 = plt.biohazardOrangeCore,
      statement = plt.dnaGreenCore,
      string = plt.cellCyanCore,
      symbol = plt.synapseGoldCore,
      type = plt.cultureMediumCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.organVioletCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.organVioletCore,
    },
    diff = {
      add = plt.dnaGreenCore,
      add_inline = plt.dnaGreenDeep,
      change = plt.synapseGoldCore,
      change_inline = plt.synapseGoldDeep,
      delete = plt.contaminationRedCore,
      delete_inline = plt.tissueRedDeep,
      text = plt.organVioletCore,
    },
    vcs = {
      added = plt.dnaGreenCore,
      changed = plt.synapseGoldCore,
      removed = plt.contaminationRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.tissueRedCore,
      green = plt.dnaGreenCore,
      yellow = plt.petriYellowCore,
      blue = plt.enzymeBlueCore,
      magenta = plt.mutationPinkCore,
      cyan = plt.cellCyanCore,
      white = plt.specimenWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.tissueRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.dnaGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.petriYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.enzymeBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.mutationPinkBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.cellCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.specimenWhiteBright,
      indexed1 = plt.dnaGreenCore,
      indexed2 = plt.mutationPinkCore,
    },
  }
end

return {
  name = "Punk – Biopunk",
  author = "PrismPunk.nvim",
  description = "Genetic manipulation — DNA green, mutation pink, cell cyan, organic laboratory.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.labGray,
    base04 = palette.labGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.tissueRedCore,
    base09 = palette.biohazardOrangeCore,
    base0A = palette.petriYellowCore,
    base0B = palette.dnaGreenCore,
    base0C = palette.cellCyanCore,
    base0D = palette.enzymeBlueCore,
    base0E = palette.mutationPinkCore,
    base0F = palette.organVioletCore,
  },
  palette = palette,
  get = M.get,
}
