local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0E14",
  bg_darker = "#101820",
  bg_dark = "#16202A",
  bg_mid = "#1D2934",
  bg_light = "#24323E",
  bg_lighter = "#2B3B48",
  bg_lightest = "#334452",
  fg_lightest = "#E6F7FF",
  fg_light = "#C2E3F5",
  fg_mid = "#9DCFE3",
  fg_dark = "#78B5CD",
  bg_alt1 = "#121A24",
  bg_alt2 = "#0C1016",
  bg_alt3 = "#1A242E",
  bg_alt4 = "#0E1419",
  glacierBlueCore = "#6FB3D2",
  glacierBlueBright = "#91C9E3",
  glacierBlueDeep = "#5C9AB8",
  frostCyanCore = "#66D9EF",
  frostCyanBright = "#88E5F5",
  frostCyanDeep = "#52B0C4",
  crystalBlueCore = "#82AAFF",
  crystalBlueBright = "#A3C4FF",
  crystalBlueDeep = "#6A8FD9",
  arcticWhiteCore = "#D4E7F5",
  arcticWhiteBright = "#EBF5FF",
  frozenPurpleCore = "#A89BE3",
  frozenPurpleBright = "#C4B8F5",
  frozenPurpleDeep = "#8E7FCC",
  permafrostGray = "#5B6F7C",
  permafrostGrayLight = "#738A99",
  permafrostGrayDark = "#475866",
  iceBlueCore = "#7DD3FC",
  iceBlueBright = "#A5E4FF",
  blizzardWhiteCore = "#F0F9FF",
  blizzardWhiteBright = "#FFFFFF",
  subzeroCyanCore = "#4FC3F7",
  subzeroCyanBright = "#6FD6FF",
  tundraTealCore = "#4DD0E1",
  tundraTealBright = "#6FE0ED",
  currentGray = "#5B6F7C",
  currentGrayLight = "#738A99",
  icicleVioletCore = "#9C8FDB",
  voidBlack = "#0A0E14",
  successGreen = "#4DD0E1",
  errorRed = "#FF6B9D",
  warningAmber = "#7DD3FC",
  infoBlue = "#82AAFF",
  frostbiteRedCore = "#FF6B9D",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.glacierBlueCore,
      insert = plt.frostCyanCore,
      visual = plt.crystalBlueCore,
      replace = plt.frostbiteRedCore,
      command = plt.arcticWhiteCore,
    },
    accent = {
      accent1 = plt.glacierBlueCore,
      accent2 = plt.crystalBlueCore,
      accent3 = plt.frostCyanCore,
      accent4 = plt.arcticWhiteCore,
      accent5 = plt.frozenPurpleCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.glacierBlueBright,
      rainbow2 = plt.frostCyanBright,
      rainbow3 = plt.crystalBlueBright,
      rainbow4 = plt.arcticWhiteBright,
      rainbow5 = plt.frozenPurpleBright,
      rainbow6 = plt.iceBlueBright,
      rainbow7 = plt.tundraTealBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.iceBlueCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.currentGray,
      header1 = plt.crystalBlueBright,
      header2 = plt.arcticWhiteBright,
      special = plt.frozenPurpleCore,
      nontext = plt.bg_lightest,
      whitespace = plt.permafrostGrayDark,
      win_separator = plt.currentGray,
      indent = plt.bg_lighter,
      indent_scope = plt.glacierBlueCore,
      picker = plt.icicleVioletCore,
      yank = plt.iceBlueBright,
      mark = plt.tundraTealBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.currentGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.currentGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.currentGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.glacierBlueBright,
        indicator = plt.glacierBlueCore,
      },
    },
    syn = {
      attribute = plt.iceBlueCore,
      boolean = plt.crystalBlueCore,
      comment = plt.permafrostGray,
      constant = plt.blizzardWhiteCore,
      deprecated = plt.voidBlack,
      func = plt.frostCyanCore,
      identifier = plt.fg_lightest,
      keyword = plt.glacierBlueCore,
      method = plt.frostCyanBright,
      number = plt.blizzardWhiteCore,
      operator = plt.arcticWhiteCore,
      parameter = plt.fg_mid,
      preproc = plt.frozenPurpleCore,
      punct = plt.fg_dark,
      regex = plt.icicleVioletCore,
      special = plt.frozenPurpleCore,
      special2 = plt.icicleVioletCore,
      special3 = plt.iceBlueCore,
      statement = plt.glacierBlueCore,
      string = plt.frostCyanCore,
      symbol = plt.iceBlueCore,
      type = plt.crystalBlueCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.frozenPurpleCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.frozenPurpleCore,
    },
    diff = {
      add = plt.tundraTealCore,
      add_inline = plt.tundraTealBright,
      change = plt.iceBlueBright,
      change_inline = plt.iceBlueBright,
      delete = plt.frostbiteRedCore,
      delete_inline = plt.errorRed,
      text = plt.frozenPurpleCore,
    },
    vcs = {
      added = plt.tundraTealCore,
      changed = plt.iceBlueBright,
      removed = plt.frostbiteRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.frostbiteRedCore,
      green = plt.tundraTealCore,
      yellow = plt.iceBlueCore,
      blue = plt.crystalBlueCore,
      magenta = plt.frozenPurpleCore,
      cyan = plt.frostCyanCore,
      white = plt.blizzardWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.frostbiteRedCore):brighten(0.15):to_hex(),
      green_bright = color(plt.tundraTealBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.iceBlueBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.crystalBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.frozenPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.frostCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.blizzardWhiteBright,
      indexed1 = plt.glacierBlueCore,
      indexed2 = plt.frozenPurpleCore,
    },
  }
end

return {
  name = "Punk – Cryopunk",
  author = "PrismPunk.nvim",
  description = "Frozen wasteland — glacier blue, frost cyan, crystal ice, arctic white, subzero cold.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.permafrostGray,
    base04 = palette.permafrostGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.frostbiteRedCore,
    base09 = palette.iceBlueCore,
    base0A = palette.arcticWhiteCore,
    base0B = palette.frostCyanCore,
    base0C = palette.tundraTealCore,
    base0D = palette.glacierBlueCore,
    base0E = palette.frozenPurpleCore,
    base0F = palette.icicleVioletCore,
  },
  palette = palette,
  get = M.get,
}
