local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0908",
  bg_darker = "#121110",
  bg_dark = "#1A1816",
  bg_mid = "#23201C",
  bg_light = "#2C2822",
  bg_lighter = "#353028",
  bg_lightest = "#3E382E",
  fg_lightest = "#E8E4DC",
  fg_light = "#D0C8BC",
  fg_mid = "#B0A898",
  fg_dark = "#8A8070",
  bg_alt1 = "#161412",
  bg_alt2 = "#0D0C0A",
  bg_alt3 = "#1E1C18",
  bg_alt4 = "#0F0E0C",
  dieselYellowCore = "#CCA900",
  dieselYellowBright = "#FFD700",
  dieselYellowDeep = "#B39500",
  dieselYellowDark = "#8A7500",
  factoryOrangeCore = "#C2601F",
  factoryOrangeBright = "#E87F3F",
  factoryOrangeDeep = "#B05418",
  factoryOrangeDark = "#8A4212",
  steelGrayCore = "#5E6A7A",
  steelGrayBright = "#7E8A9A",
  steelGrayDeep = "#4E5A6A",
  steelGrayDark = "#3E4A5A",
  militaryGreenCore = "#3F5230",
  militaryGreenBright = "#5A6F4A",
  militaryGreenDeep = "#354526",
  militaryGreenDark = "#28351C",
  mechRedCore = "#8F2828",
  mechRedBright = "#B83838",
  mechRedDeep = "#802020",
  mechRedDark = "#601818",
  chromeWhiteCore = "#C8C8C8",
  chromeWhiteBright = "#E8E8E8",
  artDecoGoldCore = "#B59400",
  artDecoGoldBright = "#DDB700",
  metropolisBluCore = "#2F4F68",
  metropolisBlueBright = "#4A6F8A",
  exhaustGray = "#4A4840",
  exhaustGrayBright = "#6A6860",
  engineBrownCore = "#4E3E30",
  engineBrownBright = "#6E5A4A",
  tankGreenCore = "#445235",
  sootBlackLight = "#3A3630",
  successGreen = "#4A5F3A",
  warningAmber = "#E6BE00",
  infoBlue = "#3A5F7A",
  errorRed = "#A03030",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.steelGrayCore,
      insert = plt.militaryGreenCore,
      visual = plt.dieselYellowCore,
      replace = plt.mechRedCore,
      command = plt.metropolisBluCore,
    },
    accent = {
      accent1 = plt.steelGrayCore,
      accent2 = plt.dieselYellowCore,
      accent3 = plt.factoryOrangeCore,
      accent4 = plt.militaryGreenCore,
      accent5 = plt.artDecoGoldCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.dieselYellowBright,
      rainbow2 = plt.factoryOrangeBright,
      rainbow3 = plt.steelGrayBright,
      rainbow4 = plt.militaryGreenBright,
      rainbow5 = plt.metropolisBlueBright,
      rainbow6 = plt.artDecoGoldBright,
      rainbow7 = plt.mechRedBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.dieselYellowBright,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.exhaustGrayBright, -- Brighter for better contrast
      header1 = plt.dieselYellowBright,
      header2 = plt.factoryOrangeBright,
      special = plt.metropolisBluCore,
      nontext = plt.fg_dark, -- Better contrast than bg_lightest
      whitespace = plt.exhaustGray,
      win_separator = plt.exhaustGrayBright, -- Brighter for better contrast
      indent = plt.bg_lighter,
      indent_scope = plt.steelGrayCore,
      picker = plt.artDecoGoldCore,
      yank = plt.dieselYellowBright,
      mark = plt.factoryOrangeBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.fg_light, -- Better contrast than bg_lightest
      line_nr_dim = plt.fg_dark, -- Better contrast than bg_lighter
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.exhaustGrayBright, -- Brighter for better contrast
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.exhaustGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.exhaustGray,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_mid, -- Better contrast than fg_dark
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.metropolisBlueBright,
        indicator = plt.steelGrayCore,
      },
    },
    syn = {
      attribute = plt.artDecoGoldCore,
      boolean = plt.factoryOrangeCore,
      comment = plt.exhaustGrayBright, -- Brighter for better contrast
      constant = plt.chromeWhiteCore,
      deprecated = plt.exhaustGray, -- Better contrast than sootBlackLight
      func = plt.militaryGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.steelGrayCore,
      method = plt.militaryGreenBright,
      number = plt.chromeWhiteCore,
      operator = plt.dieselYellowCore,
      parameter = plt.fg_light,
      preproc = plt.metropolisBluCore,
      punct = plt.fg_mid, -- Brighter for better contrast
      regex = plt.tankGreenCore,
      special = plt.metropolisBluCore,
      special2 = plt.factoryOrangeCore,
      special3 = plt.mechRedCore,
      statement = plt.steelGrayCore,
      string = plt.militaryGreenBright, -- Brighter for better contrast
      symbol = plt.artDecoGoldCore,
      type = plt.engineBrownCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.metropolisBluCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.metropolisBluCore,
    },
    diff = {
      add = plt.militaryGreenCore,
      add_inline = plt.militaryGreenDeep,
      change = plt.factoryOrangeCore,
      change_inline = plt.factoryOrangeBright,
      delete = plt.mechRedCore,
      delete_inline = plt.mechRedDeep,
      text = plt.metropolisBluCore,
    },
    vcs = {
      added = plt.militaryGreenCore,
      changed = plt.factoryOrangeCore,
      removed = plt.mechRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.mechRedCore,
      green = plt.militaryGreenCore,
      yellow = plt.dieselYellowCore,
      blue = plt.metropolisBluCore,
      magenta = plt.engineBrownCore,
      cyan = plt.steelGrayCore,
      white = plt.chromeWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.mechRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.militaryGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.dieselYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.metropolisBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.engineBrownBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.steelGrayBright):brighten(0.18):to_hex(),
      white_bright = color(plt.chromeWhiteBright):brighten(0.1):to_hex(),
      indexed1 = plt.dieselYellowCore,
      indexed2 = plt.metropolisBluCore,
    },
  }
end

return {
  name = "Punk – Dieselpunk",
  author = "PrismPunk.nvim",
  description = "Industrial revolution — diesel yellow, steel gray, military green, Art Deco machinery.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.exhaustGray,
    base04 = palette.exhaustGrayBright,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.mechRedCore,
    base09 = palette.factoryOrangeCore,
    base0A = palette.dieselYellowCore,
    base0B = palette.militaryGreenCore,
    base0C = palette.steelGrayCore,
    base0D = palette.metropolisBluCore,
    base0E = palette.artDecoGoldCore,
    base0F = palette.engineBrownCore,
  },
  palette = palette,
  get = M.get,
}
