local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0606",
  bg_darker = "#120C0C",
  bg_dark = "#1A1212",
  bg_mid = "#241818",
  bg_light = "#2E1E1E",
  bg_lighter = "#382424",
  bg_lightest = "#422A2A",
  fg_lightest = "#F5E8E8",
  fg_light = "#E0C8C8",
  fg_mid = "#C0A0A0",
  fg_dark = "#A07878",
  bg_alt1 = "#160E0E",
  bg_alt2 = "#0E0808",
  bg_alt3 = "#1E1414",
  bg_alt4 = "#100A0A",
  bloodRedCore = "#C81230",
  bloodRedBright = "#E63958",
  arterialSplashCore = "#E60000",
  arterialSplashBright = "#FF3333",
  visceralPinkCore = "#E61285",
  visceralPinkBright = "#FF3DAA",
  bruisePurpleCore = "#7A007A",
  bruisePurpleBright = "#A020A0",
  goreOrangeCore = "#E63E00",
  goreOrangeBright = "#FF6633",
  fleshToneCore = "#D8AC98",
  fleshToneBright = "#F8CCB8",
  lacerationRedCore = "#7A0000",
  lacerationRedBright = "#A52A2A",
  mutilationMaroonCore = "#70001C",
  mutilationMaroonBright = "#A0003A",
  carnageYellowCore = "#E6C200",
  carnageYellowBright = "#FFE433",
  boneWhiteCore = "#E5E5CC",
  boneWhiteBright = "#FFFFF0",
  infectionGreenCore = "#1E7A1E",
  infectionGreenBright = "#32A032",
  shockGray = "#6A5A5A",
  shockGrayLight = "#7A6A6A",
  traumaBlack = "#1A1212",
  successGreen = "#228B22",
  warningAmber = "#FFD700",
  infoBlue = "#4169E1",
  errorRed = "#DC143C",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.bloodRedCore,
      insert = plt.infectionGreenCore,
      visual = plt.visceralPinkCore,
      replace = plt.arterialSplashCore,
      command = plt.bruisePurpleCore,
    },
    accent = {
      accent1 = plt.bloodRedCore,
      accent2 = plt.arterialSplashCore,
      accent3 = plt.visceralPinkCore,
      accent4 = plt.bruisePurpleCore,
      accent5 = plt.goreOrangeCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.arterialSplashBright,
      rainbow2 = plt.bloodRedBright,
      rainbow3 = plt.visceralPinkBright,
      rainbow4 = plt.goreOrangeBright,
      rainbow5 = plt.bruisePurpleBright,
      rainbow6 = plt.lacerationRedBright,
      rainbow7 = plt.mutilationMaroonBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.carnageYellowCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.shockGray,
      header1 = plt.bloodRedBright,
      header2 = plt.carnageYellowBright,
      special = plt.visceralPinkCore,
      nontext = plt.bg_lightest,
      whitespace = plt.shockGrayLight,
      win_separator = plt.shockGray,
      indent = plt.bg_lighter,
      indent_scope = plt.bloodRedCore,
      picker = plt.bruisePurpleCore,
      yank = plt.carnageYellowBright,
      mark = plt.arterialSplashBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.shockGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.shockGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.shockGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.bloodRedBright,
        indicator = plt.bloodRedCore,
      },
    },
    syn = {
      attribute = plt.carnageYellowCore,
      boolean = plt.visceralPinkCore,
      comment = plt.shockGray,
      constant = plt.boneWhiteCore,
      deprecated = plt.traumaBlack,
      func = plt.arterialSplashCore,
      identifier = plt.fg_lightest,
      keyword = plt.bloodRedCore,
      method = plt.arterialSplashBright,
      number = plt.boneWhiteCore,
      operator = plt.visceralPinkCore,
      parameter = plt.fg_mid,
      preproc = plt.bruisePurpleCore,
      punct = plt.fg_dark,
      regex = plt.goreOrangeCore,
      special = plt.bruisePurpleCore,
      special2 = plt.goreOrangeCore,
      special3 = plt.infectionGreenCore,
      statement = plt.bloodRedCore,
      string = plt.arterialSplashCore,
      symbol = plt.carnageYellowCore,
      type = plt.fleshToneCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.bruisePurpleCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.bruisePurpleCore,
    },
    diff = {
      add = plt.infectionGreenCore,
      add_inline = plt.infectionGreenBright,
      change = plt.goreOrangeCore,
      change_inline = plt.goreOrangeBright,
      delete = plt.lacerationRedCore,
      delete_inline = plt.lacerationRedBright,
      text = plt.bruisePurpleCore,
    },
    vcs = {
      added = plt.infectionGreenCore,
      changed = plt.goreOrangeCore,
      removed = plt.lacerationRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.bloodRedCore,
      green = plt.infectionGreenCore,
      yellow = plt.carnageYellowCore,
      blue = plt.bruisePurpleCore,
      magenta = plt.visceralPinkCore,
      cyan = plt.fleshToneCore,
      white = plt.boneWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.arterialSplashBright):brighten(0.15):to_hex(),
      green_bright = color(plt.infectionGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.carnageYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.bruisePurpleBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.visceralPinkBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.fleshToneBright):brighten(0.1):to_hex(),
      white_bright = plt.boneWhiteBright,
      indexed1 = plt.bloodRedCore,
      indexed2 = plt.bruisePurpleCore,
    },
  }
end

return {
  name = "Punk – Splatterpunk",
  author = "PrismPunk.nvim",
  description = "Extreme violence — arterial splash, blood red, visceral pink, brutal gore, body horror.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shockGray,
    base04 = palette.shockGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.bloodRedCore,
    base09 = palette.goreOrangeCore,
    base0A = palette.carnageYellowCore,
    base0B = palette.infectionGreenCore,
    base0C = palette.fleshToneCore,
    base0D = palette.bruisePurpleCore,
    base0E = palette.visceralPinkCore,
    base0F = palette.arterialSplashCore,
  },
  palette = palette,
  get = M.get,
}
