local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0C0E12",
  bg_darker = "#11141A",
  bg_dark = "#171B22",
  bg_mid = "#1D222A",
  bg_light = "#232932",
  bg_lighter = "#29303A",
  bg_lightest = "#2F3742",
  fg_lightest = "#EDF2F7",
  fg_light = "#D4DBE6",
  fg_mid = "#B0BBC8",
  fg_dark = "#8A96A8",
  bg_alt1 = "#14171E",
  bg_alt2 = "#0E1014",
  bg_alt3 = "#1A1E26",
  bg_alt4 = "#0F1216",
  techBlueCore = "#0284C7",
  techBlueBright = "#38BDF8",
  dataGreenCore = "#059669",
  dataGreenBright = "#34D399",
  quantumVioletCore = "#7C3AED",
  quantumVioletBright = "#A78BFA",
  plasmaOrangeCore = "#D97706",
  plasmaOrangeBright = "#FBBF24",
  neonCyanCore = "#0891B2",
  neonCyanBright = "#22D3EE",
  circuitGreenCore = "#16A34A",
  circuitGreenBright = "#4ADE80",
  binaryWhiteCore = "#E2E8F0",
  binaryWhiteBright = "#FFFFFF",
  laserRedCore = "#DC2626",
  laserRedBright = "#F87171",
  hologramPinkCore = "#DB2777",
  hologramPinkBright = "#F472B6",
  networkBlueCore = "#2563EB",
  networkBlueBright = "#60A5FA",
  streamPurpleCore = "#9333EA",
  streamPurpleBright = "#C084FC",
  signalYellowCore = "#CA8A04",
  signalYellowBright = "#FDE047",
  metalGray = "#64748B",
  metalGrayLight = "#94A3B8",
  successGreen = "#10B981",
  warningAmber = "#F59E0B",
  infoBlue = "#0EA5E9",
  errorRed = "#EF4444",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.techBlueCore,
      insert = plt.dataGreenCore,
      visual = plt.quantumVioletCore,
      replace = plt.laserRedCore,
      command = plt.neonCyanCore,
    },
    accent = {
      accent1 = plt.techBlueCore,
      accent2 = plt.quantumVioletCore,
      accent3 = plt.dataGreenCore,
      accent4 = plt.neonCyanCore,
      accent5 = plt.plasmaOrangeCore,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.techBlueBright,
      rainbow2 = plt.quantumVioletBright,
      rainbow3 = plt.neonCyanBright,
      rainbow4 = plt.dataGreenBright,
      rainbow5 = plt.plasmaOrangeBright,
      rainbow6 = plt.hologramPinkBright,
      rainbow7 = plt.networkBlueBright,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.signalYellowCore,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.metalGray,
      header1 = plt.techBlueBright,
      header2 = plt.signalYellowBright,
      special = plt.neonCyanCore,
      nontext = plt.bg_lightest,
      whitespace = plt.metalGrayLight,
      win_separator = plt.metalGray,
      indent = plt.bg_lighter,
      indent_scope = plt.techBlueCore,
      picker = plt.streamPurpleCore,
      yank = plt.signalYellowBright,
      mark = plt.plasmaOrangeBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.metalGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.metalGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.metalGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.techBlueBright,
        indicator = plt.techBlueCore,
      },
    },
    syn = {
      attribute = plt.signalYellowCore,
      boolean = plt.neonCyanCore,
      comment = plt.metalGray,
      constant = plt.binaryWhiteCore,
      deprecated = plt.metalGray,
      func = plt.dataGreenCore,
      identifier = plt.fg_lightest,
      keyword = plt.techBlueCore,
      method = plt.dataGreenBright,
      number = plt.binaryWhiteCore,
      operator = plt.quantumVioletCore,
      parameter = plt.fg_mid,
      preproc = plt.networkBlueCore,
      punct = plt.fg_dark,
      regex = plt.streamPurpleCore,
      special = plt.neonCyanCore,
      special2 = plt.hologramPinkCore,
      special3 = plt.streamPurpleCore,
      statement = plt.techBlueCore,
      string = plt.dataGreenCore,
      symbol = plt.signalYellowCore,
      type = plt.neonCyanCore,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.neonCyanCore,
      virtual_text_error = plt.errorRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.neonCyanCore,
    },
    diff = {
      add = plt.circuitGreenCore,
      add_inline = plt.circuitGreenBright,
      change = plt.plasmaOrangeCore,
      change_inline = plt.plasmaOrangeBright,
      delete = plt.laserRedCore,
      delete_inline = plt.laserRedBright,
      text = plt.neonCyanCore,
    },
    vcs = {
      added = plt.circuitGreenCore,
      changed = plt.plasmaOrangeCore,
      removed = plt.laserRedCore,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.laserRedCore,
      green = plt.dataGreenCore,
      yellow = plt.signalYellowCore,
      blue = plt.techBlueCore,
      magenta = plt.quantumVioletCore,
      cyan = plt.neonCyanCore,
      white = plt.binaryWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.laserRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.dataGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.signalYellowBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.techBlueBright):brighten(0.15):to_hex(),
      magenta_bright = color(plt.quantumVioletBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.neonCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.binaryWhiteBright,
      indexed1 = plt.techBlueCore,
      indexed2 = plt.quantumVioletCore,
    },
  }
end

return {
  name = "Punk – Techpunk",
  author = "PrismPunk.nvim",
  description = "High-tech innovation — tech blue, quantum violet, data green, digital circuits.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.metalGray,
    base04 = palette.metalGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.laserRedCore,
    base09 = palette.plasmaOrangeCore,
    base0A = palette.signalYellowCore,
    base0B = palette.dataGreenCore,
    base0C = palette.neonCyanCore,
    base0D = palette.techBlueCore,
    base0E = palette.quantumVioletCore,
    base0F = palette.streamPurpleCore,
  },
  palette = palette,
  get = M.get,
}
