local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#060608",
  bg_darker = "#0B0B0F",
  bg_dark = "#121218",
  bg_mid = "#1A1A23",
  bg_light = "#3A3F4C",
  bg_lighter = "#565C64",
  bg_lightest = "#6A7178",
  fg_lightest = "#E8ECF0",
  fg_light = "#C8CCD4",
  fg_mid = "#ABB2BF",
  fg_dark = "#6A7178",
  bg_alt1 = "#0F1015",
  bg_alt2 = "#070809",
  bg_alt3 = "#14151D",
  bg_alt4 = "#080A0D",
  butlerSuit = "#4B4B4B",
  wayneTie = "#800020",
  alfredGray = "#708090",
  classicGray = "#696969",
  servantBlack = "#2C2C2C",
  teaTime = "#D4A574",
  britishTan = "#C19A6B",
  manorWood = "#8B7355",
  polishedSilver = "#C0C0C0",
  vintageBrass = "#B5A642",
  medicKit = "#E63946",
  firstAid = "#DC3545",
  medicalWhite = "#F8F9FA",
  bandageBeige = "#D4C5B9",
  royalBlue = "#4169E1",
  dignityBlue = "#5B7C99",
  britishBlue = "#6495ED",
  butlerTeal = "#5F9EA0",
  wisdomGold = "#DAA520",
  loyaltyAmber = "#FFBF00",
  serviceGreen = "#8FBC8F",
  devotionGray = "#A9A9A9",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.butlerSuit,
      insert = plt.royalBlue,
      visual = plt.wayneTie,
      replace = plt.medicKit,
      command = plt.wisdomGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.wisdomGold,
      bg_visual = plt.wayneTie,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.wayneTie,
      header2 = plt.wisdomGold,
      special = plt.butlerTeal,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.butlerSuit,
      indent = plt.bg_lighter,
      indent_scope = plt.butlerSuit,
      picker = plt.medicKit,
      yank = plt.wisdomGold,
      mark = plt.butlerTeal,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.wayneTie,
        bg_alternate = plt.bg_darkest,
        indicator = plt.wisdomGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.butlerSuit,
      accent2 = plt.wayneTie,
      accent3 = plt.wisdomGold,
      accent4 = plt.royalBlue,
      accent5 = plt.medicKit,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.butlerSuit,
      rainbow2 = plt.wayneTie,
      rainbow3 = plt.wisdomGold,
      rainbow4 = plt.royalBlue,
      rainbow5 = plt.teaTime,
      rainbow6 = plt.serviceGreen,
      rainbow7 = plt.butlerTeal,
    },

    syn = {
      attribute = plt.wisdomGold,
      boolean = plt.wayneTie,
      comment = plt.fg_dark,
      constant = plt.loyaltyAmber,
      deprecated = plt.fg_mid,
      func = plt.royalBlue,
      identifier = plt.fg_lightest,
      keyword = plt.butlerSuit,
      method = plt.butlerTeal,
      number = plt.vintageBrass,
      operator = plt.butlerTeal,
      parameter = plt.fg_mid,
      preproc = plt.dignityBlue,
      punct = plt.fg_mid,
      regex = plt.wisdomGold,
      statement = plt.butlerSuit,
      string = plt.teaTime,
      symbol = plt.butlerTeal,
      type = plt.wisdomGold,
      variable = plt.fg_lightest,
      special = plt.polishedSilver,
      special2 = plt.wayneTie,
      special3 = plt.royalBlue,
    },

    vcs = {
      added = plt.serviceGreen,
      removed = plt.medicKit,
      changed = plt.loyaltyAmber,
    },

    diff = {
      add = plt.serviceGreen,
      change = plt.loyaltyAmber,
      delete = plt.medicKit,
      text = plt.royalBlue,
    },

    diag = {
      ok = plt.serviceGreen,
      error = plt.medicKit,
      warning = plt.loyaltyAmber,
      info = plt.royalBlue,
      hint = plt.butlerTeal,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.medicKit,
      green = plt.serviceGreen,
      yellow = plt.wisdomGold,
      blue = plt.royalBlue,
      magenta = plt.wayneTie,
      cyan = plt.butlerTeal,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.medicKit):brighten(0.2):to_hex(),
      green_bright = color(plt.serviceGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.wisdomGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.royalBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.wayneTie):brighten(0.2):to_hex(),
      cyan_bright = color(plt.butlerTeal):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.wisdomGold,
      indexed2 = plt.wayneTie,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.medicKit,
      ["@comment.warning"] = plt.loyaltyAmber,
      ["@comment.todo"] = plt.wisdomGold,
      ["@comment.note"] = plt.butlerTeal,

      ["@constant"] = plt.loyaltyAmber,
      ["@constant.builtin"] = plt.loyaltyAmber,
      ["@constant.macro"] = plt.wisdomGold,

      ["@string"] = plt.teaTime,
      ["@string.documentation"] = plt.teaTime,
      ["@string.regex"] = plt.wisdomGold,
      ["@string.escape"] = plt.wayneTie,
      ["@string.special"] = plt.butlerTeal,
      ["@string.special.symbol"] = plt.butlerTeal,
      ["@string.special.url"] = plt.royalBlue,
      ["@string.special.path"] = plt.butlerTeal,

      ["@character"] = plt.teaTime,
      ["@character.special"] = plt.wayneTie,

      ["@number"] = plt.vintageBrass,
      ["@number.float"] = plt.vintageBrass,

      ["@boolean"] = plt.wayneTie,

      ["@function"] = plt.royalBlue,
      ["@function.builtin"] = plt.royalBlue,
      ["@function.call"] = plt.royalBlue,
      ["@function.macro"] = plt.dignityBlue,
      ["@function.method"] = plt.butlerTeal,
      ["@function.method.call"] = plt.butlerTeal,

      ["@constructor"] = plt.wisdomGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.butlerSuit,
      ["@keyword.coroutine"] = plt.alfredGray,
      ["@keyword.function"] = plt.butlerSuit,
      ["@keyword.operator"] = plt.butlerTeal,
      ["@keyword.return"] = plt.butlerSuit,
      ["@keyword.import"] = plt.royalBlue,
      ["@keyword.storage"] = plt.butlerSuit,
      ["@keyword.repeat"] = plt.butlerSuit,
      ["@keyword.conditional"] = plt.butlerSuit,
      ["@keyword.exception"] = plt.medicKit,
      ["@keyword.directive"] = plt.dignityBlue,
      ["@keyword.directive.define"] = plt.dignityBlue,

      ["@conditional"] = plt.butlerSuit,
      ["@conditional.ternary"] = plt.butlerSuit,

      ["@repeat"] = plt.butlerSuit,

      ["@label"] = plt.alfredGray,

      ["@operator"] = plt.butlerTeal,

      ["@exception"] = plt.medicKit,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.alfredGray,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.wisdomGold,
      ["@type.builtin"] = plt.wisdomGold,
      ["@type.definition"] = plt.wisdomGold,
      ["@type.qualifier"] = plt.butlerSuit,

      ["@attribute"] = plt.wisdomGold,
      ["@attribute.builtin"] = plt.wisdomGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.wisdomGold,
      ["@module.builtin"] = plt.wisdomGold,

      ["@namespace"] = plt.wisdomGold,
      ["@namespace.builtin"] = plt.wisdomGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.butlerTeal,

      ["@tag"] = plt.butlerTeal,
      ["@tag.attribute"] = plt.wisdomGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.butlerTeal,

      ["@markup.strong"] = { fg = plt.wayneTie, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.butlerSuit,
      ["@markup.heading.1"] = plt.wayneTie,
      ["@markup.heading.2"] = plt.wisdomGold,
      ["@markup.heading.3"] = plt.royalBlue,
      ["@markup.heading.4"] = plt.butlerTeal,
      ["@markup.heading.5"] = plt.teaTime,
      ["@markup.heading.6"] = plt.serviceGreen,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.royalBlue,
      ["@markup.link"] = plt.royalBlue,
      ["@markup.link.label"] = plt.butlerTeal,
      ["@markup.link.url"] = plt.royalBlue,
      ["@markup.raw"] = plt.teaTime,
      ["@markup.raw.block"] = plt.teaTime,
      ["@markup.list"] = plt.butlerTeal,
      ["@markup.list.checked"] = plt.serviceGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.serviceGreen,
      ["@diff.minus"] = plt.medicKit,
      ["@diff.delta"] = plt.loyaltyAmber,

      ["@none"] = "none",
      ["@conceal"] = plt.dignityBlue,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.wisdomGold,
      ["@constructor.javascript"] = plt.wisdomGold,
      ["@constructor.typescript"] = plt.wisdomGold,
      ["@namespace.rust"] = plt.wisdomGold,
      ["@type.qualifier.rust"] = plt.butlerSuit,
      ["@constant.macro.c"] = plt.wisdomGold,
      ["@constant.macro.cpp"] = plt.wisdomGold,
      ["@namespace.go"] = plt.wisdomGold,
      ["@property.css"] = plt.teaTime,
      ["@type.css"] = plt.butlerTeal,
      ["@label.json"] = plt.wisdomGold,
      ["@field.yaml"] = plt.teaTime,
      ["@property.toml"] = plt.teaTime,
      ["@function.builtin.bash"] = plt.royalBlue,
      ["@string.regexp"] = plt.wisdomGold,
      ["@character.special.regex"] = plt.wayneTie,
    },

    lsp = {
      ["@lsp.type.class"] = plt.wisdomGold,
      ["@lsp.type.interface"] = plt.wisdomGold,
      ["@lsp.type.struct"] = plt.wisdomGold,
      ["@lsp.type.enum"] = plt.wisdomGold,
      ["@lsp.type.enumMember"] = plt.loyaltyAmber,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.wisdomGold,

      ["@lsp.type.macro"] = plt.wisdomGold,
      ["@lsp.type.decorator"] = plt.wisdomGold,

      ["@lsp.type.builtinType"] = plt.wisdomGold,
      ["@lsp.type.selfParameter"] = plt.alfredGray,
      ["@lsp.type.typeParameter"] = plt.wisdomGold,

      ["@lsp.type.array"] = plt.wisdomGold,
      ["@lsp.type.object"] = plt.wisdomGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.loyaltyAmber,
      ["@lsp.type.enumConstant"] = plt.loyaltyAmber,

      ["@lsp.type.event"] = plt.wisdomGold,
      ["@lsp.type.regexp"] = plt.wisdomGold,
      ["@lsp.type.unresolvedReference"] = plt.wisdomGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.loyaltyAmber,
      ["@lsp.mod.async"] = plt.butlerSuit,
      ["@lsp.mod.static"] = plt.alfredGray,
      ["@lsp.mod.abstract"] = plt.wisdomGold,
      ["@lsp.mod.defaultLibrary"] = plt.wisdomGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Bat-Family – Alfred Pennyworth",
  author = "PrismPunk.nvim",
  description = "Why do we fall, sir? So we can learn to pick ourselves up. "
    .. "The loyal butler with wisdom gold, Wayne manor elegance, tea time tan, and British dignity.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.medicKit,
    base09 = palette.teaTime,
    base0A = palette.wisdomGold,
    base0B = palette.serviceGreen,
    base0C = palette.butlerTeal,
    base0D = palette.royalBlue,
    base0E = palette.wayneTie,
    base0F = palette.butlerSuit,
  },

  palette = palette,
  get = M.get,
}
