local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#000000",
  bg_darker = "#050508",
  bg_dark = "#0A0A0F",
  bg_mid = "#0F0F14",
  bg_light = "#14141A",
  bg_lighter = "#1A1A20",
  bg_lightest = "#202026",
  fg_lightest = "#E8F0FF",
  fg_light = "#C8D8F0",
  fg_mid = "#A8C0E0",
  fg_dark = "#88A8D0",
  bg_alt1 = "#030306",
  bg_alt2 = "#010102",
  bg_alt3 = "#0C0C11",
  bg_alt4 = "#020204",
  quantumBlueCore = "#00D9FF",
  quantumBlue = "#00D9FF",
  quantumBlueBright = "#33E6FF",
  quantumBlueDeep = "#00B3D9",
  neuralPurple = "#9D4EDD",
  neuralPurpleBright = "#C77DFF",
  neuralPurpleCore = "#9D4EDD",
  neuralPurpleDeep = "#7B2CBF",
  voidCyan = "#00FFFF",
  voidCyanBright = "#5AFFFF",
  voidCyanCore = "#00FFFF",
  voidCyanDeep = "#00CCCC",
  cosmicGold = "#FFD700",
  cosmicGoldBright = "#FFE55C",
  cosmicGoldCore = "#FFD700",
  cosmicGoldDeep = "#D9B600",
  stellarWhite = "#E8F0FF",
  stellarWhiteBright = "#FFFFFF",
  stellarWhiteCore = "#E8F0FF",
  stellarWhiteDeep = "#C8D8F0",
  holographicTeal = "#00D4AA",
  holographicTealBright = "#1AE8C4",
  holographicTealCore = "#00D4AA",
  digitalGray = "#52576E",
  digitalGrayLight = "#6B7089",
  digitalGrayDark = "#3D4154",
  singularityWhite = "#F0F8FF",
  singularityWhiteCore = "#F0F8FF",
  singularityWhiteBright = "#FFFFFF",
  warpPurple = "#7209B7",
  warpPurpleBright = "#9D4EDD",
  warpPurpleCore = "#7209B7",
  antimatterRed = "#FF006E",
  antimatterRedBright = "#FF3388",
  antimatterRedCore = "#FF006E",
  nebulaViolet = "#8B5CF6",
  nebulaVioletCore = "#8B5CF6",
  currentGray = "#52576E",
  currentGrayLight = "#6B7089",
  photonGreen = "#00FF88",
  photonGreenCore = "#00FF88",
  photonGreenBright = "#33FFAA",
  absoluteZero = "#000000",
  successGreen = "#00FF88",
  errorRed = "#FF006E",
  warningAmber = "#FFD700",
  infoBlue = "#00D9FF",
  seaweedGreenCore = "#00FF88",
  anglerYellowCore = "#FFD700",
  anemoneRedCore = "#FF006E",
  coralPink = "#00D9FF",
  coralPinkBright = "#33E6FF",
  coralPinkCore = "#00D9FF",
  coralPinkDeep = "#00B3D9",
  pressureWhite = "#E8F0FF",
  pressureWhiteCore = "#E8F0FF",
  pressureWhiteBright = "#FFFFFF",
  depthBlack = "#000000",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.quantumBlueCore,
      insert = plt.voidCyanCore,
      visual = plt.neuralPurpleCore,
      replace = plt.antimatterRedCore,
      command = plt.cosmicGoldCore,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.cosmicGoldDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.currentGray,
      header1 = plt.quantumBlueBright,
      header2 = plt.voidCyanBright,
      special = plt.cosmicGold,
      nontext = plt.bg_lightest,
      whitespace = plt.bg_lightest,
      win_separator = plt.currentGray,
      indent = plt.bg_lighter,
      indent_scope = plt.quantumBlueCore,
      picker = plt.cosmicGold,
      yank = plt.stellarWhiteBright,
      mark = plt.neuralPurple,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_dark,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.quantumBlueBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.quantumBlueCore,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.currentGray,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.currentGrayLight,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.currentGray,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.quantumBlueCore,
      accent2 = plt.neuralPurpleCore,
      accent3 = plt.voidCyanCore,
      accent4 = plt.cosmicGoldCore,
      accent5 = plt.stellarWhiteCore,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.quantumBlueBright,
      rainbow2 = plt.voidCyanBright,
      rainbow3 = plt.neuralPurpleBright,
      rainbow4 = plt.cosmicGoldBright,
      rainbow5 = plt.holographicTealBright,
      rainbow6 = plt.stellarWhiteBright,
      rainbow7 = plt.warpPurpleBright,
    },

    syn = {
      attribute = plt.cosmicGold,
      boolean = plt.neuralPurple,
      comment = plt.digitalGray,
      constant = plt.singularityWhite,
      deprecated = plt.absoluteZero,
      func = plt.voidCyanCore,
      identifier = plt.fg_lightest,
      keyword = plt.quantumBlueCore,
      method = plt.voidCyanBright,
      number = plt.singularityWhite,
      operator = plt.stellarWhiteCore,
      parameter = plt.fg_mid,
      preproc = plt.cosmicGoldCore,
      punct = plt.fg_dark,
      regex = plt.nebulaViolet,
      statement = plt.quantumBlueCore,
      string = plt.voidCyanCore,
      symbol = plt.cosmicGold,
      type = plt.neuralPurpleCore,
      variable = plt.fg_lightest,
      special = plt.cosmicGold,
      special2 = plt.warpPurple,
      special3 = plt.holographicTeal,
    },

    vcs = {
      added = plt.photonGreenCore,
      removed = plt.antimatterRedCore,
      changed = plt.cosmicGoldCore,
    },

    diff = {
      add = plt.photonGreenCore,
      change = plt.cosmicGoldCore,
      delete = plt.antimatterRedCore,
      text = plt.cosmicGold,
    },

    diag = {
      ok = plt.successGreen,
      error = plt.errorRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      hint = plt.cosmicGold,
    },

    term = {
      black = plt.bg_darkest,
      red = plt.antimatterRedCore,
      green = plt.photonGreenCore,
      yellow = plt.cosmicGoldCore,
      blue = plt.quantumBlueCore,
      magenta = plt.neuralPurpleCore,
      cyan = plt.voidCyanCore,
      white = plt.singularityWhiteCore,
      black_bright = color(plt.bg_darker):brighten(0.5):to_hex(),
      red_bright = color(plt.antimatterRedBright):brighten(0.15):to_hex(),
      green_bright = color(plt.photonGreenBright):brighten(0.15):to_hex(),
      yellow_bright = color(plt.cosmicGoldBright):brighten(0.15):to_hex(),
      blue_bright = color(plt.quantumBlueBright):brighten(0.18):to_hex(),
      magenta_bright = color(plt.neuralPurpleBright):brighten(0.15):to_hex(),
      cyan_bright = color(plt.voidCyanBright):brighten(0.15):to_hex(),
      white_bright = plt.singularityWhiteBright,
      indexed1 = plt.quantumBlue,
      indexed2 = plt.cosmicGold,
    },

    treesitter = {
      ["@comment"] = plt.digitalGray,
      ["@comment.documentation"] = plt.digitalGrayLight,
      ["@comment.error"] = plt.errorRed,
      ["@comment.warning"] = plt.warningAmber,
      ["@comment.todo"] = plt.cosmicGoldBright,
      ["@comment.note"] = plt.cosmicGold,

      ["@constant"] = plt.singularityWhite,
      ["@constant.builtin"] = plt.singularityWhiteCore,
      ["@constant.macro"] = plt.cosmicGold,

      ["@string"] = plt.voidCyanCore,
      ["@string.documentation"] = plt.voidCyanCore,
      ["@string.regex"] = plt.nebulaViolet,
      ["@string.escape"] = plt.stellarWhiteBright,
      ["@string.special"] = plt.voidCyanBright,
      ["@string.special.symbol"] = plt.cosmicGold,
      ["@string.special.url"] = plt.neuralPurple,
      ["@string.special.path"] = plt.voidCyanCore,

      ["@character"] = plt.voidCyanCore,
      ["@character.special"] = plt.cosmicGold,

      ["@number"] = plt.singularityWhite,
      ["@number.float"] = plt.singularityWhiteCore,

      ["@boolean"] = plt.neuralPurple,

      ["@function"] = plt.voidCyanCore,
      ["@function.builtin"] = plt.voidCyanCore,
      ["@function.call"] = plt.voidCyanCore,
      ["@function.macro"] = plt.cosmicGoldCore,
      ["@function.method"] = plt.voidCyanBright,
      ["@function.method.call"] = plt.voidCyanBright,

      ["@constructor"] = plt.neuralPurpleCore,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.quantumBlueCore,
      ["@keyword.coroutine"] = plt.cosmicGoldCore,
      ["@keyword.function"] = plt.quantumBlueCore,
      ["@keyword.operator"] = plt.stellarWhiteCore,
      ["@keyword.return"] = plt.quantumBlueCore,
      ["@keyword.import"] = plt.cosmicGoldCore,
      ["@keyword.storage"] = plt.quantumBlueCore,
      ["@keyword.repeat"] = plt.quantumBlueCore,
      ["@keyword.conditional"] = plt.quantumBlueCore,
      ["@keyword.exception"] = plt.antimatterRedCore,
      ["@keyword.directive"] = plt.cosmicGoldCore,
      ["@keyword.directive.define"] = plt.cosmicGoldCore,

      ["@conditional"] = plt.quantumBlueCore,
      ["@conditional.ternary"] = plt.quantumBlueCore,

      ["@repeat"] = plt.quantumBlueCore,

      ["@label"] = plt.cosmicGold,

      ["@operator"] = plt.stellarWhiteCore,

      ["@exception"] = plt.antimatterRedCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.quantumBlueBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.neuralPurpleCore,
      ["@type.builtin"] = plt.neuralPurpleCore,
      ["@type.definition"] = plt.neuralPurpleCore,
      ["@type.qualifier"] = plt.quantumBlueCore,

      ["@attribute"] = plt.cosmicGold,
      ["@attribute.builtin"] = plt.cosmicGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.neuralPurpleCore,
      ["@module.builtin"] = plt.neuralPurpleCore,

      ["@namespace"] = plt.neuralPurpleCore,
      ["@namespace.builtin"] = plt.neuralPurpleCore,

      ["@punctuation.delimiter"] = plt.fg_dark,
      ["@punctuation.bracket"] = plt.fg_dark,
      ["@punctuation.special"] = plt.stellarWhiteCore,

      ["@tag"] = plt.quantumBlueCore,
      ["@tag.attribute"] = plt.cosmicGold,
      ["@tag.delimiter"] = plt.stellarWhiteCore,
      ["@tag.builtin"] = plt.quantumBlueCore,

      ["@markup.strong"] = { fg = plt.quantumBlueBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.digitalGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.cosmicGold, underline = true },
      ["@markup.heading"] = plt.quantumBlueBright,
      ["@markup.heading.1"] = plt.quantumBlueBright,
      ["@markup.heading.2"] = plt.voidCyanBright,
      ["@markup.heading.3"] = plt.neuralPurpleBright,
      ["@markup.heading.4"] = plt.cosmicGoldBright,
      ["@markup.heading.5"] = plt.holographicTealBright,
      ["@markup.heading.6"] = plt.stellarWhiteBright,
      ["@markup.quote"] = plt.digitalGray,
      ["@markup.math"] = plt.singularityWhite,
      ["@markup.link"] = plt.neuralPurple,
      ["@markup.link.label"] = plt.neuralPurpleBright,
      ["@markup.link.url"] = plt.neuralPurple,
      ["@markup.raw"] = plt.voidCyanCore,
      ["@markup.raw.block"] = plt.voidCyanCore,
      ["@markup.list"] = plt.quantumBlueCore,
      ["@markup.list.checked"] = plt.photonGreenCore,
      ["@markup.list.unchecked"] = plt.digitalGray,

      ["@diff.plus"] = plt.photonGreenCore,
      ["@diff.minus"] = plt.antimatterRedCore,
      ["@diff.delta"] = plt.cosmicGoldCore,

      ["@none"] = "none",
      ["@conceal"] = plt.bg_lightest,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.neuralPurpleCore,
      ["@constructor.javascript"] = plt.neuralPurpleCore,
      ["@constructor.typescript"] = plt.neuralPurpleCore,
      ["@namespace.rust"] = plt.neuralPurpleCore,
      ["@type.qualifier.rust"] = plt.quantumBlueCore,
      ["@constant.macro.c"] = plt.cosmicGold,
      ["@constant.macro.cpp"] = plt.cosmicGold,
      ["@namespace.go"] = plt.neuralPurpleCore,
      ["@property.css"] = plt.voidCyanBright,
      ["@type.css"] = plt.quantumBlueCore,
      ["@label.json"] = plt.cosmicGold,
      ["@field.yaml"] = plt.voidCyanBright,
      ["@property.toml"] = plt.voidCyanBright,
      ["@function.builtin.bash"] = plt.voidCyanCore,
      ["@string.regexp"] = plt.nebulaViolet,
      ["@character.special.regex"] = plt.cosmicGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.neuralPurpleCore,
      ["@lsp.type.interface"] = plt.neuralPurpleCore,
      ["@lsp.type.struct"] = plt.neuralPurpleCore,
      ["@lsp.type.enum"] = plt.neuralPurpleCore,
      ["@lsp.type.enumMember"] = plt.singularityWhiteCore,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.neuralPurpleCore,

      ["@lsp.type.macro"] = plt.cosmicGold,
      ["@lsp.type.decorator"] = plt.cosmicGold,

      ["@lsp.type.builtinType"] = plt.neuralPurpleCore,
      ["@lsp.type.selfParameter"] = plt.quantumBlueBright,
      ["@lsp.type.typeParameter"] = plt.neuralPurpleCore,

      ["@lsp.type.array"] = plt.neuralPurpleCore,
      ["@lsp.type.object"] = plt.neuralPurpleCore,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.singularityWhiteCore,
      ["@lsp.type.enumConstant"] = plt.singularityWhiteCore,

      ["@lsp.type.event"] = plt.neuralPurpleCore,
      ["@lsp.type.regexp"] = plt.nebulaViolet,
      ["@lsp.type.unresolvedReference"] = plt.neuralPurpleCore,

      ["@lsp.mod.deprecated"] = { fg = plt.absoluteZero, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.singularityWhiteCore,
      ["@lsp.mod.async"] = plt.quantumBlueCore,
      ["@lsp.mod.static"] = plt.quantumBlueBright,
      ["@lsp.mod.abstract"] = plt.neuralPurpleCore,
      ["@lsp.mod.defaultLibrary"] = plt.neuralPurpleCore,
      ["@lsp.mod.documentation"] = plt.digitalGrayLight,
    },
  }
end

return {
  name = "Punk – Batman 10000",
  author = "PrismPunk.nvim",
  description = "853rd century Dark Knight — quantum blue, neural purple, void cyan, cosmic gold, absolute darkness.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.digitalGray,
    base04 = palette.digitalGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.antimatterRedCore,
    base09 = palette.cosmicGoldCore,
    base0A = palette.cosmicGoldCore,
    base0B = palette.voidCyanCore,
    base0C = palette.quantumBlueCore,
    base0D = palette.quantumBlueCore,
    base0E = palette.neuralPurpleCore,
    base0F = palette.nebulaVioletCore,
  },

  palette = palette,
  get = M.get,
}
