local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050508",
  bg_darker = "#0A0A0E",
  bg_dark = "#0F0F14",
  bg_mid = "#16161D",
  bg_light = "#2D2D35",
  bg_lighter = "#44444D",
  bg_lightest = "#5A5A64",
  fg_lightest = "#F0F0F5",
  fg_light = "#D8D8E0",
  fg_mid = "#B0B0C0",
  fg_dark = "#808090",
  bg_alt1 = "#0D0D12",
  bg_alt2 = "#070709",
  bg_alt3 = "#12121A",
  bg_alt4 = "#08080B",
  neoGothamRed = "#FF0000",
  futureRed = "#FF1744",
  terrySuit = "#E63946",
  beyondRed = "#DC143C",
  crimsonGlow = "#C41E3A",
  jetBlack = "#0A0A0A",
  nanoSuit = "#1A1A1A",
  techBlack = "#0D0D0D",
  carbonFiber = "#2D2D2D",
  cyberBlue = "#00FFFF",
  neonCyan = "#00E5FF",
  hologramBlue = "#00CCFF",
  digitalTeal = "#00B8D4",
  techGold = "#FFD700",
  circuitGold = "#FFB300",
  wayneTechGold = "#FFA000",
  futureGreen = "#00FF41",
  matrixGreen = "#39FF14",
  codeGreen = "#00FF00",
  hovercarOrange = "#FF6B35",
  skylineViolet = "#9D4EDD",
  megacityPurple = "#7209B7",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.neoGothamRed,
      insert = plt.cyberBlue,
      visual = plt.futureRed,
      replace = plt.beyondRed,
      command = plt.techGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.techGold,
      bg_visual = plt.futureRed,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.neoGothamRed,
      header2 = plt.cyberBlue,
      special = plt.futureGreen,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.neoGothamRed,
      indent = plt.bg_lighter,
      indent_scope = plt.neoGothamRed,
      picker = plt.beyondRed,
      yank = plt.techGold,
      mark = plt.cyberBlue,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.neoGothamRed,
        bg_alternate = plt.bg_darkest,
        indicator = plt.cyberBlue,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.neoGothamRed,
      accent2 = plt.cyberBlue,
      accent3 = plt.techGold,
      accent4 = plt.futureGreen,
      accent5 = plt.beyondRed,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.neoGothamRed,
      rainbow2 = plt.cyberBlue,
      rainbow3 = plt.techGold,
      rainbow4 = plt.futureGreen,
      rainbow5 = plt.hovercarOrange,
      rainbow6 = plt.skylineViolet,
      rainbow7 = plt.megacityPurple,
    },

    syn = {
      attribute = plt.techGold,
      boolean = plt.neoGothamRed,
      comment = plt.fg_dark,
      constant = plt.circuitGold,
      deprecated = plt.fg_mid,
      func = plt.cyberBlue,
      identifier = plt.fg_lightest,
      keyword = plt.neoGothamRed,
      method = plt.digitalTeal,
      number = plt.wayneTechGold,
      operator = plt.cyberBlue,
      parameter = plt.fg_mid,
      preproc = plt.skylineViolet,
      punct = plt.fg_mid,
      regex = plt.techGold,
      statement = plt.neoGothamRed,
      string = plt.futureGreen,
      symbol = plt.cyberBlue,
      type = plt.techGold,
      variable = plt.fg_lightest,
      special = plt.neonCyan,
      special2 = plt.beyondRed,
      special3 = plt.matrixGreen,
    },

    vcs = {
      added = plt.futureGreen,
      removed = plt.beyondRed,
      changed = plt.hovercarOrange,
    },

    diff = {
      add = plt.futureGreen,
      change = plt.hovercarOrange,
      delete = plt.beyondRed,
      text = plt.cyberBlue,
    },

    diag = {
      ok = plt.futureGreen,
      error = plt.beyondRed,
      warning = plt.hovercarOrange,
      info = plt.hologramBlue,
      hint = plt.digitalTeal,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.neoGothamRed,
      green = plt.futureGreen,
      yellow = plt.techGold,
      blue = plt.cyberBlue,
      magenta = plt.megacityPurple,
      cyan = plt.neonCyan,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.neoGothamRed):brighten(0.2):to_hex(),
      green_bright = color(plt.futureGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.techGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.cyberBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.megacityPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.neonCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.techGold,
      indexed2 = plt.neoGothamRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.beyondRed,
      ["@comment.warning"] = plt.hovercarOrange,
      ["@comment.todo"] = plt.neoGothamRed,
      ["@comment.note"] = plt.cyberBlue,

      ["@constant"] = plt.circuitGold,
      ["@constant.builtin"] = plt.circuitGold,
      ["@constant.macro"] = plt.wayneTechGold,

      ["@string"] = plt.futureGreen,
      ["@string.documentation"] = plt.futureGreen,
      ["@string.regex"] = plt.techGold,
      ["@string.escape"] = plt.megacityPurple,
      ["@string.special"] = plt.cyberBlue,
      ["@string.special.symbol"] = plt.neonCyan,
      ["@string.special.url"] = plt.hologramBlue,
      ["@string.special.path"] = plt.digitalTeal,

      ["@character"] = plt.futureGreen,
      ["@character.special"] = plt.megacityPurple,

      ["@number"] = plt.wayneTechGold,
      ["@number.float"] = plt.wayneTechGold,

      ["@boolean"] = plt.neoGothamRed,

      ["@function"] = plt.cyberBlue,
      ["@function.builtin"] = plt.cyberBlue,
      ["@function.call"] = plt.cyberBlue,
      ["@function.macro"] = plt.skylineViolet,
      ["@function.method"] = plt.digitalTeal,
      ["@function.method.call"] = plt.digitalTeal,

      ["@constructor"] = plt.techGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.neoGothamRed,
      ["@keyword.coroutine"] = plt.terrySuit,
      ["@keyword.function"] = plt.neoGothamRed,
      ["@keyword.operator"] = plt.cyberBlue,
      ["@keyword.return"] = plt.neoGothamRed,
      ["@keyword.import"] = plt.cyberBlue,
      ["@keyword.storage"] = plt.neoGothamRed,
      ["@keyword.repeat"] = plt.neoGothamRed,
      ["@keyword.conditional"] = plt.neoGothamRed,
      ["@keyword.exception"] = plt.beyondRed,
      ["@keyword.directive"] = plt.skylineViolet,
      ["@keyword.directive.define"] = plt.skylineViolet,

      ["@conditional"] = plt.neoGothamRed,
      ["@conditional.ternary"] = plt.neoGothamRed,

      ["@repeat"] = plt.neoGothamRed,

      ["@label"] = plt.terrySuit,

      ["@operator"] = plt.cyberBlue,

      ["@exception"] = plt.beyondRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.terrySuit,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.techGold,
      ["@type.builtin"] = plt.techGold,
      ["@type.definition"] = plt.techGold,
      ["@type.qualifier"] = plt.neoGothamRed,

      ["@attribute"] = plt.techGold,
      ["@attribute.builtin"] = plt.techGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.techGold,
      ["@module.builtin"] = plt.techGold,

      ["@namespace"] = plt.techGold,
      ["@namespace.builtin"] = plt.techGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.cyberBlue,

      ["@tag"] = plt.cyberBlue,
      ["@tag.attribute"] = plt.techGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.cyberBlue,

      ["@markup.strong"] = { fg = plt.neoGothamRed, bold = true },
      ["@markup.italic"] = { fg = plt.futureGreen, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.neoGothamRed,
      ["@markup.heading.1"] = plt.neoGothamRed,
      ["@markup.heading.2"] = plt.cyberBlue,
      ["@markup.heading.3"] = plt.techGold,
      ["@markup.heading.4"] = plt.futureGreen,
      ["@markup.heading.5"] = plt.skylineViolet,
      ["@markup.heading.6"] = plt.megacityPurple,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.cyberBlue,
      ["@markup.link"] = plt.cyberBlue,
      ["@markup.link.label"] = plt.digitalTeal,
      ["@markup.link.url"] = plt.hologramBlue,
      ["@markup.raw"] = plt.futureGreen,
      ["@markup.raw.block"] = plt.futureGreen,
      ["@markup.list"] = plt.cyberBlue,
      ["@markup.list.checked"] = plt.futureGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.futureGreen,
      ["@diff.minus"] = plt.beyondRed,
      ["@diff.delta"] = plt.hovercarOrange,

      ["@none"] = "none",
      ["@conceal"] = plt.skylineViolet,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.techGold,
      ["@constructor.javascript"] = plt.techGold,
      ["@constructor.typescript"] = plt.techGold,
      ["@namespace.rust"] = plt.techGold,
      ["@type.qualifier.rust"] = plt.neoGothamRed,
      ["@constant.macro.c"] = plt.wayneTechGold,
      ["@constant.macro.cpp"] = plt.wayneTechGold,
      ["@namespace.go"] = plt.techGold,
      ["@property.css"] = plt.futureGreen,
      ["@type.css"] = plt.cyberBlue,
      ["@label.json"] = plt.techGold,
      ["@field.yaml"] = plt.futureGreen,
      ["@property.toml"] = plt.futureGreen,
      ["@function.builtin.bash"] = plt.cyberBlue,
      ["@string.regexp"] = plt.techGold,
      ["@character.special.regex"] = plt.megacityPurple,
    },

    lsp = {
      ["@lsp.type.class"] = plt.techGold,
      ["@lsp.type.interface"] = plt.techGold,
      ["@lsp.type.struct"] = plt.techGold,
      ["@lsp.type.enum"] = plt.techGold,
      ["@lsp.type.enumMember"] = plt.neoGothamRed,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.techGold,

      ["@lsp.type.macro"] = plt.wayneTechGold,
      ["@lsp.type.decorator"] = plt.techGold,

      ["@lsp.type.builtinType"] = plt.techGold,
      ["@lsp.type.selfParameter"] = plt.terrySuit,
      ["@lsp.type.typeParameter"] = plt.techGold,

      ["@lsp.type.array"] = plt.techGold,
      ["@lsp.type.object"] = plt.techGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.neoGothamRed,
      ["@lsp.type.enumConstant"] = plt.neoGothamRed,

      ["@lsp.type.event"] = plt.techGold,
      ["@lsp.type.regexp"] = plt.techGold,
      ["@lsp.type.unresolvedReference"] = plt.techGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.neoGothamRed,
      ["@lsp.mod.async"] = plt.neoGothamRed,
      ["@lsp.mod.static"] = plt.terrySuit,
      ["@lsp.mod.abstract"] = plt.techGold,
      ["@lsp.mod.defaultLibrary"] = plt.techGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Future – Batman Beyond",
  author = "PrismPunk.nvim",
  description = "Terry McGinnis in Neo-Gotham. Cyberpunk future red suit, "
    .. "neon cyan holograms, matrix green code, and Wayne-Tech gold circuits. Schway!",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.beyondRed,
    base09 = palette.hovercarOrange,
    base0A = palette.techGold,
    base0B = palette.futureGreen,
    base0C = palette.cyberBlue,
    base0D = palette.hologramBlue,
    base0E = palette.megacityPurple,
    base0F = palette.neoGothamRed,
  },

  palette = palette,
  get = M.get,
}
