local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#060710",
  bg_darker = "#0B0F18",
  bg_dark = "#141A24",
  bg_mid = "#1C212B",
  bg_light = "#3E4451",
  bg_lighter = "#565C64",
  bg_lightest = "#ABB2BF",

  fg_lightest = "#E0E5EE",
  fg_light = "#C5CBD3",
  fg_mid = "#A0A8B5",
  fg_dark = "#7F8691",

  bg_alt1 = "#0F1420",
  bg_alt2 = "#090D16",
  bg_alt3 = "#171D28",
  bg_alt4 = "#111620",

  batCape = "#0D0D0D",
  batSuit = "#1A1A1A",
  batEmblem = "#FFD700",
  batGloves = "#1F1F1F",
  batBoots = "#1F1F1F",
  batBelt = "#D4AF37",
  batHighlight = "#3A3F4C",
  dangerRed = "#E06C75",
  infoBlue = "#61AFEF",
  tealGlow = "#00DDAA",
  arkhamPurple = "#8B66CC",
  justiceGray = "#7F8C99",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.justiceGray,
      insert = plt.infoBlue,
      visual = plt.batEmblem,
      replace = plt.dangerRed,
      command = plt.batBelt,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.batHighlight,
      bg_visual = plt.tealGlow,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.batEmblem,
      header2 = plt.batBelt,
      special = plt.tealGlow,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.justiceGray,
      indent = plt.bg_lighter,
      indent_scope = plt.justiceGray,
      picker = plt.dangerRed,
      yank = plt.batEmblem,
      mark = plt.tealGlow,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.batEmblem,
        bg_alternate = plt.bg_darkest,
        indicator = plt.batBelt,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.batEmblem,
      accent2 = plt.justiceGray,
      accent3 = plt.tealGlow,
      accent4 = plt.dangerRed,
      accent5 = plt.batHighlight,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.batEmblem,
      rainbow2 = plt.justiceGray,
      rainbow3 = plt.dangerRed,
      rainbow4 = plt.tealGlow,
      rainbow5 = plt.batHighlight,
      rainbow6 = plt.infoBlue,
      rainbow7 = plt.batBelt,
    },

    syn = {
      attribute = plt.batBelt,
      boolean = plt.batEmblem,
      comment = plt.fg_dark,
      constant = plt.batEmblem,
      deprecated = plt.fg_mid,
      func = plt.infoBlue,
      identifier = plt.fg_lightest,
      keyword = plt.justiceGray,
      method = plt.tealGlow,
      number = plt.batBelt,
      operator = plt.tealGlow,
      parameter = plt.fg_mid,
      preproc = plt.infoBlue,
      punct = plt.fg_mid,
      regex = plt.batBelt,
      statement = plt.justiceGray,
      string = plt.fg_light,
      symbol = plt.tealGlow,
      type = plt.batBelt,
      variable = plt.fg_lightest,
      special = plt.batBelt,
      special2 = plt.dangerRed,
      special3 = plt.infoBlue,
    },

    vcs = {
      added = plt.tealGlow,
      removed = plt.dangerRed,
      changed = plt.batEmblem,
    },

    diff = {
      add = plt.tealGlow,
      change = plt.batEmblem,
      delete = plt.dangerRed,
      text = plt.infoBlue,
    },

    diag = {
      ok = plt.tealGlow,
      error = plt.dangerRed,
      warning = plt.batBelt,
      info = plt.infoBlue,
      hint = plt.tealGlow,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.dangerRed,
      green = plt.tealGlow,
      yellow = plt.batEmblem,
      blue = plt.infoBlue,
      magenta = plt.arkhamPurple,
      cyan = plt.tealGlow,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerRed):brighten(0.2):to_hex(),
      green_bright = color(plt.tealGlow):brighten(0.1):to_hex(),
      yellow_bright = color(plt.batEmblem):brighten(0.2):to_hex(),
      blue_bright = color(plt.infoBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.arkhamPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.tealGlow):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.batBelt,
      indexed2 = plt.dangerRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.batBelt,
      ["@comment.todo"] = plt.infoBlue,
      ["@comment.note"] = plt.tealGlow,

      ["@constant"] = plt.batEmblem,
      ["@constant.builtin"] = plt.batEmblem,
      ["@constant.macro"] = plt.batBelt,

      ["@string"] = plt.fg_light,
      ["@string.documentation"] = plt.fg_light,
      ["@string.regex"] = plt.batBelt,
      ["@string.escape"] = plt.arkhamPurple,
      ["@string.special"] = plt.tealGlow,
      ["@string.special.symbol"] = plt.tealGlow,
      ["@string.special.url"] = plt.infoBlue,
      ["@string.special.path"] = plt.tealGlow,

      ["@character"] = plt.fg_light,
      ["@character.special"] = plt.arkhamPurple,

      ["@number"] = plt.batBelt,
      ["@number.float"] = plt.batBelt,

      ["@boolean"] = plt.batEmblem,

      ["@function"] = plt.infoBlue,
      ["@function.builtin"] = plt.infoBlue,
      ["@function.call"] = plt.infoBlue,
      ["@function.macro"] = plt.tealGlow,
      ["@function.method"] = plt.tealGlow,
      ["@function.method.call"] = plt.tealGlow,

      ["@constructor"] = plt.batBelt,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.justiceGray,
      ["@keyword.coroutine"] = plt.tealGlow,
      ["@keyword.function"] = plt.justiceGray,
      ["@keyword.operator"] = plt.tealGlow,
      ["@keyword.return"] = plt.justiceGray,
      ["@keyword.import"] = plt.infoBlue,
      ["@keyword.storage"] = plt.justiceGray,
      ["@keyword.repeat"] = plt.justiceGray,
      ["@keyword.conditional"] = plt.justiceGray,
      ["@keyword.exception"] = plt.dangerRed,
      ["@keyword.directive"] = plt.infoBlue,
      ["@keyword.directive.define"] = plt.infoBlue,

      ["@conditional"] = plt.justiceGray,
      ["@conditional.ternary"] = plt.justiceGray,

      ["@repeat"] = plt.justiceGray,

      ["@label"] = plt.tealGlow,

      ["@operator"] = plt.tealGlow,

      ["@exception"] = plt.dangerRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.tealGlow,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.batBelt,
      ["@type.builtin"] = plt.batBelt,
      ["@type.definition"] = plt.batBelt,
      ["@type.qualifier"] = plt.justiceGray,

      ["@attribute"] = plt.batBelt,
      ["@attribute.builtin"] = plt.batBelt,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.batBelt,
      ["@module.builtin"] = plt.batBelt,

      ["@namespace"] = plt.batBelt,
      ["@namespace.builtin"] = plt.batBelt,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.tealGlow,

      ["@tag"] = plt.tealGlow,
      ["@tag.attribute"] = plt.batBelt,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.tealGlow,

      ["@markup.strong"] = { fg = plt.batEmblem, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.tealGlow, underline = true },
      ["@markup.heading"] = plt.batEmblem,
      ["@markup.heading.1"] = plt.batEmblem,
      ["@markup.heading.2"] = plt.batBelt,
      ["@markup.heading.3"] = plt.justiceGray,
      ["@markup.heading.4"] = plt.infoBlue,
      ["@markup.heading.5"] = plt.tealGlow,
      ["@markup.heading.6"] = plt.arkhamPurple,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.tealGlow,
      ["@markup.link"] = plt.infoBlue,
      ["@markup.link.label"] = plt.tealGlow,
      ["@markup.link.url"] = plt.infoBlue,
      ["@markup.raw"] = plt.fg_light,
      ["@markup.raw.block"] = plt.fg_light,
      ["@markup.list"] = plt.tealGlow,
      ["@markup.list.checked"] = plt.tealGlow,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.tealGlow,
      ["@diff.minus"] = plt.dangerRed,
      ["@diff.delta"] = plt.batEmblem,

      ["@none"] = "none",
      ["@conceal"] = plt.batHighlight,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.batBelt,
      ["@constructor.javascript"] = plt.batBelt,
      ["@constructor.typescript"] = plt.batBelt,
      ["@namespace.rust"] = plt.batBelt,
      ["@type.qualifier.rust"] = plt.justiceGray,
      ["@constant.macro.c"] = plt.batBelt,
      ["@constant.macro.cpp"] = plt.batBelt,
      ["@namespace.go"] = plt.batBelt,
      ["@property.css"] = plt.fg_light,
      ["@type.css"] = plt.tealGlow,
      ["@label.json"] = plt.batBelt,
      ["@field.yaml"] = plt.fg_light,
      ["@property.toml"] = plt.fg_light,
      ["@function.builtin.bash"] = plt.infoBlue,
      ["@string.regexp"] = plt.batBelt,
      ["@character.special.regex"] = plt.arkhamPurple,
    },

    lsp = {
      ["@lsp.type.class"] = plt.batBelt,
      ["@lsp.type.interface"] = plt.batBelt,
      ["@lsp.type.struct"] = plt.batBelt,
      ["@lsp.type.enum"] = plt.batBelt,
      ["@lsp.type.enumMember"] = plt.batEmblem,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.batBelt,

      ["@lsp.type.macro"] = plt.batBelt,
      ["@lsp.type.decorator"] = plt.batBelt,

      ["@lsp.type.builtinType"] = plt.batBelt,
      ["@lsp.type.selfParameter"] = plt.tealGlow,
      ["@lsp.type.typeParameter"] = plt.batBelt,

      ["@lsp.type.array"] = plt.batBelt,
      ["@lsp.type.object"] = plt.batBelt,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.batEmblem,
      ["@lsp.type.enumConstant"] = plt.batEmblem,

      ["@lsp.type.event"] = plt.batBelt,
      ["@lsp.type.regexp"] = plt.batBelt,
      ["@lsp.type.unresolvedReference"] = plt.batBelt,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.batEmblem,
      ["@lsp.mod.async"] = plt.justiceGray,
      ["@lsp.mod.static"] = plt.tealGlow,
      ["@lsp.mod.abstract"] = plt.batBelt,
      ["@lsp.mod.defaultLibrary"] = plt.batBelt,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Bat-Family – Batman Classic",
  author = "PrismPunk.nvim",
  description = "I am vengeance, I am the night, I am Batman! "
    .. "Classic dark knight with iconic gold emblem and justice-gray readability.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.dangerRed,
    base09 = palette.batBelt,
    base0A = palette.batEmblem,
    base0B = palette.tealGlow,
    base0C = palette.tealGlow,
    base0D = palette.infoBlue,
    base0E = palette.arkhamPurple,
    base0F = palette.batGloves,
  },

  palette = palette,
  get = M.get,
}
