local color = require("prismpunk.utils.color")

local palette = {
  void_black = "#0A0A0F",
  alley_black = "#0F0F16",
  orphan_shadow = "#171722",
  lethal_core = "#21212E",
  ghost_skin = "#4B4455",
  bruised_flesh = "#5D5570",
  silent_purple = "#7A6999",
  orphan_royal = "#9988CC",
  arterial_red = "#CC0033",
  fresh_blood = "#EE1144",
  dried_blood = "#AA2233",
  wound_glow = "#FF4466",
  ghost_white = "#E8E8FF",
  moonlit_blade = "#CCCCFF",
  silent_gaze = "#AAAAFF",
  batcloth_gray = "#2D2D44",
  midnight_cape = "#1A1A2E",
  stealth_indigo = "#3A3377",
  fresh_bruise = "#773399",
  old_bruise = "#554477",
  healing_bruise = "#665588",
  hidden_heart = "#FF6699",
  david_cain_red = "#880022",
  term_red = "#CC0033",
  term_green = "#00AA88",
  term_blue = "#6666FF",
  term_yellow = "#FFCC99",
  term_cyan = "#88CCCC",
  term_magenta = "#CC66CC",
  term_red_bright = "#FF3366",
  term_green_bright = "#55CCAA",
  term_yellow_bright = "#FFDDAA",
  term_blue_bright = "#9999FF",
  term_magenta_bright = "#EE88EE",
  term_cyan_bright = "#AADDDD",

  bg_darkest = "#0A0A0F",
  fg_lightest = "#E8E8FF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.ghost_white,
      insert = plt.silent_purple,
      visual = plt.arterial_red,
      replace = plt.fresh_blood,
      command = plt.moonlit_blade,
    },

    ui = {
      fg = plt.ghost_white,
      fg_dim = plt.orphan_royal,
      fg_dimmer = plt.silent_purple,
      fg_dark = plt.bruised_flesh,
      fg_reverse = plt.void_black,

      bg_m4 = plt.lethal_core,
      bg_m3 = plt.orphan_shadow,
      bg_m2 = plt.alley_black,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.alley_black,
      bg_p2 = plt.orphan_shadow,
      bg_gutter = opts.gutter and plt.orphan_shadow or "none",
      bg_cursorline = plt.orphan_shadow,
      bg_cursorline_alt = plt.alley_black,
      bg_search = plt.wound_glow,
      bg_visual = plt.arterial_red,
      bg_statusline = plt.orphan_shadow,

      border = plt.moonlit_blade,
      header1 = plt.ghost_white,
      header2 = plt.silent_purple,
      special = plt.hidden_heart,
      nontext = plt.alley_black,
      whitespace = plt.lethal_core,
      win_separator = plt.moonlit_blade,
      indent = plt.alley_black,
      indent_scope = plt.ghost_white,
      picker = plt.silent_gaze,
      yank = plt.wound_glow,
      mark = plt.fresh_blood,
      scrollbar = plt.orphan_shadow,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.ghost_white,
        bg_selected = plt.orphan_shadow,
        fg_inactive = plt.silent_purple,
        bg_inactive = plt.void_black,
        fg_alternate = plt.arterial_red,
        bg_alternate = plt.void_black,
        indicator = plt.fresh_blood,
      },

      pmenu = {
        fg = plt.ghost_white,
        fg_sel = "none",
        fg_border = plt.orphan_shadow,
        bg_border = plt.orphan_shadow,
        bg = plt.orphan_shadow,
        bg_sel = plt.alley_black,
        bg_sbar = plt.orphan_shadow,
        bg_thumb = plt.moonlit_blade,
      },

      float = {
        fg = plt.ghost_white,
        bg = plt.alley_black,
        fg_border = plt.orphan_shadow,
        bg_border = plt.alley_black,
      },
    },

    accent = {
      accent1 = plt.ghost_white,
      accent2 = plt.silent_purple,
      accent3 = plt.arterial_red,
      accent4 = plt.hidden_heart,
      accent5 = plt.moonlit_blade,
      invert = plt.orphan_shadow,
    },

    rainbow = {
      rainbow1 = plt.ghost_white,
      rainbow2 = plt.silent_purple,
      rainbow3 = plt.arterial_red,
      rainbow4 = plt.fresh_blood,
      rainbow5 = plt.wound_glow,
      rainbow6 = plt.moonlit_blade,
      rainbow7 = plt.hidden_heart,
    },

    syn = {
      attribute = plt.ghost_white,
      boolean = plt.arterial_red,
      comment = plt.silent_purple,
      constant = plt.moonlit_blade,
      deprecated = plt.lethal_core,
      func = plt.silent_gaze,
      identifier = plt.ghost_white,
      keyword = plt.ghost_white,
      method = plt.silent_gaze,
      number = plt.wound_glow,
      operator = plt.fresh_blood,
      parameter = plt.orphan_royal,
      preproc = plt.dried_blood,
      punct = plt.silent_purple,
      regex = plt.silent_gaze,
      statement = plt.ghost_white,
      string = plt.batcloth_gray,
      symbol = plt.ghost_white,
      type = plt.moonlit_blade,
      variable = plt.ghost_white,
      special = plt.silent_gaze,
      special2 = plt.arterial_red,
      special3 = plt.hidden_heart,
    },

    vcs = { added = plt.moonlit_blade, removed = plt.arterial_red, changed = plt.fresh_blood },
    diff = { add = plt.moonlit_blade, change = plt.silent_purple, delete = plt.arterial_red, text = plt.wound_glow },
    diag = {
      ok = plt.moonlit_blade,
      error = plt.arterial_red,
      warning = plt.fresh_blood,
      info = plt.silent_gaze,
      hint = plt.hidden_heart,
    },

    term = {
      black = plt.void_black,
      red = plt.term_red,
      green = plt.term_green,
      yellow = plt.term_yellow,
      blue = plt.term_blue,
      magenta = plt.term_magenta,
      cyan = plt.term_cyan,
      white = plt.ghost_white,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_red_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_yellow_bright,
      blue_bright = plt.term_blue_bright,
      magenta_bright = plt.term_magenta_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.ghost_white,
      indexed2 = plt.silent_purple,
    },

    treesitter = {
      ["@comment"] = plt.silent_purple,
      ["@comment.documentation"] = plt.orphan_royal,
      ["@comment.error"] = plt.arterial_red,
      ["@comment.warning"] = plt.fresh_blood,
      ["@comment.todo"] = plt.moonlit_blade,
      ["@comment.note"] = plt.silent_gaze,

      ["@constant"] = plt.moonlit_blade,
      ["@constant.builtin"] = plt.moonlit_blade,
      ["@constant.macro"] = plt.dried_blood,

      ["@string"] = plt.batcloth_gray,
      ["@string.documentation"] = plt.batcloth_gray,
      ["@string.regex"] = plt.silent_gaze,
      ["@string.escape"] = plt.wound_glow,
      ["@string.special"] = plt.arterial_red,
      ["@string.special.symbol"] = plt.ghost_white,
      ["@string.special.url"] = plt.hidden_heart,
      ["@string.special.path"] = plt.batcloth_gray,

      ["@character"] = plt.batcloth_gray,
      ["@character.special"] = plt.wound_glow,

      ["@number"] = plt.wound_glow,
      ["@number.float"] = plt.wound_glow,

      ["@boolean"] = plt.arterial_red,

      ["@function"] = plt.silent_gaze,
      ["@function.builtin"] = plt.silent_gaze,
      ["@function.call"] = plt.silent_gaze,
      ["@function.macro"] = plt.fresh_blood,
      ["@function.method"] = plt.silent_gaze,
      ["@function.method.call"] = plt.silent_gaze,

      ["@constructor"] = plt.ghost_white,

      ["@parameter"] = plt.orphan_royal,
      ["@parameter.builtin"] = plt.ghost_white,

      ["@keyword"] = plt.ghost_white,
      ["@keyword.coroutine"] = plt.arterial_red,
      ["@keyword.function"] = plt.ghost_white,
      ["@keyword.operator"] = plt.fresh_blood,
      ["@keyword.return"] = plt.ghost_white,
      ["@keyword.import"] = plt.silent_gaze,
      ["@keyword.storage"] = plt.ghost_white,
      ["@keyword.repeat"] = plt.ghost_white,
      ["@keyword.conditional"] = plt.ghost_white,
      ["@keyword.exception"] = plt.arterial_red,
      ["@keyword.directive"] = plt.moonlit_blade,
      ["@keyword.directive.define"] = plt.moonlit_blade,

      ["@conditional"] = plt.ghost_white,
      ["@conditional.ternary"] = plt.ghost_white,

      ["@repeat"] = plt.ghost_white,

      ["@label"] = plt.silent_gaze,

      ["@operator"] = plt.fresh_blood,

      ["@exception"] = plt.arterial_red,

      ["@variable"] = plt.ghost_white,
      ["@variable.builtin"] = plt.moonlit_blade,
      ["@variable.parameter"] = plt.orphan_royal,
      ["@variable.member"] = plt.ghost_white,

      ["@type"] = plt.moonlit_blade,
      ["@type.builtin"] = plt.moonlit_blade,
      ["@type.definition"] = plt.moonlit_blade,
      ["@type.qualifier"] = plt.ghost_white,

      ["@attribute"] = plt.ghost_white,
      ["@attribute.builtin"] = plt.moonlit_blade,

      ["@property"] = plt.ghost_white,
      ["@field"] = plt.ghost_white,
      ["@module"] = plt.ghost_white,
      ["@module.builtin"] = plt.ghost_white,
      ["@namespace"] = plt.ghost_white,
      ["@namespace.builtin"] = plt.ghost_white,

      ["@punctuation.delimiter"] = plt.silent_purple,
      ["@punctuation.bracket"] = plt.silent_purple,
      ["@punctuation.special"] = plt.fresh_blood,

      ["@tag"] = plt.ghost_white,
      ["@tag.attribute"] = plt.moonlit_blade,
      ["@tag.delimiter"] = plt.silent_purple,
      ["@tag.builtin"] = plt.ghost_white,

      ["@markup.strong"] = { fg = plt.ghost_white, bold = true },
      ["@markup.italic"] = { fg = plt.ghost_white, italic = true },
      ["@markup.strikethrough"] = { fg = plt.lethal_core, strikethrough = true },
      ["@markup.underline"] = { fg = plt.hidden_heart, underline = true },
      ["@markup.heading"] = plt.ghost_white,
      ["@markup.heading.1"] = plt.ghost_white,
      ["@markup.heading.2"] = plt.silent_purple,
      ["@markup.heading.3"] = plt.arterial_red,
      ["@markup.heading.4"] = plt.wound_glow,
      ["@markup.heading.5"] = plt.moonlit_blade,
      ["@markup.heading.6"] = plt.hidden_heart,
      ["@markup.quote"] = plt.silent_purple,
      ["@markup.math"] = plt.silent_gaze,
      ["@markup.link"] = plt.hidden_heart,
      ["@markup.link.label"] = plt.moonlit_blade,
      ["@markup.link.url"] = plt.hidden_heart,
      ["@markup.raw"] = plt.batcloth_gray,
      ["@markup.raw.block"] = plt.batcloth_gray,
      ["@markup.list"] = plt.ghost_white,
      ["@markup.list.checked"] = plt.moonlit_blade,
      ["@markup.list.unchecked"] = plt.silent_purple,

      ["@diff.plus"] = plt.moonlit_blade,
      ["@diff.minus"] = plt.arterial_red,
      ["@diff.delta"] = plt.silent_purple,

      ["@none"] = "none",
      ["@conceal"] = plt.batcloth_gray,
      ["@spell"] = plt.ghost_white,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.ghost_white,
      ["@constructor.python"] = plt.ghost_white,
      ["@constructor.javascript"] = plt.ghost_white,
      ["@constructor.typescript"] = plt.ghost_white,
      ["@namespace.rust"] = plt.ghost_white,
      ["@type.qualifier.rust"] = plt.ghost_white,
      ["@constant.macro.c"] = plt.dried_blood,
      ["@constant.macro.cpp"] = plt.dried_blood,
      ["@namespace.go"] = plt.ghost_white,
      ["@property.css"] = plt.silent_gaze,
      ["@type.css"] = plt.ghost_white,
      ["@label.json"] = plt.ghost_white,
      ["@field.yaml"] = plt.orphan_royal,
      ["@property.toml"] = plt.orphan_royal,
      ["@function.builtin.bash"] = plt.silent_gaze,
      ["@string.regexp"] = plt.wound_glow,
      ["@character.special.regex"] = plt.fresh_blood,
    },

    lsp = {
      ["@lsp.type.class"] = plt.moonlit_blade,
      ["@lsp.type.interface"] = plt.moonlit_blade,
      ["@lsp.type.struct"] = plt.moonlit_blade,
      ["@lsp.type.enum"] = plt.moonlit_blade,
      ["@lsp.type.enumMember"] = plt.batcloth_gray,
      ["@lsp.type.property"] = plt.ghost_white,
      ["@lsp.type.namespace"] = plt.ghost_white,

      ["@lsp.type.macro"] = plt.moonlit_blade,
      ["@lsp.type.decorator"] = plt.ghost_white,

      ["@lsp.type.builtinType"] = plt.moonlit_blade,
      ["@lsp.type.selfParameter"] = plt.ghost_white,
      ["@lsp.type.typeParameter"] = plt.moonlit_blade,

      ["@lsp.type.array"] = plt.moonlit_blade,
      ["@lsp.type.object"] = plt.moonlit_blade,
      ["@lsp.type.key"] = plt.ghost_white,
      ["@lsp.type.null"] = plt.batcloth_gray,
      ["@lsp.type.enumConstant"] = plt.batcloth_gray,

      ["@lsp.type.event"] = plt.moonlit_blade,
      ["@lsp.type.regexp"] = plt.wound_glow,
      ["@lsp.type.unresolvedReference"] = plt.arterial_red,

      ["@lsp.mod.deprecated"] = { fg = plt.lethal_core, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.batcloth_gray,
      ["@lsp.mod.async"] = plt.ghost_white,
      ["@lsp.mod.static"] = plt.moonlit_blade,
      ["@lsp.mod.abstract"] = plt.moonlit_blade,
      ["@lsp.mod.defaultLibrary"] = plt.moonlit_blade,
      ["@lsp.mod.documentation"] = plt.orphan_royal,
    },
  }
end

return {
  name = "Black Bat – Orphan",
  author = "PrismPunk.nvim",
  description = "Cassandra Cain. Raised as a living weapon. Speaks with her body. "
    .. "Sees your soul before you move. Silent midnight, ghost-white eyes, "
    .. "and the red of violence she can never fully escape.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.alley_black,
    base02 = palette.orphan_shadow,
    base03 = palette.lethal_core,
    base04 = palette.silent_purple,
    base05 = palette.orphan_royal,
    base06 = palette.bruised_flesh,
    base07 = palette.ghost_white,
    base08 = palette.arterial_red,
    base09 = palette.moonlit_blade,
    base0A = palette.silent_gaze,
    base0B = palette.wound_glow,
    base0C = palette.fresh_blood,
    base0D = palette.hidden_heart,
    base0E = palette.dried_blood,
    base0F = palette.batcloth_gray,
  },

  palette = palette,
  get = M.get,
}
