local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050508",
  bg_darker = "#0A0A0E",
  bg_dark = "#101014",
  bg_mid = "#18181F",
  bg_light = "#2D2D35",
  bg_lighter = "#42424D",
  bg_lightest = "#57575F",
  fg_lightest = "#F5F5F5",
  fg_light = "#D4D4D8",
  fg_mid = "#A1A1AA",
  fg_dark = "#71717A",
  bg_alt1 = "#0E0E12",
  bg_alt2 = "#070709",
  bg_alt3 = "#13131A",
  bg_alt4 = "#08080B",
  catSuit = "#1A1A1A",
  leatherBlack = "#0D0D0D",
  midnightBlack = "#0A0A0A",
  prowlGray = "#A1A1AA",
  shadowPurr = "#71717A",
  clawSilver = "#C0C0C0",
  whipSteel = "#A9A9A9",
  jewelThief = "#E5E5E5",
  heistGray = "#D3D3D3",
  selinaGreen = "#98FB98",
  catEyes = "#7FFF00",
  emeraldHeist = "#50C878",
  envyGreen = "#8FBC8F",
  gothamsRooftop = "#4A5568",
  alleySmoke = "#6B7280",
  eastEndFog = "#9CA3AF",
  passionPurple = "#DA70D6",
  mysteryViolet = "#9370DB",
  seductionMagenta = "#BA55D3",
  batmanGray = "#708090",
  bruceWayne = "#4169E1",
  complicatedLove = "#B0C4DE",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.catSuit,
      insert = plt.catEyes,
      visual = plt.passionPurple,
      replace = plt.seductionMagenta,
      command = plt.clawSilver,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.emeraldHeist,
      bg_visual = plt.passionPurple,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.catEyes,
      header2 = plt.passionPurple,
      special = plt.selinaGreen,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.catSuit,
      indent = plt.bg_lighter,
      indent_scope = plt.prowlGray,
      picker = plt.seductionMagenta,
      yank = plt.emeraldHeist,
      mark = plt.catEyes,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.passionPurple,
        bg_alternate = plt.bg_darkest,
        indicator = plt.catEyes,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.catEyes,
      accent2 = plt.passionPurple,
      accent3 = plt.emeraldHeist,
      accent4 = plt.clawSilver,
      accent5 = plt.seductionMagenta,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.catEyes,
      rainbow2 = plt.passionPurple,
      rainbow3 = plt.selinaGreen,
      rainbow4 = plt.mysteryViolet,
      rainbow5 = plt.emeraldHeist,
      rainbow6 = plt.clawSilver,
      rainbow7 = plt.seductionMagenta,
    },

    syn = {
      attribute = plt.clawSilver,
      boolean = plt.catEyes,
      comment = plt.fg_dark,
      constant = plt.emeraldHeist,
      deprecated = plt.fg_mid,
      func = plt.selinaGreen,
      identifier = plt.fg_lightest,
      keyword = plt.heistGray,
      method = plt.catEyes,
      number = plt.whipSteel,
      operator = plt.catEyes,
      parameter = plt.fg_mid,
      preproc = plt.mysteryViolet,
      punct = plt.fg_mid,
      regex = plt.emeraldHeist,
      statement = plt.heistGray,
      string = plt.passionPurple,
      symbol = plt.catEyes,
      type = plt.clawSilver,
      variable = plt.fg_lightest,
      special = plt.seductionMagenta,
      special2 = plt.passionPurple,
      special3 = plt.selinaGreen,
    },

    vcs = {
      added = plt.selinaGreen,
      removed = plt.seductionMagenta,
      changed = plt.emeraldHeist,
    },

    diff = {
      add = plt.selinaGreen,
      change = plt.emeraldHeist,
      delete = plt.seductionMagenta,
      text = plt.catEyes,
    },

    diag = {
      ok = plt.selinaGreen,
      error = plt.seductionMagenta,
      warning = plt.emeraldHeist,
      info = plt.complicatedLove,
      hint = plt.catEyes,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.seductionMagenta,
      green = plt.selinaGreen,
      yellow = plt.emeraldHeist,
      blue = plt.bruceWayne,
      magenta = plt.passionPurple,
      cyan = plt.catEyes,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.seductionMagenta):brighten(0.2):to_hex(),
      green_bright = color(plt.selinaGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.emeraldHeist):brighten(0.2):to_hex(),
      blue_bright = color(plt.bruceWayne):brighten(0.3):to_hex(),
      magenta_bright = color(plt.passionPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.catEyes):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.emeraldHeist,
      indexed2 = plt.passionPurple,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.seductionMagenta,
      ["@comment.warning"] = plt.emeraldHeist,
      ["@comment.todo"] = plt.catEyes,
      ["@comment.note"] = plt.selinaGreen,

      ["@constant"] = plt.emeraldHeist,
      ["@constant.builtin"] = plt.emeraldHeist,
      ["@constant.macro"] = plt.clawSilver,

      ["@string"] = plt.passionPurple,
      ["@string.documentation"] = plt.passionPurple,
      ["@string.regex"] = plt.emeraldHeist,
      ["@string.escape"] = plt.seductionMagenta,
      ["@string.special"] = plt.catEyes,
      ["@string.special.symbol"] = plt.catEyes,
      ["@string.special.url"] = plt.selinaGreen,
      ["@string.special.path"] = plt.catEyes,

      ["@character"] = plt.passionPurple,
      ["@character.special"] = plt.seductionMagenta,

      ["@number"] = plt.whipSteel,
      ["@number.float"] = plt.whipSteel,

      ["@boolean"] = plt.catEyes,

      ["@function"] = plt.selinaGreen,
      ["@function.builtin"] = plt.selinaGreen,
      ["@function.call"] = plt.selinaGreen,
      ["@function.macro"] = plt.mysteryViolet,
      ["@function.method"] = plt.catEyes,
      ["@function.method.call"] = plt.catEyes,

      ["@constructor"] = plt.clawSilver,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.heistGray,
      ["@keyword.coroutine"] = plt.prowlGray,
      ["@keyword.function"] = plt.heistGray,
      ["@keyword.operator"] = plt.catEyes,
      ["@keyword.return"] = plt.heistGray,
      ["@keyword.import"] = plt.selinaGreen,
      ["@keyword.storage"] = plt.heistGray,
      ["@keyword.repeat"] = plt.heistGray,
      ["@keyword.conditional"] = plt.heistGray,
      ["@keyword.exception"] = plt.seductionMagenta,
      ["@keyword.directive"] = plt.mysteryViolet,
      ["@keyword.directive.define"] = plt.mysteryViolet,

      ["@conditional"] = plt.heistGray,
      ["@conditional.ternary"] = plt.heistGray,

      ["@repeat"] = plt.heistGray,

      ["@label"] = plt.prowlGray,

      ["@operator"] = plt.catEyes,

      ["@exception"] = plt.seductionMagenta,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.prowlGray,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.clawSilver,
      ["@type.builtin"] = plt.clawSilver,
      ["@type.definition"] = plt.clawSilver,
      ["@type.qualifier"] = plt.heistGray,

      ["@attribute"] = plt.clawSilver,
      ["@attribute.builtin"] = plt.clawSilver,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.clawSilver,
      ["@module.builtin"] = plt.clawSilver,

      ["@namespace"] = plt.clawSilver,
      ["@namespace.builtin"] = plt.clawSilver,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.catEyes,

      ["@tag"] = plt.catEyes,
      ["@tag.attribute"] = plt.clawSilver,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.catEyes,

      ["@markup.strong"] = { fg = plt.catEyes, bold = true },
      ["@markup.italic"] = { fg = plt.passionPurple, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.heistGray,
      ["@markup.heading.1"] = plt.catEyes,
      ["@markup.heading.2"] = plt.passionPurple,
      ["@markup.heading.3"] = plt.selinaGreen,
      ["@markup.heading.4"] = plt.mysteryViolet,
      ["@markup.heading.5"] = plt.emeraldHeist,
      ["@markup.heading.6"] = plt.clawSilver,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.selinaGreen,
      ["@markup.link"] = plt.selinaGreen,
      ["@markup.link.label"] = plt.catEyes,
      ["@markup.link.url"] = plt.selinaGreen,
      ["@markup.raw"] = plt.passionPurple,
      ["@markup.raw.block"] = plt.passionPurple,
      ["@markup.list"] = plt.catEyes,
      ["@markup.list.checked"] = plt.selinaGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.selinaGreen,
      ["@diff.minus"] = plt.seductionMagenta,
      ["@diff.delta"] = plt.emeraldHeist,

      ["@none"] = "none",
      ["@conceal"] = plt.mysteryViolet,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.clawSilver,
      ["@constructor.javascript"] = plt.clawSilver,
      ["@constructor.typescript"] = plt.clawSilver,
      ["@namespace.rust"] = plt.clawSilver,
      ["@type.qualifier.rust"] = plt.heistGray,
      ["@constant.macro.c"] = plt.clawSilver,
      ["@constant.macro.cpp"] = plt.clawSilver,
      ["@namespace.go"] = plt.clawSilver,
      ["@property.css"] = plt.passionPurple,
      ["@type.css"] = plt.catEyes,
      ["@label.json"] = plt.clawSilver,
      ["@field.yaml"] = plt.passionPurple,
      ["@property.toml"] = plt.passionPurple,
      ["@function.builtin.bash"] = plt.selinaGreen,
      ["@string.regexp"] = plt.emeraldHeist,
      ["@character.special.regex"] = plt.seductionMagenta,
    },

    lsp = {
      ["@lsp.type.class"] = plt.clawSilver,
      ["@lsp.type.interface"] = plt.clawSilver,
      ["@lsp.type.struct"] = plt.clawSilver,
      ["@lsp.type.enum"] = plt.clawSilver,
      ["@lsp.type.enumMember"] = plt.emeraldHeist,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.clawSilver,

      ["@lsp.type.macro"] = plt.clawSilver,
      ["@lsp.type.decorator"] = plt.clawSilver,

      ["@lsp.type.builtinType"] = plt.clawSilver,
      ["@lsp.type.selfParameter"] = plt.shadowPurr,
      ["@lsp.type.typeParameter"] = plt.clawSilver,

      ["@lsp.type.array"] = plt.clawSilver,
      ["@lsp.type.object"] = plt.clawSilver,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.emeraldHeist,
      ["@lsp.type.enumConstant"] = plt.emeraldHeist,

      ["@lsp.type.event"] = plt.clawSilver,
      ["@lsp.type.regexp"] = plt.emeraldHeist,
      ["@lsp.type.unresolvedReference"] = plt.emeraldHeist,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.emeraldHeist,
      ["@lsp.mod.async"] = plt.prowlGray,
      ["@lsp.mod.static"] = plt.shadowPurr,
      ["@lsp.mod.abstract"] = plt.clawSilver,
      ["@lsp.mod.defaultLibrary"] = plt.clawSilver,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Gotham – Catwoman",
  author = "PrismPunk.nvim",
  description = "I'm Catwoman. Hear me roar. Selina Kyle's sleek black catsuit, "
    .. "emerald heists, passionate purple mystery, and those hypnotic cat eyes. A complicated love with the Bat.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.seductionMagenta,
    base09 = palette.whipSteel,
    base0A = palette.emeraldHeist,
    base0B = palette.selinaGreen,
    base0C = palette.catEyes,
    base0D = palette.bruceWayne,
    base0E = palette.passionPurple,
    base0F = palette.mysteryViolet,
  },

  palette = palette,
  get = M.get,
}
