local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050508",
  bg_darker = "#0A0A0E",
  bg_dark = "#0F0F14",
  bg_mid = "#16161D",
  bg_light = "#2D2D35",
  bg_lighter = "#44444D",
  bg_lightest = "#5A5A64",
  fg_lightest = "#F0F0F5",
  fg_light = "#D8D8E0",
  fg_mid = "#B0B0C0",
  fg_dark = "#808090",
  bg_alt1 = "#0D0D12",
  bg_alt2 = "#070709",
  bg_alt3 = "#12121A",
  bg_alt4 = "#08080B",
  huntressViolet = "#8B00FF",
  deepPurple = "#6A0DAD",
  royalViolet = "#7B2CBF",
  darkViolet = "#5A189A",
  shadedPurple = "#4A148C",
  crossbowWhite = "#FFFFFF",
  boltSilver = "#E8E8F0",
  steelGray = "#C0C0D0",
  weaponMetal = "#A0A0B0",
  vendettaRed = "#FF0055",
  bloodCrimson = "#DC143C",
  rageRed = "#E63946",
  gothamGold = "#FFA500",
  amberGlow = "#FFB347",
  orangeFlare = "#FF8C00",
  nightCyan = "#00FFFF",
  huntCyan = "#00E5E5",
  trackerTeal = "#00CCCC",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.huntressViolet,
      insert = plt.nightCyan,
      visual = plt.deepPurple,
      replace = plt.vendettaRed,
      command = plt.gothamGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.gothamGold,
      bg_visual = plt.deepPurple,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.huntressViolet,
      header2 = plt.gothamGold,
      special = plt.nightCyan,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.huntressViolet,
      indent = plt.bg_lighter,
      indent_scope = plt.huntressViolet,
      picker = plt.vendettaRed,
      yank = plt.gothamGold,
      mark = plt.nightCyan,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.huntressViolet,
        bg_alternate = plt.bg_darkest,
        indicator = plt.gothamGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.huntressViolet,
      accent2 = plt.gothamGold,
      accent3 = plt.nightCyan,
      accent4 = plt.crossbowWhite,
      accent5 = plt.vendettaRed,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.huntressViolet,
      rainbow2 = plt.gothamGold,
      rainbow3 = plt.nightCyan,
      rainbow4 = plt.crossbowWhite,
      rainbow5 = plt.vendettaRed,
      rainbow6 = plt.royalViolet,
      rainbow7 = plt.amberGlow,
    },

    syn = {
      attribute = plt.gothamGold,
      boolean = plt.huntressViolet,
      comment = plt.fg_dark,
      constant = plt.gothamGold,
      deprecated = plt.fg_mid,
      func = plt.nightCyan,
      identifier = plt.fg_lightest,
      keyword = plt.huntressViolet,
      method = plt.trackerTeal,
      number = plt.steelGray,
      operator = plt.nightCyan,
      parameter = plt.fg_mid,
      preproc = plt.royalViolet,
      punct = plt.fg_mid,
      regex = plt.gothamGold,
      statement = plt.huntressViolet,
      string = plt.crossbowWhite,
      symbol = plt.nightCyan,
      type = plt.gothamGold,
      variable = plt.fg_lightest,
      special = plt.amberGlow,
      special2 = plt.vendettaRed,
      special3 = plt.nightCyan,
    },

    vcs = {
      added = plt.nightCyan,
      removed = plt.vendettaRed,
      changed = plt.gothamGold,
    },

    diff = {
      add = plt.nightCyan,
      change = plt.gothamGold,
      delete = plt.vendettaRed,
      text = plt.huntressViolet,
    },

    diag = {
      ok = plt.nightCyan,
      error = plt.vendettaRed,
      warning = plt.gothamGold,
      info = plt.royalViolet,
      hint = plt.trackerTeal,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.vendettaRed,
      green = plt.nightCyan,
      yellow = plt.gothamGold,
      blue = plt.huntressViolet,
      magenta = plt.royalViolet,
      cyan = plt.trackerTeal,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.vendettaRed):brighten(0.2):to_hex(),
      green_bright = color(plt.nightCyan):brighten(0.1):to_hex(),
      yellow_bright = color(plt.gothamGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.huntressViolet):brighten(0.3):to_hex(),
      magenta_bright = color(plt.royalViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.trackerTeal):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.gothamGold,
      indexed2 = plt.vendettaRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.vendettaRed,
      ["@comment.warning"] = plt.gothamGold,
      ["@comment.todo"] = plt.huntressViolet,
      ["@comment.note"] = plt.nightCyan,

      ["@constant"] = plt.gothamGold,
      ["@constant.builtin"] = plt.gothamGold,
      ["@constant.macro"] = plt.amberGlow,

      ["@string"] = plt.crossbowWhite,
      ["@string.documentation"] = plt.crossbowWhite,
      ["@string.regex"] = plt.gothamGold,
      ["@string.escape"] = plt.royalViolet,
      ["@string.special"] = plt.nightCyan,
      ["@string.special.symbol"] = plt.nightCyan,
      ["@string.special.url"] = plt.trackerTeal,
      ["@string.special.path"] = plt.trackerTeal,

      ["@character"] = plt.crossbowWhite,
      ["@character.special"] = plt.royalViolet,

      ["@number"] = plt.steelGray,
      ["@number.float"] = plt.steelGray,

      ["@boolean"] = plt.huntressViolet,

      ["@function"] = plt.nightCyan,
      ["@function.builtin"] = plt.nightCyan,
      ["@function.call"] = plt.nightCyan,
      ["@function.macro"] = plt.royalViolet,
      ["@function.method"] = plt.trackerTeal,
      ["@function.method.call"] = plt.trackerTeal,

      ["@constructor"] = plt.gothamGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.huntressViolet,
      ["@keyword.coroutine"] = plt.deepPurple,
      ["@keyword.function"] = plt.huntressViolet,
      ["@keyword.operator"] = plt.nightCyan,
      ["@keyword.return"] = plt.huntressViolet,
      ["@keyword.import"] = plt.nightCyan,
      ["@keyword.storage"] = plt.huntressViolet,
      ["@keyword.repeat"] = plt.huntressViolet,
      ["@keyword.conditional"] = plt.huntressViolet,
      ["@keyword.exception"] = plt.vendettaRed,
      ["@keyword.directive"] = plt.royalViolet,
      ["@keyword.directive.define"] = plt.royalViolet,

      ["@conditional"] = plt.huntressViolet,
      ["@conditional.ternary"] = plt.huntressViolet,

      ["@repeat"] = plt.huntressViolet,

      ["@label"] = plt.deepPurple,

      ["@operator"] = plt.nightCyan,

      ["@exception"] = plt.vendettaRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.deepPurple,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.gothamGold,
      ["@type.builtin"] = plt.gothamGold,
      ["@type.definition"] = plt.gothamGold,
      ["@type.qualifier"] = plt.huntressViolet,

      ["@attribute"] = plt.gothamGold,
      ["@attribute.builtin"] = plt.gothamGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.gothamGold,
      ["@module.builtin"] = plt.gothamGold,

      ["@namespace"] = plt.gothamGold,
      ["@namespace.builtin"] = plt.gothamGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.nightCyan,

      ["@tag"] = plt.nightCyan,
      ["@tag.attribute"] = plt.gothamGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.nightCyan,

      ["@markup.strong"] = { fg = plt.huntressViolet, bold = true },
      ["@markup.italic"] = { fg = plt.crossbowWhite, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.huntressViolet,
      ["@markup.heading.1"] = plt.huntressViolet,
      ["@markup.heading.2"] = plt.gothamGold,
      ["@markup.heading.3"] = plt.nightCyan,
      ["@markup.heading.4"] = plt.royalViolet,
      ["@markup.heading.5"] = plt.crossbowWhite,
      ["@markup.heading.6"] = plt.vendettaRed,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.nightCyan,
      ["@markup.link"] = plt.nightCyan,
      ["@markup.link.label"] = plt.trackerTeal,
      ["@markup.link.url"] = plt.nightCyan,
      ["@markup.raw"] = plt.crossbowWhite,
      ["@markup.raw.block"] = plt.crossbowWhite,
      ["@markup.list"] = plt.nightCyan,
      ["@markup.list.checked"] = plt.nightCyan,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.nightCyan,
      ["@diff.minus"] = plt.vendettaRed,
      ["@diff.delta"] = plt.gothamGold,

      ["@none"] = "none",
      ["@conceal"] = plt.royalViolet,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.gothamGold,
      ["@constructor.javascript"] = plt.gothamGold,
      ["@constructor.typescript"] = plt.gothamGold,
      ["@namespace.rust"] = plt.gothamGold,
      ["@type.qualifier.rust"] = plt.huntressViolet,
      ["@constant.macro.c"] = plt.amberGlow,
      ["@constant.macro.cpp"] = plt.amberGlow,
      ["@namespace.go"] = plt.gothamGold,
      ["@property.css"] = plt.crossbowWhite,
      ["@type.css"] = plt.nightCyan,
      ["@label.json"] = plt.gothamGold,
      ["@field.yaml"] = plt.crossbowWhite,
      ["@property.toml"] = plt.crossbowWhite,
      ["@function.builtin.bash"] = plt.nightCyan,
      ["@string.regexp"] = plt.gothamGold,
      ["@character.special.regex"] = plt.royalViolet,
    },

    lsp = {
      ["@lsp.type.class"] = plt.gothamGold,
      ["@lsp.type.interface"] = plt.gothamGold,
      ["@lsp.type.struct"] = plt.gothamGold,
      ["@lsp.type.enum"] = plt.gothamGold,
      ["@lsp.type.enumMember"] = plt.huntressViolet,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.gothamGold,

      ["@lsp.type.macro"] = plt.amberGlow,
      ["@lsp.type.decorator"] = plt.gothamGold,

      ["@lsp.type.builtinType"] = plt.gothamGold,
      ["@lsp.type.selfParameter"] = plt.deepPurple,
      ["@lsp.type.typeParameter"] = plt.gothamGold,

      ["@lsp.type.array"] = plt.gothamGold,
      ["@lsp.type.object"] = plt.gothamGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.huntressViolet,
      ["@lsp.type.enumConstant"] = plt.huntressViolet,

      ["@lsp.type.event"] = plt.gothamGold,
      ["@lsp.type.regexp"] = plt.gothamGold,
      ["@lsp.type.unresolvedReference"] = plt.gothamGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.huntressViolet,
      ["@lsp.mod.async"] = plt.huntressViolet,
      ["@lsp.mod.static"] = plt.deepPurple,
      ["@lsp.mod.abstract"] = plt.gothamGold,
      ["@lsp.mod.defaultLibrary"] = plt.gothamGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Gotham – Huntress",
  author = "PrismPunk.nvim",
  description = "Violet vengeance. Crossbow white bolts, electric cyan tracking, "
    .. "Gotham gold streets. The Huntress stalks the night.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.vendettaRed,
    base09 = palette.amberGlow,
    base0A = palette.gothamGold,
    base0B = palette.nightCyan,
    base0C = palette.trackerTeal,
    base0D = palette.huntressViolet,
    base0E = palette.royalViolet,
    base0F = palette.crossbowWhite,
  },

  palette = palette,
  get = M.get,
}
