local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#080808",
  bg_darker = "#0F0F0F",
  bg_dark = "#1A1A1A",
  bg_mid = "#242424",
  bg_light = "#3D3D3D",
  bg_lighter = "#565656",
  bg_lightest = "#6F6F6F",
  fg_lightest = "#F0F0F0",
  fg_light = "#D8D8D8",
  fg_mid = "#B0B0B0",
  fg_dark = "#808080",
  bg_alt1 = "#151515",
  bg_alt2 = "#0A0A0A",
  bg_alt3 = "#1D1D1D",
  bg_alt4 = "#0C0C0C",
  executiveSuit = "#2D2D2D",
  charcoalGray = "#36454F",
  businessGray = "#708090",
  professionalGray = "#778899",
  slateGray = "#6C7A89",
  wayneTechGold = "#FFD700",
  innovationGold = "#FFB300",
  patentGold = "#DAA520",
  prototypeAmber = "#FFBF00",
  blueprintBlue = "#4682B4",
  engineeringBlue = "#5B8DB8",
  designBlue = "#6495ED",
  schematicCyan = "#5F9EA0",
  ledGreen = "#32CD32",
  circuitGreen = "#00FF7F",
  powerGreen = "#00FA9A",
  warningOrange = "#FF8C00",
  alertRed = "#DC143C",
  statusViolet = "#9370DB",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.businessGray,
      insert = plt.blueprintBlue,
      visual = plt.charcoalGray,
      replace = plt.alertRed,
      command = plt.wayneTechGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.wayneTechGold,
      bg_visual = plt.charcoalGray,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.wayneTechGold,
      header2 = plt.blueprintBlue,
      special = plt.schematicCyan,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.businessGray,
      indent = plt.bg_lighter,
      indent_scope = plt.businessGray,
      picker = plt.alertRed,
      yank = plt.wayneTechGold,
      mark = plt.ledGreen,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.businessGray,
        bg_alternate = plt.bg_darkest,
        indicator = plt.wayneTechGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.businessGray,
      accent2 = plt.wayneTechGold,
      accent3 = plt.blueprintBlue,
      accent4 = plt.ledGreen,
      accent5 = plt.alertRed,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.businessGray,
      rainbow2 = plt.wayneTechGold,
      rainbow3 = plt.blueprintBlue,
      rainbow4 = plt.ledGreen,
      rainbow5 = plt.schematicCyan,
      rainbow6 = plt.statusViolet,
      rainbow7 = plt.warningOrange,
    },

    syn = {
      attribute = plt.wayneTechGold,
      boolean = plt.ledGreen,
      comment = plt.fg_dark,
      constant = plt.patentGold,
      deprecated = plt.fg_mid,
      func = plt.blueprintBlue,
      identifier = plt.fg_lightest,
      keyword = plt.businessGray,
      method = plt.schematicCyan,
      number = plt.innovationGold,
      operator = plt.schematicCyan,
      parameter = plt.fg_mid,
      preproc = plt.engineeringBlue,
      punct = plt.fg_mid,
      regex = plt.wayneTechGold,
      statement = plt.businessGray,
      string = plt.circuitGreen,
      symbol = plt.schematicCyan,
      type = plt.wayneTechGold,
      variable = plt.fg_lightest,
      special = plt.prototypeAmber,
      special2 = plt.alertRed,
      special3 = plt.blueprintBlue,
    },

    vcs = {
      added = plt.powerGreen,
      removed = plt.alertRed,
      changed = plt.warningOrange,
    },

    diff = {
      add = plt.powerGreen,
      change = plt.warningOrange,
      delete = plt.alertRed,
      text = plt.blueprintBlue,
    },

    diag = {
      ok = plt.ledGreen,
      error = plt.alertRed,
      warning = plt.warningOrange,
      info = plt.designBlue,
      hint = plt.schematicCyan,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.alertRed,
      green = plt.ledGreen,
      yellow = plt.wayneTechGold,
      blue = plt.blueprintBlue,
      magenta = plt.statusViolet,
      cyan = plt.schematicCyan,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.alertRed):brighten(0.2):to_hex(),
      green_bright = color(plt.ledGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.wayneTechGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.blueprintBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.statusViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.schematicCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.wayneTechGold,
      indexed2 = plt.alertRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.alertRed,
      ["@comment.warning"] = plt.warningOrange,
      ["@comment.todo"] = plt.wayneTechGold,
      ["@comment.note"] = plt.blueprintBlue,

      ["@constant"] = plt.patentGold,
      ["@constant.builtin"] = plt.patentGold,
      ["@constant.macro"] = plt.innovationGold,

      ["@string"] = plt.circuitGreen,
      ["@string.documentation"] = plt.circuitGreen,
      ["@string.regex"] = plt.wayneTechGold,
      ["@string.escape"] = plt.statusViolet,
      ["@string.special"] = plt.schematicCyan,
      ["@string.special.symbol"] = plt.schematicCyan,
      ["@string.special.url"] = plt.blueprintBlue,
      ["@string.special.path"] = plt.schematicCyan,

      ["@character"] = plt.circuitGreen,
      ["@character.special"] = plt.statusViolet,

      ["@number"] = plt.innovationGold,
      ["@number.float"] = plt.innovationGold,

      ["@boolean"] = plt.ledGreen,

      ["@function"] = plt.blueprintBlue,
      ["@function.builtin"] = plt.blueprintBlue,
      ["@function.call"] = plt.blueprintBlue,
      ["@function.macro"] = plt.engineeringBlue,
      ["@function.method"] = plt.schematicCyan,
      ["@function.method.call"] = plt.schematicCyan,

      ["@constructor"] = plt.wayneTechGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.businessGray,
      ["@keyword.coroutine"] = plt.professionalGray,
      ["@keyword.function"] = plt.businessGray,
      ["@keyword.operator"] = plt.schematicCyan,
      ["@keyword.return"] = plt.businessGray,
      ["@keyword.import"] = plt.blueprintBlue,
      ["@keyword.storage"] = plt.businessGray,
      ["@keyword.repeat"] = plt.businessGray,
      ["@keyword.conditional"] = plt.businessGray,
      ["@keyword.exception"] = plt.alertRed,
      ["@keyword.directive"] = plt.engineeringBlue,
      ["@keyword.directive.define"] = plt.engineeringBlue,

      ["@conditional"] = plt.businessGray,
      ["@conditional.ternary"] = plt.businessGray,

      ["@repeat"] = plt.businessGray,

      ["@label"] = plt.professionalGray,

      ["@operator"] = plt.schematicCyan,

      ["@exception"] = plt.alertRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.professionalGray,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.wayneTechGold,
      ["@type.builtin"] = plt.wayneTechGold,
      ["@type.definition"] = plt.wayneTechGold,
      ["@type.qualifier"] = plt.businessGray,

      ["@attribute"] = plt.wayneTechGold,
      ["@attribute.builtin"] = plt.wayneTechGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.wayneTechGold,
      ["@module.builtin"] = plt.wayneTechGold,

      ["@namespace"] = plt.wayneTechGold,
      ["@namespace.builtin"] = plt.wayneTechGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.schematicCyan,

      ["@tag"] = plt.schematicCyan,
      ["@tag.attribute"] = plt.wayneTechGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.schematicCyan,

      ["@markup.strong"] = { fg = plt.wayneTechGold, bold = true },
      ["@markup.italic"] = { fg = plt.circuitGreen, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.businessGray,
      ["@markup.heading.1"] = plt.wayneTechGold,
      ["@markup.heading.2"] = plt.blueprintBlue,
      ["@markup.heading.3"] = plt.ledGreen,
      ["@markup.heading.4"] = plt.schematicCyan,
      ["@markup.heading.5"] = plt.engineeringBlue,
      ["@markup.heading.6"] = plt.statusViolet,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.blueprintBlue,
      ["@markup.link"] = plt.blueprintBlue,
      ["@markup.link.label"] = plt.schematicCyan,
      ["@markup.link.url"] = plt.designBlue,
      ["@markup.raw"] = plt.circuitGreen,
      ["@markup.raw.block"] = plt.circuitGreen,
      ["@markup.list"] = plt.schematicCyan,
      ["@markup.list.checked"] = plt.ledGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.powerGreen,
      ["@diff.minus"] = plt.alertRed,
      ["@diff.delta"] = plt.warningOrange,

      ["@none"] = "none",
      ["@conceal"] = plt.engineeringBlue,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.wayneTechGold,
      ["@constructor.javascript"] = plt.wayneTechGold,
      ["@constructor.typescript"] = plt.wayneTechGold,
      ["@namespace.rust"] = plt.wayneTechGold,
      ["@type.qualifier.rust"] = plt.businessGray,
      ["@constant.macro.c"] = plt.innovationGold,
      ["@constant.macro.cpp"] = plt.innovationGold,
      ["@namespace.go"] = plt.wayneTechGold,
      ["@property.css"] = plt.circuitGreen,
      ["@type.css"] = plt.schematicCyan,
      ["@label.json"] = plt.wayneTechGold,
      ["@field.yaml"] = plt.circuitGreen,
      ["@property.toml"] = plt.circuitGreen,
      ["@function.builtin.bash"] = plt.blueprintBlue,
      ["@string.regexp"] = plt.wayneTechGold,
      ["@character.special.regex"] = plt.statusViolet,
    },

    lsp = {
      ["@lsp.type.class"] = plt.wayneTechGold,
      ["@lsp.type.interface"] = plt.wayneTechGold,
      ["@lsp.type.struct"] = plt.wayneTechGold,
      ["@lsp.type.enum"] = plt.wayneTechGold,
      ["@lsp.type.enumMember"] = plt.patentGold,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.wayneTechGold,

      ["@lsp.type.macro"] = plt.innovationGold,
      ["@lsp.type.decorator"] = plt.wayneTechGold,

      ["@lsp.type.builtinType"] = plt.wayneTechGold,
      ["@lsp.type.selfParameter"] = plt.professionalGray,
      ["@lsp.type.typeParameter"] = plt.wayneTechGold,

      ["@lsp.type.array"] = plt.wayneTechGold,
      ["@lsp.type.object"] = plt.wayneTechGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.patentGold,
      ["@lsp.type.enumConstant"] = plt.patentGold,

      ["@lsp.type.event"] = plt.wayneTechGold,
      ["@lsp.type.regexp"] = plt.wayneTechGold,
      ["@lsp.type.unresolvedReference"] = plt.wayneTechGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.patentGold,
      ["@lsp.mod.async"] = plt.businessGray,
      ["@lsp.mod.static"] = plt.professionalGray,
      ["@lsp.mod.abstract"] = plt.wayneTechGold,
      ["@lsp.mod.defaultLibrary"] = plt.wayneTechGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Wayne Tech – Lucius Fox",
  author = "PrismPunk.nvim",
  description = "Mr. Fox, CEO of Wayne Enterprises Applied Sciences. "
    .. "Executive gray suit, blueprint blue schematics, innovation gold patents, "
    .. "and LED green circuit boards. Professional engineering excellence.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.alertRed,
    base09 = palette.warningOrange,
    base0A = palette.wayneTechGold,
    base0B = palette.ledGreen,
    base0C = palette.schematicCyan,
    base0D = palette.blueprintBlue,
    base0E = palette.statusViolet,
    base0F = palette.businessGray,
  },

  palette = palette,
  get = M.get,
}
