local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050608",
  bg_darker = "#0A0B0F",
  bg_dark = "#111217",
  bg_mid = "#1A1A22",
  bg_light = "#3A3F4C",
  bg_lighter = "#565C64",
  bg_lightest = "#6A7178",
  fg_lightest = "#E8ECF0",
  fg_light = "#C8CCD4",
  fg_mid = "#ABB2BF",
  fg_dark = "#6A7178",
  bg_alt1 = "#0F1015",
  bg_alt2 = "#070809",
  bg_alt3 = "#14151D",
  bg_alt4 = "#080A0D",
  robinRed = "#FF0000",
  damianRed = "#DC143C",
  capeRed = "#C41E3A",
  assassinRed = "#B71C1C",
  bloodRed = "#8B0000",
  tunicGreen = "#00FF00",
  leagueGreen = "#32CD32",
  robinGreen = "#228B22",
  assassinGreen = "#006400",
  katanaSilver = "#C0C0C0",
  swordSteel = "#A9A9A9",
  bladeGray = "#808080",
  armorGold = "#FFD700",
  alGhulGold = "#DAA520",
  leagueOfShadows = "#2F4F4F",
  raAlGhul = "#556B2F",
  taliaGreen = "#6B8E23",
  sonOfBatman = "#1E90FF",
  bruceBlue = "#4169E1",
  wayneBlue = "#4682B4",
  superiorityPurple = "#9370DB",
  arroganceViolet = "#8B008B",
  heirOrange = "#FF8C00",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.robinRed,
      insert = plt.leagueGreen,
      visual = plt.damianRed,
      replace = plt.assassinRed,
      command = plt.armorGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.armorGold,
      bg_visual = plt.damianRed,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.robinRed,
      header2 = plt.tunicGreen,
      special = plt.leagueGreen,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.robinRed,
      indent = plt.bg_lighter,
      indent_scope = plt.robinRed,
      picker = plt.assassinRed,
      yank = plt.armorGold,
      mark = plt.leagueGreen,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.robinRed,
        bg_alternate = plt.bg_darkest,
        indicator = plt.armorGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.robinRed,
      accent2 = plt.tunicGreen,
      accent3 = plt.armorGold,
      accent4 = plt.sonOfBatman,
      accent5 = plt.assassinRed,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.robinRed,
      rainbow2 = plt.tunicGreen,
      rainbow3 = plt.armorGold,
      rainbow4 = plt.sonOfBatman,
      rainbow5 = plt.leagueGreen,
      rainbow6 = plt.superiorityPurple,
      rainbow7 = plt.heirOrange,
    },

    syn = {
      attribute = plt.armorGold,
      boolean = plt.robinRed,
      comment = plt.fg_dark,
      constant = plt.armorGold,
      deprecated = plt.fg_mid,
      func = plt.leagueGreen,
      identifier = plt.fg_lightest,
      keyword = plt.robinRed,
      method = plt.taliaGreen,
      number = plt.katanaSilver,
      operator = plt.taliaGreen,
      parameter = plt.fg_mid,
      preproc = plt.raAlGhul,
      punct = plt.fg_mid,
      regex = plt.armorGold,
      statement = plt.robinRed,
      string = plt.tunicGreen,
      symbol = plt.taliaGreen,
      type = plt.armorGold,
      variable = plt.fg_lightest,
      special = plt.superiorityPurple,
      special2 = plt.assassinRed,
      special3 = plt.leagueGreen,
    },

    vcs = {
      added = plt.leagueGreen,
      removed = plt.assassinRed,
      changed = plt.armorGold,
    },

    diff = {
      add = plt.leagueGreen,
      change = plt.armorGold,
      delete = plt.assassinRed,
      text = plt.sonOfBatman,
    },

    diag = {
      ok = plt.leagueGreen,
      error = plt.assassinRed,
      warning = plt.heirOrange,
      info = plt.sonOfBatman,
      hint = plt.taliaGreen,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.robinRed,
      green = plt.tunicGreen,
      yellow = plt.armorGold,
      blue = plt.sonOfBatman,
      magenta = plt.superiorityPurple,
      cyan = plt.leagueGreen,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.robinRed):brighten(0.2):to_hex(),
      green_bright = color(plt.tunicGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.armorGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.sonOfBatman):brighten(0.3):to_hex(),
      magenta_bright = color(plt.superiorityPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.leagueGreen):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.armorGold,
      indexed2 = plt.robinRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.assassinRed,
      ["@comment.warning"] = plt.heirOrange,
      ["@comment.todo"] = plt.robinRed,
      ["@comment.note"] = plt.leagueGreen,

      ["@constant"] = plt.armorGold,
      ["@constant.builtin"] = plt.armorGold,
      ["@constant.macro"] = plt.alGhulGold,

      ["@string"] = plt.tunicGreen,
      ["@string.documentation"] = plt.tunicGreen,
      ["@string.regex"] = plt.armorGold,
      ["@string.escape"] = plt.superiorityPurple,
      ["@string.special"] = plt.leagueGreen,
      ["@string.special.symbol"] = plt.taliaGreen,
      ["@string.special.url"] = plt.leagueGreen,
      ["@string.special.path"] = plt.taliaGreen,

      ["@character"] = plt.tunicGreen,
      ["@character.special"] = plt.superiorityPurple,

      ["@number"] = plt.katanaSilver,
      ["@number.float"] = plt.katanaSilver,

      ["@boolean"] = plt.robinRed,

      ["@function"] = plt.leagueGreen,
      ["@function.builtin"] = plt.leagueGreen,
      ["@function.call"] = plt.leagueGreen,
      ["@function.macro"] = plt.raAlGhul,
      ["@function.method"] = plt.taliaGreen,
      ["@function.method.call"] = plt.taliaGreen,

      ["@constructor"] = plt.armorGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.robinRed,
      ["@keyword.coroutine"] = plt.damianRed,
      ["@keyword.function"] = plt.robinRed,
      ["@keyword.operator"] = plt.taliaGreen,
      ["@keyword.return"] = plt.robinRed,
      ["@keyword.import"] = plt.leagueGreen,
      ["@keyword.storage"] = plt.robinRed,
      ["@keyword.repeat"] = plt.robinRed,
      ["@keyword.conditional"] = plt.robinRed,
      ["@keyword.exception"] = plt.assassinRed,
      ["@keyword.directive"] = plt.raAlGhul,
      ["@keyword.directive.define"] = plt.raAlGhul,

      ["@conditional"] = plt.robinRed,
      ["@conditional.ternary"] = plt.robinRed,

      ["@repeat"] = plt.robinRed,

      ["@label"] = plt.damianRed,

      ["@operator"] = plt.taliaGreen,

      ["@exception"] = plt.assassinRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.damianRed,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.armorGold,
      ["@type.builtin"] = plt.armorGold,
      ["@type.definition"] = plt.armorGold,
      ["@type.qualifier"] = plt.robinRed,

      ["@attribute"] = plt.armorGold,
      ["@attribute.builtin"] = plt.armorGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.armorGold,
      ["@module.builtin"] = plt.armorGold,

      ["@namespace"] = plt.armorGold,
      ["@namespace.builtin"] = plt.armorGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.taliaGreen,

      ["@tag"] = plt.taliaGreen,
      ["@tag.attribute"] = plt.armorGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.taliaGreen,

      ["@markup.strong"] = { fg = plt.robinRed, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.robinRed,
      ["@markup.heading.1"] = plt.robinRed,
      ["@markup.heading.2"] = plt.armorGold,
      ["@markup.heading.3"] = plt.tunicGreen,
      ["@markup.heading.4"] = plt.leagueGreen,
      ["@markup.heading.5"] = plt.sonOfBatman,
      ["@markup.heading.6"] = plt.superiorityPurple,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.leagueGreen,
      ["@markup.link"] = plt.leagueGreen,
      ["@markup.link.label"] = plt.taliaGreen,
      ["@markup.link.url"] = plt.leagueGreen,
      ["@markup.raw"] = plt.tunicGreen,
      ["@markup.raw.block"] = plt.tunicGreen,
      ["@markup.list"] = plt.taliaGreen,
      ["@markup.list.checked"] = plt.leagueGreen,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.leagueGreen,
      ["@diff.minus"] = plt.assassinRed,
      ["@diff.delta"] = plt.armorGold,

      ["@none"] = "none",
      ["@conceal"] = plt.raAlGhul,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.armorGold,
      ["@constructor.javascript"] = plt.armorGold,
      ["@constructor.typescript"] = plt.armorGold,
      ["@namespace.rust"] = plt.armorGold,
      ["@type.qualifier.rust"] = plt.robinRed,
      ["@constant.macro.c"] = plt.alGhulGold,
      ["@constant.macro.cpp"] = plt.alGhulGold,
      ["@namespace.go"] = plt.armorGold,
      ["@property.css"] = plt.tunicGreen,
      ["@type.css"] = plt.taliaGreen,
      ["@label.json"] = plt.armorGold,
      ["@field.yaml"] = plt.tunicGreen,
      ["@property.toml"] = plt.tunicGreen,
      ["@function.builtin.bash"] = plt.leagueGreen,
      ["@string.regexp"] = plt.armorGold,
      ["@character.special.regex"] = plt.superiorityPurple,
    },

    lsp = {
      ["@lsp.type.class"] = plt.armorGold,
      ["@lsp.type.interface"] = plt.armorGold,
      ["@lsp.type.struct"] = plt.armorGold,
      ["@lsp.type.enum"] = plt.armorGold,
      ["@lsp.type.enumMember"] = plt.robinRed,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.armorGold,

      ["@lsp.type.macro"] = plt.alGhulGold,
      ["@lsp.type.decorator"] = plt.armorGold,

      ["@lsp.type.builtinType"] = plt.armorGold,
      ["@lsp.type.selfParameter"] = plt.damianRed,
      ["@lsp.type.typeParameter"] = plt.armorGold,

      ["@lsp.type.array"] = plt.armorGold,
      ["@lsp.type.object"] = plt.armorGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.robinRed,
      ["@lsp.type.enumConstant"] = plt.robinRed,

      ["@lsp.type.event"] = plt.armorGold,
      ["@lsp.type.regexp"] = plt.armorGold,
      ["@lsp.type.unresolvedReference"] = plt.armorGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.robinRed,
      ["@lsp.mod.async"] = plt.robinRed,
      ["@lsp.mod.static"] = plt.damianRed,
      ["@lsp.mod.abstract"] = plt.armorGold,
      ["@lsp.mod.defaultLibrary"] = plt.armorGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Bat-Family – Robin (Damian Wayne)",
  author = "PrismPunk.nvim",
  description = "I'm the son of Batman! The League of Assassins' heir with Robin red, "
    .. "league green, katana steel, and the arrogance of Ra's al Ghul's grandson. "
    .. "Trained by Talia, destined for greatness.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.assassinRed,
    base09 = palette.heirOrange,
    base0A = palette.armorGold,
    base0B = palette.tunicGreen,
    base0C = palette.leagueGreen,
    base0D = palette.sonOfBatman,
    base0E = palette.superiorityPurple,
    base0F = palette.robinRed,
  },

  palette = palette,
  get = M.get,
}
