local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0508",
  bg_darker = "#100A0E",
  bg_dark = "#1A0F14",
  bg_mid = "#24181F",
  bg_light = "#3D2D35",
  bg_lighter = "#56424D",
  bg_lightest = "#6F5764",
  fg_lightest = "#F5E8F1",
  fg_light = "#E8D0DF",
  fg_mid = "#C9A8BC",
  fg_dark = "#9A7588",
  bg_alt1 = "#150C11",
  bg_alt2 = "#0D070A",
  bg_alt3 = "#1D101A",
  bg_alt4 = "#0E080B",
  selinaBlack = "#1A0F14",
  laceDark = "#2D1F26",
  velvetBlack = "#241A20",
  midnightSilk = "#1F151A",
  femmeRed = "#DC143C",
  lipstickRed = "#E63946",
  passionRed = "#FF1744",
  roseRed = "#C41E3A",
  diamondWhite = "#F8F8FF",
  pearlSheen = "#FAF0E6",
  jewelWhite = "#FFFFF0",
  silverShine = "#E8E8F0",
  seductionPink = "#FF69B4",
  blushPink = "#FFB6C1",
  rougePink = "#FF1493",
  mysteryMagenta = "#DA70D6",
  emeraldHeist = "#50C878",
  sapphireBlue = "#0F52BA",
  amethystPurple = "#9966CC",
  champagneGold = "#F7E7CE",
  luxuryGold = "#FFD700",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.seductionPink,
      insert = plt.emeraldHeist,
      visual = plt.femmeRed,
      replace = plt.passionRed,
      command = plt.luxuryGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.luxuryGold,
      bg_visual = plt.femmeRed,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.seductionPink,
      header2 = plt.luxuryGold,
      special = plt.emeraldHeist,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.seductionPink,
      indent = plt.bg_lighter,
      indent_scope = plt.seductionPink,
      picker = plt.passionRed,
      yank = plt.luxuryGold,
      mark = plt.emeraldHeist,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.seductionPink,
        bg_alternate = plt.bg_darkest,
        indicator = plt.luxuryGold,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.seductionPink,
      accent2 = plt.femmeRed,
      accent3 = plt.emeraldHeist,
      accent4 = plt.diamondWhite,
      accent5 = plt.passionRed,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.seductionPink,
      rainbow2 = plt.femmeRed,
      rainbow3 = plt.luxuryGold,
      rainbow4 = plt.emeraldHeist,
      rainbow5 = plt.sapphireBlue,
      rainbow6 = plt.amethystPurple,
      rainbow7 = plt.diamondWhite,
    },

    syn = {
      attribute = plt.luxuryGold,
      boolean = plt.seductionPink,
      comment = plt.fg_dark,
      constant = plt.luxuryGold,
      deprecated = plt.fg_mid,
      func = plt.emeraldHeist,
      identifier = plt.fg_lightest,
      keyword = plt.seductionPink,
      method = plt.emeraldHeist,
      number = plt.silverShine,
      operator = plt.emeraldHeist,
      parameter = plt.fg_mid,
      preproc = plt.mysteryMagenta,
      punct = plt.fg_mid,
      regex = plt.luxuryGold,
      statement = plt.seductionPink,
      string = plt.diamondWhite,
      symbol = plt.emeraldHeist,
      type = plt.luxuryGold,
      variable = plt.fg_lightest,
      special = plt.rougePink,
      special2 = plt.passionRed,
      special3 = plt.sapphireBlue,
    },

    vcs = {
      added = plt.emeraldHeist,
      removed = plt.passionRed,
      changed = plt.luxuryGold,
    },

    diff = {
      add = plt.emeraldHeist,
      change = plt.luxuryGold,
      delete = plt.passionRed,
      text = plt.seductionPink,
    },

    diag = {
      ok = plt.emeraldHeist,
      error = plt.passionRed,
      warning = plt.luxuryGold,
      info = plt.sapphireBlue,
      hint = plt.emeraldHeist,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.femmeRed,
      green = plt.emeraldHeist,
      yellow = plt.luxuryGold,
      blue = plt.sapphireBlue,
      magenta = plt.seductionPink,
      cyan = plt.emeraldHeist,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.femmeRed):brighten(0.2):to_hex(),
      green_bright = color(plt.emeraldHeist):brighten(0.1):to_hex(),
      yellow_bright = color(plt.luxuryGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.sapphireBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.seductionPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.emeraldHeist):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.luxuryGold,
      indexed2 = plt.passionRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.passionRed,
      ["@comment.warning"] = plt.luxuryGold,
      ["@comment.todo"] = plt.seductionPink,
      ["@comment.note"] = plt.emeraldHeist,

      ["@constant"] = plt.luxuryGold,
      ["@constant.builtin"] = plt.luxuryGold,
      ["@constant.macro"] = plt.champagneGold,

      ["@string"] = plt.diamondWhite,
      ["@string.documentation"] = plt.diamondWhite,
      ["@string.regex"] = plt.luxuryGold,
      ["@string.escape"] = plt.rougePink,
      ["@string.special"] = plt.emeraldHeist,
      ["@string.special.symbol"] = plt.emeraldHeist,
      ["@string.special.url"] = plt.sapphireBlue,
      ["@string.special.path"] = plt.emeraldHeist,

      ["@character"] = plt.diamondWhite,
      ["@character.special"] = plt.rougePink,

      ["@number"] = plt.silverShine,
      ["@number.float"] = plt.silverShine,

      ["@boolean"] = plt.seductionPink,

      ["@function"] = plt.emeraldHeist,
      ["@function.builtin"] = plt.emeraldHeist,
      ["@function.call"] = plt.emeraldHeist,
      ["@function.macro"] = plt.mysteryMagenta,
      ["@function.method"] = plt.emeraldHeist,
      ["@function.method.call"] = plt.emeraldHeist,

      ["@constructor"] = plt.luxuryGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.seductionPink,
      ["@keyword.coroutine"] = plt.blushPink,
      ["@keyword.function"] = plt.seductionPink,
      ["@keyword.operator"] = plt.emeraldHeist,
      ["@keyword.return"] = plt.seductionPink,
      ["@keyword.import"] = plt.emeraldHeist,
      ["@keyword.storage"] = plt.seductionPink,
      ["@keyword.repeat"] = plt.seductionPink,
      ["@keyword.conditional"] = plt.seductionPink,
      ["@keyword.exception"] = plt.passionRed,
      ["@keyword.directive"] = plt.mysteryMagenta,
      ["@keyword.directive.define"] = plt.mysteryMagenta,

      ["@conditional"] = plt.seductionPink,
      ["@conditional.ternary"] = plt.seductionPink,

      ["@repeat"] = plt.seductionPink,

      ["@label"] = plt.blushPink,

      ["@operator"] = plt.emeraldHeist,

      ["@exception"] = plt.passionRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.blushPink,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.luxuryGold,
      ["@type.builtin"] = plt.luxuryGold,
      ["@type.definition"] = plt.luxuryGold,
      ["@type.qualifier"] = plt.seductionPink,

      ["@attribute"] = plt.luxuryGold,
      ["@attribute.builtin"] = plt.luxuryGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.luxuryGold,
      ["@module.builtin"] = plt.luxuryGold,

      ["@namespace"] = plt.luxuryGold,
      ["@namespace.builtin"] = plt.luxuryGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.emeraldHeist,

      ["@tag"] = plt.emeraldHeist,
      ["@tag.attribute"] = plt.luxuryGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.emeraldHeist,

      ["@markup.strong"] = { fg = plt.seductionPink, bold = true },
      ["@markup.italic"] = { fg = plt.diamondWhite, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.fg_light, underline = true },
      ["@markup.heading"] = plt.seductionPink,
      ["@markup.heading.1"] = plt.seductionPink,
      ["@markup.heading.2"] = plt.femmeRed,
      ["@markup.heading.3"] = plt.luxuryGold,
      ["@markup.heading.4"] = plt.emeraldHeist,
      ["@markup.heading.5"] = plt.sapphireBlue,
      ["@markup.heading.6"] = plt.amethystPurple,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.emeraldHeist,
      ["@markup.link"] = plt.emeraldHeist,
      ["@markup.link.label"] = plt.emeraldHeist,
      ["@markup.link.url"] = plt.sapphireBlue,
      ["@markup.raw"] = plt.diamondWhite,
      ["@markup.raw.block"] = plt.diamondWhite,
      ["@markup.list"] = plt.emeraldHeist,
      ["@markup.list.checked"] = plt.emeraldHeist,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.emeraldHeist,
      ["@diff.minus"] = plt.passionRed,
      ["@diff.delta"] = plt.luxuryGold,

      ["@none"] = "none",
      ["@conceal"] = plt.mysteryMagenta,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.luxuryGold,
      ["@constructor.javascript"] = plt.luxuryGold,
      ["@constructor.typescript"] = plt.luxuryGold,
      ["@namespace.rust"] = plt.luxuryGold,
      ["@type.qualifier.rust"] = plt.seductionPink,
      ["@constant.macro.c"] = plt.champagneGold,
      ["@constant.macro.cpp"] = plt.champagneGold,
      ["@namespace.go"] = plt.luxuryGold,
      ["@property.css"] = plt.diamondWhite,
      ["@type.css"] = plt.emeraldHeist,
      ["@label.json"] = plt.luxuryGold,
      ["@field.yaml"] = plt.diamondWhite,
      ["@property.toml"] = plt.diamondWhite,
      ["@function.builtin.bash"] = plt.emeraldHeist,
      ["@string.regexp"] = plt.luxuryGold,
      ["@character.special.regex"] = plt.rougePink,
    },

    lsp = {
      ["@lsp.type.class"] = plt.luxuryGold,
      ["@lsp.type.interface"] = plt.luxuryGold,
      ["@lsp.type.struct"] = plt.luxuryGold,
      ["@lsp.type.enum"] = plt.luxuryGold,
      ["@lsp.type.enumMember"] = plt.seductionPink,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.luxuryGold,

      ["@lsp.type.macro"] = plt.champagneGold,
      ["@lsp.type.decorator"] = plt.luxuryGold,

      ["@lsp.type.builtinType"] = plt.luxuryGold,
      ["@lsp.type.selfParameter"] = plt.blushPink,
      ["@lsp.type.typeParameter"] = plt.luxuryGold,

      ["@lsp.type.array"] = plt.luxuryGold,
      ["@lsp.type.object"] = plt.luxuryGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.seductionPink,
      ["@lsp.type.enumConstant"] = plt.seductionPink,

      ["@lsp.type.event"] = plt.luxuryGold,
      ["@lsp.type.regexp"] = plt.luxuryGold,
      ["@lsp.type.unresolvedReference"] = plt.luxuryGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.seductionPink,
      ["@lsp.mod.async"] = plt.seductionPink,
      ["@lsp.mod.static"] = plt.blushPink,
      ["@lsp.mod.abstract"] = plt.luxuryGold,
      ["@lsp.mod.defaultLibrary"] = plt.luxuryGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Gotham – Selina Kyle (Femme Fatale)",
  author = "PrismPunk.nvim",
  description = "Velvet elegance and diamond heists. Seduction pink lipstick, passion red desire, "
    .. "emerald jewel thefts, and champagne luxury. The femme fatale who stole Bruce's heart.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.passionRed,
    base09 = palette.champagneGold,
    base0A = palette.luxuryGold,
    base0B = palette.emeraldHeist,
    base0C = palette.emeraldHeist,
    base0D = palette.sapphireBlue,
    base0E = palette.seductionPink,
    base0F = palette.diamondWhite,
  },

  palette = palette,
  get = M.get,
}
