local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#090507",
  bg_darker = "#0F0B0B",
  bg_dark = "#141215",
  bg_mid = "#1B1719",
  bg_light = "#221D1F",
  bg_lighter = "#2F2A26",
  bg_lightest = "#3A3532",
  fg_lightest = "#EFE7E2",
  fg_light = "#C4B8AF",
  fg_mid = "#9E9086",
  fg_dark = "#6E6660",
  bg_alt1 = "#1A1517",
  bg_alt2 = "#0D0909",
  bg_alt3 = "#211C1E",
  bg_alt4 = "#120E10",
  brassBright = "#D9A04A",
  brassCore = "#B07A2D",
  brassDark = "#8B5F2B",
  brassDeep = "#6B4921",
  primalRed = "#D94F4F",
  warriorRed = "#B33A3A",
  bloodRed = "#8E2D2D",
  ancientGold = "#FFD966",
  featherGold = "#FFD9B3",
  wingBronze = "#8B5F2B",
  skyIndigo = "#5566A3",
  mysticBlue = "#4A5C99",
  flightBlue = "#61AFEF",
  stone = "#9E9086",
  stoneLight = "#B5A89D",
  leather = "#5A5252",
  shadowGray = "#342F2F",
  dimGray = "#5A5252",
  lightGray = "#EFE7E2",
  dangerRed = "#D94F4F",
  warningOrange = "#FFC870",
  infoBlue = "#61AFEF",
  hintTeal = "#5FA899",
  earthBrown = "#6B4921",
  metalGray = "#7A7268",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.brassCore,
      insert = plt.brassBright,
      visual = plt.skyIndigo,
      replace = plt.primalRed,
      command = plt.ancientGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      bg_search = plt.earthBrown,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.brassDark,
      header1 = plt.brassBright,
      header2 = plt.ancientGold,
      special = plt.skyIndigo,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.brassCore,
      indent = plt.bg_lighter,
      indent_scope = plt.brassCore,
      picker = plt.primalRed,
      yank = plt.featherGold,
      mark = plt.skyIndigo,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.brassBright,
        bg_alternate = plt.bg_darkest,
        indicator = plt.brassCore,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.brassDark,
        bg_border = plt.bg_darker,
      },
    },

    accent = {
      accent1 = plt.brassCore,
      accent2 = plt.brassBright,
      accent3 = plt.ancientGold,
      accent4 = plt.skyIndigo,
      accent5 = plt.hintTeal,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.brassBright,
      rainbow2 = plt.brassCore,
      rainbow3 = plt.ancientGold,
      rainbow4 = plt.skyIndigo,
      rainbow5 = plt.hintTeal,
      rainbow6 = plt.earthBrown,
      rainbow7 = plt.metalGray,
    },

    syn = {
      attribute = plt.ancientGold,
      boolean = plt.warriorRed,
      comment = plt.shadowGray,
      constant = plt.featherGold,
      deprecated = plt.dimGray,
      func = plt.skyIndigo,
      identifier = plt.fg_lightest,
      keyword = plt.brassCore,
      method = plt.mysticBlue,
      number = plt.ancientGold,
      operator = plt.hintTeal,
      parameter = plt.fg_mid,
      preproc = plt.brassBright,
      punct = plt.fg_mid,
      regex = plt.hintTeal,
      statement = plt.brassCore,
      string = plt.brassBright,
      symbol = plt.ancientGold,
      type = plt.ancientGold,
      variable = plt.fg_lightest,
      special = plt.brassBright,
      special2 = plt.skyIndigo,
      special3 = plt.metalGray,
    },

    vcs = {
      added = plt.brassBright,
      removed = plt.primalRed,
      changed = plt.ancientGold,
    },

    diff = {
      add = plt.brassBright,
      change = plt.ancientGold,
      delete = plt.primalRed,
      text = plt.skyIndigo,
    },

    diag = {
      ok = plt.brassBright,
      error = plt.dangerRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      hint = plt.hintTeal,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.primalRed,
      green = plt.brassBright,
      yellow = plt.ancientGold,
      blue = plt.flightBlue,
      magenta = plt.warriorRed,
      cyan = plt.hintTeal,
      white = plt.stone,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.primalRed):brighten(0.2):to_hex(),
      green_bright = color(plt.brassBright):brighten(0.1):to_hex(),
      yellow_bright = color(plt.ancientGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.flightBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.warriorRed):brighten(0.2):to_hex(),
      cyan_bright = color(plt.hintTeal):brighten(0.1):to_hex(),
      white_bright = color(plt.stone):brighten(0.2):to_hex(),
      indexed1 = plt.ancientGold,
      indexed2 = plt.primalRed,
    },

    treesitter = {
      ["@comment"] = plt.shadowGray,
      ["@comment.documentation"] = plt.dimGray,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningOrange,
      ["@comment.todo"] = plt.infoBlue,
      ["@comment.note"] = plt.hintTeal,

      ["@constant"] = plt.featherGold,
      ["@constant.builtin"] = plt.featherGold,
      ["@constant.macro"] = plt.ancientGold,

      ["@string"] = plt.brassBright,
      ["@string.documentation"] = plt.brassBright,
      ["@string.regex"] = plt.hintTeal,
      ["@string.escape"] = plt.ancientGold,
      ["@string.special"] = plt.featherGold,
      ["@string.special.symbol"] = plt.ancientGold,
      ["@string.special.url"] = plt.skyIndigo,
      ["@string.special.path"] = plt.brassBright,

      ["@character"] = plt.brassBright,
      ["@character.special"] = plt.ancientGold,

      ["@number"] = plt.ancientGold,
      ["@number.float"] = plt.ancientGold,

      ["@boolean"] = plt.warriorRed,

      ["@function"] = plt.skyIndigo,
      ["@function.builtin"] = plt.skyIndigo,
      ["@function.call"] = plt.skyIndigo,
      ["@function.macro"] = plt.brassBright,
      ["@function.method"] = plt.mysticBlue,
      ["@function.method.call"] = plt.mysticBlue,

      ["@constructor"] = plt.ancientGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.brassCore,
      ["@keyword.coroutine"] = plt.brassBright,
      ["@keyword.function"] = plt.brassCore,
      ["@keyword.operator"] = plt.hintTeal,
      ["@keyword.return"] = plt.brassCore,
      ["@keyword.import"] = plt.brassBright,
      ["@keyword.storage"] = plt.brassCore,
      ["@keyword.repeat"] = plt.brassCore,
      ["@keyword.conditional"] = plt.brassCore,
      ["@keyword.exception"] = plt.primalRed,
      ["@keyword.directive"] = plt.brassBright,
      ["@keyword.directive.define"] = plt.brassBright,

      ["@conditional"] = plt.brassCore,
      ["@conditional.ternary"] = plt.brassCore,

      ["@repeat"] = plt.brassCore,

      ["@label"] = plt.brassBright,

      ["@operator"] = plt.hintTeal,

      ["@exception"] = plt.primalRed,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.brassBright,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.ancientGold,
      ["@type.builtin"] = plt.ancientGold,
      ["@type.definition"] = plt.ancientGold,
      ["@type.qualifier"] = plt.brassCore,

      ["@attribute"] = plt.ancientGold,
      ["@attribute.builtin"] = plt.ancientGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.ancientGold,
      ["@module.builtin"] = plt.ancientGold,

      ["@namespace"] = plt.ancientGold,
      ["@namespace.builtin"] = plt.ancientGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.hintTeal,

      ["@tag"] = plt.brassCore,
      ["@tag.attribute"] = plt.ancientGold,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.brassCore,

      ["@markup.strong"] = { fg = plt.brassBright, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.shadowGray, strikethrough = true },
      ["@markup.underline"] = { fg = plt.featherGold, underline = true },
      ["@markup.heading"] = plt.brassBright,
      ["@markup.heading.1"] = plt.brassBright,
      ["@markup.heading.2"] = plt.ancientGold,
      ["@markup.heading.3"] = plt.skyIndigo,
      ["@markup.heading.4"] = plt.hintTeal,
      ["@markup.heading.5"] = plt.brassCore,
      ["@markup.heading.6"] = plt.metalGray,
      ["@markup.quote"] = plt.dimGray,
      ["@markup.math"] = plt.ancientGold,
      ["@markup.link"] = plt.skyIndigo,
      ["@markup.link.label"] = plt.hintTeal,
      ["@markup.link.url"] = plt.skyIndigo,
      ["@markup.raw"] = plt.brassBright,
      ["@markup.raw.block"] = plt.brassBright,
      ["@markup.list"] = plt.brassCore,
      ["@markup.list.checked"] = plt.brassBright,
      ["@markup.list.unchecked"] = plt.dimGray,

      ["@diff.plus"] = plt.brassBright,
      ["@diff.minus"] = plt.primalRed,
      ["@diff.delta"] = plt.ancientGold,

      ["@none"] = "none",
      ["@conceal"] = plt.earthBrown,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.ancientGold,
      ["@constructor.javascript"] = plt.ancientGold,
      ["@constructor.typescript"] = plt.ancientGold,
      ["@namespace.rust"] = plt.ancientGold,
      ["@type.qualifier.rust"] = plt.brassCore,
      ["@constant.macro.c"] = plt.ancientGold,
      ["@constant.macro.cpp"] = plt.ancientGold,
      ["@namespace.go"] = plt.ancientGold,
      ["@property.css"] = plt.mysticBlue,
      ["@type.css"] = plt.brassCore,
      ["@label.json"] = plt.ancientGold,
      ["@field.yaml"] = plt.mysticBlue,
      ["@property.toml"] = plt.mysticBlue,
      ["@function.builtin.bash"] = plt.skyIndigo,
      ["@string.regexp"] = plt.hintTeal,
      ["@character.special.regex"] = plt.ancientGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.ancientGold,
      ["@lsp.type.interface"] = plt.ancientGold,
      ["@lsp.type.struct"] = plt.ancientGold,
      ["@lsp.type.enum"] = plt.ancientGold,
      ["@lsp.type.enumMember"] = plt.featherGold,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.ancientGold,

      ["@lsp.type.macro"] = plt.ancientGold,
      ["@lsp.type.decorator"] = plt.ancientGold,

      ["@lsp.type.builtinType"] = plt.ancientGold,
      ["@lsp.type.selfParameter"] = plt.brassBright,
      ["@lsp.type.typeParameter"] = plt.ancientGold,

      ["@lsp.type.array"] = plt.ancientGold,
      ["@lsp.type.object"] = plt.ancientGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.featherGold,
      ["@lsp.type.enumConstant"] = plt.featherGold,

      ["@lsp.type.event"] = plt.ancientGold,
      ["@lsp.type.regexp"] = plt.hintTeal,
      ["@lsp.type.unresolvedReference"] = plt.ancientGold,

      ["@lsp.mod.deprecated"] = { fg = plt.dimGray, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.featherGold,
      ["@lsp.mod.async"] = plt.brassCore,
      ["@lsp.mod.static"] = plt.brassBright,
      ["@lsp.mod.abstract"] = plt.ancientGold,
      ["@lsp.mod.defaultLibrary"] = plt.ancientGold,
      ["@lsp.mod.documentation"] = plt.dimGray,
    },
  }
end

return {
  name = "Justice League – Hawkman",
  author = "PrismPunk.nvim",
  description = "Ancient warrior — brass wings and primal force.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.dimGray,
    base05 = palette.stone,
    base06 = palette.lightGray,
    base07 = palette.featherGold,
    base08 = palette.primalRed,
    base09 = palette.ancientGold,
    base0A = palette.ancientGold,
    base0B = palette.brassBright,
    base0C = palette.hintTeal,
    base0D = palette.skyIndigo,
    base0E = palette.brassCore,
    base0F = palette.earthBrown,
  },

  palette = palette,
  get = M.get,
}
