local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#04120A",
  bg_darker = "#0B140D",
  bg_dark = "#111A14",
  bg_mid = "#18221B",
  bg_light = "#2F3834",
  bg_lighter = "#5B6069",
  bg_lightest = "#A9BFB4",

  fg_lightest = "#E6F7F2",
  fg_light = "#9FE6D6",
  fg_mid = "#A9BFB4",
  fg_dark = "#5B6069",

  bg_alt1 = "#0D1610",
  bg_alt2 = "#09120B",
  bg_alt3 = "#141D16",
  bg_alt4 = "#0F1812",

  martianGreen = "#1AA35A",
  emeraldDeep = "#178A4A",
  martianCore = "#0F6B39",
  crimsonEye = "#D63A3A",
  etherBlue = "#66C6FF",
  jadeEmpathy = "#2FB06A",
  accentGold = "#FFD966",
  accentViolet = "#B39BFF",
  dangerRed = "#FF6666",
  warningOrange = "#FFC870",
  infoBlue = "#61AFEF",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.martianCore,
      insert = plt.etherBlue,
      visual = plt.martianGreen,
      replace = plt.crimsonEye,
      command = plt.jadeEmpathy,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_dark,
      fg_dark = plt.bg_lightest,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.emeraldDeep,
      bg_visual = plt.accentViolet,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.accentGold,
      header2 = plt.crimsonEye,
      special = plt.jadeEmpathy,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.martianCore,
      indent = plt.bg_lighter,
      indent_scope = plt.martianCore,
      picker = plt.crimsonEye,
      yank = plt.accentGold,
      mark = plt.jadeEmpathy,
      scrollbar = plt.bg_lighter,
      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.accentGold,
        bg_alternate = plt.bg_darkest,
        indicator = plt.jadeEmpathy,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.accentGold,
      accent2 = plt.martianCore,
      accent3 = plt.jadeEmpathy,
      accent4 = plt.crimsonEye,
      accent5 = plt.accentViolet,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.accentGold,
      rainbow2 = plt.martianCore,
      rainbow3 = plt.crimsonEye,
      rainbow4 = plt.jadeEmpathy,
      rainbow5 = plt.accentViolet,
      rainbow6 = plt.emeraldDeep,
      rainbow7 = plt.etherBlue,
    },

    syn = {
      attribute = plt.warningOrange,
      boolean = plt.jadeEmpathy,
      comment = plt.fg_dark,
      constant = plt.crimsonEye,
      deprecated = plt.fg_mid,
      func = plt.etherBlue,
      identifier = plt.fg_lightest,
      keyword = plt.martianCore,
      method = plt.jadeEmpathy,
      number = plt.accentGold,
      operator = plt.jadeEmpathy,
      parameter = plt.fg_mid,
      preproc = plt.etherBlue,
      punct = plt.fg_mid,
      regex = plt.warningOrange,
      statement = plt.martianCore,
      string = plt.martianGreen,
      symbol = plt.jadeEmpathy,
      type = plt.accentGold,
      variable = plt.fg_lightest,
      special = plt.warningOrange,
      special2 = plt.crimsonEye,
      special3 = plt.etherBlue,
    },

    vcs = {
      added = plt.jadeEmpathy,
      removed = plt.crimsonEye,
      changed = plt.accentGold,
    },

    diff = {
      add = plt.jadeEmpathy,
      change = plt.accentGold,
      delete = plt.crimsonEye,
      text = plt.etherBlue,
    },

    diag = {
      ok = plt.jadeEmpathy,
      error = plt.dangerRed,
      warning = plt.warningOrange,
      info = plt.infoBlue,
      hint = plt.jadeEmpathy,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.crimsonEye,
      green = plt.martianGreen,
      yellow = plt.accentGold,
      blue = plt.etherBlue,
      magenta = plt.accentViolet,
      cyan = plt.jadeEmpathy,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.crimsonEye):brighten(0.2):to_hex(),
      green_bright = color(plt.martianGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.accentGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.etherBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.accentViolet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.jadeEmpathy):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.accentGold,
      indexed2 = plt.crimsonEye,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@comment.documentation"] = plt.fg_mid,
      ["@comment.error"] = plt.dangerRed,
      ["@comment.warning"] = plt.warningOrange,
      ["@comment.todo"] = plt.etherBlue,
      ["@comment.note"] = plt.jadeEmpathy,

      ["@constant"] = plt.crimsonEye,
      ["@constant.builtin"] = plt.crimsonEye,
      ["@constant.macro"] = plt.warningOrange,

      ["@string"] = plt.martianGreen,
      ["@string.documentation"] = plt.martianGreen,
      ["@string.regex"] = plt.warningOrange,
      ["@string.escape"] = plt.accentGold,
      ["@string.special"] = plt.jadeEmpathy,
      ["@string.special.symbol"] = plt.jadeEmpathy,
      ["@string.special.url"] = plt.accentViolet,
      ["@string.special.path"] = plt.martianGreen,

      ["@character"] = plt.martianGreen,
      ["@character.special"] = plt.accentGold,

      ["@number"] = plt.accentGold,
      ["@number.float"] = plt.accentGold,

      ["@boolean"] = plt.jadeEmpathy,

      ["@function"] = plt.etherBlue,
      ["@function.builtin"] = plt.etherBlue,
      ["@function.call"] = plt.etherBlue,
      ["@function.macro"] = plt.emeraldDeep,
      ["@function.method"] = plt.jadeEmpathy,
      ["@function.method.call"] = plt.jadeEmpathy,

      ["@constructor"] = plt.accentGold,

      ["@parameter"] = plt.fg_mid,
      ["@parameter.builtin"] = plt.fg_light,

      ["@keyword"] = plt.martianCore,
      ["@keyword.coroutine"] = plt.emeraldDeep,
      ["@keyword.function"] = plt.martianCore,
      ["@keyword.operator"] = plt.jadeEmpathy,
      ["@keyword.return"] = plt.martianCore,
      ["@keyword.import"] = plt.etherBlue,
      ["@keyword.storage"] = plt.martianCore,
      ["@keyword.repeat"] = plt.martianCore,
      ["@keyword.conditional"] = plt.martianCore,
      ["@keyword.exception"] = plt.martianCore,
      ["@keyword.directive"] = plt.etherBlue,
      ["@keyword.directive.define"] = plt.etherBlue,

      ["@conditional"] = plt.martianCore,
      ["@conditional.ternary"] = plt.martianCore,

      ["@repeat"] = plt.martianCore,

      ["@label"] = plt.emeraldDeep,

      ["@operator"] = plt.jadeEmpathy,

      ["@exception"] = plt.martianCore,

      ["@variable"] = plt.fg_lightest,
      ["@variable.builtin"] = plt.emeraldDeep,
      ["@variable.parameter"] = plt.fg_mid,
      ["@variable.member"] = plt.fg_light,

      ["@type"] = plt.accentGold,
      ["@type.builtin"] = plt.accentGold,
      ["@type.definition"] = plt.accentGold,
      ["@type.qualifier"] = plt.martianCore,

      ["@attribute"] = plt.warningOrange,
      ["@attribute.builtin"] = plt.accentGold,

      ["@property"] = plt.fg_light,

      ["@field"] = plt.fg_light,

      ["@module"] = plt.accentGold,
      ["@module.builtin"] = plt.accentGold,

      ["@namespace"] = plt.accentGold,
      ["@namespace.builtin"] = plt.accentGold,

      ["@punctuation.delimiter"] = plt.fg_mid,
      ["@punctuation.bracket"] = plt.fg_mid,
      ["@punctuation.special"] = plt.jadeEmpathy,

      ["@tag"] = plt.martianCore,
      ["@tag.attribute"] = plt.warningOrange,
      ["@tag.delimiter"] = plt.fg_mid,
      ["@tag.builtin"] = plt.martianCore,

      ["@markup.strong"] = { fg = plt.accentGold, bold = true },
      ["@markup.italic"] = { fg = plt.fg_light, italic = true },
      ["@markup.strikethrough"] = { fg = plt.fg_dark, strikethrough = true },
      ["@markup.underline"] = { fg = plt.jadeEmpathy, underline = true },
      ["@markup.heading"] = plt.accentGold,
      ["@markup.heading.1"] = plt.accentGold,
      ["@markup.heading.2"] = plt.accentGold,
      ["@markup.heading.3"] = plt.martianCore,
      ["@markup.heading.4"] = plt.etherBlue,
      ["@markup.heading.5"] = plt.jadeEmpathy,
      ["@markup.heading.6"] = plt.accentViolet,
      ["@markup.quote"] = plt.fg_mid,
      ["@markup.math"] = plt.jadeEmpathy,
      ["@markup.link"] = plt.accentViolet,
      ["@markup.link.label"] = plt.jadeEmpathy,
      ["@markup.link.url"] = plt.accentViolet,
      ["@markup.raw"] = plt.martianGreen,
      ["@markup.raw.block"] = plt.martianGreen,
      ["@markup.list"] = plt.martianCore,
      ["@markup.list.checked"] = plt.jadeEmpathy,
      ["@markup.list.unchecked"] = plt.fg_mid,

      ["@diff.plus"] = plt.jadeEmpathy,
      ["@diff.minus"] = plt.crimsonEye,
      ["@diff.delta"] = plt.accentGold,

      ["@none"] = "none",
      ["@conceal"] = plt.emeraldDeep,
      ["@spell"] = plt.fg_lightest,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.fg_light,
      ["@constructor.python"] = plt.accentGold,
      ["@constructor.javascript"] = plt.accentGold,
      ["@constructor.typescript"] = plt.accentGold,
      ["@namespace.rust"] = plt.accentGold,
      ["@type.qualifier.rust"] = plt.martianCore,
      ["@constant.macro.c"] = plt.warningOrange,
      ["@constant.macro.cpp"] = plt.warningOrange,
      ["@namespace.go"] = plt.accentGold,
      ["@property.css"] = plt.accentViolet,
      ["@type.css"] = plt.martianCore,
      ["@label.json"] = plt.accentGold,
      ["@field.yaml"] = plt.accentViolet,
      ["@property.toml"] = plt.accentViolet,
      ["@function.builtin.bash"] = plt.etherBlue,
      ["@string.regexp"] = plt.warningOrange,
      ["@character.special.regex"] = plt.accentGold,
    },

    lsp = {
      ["@lsp.type.class"] = plt.accentGold,
      ["@lsp.type.interface"] = plt.accentGold,
      ["@lsp.type.struct"] = plt.accentGold,
      ["@lsp.type.enum"] = plt.accentGold,
      ["@lsp.type.enumMember"] = plt.crimsonEye,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.type.namespace"] = plt.accentGold,

      ["@lsp.type.macro"] = plt.warningOrange,
      ["@lsp.type.decorator"] = plt.accentGold,

      ["@lsp.type.builtinType"] = plt.accentGold,
      ["@lsp.type.selfParameter"] = plt.emeraldDeep,
      ["@lsp.type.typeParameter"] = plt.accentGold,

      ["@lsp.type.array"] = plt.accentGold,
      ["@lsp.type.object"] = plt.accentGold,
      ["@lsp.type.key"] = plt.fg_light,
      ["@lsp.type.null"] = plt.crimsonEye,
      ["@lsp.type.enumConstant"] = plt.crimsonEye,

      ["@lsp.type.event"] = plt.accentGold,
      ["@lsp.type.regexp"] = plt.warningOrange,
      ["@lsp.type.unresolvedReference"] = plt.accentGold,

      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.crimsonEye,
      ["@lsp.mod.async"] = plt.martianCore,
      ["@lsp.mod.static"] = plt.emeraldDeep,
      ["@lsp.mod.abstract"] = plt.accentGold,
      ["@lsp.mod.defaultLibrary"] = plt.accentGold,
      ["@lsp.mod.documentation"] = plt.fg_mid,
    },
  }
end

return {
  name = "Justice League – Martian Manhunter",
  author = "PrismPunk.nvim",
  description = "Alien calm — empathy, stealth, and quiet strength.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.crimsonEye,
    base09 = palette.etherBlue,
    base0A = palette.accentGold,
    base0B = palette.martianGreen,
    base0C = palette.fg_light,
    base0D = palette.etherBlue,
    base0E = palette.accentViolet,
    base0F = palette.jadeEmpathy,
  },

  palette = palette,
  get = M.get,
}
