local color = require("prismpunk.utils.color")
local palette = require("prismpunk.palettes.dc.justice-league.starfire")

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.tamaran_gold,
      insert = plt.starbolt_green,
      visual = plt.tamaran_purple,
      replace = plt.radiant_heat,
      command = plt.kori_violet,
    },

    ui = {
      fg = plt.starfire_skin,
      fg_dim = plt.sunrise_glow,
      fg_dimmer = plt.solar_orange,
      fg_dark = plt.ultraviolet_gaze,
      fg_reverse = plt.void_black,

      bg_m4 = plt.nova_glow,
      bg_m3 = plt.star_core,
      bg_m2 = plt.tamaran_void,
      bg_m1 = plt.void_black,
      bg_dim = plt.void_black,
      bg = plt.void_black,
      bg_p1 = plt.tamaran_void,
      bg_p2 = plt.star_core,
      bg_gutter = opts.gutter and plt.star_core or "none",
      bg_cursorline = plt.star_core,
      bg_cursorline_alt = plt.tamaran_void,
      bg_search = plt.nova_purple,
      bg_visual = plt.tamaran_purple,
      bg_statusline = plt.star_core,

      border = plt.sunrise_glow,
      header1 = plt.tamaran_gold,
      header2 = plt.starbolt_green,
      special = plt.tamaran_purple,
      nontext = plt.tamaran_void,
      whitespace = plt.nova_glow,
      win_separator = plt.sunrise_glow,
      indent = plt.tamaran_void,
      indent_scope = plt.solar_orange,
      picker = plt.starfire_skin,
      yank = plt.radiant_heat,
      mark = plt.kori_violet,
      scrollbar = plt.star_core,

      tabline = {
        bg = plt.void_black,
        fg_selected = plt.starfire_skin,
        bg_selected = plt.star_core,
        fg_inactive = plt.solar_orange,
        bg_inactive = plt.void_black,
        fg_alternate = plt.tamaran_gold,
        bg_alternate = plt.void_black,
        indicator = plt.starbolt_green,
      },

      pmenu = {
        fg = plt.starfire_skin,
        fg_sel = "none",
        fg_border = plt.star_core,
        bg_border = plt.star_core,
        bg = plt.star_core,
        bg_sel = plt.tamaran_void,
        bg_sbar = plt.star_core,
        bg_thumb = plt.sunrise_glow,
      },

      float = {
        fg = plt.starfire_skin,
        bg = plt.tamaran_void,
        fg_border = plt.star_core,
        bg_border = plt.tamaran_void,
      },
    },

    accent = {
      accent1 = plt.tamaran_gold,
      accent2 = plt.starbolt_green,
      accent3 = plt.tamaran_purple,
      accent4 = plt.kori_violet,
      accent5 = plt.radiant_heat,
      invert = plt.star_core,
    },

    rainbow = {
      rainbow1 = plt.tamaran_gold,
      rainbow2 = plt.solar_orange,
      rainbow3 = plt.starfire_skin,
      rainbow4 = plt.starbolt_green,
      rainbow5 = plt.tamaran_emerald,
      rainbow6 = plt.tamaran_purple,
      rainbow7 = plt.nova_purple,
    },

    syn = {
      attribute = plt.starfire_skin,
      boolean = plt.radiant_heat,
      comment = plt.sunrise_glow,
      constant = plt.solar_orange,
      deprecated = plt.nova_glow,
      func = plt.tamaran_gold,
      identifier = plt.starfire_skin,
      keyword = plt.tamaran_gold,
      method = plt.starbolt_green,
      number = plt.kori_violet,
      operator = plt.tamaran_purple,
      parameter = plt.sunrise_glow,
      preproc = plt.radiant_heat,
      punct = plt.sunrise_glow,
      regex = plt.alien_radiance,
      statement = plt.tamaran_gold,
      string = plt.starbolt_green,
      symbol = plt.starfire_skin,
      type = plt.tamaran_purple,
      variable = plt.starfire_skin,
      special = plt.nova_purple,
      special2 = plt.tamaran_emerald,
      special3 = plt.kori_violet,
    },

    vcs = { added = plt.starbolt_green, removed = plt.radiant_heat, changed = plt.tamaran_purple },
    diff = { add = plt.starbolt_green, change = plt.tamaran_emerald, delete = plt.radiant_heat, text = plt.nova_purple },
    diag = {
      ok = plt.starbolt_green,
      error = plt.radiant_heat,
      warning = plt.tamaran_gold,
      info = plt.tamaran_purple,
      hint = plt.kori_violet,
    },

    term = {
      black = plt.void_black,
      red = plt.term_orange,
      green = plt.term_green,
      yellow = plt.term_orange,
      blue = plt.term_violet,
      magenta = plt.term_purple,
      cyan = plt.term_cyan,
      white = plt.starfire_skin,

      black_bright = color(plt.void_black):brighten(0.9):to_hex(),
      red_bright = plt.term_orange_bright,
      green_bright = plt.term_green_bright,
      yellow_bright = plt.term_orange_bright,
      blue_bright = plt.term_violet_bright,
      magenta_bright = plt.term_purple_bright,
      cyan_bright = plt.term_cyan_bright,
      white_bright = "#ffffff",
      indexed1 = plt.tamaran_gold,
      indexed2 = plt.starbolt_green,
    },

    treesitter = {
      ["@comment"] = plt.sunrise_glow,
      ["@comment.documentation"] = plt.solar_orange,
      ["@comment.error"] = plt.radiant_heat,
      ["@comment.warning"] = plt.tamaran_gold,
      ["@comment.todo"] = plt.tamaran_purple,
      ["@comment.note"] = plt.kori_violet,

      ["@constant"] = plt.solar_orange,
      ["@constant.builtin"] = plt.solar_orange,
      ["@constant.macro"] = plt.kori_violet,

      ["@string"] = plt.starbolt_green,
      ["@string.documentation"] = plt.starbolt_green,
      ["@string.regex"] = plt.alien_radiance,
      ["@string.escape"] = plt.tamaran_emerald,
      ["@string.special"] = plt.radiant_heat,
      ["@string.special.symbol"] = plt.starfire_skin,
      ["@string.special.url"] = plt.tamaran_purple,
      ["@string.special.path"] = plt.starbolt_green,

      ["@character"] = plt.starbolt_green,
      ["@character.special"] = plt.tamaran_emerald,

      ["@number"] = plt.kori_violet,
      ["@number.float"] = plt.kori_violet,

      ["@boolean"] = plt.radiant_heat,

      ["@function"] = plt.tamaran_gold,
      ["@function.builtin"] = plt.tamaran_gold,
      ["@function.call"] = plt.tamaran_gold,
      ["@function.macro"] = plt.starbolt_green,
      ["@function.method"] = plt.starbolt_green,
      ["@function.method.call"] = plt.starbolt_green,

      ["@constructor"] = plt.starfire_skin,

      ["@parameter"] = plt.sunrise_glow,
      ["@parameter.builtin"] = plt.starfire_skin,

      ["@keyword"] = plt.tamaran_gold,
      ["@keyword.coroutine"] = plt.radiant_heat,
      ["@keyword.function"] = plt.tamaran_gold,
      ["@keyword.operator"] = plt.tamaran_purple,
      ["@keyword.return"] = plt.tamaran_gold,
      ["@keyword.import"] = plt.starbolt_green,
      ["@keyword.storage"] = plt.tamaran_gold,
      ["@keyword.repeat"] = plt.tamaran_gold,
      ["@keyword.conditional"] = plt.tamaran_gold,
      ["@keyword.exception"] = plt.nova_purple,
      ["@keyword.directive"] = plt.radiant_heat,
      ["@keyword.directive.define"] = plt.radiant_heat,

      ["@conditional"] = plt.tamaran_gold,
      ["@conditional.ternary"] = plt.tamaran_gold,

      ["@repeat"] = plt.tamaran_gold,

      ["@label"] = plt.starbolt_green,

      ["@operator"] = plt.tamaran_purple,

      ["@exception"] = plt.nova_purple,

      ["@variable"] = plt.starfire_skin,
      ["@variable.builtin"] = plt.solar_orange,
      ["@variable.parameter"] = plt.sunrise_glow,
      ["@variable.member"] = plt.starfire_skin,

      ["@type"] = plt.tamaran_purple,
      ["@type.builtin"] = plt.tamaran_purple,
      ["@type.definition"] = plt.tamaran_purple,
      ["@type.qualifier"] = plt.tamaran_gold,

      ["@attribute"] = plt.starfire_skin,
      ["@attribute.builtin"] = plt.tamaran_purple,

      ["@property"] = plt.starfire_skin,
      ["@field"] = plt.starfire_skin,
      ["@module"] = plt.starfire_skin,
      ["@module.builtin"] = plt.starfire_skin,
      ["@namespace"] = plt.starfire_skin,
      ["@namespace.builtin"] = plt.starfire_skin,

      ["@punctuation.delimiter"] = plt.sunrise_glow,
      ["@punctuation.bracket"] = plt.solar_orange,
      ["@punctuation.special"] = plt.tamaran_purple,

      ["@tag"] = plt.tamaran_gold,
      ["@tag.attribute"] = plt.tamaran_purple,
      ["@tag.delimiter"] = plt.sunrise_glow,
      ["@tag.builtin"] = plt.tamaran_gold,

      ["@markup.strong"] = { fg = plt.tamaran_gold, bold = true },
      ["@markup.italic"] = { fg = plt.starfire_skin, italic = true },
      ["@markup.strikethrough"] = { fg = plt.nova_glow, strikethrough = true },
      ["@markup.underline"] = { fg = plt.radiant_heat, underline = true },
      ["@markup.heading"] = plt.tamaran_gold,
      ["@markup.heading.1"] = plt.tamaran_gold,
      ["@markup.heading.2"] = plt.solar_orange,
      ["@markup.heading.3"] = plt.starfire_skin,
      ["@markup.heading.4"] = plt.tamaran_purple,
      ["@markup.heading.5"] = plt.kori_violet,
      ["@markup.heading.6"] = plt.starbolt_green,
      ["@markup.quote"] = plt.sunrise_glow,
      ["@markup.math"] = plt.alien_radiance,
      ["@markup.link"] = plt.tamaran_purple,
      ["@markup.link.label"] = plt.nova_purple,
      ["@markup.link.url"] = plt.starbolt_green,
      ["@markup.raw"] = plt.starbolt_green,
      ["@markup.raw.block"] = plt.starbolt_green,
      ["@markup.list"] = plt.tamaran_gold,
      ["@markup.list.checked"] = plt.starbolt_green,
      ["@markup.list.unchecked"] = plt.sunrise_glow,

      ["@diff.plus"] = plt.starbolt_green,
      ["@diff.minus"] = plt.radiant_heat,
      ["@diff.delta"] = plt.tamaran_purple,

      ["@none"] = "none",
      ["@conceal"] = plt.sunrise_glow,
      ["@spell"] = plt.starfire_skin,
      ["@nospell"] = "none",

      ["@lsp.type.property.lua"] = plt.starfire_skin,
      ["@constructor.python"] = plt.tamaran_gold,
      ["@constructor.javascript"] = plt.tamaran_gold,
      ["@constructor.typescript"] = plt.tamaran_gold,
      ["@namespace.rust"] = plt.starfire_skin,
      ["@type.qualifier.rust"] = plt.tamaran_gold,
      ["@constant.macro.c"] = plt.kori_violet,
      ["@constant.macro.cpp"] = plt.kori_violet,
      ["@namespace.go"] = plt.starfire_skin,
      ["@property.css"] = plt.starbolt_green,
      ["@type.css"] = plt.tamaran_gold,
      ["@label.json"] = plt.starfire_skin,
      ["@field.yaml"] = plt.sunrise_glow,
      ["@property.toml"] = plt.sunrise_glow,
      ["@function.builtin.bash"] = plt.starbolt_green,
      ["@string.regexp"] = plt.alien_radiance,
      ["@character.special.regex"] = plt.tamaran_emerald,
    },

    lsp = {
      ["@lsp.type.class"] = plt.tamaran_purple,
      ["@lsp.type.interface"] = plt.tamaran_purple,
      ["@lsp.type.struct"] = plt.tamaran_purple,
      ["@lsp.type.enum"] = plt.tamaran_purple,
      ["@lsp.type.enumMember"] = plt.solar_orange,
      ["@lsp.type.property"] = plt.starfire_skin,
      ["@lsp.type.namespace"] = plt.starfire_skin,

      ["@lsp.type.macro"] = plt.kori_violet,
      ["@lsp.type.decorator"] = plt.tamaran_gold,

      ["@lsp.type.builtinType"] = plt.tamaran_purple,
      ["@lsp.type.selfParameter"] = plt.tamaran_gold,
      ["@lsp.type.typeParameter"] = plt.tamaran_purple,

      ["@lsp.type.array"] = plt.tamaran_purple,
      ["@lsp.type.object"] = plt.tamaran_purple,
      ["@lsp.type.key"] = plt.starfire_skin,
      ["@lsp.type.null"] = plt.solar_orange,
      ["@lsp.type.enumConstant"] = plt.solar_orange,

      ["@lsp.type.event"] = plt.tamaran_purple,
      ["@lsp.type.regexp"] = plt.alien_radiance,
      ["@lsp.type.unresolvedReference"] = plt.radiant_heat,

      ["@lsp.mod.deprecated"] = { fg = plt.nova_glow, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.solar_orange,
      ["@lsp.mod.async"] = plt.tamaran_gold,
      ["@lsp.mod.static"] = plt.tamaran_purple,
      ["@lsp.mod.abstract"] = plt.tamaran_purple,
      ["@lsp.mod.defaultLibrary"] = plt.tamaran_purple,
      ["@lsp.mod.documentation"] = plt.sunrise_glow,
    },
  }
end

return {
  name = "Starfire – Princess of Tamaran",
  author = "PrismPunk.nvim",
  description = "She came from the stars with a heart full of love and hands full of starbolts. "
    .. "Golden skin, emerald fire, violet eyes that burn brighter than any sun.",

  base16 = {
    base00 = palette.void_black,
    base01 = palette.tamaran_void,
    base02 = palette.star_core,
    base03 = palette.nova_glow,
    base04 = palette.sunrise_glow,
    base05 = palette.solar_orange,
    base06 = palette.starfire_skin,
    base07 = palette.starfire_skin,
    base08 = palette.radiant_heat,
    base09 = palette.tamaran_gold,
    base0A = palette.starbolt_green,
    base0B = palette.tamaran_emerald,
    base0C = palette.tamaran_purple,
    base0D = palette.kori_violet,
    base0E = palette.nova_purple,
    base0F = palette.alien_radiance,
  },

  palette = palette,
  get = M.get,
}
