local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0a14",
  bg_darker = "#12121e",
  bg_dark = "#1a1a28",
  bg_mid = "#222232",
  bg_light = "#2a2a3c",
  bg_lighter = "#323246",
  bg_lightest = "#3a3a50",
  bg_alt1 = "#42425a",
  bg_alt2 = "#4a4a64",
  bg_alt3 = "#52526e",
  bg_alt4 = "#5a5a78",
  fg_darkest = "#ffffff",
  fg_dark = "#f5f5ff",
  fg_mid = "#e6e6fa",
  fg_light = "#d7d7eb",
  fg_lighter = "#c8c8dc",
  fg_lightest = "#b9b9cd",
  bridgeRed = "#ff4d4d",
  flameOrange = "#ff9933",
  sunGold = "#ffdd33",
  lightYellow = "#ffff66",
  springGreen = "#99ff33",
  emeraldGreen = "#33ff33",
  aquaMint = "#33ffdd",
  skyBlue = "#33ddff",
  deepBlue = "#3399ff",
  royalBlue = "#4d88ff",
  violetPurple = "#9966ff",
  mysticMagenta = "#dd33ff",
  rosePink = "#ff33dd",
  blushPink = "#ffaadd",
  lavenderMist = "#e6e6fa",
  ashGrey = "#9ca3af",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.royalBlue,
      insert = plt.springGreen,
      visual = plt.violetPurple,
      replace = plt.bridgeRed,
      command = plt.sunGold,
    },
    accent = {
      accent1 = plt.bridgeRed,
      accent2 = plt.sunGold,
      accent3 = plt.emeraldGreen,
      accent4 = plt.skyBlue,
      accent5 = plt.violetPurple,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.bridgeRed,
      rainbow2 = plt.flameOrange,
      rainbow3 = plt.sunGold,
      rainbow4 = plt.springGreen,
      rainbow5 = plt.skyBlue,
      rainbow6 = plt.royalBlue,
      rainbow7 = plt.violetPurple,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.sunGold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.royalBlue,
      header2 = plt.violetPurple,
      special = plt.skyBlue,
      nontext = plt.bg_lighter,
      whitespace = plt.ashGrey,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.skyBlue,
      picker = plt.mysticMagenta,
      yank = plt.sunGold,
      mark = plt.violetPurple,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.ashGrey,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.skyBlue,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.skyBlue,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.ashGrey,
        fg_selected = plt.fg_light,
        fg_alternate = plt.skyBlue,
        indicator = plt.violetPurple,
      },
    },
    syn = {
      attribute = plt.rosePink,
      boolean = plt.violetPurple,
      comment = plt.ashGrey,
      constant = plt.flameOrange,
      deprecated = plt.fg_lighter,
      func = plt.royalBlue,
      identifier = plt.fg_light,
      keyword = plt.bridgeRed,
      method = plt.skyBlue,
      number = plt.violetPurple,
      operator = plt.mysticMagenta,
      parameter = plt.lavenderMist,
      preproc = plt.flameOrange,
      punct = plt.fg_lighter,
      regex = plt.rosePink,
      special = plt.aquaMint,
      special2 = plt.blushPink,
      special3 = plt.mysticMagenta,
      statement = plt.bridgeRed,
      string = plt.springGreen,
      symbol = plt.sunGold,
      type = plt.skyBlue,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.bridgeRed,
      warning = plt.sunGold,
      info = plt.skyBlue,
      ok = plt.springGreen,
      hint = plt.ashGrey,
      virtual_text_error = plt.bridgeRed,
      virtual_text_warning = plt.sunGold,
      virtual_text_info = plt.skyBlue,
      virtual_text_ok = plt.springGreen,
      virtual_text_hint = plt.ashGrey,
    },
    diff = {
      add = plt.springGreen,
      add_inline = plt.emeraldGreen,
      change = plt.skyBlue,
      change_inline = plt.aquaMint,
      delete = plt.bridgeRed,
      delete_inline = plt.bg_darker,
      text = plt.sunGold,
    },
    vcs = {
      added = plt.springGreen,
      changed = plt.skyBlue,
      removed = plt.bridgeRed,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.bridgeRed,
      green = plt.springGreen,
      yellow = plt.sunGold,
      blue = plt.royalBlue,
      magenta = plt.mysticMagenta,
      cyan = plt.skyBlue,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.bridgeRed):brighten(0.1):to_hex(),
      green_bright = color(plt.springGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.sunGold):brighten(0.1):to_hex(),
      blue_bright = color(plt.royalBlue):brighten(0.1):to_hex(),
      magenta_bright = color(plt.mysticMagenta):brighten(0.1):to_hex(),
      cyan_bright = color(plt.skyBlue):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.springGreen,
      indexed2 = plt.skyBlue,
    },
  }
end

return {
  name = "Asgard – Bifröst",
  author = "PrismPunk",
  description = "Rainbow bridge — prismatic spectrum, realm connection, shimmering arc, divine pathway. "
    .. "Bifröst is the burning rainbow bridge that connects Midgard (Earth) to Asgard, guarded by "
    .. "Heimdallr. It shimmers with all colors of the spectrum, a divine pathway between realms. "
    .. "The bridge is said to be made of fire, water, and air, and will shatter during Ragnarök when "
    .. "the sons of Múspell ride across it. This theme captures the bridge's prismatic glory — deep "
    .. "cosmic void backgrounds anchor the infinite space between realms, while the full spectrum "
    .. "blazes across the palette. Fiery reds and oranges burn at one end, golden yellows shine at "
    .. "the peak, vibrant greens pulse with life, cool blues and cyans flow like water, deep royal "
    .. "blues anchor the divine, and mystical purples and magentas shimmer with magic. The rainbow "
    .. "bridge connects all realms, all colors, all possibilities.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.ashGrey,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.bridgeRed,
    base09 = palette.flameOrange,
    base0A = palette.sunGold,
    base0B = palette.springGreen,
    base0C = palette.skyBlue,
    base0D = palette.royalBlue,
    base0E = palette.violetPurple,
    base0F = palette.mysticMagenta,
  },
  palette = palette,
  get = M.get,
}
