local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1a00",
  bg_darker = "#333300",
  bg_dark = "#4d4d00",
  bg_mid = "#666600",
  bg_light = "#808000",
  bg_lighter = "#999900",
  bg_lightest = "#b3b300",
  bg_alt1 = "#cccc00",
  bg_alt2 = "#e6e600",
  bg_alt3 = "#ffff00",
  bg_alt4 = "#ffff33",
  fg_darkest = "#99ccff",
  fg_dark = "#cce6ff",
  fg_mid = "#e6f5ff",
  fg_light = "#f5faff",
  fg_lighter = "#ffffff",
  fg_lightest = "#ffffff",
  regalGold = "#ffff66",
  queenlyRadiance = "#ffff99",
  maternalWarmth = "#ffffcc",
  foresightSilver = "#66b3ff",
  skyThrone = "#0080ff",
  wisdomBlue = "#3399ff",
  protectiveGaze = "#0066cc",
  destinyWeave = "#004d99",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.skyThrone,
      insert = plt.regalGold,
      visual = plt.wisdomBlue,
      replace = plt.maternalWarmth,
      command = plt.foresightSilver,
    },
    accent = {
      accent1 = plt.skyThrone,
      accent2 = plt.regalGold,
      accent3 = plt.foresightSilver,
      accent4 = plt.wisdomBlue,
      accent5 = plt.maternalWarmth,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.regalGold,
      rainbow2 = plt.queenlyRadiance,
      rainbow3 = plt.maternalWarmth,
      rainbow4 = plt.skyThrone,
      rainbow5 = plt.wisdomBlue,
      rainbow6 = plt.foresightSilver,
      rainbow7 = plt.fg_lightest,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_lighter,
      fg_dimmer = plt.fg_light,
      fg_dark = plt.fg_mid,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.skyThrone,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.skyThrone,
      header2 = plt.regalGold,
      special = plt.foresightSilver,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.wisdomBlue,
      indent = plt.bg_light,
      indent_scope = plt.skyThrone,
      picker = plt.regalGold,
      yank = plt.foresightSilver,
      mark = plt.maternalWarmth,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_dark,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.skyThrone,
        indicator = plt.regalGold,
      },
    },
    syn = {
      attribute = plt.regalGold,
      boolean = plt.maternalWarmth,
      comment = plt.bg_alt1,
      constant = plt.queenlyRadiance,
      deprecated = plt.bg_alt2,
      func = plt.skyThrone,
      identifier = plt.fg_light,
      keyword = plt.wisdomBlue,
      method = plt.skyThrone,
      number = plt.queenlyRadiance,
      operator = plt.foresightSilver,
      parameter = plt.regalGold,
      preproc = plt.protectiveGaze,
      punct = plt.fg_mid,
      regex = plt.destinyWeave,
      special = plt.foresightSilver,
      special2 = plt.wisdomBlue,
      special3 = plt.maternalWarmth,
      statement = plt.wisdomBlue,
      string = plt.regalGold,
      symbol = plt.skyThrone,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.maternalWarmth,
      warning = plt.queenlyRadiance,
      info = plt.skyThrone,
      ok = plt.foresightSilver,
      hint = plt.wisdomBlue,
      virtual_text_error = plt.maternalWarmth,
      virtual_text_warning = plt.queenlyRadiance,
      virtual_text_info = plt.skyThrone,
      virtual_text_ok = plt.foresightSilver,
      virtual_text_hint = plt.wisdomBlue,
    },
    diff = {
      add = plt.regalGold,
      add_inline = plt.queenlyRadiance,
      change = plt.skyThrone,
      change_inline = plt.wisdomBlue,
      delete = plt.maternalWarmth,
      delete_inline = plt.queenlyRadiance,
      text = plt.foresightSilver,
    },
    vcs = {
      added = plt.regalGold,
      changed = plt.skyThrone,
      removed = plt.maternalWarmth,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.maternalWarmth,
      green = plt.regalGold,
      yellow = plt.queenlyRadiance,
      blue = plt.skyThrone,
      magenta = plt.wisdomBlue,
      cyan = plt.foresightSilver,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.maternalWarmth):brighten(0.15):to_hex(),
      green_bright = color(plt.regalGold):brighten(0.15):to_hex(),
      yellow_bright = color(plt.queenlyRadiance):brighten(0.15):to_hex(),
      blue_bright = color(plt.skyThrone):brighten(0.15):to_hex(),
      magenta_bright = color(plt.wisdomBlue):brighten(0.2):to_hex(),
      cyan_bright = color(plt.foresightSilver):brighten(0.15):to_hex(),
      white_bright = plt.fg_lightest,
      indexed1 = plt.protectiveGaze,
      indexed2 = plt.destinyWeave,
    },
  }
end

return {
  name = "Asgard – Frigg",
  author = "PrismPunk",
  description = "Queen of Asgard — regal golds, sky blues, maternal warmth, foresight silver. "
    .. "Frigg is the wife of Óðinn and the highest of the goddesses, queen of Asgard "
    .. "and mistress of Fensalir. She knows the fate of all beings but speaks of it to "
    .. "none. As the goddess of marriage, motherhood, and domestic arts, she weaves the "
    .. "clouds and spins the threads of destiny. Her wisdom rivals even Óðinn's, though "
    .. "she keeps her counsel. She sees all that will come to pass, including the death "
    .. "of her beloved son Baldr, yet even her foresight cannot change what is written. "
    .. "This palette weaves regal golds from deep olive through brilliant yellow into "
    .. "the sky blues of her domain — from deep ocean to the palest cloud-silver, "
    .. "reflecting both her queenly authority and her maternal grace.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.maternalWarmth,
    base09 = palette.queenlyRadiance,
    base0A = palette.regalGold,
    base0B = palette.regalGold,
    base0C = palette.foresightSilver,
    base0D = palette.skyThrone,
    base0E = palette.wisdomBlue,
    base0F = palette.protectiveGaze,
  },
  palette = palette,
  get = M.get,
}
