local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0d0a08",
  bg_darker = "#1a1410",
  bg_dark = "#2a2118",
  bg_mid = "#3a2e20",
  bg_light = "#4a3b28",
  bg_lighter = "#5a4830",
  bg_lightest = "#6a5538",
  bg_alt1 = "#7a6240",
  bg_alt2 = "#8a6f48",
  bg_alt3 = "#9a7c50",
  bg_alt4 = "#aa8958",
  fg_darkest = "#fff8e7",
  fg_dark = "#f5ead5",
  fg_mid = "#ebdcc3",
  fg_light = "#e1ceb1",
  fg_lighter = "#d7c09f",
  fg_lightest = "#cdb28d",
  ashWood = "#8b6f47",
  worldTreeGrain = "#a0845a",
  runeCarved = "#b5996d",
  oathBronze = "#d4a574",
  spearTip = "#e8b86d",
  neverMiss = "#ffd700",
  allFatherGold = "#ffcc33",
  fateStrike = "#ff9900",
  battleOath = "#cc7722",
  wisdomAmber = "#aa6611",
  sacrificeRed = "#8b3a3a",
  yggdrasilGreen = "#4a7c59",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.neverMiss,
      insert = plt.yggdrasilGreen,
      visual = plt.oathBronze,
      replace = plt.sacrificeRed,
      command = plt.allFatherGold,
    },
    accent = {
      accent1 = plt.neverMiss,
      accent2 = plt.allFatherGold,
      accent3 = plt.oathBronze,
      accent4 = plt.yggdrasilGreen,
      accent5 = plt.fateStrike,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.neverMiss,
      rainbow2 = plt.fateStrike,
      rainbow3 = plt.battleOath,
      rainbow4 = plt.oathBronze,
      rainbow5 = plt.yggdrasilGreen,
      rainbow6 = plt.sacrificeRed,
      rainbow7 = plt.wisdomAmber,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.neverMiss,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.neverMiss,
      header2 = plt.allFatherGold,
      special = plt.oathBronze,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.neverMiss,
      picker = plt.allFatherGold,
      yank = plt.oathBronze,
      mark = plt.fateStrike,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.neverMiss,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.neverMiss,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.neverMiss,
        indicator = plt.allFatherGold,
      },
    },
    syn = {
      attribute = plt.allFatherGold,
      boolean = plt.oathBronze,
      comment = plt.ashWood,
      constant = plt.neverMiss,
      deprecated = plt.fg_lighter,
      func = plt.fateStrike,
      identifier = plt.fg_light,
      keyword = plt.battleOath,
      method = plt.spearTip,
      number = plt.yggdrasilGreen,
      operator = plt.oathBronze,
      parameter = plt.runeCarved,
      preproc = plt.wisdomAmber,
      punct = plt.fg_lighter,
      regex = plt.worldTreeGrain,
      special = plt.neverMiss,
      special2 = plt.allFatherGold,
      special3 = plt.yggdrasilGreen,
      statement = plt.battleOath,
      string = plt.yggdrasilGreen,
      symbol = plt.fateStrike,
      type = plt.spearTip,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.sacrificeRed,
      warning = plt.fateStrike,
      info = plt.neverMiss,
      ok = plt.yggdrasilGreen,
      hint = plt.ashWood,
      virtual_text_error = plt.sacrificeRed,
      virtual_text_warning = plt.fateStrike,
      virtual_text_info = plt.neverMiss,
      virtual_text_ok = plt.yggdrasilGreen,
      virtual_text_hint = plt.ashWood,
    },
    diff = {
      add = plt.yggdrasilGreen,
      add_inline = plt.worldTreeGrain,
      change = plt.allFatherGold,
      change_inline = plt.spearTip,
      delete = plt.sacrificeRed,
      delete_inline = plt.bg_darker,
      text = plt.neverMiss,
    },
    vcs = {
      added = plt.yggdrasilGreen,
      changed = plt.allFatherGold,
      removed = plt.sacrificeRed,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.sacrificeRed,
      green = plt.yggdrasilGreen,
      yellow = plt.neverMiss,
      blue = plt.spearTip,
      magenta = plt.battleOath,
      cyan = plt.allFatherGold,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.sacrificeRed):brighten(0.15):to_hex(),
      green_bright = color(plt.yggdrasilGreen):brighten(0.15):to_hex(),
      yellow_bright = color(plt.neverMiss):brighten(0.1):to_hex(),
      blue_bright = color(plt.spearTip):brighten(0.1):to_hex(),
      magenta_bright = color(plt.battleOath):brighten(0.15):to_hex(),
      cyan_bright = color(plt.allFatherGold):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.neverMiss,
      indexed2 = plt.allFatherGold,
    },
  }
end

return {
  name = "Asgard – Gungnir",
  author = "PrismPunk",
  description = "Odin's spear — ash wood browns, oath-binder bronze, rune-carved shaft. "
    .. "Gungnir, forged by the sons of Ivaldi, never misses its mark. Carved from Yggdrasil's ash, "
    .. "tipped with bronze that binds oaths, etched with runes of fate and sacrifice. This theme "
    .. "captures the spear's essence: warm earth browns for ancient wood, brilliant golds for the "
    .. "never-missing strike, deep greens from the World Tree, sacrifice reds from Odin's eye, "
    .. "and bronze ambers for oaths sworn upon its shaft. Where wisdom meets war, where every throw "
    .. "shapes destiny, where the All-Father's will pierces through the veil of fate itself.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.sacrificeRed,
    base09 = palette.fateStrike,
    base0A = palette.neverMiss,
    base0B = palette.yggdrasilGreen,
    base0C = palette.allFatherGold,
    base0D = palette.spearTip,
    base0E = palette.battleOath,
    base0F = palette.wisdomAmber,
  },
  palette = palette,
  get = M.get,
}
