local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#000000",
  bg_darker = "#0d0d0d",
  bg_dark = "#1a1a1a",
  bg_mid = "#262626",
  bg_light = "#333333",
  bg_lighter = "#404040",
  bg_lightest = "#4d4d4d",
  bg_alt1 = "#595959",
  bg_alt2 = "#666666",
  bg_alt3 = "#737373",
  bg_alt4 = "#808080",
  fg_darkest = "#ffffff",
  fg_dark = "#bfbfbf",
  fg_mid = "#b3b3b3",
  fg_light = "#a6a6a6",
  fg_lighter = "#999999",
  fg_lightest = "#8c8c8c",
  voidDepth = "#1c1c1c",
  shadowEdge = "#2e2e2e",
  blindness = "#404040",
  manipulation = "#525252",
  unseeing = "#646464",
  darkness = "#767676",
  greyVeil = "#888888",
  mistletoeShadow = "#9a9a9a",
  tragicFate = "#acacac",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.greyVeil,
      insert = plt.mistletoeShadow,
      visual = plt.darkness,
      replace = plt.manipulation,
      command = plt.tragicFate,
    },
    accent = {
      accent1 = plt.greyVeil,
      accent2 = plt.mistletoeShadow,
      accent3 = plt.darkness,
      accent4 = plt.manipulation,
      accent5 = plt.unseeing,
      invert = plt.fg_darkest,
    },
    rainbow = {
      rainbow1 = plt.greyVeil,
      rainbow2 = plt.mistletoeShadow,
      rainbow3 = plt.darkness,
      rainbow4 = plt.manipulation,
      rainbow5 = plt.unseeing,
      rainbow6 = plt.shadowEdge,
      rainbow7 = plt.tragicFate,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.mistletoeShadow,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.greyVeil,
      header2 = plt.mistletoeShadow,
      special = plt.darkness,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.manipulation,
      indent = plt.bg_light,
      indent_scope = plt.unseeing,
      picker = plt.darkness,
      yank = plt.mistletoeShadow,
      mark = plt.greyVeil,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.tragicFate,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.darkness,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.unseeing,
        indicator = plt.mistletoeShadow,
      },
    },
    syn = {
      attribute = plt.darkness,
      boolean = plt.greyVeil,
      comment = plt.shadowEdge,
      constant = plt.mistletoeShadow,
      deprecated = plt.bg_alt3,
      func = plt.greyVeil,
      identifier = plt.fg_light,
      keyword = plt.darkness,
      method = plt.greyVeil,
      number = plt.mistletoeShadow,
      operator = plt.manipulation,
      parameter = plt.fg_mid,
      preproc = plt.unseeing,
      punct = plt.voidDepth,
      regex = plt.tragicFate,
      special = plt.tragicFate,
      special2 = plt.blindness,
      special3 = plt.fg_darkest,
      statement = plt.darkness,
      string = plt.mistletoeShadow,
      symbol = plt.unseeing,
      type = plt.darkness,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.manipulation,
      warning = plt.mistletoeShadow,
      info = plt.darkness,
      ok = plt.greyVeil,
      hint = plt.shadowEdge,
      virtual_text_error = plt.manipulation,
      virtual_text_warning = plt.mistletoeShadow,
      virtual_text_info = plt.darkness,
      virtual_text_ok = plt.greyVeil,
      virtual_text_hint = plt.shadowEdge,
    },
    diff = {
      add = plt.greyVeil,
      add_inline = plt.darkness,
      change = plt.mistletoeShadow,
      change_inline = plt.tragicFate,
      delete = plt.manipulation,
      delete_inline = plt.voidDepth,
      text = plt.greyVeil,
    },
    vcs = {
      added = plt.greyVeil,
      changed = plt.mistletoeShadow,
      removed = plt.manipulation,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.manipulation,
      green = plt.greyVeil,
      yellow = plt.mistletoeShadow,
      blue = plt.darkness,
      magenta = plt.unseeing,
      cyan = plt.tragicFate,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.manipulation):brighten(0.1):to_hex(),
      green_bright = color(plt.greyVeil):brighten(0.1):to_hex(),
      yellow_bright = color(plt.mistletoeShadow):brighten(0.1):to_hex(),
      blue_bright = color(plt.darkness):brighten(0.2):to_hex(),
      magenta_bright = color(plt.unseeing):brighten(0.2):to_hex(),
      cyan_bright = color(plt.tragicFate):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.shadowEdge,
      indexed2 = plt.voidDepth,
    },
  }
end

return {
  name = "Asgard – Höðr",
  author = "PrismPunk",
  description = "Blind God — shadow blacks, mistletoe's darkness, tragic manipulation, sightless void. "
    .. "Höðr is the blind god, manipulated by Loki into killing his brother Baldr with a dart of "
    .. "mistletoe. He dwells in eternal darkness, unable to see the beauty of Asgard or the tragedy "
    .. "he was tricked into causing. This monochromatic palette moves through pure blacks to bright "
    .. "whites, representing the spectrum of shadow and light that Höðr cannot perceive. Deep voids "
    .. "form the background, while grey veils and mistletoe shadows provide subtle contrast. The theme "
    .. "captures the tragedy of blindness, the manipulation of innocence, and the darkness of fate.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.manipulation,
    base09 = palette.mistletoeShadow,
    base0A = palette.tragicFate,
    base0B = palette.mistletoeShadow,
    base0C = palette.darkness,
    base0D = palette.darkness,
    base0E = palette.greyVeil,
    base0F = palette.shadowEdge,
  },
  palette = palette,
  get = M.get,
}
