local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0d0805",
  bg_darker = "#1a100a",
  bg_dark = "#271810",
  bg_mid = "#342016",
  bg_light = "#41281c",
  bg_lighter = "#4e3022",
  bg_lightest = "#5b3828",
  bg_alt1 = "#68402e",
  bg_alt2 = "#754834",
  bg_alt3 = "#82503a",
  bg_alt4 = "#8f5840",
  fg_darkest = "#faf5ed",
  fg_dark = "#f0e9d9",
  fg_mid = "#e6ddc5",
  fg_light = "#dcd1b1",
  fg_lighter = "#d2c59d",
  fg_lightest = "#c8b989",
  oakHull = "#8b5a3c",
  vesselDeck = "#a67c5d",
  shipTimber = "#c19a7e",
  sacredWood = "#9d6b4a",
  funeralFlame = "#ff6b35",
  pyreOrange = "#ff8c42",
  emberGlow = "#ffa85c",
  ashRising = "#cc7a4d",
  baldrGold = "#ffcc66",
  innocenceLost = "#ffe699",
  godlyRadiance = "#ffd480",
  griefBlue = "#5a7a99",
  nannasTears = "#7a9ab8",
  mistletoeGreen = "#4a7c59",
  helShadow = "#3d2a1f",
  deathClaim = "#8b3a3a",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.baldrGold,
      insert = plt.mistletoeGreen,
      visual = plt.funeralFlame,
      replace = plt.deathClaim,
      command = plt.godlyRadiance,
    },
    accent = {
      accent1 = plt.baldrGold,
      accent2 = plt.funeralFlame,
      accent3 = plt.oakHull,
      accent4 = plt.mistletoeGreen,
      accent5 = plt.griefBlue,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.baldrGold,
      rainbow2 = plt.funeralFlame,
      rainbow3 = plt.pyreOrange,
      rainbow4 = plt.oakHull,
      rainbow5 = plt.mistletoeGreen,
      rainbow6 = plt.griefBlue,
      rainbow7 = plt.deathClaim,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.baldrGold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.baldrGold,
      header2 = plt.funeralFlame,
      special = plt.oakHull,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.baldrGold,
      picker = plt.godlyRadiance,
      yank = plt.funeralFlame,
      mark = plt.pyreOrange,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.baldrGold,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.baldrGold,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.baldrGold,
        indicator = plt.funeralFlame,
      },
    },
    syn = {
      attribute = plt.godlyRadiance,
      boolean = plt.pyreOrange,
      comment = plt.griefBlue,
      constant = plt.baldrGold,
      deprecated = plt.fg_lighter,
      func = plt.funeralFlame,
      identifier = plt.fg_light,
      keyword = plt.oakHull,
      method = plt.emberGlow,
      number = plt.nannasTears,
      operator = plt.shipTimber,
      parameter = plt.vesselDeck,
      preproc = plt.ashRising,
      punct = plt.fg_lighter,
      regex = plt.mistletoeGreen,
      special = plt.baldrGold,
      special2 = plt.innocenceLost,
      special3 = plt.nannasTears,
      statement = plt.oakHull,
      string = plt.mistletoeGreen,
      symbol = plt.funeralFlame,
      type = plt.sacredWood,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.deathClaim,
      warning = plt.funeralFlame,
      info = plt.nannasTears,
      ok = plt.mistletoeGreen,
      hint = plt.griefBlue,
      virtual_text_error = plt.deathClaim,
      virtual_text_warning = plt.funeralFlame,
      virtual_text_info = plt.nannasTears,
      virtual_text_ok = plt.mistletoeGreen,
      virtual_text_hint = plt.griefBlue,
    },
    diff = {
      add = plt.mistletoeGreen,
      add_inline = plt.nannasTears,
      change = plt.baldrGold,
      change_inline = plt.godlyRadiance,
      delete = plt.deathClaim,
      delete_inline = plt.bg_darker,
      text = plt.baldrGold,
    },
    vcs = {
      added = plt.mistletoeGreen,
      changed = plt.baldrGold,
      removed = plt.deathClaim,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.deathClaim,
      green = plt.mistletoeGreen,
      yellow = plt.baldrGold,
      blue = plt.nannasTears,
      magenta = plt.funeralFlame,
      cyan = plt.griefBlue,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.deathClaim):brighten(0.15):to_hex(),
      green_bright = color(plt.mistletoeGreen):brighten(0.15):to_hex(),
      yellow_bright = color(plt.baldrGold):brighten(0.1):to_hex(),
      blue_bright = color(plt.nannasTears):brighten(0.15):to_hex(),
      magenta_bright = color(plt.funeralFlame):brighten(0.15):to_hex(),
      cyan_bright = color(plt.griefBlue):brighten(0.15):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.baldrGold,
      indexed2 = plt.funeralFlame,
    },
  }
end

return {
  name = "Asgard – Hringhorni",
  author = "PrismPunk",
  description = "Baldr's ship — funeral pyre, greatest vessel, tragic voyage. "
    .. "Hringhorni, the greatest of all ships, became Baldr's funeral pyre. The most beautiful god, "
    .. "beloved by all, struck down by Loki's treachery and a mistletoe dart. His wife Nanna died "
    .. "of grief and joined him on the pyre. This theme captures Norse mythology's most tragic moment: "
    .. "warm oak browns for the sacred vessel, funeral flame oranges consuming the greatest ship, "
    .. "Baldr's golden radiance fading into ash, grief blues for Nanna's tears and the weeping gods, "
    .. "mistletoe green for the innocent weapon, and death's crimson for Hel's claim. The voyage "
    .. "to the underworld, pushed out to sea ablaze, marking the beginning of Ragnarök's inevitability.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.deathClaim,
    base09 = palette.funeralFlame,
    base0A = palette.baldrGold,
    base0B = palette.mistletoeGreen,
    base0C = palette.nannasTears,
    base0D = palette.griefBlue,
    base0E = palette.oakHull,
    base0F = palette.pyreOrange,
  },
  palette = palette,
  get = M.get,
}
