local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a0f00",
  bg_darker = "#331f00",
  bg_dark = "#4d2e00",
  bg_mid = "#663d00",
  bg_light = "#804d00",
  bg_lighter = "#995c00",
  bg_lightest = "#b36b00",
  bg_alt1 = "#cc7a00",
  bg_alt2 = "#e68a00",
  bg_alt3 = "#ff9900",
  bg_alt4 = "#ffa619",
  fg_darkest = "#ffffff",
  fg_dark = "#fffbf7",
  fg_mid = "#fff6ef",
  fg_light = "#fdeddf",
  fg_lighter = "#f9e3cf",
  fg_lightest = "#f5d9bf",
  bronzeArmor = "#d4a574",
  battlefieldSteel = "#a8b8c8",
  bloodOath = "#ff4444",
  valhallaSky = "#6ba3d4",
  shieldBoss = "#d8d8d8",
  fateThread = "#f4c542",
  chosenSoul = "#e8e8ff",
  spearTip = "#5a7a7a",
  honorBound = "#e6b800",
  protectiveWard = "#5a9ee6",
  divineChoice = "#ffd700",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.valhallaSky,
      insert = plt.bronzeArmor,
      visual = plt.bloodOath,
      replace = plt.fateThread,
      command = plt.shieldBoss,
    },
    accent = {
      accent1 = plt.valhallaSky,
      accent2 = plt.bronzeArmor,
      accent3 = plt.bloodOath,
      accent4 = plt.fateThread,
      accent5 = plt.shieldBoss,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.valhallaSky,
      rainbow2 = plt.protectiveWard,
      rainbow3 = plt.bronzeArmor,
      rainbow4 = plt.fateThread,
      rainbow5 = plt.bloodOath,
      rainbow6 = plt.shieldBoss,
      rainbow7 = plt.battlefieldSteel,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.bloodOath,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.valhallaSky,
      header2 = plt.bronzeArmor,
      special = plt.bloodOath,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.valhallaSky,
      picker = plt.bronzeArmor,
      yank = plt.bloodOath,
      mark = plt.fateThread,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.valhallaSky,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.valhallaSky,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.valhallaSky,
        indicator = plt.bronzeArmor,
      },
    },
    syn = {
      attribute = plt.bronzeArmor,
      boolean = plt.bloodOath,
      comment = plt.bg_lightest,
      constant = plt.valhallaSky,
      deprecated = plt.fg_lighter,
      func = plt.valhallaSky,
      identifier = plt.fg_light,
      keyword = plt.bloodOath,
      method = plt.bronzeArmor,
      number = plt.fateThread,
      operator = plt.shieldBoss,
      parameter = plt.chosenSoul,
      preproc = plt.protectiveWard,
      punct = plt.fg_lighter,
      regex = plt.bronzeArmor,
      special = plt.bloodOath,
      special2 = plt.fateThread,
      special3 = plt.divineChoice,
      statement = plt.bloodOath,
      string = plt.bronzeArmor,
      symbol = plt.valhallaSky,
      type = plt.protectiveWard,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.bloodOath,
      warning = plt.fateThread,
      info = plt.valhallaSky,
      ok = plt.bronzeArmor,
      hint = plt.bg_lightest,
      virtual_text_error = plt.bloodOath,
      virtual_text_warning = plt.fateThread,
      virtual_text_info = plt.valhallaSky,
      virtual_text_ok = plt.bronzeArmor,
      virtual_text_hint = plt.bg_lightest,
    },
    diff = {
      add = plt.bronzeArmor,
      add_inline = plt.valhallaSky,
      change = plt.fateThread,
      change_inline = plt.protectiveWard,
      delete = plt.bloodOath,
      delete_inline = plt.bg_darker,
      text = plt.shieldBoss,
    },
    vcs = {
      added = plt.bronzeArmor,
      changed = plt.fateThread,
      removed = plt.bloodOath,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.bloodOath,
      green = plt.bronzeArmor,
      yellow = plt.fateThread,
      blue = plt.valhallaSky,
      magenta = plt.chosenSoul,
      cyan = plt.protectiveWard,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.bloodOath):brighten(0.1):to_hex(),
      green_bright = color(plt.bronzeArmor):brighten(0.1):to_hex(),
      yellow_bright = color(plt.fateThread):brighten(0.1):to_hex(),
      blue_bright = color(plt.valhallaSky):brighten(0.1):to_hex(),
      magenta_bright = color(plt.chosenSoul):brighten(0.1):to_hex(),
      cyan_bright = color(plt.protectiveWard):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.valhallaSky,
      indexed2 = plt.bronzeArmor,
    },
  }
end

return {
  name = "Asgard – Kára",
  author = "PrismPunk",
  description = "Battle chooser — Valhalla's sky blue, bronze armor, blood oath crimson, fate's gold. "
    .. "Kára chooses the slain on the battlefield, guiding worthy warriors to Valhalla's halls. "
    .. "This theme captures the moment of divine choice: deep sky blue for Valhalla's eternal realm, "
    .. "bronze for protective armor, deep crimson for blood oaths and sacrifice, silver for shields, "
    .. "and gold for the threads of fate she weaves. The battlefield at dusk — where steel meets sky, "
    .. "honor meets destiny, and the chosen rise to glory.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.bloodOath,
    base09 = palette.fateThread,
    base0A = palette.divineChoice,
    base0B = palette.bronzeArmor,
    base0C = palette.valhallaSky,
    base0D = palette.protectiveWard,
    base0E = palette.shieldBoss,
    base0F = palette.chosenSoul,
  },
  palette = palette,
  get = M.get,
}
