local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0a14",
  bg_darker = "#14141e",
  bg_dark = "#1e1e28",
  bg_mid = "#282832",
  bg_light = "#32323c",
  bg_lighter = "#3c3c46",
  bg_lightest = "#464650",
  bg_alt1 = "#50505a",
  bg_alt2 = "#5a5a64",
  bg_alt3 = "#64646e",
  bg_alt4 = "#6e6e78",
  fg_darkest = "#ffffff",
  fg_dark = "#fefefe",
  fg_mid = "#fcfcfc",
  fg_light = "#f8f8f8",
  fg_lighter = "#f0f0f0",
  fg_lightest = "#e0e0e0",
  lightningStrike = "#e0f4ff",
  stormSilver = "#c0d8e8",
  hammerSteel = "#a8b8c8",
  giantCrusher = "#8c9cac",
  thunderForge = "#5a7fa8",
  consecrationBlue = "#4169e1",
  stormCore = "#3a5fcc",
  mjollnirGlow = "#d0e8ff",
  ironWill = "#708090",
  runeEtched = "#b0c4de",
  worthyMetal = "#c0c0c0",
  divineStrike = "#87ceeb",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.consecrationBlue,
      insert = plt.lightningStrike,
      visual = plt.hammerSteel,
      replace = plt.thunderForge,
      command = plt.worthyMetal,
    },
    accent = {
      accent1 = plt.consecrationBlue,
      accent2 = plt.lightningStrike,
      accent3 = plt.hammerSteel,
      accent4 = plt.thunderForge,
      accent5 = plt.worthyMetal,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.consecrationBlue,
      rainbow2 = plt.thunderForge,
      rainbow3 = plt.hammerSteel,
      rainbow4 = plt.stormSilver,
      rainbow5 = plt.lightningStrike,
      rainbow6 = plt.divineStrike,
      rainbow7 = plt.worthyMetal,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.lightningStrike,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.consecrationBlue,
      header2 = plt.lightningStrike,
      special = plt.hammerSteel,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.consecrationBlue,
      picker = plt.lightningStrike,
      yank = plt.hammerSteel,
      mark = plt.thunderForge,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.consecrationBlue,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.consecrationBlue,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.consecrationBlue,
        indicator = plt.lightningStrike,
      },
    },
    syn = {
      attribute = plt.lightningStrike,
      boolean = plt.hammerSteel,
      comment = plt.ironWill,
      constant = plt.consecrationBlue,
      deprecated = plt.fg_lighter,
      func = plt.consecrationBlue,
      identifier = plt.fg_light,
      keyword = plt.thunderForge,
      method = plt.stormCore,
      number = plt.divineStrike,
      operator = plt.worthyMetal,
      parameter = plt.runeEtched,
      preproc = plt.giantCrusher,
      punct = plt.fg_lighter,
      regex = plt.mjollnirGlow,
      special = plt.lightningStrike,
      special2 = plt.stormSilver,
      special3 = plt.hammerSteel,
      statement = plt.thunderForge,
      string = plt.lightningStrike,
      symbol = plt.consecrationBlue,
      type = plt.stormCore,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.thunderForge,
      warning = plt.divineStrike,
      info = plt.consecrationBlue,
      ok = plt.worthyMetal,
      hint = plt.ironWill,
      virtual_text_error = plt.thunderForge,
      virtual_text_warning = plt.divineStrike,
      virtual_text_info = plt.consecrationBlue,
      virtual_text_ok = plt.worthyMetal,
      virtual_text_hint = plt.ironWill,
    },
    diff = {
      add = plt.worthyMetal,
      add_inline = plt.stormSilver,
      change = plt.lightningStrike,
      change_inline = plt.divineStrike,
      delete = plt.thunderForge,
      delete_inline = plt.bg_darker,
      text = plt.mjollnirGlow,
    },
    vcs = {
      added = plt.worthyMetal,
      changed = plt.lightningStrike,
      removed = plt.thunderForge,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.thunderForge,
      green = plt.worthyMetal,
      yellow = plt.divineStrike,
      blue = plt.consecrationBlue,
      magenta = plt.stormCore,
      cyan = plt.lightningStrike,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.thunderForge):brighten(0.1):to_hex(),
      green_bright = color(plt.worthyMetal):brighten(0.1):to_hex(),
      yellow_bright = color(plt.divineStrike):brighten(0.1):to_hex(),
      blue_bright = color(plt.consecrationBlue):brighten(0.15):to_hex(),
      magenta_bright = color(plt.stormCore):brighten(0.1):to_hex(),
      cyan_bright = color(plt.lightningStrike):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.consecrationBlue,
      indexed2 = plt.lightningStrike,
    },
  }
end

return {
  name = "Asgard – Mjölnir",
  author = "PrismPunk",
  description = "Thor's hammer — lightning silver, giant-crusher steel, consecration iron. "
    .. "Mjölnir, forged by dwarven smiths in the heart of a dying star, returns always to Thor's hand. "
    .. "This theme captures the hammer's essence: deep storm blues for the thunder god's power, "
    .. "brilliant lightning whites for the strike that splits mountains, consecration blues for the "
    .. "sacred runes etched into its surface, and steel silvers for the metal that crushes giants. "
    .. "Only the worthy may lift it — where divine storm meets unbreakable iron, where lightning "
    .. "becomes weapon, where Thor's will is made manifest in metal and thunder.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.thunderForge,
    base09 = palette.divineStrike,
    base0A = palette.lightningStrike,
    base0B = palette.worthyMetal,
    base0C = palette.mjollnirGlow,
    base0D = palette.consecrationBlue,
    base0E = palette.stormCore,
    base0F = palette.ironWill,
  },
  palette = palette,
  get = M.get,
}
