local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#000000",
  bg_darker = "#0a0a14",
  bg_dark = "#12121f",
  bg_mid = "#1a1a2b",
  bg_light = "#222238",
  bg_lighter = "#2a2a45",
  bg_lightest = "#323252",
  bg_alt1 = "#3a3a5f",
  bg_alt2 = "#42426c",
  bg_alt3 = "#4a4a79",
  bg_alt4 = "#525286",
  fg_darkest = "#e6e6ff",
  fg_dark = "#c9c9e6",
  fg_mid = "#adadcc",
  fg_light = "#9090b3",
  fg_lighter = "#747499",
  fg_lightest = "#585880",
  ravenBlack = "#0d0d1a",
  ravenWing = "#1a1a33",
  twilightDepth = "#252547",
  mysticPurple = "#4a4a7a",
  runicBlue = "#6b6bcc",
  runicGlow = "#7d7de6",
  runicFlare = "#9090ff",
  arcaneGlow = "#8585d9",
  huginn = "#9999e6",
  muninn = "#9999e6",
  mimirWell = "#7a7acc",
  yggdrasilAsh = "#4d4d66",
  gungnirTip = "#b8b8d4",
  divineGold = "#ccaa66",
  paleWisdom = "#d4c299",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.runicBlue,
      insert = plt.runicGlow,
      visual = plt.mysticPurple,
      replace = plt.divineGold,
      command = plt.runicFlare,
    },
    accent = {
      accent1 = plt.runicBlue,
      accent2 = plt.runicGlow,
      accent3 = plt.mysticPurple,
      accent4 = plt.divineGold,
      accent5 = plt.runicFlare,
      invert = plt.fg_darkest,
    },
    rainbow = {
      rainbow1 = plt.runicBlue,
      rainbow2 = plt.runicGlow,
      rainbow3 = plt.runicFlare,
      rainbow4 = plt.mysticPurple,
      rainbow5 = plt.arcaneGlow,
      rainbow6 = plt.mimirWell,
      rainbow7 = plt.divineGold,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.ravenWing or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.mysticPurple,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.twilightDepth,
      header1 = plt.runicGlow,
      header2 = plt.runicFlare,
      special = plt.divineGold,
      nontext = plt.bg_lighter,
      whitespace = plt.yggdrasilAsh,
      win_separator = plt.twilightDepth,
      indent = plt.bg_light,
      indent_scope = plt.runicBlue,
      picker = plt.runicGlow,
      yank = plt.runicFlare,
      mark = plt.divineGold,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.yggdrasilAsh,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.runicBlue,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.runicBlue,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.twilightDepth,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.yggdrasilAsh,
        fg_selected = plt.fg_light,
        fg_alternate = plt.runicBlue,
        indicator = plt.runicGlow,
      },
    },
    syn = {
      attribute = plt.runicFlare,
      boolean = plt.divineGold,
      comment = plt.yggdrasilAsh,
      constant = plt.muninn,
      deprecated = plt.fg_lighter,
      func = plt.runicGlow,
      identifier = plt.fg_light,
      keyword = plt.runicBlue,
      method = plt.runicGlow,
      number = plt.paleWisdom,
      operator = plt.mimirWell,
      parameter = plt.fg_mid,
      preproc = plt.mysticPurple,
      punct = plt.gungnirTip,
      regex = plt.runicFlare,
      special = plt.divineGold,
      special2 = plt.muninn,
      special3 = plt.paleWisdom,
      statement = plt.runicBlue,
      string = plt.muninn,
      symbol = plt.mysticPurple,
      type = plt.arcaneGlow,
      variable = plt.fg_light,
      annotation = plt.runicFlare,
    },
    diag = {
      error = plt.divineGold,
      warning = plt.paleWisdom,
      info = plt.runicGlow,
      ok = plt.arcaneGlow,
      hint = plt.yggdrasilAsh,
      virtual_text_error = plt.divineGold,
      virtual_text_warning = plt.paleWisdom,
      virtual_text_info = plt.runicGlow,
      virtual_text_ok = plt.arcaneGlow,
      virtual_text_hint = plt.yggdrasilAsh,
    },
    diff = {
      add = plt.arcaneGlow,
      add_inline = plt.runicGlow,
      change = plt.muninn,
      change_inline = plt.mysticPurple,
      delete = plt.divineGold,
      delete_inline = plt.ravenBlack,
      text = plt.runicBlue,
    },
    vcs = {
      added = plt.arcaneGlow,
      changed = plt.muninn,
      removed = plt.divineGold,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.divineGold,
      green = plt.arcaneGlow,
      yellow = plt.paleWisdom,
      blue = plt.runicBlue,
      magenta = plt.mysticPurple,
      cyan = plt.runicGlow,
      white = plt.fg_darkest,
      black_bright = color(plt.ravenBlack):brighten(0.3):to_hex(),
      red_bright = color(plt.divineGold):brighten(0.1):to_hex(),
      green_bright = color(plt.arcaneGlow):brighten(0.1):to_hex(),
      yellow_bright = color(plt.paleWisdom):brighten(0.1):to_hex(),
      blue_bright = color(plt.runicBlue):brighten(0.2):to_hex(),
      magenta_bright = color(plt.mysticPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.runicGlow):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.muninn,
      indexed2 = plt.mimirWell,
    },
  }
end

return {
  name = "Asgard – Óðinn",
  author = "PrismPunk",
  description = "Allfather — raven blacks, twilight purples, runic blues, divine gold whispers. "
    .. "Óðinn is the Allfather, god of wisdom, war, and magic. He sacrificed his eye at Mimir's well "
    .. "for knowledge, hung from Yggdrasil for nine nights to learn the runes, and wanders the realms "
    .. "in disguise. His ravens Huginn (thought) and Muninn (memory) fly across all worlds, bringing "
    .. "him knowledge. This theme captures the mystical twilight of his wisdom — deep raven blacks form "
    .. "the foundation, layered with purple-tinged blues of runic magic and arcane power. Ash grey "
    .. "represents Yggdrasil and the dim elements of forgotten knowledge, while subtle gold accents "
    .. "hint at his divine authority without overwhelming the atmospheric depth.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.yggdrasilAsh,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.divineGold,
    base09 = palette.paleWisdom,
    base0A = palette.muninn,
    base0B = palette.muninn,
    base0C = palette.runicGlow,
    base0D = palette.runicBlue,
    base0E = palette.mysticPurple,
    base0F = palette.arcaneGlow,
  },
  palette = palette,
  get = M.get,
}
