local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0d1117",
  bg_darker = "#161b22",
  bg_dark = "#1f2937",
  bg_mid = "#283548",
  bg_light = "#374151",
  bg_lighter = "#475569",
  bg_lightest = "#64748b",
  bg_alt1 = "#334155",
  bg_alt2 = "#3f4f66",
  bg_alt3 = "#4b5d7a",
  bg_alt4 = "#576b8e",
  fg_darkest = "#f8fafc",
  fg_dark = "#e2e8f0",
  fg_mid = "#cbd5e1",
  fg_light = "#94a3b8",
  fg_lighter = "#64748b",
  fg_lightest = "#475569",
  swanWhite = "#ffffff",
  pearlFeather = "#f0f4f8",
  silverWing = "#d4dce6",
  lakeReflection = "#4a90a4",
  waterRipple = "#5ba3b8",
  dawnMist = "#f4d5e0",
  rosePink = "#e8a4b8",
  transformGlow = "#d4b0c0",
  valkyrieSilver = "#c0c8d0",
  flightTrail = "#a8b8c8",
  gracefulArc = "#8ca0b0",
  wingBeat = "#7088a0",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.lakeReflection,
      insert = plt.waterRipple,
      visual = plt.rosePink,
      replace = plt.dawnMist,
      command = plt.valkyrieSilver,
    },
    accent = {
      accent1 = plt.lakeReflection,
      accent2 = plt.waterRipple,
      accent3 = plt.rosePink,
      accent4 = plt.dawnMist,
      accent5 = plt.valkyrieSilver,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.lakeReflection,
      rainbow2 = plt.waterRipple,
      rainbow3 = plt.rosePink,
      rainbow4 = plt.dawnMist,
      rainbow5 = plt.valkyrieSilver,
      rainbow6 = plt.flightTrail,
      rainbow7 = plt.gracefulArc,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.rosePink,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.lakeReflection,
      header2 = plt.waterRipple,
      special = plt.rosePink,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.lakeReflection,
      picker = plt.waterRipple,
      yank = plt.rosePink,
      mark = plt.dawnMist,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.lakeReflection,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.lakeReflection,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.lakeReflection,
        indicator = plt.waterRipple,
      },
    },
    syn = {
      attribute = plt.waterRipple,
      boolean = plt.rosePink,
      comment = plt.bg_lightest,
      constant = plt.lakeReflection,
      deprecated = plt.fg_lighter,
      func = plt.lakeReflection,
      identifier = plt.fg_light,
      keyword = plt.rosePink,
      method = plt.waterRipple,
      number = plt.dawnMist,
      operator = plt.valkyrieSilver,
      parameter = plt.flightTrail,
      preproc = plt.lakeReflection,
      punct = plt.fg_lighter,
      regex = plt.waterRipple,
      special = plt.rosePink,
      special2 = plt.dawnMist,
      special3 = plt.transformGlow,
      statement = plt.rosePink,
      string = plt.waterRipple,
      symbol = plt.lakeReflection,
      type = plt.valkyrieSilver,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.rosePink,
      warning = plt.dawnMist,
      info = plt.waterRipple,
      ok = plt.lakeReflection,
      hint = plt.bg_lightest,
      virtual_text_error = plt.rosePink,
      virtual_text_warning = plt.dawnMist,
      virtual_text_info = plt.waterRipple,
      virtual_text_ok = plt.lakeReflection,
      virtual_text_hint = plt.bg_lightest,
    },
    diff = {
      add = plt.waterRipple,
      add_inline = plt.lakeReflection,
      change = plt.dawnMist,
      change_inline = plt.rosePink,
      delete = plt.rosePink,
      delete_inline = plt.bg_darker,
      text = plt.valkyrieSilver,
    },
    vcs = {
      added = plt.waterRipple,
      changed = plt.dawnMist,
      removed = plt.rosePink,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.rosePink,
      green = plt.waterRipple,
      yellow = plt.dawnMist,
      blue = plt.lakeReflection,
      magenta = plt.transformGlow,
      cyan = plt.valkyrieSilver,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.rosePink):brighten(0.1):to_hex(),
      green_bright = color(plt.waterRipple):brighten(0.1):to_hex(),
      yellow_bright = color(plt.dawnMist):brighten(0.1):to_hex(),
      blue_bright = color(plt.lakeReflection):brighten(0.1):to_hex(),
      magenta_bright = color(plt.transformGlow):brighten(0.1):to_hex(),
      cyan_bright = color(plt.valkyrieSilver):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.lakeReflection,
      indexed2 = plt.waterRipple,
    },
  }
end

return {
  name = "Asgard – Ölrún",
  author = "PrismPunk",
  description = "Swan maiden — enchanted lake blues, stolen cloak pink, shape-shifting silver. "
    .. "Ölrún is another valkyrie swan maiden whose feather cloak was stolen while bathing. "
    .. "This theme mirrors Sváfa's approach but swaps warm dawn rose-gold for softer, enchanted "
    .. "pinks — the color of her stolen cloak and the magic that binds her. Deep lake blues remain "
    .. "for the water where she transforms, silver-white for swan feathers, but now delicate rose "
    .. "and blush pinks represent the enchantment and vulnerability of her stolen form. Same balance, "
    .. "different emotion — where Sváfa is dawn's warmth, Ölrún is twilight's gentle magic.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.rosePink,
    base09 = palette.dawnMist,
    base0A = palette.transformGlow,
    base0B = palette.waterRipple,
    base0C = palette.lakeReflection,
    base0D = palette.valkyrieSilver,
    base0E = palette.flightTrail,
    base0F = palette.swanWhite,
  },
  palette = palette,
  get = M.get,
}
