local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0e0d08",
  bg_darker = "#16140c",
  bg_dark = "#1e1c12",
  bg_mid = "#272418",
  bg_light = "#302c1e",
  bg_lighter = "#3a3526",
  bg_lightest = "#44402e",
  bg_alt1 = "#504a36",
  bg_alt2 = "#5c5540",
  bg_alt3 = "#68604a",
  bg_alt4 = "#746b54",
  fg_lightest = "#f0e8d8",
  fg_light = "#d8d0be",
  fg_mid = "#a89e88",
  fg_dark = "#786e58",
  goldenHair = "#d4a830",
  grainSheaf = "#c8b848",
  rowanBerry = "#c85040",
  earthLoam = "#8a7048",
  meadowGreen = "#5a9a50",
  hearthEmber = "#c87838",
  spindle = "#a088b0",
  skyLinen = "#6888a8",
  fidelityRose = "#b86878",
  harvestMoon = "#d8b860",
  thatchGold = "#b89830",
  birchBark = "#c8b898",
  wellWater = "#5080a0",
  ironPan = "#607068",
  rootDark = "#2a2418",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.goldenHair,
      insert = plt.meadowGreen,
      visual = plt.spindle,
      replace = plt.rowanBerry,
      command = plt.hearthEmber,
    },
    accent = {
      accent1 = plt.goldenHair,
      accent2 = plt.meadowGreen,
      accent3 = plt.skyLinen,
      accent4 = plt.fg_light,
      accent5 = plt.fidelityRose,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.goldenHair,
      rainbow2 = plt.meadowGreen,
      rainbow3 = plt.skyLinen,
      rainbow4 = plt.spindle,
      rainbow5 = plt.fidelityRose,
      rainbow6 = plt.hearthEmber,
      rainbow7 = plt.grainSheaf,
    },
    i = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.goldenHair,
      bg_visual = plt.rootDark,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.goldenHair,
      header2 = plt.grainSheaf,
      special = plt.harvestMoon,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.earthLoam,
      indent = plt.bg_light,
      indent_scope = plt.goldenHair,
      picker = plt.grainSheaf,
      yank = plt.harvestMoon,
      mark = plt.spindle,
      scrollbar = plt.bg_lighter,
      selection = plt.rootDark,
      line_nr = plt.fg_dark,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.goldenHair,
        indicator = plt.grainSheaf,
      },
    },
    syn = {
      attribute = plt.hearthEmber,
      boolean = plt.spindle,
      comment = plt.ironPan,
      constant = plt.skyLinen,
      deprecated = plt.fg_dark,
      func = plt.goldenHair,
      identifier = plt.fg_light,
      keyword = plt.fidelityRose,
      method = plt.goldenHair,
      number = plt.harvestMoon,
      operator = plt.birchBark,
      parameter = plt.meadowGreen,
      preproc = plt.rowanBerry,
      punct = plt.fg_mid,
      regex = plt.spindle,
      special = plt.harvestMoon,
      special2 = plt.hearthEmber,
      special3 = plt.thatchGold,
      statement = plt.fidelityRose,
      string = plt.meadowGreen,
      symbol = plt.wellWater,
      type = plt.skyLinen,
      variable = plt.fg_light,
      annotation = plt.grainSheaf,
    },
    diag = {
      error = plt.rowanBerry,
      warning = plt.hearthEmber,
      info = plt.skyLinen,
      ok = plt.meadowGreen,
      hint = plt.goldenHair,
      virtual_text_error = plt.rowanBerry,
      virtual_text_warning = plt.hearthEmber,
      virtual_text_info = plt.skyLinen,
      virtual_text_ok = plt.meadowGreen,
      virtual_text_hint = plt.goldenHair,
    },
    diff = {
      add = plt.meadowGreen,
      add_inline = plt.grainSheaf,
      change = plt.skyLinen,
      change_inline = plt.spindle,
      delete = plt.rowanBerry,
      delete_inline = plt.fidelityRose,
      text = plt.goldenHair,
    },
    vcs = {
      added = plt.meadowGreen,
      changed = plt.skyLinen,
      removed = plt.rowanBerry,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.rowanBerry,
      green = plt.meadowGreen,
      yellow = plt.goldenHair,
      blue = plt.skyLinen,
      magenta = plt.spindle,
      cyan = plt.wellWater,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.rowanBerry):brighten(0.2):to_hex(),
      green_bright = color(plt.meadowGreen):brighten(0.15):to_hex(),
      yellow_bright = color(plt.goldenHair):brighten(0.15):to_hex(),
      blue_bright = color(plt.skyLinen):brighten(0.15):to_hex(),
      magenta_bright = color(plt.spindle):brighten(0.2):to_hex(),
      cyan_bright = color(plt.wellWater):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.hearthEmber,
      indexed2 = plt.thatchGold,
    },
  }
end

return {
  name = "Ásgarðr – Sif",
  author = "PrismPunk",
  description = "Sif, golden-haired wife of Þórr, goddess of the earth, grain, and the "
    .. "bonds of hearth and harvest. Where Þórr is storm and fury, Sif is the field "
    .. "after the rain — the warm soil that receives the lightning and turns it into "
    .. "growth. Her golden hair, famously shorn by Loki and replaced by the Dvergar "
    .. "with real gold spun finer than thread, is the ripening wheat itself, the "
    .. "visible promise that the land will provide. She is fidelity, rootedness, the "
    .. "quiet strength of the one who keeps the hall while the thunder god rides out. "
    .. "This palette is drawn from the earth she tends: deep loam and root-dark "
    .. "backgrounds, lit by the warm gold of her hair and the harvest moon, the "
    .. "green of meadow and kitchen garden, the rose of rowan berries strung above "
    .. "the door for protection, the muted blue of sky seen through linen hung to "
    .. "dry. Hearthfire ember and birch bark warm the edges, while spindle-purple "
    .. "recalls the wool she spins and the quiet domestic magic of the Æsir's "
    .. "greatest hall. It is a theme of warmth, patience, and the deep fertility "
    .. "that outlasts every storm.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.rowanBerry,
    base09 = palette.hearthEmber,
    base0A = palette.goldenHair,
    base0B = palette.meadowGreen,
    base0C = palette.wellWater,
    base0D = palette.skyLinen,
    base0E = palette.spindle,
    base0F = palette.fidelityRose,
  },
  palette = palette,
  get = M.get,
}
