local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#050a0c",
  bg_darker = "#0a1418",
  bg_dark = "#0f1e24",
  bg_mid = "#142830",
  bg_light = "#19323c",
  bg_lighter = "#1e3c48",
  bg_lightest = "#234654",
  bg_alt1 = "#285060",
  bg_alt2 = "#2d5a6c",
  bg_alt3 = "#326478",
  bg_alt4 = "#376e84",
  fg_darkest = "#f0fafb",
  fg_dark = "#e6f4f5",
  fg_mid = "#dceef0",
  fg_light = "#d2e8ea",
  fg_lighter = "#c8e2e5",
  fg_lightest = "#bedcdf",
  magicTeal = "#00a896",
  craftGlow = "#02c39a",
  foldingRune = "#05d9a5",
  pocketWonder = "#4dd4ac",
  windSilver = "#8ec5d1",
  sailBreeze = "#a8d8e0",
  favorableGust = "#c2ebef",
  dwarvenForge = "#7a9ca8",
  ivalidisGift = "#5a8c9e",
  runicThread = "#3a7c8e",
  goldenMast = "#d4af37",
  freyrGold = "#e6c158",
  treasureGleam = "#f0d279",
  deepVoyage = "#1a4d5c",
  seaDepth = "#2a5d6c",
  oceanHorizon = "#3a6d7c",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.magicTeal,
      insert = plt.craftGlow,
      visual = plt.goldenMast,
      replace = plt.runicThread,
      command = plt.freyrGold,
    },
    accent = {
      accent1 = plt.magicTeal,
      accent2 = plt.goldenMast,
      accent3 = plt.craftGlow,
      accent4 = plt.windSilver,
      accent5 = plt.dwarvenForge,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.magicTeal,
      rainbow2 = plt.craftGlow,
      rainbow3 = plt.goldenMast,
      rainbow4 = plt.windSilver,
      rainbow5 = plt.dwarvenForge,
      rainbow6 = plt.foldingRune,
      rainbow7 = plt.freyrGold,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.magicTeal,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.magicTeal,
      header2 = plt.goldenMast,
      special = plt.craftGlow,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.magicTeal,
      picker = plt.foldingRune,
      yank = plt.craftGlow,
      mark = plt.goldenMast,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.magicTeal,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.magicTeal,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.magicTeal,
        indicator = plt.craftGlow,
      },
    },
    syn = {
      attribute = plt.foldingRune,
      boolean = plt.craftGlow,
      comment = plt.windSilver,
      constant = plt.magicTeal,
      deprecated = plt.fg_lighter,
      func = plt.craftGlow,
      identifier = plt.fg_light,
      keyword = plt.dwarvenForge,
      method = plt.pocketWonder,
      number = plt.freyrGold,
      operator = plt.sailBreeze,
      parameter = plt.ivalidisGift,
      preproc = plt.runicThread,
      punct = plt.fg_lighter,
      regex = plt.oceanHorizon,
      special = plt.magicTeal,
      special2 = plt.goldenMast,
      special3 = plt.favorableGust,
      statement = plt.dwarvenForge,
      string = plt.goldenMast,
      symbol = plt.craftGlow,
      type = plt.dwarvenForge,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.runicThread,
      warning = plt.goldenMast,
      info = plt.windSilver,
      ok = plt.craftGlow,
      hint = plt.sailBreeze,
      virtual_text_error = plt.runicThread,
      virtual_text_warning = plt.goldenMast,
      virtual_text_info = plt.windSilver,
      virtual_text_ok = plt.craftGlow,
      virtual_text_hint = plt.sailBreeze,
    },
    diff = {
      add = plt.craftGlow,
      add_inline = plt.foldingRune,
      change = plt.magicTeal,
      change_inline = plt.pocketWonder,
      delete = plt.runicThread,
      delete_inline = plt.bg_darker,
      text = plt.magicTeal,
    },
    vcs = {
      added = plt.craftGlow,
      changed = plt.magicTeal,
      removed = plt.runicThread,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.runicThread,
      green = plt.craftGlow,
      yellow = plt.goldenMast,
      blue = plt.magicTeal,
      magenta = plt.dwarvenForge,
      cyan = plt.windSilver,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.runicThread):brighten(0.15):to_hex(),
      green_bright = color(plt.craftGlow):brighten(0.15):to_hex(),
      yellow_bright = color(plt.goldenMast):brighten(0.1):to_hex(),
      blue_bright = color(plt.magicTeal):brighten(0.15):to_hex(),
      magenta_bright = color(plt.dwarvenForge):brighten(0.15):to_hex(),
      cyan_bright = color(plt.windSilver):brighten(0.15):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.magicTeal,
      indexed2 = plt.craftGlow,
    },
  }
end

return {
  name = "Asgard – Skíðblaðnir",
  author = "PrismPunk",
  description = "Foldable ship — magical craft, always favorable wind, pocket-sized wonder. "
    .. "Skíðblaðnir, crafted by the sons of Ivaldi, is the greatest of ships. Large enough to hold "
    .. "all the Æsir with their weapons and armor, yet folds small enough to fit in a pocket. "
    .. "It always has favorable wind wherever it sails. Given to Freyr, this marvel of dwarven "
    .. "craftsmanship represents impossible magic made real. This theme captures the wonder: "
    .. "magical teals for the enchanted vessel glowing with runes, golden mast for Freyr's treasure, "
    .. "silver winds that never fail, dwarven forge blues for Ivaldi's sons' masterwork, and deep "
    .. "ocean depths for endless voyages. The pocket-sized wonder that conquers all seas.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.runicThread,
    base09 = palette.goldenMast,
    base0A = palette.freyrGold,
    base0B = palette.craftGlow,
    base0C = palette.magicTeal,
    base0D = palette.windSilver,
    base0E = palette.dwarvenForge,
    base0F = palette.foldingRune,
  },
  palette = palette,
  get = M.get,
}
