local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#00101a",
  bg_darker = "#002033",
  bg_dark = "#00304d",
  bg_mid = "#004066",
  bg_light = "#005080",
  bg_lighter = "#006099",
  bg_lightest = "#0070b3",
  bg_alt1 = "#0080cc",
  bg_alt2 = "#0090e6",
  bg_alt3 = "#00a0ff",
  bg_alt4 = "#19aaff",
  fg_darkest = "#ffffff",
  fg_dark = "#f6fbff",
  fg_mid = "#edf6ff",
  fg_light = "#ddedff",
  fg_lighter = "#cbd7fa",
  fg_lightest = "#b9c1f5",
  royalBlue = "#4169e1",
  highTower = "#5f7fe6",
  battleDecision = "#7d95eb",
  odinMessenger = "#9babf0",
  skyThrone = "#80d2ff",
  divineCommand = "#66c8ff",
  valkyrieWing = "#99dcff",
  fateDecree = "#4dbeff",
  celestialGlow = "#edf6ff",
  crownedChoice = "#33b4ff",
  sovereignWill = "#19aaff",
  exaltedDuty = "#b9c1f5",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.royalBlue,
      insert = plt.skyThrone,
      visual = plt.battleDecision,
      replace = plt.divineCommand,
      command = plt.celestialGlow,
    },
    accent = {
      accent1 = plt.royalBlue,
      accent2 = plt.skyThrone,
      accent3 = plt.battleDecision,
      accent4 = plt.divineCommand,
      accent5 = plt.celestialGlow,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.royalBlue,
      rainbow2 = plt.highTower,
      rainbow3 = plt.battleDecision,
      rainbow4 = plt.odinMessenger,
      rainbow5 = plt.skyThrone,
      rainbow6 = plt.valkyrieWing,
      rainbow7 = plt.celestialGlow,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.battleDecision,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.royalBlue,
      header2 = plt.skyThrone,
      special = plt.battleDecision,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.royalBlue,
      picker = plt.skyThrone,
      yank = plt.battleDecision,
      mark = plt.divineCommand,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.royalBlue,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.royalBlue,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.royalBlue,
        indicator = plt.skyThrone,
      },
    },
    syn = {
      attribute = plt.skyThrone,
      boolean = plt.battleDecision,
      comment = plt.bg_lightest,
      constant = plt.royalBlue,
      deprecated = plt.fg_lighter,
      func = plt.royalBlue,
      identifier = plt.fg_light,
      keyword = plt.battleDecision,
      method = plt.highTower,
      number = plt.divineCommand,
      operator = plt.celestialGlow,
      parameter = plt.exaltedDuty,
      preproc = plt.odinMessenger,
      punct = plt.fg_lighter,
      regex = plt.fateDecree,
      special = plt.valkyrieWing,
      special2 = plt.divineCommand,
      special3 = plt.celestialGlow,
      statement = plt.battleDecision,
      string = plt.skyThrone,
      symbol = plt.royalBlue,
      type = plt.highTower,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.battleDecision,
      warning = plt.divineCommand,
      info = plt.royalBlue,
      ok = plt.skyThrone,
      hint = plt.bg_lightest,
      virtual_text_error = plt.battleDecision,
      virtual_text_warning = plt.divineCommand,
      virtual_text_info = plt.royalBlue,
      virtual_text_ok = plt.skyThrone,
      virtual_text_hint = plt.bg_lightest,
    },
    diff = {
      add = plt.skyThrone,
      add_inline = plt.divineCommand,
      change = plt.battleDecision,
      change_inline = plt.highTower,
      delete = plt.royalBlue,
      delete_inline = plt.bg_darker,
      text = plt.celestialGlow,
    },
    vcs = {
      added = plt.skyThrone,
      changed = plt.divineCommand,
      removed = plt.royalBlue,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.battleDecision,
      green = plt.skyThrone,
      yellow = plt.divineCommand,
      blue = plt.royalBlue,
      magenta = plt.odinMessenger,
      cyan = plt.fateDecree,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.battleDecision):brighten(0.1):to_hex(),
      green_bright = color(plt.skyThrone):brighten(0.1):to_hex(),
      yellow_bright = color(plt.divineCommand):brighten(0.1):to_hex(),
      blue_bright = color(plt.royalBlue):brighten(0.15):to_hex(),
      magenta_bright = color(plt.odinMessenger):brighten(0.1):to_hex(),
      cyan_bright = color(plt.fateDecree):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.royalBlue,
      indexed2 = plt.skyThrone,
    },
  }
end

return {
  name = "Asgard – Skögul",
  author = "PrismPunk",
  description = "High-towering — royal blues, battle decider, Odin's messenger. "
    .. "Skögul stands tall among the Valkyries, bearing Odin's sovereign will to the battlefield. "
    .. "Her name means 'high-towering' or 'shaker,' reflecting her authority in deciding the fate "
    .. "of warriors. This theme captures the majesty of her divine duty: deep ocean blues represent "
    .. "the depths of Odin's wisdom, royal blues embody her exalted position, and sky blues shimmer "
    .. "like her wings descending from Asgard. She is the decree made manifest — where the Allfather's "
    .. "command meets mortal destiny in brilliant azure light.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.battleDecision,
    base09 = palette.divineCommand,
    base0A = palette.celestialGlow,
    base0B = palette.skyThrone,
    base0C = palette.fateDecree,
    base0D = palette.royalBlue,
    base0E = palette.odinMessenger,
    base0F = palette.valkyrieWing,
  },
  palette = palette,
  get = M.get,
}
