local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1a1a",
  bg_darker = "#2d2d2d",
  bg_dark = "#404040",
  bg_mid = "#535353",
  bg_light = "#666666",
  bg_lighter = "#797979",
  bg_lightest = "#8c8c8c",
  bg_alt1 = "#9f9f9f",
  bg_alt2 = "#b2b2b2",
  bg_alt3 = "#c5c5c5",
  bg_alt4 = "#d8d8d8",
  fg_darkest = "#ffffff",
  fg_dark = "#feffff",
  fg_mid = "#fdffff",
  fg_light = "#fafeff",
  fg_lighter = "#f6fcff",
  fg_lightest = "#ecf8ff",
  shadowGallop = "#708090",
  silverMist = "#8496a6",
  betweenWorlds = "#98acbc",
  swiftGrey = "#acc2d2",
  mountSilver = "#c0d8e8",
  eightLegged = "#d4eefe",
  odinSteed = "#e0f4ff",
  realmRunner = "#ecf8ff",
  ghostHoof = "#f6fcff",
  voidWalker = "#fafeff",
  dimensionStride = "#fdffff",
  cosmicGallop = "#feffff",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.swiftGrey,
      insert = plt.betweenWorlds,
      visual = plt.mountSilver,
      replace = plt.eightLegged,
      command = plt.odinSteed,
    },
    accent = {
      accent1 = plt.shadowGallop,
      accent2 = plt.swiftGrey,
      accent3 = plt.mountSilver,
      accent4 = plt.eightLegged,
      accent5 = plt.odinSteed,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.shadowGallop,
      rainbow2 = plt.silverMist,
      rainbow3 = plt.betweenWorlds,
      rainbow4 = plt.swiftGrey,
      rainbow5 = plt.mountSilver,
      rainbow6 = plt.eightLegged,
      rainbow7 = plt.odinSteed,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.mountSilver,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.swiftGrey,
      header2 = plt.mountSilver,
      special = plt.eightLegged,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.swiftGrey,
      picker = plt.odinSteed,
      yank = plt.mountSilver,
      mark = plt.eightLegged,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.swiftGrey,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.swiftGrey,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_lightest,
        fg_selected = plt.fg_light,
        fg_alternate = plt.swiftGrey,
        indicator = plt.mountSilver,
      },
    },
    syn = {
      attribute = plt.odinSteed,
      boolean = plt.mountSilver,
      comment = plt.bg_lightest,
      constant = plt.betweenWorlds,
      deprecated = plt.fg_lighter,
      func = plt.swiftGrey,
      identifier = plt.fg_light,
      keyword = plt.shadowGallop,
      method = plt.betweenWorlds,
      number = plt.mountSilver,
      operator = plt.silverMist,
      parameter = plt.realmRunner,
      preproc = plt.betweenWorlds,
      punct = plt.fg_lighter,
      regex = plt.odinSteed,
      special = plt.eightLegged,
      special2 = plt.ghostHoof,
      special3 = plt.voidWalker,
      statement = plt.shadowGallop,
      string = plt.swiftGrey,
      symbol = plt.mountSilver,
      type = plt.betweenWorlds,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.shadowGallop,
      warning = plt.swiftGrey,
      info = plt.betweenWorlds,
      ok = plt.mountSilver,
      hint = plt.bg_lightest,
      virtual_text_error = plt.shadowGallop,
      virtual_text_warning = plt.swiftGrey,
      virtual_text_info = plt.betweenWorlds,
      virtual_text_ok = plt.mountSilver,
      virtual_text_hint = plt.bg_lightest,
    },
    diff = {
      add = plt.mountSilver,
      add_inline = plt.eightLegged,
      change = plt.betweenWorlds,
      change_inline = plt.swiftGrey,
      delete = plt.shadowGallop,
      delete_inline = plt.bg_darker,
      text = plt.odinSteed,
    },
    vcs = {
      added = plt.mountSilver,
      changed = plt.betweenWorlds,
      removed = plt.shadowGallop,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.shadowGallop,
      green = plt.mountSilver,
      yellow = plt.swiftGrey,
      blue = plt.betweenWorlds,
      magenta = plt.odinSteed,
      cyan = plt.eightLegged,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.shadowGallop):brighten(0.1):to_hex(),
      green_bright = color(plt.mountSilver):brighten(0.1):to_hex(),
      yellow_bright = color(plt.swiftGrey):brighten(0.1):to_hex(),
      blue_bright = color(plt.betweenWorlds):brighten(0.1):to_hex(),
      magenta_bright = color(plt.odinSteed):brighten(0.1):to_hex(),
      cyan_bright = color(plt.eightLegged):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.swiftGrey,
      indexed2 = plt.betweenWorlds,
    },
  }
end

return {
  name = "Asgard – Sleipnir",
  author = "PrismPunk",
  description = "Eight-legged steed — swift greys, between-worlds silver, Odin's mount, shadow gallop. "
    .. "Sleipnir is Odin's eight-legged horse, the swiftest of all steeds, capable of galloping across "
    .. "the sky, over the sea, and between the nine realms. Born of Loki's shapeshifting trickery, "
    .. "Sleipnir can traverse any terrain and dimension, carrying the Allfather on his journeys through "
    .. "the cosmos. This theme captures the horse's ethereal nature — deep shadow greys anchor the void "
    .. "between worlds, while silvery blues shimmer like moonlight on a galloping steed. The palette "
    .. "flows from slate grey shadows through misty silvers to pale sky blues, evoking the liminal "
    .. "spaces Sleipnir traverses. Swift, spectral, and otherworldly — the mount that bridges all realms.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_lightest,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.shadowGallop,
    base09 = palette.silverMist,
    base0A = palette.swiftGrey,
    base0B = palette.mountSilver,
    base0C = palette.eightLegged,
    base0D = palette.betweenWorlds,
    base0E = palette.odinSteed,
    base0F = palette.realmRunner,
  },
  palette = palette,
  get = M.get,
}
