local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#001a33",
  bg_darker = "#002b4d",
  bg_dark = "#003c66",
  bg_mid = "#004d80",
  bg_light = "#005e99",
  bg_lighter = "#006fb3",
  bg_lightest = "#0080cc",
  bg_alt1 = "#1a91e6",
  bg_alt2 = "#33a2ff",
  bg_alt3 = "#4db3ff",
  bg_alt4 = "#66c4ff",
  fg_darkest = "#99e6ff",
  fg_dark = "#b3f0ff",
  fg_mid = "#ccf7ff",
  fg_light = "#e6fdff",
  fg_lighter = "#ffffff",
  fg_lightest = "#ffffff",
  thunderStrike = "#8b0000",
  hammerForge = "#a01a1a",
  battleRage = "#b53434",
  lightningFlash = "#80d5ff",
  stormFury = "#0080cc",
  mjolnirCrash = "#ca4e4e",
  tempestRoar = "#1a91e6",
  skyWrath = "#4db3ff",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.stormFury,
      insert = plt.lightningFlash,
      visual = plt.tempestRoar,
      replace = plt.thunderStrike,
      command = plt.skyWrath,
    },
    accent = {
      accent1 = plt.stormFury,
      accent2 = plt.lightningFlash,
      accent3 = plt.thunderStrike,
      accent4 = plt.tempestRoar,
      accent5 = plt.mjolnirCrash,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.thunderStrike,
      rainbow2 = plt.hammerForge,
      rainbow3 = plt.battleRage,
      rainbow4 = plt.stormFury,
      rainbow5 = plt.tempestRoar,
      rainbow6 = plt.skyWrath,
      rainbow7 = plt.lightningFlash,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_lighter,
      fg_dimmer = plt.fg_light,
      fg_dark = plt.fg_mid,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.stormFury,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.stormFury,
      header2 = plt.lightningFlash,
      special = plt.thunderStrike,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.tempestRoar,
      indent = plt.bg_light,
      indent_scope = plt.stormFury,
      picker = plt.lightningFlash,
      yank = plt.skyWrath,
      mark = plt.mjolnirCrash,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_dark,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.stormFury,
        indicator = plt.lightningFlash,
      },
    },
    syn = {
      attribute = plt.lightningFlash,
      boolean = plt.thunderStrike,
      comment = plt.bg_alt1,
      constant = plt.mjolnirCrash,
      deprecated = plt.bg_alt2,
      func = plt.stormFury,
      identifier = plt.fg_light,
      keyword = plt.tempestRoar,
      method = plt.stormFury,
      number = plt.mjolnirCrash,
      operator = plt.skyWrath,
      parameter = plt.lightningFlash,
      preproc = plt.battleRage,
      punct = plt.fg_mid,
      regex = plt.hammerForge,
      special = plt.thunderStrike,
      special2 = plt.tempestRoar,
      special3 = plt.mjolnirCrash,
      statement = plt.tempestRoar,
      string = plt.lightningFlash,
      symbol = plt.stormFury,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.thunderStrike,
      warning = plt.mjolnirCrash,
      info = plt.stormFury,
      ok = plt.lightningFlash,
      hint = plt.tempestRoar,
      virtual_text_error = plt.thunderStrike,
      virtual_text_warning = plt.mjolnirCrash,
      virtual_text_info = plt.stormFury,
      virtual_text_ok = plt.lightningFlash,
      virtual_text_hint = plt.tempestRoar,
    },
    diff = {
      add = plt.lightningFlash,
      add_inline = plt.skyWrath,
      change = plt.stormFury,
      change_inline = plt.tempestRoar,
      delete = plt.thunderStrike,
      delete_inline = plt.hammerForge,
      text = plt.mjolnirCrash,
    },
    vcs = {
      added = plt.lightningFlash,
      changed = plt.stormFury,
      removed = plt.thunderStrike,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.thunderStrike,
      green = plt.lightningFlash,
      yellow = plt.skyWrath,
      blue = plt.stormFury,
      magenta = plt.tempestRoar,
      cyan = plt.lightningFlash,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = plt.battleRage,
      green_bright = color(plt.lightningFlash):brighten(0.15):to_hex(),
      yellow_bright = color(plt.skyWrath):brighten(0.15):to_hex(),
      blue_bright = color(plt.stormFury):brighten(0.15):to_hex(),
      magenta_bright = color(plt.tempestRoar):brighten(0.2):to_hex(),
      cyan_bright = color(plt.lightningFlash):brighten(0.15):to_hex(),
      white_bright = plt.fg_lightest,
      indexed1 = plt.mjolnirCrash,
      indexed2 = plt.hammerForge,
    },
  }
end

return {
  name = "Asgard – Þórr",
  author = "PrismPunk",
  description = "Thunder god — storm blues, lightning whites, hammer-strike reds, tempest fury. "
    .. "Þórr is the mightiest warrior of the Æsir, protector of Midgard and slayer of "
    .. "giants. His hammer Mjölnir strikes with the force of thunder, and lightning "
    .. "follows in his wake. He rides across the sky in a chariot pulled by two goats, "
    .. "Tanngrisnir and Tanngnjóstr, and the rumble of wheels is the sound of the storm. "
    .. "Where Óðinn is cunning and grey, Þórr is direct and elemental — a force of nature "
    .. "incarnate. This palette crashes from deep storm-cloud blues through electric "
    .. "lightning whites to the blood-red fury of battle. Every strike of Mjölnir splits "
    .. "the sky, and the thunder that follows shakes the Nine Realms.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.thunderStrike,
    base09 = palette.mjolnirCrash,
    base0A = palette.skyWrath,
    base0B = palette.lightningFlash,
    base0C = palette.lightningFlash,
    base0D = palette.stormFury,
    base0E = palette.tempestRoar,
    base0F = palette.battleRage,
  },
  palette = palette,
  get = M.get,
}
