local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0202",
  bg_darker = "#150505",
  bg_dark = "#200808",
  bg_mid = "#2b0b0b",
  bg_light = "#360e0e",
  bg_lighter = "#411111",
  bg_lightest = "#4c1414",
  bg_alt1 = "#571717",
  bg_alt2 = "#621a1a",
  bg_alt3 = "#6d1d1d",
  bg_alt4 = "#782020",
  fg_darkest = "#f5d5d5",
  fg_dark = "#ecc0c0",
  fg_mid = "#e3abab",
  fg_light = "#da9696",
  fg_lighter = "#d18181",
  fg_lightest = "#c86c6c",
  sacrificeHand = "#8b4513",
  fenrirJaws = "#2f1a0a",
  gleipnirChain = "#b8b8b8",
  oathKeeper = "#cd853f",
  justicePrice = "#a0522d",
  ironWill = "#696969",
  warLaw = "#d2691e",
  bindingWord = "#dcdcdc",
  honorBound = "#bc8f8f",
  swordlessArm = "#8b7355",
  righteousBlood = "#a52a2a",
  moralAuthority = "#c0c0c0",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.oathKeeper,
      insert = plt.warLaw,
      visual = plt.sacrificeHand,
      replace = plt.righteousBlood,
      command = plt.gleipnirChain,
    },
    accent = {
      accent1 = plt.oathKeeper,
      accent2 = plt.warLaw,
      accent3 = plt.sacrificeHand,
      accent4 = plt.justicePrice,
      accent5 = plt.ironWill,
      invert = plt.bindingWord,
    },
    rainbow = {
      rainbow1 = plt.oathKeeper,
      rainbow2 = plt.warLaw,
      rainbow3 = plt.honorBound,
      rainbow4 = plt.sacrificeHand,
      rainbow5 = plt.justicePrice,
      rainbow6 = plt.ironWill,
      rainbow7 = plt.swordlessArm,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.oathKeeper,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.oathKeeper,
      header2 = plt.warLaw,
      special = plt.gleipnirChain,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.ironWill,
      indent = plt.bg_light,
      indent_scope = plt.oathKeeper,
      picker = plt.sacrificeHand,
      yank = plt.warLaw,
      mark = plt.oathKeeper,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.oathKeeper,
      float = {
        fg = plt.fg_dark,
        bg = plt.bg_mid,
        fg_border = plt.bg_alt2,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_dark,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_dark,
        fg_alternate = plt.oathKeeper,
        indicator = plt.ironWill,
      },
    },
    syn = {
      attribute = plt.warLaw,
      boolean = plt.oathKeeper,
      comment = plt.bg_alt2,
      constant = plt.honorBound,
      deprecated = plt.bg_alt3,
      func = plt.justicePrice,
      identifier = plt.fg_dark,
      keyword = plt.oathKeeper,
      method = plt.justicePrice,
      number = plt.sacrificeHand,
      operator = plt.gleipnirChain,
      parameter = plt.fg_mid,
      preproc = plt.ironWill,
      punct = plt.fg_light,
      regex = plt.swordlessArm,
      special = plt.warLaw,
      special2 = plt.moralAuthority,
      special3 = plt.bindingWord,
      statement = plt.oathKeeper,
      string = plt.sacrificeHand,
      symbol = plt.fenrirJaws,
      type = plt.fg_dark,
      variable = plt.fg_dark,
    },
    diag = {
      error = plt.righteousBlood,
      warning = plt.warLaw,
      info = plt.gleipnirChain,
      ok = plt.honorBound,
      hint = plt.ironWill,
      virtual_text_error = plt.righteousBlood,
      virtual_text_warning = plt.warLaw,
      virtual_text_info = plt.gleipnirChain,
      virtual_text_ok = plt.honorBound,
      virtual_text_hint = plt.ironWill,
    },
    diff = {
      add = plt.honorBound,
      add_inline = plt.warLaw,
      change = plt.oathKeeper,
      change_inline = plt.sacrificeHand,
      delete = plt.righteousBlood,
      delete_inline = plt.fenrirJaws,
      text = plt.gleipnirChain,
    },
    vcs = {
      added = plt.honorBound,
      changed = plt.oathKeeper,
      removed = plt.righteousBlood,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.righteousBlood,
      green = plt.honorBound,
      yellow = plt.oathKeeper,
      blue = plt.ironWill,
      magenta = plt.warLaw,
      cyan = plt.gleipnirChain,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.righteousBlood):brighten(0.2):to_hex(),
      green_bright = color(plt.honorBound):brighten(0.2):to_hex(),
      yellow_bright = color(plt.oathKeeper):brighten(0.1):to_hex(),
      blue_bright = color(plt.ironWill):brighten(0.3):to_hex(),
      magenta_bright = color(plt.warLaw):brighten(0.1):to_hex(),
      cyan_bright = color(plt.gleipnirChain):brighten(0.1):to_hex(),
      white_bright = plt.bindingWord,
      indexed1 = plt.justicePrice,
      indexed2 = plt.swordlessArm,
    },
  }
end

return {
  name = "Asgard – Týr",
  author = "PrismPunk",
  description = "War and justice — blood reds, honorable crimsons, one-handed sacrifice, iron resolve. "
    .. "Týr, god of war and justice, embodies the paradox of honorable violence. When the "
    .. "gods need to bind Fenrir, the monstrous wolf destined to devour Óðinn at Ragnarök, "
    .. "they forge Gleipnir — a chain made from impossible things: the sound of a cat's "
    .. "footfall, the beard of a woman, the roots of a mountain, the sinews of a bear, "
    .. "the breath of a fish, the spittle of a bird. Fenrir, suspicious of the gods' "
    .. "intentions, agrees to be bound only if one of them places a hand in his mouth as "
    .. "pledge of good faith. Týr steps forward. He knows the gods intend betrayal. He "
    .. "knows Fenrir will bite down. He places his right hand between those jaws anyway, "
    .. "because the binding must happen, because sometimes justice demands sacrifice, "
    .. "because honor means keeping your word even when breaking it would save you. The "
    .. "chain holds. The jaws close. Týr loses his sword hand but gains something greater: "
    .. "the moral authority to stand at Ragnarök not as a warrior seeking glory, but as "
    .. "law itself made flesh. This palette is blood on iron, the crimson of sacrifice, "
    .. "the deep red of oaths kept at terrible cost.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.righteousBlood,
    base09 = palette.sacrificeHand,
    base0A = palette.oathKeeper,
    base0B = palette.honorBound,
    base0C = palette.gleipnirChain,
    base0D = palette.warLaw,
    base0E = palette.ironWill,
    base0F = palette.justicePrice,
  },
  palette = palette,
  get = M.get,
}
