local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#001a26",
  bg_darker = "#00334d",
  bg_dark = "#004d73",
  bg_mid = "#006699",
  bg_light = "#0080c0",
  bg_lighter = "#0099e6",
  bg_lightest = "#00b3ff",
  bg_alt1 = "#1abfff",
  bg_alt2 = "#33ccff",
  bg_alt3 = "#4dd9ff",
  bg_alt4 = "#66e6ff",
  fg_darkest = "#ffffff",
  fg_dark = "#fefeff",
  fg_mid = "#fdfcff",
  fg_light = "#fbfaff",
  fg_lighter = "#f9f8fe",
  fg_lightest = "#e6f0f8",
  frozenLake = "#80f0ff",
  skiTrack = "#99f7ff",
  snowfield = "#b3fbff",
  iceShine = "#ccfeff",
  glacialPeak = "#e6ffff",
  ashBow = "#8b7355",
  yewWood = "#a0826d",
  birchShaft = "#c19a6b",
  steelEdge = "#b0c4de",
  arrowhead = "#778899",
  silverTip = "#c0c0c0",
  winterSun = "#fffacd",
  paleGold = "#f0e68c",
  huntFocus = "#4dd9ff",
  perfectShot = "#00b3ff",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.perfectShot,
      insert = plt.winterSun,
      visual = plt.huntFocus,
      replace = plt.arrowhead,
      command = plt.frozenLake,
    },
    accent = {
      accent1 = plt.perfectShot,
      accent2 = plt.winterSun,
      accent3 = plt.frozenLake,
      accent4 = plt.birchShaft,
      accent5 = plt.steelEdge,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.perfectShot,
      rainbow2 = plt.winterSun,
      rainbow3 = plt.huntFocus,
      rainbow4 = plt.birchShaft,
      rainbow5 = plt.steelEdge,
      rainbow6 = plt.frozenLake,
      rainbow7 = plt.silverTip,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.winterSun,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.perfectShot,
      header2 = plt.winterSun,
      special = plt.steelEdge,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.arrowhead,
      indent = plt.bg_light,
      indent_scope = plt.birchShaft,
      picker = plt.huntFocus,
      yank = plt.winterSun,
      mark = plt.perfectShot,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.paleGold,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.steelEdge,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.birchShaft,
        indicator = plt.winterSun,
      },
    },
    syn = {
      attribute = plt.huntFocus,
      boolean = plt.steelEdge,
      comment = plt.ashBow,
      constant = plt.paleGold,
      deprecated = plt.bg_alt3,
      func = plt.perfectShot,
      identifier = plt.fg_light,
      keyword = plt.frozenLake,
      method = plt.huntFocus,
      number = plt.winterSun,
      operator = plt.arrowhead,
      parameter = plt.fg_mid,
      preproc = plt.steelEdge,
      punct = plt.yewWood,
      regex = plt.silverTip,
      special = plt.silverTip,
      special2 = plt.iceShine,
      special3 = plt.fg_darkest,
      statement = plt.snowfield,
      string = plt.winterSun,
      symbol = plt.birchShaft,
      type = plt.frozenLake,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.arrowhead,
      warning = plt.paleGold,
      info = plt.frozenLake,
      ok = plt.huntFocus,
      hint = plt.ashBow,
      virtual_text_error = plt.arrowhead,
      virtual_text_warning = plt.paleGold,
      virtual_text_info = plt.frozenLake,
      virtual_text_ok = plt.huntFocus,
      virtual_text_hint = plt.ashBow,
    },
    diff = {
      add = plt.huntFocus,
      add_inline = plt.steelEdge,
      change = plt.winterSun,
      change_inline = plt.paleGold,
      delete = plt.arrowhead,
      delete_inline = plt.yewWood,
      text = plt.perfectShot,
    },
    vcs = {
      added = plt.huntFocus,
      changed = plt.winterSun,
      removed = plt.arrowhead,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.arrowhead,
      green = plt.huntFocus,
      yellow = plt.winterSun,
      blue = plt.frozenLake,
      magenta = plt.perfectShot,
      cyan = plt.skiTrack,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.arrowhead):brighten(0.1):to_hex(),
      green_bright = color(plt.huntFocus):brighten(0.1):to_hex(),
      yellow_bright = color(plt.winterSun):brighten(0.1):to_hex(),
      blue_bright = color(plt.frozenLake):brighten(0.2):to_hex(),
      magenta_bright = color(plt.perfectShot):brighten(0.2):to_hex(),
      cyan_bright = color(plt.skiTrack):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.birchShaft,
      indexed2 = plt.ashBow,
    },
  }
end

return {
  name = "Asgard – Ullr",
  author = "PrismPunk",
  description = "Hunting and Winter — frozen lake, ash bow, steel edge, winter sun. "
    .. "Ullr is the god of hunting, archery, skiing, and winter excellence. He is the silent "
    .. "hunter gliding across frozen lakes, the archer whose arrow never misses, the skier "
    .. "whose tracks cut perfect lines through untouched snow. When Odin was exiled, Ullr "
    .. "ruled Asgard for ten winters, and his reign was marked by cold perfection and flawless "
    .. "execution. This palette blends ice blues with warm woods and cold metals. Deep frozen "
    .. "blue backgrounds evoke winter depths, while bright cyan accents represent the clarity "
    .. "of the hunt. Warm wooden tones bring the bow and skis to life in comments, punctuation, "
    .. "and symbols. Steel and silver add metallic precision to operators and special elements. "
    .. "Pale gold and winter sun illuminate strings and numbers like low sunlight on snow. The "
    .. "theme captures the frozen silence of the hunt, the warmth of crafted wood, the cold bite "
    .. "of steel, and the pale gold of winter's sun.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.arrowhead,
    base09 = palette.winterSun,
    base0A = palette.paleGold,
    base0B = palette.winterSun,
    base0C = palette.frozenLake,
    base0D = palette.frozenLake,
    base0E = palette.perfectShot,
    base0F = palette.ashBow,
  },
  palette = palette,
  get = M.get,
}
