local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#1a1400",
  bg_darker = "#2d1f0a",
  bg_dark = "#3d2a10",
  bg_mid = "#4d3516",
  bg_light = "#5d401c",
  bg_lighter = "#6d4b22",
  bg_lightest = "#7d5628",
  bg_alt1 = "#8d612e",
  bg_alt2 = "#9d6c34",
  bg_alt3 = "#ad773a",
  bg_alt4 = "#bd8240",
  fg_darkest = "#fff9ec",
  fg_dark = "#f5ede0",
  fg_mid = "#ebe1d4",
  fg_light = "#e1d5c8",
  fg_lighter = "#d7c9bc",
  fg_lightest = "#cdbdb0",
  hallGold = "#daa520",
  shieldBronze = "#cd7f32",
  meadHoney = "#f0c05a",
  feastFire = "#ff6b35",
  einherjarCrimson = "#c1440e",
  odinBlue = "#4a6fa5",
  runeStone = "#8b9dc3",
  ashGrey = "#6b7280",
  spearSilver = "#b8c5d6",
  gloryAmber = "#ffb347",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.hallGold,
      insert = plt.meadHoney,
      visual = plt.odinBlue,
      replace = plt.feastFire,
      command = plt.shieldBronze,
    },
    accent = {
      accent1 = plt.hallGold,
      accent2 = plt.feastFire,
      accent3 = plt.odinBlue,
      accent4 = plt.meadHoney,
      accent5 = plt.shieldBronze,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.einherjarCrimson,
      rainbow2 = plt.feastFire,
      rainbow3 = plt.shieldBronze,
      rainbow4 = plt.hallGold,
      rainbow5 = plt.meadHoney,
      rainbow6 = plt.runeStone,
      rainbow7 = plt.odinBlue,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_darker or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.meadHoney,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_lighter,
      header1 = plt.hallGold,
      header2 = plt.feastFire,
      special = plt.odinBlue,
      nontext = plt.bg_lighter,
      whitespace = plt.ashGrey,
      win_separator = plt.bg_lighter,
      indent = plt.bg_light,
      indent_scope = plt.hallGold,
      picker = plt.meadHoney,
      yank = plt.gloryAmber,
      mark = plt.odinBlue,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.ashGrey,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.hallGold,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.hallGold,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.ashGrey,
        fg_selected = plt.fg_light,
        fg_alternate = plt.hallGold,
        indicator = plt.feastFire,
      },
    },
    syn = {
      attribute = plt.gloryAmber,
      boolean = plt.odinBlue,
      comment = plt.ashGrey,
      constant = plt.shieldBronze,
      deprecated = plt.fg_lighter,
      func = plt.hallGold,
      identifier = plt.fg_light,
      keyword = plt.einherjarCrimson,
      method = plt.meadHoney,
      number = plt.odinBlue,
      operator = plt.feastFire,
      parameter = plt.spearSilver,
      preproc = plt.shieldBronze,
      punct = plt.fg_lighter,
      regex = plt.gloryAmber,
      special = plt.runeStone,
      special2 = plt.meadHoney,
      special3 = plt.feastFire,
      statement = plt.einherjarCrimson,
      string = plt.meadHoney,
      symbol = plt.shieldBronze,
      type = plt.odinBlue,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.einherjarCrimson,
      warning = plt.feastFire,
      info = plt.odinBlue,
      ok = plt.meadHoney,
      hint = plt.ashGrey,
      virtual_text_error = plt.einherjarCrimson,
      virtual_text_warning = plt.feastFire,
      virtual_text_info = plt.odinBlue,
      virtual_text_ok = plt.meadHoney,
      virtual_text_hint = plt.ashGrey,
    },
    diff = {
      add = plt.meadHoney,
      add_inline = plt.gloryAmber,
      change = plt.odinBlue,
      change_inline = plt.runeStone,
      delete = plt.einherjarCrimson,
      delete_inline = plt.bg_darker,
      text = plt.hallGold,
    },
    vcs = {
      added = plt.meadHoney,
      changed = plt.odinBlue,
      removed = plt.einherjarCrimson,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.einherjarCrimson,
      green = plt.meadHoney,
      yellow = plt.gloryAmber,
      blue = plt.odinBlue,
      magenta = plt.feastFire,
      cyan = plt.runeStone,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.einherjarCrimson):brighten(0.1):to_hex(),
      green_bright = color(plt.meadHoney):brighten(0.1):to_hex(),
      yellow_bright = color(plt.gloryAmber):brighten(0.1):to_hex(),
      blue_bright = color(plt.odinBlue):brighten(0.1):to_hex(),
      magenta_bright = color(plt.feastFire):brighten(0.1):to_hex(),
      cyan_bright = color(plt.runeStone):brighten(0.1):to_hex(),
      white_bright = plt.fg_darkest,
      indexed1 = plt.meadHoney,
      indexed2 = plt.odinBlue,
    },
  }
end

return {
  name = "Asgard – Valhöll",
  author = "PrismPunk",
  description = "Hall of the slain — warrior's gold, feast fire, Odin's blue, mead honey. "
    .. "Valhöll (Valhalla) is Odin's majestic hall in Asgard where the Einherjar — warriors who "
    .. "died gloriously in battle — feast and prepare for Ragnarök. The hall gleams with golden "
    .. "shields on its walls, and mead flows endlessly from the goat Heiðrún. Each day the warriors "
    .. "fight, and each night they feast, their wounds healed, celebrating eternal warrior glory. "
    .. "This theme captures the hall's vibrant energy — deep earth tones anchor the ancient wooden "
    .. "foundations, while warrior's gold and bronze shields gleam on the walls. Feast fire crackles "
    .. "with warmth and crimson battle-blood, mead honey flows golden and sweet, while Odin's watchful "
    .. "blue and rune stone grey remind us whose hall this is. The palette balances celebration with "
    .. "solemnity — glory earned through death, honor forged in battle.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.ashGrey,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.einherjarCrimson,
    base09 = palette.feastFire,
    base0A = palette.meadHoney,
    base0B = palette.meadHoney,
    base0C = palette.runeStone,
    base0D = palette.odinBlue,
    base0E = palette.hallGold,
    base0F = palette.shieldBronze,
  },
  palette = palette,
  get = M.get,
}
