local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0d0d0d",
  bg_darker = "#1a1a1a",
  bg_dark = "#262626",
  bg_mid = "#333333",
  bg_light = "#404040",
  bg_lighter = "#4d4d4d",
  bg_lightest = "#595959",
  bg_alt1 = "#666666",
  bg_alt2 = "#737373",
  bg_alt3 = "#808080",
  bg_alt4 = "#8c8c8c",
  fg_darkest = "#f0f0f0",
  fg_dark = "#e6e6e6",
  fg_mid = "#d9d9d9",
  fg_light = "#cccccc",
  fg_lighter = "#bfbfbf",
  fg_lightest = "#b3b3b3",
  silentSteel = "#708090",
  ironResolve = "#778899",
  gridarvolr = "#5f9ea0",
  fenrisJaw = "#7a9a4a",
  thickLeather = "#a08b74",
  forestWatch = "#6a9a6a",
  mutedVengeance = "#82a82e",
  ashGrey = "#a9a9a9",
  stoneQuiet = "#7a7a7a",
  endlessWait = "#9acd32",
  ragnarokMoment = "#7cfc00",
  immortalWhite = "#ffffff",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.silentSteel,
      insert = plt.mutedVengeance,
      visual = plt.endlessWait,
      replace = plt.ragnarokMoment,
      command = plt.ironResolve,
    },
    accent = {
      accent1 = plt.silentSteel,
      accent2 = plt.mutedVengeance,
      accent3 = plt.endlessWait,
      accent4 = plt.ironResolve,
      accent5 = plt.ashGrey,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.silentSteel,
      rainbow2 = plt.ironResolve,
      rainbow3 = plt.mutedVengeance,
      rainbow4 = plt.endlessWait,
      rainbow5 = plt.forestWatch,
      rainbow6 = plt.thickLeather,
      rainbow7 = plt.ashGrey,
    },
    ui = {
      fg = plt.fg_darkest,
      fg_dim = plt.fg_dark,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_light,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_dark or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.mutedVengeance,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.silentSteel,
      header2 = plt.mutedVengeance,
      special = plt.endlessWait,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_alt2,
      win_separator = plt.stoneQuiet,
      indent = plt.bg_light,
      indent_scope = plt.silentSteel,
      picker = plt.endlessWait,
      yank = plt.mutedVengeance,
      mark = plt.silentSteel,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.bg_alt3,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.mutedVengeance,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.stoneQuiet,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = "none",
        fg_border = plt.bg_alt2,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.bg_alt3,
        fg_selected = plt.fg_light,
        fg_alternate = plt.silentSteel,
        indicator = plt.mutedVengeance,
      },
    },
    syn = {
      attribute = plt.mutedVengeance,
      boolean = plt.endlessWait,
      comment = plt.stoneQuiet,
      constant = plt.ironResolve,
      deprecated = plt.bg_alt3,
      func = plt.silentSteel,
      identifier = plt.fg_light,
      keyword = plt.gridarvolr,
      method = plt.silentSteel,
      number = plt.mutedVengeance,
      operator = plt.fg_lighter,
      parameter = plt.fg_mid,
      preproc = plt.endlessWait,
      punct = plt.fg_light,
      regex = plt.thickLeather,
      special = plt.ragnarokMoment,
      special2 = plt.ashGrey,
      special3 = plt.immortalWhite,
      statement = plt.fenrisJaw,
      string = plt.thickLeather,
      symbol = plt.forestWatch,
      type = plt.fg_light,
      variable = plt.fg_light,
    },
    diag = {
      error = plt.ragnarokMoment,
      warning = plt.endlessWait,
      info = plt.silentSteel,
      ok = plt.mutedVengeance,
      hint = plt.ironResolve,
      virtual_text_error = plt.ragnarokMoment,
      virtual_text_warning = plt.endlessWait,
      virtual_text_info = plt.silentSteel,
      virtual_text_ok = plt.mutedVengeance,
      virtual_text_hint = plt.ironResolve,
    },
    diff = {
      add = plt.mutedVengeance,
      add_inline = plt.endlessWait,
      change = plt.silentSteel,
      change_inline = plt.ironResolve,
      delete = plt.ragnarokMoment,
      delete_inline = plt.ashGrey,
      text = plt.silentSteel,
    },
    vcs = {
      added = plt.mutedVengeance,
      changed = plt.silentSteel,
      removed = plt.ragnarokMoment,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.ragnarokMoment,
      green = plt.mutedVengeance,
      yellow = plt.endlessWait,
      blue = plt.silentSteel,
      magenta = plt.ironResolve,
      cyan = plt.ashGrey,
      white = plt.fg_darkest,
      black_bright = color(plt.bg_darkest):brighten(0.3):to_hex(),
      red_bright = color(plt.ragnarokMoment):brighten(0.1):to_hex(),
      green_bright = color(plt.mutedVengeance):brighten(0.2):to_hex(),
      yellow_bright = color(plt.endlessWait):brighten(0.1):to_hex(),
      blue_bright = color(plt.silentSteel):brighten(0.2):to_hex(),
      magenta_bright = color(plt.ironResolve):brighten(0.2):to_hex(),
      cyan_bright = color(plt.ashGrey):brighten(0.1):to_hex(),
      white_bright = plt.immortalWhite,
      indexed1 = plt.thickLeather,
      indexed2 = plt.forestWatch,
    },
  }
end

return {
  name = "Asgard – Víðarr",
  author = "PrismPunk",
  description = "Silent God — charcoal greys, slate blues, muted olive greens, iron resolve. "
    .. "Víðarr is the silent god, second only to Thor in strength, and he speaks not a "
    .. "word. He dwells in Víði, a land of tall grass and thick forests, and his shoe is "
    .. "made from all the leather scraps discarded by cobblers since the beginning of "
    .. "time — for it must be strong enough to stand in the jaws of Fenrir. At Ragnarök, "
    .. "when the great wolf devours Odin, Víðarr will step forward without a sound. He "
    .. "will place one foot in Fenrir's lower jaw and with his hands tear the beast's "
    .. "mouth apart, avenging his father in silence. He is patience incarnate, the "
    .. "revenge that waits through ages, the strength that needs no boast. This palette "
    .. "is stone and steel — charcoal-grey backgrounds rising through neutral greys, "
    .. "contrasted with slate-blue keywords (`silentSteel`, `ironResolve`), dark olive "
    .. "statements (`fenrisJaw`), muted olive-green accents (`mutedVengeance`), and "
    .. "leather-brown strings (`thickLeather`). The brightest accent is `ragnarokMoment` "
    .. "— a sharp lawn green for errors, the instant vengeance strikes. This is the grey "
    .. "stone of endless waiting, the blue-grey of iron will, and the muted green of "
    .. "forest shadows where silence is strength.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.bg_alt2,
    base05 = palette.fg_mid,
    base06 = palette.fg_dark,
    base07 = palette.fg_darkest,
    base08 = palette.ragnarokMoment,
    base09 = palette.endlessWait,
    base0A = palette.mutedVengeance,
    base0B = palette.forestWatch,
    base0C = palette.ashGrey,
    base0D = palette.silentSteel,
    base0E = palette.ironResolve,
    base0F = palette.thickLeather,
  },
  palette = palette,
  get = M.get,
}
