local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0c0a05",
  bg_darker = "#14130a",
  bg_dark = "#1d1c0f",
  bg_mid = "#282614",
  bg_light = "#353219",
  bg_lighter = "#45401e",
  bg_lightest = "#574f23",
  bg_alt1 = "#6b6028",
  bg_alt2 = "#81732d",
  bg_alt3 = "#9e8a32",
  bg_alt4 = "#c0a637",
  fg_lightest = "#aaaaaa",
  fg_light = "#969696",
  fg_mid = "#828282",
  fg_dark = "#6e6e6e",
  goldRoof = "#ffd700",
  riverSpanning = "#ffe14d",
  entryToDeath = "#ffeb7a",
  resonantCrossing = "#fff5a7",
  echoingBridge = "#e8cf3c",
  gjollRiver = "#c0a637",
  bridgeResonance = "#9e8a32",
  deathThreshold = "#81732d",
  goldenPath = "#6b6028",
  bridgeEcho = "#5a5a5a",
  shadowCrossing = "#464646",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.goldRoof,
      insert = plt.entryToDeath,
      visual = plt.resonantCrossing,
      replace = plt.echoingBridge,
      command = plt.gjollRiver,
    },
    accent = {
      accent1 = plt.goldRoof,
      accent2 = plt.entryToDeath,
      accent3 = plt.resonantCrossing,
      accent4 = plt.fg_light,
      accent5 = plt.echoingBridge,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.goldRoof,
      rainbow2 = plt.riverSpanning,
      rainbow3 = plt.entryToDeath,
      rainbow4 = plt.resonantCrossing,
      rainbow5 = plt.echoingBridge,
      rainbow6 = plt.gjollRiver,
      rainbow7 = plt.bridgeResonance,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.resonantCrossing,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.goldRoof,
      header2 = plt.echoingBridge,
      special = plt.gjollRiver,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.entryToDeath,
      indent = plt.bg_light,
      indent_scope = plt.goldRoof,
      picker = plt.resonantCrossing,
      yank = plt.gjollRiver,
      mark = plt.deathThreshold,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.goldRoof,
        indicator = plt.echoingBridge,
      },
    },
    syn = {
      attribute = plt.gjollRiver,
      boolean = plt.deathThreshold,
      comment = plt.fg_mid,
      constant = plt.resonantCrossing,
      deprecated = plt.fg_dark,
      func = plt.echoingBridge,
      identifier = plt.fg_lightest,
      keyword = plt.deathThreshold,
      method = plt.echoingBridge,
      number = plt.resonantCrossing,
      operator = plt.entryToDeath,
      parameter = plt.goldenPath,
      preproc = plt.gjollRiver,
      punct = plt.fg_mid,
      regex = plt.deathThreshold,
      special = plt.gjollRiver,
      special2 = plt.deathThreshold,
      special3 = plt.goldenPath,
      statement = plt.deathThreshold,
      string = plt.echoingBridge,
      symbol = plt.entryToDeath,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.echoingBridge,
      warning = plt.resonantCrossing,
      info = plt.goldRoof,
      ok = plt.bridgeResonance,
      hint = plt.gjollRiver,
      virtual_text_error = plt.echoingBridge,
      virtual_text_warning = plt.resonantCrossing,
      virtual_text_info = plt.goldRoof,
      virtual_text_ok = plt.bridgeResonance,
      virtual_text_hint = plt.gjollRiver,
    },
    diff = {
      add = plt.bridgeResonance,
      add_inline = plt.entryToDeath,
      change = plt.resonantCrossing,
      change_inline = plt.deathThreshold,
      delete = plt.echoingBridge,
      delete_inline = plt.goldRoof,
      text = plt.gjollRiver,
    },
    vcs = {
      added = plt.bridgeResonance,
      changed = plt.resonantCrossing,
      removed = plt.echoingBridge,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.echoingBridge,
      green = plt.bridgeResonance,
      yellow = plt.gjollRiver,
      blue = plt.goldRoof,
      magenta = plt.resonantCrossing,
      cyan = plt.entryToDeath,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.echoingBridge):brighten(0.2):to_hex(),
      green_bright = color(plt.bridgeResonance):brighten(0.15):to_hex(),
      yellow_bright = color(plt.gjollRiver):brighten(0.15):to_hex(),
      blue_bright = color(plt.goldRoof):brighten(0.15):to_hex(),
      magenta_bright = color(plt.resonantCrossing):brighten(0.2):to_hex(),
      cyan_bright = color(plt.entryToDeath):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.goldenPath,
      indexed2 = plt.deathThreshold,
    },
  }
end

return {
  name = "Helheim – Gjallarbru",
  author = "PrismPunk",
  description = "Echoing bridge — gold-roofed, river-spanning, entry to death, resonant crossing. "
    .. "Gjallarbru is the bridge that spans the river Gjöll, the boundary between the "
    .. "living world and Helheim. Its roof is covered in glittering gold, and it echoes "
    .. "with the sound of every soul that crosses it. Móðguðr stands guard here, "
    .. "challenging all who would pass. The bridge is both magnificent and ominous — a "
    .. "golden path that leads only to death, a threshold that once crossed cannot be "
    .. "uncrossed. The palette uses rich golds and dark earth tones, capturing the "
    .. "paradox of a beautiful structure that serves as the final passage, where the "
    .. "echo of footsteps resonates with finality.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.echoingBridge,
    base09 = palette.resonantCrossing,
    base0A = palette.goldenPath,
    base0B = palette.bridgeResonance,
    base0C = palette.gjollRiver,
    base0D = palette.goldRoof,
    base0E = palette.entryToDeath,
    base0F = palette.deathThreshold,
  },
  palette = palette,
  get = M.get,
}
