local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0a0505",
  bg_darker = "#140a0a",
  bg_dark = "#1e0f0f",
  bg_mid = "#281414",
  bg_light = "#321919",
  bg_lighter = "#3c1e1e",
  bg_lightest = "#462323",
  bg_alt1 = "#502828",
  bg_alt2 = "#5a2d2d",
  bg_alt3 = "#643232",
  bg_alt4 = "#6e3737",
  fg_lightest = "#828282",
  fg_light = "#6e6e6e",
  fg_mid = "#5a5a5a",
  fg_dark = "#464646",
  bloodStained = "#8b0000",
  ragnarokHowl = "#a01010",
  bridgeGuardian = "#b52020",
  chainedBeast = "#ca3030",
  helHound = "#df4040",
  corpseTeeth = "#783c3c",
  ironChain = "#323232",
  guardianFury = "#824141",
  deathWatch = "#8c4646",
  boundRage = "#964b4b",
  helGate = "#a05050",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.bloodStained,
      insert = plt.bridgeGuardian,
      visual = plt.chainedBeast,
      replace = plt.helHound,
      command = plt.helGate,
    },
    accent = {
      accent1 = plt.bloodStained,
      accent2 = plt.bridgeGuardian,
      accent3 = plt.chainedBeast,
      accent4 = plt.fg_light,
      accent5 = plt.helHound,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.bloodStained,
      rainbow2 = plt.ragnarokHowl,
      rainbow3 = plt.bridgeGuardian,
      rainbow4 = plt.chainedBeast,
      rainbow5 = plt.helHound,
      rainbow6 = plt.guardianFury,
      rainbow7 = plt.helGate,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.chainedBeast,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.bloodStained,
      header2 = plt.helHound,
      special = plt.helGate,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.bridgeGuardian,
      indent = plt.bg_light,
      indent_scope = plt.bloodStained,
      picker = plt.chainedBeast,
      yank = plt.helGate,
      mark = plt.deathWatch,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.bloodStained,
        indicator = plt.helHound,
      },
    },
    syn = {
      attribute = plt.helGate,
      boolean = plt.deathWatch,
      comment = plt.fg_mid,
      constant = plt.chainedBeast,
      deprecated = plt.fg_dark,
      func = plt.helHound,
      identifier = plt.fg_lightest,
      keyword = plt.deathWatch,
      method = plt.helHound,
      number = plt.chainedBeast,
      operator = plt.bridgeGuardian,
      parameter = plt.corpseTeeth,
      preproc = plt.helGate,
      punct = plt.fg_mid,
      regex = plt.deathWatch,
      special = plt.helGate,
      special2 = plt.deathWatch,
      special3 = plt.corpseTeeth,
      statement = plt.deathWatch,
      string = plt.helHound,
      symbol = plt.bridgeGuardian,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.helHound,
      warning = plt.chainedBeast,
      info = plt.bloodStained,
      ok = plt.guardianFury,
      hint = plt.helGate,
      virtual_text_error = plt.helHound,
      virtual_text_warning = plt.chainedBeast,
      virtual_text_info = plt.bloodStained,
      virtual_text_ok = plt.guardianFury,
      virtual_text_hint = plt.helGate,
    },
    diff = {
      add = plt.guardianFury,
      add_inline = plt.bridgeGuardian,
      change = plt.chainedBeast,
      change_inline = plt.deathWatch,
      delete = plt.helHound,
      delete_inline = plt.bloodStained,
      text = plt.helGate,
    },
    vcs = {
      added = plt.guardianFury,
      changed = plt.chainedBeast,
      removed = plt.helHound,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.helHound,
      green = plt.guardianFury,
      yellow = plt.helGate,
      blue = plt.bloodStained,
      magenta = plt.chainedBeast,
      cyan = plt.bridgeGuardian,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.helHound):brighten(0.2):to_hex(),
      green_bright = color(plt.guardianFury):brighten(0.15):to_hex(),
      yellow_bright = color(plt.helGate):brighten(0.15):to_hex(),
      blue_bright = color(plt.bloodStained):brighten(0.15):to_hex(),
      magenta_bright = color(plt.chainedBeast):brighten(0.2):to_hex(),
      cyan_bright = color(plt.bridgeGuardian):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.corpseTeeth,
      indexed2 = plt.deathWatch,
    },
  }
end

return {
  name = "Helheim – Garmr",
  author = "PrismPunk",
  description = "Hel-hound — blood-stained, Ragnarok's howl, bridge guardian, chained beast. "
    .. "Garmr is the monstrous hound chained at the entrance to Helheim, guarding the "
    .. "bridge Gjallarbru that leads to Hel's realm. His chest is perpetually stained "
    .. "with the blood of the dead who pass by, and his howl is said to herald Ragnarok. "
    .. "During the final battle, he will break free from his chains and fight Tyr, the "
    .. "one-handed god of war, and both will slay each other. Garmr embodies primal rage "
    .. "barely contained, eternal vigilance at death's threshold, and the inevitability "
    .. "of apocalypse. The palette is dominated by deep blood reds against dark browns "
    .. "and greys — the colors of dried blood, iron chains, and the shadowy entrance to "
    .. "the underworld where this beast eternally waits.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.helHound,
    base09 = palette.chainedBeast,
    base0A = palette.corpseTeeth,
    base0B = palette.guardianFury,
    base0C = palette.helGate,
    base0D = palette.bloodStained,
    base0E = palette.bridgeGuardian,
    base0F = palette.deathWatch,
  },
  palette = palette,
  get = M.get,
}
