local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#08070a",
  bg_darker = "#110e14",
  bg_dark = "#19161e",
  bg_mid = "#231f29",
  bg_light = "#2f2935",
  bg_lighter = "#3c3443",
  bg_lightest = "#4a4052",
  bg_alt1 = "#594e63",
  bg_alt2 = "#6d6177",
  bg_alt3 = "#84788d",
  bg_alt4 = "#a495a8",
  fg_lightest = "#ffffff",
  fg_light = "#f0f0f0",
  fg_mid = "#e0e0e0",
  fg_dark = "#d6c9d8",
  gjallarbruKeeper = "#c0c0c0",
  tollTaker = "#cacaca",
  thresholdGuardian = "#d4d4d4",
  bridgeMaiden = "#dedede",
  deathsPassage = "#e8e8e8",
  helheimGate = "#f2f2f2",
  soulCrossing = "#fcfcfc",
  purpleMist = "#a495a8",
  bridgeShadow = "#84788d",
  maidenWatch = "#6d6177",
  tollPrice = "#594e63",
}

local M = {}

---@param plt table|nil
---@param opts table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.gjallarbruKeeper,
      insert = plt.thresholdGuardian,
      visual = plt.bridgeMaiden,
      replace = plt.deathsPassage,
      command = plt.helheimGate,
    },
    accent = {
      accent1 = plt.gjallarbruKeeper,
      accent2 = plt.thresholdGuardian,
      accent3 = plt.bridgeMaiden,
      accent4 = plt.fg_light,
      accent5 = plt.deathsPassage,
      invert = plt.bg_mid,
    },
    rainbow = {
      rainbow1 = plt.gjallarbruKeeper,
      rainbow2 = plt.tollTaker,
      rainbow3 = plt.thresholdGuardian,
      rainbow4 = plt.bridgeMaiden,
      rainbow5 = plt.deathsPassage,
      rainbow6 = plt.helheimGate,
      rainbow7 = plt.soulCrossing,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_darkest,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      cursorline = plt.bg_mid,
      bg_highlight = plt.bg_light,
      bg_search = plt.bridgeMaiden,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt1,
      header1 = plt.gjallarbruKeeper,
      header2 = plt.deathsPassage,
      special = plt.helheimGate,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.thresholdGuardian,
      indent = plt.bg_light,
      indent_scope = plt.gjallarbruKeeper,
      picker = plt.bridgeMaiden,
      yank = plt.helheimGate,
      mark = plt.maidenWatch,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.gjallarbruKeeper,
        indicator = plt.deathsPassage,
      },
    },
    syn = {
      attribute = plt.helheimGate,
      boolean = plt.maidenWatch,
      comment = plt.fg_mid,
      constant = plt.bridgeMaiden,
      deprecated = plt.fg_dark,
      func = plt.deathsPassage,
      identifier = plt.fg_lightest,
      keyword = plt.maidenWatch,
      method = plt.deathsPassage,
      number = plt.bridgeMaiden,
      operator = plt.thresholdGuardian,
      parameter = plt.purpleMist,
      preproc = plt.helheimGate,
      punct = plt.fg_mid,
      regex = plt.maidenWatch,
      special = plt.helheimGate,
      special2 = plt.maidenWatch,
      special3 = plt.purpleMist,
      statement = plt.maidenWatch,
      string = plt.deathsPassage,
      symbol = plt.thresholdGuardian,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.deathsPassage,
      warning = plt.bridgeMaiden,
      info = plt.gjallarbruKeeper,
      ok = plt.bridgeShadow,
      hint = plt.helheimGate,
      virtual_text_error = plt.deathsPassage,
      virtual_text_warning = plt.bridgeMaiden,
      virtual_text_info = plt.gjallarbruKeeper,
      virtual_text_ok = plt.bridgeShadow,
      virtual_text_hint = plt.helheimGate,
    },
    diff = {
      add = plt.bridgeShadow,
      add_inline = plt.thresholdGuardian,
      change = plt.bridgeMaiden,
      change_inline = plt.maidenWatch,
      delete = plt.deathsPassage,
      delete_inline = plt.gjallarbruKeeper,
      text = plt.helheimGate,
    },
    vcs = {
      added = plt.bridgeShadow,
      changed = plt.bridgeMaiden,
      removed = plt.deathsPassage,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.deathsPassage,
      green = plt.bridgeShadow,
      yellow = plt.helheimGate,
      blue = plt.gjallarbruKeeper,
      magenta = plt.bridgeMaiden,
      cyan = plt.thresholdGuardian,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.deathsPassage):brighten(0.2):to_hex(),
      green_bright = color(plt.bridgeShadow):brighten(0.15):to_hex(),
      yellow_bright = color(plt.helheimGate):brighten(0.15):to_hex(),
      blue_bright = color(plt.gjallarbruKeeper):brighten(0.15):to_hex(),
      magenta_bright = color(plt.bridgeMaiden):brighten(0.2):to_hex(),
      cyan_bright = color(plt.thresholdGuardian):brighten(0.15):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.15):to_hex(),
      indexed1 = plt.purpleMist,
      indexed2 = plt.maidenWatch,
    },
  }
end

return {
  name = "Helheim – Móðguðr",
  author = "PrismPunk",
  description = "Bridge maiden — Gjallarbru's keeper, toll-taker, threshold guardian. "
    .. "Móðguðr is the maiden who guards Gjallarbru, the bridge that spans the river "
    .. "Gjöll and leads to Helheim. She challenges all who would cross, asking their "
    .. "name and lineage, and judges whether they have the right to enter the realm of "
    .. "the dead. She is neither cruel nor kind, but dutiful — a threshold guardian who "
    .. "maintains the boundary between the living world and the dead. The palette uses "
    .. "silvery greys and pale purples, evoking the misty, liminal space of the bridge "
    .. "itself — neither fully in the world of the living nor completely in death's "
    .. "domain, a place of passage and judgment where Móðguðr eternally stands watch.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_mid,
    base03 = palette.bg_light,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.deathsPassage,
    base09 = palette.bridgeMaiden,
    base0A = palette.purpleMist,
    base0B = palette.bridgeShadow,
    base0C = palette.helheimGate,
    base0D = palette.gjallarbruKeeper,
    base0E = palette.thresholdGuardian,
    base0F = palette.maidenWatch,
  },
  palette = palette,
  get = M.get,
}
