local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0F0808",
  bg_darker = "#180C0C",
  bg_dark = "#241010",
  bg_mid = "#3A1818",
  bg_light = "#5A2828",
  bg_lighter = "#803838",
  bg_lightest = "#B34A4A",

  fg_lightest = "#FFE8E8",
  fg_light = "#FFC8C8",
  fg_mid = "#FFA8A8",
  fg_dark = "#E68C8C",

  bg_alt1 = "#1C0F0F",
  bg_alt2 = "#140A0A",
  bg_alt3 = "#2A1414",
  bg_alt4 = "#220E0E",

  sniperRed = "#FF1A1A",
  bloodScope = "#FF3333",
  targetGold = "#FFAA00",
  thermalCyan = "#00FFFF",
  nightvisionGreen = "#00FF88",
  ricochetPink = "#FF4488",
  tracerWhite = "#FFE8E8",
  muzzleFlash = "#FFFF66",
  killzoneViolet = "#CC00FF",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.sniperRed,
      insert = plt.thermalCyan,
      visual = plt.bloodScope,
      replace = plt.ricochetPink,
      command = plt.targetGold,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.muzzleFlash,
      bg_visual = plt.killzoneViolet,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.targetGold,
      header2 = plt.sniperRed,
      special = plt.nightvisionGreen,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.bloodScope,
      indent = plt.bg_lighter,
      indent_scope = plt.sniperRed,
      picker = plt.ricochetPink,
      yank = plt.muzzleFlash,
      mark = plt.thermalCyan,
      scrollbar = plt.bg_lighter,

      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.targetGold,
        bg_alternate = plt.bg_darkest,
        indicator = plt.sniperRed,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.targetGold,
      accent2 = plt.sniperRed,
      accent3 = plt.thermalCyan,
      accent4 = plt.bloodScope,
      accent5 = plt.killzoneViolet,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.targetGold,
      rainbow2 = plt.sniperRed,
      rainbow3 = plt.ricochetPink,
      rainbow4 = plt.thermalCyan,
      rainbow5 = plt.killzoneViolet,
      rainbow6 = plt.nightvisionGreen,
      rainbow7 = plt.muzzleFlash,
    },

    syn = {
      attribute = plt.targetGold,
      boolean = plt.nightvisionGreen,
      comment = plt.fg_dark,
      constant = plt.targetGold,
      deprecated = plt.fg_mid,
      func = plt.sniperRed,
      identifier = plt.fg_lightest,
      keyword = plt.bloodScope,
      method = plt.thermalCyan,
      number = plt.ricochetPink,
      operator = plt.thermalCyan,
      parameter = plt.fg_mid,
      preproc = plt.sniperRed,
      punct = plt.fg_mid,
      regex = plt.killzoneViolet,
      statement = plt.bloodScope,
      string = plt.targetGold,
      symbol = plt.thermalCyan,
      type = plt.tracerWhite,
      variable = plt.fg_lightest,
      special = plt.muzzleFlash,
      special2 = plt.sniperRed,
      special3 = plt.bloodScope,
    },

    vcs = { added = plt.nightvisionGreen, removed = plt.bloodScope, changed = plt.targetGold },
    diff = {
      add = plt.nightvisionGreen,
      change = plt.targetGold,
      delete = plt.sniperRed,
      text = plt.killzoneViolet,
    },
    diag = {
      ok = plt.nightvisionGreen,
      error = plt.sniperRed,
      warning = plt.muzzleFlash,
      info = plt.thermalCyan,
      hint = plt.ricochetPink,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.sniperRed,
      green = plt.nightvisionGreen,
      yellow = plt.targetGold,
      blue = plt.thermalCyan,
      magenta = plt.ricochetPink,
      cyan = plt.thermalCyan,
      white = plt.fg_light,
      black_bright = color(plt.bg_alt3):brighten(0.6):to_hex(),
      red_bright = color(plt.sniperRed):brighten(0.2):to_hex(),
      green_bright = color(plt.nightvisionGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.targetGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.thermalCyan):brighten(0.3):to_hex(),
      magenta_bright = color(plt.ricochetPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.thermalCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.targetGold,
      indexed2 = plt.sniperRed,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@constant"] = plt.targetGold,
      ["@string"] = plt.targetGold,
      ["@string.regex"] = plt.killzoneViolet,
      ["@number"] = plt.ricochetPink,
      ["@function"] = plt.sniperRed,
      ["@keyword"] = plt.bloodScope,
      ["@operator"] = plt.thermalCyan,
      ["@variable"] = plt.fg_lightest,
      ["@type"] = plt.tracerWhite,
      ["@tag"] = plt.bloodScope,
      ["@markup.strong"] = { fg = plt.targetGold, bold = true },
      ["@diff.plus"] = plt.nightvisionGreen,
      ["@diff.minus"] = plt.sniperRed,
      ["@conceal"] = plt.killzoneViolet,
    },

    lsp = {
      ["@lsp.type.class"] = plt.tracerWhite,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.targetGold,
    },
  }
end

return {
  name = "Crime Syndicate – Deadeye",
  author = "PrismPunk.nvim",
  description = "Earth-3’s Deadshot. One bullet, one kill, from three continents away. "
    .. "Cold, precise, and always watching through the scope.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.sniperRed,
    base09 = palette.ricochetPink,
    base0A = palette.targetGold,
    base0B = palette.nightvisionGreen,
    base0C = palette.thermalCyan,
    base0D = palette.bloodScope,
    base0E = palette.killzoneViolet,
    base0F = palette.muzzleFlash,
  },

  palette = palette,
  get = M.get,
}
