local palette = {
  bg_darkest = "#0F0A0A",
  bg_darker = "#1A1212",
  bg_dark = "#261818",
  bg_mid = "#3D2828",
  bg_light = "#5A3C3C",
  bg_lighter = "#805050",
  bg_lightest = "#C27E7D",

  fg_lightest = "#FEF7BB",
  fg_light = "#F0E8A8",
  fg_mid = "#E0D890",
  fg_dark = "#91A8B4",

  bg_alt1 = "#1E1414",
  bg_alt2 = "#140C0C",
  bg_alt3 = "#2C1E1E",
  bg_alt4 = "#221616",

  corpseFire = "#C27E7D",
  radiationGold = "#FAD31A",
  meltdownYellow = "#EED11F",
  nuclearCream = "#FEF7BB",
  decaySteel = "#59879B",
  toxicAsh = "#91A8B4",
}

local M = {}

M.get = function(opts, plt)
  return {
    modes = {
      normal = plt.corpseFire,
      insert = plt.decaySteel,
      visual = plt.radiationGold,
      replace = plt.meltdownYellow,
      command = plt.nuclearCream,
    },

    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg_m4 = plt.bg_alt4,
      bg_m3 = plt.bg_alt3,
      bg_m2 = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_dim = plt.bg_darker,
      bg = plt.bg_darkest,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = opts.gutter and plt.bg_light or "none",
      bg_cursorline = plt.bg_mid,
      bg_cursorline_alt = plt.bg_light,
      bg_search = plt.radiationGold,
      bg_visual = plt.toxicAsh,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt4,
      header1 = plt.meltdownYellow,
      header2 = plt.corpseFire,
      special = plt.decaySteel,
      nontext = plt.bg_lighter,
      whitespace = plt.bg_lightest,
      win_separator = plt.corpseFire,
      indent = plt.bg_lighter,
      indent_scope = plt.corpseFire,
      picker = plt.nuclearCream,
      yank = plt.radiationGold,
      mark = plt.meltdownYellow,
      scrollbar = plt.bg_lighter,

      tabline = {
        bg = plt.bg_darkest,
        fg_selected = plt.fg_lightest,
        bg_selected = plt.bg_dark,
        fg_inactive = plt.fg_mid,
        bg_inactive = plt.bg_darkest,
        fg_alternate = plt.meltdownYellow,
        bg_alternate = plt.bg_darkest,
        indicator = plt.corpseFire,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lightest,
      },
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bg_lighter,
        bg_border = plt.bg_mid,
      },
    },

    accent = {
      accent1 = plt.radiationGold,
      accent2 = plt.corpseFire,
      accent3 = plt.decaySteel,
      accent4 = plt.meltdownYellow,
      accent5 = plt.toxicAsh,
      invert = plt.bg_light,
    },

    rainbow = {
      rainbow1 = plt.meltdownYellow,
      rainbow2 = plt.corpseFire,
      rainbow3 = plt.radiationGold,
      rainbow4 = plt.decaySteel,
      rainbow5 = plt.nuclearCream,
      rainbow6 = plt.toxicAsh,
      rainbow7 = plt.corpseFire,
    },

    syn = {
      attribute = plt.meltdownYellow,
      boolean = plt.decaySteel,
      comment = plt.fg_dark,
      constant = plt.radiationGold,
      deprecated = plt.fg_mid,
      func = plt.corpseFire,
      identifier = plt.fg_lightest,
      keyword = plt.decaySteel,
      method = plt.toxicAsh,
      number = plt.nuclearCream,
      operator = plt.decaySteel,
      parameter = plt.fg_mid,
      preproc = plt.corpseFire,
      punct = plt.fg_mid,
      regex = plt.radiationGold,
      statement = plt.decaySteel,
      string = plt.nuclearCream,
      symbol = plt.toxicAsh,
      type = plt.fg_lightest,
      variable = plt.fg_lightest,
      special = plt.meltdownYellow,
      special2 = plt.corpseFire,
      special3 = plt.decaySteel,
    },

    vcs = { added = plt.decaySteel, removed = plt.corpseFire, changed = plt.radiationGold },
    diff = { add = plt.decaySteel, change = plt.radiationGold, delete = plt.corpseFire, text = plt.toxicAsh },
    diag = {
      ok = plt.decaySteel,
      error = plt.corpseFire,
      warning = plt.meltdownYellow,
      info = plt.radiationGold,
      hint = plt.nuclearCream,
    },

    term = {
      black = plt.bg_alt3,
      red = plt.corpseFire,
      green = plt.decaySteel,
      yellow = plt.radiationGold,
      blue = plt.decaySteel,
      magenta = plt.toxicAsh,
      cyan = plt.decaySteel,
      white = plt.fg_light,
      black_bright = "#3C2828",
      red_bright = "#D69897",
      green_bright = "#6B9DB0",
      yellow_bright = "#FFE566",
      blue_bright = "#6BA3B8",
      magenta_bright = "#A8BCC8",
      cyan_bright = "#6BA3B8",
      white_bright = "#FFF8D0",
      indexed1 = plt.radiationGold,
      indexed2 = plt.corpseFire,
    },

    treesitter = {
      ["@comment"] = plt.fg_dark,
      ["@constant"] = plt.radiationGold,
      ["@string"] = plt.nuclearCream,
      ["@string.regex"] = plt.meltdownYellow,
      ["@number"] = plt.nuclearCream,
      ["@function"] = plt.corpseFire,
      ["@keyword"] = plt.decaySteel,
      ["@operator"] = plt.toxicAsh,
      ["@variable"] = plt.fg_lightest,
      ["@type"] = plt.fg_lightest,
      ["@punctuation"] = plt.fg_mid,
      ["@tag"] = plt.decaySteel,
      ["@markup.strong"] = { fg = plt.radiationGold, bold = true },
      ["@diff.plus"] = plt.decaySteel,
      ["@diff.minus"] = plt.corpseFire,
      ["@conceal"] = plt.toxicAsh,
    },

    lsp = {
      ["@lsp.type.class"] = plt.fg_lightest,
      ["@lsp.type.property"] = plt.fg_light,
      ["@lsp.mod.deprecated"] = { fg = plt.fg_mid, strikethrough = true },
      ["@lsp.mod.readonly"] = plt.radiationGold,
    },
  }
end

return {
  name = "Crime Syndicate – Deathstorm",
  author = "PrismPunk.nvim",
  description = "The walking corpse of Firestorm. His flames are blood-red decay. "
    .. "His core leaks radioactive gold. Everything burns cold.",

  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.bg_light,
    base05 = palette.fg_mid,
    base06 = palette.fg_lightest,
    base07 = palette.fg_light,
    base08 = palette.corpseFire,
    base09 = palette.meltdownYellow,
    base0A = palette.radiationGold,
    base0B = palette.nuclearCream,
    base0C = palette.decaySteel,
    base0D = palette.toxicAsh,
    base0E = palette.corpseFire,
    base0F = palette.radiationGold,
  },

  palette = palette,
  get = M.get,
}
