local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0614",
  bg_darker = "#0F0B1A",
  bg_dark = "#161122",
  bg_mid = "#1D172A",
  bg_light = "#251E35",
  bg_lighter = "#2D2640",
  bg_lightest = "#362E4D",
  fg_lightest = "#EDE7FF",
  fg_light = "#D8D0F0",
  fg_mid = "#B8A8D8",
  fg_dark = "#8878A8",
  bg_alt1 = "#120D1E",
  bg_alt2 = "#080410",
  bg_alt3 = "#1A1428",
  bg_alt4 = "#050209",
  geniusPurple = "#9D4EDD",
  geniusPurpleBright = "#B565FF",
  geniusPurpleCore = "#8338EC",
  geniusPurpleDeep = "#6B2FC7",
  geniusPurpleDark = "#4E1F8C",
  techCyan = "#00D9FF",
  techCyanBright = "#33E4FF",
  techCyanCore = "#00B8D4",
  techCyanDeep = "#0097A7",
  circuitGreen = "#39FF14",
  circuitGreenBright = "#5DFF38",
  circuitGreenCore = "#2ECC40",
  circuitGreenDeep = "#229A2F",
  inventionOrange = "#FF9500",
  inventionOrangeBright = "#FFAA33",
  inventionOrangeDeep = "#E67E00",
  dataBlue = "#4D79FF",
  dataBlueBright = "#668CFF",
  dataBlueCore = "#3D5FCC",
  dataBlueDeep = "#2D4799",
  neonPink = "#FF00FF",
  neonPinkBright = "#FF33FF",
  neonPinkDeep = "#CC00CC",
  boStaffWood = "#8B6F47",
  boStaffWoodDark = "#6F5A38",
  boStaffTip = "#D4AF37",
  hologramBlue = "#00FFFF",
  hologramBlueShift = "#00E6E6",
  computerGray = "#6B7A8F",
  computerGrayLight = "#8A95A5",
  computerGrayDark = "#4E5968",
  wireSilver = "#B0B8C0",
  labGreen = "#1B4D3E",
  screenGlow = "#7B2CBF",
  dangerRed = "#E74C3C",
  warningAmber = "#F39C12",
  infoBlue = "#3498DB",
  successGreen = "#27AE60",
  techLab = "#1A0F2E",
  gadgetryPurple = "#7209B7",
  innovationTeal = "#06AED5",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.geniusPurpleCore,
      insert = plt.circuitGreen,
      visual = plt.techCyan,
      replace = plt.dangerRed,
      command = plt.inventionOrange,
    },
    accent = {
      accent1 = plt.geniusPurpleCore,
      accent2 = plt.techCyan,
      accent3 = plt.circuitGreen,
      accent4 = plt.inventionOrange,
      accent5 = plt.dataBlue,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.geniusPurpleBright,
      rainbow2 = plt.techCyanBright,
      rainbow3 = plt.circuitGreenBright,
      rainbow4 = plt.inventionOrangeBright,
      rainbow5 = plt.dataBlueBright,
      rainbow6 = plt.neonPinkBright,
      rainbow7 = plt.wireSilver,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.techCyanDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.computerGray,
      header1 = plt.techCyanBright,
      header2 = plt.geniusPurpleBright,
      special = plt.techCyanBright,
      nontext = plt.computerGrayDark,
      whitespace = plt.computerGrayLight,
      win_separator = plt.computerGray,
      indent = plt.bg_lighter,
      indent_scope = plt.geniusPurpleCore,
      picker = plt.gadgetryPurple,
      yank = plt.circuitGreenBright,
      mark = plt.neonPinkBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.bg_lightest,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.computerGray,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.computerGray,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.computerGrayLight,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_dark,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.dataBlueBright,
        indicator = plt.geniusPurpleCore,
      },
    },
    syn = {
      attribute = plt.inventionOrange,
      boolean = plt.dataBlue,
      comment = plt.computerGray,
      constant = plt.wireSilver,
      deprecated = plt.computerGrayDark,
      func = plt.techCyan,
      identifier = plt.fg_lightest,
      keyword = plt.geniusPurpleCore,
      method = plt.techCyanBright,
      number = plt.inventionOrange,
      operator = plt.circuitGreen,
      parameter = plt.fg_mid,
      preproc = plt.neonPink,
      punct = plt.fg_dark,
      regex = plt.neonPinkDeep,
      special = plt.techCyanBright,
      special2 = plt.neonPinkBright,
      special3 = plt.hologramBlue,
      statement = plt.geniusPurpleCore,
      string = plt.circuitGreen,
      symbol = plt.inventionOrange,
      type = plt.dataBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.techCyan,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.techCyan,
    },
    diff = {
      add = plt.circuitGreen,
      add_inline = plt.circuitGreenDeep,
      change = plt.inventionOrange,
      change_inline = plt.inventionOrangeDeep,
      delete = plt.dangerRed,
      delete_inline = plt.dangerRed,
      text = plt.techCyan,
    },
    vcs = {
      added = plt.circuitGreen,
      changed = plt.inventionOrange,
      removed = plt.dangerRed,
    },
    term = {
      black = plt.techLab,
      red = plt.dangerRed,
      green = plt.circuitGreenCore,
      yellow = plt.inventionOrange,
      blue = plt.dataBlueCore,
      magenta = plt.geniusPurpleCore,
      cyan = plt.techCyanCore,
      white = plt.wireSilver,
      black_bright = color(plt.techLab):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerRed):brighten(0.2):to_hex(),
      green_bright = color(plt.circuitGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.inventionOrangeBright):brighten(0.2):to_hex(),
      blue_bright = color(plt.dataBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.geniusPurpleBright):brighten(0.2):to_hex(),
      cyan_bright = color(plt.techCyanBright):brighten(0.2):to_hex(),
      white_bright = color(plt.wireSilver):brighten(0.2):to_hex(),
      indexed1 = plt.geniusPurple,
      indexed2 = plt.techCyan,
    },
  }
end

return {
  name = "TMNT – Donatello",
  author = "PrismPunk.nvim",
  description = "Tech genius — intelligent, inventive, analytical.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.computerGray,
    base04 = palette.computerGrayLight,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dangerRed,
    base09 = palette.inventionOrange,
    base0A = palette.inventionOrangeBright,
    base0B = palette.circuitGreen,
    base0C = palette.techCyan,
    base0D = palette.dataBlue,
    base0E = palette.geniusPurpleCore,
    base0F = palette.boStaffWood,
  },
  palette = palette,
  get = M.get,
}
