local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0E14",
  bg_darker = "#0F1419",
  bg_dark = "#151B24",
  bg_mid = "#1C2430",
  bg_light = "#242D3D",
  bg_lighter = "#2D3748",
  bg_lightest = "#374357",
  fg_lightest = "#E6F0FF",
  fg_light = "#D0DFF0",
  fg_mid = "#A8B8D0",
  fg_dark = "#7A8BA0",
  bg_alt1 = "#121720",
  bg_alt2 = "#080B10",
  bg_alt3 = "#1A2230",
  bg_alt4 = "#050709",
  leaderBlue = "#4A90E2",
  leaderBlueBright = "#5CA4FF",
  leaderBlueCore = "#3D7EC8",
  leaderBlueDeep = "#2D5F9F",
  leaderBlueDark = "#1E4070",
  katanaSilver = "#C0D0E0",
  katanaSteel = "#8FA8C0",
  katanaBlade = "#6B8CA8",
  katanaEdge = "#4D6B88",
  honorGold = "#FFD700",
  honorGoldMuted = "#D4AF37",
  honorGoldDeep = "#B8942F",
  focusCyan = "#5FBFDF",
  focusCyanBright = "#7FD4EF",
  focusCyanDeep = "#4A9FB8",
  disciplineGreen = "#5FB388",
  disciplineGreenBright = "#7FC9A0",
  disciplineGreenDeep = "#4A8F6F",
  shadowGray = "#4A5568",
  shadowGrayDark = "#363D4D",
  shadowGrayDeep = "#2A3240",
  steelBlue = "#607D99",
  ninjaBlack = "#1A1F2E",
  dojoWood = "#6B5744",
  dangerRed = "#E74C3C",
  warningAmber = "#F39C12",
  infoBlue = "#3498DB",
  successGreen = "#27AE60",
  sewerDark = "#0D1117",
  meditationBlue = "#2D4A6F",
  strategyPurple = "#6B7BB8",
  leadershipGlow = "#D0E8FF",
  leadershipVivid = "#E0F0FF",
  leadershipFlare = "#F0F8FF",
  honorAccent1 = "#3A506B",
  honorAccent2 = "#425A78",
  honorAccent3 = "#4A6485",
  honorAccent4 = "#526E92",
  honorAccent5 = "#5A789F",
}

local M = {}

---@param opts table
---@param plt table
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.leaderBlueCore,
      insert = plt.disciplineGreen,
      visual = plt.focusCyan,
      replace = plt.dangerRed,
      command = plt.honorGold,
    },
    accent = {
      accent1 = plt.leaderBlueCore,
      accent2 = plt.katanaSilver,
      accent3 = plt.honorGold,
      accent4 = plt.focusCyan,
      accent5 = plt.disciplineGreen,
      invert = plt.bg_light,
    },
    rainbow = {
      rainbow1 = plt.leaderBlueBright,
      rainbow2 = plt.focusCyanBright,
      rainbow3 = plt.honorGold,
      rainbow4 = plt.disciplineGreenBright,
      rainbow5 = plt.katanaSilver,
      rainbow6 = plt.strategyPurple,
      rainbow7 = plt.steelBlue,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.bg_alt1,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_mid,
      bg_search = plt.focusCyanDeep,
      bg_visual = plt.bg_mid,
      bg_statusline = plt.bg_light,
      border = plt.steelBlueBright,
      header1 = plt.leaderBlueBright,
      header2 = plt.honorGold,
      special = plt.focusCyan,
      nontext = plt.fg_dark,
      whitespace = plt.shadowGrayDark,
      win_separator = plt.steelBlueBright,
      indent = plt.bg_lighter,
      indent_scope = plt.leaderBlueCore,
      picker = plt.strategyPurple,
      yank = plt.honorGold,
      mark = plt.focusCyanBright,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_mid,
      line_nr = plt.fg_light,
      line_nr_dim = plt.fg_dark,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_darker,
        fg_border = plt.steelBlueBright,
        bg_border = plt.bg_darker,
      },
      pmenu = {
        fg = plt.fg_light,
        fg_sel = plt.fg_lightest,
        fg_border = plt.steelBlue,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.steelBlue,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darkest,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.leaderBlueBright,
        indicator = plt.leaderBlueCore,
      },
    },
    syn = {
      attribute = plt.honorGold,
      boolean = plt.leaderBlueCore,
      comment = plt.shadowGrayDark,
      constant = plt.katanaSilver,
      deprecated = plt.shadowGray,
      func = plt.focusCyan,
      identifier = plt.fg_lightest,
      keyword = plt.leaderBlueCore,
      method = plt.focusCyanBright,
      number = plt.honorGold,
      operator = plt.katanaSteel,
      parameter = plt.fg_light,
      preproc = plt.strategyPurple,
      punct = plt.fg_mid,
      regex = plt.disciplineGreen,
      special = plt.focusCyan,
      special2 = plt.strategyPurple,
      special3 = plt.steelBlue,
      statement = plt.leaderBlueCore,
      string = plt.disciplineGreenBright,
      symbol = plt.honorGold,
      type = plt.katanaSilver,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.dangerRed,
      warning = plt.warningAmber,
      info = plt.infoBlue,
      ok = plt.successGreen,
      hint = plt.focusCyan,
      virtual_text_error = plt.dangerRed,
      virtual_text_warning = plt.warningAmber,
      virtual_text_info = plt.infoBlue,
      virtual_text_ok = plt.successGreen,
      virtual_text_hint = plt.focusCyan,
    },
    diff = {
      add = plt.disciplineGreen,
      add_inline = plt.disciplineGreenDeep,
      change = plt.honorGold,
      change_inline = plt.honorGoldDeep,
      delete = plt.dangerRed,
      delete_inline = plt.dangerRed,
      text = plt.focusCyan,
    },
    vcs = {
      added = plt.disciplineGreen,
      changed = plt.honorGold,
      removed = plt.dangerRed,
    },
    term = {
      black = plt.ninjaBlack,
      red = plt.dangerRed,
      green = plt.disciplineGreen,
      yellow = plt.honorGold,
      blue = plt.leaderBlueCore,
      magenta = plt.strategyPurple,
      cyan = plt.focusCyan,
      white = plt.katanaSilver,
      black_bright = color(plt.ninjaBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerRed):brighten(0.2):to_hex(),
      green_bright = color(plt.disciplineGreenBright):brighten(0.2):to_hex(),
      yellow_bright = color(plt.honorGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.leaderBlueBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.strategyPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.focusCyanBright):brighten(0.2):to_hex(),
      white_bright = color(plt.katanaSilver):brighten(0.2):to_hex(),
      indexed1 = plt.honorGoldMuted,
      indexed2 = plt.leaderBlueCore,
    },
  }
end

return {
  name = "TMNT – Leonardo",
  author = "PrismPunk.nvim",
  description = "Leader in blue — disciplined, strategic, honorable.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.shadowGray,
    base04 = palette.shadowGrayDark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.dangerRed,
    base09 = palette.honorGold,
    base0A = palette.honorGoldMuted,
    base0B = palette.disciplineGreen,
    base0C = palette.focusCyan,
    base0D = palette.leaderBlueCore,
    base0E = palette.strategyPurple,
    base0F = palette.dojoWood,
  },
  palette = palette,
  get = M.get,
}
