local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#0F1A22",
  sumiInk1 = "#182830",
  sumiInk2 = "#223640",
  sumiInk3 = "#2C4450",
  sumiInk4 = "#486070",
  sumiInkShadow = "#081218",
  sumiInkEcho = "#142028",
  sumiInkTint = "#1A2832",
  sumiInkDeep = "#203038",
  sumiInkRidge = "#384858",
  fujiWhite = "#E8E8F0",
  oldWhite = "#C8C8D0",
  softGray = "#8898A8",
  dragonGray = "#6A7A8A",
  dragonGray2 = "#98A8B8",
  midnightTeal1 = "#2A8A9A",
  midnightTeal2 = "#30A0B8",
  midnightTeal3 = "#58A0A8",
  midnightTeal4 = "#48B0B0",
  midnightBlue1 = "#6888A8",
  midnightBlue2 = "#78A0B8",
  midnightBlue3 = "#98B0C8",
  midnightIndigo = "#7878A8",
  midnightAccent1 = "#182830",
  midnightAccent2 = "#223640",
  midnightAccent3 = "#2C4450",
  midnightAccent4 = "#385060",
  midnightAccent5 = "#486070",
  midnightGold1 = "#D8C888",
  midnightGold2 = "#E8D8A8",

  bg_darkest = "#0F1A22",
  fg_lightest = "#E8E8F0",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.midnightTeal1,
      insert = plt.midnightTeal3,
      visual = plt.midnightIndigo,
      replace = plt.midnightTeal2,
      command = plt.midnightGold1,
    },
    accent = {
      accent1 = plt.midnightTeal2,
      accent2 = plt.midnightTeal1,
      accent3 = plt.midnightIndigo,
      accent4 = plt.midnightBlue1,
      accent5 = plt.midnightGold1,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.midnightTeal2,
      rainbow2 = plt.midnightTeal3,
      rainbow3 = plt.midnightGold1,
      rainbow4 = plt.midnightTeal1,
      rainbow5 = plt.midnightBlue1,
      rainbow6 = plt.midnightIndigo,
      rainbow7 = plt.midnightGold2,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = "#A0B0C0",
      fg_dark = "#8090A0",
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInkEcho,
      bg_m2 = plt.sumiInk1,
      bg_m3 = plt.sumiInk2,
      bg_m4 = plt.sumiInk3,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInkEcho or "none",
      bg_cursorline = plt.sumiInk2,
      bg_cursorline_alt = plt.sumiInk3,
      cursorline = plt.sumiInk2,
      bg_highlight = plt.sumiInk3,
      bg_search = plt.midnightAccent3,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInkEcho,
      border = plt.sumiInk4,
      header1 = plt.midnightTeal2,
      header2 = plt.midnightGold1,
      special = plt.midnightTeal4,
      nontext = plt.sumiInk3,
      whitespace = plt.sumiInk3,
      win_separator = plt.sumiInk4,
      indent = plt.sumiInk2,
      indent_scope = plt.midnightTeal1,
      picker = plt.midnightIndigo,
      yank = plt.midnightGold1,
      mark = plt.midnightTeal2,
      scrollbar = plt.sumiInk3,
      selection = plt.sumiInk3,
      line_nr = plt.sumiInk4,
      line_nr_dim = plt.sumiInk3,
      line_nr_active = plt.fujiWhite,
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = plt.fujiWhite,
        fg_border = plt.sumiInk4,
        bg = plt.sumiInk2,
        bg_sel = plt.sumiInk3,
        bg_border = plt.sumiInk2,
        bg_sbar = plt.sumiInk2,
        bg_thumb = plt.sumiInk4,
      },
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk2,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk2,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInkEcho,
        fg_inactive = "#8090A0",
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.midnightTeal2,
        indicator = plt.midnightTeal1,
      },
    },
    syn = {
      attribute = plt.oldWhite,
      boolean = plt.midnightTeal2,
      comment = "#A0B0C0",
      constant = plt.oldWhite,
      deprecated = "#7080A0",
      func = plt.midnightBlue2,
      identifier = plt.fujiWhite,
      keyword = plt.midnightTeal1,
      method = plt.midnightBlue2,
      number = plt.midnightGold1,
      operator = plt.midnightGold2,
      parameter = plt.oldWhite,
      preproc = plt.midnightIndigo,
      punct = "#98A8B8",
      regex = plt.midnightTeal3,
      special = plt.midnightTeal2,
      special2 = plt.midnightBlue3,
      special3 = plt.midnightIndigo,
      statement = plt.midnightTeal1,
      string = plt.midnightTeal3,
      symbol = plt.midnightTeal2,
      type = plt.midnightIndigo,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.midnightTeal1,
      warning = plt.midnightGold1,
      info = plt.midnightTeal2,
      hint = plt.midnightTeal3,
      ok = plt.midnightTeal4,
      virtual_text_error = plt.midnightTeal1,
      virtual_text_warning = plt.midnightGold2,
      virtual_text_info = plt.midnightTeal3,
      virtual_text_hint = plt.midnightTeal4,
      virtual_text_ok = plt.midnightTeal3,
    },
    diff = {
      add = plt.midnightTeal3,
      add_inline = plt.midnightTeal4,
      change = plt.midnightGold1,
      change_inline = plt.midnightGold2,
      delete = plt.midnightTeal1,
      delete_inline = plt.midnightTeal2,
      text = plt.midnightTeal2,
    },
    vcs = {
      added = plt.midnightTeal3,
      changed = plt.midnightGold1,
      removed = plt.midnightTeal1,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.midnightTeal1,
      green = plt.midnightTeal3,
      yellow = plt.midnightGold1,
      blue = plt.midnightBlue1,
      magenta = plt.midnightIndigo,
      cyan = plt.midnightTeal2,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.midnightTeal1):brighten(0.2):to_hex(),
      green_bright = color(plt.midnightTeal3):brighten(0.1):to_hex(),
      yellow_bright = color(plt.midnightGold1):brighten(0.2):to_hex(),
      blue_bright = color(plt.midnightBlue1):brighten(0.3):to_hex(),
      magenta_bright = color(plt.midnightIndigo):brighten(0.2):to_hex(),
      cyan_bright = color(plt.midnightTeal2):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.midnightGold2,
      indexed2 = plt.midnightBlue3,
    },
  }
end

return {
  name = "Kanagawa Paper – Azure",
  author = "PrismPunk.nvim",
  description = "Deep ocean dark theme with bright teal accents and steel blue highlights.",

  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInkEcho,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softGray,
    base08 = palette.midnightTeal1,
    base09 = palette.midnightTeal2,
    base0A = palette.midnightGold1,
    base0B = palette.midnightTeal3,
    base0C = palette.midnightTeal4,
    base0D = palette.midnightBlue1,
    base0E = palette.midnightIndigo,
    base0F = palette.midnightBlue2,
  },

  palette = palette,
  get = M.get,
}
