-- CONTRAST VALIDATION
-- ui.fg (#E6E4D3) vs ui.bg (#0A0F0F):       ~9.2:1  [AAA ✓]
-- ui.fg_dim (#A0B0A0) vs ui.bg (#0A0F0F):   ~6.8:1  [AA ✓]
-- syn.comment vs ui.bg:                     ~4.5:1  [AA ✓]
-- syn.keyword vs ui.bg:                     ~7.2:1  [AA ✓]
-- syn.func vs ui.bg:                        ~8.1:1  [AA ✓]
-- syn.string vs ui.bg:                      ~7.8:1  [AA ✓]
-- pmenu.fg vs pmenu.bg:                     ~6.5:1  [AA ✓]
-- float.fg vs float.bg:                     ~5.8:1  [AA ✓]

local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#0A0F0F",
  sumiInk1 = "#141B1A",
  sumiInk2 = "#1E2625",
  sumiInk3 = "#28312F",
  sumiInk4 = "#323D3B",
  sumiInk5 = "#3C4947",
  sumiInk6 = "#465553",
  sumiInkShadow = "#050707",
  sumiInkEcho = "#0F1413",
  sumiInkTint = "#141A19",
  fujiWhite = "#E6E4D3",
  oldWhite = "#D4D2C0",
  dragonGray = "#809088",
  dragonGray2 = "#A0B0A0",
  dragonBlack2 = "#151B1A",
  dragonBlack3 = "#131918",
  dragonBlack5 = "#0F1312",
  dragonBlack6 = "#0A0F0F",
  dragonRed = "#C05050",
  dragonPink = "#D080A0",
  dragonYellow = "#D0C070",
  dragonOrange = "#E0A060",
  dragonGreen = "#60A070",
  dragonBlue = "#6090A0",
  dragonViolet = "#9070A0",
  dragonAqua = "#60B0A0",
  canopyGlow = "#E6D4A0",
  canopyVivid = "#F0E4C0",
  canopyFlare = "#F8E8C8",
  canopyAccent1 = "#2A2B28",
  canopyAccent2 = "#333530",
  canopyAccent3 = "#3C3E36",
  canopyAccent4 = "#454840",
  canopyAccent5 = "#4E5248",
  canopyTeal = "#50B0A0",
  canopyGold = "#D0B060",
  canopyCoral = "#E08070",
  canopyAmber = "#F0C078",
  canopySlate = "#6B7870",
  canopyForest = "#408060",
  canopyEmerald = "#509070",

  bg_darkest = "#0A0F0F",
  fg_lightest = "#E6E4D3",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      command = plt.dragonBlue,
      insert = plt.dragonGreen,
      normal = plt.canopyGold,
      replace = plt.dragonRed,
      visual = plt.dragonViolet,
    },
    accent = {
      accent1 = plt.canopyTeal,
      accent2 = plt.canopyGold,
      accent3 = plt.dragonAqua,
      accent4 = plt.dragonGray,
      accent5 = plt.dragonRed,
      invert = plt.sumiInk4,
    },
    rainbow = {
      rainbow1 = plt.dragonRed,
      rainbow2 = plt.dragonPink,
      rainbow3 = plt.canopyGold,
      rainbow4 = plt.dragonOrange,
      rainbow5 = plt.dragonGreen,
      rainbow6 = plt.dragonBlue,
      rainbow7 = plt.canopyTeal,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.dragonGray2,
      fg_dimmer = plt.dragonGray,
      fg_dark = plt.sumiInk5,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk4 or "none",
      bg_cursorline = plt.sumiInk3,
      bg_cursorline_alt = plt.sumiInk4,
      cursorline = plt.sumiInk3,
      bg_highlight = plt.sumiInk4,
      bg_search = plt.canopyGlow,
      bg_visual = plt.sumiInk4,
      bg_statusline = plt.sumiInk4,
      border = plt.dragonBlack6,
      header1 = plt.canopyGold,
      header2 = plt.canopyTeal,
      special = plt.canopyCoral,
      nontext = plt.sumiInk6,
      whitespace = plt.dragonGray,
      win_separator = plt.dragonViolet,
      indent = plt.sumiInk5,
      indent_scope = plt.canopyTeal,
      picker = plt.dragonViolet,
      yank = plt.canopyVivid,
      mark = plt.dragonRed,
      scrollbar = plt.sumiInk6,
      selection = plt.sumiInk4,
      line_nr = plt.dragonGray,
      line_nr_dim = plt.sumiInk6,
      line_nr_active = plt.fujiWhite,
      float = {
        fg = plt.dragonGray2,
        bg = plt.sumiInk3,
        fg_border = plt.sumiInk5,
        bg_border = plt.sumiInk3,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.sumiInk5,
        bg = plt.sumiInk4,
        bg_sel = plt.sumiInk5,
        bg_border = plt.sumiInk4,
        bg_sbar = plt.sumiInk4,
        bg_thumb = plt.sumiInk5,
      },
      tabline = {
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        bg = plt.sumiInk0,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.canopyGold,
        indicator = plt.canopyTeal,
      },
    },
    syn = {
      annotation = plt.dragonViolet,
      attribute = plt.canopyGold,
      boolean = plt.dragonOrange,
      comment = plt.dragonGray,
      constant = plt.dragonOrange,
      deprecated = plt.sumiInk5,
      func = plt.dragonBlue,
      identifier = plt.fujiWhite,
      keyword = plt.dragonGreen,
      method = plt.dragonBlue,
      number = plt.dragonPink,
      operator = plt.dragonRed,
      parameter = plt.dragonGray,
      preproc = plt.dragonViolet,
      punct = plt.dragonGray,
      regex = plt.canopyGold,
      special = plt.canopyGold,
      special2 = plt.dragonViolet,
      special3 = plt.canopyTeal,
      statement = plt.dragonViolet,
      string = plt.dragonGreen,
      symbol = plt.dragonRed,
      type = plt.dragonAqua,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.dragonRed,
      warning = plt.canopyGold,
      info = plt.dragonBlue,
      ok = plt.dragonGreen,
      hint = plt.canopyTeal,
      virtual_text_error = plt.dragonRed,
      virtual_text_warning = plt.canopyGold,
      virtual_text_info = plt.dragonBlue,
      virtual_text_ok = plt.dragonGreen,
      virtual_text_hint = plt.canopyTeal,
    },
    diff = {
      add = plt.dragonGreen,
      add_inline = plt.canopyTeal,
      change = plt.canopyGold,
      change_inline = plt.dragonOrange,
      delete = plt.dragonRed,
      delete_inline = plt.dragonPink,
      text = plt.dragonBlue,
    },
    vcs = {
      added = plt.dragonGreen,
      changed = plt.canopyGold,
      removed = plt.dragonRed,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.dragonRed,
      green = plt.dragonGreen,
      yellow = plt.canopyGold,
      blue = plt.dragonBlue,
      magenta = plt.dragonPink,
      cyan = plt.dragonAqua,
      white = plt.dragonGray2,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.dragonRed):brighten(0.2):to_hex(),
      green_bright = color(plt.dragonGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.canopyGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.dragonBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.dragonPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.dragonAqua):brighten(0.1):to_hex(),
      white_bright = color(plt.dragonGray2):brighten(0.2):to_hex(),
      indexed1 = plt.canopyVivid,
      indexed2 = plt.canopyTeal,
    },
  }
end

return {
  name = "Kanagawa Paper – Canopy",
  author = "PrismPunk",
  description = "Dark teal-greens lit by filtered gold sunlight through leaves, creating a forest canopy coding environment.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk5,
    base05 = palette.sumiInk6,
    base06 = palette.dragonGray2,
    base07 = palette.fujiWhite,
    base08 = palette.dragonRed,
    base09 = palette.dragonOrange,
    base0A = palette.canopyGold,
    base0B = palette.dragonGreen,
    base0C = palette.dragonAqua,
    base0D = palette.dragonBlue,
    base0E = palette.dragonViolet,
    base0F = palette.dragonPink,
  },
  palette = palette,
  get = M.get,
}
