
local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0D0C0C",
  bg_darker = "#1E1C1C",
  bg_dark = "#302E2E",
  bg_mid = "#484444",
  bg_light = "#646060",
  bg_lighter = "#908888",
  bg_lightest = "#BEB8B8",

  bg_alt1 = "#242222",
  bg_alt2 = "#383434",
  bg_alt3 = "#4C4848",

  fg_lightest = "#BEB8B8",
  fg_light = "#908888",
  fg_mid = "#646060",
  fg_dark = "#484444",

  ashBlack = "#0D0C0C",
  charcoal = "#1E1C1C",
  smoke = "#302E2E",
  grey = "#484444",
  stone = "#646060",
  silver = "#908888",
  white = "#BEB8B8",
  ember = "#D4602A",
  orange = "#FF5810",
  amber = "#FF8030",
  red = "#C03010",
  pink = "#F8C0A0",
  blue = "#405870",
  sky = "#6088A0",
  cyan = "#A8C8E0",
  cream = "#E8F4F8",

  fg_reverse = "#0D0C0C",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.ember,
      insert = plt.orange,
      visual = plt.cyan,
      replace = plt.red,
      command = plt.sky,
    },
    accent = {
      accent1 = plt.ember,
      accent2 = plt.orange,
      accent3 = plt.cyan,
      accent4 = plt.sky,
      accent5 = plt.red,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.ember,
      rainbow2 = plt.orange,
      rainbow3 = plt.amber,
      rainbow4 = plt.pink,
      rainbow5 = plt.cyan,
      rainbow6 = plt.sky,
      rainbow7 = plt.blue,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.pink,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.ember,
      header2 = plt.orange,
      special = plt.cyan,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.cyan,
      indent = plt.bg_light,
      indent_scope = plt.ember,
      picker = plt.cyan,
      yank = plt.pink,
      mark = plt.amber,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.amber,
        indicator = plt.ember,
      },
    },
    syn = {
      attribute = plt.cyan,
      boolean = plt.amber,
      comment = plt.fg_mid,
      constant = plt.amber,
      deprecated = plt.fg_dark,
      func = plt.ember,
      identifier = plt.fg_lightest,
      keyword = plt.cyan,
      method = plt.ember,
      number = plt.sky,
      operator = plt.orange,
      parameter = plt.fg_mid,
      preproc = plt.sky,
      punct = plt.fg_mid,
      regex = plt.cyan,
      special = plt.cyan,
      special2 = plt.sky,
      special3 = plt.blue,
      statement = plt.sky,
      string = plt.blue,
      symbol = plt.orange,
      type = plt.blue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.red,
      warning = plt.amber,
      info = plt.ember,
      ok = plt.cyan,
      hint = plt.sky,
      virtual_text_error = plt.red,
      virtual_text_warning = plt.amber,
      virtual_text_info = plt.ember,
      virtual_text_ok = plt.cyan,
      virtual_text_hint = plt.sky,
    },
    diff = {
      add = plt.cyan,
      add_inline = plt.sky,
      change = plt.amber,
      change_inline = plt.orange,
      delete = plt.red,
      delete_inline = plt.pink,
      text = plt.ember,
    },
    vcs = {
      added = plt.cyan,
      changed = plt.amber,
      removed = plt.red,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.red,
      green = plt.cyan,
      yellow = plt.amber,
      blue = plt.ember,
      magenta = plt.pink,
      cyan = plt.sky,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.red):brighten(0.2):to_hex(),
      green_bright = color(plt.cyan):brighten(0.1):to_hex(),
      yellow_bright = color(plt.amber):brighten(0.2):to_hex(),
      blue_bright = color(plt.ember):brighten(0.3):to_hex(),
      magenta_bright = color(plt.pink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.sky):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.blue,
      indexed2 = plt.cream,
    },
  }
end

return {
  name = "Kanagawa Paper – Cinder",
  author = "PrismPunk",
  description = "Monochromatic ash greys with single warm ember accent.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.red,
    base09 = palette.amber,
    base0A = palette.orange,
    base0B = palette.cyan,
    base0C = palette.sky,
    base0D = palette.ember,
    base0E = palette.blue,
    base0F = palette.charcoal,
  },
  palette = palette,
  get = M.get,
}
