local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#140C08",
  sumiInk1 = "#2C1A12",
  sumiInk2 = "#4A2E20",
  sumiInk3 = "#6E4030",
  sumiInk4 = "#9A5A40",
  sumiInk5 = "#C47858",
  sumiInk6 = "#A8845A",
  sumiInkShadow = "#0E0804",
  sumiInkEcho = "#1C100A",
  sumiInkTint = "#241810",
  fujiWhite = "#FFF0D8",
  oldWhite = "#D4B08A",
  dragonGray = "#A8845A",
  dragonGray2 = "#D4B08A",
  dragonBlack2 = "#1C100A",
  dragonBlack3 = "#1A0F08",
  dragonBlack5 = "#130C06",
  dragonBlack6 = "#0E0804",
  dragonRed = "#E06030",
  dragonPink = "#FF8048",
  dragonYellow = "#E8D840",
  dragonOrange = "#FF8048",
  dragonGreen = "#407858",
  dragonBlue = "#60A870",
  dragonViolet = "#90C890",
  dragonAqua = "#90C890",
  edoGlow = "#F0C090",
  edoVivid = "#FFF0D8",
  edoFlare = "#FFF0D8",
  edoAccent1 = "#3A2218",
  edoAccent2 = "#442A20",
  edoAccent3 = "#4E3228",
  edoAccent4 = "#583830",
  edoAccent5 = "#624038",
  edoTeal = "#60A870",
  edoCoral = "#E06030",
  edoAmber = "#F0C090",
  edoSlate = "#A8845A",

  bg_darkest = "#0E0804",
  fg_lightest = "#FFF0D8",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      command = plt.dragonBlue,
      insert = plt.dragonGreen,
      normal = plt.dragonYellow,
      replace = plt.dragonRed,
      visual = plt.dragonViolet,
    },
    accent = {
      accent1 = plt.dragonBlue,
      accent2 = plt.dragonOrange,
      accent3 = plt.dragonAqua,
      accent4 = plt.dragonGray,
      accent5 = plt.dragonRed,
      invert = plt.sumiInk4,
    },
    rainbow = {
      rainbow1 = plt.dragonRed,
      rainbow2 = plt.dragonPink,
      rainbow3 = plt.dragonYellow,
      rainbow4 = plt.dragonOrange,
      rainbow5 = plt.dragonGreen,
      rainbow6 = plt.dragonBlue,
      rainbow7 = plt.dragonAqua,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.dragonGray2,
      fg_dimmer = plt.dragonGray,
      fg_dark = plt.sumiInk5,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk4 or "none",
      bg_cursorline = plt.sumiInk3,
      bg_cursorline_alt = plt.sumiInk4,
      cursorline = plt.sumiInk3,
      bg_highlight = plt.sumiInk4,
      bg_search = plt.edoGlow,
      bg_visual = plt.sumiInk4,
      bg_statusline = plt.sumiInk4,
      border = plt.dragonBlack6,
      header1 = plt.dragonYellow,
      header2 = plt.dragonBlue,
      special = plt.edoCoral,
      nontext = plt.sumiInk6,
      whitespace = plt.dragonGray,
      win_separator = plt.dragonViolet,
      indent = plt.sumiInk5,
      indent_scope = plt.dragonBlue,
      picker = plt.dragonViolet,
      yank = plt.edoVivid,
      mark = plt.dragonRed,
      scrollbar = plt.sumiInk6,
      selection = plt.sumiInk4,
      line_nr = plt.dragonGray,
      line_nr_dim = plt.sumiInk6,
      line_nr_active = plt.fujiWhite,
      float = {
        fg = plt.dragonGray2,
        bg = plt.sumiInk3,
        fg_border = plt.sumiInk5,
        bg_border = plt.sumiInk3,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.sumiInk5,
        bg = plt.sumiInk4,
        bg_sel = plt.sumiInk5,
        bg_border = plt.sumiInk4,
        bg_sbar = plt.sumiInk4,
        bg_thumb = plt.sumiInk5,
      },
      tabline = {
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        bg = plt.sumiInk0,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.dragonYellow,
        indicator = plt.dragonBlue,
      },
    },
    syn = {
      annotation = plt.dragonViolet,
      attribute = plt.dragonYellow,
      boolean = plt.dragonOrange,
      comment = plt.sumiInk5,
      constant = plt.dragonOrange,
      deprecated = plt.sumiInk5,
      func = plt.dragonBlue,
      identifier = plt.fujiWhite,
      keyword = plt.dragonPink,
      method = plt.dragonBlue,
      number = plt.dragonPink,
      operator = plt.dragonRed,
      parameter = plt.dragonGray,
      preproc = plt.dragonViolet,
      punct = plt.dragonGray,
      regex = plt.dragonYellow,
      special = plt.dragonYellow,
      special2 = plt.dragonViolet,
      special3 = plt.dragonAqua,
      statement = plt.dragonViolet,
      string = plt.dragonGreen,
      symbol = plt.dragonRed,
      type = plt.dragonAqua,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.dragonRed,
      warning = plt.dragonYellow,
      info = plt.dragonBlue,
      ok = plt.dragonGreen,
      hint = plt.dragonAqua,
      virtual_text_error = plt.dragonRed,
      virtual_text_warning = plt.dragonYellow,
      virtual_text_info = plt.dragonBlue,
      virtual_text_ok = plt.dragonGreen,
      virtual_text_hint = plt.dragonAqua,
    },
    diff = {
      add = plt.dragonGreen,
      add_inline = plt.dragonAqua,
      change = plt.dragonYellow,
      change_inline = plt.dragonOrange,
      delete = plt.dragonRed,
      delete_inline = plt.dragonPink,
      text = plt.dragonBlue,
    },
    vcs = {
      added = plt.dragonGreen,
      changed = plt.dragonYellow,
      removed = plt.dragonRed,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.dragonRed,
      green = plt.dragonGreen,
      yellow = plt.dragonYellow,
      blue = plt.dragonBlue,
      magenta = plt.dragonPink,
      cyan = plt.dragonAqua,
      white = plt.dragonGray2,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.dragonRed):brighten(0.2):to_hex(),
      green_bright = color(plt.dragonGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.dragonYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.dragonBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.dragonPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.dragonAqua):brighten(0.1):to_hex(),
      white_bright = color(plt.dragonGray2):brighten(0.2):to_hex(),
      indexed1 = plt.edoVivid,
      indexed2 = plt.edoFlare,
    },
  }
end

return {
  name = "Kanagawa Paper – Claysoil",
  author = "PrismPunk",
  description = "Rich terracotta and burnt sienna aesthetic on deep brown-black background, inspired by clay soil textures.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk5,
    base05 = palette.sumiInk6,
    base06 = palette.dragonGray2,
    base07 = palette.fujiWhite,
    base08 = palette.dragonRed,
    base09 = palette.dragonOrange,
    base0A = palette.dragonYellow,
    base0B = palette.dragonGreen,
    base0C = palette.dragonAqua,
    base0D = palette.dragonBlue,
    base0E = palette.dragonViolet,
    base0F = palette.dragonPink,
  },
  palette = palette,
  get = M.get,
}
