local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#140A05",
  sumiInk1 = "#1F1208",
  sumiInk2 = "#2B180A",
  sumiInk3 = "#38200F",
  sumiInk4 = "#452814",
  sumiInk5 = "#523019",
  sumiInk6 = "#5F381E",
  sumiInkShadow = "#0A0502",
  sumiInkEcho = "#100803",
  sumiInkTint = "#170B06",
  fujiWhite = "#FFD7A8",
  oldWhite = "#E8C08A",
  dragonGray = "#8B6239",
  dragonGray2 = "#C9925D",
  dragonBlack2 = "#1C1006",
  dragonBlack3 = "#1A0F05",
  dragonBlack5 = "#130A03",
  dragonBlack6 = "#0E0702",
  dragonRed = "#C8301C",
  dragonPink = "#D16D6A",
  dragonYellow = "#C08A3E",
  dragonOrange = "#FF9033",
  dragonGreen = "#767A4A",
  dragonBlue = "#6A8A95",
  dragonViolet = "#957F78",
  dragonAqua = "#6A958A",
  emberGlow = "#FFE4B8",
  emberVivid = "#FFD090",
  emberFlare = "#FFC880",
  emberAccent1 = "#2A180A",
  emberAccent2 = "#33200F",
  emberAccent3 = "#3C2814",
  emberAccent4 = "#453019",
  emberAccent5 = "#4E381E",
  emberCrimson = "#E64028",
  emberAmber = "#F0A060",
  emberCoral = "#E67A50",
  emberSlate = "#6B7880",

  bg_darkest = "#0E0702",
  fg_lightest = "#FFD7A8",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      command = plt.dragonBlue,
      insert = plt.dragonGreen,
      normal = plt.dragonOrange,
      replace = plt.dragonRed,
      visual = plt.dragonViolet,
    },
    accent = {
      accent1 = plt.dragonOrange,
      accent2 = plt.emberCrimson,
      accent3 = plt.dragonAqua,
      accent4 = plt.dragonGray,
      accent5 = plt.dragonRed,
      invert = plt.sumiInk4,
    },
    rainbow = {
      rainbow1 = plt.dragonRed,
      rainbow2 = plt.emberCoral,
      rainbow3 = plt.dragonYellow,
      rainbow4 = plt.dragonOrange,
      rainbow5 = plt.dragonGreen,
      rainbow6 = plt.dragonBlue,
      rainbow7 = plt.dragonAqua,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.dragonGray2,
      fg_dimmer = plt.dragonGray,
      fg_dark = plt.sumiInk5,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk4 or "none",
      bg_cursorline = plt.sumiInk3,
      bg_cursorline_alt = plt.sumiInk4,
      cursorline = plt.sumiInk3,
      bg_highlight = plt.sumiInk4,
      bg_search = plt.emberGlow,
      bg_visual = plt.sumiInk4,
      bg_statusline = plt.sumiInk4,
      border = plt.dragonBlack6,
      header1 = plt.dragonOrange,
      header2 = plt.emberCrimson,
      special = plt.emberCoral,
      nontext = plt.sumiInk6,
      whitespace = plt.dragonGray,
      win_separator = plt.dragonViolet,
      indent = plt.sumiInk5,
      indent_scope = plt.dragonOrange,
      picker = plt.dragonViolet,
      yank = plt.emberVivid,
      mark = plt.dragonRed,
      scrollbar = plt.sumiInk6,
      selection = plt.sumiInk4,
      line_nr = plt.dragonGray,
      line_nr_dim = plt.sumiInk6,
      line_nr_active = plt.fujiWhite,
      float = {
        fg = plt.dragonGray2,
        bg = plt.sumiInk3,
        fg_border = plt.sumiInk5,
        bg_border = plt.sumiInk3,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.sumiInk5,
        bg = plt.sumiInk4,
        bg_sel = plt.sumiInk5,
        bg_border = plt.sumiInk4,
        bg_sbar = plt.sumiInk4,
        bg_thumb = plt.sumiInk5,
      },
      tabline = {
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        bg = plt.sumiInk0,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.dragonOrange,
        indicator = plt.emberCrimson,
      },
    },
    syn = {
      annotation = plt.dragonViolet,
      attribute = plt.dragonYellow,
      boolean = plt.dragonOrange,
      comment = plt.dragonGray2,
      constant = plt.dragonOrange,
      deprecated = plt.sumiInk5,
      func = plt.emberAmber,
      identifier = plt.fujiWhite,
      keyword = plt.emberCrimson,
      method = plt.emberAmber,
      number = plt.emberCoral,
      operator = plt.dragonRed,
      parameter = plt.dragonGray,
      preproc = plt.dragonViolet,
      punct = plt.dragonGray,
      regex = plt.dragonYellow,
      special = plt.dragonYellow,
      special2 = plt.dragonViolet,
      special3 = plt.dragonAqua,
      statement = plt.dragonViolet,
      string = plt.dragonGreen,
      symbol = plt.dragonRed,
      type = plt.dragonAqua,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.dragonRed,
      warning = plt.dragonYellow,
      info = plt.dragonBlue,
      ok = plt.dragonGreen,
      hint = plt.dragonAqua,
      virtual_text_error = plt.dragonRed,
      virtual_text_warning = plt.dragonYellow,
      virtual_text_info = plt.dragonBlue,
      virtual_text_ok = plt.dragonGreen,
      virtual_text_hint = plt.dragonAqua,
    },
    diff = {
      add = plt.dragonGreen,
      add_inline = plt.dragonAqua,
      change = plt.dragonYellow,
      change_inline = plt.dragonOrange,
      delete = plt.dragonRed,
      delete_inline = plt.emberCoral,
      text = plt.emberAmber,
    },
    vcs = {
      added = plt.dragonGreen,
      changed = plt.dragonYellow,
      removed = plt.dragonRed,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.dragonRed,
      green = plt.dragonGreen,
      yellow = plt.dragonYellow,
      blue = plt.dragonBlue,
      magenta = plt.dragonPink,
      cyan = plt.dragonAqua,
      white = plt.dragonGray2,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.dragonRed):brighten(0.2):to_hex(),
      green_bright = color(plt.dragonGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.dragonYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.dragonBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.dragonPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.dragonAqua):brighten(0.1):to_hex(),
      white_bright = color(plt.dragonGray2):brighten(0.2):to_hex(),
      indexed1 = plt.emberVivid,
      indexed2 = plt.emberFlare,
    },
  }
end

return {
  name = "Kanagawa Paper – Ember",
  author = "PrismPunk",
  description = "Warm ember-orange and dark red tones on deep black background for cozy coding sessions.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk5,
    base05 = palette.sumiInk6,
    base06 = palette.dragonGray2,
    base07 = palette.fujiWhite,
    base08 = palette.dragonRed,
    base09 = palette.dragonOrange,
    base0A = palette.dragonYellow,
    base0B = palette.dragonGreen,
    base0C = palette.dragonAqua,
    base0D = palette.emberAmber,
    base0E = palette.emberCrimson,
    base0F = palette.dragonPink,
  },
  palette = palette,
  get = M.get,
}
