local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#151210",
  sumiInk1 = "#1E1A18",
  sumiInk2 = "#272320",
  sumiInk3 = "#322C28",
  sumiInk4 = "#4A423A",
  sumiInkShadow = "#0D0A08",
  sumiInkEcho = "#1A1614",
  sumiInkTint = "#201C1A",
  sumiInkDeep = "#242018",
  sumiInkRidge = "#2E2822",
  fujiWhite = "#A8B89A",
  oldWhite = "#B8A898",
  softGray = "#6A6258",
  dragonGray = "#5A6A7A",
  dragonGray2 = "#7A8A9A",
  floralSage1 = "#7A8A6A",
  floralSage2 = "#8B9A7B",
  floralSageGlow = "#9AAA8B",
  floralLavender1 = "#8A7A9A",
  floralLavender2 = "#9A8AAA",
  floralLavender3 = "#7A6A8A",
  floralRose1 = "#9A7A7A",
  floralRose2 = "#AA8A8A",
  floralRoseDusty = "#B89A9A",
  floralCoral1 = "#C49080",
  floralCoral2 = "#D4A090",
  floralGold1 = "#9A8A6A",
  floralGold2 = "#AAA898",
  floralPeach1 = "#D4A090",
  floralPeach2 = "#E4B0A0",
  floralAccent1 = "#1E1A18",
  floralAccent2 = "#272320",
  floralAccent3 = "#322C28",
  floralAccent4 = "#3C342C",
  floralAccent5 = "#4A423A",

  bg_darkest = "#151210",
  fg_lightest = "#A8B89A",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.floralRose1,
      insert = plt.floralSage1,
      visual = plt.floralLavender1,
      replace = plt.floralCoral1,
      command = plt.floralPeach1,
    },
    accent = {
      accent1 = plt.floralRose1,
      accent2 = plt.floralSage1,
      accent3 = plt.floralLavender1,
      accent4 = plt.floralCoral1,
      accent5 = plt.floralGold1,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.floralRose1,
      rainbow2 = plt.floralCoral1,
      rainbow3 = plt.floralPeach1,
      rainbow4 = plt.floralSage1,
      rainbow5 = plt.floralLavender1,
      rainbow6 = plt.floralGold1,
      rainbow7 = plt.floralRoseDusty,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.softGray,
      fg_dark = plt.dragonGray,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInkEcho,
      bg_m2 = plt.sumiInk1,
      bg_m3 = plt.sumiInk2,
      bg_m4 = plt.sumiInk3,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInkEcho or "none",
      bg_cursorline = plt.sumiInk2,
      bg_cursorline_alt = plt.sumiInk3,
      cursorline = plt.sumiInk2,
      bg_highlight = plt.sumiInk3,
      bg_search = plt.floralAccent3,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInkEcho,
      border = plt.sumiInk4,
      header1 = plt.floralLavender1,
      header2 = plt.floralPeach1,
      special = plt.floralRoseDusty,
      nontext = plt.sumiInk3,
      whitespace = plt.sumiInk3,
      win_separator = plt.sumiInk4,
      indent = plt.sumiInk2,
      indent_scope = plt.floralRose1,
      picker = plt.floralLavender2,
      yank = plt.floralPeach1,
      mark = plt.floralRose1,
      scrollbar = plt.sumiInk3,
      selection = plt.sumiInk3,
      line_nr = plt.sumiInk4,
      line_nr_dim = plt.sumiInk3,
      line_nr_active = plt.fujiWhite,
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = plt.fujiWhite,
        fg_border = plt.sumiInk4,
        bg = plt.sumiInk2,
        bg_sel = plt.sumiInk3,
        bg_border = plt.sumiInk2,
        bg_sbar = plt.sumiInk2,
        bg_thumb = plt.sumiInk4,
      },
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk2,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk2,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInkEcho,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.floralPeach1,
        indicator = plt.floralLavender1,
      },
    },
    syn = {
      attribute = plt.oldWhite,
      boolean = plt.floralLavender1,
      comment = plt.softGray,
      constant = plt.oldWhite,
      deprecated = plt.dragonGray,
      func = plt.floralLavender2,
      identifier = plt.fujiWhite,
      keyword = plt.floralRose1,
      method = plt.floralLavender2,
      number = plt.floralPeach1,
      operator = plt.floralGold1,
      parameter = plt.oldWhite,
      preproc = plt.floralLavender3,
      punct = plt.softGray,
      regex = plt.floralCoral1,
      special = plt.floralCoral2,
      special2 = plt.floralRoseDusty,
      special3 = plt.floralLavender2,
      statement = plt.floralRose1,
      string = plt.floralSage2,
      symbol = plt.floralRose2,
      type = plt.floralLavender1,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.floralRose1,
      warning = plt.floralPeach1,
      info = plt.floralLavender1,
      hint = plt.floralSage1,
      ok = plt.floralSage2,
      virtual_text_error = plt.floralRose2,
      virtual_text_warning = plt.floralPeach2,
      virtual_text_info = plt.floralLavender2,
      virtual_text_hint = plt.floralSageGlow,
      virtual_text_ok = plt.floralSage2,
    },
    diff = {
      add = plt.floralSage1,
      add_inline = plt.floralSageGlow,
      change = plt.floralPeach1,
      change_inline = plt.floralPeach2,
      delete = plt.floralRose1,
      delete_inline = plt.floralRose2,
      text = plt.floralLavender1,
    },
    vcs = {
      added = plt.floralSage1,
      changed = plt.floralPeach1,
      removed = plt.floralRose1,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.floralRose1,
      green = plt.floralSage1,
      yellow = plt.floralPeach1,
      blue = plt.floralLavender1,
      magenta = plt.floralLavender2,
      cyan = plt.floralCoral1,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.floralRose1):brighten(0.2):to_hex(),
      green_bright = color(plt.floralSage1):brighten(0.1):to_hex(),
      yellow_bright = color(plt.floralPeach1):brighten(0.2):to_hex(),
      blue_bright = color(plt.floralLavender1):brighten(0.3):to_hex(),
      magenta_bright = color(plt.floralLavender2):brighten(0.2):to_hex(),
      cyan_bright = color(plt.floralCoral1):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.floralGold1,
      indexed2 = plt.floralRoseDusty,
    },
  }
end

return {
  name = "Kanagawa Paper – Floral",
  author = "PrismPunk.nvim",
  description = "Botanical dark theme with dried flower tones of sage, lavender, and muted coral.",

  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInkEcho,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softGray,
    base08 = palette.floralRose1,
    base09 = palette.floralRose2,
    base0A = palette.floralPeach1,
    base0B = palette.floralSage1,
    base0C = palette.floralCoral1,
    base0D = palette.floralLavender1,
    base0E = palette.floralLavender2,
    base0F = palette.floralGold1,
  },

  palette = palette,
  get = M.get,
}
