local color = require("prismpunk.utils.color")

local palette = {
  winterInk0 = "#0E1520",
  winterInk1 = "#1C2B3A",
  winterInk2 = "#2E4458",
  winterInk3 = "#3A5568",
  winterInk4 = "#4A6678",
  winterInk5 = "#5B8CAA",
  winterInk6 = "#7FB3CC",
  winterInkShadow = "#080C10",
  winterInkEcho = "#121D28",
  winterInkTint = "#182430",

  frostWhite = "#EEF6F8",
  frostGray1 = "#CDE4EC",
  frostGray2 = "#A8CCD8",
  frostGray3 = "#7FB3CC",
  frostGray4 = "#5B8CAA",
  oldIce = "#D0E8F0",

  winterBlue = "#5B8CAA",
  winterCyan = "#7FB3CC",
  winterAqua = "#A8CCD8",
  winterSnow = "#CDE4EC",

  winterRed = "#8B4A5A",
  winterRose = "#A06070",
  winterPink = "#B07080",

  winterGreen = "#4A6A6A",
  winterLime = "#5A8060",

  winterYellow = "#A89060",
  winterGold = "#C0A070",

  winterOrange = "#906040",
  winterPeach = "#A07050",

  winterViolet = "#605080",
  winterPurple = "#706090",

  winterGlow = "#CDE4EC",
  winterFlare = "#D0E8F0",
  winterSpecial = "#7FB3CC",

  bg_darkest = "#0E1520",
  fg_lightest = "#EEF6F8",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.winterBlue,
      insert = plt.winterGreen,
      visual = plt.winterViolet,
      replace = plt.winterRose,
      command = plt.winterGold,
    },
    accent = {
      accent1 = plt.winterBlue,
      accent2 = plt.winterGold,
      accent3 = plt.winterCyan,
      accent4 = plt.frostGray1,
      accent5 = plt.winterRose,
      invert = plt.winterInk2,
    },
    rainbow = {
      rainbow1 = plt.winterRose,
      rainbow2 = plt.winterPink,
      rainbow3 = plt.winterGold,
      rainbow4 = plt.winterOrange,
      rainbow5 = plt.winterGreen,
      rainbow6 = plt.winterBlue,
      rainbow7 = plt.winterCyan,
    },
    ui = {
      fg = plt.frostWhite,
      fg_dim = plt.frostGray1,
      fg_dimmer = plt.frostGray2,
      fg_dark = plt.frostGray4,
      fg_reverse = plt.winterInk0,
      bg = plt.winterInk0,
      bg_dim = plt.winterInk0,
      bg_m1 = plt.winterInk1,
      bg_m2 = plt.winterInk2,
      bg_m3 = plt.winterInk3,
      bg_m4 = plt.winterInk4,
      bg_p1 = plt.winterInk2,
      bg_p2 = plt.winterInk3,
      bg_gutter = (opts.gutter ~= false) and plt.winterInk4 or "none",
      bg_cursorline = plt.winterInk3,
      bg_cursorline_alt = plt.winterInk4,
      cursorline = plt.winterInk3,
      bg_highlight = plt.winterInk4,
      bg_search = plt.winterGlow,
      bg_visual = plt.winterInk4,
      bg_statusline = plt.winterInk4,
      border = plt.winterInk0,
      header1 = plt.winterGold,
      header2 = plt.winterBlue,
      special = plt.winterSpecial,
      nontext = plt.winterInk5,
      whitespace = plt.frostGray2,
      win_separator = plt.winterViolet,
      indent = plt.winterInk4,
      indent_scope = plt.winterBlue,
      picker = plt.winterViolet,
      yank = plt.winterGlow,
      mark = plt.winterRose,
      scrollbar = plt.winterInk5,
      selection = plt.winterInk4,
      line_nr = plt.frostGray2,
      line_nr_dim = plt.winterInk5,
      line_nr_active = plt.frostWhite,
      float = {
        fg = plt.frostGray1,
        bg = plt.winterInk3,
        fg_border = plt.winterInk5,
        bg_border = plt.winterInk3,
      },
      pmenu = {
        fg = plt.frostWhite,
        fg_sel = "none",
        fg_border = plt.winterInk5,
        bg = plt.winterInk4,
        bg_sel = plt.winterInk5,
        bg_border = plt.winterInk4,
        bg_sbar = plt.winterInk4,
        bg_thumb = plt.winterInk5,
      },
      tabline = {
        bg_inactive = plt.winterInk0,
        bg_selected = plt.winterInk2,
        bg_alternate = plt.winterInk1,
        bg = plt.winterInk0,
        fg_inactive = plt.frostGray2,
        fg_selected = plt.frostWhite,
        fg_alternate = plt.winterGold,
        indicator = plt.winterBlue,
      },
    },
    syn = {
      attribute = plt.winterGold,
      boolean = plt.winterOrange,
      comment = plt.frostGray3,
      constant = plt.winterOrange,
      deprecated = plt.frostGray3,
      func = plt.winterBlue,
      identifier = plt.frostWhite,
      keyword = plt.winterRose,
      method = plt.winterBlue,
      number = plt.winterPink,
      operator = plt.winterRose,
      parameter = plt.frostGray2,
      preproc = plt.winterViolet,
      punct = plt.frostGray2,
      regex = plt.winterGold,
      special = plt.winterGold,
      special2 = plt.winterViolet,
      special3 = plt.winterCyan,
      statement = plt.winterViolet,
      string = plt.winterGreen,
      symbol = plt.winterRose,
      type = plt.winterCyan,
      variable = plt.frostWhite,
    },
    diag = {
      error = plt.winterRose,
      warning = plt.winterGold,
      info = plt.winterBlue,
      ok = plt.winterGreen,
      hint = plt.winterCyan,
      virtual_text_error = plt.winterRose,
      virtual_text_warning = plt.winterGold,
      virtual_text_info = plt.winterBlue,
      virtual_text_ok = plt.winterGreen,
      virtual_text_hint = plt.winterCyan,
    },
    diff = {
      add = plt.winterGreen,
      add_inline = plt.winterCyan,
      change = plt.winterGold,
      change_inline = plt.winterOrange,
      delete = plt.winterRose,
      delete_inline = plt.winterPink,
      text = plt.winterBlue,
    },
    vcs = {
      added = plt.winterGreen,
      changed = plt.winterGold,
      removed = plt.winterRose,
    },
    term = {
      black = plt.winterInk0,
      red = plt.winterRose,
      green = plt.winterGreen,
      yellow = plt.winterGold,
      blue = plt.winterBlue,
      magenta = plt.winterPink,
      cyan = plt.winterCyan,
      white = plt.frostGray1,
      black_bright = color(plt.winterInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.winterRose):brighten(0.2):to_hex(),
      green_bright = color(plt.winterGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.winterGold):brighten(0.2):to_hex(),
      blue_bright = color(plt.winterBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.winterPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.winterCyan):brighten(0.1):to_hex(),
      white_bright = color(plt.frostGray1):brighten(0.2):to_hex(),
      indexed1 = plt.winterSpecial,
      indexed2 = plt.winterGlow,
    },
  }
end

return {
  name = "Kanagawa Paper – Frost",
  author = "PrismPunk",
  description = "Cold stark whites and ice-blues on near-black, high-contrast winter theme.",
  base16 = {
    base00 = palette.winterInk0,
    base01 = palette.winterInk1,
    base02 = palette.winterInk2,
    base03 = palette.winterInk3,
    base04 = palette.frostGray3,
    base05 = palette.frostGray2,
    base06 = palette.frostGray1,
    base07 = palette.frostWhite,
    base08 = palette.winterRose,
    base09 = palette.winterOrange,
    base0A = palette.winterGold,
    base0B = palette.winterGreen,
    base0C = palette.winterCyan,
    base0D = palette.winterBlue,
    base0E = palette.winterViolet,
    base0F = palette.winterPink,
  },
  palette = palette,
  get = M.get,
}
