local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0B0C14",
  bg_darker = "#13152A",
  bg_dark = "#1E2240",
  bg_mid = "#2E3460",
  bg_light = "#424E80",
  bg_lighter = "#5C6AA0",
  bg_lightest = "#7A88C0",

  bg_alt1 = "#1A1E38",
  bg_alt2 = "#252A50",
  bg_alt3 = "#343C6C",

  fg_lightest = "#D0D4F8",
  fg_light = "#A8B0E8",
  fg_mid = "#7A88C0",
  fg_dark = "#5C6AA0",

  indigoVoid = "#0B0C14",
  indigoDeep = "#13152A",
  indigoNight = "#1E2240",
  indigoMid = "#2E3460",
  indigoSlate = "#424E80",
  indigoMist = "#5C6AA0",
  indigoFog = "#7A88C0",
  periwinkle = "#A8B0E8",
  lavenderFrost = "#D0D4F8",
  violet = "#8868C8",
  plum = "#A880D8",
  wisteria = "#C4A8E8",
  gold = "#E8C840",
  amber = "#F0A830",
  copper = "#C87840",
  rose = "#C85870",
  blush = "#E07890",
  petal = "#F0A0B8",

  fg_reverse = "#0B0C14",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.periwinkle,
      insert = plt.gold,
      visual = plt.violet,
      replace = plt.rose,
      command = plt.wisteria,
    },
    accent = {
      accent1 = plt.periwinkle,
      accent2 = plt.gold,
      accent3 = plt.violet,
      accent4 = plt.wisteria,
      accent5 = plt.rose,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.periwinkle,
      rainbow2 = plt.gold,
      rainbow3 = plt.indigoMid,
      rainbow4 = plt.wisteria,
      rainbow5 = plt.wisteria,
      rainbow6 = plt.violet,
      rainbow7 = plt.blush,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.gold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.periwinkle,
      header2 = plt.gold,
      special = plt.violet,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.violet,
      indent = plt.bg_light,
      indent_scope = plt.periwinkle,
      picker = plt.violet,
      yank = plt.gold,
      mark = plt.blush,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.gold,
        indicator = plt.periwinkle,
      },
    },
    syn = {
      attribute = plt.gold,
      boolean = plt.blush,
      comment = plt.fg_mid,
      constant = plt.blush,
      deprecated = plt.fg_dark,
      func = plt.periwinkle,
      identifier = plt.fg_lightest,
      keyword = plt.violet,
      method = plt.periwinkle,
      number = plt.wisteria,
      operator = plt.blush,
      parameter = plt.fg_mid,
      preproc = plt.wisteria,
      punct = plt.fg_mid,
      regex = plt.gold,
      special = plt.gold,
      special2 = plt.wisteria,
      special3 = plt.indigoMid,
      statement = plt.wisteria,
      string = plt.indigoMist,
      symbol = plt.blush,
      type = plt.indigoFog,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.rose,
      warning = plt.blush,
      info = plt.periwinkle,
      ok = plt.gold,
      hint = plt.indigoFog,
      virtual_text_error = plt.rose,
      virtual_text_warning = plt.blush,
      virtual_text_info = plt.periwinkle,
      virtual_text_ok = plt.gold,
      virtual_text_hint = plt.indigoFog,
    },
    diff = {
      add = plt.gold,
      add_inline = plt.indigoFog,
      change = plt.blush,
      change_inline = plt.petal,
      delete = plt.rose,
      delete_inline = plt.wisteria,
      text = plt.periwinkle,
    },
    vcs = {
      added = plt.gold,
      changed = plt.blush,
      removed = plt.rose,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.rose,
      green = plt.periwinkle,
      yellow = plt.gold,
      blue = plt.indigoMid,
      magenta = plt.violet,
      cyan = plt.wisteria,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.rose):brighten(0.2):to_hex(),
      green_bright = color(plt.periwinkle):brighten(0.1):to_hex(),
      yellow_bright = color(plt.gold):brighten(0.2):to_hex(),
      blue_bright = color(plt.indigoMid):brighten(0.3):to_hex(),
      magenta_bright = color(plt.violet):brighten(0.2):to_hex(),
      cyan_bright = color(plt.wisteria):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.plum,
      indexed2 = plt.copper,
    },
  }
end

return {
  name = "Kanagawa Paper – Indigo",
  author = "PrismPunk",
  description = "Deep indigo nights and periwinkle mist, cold and contemplative.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.rose,
    base09 = palette.blush,
    base0A = palette.gold,
    base0B = palette.periwinkle,
    base0C = palette.indigoFog,
    base0D = palette.violet,
    base0E = palette.wisteria,
    base0F = palette.indigoDeep,
  },
  palette = palette,
  get = M.get,
}
