local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0C10",
  bg_darker = "#141820",
  bg_dark = "#202830",
  bg_mid = "#303C48",
  bg_light = "#445260",
  bg_lighter = "#586878",
  bg_lightest = "#6C7C90",

  bg_alt1 = "#1A2028",
  bg_alt2 = "#283038",
  bg_alt3 = "#384450",

  fg_lightest = "#F8FCFF",
  fg_light = "#D8F0F8",
  fg_mid = "#B8C8D8",
  fg_dark = "#8898C0",

  ironBlack = "#0A0C10",
  charcoal = "#141820",
  slate = "#202830",
  steel = "#303C48",
  gunmetal = "#445260",
  steelBlue = "#6878A0",
  frost = "#8898C0",
  mist = "#B8C8D8",
  ice = "#D8F0F8",
  pearl = "#F8FCFF",
  copper = "#C06850",
  bronze = "#A07030",
  brass = "#C09040",
  gold = "#E8C060",
  peach = "#E09070",
  apricot = "#F8B890",

  fg_reverse = "#0A0C10",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.frost,
      insert = plt.gold,
      visual = plt.steelBlue,
      replace = plt.copper,
      command = plt.mist,
    },
    accent = {
      accent1 = plt.frost,
      accent2 = plt.gold,
      accent3 = plt.steelBlue,
      accent4 = plt.mist,
      accent5 = plt.copper,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.frost,
      rainbow2 = plt.gold,
      rainbow3 = plt.steelBlue,
      rainbow4 = plt.mist,
      rainbow5 = plt.brass,
      rainbow6 = plt.peach,
      rainbow7 = plt.copper,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.gold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.frost,
      header2 = plt.gold,
      special = plt.steelBlue,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.steelBlue,
      indent = plt.bg_light,
      indent_scope = plt.frost,
      picker = plt.steelBlue,
      yank = plt.gold,
      mark = plt.peach,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.gold,
        indicator = plt.frost,
      },
    },
    syn = {
      attribute = plt.gold,
      boolean = plt.peach,
      comment = plt.fg_mid,
      constant = plt.peach,
      deprecated = plt.fg_dark,
      func = plt.frost,
      identifier = plt.fg_lightest,
      keyword = plt.steelBlue,
      method = plt.frost,
      number = plt.mist,
      operator = plt.peach,
      parameter = plt.fg_mid,
      preproc = plt.mist,
      punct = plt.fg_mid,
      regex = plt.gold,
      special = plt.gold,
      special2 = plt.mist,
      special3 = plt.gunmetal,
      statement = plt.mist,
      string = plt.ice,
      symbol = plt.peach,
      type = plt.steelBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.copper,
      warning = plt.peach,
      info = plt.frost,
      ok = plt.gold,
      hint = plt.ice,
      virtual_text_error = plt.copper,
      virtual_text_warning = plt.peach,
      virtual_text_info = plt.frost,
      virtual_text_ok = plt.gold,
      virtual_text_hint = plt.ice,
    },
    diff = {
      add = plt.gold,
      add_inline = plt.ice,
      change = plt.peach,
      change_inline = plt.apricot,
      delete = plt.copper,
      delete_inline = plt.bronze,
      text = plt.frost,
    },
    vcs = {
      added = plt.gold,
      changed = plt.peach,
      removed = plt.copper,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.copper,
      green = plt.frost,
      yellow = plt.gold,
      blue = plt.steelBlue,
      magenta = plt.mist,
      cyan = plt.ice,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.copper):brighten(0.2):to_hex(),
      green_bright = color(plt.frost):brighten(0.1):to_hex(),
      yellow_bright = color(plt.gold):brighten(0.2):to_hex(),
      blue_bright = color(plt.steelBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.mist):brighten(0.2):to_hex(),
      cyan_bright = color(plt.ice):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.brass,
      indexed2 = plt.bronze,
    },
  }
end

return {
  name = "Kanagawa Paper – Iron Fan",
  author = "PrismPunk",
  description = "Cool dark greys with cold steel-blue, samurai steel.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.copper,
    base09 = palette.peach,
    base0A = palette.gold,
    base0B = palette.frost,
    base0C = palette.ice,
    base0D = palette.steelBlue,
    base0E = palette.mist,
    base0F = palette.charcoal,
  },
  palette = palette,
  get = M.get,
}
