local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#0F0F0F",
  sumiInk1 = "#121312",
  sumiInk2 = "#162127",
  sumiInk3 = "#292528",
  sumiInk4 = "#45455B",
  sumiInkShadow = "#030303",
  sumiInkEcho = "#0C1519",
  sumiInkTint = "#1F4433",
  sumiInkDeep = "#2B313F",
  sumiInkRidge = "#373A3E",
  fujiWhite = "#F5F0E6",
  oldWhite = "#EFEFEF",
  softGray = "#8C7C6C",
  dragonGray = "#60768C",
  dragonGray2 = "#879EBF",
  katanaRed1 = "#D12128",
  katanaRed2 = "#AD0013",
  katanaRed3 = "#81021F",
  katanaRedGlow = "#AD3A3C",
  katanaRedVivid = "#B83A2D",
  katanaOrange1 = "#FF8A00",
  katanaOrange2 = "#F26838",
  katanaOrangeGlow = "#FFDB89",
  katanaOrangeFlare = "#FAE3AC",
  katanaGold1 = "#CFB787",
  katanaGold2 = "#DCC9A9",
  katanaIndigo1 = "#5D3FD3",
  katanaIndigo2 = "#53589A",
  katanaIndigoGlow = "#879EBF",
  katanaBlue1 = "#0F95B0",
  katanaBlue2 = "#4B848A",
  katanaBlue3 = "#3E6868",
  katanaBlue4 = "#134857",
  katanaCyan = "#4B607F",
  katanaGreen1 = "#73A642",
  katanaGreen2 = "#4E6851",
  katanaPink1 = "#F6C6C2",
  katanaPink2 = "#D1AEA6",
  katanaAccent1 = "#2B313F",
  katanaAccent2 = "#373A3E",
  katanaAccent3 = "#45455B",
  katanaAccent4 = "#4B607F",
  katanaAccent5 = "#53589A",

  bg_darkest = "#0F0F0F",
  fg_lightest = "#F5F0E6",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.katanaIndigo1,
      insert = plt.katanaGreen1,
      visual = plt.katanaIndigo2,
      replace = plt.katanaRed1,
      command = plt.katanaOrange1,
    },
    accent = {
      accent1 = plt.katanaRed1,
      accent2 = plt.katanaOrange1,
      accent3 = plt.katanaIndigo1,
      accent4 = plt.katanaBlue1,
      accent5 = plt.katanaGreen1,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.katanaRed1,
      rainbow2 = plt.katanaOrange1,
      rainbow3 = plt.katanaGold1,
      rainbow4 = plt.katanaGreen1,
      rainbow5 = plt.katanaBlue1,
      rainbow6 = plt.katanaIndigo1,
      rainbow7 = plt.katanaPink1,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.softGray,
      fg_dark = plt.dragonGray,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInkEcho,
      bg_m2 = plt.sumiInk1,
      bg_m3 = plt.sumiInkDeep,
      bg_m4 = plt.sumiInk3,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInkEcho or "none",
      bg_cursorline = plt.sumiInk2,
      bg_cursorline_alt = plt.sumiInkDeep,
      cursorline = plt.sumiInk2,
      bg_highlight = plt.sumiInkDeep,
      bg_search = plt.katanaAccent3,
      bg_visual = plt.sumiInkDeep,
      bg_statusline = plt.sumiInkEcho,
      border = plt.sumiInk4,
      header1 = plt.katanaIndigo1,
      header2 = plt.katanaOrange1,
      special = plt.katanaBlue1,
      nontext = plt.sumiInk3,
      whitespace = plt.sumiInk3,
      win_separator = plt.sumiInk4,
      indent = plt.sumiInk2,
      indent_scope = plt.katanaIndigo1,
      picker = plt.katanaIndigo2,
      yank = plt.katanaOrangeGlow,
      mark = plt.katanaRedGlow,
      scrollbar = plt.sumiInk3,
      selection = plt.sumiInkDeep,
      line_nr = plt.sumiInk4,
      line_nr_dim = plt.sumiInk3,
      line_nr_active = plt.fujiWhite,
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = plt.fujiWhite,
        fg_border = plt.sumiInk4,
        bg = plt.sumiInk2,
        bg_sel = plt.sumiInkDeep,
        bg_border = plt.sumiInk2,
        bg_sbar = plt.sumiInk2,
        bg_thumb = plt.sumiInk4,
      },
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk2,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk2,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInkEcho,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.katanaOrange1,
        indicator = plt.katanaIndigo1,
      },
    },
    syn = {
      attribute = plt.oldWhite,
      boolean = plt.katanaBlue1,
      comment = plt.softGray,
      constant = plt.oldWhite,
      deprecated = plt.dragonGray,
      func = plt.katanaIndigo2,
      identifier = plt.fujiWhite,
      keyword = plt.katanaRed1,
      method = plt.katanaIndigo2,
      number = plt.katanaOrange1,
      operator = plt.katanaOrange2,
      parameter = plt.oldWhite,
      preproc = plt.katanaIndigo1,
      punct = plt.softGray,
      regex = plt.katanaBlue1,
      special = plt.katanaOrangeGlow,
      special2 = plt.katanaPink1,
      special3 = plt.katanaIndigoGlow,
      statement = plt.katanaRed1,
      string = plt.katanaGreen1,
      symbol = plt.katanaRedGlow,
      type = plt.katanaIndigo1,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.katanaRed1,
      warning = plt.katanaOrange1,
      info = plt.katanaBlue1,
      hint = plt.katanaGreen1,
      ok = plt.katanaBlue2,
      virtual_text_error = plt.katanaRed2,
      virtual_text_warning = plt.katanaOrange2,
      virtual_text_info = plt.katanaBlue1,
      virtual_text_hint = plt.katanaGreen1,
      virtual_text_ok = plt.katanaBlue2,
    },
    diff = {
      add = plt.katanaGreen1,
      add_inline = plt.katanaGold1,
      change = plt.katanaOrange1,
      change_inline = plt.katanaOrangeGlow,
      delete = plt.katanaRed1,
      delete_inline = plt.katanaRedGlow,
      text = plt.katanaBlue1,
    },
    vcs = {
      added = plt.katanaGreen1,
      changed = plt.katanaOrange1,
      removed = plt.katanaRed1,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.katanaRed1,
      green = plt.katanaGreen1,
      yellow = plt.katanaOrange1,
      blue = plt.katanaBlue2,
      magenta = plt.katanaIndigo1,
      cyan = plt.katanaBlue1,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.katanaRed1):brighten(0.2):to_hex(),
      green_bright = color(plt.katanaGreen1):brighten(0.1):to_hex(),
      yellow_bright = color(plt.katanaOrange1):brighten(0.2):to_hex(),
      blue_bright = color(plt.katanaBlue2):brighten(0.3):to_hex(),
      magenta_bright = color(plt.katanaIndigo1):brighten(0.2):to_hex(),
      cyan_bright = color(plt.katanaBlue1):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.katanaOrange2,
      indexed2 = plt.katanaIndigoGlow,
    },
  }
end

return {
  name = "Kanagawa Paper – Katana",
  author = "PrismPunk.nvim",
  description = "Sharp, high-contrast dark theme with vibrant accents and blade-like precision.",

  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInkEcho,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softGray,
    base08 = palette.katanaRed1,
    base09 = palette.katanaRedVivid,
    base0A = palette.katanaOrange1,
    base0B = palette.katanaGreen1,
    base0C = palette.katanaBlue1,
    base0D = palette.katanaIndigo1,
    base0E = palette.katanaIndigo2,
    base0F = palette.katanaBlue2,
  },

  palette = palette,
  get = M.get,
}
