local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0A0608",
  bg_darker = "#11070A",
  bg_dark = "#1C0C10",
  bg_mid = "#2A1016",
  bg_light = "#38131B",
  bg_lighter = "#4D1823",
  bg_lightest = "#6A1020",

  bg_alt1 = "#180A0E",
  bg_alt2 = "#220D12",
  bg_alt3 = "#300E14",

  fg_lightest = "#FFFAF0",
  fg_light = "#FFF8E8",
  fg_mid = "#C8B4B0",
  fg_dark = "#988480",

  urushiBlack = "#0A0608",
  crimsonLacquer = "#400808",
  bloodOxide = "#801010",
  shrineRed = "#A81828",
  shuiro = "#D42030",
  cinnabar = "#FF4028",
  coral = "#FF6040",

  makieGold = "#F0D840",
  richGold = "#F8C020",
  warmGold = "#E0A010",
  antiqueBrass = "#C8940A",

  radenBlue = "#82A4A8",
  radenPurple = "#B090B8",
  radenGreen = "#98B088",

  fg_reverse = "#0A0608",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.makieGold,
      insert = plt.cinnabar,
      visual = plt.radenPurple,
      replace = plt.shuiro,
      command = plt.radenBlue,
    },
    accent = {
      accent1 = plt.makieGold,
      accent2 = plt.cinnabar,
      accent3 = plt.radenBlue,
      accent4 = plt.radenPurple,
      accent5 = plt.shuiro,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.makieGold,
      rainbow2 = plt.cinnabar,
      rainbow3 = plt.radenBlue,
      rainbow4 = plt.antiqueBrass,
      rainbow5 = plt.radenPurple,
      rainbow6 = plt.shuiro,
      rainbow7 = plt.radenGreen,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.antiqueBrass,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.makieGold,
      header2 = plt.cinnabar,
      special = plt.radenPurple,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.crimsonLacquer,
      indent = plt.bg_light,
      indent_scope = plt.makieGold,
      picker = plt.radenBlue,
      yank = plt.warmGold,
      mark = plt.shuiro,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.bloodOxide,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.bloodOxide,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.warmGold,
        indicator = plt.makieGold,
      },
    },
    syn = {
      attribute = plt.warmGold,
      boolean = plt.coral,
      comment = plt.fg_dark,
      constant = plt.coral,
      deprecated = plt.fg_dark,
      func = plt.makieGold,
      identifier = plt.fg_lightest,
      keyword = plt.cinnabar,
      method = plt.richGold,
      number = plt.radenPurple,
      operator = plt.shuiro,
      parameter = plt.fg_mid,
      preproc = plt.radenPurple,
      punct = plt.fg_mid,
      regex = plt.radenGreen,
      special = plt.warmGold,
      special2 = plt.radenPurple,
      special3 = plt.radenBlue,
      statement = plt.cinnabar,
      string = plt.antiqueBrass,
      symbol = plt.shuiro,
      type = plt.radenBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.shuiro,
      warning = plt.warmGold,
      info = plt.radenBlue,
      ok = plt.radenGreen,
      hint = plt.fg_mid,
      virtual_text_error = plt.shuiro,
      virtual_text_warning = plt.warmGold,
      virtual_text_info = plt.radenBlue,
      virtual_text_ok = plt.radenGreen,
      virtual_text_hint = plt.fg_mid,
    },
    diff = {
      add = plt.radenGreen,
      add_inline = plt.radenBlue,
      change = plt.antiqueBrass,
      change_inline = plt.warmGold,
      delete = plt.shrineRed,
      delete_inline = plt.shuiro,
      text = plt.makieGold,
    },
    vcs = {
      added = plt.radenGreen,
      changed = plt.antiqueBrass,
      removed = plt.shrineRed,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.shrineRed,
      green = plt.radenGreen,
      yellow = plt.antiqueBrass,
      blue = plt.radenBlue,
      magenta = plt.radenPurple,
      cyan = plt.radenBlue,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.shrineRed):brighten(0.2):to_hex(),
      green_bright = color(plt.radenGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.antiqueBrass):brighten(0.2):to_hex(),
      blue_bright = color(plt.radenBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.radenPurple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.radenBlue):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.shuiro,
      indexed2 = plt.coral,
    },
  }
end

return {
  name = "Kanagawa Paper – Lacquer",
  author = "PrismPunk",
  description = "A striking, high-contrast palette of deep urushi black, vermilion, and maki-e gold leaf, accented with iridescent abalone shell.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.shuiro,
    base09 = palette.cinnabar,
    base0A = palette.warmGold,
    base0B = palette.makieGold,
    base0C = palette.radenBlue,
    base0D = palette.radenPurple,
    base0E = palette.radenGreen,
    base0F = palette.crimsonLacquer,
  },
  palette = palette,
  get = M.get,
}
