
local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0E1010",
  bg_darker = "#1C2220",
  bg_dark = "#2E3C38",
  bg_mid = "#485848",
  bg_light = "#6A7A64",
  bg_lighter = "#8C9C7E",
  bg_lightest = "#B0C098",

  bg_alt1 = "#24302C",
  bg_alt2 = "#384C44",
  bg_alt3 = "#4C6458",

  fg_lightest = "#D4D8A8",
  fg_light = "#B0C098",
  fg_mid = "#8C9C7E",
  fg_dark = "#6A7A64",

  forestBlack = "#0E1010",
  mossDark = "#1C2220",
  lichenMid = "#2E3C38",
  sage = "#485848",
  olive = "#6A7A64",
  khaki = "#8C9C7E",
  lime = "#B0C098",
  yellow = "#D4C820",
  gold = "#F0E030",
  purple = "#806890",
  lavender = "#A890B8",
  lilac = "#C8B0D8",
  red = "#C05838",
  coral = "#D87858",
  salmon = "#F0A880",

  fg_reverse = "#0E1010",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.lime,
      insert = plt.gold,
      visual = plt.purple,
      replace = plt.red,
      command = plt.lavender,
    },
    accent = {
      accent1 = plt.lime,
      accent2 = plt.gold,
      accent3 = plt.purple,
      accent4 = plt.lavender,
      accent5 = plt.red,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.lime,
      rainbow2 = plt.gold,
      rainbow3 = plt.sage,
      rainbow4 = plt.lilac,
      rainbow5 = plt.lavender,
      rainbow6 = plt.purple,
      rainbow7 = plt.salmon,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.gold,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.lime,
      header2 = plt.gold,
      special = plt.purple,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.purple,
      indent = plt.bg_light,
      indent_scope = plt.lime,
      picker = plt.purple,
      yank = plt.gold,
      mark = plt.coral,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.gold,
        indicator = plt.lime,
      },
    },
    syn = {
      attribute = plt.gold,
      boolean = plt.coral,
      comment = plt.fg_mid,
      constant = plt.coral,
      deprecated = plt.fg_dark,
      func = plt.lime,
      identifier = plt.fg_lightest,
      keyword = plt.purple,
      method = plt.lime,
      number = plt.lavender,
      operator = plt.coral,
      parameter = plt.fg_mid,
      preproc = plt.lavender,
      punct = plt.fg_mid,
      regex = plt.gold,
      special = plt.gold,
      special2 = plt.lavender,
      special3 = plt.sage,
      statement = plt.lavender,
      string = plt.sage,
      symbol = plt.coral,
      type = plt.sage,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.red,
      warning = plt.coral,
      info = plt.lime,
      ok = plt.gold,
      hint = plt.sage,
      virtual_text_error = plt.red,
      virtual_text_warning = plt.coral,
      virtual_text_info = plt.lime,
      virtual_text_ok = plt.gold,
      virtual_text_hint = plt.sage,
    },
    diff = {
      add = plt.gold,
      add_inline = plt.sage,
      change = plt.coral,
      change_inline = plt.salmon,
      delete = plt.red,
      delete_inline = plt.lilac,
      text = plt.lime,
    },
    vcs = {
      added = plt.gold,
      changed = plt.coral,
      removed = plt.red,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.red,
      green = plt.lime,
      yellow = plt.gold,
      blue = plt.sage,
      magenta = plt.purple,
      cyan = plt.lavender,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.red):brighten(0.2):to_hex(),
      green_bright = color(plt.lime):brighten(0.1):to_hex(),
      yellow_bright = color(plt.gold):brighten(0.2):to_hex(),
      blue_bright = color(plt.sage):brighten(0.3):to_hex(),
      magenta_bright = color(plt.purple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.lavender):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.lilac,
      indexed2 = plt.salmon,
    },
  }
end

return {
  name = "Kanagawa Paper – Lichen",
  author = "PrismPunk",
  description = "Dusty sage and pale yellow-greens, cold and earthy.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.red,
    base09 = palette.coral,
    base0A = palette.gold,
    base0B = palette.lime,
    base0C = palette.sage,
    base0D = palette.purple,
    base0E = palette.lavender,
    base0F = palette.mossDark,
  },
  palette = palette,
  get = M.get,
}
