local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#0B100E",
  sumiInk1 = "#16201B",
  sumiInk2 = "#212E26",
  sumiInk3 = "#2C3C31",
  sumiInk4 = "#374A3C",
  sumiInk5 = "#425847",
  sumiInk6 = "#4D6652",
  sumiInkShadow = "#070A09",
  sumiInkEcho = "#111815",
  sumiInkTint = "#1A221E",
  fujiWhite = "#C9D1C7",
  oldWhite = "#B8C0B4",
  dragonGray = "#788076",
  dragonGray2 = "#9CA597",
  dragonBlack2 = "#1C2420",
  dragonBlack3 = "#1A221E",
  dragonBlack5 = "#131816",
  dragonBlack6 = "#0E1210",
  dragonRed = "#D06060",
  dragonPink = "#E08A9A",
  dragonYellow = "#D0B078",
  dragonOrange = "#E0A060",
  dragonGreen = "#76A06A",
  dragonBlue = "#6A90B0",
  dragonViolet = "#9A8AB0",
  dragonAqua = "#6AB0A0",
  mossGlow = "#C9D1C7",
  mossVivid = "#D9E1D7",
  mossFlare = "#E9F1E7",
  mossAccent1 = "#2A322E",
  mossAccent2 = "#333A36",
  mossAccent3 = "#3C423E",
  mossAccent4 = "#454A46",
  mossAccent5 = "#4E5450",
  mossTeal = "#5FA090",
  mossCoral = "#E08A80",
  mossAmber = "#D0B078",
  mossSlate = "#6B7870",

  bg_darkest = "#0E1210",
  fg_lightest = "#C9D1C7",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      command = plt.dragonBlue,
      insert = plt.dragonGreen,
      normal = plt.dragonYellow,
      replace = plt.dragonRed,
      visual = plt.dragonViolet,
    },
    accent = {
      accent1 = plt.dragonGreen,
      accent2 = plt.dragonOrange,
      accent3 = plt.dragonAqua,
      accent4 = plt.dragonGray,
      accent5 = plt.dragonRed,
      invert = plt.sumiInk4,
    },
    rainbow = {
      rainbow1 = plt.dragonRed,
      rainbow2 = plt.dragonPink,
      rainbow3 = plt.dragonYellow,
      rainbow4 = plt.dragonOrange,
      rainbow5 = plt.dragonGreen,
      rainbow6 = plt.dragonBlue,
      rainbow7 = plt.dragonAqua,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.dragonGray2,
      fg_dimmer = plt.dragonGray,
      fg_dark = plt.sumiInk5,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInk2,
      bg_m3 = plt.sumiInk3,
      bg_m4 = plt.sumiInk4,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk4 or "none",
      bg_cursorline = plt.sumiInk3,
      bg_cursorline_alt = plt.sumiInk4,
      cursorline = plt.sumiInk3,
      bg_highlight = plt.sumiInk4,
      bg_search = plt.mossGlow,
      bg_visual = plt.sumiInk4,
      bg_statusline = plt.sumiInk4,
      border = plt.dragonBlack6,
      header1 = plt.dragonYellow,
      header2 = plt.dragonGreen,
      special = plt.mossCoral,
      nontext = plt.sumiInk6,
      whitespace = plt.dragonGray,
      win_separator = plt.dragonViolet,
      indent = plt.sumiInk5,
      indent_scope = plt.dragonGreen,
      picker = plt.dragonViolet,
      yank = plt.mossVivid,
      mark = plt.dragonRed,
      scrollbar = plt.sumiInk6,
      selection = plt.sumiInk4,
      line_nr = plt.dragonGray,
      line_nr_dim = plt.sumiInk6,
      line_nr_active = plt.fujiWhite,
      float = {
        fg = plt.dragonGray2,
        bg = plt.sumiInk3,
        fg_border = plt.sumiInk5,
        bg_border = plt.sumiInk3,
      },
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = "none",
        fg_border = plt.sumiInk5,
        bg = plt.sumiInk4,
        bg_sel = plt.sumiInk5,
        bg_border = plt.sumiInk4,
        bg_sbar = plt.sumiInk4,
        bg_thumb = plt.sumiInk5,
      },
      tabline = {
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        bg = plt.sumiInk0,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.dragonYellow,
        indicator = plt.dragonGreen,
      },
    },
    syn = {
      annotation = plt.dragonViolet,
      attribute = plt.dragonYellow,
      boolean = plt.dragonOrange,
      comment = plt.sumiInk5,
      constant = plt.dragonOrange,
      deprecated = plt.sumiInk5,
      func = plt.dragonGreen,
      identifier = plt.fujiWhite,
      keyword = plt.dragonViolet,
      method = plt.dragonGreen,
      number = plt.dragonPink,
      operator = plt.dragonRed,
      parameter = plt.dragonGray,
      preproc = plt.dragonViolet,
      punct = plt.dragonGray,
      regex = plt.dragonYellow,
      special = plt.dragonYellow,
      special2 = plt.dragonViolet,
      special3 = plt.dragonAqua,
      statement = plt.dragonViolet,
      string = plt.dragonGreen,
      symbol = plt.dragonRed,
      type = plt.dragonAqua,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.dragonRed,
      warning = plt.dragonYellow,
      info = plt.dragonBlue,
      ok = plt.dragonGreen,
      hint = plt.dragonAqua,
      virtual_text_error = plt.dragonRed,
      virtual_text_warning = plt.dragonYellow,
      virtual_text_info = plt.dragonBlue,
      virtual_text_ok = plt.dragonGreen,
      virtual_text_hint = plt.dragonAqua,
    },
    diff = {
      add = plt.dragonGreen,
      add_inline = plt.dragonAqua,
      change = plt.dragonYellow,
      change_inline = plt.dragonOrange,
      delete = plt.dragonRed,
      delete_inline = plt.dragonPink,
      text = plt.dragonBlue,
    },
    vcs = {
      added = plt.dragonGreen,
      changed = plt.dragonYellow,
      removed = plt.dragonRed,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.dragonRed,
      green = plt.dragonGreen,
      yellow = plt.dragonYellow,
      blue = plt.dragonBlue,
      magenta = plt.dragonPink,
      cyan = plt.dragonAqua,
      white = plt.dragonGray2,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.dragonRed):brighten(0.2):to_hex(),
      green_bright = color(plt.dragonGreen):brighten(0.1):to_hex(),
      yellow_bright = color(plt.dragonYellow):brighten(0.2):to_hex(),
      blue_bright = color(plt.dragonBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.dragonPink):brighten(0.2):to_hex(),
      cyan_bright = color(plt.dragonAqua):brighten(0.1):to_hex(),
      white_bright = color(plt.dragonGray2):brighten(0.2):to_hex(),
      indexed1 = plt.mossVivid,
      indexed2 = plt.mossFlare,
    },
  }
end

return {
  name = "Kanagawa Paper – Moss",
  author = "PrismPunk",
  description = "Deep earthy moss-green theme with paper-like warmth and good readability.",
  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk5,
    base05 = palette.sumiInk6,
    base06 = palette.dragonGray2,
    base07 = palette.fujiWhite,
    base08 = palette.dragonRed,
    base09 = palette.dragonOrange,
    base0A = palette.dragonYellow,
    base0B = palette.dragonGreen,
    base0C = palette.dragonAqua,
    base0D = palette.dragonBlue,
    base0E = palette.dragonViolet,
    base0F = palette.dragonPink,
  },
  palette = palette,
  get = M.get,
}
