
local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0C0E10",
  bg_darker = "#1A1E22",
  bg_dark = "#2E3438",
  bg_mid = "#464E54",
  bg_light = "#687076",
  bg_lighter = "#8A9298",
  bg_lightest = "#ACC0C8",

  bg_alt1 = "#1E2428",
  bg_alt2 = "#30383C",
  bg_alt3 = "#4A5258",

  fg_lightest = "#D4E4E8",
  fg_light = "#ACC0C8",
  fg_mid = "#8A9298",
  fg_dark = "#687076",

  arcticBlack = "#0C0E10",
  glacierDark = "#1A1E22",
  frostMid = "#2E3438",
  iceBlue = "#3060A8",
  frostBlue = "#5888C8",
  skyBlue = "#90B8E0",
  cloudLight = "#C8E0F0",
  lavender = "#9858B0",
  purple = "#B880D0",
  lilac = "#D8B0F0",
  amber = "#D89030",

  fg_reverse = "#0C0E10",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.iceBlue,
      insert = plt.skyBlue,
      visual = plt.lavender,
      replace = plt.amber,
      command = plt.purple,
    },
    accent = {
      accent1 = plt.iceBlue,
      accent2 = plt.frostBlue,
      accent3 = plt.skyBlue,
      accent4 = plt.lavender,
      accent5 = plt.amber,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.iceBlue,
      rainbow2 = plt.frostBlue,
      rainbow3 = plt.skyBlue,
      rainbow4 = plt.cloudLight,
      rainbow5 = plt.lavender,
      rainbow6 = plt.purple,
      rainbow7 = plt.lilac,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.cloudLight,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.iceBlue,
      header2 = plt.frostBlue,
      special = plt.lavender,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.lavender,
      indent = plt.bg_light,
      indent_scope = plt.iceBlue,
      picker = plt.lavender,
      yank = plt.cloudLight,
      mark = plt.amber,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.amber,
        indicator = plt.iceBlue,
      },
    },
    syn = {
      attribute = plt.frostBlue,
      boolean = plt.amber,
      comment = plt.fg_mid,
      constant = plt.amber,
      deprecated = plt.fg_dark,
      func = plt.iceBlue,
      identifier = plt.fg_lightest,
      keyword = plt.lavender,
      method = plt.iceBlue,
      number = plt.purple,
      operator = plt.amber,
      parameter = plt.fg_mid,
      preproc = plt.purple,
      punct = plt.fg_mid,
      regex = plt.frostBlue,
      special = plt.frostBlue,
      special2 = plt.purple,
      special3 = plt.skyBlue,
      statement = plt.purple,
      string = plt.skyBlue,
      symbol = plt.amber,
      type = plt.skyBlue,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.amber,
      warning = plt.lilac,
      info = plt.iceBlue,
      ok = plt.skyBlue,
      hint = plt.frostBlue,
      virtual_text_error = plt.amber,
      virtual_text_warning = plt.lilac,
      virtual_text_info = plt.iceBlue,
      virtual_text_ok = plt.skyBlue,
      virtual_text_hint = plt.frostBlue,
    },
    diff = {
      add = plt.skyBlue,
      add_inline = plt.frostBlue,
      change = plt.lilac,
      change_inline = plt.purple,
      delete = plt.amber,
      delete_inline = plt.lavender,
      text = plt.iceBlue,
    },
    vcs = {
      added = plt.skyBlue,
      changed = plt.lilac,
      removed = plt.amber,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.amber,
      green = plt.skyBlue,
      yellow = plt.lilac,
      blue = plt.iceBlue,
      magenta = plt.purple,
      cyan = plt.frostBlue,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.amber):brighten(0.2):to_hex(),
      green_bright = color(plt.skyBlue):brighten(0.1):to_hex(),
      yellow_bright = color(plt.lilac):brighten(0.2):to_hex(),
      blue_bright = color(plt.iceBlue):brighten(0.3):to_hex(),
      magenta_bright = color(plt.purple):brighten(0.2):to_hex(),
      cyan_bright = color(plt.frostBlue):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.lavender,
      indexed2 = plt.cloudLight,
    },
  }
end

return {
  name = "Kanagawa Paper – Permafrost",
  author = "PrismPunk",
  description = "Desaturated cool greys and glacier blues, cold and minimal.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.amber,
    base09 = palette.purple,
    base0A = palette.lilac,
    base0B = palette.skyBlue,
    base0C = palette.frostBlue,
    base0D = palette.iceBlue,
    base0E = palette.lavender,
    base0F = palette.glacierDark,
  },
  palette = palette,
  get = M.get,
}
