local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#100C06",
  bg_darker = "#201808",
  bg_dark = "#342810",
  bg_mid = "#4E3C1A",
  bg_light = "#6C5224",
  bg_lighter = "#8A6A30",
  bg_lightest = "#AA823C",

  bg_alt1 = "#282010",
  bg_alt2 = "#3C3018",
  bg_alt3 = "#584420",

  fg_lightest = "#FFF8C0",
  fg_light = "#F8D040",
  fg_mid = "#D8A858",
  fg_dark = "#B48040",

  earthBlack = "#100C06",
  umber = "#201808",
  clay = "#342810",
  ochre = "#4E3C1A",
  sienna = "#6C5224",
  bronze = "#906830",
  brass = "#B48040",
  gold = "#D8A858",
  amber = "#F8D040",
  cream = "#FFF8C0",
  vermillion = "#C03010",
  rust = "#E05020",
  cobalt = "#3060B0",
  azure = "#5080D0",
  jade = "#70C850",
  lime = "#90E060",

  fg_reverse = "#100C06",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.azure,
      insert = plt.amber,
      visual = plt.cobalt,
      replace = plt.rust,
      command = plt.jade,
    },
    accent = {
      accent1 = plt.azure,
      accent2 = plt.amber,
      accent3 = plt.cobalt,
      accent4 = plt.jade,
      accent5 = plt.rust,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.azure,
      rainbow2 = plt.amber,
      rainbow3 = plt.jade,
      rainbow4 = plt.cobalt,
      rainbow5 = plt.rust,
      rainbow6 = plt.lime,
      rainbow7 = plt.vermillion,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.amber,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.azure,
      header2 = plt.amber,
      special = plt.cobalt,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.cobalt,
      indent = plt.bg_light,
      indent_scope = plt.azure,
      picker = plt.cobalt,
      yank = plt.amber,
      mark = plt.jade,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.amber,
        indicator = plt.azure,
      },
    },
    syn = {
      attribute = plt.amber,
      boolean = plt.rust,
      comment = plt.fg_mid,
      constant = plt.rust,
      deprecated = plt.fg_dark,
      func = plt.azure,
      identifier = plt.fg_lightest,
      keyword = plt.cobalt,
      method = plt.azure,
      number = plt.jade,
      operator = plt.rust,
      parameter = plt.fg_mid,
      preproc = plt.jade,
      punct = plt.fg_mid,
      regex = plt.amber,
      special = plt.amber,
      special2 = plt.jade,
      special3 = plt.bronze,
      statement = plt.jade,
      string = plt.lime,
      symbol = plt.rust,
      type = plt.cobalt,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.vermillion,
      warning = plt.rust,
      info = plt.azure,
      ok = plt.amber,
      hint = plt.jade,
      virtual_text_error = plt.vermillion,
      virtual_text_warning = plt.rust,
      virtual_text_info = plt.azure,
      virtual_text_ok = plt.amber,
      virtual_text_hint = plt.jade,
    },
    diff = {
      add = plt.amber,
      add_inline = plt.lime,
      change = plt.rust,
      change_inline = plt.vermillion,
      delete = plt.vermillion,
      delete_inline = plt.umber,
      text = plt.azure,
    },
    vcs = {
      added = plt.amber,
      changed = plt.rust,
      removed = plt.vermillion,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.vermillion,
      green = plt.jade,
      yellow = plt.amber,
      blue = plt.cobalt,
      magenta = plt.rust,
      cyan = plt.azure,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.vermillion):brighten(0.2):to_hex(),
      green_bright = color(plt.jade):brighten(0.1):to_hex(),
      yellow_bright = color(plt.amber):brighten(0.2):to_hex(),
      blue_bright = color(plt.cobalt):brighten(0.3):to_hex(),
      magenta_bright = color(plt.rust):brighten(0.2):to_hex(),
      cyan_bright = color(plt.azure):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.lime,
      indexed2 = plt.bronze,
    },
  }
end

return {
  name = "Kanagawa Paper – Rakuichi",
  author = "PrismPunk",
  description = "Dark earthy mid-tones with muted market-stall warmth.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.vermillion,
    base09 = palette.rust,
    base0A = palette.amber,
    base0B = palette.jade,
    base0C = palette.azure,
    base0D = palette.cobalt,
    base0E = palette.lime,
    base0F = palette.umber,
  },
  palette = palette,
  get = M.get,
}
