local color = require("prismpunk.utils.color")

local palette = {
  sumiInk0 = "#292528",
  sumiInk1 = "#2C2C2E",
  sumiInk2 = "#373A3E",
  sumiInk3 = "#45455B",
  sumiInk4 = "#60768C",
  sumiInkShadow = "#162127",
  sumiInkEcho = "#2B313F",
  sumiInkTint = "#1F4433",
  sumiInkDeep = "#01344F",
  sumiInkRidge = "#3A3534",
  fujiWhite = "#D1AEA6",
  oldWhite = "#E8D8C9",
  softGray = "#8C7C6C",
  dragonGray = "#60768C",
  dragonGray2 = "#879EBF",
  roninRed1 = "#AD3A3C",
  roninRed2 = "#8B0000",
  roninRedGlow = "#B83A2D",
  roninRedVivid = "#D12128",
  roninBrown1 = "#A67D43",
  roninBrown2 = "#Cf9D7B",
  roninBrown3 = "#CFB787",
  roninBrownGlow = "#DCC9A9",
  roninBrownFlare = "#E8D8C9",
  roninOrange1 = "#F26838",
  roninOrange2 = "#FBC359",
  roninGreen1 = "#4E6851",
  roninGreen2 = "#73A642",
  roninGreenGlow = "#4B848A",
  roninTeal1 = "#3E6868",
  roninTeal2 = "#4B848A",
  roninTeal3 = "#134857",
  roninTeal4 = "#0F95B0",
  roninBlue1 = "#4B607F",
  roninBlue2 = "#60768C",
  roninBlue3 = "#45455B",
  roninAccent1 = "#2B313F",
  roninAccent2 = "#373A3E",
  roninAccent3 = "#45455B",
  roninAccent4 = "#4B607F",
  roninAccent5 = "#60768C",

  bg_darkest = "#292528",
  fg_lightest = "#D1AEA6",
}

local M = {}

M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.roninBrown1,
      insert = plt.roninGreen1,
      visual = plt.roninTeal2,
      replace = plt.roninRed1,
      command = plt.roninBrown3,
    },
    accent = {
      accent1 = plt.roninRed1,
      accent2 = plt.roninBrown1,
      accent3 = plt.roninTeal2,
      accent4 = plt.roninOrange1,
      accent5 = plt.roninGreen1,
      invert = plt.sumiInk3,
    },
    rainbow = {
      rainbow1 = plt.roninRed1,
      rainbow2 = plt.roninOrange1,
      rainbow3 = plt.roninBrown3,
      rainbow4 = plt.roninGreen1,
      rainbow5 = plt.roninTeal2,
      rainbow6 = plt.roninBlue1,
      rainbow7 = plt.roninBrown2,
    },
    ui = {
      fg = plt.fujiWhite,
      fg_dim = plt.oldWhite,
      fg_dimmer = plt.softGray,
      fg_dark = plt.dragonGray,
      fg_reverse = plt.sumiInk0,
      bg = plt.sumiInk0,
      bg_dim = plt.sumiInk0,
      bg_m1 = plt.sumiInk1,
      bg_m2 = plt.sumiInkEcho,
      bg_m3 = plt.sumiInk2,
      bg_m4 = plt.sumiInk3,
      bg_p1 = plt.sumiInk2,
      bg_p2 = plt.sumiInk3,
      bg_gutter = (opts.gutter ~= false) and plt.sumiInk1 or "none",
      bg_cursorline = plt.sumiInk2,
      bg_cursorline_alt = plt.sumiInk3,
      cursorline = plt.sumiInk2,
      bg_highlight = plt.sumiInk3,
      bg_search = plt.roninAccent2,
      bg_visual = plt.sumiInk3,
      bg_statusline = plt.sumiInk1,
      border = plt.sumiInk4,
      header1 = plt.roninBrown1,
      header2 = plt.roninOrange2,
      special = plt.roninTeal4,
      nontext = plt.sumiInk3,
      whitespace = plt.sumiInk3,
      win_separator = plt.sumiInk4,
      indent = plt.sumiInk2,
      indent_scope = plt.roninBrown1,
      picker = plt.roninTeal2,
      yank = plt.roninBrownGlow,
      mark = plt.roninRedGlow,
      scrollbar = plt.sumiInk3,
      selection = plt.sumiInk3,
      line_nr = plt.sumiInk4,
      line_nr_dim = plt.sumiInk3,
      line_nr_active = plt.fujiWhite,
      pmenu = {
        fg = plt.fujiWhite,
        fg_sel = plt.fujiWhite,
        fg_border = plt.sumiInk4,
        bg = plt.sumiInk2,
        bg_sel = plt.sumiInk3,
        bg_border = plt.sumiInk2,
        bg_sbar = plt.sumiInk2,
        bg_thumb = plt.sumiInk4,
      },
      float = {
        fg = plt.oldWhite,
        bg = plt.sumiInk2,
        fg_border = plt.sumiInk4,
        bg_border = plt.sumiInk2,
      },
      tabline = {
        bg = plt.sumiInk0,
        bg_inactive = plt.sumiInk0,
        bg_selected = plt.sumiInk2,
        bg_alternate = plt.sumiInk1,
        fg_inactive = plt.dragonGray,
        fg_selected = plt.fujiWhite,
        fg_alternate = plt.roninBrown1,
        indicator = plt.roninBrown1,
      },
    },
    syn = {
      attribute = plt.oldWhite,
      boolean = plt.roninTeal2,
      comment = plt.softGray,
      constant = plt.oldWhite,
      deprecated = plt.dragonGray,
      func = plt.roninBlue1,
      identifier = plt.fujiWhite,
      keyword = plt.roninRed1,
      method = plt.roninBlue1,
      number = plt.roninBrown3,
      operator = plt.roninOrange2,
      parameter = plt.oldWhite,
      preproc = plt.roninTeal2,
      punct = plt.softGray,
      regex = plt.roninTeal1,
      special = plt.roninOrange1,
      special2 = plt.roninBrown2,
      special3 = plt.roninTeal4,
      statement = plt.roninRed1,
      string = plt.roninGreen2,
      symbol = plt.roninRedGlow,
      type = plt.roninTeal2,
      variable = plt.fujiWhite,
    },
    diag = {
      error = plt.roninRed1,
      warning = plt.roninOrange2,
      info = plt.roninTeal2,
      hint = plt.roninGreen1,
      ok = plt.roninGreen2,
      virtual_text_error = plt.roninRedGlow,
      virtual_text_warning = plt.roninOrange1,
      virtual_text_info = plt.roninTeal2,
      virtual_text_hint = plt.roninGreen2,
      virtual_text_ok = plt.roninGreenGlow,
    },
    diff = {
      add = plt.roninGreen1,
      add_inline = plt.roninGreenGlow,
      change = plt.roninBrown3,
      change_inline = plt.roninBrownGlow,
      delete = plt.roninRed1,
      delete_inline = plt.roninRedGlow,
      text = plt.roninTeal2,
    },
    vcs = {
      added = plt.roninGreen1,
      changed = plt.roninBrown3,
      removed = plt.roninRed1,
    },
    term = {
      black = plt.sumiInk0,
      red = plt.roninRed1,
      green = plt.roninGreen1,
      yellow = plt.roninBrown3,
      blue = plt.roninTeal2,
      magenta = plt.roninBlue1,
      cyan = plt.roninTeal4,
      white = plt.oldWhite,
      black_bright = color(plt.sumiInk0):brighten(0.6):to_hex(),
      red_bright = color(plt.roninRed1):brighten(0.2):to_hex(),
      green_bright = color(plt.roninGreen1):brighten(0.1):to_hex(),
      yellow_bright = color(plt.roninBrown3):brighten(0.2):to_hex(),
      blue_bright = color(plt.roninTeal2):brighten(0.3):to_hex(),
      magenta_bright = color(plt.roninBlue1):brighten(0.2):to_hex(),
      cyan_bright = color(plt.roninTeal4):brighten(0.1):to_hex(),
      white_bright = color(plt.oldWhite):brighten(0.2):to_hex(),
      indexed1 = plt.roninOrange1,
      indexed2 = plt.roninTeal4,
    },
  }
end

return {
  name = "Kanagawa Paper – Ronin",
  author = "PrismPunk.nvim",
  description = "Weathered, muted dark theme with warm tones of antique brass and aged leather.",

  base16 = {
    base00 = palette.sumiInk0,
    base01 = palette.sumiInk1,
    base02 = palette.sumiInk2,
    base03 = palette.sumiInk3,
    base04 = palette.sumiInk4,
    base05 = palette.fujiWhite,
    base06 = palette.oldWhite,
    base07 = palette.softGray,
    base08 = palette.roninRed1,
    base09 = palette.roninRedGlow,
    base0A = palette.roninBrown1,
    base0B = palette.roninGreen1,
    base0C = palette.roninTeal2,
    base0D = palette.roninBlue1,
    base0E = palette.roninTeal1,
    base0F = palette.roninOrange1,
  },

  palette = palette,
  get = M.get,
}
