local color = require("prismpunk.utils.color")

local palette = {
  bg_darkest = "#0C0808",
  bg_darker = "#1C1010",
  bg_dark = "#301414",
  bg_mid = "#502020",
  bg_light = "#703028",
  bg_lighter = "#904038",
  bg_lightest = "#B05848",

  bg_alt1 = "#241818",
  bg_alt2 = "#3C2818",
  bg_alt3 = "#543830",

  fg_lightest = "#F8F8F0",
  fg_light = "#FFF0E8",
  fg_mid = "#E0B880",
  fg_dark = "#C89060",

  voidBlack = "#0C0808",
  charcoal = "#1C1010",
  umber = "#301414",
  mahogany = "#502020",
  vermillion = "#C84020",
  cinnabar = "#E06030",
  flame = "#FF4820",
  coral = "#FF7040",
  amber = "#E0B880",
  sand = "#C89060",
  jade = "#68A8A0",
  celadon = "#90C8C0",
  teal = "#5C9890",
  ivory = "#FFF0E8",
  pearl = "#F8F8F0",

  fg_reverse = "#0C0808",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.celadon,
      insert = plt.amber,
      visual = plt.vermillion,
      replace = plt.flame,
      command = plt.coral,
    },
    accent = {
      accent1 = plt.celadon,
      accent2 = plt.amber,
      accent3 = plt.vermillion,
      accent4 = plt.coral,
      accent5 = plt.flame,
      invert = plt.bg_darkest,
    },
    rainbow = {
      rainbow1 = plt.celadon,
      rainbow2 = plt.amber,
      rainbow3 = plt.jade,
      rainbow4 = plt.coral,
      rainbow5 = plt.vermillion,
      rainbow6 = plt.cinnabar,
      rainbow7 = plt.flame,
    },
    ui = {
      fg = plt.fg_lightest,
      fg_dim = plt.fg_light,
      fg_dimmer = plt.fg_mid,
      fg_dark = plt.fg_dark,
      fg_reverse = plt.fg_reverse,
      bg = plt.bg_darkest,
      bg_dim = plt.bg_darkest,
      bg_m1 = plt.bg_darker,
      bg_m2 = plt.bg_dark,
      bg_m3 = plt.bg_mid,
      bg_m4 = plt.bg_light,
      bg_p1 = plt.bg_dark,
      bg_p2 = plt.bg_mid,
      bg_gutter = (opts.gutter ~= false) and plt.bg_light or "none",
      bg_cursorline = plt.bg_dark,
      bg_cursorline_alt = plt.bg_mid,
      cursorline = plt.bg_dark,
      bg_highlight = plt.bg_light,
      bg_search = plt.amber,
      bg_visual = plt.bg_light,
      bg_statusline = plt.bg_light,
      border = plt.bg_alt2,
      header1 = plt.celadon,
      header2 = plt.amber,
      special = plt.vermillion,
      nontext = plt.bg_lighter,
      whitespace = plt.fg_dark,
      win_separator = plt.vermillion,
      indent = plt.bg_light,
      indent_scope = plt.celadon,
      picker = plt.vermillion,
      yank = plt.amber,
      mark = plt.coral,
      scrollbar = plt.bg_lighter,
      selection = plt.bg_light,
      line_nr = plt.fg_mid,
      line_nr_dim = plt.bg_lighter,
      line_nr_active = plt.fg_lightest,
      float = {
        fg = plt.fg_light,
        bg = plt.bg_mid,
        fg_border = plt.fg_dark,
        bg_border = plt.bg_mid,
      },
      pmenu = {
        fg = plt.fg_lightest,
        fg_sel = "none",
        fg_border = plt.fg_dark,
        bg = plt.bg_light,
        bg_sel = plt.bg_lighter,
        bg_border = plt.bg_light,
        bg_sbar = plt.bg_light,
        bg_thumb = plt.bg_lighter,
      },
      tabline = {
        bg = plt.bg_darkest,
        bg_inactive = plt.bg_darkest,
        bg_selected = plt.bg_dark,
        bg_alternate = plt.bg_darker,
        fg_inactive = plt.fg_mid,
        fg_selected = plt.fg_lightest,
        fg_alternate = plt.amber,
        indicator = plt.celadon,
      },
    },
    syn = {
      attribute = plt.amber,
      boolean = plt.coral,
      comment = plt.fg_mid,
      constant = plt.coral,
      deprecated = plt.fg_dark,
      func = plt.celadon,
      identifier = plt.fg_lightest,
      keyword = plt.vermillion,
      method = plt.celadon,
      number = plt.coral,
      operator = plt.coral,
      parameter = plt.fg_mid,
      preproc = plt.coral,
      punct = plt.fg_mid,
      regex = plt.amber,
      special = plt.amber,
      special2 = plt.coral,
      special3 = plt.jade,
      statement = plt.coral,
      string = plt.jade,
      symbol = plt.coral,
      type = plt.teal,
      variable = plt.fg_lightest,
    },
    diag = {
      error = plt.flame,
      warning = plt.coral,
      info = plt.celadon,
      ok = plt.amber,
      hint = plt.jade,
      virtual_text_error = plt.flame,
      virtual_text_warning = plt.coral,
      virtual_text_info = plt.celadon,
      virtual_text_ok = plt.amber,
      virtual_text_hint = plt.jade,
    },
    diff = {
      add = plt.amber,
      add_inline = plt.jade,
      change = plt.coral,
      change_inline = plt.cinnabar,
      delete = plt.flame,
      delete_inline = plt.vermillion,
      text = plt.celadon,
    },
    vcs = {
      added = plt.amber,
      changed = plt.coral,
      removed = plt.flame,
    },
    term = {
      black = plt.bg_darkest,
      red = plt.flame,
      green = plt.celadon,
      yellow = plt.amber,
      blue = plt.jade,
      magenta = plt.vermillion,
      cyan = plt.teal,
      white = plt.fg_light,
      black_bright = color(plt.bg_darkest):brighten(0.6):to_hex(),
      red_bright = color(plt.flame):brighten(0.2):to_hex(),
      green_bright = color(plt.celadon):brighten(0.1):to_hex(),
      yellow_bright = color(plt.amber):brighten(0.2):to_hex(),
      blue_bright = color(plt.jade):brighten(0.3):to_hex(),
      magenta_bright = color(plt.vermillion):brighten(0.2):to_hex(),
      cyan_bright = color(plt.teal):brighten(0.1):to_hex(),
      white_bright = color(plt.fg_light):brighten(0.2):to_hex(),
      indexed1 = plt.cinnabar,
      indexed2 = plt.sand,
    },
  }
end

return {
  name = "Kanagawa Paper – Shrine Gate",
  author = "PrismPunk",
  description = "Vermillion and dark wood-black, stark and ceremonial.",
  base16 = {
    base00 = palette.bg_darkest,
    base01 = palette.bg_darker,
    base02 = palette.bg_dark,
    base03 = palette.bg_mid,
    base04 = palette.fg_dark,
    base05 = palette.fg_mid,
    base06 = palette.fg_light,
    base07 = palette.fg_lightest,
    base08 = palette.flame,
    base09 = palette.coral,
    base0A = palette.amber,
    base0B = palette.celadon,
    base0C = palette.jade,
    base0D = palette.vermillion,
    base0E = palette.coral,
    base0F = palette.charcoal,
  },
  palette = palette,
  get = M.get,
}
