local color = require("prismpunk.utils.color")

local palette = {
  inkBlack = "#0C0A08",
  charcoalBlack = "#1C1A14",
  umberBlack = "#2C2A1C",
  tealDeep = "#285048",
  tealMid = "#3C6858",
  tealBright = "#48A8C0",
  tealPale = "#70C8E0",
  rustDeep = "#883820",
  rustBright = "#E83828",
  rustPale = "#F06050",
  goldDeep = "#C09020",
  goldMid = "#D8C870",
  plumDeep = "#A848A0",
  plumBright = "#C870C0",
  paperWarm = "#F8F0D0",
  paperBright = "#FFFAE8",
  bg_darkest = "#0C0A08",
  fg_lightest = "#FFFAE8",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.tealMid,
      insert = plt.tealBright,
      visual = plt.plumBright,
      replace = plt.rustBright,
      command = plt.goldMid,
    },
    accent = {
      accent1 = plt.tealBright,
      accent2 = plt.rustBright,
      accent3 = plt.goldMid,
      accent4 = plt.plumBright,
      accent5 = plt.paperWarm,
      invert = plt.inkBlack,
    },
    rainbow = {
      rainbow1 = plt.rustBright,
      rainbow2 = plt.goldMid,
      rainbow3 = plt.tealBright,
      rainbow4 = plt.plumBright,
      rainbow5 = plt.tealPale,
      rainbow6 = plt.paperWarm,
      rainbow7 = plt.rustDeep,
    },
    ui = {
      fg = plt.paperBright,
      fg_dim = plt.paperWarm,
      fg_dimmer = plt.goldMid,
      fg_dark = plt.tealMid,
      fg_reverse = plt.inkBlack,
      bg = plt.inkBlack,
      bg_dim = plt.inkBlack,
      bg_m1 = plt.charcoalBlack,
      bg_m2 = plt.umberBlack,
      bg_m3 = plt.tealDeep,
      bg_m4 = plt.tealMid,
      bg_p1 = plt.charcoalBlack,
      bg_p2 = plt.umberBlack,
      bg_gutter = (opts.gutter ~= false) and plt.charcoalBlack or "none",
      bg_cursorline = plt.charcoalBlack,
      bg_cursorline_alt = plt.umberBlack,
      cursorline = plt.charcoalBlack,
      bg_highlight = plt.tealDeep,
      bg_search = plt.goldDeep,
      bg_visual = plt.plumDeep,
      bg_statusline = plt.charcoalBlack,
      border = plt.umberBlack,
      header1 = plt.tealBright,
      header2 = plt.goldMid,
      special = plt.rustBright,
      nontext = plt.umberBlack,
      whitespace = plt.tealDeep,
      win_separator = plt.umberBlack,
      indent = plt.charcoalBlack,
      indent_scope = plt.tealDeep,
      picker = plt.tealBright,
      yank = plt.goldMid,
      mark = plt.plumBright,
      scrollbar = plt.umberBlack,
      selection = plt.tealDeep,
      line_nr = plt.tealMid,
      line_nr_dim = plt.umberBlack,
      line_nr_active = plt.paperBright,
      float = {
        fg = plt.paperWarm,
        bg = plt.umberBlack,
        fg_border = plt.tealMid,
        bg_border = plt.umberBlack,
      },
      pmenu = {
        fg = plt.paperBright,
        fg_sel = plt.paperBright,
        fg_border = plt.tealMid,
        bg = plt.charcoalBlack,
        bg_sel = plt.tealDeep,
        bg_border = plt.charcoalBlack,
        bg_sbar = plt.charcoalBlack,
        bg_thumb = plt.umberBlack,
      },
      tabline = {
        bg = plt.inkBlack,
        bg_inactive = plt.inkBlack,
        bg_selected = plt.charcoalBlack,
        bg_alternate = plt.charcoalBlack,
        fg_inactive = plt.tealMid,
        fg_selected = plt.paperBright,
        fg_alternate = plt.goldMid,
        indicator = plt.tealBright,
      },
    },
    syn = {
      attribute = plt.goldMid,
      boolean = plt.rustBright,
      comment = plt.tealMid,
      constant = plt.paperWarm,
      deprecated = plt.umberBlack,
      func = plt.tealBright,
      identifier = plt.paperWarm,
      keyword = plt.rustBright,
      method = plt.tealBright,
      number = plt.goldMid,
      operator = plt.tealPale,
      parameter = plt.paperWarm,
      preproc = plt.plumBright,
      punct = plt.tealMid,
      regex = plt.goldDeep,
      special = plt.rustBright,
      special2 = plt.plumBright,
      special3 = plt.rustDeep,
      statement = plt.rustBright,
      string = plt.goldMid,
      symbol = plt.tealPale,
      type = plt.tealPale,
      variable = plt.paperBright,
    },
    diag = {
      error = plt.rustBright,
      warning = plt.goldDeep,
      info = plt.tealBright,
      hint = plt.plumBright,
      ok = plt.tealPale,
      virtual_text_error = plt.rustBright,
      virtual_text_warning = plt.goldDeep,
      virtual_text_info = plt.tealBright,
      virtual_text_hint = plt.plumBright,
      virtual_text_ok = plt.tealPale,
    },
    diff = {
      add = plt.tealDeep,
      add_inline = plt.tealBright,
      change = plt.goldDeep,
      change_inline = plt.goldMid,
      delete = plt.rustDeep,
      delete_inline = plt.rustBright,
      text = plt.umberBlack,
    },
    vcs = {
      added = plt.tealBright,
      changed = plt.goldMid,
      removed = plt.rustBright,
    },
    term = {
      black = plt.inkBlack,
      red = plt.rustDeep,
      green = plt.tealMid,
      yellow = plt.goldDeep,
      blue = plt.tealBright,
      magenta = plt.plumDeep,
      cyan = plt.tealPale,
      white = plt.paperWarm,
      black_bright = color(plt.inkBlack):brighten(0.6):to_hex(),
      red_bright = color(plt.rustDeep):brighten(0.2):to_hex(),
      green_bright = color(plt.tealMid):brighten(0.2):to_hex(),
      yellow_bright = color(plt.goldDeep):brighten(0.2):to_hex(),
      blue_bright = color(plt.tealBright):brighten(0.2):to_hex(),
      magenta_bright = color(plt.plumDeep):brighten(0.3):to_hex(),
      cyan_bright = color(plt.tealPale):brighten(0.1):to_hex(),
      white_bright = color(plt.paperWarm):brighten(0.1):to_hex(),
      indexed1 = plt.paperBright,
      indexed2 = plt.umberBlack,
    },
  }
end

return {
  name = "Paper – Ukiyo-e",
  author = "PrismPunk.nvim",
  description = "Flat woodblock print aesthetic. Warm black ink ground, teal water and pine, rust earth and structure, muted gold light, plum fabric shadows. No gradients, no depth — just carved colour blocks on rice paper.",

  base16 = {
    base00 = palette.inkBlack,
    base01 = palette.charcoalBlack,
    base02 = palette.umberBlack,
    base03 = palette.tealDeep,
    base04 = palette.tealMid,
    base05 = palette.paperBright,
    base06 = palette.paperWarm,
    base07 = palette.goldMid,
    base08 = palette.rustBright,
    base09 = palette.rustDeep,
    base0A = palette.goldDeep,
    base0B = palette.tealMid,
    base0C = palette.tealBright,
    base0D = palette.tealPale,
    base0E = palette.plumBright,
    base0F = palette.rustPale,
  },

  palette = palette,
  get = M.get,
}
