local color = require("prismpunk.utils.color")

local palette = {
  abyssNavy = "#06080E",
  deepNavy = "#0C1428",
  trenchNavy = "#142040",
  waveNavy = "#1C3060",
  swellNavy = "#244080",
  crestNavy = "#2860A0",
  sprayBlue = "#60A0C8",
  foamWhite = "#D8EEF8",
  crestWhite = "#F8FCFF",
  undertowIndigo = "#1840A8",
  currentIndigo = "#3060D0",
  horizonDeep = "#C87020",
  horizonWarm = "#E8A030",
  horizonBright = "#F0D060",
  dangerDeep = "#C82020",
  dangerBright = "#E84030",
  bg_darkest = "#06080E",
  fg_lightest = "#F8FCFF",
}

local M = {}

---@param opts table|nil
---@param plt table|nil
---@return table
M.get = function(opts, plt)
  plt = plt or palette
  opts = opts or {}
  return {
    modes = {
      normal = plt.sprayBlue,
      insert = plt.currentIndigo,
      visual = plt.waveNavy,
      replace = plt.dangerBright,
      command = plt.foamWhite,
    },
    accent = {
      accent1 = plt.currentIndigo,
      accent2 = plt.horizonWarm,
      accent3 = plt.dangerBright,
      accent4 = plt.foamWhite,
      accent5 = plt.horizonBright,
      invert = plt.abyssNavy,
    },
    rainbow = {
      rainbow1 = plt.dangerBright,
      rainbow2 = plt.horizonWarm,
      rainbow3 = plt.horizonBright,
      rainbow4 = plt.currentIndigo,
      rainbow5 = plt.sprayBlue,
      rainbow6 = plt.foamWhite,
      rainbow7 = plt.undertowIndigo,
    },
    ui = {
      fg = plt.crestWhite,
      fg_dim = plt.foamWhite,
      fg_dimmer = plt.sprayBlue,
      fg_dark = plt.crestNavy,
      fg_reverse = plt.abyssNavy,
      bg = plt.abyssNavy,
      bg_dim = plt.abyssNavy,
      bg_m1 = plt.deepNavy,
      bg_m2 = plt.trenchNavy,
      bg_m3 = plt.waveNavy,
      bg_m4 = plt.swellNavy,
      bg_p1 = plt.trenchNavy,
      bg_p2 = plt.waveNavy,
      bg_gutter = (opts.gutter ~= false) and plt.deepNavy or "none",
      bg_cursorline = plt.trenchNavy,
      bg_cursorline_alt = plt.waveNavy,
      cursorline = plt.trenchNavy,
      bg_highlight = plt.undertowIndigo,
      bg_search = plt.currentIndigo,
      bg_visual = plt.waveNavy,
      bg_statusline = plt.deepNavy,
      border = plt.swellNavy,
      header1 = plt.currentIndigo,
      header2 = plt.sprayBlue,
      special = plt.horizonWarm,
      nontext = plt.swellNavy,
      whitespace = plt.waveNavy,
      win_separator = plt.waveNavy,
      indent = plt.trenchNavy,
      indent_scope = plt.undertowIndigo,
      picker = plt.currentIndigo,
      yank = plt.horizonBright,
      mark = plt.sprayBlue,
      scrollbar = plt.swellNavy,
      selection = plt.undertowIndigo,
      line_nr = plt.crestNavy,
      line_nr_dim = plt.waveNavy,
      line_nr_active = plt.crestWhite,
      float = {
        fg = plt.foamWhite,
        bg = plt.waveNavy,
        fg_border = plt.crestNavy,
        bg_border = plt.waveNavy,
      },
      pmenu = {
        fg = plt.crestWhite,
        fg_sel = plt.crestWhite,
        fg_border = plt.crestNavy,
        bg = plt.trenchNavy,
        bg_sel = plt.undertowIndigo,
        bg_border = plt.trenchNavy,
        bg_sbar = plt.trenchNavy,
        bg_thumb = plt.swellNavy,
      },
      tabline = {
        bg = plt.abyssNavy,
        bg_inactive = plt.abyssNavy,
        bg_selected = plt.trenchNavy,
        bg_alternate = plt.deepNavy,
        fg_inactive = plt.crestNavy,
        fg_selected = plt.crestWhite,
        fg_alternate = plt.sprayBlue,
        indicator = plt.currentIndigo,
      },
    },
    syn = {
      attribute = plt.sprayBlue,
      boolean = plt.horizonBright,
      comment = plt.crestNavy,
      constant = plt.crestWhite,
      deprecated = plt.swellNavy,
      func = plt.currentIndigo,
      identifier = plt.foamWhite,
      keyword = plt.horizonWarm,
      method = plt.currentIndigo,
      number = plt.horizonBright,
      operator = plt.sprayBlue,
      parameter = plt.foamWhite,
      preproc = plt.undertowIndigo,
      punct = plt.crestNavy,
      regex = plt.horizonWarm,
      special = plt.horizonWarm,
      special2 = plt.sprayBlue,
      special3 = plt.dangerDeep,
      statement = plt.horizonWarm,
      string = plt.foamWhite,
      symbol = plt.sprayBlue,
      type = plt.sprayBlue,
      variable = plt.crestWhite,
    },
    diag = {
      error = plt.dangerBright,
      warning = plt.horizonWarm,
      info = plt.currentIndigo,
      hint = plt.sprayBlue,
      ok = plt.foamWhite,
      virtual_text_error = plt.dangerBright,
      virtual_text_warning = plt.horizonWarm,
      virtual_text_info = plt.currentIndigo,
      virtual_text_hint = plt.sprayBlue,
      virtual_text_ok = plt.foamWhite,
    },
    diff = {
      add = plt.undertowIndigo,
      add_inline = plt.currentIndigo,
      change = plt.horizonWarm,
      change_inline = plt.horizonBright,
      delete = plt.dangerDeep,
      delete_inline = plt.dangerBright,
      text = plt.waveNavy,
    },
    vcs = {
      added = plt.currentIndigo,
      changed = plt.horizonWarm,
      removed = plt.dangerBright,
    },
    term = {
      black = plt.abyssNavy,
      red = plt.dangerDeep,
      green = plt.sprayBlue,
      yellow = plt.horizonWarm,
      blue = plt.undertowIndigo,
      magenta = plt.currentIndigo,
      cyan = plt.crestNavy,
      white = plt.foamWhite,
      black_bright = color(plt.abyssNavy):brighten(0.6):to_hex(),
      red_bright = color(plt.dangerDeep):brighten(0.2):to_hex(),
      green_bright = color(plt.sprayBlue):brighten(0.1):to_hex(),
      yellow_bright = color(plt.horizonWarm):brighten(0.2):to_hex(),
      blue_bright = color(plt.undertowIndigo):brighten(0.3):to_hex(),
      magenta_bright = color(plt.currentIndigo):brighten(0.2):to_hex(),
      cyan_bright = color(plt.crestNavy):brighten(0.2):to_hex(),
      white_bright = color(plt.foamWhite):brighten(0.1):to_hex(),
      indexed1 = plt.crestWhite,
      indexed2 = plt.swellNavy,
    },
  }
end

return {
  name = "Paper – Wavecrest",
  author = "PrismPunk.nvim",
  description = "Hokusai's Great Wave as a colour system. The abyss below, the foam above, the indigo current that connects them — and against all that cold blue inevitability, a single amber horizon and a boat that might not make it.",

  base16 = {
    base00 = palette.abyssNavy,
    base01 = palette.deepNavy,
    base02 = palette.trenchNavy,
    base03 = palette.waveNavy,
    base04 = palette.crestNavy,
    base05 = palette.crestWhite,
    base06 = palette.foamWhite,
    base07 = palette.sprayBlue,
    base08 = palette.dangerBright,
    base09 = palette.horizonWarm,
    base0A = palette.horizonBright,
    base0B = palette.sprayBlue,
    base0C = palette.currentIndigo,
    base0D = palette.undertowIndigo,
    base0E = palette.dangerDeep,
    base0F = palette.horizonDeep,
  },

  palette = palette,
  get = M.get,
}
