local M = {}

local punkpalette = require("prismpunk.palette")
local punkconf = require("prismpunk.config")

M.export_toml = function(theme)
  local c = theme.colors or theme
  local name = theme.name or "PrismPunk Theme"

  local lines = {
    "# " .. name,
    "# Generated by prismpunk.nvim",
    "# " .. os.date("%Y-%m-%d %H:%M:%S"),
    "",
    "[colors.primary]",
    'background = "' .. c.base00 .. '"',
    'foreground = "' .. c.base05 .. '"',
    "",
    "[colors.cursor]",
    'text = "' .. c.base00 .. '"',
    'cursor = "' .. c.base05 .. '"',
    "",
    "[colors.selection]",
    'text = "' .. c.base05 .. '"',
    'background = "' .. c.base02 .. '"',
    "",
    "[colors.normal]",
    'black = "' .. c.base00 .. '"',
    'red = "' .. c.base08 .. '"',
    'green = "' .. c.base0B .. '"',
    'yellow = "' .. c.base0A .. '"',
    'blue = "' .. c.base0D .. '"',
    'magenta = "' .. c.base0E .. '"',
    'cyan = "' .. c.base0C .. '"',
    'white = "' .. c.base05 .. '"',
    "",
    "[colors.bright]",
    'black = "' .. c.base03 .. '"',
    'red = "' .. c.base08 .. '"',
    'green = "' .. c.base0B .. '"',
    'yellow = "' .. c.base0A .. '"',
    'blue = "' .. c.base0D .. '"',
    'magenta = "' .. c.base0E .. '"',
    'cyan = "' .. c.base0C .. '"',
    'white = "' .. c.base07 .. '"',
  }
  return table.concat(lines, "\n")
end

M.write_config = function(theme, path)
  local content = M.export_toml(theme)
  path = vim.fn.expand(path)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  local file = io.open(path, "w")
  if not file then
    vim.notify("Prismpunk: Failed to write " .. path, vim.log.levels.ERROR)
    return false
  end
  file:write(content)
  file:close()
  return true
end

M.reload = function() return true end

M.export_and_reload = function(theme, conf)
  if not conf.config_path then
    vim.notify("Prismpunk: Alacritty config_path not set", vim.log.levels.WARN)
    return
  end

  local success = M.write_config(theme, conf.config_path)

  if success then
    vim.notify("Prismpunk: Alacritty theme exported to " .. conf.config_path, vim.log.levels.INFO)
    if conf.auto_reload then
      vim.notify("Prismpunk: Alacritty requires manual restart to apply theme", vim.log.levels.INFO)
      M.reload()
    end
  end
end

M.export = function(theme_name)
  local parsed = punkconf.parse_theme(theme_name)
  local theme_path
  if parsed.universe then
    theme_path = "prismpunk.themes." .. parsed.universe:gsub("%-", "%.") .. "." .. parsed.name
  else
    theme_path = "prismpunk.themes." .. parsed.name
  end
  local ok, spec = pcall(require, theme_path)
  if not ok then
    vim.notify("Failed to load theme: " .. theme_name, vim.log.levels.ERROR)
    return nil
  end
  return M.export_toml(punkpalette.create_theme(spec))
end

M.save = function(theme_name, output_path)
  output_path = output_path or vim.fn.expand("~/.config/alacritty/prismpunk.toml")
  local parsed = punkconf.parse_theme(theme_name)
  local theme_path
  if parsed.universe then
    theme_path = "prismpunk.themes." .. parsed.universe:gsub("%-", "%.") .. "." .. parsed.name
  else
    theme_path = "prismpunk.themes." .. parsed.name
  end
  local ok, spec = pcall(require, theme_path)
  if not ok then
    vim.notify("Failed to load theme: " .. theme_name, vim.log.levels.ERROR)
    return
  end
  local success = M.write_config(punkpalette.create_theme(spec), output_path)
  if success then vim.notify("Exported to: " .. output_path, vim.log.levels.INFO) end
end

return M
