local M = {}

local punkpalette = require("prismpunk.palette")
local punkconf = require("prismpunk.config")

M.export_conf = function(theme)
  local c = theme.colors or theme
  local name = theme.name or "PrismPunk Theme"

  local lines = {
    "# " .. name,
    "# Generated by prismpunk.nvim",
    "# " .. os.date("%Y-%m-%d %H:%M:%S"),
    "",
    "background " .. c.base00,
    "foreground " .. c.base05,
    "",
    "color0  " .. c.base00,
    "color1  " .. c.base08,
    "color2  " .. c.base0B,
    "color3  " .. c.base0A,
    "color4  " .. c.base0D,
    "color5  " .. c.base0E,
    "color6  " .. c.base0C,
    "color7  " .. c.base05,
    "color8  " .. c.base03,
    "color9  " .. c.base08,
    "color10 " .. c.base0B,
    "color11 " .. c.base0A,
    "color12 " .. c.base0D,
    "color13 " .. c.base0E,
    "color14 " .. c.base0C,
    "color15 " .. c.base07,
    "",
    "selection_foreground " .. c.base00,
    "selection_background " .. c.base05,
    "",
    "cursor " .. c.base05,
    "cursor_text_color " .. c.base00,
  }
  return table.concat(lines, "\n")
end

M.write_config = function(theme, path)
  local content = M.export_conf(theme)
  path = vim.fn.expand(path)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  local file = io.open(path, "w")
  if not file then
    vim.notify("Prismpunk: Failed to write " .. path, vim.log.levels.ERROR)
    return false
  end
  file:write(content)
  file:close()
  return true
end

M.reload = function(path)
  path = vim.fn.expand(path or "~/.config/kitty/prismpunk.conf")

  -- method I: kitty @ set-colors (if running inside Kitty)
  local result = vim.fn.system("kitty @ set-colors --all --configured " .. vim.fn.shellescape(path) .. " 2>&1") -- luacheck: ignore
  if vim.v.shell_error == 0 then return true end

  -- method II: KITTY_LISTEN_ON socket
  local listen_on = vim.env.KITTY_LISTEN_ON
  if listen_on and listen_on ~= "" then
    result = vim.fn.system(
      "kitty @ --to "
        .. vim.fn.shellescape(listen_on)
        .. " set-colors --all --configured "
        .. vim.fn.shellescape(path)
        .. " 2>&1"
    )
    if vim.v.shell_error == 0 then return true end
  end

  -- method III: find kitty socket automatically
  local socket_search = vim.fn.system("find /tmp -name 'kitty-*' -type s 2>/dev/null | head -1")
  if socket_search and socket_search ~= "" then
    local socket = vim.trim(socket_search)
    result = vim.fn.system(
      "kitty @ --to unix:"
        .. vim.fn.shellescape(socket)
        .. " set-colors --all --configured "
        .. vim.fn.shellescape(path)
        .. " 2>&1"
    )
    if vim.v.shell_error == 0 then return true end
  end

  -- method IV: Send SIGUSR1 signal (requires allow_remote_control yes in kitty.conf)
  result = vim.fn.system("pkill -USR1 kitty 2>&1")
  if vim.v.shell_error == 0 then return true end

  return false
end

M.export_and_reload = function(theme, conf)
  if not conf.config_path then
    vim.notify("Prismpunk: Kitty config_path not set", vim.log.levels.WARN)
    return
  end

  local success = M.write_config(theme, conf.config_path)
  if success then
    -- vim.notify("Prismpunk: Kitty theme exported to " .. conf.config_path, vim.log.levels.INFO)
    if conf.auto_reload then
      if not M.reload(conf.config_path) then
        vim.notify(
          "Prismpunk: Failed to reload Kitty automatically. You may need to:\n"
            .. "1. Enable 'allow_remote_control yes' in kitty.conf\n"
            .. "2. Set 'listen_on unix:/tmp/kitty' in kitty.conf\n"
            .. "3. Or restart Kitty manually",
          vim.log.levels.WARN
        )
        -- else
        -- vim.notify("Prismpunk: Kitty theme reloaded successfully!", vim.log.levels.INFO)
      end
    end
  end
end

M.export = function(theme_name)
  local parsed = punkconf.parse_theme(theme_name)
  local theme_path
  if parsed.universe then
    theme_path = "prismpunk.themes." .. parsed.universe:gsub("%-", "%.") .. "." .. parsed.name
  else
    theme_path = "prismpunk.themes." .. parsed.name
  end
  local ok, spec = pcall(require, theme_path)
  if not ok then
    vim.notify("Failed to load theme: " .. theme_name, vim.log.levels.ERROR)
    return nil
  end
  return M.export_conf(punkpalette.create_theme(spec))
end

M.save = function(theme_name, output_path)
  output_path = output_path or vim.fn.expand("~/.config/kitty/prismpunk.conf")
  local parsed = punkconf.parse_theme(theme_name)
  local theme_path
  if parsed.universe then
    theme_path = "prismpunk.themes." .. parsed.universe:gsub("%-", "%.") .. "." .. parsed.name
  else
    theme_path = "prismpunk.themes." .. parsed.name
  end
  local ok, spec = pcall(require, theme_path)
  if not ok then
    vim.notify("Failed to load theme: " .. theme_name, vim.log.levels.ERROR)
    return
  end
  local success = M.write_config(punkpalette.create_theme(spec), output_path)
  if success then vim.notify("Exported to: " .. output_path, vim.log.levels.INFO) end
end

return M
